### PR TITLE
fix: Ensure orphaned browser instance is killed before connecting to a new one

### LINKED ISSUE #24377: Weird flicker in video for end to end test on updating to v10.10.0
### Current behavior

We were previously using cypress version `9.7.0` and now want to update to version `10.10.0`. However, we sometimes get an issue with the end-to-end tests when running on GitLab CI.

As you can see from the video, a weird flicker happens during the test and it eventually fails. Does it seem that the test is jumping up and down the commands as it was running two instances of the test? The video is only showing the start of the test and is pixelated since this is a private project. 

https://user-images.githubusercontent.com/43796105/197748959-0059a24d-fa4a-4f33-95e0-5579ec479ccd.mp4

We haven't been able to reproduce this behavior locally, and it doesn't constantly happen on the CI. It is also not specific to this test, sometimes the other end-to-end tests fail occasionally and the videos have the same weird flicker. These tests didn't have this issue before upgrading cypress version.

### Desired behavior

We would like to be able to update cypress to version 10, but this issue is delaying the update since we cannot rely on the end-to-end tests for our CI.

### Test code to reproduce

We can't provide the full test code since this is a private project.

* `cypress.config.ts`
```typescript
import { defineConfig } from "cypress";

export default defineConfig({
    chromeWebSecurity: false,
    defaultCommandTimeout: 15000,
    viewportWidth: 1920,
    viewportHeight: 1080,
    videoUploadOnPasses: false,

    projectId: "xxxxxx",

    e2e: {
        setupNodeEvents(on, _config) {},

        retries: {
            runMode: 0,
        },

        specPattern: "cypress/e2e/**/*.{ts,tsx}",
    },
});
```

* `cypress-dockerfile`
```dockerfile
FROM cypress/included:10.10.0

RUN npm install -g pnpm@6.2.1

# other packages installed necessary to run our e2e tests
```

* `gitlab-ci.yml`
```yml
itest:end-to-end:
    image: ${ITEST_IMAGE}
    stage: itest
    script:
      # backend necessary scripts
  
      - cd frontend
      - echo -e "\e[0Ksection_start:`date +%s`:frontend-deps[collapsed=true]\r\e[0KInstalling frontend deps"
      - CYPRESS_INSTALL_BINARY=0 pnpm install --no-verify-store-integrity --frozen-lockfile -r
      - echo -e "\e[0Ksection_end:`date +%s`:frontend-deps\r\e[0K"
      - cypress run
        --config baseUrl="http://localhost:8001/",defaultCommandTimeout=60000,watchForFileChanges=false,pageLoadTimeout=100000,numTestsKeptInMemory=0
        --browser chrome
        --reporter mocha-junit-reporter
        --reporter-options 'mochaFile=cypress/reports/junit/junit-[hash].xml'
        --env KC_HOSTNAME="localhost:8080"
        --spec clusters-active.ts
    artifacts:
      when: on_failure
      paths:
        - frontend/cypress/screenshots
        - frontend/cypress/videos
        - logs
      expire_in: 15 days
      reports:
        junit: frontend/cypress/reports/junit/*.xml
```

* gitlab output
```
$ cypress run --config baseUrl="http://localhost:8001/",defaultCommandTimeout=60000,watchForFileChanges=false,pageLoadTimeout=100000,numTestsKeptInMemory=0 --browser chrome --reporter mocha-junit-reporter --reporter-options 'mochaFile=cypress/reports/junit/junit-[hash].xml' --env KC_HOSTNAME="localhost:8080" --spec clusters-active.ts
[10659:1017/234749.919499:ERROR:node_bindings.cc(279)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[10659:1017/234750.894445:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 10889: Permission denied (13)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[10889:1017/234750.909020:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.10.0                                                                        │
  │ Browser:        Chrome 100 (headless)                                                          │
  │ Node Version:   v16.14.2 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (clusters-active.ts)                                                   │
  │ Searched:       cypress/e2e/customer/clusters-active.ts                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  clusters-active.ts                                                              (1 of 1)
Timed out waiting for the browser to connect. Retrying...
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      8                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 40 seconds                                                             │
  │ Spec Ran:     clusters-active.ts                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  /builds/.../frontend/cypress/screenshots/clusters-act     (1280x720)
     ive.ts/test -- before all hook (failed).png                        
  -  /builds/.../frontend/cypress/screenshots/clusters-act     (1280x720)
     ive.ts/test -- after all hook (failed).png                         
  (Video)
  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /builds/.../frontend/cypress/vid    (6 seconds)
                          eos/clusters-active.ts.mp4                                                
====================================================================================================
  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  clusters-active.ts                       01:40        9        -        1        -        8 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     01:40        9        -        1        -        8  
```

### Cypress Version

10.10.0

### Node version

v16.14.2

### Operating System

cypress/included:10.10.0

### Debug Logs

_No response_

### Other

Which debug logs would be more relevant for this? `DEBUG=cypress:*` has too many logs, so the GitLab job exceeds the maximum logs saved before the test finishes.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #24377

### Additional details

See the code comment in  `browsers/index.ts`.

### Steps to test

I was never able to reproduce the issue for this, so unfortunately it's not really possible to test it out manually.

### PR Tasks

- [x] Have tests been added/updated?
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/index.ts [hunk 1]
```diff
@@ -155,6 +155,26 @@ export = {
 
     debug('browser opened')
 
+    // in most cases, we'll kill any running browser instance before launching
+    // a new one when we call `kill(true)` on the first line of this function.
+    // however, the code that calls this sets a timeout and, if that timeout
+    // hits, it catches the timeout error and retries launcing the browser by
```
Comment (mschile) [inline packages/server/lib/browsers/index.ts]:
```suggestion
    // hits, it catches the timeout error and retries launching the browser by
```

File: packages/server/test/unit/browsers/browsers_spec.js [hunk 2]
```diff
@@ -156,6 +158,54 @@ describe('lib/browsers/index', () => {
         expect(err).to.have.property('message').to.contain(`Browser: ${chalk.yellow('foo-bad-bang')} was not found on your system`)
       })
     })
+
+    // https://github.com/cypress-io/cypress/issues/24377
+    it('kills browser if one connects while launching another instance', async () => {
```
Comment (mjhenkes) [inline packages/server/test/unit/browsers/browsers_spec.js]: impressive that you were able to reproduce this in a test!

**Review by mjhenkes — APPROVED** [review]

File: packages/server/lib/browsers/index.ts [hunk 3]
```diff
@@ -155,6 +155,26 @@ export = {
...
+    // on the 2nd attempt (during `browserLaunch.open()` directly above), the
+    // 1st instance gets created but then orphaned when we override the
+    // `instance` singleton after the 2nd attempt succeeds. this causes wonky
+    // things to occur because we're connected to and receiving messages from
+    // 2 browser instances. attempting to kill again ensures we kill the 1st
+    // browser and only connect to the 2nd one. if we didn't run into the race
+    // condition where there's an orphaned browser instance, this call ends up
+    // a harmless no-op.
+    // https://github.com/cypress-io/cypress/issues/24377
+    await kill(true)
```
Comment (mschile) [inline packages/server/lib/browsers/index.ts]: What happens if the second browser fully connects and starts running the spec and then the first browser connects?

Comment (chrisbreiding) [reply packages/server/lib/browsers/index.ts]: That's a good question. It would probably override the browser instance singleton after it resolves and we'd still have the double browser issue. This has me thinking the solution may need to be more robust than this in order to handle an orphaned browser launching at any given time...

**Review by mjhenkes — APPROVED** [review]

File: packages/server/lib/browsers/index.ts [hunk 4]
```diff
@@ -155,6 +180,34 @@ export = {
...
+    // from 2 browser instances.
+    //
+    // to counteract this potential race condition, we use the `instanceId`
+    // global to essentially track which browser launch attempt is the latest
+    // one. the latest one should always be the correct one we want to connect
+    // to, so if the `instanceId` global has changed in the course of launching
+    // this browser, it means it has been orphaned and should be terminated.
+    //
+    // https://github.com/cypress-io/cypress/issues/24377
+    if (thisInstanceId !== instanceId) {
```
Comment (mschile) [inline packages/server/lib/browsers/index.ts]: Are we able to use the presence of `instance` as the signal instead of using `instanceId`? This way, the first browser to connect wins and then any subsequent browser instances would just be killed.

File: packages/server/lib/browsers/index.ts [hunk 5]
```diff
@@ -15,23 +15,39 @@ const debug = Debug('cypress:server:browsers')
 const isBrowserFamily = check.oneOf(BROWSER_FAMILY)
 
 let instance: BrowserInstance | null = null
+let instanceId = 0
```
Comment (mschile) [inline packages/server/lib/browsers/index.ts]:
```suggestion
let openAttempt = 0
```

File: packages/server/lib/browsers/index.ts (hunk 4 above)
Comment (chrisbreiding) [reply packages/server/lib/browsers/index.ts]: We need the latest attempt (in the case of 2 attempts, browser 2) to be the one we use since the connection to any earlier launch (browser 1) is lost in the calling code via the timeout error. If we use `instance` as the signal and browser 1 connects  _while_ browser 2 is launching, `instance` will get set by browser 1 while browser 2 is still launching and browser 2 will terminate itself once it launches because `instance` will refer to browser 1.

Using the incrementing number for each call to `open` is the simplest way I could think of to ensure the latest attempt wins out.

**Review by mschile — APPROVED** [review]

File: packages/server/lib/browsers/index.ts (hunk 5 above)
Comment (chrisbreiding) [reply packages/server/lib/browsers/index.ts]: Addressed in https://github.com/cypress-io/cypress/pull/25898/commits/b6ec574ce3f595ef8daefbe21a1946770ea6046f
