### PR TITLE
Extend cy.its and cy.invoke to accept a number as 1st arg

### LINKED ISSUE #5754: `cy.its()` should support `number` as an argument
### Current behavior:

```
CypressError: cy.its() only accepts a string as the first argument.
```

### Desired behavior:

```
CypressError: cy.its() only accepts a string or a number as the first argument.
```

### Steps to reproduce: (app code and test code)

```js
cy.wrap([]).its(0)
```

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5754 

### User facing changelog

- `cy.its()` and `cy.invoke()` now support a number for the first argument.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2264
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

### CODE REVIEW

**Comment by flotwig** [comment]
@bahmutov Can you help me figure out why the dtslint tests are failing? The error makes absolutely no sense to me... nor do the types :sweat_smile:

File: cli/types/tests/cypress-tests.ts [hunk 1]
```diff
@@ -98,6 +98,10 @@ cy.wrap({ foo: [1, 2, 3] })
     s
   })
 
+cy.wrap(['foo', 'bar']).its(1)
```
Comment (bahmutov) [inline cli/types/tests/cypress-tests.ts]: // can you add expected type or value assertion here?

File: cli/types/tests/cypress-tests.ts [hunk 2]
```diff
@@ -98,6 +98,10 @@ cy.wrap({ foo: [1, 2, 3] })
...
+
+cy.wrap([()=>{}, ()=>{}]).invoke(1)
```
Comment (bahmutov) [inline cli/types/tests/cypress-tests.ts]: ughh, in this case it should invoke first function in the array?

**Comment by bahmutov** [comment]
I have to look at the failure tomorrow, but I would love just `its(index)` for arrays, and skip trying to make `invoke` work - what's a normal real-world use case for `invoke(1)`?

**Comment by flotwig** [comment]
it's and invoke are the same code path, so invoke(n) comes for free

**Comment by bahmutov** [comment]
Yeah but i still don’t see a good example for it

**Comment by flotwig** [comment]
> Yeah but i still don’t see a good example for it

Me either, but i still want to keep invoke(n)...

1. it matches the contract for indexing into an object, which is 50% of what invoke does - this reduces cognitive overload
2. we don't have to go back and add invoke(n) at a later date when someone does end up wanting it
3. it matches it() so users don't have to remember 2 different signatures

File: cli/types/tests/cypress-tests.ts (hunk 2 above)
Comment (flotwig) [reply cli/types/tests/cypress-tests.ts]: yep. i tried to strongly type this using `ReturnType`, but couldn't get anything to really work, so left it as is

File: cli/types/tests/cypress-tests.ts (hunk 1 above)
Comment (flotwig) [reply cli/types/tests/cypress-tests.ts]: done

**Comment by bahmutov** [comment]
@dmtrKovalenko and @tgriesser - if you can give this `cy.its` and `cy.invoke` a quick look - seems this is the best I could do to specify type of the yielded value when using a numerical index for arrays. 

Second question: any advice on what the minimum version of TypeScript we should use? Right now this PR updates it from 2.8 to 2.9 - but most of the libs I see right now around are already on 3.x no? We could start shipping 3.x and 2.x and then deprecate 2.x types.

File: cli/types/index.d.ts [hunk 3]
```diff
@@ -866,6 +866,12 @@ declare namespace Cypress {
      */
     hash(options?: Partial<Loggable & Timeoutable>): Chainable<string>
 
+    /**
+     * Invoke a function in an array of functions.
+     * @see https://on.cypress.io/invoke
+     */
+    invoke<T extends (...args: any[]) => any, Subject extends T[]>(index: number): Chainable<ReturnType<T>>
+
```
Comment (bahmutov) [inline cli/types/index.d.ts]: wish here I could write `<ReturnType<Subject[index]>>` to point at specific function

**Comment by flotwig** [comment]
I don't think it's a good idea to purposely restrict `invoke`. 

As a developer, I expect `invoke` to have the same function signature as an `its` call, because my mental model tells me that they do the exact same thing, except `invoke` has the additional step of calling the property at the end. I see absolutely no reason to make the behavior of `invoke` diverge from `its`. 

Just because we don't have a use case doesn't mean we should take the extra time to develop a method to block users from taking advantage of that unknown use case.

**Comment by jennifer-shehane** [comment]
@flotwig So the above example I provided is correct? I'm fine as long as I have a correct example to add to the docs.

**Comment by bahmutov** [comment]
For some reason I am seeing a use case with React hooks returned from user’s app somehow - it is an array so you want to invoke a function using an index

**Comment by flotwig** [comment]
> @flotwig So the above example I provided is correct? I'm fine as long as I have a correct example to add to the docs.

Yeah, it looks right to me.

**Comment by brian-mann** [comment]
> I agree with @bahmutov on this one. All of the arguments for accepting a Number for `.invoke` are 'its easier', not the actual functionality of even needing this thing.
> 
> Trying to write the docs is a bit weird, let me understand (because we add an example of each use of an argument for our docs). The below would be a correct example?
> 
> ```js
> const square = function(n) { return n * n }
> const halve = function(n) { return n / 2 }
> 
> cy.wrap([square, halve]).invoke(1, 8).should('eq', 4)
> ```
> 
> WIP docs PR I started: [cypress-io/cypress-documentation#2264](https://github.com/cypress-io/cypress-documentation/pull/2264)

This is a.... unbelievably confusing example - please do not use it. I don't even think it's correct.
