### PR TITLE
fix: update firefox to close extra windows between specs

### LINKED ISSUE #29473: Flaky internal service-worker test on Firefox browser
### What would you like?

CircleCI failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/61470/workflows/2786f457-f32c-45f3-8653-4623e006a71e/jobs/2554165

Screenshot 2024-05-03 at 11 18 10 AM (1)

Able to reliably reproduce locally running these tests in this order. Note, any spec can be in the middle spec to recreate.
```
yarn cypress:run --browser firefox --spec cypress/e2e/e2e/abort_beforeunload_event_child.cy.ts cypress/e2e/e2e/origin/commands/spies_stubs_clocks.cy.ts cypress/e2e/e2e/service-worker.cy.js --runner-ui
```

There is a test opening a new window in Firefox. But in the other browsers, this just opens 1 tab. 
```js
cy.window().invoke('open', '/fixtures/blocking_beforeunload_event.html')
```

This only happens if we don't pass the 3rd option to [`window.open`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open).

Fails:
```js
window.open('/fixtures/blocking_beforeunload_event.html', 'test')
```
Works:
```js
window.open('/fixtures/blocking_beforeunload_event.html', 'test', 'popup')
```

### Why is this needed?

We should be closing all windows in between specs. This may be affecting users of Cypress in odd ways.

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #29473

### Additional details

In `firefox`, if [window.open](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) is used to open a new window, we do not close the extra window between specs which can lead to issues in subsequent specs such as performance issues in service workers.

```
window.open('/fixtures/blocking_beforeunload_event.html')
```

* Updated `background.js` to close the extra windows between specs
* Renamed  `resetBrowserTabsForNextTest` to `resetBrowserTabsForNextSpec`

### Steps to test

Run a test that opens a new window in `firefox` and verify it gets closed between specs.

### How has the user experience changed?

Before:
Screenshot 2024-05-06 at 11 42 36 AM

After:
Screenshot 2024-05-06 at 11 40 24 AM

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/extension/app/v2/background.js [hunk 1]
```diff
@@ -136,8 +136,8 @@ const connect = function (host, path, extraOpts) {
         return invoke('takeScreenshot', id)
       case 'reset:browser:state':
         return invoke('resetBrowserState', id)
-      case 'reset:browser:tabs:for:next:test':
-        return invoke('resetBrowserTabsForNextTest', id)
+      case 'reset:browser:tabs:for:next:spec':
```
Comment (ryanthemanuel) [inline packages/extension/app/v2/background.js:139]: Thanks for fixing my bad naming.

**Review by ryanthemanuel — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]
