### PR TITLE
fix: issue with service worker attachments

### LINKED ISSUE #28141: Test Runner Crashing since Cypress version 13.3.2 when encountering "Inspected target navigated or closed"
### Current behavior

When navigating to a URL that presents it with "Inspected target navigated or closed", the entire Test Runner crashes.

### Desired behavior

Fail the test but not fail the test runner.
This happens in  `cypress open`. In some cases it has been seen in the headless runner, but perhaps not with the replication steps below.

### Test code to reproduce
```js
describe('Test Crashes starting in Cypress version 13.3.2', () => {
  it('Test Runner Crashes', () => {
    cy.visit('https://mydc-staging2.mydirectives.com/sso/service-worker.js');
  })
})
```

### Cypress Version

13.3.3

### Node version

v16.16.0

### Operating System

Windows 11 Pro -Version 10.0.22621 Build 22621

### Debug Logs

```shell
cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +290ms
Inspected target navigated or closed
Error: Inspected target navigated or closed
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
  cypress:server:browsers:browser-cri-client Target.targetDestroyed { event: { targetId: 'A9047117C6C94B9FCD8ADAAF5B4D5F07' }, closing: false, closed: false, resettingBrowserTargets: false } +2m
  cypress:server:cloud:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"Error","message":"Inspected target navigated or closed","stack":"Error: Inspected target navigated or closed\n    at <embedded>:2466:519827\n    at _._handleMessage (<embedded>:2466:521860)\n    at A.<anonymous> (<embedded>:2466:521673)\n    at A.emit (node:events:513:28)\n    at g.U (<embedded>:2466:506953)\n    at g.emit (node:events:513:28)\n    at g.dataMessage (<embedded>:2466:487328)\n    at <embedded>:2466:486860\n    at <embedded>:2466:478182\n    at <embedded>:2466:479134\n    at afterWrite (node:internal<stripped-path>writable:500:5)\n    at onwrite (node:internal<stripped-path>writable:480:7)\n    at Zlib.<anonymous> (node:internal<stripped-path>transform:190:7)\n    at Zlib.processCallback (node:zlib:613:8)"},"version":"13.3.3","osName":"win32","osVersion":"10.0.22621","osCpus":[{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3819218,"nice":0,"sys":3683187,"idle":230978234,"irq":465281}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":2264953,"nice":0,"sys":1155750,"idle":235059687,"irq":29890}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":6428734,"nice":0,"sys":4985656,"idle":227065968,"irq":117281}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":4128031,"nice":0,"sys":1897718,"idle":232454625,"irq":29000}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":5333765,"nice":0,"sys":3440531,"idle":229706109,"irq":91875}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3480671,"nice":0,"sys":1953515,"idle":233046171,"irq":44500}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":6683687,"nice":0,"sys":4067828,"idle":227728843,"irq":95671}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":4823500,"nice":0,"sys":2141218,"idle":231515609,"irq":38093}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3838921,"nice":0,"sys":2479812,"idle":232161593,"irq":55875}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3103187,"nice":0,"sys":1610218,"idle":233766953,"irq":55546}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":5320218,"nice":0,"sys":3082937,"idle":230077234,"irq":70359}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3750718,"nice":0,"sys":1677640,"idle":233052015,"irq":28640}}],"osMemory":{"free":3751272448,"total":17095184384}},"headers":{"x-os-name":"win32","x-cypress-version":"13.3.3"}} and token: undefined +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' } +177ms
  cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 } +302ms
  cypress:server:browsers:electron closed event fired +2m
  cypress:server:windows error removing all extensions { err: TypeError: Object has been destroyed at Object.f (<embedded>:4454:93274) at BrowserWindow.<anonymous> (<embedded>:4454:106754)     at Object.onceWrapper (node:events:628:26)     at BrowserWindow.emit (node:events:525:35) at <embedded>:4460:18960 at tryCatcher (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:512:31) at Promise._settlePromise (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:569:18) at Promise._settlePromise0 (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:614:10) at Promise._settlePromises (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\promise.js:694:18) at _drainQueueStep (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\async.js:138:12) at _drainQueue (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\async.js:131:9) at Async._drainQueues (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\async.js:147:5) at Immediate._onImmediate (C:\Users\<user>\AppData\Local\Cypress\Cache\13.3.3\Cypress\resources\app\node_modules\bluebird\js\release\async.js:17:14)


GET /widgetBase/bootstrap.js 200 38.269 ms - -
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +8ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +1ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://mydc-staging2.mydirectives.com', strategy: 'http', fileServer: null, domainName: 'mydirectives.com', props: { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } } for: https://mydc-staging2.mydirectives.com/sso/service-worker.js +9ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'mydirectives', tld: 'com' } +0ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://mydc-staging2.mydirectives.com', strategy: 'http', fileServer: null, domainName: 'mydirectives.com', props: { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } } for: https://mydirectives.com +0ms
  cypress:server:stream_buffer stream buffer writeable final called +45ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://mydc-staging2.mydirectives.com/sso/service-worker.js' } +46ms
  cypress:network:agent got family { family: 4, href: 'https://mydc-staging2.mydirectives.com/sso/service-worker.js' } +0ms
  cypress:server:request received status code & headers on request { requestId: 'request41', statusCode: 200, headers: { 'content-type': 'text/html', 'set-cookie': [ 'AWSALB=FofI3ZS6xRJ5/9hdLqjzBvpUxb1K+wUCEZfBXW38T3Vg2TWqurYRDAsSe7ozlIiSJw1781fjAYgJXrUbHHn2KexqD/h2VhlxLGI6DQXLsHp+dKQorewxUoc7mTfW; Expires=Wed, 01 Nov 2023 16:13:13 GMT; Path=/', 'AWSALBCORS=FofI3ZS6xRJ5/9hdLqjzBvpUxb1K+wUCEZfBXW38T3Vg2TWqurYRDAsSe7ozlIiSJw1781fjAYgJXrUbHHn2KexqD/h2VhlxLGI6DQXLsHp+dKQorewxUoc7mTfW; Expires=Wed, 01 Nov 2023 16:13:13 GMT; Path=/; SameSite=None; Secure' ] } } +87ms
  cypress:server:request successful response received { requestId: 'request41' } +0ms
  cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/sso/service-worker.js' }, request: undefined } +86ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'mydirectives', tld: 'com' } +76ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://mydc-staging2.mydirectives.com', strategy: 'http', fileServer: null, domainName: 'mydirectives.com', props: { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } } for: https://mydirectives.com +76ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +1ms
  cypress:server:remote-states getting primary remote state: { auth: null, origin: 'https://mydc-staging2.mydirectives.com', strategy: 'http', fileServer: null, domainName: 'mydirectives.com', props: { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } } +1ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } +0ms
  cypress:network:cors Parsed URL { port: '443', protocol: 'https:', subdomain: null, domain: 'mydirectives', tld: 'com' } +0ms
  cypress:server:remote-states getting remote state: { auth: null, origin: 'https://mydc-staging2.mydirectives.com', strategy: 'http', fileServer: null, domainName: 'mydirectives.com', props: { port: '443', protocol: 'https:', subdomain: 'mydc-staging2', domain: 'mydirectives', tld: 'com' } } for: https://mydirectives.com +0ms
GET /sso/service-worker.js 200 78.695 ms - -
Inspected target navigated or closed
Error: Inspected target navigated or closed
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
  cypress:server:lib:util:suppress_warnings suppressed emitWarning from node: { process: process { version: 'v18.15.0', versions: { node: '18.15.0', v8: '11.4.183.29-electron.0', uv: '1.44.2', zlib: '1.2.13',brotli: '1.0.9', ares: '1.18.1', modules: '116', nghttp2: '1.51.0', napi: '8', llhttp: '6.0.10', uvwasi: '0.0.15', acorn: '8.8.2', simdutf: '3.1.0', undici: '5.20.0', openssl: '1.1.1', cldr: '42.0', icu: '72.1', tz: '2023a', unicode: '15.0', electron: '25.8.4', chrome: '114.0.5735.289' }, arch: 'x64', platform: 'win32', release: { name: 'node', lts: 'Hydrogen', sourceUrl: 'https://nodejs.org/download/release/v18.15.0/node-v18.15.0.tar.gz', headersUrl: 'https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz', libUrl: 'https://nodejs.org/download/release/v18.15.0/win-x64/node.lib' }, _rawDebug: [Function: _rawDebug], moduleLoadList: [ 'Internal Binding builtins', 'Internal Binding errors', 'Internal Binding util', 'NativeModule internal/errors', 'Internal Binding config', 'Internal Binding timers', 'Internal Binding async_wrap', 'Internal Binding constants', 'Internal Binding types', 'NativeModule internal/util', 'NativeModule internal/util/types', 'NativeModule internal/validators', 'NativeModule internal/promise_hooks', 'Internal Binding task_queue', 'Internal Binding symbols', 'NativeModule internal/async_hooks', 'NativeModule internal/linkedlist', 'NativeModule internal/priority_queue', 'NativeModule internal/assert', 'Internal Binding icu', 'NativeModule internal/util/inspect', 'NativeModule internal/util/debuglog', 'NativeModule internal/timers', 'NativeModule events', 'Internal Binding buffer', 'Internal Binding string_decoder', 'NativeModule internal/buffer', 'Internal Binding blob', 'NativeModule internal/encoding', 'Internal Binding messaging', 'NativeModule internal/worker/js_transferable', 'NativeModule internal/constants', 'NativeModule internal/blob', 'NativeModule internal/file', 'NativeModule buffer', 'NativeModule internal/modules/esm/handle_process_exit', 'Internal Binding process_methods', 'NativeModule internal/process/per_thread', 'Internal Binding credentials', 'NativeModule internal/process/promises', 'NativeModule internal/fixed_queue', 'NativeModule async_hooks', 'NativeModule internal/process/task_queues', 'NativeModule timers', 'Internal Binding worker', 'NativeModule internal/util/parse_args/utils', 'NativeModule internal/util/parse_args/parse_args', 'NativeModule internal/mime', 'NativeModule util', 'Internal Binding performance', 'NativeModule internal/perf/utils', 'NativeModule internal/event_target', 'NativeModule internal/abort_controller', 'NativeModule internal/streams/utils', 'NativeModule internal/streams/end-of-stream', 'NativeModule internal/streams/destroy', 'NativeModule internal/streams/legacy', 'NativeModule internal/streams/add-abort-signal', 'NativeModule internal/streams/buffer_list', 'NativeModule internal/streams/state', 'NativeModule string_decoder', 'NativeModule internal/streams/from', 'NativeModule internal/streams/readable', 'NativeModule internal/streams/writable', 'NativeModule internal/streams/duplex', 'NativeModule internal/streams/pipeline', 'NativeModule internal/streams/compose', 'NativeModule internal/streams/operators', 'NativeModule stream/promises', 'NativeModule internal/streams/transform', 'NativeModule internal/streams/passthrough', 'NativeModule stream', 'NativeModule internal/worker/io', 'NativeModule internal/structured_clone', 'Internal Binding trace_events', 'NativeModule path', 'NativeModule internal/process/execution', 'NativeModule internal/process/warning', 'Internal Binding fs', 'NativeModule internal/querystring', 'NativeModule querystring', 'Internal Binding url', 'NativeModule internal/url', 'NativeModule internal/fs/utils', 'Internal Binding fs_dir', 'NativeModule internal/fs/dir', 'Internal Binding fs_event_wrap', 'Internal Binding uv', 'NativeModule internal/fs/watchers', 'NativeModule internal/fs/read_file_context', 'NativeModule fs', 'Internal Binding serdes', 'Internal Binding mksnapshot', 'NativeModule internal/v8/startup_snapshot', 'Internal Binding profiler', 'Internal Binding heap_utils', 'Internal Binding stream_wrap', 'NativeModule internal/stream_base_commons', 'NativeModule internal/heap_utils', 'Internal Binding options', ... 155 more items ], binding: [Function: binding], _linkedBinding: [Function: _linkedBinding], _events: [Object: null prototype] { newListener: [Function: startListeningIfSignal], removeListener: [Function: stopListeningIfSignal], warning: [Function: onWarning], uncaughtException: [Function], exit: [Array], SIGABRT: [Array], SIGALRM: [Array], SIGHUP: [Array], SIGINT: [Array], SIGTERM: [Array] }, _eventsCount: 10, _maxListeners: undefined, domain: null, _exiting: [Getter/Setter], config: [Getter/Setter], dlopen: [Function: func], uptime: [Function: uptime], _getActiveRequests: [Function: _getActiveRequests], _getActiveHandles: [Function: _getActiveHandles], getActiveResourcesInfo: [Function: getActiveResourcesInfo], reallyExit: [Function: g], _kill: [Function: _kill], cpuUsage: [Function: cpuUsage], resourceUsage: [Function: resourceUsage], memoryUsage: [Function: memoryUsage] { rss: [Function:rss] }, constrainedMemory: [Function: constrainedMemory], kill: [Function: kill], exit: [Function: exit], hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] }, openStdin: [Function (anonymous)], allowedNodeEnvironmentFlags: [Getter/Setter], assert: [Function: deprecated], features: { inspector: true, debug: false, uv: true, ipv6: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true, cached_builtins: [Getter] }, _fatalException: [Function (anonymous)], setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback], hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback], emitWarning: [Function (anonymous)], nextTick: [Function (anonymous)], _tickCallback: [Function: runNextTicks], _debugProcess: [Function: _debugProcess], _debugEnd: [Function: _debugEnd], _startProfilerIdleNotifier: [Function (anonymous)], _stopProfilerIdleNotifier: [Function (anonymous)], stdout: [Getter], stdin: [Getter], stderr: [Getter], abort: [Function: abort], umask: [Function: wrappedUmask], chdir: [Function (anonymous)], cwd: [Function (anonymous)], env: { ALLUSERSPROFILE: 'C:\\ProgramData', API_TEST_ENVIRONMENT: 'development', APPDATA: 'C:\\Users\\<user>\\AppData\\Roaming', ASPNETCORE_ENVIRONMENT: 'Development', COLOR: '1', CommonProgramFiles: 'C:\\Program Files\\Common Files', 'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files', CommonProgramW6432: 'C:\\Program Files\\Common Files', COMPUTERNAME: 'PS-MKRAINES-LEG', ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe', CYPRESS: 'true', CYPRESS_INTERNAL_ENV: 'production', DEBUG: 'cypress:*', DEBUG_COLORS: '1', DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData', EDITOR: 'C:\\WINDOWS\\notepad.exe', FORCE_COLOR: '1', FORCE_STDERR_TTY: '1', FORCE_STDIN_TTY: '1', FORCE_STDOUT_TTY: '1', HOME: 'C:\\Users\\<user>', HOMEDRIVE: 'C:', HOMEPATH:'\\Users\\<user>', INIT_CWD: 'C:\\dev\\CypressTest', 'JetBrains Rider': 'C:\\Program Files\\JetBrains\\JetBrains Rider 2022.2.2\\bin;', LOCALAPPDATA: 'C:\\Users\\<user>\\AppData\\Local', LOGONSERVER: '\\\\PS-MKRAINES-LEG', MOCHA_COLORS: '1', NODE: 'C:\\Program Files\\nodejs\\node.exe', NODE_TLS_REJECT_UNAUTHORIZED: '0', NO_PROXY: '127.0.0.1,::1,localhost', npm_command: 'exec', npm_config_cache: 'C:\\Users\\<user>\\AppData\\Local\\npm-cache', npm_config_globalconfig: 'C:\\Program Files\\nodejs\\etc\\npmrc', npm_config_global_prefix: 'C:\\Program Files\\nodejs', npm_config_init_module: 'C:\\Users\\<user>\\.npm-init.js', npm_config_local_prefix: 'C:\\dev\\CypressTest', npm_config_metrics_registry: 'https://registry.npmjs.org/', npm_config_node_gyp: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js', npm_config_noproxy: '', npm_config_prefix: 'C:\\Program Files\\nodejs', npm_config_userconfig: 'C:\\Users\\<user>\\.npmrc', npm_config_user_agent: 'npm/9.2.0 node/v16.16.0 win32 x64 workspaces/false', npm_execpath: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\bin\\npx-cli.js', npm_lifecycle_event: 'npx', npm_lifecycle_script: 'cypress', npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe', npm_package_json: 'C:\\dev\\CypressTest\\package.json', npm_package_name: 'cypresstest', npm_package_version: '1.0.0', NUMBER_OF_PROCESSORS: '12', NVM_HOME: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm', NVM_SYMLINK: 'C:\\Program Files\\nodejs', OneDrive: 'C:\\Users\\<user>\\OneDrive - CRISP', OneDriveCommercial: 'C:\\Users\\<user>\\OneDrive - CRISP', ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined', OS: 'Windows_NT', Path: 'C:\\dev\\CypressTest\\node_modules\\.bin;C:\\dev\\CypressTest\\node_modules\\.bin;C:\\dev\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Users\\<user>\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\dotnet-core-uninstall\\;C:\\Users\\<user>\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\<user>\\.dotnet\\tools;C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\<user>\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;;C:\\Program Files\\JetBrains\\JetBrains Rider 2022.2.2\\bin;;;C:\\Users\\<user>\\AppData\\Local\\Programs\\Fiddler', PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', PROCESSOR_ARCHITECTURE: 'AMD64', PROCESSOR_IDENTIFIER:'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel', PROCESSOR_LEVEL: '6', PROCESSOR_REVISION: '9e0a', ProgramData: 'C:\\ProgramData', ProgramFiles: 'C:\\Program Files', 'ProgramFiles(x86)': 'C:\\Program Files (x86)', ProgramW6432: 'C:\\Program Files', PROJECT_BASE_DIR: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app', PROMPT: '$P$G', PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\', PUBLIC: 'C:\\Users\\Public', 'PyCharm Community Edition': 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;', SESSIONNAME: 'Console', SystemDrive: 'C:', SystemRoot: 'C:\\WINDOWS', TEMP: 'C:\\Users\\<user>\\AppData\\Local\\Temp', TMP: 'C:\\Users\\<user>\\AppData\\Local\\Temp', USERDOMAIN: 'AzureAD', USERDOMAIN_ROAMINGPROFILE: 'AzureAD', USERNAME: '<user>', USERPROFILE: 'C:\\Users\\<user>', UV_THREADPOOL_SIZE: '128', windir: 'C:\\WINDOWS', WSLENV: 'WT_SESSION:WT_PROFILE_ID:', WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}', WT_SESSION: '589d2978-d903-4500-832a-b9944990d5cd' }, type: 'browser', resourcesPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources', helperExecPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', crash: [Function (anonymous)], hang: [Function (anonymous)], getCreationTime: [Function (anonymous)], getHeapStatistics: [Function (anonymous)], getBlinkMemoryInfo: [Function (anonymous)], getProcessMemoryInfo: [Function (anonymous)], getSystemMemoryInfo: [Function (anonymous)], getSystemVersion: [Function (anonymous)], getIOCounters: [Function (anonymous)], getCPUUsage: [Function (anonymous)], takeHeapSnapshot: [Function (anonymous)], activateUvLoop: [Function (anonymous)], title: 'node', argv: [ 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', '--', '--project', 'C:\\dev\\CypressTest', '--cwd', 'C:\\dev\\CypressTest', '--userNodePath', 'C:\\Program Files\\nodejs\\node.exe', '--userNodeVersion', '16.16.0' ], execArgv: [], pid: 18120, ppid: 4820, execPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', debugPort: 9229, argv0: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', exitCode: 1, _preload_modules: [], report: [Getter], setSourceMapsEnabled: [Function: setSourceMapsEnabled], _firstFileName: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app\\index.js', mainModule: Module { id: '.', path: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app', exports: {}, filename: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app\\index.js', loaded: true,children: [], paths: [Array] }, noAsar: undefined, enablePromiseAPIs: false, noDeprecation: true, traceDeprecation: true, __signal_exit_emitter__: EventEmitter { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: Infinity, count: 2, emitted: {}, infinite: true, [Symbol(kCapture)]: false }, emit: [Function: f], [Symbol(kCapture)]: false }, warning: 'Error: Inspected target navigated or closed\n' + '   at <embedded>:2466:519827\n' + '    at _._handleMessage (<embedded>:2466:521860)\n' + '    at A.<anonymous> (<embedded>:2466:521673)\n' + '    at A.emit (node:events:513:28)\n' + '    at g.U (<embedded>:2466:506953)\n' + '    at g.emit (node:events:513:28)\n' + '    at g.dataMessage (<embedded>:2466:487328)\n' + '    at <embedded>:2466:486860\n' + '    at <embedded>:2466:478182\n' + '    at <embedded>:2466:479134\n' + '    at afterWrite (node:internal/streams/writable:500:5)\n' + '    at onwrite (node:internal/streams/writable:480:7)\n' + '    at Zlib.<anonymous> (node:internal/streams/transform:190:7)\n' + '    at Zlib.processCallback (node:zlib:613:8)', type: 'UnhandledPromiseRejectionWarning', code: undefined, args: [] } +0ms
  cypress:server:lib:util:suppress_warnings suppressed emitWarning from node: { process: process { version: 'v18.15.0', versions: { node: '18.15.0', v8: '11.4.183.29-electron.0', uv: '1.44.2', zlib: '1.2.13',brotli: '1.0.9', ares: '1.18.1', modules: '116', nghttp2: '1.51.0', napi: '8', llhttp: '6.0.10', uvwasi: '0.0.15', acorn: '8.8.2', simdutf: '3.1.0', undici: '5.20.0', openssl: '1.1.1', cldr: '42.0', icu: '72.1', tz: '2023a', unicode: '15.0', electron: '25.8.4', chrome: '114.0.5735.289' }, arch: 'x64', platform: 'win32', release: { name: 'node', lts: 'Hydrogen', sourceUrl: 'https://nodejs.org/download/release/v18.15.0/node-v18.15.0.tar.gz', headersUrl: 'https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz', libUrl: 'https://nodejs.org/download/release/v18.15.0/win-x64/node.lib' }, _rawDebug: [Function: _rawDebug], moduleLoadList: [ 'Internal Binding builtins', 'Internal Binding errors', 'Internal Binding util', 'NativeModule internal/errors', 'Internal Binding config', 'Internal Binding timers', 'Internal Binding async_wrap', 'Internal Binding constants', 'Internal Binding types', 'NativeModule internal/util', 'NativeModule internal/util/types', 'NativeModule internal/validators', 'NativeModule internal/promise_hooks', 'Internal Binding task_queue', 'Internal Binding symbols', 'NativeModule internal/async_hooks', 'NativeModule internal/linkedlist', 'NativeModule internal/priority_queue', 'NativeModule internal/assert', 'Internal Binding icu', 'NativeModule internal/util/inspect', 'NativeModule internal/util/debuglog', 'NativeModule internal/timers', 'NativeModule events', 'Internal Binding buffer', 'Internal Binding string_decoder', 'NativeModule internal/buffer', 'Internal Binding blob', 'NativeModule internal/encoding', 'Internal Binding messaging', 'NativeModule internal/worker/js_transferable', 'NativeModule internal/constants', 'NativeModule internal/blob', 'NativeModule internal/file', 'NativeModule buffer', 'NativeModule internal/modules/esm/handle_process_exit', 'Internal Binding process_methods', 'NativeModule internal/process/per_thread', 'Internal Binding credentials', 'NativeModule internal/process/promises', 'NativeModule internal/fixed_queue', 'NativeModule async_hooks', 'NativeModule internal/process/task_queues', 'NativeModule timers', 'Internal Binding worker', 'NativeModule internal/util/parse_args/utils', 'NativeModule internal/util/parse_args/parse_args', 'NativeModule internal/mime', 'NativeModule util', 'Internal Binding performance', 'NativeModule internal/perf/utils', 'NativeModule internal/event_target', 'NativeModule internal/abort_controller', 'NativeModule internal/streams/utils', 'NativeModule internal/streams/end-of-stream', 'NativeModule internal/streams/destroy', 'NativeModule internal/streams/legacy', 'NativeModule internal/streams/add-abort-signal', 'NativeModule internal/streams/buffer_list', 'NativeModule internal/streams/state', 'NativeModule string_decoder', 'NativeModule internal/streams/from', 'NativeModule internal/streams/readable', 'NativeModule internal/streams/writable', 'NativeModule internal/streams/duplex', 'NativeModule internal/streams/pipeline', 'NativeModule internal/streams/compose', 'NativeModule internal/streams/operators', 'NativeModule stream/promises', 'NativeModule internal/streams/transform', 'NativeModule internal/streams/passthrough', 'NativeModule stream', 'NativeModule internal/worker/io', 'NativeModule internal/structured_clone', 'Internal Binding trace_events', 'NativeModule path', 'NativeModule internal/process/execution', 'NativeModule internal/process/warning', 'Internal Binding fs', 'NativeModule internal/querystring', 'NativeModule querystring', 'Internal Binding url', 'NativeModule internal/url', 'NativeModule internal/fs/utils', 'Internal Binding fs_dir', 'NativeModule internal/fs/dir', 'Internal Binding fs_event_wrap', 'Internal Binding uv', 'NativeModule internal/fs/watchers', 'NativeModule internal/fs/read_file_context', 'NativeModule fs', 'Internal Binding serdes', 'Internal Binding mksnapshot', 'NativeModule internal/v8/startup_snapshot', 'Internal Binding profiler', 'Internal Binding heap_utils', 'Internal Binding stream_wrap', 'NativeModule internal/stream_base_commons', 'NativeModule internal/heap_utils', 'Internal Binding options', ... 155 more items ], binding: [Function: binding], _linkedBinding: [Function: _linkedBinding], _events: [Object: null prototype] { newListener: [Function: startListeningIfSignal], removeListener: [Function: stopListeningIfSignal], warning: [Function: onWarning], uncaughtException: [Function], exit: [Array], SIGABRT: [Array], SIGALRM: [Array], SIGHUP: [Array], SIGINT: [Array], SIGTERM: [Array] }, _eventsCount: 10, _maxListeners: undefined, domain: null, _exiting: [Getter/Setter], config: [Getter/Setter], dlopen: [Function: func], uptime: [Function: uptime], _getActiveRequests: [Function: _getActiveRequests], _getActiveHandles: [Function: _getActiveHandles], getActiveResourcesInfo: [Function: getActiveResourcesInfo], reallyExit: [Function: g], _kill: [Function: _kill], cpuUsage: [Function: cpuUsage], resourceUsage: [Function: resourceUsage], memoryUsage: [Function: memoryUsage] { rss: [Function:rss] }, constrainedMemory: [Function: constrainedMemory], kill: [Function: kill], exit: [Function: exit], hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] }, openStdin: [Function (anonymous)], allowedNodeEnvironmentFlags: [Getter/Setter], assert: [Function: deprecated], features: { inspector: true, debug: false, uv: true, ipv6: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true, cached_builtins: [Getter] }, _fatalException: [Function (anonymous)], setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback], hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback], emitWarning: [Function (anonymous)], nextTick: [Function (anonymous)], _tickCallback: [Function: runNextTicks], _debugProcess: [Function: _debugProcess], _debugEnd: [Function: _debugEnd], _startProfilerIdleNotifier: [Function (anonymous)], _stopProfilerIdleNotifier: [Function (anonymous)], stdout: [Getter], stdin: [Getter], stderr: [Getter], abort: [Function: abort], umask: [Function: wrappedUmask], chdir: [Function (anonymous)], cwd: [Function (anonymous)], env: { ALLUSERSPROFILE: 'C:\\ProgramData', API_TEST_ENVIRONMENT: 'development', APPDATA: 'C:\\Users\\<user>\\AppData\\Roaming', ASPNETCORE_ENVIRONMENT: 'Development', COLOR: '1', CommonProgramFiles: 'C:\\Program Files\\Common Files', 'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files', CommonProgramW6432: 'C:\\Program Files\\Common Files', COMPUTERNAME: 'PS-MKRAINES-LEG', ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe', CYPRESS: 'true', CYPRESS_INTERNAL_ENV: 'production', DEBUG: 'cypress:*', DEBUG_COLORS: '1', DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData', EDITOR: 'C:\\WINDOWS\\notepad.exe', FORCE_COLOR: '1', FORCE_STDERR_TTY: '1', FORCE_STDIN_TTY: '1', FORCE_STDOUT_TTY: '1', HOME: 'C:\\Users\\<user>', HOMEDRIVE: 'C:', HOMEPATH:'\\Users\\<user>', INIT_CWD: 'C:\\dev\\CypressTest', 'JetBrains Rider': 'C:\\Program Files\\JetBrains\\JetBrains Rider 2022.2.2\\bin;', LOCALAPPDATA: 'C:\\Users\\<user>\\AppData\\Local', LOGONSERVER: '\\\\PS-MKRAINES-LEG', MOCHA_COLORS: '1', NODE: 'C:\\Program Files\\nodejs\\node.exe', NODE_TLS_REJECT_UNAUTHORIZED: '0', NO_PROXY: '127.0.0.1,::1,localhost', npm_command: 'exec', npm_config_cache: 'C:\\Users\\<user>\\AppData\\Local\\npm-cache', npm_config_globalconfig: 'C:\\Program Files\\nodejs\\etc\\npmrc', npm_config_global_prefix: 'C:\\Program Files\\nodejs', npm_config_init_module: 'C:\\Users\\<user>\\.npm-init.js', npm_config_local_prefix: 'C:\\dev\\CypressTest', npm_config_metrics_registry: 'https://registry.npmjs.org/', npm_config_node_gyp: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js', npm_config_noproxy: '', npm_config_prefix: 'C:\\Program Files\\nodejs', npm_config_userconfig: 'C:\\Users\\<user>\\.npmrc', npm_config_user_agent: 'npm/9.2.0 node/v16.16.0 win32 x64 workspaces/false', npm_execpath: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\bin\\npx-cli.js', npm_lifecycle_event: 'npx', npm_lifecycle_script: 'cypress', npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe', npm_package_json: 'C:\\dev\\CypressTest\\package.json', npm_package_name: 'cypresstest', npm_package_version: '1.0.0', NUMBER_OF_PROCESSORS: '12', NVM_HOME: 'C:\\Users\\<user>\\AppData\\Roaming\\nvm', NVM_SYMLINK: 'C:\\Program Files\\nodejs', OneDrive: 'C:\\Users\\<user>\\OneDrive - CRISP', OneDriveCommercial: 'C:\\Users\\<user>\\OneDrive - CRISP', ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined', OS: 'Windows_NT', Path: 'C:\\dev\\CypressTest\\node_modules\\.bin;C:\\dev\\CypressTest\\node_modules\\.bin;C:\\dev\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Users\\<user>\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Users\\<user>\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\dotnet-core-uninstall\\;C:\\Users\\<user>\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\<user>\\.dotnet\\tools;C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\<user>\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;;C:\\Program Files\\JetBrains\\JetBrains Rider 2022.2.2\\bin;;;C:\\Users\\<user>\\AppData\\Local\\Programs\\Fiddler', PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', PROCESSOR_ARCHITECTURE: 'AMD64', PROCESSOR_IDENTIFIER:'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel', PROCESSOR_LEVEL: '6', PROCESSOR_REVISION: '9e0a', ProgramData: 'C:\\ProgramData', ProgramFiles: 'C:\\Program Files', 'ProgramFiles(x86)': 'C:\\Program Files (x86)', ProgramW6432: 'C:\\Program Files', PROJECT_BASE_DIR: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app', PROMPT: '$P$G', PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\', PUBLIC: 'C:\\Users\\Public', 'PyCharm Community Edition': 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;', SESSIONNAME: 'Console', SystemDrive: 'C:', SystemRoot: 'C:\\WINDOWS', TEMP: 'C:\\Users\\<user>\\AppData\\Local\\Temp', TMP: 'C:\\Users\\<user>\\AppData\\Local\\Temp', USERDOMAIN: 'AzureAD', USERDOMAIN_ROAMINGPROFILE: 'AzureAD', USERNAME: '<user>', USERPROFILE: 'C:\\Users\\<user>', UV_THREADPOOL_SIZE: '128', windir: 'C:\\WINDOWS', WSLENV: 'WT_SESSION:WT_PROFILE_ID:', WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}', WT_SESSION: '589d2978-d903-4500-832a-b9944990d5cd' }, type: 'browser', resourcesPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources', helperExecPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', crash: [Function (anonymous)], hang: [Function (anonymous)], getCreationTime: [Function (anonymous)], getHeapStatistics: [Function (anonymous)], getBlinkMemoryInfo: [Function (anonymous)], getProcessMemoryInfo: [Function (anonymous)], getSystemMemoryInfo: [Function (anonymous)], getSystemVersion: [Function (anonymous)], getIOCounters: [Function (anonymous)], getCPUUsage: [Function (anonymous)], takeHeapSnapshot: [Function (anonymous)], activateUvLoop: [Function (anonymous)], title: 'node', argv: [ 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', '--', '--project', 'C:\\dev\\CypressTest', '--cwd', 'C:\\dev\\CypressTest', '--userNodePath', 'C:\\Program Files\\nodejs\\node.exe', '--userNodeVersion', '16.16.0' ], execArgv: [], pid: 18120, ppid: 4820, execPath: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', debugPort: 9229, argv0: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\Cypress.exe', exitCode: 1, _preload_modules: [], report: [Getter], setSourceMapsEnabled: [Function: setSourceMapsEnabled], _firstFileName: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app\\index.js', mainModule: Module { id: '.', path: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app', exports: {}, filename: 'C:\\Users\\<user>\\AppData\\Local\\Cypress\\Cache\\13.3.3\\Cypress\\resources\\app\\index.js', loaded: true,children: [], paths: [Array] }, noAsar: undefined, enablePromiseAPIs: false, noDeprecation: true, traceDeprecation: true, __signal_exit_emitter__: EventEmitter { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: Infinity, count: 2, emitted: {}, infinite: true, [Symbol(kCapture)]: false }, emit: [Function: f], [Symbol(kCapture)]: false }, warning: Error: Inspected target navigated or closed at <embedded>:2466:519827 at _._handleMessage (<embedded>:2466:521860) at A.<anonymous> (<embedded>:2466:521673)     at A.emit (node:events:513:28) at g.U (<embedded>:2466:506953)     at g.emit (node:events:513:28) at g.dataMessage (<embedded>:2466:487328) at <embedded>:2466:486860 at <embedded>:2466:478182 at <embedded>:2466:479134     at afterWrite (node:internal/streams/writable:500:5)     at onwrite (node:internal/streams/writable:480:7)     at Zlib.<anonymous> (node:internal/streams/transform:190:7)     at Zlib.processCallback (node:zlib:613:8), type: undefined, code: undefined, args: [] } +9ms
  cypress:server:browsers:browser-cri-client Target.targetDestroyed { event: { targetId: 'D67595C3362748B382BE0A409C7AC4F5' }, closing: false, closed: false, resettingBrowserTargets: false } +18s
  cypress:server:cloud:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"Error","message":"Inspected target navigated or closed","stack":"Error: Inspected target navigated or closed\n    at <embedded>:2466:519827\n    at _._handleMessage (<embedded>:2466:521860)\n    at A.<anonymous> (<embedded>:2466:521673)\n    at A.emit (node:events:513:28)\n    at g.U (<embedded>:2466:506953)\n    at g.emit (node:events:513:28)\n    at g.dataMessage (<embedded>:2466:487328)\n    at <embedded>:2466:486860\n    at <embedded>:2466:478182\n    at <embedded>:2466:479134\n    at afterWrite (node:internal<stripped-path>writable:500:5)\n    at onwrite (node:internal<stripped-path>writable:480:7)\n    at Zlib.<anonymous> (node:internal<stripped-path>transform:190:7)\n    at Zlib.processCallback (node:zlib:613:8)"},"version":"13.3.3","osName":"win32","osVersion":"10.0.22621","osCpus":[{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3952906,"nice":0,"sys":3798421,"idle":239367750,"irq":480984}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":2374796,"nice":0,"sys":1193531,"idle":243550500,"irq":30593}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":6793921,"nice":0,"sys":5150328,"idle":235174546,"irq":122546}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":4272875,"nice":0,"sys":1950953,"idle":240894984,"irq":29875}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":5519828,"nice":0,"sys":3519515,"idle":238079500,"irq":93687}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3587281,"nice":0,"sys":2000453,"idle":241531062,"irq":45203}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":6871500,"nice":0,"sys":4137718,"idle":236109578,"irq":96875}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":4967718,"nice":0,"sys":2184859,"idle":239966187,"irq":38781}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":4029578,"nice":0,"sys":2596093,"idle":240493093,"irq":58468}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3211984,"nice":0,"sys":1648453,"idle":242258359,"irq":56375}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":5480671,"nice":0,"sys":3149187,"idle":238488968,"irq":71343}},{"model":"Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz","speed":2592,"times":{"user":3874968,"nice":0,"sys":1718078,"idle":241525765,"irq":29359}}],"osMemory":{"free":4306591744,"total":17095184384}},"headers":{"x-os-name":"win32","x-cypress-version":"13.3.3"}} and token: undefined +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' } +107ms
  cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 } +275ms
  cypress:network:connect got addresses { hostname: 'api.cypress.io', port: 443, addresses: [ { address: '172.67.25.250', family: 4 }, { address: '104.22.10.239', family: 4 }, { address: '104.22.11.239', family: 4 } ] } +1ms
  cypress:server:browsers killing browser process +18s
  cypress:server:browsers:chrome closing remote interface client { options: { gracefulShutdown: true } } +18s
  cypress:server:browsers:cri-client closing cri client { closed: false, target: '396D56893C353CF152C9FD0DA68A43BF' } +18s
  cypress:server:browsers:chrome closing chrome +1ms
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 87, proxyRequestsReceived: 34, immediatelyMatchedRequests: 14, unmatchedRequests: 13, unmatchedPreRequests: 0 } +0ms
  cypress:network:agent got family { family: 4, href: 'https://api.cypress.io/exceptions' } +20ms
  cypress:server:browsers:cri-client closed cri client { closed: true, target: '396D56893C353CF152C9FD0DA68A43BF' } +13ms
  cypress:server:browsers:cri-client closing cri client { closed: false, target: 'ws://127.0.0.1:9033/devtools/browser/e9b11170-2093-420a-850f-b8f026c7e2a3' } +0ms
  cypress:server:browsers:cri-client closed cri client { closed: true, target: 'ws://127.0.0.1:9033/devtools/browser/e9b11170-2093-420a-850f-b8f026c7e2a3' } +9ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'content-autofill.googleapis.com:443' } +307ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'clientservices.googleapis.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'fonts.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'widget.freshworks.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'safebrowsing.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'accounts.google.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'content-autofill.googleapis.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'localhost:9023' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'www.google.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'fonts.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'safebrowsing.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'safebrowsing.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'widget.freshworks.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'optimizationguide-pa.googleapis.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'optimizationguide-pa.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'fonts.gstatic.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'fonts.googleapis.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'fonts.googleapis.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'stats.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'stats.mydirectives.com:443' } +0ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +1ms
  cypress:https-proxy received error on client browserSocket { err: Error: read ECONNRESET     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) { errno: -4077, code: 'ECONNRESET', syscall: 'read' }, url: 'mydc-api-staging2.mydirectives.com:443' } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +40s
  cypress:cli child event fired { event: 'close', code: 1, signal: null } +0ms
```

### Other

This started failing in version 13.3.2
Although there is likely something not-quite-right in the target URL, this defect is preventing us from upgrading to the latest versions of Cypress

### LINKED ISSUE #28148: Error: Session with given id not found.
### Current behavior

Cypress is failing in GitHub Actions workflow:

```
Session with given id not found.
Error: Session with given id not found.
    at <embedded>:2466:519827
    at _._handleMessage (<embedded>:2466:521860)
    at A.<anonymous> (<embedded>:2466:521673)
    at A.emit (node:events:513:28)
    at g.U (<embedded>:2466:506953)
    at g.emit (node:events:513:28)
    at g.dataMessage (<embedded>:2466:487328)
    at <embedded>:2466:486860
    at <embedded>:2466:478182
    at <embedded>:2466:479134
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.<anonymous> (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

### Desired behavior

Cypress GitHub Action passes

### Test code to reproduce

https://github.com/remarkablemark/cypress-cucumber-steps/pull/537

### Cypress Version

13.3.3

### Node version

18.18.2

### Operating System

Ubuntu 22.04.3

### Debug Logs

_No response_

### Other

Related to https://github.com/cypress-io/cypress/issues/28136#issuecomment-1779617812

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28141
- Closes #28148

### Additional details

When we added logic to ensure we were attaching to CDP traffic we were not resilient enough to handle situations where the worker targets would attach and the immediately be closed (this can happen due to navigations or refreshing of the page). To fix this we will catch the errors. There's nothing really to do if the targets have been disposed anyway.

### Steps to test

n/a

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 1]
```diff
@@ -198,12 +198,17 @@ export class BrowserCriClient {
...
+            }
 
-          if (event.waitingForDebugger) {
-            await browserClient.send('Runtime.runIfWaitingForDebugger', undefined, event.sessionId)
+            if (event.waitingForDebugger) {
+              await browserClient.send('Runtime.runIfWaitingForDebugger', undefined, event.sessionId)
+            }
+          } catch (error) {
+            // it's possible that the target was closed before we could enable network and continue, in that case, just ignore
+            debug('error attaching to target browser', error)
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/browser-cri-client.ts:211]: Would the error we are trying to fix be observed on lines 216 & 217 if the target has already closed?

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 2]
```diff
@@ -198,12 +198,17 @@ export class BrowserCriClient {
         // The basic approach here is we attach to targets and enable network traffic
         // We must attach in a paused state so that we can enable network traffic before the target starts running.
         browserClient.on('Target.attachedToTarget', async (event) => {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/browser-cri-client.ts:200]: Is it possible to have a system-test in place to verify this behavior?

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 1 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/browser-cri-client.ts:211]: No. Those lines happen as part of setup before we even get to user land.

File: cli/CHANGELOG.md [hunk 3]
```diff
@@ -1,4 +1,12 @@
 <!-- See the ../guides/writing-the-cypress-changelog.md for details on writing the changelog. -->
+## 13.3.4
+
+_Released 11/7/2023 (PENDING)_
+
+**Bugfixes:**
+
+- Fixed a regression in `13.3.2` where loading a service worker and immediately reloading the page can cause a crash. Fixes [#28141](https://github.com/cypress-io/cypress/issues/28141).
```
Comment (emilyrohrbough) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed a regression in [`13.3.2`](https://docs.cypress.io/guides/references/changelog/13.3.2) where loading a service worker and immediately reloading the page can cause a crash. Fixes [#28141](https://github.com/cypress-io/cypress/issues/28141).
```

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 2 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/browser-cri-client.ts:200]: I was unable to get this reproduced reliably with a system test or cypress in cypress test (even the website in question does not cause the problem). As a result, I am just going with a targeted unit test.

**Review by chrisbreiding — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@ryanthemanuel 

- I was able to confirm that #28148 is resolved by this PR by building and running the HEAD of the develop branch.

**Comment by jennifer-shehane** [comment]
Thanks @MikeMcC399, we're still working on getting a release out.

**Comment by MikeMcC399** [comment]
Shouldn't the https://github.com/apps/cypress-bot run to mark this as released?
