### PR TITLE
fix: (vite-dev-server) wait for support file

### LINKED ISSUE #25913: Component tests failing intermittently with uncaught Vite "failed to fetch dynamically imported module" error in CI
### Current behavior

We started migrating our project from CRA to Vite and we have almost 300 component and 40 E2E Cypress tests in place. Unfortunately, after fixing all the other issues, we are still not able to stabilize our tests since there is always 1 or 2 failing randomly on "Failed to fetch dynamically imported module" errors.

We noticed that it's somehow related to the load of CI. Under some conditions more tests are failing like this, in other times it succeeds. But it's random. We checked our tests and we are pretty sure it's not caused by any logic we have.

We've checked some of the existing issues on Cypress & Vite, tried various workaround but no luck with any of them.

What we think is happening is that Cypress is not waiting for Vite to "boot up" properly and retries don't help with it, only when new spec is run, it works.

Note: it only happens with component tests. For E2E tests we had similar stability issues but we solved them by building production version and then just serving it with `vite preview`. This made integration tests faster and very stable. Previously they were also timeouting.

Note 2: we have a lot of components and lot of dependencies in our project, we also use MUI as our base. But with CRA we were able to have stable tests, it was just around two times slower. That's why we want to use Vite now.

Note 3: we are running "Component tests" in parallel, currently in 4 groups.

### Desired behavior

No random problems with Cypress + Vite combo.

### Test code to reproduce

Unfortunately can't provide this since our project is private. And I'm afraid that it's related to project's complexity and that's why we can't easily create another one for reproduction.

### Cypress Version

v12.6.0

### Node version

v16.18.1

### Operating System

Docker Hub image: cypress/included for v12.6.0 version

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes https://github.com/cypress-io/cypress/issues/25913

### Additional details
- **Why:** In CI (and sometimes locally), the Cypress iframe can load and run `initCypressTests.js` before the Vite dev server has finished serving the support file, leading to "Failed to fetch dynamically imported module" and flaky test failures.
- **What's affected:** `@cypress/vite-dev-server` startup sequence.
- **Implementation:** After `server.listen()`, the dev server now polls the support file URL until it returns HTTP 200 before signaling "dev server ready". A new `waitForSupportFile.ts` module builds the same URL path the browser client uses and polls up to 30 times (200ms apart) before timing out. This makes the "ready" signal deterministic and eliminates the race between server startup and the iframe's first module request.

---

> [!NOTE]
> **Medium Risk**
> Changes the dev-server readiness gate and adds network polling during startup, which could introduce delays or timeouts in environments with unusual Vite host/serve behavior.
> 
> **Overview**
> Fixes a flake in `@cypress/vite-dev-server` where the CT iframe could attempt to import the support file before Vite was able to serve it.
> 
> After `server.listen()`, the dev server now computes the same support-file URL the browser will import (respecting `devServerPublicPathRoute` and Windows path handling) and polls it until it returns a successful response before returning the resolved dev-server config. Adds unit tests for the URL/path builder and polling behavior, and documents the bugfix in the CLI changelog.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit ee1860ae3ef305e254ed80bbbf458a17d7cbfd66. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### Steps to test
- Run component tests using the Vite dev server in an environment where the server can be slow to serve modules (e.g. CI or under load). Before: occasional "Failed to fetch dynamically imported module"; after: dev server waits for the support file to be servable before signaling ready.
- New unit tests: `yarn workspace @cypress/vite-dev-server test -- waitForSupportFile.spec.ts`

### How has the user experience changed?
- **Before:** Intermittent "Failed to fetch dynamically imported module" failures when the iframe requested the support file before Vite had it ready.
- **After:** Dev server is considered ready only when the support file URL returns HTTP 200, eliminating the race condition.

### PR Tasks
- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/vite-dev-server/client/initCypressTests.js [hunk 1]
```diff
@@ -5,6 +5,33 @@ const CypressInstance = window.Cypress = parent.Cypress
 
 const importsToLoad = []
 
+// Retry dynamic import to tolerate Vite dev server not ready yet (e.g. in CI).
+// "Failed to fetch dynamically imported module" can happen when the iframe loads
+// before the server has finished serving the support or spec module.
+function isRetryableImportError (err) {
+  const msg = err && err.message
```
Comment (AtofStryker) [inline npm/vite-dev-server/client/initCypressTests.js]: FWIW i jumped down this rabbit hole in late December / early January with @jennifer-shehane 's PR https://github.com/cypress-io/cypress/pull/33149#discussion_r2651854680. Once a dynamic import is executed, the result is cached and AFAIK the request cannot be retried because it will yield the same results. The other issue is that the optimize dependency tree can change, and the server will reload mid test execution, so there are no guarantees.

Comment (mschile) [reply npm/vite-dev-server/client/initCypressTests.js]: Yeah, I had meant to revert this change and only keep the waiting for support file.

File: npm/vite-dev-server/test/waitForSupportFile.spec.ts [hunk 2]
```diff
@@ -0,0 +1,95 @@
+import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
+import { getSupportFileRelativePath, waitUntilUrlReady } from '../src/waitForSupportFile.js'
```
Comment (AtofStryker) [inline npm/vite-dev-server/test/waitForSupportFile.spec.ts]: Within the the `vitest` tests themselves we usually import the TS file to test, even though the package is an ESM and imports `.js` in the source files. Mostly recommending this for consistency

```suggestion
import { getSupportFileRelativePath, waitUntilUrlReady } from '../src/waitForSupportFile'
```

**Review by AtofStryker — APPROVED** [review]

**Review by AtofStryker — COMMENTED** [review]
Code looks good. Did you want to add a change entry to the app?

File: npm/vite-dev-server/test/waitForSupportFile.spec.ts (hunk 2 above)
Comment (mschile) [reply npm/vite-dev-server/test/waitForSupportFile.spec.ts]: updated [84faae5](https://github.com/cypress-io/cypress/pull/33487/commits/84faae57d0234973c8526dddf8010914a9b3248b)

**Comment by mschile** [comment]
> Did you want to add a change entry to the app?

Yep, added a changelog entry. [ee1860a](https://github.com/cypress-io/cypress/pull/33487/commits/ee1860ae3ef305e254ed80bbbf458a17d7cbfd66)
