### PR TITLE
fix: empty state urls in navigation

### LINKED ISSUE #19749: `undefined (reading 'undefined')` on cypress_runner.js
### Current behavior

When running on `cypress@9.3.1`, there is an issue on `cypress_runner.js` - `Cannot read properties of undefined (reading 'undefined')`. It happens on https://github.com/cypress-io/cypress/blob/8355e5d8ec35411a6935687c9c91540dd32cf7f4/packages/driver/src/cy/navigation.ts#L29

image

This error usually happens on `cy.go('back')`. Failing tests on Cypress dashboard - https://dashboard.cypress.io/projects/oqk3fk/runs/4680/overview

### Desired behavior

No undefined error messages

### Test code to reproduce

 it('should return to previous page', function () {
    cy.go('back')
 })

### Cypress Version

9.3.1

### Other

_No response_

### LINKED ISSUE #20539: Cannot read properties of undefined (reading 'undefined') in historyNavigationTriggeredHashChange
### Current behavior

We have a Cypress test which tests UI navigation by clicking links, then using the browser's back button to pop the history stack. When running this test in Cypress 9.5.0, we get a stack trace from Cypress code:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'undefined')
    at historyNavigationTriggeredHashChange (cypress_runner.js:166581:101)
    at HTMLIFrameElement.<anonymous> (cypress_runner.js:173017:111)
    at HTMLIFrameElement.dispatch (cypress_runner.js:113217:27)
    at HTMLIFrameElement.elemData.handle (cypress_runner.js:113025:28)
```

### Desired behavior

No stack trace.

### Test code to reproduce

N/A

### Cypress Version

9.5.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by mr-short**
- Closes #19749
- Closes #20539 

### User facing changelog

n/a

### Additional details

This issue occurs during url state changes and Cypress attempts to test the current url, but the state is empty.

### How has the user experience changed?

Cypress stops randomly throwing this error and failing tests:
`TypeError: Cannot read properties of undefined (reading 'undefined')`

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]
🎉 Thank you for the contribution!

File: packages/driver/src/cy/navigation.ts [hunk 1]
```diff
@@ -25,6 +26,11 @@ export const historyNavigationTriggeredHashChange = (state): boolean => {
   }
 
   const urls = state('urls')
+
+  if (_.isEmpty(urls)) {
```
Comment (tbiethman) [inline packages/driver/src/cy/navigation.ts:30]: Let's explicitly check for a urlPosition value here too before continuing on. Your second spec asserts that it doesn't throw without a value, but the logic that follows isn't very meaningful without one.

**Review by tbiethman — APPROVED** [review]
