### PR TITLE
fix(server): Fix EACCES on extension installation if copied from read-only location

### LINKED ISSUE #3852: After upgrading to 3.2.0 specs won't run on chrome or chromium only on Electron browser
### Current behavior:
```
Can't start server
EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'  
```
image

Debug output:
```
$ DEBUG=cypress:* 
cypress:server:events send error: { Error: EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'   cause: { Error: EACCES: permission denied, unlink '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js'   errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' }, isOperational: true, errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' } +21ms                                                                
  cypress:server:events sending ipc data { type: 'launch:browser', data: { id: 0.19919725450670933, __error: { name: 'Error', stack: 'Error: EACCES: permission denied, unlink \'/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js\'\n\n', message: 'EACCES: permission denied, unlink \'/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js\'', cause: [Object], isOperational: true, errno: -13, code: 'EACCES', syscall: 'unlink', path: '/home/acyuta/.config/Cypress/cy/production/browsers/chrome/interactive/CypressExtension/background.js' } } } +1ms
```

### Desired behavior:
Browser should open and run selected spec(s)

### Steps to reproduce: (app code and test code)
```
$(npm bin)/cypress open # which currently points to ~/.cache/Cypress/3.2.0/Cypress/Cypress
Click on any spec
Error shows on app screen
```

If I clear (rm -rf ~/.config/Cypress) the config folder it gets recreated on next run, but error persists.
If I switch to Electron browser, specs run as expected.
If I run specs from the cli (`$(npm bin)/cypress run`), specs run as expected.

### Versions
Cypress 3.2.0
Chrome and Chromium 72
Linux NixOS 4.14.98

### PR DESCRIPTION
**Pull request by Abdillah**
- Closes #3852

### User facing changelog
Fix running tests in Chrome and Firefox when cypress is installed in a read-only location

### Additional details
The addon installation need write access to `background.js`, while copying from read-only location retain the non-writable permission.

Older implementation on https://github.com/cypress-io/cypress/pull/5579 without any test.

### How has the user experience changed?
No

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@Abdillah Thanks for writing up a fix and a test!

There's a typescript error throwing if you check the CI logs and one of the server unit tests. Can you address these? https://app.circleci.com/pipelines/github/cypress-io/cypress/23127/workflows/6f34e5d5-c409-4c4e-b43c-45f9e7af8718/jobs/852632

```
lib/browsers/chrome.ts(378,14): error TS2551: Property 'chmodAsync' does not exist on type 'PromisifiedFsExtra & typeof import("/root/cypress/node_modules/@types/fs-extra/index")'. Did you mean 'chmodSync'?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Abdillah** [comment]
Done!

The cri-client spec still has error, but I see no relation to this PR. Moreover, it's a strange error: clearly checked that the `cri-client.js` and `cri-client.ts` exists and added `__dirname` to ensure that but it still raised the error.

File: packages/server/test/unit/browsers/chrome_spec.js [hunk 1]
```diff
@@ -228,6 +231,43 @@ describe('lib/browsers/chrome', () => {
       })
     })
 
+    it('install extension and ensure write access', function () {
+      mockfs({
```
Comment (flotwig) [inline packages/server/test/unit/browsers/chrome_spec.js:235]: I think the reason this is failing is because `fs` is not being restored after the test. Try adding an `afterEach` that calls the callback returned by `mockfs` to reset the `fs`: https://github.com/tschaub/mock-fs#mockrestore

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/server/test/unit/browsers/chrome_spec.js (hunk 1 above)
Comment (Abdillah) [reply packages/server/test/unit/browsers/chrome_spec.js:235]: Ah I see.. thanks for the hint @flotwig

File: packages/server/lib/browsers/chrome.ts [hunk 2]
```diff
@@ -375,6 +375,7 @@ export = {
 
     // copy the extension src to the extension dist
     await utils.copyExtension(pathToExtension, extensionDest)
+    fs.chmodSync(extensionBg, 0o0644)
```
Comment (flotwig) [inline packages/server/lib/browsers/chrome.ts:378]: Use asynchronous methods:

```suggestion
    await fs.chmod(extensionBg, 0o0644)
```

**Comment by Abdillah** [comment]
Thank you for the reviews and also the changes, @flotwig @jennifer-shehane. 
Can the failing test be ignored for this PR to be merged? Is there any more work necessary on my side?
