### PR TITLE
Ignore dangling node in DOM tree.

### LINKED ISSUE #6745: Cannot read property 'map' of null at parseMatrix2D
### Current behavior:

Trying `cy.get('.selector')` - fail with TypeError: `Cannot read property 'map' of null`

When the "vue-fragment" component is included in the project, cypress, for some reason, cannot parse

image

### Test code to reproduce

I created a repository to reproduce:
https://github.com/shoomakov/cypress-issue

```
npm i
npm run serve

cd tests/e2e
npm i
npm run dev
```

### Versions
Cypress v.4.0.2
Browser Chrome

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #6745

### User facing changelog

`vue-fragment` made `isVisible` fail. It is fixed in this PR.

#### Why was this change necessary?

Because of the manipulation of `parentNode` by `vue-fragment`. Dangling elements are created and they return empty string. [Because `getComputedStyle()` returns empty strings when the element is not in the DOM tree.](https://bugs.chromium.org/p/chromium/issues/detail?id=558165)

#### What is affected by this change?

N/A

#### Any implementation details to explain?

Created a test file that replicate the behavior. They're done in these 3 steps.

**Step 1. Create new DOM tree**
Screenshot from 2020-03-20 15-14-21

**Step 2. Add paragraph to parent and set parentNode to container**
Screenshot from 2020-03-20 15-14-21 (copy)

**Step 3. Remove container and set parentNode to parent**
Screenshot from 2020-03-20 15-14-23

Because of the Step 3, container is not in the DOM tree, but it's the parent of paragraph. So, it can be accessed and the bug occurred. 

### How has the user experience changed?

`cy.get()` works even if `vue-fragment` is used. 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I'm curious about the tests here because I feel like something similar may be happening for Lightning Web Components, where they are forcefully changing the `parentNode` or something where it ends up being null. https://github.com/cypress-io/cypress/issues/6707

**Comment by sainthkh** [comment]
I'll check it out.

**Comment by sainthkh** [comment]
@jennifer-shehane 

As #6707 and #4373 are closed and cannot be commented, I write my research here. 

The cause of this problem is that [Salesforce team defined their own Node](https://github.com/salesforce/lwc/blob/v1.0.3/packages/%40lwc/synthetic-shadow/src/faux-shadow/node.ts#L163). And when the type of the parent of a node is not `Element`, it returned null. ([check this code](https://github.com/salesforce/lwc/blob/v1.0.3/packages/%40lwc/synthetic-shadow/src/faux-shadow/node.ts#L89))

Because of that, in our example, the parent of `lightning-badge`, `c-app`, is not Element. So, it returned `null`.

Interestingly, this node-patching is removed from v1.1.0 of lwc. So, I guess the problem should not happen with the versions after that. 

And as for the solution of this null problem, I think your #6708 is the best solution. 

As the example didn't patch `parentElement`, I thought we could use that instead. But [as you can see here](https://github.com/salesforce/lwc/blob/v1.0.3/packages/%40lwc/synthetic-shadow/src/faux-shadow/node.ts#L170), they also defined parentElement here. It seems that it is not included in the example because of tree shaking.

**Comment by jennifer-shehane** [comment]
@sainthkh Awesome, this makes sense. Thanks for looking into that. I do think the el existence checks are good, not sure they are *everywhere* they need to be in our code though.

File: packages/driver/src/dom/transform.ts [hunk 1]
```diff
@@ -44,15 +48,17 @@ const extractTransformInfoFromElements = ($el: any, list: TransformInfo[] = []):
...
-    transformStyle: style.getPropertyValue('transform-style') as TransformStyle,
-    transform: style.getPropertyValue('transform'),
-  }
+  return style.getPropertyValue('backface-visibility') !== ''
+    ? {
+      backfaceVisibility: style.getPropertyValue('backface-visibility') as BackfaceVisibility,
+      transformStyle: style.getPropertyValue('transform-style') as TransformStyle,
+      transform: style.getPropertyValue('transform'),
+    }
+    : null
```
Comment (brian-mann) [inline packages/driver/src/dom/transform.ts]:
```suggestion
  const backfaceVisibility = style.getPropertyValue('backface-visibility')
  
  // this handles an edge case from frameworks like `vue-fragment` 
  // that modify the `parentNode` of the element
  // @see https://github.com/cypress-io/cypress/pull/6787
  // @see https://github.com/cypress-io/cypress/issues/6745
  if (backfaceVisibility === '') {
    return null
  }
  
  return {
    backfaceVisibility as BackfaceVisibility,
    transformStyle: style.getPropertyValue('transform-style') as TransformStyle,
    transform: style.getPropertyValue('transform'),
  }
```

Comment (brian-mann) [reply packages/driver/src/dom/transform.ts]: just want this change to clarify on why its necessary, and link out to the additional bits

File: packages/driver/test/cypress/integration/dom/visibility_spec.ts [hunk 2]
```diff
@@ -835,6 +835,11 @@ describe('src/cypress/dom/visibility', () => {
           expect(el).to.be.visible
         })
 
+        it('is visible even if there is a dangling element in the tree', () => {
+          cy.visit('/fixtures/dangling-element.html')
+          cy.get('.hello')
+        })
+
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/dom/visibility_spec.ts]:
```suggestion
		// https://github.com/cypress-io/cypress/issues/6745
        it('is visible even if there is a dangling element in the tree', () => {
          cy.visit('/fixtures/dangling-element.html')
          cy.get('.hello')
        })

```

Comment (brian-mann) [reply packages/driver/test/cypress/integration/dom/visibility_spec.ts]: whenever you're writing a test that fixes a specific issue always note it as a comment so other team members understand its connection to the underlying issue

File: packages/driver/src/dom/transform.ts [hunk 3]
```diff
@@ -33,7 +33,11 @@ interface TransformInfo {
 }
 
 const extractTransformInfoFromElements = ($el: any, list: TransformInfo[] = []): TransformInfo[] => {
-  list.push(extractTransformInfo($el))
+  const info = extractTransformInfo($el)
+
+  if (info !== null) {
```
Comment (brian-mann) [inline packages/driver/src/dom/transform.ts]:
```suggestion
  if (info) {
```

or 

```suggestion
  info && list.push(info)
```

Comment (sainthkh) [reply packages/driver/src/dom/transform.ts]: Done.

File: packages/driver/test/cypress/integration/dom/visibility_spec.ts (hunk 2 above)
Comment (sainthkh) [reply packages/driver/test/cypress/integration/dom/visibility_spec.ts]: Done.

File: packages/driver/src/dom/transform.ts (hunk 1 above)
Comment (sainthkh) [reply packages/driver/src/dom/transform.ts]: Done.

**Comment by sainthkh** [comment]
@brian-mann 

* Fixed all.
* Thanks for the advice about commenting.

**Comment by jennifer-shehane** [comment]
@sainthkh Yeah, comments are our friend, especially when answering 'why do we even need this piece of code?'

File: packages/driver/src/dom/transform.ts [hunk 4]
```diff
@@ -44,15 +48,22 @@ const extractTransformInfoFromElements = ($el: any, list: TransformInfo[] = []):
...
+  // `parentNode` is modified and out of the DOM tree.
+  // @see https://github.com/cypress-io/cypress/pull/6787
+  // @see https://github.com/cypress-io/cypress/issues/6745
+  return style.getPropertyValue('backface-visibility') !== ''
+    ? {
+      backfaceVisibility: style.getPropertyValue('backface-visibility') as BackfaceVisibility,
+      transformStyle: style.getPropertyValue('transform-style') as TransformStyle,
+      transform: style.getPropertyValue('transform'),
+    }
+    : null
```
Comment (brian-mann) [inline packages/driver/src/dom/transform.ts]:
```suggestion
  const backfaceVisibility = style.getPropertyValue('backface-visibility')
  
  // When an element is not in the DOM tree, getComputedStyle() returns empty string.
  // In an edge case from frameworks like `vue-fragment`
  // `parentNode` is modified and out of the DOM tree.
  // @see https://github.com/cypress-io/cypress/pull/6787
  // @see https://github.com/cypress-io/cypress/issues/6745
  if (backfaceVisibility === '') {
    return null
  }
  
  return {
    backfaceVisibility as BackfaceVisibility,
    transformStyle: style.getPropertyValue('transform-style') as TransformStyle,
    transform: style.getPropertyValue('transform'),
  }
```
