### PR TITLE
fix(server): close Firefox completely between specs on Windows

### LINKED ISSUE #6392: Cypress could not connect to Firefox. `Error: cannot open socket` displayed at beginning of running spec
When running cypress with options '--headless --browser firefox', cypress halts **at the start of the second spec** with message: 

```
Cypress could not connect to Firefox.

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure sure that there are no other instances of Firefox launched by Cypress running.
```

This blocks running all specs in 'run' mode
Windows 10, Firefox version 72 (64 bit)

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-82) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by suryart**
Firefox is spawned differently than chrome. For Firefox, the `.kill()` does not actually close the instance running with the current profile from the arguments. It spawns a parent and a child process and runs the spec in the child process instance, while `.kill()` kills the child process, it leaves the parent process running, leading the next run to conflict with another spawned process(which fails for obvious reason) for the next spec execution.

- Fix #6392 

### User facing changelog

- Fixed an issue where running multiple specs in `cypress run` on Windows could fail.

### Additional details

Bug fix: Video recording fails as Firefox instance not closing at the end of the spec on Windows.
Bug fix: Failing to start new spec with Firefox as previous Firefox instance not closing at the end of the spec on Windows.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ na ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ na ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ na ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hi, we're changing our contributing workflow to use Draft PRs instead of `[WIP]` in the title. I've converted this PR to a Draft PR and removed `[WIP]` from the title. 

Please [mark the PR as **Ready for Review**](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review) when you're ready for a Cypress team member to review the PR.

**Comment by flotwig** [comment]
@suryart does this only apply on win32, confirmed? it seems that users are having similar issues on macOS and linux, although not everyone :thinking:

**Comment by flotwig** [comment]
ah, i get it, this only happens on windows because we have to use cmd.exe to spawn firefox, and firefox immediately detaches itself from cmd.exe which leads to `proc.kill` failing...

**Comment by suryart** [comment]
> @suryart does this only apply on win32, confirmed? it seems that users are having similar issues on macOS and linux, although not everyone 🤔

Sorry for the delayed response. I see in the other comment that you've figured it's happening only on Windows(win32). The PR mentioned seems like the right approach to me. So, please feel free to close this PR if needed.

File: packages/server/lib/browsers/firefox.ts [hunk 1]
```diff
@@ -412,5 +414,38 @@ export async function open (browser: Browser, url, options: any = {}) {
...
+
+      killFirefoxInstanceWin32(browserInstance)
+    }
+  }
+
   return browserInstance
 }
+
+const killFirefoxInstanceWin32 = (browserInstance) => {
+  let instanceKill = `TASKKILL /T /PID ${browserInstance.pid}`
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts:430]: Can you use Node's `process.kill(pid)` here instead?

File: packages/server/lib/browsers/firefox.ts [hunk 2]
```diff
@@ -412,5 +414,38 @@ export async function open (browser: Browser, url, options: any = {}) {
...
+
+  let parentPidFile = browserInstance.spawnargs[browserInstance.spawnargs.length - 1].split('\\')
+  let parentPidWithFilename = parentPidFile[parentPidFile.length - 1].split('-')
+  let parentPid = parentPidWithFilename[parentPidWithFilename.length - 1]
+
+  let parentKill = `TASKKILL /T /PID ${parentPid}`
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts:436]: `process.kill(pid)`

File: packages/server/lib/browsers/firefox.ts [hunk 3]
```diff
@@ -412,5 +414,38 @@ export async function open (browser: Browser, url, options: any = {}) {
...
+
   return browserInstance
 }
+
+const killFirefoxInstanceWin32 = (browserInstance) => {
+  let instanceKill = `TASKKILL /T /PID ${browserInstance.pid}`
+
+  let parentPidFile = browserInstance.spawnargs[browserInstance.spawnargs.length - 1].split('\\')
+  let parentPidWithFilename = parentPidFile[parentPidFile.length - 1].split('-')
+  let parentPid = parentPidWithFilename[parentPidWithFilename.length - 1]
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts:434]: use a regex instead of manual string splitting for clarity

File: packages/server/lib/browsers/firefox.ts [hunk 4]
```diff
@@ -412,5 +414,38 @@ export async function open (browser: Browser, url, options: any = {}) {
 
   await firefoxUtil.setup({ extensions: launchOptions.extensions, url, foxdriverPort, marionettePort })
 
+  // Override the .kill method for Windows so that the Browsers closes b/w specs
+  if (os.platform() === 'win32') {
+    browserInstance.kill = async (...args) => {
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts:419]:
```suggestion
    browserInstance.kill = (...args) => {
```

child_process.kill isn't async is it?

File: packages/server/lib/browsers/firefox.ts [hunk 5]
```diff
@@ -412,5 +414,38 @@ export async function open (browser: Browser, url, options: any = {}) {
 
   await firefoxUtil.setup({ extensions: launchOptions.extensions, url, foxdriverPort, marionettePort })
 
+  // Override the .kill method for Windows so that the Browsers closes b/w specs
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts:417]: add issue link
```suggestion
  // Override the .kill method for Windows so that the Browsers closes b/w specs
  // @see ...
```

**Comment by suryart** [comment]
> Hey @suryart, thanks for the PR. I tried doing a different fix in #7336 but it didn't work, so we should continue with your approach.
> 
> This PR looks good so far. Please add some unit tests in `firefox_spec.ts` to ensure there is not a regression, address the comments, and it should be good to merge.

Sure. Thank you for the reviews. I will update code according to the changes requested in a few weeks.

**Comment by flotwig** [comment]
@suryart I'll try to finish this up today, so we can get the fix out with the release next week

File: packages/server/lib/browsers/firefox.ts [hunk 6]
```diff
@@ -419,5 +421,38 @@ export async function open (browser: Browser, url, options: any = {}) {
...
+
   return browserInstance
 }
+
+const killFirefoxInstanceWin32 = (browserInstance) => {
+  let instanceKill = `TASKKILL /T /PID ${browserInstance.pid}`
+
+  let parentPidFile = browserInstance.spawnargs[browserInstance.spawnargs.length - 1].split('\\')
+  let parentPidWithFilename = parentPidFile[parentPidFile.length - 1].split('-')
+  let parentPid = parentPidWithFilename[parentPidWithFilename.length - 1]
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox.ts]: the pid here is actually the pid of the Cypress Electron process, which we don't want to kill

**Comment by flotwig** [comment]
having some issues getting this to work, something doesn't like being killed: 
image

**Comment by bhaskerchari** [comment]
@flotwig,

Any luck with the changes done and the approach you have taken? I have also tried various ways of killing firefox instance but getting the same error as you mentioned in the above comment.

**Comment by flotwig** [comment]
@bhaskerchari not yet, for now you could probably disable video recording (`video: false`) to avoid this error.

**Comment by bhaskerchari** [comment]
> @bhaskerchari not yet, for now you could probably disable video recording (`video: false`) to avoid this error.

@flotwig , Sorry just curious how does it work by disabling video recording (`video: false`) to avoid this error? What it has to do with Video recording? However I tried this option you suggested but still didn't work.

**Comment by flotwig** [comment]
@bhaskerchari I was able to work around the ECONNRESET error by handling foxdriver errors here: 111e09b

**Comment by bhaskerchari** [comment]
> @bhaskerchari I was able to work around the ECONNRESET error by handling foxdriver errors here: [111e09b](https://github.com/cypress-io/cypress/commit/111e09b255741c0461c29d6449be735a8c497e5b)

@flotwig ,

Thank you for the update but any idea on when the fix may be released into the latest cypress version?

**Comment by flotwig** [comment]
> Thank you for the update but any idea on when the fix may be released into the latest cypress version?

Hopefully within the next release.

File: packages/server/test/e2e/1_firefox_spec.ts [hunk 7]
```diff
@@ -68,4 +68,12 @@ describe('e2e firefox', function () {
       expect(stderr).not.to.include('foxdriver')
     },
   })
+
+  // NOTE: only an issue on windows
+  // https://github.com/cypress-io/cypress/issues/6392
+  e2e.it.skip('can run multiple specs', {
```
Comment (bahmutov) [inline packages/server/test/e2e/1_firefox_spec.ts:74]: can't this test be enabled to run on Windows only?

Comment (flotwig) [reply packages/server/test/e2e/1_firefox_spec.ts:74]: not in our existing test setup, we run 0 e2e tests on Windows

Comment (bahmutov) [reply packages/server/test/e2e/1_firefox_spec.ts:74]: ughh, it would be nice to run some e2e tests on Windows

**Comment by flotwig** [comment]
@bahmutov now that https://github.com/cypress-io/cypress-example-kitchensink/pull/436 is opened, can this be approved?
