### PR TITLE
fix: clean up the primaryOriginCommunicator when the iframe is torndown to…

### LINKED ISSUE #21319: [Spike] Investigate increased memory usage with recent Firefox versions (98+)
### Current behavior

When updating our internal CI image to run with Firefox 98, one of our existing builds started timing out/crashing due to a lack of resources. [Example](https://app.circleci.com/pipelines/github/cypress-io/cypress/36853/workflows/0372af92-795e-47b2-9579-d93749d37827/jobs/1478739)

I was able to trace this increase back to a commit and gather some metrics before/after it was merged:

Spec ran: [runner/cypress/integration/reporter.errors.spec.js](https://github.com/cypress-io/cypress/blob/develop/packages/runner/cypress/integration/reporter.errors.spec.js)
OS: macOS Monterey
System: i9 / 16GB total RAM

Commit: 0bb655e379 |   |   | RAM (GB) |   |   |  
-- | -- | -- | -- | -- | -- | --
  | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Avg
Firefox 99 | 2.55 | 2.53 | 2.59 | 2.68 | 2.43 | 2.556
Firefox 99 (numTestsKeptInMemory=0) | 1.39 | 1.18 | 0.953 | 1.32 | 1.29 | 1.2266
Chrome 101 | 1.55 | 1.69 | 1.74 | 1.59 | 1.6 | 1.634
Chrome 101 (numTestsKeptInMemory=0) | 1.13 | 1.12 | 1.14 | 1.15 | 1.12 | 1.132

Commit: 676fc97f46 |   |   | RAM (GB) |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Avg | % Increase
Firefox 99 | 3.52 | 3.5 | 3.53 | 3.51 | 3.52 | 3.516 | 37.56
Firefox 99 (numTestsKeptInMemory=0) | 3.19 | 3.28 | 3.21 | 3.25 | 3.23 | 3.232 | 163 (❗)
Chrome 101 | 1.63 | 1.58 | 1.66 | 1.59 | 1.59 | 1.61 | -1.5
Chrome 101 (numTestsKeptInMemory=0) | 1.27 | 1.28 | 1.26 | 1.27 | 1.26 | 1.268 | 12.01

To summarize, with 676fc97f46 (the origin feature branch merge) we start using a lot more memory with FF99. Chrome 101 stays relatively stable. 

That spec file has 83 individual tests in it, and its snapshots can be quite large. So I also recorded runs with the `numTestsKeptInMemory` config value set to 0 to see what impact it had on memory usage. You can see that with 0bb655e379, setting that config property had a significant impact on FF99 and cut its usage in half; however, it had a minimal effect on 676fc97f46. It also had a decreased effect with Chrome 101 on 676fc97f46, with usage up 12% from the previous commit.

We should track down where/why this memory is being held.

### Desired behavior

We don't consume more memory than we have to when running with Firefox.

### Test code to reproduce

1. Checkout cypress
2. Run `yarn cypress:open`
3. Run  [runner/cypress/integration/reporter.errors.spec.js](https://github.com/cypress-io/cypress/blob/develop/packages/runner/cypress/integration/reporter.errors.spec.js) in various browsers
4. Look at held memory after run completes

### Cypress Version

9.6.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
… prevent dangling memory leaks

- Closes #21319 #21651

### Additional details

The goal of this PR is to address potential memory leak issues with the `cy.origin` communicators to make sure they are reset any time a new version of the driver is created (on teardown). This should prevent memory leaks of hidden event emitters stacking, leading to performance issues or weird behaviors. Regression tests are added for cy in cy to make sure hot reloads works with cy origin (no weird event state/bindings) as well as rerunning the spec from the main menu.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/runner/event-manager.ts [hunk 1]
```diff
@@ -673,6 +671,28 @@ export class EventManager {
...
+     *
+     * This is also applicable when a user changes their spec file and hot reloads their spec, in which case we need to rebind onMessage
+     * with the newly creates Cypress.primaryOriginCommunicator
+     */
+    window?.top?.removeEventListener('message', crossOriginOnMessageRef, false)
+    crossOriginOnMessageRef = ({ data, source }) => {
+      Cypress?.primaryOriginCommunicator.onMessage({ data, source })
+
+      return undefined
+    }
```
Comment (tgriesser) [inline packages/app/src/runner/event-manager.ts:693]: Could we just move this entire thing to the outer scope and rely on the `Cypress` being global, rather than reassigning?

Comment (AtofStryker) [reply packages/app/src/runner/event-manager.ts:693]: We can't due to `Cypress` being recreated. What ultimately happens is the `primaryOriginCommunicator` is the wrong instance, so we need to rebind when Cypress is created

File: packages/app/cypress/e2e/cypress-origin-communicator.cy.ts [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+      cy.waitForSpecToFinish()
+
+      cy.get('.passed > .num').should('contain', 1)
+      // make sure duplicate logs are not present
+      cy.get('.command-name-origin').find('.command-name-log').should('have.length', 2)
+
+      cy.withCtx(async (ctx) => {
+        const indexPath = ctx.path.join('cypress', 'e2e', 'origin', 'simple_origin.cy.js')
+
+        await ctx.actions.file.writeFileInProject(
```
Comment (mjhenkes) [inline packages/app/cypress/e2e/cypress-origin-communicator.cy.ts:129]: clever!

**Review by mjhenkes — APPROVED** [review]
