### PR TITLE
fix(angular): set webpack base so angular assets load

### LINKED ISSUE #23797: Cypress component tests not loading assets with Angular
### Current behavior

It will not load assets:

image

Even though the dev server is copying the assets:
Screenshot 2022-09-13 at 13 40 07

### Desired behavior

It should load assets from eg.:

http://localhost:8080/assets

### Test code to reproduce

image

https://github.com/lydemann/cypress-assets-bug

### Cypress Version

10.7.0

### Node version

16.14.2

### Operating System

12.3.1

### Debug Logs

_No response_

### Other

Assets are not loaded, eg. the image in the repo

### PR DESCRIPTION
**Pull request by jordanpowell88**
- Closes #23797

### User facing changelog
sets the webpack base so that angular assets get compiled and loaded with the correct path

### Additional details
image-loading-in-cypress

### PR Tasks

- [X] Have tests been added/updated?
- [X] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts [hunk 1]
```diff
@@ -48,7 +48,8 @@ export function makeDefaultWebpackConfig (
       new HtmlWebpackPlugin({
         template: indexHtmlFile,
         // Angular generates all of it's scripts with <script type="module">. Live-reloading breaks without this option.
-        ...(config.devServerConfig.framework === 'angular' ? { scriptLoading: 'module' } : {}),
+        // We need to manually set the base here to `/__cypres/src/` so that static assets load with our proxy
```
Comment (mike-plummer) [inline npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts]: Typo: `/__cypres/`

**Review by mike-plummer — APPROVED** [review]

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts (hunk 1 above)
Comment (jordanpowell88) [reply npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts]: Good catch @mike-plummer

**Review by ZachJW34 — APPROVED** [review]

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts [hunk 2]
```diff
@@ -48,7 +48,8 @@ export function makeDefaultWebpackConfig (
       new HtmlWebpackPlugin({
         template: indexHtmlFile,
         // Angular generates all of it's scripts with <script type="module">. Live-reloading breaks without this option.
-        ...(config.devServerConfig.framework === 'angular' ? { scriptLoading: 'module' } : {}),
+        // We need to manually set the base here to `/__cypress/src/` so that static assets load with our proxy
+        ...(config.devServerConfig.framework === 'angular' ? { scriptLoading: 'module', base: '/__cypress/src/' } : {}),
```
Comment (lydemann) [inline npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts:52]: Does this also work when loading assets from Javascript?
