### PR TITLE
fix: Refetch latest cloud data when opening cloud connect modals

### LINKED ISSUE #23538: Refetch orgs and projects on connection modal open
If a project is created in the Dashboard before the project connection modal is opened, then it is not shown in the list of existing projects to connect. Similarly, if the modal is used to create a new project, then the projectId is deleted, it is not possible to then reconnect that same project.

A user's organizations and projects should be refetched whenever that modal is opened, so that the most up-to-date orgs and projects are shown as options to connect.

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #23538 

### User facing changelog
* Fixes an issue where outdated organization and project information could be shown in dialogs to connect a project to the Cypress Dashboard.

### Additional details
* Adding a refetch when opening any of the Cloud Connect modals (Create/Select organization, Create/Select project) to reflect any org/project changes that have occurred outside the Cypress app since the user last logged in/opened the app
* Fixed an issue in the Select Project dialog that would continue to use old data in select menus after an updated `gql` prop was passed in

### Steps to test
This procedure involves creating/deleting cloud data. We point to Prod for cloud data by default now, if you would be more comfortable testing against Staging you can do so by launching like so `CYPRESS_INTERNAL_ENV=staging yarn dev`

1. Open a project that is not connected to the cloud (no `projectId` config entry) in the app, CT or E2E
2. Ensure you are logged in.
3. Open the dashboard in your browser (`dashboard.cypress.io` or `dashboard-staging.cypress.io` depending on how you launched). Make note of your organization memberships and what projects are in each org.
4. In the app, when mousing over the "Latest runs" and "Average duration" header tooltips you should get a "Connect project" action. Click to open the connect project modal, verify list of orgs and projects matches what is in the dashboard. Close the modal without taking any action.
5. In the dashboard, create a new project and name it something distinctive
6. In Cypress, re-open the Connect Project modal. Verify newly-created project is reflected in the options. Close the modal without taking any action
7. In the dashboard, create a new organization and name it something distinctive
8. In Cypress, re-open the Connect Project modal. Verify newly-created organization is reflected in the options.

**[Regression Test]**
9. Verify select menus within the modal update appropriately when selecting different organizations (projects list should change, previous project selection should be wiped out).
10. Select an org and a project and save selection using "Connect project" button. Verify correct project ID is saved into project config.

### How has the user experience changed?

https://user-images.githubusercontent.com/11482842/187937181-4e4daa5b-37a5-4198-a9a7-8c90ec6071d1.mov

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts [hunk 1]
```diff
@@ -644,9 +644,9 @@ export const mutation = mutationType({
       },
     })
 
-    t.field('refreshOrganizations', {
+    t.field('refreshCloudViewer', {
```
Comment (mike-plummer) [inline packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts:647]: Renaming this to make it clear this invalidates more than just the organizations data

**Review by astone123 — APPROVED** [review]
Works well for me 👍🏻

File: packages/app/src/runs/modals/CloudConnectModals.spec.tsx [hunk 2]
```diff
@@ -18,7 +19,16 @@ describe('<CloudConnectModals />', () => {
 
         result.cloudViewer = {
           ...CloudUserStubs.me,
-          organizations: noOrg ? null : CloudOrganizationConnectionStubs,
+          organizations: hasOrg ? cloneDeep(CloudOrganizationConnectionStubs) : null,
```
Comment (lmiller1990) [inline packages/app/src/runs/modals/CloudConnectModals.spec.tsx:22]: Why do we need to cloneDeep here?

File: packages/app/src/runs/modals/CloudConnectModals.spec.tsx [hunk 3]
```diff
@@ -29,10 +39,43 @@ describe('<CloudConnectModals />', () => {
...
+      cy.contains(defaultMessages.runs.connect.modal.createOrg.button).should('be.visible')
+
+      cy.percySnapshot()
+    })
+  })
+
+  context('has organizations', () => {
+    context('with no projects', () => {
+      beforeEach(() => {
+        mountDialog(true, false)
```
Comment (lmiller1990) [inline packages/app/src/runs/modals/CloudConnectModals.spec.tsx:57]: `mountDialog(true, false)` seems kind of hard to understand - I wonder if this should be an object of options?

File: packages/app/src/runs/modals/SelectCloudProjectModal.vue [hunk 4]
```diff
@@ -285,31 +285,41 @@ const isInternalServerError = ref(false)
...
-const pickedProject = ref<CloudProjectNodeFragment>()
+  return sortBy(options || [], 'name')
+})
+const newProject = ref(projectOptions.value.length === 0)
+const pickedProject = ref<typeof projectOptions.value[number]>()
 
-watchEffect(() => {
-  if (pickedOrganization.value?.projects?.nodes?.length === 1) {
-    pickedProject.value = pickedOrganization.value.projects.nodes[0]
+watch([projectOptions], () => {
```
Comment (lmiller1990) [inline packages/app/src/runs/modals/SelectCloudProjectModal.vue:316]: How come we changed to this syntax? I think `watch` + `immediate: true` is the same as `watchEffect`?

Also I think this is now actually doing something a little different - if you use `watch`, you need to get the new value from the callback - [docs](https://vuejs.org/guide/essentials/watchers.html#basic-example). Eg:

```js
watch(projectOptions, (newProjectOptions) => {
                       ^^^^^^^ this is the latest value
  // stuff
})
```

**Review by lmiller1990 — COMMENTED** [review]
Quick few comments, main query is around `watch` - I think the code change makes the behavior slightly different which might have been unintended?

File: packages/app/src/runs/modals/CloudConnectModals.spec.tsx (hunk 2 above)
Comment (mike-plummer) [reply packages/app/src/runs/modals/CloudConnectModals.spec.tsx:22]: The GQL stub isn't reset between tests since it's just a simple object import, since I'm mutating the data on lines 26-31 I didn't want my changes leaking into other tests

File: packages/app/src/runs/modals/SelectCloudProjectModal.vue (hunk 4 above)
Comment (mike-plummer) [reply packages/app/src/runs/modals/SelectCloudProjectModal.vue:316]: Good call. My refactor meandered through a state where I had an reference loop between two `watchEffect`s hence the change to this format, but has since changed further so I can switch back to `watchEffect`

**Review by ZachJW34 — APPROVED** [review]
Works great, LGTM!

File: packages/app/src/runs/modals/CloudConnectModals.spec.tsx (hunk 2 above)
Comment (mike-plummer) [reply packages/app/src/runs/modals/CloudConnectModals.spec.tsx:27]: @lmiller1990 Going to merge this PR so it doesn't sit too long, but let me know if you have an issue with this pattern or know of a better way to address it - happy to revisit this
