### PR TITLE
fix: edge cases during cy.type in number input

### LINKED ISSUE #5968: {enter} on input type=number leads to invalid input (3.8.0 regression)
### Current behavior: 

 when you  type a number in an number input and then type enter, the input becomes empty and the console logs an error:

```
cypress_runner.js:107262 The specified value "12\n" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
```

You can see that the `{enter}` adds `\n` to the input value.

### Desired behavior:

It should set the value without `\n` 

### Steps to reproduce: (app code and test code)

html:
```html
<input type="number" id="input" />
```

spec code:

```js
cy.get('#input')
  .type('2')
  .type('{enter}')
```

### Versions

Cypress 3.8.0
edit: Chrome 79 with cypress run

Possibly related to https://github.com/cypress-io/cypress/pull/5854

### LINKED ISSUE #5997: `.type()` does not type chars in number input beyond special chars (like `,`)
### Current behavior: 

Pre-conditions - in my text form "," sign not allowed to input

Input inside type() func: 

**1,99**

Output: 

**1**

### Desired behavior:

**199**

It worked in previous version of cypress correctly and problem I met in 3.8.0

### Steps to reproduce: (app code and test code)

Just try to type from tests some signs that couldn't be written.

### Versions

Cypress 3.8.0
OS: Mac Mojave
Browser: Chrome

### PR DESCRIPTION
**Pull request by kuceb**
- fix #5968
{enter} in input type=number
- fix #5997
allow non-number chars in number input

### User facing changelog
- bug fix: fixed regression in 3.8.0 during cy.type with non-number characters and {enter} special character.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
I confirmed this is working and fixes the failing cases in the issues. Tests cover these 2 cases. 👍

File: packages/driver/src/cy/keyboard.ts [hunk 1]
```diff
@@ -260,7 +260,11 @@ const shouldUpdateValue = (el: HTMLElement, key: KeyDetails, options) => {
 
       if (!(numberRe.test(potentialValue))) {
         debug('skipping inserting value since number input would be invalid', key.text, potentialValue)
-        options.prevVal = needsValue + key.text
+        if (key.text.match(/[-+eE\d\.]/)) {
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: this `regexp` should be hoisted to the top and given a variable name to help describe what it is

File: packages/driver/src/cy/keyboard.ts [hunk 2]
```diff
@@ -477,7 +481,9 @@ function _getEndIndex (str, substr) {
 // Simulated default actions for select few keys.
 const simulatedDefaultKeyMap: { [key: string]: SimulatedDefault } = {
   Enter: (el, key, options) => {
-    $selection.replaceSelectionContents(el, '\n')
+    if (!$elements.isInput(el)) {
+      $selection.replaceSelectionContents(el, '\n')
+    }
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: a description of why this is necessary would be helpful here.

File: packages/driver/src/cy/keyboard.ts (hunk 1 above)
Comment (brian-mann) [reply packages/driver/src/cy/keyboard.ts]: also a description would be helpful
