### PR TITLE
fix: can send binary data with cy.request.

### LINKED ISSUE #6178: cy.Request does not send binary data (blob)
Sending blob as body of a request sends empty content:

``` js
const body = new Blob([[1, 2, 3, 4]], { type: "application/octet-stream" });
cy.request(
  {
    body,
    method: "POST",
    url: "api/binaryBody",
    headers: {
      "Content-Type": "application/octet-stream",
    }
  })
  .then(response => {
    expect(response.status).to.equal(200);
  });
```

Results in following request:

```
The request we sent was:

Method: POST
URL: https://localhost:5001/api/binaryBody
Headers: {
  "Connection": "keep-alive",
  "Content-Type": "application/octet-stream",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-length": 2
}
Body: {}
```

### Expected behavior:

Binary data from the blob should be sent as the request body and the `content-length` header should be set correctly

### Versions

Cypress: 3.8.2
OS: Windows 10 v1809, 64-bit
Browser: Chrome 76.0.3809.132
Node.js: 12.13.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #6178

### User facing changelog

`cy.request` can now send blob data.

### Additional details
- Why was this change necessary? => Blob data was ignored because it cannot be serialized with `JSON.stringify`. 
- What is affected by this change? => N/A
- Any implementation details to explain? => Blob is encoded into base64 in the client and decoded and encoded to Buffer in the server and send it.

### How has the user experience changed?

N/A

### Possible Problem

`@cypress/request-promise` encodes `Buffer` into an object. Maybe this format might not be what users want. 

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by sainthkh** [comment]
waiting for fix in test-cypress-scaffold and test-binary-against-awesome-typescript-loader.

File: packages/driver/src/cy/commands/request.js [hunk 1]
```diff
@@ -277,7 +277,23 @@ module.exports = (Commands, Cypress, cy, state, config) => {
       // because we're handling timeouts ourselves
       cy.clearTimeout('http:request')
 
-      return Cypress.backend('http:request', requestOpts)
+      return Promise.try(() => {
+        // https://github.com/cypress-io/cypress/issues/6178
+        // Check if body is Blob.
+        // construct.name is added because the parent of the Blob is not the same Blob
+        // if it's generated from the test spec code.
+        if (requestOpts.body instanceof Blob || requestOpts?.body?.constructor.name === 'Blob') {
```
Comment (flotwig) [inline packages/driver/src/cy/commands/request.js:285]: What about `File` or `ArrayBuffer`? Do we only seek to support `Blob`?

The websocket between the driver and server uses socket.io, and if you check out socket.io's source code, it supports transmitting `ArrayBuffer`, views, `File`, and `Blob`: https://github.com/socketio/socket.io-parser/blob/af1b23ca85fb64a0d7a050abd0362c5f632ce429/lib/is-binary.ts#L25-L31

Since `socket.io` already supports the serialization, maybe we should not `JSON.stringify` it at all before passing it to the websocket, and instead we should fix `Cypress.backend` to trust `socket.io`'s serialization?

What do you think about all this?

**Comment by flotwig** [comment]
Oh, look what I found @sainthkh: https://github.com/cypress-io/cypress/issues/1647 Request to support uploading formdata/`File` here

File: packages/driver/src/cy/commands/request.js (hunk 1 above)
Comment (flotwig) [reply packages/driver/src/cy/commands/request.js:285]: Oh, look what I found @sainthkh: #1647 Request to support uploading formdata/File here

Comment (sainthkh) [reply packages/driver/src/cy/commands/request.js:285]: I read the code of `socket.io` and learned that the `stringify` process is done by `socket.io`, not Cypress. 

The user-given data is sent to server with `runner` below:

https://github.com/cypress-io/cypress/blob/1e7a3faa4c26bea5aea12be4f5eb023235c3b1a4/packages/runner/src/lib/event-manager.js#L367-L371

When you check the `args` above, `body` is still `Blob` object.

And the data passed to `socket.io` is passed to [`socket.io`'s `emit()`](https://github.com/socketio/socket.io/blob/master/lib/socket.ts#L191-L217) to [`packet()`](https://github.com/socketio/socket.io/blob/master/lib/socket.ts#L281-L288) to [`socket.io-client`'s `_packet()`](https://github.com/socketio/socket.io-client/blob/2edf0f308c8b969928124d02e81e21c456f736a7/lib/manager.ts#L672-L679), which calls the `encode()` of [`socket.io-parser`'s `encode()`](https://github.com/socketio/socket.io-parser/blob/af1b23ca85fb64a0d7a050abd0362c5f632ce429/lib/index.ts#L44-L57) below:

```js
  public encode(obj: Packet) {
    debug("encoding packet %j", obj);


    if (obj.type === PacketType.EVENT || obj.type === PacketType.ACK) {
      if (hasBinary(obj)) { // <= this line
        obj.type =
          obj.type === PacketType.EVENT
            ? PacketType.BINARY_EVENT
            : PacketType.BINARY_ACK;
        return this.encodeAsBinary(obj);
      }
    }
    return [this.encodeAsString(obj)];
  }
```

It calls `hasBinary()` and it calls the `isBinary` function you referenced above. And I checked that [`hasBinary`](https://github.com/socketio/socket.io-parser/blob/af1b23ca85fb64a0d7a050abd0362c5f632ce429/lib/is-binary.ts#L33-L66) ignores JavaScript objects that contain binary data as in our case. It only checks the entire data is binary or not. I'm not sure why they ignored this case, but I suspect it's because of the performance. As we all know, traversing tree is really expensive. 

As for our case, I guess we need to mimic the behavior of `encodeAsBinary()`. It might not be hard because we can reuse the functions in `socket.io-parser`.

Phew, this issue seems much much bigger than I first thought.

Comment (sainthkh) [reply packages/driver/src/cy/commands/request.js:285]: After server gets the data, I didn't do anything and it encoded it to string. To conserve it as binary, we need to set `encoding` to `null`. [Check this.](https://stackoverflow.com/questions/37703518/how-to-post-binary-data-in-request-using-request-library)

# TODO

- [ ] Fix test for `Blob`.
- [ ] Create tests for `ArrayBuffer`, `File`
- [ ] Send binary data to Cypress server.
- [ ] Send binary data to the user server.

Comment (flotwig) [reply packages/driver/src/cy/commands/request.js:285]: Wow, this is a lot more complicated than I thought. Great deep-dive.

If it makes more sense to split this into multiple PRs for Blob/File/formdata, just let me know, we can do that too.

File: packages/driver/src/cy/commands/request.js [hunk 2]
```diff
@@ -277,7 +277,23 @@ module.exports = (Commands, Cypress, cy, state, config) => {
...
+          return Cypress.Blob.blobToBase64String(requestOpts.body).then((str) => {
```
Comment (sainthkh) [inline packages/driver/src/cy/commands/request.js:286]: I first thought of writing code with `socket.io-parser` functions. But it seems to me that those functions are more of `private` functions than `public API`s. So, I decided to use the current code.

File: packages/driver/cypress/integration/commands/request_spec.js [hunk 3]
```diff
@@ -473,6 +473,34 @@ describe('src/cy/commands/request', () => {
...
+        )
+        .then((response) => {
+          expect(response.status).to.equal(200)
+
+          // When user-passed body to the Nodejs server is a Buffer,
+          // Nodejs doesn't provide any decoder in the response.
+          // So, we need to decode it ourselves.
+          const dec = new TextDecoder()
+
+          expect(dec.decode(response.body)).to.contain('1,2,3,4')
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/request_spec.js:499]: I thought adding this decoding part to Cypress server because `content-type: text/html` with `ArrayBuffer` body is a bit weird. But I also thought that it's how Express.js works and we need to respect that. 

I didn't experiment how other frameworks work.

File: packages/driver/src/cy/commands/request.js [hunk 4]
```diff
@@ -277,7 +277,23 @@ module.exports = (Commands, Cypress, cy, state, config) => {
...
+            requestOpts.body = {
+              isBinary: true,
+              base64: str,
+            }
+          })
+        }
```
Comment (sainthkh) [inline packages/driver/src/cy/commands/request.js:292]: `ArrayBuffer`, `File`, formdata will be appended here later.

File: packages/server/lib/request.js [hunk 5]
```diff
@@ -469,14 +470,6 @@ module.exports = function (options = {}) {
       return createRetryingRequestStream(opts)
     },
 
-    contentTypeIsJson (response) {
-      // TODO: use https://github.com/jshttp/type-is for this
```
Comment (sainthkh) [inline packages/server/lib/request.js:473]: This TODO has been fixed because I needed `typeis(response, ['text/*'])`. It has been removed in the last commit. I think it doesn't do any harm if it is left as fixed.

File: packages/server/package.json [hunk 6]
```diff
@@ -115,6 +115,7 @@
     "trash": "5.2.0",
     "tree-kill": "1.2.2",
     "ts-node": "8.5.4",
+    "type-is": "1.6.18",
```
Comment (sainthkh) [inline packages/server/package.json:118]: I checked `yarn.lock` and `type-is` existed. So, it doesn't increase the bundle size.

**Review by sainthkh — COMMENTED** [review]
I left some notes that show the reasons behind my decisions and are not appropriate for comments inside code.

File: packages/server/lib/request.js (hunk 5 above)
Comment (sainthkh) [reply packages/server/lib/request.js]: Rolled back because of unit test failure.

File: packages/server/package.json (hunk 6 above)
Comment (sainthkh) [reply packages/server/package.json]: Rolled back because of unit test failure.

File: packages/server/lib/request.js [hunk 7]
```diff
@@ -705,6 +705,16 @@ module.exports = function (options = {}) {
         delete options.body
       }
 
+      // https://github.com/cypress-io/cypress/issues/6178
+      // if body is a Blob
+      if (options?.body?.base64 && options?.body?.isBinary) {
```
Comment (flotwig) [inline packages/server/lib/request.js:710]:
```suggestion
      if (options.bodyIsBase64Encoded) {
```

File: packages/server/lib/request.js [hunk 8]
```diff
@@ -705,6 +705,16 @@ module.exports = function (options = {}) {
...
+        options.body = Buffer.from(options?.body.base64, 'base64')
```
Comment (flotwig) [inline packages/server/lib/request.js:711]: We either need to check that options.body is base64, or try/catch this, or both

File: packages/driver/src/cy/commands/request.js (hunk 2 above)
Comment (flotwig) [inline packages/driver/src/cy/commands/request.js:286]: Do you want to rewrite this so that `cy.request` is an async/await function? We are trying to modernize the codebase's Promise usage, and this looks like a prime opportunity.

File: packages/driver/src/cy/commands/request.js [hunk 9]
```diff
@@ -277,7 +277,23 @@ module.exports = (Commands, Cypress, cy, state, config) => {
...
+      return Promise.try(() => {
+        // https://github.com/cypress-io/cypress/issues/6178
+        // Check if body is Blob.
+        // construct.name is added because the parent of the Blob is not the same Blob
+        // if it's generated from the test spec code.
+        if (requestOpts.body instanceof Blob || requestOpts?.body?.constructor.name === 'Blob') {
+          return Cypress.Blob.blobToBase64String(requestOpts.body).then((str) => {
+            requestOpts.body = {
+              isBinary: true,
+              base64: str,
```
Comment (flotwig) [inline packages/driver/src/cy/commands/request.js:289]: Instead of using `hasBinary` and `base64` to signal that you're sending the body as base64, let's just base64 the body and signal out-of-band in request opts, so there is never a risk of any collisions. Plus it makes the code more straightforward imo.

Something like:

```js
requestOpts.bodyIsBase64Encoded = true
requestOpts.body = str
```

**Review by flotwig — CHANGES_REQUESTED** [review]
Looks good, some small changes recommended

File: packages/driver/src/cy/commands/request.js (hunk 2 above)
Comment (sainthkh) [reply packages/driver/src/cy/commands/request.js:288]: I checked the code and concluded that it cannot be done in the current situation because of [`Bluebird.timeout()`](http://bluebirdjs.com/docs/api/timeout.html). Timeout cannot be handled with async/await because they wait forever for promise resolving/rejecting. 

To refactor, we might need to create a wrapper function that handles timeout.

Example:

```js
const wrapper = async (options) => {
  return Promise.race([
    new Promise(), // handles command logic
    new Promise(), // handles timeout. Throws `TimeoutError`.
  ])
}
```

**Review by flotwig — APPROVED** [review]
nice work!
