### PR TITLE
fix firefox video record crash when too few video frames recevied

### LINKED ISSUE #6408: 'We failed to record the video' error in Firefox when running 2 spec files
### Current behavior:

When running `cypress run --browser firefox` over 2 specs files, the below warning is printed. This warning does **not** print when only running 1 spec file.

(Running in `develop` gives a slightly better stack trace, so I've pasted the warning from `develop` branch)

#### Error

Screen Shot 2020-02-14 at 1 07 07 PM

```
Warning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/Users/jennifer/Dev/cypress/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

Warning: We failed processing this video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/Users/jennifer/Dev/cypress/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
From previous event:
    at deferredPromise (/Users/jennifer/Dev/cypress/packages/server/lib/video_capture.js:21:19)
    at Object.start (/Users/jennifer/Dev/cypress/packages/server/lib/video_capture.js:65:19)
    at /Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:669:6
    at /Users/jennifer/Dev/cypress/packages/server/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/Users/jennifer/Dev/cypress/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:166:5)
From previous event:
    at Object.createVideoRecording (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:667:4)
    at Object.<anonymous> (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:724:15)
From previous event:
    at Object.runSpec (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1277:17)
    at runEachSpec (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1220:19)
From previous event:
    at serial (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:372:20)
    at iterateThroughSpecs (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:433:10)
    at Object.runSpecs (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1227:12)
    at runAllSpecs (/Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1399:25)
    at /Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1446:18
From previous event:
    at /Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1384:10
From previous event:
    at /Users/jennifer/Dev/cypress/packages/server/lib/modes/run.js:1358:8
    at processImmediate (internal/timers.js:439:21)
```

#### Debug logs around the warning:

```
  cypress:server:browsers killing browser process +2s
info @benmalka/foxdriver:Client connection closed by server
  cypress:server:preprocessor removeFile /Users/jennifer/Dev/cypress-transform-test/cypress/integration/spec2.js +1s
  cypress:server:preprocessor base emitter plugin close event +0ms
  cypress:server:preprocessor base emitter native close event +0ms
  cypress:browserify close: /Users/jennifer/Dev/cypress-transform-test/cypress/integration/spec2.js +1s
  cypress:browserify close: /Users/jennifer/Dev/cypress-transform-test/cypress/integration/spec2.js +0ms
  cypress:server:browsers browser process killed +48ms
  cypress:server:run ending the video recording { name: '/Users/jennifer/Dev/cypress-transform-test/cypress/videos/spec2.js.mp4', videoCompression: 32, shouldUploadVideo: true } +49ms
  cypress:server:video capture stderr log { message: 'pipe:0: Function not implemented' } +5s
  cypress:server:video capture stderr log { message: '' } +2ms
  cypress:server:video capture errored: { error: 'ffmpeg exited with code 1: pipe:0: Function not implemented\n', stdout: '', stderr: 'ffmpeg version N-92718-g092cb17983-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers\n' + '  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)\n' + '  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavWarning: We failed to record the video.

This error will not alter the exit code.

Error: ffmpeg exited with code 1: pipe:0: Function not implemented

    at ChildProcess.<anonymous> (/Users/jennifer/Dev/cypress/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

pack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n' + '  libavutil      56. 24.101 / 56. 24.101\n' + '  libavcodec     58. 42.102 / 58. 42.102\n' + '  libavformat    58. 24.101 / 58. 24.101\n' + '  libavdevice    58.  6.101 / 58.  6.101\n' + '  libavfilter     7. 46.101 /  7. 46.101\n' + '  libswscale      5.  4.100 /  5.  4.100\n' + '  libswresample   3.  4.100 /  3.  4.100\n' + '  libpostproc    55.  4.100 / 55.  4.100\n' + 'pipe:0: Function not implemented\n' } +2ms
```

### Desired behavior:

Record video in Firefox for multiple spec files. 

### Test code to reproduce

`spec.js`

```js
it('test', () => {
  expect(true).to.be.true
})
```

`spec2.js`

```js
it('test', () => {
  expect(true).to.be.true
})
```

### Versions

Cypress 4.0.0 and 4.0.1
Firefox 72
MacOS Mohave

### PR DESCRIPTION
**Pull request by kuceb**
- Closes #6408

### User facing changelog

- Firefox video recording will no longer crash when running very short spec files.

### Additional details

- fix bug causing video recording to crash in firfox when fewer than 2 frames/chunks received - this was causing lots of flake for our e2e tests
- likely does not affect many users since it only occurs with very very short length specs

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by flotwig — DISMISSED** [review]
I'm a fan of reducing flake, but is this covering up a real issue with Firefox? Have you been able to see what is causing the video recording to fail so frequently in this spec?

**Comment by Bkucera** [comment]
ugh, there's another test with the same problem, going to look more into this

**Review by jennifer-shehane — DISMISSED** [review]
So this is an actual bug in Cypress that is causing this 'flake'. I'm not sure I agree with just turning off video in order to ignore the bug that is happening to users and should be fixed. 

https://github.com/cypress-io/cypress/issues/6408

Previously failed test: https://circleci.com/gh/cypress-io/cypress/310577

(We've discussed in product team potentially bringing this and other Firefox issues in for an upcoming sprint)

**Comment by Bkucera** [comment]
@jennifer-shehane yes, I am looking more into this

File: packages/server/lib/modes/run.js [hunk 1]
```diff
@@ -1120,27 +1118,31 @@ module.exports = {
 
       obj.shouldUploadVideo = suv
 
-      debug('attempting to close the browser')
+      let videoCaptureFailed = false
+
+      if (endVideoCapture) {
+        await endVideoCapture()
+        .tapCatch(() => videoCaptureFailed = true)
+        .catch(warnVideoRecordingFailed)
```
Comment (Bkucera) [inline packages/server/lib/modes/run.js:1126]: I prefer syntax of `.catch()` to `try {} catch {}`

Comment (Bkucera) [reply packages/server/lib/modes/run.js:1126]: changed the logic to be:
- stop video recording
- close browser
- video compression

previously it was:
- close browser
- stop video recording + video compress

File: packages/server/test/unit/modes/run_spec.js [hunk 2]
```diff
@@ -522,6 +495,59 @@ describe('lib/modes/run', () => {
...
+        compressedVideoName: 'foo-compressed.mp4',
+        videoCompression: 32,
+        videoUploadOnPasses: true,
+        gui: false,
+        endVideoCapture,
+      })
+
+      expect(errors.warning).to.be.calledWith('VIDEO_POST_PROCESSING_FAILED')
+
+      expect(videoCapture.process).not.to.be.called
```
Comment (flotwig) [inline packages/server/test/unit/modes/run_spec.js:522]: to check my understanding: previously, this error would crash the process, now it's dressed up in a warning?

so e2e tests *can* still fail, but only in these 2 (more rare than now) conditions:

1. `WAIT_FOR_MORE_FRAMES_TIMEOUT` is exceeded and <2 frames are received; or
2. `ffmpeg` gives an error *not* caused by receiving 0 frames

is that all correct?

File: packages/server/lib/modes/run.js [hunk 3]
```diff
@@ -806,101 +812,93 @@ module.exports = {
...
-    .catch((err) => {
-      // log that post processing was attempted
-      // but failed and dont let this change the run exit code
-      errors.warning('VIDEO_POST_PROCESSING_FAILED', err.stack)
-    })
+        console.log('    Compression progress: ', chalk.cyan(percentage))
+      }
+    }
+
+    // bar.tickTotal(float)
```
Comment (flotwig) [inline packages/server/lib/modes/run.js:899]:
```suggestion
```

File: packages/server/lib/modes/run.js [hunk 4]
```diff
@@ -1120,27 +1118,31 @@ module.exports = {
...
-      .then(() => {
-        if (endVideoCapture) {
-          return this.postProcessRecording(
-            endVideoCapture,
-            videoName,
-            compressedVideoName,
-            videoCompression,
-            suv,
-          ).then(finish)
-          // TODO: add a catch here
```
Comment (flotwig) [inline packages/server/lib/modes/run.js:1139]: ah, `TODO` comments, the origin of all the world's best bugs

nice

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/server/test/unit/modes/run_spec.js (hunk 2 above)
Comment (Bkucera) [reply packages/server/test/unit/modes/run_spec.js:522]: the error was always a warning, but it would cause our tests to fail because the stdout didnt match when we printed the warning message.

yes those scenarios would cause stdout to show the warning and e2e tests to fail

File: packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html [hunk 5]
```diff
@@ -1,5 +1,14 @@
...
-  chrome.devtools.inspectedWindow.eval('window.theExtensionLoaded = true')
-})
+<script>
+  function addProperty () {
+    chrome.devtools.inspectedWindow.onResourceAdded.addListener(() => {
+      chrome.devtools.inspectedWindow.eval('window.theExtensionLoaded = true')
+    })
+  }
+
+  // sometimes chrome.devtools is undefined, most likely bug in chromium :|
```
Comment (flotwig) [inline packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html:8]: the `if` checks for `inspectedWindow`, so i'm guessing you meant this?

```suggestion
  // sometimes chrome.devtools.inspectedWindow is undefined, most likely bug in chromium :|
```

is there a bug report that you can link to here? or is it just a race condition that the inspected page hasn't loaded yet and so `inspectedWindow` is undefined?

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html (hunk 5 above)
Comment (Bkucera) [reply packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html:8]: whoops

Comment (Bkucera) [reply packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html:8]: no bug report, just noticed it failing in CI: https://circleci.com/gh/cypress-io/cypress/314207?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Review by flotwig — DISMISSED** [review]

File: packages/driver/test/cypress/integration/e2e/focus_blur_spec.js [hunk 6]
```diff
@@ -513,27 +513,22 @@ describe('polyfill programmatic blur events', () => {
...
-          Cypress.log({ message: 'reset mock', state: 'passed' })
-          setImmediate(() => v.reset())
-        })
-      })
 
       cy.$$('input:first')[0].focus()
+      cy.document().then((doc) => {
+        // we need to wait for initial selectionchange event on input:first
+        // which sets up the state for the tests
+        // NOTE: initial selectionchange event does not fire in firefox
```
[the remark this answers is not in the document]
Comment (Bkucera) [reply packages/driver/test/cypress/integration/e2e/focus_blur_spec.js:522]: I don't think so, I ran the test 100 times locally with no failure - before this it would fail 20/100 times

**Review by flotwig — APPROVED** [review]
