### PR TITLE
dont send focus events to hidden focusable elements

### LINKED ISSUE #4898: onFocus event incorrectly fires on a hidden element starting on v3.3.2
### Current behavior:
Since the merge of https://github.com/cypress-io/cypress/pull/2982 in v3.3.2, the hidden search bar on the site https://www.unibet.com/betting/sports/home is always opened on cy.visit() of the page
Screenshot 2019-08-01 at 3 06 41 PM

This does not happen when the site is visited manually without Cypress

### Desired behavior:

The search bar remains hidden, same as if the page is visited manually.

### Steps to reproduce: (app code and test code)

1. Navigate to the page https://www.unibet.com/betting/sports/home with cy.visit()

### Versions

Issue started with Cypress 3.3.2

### PR DESCRIPTION
**Pull request by kuceb**
- fix #4898

**a few notes**:
- the issue here was that calling `.focus` on a focusable element will not send events if the element is `display:none` or `visibility:hidden` (or inherited from ancestor) 
- don't use the same visibility algo as `:visible` since focusing an input of 0x0 size or `opacity:0` will still send focus events
- `display:none` needs to be checked via walking up the parent nodes, while `visibility:none` is inherited and can be checked with `getComputedStype` (or `$.css`)

### tasks
- [x] [feedback] add links to w3c, rename method to `W3CFocusable` for clarity

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cy/focused.coffee [hunk 1]
```diff
@@ -146,7 +147,11 @@ create = (state) ->
     ## is always in focus
     $focused = getFocused()
 
-    if $elements.isFocusable($dom.wrap(el)) && (!$focused || $focused[0] isnt el)
+    if (
+      $elements.isFocusable($dom.wrap(el)) &&
+      (!$focused || $focused[0] isnt el) &&
+      !($visibility.parentHasDisplayNone($dom.wrap(el)) || $dom.wrap(el).css('visibility') is 'hidden')
```
Comment (Bkucera) [inline packages/driver/src/cy/focused.coffee]: hopefully this is the most optimal order of conditionals

Comment (brian-mann) [reply packages/driver/src/cy/focused.coffee]: Can we extract this logic into a function that clearly expresses all the things that these checks do? It's fine if its a looooong name. Otherwise this is extremely dense. I'd accept comments as well but perhaps we can come up with a good name.

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/focused.coffee (hunk 1 above)
Comment (mayfieldiv) [reply packages/driver/src/cy/focused.coffee]:
```suggestion
      !$visibility.parentHasDisplayNone($dom.wrap(el)) &&
      $dom.wrap(el).css('visibility') isnt 'hidden'
```

File: packages/driver/src/cy/focused.coffee [hunk 2]
```diff
@@ -146,7 +147,11 @@ create = (state) ->
     ## is always in focus
     $focused = getFocused()
 
-    if $elements.isFocusable($dom.wrap(el)) && (!$focused || $focused[0] isnt el)
+    if (
+      $elements.isFocusable($dom.wrap(el)) &&
+      (!$focused || $focused[0] isnt el) &&
```
Comment (mayfieldiv) [inline packages/driver/src/cy/focused.coffee]:
```suggestion
      $focused?[0] isnt el &&
```

**Review by jennifer-shehane — DISMISSED** [review]

File: packages/driver/src/dom/elements.js [hunk 3]
```diff
@@ -387,6 +390,10 @@ const isFocusable = ($el) => {
   })
 }
 
+const isFocusableAndNotHidden = (el) => {
```
Comment (brian-mann) [inline packages/driver/src/dom/elements.js]: We are overloading the term `hidden` because hidden has special semantic meaning to Cypress and our own algorithm.

This code is attempting to match the **w3c definition** of hidden, which is completely unclear and opaque. 

This code not only needs comments indicating this distinction, but it could also use either the w3c algorithm dropped in as a comment - or instead, a link to the w3c definition. Ideally, both

File: packages/driver/test/cypress/integration/e2e/focus_blur_spec.js [hunk 4]
```diff
@@ -679,4 +679,58 @@ describe('intercept blur methods correctly', () => {
     })
 
   })
+
+  it('does not send focus events for focusable elements that are hidden', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/e2e/focus_blur_spec.js]: annotate that this is the `w3c defined hidden` algorithm

File: packages/driver/test/cypress/integration/e2e/focus_blur_spec.js [hunk 5]
```diff
@@ -679,4 +679,58 @@ describe('intercept blur methods correctly', () => {
...
+      cy.get('no-focus-1').should('not.be.visible')
+      cy.get('no-focus-2').should('not.be.visible')
+      cy.get('no-focus-3').should('not.be.visible')
+      cy.get('no-focus-4').should('not.be.visible')
+
+    })
+
+  })
+
+  it('does send focus events for focusable elements that are 0x0 size', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/e2e/focus_blur_spec.js]: annotate that this is the `w3c defined hidden` algorithm

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/driver/src/dom/elements.js (hunk 3 above)
Comment (Bkucera) [reply packages/driver/src/dom/elements.js]: ah, the correct term is `inert` https://html.spec.whatwg.org/multipage/interaction.html#focusable-area

**Review by brian-mann — APPROVED** [review]
