### PR TITLE
Check backface visibility when the parents of the target element has css style transform-style: preserve-3d.

### LINKED ISSUE #5682: backface-visibility: hidden with transform-style: preserve-3d fails the "is.visible" test
### Current behavior:
Currently an element with `backface-visibility: hidden; transform: rotateY(180deg);` that is inside a parent with `transform-style: preserve-3d; transform: rotateY(180deg)` will fail the `is.visible` assertion

The same problem mentioned in #2985 was marked as fixed by https://github.com/cypress-io/cypress/pull/5591 i only think the case where the parent has the css property `transform-style: preserve-3d;` was forgotten

### Desired behavior:
it should not fail the `is.visible` assertion

### Steps to reproduce: (app code and test code)

**app code**
https://codepen.io/loekup/pen/rNNZqZW

**test code**
```js
describe('backface-visibility: hidden; test', function () {
    it('should flip and validate the visibility of the card faces', function () {
        cy.visit('index.html')
        cy.get('.front').should('be.visible');
        cy.get('.back').should('not.be.visible');
        cy.get('.container').click();
        cy.get('.front').should('not.be.visible');
        cy.get('.back').should('be.visible');
    });
});
```

### Versions
3.6.1.

### LINKED ISSUE #6093: width/height 0 and transform + overflow hidden
### Current behavior:

When an element has width or height 0px with non-`none` transform and overflow `hidden`, it is not visible. But `isHidden()` cannot detect it. 

```html
<!-- Example -->
<div style="height: 0px; transform: translate(1, 2)"><p>Visible</p></div>
<div style="height: 0px; transform: translate(1, 2); overflow: hidden"><p>Invisible</p></div>
```

It is found with cypress-example-piechopper in https://circleci.com/gh/cypress-io/cypress-test-example-repos/71863. 

### Desired behavior:

`isHidden()` should detect it. 

### Steps to reproduce: (app code and test code)

1. Download https://github.com/cypress-io/cypress-example-piechopper.
2. Change cypress to dev version. 
3. Run app_spec.js 
4. "displays hamburger menu" fails.

### Versions

After #6000 is merged.

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #5682
- Closes #6093

### User facing changelog

* Checks backface visibility when the parents of the target element has css style `transform-style: preserve-3d`.
* When width/height is 0px and overflow is hidden, it is invisible even if `transform` is not `none`. -> #6000 couldn't detect this case and it is fixed. 

#### Why was this change necessary?

* In #5591, it covered only when every element has `transform-style: flat`. When there is an element with `transform-style: preserve-3d`. Backface visibility didn't work properly. 
* #6000 missed a case where `transform` and `overflow` are together. 

#### What is affected by this change?

N/A

#### Any implementation details to explain?

* #5591: This changes `elIsHiddenByTransform` and `elIsBackface` together. 
* #6093: This changes `elHasNoEffectiveWidthOrHeight`

### How has the user experience changed?

* The test in the issue #5682 passes.
* Failed test in https://github.com/cypress-io/cypress-example-piechopper passes.

### Backface Visibility Detection cannot be perfect when there is an element with `perserve-3d`.

After some research, I realized that the behaviors of descendant elements are inconsistent from browser to browser. 

And it's a bit unpredictable in the same browsers. 

For example, when you hide `preserve-3d` descendants with flat element like below:

```html
<div class="grandgrandparent" style="backface-visibility: hidden; transform: rotateX(180deg);">
  Grandgrandparent rotateX(180deg)
  <div class="grandparent" style="transform-style: preserve-3d; transform: rotateX(30deg)">
    Grandparent rotateX(30deg)
    <div class="parent" style="transform-style: preserve-3d; transform: rotateX(30deg)">
      Parent rotateX(30deg)
      <div id="a3-1" class="target" style="backface-visibility: hidden;">No transform</div>
    </div>
  </div>
</div>
```

Chrome:
Screenshot from 2019-12-11 16-30-04

Firefox:
Screenshot from 2019-12-11 16-30-34

And there are `flat elements between `preserve-3d` and `hidden` elements like below: 

```html
<h4>Grandgrandparent Flipped + Grandparent no transform + Parent no transform with hidden + Child Indentity</h4>
<div class="grandgrandparent" style="transform-style: preserve-3d; transform: rotateX(180deg)">
  Grandparent rotateX(180deg)
  <div class="grandparent">
    Grandparent
    <div class="parent" style="backface-visibility: hidden;">
      Parent no transform
      <div id="a2-2-4" class="target" style="transform: rotateX(0deg)">Target</div>
    </div>
  </div>
</div>

<h4>Grandgrandparent Flipped + Grandparent Identity + Parent no transform with hidden + Child Indentity</h4>
<div class="grandgrandparent" style="transform-style: preserve-3d; transform: rotateX(180deg)">
  Grandparent rotateX(180deg)
  <div class="grandparent" style="transform: rotateX(0deg)">
    Grandparent
    <div class="parent" style="backface-visibility: hidden;">
      Parent no transform
      <div id="a2-2-4" class="target" style="transform: rotateX(0deg)">Target</div>
    </div>
  </div>
</div>
```

Chrome:
Screenshot from 2019-12-11 16-35-34

Firefox: 
Screenshot from 2019-12-11 16-35-36

So, this PR focuses only on 2 things:

1. When the target element has direct ancestor(s) with 'preserve-3d`, then it only checks those `preserve-3d` ancestors and ignore others.
2. When the target element has a parent element with `flat`. It goes up and checks and ignores `preserve-3d` elements. 

When some element goes out of this scope, it returns that it's not a backface. And this decision can be false. 

I guess this difference between browsers happened because the transform-related specs are now in draft stage.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
  - [ ] We might need to document the limits of backface visibility I described above. 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/dom/visibility.js [hunk 1]
```diff
@@ -123,52 +119,196 @@ const elHasVisibilityHidden = ($el) => {
   return $el.css('visibility') === 'hidden'
 }
 
-const numberRegex = /-?[0-9]+(?:\.[0-9]+)?/g
-// This is a simplified version of backface culling.
+const elIsHiddenByTransform = ($el) => {
```
Comment (chrisbreiding) [inline packages/driver/src/dom/visibility.js]: Let's rename this function to fit its new behavior better. It used to return a boolean, but now it returns a string, so the `IsHidden` part doesn't really work anymore.

File: packages/driver/src/dom/visibility.js [hunk 2]
```diff
@@ -123,52 +119,196 @@ const elHasVisibilityHidden = ($el) => {
...
+      normal = findNormal(list[i].transform, normal)
+    }
+
+    return normal
   }
 
-  const m3d = transform.substring(8).match(numberRegex)
-  const defaultNormal = [0, 0, -1]
-  const elNormal = findNormal(m3d)
+  const skipToNextFlat = () => {
```
Comment (chrisbreiding) [inline packages/driver/src/dom/visibility.js]: This file is starting to get really long. I think it would be good to extract some or most of these lower-level functions into a separate file or perhaps multiple files that are specific to transforms, backface, etc. Then we can keep this file's abstractions at a higher level and focused on the concept of visibility.

**Comment by jennifer-shehane** [comment]
@sainthkh A bit of conflict since I merged in your other PR

**Comment by sainthkh** [comment]
Fixed conflicts and refactored.
