### PR TITLE
fix: `times` option of `cy.intercept` doesn't work with `req.reply`

### LINKED ISSUE #17139: `times` option of `cy.intercept` doesn't work with `req.reply`
### Current behavior

I've written the code below when fixing #16821.

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="/node_modules/jquery/dist/jquery.js"></script>
  </head>
  <body>
    <button id="request">request</button>
    <div id="result"></div>
    <script type="text/javascript">
      $(function(){
        $("button#request").click(function(){
          $.ajax({
            method: "POST",
            url: "/post-only",
            data: JSON.stringify({client: 'data'})
          })
          .then((data) => {
            $('#result').text(data)
          })
        })
      })
    </script>
  </body>
</html>
```

```js
it('works with reply', () => {
  cy.intercept({
    method: 'POST',
    times: 1,
    url: '/post-only',
  },
  (req) => {
    req.reply('stubbed data')
  }).as('interceptor')

  cy.visit('fixtures/request.html')

  cy.get('#request').click()
  cy.get('#result').should('contain', 'stubbed data')

  cy.get('#request').click()
  cy.get('#result').should('contain', 'client') // Fail
})
```

But it failed because our `times` counter only works with `before:request` event. But `reply` doesn't fire it and it only fires `response`-related ones. 

### Desired behavior

The test should pass.

### Test code to reproduce

See above.

### Versions

Current Cypress 7.6.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #17139

### User facing changelog

`times` option of `cy.intercept` works with `req.reply`

### Additional details
- Why was this change necessary? => `times` option of `cy.intercept` doesn't work with `req.reply`. It's not an expected behavior.
- What is affected by this change? => N/A
- Any implementation details to explain? => I've left a long comment about the implementation decision in the code.

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -2184,6 +2184,61 @@ describe('network stubbing', { retries: 2 }, function () {
...
+
+            cy.get('#request').click()
+            cy.get('#result').should('contain', 'foo stubbed data 1')
+
+            cy.get('#request').click()
+            cy.get('#result').should('contain', 'nothing stubbed data 2')
+
+            cy.get('#request').click()
+            cy.get('#result').should('contain', 'client') // Fail
+          })
```
Comment (flotwig) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:2241]: @sainthkh I added this test while checking out the fix, I believe it should pass, but it is failing. This should pass though, unless I'm missing something obvious, can you check it out?

File: packages/net-stubbing/lib/server/intercepted-request.ts [hunk 2]
```diff
@@ -184,7 +184,31 @@ export class InterceptedRequest {
...
+          // from driver/src/cy/net-stubbing/events/before-requests.ts
+          // to sendStaticResponse at util.ts
+          // to middleware/request.ts
+          // to middleware/response.ts
+          // to here.
+          //
+          // This is a really ugly solution.
+          // But `cypressInternalResReplyCall` is necessary below because of the 3 reasons.
+          // 1. res.reply() call inside responseHandler inside cy.intercept()
+          // doesn't trigger `before:request` event.
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/intercepted-request.ts:200]:
```suggestion
          // 1. req.reply() call inside responseHandler inside cy.intercept()
          // doesn't trigger `before:request` event.
```

also, what does this mean? `before:request` is what causes the request handler to be run, so this is not quite right

File: packages/net-stubbing/lib/server/intercepted-request.ts [hunk 3]
```diff
@@ -184,7 +184,31 @@ export class InterceptedRequest {
...
+          // 2. We cannot simply add `before:response` below
+          // because it can cause duplicated counting for the same request
+          // (one for `before:request` and one more for `before:response`)
+          // 3. Blocking `before:response` when `before:request` is called doesn't work
+          // because there are multiple `before:response` events for the same request
+          // when you register several intercepts for a single url.
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/intercepted-request.ts:206]: Can you add test cases for these in addition to/instead of inlining it as a comment? I discovered an issue with this fix while trying to write a test for (3).

File: packages/net-stubbing/lib/server/intercepted-request.ts [hunk 4]
```diff
@@ -184,7 +184,31 @@ export class InterceptedRequest {
...
+          // https://github.com/cypress-io/cypress/issues/17139
+          // This `cypressInternalResReplyCall` came
+          // from driver/src/cy/net-stubbing/events/before-requests.ts
+          // to sendStaticResponse at util.ts
+          // to middleware/request.ts
+          // to middleware/response.ts
+          // to here.
+          //
+          // This is a really ugly solution.
+          // But `cypressInternalResReplyCall` is necessary below because of the 3 reasons.
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/intercepted-request.ts:198]: 😁

Would it be easier to fix this bug by updating how `req.reply`/`res.send` are handled in the driver code? Currently, calls to `sendStaticResponse` dispatch a single `send:static:response` event:

https://github.com/cypress-io/cypress/blob/636aae03b0b504635d2ccb013cbc7ae9b2ce735e/packages/driver/src/cy/net-stubbing/events/before-request.ts#L277-L277

https://github.com/cypress-io/cypress/blob/636aae03b0b504635d2ccb013cbc7ae9b2ce735e/packages/driver/src/cy/net-stubbing/events/response.ts#L80-L80

https://github.com/cypress-io/cypress/blob/636aae03b0b504635d2ccb013cbc7ae9b2ce735e/packages/driver/src/cy/net-stubbing/events/index.ts#L56-L61

But... it seems like this whole bug that this PR fixes, is being caused by `send:static:response` not ultimately resolving the Promise in `handleSubscriptions`:

https://github.com/cypress-io/cypress/blob/636aae03b0b504635d2ccb013cbc7ae9b2ce735e/packages/net-stubbing/lib/server/intercepted-request.ts#L164-L166

So maybe a more elegant fix would be to get rid of `send:static:response` and update `event:handler:resolved` to add a `staticResponse` field. What do you think @sainthkh ?

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts (hunk 1 above)
Comment (sainthkh) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:2241]: I also met the case that the last assertion failed, but in most cases, the test failed [with the second assertion, `foo stubbed data 1`. ](https://app.circleci.com/pipelines/github/cypress-io/cypress/22577/workflows/77244acf-f120-47e8-b2b6-5ca08e4eba95/jobs/829175)

It was happening because the second intercept is counted twice with `before:request` and `response` event. 

I learned that the solution in this PR doesn't work when there are 2+ `cy.intercept`s. So, I should drop this route and trying to fix it with your suggestion below.

File: packages/net-stubbing/lib/server/intercepted-request.ts (hunk 4 above)
Comment (sainthkh) [reply packages/net-stubbing/lib/server/intercepted-request.ts:198]: I tried other solutions like creating a record that tracks request ID and route ID. But it doesn't work, either. 

I'll try yours tomorrow.

**Comment by sainthkh** [comment]
After some research, I realized that `before:request` event is always fired for every request and [handleSubscription](https://github.com/cypress-io/cypress/blob/bc4df1e96221406f8908851692af9da9c1bf792f/packages/net-stubbing/lib/server/intercepted-request.ts#L142) determines if it should be sent to the client. It is the better place to count the route calls. 

I solved the problem by moving the code inside `handleSubscription`.

File: packages/net-stubbing/lib/server/intercepted-request.ts [hunk 5]
```diff
@@ -153,6 +153,18 @@ export class InterceptedRequest {
...
+        if (eventName === 'before:request') {
+          const route = this.matchingRoutes.find(({ id }) => id === subscription.routeId) as BackendRoute
+
+          route.matches++
+
+          if (route.routeMatcher.times && route.matches >= route.routeMatcher.times) {
+            route.disabled = true
+          }
+        }
+
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/intercepted-request.ts:167]: heh, nice. i like this a lot more :smile:

**Review by flotwig — APPROVED** [review]
