### PR TITLE
fix: Add flag to delay update in chrome

### LINKED ISSUE #16693: Chrome update warning blocks hover tests
### Current behavior

We use the official docker image https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node14.16.0-chrome89-ff86 and our builds that checked hover suddenly stopped working.

We build a lot of images and found that the issue lied in few specific chrome versions.

I connected using X11 and found that chrome sometimes displays an update message which means the `.trigger('mouseover')` does not work correctly.

image

```
Can't update Chrome
Chrome couldn't update to the latest version, so you're missing out on new features and security fixes.
```

### Desired behavior
Chrome auto update should be disabled or dismissed.

### Test code to reproduce

~I'll create one and update the ticket.~

No longer required.

### Versions

| Image | Chrome | Base | Result |
|-------|--------|------|--------|
|cypress/browsers:node12.18.3-chrome87-ff82|87.0.4280.66|12.18.3 |:white_check_mark:|
|custom|87.0.4280.66|14.16.0|:white_check_mark:|
|custom|87.0.4280.88|14.16.0|:white_check_mark:|
|custom|88.0.4324.96|14.16.0|:x:|
|custom|88.0.4324.146|14.16.0|:x:|
|custom|88.0.4324.150|14.16.0|:x:|
|custom|88.0.4324.182|14.16.0|:x:|
|cypress/browsers:node14.16.0-chrome89-ff86|89.0.4389.72  |14.16.0|:x:|
|custom|89.0.4389.82|14.16.0|:white_check_mark:|
|custom|89.0.4389.90|14.16.0|:white_check_mark:|
|custom|89.0.4389.114|14.16.0|:white_check_mark:|
|custom|89.0.4389.128|14.16.0|:white_check_mark:|
|custom|90.0.4430.72|14.16.0|:white_check_mark:|
|custom|90.0.4430.85|14.16.0|:white_check_mark:|
|custom|90.0.4430.93|14.16.0|:white_check_mark:|
|cypress/browsers:node14.16.0-chrome90-ff88|90.0.4430.212|14.16.0|:white_check_mark:|

`cypress@7.4.0`

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #16693 

### User Facing Changelog

Cypress now passes a flag to Chrome to prevent update notifications in some cases.

### Additional Details

- There's [some discussion](https://stackoverflow.com/questions/58993181/disable-chromium-can-not-update-chromium-window-notification) on the web that in certain cases the `--disable-component-update` doesn't disable updating.
- I actually had a hard time testing this flag because you'd have to simulate Chrome needing an update, auto-updating, and also failing the update for some reason. The user confirmed it fixed their issue: https://github.com/cypress-io/cypress/issues/16693#issuecomment-848944961
- Chrome notes on this flag: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/upgrade_detector/upgrade_detector_impl.cc;l=420;drc=9fcc9d7b2915b6192ee6810eec54c50deb6313c6
	>// The outdated simulation can work without a value, which means outdated
    >// now, or with a value that must be a well formed date/time string that
    >// overrides the build date.

### CODE REVIEW

File: packages/server/lib/browsers/chrome.ts [hunk 1]
```diff
@@ -92,6 +92,9 @@ const DEFAULT_ARGS = [
   '--safebrowsing-disable-download-protection',
   '--disable-client-side-phishing-detection',
   '--disable-component-update',
+  // Simulate when chrome needs an update.
+  // This prevents an 'update' from displaying til the given date
+  `--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'`,
```
Comment (flotwig) [inline packages/server/lib/browsers/chrome.ts:97]: such tech debt, we're gonna have to deal with this in only 78 years!

/s

on a serious note, i saw a couple other ways to disable this, but i guess they're all equally as weird as this:

```ts
--check-for-update-interval=31536000
--simulate-update-hresult=something, not exactly sure
```

**Review by flotwig — APPROVED** [review]

**Comment by effrenus** [comment]
👋 We recently encountered same problem, want to share some findings:
* Version detector active only in Chrome, disabled in Chromium build since 79.0.3934.0: [upgrade_detector_impl.cc#L73](https://github.com/chromium/chromium/blob/d7da0240cae77824d1eda25745c4022757499131/chrome/browser/upgrade_detector/upgrade_detector_impl.cc#L73).
* Also exists `OutdatedBuildDetector` feature flag since 54.0.2837.0: [upgrade_detector_impl.cc#L184](https://github.com/chromium/chromium/blob/d7da0240cae77824d1eda25745c4022757499131/chrome/browser/upgrade_detector/upgrade_detector_impl.cc#L184). Can be disabled by `--disable-features=OutdatedBuildDetector` / [base_switches.cc#L18](https://github.com/chromium/chromium/blob/d7da0240cae77824d1eda25745c4022757499131/base/base_switches.cc#L18) (not tested).
* `--check-for-update-interval` – not worked for us by itself, not sure why)

Thx for another workaround: `--simulate-outdated-no-au`
