### PR TITLE
fix: Use post message instead of web sockets for spec bridges.

### LINKED ISSUE #22874: Cypress fails to visit in cy.origin block after ~30 cy.origin blocks
### Current behavior

After creating ~30 spec bridges, attempting to visit inside a `cy.origin` block will fail to visit.
Screen Shot 2022-07-20 at 2 55 55 PM

### Desired behavior

We should successfully visit.

### Test code to reproduce

This test can be run in the 'driver' project in cypress.

```js
it('fails to visit', () => {
    // Make ~30 spec bridges
    for (let index = 0; index < 29; index++) {
        cy.origin(`http://www.${index}.com:3500`, () => undefined)
    }

    cy.origin('http://www.app.foobar.com:3500', () => {
        cy.visit('/fixtures/primary-origin.html') // this fails to visit
        cy.log('derp') // This is here to prevent the test from exiting early.
    })
})
```

### Cypress Version

10.3.1

### Other

_No response_

### LINKED ISSUE #23967: Move XmlHttpRequest and Fetch patches to cross-origin injection code
### What would you like?

In preparation for `experimentalSessionAndOrigin` to go GA, we likely need to move the XmlHttpRequest and Fetch injections into the `injection/cross-origin.js` file. Since Cypress may or may not be instantiated yet, we might be able to leverage `postMessage` to send credentialStatus and resourceType to the primary, and the primary sends the information to the web socket. 

Currently the `Cypress.backend` request happens before the request is actually send to the server, which usually almost always means that the credentials are stored in the map by the time the proxy tries to access them. If using `postMessage`, this might no longer be the case, and the proxy may need to listen for an event or poll until it finds the credentials it needs without slowing down the proxy server

### Why is this needed?

Given the following example:

```
it('does a cross-origin navigation', () => {
  cy.visit('https://localhost:8080/index.html')

  cy.visit('https://www.foobar.com/index.html')
  /**
   * After visit, The AUT calls:
   *
   * fetch('www.boobaz.com/test-request', { credentials: 'include' })
   *
   * Since there is no cy.origin block active, or maybe the patch happens after the request,
   * we are unable to infer the credentials in the proxy, which essentially leads to
   * the ability of the request for www.boobaz.com/test-request does not attach cookies nor
   * has the ability to set them. This might be a problem for those who attach a cy.origin lazily after visit,
   * or are using cy.visit with chromeWebSecurity: false without cy.origin blocks.
   */
})
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by mjhenkes**
- Closes #22874
- Closes #23967

### User facing changelog
* cy.origin now supports > 30 unique origin spec bridges per test 

### Additional details
Chrome has a limit of 30 protected web sockets per page, previously each spec bridge had it's own websocket to communicate with the server, this pr changes the spec bridge to instead use postmessage to communicate to the primary cypress instance and use that websocket to communicate with the server. This avoids the 30 websocket limit.

This pr also moves fetch and xhr patches from the driver to the injection and makes them async.

### Steps to test

A new test was added verifying this change in cy.origin.cy.ts

### How has the user experience changed?

The user experience has remained the same.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/runner/event-manager.ts [hunk 1]
```diff
@@ -625,9 +625,13 @@ export class EventManager {
       const eventID = log.get('id')
 
       const requestSnapshot = () => {
-        return Cypress.primaryOriginCommunicator.toSpecBridgePromise(specBridge, 'snapshot:generate:for:log', {
-          name,
-          id: eventID,
+        return Cypress.primaryOriginCommunicator.toSpecBridgePromise({
```
Comment (mjhenkes) [inline packages/app/src/runner/event-manager.ts:627]: toSpecBridgePromise now takes an object, so i can name parameters.

File: packages/app/src/runner/event-manager.ts [hunk 2]
```diff
@@ -611,8 +611,8 @@ export class EventManager {
     })
 
     // Reflect back to the requesting origin the status of the 'duringUserTestExecution' state
-    Cypress.primaryOriginCommunicator.on('sync:during:user:test:execution', ({ specBridgeResponseEvent }, origin) => {
-      Cypress.primaryOriginCommunicator.toSpecBridge(origin, specBridgeResponseEvent, cy.state('duringUserTestExecution'))
+    Cypress.primaryOriginCommunicator.on('sync:during:user:test:execution', (_data, { origin, responseEvent }) => {
```
Comment (mjhenkes) [inline packages/app/src/runner/event-manager.ts:613]: response event has moved to be part the second parameter object and no longer part of data which should be only information sent by the caller.

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts [hunk 3]
```diff
@@ -62,9 +63,7 @@ describe('src/cross-origin/patches', { browser: '!webkit' }, () => {
     describe('from the AUT', () => {
       beforeEach(() => {
         cy.intercept('/test-request').as('testRequest')
-        cy.origin('http://www.foobar.com:3500', () => {
-          cy.stub(Cypress, 'backend').callThrough()
-        })
```
Comment (mjhenkes) [inline packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:67]: The stubs for backend have been moved out of the origin call and are now stubbed on the primary cypress instance because we will now call into the primary cypress instance through post message to call the backend method.

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts [hunk 4]
```diff
@@ -398,13 +427,16 @@ describe('src/cross-origin/patches', { browser: '!webkit' }, () => {
...
-                expect(Cypress.backend).not.to.have.been.calledWithMatch('request:sent:with:credentials')
 
                 return false
               })
 
               cy.get(`[data-cy="trigger-xml-http-request-with-bad-options"]`).click()
             })
+
+          cy.then(() => {
+            expect(Cypress.backend).to.have.been.calledWithMatch('request:sent:with:credentials')
```
Comment (mjhenkes) [inline packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:433]: the backend request will actually be called in this case (not a typo)

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts [hunk 5]
```diff
@@ -484,13 +519,16 @@ describe('src/cross-origin/patches', { browser: '!webkit' }, () => {
...
```
Comment (mjhenkes) [inline packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:525]: the backend request will actually be called in this case (not a typo)

File: packages/driver/src/cross-origin/communicator.ts [hunk 6]
```diff
@@ -19,42 +19,41 @@ const SNAPSHOT_EVENT_PREFIX = `${CROSS_ORIGIN_PREFIX}snapshot:`
  * @param event the name of the event to be promisified.
  * @param specBridgeName the name of the spec bridge receiving the event.
  * @param communicator the communicator that is sending the message
+ * @param timeout - in ms, if the promise does not complete during this timeout, fail the promise.
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts]: added a timeout parameter since some of the automation/backend calls take longer than a second.

File: packages/driver/src/cross-origin/communicator.ts [hunk 7]
```diff
@@ -19,42 +19,41 @@ const SNAPSHOT_EVENT_PREFIX = `${CROSS_ORIGIN_PREFIX}snapshot:`
...
   reject,
-  data,
   event,
   specBridgeName,
   communicator,
+  timeout = 1000,
 }: {
   resolve: Function
   reject: Function
-  data?: any
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts:34]: data is no longer modified since the `responseEvent` is sent back separately

File: packages/driver/src/cross-origin/communicator.ts [hunk 8]
```diff
@@ -105,7 +104,7 @@ export class PrimaryOriginCommunicator extends EventEmitter {
         data.data.err = reifySerializedError(data.data.err, this.userInvocationStack as string)
       }
 
-      this.emit(messageName, data.data, data.origin, source)
+      this.emit(messageName, data.data, { origin: data.origin, source, responseEvent: data.responseEvent })
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts:107]: Group event metadata in a single object.

File: packages/driver/src/cross-origin/communicator.ts [hunk 9]
```diff
@@ -137,9 +136,30 @@ export class PrimaryOriginCommunicator extends EventEmitter {
...
+  }
 
+  /**
+   * Event to be sent to sent to a specific source.
+   * @param origin - the origin of the spec bridge to send the event to.
+   * @param event - the name of the event to be sent.
+   * @param data - any meta data to be sent with the event.
+   * @param responseEvent - the even to be responded with when sending back a result.
+   */
+  toSource (source: Window, event: string, data?: any, responseEvent?: string) {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts:162]: Added toSource to shortcut when responding back to a post message that expects a response. This also allows us to work for both spec bridge messages and AUT messages.

File: packages/driver/src/cross-origin/communicator.ts [hunk 10]
```diff
@@ -242,15 +274,16 @@ export class SpecBridgeCommunicator extends EventEmitter {
...
   }
 
   /**
    * Events to be sent to the primary communicator instance.
    * @param {string} event - the name of the event to be sent.
    * @param {Cypress.ObjectLike} data - any meta data to be sent with the event.
+   * @param responseEvent - the even to be responded with when sending back a result.
    */
-  toPrimary (event: string, data?: Cypress.ObjectLike, options: { syncGlobals: boolean } = { syncGlobals: false }) {
+  toPrimary (event: string, data?: Cypress.ObjectLike, options: { syncGlobals: boolean } = { syncGlobals: false }, responseEvent?: string) {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts:286]: we should consider making toPrimary take an object too. I didn't make the change here because i was already making enough changes, but would be willing to update if everyone agrees.

File: packages/driver/src/cross-origin/cypress.ts [hunk 11]
```diff
@@ -172,26 +175,18 @@ const attachToWindow = (autWindow: Window) => {
     patchFormElementSubmit(autWindow)
   }
 
-  Cypress.removeAllListeners('app:timers:reset')
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/cypress.ts]: moved this to the injection

File: packages/driver/src/cross-origin/cypress.ts [hunk 12]
```diff
@@ -172,26 +175,18 @@ const attachToWindow = (autWindow: Window) => {
...
-  Cypress.on('app:timers:reset', autWindow.cypressTimersReset)
-  // @ts-ignore - the injected code adds the cypressTimersPause function to window
-  Cypress.on('app:timers:pause', autWindow.cypressTimersPause)
-
   cy.urlNavigationEvent('before:load')
 
   cy.overrides.wrapNativeMethods(autWindow)
 
+  // @ts-expect-error - the injected code adds the cypressApplyPatchesOnAttach function to window
+  autWindow.cypressApplyPatchesOnAttach()
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/cypress.ts]: Added this as the one place to apply any patches on attach.

File: packages/driver/src/cross-origin/cypress.ts [hunk 13]
```diff
@@ -172,26 +175,18 @@ const attachToWindow = (autWindow: Window) => {
...
+
   // place after override incase fetch is polyfilled in the AUT injection
   // this can be in the beforeLoad code as we only want to patch fetch/xmlHttpRequest
   // when the cy.origin block is active to track credential use
-  patchFetch(Cypress, autWindow)
-  patchXmlHttpRequest(Cypress, autWindow)
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/cypress.ts:178]: moved to the injection

File: packages/driver/src/cross-origin/events/socket.ts [hunk 14]
```diff
@@ -1,18 +1,16 @@
...
-
 export const handleSocketEvents = (Cypress) => {
-  const webSocket = createWebsocket({ path: Cypress.config('socketIoRoute'), browserFamily: Cypress.config('browser').family })
-
-  webSocket.connect()
-
-  const onBackendRequest = (...args) => {
-    webSocket.emit('backend:request', ...args)
-  }
+  const onRequest = async (event, args) => {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/events/socket.ts:2]: we now delegate any websocket connections to the primary cypress instance and communicate with it via post message.

File: packages/driver/src/cross-origin/patches/utils/index.ts [hunk 15]
```diff
@@ -1,17 +0,0 @@
-export const captureFullRequestUrl = (relativeOrAbsoluteUrlString: string, window: Window) => {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/utils/index.ts:1]: moved to the runner

File: packages/runner/injection/cross-origin.js [hunk 16]
```diff
@@ -50,22 +52,17 @@ window.addEventListener('beforeunload', () => {
 // This error could also be handled by creating and attaching a spec bridge and re-throwing the error.
 // If this approach proves to be an issue we could try the new solution.
 const handleErrorEvent = (event) => {
-  if (window.Cypress) {
-    // A spec bridge has attached so we don't need to forward errors to top anymore.
-    window.removeEventListener('error', handleErrorEvent)
-  } else {
```
Comment (mjhenkes) [inline packages/runner/injection/cross-origin.js:56]: this is now cleaned up in the `cypressApplyPatchesOnAttach` function

File: packages/runner/injection/patches/fetch.ts [hunk 17]
```diff
@@ -1,16 +1,16 @@
-import { captureFullRequestUrl } from './utils'
+import { captureFullRequestUrl, requestSentWithCredentials } from './utils'
 
-export const patchFetch = (Cypress: Cypress.Cypress, window) => {
+export const patchFetch = (window) => {
   // if fetch is available in the browser, or is polyfilled by whatwg fetch
   // intercept method calls and add cypress headers to determine cookie applications in the proxy
   // for simulated top. @see https://github.github.io/fetch/ for default options
-  if (!Cypress.config('experimentalSessionAndOrigin') || !window.fetch) {
+  if (!window.fetch) {
```
Comment (mjhenkes) [inline packages/runner/injection/patches/fetch.ts:7]: experimental session and origin config doesn't really apply here because it is only injected if the flag is enabled anyway

File: packages/runner/injection/patches/fetch.ts [hunk 18]
```diff
@@ -1,16 +1,16 @@
...
     return
   }
 
   const originalFetch = window.fetch
 
-  window.fetch = function (...args) {
+  window.fetch = async function (...args) {
```
Comment (mjhenkes) [inline packages/runner/injection/patches/fetch.ts:13]: we're now async so we can await the backend call.. i think previously it was a race condition.

File: packages/runner/injection/patches/fetch.ts [hunk 19]
```diff
@@ -34,17 +34,13 @@ export const patchFetch = (Cypress: Cypress.Cypress, window) => {
...
-      if (url) {
-        // @ts-expect-error
-        Cypress.backend('request:sent:with:credentials', {
-          // TODO: might need to go off more information here or at least make collisions less likely
-          url,
-          resourceType: 'fetch',
-          credentialStatus: credentials,
-        })
-      }
+      await requestSentWithCredentials({
```
Comment (mjhenkes) [inline packages/runner/injection/patches/fetch.ts:37]: this function handles the url and checks if cypress is on window, this is common between fetch and xhr calls.

File: packages/runner/injection/patches/utils/index.ts [hunk 20]
```diff
@@ -0,0 +1,82 @@
...
+    try {
+      // likely a relative path, construct the full url
+      url = new URL(relativeOrAbsoluteUrlString, window.location.origin).toString()
+    } catch (err2) {
+      return undefined
+    }
+  }
+
+  return url
+}
```
Comment (mjhenkes) [inline packages/runner/injection/patches/utils/index.ts:17]: No changes to the `captureFullRequestUrl` function, just moved from the driver.

File: packages/runner/injection/patches/utils/index.ts [hunk 21]
```diff
@@ -0,0 +1,82 @@
...
+const CROSS_ORIGIN_PREFIX = 'cross:origin:'
+
+/**
+ * Sets up a promisified post message
+ * @param data the data to send
+ * @param event the name of the event to be promisified.
+ * @param timeout - in ms, if the promise does not complete during this timeout, fail the promise.
+ * @returns the data to send
+ */
+export const postMessagePromise = <T>({ event, data = {}, timeout }: {event: string, data: any, timeout: number}): Promise<T> => {
```
Comment (mjhenkes) [inline packages/runner/injection/patches/utils/index.ts:28]: this is very similar to what we're doing in the communicator, but just different enough to warrant it's own function.

**Review by AtofStryker — COMMENTED** [review]
we can probably remove the `beforeEach` in `validation.cy.ts` now which might be a good signal if too many spec bridges causes a problem again

File: packages/driver/src/cross-origin/communicator.ts [hunk 22]
```diff
@@ -137,9 +136,30 @@ export class PrimaryOriginCommunicator extends EventEmitter {
     })
   }
 
-  toSpecBridge (origin: string, event: string, data?: any) {
+  /**
+   * Event to be sent to sent to a specific spec bridge.
+   * @param origin - the origin of the spec bridge to send the event to.
+   * @param event - the name of the event to be sent.
+   * @param data - any meta data to be sent with the event.
+   * @param responseEvent - the even to be responded with when sending back a result.
```
Comment (chrisbreiding) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * Sends an event to a specific spec bridge.
   * @param origin - the origin of the spec bridge to send the event to.
   * @param event - the name of the event to be sent.
   * @param data - any meta data to be sent with the event.
   * @param responseEvent - the event to be responded with when sending back a result.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 23]
```diff
@@ -114,7 +113,7 @@ export class PrimaryOriginCommunicator extends EventEmitter {
   }
 
   /**
-   * Events to be sent to the spec bridge communicator instance.
+   * Event to be sent to the all spec bridge communicator instances.
```
Comment (chrisbreiding) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * Sends an event to all spec bridge communicator instances.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 24]
```diff
@@ -137,9 +136,30 @@ export class PrimaryOriginCommunicator extends EventEmitter {
...
+      this.toSource(source, event, data, responseEvent)
+    }
+  }
 
+  /**
+   * Event to be sent to sent to a specific source.
+   * @param origin - the origin of the spec bridge to send the event to.
+   * @param event - the name of the event to be sent.
+   * @param data - any meta data to be sent with the event.
+   * @param responseEvent - the even to be responded with when sending back a result.
```
Comment (chrisbreiding) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * Sends an event to a specific source.
   * @param origin - the origin of the spec bridge to send the event to.
   * @param event - the name of the event to be sent.
   * @param data - any meta data to be sent with the event.
   * @param responseEvent - the event to be responded with when sending back a result.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 25]
```diff
@@ -242,15 +274,16 @@ export class SpecBridgeCommunicator extends EventEmitter {
...
 
-    this.emit(data.event, data.data)
+    this.emit(data.event, data.data, { responseEvent: data.responseEvent })
   }
 
   /**
    * Events to be sent to the primary communicator instance.
    * @param {string} event - the name of the event to be sent.
    * @param {Cypress.ObjectLike} data - any meta data to be sent with the event.
+   * @param responseEvent - the even to be responded with when sending back a result.
```
Comment (chrisbreiding) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * @param responseEvent - the event to be responded with when sending back a result.
```

File: packages/runner/injection/cross-origin.js [hunk 26]
```diff
@@ -92,13 +89,33 @@ const timers = createTimers()
...
+// Add a function to window for the spec bridge to call after it has attached.
+window.__attachToCypress = (Cypress) => {
+  // A spec bridge has attached so we don't need to forward errors to top anymore.
+  window.removeEventListener('error', handleErrorEvent)
+
+  Cypress.removeAllListeners('app:timers:reset')
+  Cypress.removeAllListeners('app:timers:pause')
+
+  Cypress.on('app:timers:reset', timersReset)
+  Cypress.on('app:timers:pause', timersPause)
```
Comment (chrisbreiding) [inline packages/runner/injection/cross-origin.js]:
```suggestion
// Patched to track credentials use.
patchFetch(window)
patchXmlHttpRequest(window)

// Add a function to window for the spec bridge to call after it has attached.
window.__attachToCypress = (Cypress) => {
  // A spec bridge has attached so we don't need to forward errors to top anymore.
  window.removeEventListener('error', handleErrorEvent)

  Cypress.removeAllListeners('app:timers:reset')
  Cypress.removeAllListeners('app:timers:pause')

  Cypress.on('app:timers:reset', timers.reset)
  Cypress.on('app:timers:pause', timers.pause)
```

File: packages/runner/injection/patches/fetch.ts [hunk 27]
```diff
@@ -21,11 +21,11 @@ export const patchFetch = (Cypress: Cypress.Cypress, window) => {
       if (resource instanceof window.Request) {
         ({ url, credentials } = resource)
       } else if (resource instanceof window.URL) {
-        // should be a no-op for URL
+      // should be a no-op for URL
```
Comment (chrisbreiding) [inline packages/runner/injection/patches/fetch.ts]:
```suggestion
        // should be a no-op for URL
```

File: packages/runner/injection/patches/fetch.ts [hunk 28]
```diff
@@ -34,17 +34,13 @@ export const patchFetch = (Cypress: Cypress.Cypress, window) => {
...
-        })
-      }
+      await requestSentWithCredentials({
+        url,
+        resourceType: 'fetch',
+        credentialStatus: credentials,
+      })
     } finally {
-      // if our internal logic errors for whatever reason, do NOT block the end user and continue the request
+    // if our internal logic errors for whatever reason, do NOT block the end user and continue the request
```
Comment (chrisbreiding) [inline packages/runner/injection/patches/fetch.ts]:
```suggestion
      // if our internal logic errors for whatever reason, do NOT block the end user and continue the request
```

File: packages/runner/injection/patches/utils/index.ts [hunk 29]
```diff
@@ -0,0 +1,82 @@
...
+
+  return url
+}
+
+const CROSS_ORIGIN_PREFIX = 'cross:origin:'
+
+/**
+ * Sets up a promisified post message
+ * @param data the data to send
+ * @param event the name of the event to be promisified.
```
Comment (chrisbreiding) [inline packages/runner/injection/patches/utils/index.ts]:
```suggestion
 * @param data - the data to send
 * @param event - the name of the event to be promisified.
```

File: packages/runner/injection/patches/utils/index.ts [hunk 30]
```diff
@@ -0,0 +1,82 @@
...
+      event: eventName,
+      data,
+      responseEvent,
+    }, '*')
+  })
+}
+
+/**
+ * Returns a promise from the backend request for the 'request:sent:with:credentials' event.
+ * @param args an object containing a url, resourceType and Credential status.
```
Comment (chrisbreiding) [inline packages/runner/injection/patches/utils/index.ts]:
```suggestion
 * @param args - an object containing a url, resourceType and Credential status.
```

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/runner/injection/patches/utils/index.ts (hunk 30 above)
Comment (mjhenkes) [reply packages/runner/injection/patches/utils/index.ts]: in the IDE the color is different between the arg and the description 😅

File: packages/driver/src/cross-origin/cypress.ts [hunk 31]
```diff
@@ -172,26 +175,18 @@ const attachToWindow = (autWindow: Window) => {
...
-  // @ts-expect-error - the injected code adds the cypressTimersReset function to window
-  Cypress.on('app:timers:reset', autWindow.cypressTimersReset)
-  // @ts-ignore - the injected code adds the cypressTimersPause function to window
-  Cypress.on('app:timers:pause', autWindow.cypressTimersPause)
-
   cy.urlNavigationEvent('before:load')
 
   cy.overrides.wrapNativeMethods(autWindow)
 
+  // @ts-expect-error - the injected code adds the cypressApplyPatchesOnAttach function to window
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/cypress.ts]:
```suggestion
  // @ts-expect-error - the injected code adds the __attachToCypress function to window
```

File: packages/runner/injection/patches/utils/index.ts (hunk 30 above)
Comment (chrisbreiding) [reply packages/runner/injection/patches/utils/index.ts]: Yeah, it's the nittiest of nitpicks, but just thought these should be consistent.

Comment (mjhenkes) [reply packages/runner/injection/patches/utils/index.ts]: No worries, i think it's better with the dash!

**Review by chrisbreiding — APPROVED** [review]

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:67]: `backend` is once of those private public methods, right? I don't think we need to update any documentation with this move since users shouldn't be using `Cypress.backend`, right?

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:433]: should we change the test name, like `still emits credential status in the case absolute url can be parsed even though request results in 404`?

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:525]: same suggestion here about a better name?

File: packages/driver/src/cross-origin/communicator.ts (hunk 6 above)
Comment (AtofStryker) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
 * @param [timeout=1000] - in ms, if the promise does not complete during this timeout, fail the promise.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 32]
```diff
@@ -137,9 +136,30 @@ export class PrimaryOriginCommunicator extends EventEmitter {
...
+    const source = this.crossOriginDriverWindows[origin]
+
+    if (source) {
+      this.toSource(source, event, data, responseEvent)
+    }
+  }
 
+  /**
+   * Sends an event to a specific source.
+   * @param origin - the origin of the spec bridge to send the event to.
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * @param source - a reference to the window object that sent the message.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 33]
```diff
@@ -159,20 +180,31 @@ export class PrimaryOriginCommunicator extends EventEmitter {
    * @param {string} event - the name of the event to be sent.
    * @param {Cypress.ObjectLike} data - any meta data to be sent with the event.
    * @param options - contains boolean to sync globals
+   * @param timeout - in ms, if the promise does not complete during this timeout, fail the promise.
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * @param [timeout=1000] - in ms, if the promise does not complete during this timeout, fail the promise.
```

File: packages/driver/src/cross-origin/communicator.ts [hunk 34]
```diff
@@ -281,20 +315,31 @@ export class SpecBridgeCommunicator extends EventEmitter {
...
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/communicator.ts]:
```suggestion
   * @param [timeout=1000] - in ms, if the promise does not complete during this timeout, fail the promise.
```

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 3 above)
Comment (mjhenkes) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:67]: Yeah no users should be using it or trying to stub it.

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 4 above)
Comment (mjhenkes) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:433]: updated

File: packages/driver/cypress/e2e/e2e/origin/patches.cy.ts (hunk 5 above)
Comment (mjhenkes) [reply packages/driver/cypress/e2e/e2e/origin/patches.cy.ts:525]: updated

**Review by AtofStryker — APPROVED** [review]
