### PR TITLE
fix: return type of Cookies.default

### LINKED ISSUE #15426: `Cypress.Cookies.defaults()` return type is `void` but the code does return a value
### What would you like?

`Cypress.Cookies.defaults()` allow to preserve some cookies during the test execution.  

However, there is no official way to extend the existing list of defaults.

`Cypress.Cookies.defaults()` return the default object but the type tells it returns `void`

Ideally the returnType of `Cypress.Cookies.defaults()` should be change, or a method to retrieve defaults could be added

### Why is this needed?

We have a cypress plugin doing some user authentication.  
This plugin uses `Cypress.Cookies.defaults()` to make sure the authentication is working.  

In our code, we also have a special cookie that we set and we could like it to be preserved.

With current types it seems impossible.  

However, we can "hack" something because `Cypress.Cookies.defaults()`  does return a value:

```js
// the Cypress type wrongly says the default method is returning void.
		// in fact it returns the destination object (because the implementation is based on _.extends)
		// see https://github.com/cypress-io/cypress/blob/c12347dc9c4f9dc0662ad9350536c6c6b99225c4/packages/driver/src/cypress/cookies.js#L144
		// thanks to this hack we can extend the existing defaults and add our cookie
		const currentDefault = Cypress.Cookies.defaults({}) as unknown as Partial<Cypress.CookieDefaults> | undefined;
		if (currentDefault && 'preserve' in currentDefault) {
			const { preserve } = currentDefault;
			const toPreserve = [];
			if (Array.isArray(preserve)) {
				toPreserve.push(...preserve, USERNAME_COOKIE);
			} else if (typeof preserve === 'string') {
				toPreserve.push(preserve, USERNAME_COOKIE);
			} else if (!preserve) {
				toPreserve.push(USERNAME_COOKIE);
			} else {
				throw new Error(`could not extend the existing Cypress.Cookies.defaults, received: ${JSON.stringify(currentDefault)}`);
			}
			Cypress.Cookies.defaults({ preserve: toPreserve });
			cy.log(`Preserved cookies: ${toPreserve.join()}`);
		} else {
			// because this whole solution is hack, let's be verbose in case of failure
			throw new Error(`could not fetch the existing Cypress.Cookies.defaults, received: ${JSON.stringify(currentDefault)}`);
		}
```

### PR DESCRIPTION
**Pull request by ben8p**
- Closes #15426 

### User facing changelog

the return type for Cookies.default() was incorrectly set to void.  It now match the implementation (returning the destination object)

### Additional details

This change allow to extends the existing default without using typescript tricks to get around the return type.

### PR Tasks

- [X] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -404,7 +404,7 @@ declare namespace Cypress {
     Cookies: {
       debug(enabled: boolean, options?: Partial<DebugOptions>): void
       preserveOnce(...names: string[]): void
-      defaults(options: Partial<CookieDefaults>): void
+      defaults(options: Partial<CookieDefaults>): Partial<CookieDefaults>
```
Comment (flotwig) [inline cli/types/cypress.d.ts:407]:
```suggestion
      defaults(options: Partial<CookieDefaults>): CookieDefaults
```

**Review by flotwig — DISMISSED** [review]
I think this behavior isn't even intentional, it's just leftover from the original coffeescript:

https://github.com/cypress-io/cypress/blob/86a5afea3829596fad48d1c6959d7278e3047bc2/packages/driver/src/cypress/cookies.js#L103-L105

It is implicitly returned there, probably not on purpose.

But we can update the types to be correct anyways.
