### PR TITLE
fix: suite-level-only configuration does not throw when config is restored

### LINKED ISSUE #23644: testIsolation Config Throws on 2nd Test
### Current behavior

Screen Shot 2022-08-31 at 9 18 31 AM

- quick debugging shows override level is "undefined" when it should be "suite"

### Desired behavior

Config validation correctly ensures which level the configuration is being applied from.

### Test code to reproduce

```js
describe('page', {testIsolation: 'legacy' }, () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
  })

  it('works', () => {
    cy.url().should('eq', 'https://example.cypress.io')
  })
})
````

### Cypress Version

10.5.0+

### Node version

n/a

### Operating System

n/a

### Debug Logs

```shell
n/a
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #23644 

Before each test, the previous global configuration is restored. On the second test in a suite, the first test's configuration overrides are remove and the configuration is restores to be the suite-level configurations.

### User facing changelog

- Fixed an issue where setting the testIsolation configuration at the suite level would throw on the second test. Fixed [#23644](https://github.com/cypress-io/cypress/issues/23644).

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: system-tests/test/testConfigOverrides_spec.ts [hunk 1]
```diff
@@ -10,6 +10,16 @@ const outputPath = path.join(e2ePath, 'output.json')
 describe('testConfigOverrides', () => {
   systemTests.setup()
 
+  systemTests.it('successfully runs valid suite-level-only overrides', {
+    spec: 'testConfigOverrides/valid-suite-only.js',
+    snapshot: true,
+    expectedExitCode: 0,
+    browser: 'electron',
```
Comment (AtofStryker) [inline system-tests/test/testConfigOverrides_spec.ts:17]: any reason we only want to run this in electron?

**Review by AtofStryker — APPROVED** [review]

File: system-tests/test/testConfigOverrides_spec.ts (hunk 1 above)
Comment (emilyrohrbough) [reply system-tests/test/testConfigOverrides_spec.ts:17]: I don't expect the test config overrides to be applied different per browser so I didn't think it was necessary

Comment (chrisbreiding) [reply system-tests/test/testConfigOverrides_spec.ts:17]: Why a system test instead of a driver test?

Comment (emilyrohrbough) [reply system-tests/test/testConfigOverrides_spec.ts:17]: I wrote as a system test because this was fixing the case when the second tests in a describe block not successfully running when the configuration was resetting between specs.

**Review by chrisbreiding — APPROVED** [review]
