### PR TITLE
fix: secondary domain command state

### LINKED ISSUE #19545: Multi-domain: Secondary domain command state sometimes incorrect in UI
### Current behavior

Currently within the [feature-multidomain](https://github.com/cypress-io/cypress/tree/feature-multidomain) branch, there is an issue that is persisting between commands executed within the secondary domain context. These commands always finish, but are not updated correctly in the UI sometimes and may shown as 'pending'. Here is the same test executed 3 consecutive times, each producing a different UI output.

Screen Shot 2022-01-04 at 10 30 42 AM

Screen Shot 2022-01-04 at 10 30 52 AM

Screen Shot 2022-01-04 at 10 31 04 AM

### Desired behavior

The expectation is that the multi-domain tests should not having any pending commands after test execution and should be readily reproducible after consecutive runs.

 Screen Shot 2022-01-04 at 10 31 04 AM

### Test code to reproduce

[example test in question](https://github.com/cypress-io/cypress/blob/feature-multidomain/packages/driver/cypress/integration/e2e/multidomain_spec.ts#L36)

### Cypress Version

feature-multidomain (version TBD)

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #19545

### Additional details

#19545 showcases a problem where commands executed within the secondary domain (SD) were sometimes displaying as `pending` after a test was finished. This was due to a race condition where commands were finished in the SD, but command logs were not yet updated. The primary domain (PD) would wait for when all commands were finished, and then would unbind listeners. Consider the following use case:

* `command:update` emits ended command
* command queue finished
* listeners are unbound from PD
* new log updates are emitted via `log:changed` from the SD, but no one is actively listening on them, resulting in "pending" commands

The proposed fix here keeps the log and command streams open until all commands and logs are ended. Only then will the `command:update` and `log:changed` events be unbound. In the case where `done` is provided, commands are immediately cleaned up to allow no additional commands to be enqueued in the SD, but waits for all logs to stream in from the SD to determine pass/fail events. If no commands are enqueued and `done` is not provided or the `switchToDomain` function fails, log/command listeners are cleaned up immediately.

In addition to keeping the log stream open, we also need to sync the log messages coming back from the SD. Since certain values in the log are not serializable, they come back as empty objects or other values when hitting the PD. We only want to update values that are difference. If the values differ and are not `undefined`,`null`, or an empty `{}` or `[]`, the log is updated with the value. Otherwise, the update is ignored.

NOTE: Since `lodash` doesn't appear to have a deep diff method available, I added one to the `utils` that uses a few `lodash` methods to accomplish a deep diff.

It's also worth noting that I broke out the `log:added`, `log:changed`, and `command:update` events in the SD into the same named events in the PD. This offloads some of the responsibility from the `command:update` handler and allows to more flexibly move event/cleanup handlers around as needed as we work off of multi-domain.

Since we don't yet handle secondary domain command timeout/failures, the added test just explores the happy path to make sure no logs are pending by the time the log stream closes. We likely want to add more to these tests in the future.

### How has the user experience changed?
When tests would run before, tests would pass but sometimes contain pending commands from the SD

now, when tests run, all commands running in the SD should now be settled

### PR Tasks

- [x] Have tests been added/updated?
- [ N/A ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ N/A ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ N/A ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ N/A ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/e2e/multi_domain_spec.ts [hunk 1]
```diff
@@ -312,6 +314,42 @@ describe('multi-domain', { experimentalSessionSupport: true, experimentalMultiDo
...
+      const logsChangedGivingUpdate = {}
+
+      cy.on('log:added', (addedLog) => {
+        if (!addedLog.ended && addedLog?.id.includes(domain)) {
+          logsAddedNeedingUpdate[addedLog.id] = addedLog
+        }
+      })
+
+      cy.on('log:changed', (changedLog) => {
+        if (changedLog.ended && changedLog?.id.includes(domain)) {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/e2e/multi_domain_spec.ts:329]: If it's possible for `changedLog` to be undefined, shouldn't both references here use the optional chaining operator?

File: packages/driver/src/multi-domain/index.ts [hunk 2]
```diff
@@ -29,13 +29,13 @@ const onCommandEnd = (command: Cypress.CommandQueue) => {
...
+  specBridgeCommunicator.toPrimary('log:added', {
     logAdded: $Log.toSerializedJSON(attrs),
   })
 }
 
 const onLogChanged = (attrs) => {
-  specBridgeCommunicator.toPrimary('command:update', {
+  specBridgeCommunicator.toPrimary('log:changed', {
     logChanged: $Log.toSerializedJSON(attrs),
   })
```
Comment (chrisbreiding) [inline packages/driver/src/multi-domain/index.ts:40]: Since these are discrete events now, let's just pass along the serialized log attrs directly and skip the `logAdded` and `logChanged` properties. e.g:

```js
  specBridgeCommunicator.toPrimary('log:added', $Log.toSerializedJSON(attrs))
```

File: packages/driver/src/cy/multi-domain/index.ts [hunk 3]
```diff
@@ -144,56 +129,138 @@ export function addCommands (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
...
+        const { deferred, log } = logs[logChanged.id]
 
-        if (details.logChanged) {
-          const log = logs[details.logChanged.id]
+        // NOTE: Cypress.LogConfig only contains partial types of what exists on the log attributes, missing a lot of 'private' properties
+        const logAttrs = log.get()
 
-          if (log) {
-            log.set(details.logChanged)
+        const updatedLogAttributes: Partial<Cypress.Log> = difference(logChanged, logAttrs)
```
Comment (chrisbreiding) [inline packages/driver/src/cy/multi-domain/index.ts:166]: Is a deep difference truly necessary? When it gets merged into the log with `log.set()`, it does a shallow merge with `_.extend`, so any properties deeper than the second level will be overwritten on the log anyway.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/integration/e2e/multi_domain_spec.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/driver/cypress/integration/e2e/multi_domain_spec.ts:329]: Technically, I think so. We should put the optional chainer here to be safe. Will update!

File: packages/driver/src/multi-domain/index.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/driver/src/multi-domain/index.ts:40]: Good thinking!

File: packages/driver/src/cy/multi-domain/index.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts:166]: Probably not. Sounds like we just need to check one level deep for an object to see if there is a difference, and if so just return the different object that is keyed, as opposed to recursively trying to merge it. Will take a look and update it!

File: packages/driver/cypress/integration/e2e/multi_domain_spec.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/driver/cypress/integration/e2e/multi_domain_spec.ts:329]: I'm also going to add this to `addedLog`

File: packages/driver/src/cy/multi-domain/index.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts]: wound up just doing something like below and getting rid of the `difference` util all together
```js
      const updatedLogAttributes: Partial<Cypress.Log> = _.transform(logChanged, (result: {[key: string]: any }, value: any, key: string) => {
          if (!_.isEqual(value, logAttrs[key])) {
            result[key] = value
          }
        })
``

File: packages/driver/src/cy/multi-domain/index.ts [hunk 4]
```diff
@@ -144,56 +128,142 @@ export function addCommands (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
...
+      }
 
-        if (details.logChanged) {
-          const log = logs[details.logChanged.id]
+      const onLogChanged = (logChanged) => {
+        const { deferred, log } = logs[logChanged.id]
 
-          if (log) {
-            log.set(details.logChanged)
+        // NOTE: Cypress.LogConfig only contains partial types of what exists on the log attributes, missing a lot of 'private' properties
```
Comment (flotwig) [inline packages/driver/src/cy/multi-domain/index.ts:162]: If it would help to create additional "internal" types, the `driver` already has some types for `Cypress.LogConfig` here that can be extended: https://github.com/cypress-io/cypress/blob/1f28650d684c0b35265983edb92d58db325be819/packages/driver/types/internal-types.d.ts#L49-L68

**Review by flotwig — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
If it were me I'd look at removing some of the useage of lodash, like the foreach and maps for example. I want to believe that someday we can reduce our dependencies like lodash. Though i do think _.isEqual seems pretty useful :), Lodash is hypermodularized so we could just pull in the functions we use instead of the whole thing.

That said you don't have to change any of that, It's just my opinion.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/multi-domain/index.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts:162]: I didn't actually notice the name of the interface file 😂 . I can go ahead the ones we are using here as well as some others!

**Comment by AtofStryker** [comment]
> If it were me I'd look at removing some of the useage of lodash, like the foreach and maps for example. I want to believe that someday we can reduce our dependencies like lodash. Though i do think _.isEqual seems pretty useful :), Lodash is hypermodularized so we could just pull in the functions we use instead of the whole thing.
> 
> That said you don't have to change any of that, It's just my opinion.

@mjhenkes I'd love to have a team conversation about this idea! I originally had a lot of the foreach and maps using native functions, but I went 💯  in on lodash to be consistent once refactoring. I used to import each module individually like `import isEqual from 'lodash/isEqual'` to get the tree shaking benefits, but a friend sent me [this](https://lodash.com/per-method-packages) and since then I stopped doing it, especially here since we seem to import the whole package in most places `lodash` is used. That being said, I might love `lodash` a bit too much 😅 .

File: packages/driver/src/cy/multi-domain/index.ts [hunk 5]
```diff
@@ -144,56 +128,142 @@ export function addCommands (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
...
+        const logAttrs = log.get()
+
+        const updatedLogAttributes: Partial<Cypress.Log> = _.transform(logChanged, (result: {[key: string]: any }, value: any, key: string) => {
+          if (!_.isEqual(value, logAttrs[key])) {
+            result[key] = value
           }
+        })
```
[the remark this answers is not in the document]
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts:169]: oh yeah we can do that now! Gonna give the rest of this an overview just to make sure some refactoring benefits didn't get left out.

**Comment by mschile** [comment]
I received the following error when testing locally:
Screen Shot 2022-01-14 at 9 18 20 AM

Seems to happen during rerun scenarios where a test fails and then is corrected to pass.

**Comment by AtofStryker** [comment]
> I received the following error when testing locally: Screen Shot 2022-01-14 at 9 18 20 AM
> 
> Seems to happen during rerun scenarios where a test fails and then is corrected to pass.

Going to try and reproduce this. Sounds like at a minimum we need mote guards on what is passed into the `onLogChanged` handler.

**Comment by AtofStryker** [comment]
@mschile pushed some changes that should prevent this from erroring on test reruns incase the added/change handler gets undefined values. It seems to be working on my end, but would you mind taking another look?

File: packages/driver/src/cy/multi-domain/index.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts]: @flotwig @chrisbreiding I tried to enhance the log types on 4429a9742b1fbf7b3b4c2a21dd2a12889f942875. Some of it is a bit out of scope of this PR, but wanted to get y'alls opinion on it. Tried to get some types in there that aren't currently documented, but are used elsewhere in the codebase

File: packages/driver/src/cy/multi-domain/index.ts [hunk 6]
```diff
@@ -144,56 +128,138 @@ export function addCommands (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
...
+      const updateCommand = ({ id, end }) => {
+        if (end) {
+          const command = commands[id]
+
+          if (command) {
+            delete commands[id]
+            command.deferred.resolve()
+          }
+        }
+      }
```
Comment (chrisbreiding) [inline packages/driver/src/cy/multi-domain/index.ts:140]: Sorry I didn't notice this earlier, but this should be changed to `endCommand` and the event to `command:end`. Then we can get rid of the `end` property and the `if` condition here.

File: packages/driver/src/cy/multi-domain/index.ts [hunk 7]
```diff
@@ -144,56 +128,138 @@ export function addCommands (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
...
+          const logAttrs = log.get()
 
-          return
-        }
+          _.forEach(attrs, (value: any, key: string) => {
+            if (!_.isEqual(value, logAttrs[key])) {
+              if (value !== undefined && value !== null && !(_.isObject(value) && _.isEmpty(value))) {
+                log.set(key as keyof Cypress.LogConfig, value)
+              }
+            }
```
Comment (chrisbreiding) [inline packages/driver/src/cy/multi-domain/index.ts:170]:
```suggestion
            if (
              value != null
              && !(_.isObject(value) && _.isEmpty(value))
              && !_.isEqual(value, logAttrs[key])
            ) {
              log.set(key as keyof Cypress.LogConfig, value)
            }
```

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

**Comment by mschile** [comment]
> @mschile I pushed some changes that should prevent this from erroring on test reruns incase the added/change handler gets undefined values. It seems to be working on my end, but would you mind taking another look?

I'm still seeing the issue with the pause/debug commands (those may not be fully supported yet in multi-domain).

Running the following test with the developer tools open produces the issue:
```
  it('runs commands in secondary domain', () => {
    cy.switchToDomain('foobar.com', () => {
      cy
      .get('[data-cy="dom-check"]')
      .invoke('text')
      .debug()
      .should('equal', 'From a secondary domain')
    })

    cy.log('after switchToDomain')
  })
```

**Comment by AtofStryker** [comment]
> 

@mschile Ah interesting! Looks like certain debug logs are created only on the log change event, or are already considered done and updates continue to stream in. Those updates aren't super important AFAIK for now, so I added some additional guards that should prevent that from happening. I don't have a test for that right now, so I am wondering if we want to make one that uses the `debug()` command or just insert it into a test with a comment that it's purpose is to make sure there aren't regressions with the cross domain log changes. What do you think?

File: packages/driver/src/cy/multi-domain/index.ts (hunk 7 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts]: fixed!

File: packages/driver/src/cy/multi-domain/index.ts (hunk 6 above)
Comment (AtofStryker) [reply packages/driver/src/cy/multi-domain/index.ts]: No worries! I renamed the event to `command:end` and only kept the ID on destructure.  Figured we can keep the destructure pattern as we like to send other properties sometimes to debug

**Review by chrisbreiding — APPROVED** [review]
Looks good! 

I wouldn't worry about pause/debug for this PR. We can focus on those in a future story.
