### PR TITLE
fix: do not override electron debug port if previously set

### LINKED ISSUE #26711: Failed to connect to Chrome Debugging Protocol
### Current behavior

Cypress Crashes when Cypress Har Generator is enabled (https://github.com/NeuraLegion/cypress-har-generator) with Electron Browser with Flag ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222

Logs:
```
npm run cypress:run -- cypress/config/localreact.config.js

> cloudranger-v2-cypress@1.0.0 cypress:run
> percy exec -t 350 -- node scripts/cypress.js cypress/config/localreact.config.js

[percy] Skipping visual tests
[percy] Error: Missing Percy token
[percy] Running "node scripts/cypress.js cypress/config/localreact.config.js"


DevTools listening on ws://127.0.0.1:56853/devtools/browser/0f66cba6-f00b-4862-b756-1b4362f52b21

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.12.0                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v16.20.0 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (smoke-dash.spec.js)                                                   │
  │ Searched:       C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automa │
  │                 tion\Protractor\cloudranger-v2-testing\Cypress\cypress\e2e\Group-0\1-General\s │
  │                 moke-dash.spec.js                                                              │
  │ Experiments:    experimentalMemoryManagement=true                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  smoke-dash.spec.js                                                              (1 of 1)


  1) "before all" hook for "Smoke Test Dashboard Page"

  0 passing (2s)
  1 failing

  1) CR Page Smoke Tests
       "before all" hook for "Smoke Test Dashboard Page":
     CypressError: `cy.task('recordHar')` failed with the following error:

> Failed to connect to Chrome Debugging Protocol

Possible reasons for failure:
  - Chrome not running in headless mode
  - Using Chrome version 58 or earlier
  - Inconsistent RDP configuration settings.

The stack trace for this error is:

https://on.cypress.io/api/task

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
      at <unknown> (http://localhost:56855/__cypress/runner/cypress_runner.js:150983:78)
      at tryCatcher (http://localhost:56855/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:56855/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:56855/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:56855/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:56855/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:56855/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:56855/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:56855/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:56855/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (webpack:///C:/Users/Tony Mullan/Documents/Project/QA - 0000-000 CloudRanger/TM08 - Automation/Protractor/cloudranger-v2-testing/Cypress/node_modules/@neuralegion/cypress-har-generator/commands.js:1:1260)

  From Node.js Internals:
    Error: Failed to connect to Chrome Debugging Protocol

    Possible reasons for failure:
      - Chrome not running in headless mode
      - Using Chrome version 58 or earlier
      - Inconsistent RDP configuration settings.

    The stack trace for this error is:
        at V.<anonymous> (C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automation\Protractor\cloudranger-v2-testing\Cypress\node_modules\@neuralegion\cypress-har-generator\dist\index.js:1:39760)
    at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automation\Protractor\cloudranger-v2-testing\Cypress\node_modules\tslib\tslib.js:164:62)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)



[mochawesome] Report JSON saved to C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automation\Protractor\cloudranger-v2-testing\Cypress\mochawesome-report\mochawesome_05102023_114250.json

Results Stats {
  suites: 1,
  tests: 1,
  passes: 0,
  pending: 0,
  skipped: 0,
  failures: 1,
  wallClockStartedAt: '2023-05-10T10:42:48.239Z',
  wallClockEndedAt: '2023-05-10T10:42:50.599Z',
  wallClockDuration: 2360
}
Finished running spec cypress\e2e\Group-0\1-General\smoke-dash.spec.js

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     smoke-dash.spec.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automati     (1280x720)
     on\Protractor\cloudranger-v2-testing\Cypress\cypress\screenshots\smoke-dash.spec
     .js\Smoke Test Dashboard Page -- before all hook (failed).png


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: 0 seconds

  -  Video output: C:\Users\Tony Mullan\Documents\Project\QA - 0000-000 CloudRanger\TM08 - Automation\Protractor\cloudranger-v2-testing\Cypress\cypress\videos\smoke-dash.spec.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  smoke-dash.spec.js                       00:02        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:02        1        -        1        -        -  

```

### Desired behavior

Works Fine in Previous Cypress Releases

### Test code to reproduce

Run a spec with Electron and Cypress Har Generator enabled

`cy.recordHar({ includeMimes: ['application/json'] })`

### Cypress Version

12.12.0

### Node version

v16.20.0

### Operating System

Windows and Ubuntu

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by warrensplayer**
- Closes https://github.com/cypress-io/cypress/issues/26711

### Additional details

PR https://github.com/cypress-io/cypress/pull/26573 added logic to assign a random available port for Electron to use as the debugging port to connect to CDP.  This PR adds a check to make sure if a port has been passed in via setting an environment variable (i.e. `ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222`) as documented here (https://docs.cypress.io/api/plugins/browser-launch-api#Modify-Electron-app-switches) that it will not get overridden with a random port.

### Steps to test

* Look at unit test added
* Run test with example repo in reported issue
  * Clone [NeuraLegion/cypress-har-generator](https://github.com/NeuraLegion/cypress-har-generator)
  * cd to `example` directory
  * install Cypress `12.12.0` - `npm i -D Cypress@12.12.0`
  * install rest of dependencies - `npm i`
  * run tests - `ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 npm run test`
  * view failure

```
     CypressError: `cy.task('recordHar')` failed with the following error:

> Failed to connect to Chrome Debugging Protocol

Possible reasons for failure:
  - Chrome not running in headless mode
  - Using Chrome version 58 or earlier
  - Inconsistent RDP configuration settings.
```

* View fix in this branch
  * in the example repo in the `example` directory, run `npm run start` to start the example server
  * switch to this branch in the Cypress project
  * cd `packages/app`
  * run `ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 yarn cypress:run-cypress-in-cypress node ../../scripts/cypress run --project {path_to}/cypress-har-generator/example` and switch out path to the reproduction repo where it says `path_to` in this command
  * Tests should run successfully

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [-] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [-] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/util/electron-app.js [hunk 1]
```diff
@@ -24,11 +24,20 @@ const getRemoteDebuggingPort = () => {
...
+    if (app.commandLine.getSwitchValue('remote-debugging-port')) {
+      return
+    }
+
+    const port = await getPort()
+
     // set up remote debugging port
     app.commandLine.appendSwitch('remote-debugging-port', String(port))
+
+    return app.commandLine.appendSwitch
```
Comment (mike-plummer) [inline packages/server/lib/util/electron-app.js]:
```suggestion
    // if port was already set via passing from environment variable ELECTRON_EXTRA_LAUNCH_ARGS,
    // then just keep the supplied value
    if (!app.commandLine.getSwitchValue('remote-debugging-port')) {
      const port = await getPort()

      // set up remote debugging port
      app.commandLine.appendSwitch('remote-debugging-port', String(port))
    }
    
    return app.commandLine.appendSwitch
```

Should we preserve the existing return value for either path?

File: cli/CHANGELOG.md [hunk 2]
```diff
@@ -12,10 +12,11 @@ _Released 07/05/2023 (PENDING)_
 - Fixed issues where commands would fail with the error `must only be invoked from the spec file or support file`. Fixes [#27149](https://github.com/cypress-io/cypress/issues/27149) and [#27163](https://github.com/cypress-io/cypress/issues/27163).
 - Fixed an issue where chrome was not recovering from browser crashes properly. Fixes [#24650](https://github.com/cypress-io/cypress/issues/24650).
 - Fixed a race condition that was causing a GraphQL error to appear on the [Debug page](https://docs.cypress.io/guides/cloud/runs#Debug) when viewing a running Cypress Cloud build. Fixed in [#27134](https://github.com/cypress-io/cypress/pull/27134).
+- Fixed an issue to prevent the debug port for Electron that was passed in with the ELECTRON_EXTRA_LAUNCH_ARGS environment variable from getting overridden. Addresses [#26711](https://github.com/cypress-io/cypress/issues/26711).
```
Comment (mike-plummer) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue where a value for the Electron debug port would not be respected if defined using the `ELECTRON_EXTRA_LAUNCH_ARGS` environment variable. Fixes [#26711](https://github.com/cypress-io/cypress/issues/26711).
```

**Review by lmiller1990 — APPROVED** [review]
Code seems fine. I followed the repro instructions but I did not encounter an error, though 🤔

File: packages/server/lib/util/electron-app.js (hunk 1 above)
Comment (warrensplayer) [reply packages/server/lib/util/electron-app.js]: I was the one that added the return value when trying to debug my unit test. It is not used so I just removed it.

**Review by ryanthemanuel — APPROVED** [review]
