### PR TITLE
Use websockets to stub large XHR response bodies instead of headers

### LINKED ISSUE #5431: 431 status code on stubbed XHR requests with large response in 3.5.0
## Current behavior: 

I have a request that is responding with a 431 status in 3.5.0 of Cypress, which was responding with a 200 in 3.4.1.

>431 Request Header Fields Too Large

We are legitimately sending a large amount of characters in our response, I've included it below. If I reduce the size of this response content, it then passes as 200 status code.

Screen Shot 2019-10-23 at 5 56 55 PM

### Desired behavior:

Responding with a 200

Screen Shot 2019-10-23 at 5 57 49 PM

### Steps to reproduce: (app code and test code)

```js
it('displays algolia dropdown on search', () => {
  cy.server()
  cy.route({
    method: 'POST',
    url: /algolia/,
    response: {
      'results': [
        {
          'hits': [
            {
              'hierarchy': { 'lvl2': null, 'lvl3': null, 'lvl0': 'Known Issues', 'lvl1': null, 'lvl6': null, 'lvl4': null, 'lvl5': null },
              'url': 'https://docs-staging.cypress.io/guides/appendices/known-issues.html#content-inner', 'content': 'Missing Commands Some commands have not been implemented in Cypress. Some commands will be implemented in the future and some do not make sense to implement in Cypress.  Right click Issue #53  Workaround  Oftentimes you can use  .invoke()  or  cy.wrap()  to trigger the event or execute the action in the DOM.  Example of right clicking on an element using jQuery  cy . get ( &#x27;#nav&#x27; ) . first ( ) . invoke ( &#x27;trigger&#x27; ,   &#x27;contextmenu&#x27; )   Example of right clicking on an element without jQuery  // need to create the event to later dispatch  var  e  =   new   Event ( &#x27;contextmenu&#x27; ,   { bubbles :   true ,  cancelable :   true } )  // set coordinates of click e . clientX  =   451 e . clientY  =   68 cy   . get ( &#x27;#nav&#x27; ) . first ( ) . then ( function ( $el )   {     $el [ 0 ] . dispatchEvent ( e )    } )   Hover Issue #10  Sometimes an element has specific logic on hover. Maybe the element doesn’t even display to be clickable until you hover over a specific element.  Workaround  Oftentimes you can use  .invoke()  or  cy.wrap()  to show the element before you perform the action.  Example of showing an element in order to perform action  cy . get ( &#x27;.content&#x27; ) . invoke ( &#x27;show&#x27; ) . click ( )   You can also force the action to be performed on the element regardless of whether the element is visible or not.  Example of clicking on a hidden element  cy . get ( &#x27;.content&#x27; ) . click ( { force :   true } )   Example of checking a hidden element  cy . get ( &#x27;.checkbox&#x27; ) . check ( { force :   true } )   Difficult use cases Cypress does not support the following use cases.  Iframes Issue #136  You cannot target elements or interact with anything in an iframe - regardless of it being a same domain or cross domain iframe.  This is actively being worked on in Cypress and you’ll first see support for same domain iframes, followed by cross domain (they are much harder to do).  Workaround  Sit tight, comment on the issue so we know you care about this support, and be patient.  OAuth This is related to the iframe issue above, but basically  oauth  usually will not work. This is one of the hardest things for Cypress to be able to handle as there are so many different implementations and mechanisms.  Likely we will be able to support server side oauth redirects, but for client side popups you’ll use sinon  and  stub  the oauth response directly in your code. This is actually possible to do right now but we don’t have any good docs or tutorials on it.  Workaround  Come into Gitter  and talk to us about what you’re trying to do. We’ll tell you if you’re able to mock this and how to do it.  window.fetch routing and stubbing Issue #95  Support for  fetch  has not been added but it’s possible to handle in the same way as we handle  XHRs . This biggest challenge here is that you can use  fetch  in  Service Workers  outside of the global context. We’ll likely have to move routing to the server and handle it in the proxy layer but it should be possible.  While we currently provide things like the stack trace and initiator line for XHR’s we will not be able to provide that for  fetch .  Workaround  Sit tight, comment on the issue so we know you care about this support, and be patient', 'anchor': 'content-inner', 'objectID': '15872310', '_snippetResult': { 'content': { 'value': 'to implement in Cypress.  Right <span class="algolia-docsearch-suggestion--highlight">click Issue #53</span>  Workaround  Oftentimes', 'matchLevel': 'full' } }, '_highlightResult': { 'hierarchy': { 'lvl0': { 'value': 'Known Issues', 'matchLevel': 'none', 'matchedWords': [] } }, 'content': { 'value': 'Missing Commands Some commands have not been implemented in Cypress. Some commands will be implemented in the future and some do not make sense to implement in Cypress.  Right <span class="algolia-docsearch-suggestion--highlight">click Issue #53</span>  Workaround  Oftentimes you can use  .invoke()  or  cy.wrap()  to trigger the event or execute the action in the DOM.  Example of right clicking on an element using jQuery  cy . get ( \'#nav\' ) . first ( ) . invoke ( \'trigger\' ,   \'contextmenu\' )   Example of right clicking on an element without jQuery  // need to create the event to later dispatch  var  e  =   new   Event ( \'contextmenu\' ,   { bubbles :   true ,  cancelable :   true } )  // set coordinates of click e . clientX  =   451 e . clientY  =   68 cy   . get ( \'#nav\' ) . first ( ) . then ( function ( $el )   {     $el [ 0 ] . dispatchEvent ( e )    } )   Hover Issue #10  Sometimes an element has specific logic on hover. Maybe the element doesn’t even display to be clickable until you hover over a specific element.  Workaround  Oftentimes you can use  .invoke()  or  cy.wrap()  to show the element before you perform the action.  Example of showing an element in order to perform action  cy . get ( \'.content\' ) . invoke ( \'show\' ) . click ( )   You can also force the action to be performed on the element regardless of whether the element is visible or not.  Example of clicking on a hidden element  cy . get ( \'.content\' ) . click ( { force :   true } )   Example of checking a hidden element  cy . get ( \'.checkbox\' ) . check ( { force :   true } )   Difficult use cases Cypress does not support the following use cases.  Iframes Issue #136  You cannot target elements or interact with anything in an iframe - regardless of it being a same domain or cross domain iframe.  This is actively being worked on in Cypress and you’ll first see support for same domain iframes, followed by cross domain (they are much harder to do).  Workaround  Sit tight, comment on the issue so we know you care about this support, and be patient.  OAuth This is related to the iframe issue above, but basically  oauth  usually will not work. This is one of the hardest things for Cypress to be able to handle as there are so many different implementations and mechanisms.  Likely we will be able to support server side oauth redirects, but for client side popups you’ll use sinon  and  stub  the oauth response directly in your code. This is actually possible to do right now but we don’t have any good docs or tutorials on it.  Workaround  Come into Gitter  and talk to us about what you’re trying to do. We’ll tell you if you’re able to mock this and how to do it.  window.fetch routing and stubbing Issue #95  Support for  fetch  has not been added but it’s possible to handle in the same way as we handle  XHRs . This biggest challenge here is that you can use  fetch  in  Service Workers  outside of the global context. We’ll likely have to move routing to the server and handle it in the proxy layer but it should be possible.  While we currently provide things like the stack trace and initiator line for XHR’s we will not be able to provide that for  fetch .  Workaround  Sit tight, comment on the issue so we know you care about this support, and be patient', 'matchLevel': 'full', 'fullyHighlighted': false, 'matchedWords': ['click', 'issue', '53'] }, 'hierarchy_camel': [{ 'lvl0': { 'value': 'Known Issues', 'matchLevel': 'none', 'matchedWords': [] } }] },
            },
          ], 'nbHits': 1, 'page': 0, 'nbPages': 1, 'hitsPerPage': 5, 'processingTimeMS': 1, 'exhaustiveNbHits': true, 'query': '"click Issue #53" ', 'params': 'query=%22click%20Issue%20%2353%22%20&hitsPerPage=5', 'index': 'cypress',
        },
      ],
    },
  }).as('postAlgolia')
  cy.visit('https://docs.cypress.io')
  cy.get('#search-input').type('g')
  cy.wait('@postAlgolia')
  cy.get('.ds-dropdown-menu').should('be.visible')
})
```

### Versions

3.5.0

### PR DESCRIPTION
**Pull request by flotwig**
### User facing changelog

Fixed a regression where `cy.route` stubs with a response of more than about 8 kilobytes of data would cause an HTTP 431 error to occur. Fixes #5431 

### Additional details

- Temporary workaround for #5452 #5492 
- Most users get the 431 when they are stubbing a large response XHR body
- This is because the XHR response is sent to the backend (for stubbing the actual response body) as a header `X-Cypress-Response`
- This PR makes it so that for responses > 4kb, they will be serialized, sent over the websocket, and then fulfilled with the body asynchronously on the server-side when the request is received
- 4kb was chosen because it is less than the new maximum header size (8kb), and it leaves extra room for things like big `Cookie` headers and `Authorization` headers

### How has the user experience changed?

Large response stubs work.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/server/lib/xhr_ws_server.ts [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+  }
+
+  function getDeferredResponse (id) {
+    debug('getDeferredResponse %o', { id })
+    // if we already have it, send it
+    const res = incomingXhrs[id]
+
+    if (res) {
+      if (res.then) {
+        debug('returning existing deferred promise for %o', { id })
```
Comment (flotwig) [inline packages/server/lib/xhr_ws_server.ts]: Should be a `return res` here

Comment (brian-mann) [reply packages/server/lib/xhr_ws_server.ts]: does this still need to happen?

File: packages/server/lib/xhr_ws_server.ts [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+    .tap((res) => {
+      debug('deferred response found %o', { id, res: trunc(res) })
+    })
+  }
+
+  function reset () {
+    debug('resetting incomingXhrs %o', { length: incomingXhrs.length })
+
+    _.forEach(incomingXhrs, ({ reject }) => {
+      reject(new Error('This stubbed XHR was pending on a stub response object from the driver, but the test ended before that happened.'))
```
Comment (brian-mann) [inline packages/server/lib/xhr_ws_server.ts]: this does not feel correct - tests can end while the XHR is in flight without that being an actual error

File: packages/server/lib/socket.coffee [hunk 3]
```diff
@@ -335,6 +341,8 @@ class Socket
       socket.on "external:open", (url) ->
         require("electron").shell.openExternal(url)
 
+      socket.on "test:before:run:async", options.onBeforeTestRun
```
Comment (brian-mann) [inline packages/server/lib/socket.coffee]: this isn't doing anything

File: packages/server/lib/socket.coffee [hunk 4]
```diff
@@ -132,6 +132,8 @@ class Socket
 
     _.defaults options,
       socketId: null
+      onBeforeTestRun: ->
```
Comment (brian-mann) [inline packages/server/lib/socket.coffee]: i think you meant to write `onResetXhrServer` here

File: packages/runner/src/lib/event-manager.js [hunk 5]
```diff
@@ -296,6 +296,10 @@ const eventManager = {
       })
     })
 
+    Cypress.on('test:before:run:async', () => {
+      Cypress.backend('reset:xhr:server')
+    })
```
Comment (brian-mann) [inline packages/runner/src/lib/event-manager.js]: This should go in `packages/driver/src/cy/commands/xhr.coffee`

Refer to these files as reference:
- packages/driver/src/cy/commands/cookies.coffee
- packages/driver/src/cy/commands/window.coffee

File: packages/server/lib/xhr_ws_server.ts (hunk 2 above)
Comment (flotwig) [reply packages/server/lib/xhr_ws_server.ts]: This is really just to ensure that the HTTP request is closed before creating new tests; otherwise, the connections would pile up until they timed out.

It could also be fulfilled with a successful response, or left to time out.

**Comment by jennifer-shehane** [comment]
Pulling this down to run against Services to see if it fixes their requests.

File: packages/driver/src/cy/commands/xhr.coffee [hunk 6]
```diff
@@ -253,6 +253,9 @@ module.exports = (Commands, Cypress, cy, state, config) ->
     ## reset the existing server
     reset()
 
+    ## reset any state on the backend
+    Cypress.backend('reset:xhr:server')
```
Comment (brian-mann) [inline packages/driver/src/cy/commands/xhr.coffee]: You can't do this because this function is async - Cypress will not await it and everything will be out of band causing race conditions.

You need to explicitly set up a handler for `test:before:run:async` and return this invocation. Refer to my previous messages and links to the other files that do the same things (like cookies).

File: packages/server/lib/xhr_ws_server.ts [hunk 7]
```diff
@@ -11,55 +11,76 @@ function trunc (str) {
   })
 }
 
+type DeferredPromise<T> = {
+  resolve: Function
+  reject: Function
+  p: Bluebird<T>
```
Comment (brian-mann) [inline packages/server/lib/xhr_ws_server.ts]: call this `promise` which mimics the existing `Bluebird.defer()` interface and is consistent with how we use this in other places.

image

File: packages/server/lib/xhr_ws_server.ts [hunk 8]
```diff
@@ -11,55 +11,76 @@ function trunc (str) {
...
 
   function reset () {
-    debug('resetting incomingXhrs %o', { length: incomingXhrs.length })
+    debug('resetting incomingXhrs')
 
-    _.forEach(incomingXhrs, ({ reject }) => {
-      reject(new Error('This stubbed XHR was pending on a stub response object from the driver, but the test ended before that happened.'))
+    _.forEach(incomingXhrResponses, (res) => {
+      if (typeof res !== 'string') {
+        res.reject(new Error('This stubbed XHR was pending on a stub response object from the driver, but the test ended before that happened.'))
```
Comment (brian-mann) [inline packages/server/lib/xhr_ws_server.ts]: if the XHR is in flight during reset, the the server's XHR controller is awaiting a promise... when you reject it unless we handle those exceptions - what will happen?

I would need to review how the XHR does fixture handling / error recovery to know how it will fail, but we need to be careful here.

Perhaps it would be easier to throw a very specific Error instance (with a special property) that the XHR controller code could specifically add a targeted `.catch({ xhrReset: true })` and recover gracefully by killing the socket connection and not giving a response. Should be easy to test too via the `integration/http_integration_spec.coffee` file. You just reset after making sending a request in flight. The connection should close without a response.

File: packages/driver/src/cy/commands/xhr.coffee (hunk 6 above)
Comment (flotwig) [reply packages/driver/src/cy/commands/xhr.coffee]: I thought of that, I figured this would actually work fine, since the "clear" command would be enqueued behind any "set" commands anyways. But I'll change it to be explicit instead of implicit, like you showed.

File: packages/server/lib/controllers/xhrs.coffee [hunk 9]
```diff
@@ -79,10 +87,13 @@ module.exports = {
       {data: bytes, encoding: encoding}
 
   getResponse: (resp, config) ->
+    if resp.then
+      return resp
```
Comment (brian-mann) [inline packages/server/lib/controllers/xhrs.coffee]: reshape the resolved object with the `data` payload and remove it from the other area
