### PR TITLE
fix: switch back to using jquery width/height on element dimensions

### LINKED ISSUE #5239: [develop] dom highlights need to account for box-sizing: border-box
edit: Only occuring in develop due to Jquery upgrade

when element has `box-sizing: border-box`, we need to subtract padding from total height to calculate "content" highlight 

With border-box, without border-box

out2

most css frameworks set `* {box-sizing: border-box}`

### PR DESCRIPTION
**Pull request by Bkucera**
- fix #5239
- partially revert #1229 
- address #1215
### Description of change
- use jquery .width() and height() methods to calculate dimensions of elements for dom highlights

### How the design has changed

before:

after:
image

### Pre-merge Tasks
- [x] fix padding box as well

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/runner/src/lib/dom.js [hunk 1]
```diff
@@ -112,6 +112,11 @@ function addElementBoxModelLayers ($el, $body) {
       obj.left -= dimensions.marginLeft
     }
 
+    if (attr === 'Padding') {
```
Comment (brian-mann) [inline packages/runner/src/lib/dom.js]: why is this necessary? what test would have failed without this?

File: packages/runner/src/lib/dom.js [hunk 2]
```diff
@@ -338,8 +342,8 @@ function isInViewport (win, el) {
   return (
     rect.top >= 0 &&
     rect.left >= 0 &&
-    rect.bottom <= win.innerHeight &&
-    rect.right <= win.innerWidth
+    rect.bottom <= $(win).height() &&
```
Comment (brian-mann) [inline packages/runner/src/lib/dom.js]: I thought we wanted to use `outerHeight` and `outerWidth` here... ? Since that's the entire point of why we moved to use the native methods...

Can you add a test?

File: packages/runner/src/lib/dom.js (hunk 1 above)
Comment (Bkucera) [reply packages/runner/src/lib/dom.js]: both tests would have failed. the Content box (blue) would have been outside the Padding box (green)
