### PR TITLE
fix(net-stubbing): match cy.intercept(url) globs against url+path

### LINKED ISSUE #9379: intercept()'s minimatch glob-matching against routeMatcher url property no longer works
### Current behavior
In Cypress 4.12.1, matching a route (`cy.route()`) with a `url` property that contains a string with minimatch syntax (`*`) works.

In Cypress 6.0.0, using `cy.intercept()` with a `routeMatcher.url` that also contains minimatch syntax fails to match.

The help at https://docs.cypress.io/api/commands/intercept.html#routeMatcher-RouteMatcher says:
> All properties are optional. All properties that are set must match for the route to handle a request. If a string is passed to any property, it will be glob-matched against the request using minimatch.The available routeMatcher properties are listed below:

### Desired behavior
Glob-matching should succeed with string properties passed to `cy.intercept()` in a `routeMatcher`.

### LINKED ISSUE #14256: Replacing cy.route with cy.intercept, having trouble with wildcard use
I'm currently trying to rewrite a test using the deprecated cy.route command to use the cy.intercept command, but I'm having trouble getting the latter to work when using wildcards as part of the service reference. I'm currently running Cypress 6.1.0.

The code below is the old code that works properly.

```js
cy.server()
cy.route('GET', 'services/api/agenda/Appointment?id=**').as('appointmentService')
cy.wait('@appointmentService').should('have.property', 'status', 200)
```

I tried replacing it with the following code, but that results in a time-out:

```js
cy.intercept('GET', 'services/api/agenda/Appointment?id=**').as('appointmentService')
cy.wait('@appointmentService').its('response.statusCode').should('eq', 200)
```

Curiously, if I try using a fixed id like in the code below, it DOES work. (though only once and only if other tests involving that part succeed, which is why I wanted to use a wildcard instead of a fixed id to begin with since the id changes every time a new appointment is created)

```js
cy.intercept('GET', 'services/api/agenda/Appointment?id=35').as('appointmentService')
cy.wait('@appointmentService').its('response.statusCode').should('eq', 200)
```

Is this a technical issue or does the intercept command handle wildcards differently that I missed?

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #9379 
- Closes #14256

### Additional details

- adds a `matchUrlAgainstPath` property to RouteMatcher
	- allows differentiating `cy.intercept(url)` from `cy.intercept({ url })` or `cy.intercept({ path })`
	- also follows old `cy.route` behavior by applying a `/` prefix to un-prefixed `url` values that are being matched against a path - old behavior: https://github.com/cypress-io/cypress/blob/ad194de98ffbbcdf687aa7c6c64b1cc1f6690a94/packages/driver/src/cypress/server.js#L296-L301

### How has the user experience changed?

now works as described in https://github.com/cypress-io/cypress/issues/9379#issuecomment-742004697

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3424
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/net-stubbing/test/unit/route-matching-spec.ts [hunk 1]
```diff
@@ -41,100 +42,120 @@ describe('intercept-request', function () {
...
+      })
+
+      it('can glob-match against queryparams', function () {
+        tryMatch({
+          proxiedUrl: 'http://foo.com/foo/nested?k=v',
+        }, {
+          matchUrlAgainstPath: true,
+          url: '/*/nested?k=*',
+        })
+      })
```
Comment (flotwig) [inline packages/net-stubbing/test/unit/route-matching-spec.ts:158]: @jennifer-shehane what do you think about this? since it matches against `path`, it matches including querystrings, which means `/*/foo` won't match `/1/foo?a=b` but `/*/foo*` will

File: packages/net-stubbing/lib/external-types.ts [hunk 2]
```diff
@@ -254,6 +250,11 @@ export interface RouteMatcherOptionsGeneric<S> extends RouteMatcherCompatOptions
    * If 'false', only HTTP requests will be matched.
    */
   https?: boolean
+  /**
+   * If `true`, will match the supplied `url` against incoming `path`s.
+   * Cannot be set without `url` or with `path`.
```
Comment (jennifer-shehane) [inline packages/net-stubbing/lib/external-types.ts:255]: Slightly confusing. 😅 

```suggestion
   * Requires a `url` argument. Cannot be used with a `path` argument.
```

File: packages/net-stubbing/test/unit/route-matching-spec.ts (hunk 1 above)
Comment (jennifer-shehane) [reply packages/net-stubbing/test/unit/route-matching-spec.ts:158]: I feel like this is expected.

File: packages/driver/src/cy/net-stubbing/add-command.ts [hunk 3]
```diff
@@ -133,6 +137,16 @@ function validateRouteMatcherOptions (routeMatcher: RouteMatcherOptions): { isVa
...
 
+  if (routeMatcher.matchUrlAgainstPath) {
+    if (!routeMatcher.url) {
+      return err('`matchUrlAgainstPath` requires a `url` to be specified.')
+    }
+
+    if (routeMatcher.path) {
+      return err('`matchUrlAgainstPath` and `path` cannot both be set.')
+    }
+  }
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/net-stubbing/add-command.ts:148]: Can you add tests for these?

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Can you add a test for passing `matchUrlAgainstPath: false` to ensure this will strictly match against the url if set to false?

Should be good to merge after my comments are addressed.

**Review by jennifer-shehane — APPROVED** [review]

**Review by jennifer-shehane — DISMISSED** [review]
