### PR TITLE
fix: only take snapshots if the AUT document is in state

### LINKED ISSUE #24506: Improve cy.origin time travel snapshots
### What would you like?

Since Cypress 10.9.0, the implementation for cy.origin snapshots needs to be revisited. Currently, in transitionary states, the snapshots do not provide a lot of value and show a cypress-in-cypress snapshot. Ideally, a snapshot of the transition should be shown, and if not available, no snapshot should be taken. 

### Why is this needed?

This is important for cy.origin user experience to continue a good experience of time travel debugging 

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #24506 

### User facing changelog
Interactive time travel snapshots no longer capture all of Cypress application when Application Under Test frame has navigated away. 

### Additional details
Main thing this is fixing is new behavior introduced  in `10.9.0` likely with #23297 where there is now async behavior from when snapshots are taken vs what document is loaded in state. This was leading to Cypress in Cypress like snapshots, which don't provide the user a lot of value and are confusing. This PR makes sure either the document is in state or the snapshot is coming from a cross origin spec bridge (cy.origin).

##### before fix
snapshot-before-fix

##### after fix
snapshot-after-fix

### PR Tasks

- [x] Have tests been added/updated? (tests to make sure no regressions in snapshot behavior are passing)
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?N/A
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by mjhenkes — APPROVED** [review]

**Review by chrisbreiding — COMMENTED** [review]
Is it possible to add a test for this?

**Comment by AtofStryker** [comment]
> Is it possible to add a test for this?

I think we can but I am not sure it will be reliable. Maybe a test that executes a visit away from the primary domain and checks the log snapshot to see if one exists, and if one does, fail the test?

**Comment by chrisbreiding** [comment]
> I think we can but I am not sure it will be reliable. Maybe a test that executes a visit away from the primary domain and checks the log snapshot to see if one exists, and if one does, fail the test?

It doesn't necessarily have to be a full e2e test. More of unit/integration test [like these](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cy/snapshot.cy.js) would still give us some coverage.

**Comment by AtofStryker** [comment]
> > I think we can but I am not sure it will be reliable. Maybe a test that executes a visit away from the primary domain and checks the log snapshot to see if one exists, and if one does, fail the test?
> 
> It doesn't necessarily have to be a full e2e test. More of unit/integration test [like these](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cy/snapshot.cy.js) would still give us some coverage.

sounds good to me. I added a small integration test to make sure the snapshots are null after the document unloads as well as an e2e test to make sure cy origin snapshots still work in [97da4aa](https://github.com/cypress-io/cypress/pull/24519/commits/97da4aa9e9ff9233720c50f0908e0bf892189a36)

File: packages/driver/src/cy/snapshots.ts [hunk 1]
```diff
@@ -229,6 +229,11 @@ export const create = ($$: $Cy['$$'], state: StateFunc) => {
 
   const createSnapshot = (name, $elToHighlight, preprocessedSnapshot) => {
     Cypress.action('cy:snapshot', name)
+    // only take a snapshot if the AUT document is in state to prevent cypress-in-cypress like snapshots
+    // or if the snapshot has been taken in a spec bridge and has already been preprocessed
```
Comment (chrisbreiding) [inline packages/driver/src/cy/snapshots.ts]:
```suggestion
    // when using cy.origin() and in a transitionary state, state('document')
    // can be undefined, resulting in a bizarre snapshot of the entire Cypress
    // UI. better not to take the snapshot in that case.
    // https://github.com/cypress-io/cypress/issues/24506
    // also, do not take the snapshot here if it has already been taken and
    // preprocessed in a spec bridge.
```

Trying to give a little more context for the sake of future engineers and even us when we've forgotten the reason for this. Might be good to add a screenshot of the previous behavior to the issue for posterity.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/snapshots.ts [hunk 2]
```diff
@@ -229,6 +229,11 @@ export const create = ($$: $Cy['$$'], state: StateFunc) => {
...
+    if (!preprocessedSnapshot && !state('document')) {
+      return null
+    }
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/snapshots.ts:240]: Does this fix just mean there are more missing screenshots? Can you share a few scenarios this is currently broken? I'd like to test the before & after locally. Does the comment on line 249 no long valid? This is where we are falling back to `window.document`....would it be more appropriate to query for the AUT iframe?

Comment (emilyrohrbough) [reply packages/driver/src/cy/snapshots.ts:240]: ~I am also wondering if we should update some of our origin tests to verify there are snapshots / no snapshots for various scenarios.~

I didn't realize the updated tests were specific to origin tests for snapshot. Will be exicted to merge these someday 😄

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts [hunk 3]
```diff
@@ -2,107 +2,153 @@
...
-      cy.wait('@fooBarBaz')
+      cy.get(`[data-cy="assertion-header"]`)
     })
 
     cy.shouldWithTimeout(() => {
-      const xhrLogFromSecondaryOrigin = findLog(logs, 'xhr', 'http://localhost:3500/foo.bar.baz.json')?.get()
+      const getLogFromSecondaryOrigin = findLog(logs, '[data-cy="assertion-header"]')?.get()
 
-      expect(xhrLogFromSecondaryOrigin).to.not.be.undefined
+      expect(getLogFromSecondaryOrigin).to.not.be.undefined
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]:
```suggestion
      expect(getLogFromSecondaryOrigin).to.be.defined
```

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts [hunk 4]
```diff
@@ -2,107 +2,153 @@
...
+  })
+
+  it('takes snapshots from the secondary origin even after the primary AUT has been unloaded from state', () => {
+    const findLog = (logMap: Map<string, any>, selector) => {
+      return Array.from(logMap.values()).find((log: any) => {
+        const props = log.get()
 
-  beforeEach(() => {
-    logs = new Map()
+        return (props?.consoleProps?.Selector === selector)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:20]: What log is this associated with?

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts [hunk 5]
```diff
@@ -2,107 +2,153 @@
...
+        const snapshots = xhrLogFromSecondaryOrigin.snapshots.map((snapshot) => snapshot.body.get()[0])
+
+        snapshots.forEach((snapshot) => {
+          expect(snapshot.querySelector(`[data-cy="assertion-header"]`)).to.have.property('innerText').that.equals('Making XHR and Fetch Requests behind the scenes if fireOnload is true!')
+        })
+      })
     })
 
-    cy.visit('http://www.foobar.com:3500/fixtures/xhr-fetch-requests.html')
+    it('Does not take snapshots of XHR/fetch requests from secondary origin if the wrong origin is / origin mismatch, but instead the primary origin (existing behavior)', {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: I read this 2x and am a little confused

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts [hunk 6]
```diff
@@ -2,107 +2,153 @@
...
+
+      cy.visit('http://www.foobar.com:3500/fixtures/xhr-fetch-requests.html')
+
+      cy.origin('http://www.barbaz.com:3500', () => {
+        // need to set isInteractive in the spec bridge in order to take xhr snapshots in run mode, similar to how isInteractive is set within support/defaults.js
+        // @ts-ignore
+        Cypress.config('isInteractive', true)
+
+        cy.get(`[data-cy="assertion-header"]`).should('exist')
+        cy.wait('@fooBarBaz')
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:153]: Is this failing because the alias does not exist?

Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:153]: NVM coming from beforeEach

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts [hunk 7]
```diff
@@ -2,107 +2,153 @@
...
+        expect(snapshots.length).to.equal(2)
+
+        // TODO: Since we have two events, one of them does not have a request snapshot
+
+        expect(snapshots[1].querySelector(`[data-cy="assertion-header"]`)).to.have.property('innerText').that.equals('Making XHR and Fetch Requests behind the scenes if fireOnload is true!')
+      })
+    })
+
+    // TODO: fix flaky test https://github.com/cypress-io/cypress/issues/23437
+    it.skip('verifies fetch requests made while a secondary origin is active eventually update with snapshots of the secondary origin', () => {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:104]: Are we able to unskip these tests? Maybe add some retries?

File: packages/driver/src/cy/snapshots.ts (hunk 2 above)
Comment (chrisbreiding) [reply packages/driver/src/cy/snapshots.ts:240]: > Does the comment on line 249 no long valid? This is where we are falling back to window.document

That's a good question. Seems like [these lines](https://github.com/cypress-io/cypress/blob/7c5ab8a9c4cdf58a5d3fa02870d72c2206cb9036/packages/driver/src/cy/snapshots.ts#L253-L254) should be updated/removed.

> would it be more appropriate to query for the AUT iframe?

I think if there's no `state('document')`, it won't be possible because that means we don't have synchronous access to the AUT.

Comment (AtofStryker) [reply packages/driver/src/cy/snapshots.ts:240]: This actually brings up a good point, but I think it needs to stay. Main reason is logs streaming in from the secondary need to be cloned off a document, which in this case the primary document state is unloaded. But the backup isn't the AUT document in this case, rather the actual top document, which is OK since we only using the window to clone the node. If anything, we should probably use `window.document` here instead of `state("document")`

I'll play around with this to make sure it works as expect and will add a comment to explain this logic

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: I am not sure why but I cannot get this type to show up in a chai assertion. I don't think it is actually valid 🙁

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:20]: In this case ,we are just digging out the `[data-cy="assertion-header"]` get log to make sure the snapshot is sent back over and not omitted with our new logic changes

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: I think this is missing the word `visited` in the name. I can add it.

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 7 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:104]: Let me revisit this and see what the current state is

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 3 above)
Comment (chrisbreiding) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: Yeah, doesn't seem to be a [bundled chai assertion](https://www.chaijs.com/api/bdd/), but we add on to chai with various libs, so it's possible it ends up as an assertion somehow, since we do use `to.be.defined` in a few other tests. I think the "correct" assertion is `.to.exist`.

File: packages/driver/src/cy/snapshots.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/driver/src/cy/snapshots.ts:240]: > Does this fix just mean there are more missing screenshots? Can you share a few scenarios this is currently broken? I'd like to test the before & after locally.

@emilyrohrbough you can run the snapshot tests from the driver locally, but the impact isn't exactly super noticeable there. Do you have `cypress-origin-providers` set up at all?

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 7 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:104]: So I can get the tests to pass, but from the [flake report](https://github.com/cypress-io/cypress/issues/23437) the flake is fairly rare, like 2%. I think by default we already retry twice in CI, so I doubt it will fix the problem immediately. @mjhenkes and I were able to reproduce this a few months back, and if I remember correctly there were collisions with the proxy logging on xhr request. I could be completely wrong though. It's been a while 😅

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: addressed in 1d4323475b

File: packages/driver/src/cy/snapshots.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/driver/src/cy/snapshots.ts:240]: Added comments in 228cef0524. I kept the current logic of using loaded document in state first before the specbridge/root document because of how many edge cases exist in snapshot code that could potentially break, but not be caught by this change. Here be 🐉 s.

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 7 above)
Comment (mjhenkes) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:104]: it's possible this gets resolved by removing server/route, but i'm not 100%. I vote we revisit the flake tests after 12.0.0

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts]: updated to `to.exist` in 17d37f56ec

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 4 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:20]: Is that associated with the origin command log or an xhr log?

File: packages/driver/src/cy/snapshots.ts (hunk 2 above)
Comment (emilyrohrbough) [reply packages/driver/src/cy/snapshots.ts:240]: I can easily setup ` cypress-origin-providers` but even if I run the driver tests, what would I be looking for to verify this was acutally fixed? xhr requests?

File: packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/snapshots.cy.ts:20]: origin command log since the get is invoked inside the cy.origin

File: packages/driver/src/cy/snapshots.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/driver/src/cy/snapshots.ts:240]: If you run the `snapshots.cy.ts` inside the `origin` driver tests, hover over the `(page load)` or `(new url)` logs to see no snapshot taken, where as before it would look something like this:
Screen Shot 2022-11-04 at 1 07 54 PM

**Comment by AtofStryker** [comment]
@chrisbreiding @emilyrohrbough this should be ready for another look. I forgot I needed to set `isInteractive` inside `cy.origin` to receive snapshots

**Review by chrisbreiding — APPROVED** [review]
