### PR TITLE
fix: Show stacks and code frames in specs named with spaces

### LINKED ISSUE #7553: Specs named with spaces have malformed stacks and no code frames for errors
### Current behavior:

If a test fails or there is an error in a spec that has a space in its name, the following issues occur:

- The error stack does not point to the user code as it should
  - This also makes it impossible to open in IDE
- The stack line has `undefined:NaN` instead of `<line>:<column>` (_edit (7/9/20): only happens in `develop`_)
- The code frame does not display

Screen Shot 2020-06-01 at 9 51 52 AM

### Desired behavior:

Errors should display properly regardless of file naming conventions.

### Test code to reproduce

- Create a spec file with a space in its name (e.g. `cypress/integration/with space_spec.js`)
- Make it fail

```javascript
it('fails', () => {
  expect('actual').to.equal('expected')
})
```

### Versions

Cypress 4.6.0+

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #7553

### User facing changelog

- Fixed an issue where stacks and code frames would not appear properly for spec paths that included spaces.

### Additional details
* Why was this change necessary? => stacks and code frames didn't work properly when there are spaces in the file name.
* What is affected by this change? => N/A
* Any implementation details to explain? => When there are spaces, they weren't encoded to be handled properly. This PR solves the problem by encoding before extracting a sourcemap and decoding before showing the file name in the codeframe. 

### How has the user experience changed?
**Before:**

image

**After:**

Screenshot from 2020-11-16 15-52-30

### PR Tasks

* [x] Have tests been added/updated?
* [ ] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/reporter/src/errors/error-stack.tsx [hunk 1]
```diff
@@ -42,6 +43,10 @@ const ErrorStack = observer(({ err }: Props) => {
 
   let stopLinking = false
   const lines = _.map(stackLines, (stackLine, index) => {
+    if ((stackLine as ParsedStackFileLine).column) {
```
Comment (chrisbreiding) [inline packages/reporter/src/errors/error-stack.tsx:46]: Why only decode the file paths if there is a `column` property?

Comment (sainthkh) [reply packages/reporter/src/errors/error-stack.tsx:46]: There are 2 types of `stackLine`: `ParsedStackFileLine` and `ParsedStackMessageLine`. And one of the properties that `ParsedStackFileLine` has but `ParsedStackMessageLine` doesn't is `column`. I wanted to say "if the type of stackLine is ParsedStackFileLine". 

It's the opposite of `(stackLine as ParsedStackMessageLine).message != null` below. 

I didn't leave any comments because none is used for `(stackLine as ParsedStackMessageLine).message != null` lines. But it may be better to have one.

Comment (chrisbreiding) [reply packages/reporter/src/errors/error-stack.tsx]: I see. I refactored it a bit to abstract the `isMessageLine()` check and also made that specific condition unnecessary because once you get farther down in this function, it's guaranteed the line will be a `ParsedStackFileLine` (we return early if it's a message line). 

One thing to keep in mind with a condition like that is that if `column === 0`, the condition will falsely fail, so `column != null` would be a safer way to go.

**Review by chrisbreiding — APPROVED** [review]
