### PR TITLE
fix: Add support for system node 17

### LINKED ISSUE #18914: Cypress 9.0.0 + Node 17.1 (Win 11) Crashes
### Current behavior

Setup:
- Windows 11
- Node/NPM installed via Windows Binary Zip (64bit) into a predefined folder, included in the PATH so npm, etc, can be called from anywhere
- Cypress installed as completely vanilla (i.e. `npx cypress cache clear && npx cypress install && npx cypress open`) - no other config or setup changes at all

When I use Cypress 9.0.0 and Node 17.1 (i.e. latest versions), Cypress opens up and displays the sample tests, but clicking any one of them results in the following error (non-important folder names redacted for privacy):

**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`[appDir]\cypress\plugins\index.js`)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`[appDir]\cypress\plugins\index.js`)
    at Object.get (C:\Users\[user]\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\errors.js:1043:15)
    at EventEmitter.handleError (C:\Users\[user]\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\plugins\index.js:189:20)
    at EventEmitter.emit (node:events:394:28)
    at ChildProcess.<anonymous> (C:\Users\[user]\AppData\Local\Cypress\Cache\9.0.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (node:events:394:28)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

```

If I downgrade either/both to Cypress 8.7, or Node 16.13 (LTS version), then everything works fine and as expected, i.e.
- Cypress 8.7 + Node 17.1 works
- Cypress 9.0 + Node 16.13 works
- Cypress 8.7 + Node 16.13 works

### Desired behavior

Cypress 9.0 should run as expected with Node 17.1

### Test code to reproduce

No test code required, it'll fail running the examples

### Cypress Version

9.0.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes #18914

### User facing changelog
When using the default configuratation of `"nodeVersion": "system"` with an installed system node >=17, cypress will now work properly rather than throw an error incorrectly pointing to the user's plugin file.

### Additional details
Previously, users could work around this by setting `NODE_OPTIONS=--openssl-legacy-provider`. We now apply this workaround by default when detecting system node version 17.

### How has the user experience changed?
image

This error no longer occurs when attempting to run spec files. It incorrectly points to the user's plugin file as the cause, while this was actually a bug with Cypress' bundled webpack.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? N/A
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)? N/A
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)? N/A

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

File: packages/server/lib/plugins/index.js [hunk 1]
```diff
@@ -37,6 +38,43 @@ const registerHandler = (handler) => {
...
+  // If we're on node version 17 or higher, we need the
+  // NODE_ENV --openssl-legacy-provider so that webpack can continue to use
+  // the md4 hash function. This would cause an error prior to node 17
+  // though, so we have to detect node's major version before spawning the
+  // plugins process.
+
+  // To be removed on update to webpack >= 5.61, which no longer relies on
+  // node's builtin crypto.hash function.
+  if (semver.satisfies(config.resolvedNodeVersion, '>=17.0.0')) {
+    childOptions.env.NODE_OPTIONS += ' --openssl-legacy-provider'
```
Comment (mjhenkes) [inline packages/server/lib/plugins/index.js:65]: is it possible for users to bring their own version of webpack?

Comment (mjhenkes) [reply packages/server/lib/plugins/index.js:65]: If so, could we check to see if they're using our version or theirs before adding the option?

Comment (mjhenkes) [reply packages/server/lib/plugins/index.js:65]: actually i'm not sure that really matters, this is probably fine

**Review by mjhenkes — APPROVED** [review]

File: packages/server/lib/plugins/index.js (hunk 1 above)
Comment (BlueWinds) [reply packages/server/lib/plugins/index.js:65]: I believe that while they can bring their own webpack *config*, but not version. And if I'm wrong and they can, it should still be harmless to add the arg.

**Comment by aeneasr** [comment]
For me, Cypress 9.1.1 fails on macOS Monterey on a M1 with:

```
> cypress open --browser chrome "--config" "integrationFolder=cypress/integration"

/opt/homebrew/Cellar/node/17.2.0/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

Is this a regression of this PR?
