### PR TITLE
fix(vite-dev-server): do not use incremental esbuild option with Vite v4.2.0+

### LINKED ISSUE #26138: vite-dev-server specifies invalid esbuild option `incremental` for Vite 4.2.0
Vite updated esbuild to [v0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0) which removes the `incremental` build option that we set in `vite-dev-server` https://github.com/cypress-io/cypress/blob/a63a474baa81db55c065902ade716f45bc489ffb/npm/vite-dev-server/src/resolveConfig.ts#L87

The result is that when you try to run a Cypress test with a project that is using Vite 4.2.0, you get this error message in the logs:
```
[vite] error while updating dependencies:
Error: Context failed with 1 error:
/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in context() call: "incremental"
    at failureErrorWithLog (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:953:16
    at responseCallbacks.<computed> (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/adams/projects/cypress-component-testing-apps/react-vite-ts/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
Along with this error in the command log

Fix component testing with Vite by removing the now invalid `incremental` esbuild option and figure out how to maintain the same build behavior.

### PR DESCRIPTION
**Pull request by astone123**
- Closes https://github.com/cypress-io/cypress/issues/26138 

### Additional details

Vite updated esbuild to [v0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0) which removes the incremental build option that we set in vite-dev-server. This PR makes it so that property is removed from the Vite config if the Vite version is at least 4.2.0.

### Steps to test

I updated all of our monorepo packages to use Vite 4.2.0, so if those tests run successfully then we're good

### How has the user experience changed?

CT tests will now run with Vite 4.2.0

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 1]
```diff
@@ -79,28 +80,34 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
     paths: [projectRoot],
   })))
 
+  const esbuildOptions: { incremental?: boolean, plugins: any[] } = {
```
Comment (astone123) [inline npm/vite-dev-server/src/resolveConfig.ts]: I couldn't figure out where to get the types for this 🤔

Comment (lmiller1990) [reply npm/vite-dev-server/src/resolveConfig.ts]: Yeah, me either.

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@
 import debugFn from 'debug'
 import type { InlineConfig } from 'vite'
 import path from 'path'
+import semverGte from 'semver/functions/gte'
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/resolveConfig.ts:9]: do we need to add `semver` to the `vite-dev-server/package.json`?

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 3]
```diff
@@ -79,28 +80,34 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
...
+            // See: https://github.com/cypress-io/cypress/pull/21599
+            result.warnings = [...result.warnings, ...result.errors]
+            result.errors = []
+          })
+        },
+      },
+    ],
+  }
+
+  if (vite.version && semverGte(vite.version, '4.2.0')) {
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/resolveConfig.ts]: I also found out we can do `vite.esbuildVersion`, that would be another option, but what you are doing is probably better.

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 4]
```diff
@@ -79,28 +80,34 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
...
+    delete esbuildOptions.incremental
+  }
+
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/resolveConfig.ts]: I think we can preserve the type safety a bit more, how about instead of add/delete, just add if needed:

```js
  const conf: InlineConfig = {
    root: projectRoot,
    base: `${devServerPublicPathRoute}/`,
    optimizeDeps: {
      esbuildOptions: {
        plugins: [
          {
            name: 'cypress-esbuild-plugin',
            setup (build) {
              build.onEnd(function (result) {
                // We don't want to completely fail the build here on errors so we treat the errors as warnings
                // which will handle things more gracefully. Vite will 500 on files that have errors when they
                // are requested later and Cypress will display an error message.
                // See: https://github.com/cypress-io/cypress/pull/21599
                result.warnings = [...result.warnings, ...result.errors]
                result.errors = []
              })
            },
          },
        ],
      },
      entries: [
        ...specs.map((s) => path.relative(projectRoot, s.relative)),
        ...(supportFile ? [path.resolve(projectRoot, supportFile)] : []),
      ].filter((v) => v != null),
    },
    // ... other stuff ...
   
  }

  // add it here
  if (vite_version > 4.2.0 ^^ conf?.optimizeDeps?.esbuildOptions) {
    conf.optimizeDeps.esbuildOptions.incremental = true
  }

  return conf
```

File: npm/vite-dev-server/src/resolveConfig.ts (hunk 1 above)
Comment (lmiller1990) [reply npm/vite-dev-server/src/resolveConfig.ts]: Can we update the entire repo to use Vite 4.2.0? (packages/app, packages/launchpad, etc)?

Comment (lmiller1990) [reply npm/vite-dev-server/src/resolveConfig.ts]: We wouldn't need the system test either then - we'd have the core repo tests.

File: npm/vite-dev-server/src/resolveConfig.ts (hunk 4 above)
Comment (astone123) [reply npm/vite-dev-server/src/resolveConfig.ts]: Good idea, thanks

**Review by lmiller1990 — APPROVED** [review]
Looks good, could drop the Vite system test I think...

File: cli/CHANGELOG.md [hunk 5]
```diff
@@ -1,4 +1,12 @@
 <!-- See the ../guides/writing-the-cypress-changelog.md for details on writing the changelog. -->
+## 12.9.0
+
+_Released 03/28/2023 (PENDING)_
+
+**Bugfixes:**
+
+ - Dropped the `incremental` esbuild option from our Vite dev server configuration after Vite 4.2.0. Fixes [#26138](https://github.com/cypress-io/cypress/issues/26138).
```
Comment (mike-plummer) [inline cli/CHANGELOG.md]: - Dropped the `incremental` esbuild option from our Vite dev server configuration after Vite 4.2.0. Fixes [#26138](https://github.com/cypress-io/cypress/issues/26138).
```suggestion
 - Fixed a compatibility issue so that component test projects can use [Vite](https://vitejs.dev/) version 4.2.0 and greater. Fixes [#26138](https://github.com/cypress-io/cypress/issues/26138).
```

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 6]
```diff
@@ -79,12 +80,11 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
     paths: [projectRoot],
   })))
 
-  return {
+  const viteConfig: InlineConfig = {
```
Comment (mike-plummer) [inline npm/vite-dev-server/src/resolveConfig.ts:83]: I was going to suggest using the `satisfies` operator so the `!` assertions wouldn't be necessary below, but apparently our linter config doesn't know about it yet 😢 .

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 7]
```diff
@@ -128,4 +128,12 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
       CypressSourcemap(config, vite),
     ],
   }
+
+  if (!vite.version || !semverGte(vite.version, '4.2.0')) {
+    // We are using Vite 4.2.0+, so `incremental` doesn't exist in the types
+    // @ts-expect-error
+    viteConfig.optimizeDeps!.esbuildOptions!.incremental = true
```
Comment (mike-plummer) [inline npm/vite-dev-server/src/resolveConfig.ts]: I think if we reverse the logic we don't need the `!` assertions or the `@ts-expect`. Have `incremental: true` in the base config, then `delete` if version > 4.2.0

`delete viteConfig.optimizeDeps?.esbuildOptions?.incremental`

**Review by mike-plummer — APPROVED** [review]
Nothing blocking, just a couple stylistic suggestions

File: npm/vite-dev-server/src/resolveConfig.ts (hunk 7 above)
Comment (astone123) [reply npm/vite-dev-server/src/resolveConfig.ts]: yeah that makes sense. I reversed the logic there, should help prevent runtime errors if something changes with the config object above

**Comment by reintroducing** [comment]
@lmiller1990 @astone123 This looks like it has been released, but I just bumped all of my dependencies to the latest (Vite and Cypress) and am still running into the same error:
Screenshot 2023-03-21 at 11 36 13 AM
Should this be working now? My dependencies are as follows:
```
"@cypress/code-coverage": "3.10.0",
"@cypress/vite-dev-server": "5.0.5",
"@nabla/vite-plugin-eslint": "1.5.0",
"@testing-library/cypress": "9.0.0",
"@testing-library/react": "14.0.0",
"@vitejs/plugin-react": "3.1.0",
"cypress": "12.8.1",
"cypress-axe": "1.4.0",
"start-server-and-test": "2.0.0",
"vite": "4.2.1",
"vite-plugin-istanbul": "4.0.1",
"vite-plugin-stylelint": "4.3.0"
```

**Comment by astone123** [comment]
hey @reintroducing, this has not yet been released. It has been merged into our main branch and will go out with the next Cypress release.

**Comment by reintroducing** [comment]
@astone123 my apologies, I looked at the release notes [here](https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/CHANGELOG.md) and was under the impression this was already published. do you by any chance have a timeline for this release?

**Comment by lmiller1990** [comment]
We did a release last week and do a release every 2 weeks, so in around 1 week time 🚀

**Comment by reintroducing** [comment]
@lmiller1990 got it, thank you. So I assume it’s safe to say the release notes I linked to in my prior comment are incorrect and that was not actually part of the release on 3/20 (v5.0.5)?

**Comment by lmiller1990** [comment]
Hmm, good point, since those are also released on npm individually, I think you could manually install the latest https://www.npmjs.com/package/@cypress/vite-dev-server/v/2.2.1 and wire it up, something like:

```js
const { defineConfig } = require("cypress");
const viteDevServer = require("@cypress/vite-dev-server");

module.exports = defineConfig({
  component: {
    devServer(cypressConfig) {
      return viteDevServer.devServer({ cypressConfig });
    },
  }
});
```

You won't be able to use the `bundler: 'vite'` style API if you do it this way. If you are (really) eager to use Vite 4.2, you could do this, but unless it's really pressing, I'd recommend using 4.1 until roughly 1 week, when the main Cypress binary is released, which will include the patch to Vite Dev Server.

Is there something exciting in Vite 4.2 or do you just want to keep everything up to date?

**Comment by reintroducing** [comment]
Just keeping everything up to date. I’m in no rush so I can patiently await the next release no problem, just wanted to make sure I wasn’t misunderstanding the release notes and assuming it was fixed in that release but still having issues. I’ll wait on the next release and confirm everything is good to go.

**Comment by reintroducing** [comment]
@lmiller1990 i can confirm this is fixed with the latest release. Thank you.

**Comment by lmiller1990** [comment]
Great!

Still trying to figure out https://github.com/cypress-io/cypress/issues/25913 ...
