### PR TITLE
fix: added validation for timeout for query operations

### LINKED ISSUE #29323: If anything but a number is passed as the timeout option on cy.get(), the test never reaches the failure state
### Current behavior

Passing something that is not a number to the timeout field causes what should be a failing test never to reach the failure state.

### Desired behavior

If the option is not a valid number, ignore it and apply the default timeout (AFAIK 4s). 

### Test code to reproduce

https://github.com/bernardodomingues-hotmart/cypress-test-tiny

### Cypress Version

13.7.3

### Node version

v20.12.2

### Operating System

macOS 13.6.6 / Docker cypress-included

### Debug Logs

_No response_

### Other

Even though we should have TS for type checking, old codebases are still in JS. This was caused by a developer error when creating custom commands, but there should be a safety net, as IMHO is better for a test to fail fast than never finish. This in a CI environment was a disaster :)

### PR DESCRIPTION
**Pull request by percytrar**
- Closes #29323 

### Additional details

When an invalid `timeout` value like `{}` is passed in `options` to a query method like `get` it resulted in infinite waiting, the test simply didn't timed out.
Affects query methods - `get`, `shadow` and `contains`

### Steps to test

Add this to the `querying.cy.js` test file
```javaScript
cy.get('#some-el', { timeout: {} })
```
### How has the user experience changed?

Before fix -
Screenshot 2024-04-14 at 11 42 32 AM

After fix -
Screenshot 2024-04-14 at 11 37 35 AM

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cy/commands/querying/querying.ts [hunk 1]
```diff
@@ -142,13 +142,21 @@ function getAlias (selector, log, cy) {
 }
 
 export default (Commands, Cypress, cy, state) => {
+  function validateTimeoutFromOpts (options: GetOptions | ContainsOptions | ShadowOptions = {}) {
+    if (_.isPlainObject(options) && options.hasOwnProperty('timeout') && !_.isFinite(options.timeout)) {
+      $errUtils.throwErr(new Error(`contains invalid timeout - ${options.timeout}`))
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/commands/querying/querying.ts]: Typically we keep error messages within our [`error_messages.ts` file](https://github.com/cypress-io/cypress/blob/a11y-fix-3/packages/driver/src/cypress/error_messages.ts#L144) and call into that to throw the error message (for simplicity). You can see an example of this in line 153 of this same file. Could you refactor this to put the message there?

For the error message, to match other error messages to give the user all the info they need to fix it, I would suggest: 

```
{{cmd}} only accepts a number for its `timeout` option. You passed: \`{{timeout}}\`
```

So that for the user it will print:

```
`cy.get` only accepts a number for its `timeout` option. You passed: `abc`
```

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 2]
```diff
@@ -18,6 +18,64 @@ describe('src/cy/commands/querying', () => {
       })
     })
 
+    describe('should throw when timeout is not a number', () => {
```
Comment (jennifer-shehane) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:21]: Thanks for adding tests!

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@percytrar Thanks for the contribution. I have some suggestions on the error message.

File: packages/driver/src/cy/commands/querying/querying.ts (hunk 1 above)
Comment (percytrar) [reply packages/driver/src/cy/commands/querying/querying.ts]: Thanks for the info, added new error msgs 👍

**Comment by percytrar** [comment]
After updating error messages - 
Screenshot 2024-04-15 at 11 55 23 PM

File: packages/driver/src/cy/commands/querying/querying.ts (hunk 1 above)
Comment (percytrar) [reply packages/driver/src/cy/commands/querying/querying.ts]: This is addressed.

**Review by jennifer-shehane — APPROVED** [review]
The types seem to already correctly warn when timeout is invalid. 
Screenshot 2024-04-15 at 2 42 48 PM


Verified locally that this now errors instead of hanging forever when the element is not found. 

#### Before

Screenshot 2024-04-15 at 2 45 53 PM

#### After

Screenshot 2024-04-15 at 2 47 00 PM

**Comment by percytrar** [comment]
How much time does it take for these runs to execute? Or they are run in batch at a particular time of the day?
Screenshot 2024-04-17 at 9 35 05 AM

**Comment by jennifer-shehane** [comment]
@percytrar We have to manually approve all contributor PRs to run to ensure there's nothing nefarious about to run in our CI machines unfortunately, so it just sits there until we push a button.

**Comment by percytrar** [comment]
@jennifer-shehane By when can we expect that this PR will be merged? We need 2 approvals.

File: packages/driver/src/cy/commands/querying/querying.ts [hunk 3]
```diff
@@ -142,13 +144,23 @@ function getAlias (selector, log, cy) {
...
 
 export default (Commands, Cypress, cy, state) => {
+  function validateTimeoutFromOpts (options: GetOptions | ContainsOptions | ShadowOptions = {}, queryCommand: QueryCommandOptions = '') {
+    if (!isEmpty(queryCommand) && _.isPlainObject(options) && options.hasOwnProperty('timeout') && !_.isFinite(options.timeout)) {
+      $errUtils.throwErrByPath(`${queryCommand}.invalid_option_timeout`, {
+        args: { timeout: options.timeout },
+      })
+    }
+  }
+
```
Comment (cacieprins) [inline packages/driver/src/cy/commands/querying/querying.ts]: Since it does not reference any values via closure, it's possible to pull this function up to the top level so it does not get re-created each time the default export is called.

```suggestion

function validateTimeoutFromOpts (options: GetOptions | ContainsOptions | ShadowOptions = {}, queryCommand: QueryCommandOptions = '') {
  if (!_.isEmpty(queryCommand) && _.isPlainObject(options) && options.hasOwnProperty('timeout') && !_.isFinite(options.timeout)) {
    $errUtils.throwErrByPath(`${queryCommand}.invalid_option_timeout`, {
      args: { timeout: options.timeout },
    })
  }
}

export default (Commands, Cypress, cy, state) => {
```

**Review by cacieprins — CHANGES_REQUESTED** [review]

**Comment by cacieprins** [comment]
Just a small performance-related note, otherwise looks good!

File: packages/driver/src/cy/commands/querying/querying.ts (hunk 3 above)
Comment (percytrar) [reply packages/driver/src/cy/commands/querying/querying.ts]: Oh yeah, makes sense.

Comment (percytrar) [reply packages/driver/src/cy/commands/querying/querying.ts]: This is addressed, thanks for the review.

**Review by cacieprins — APPROVED** [review]

File: packages/driver/src/cy/commands/querying/querying.ts (hunk 3 above)
Comment (cacieprins) [reply packages/driver/src/cy/commands/querying/querying.ts]: Thank you!

**Comment by jennifer-shehane** [comment]
@percytrar I'll try to get this merged for the next release.
