### PR TITLE
Escape paths passed by `--browser`

### LINKED ISSUE #3979: Browsers with spaces in the path name cannot be launched from `--browser`
The `--browser=<path>` option introduced in #1026 does not work properly if the path includes spaces. The spaces will not be properly escaped when doing the `--version` call, but will be escaped when launching the actual browser, making it impossible to both detect and launch a browser whose path contains spaces.

Workaround: create a symlink that does not contain spaces to the browser, and use that as the path.

### PR DESCRIPTION
**Pull request by flotwig**
This PR escapes paths passed to `--browser` so that paths with spaces and other special characters will work.

Fixes #3979

### CODE REVIEW

File: packages/server/__snapshots__/2_browser_path_spec.coffee.js [hunk 1]
```diff
@@ -1,3 +1,14 @@
...
+We could not identify a known browser at the path you provided: \`/this/aint/gonna/be/found\`
+
+The output from the command we ran was:
+
+ Command failed: /bin/sh -c "/this/aint/gonna/be/found" --version
+/bin/sh: 1: /this/aint/gonna/be/found: not found
+
+
+`
+
```
Comment (jennifer-shehane) [inline packages/server/__snapshots__/2_browser_path_spec.coffee.js]: @flotwig I updated this snapshot - please review and ensure it's correct.

Comment (flotwig) [reply packages/server/__snapshots__/2_browser_path_spec.coffee.js]: I thought we deleted that snapshot in #4009, this shouldn't be needed anymore.
