### PR TITLE
Fix deprecation warnings from Electron 8 upgrade

### LINKED ISSUE #6750: Deprecation warnings from electron / node during `cypress open`
### Current behavior:

Since updating to 4.2.0, I'm seeing some deprecation warnings in the stdout when running `cypress open`

```
Opening Cypress...
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:87713) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:87713) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

### Desired behavior:

Would like for users of cypress to either not have these deprecation warnings shown to them or fix the usecases so the deprecation warnings do not need to be shown at all.

### Deprecation warnings

I believe all of these originate from https://github.com/cypress-io/cypress/pull/6555

1. Electron https://github.com/electron/electron/issues/18397

	This is being used here, looks like this issue is already noted https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/electron-app.js#L18:L18

2. Node - also coming from Electron. Explanation of this one here: https://www.electronjs.org/docs/breaking-changes#sending-non-js-objects-over-ipc-now-throws-an-exception

### Versions

4.2.0

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6750 

### User facing changelog

- Fixed a regression in 4.2.0 where Electron deprecation warnings were printed to `stderr` in `open` mode.

### Additional details

- now, objects sent via IPC in `open` mode are cloned to exclude functions and elements, to make the Structured Clone Algorithm usable: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
- previously, `allowRendererProcessReuse` was only set in `run` mode, now it's set in `open` mode too to get rid of the warning
- now we set `noDeprecation` when the env is `production`, so no deprecation warnings will be printed in built binaries

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/gui/events.coffee [hunk 1]
```diff
@@ -21,12 +21,23 @@ chromePolicyCheck = require("../util/chrome_policy_check")
 browsers    = require("../browsers")
 konfig      = require("../konfig")
 
+removeUnserializableValues = (obj) =>
+  ## remove values that cannot be cloned
+  ## https://github.com/cypress-io/cypress/issues/6750
+  _.cloneDeepWith obj, (val) =>
+    if _.isFunction(val)
```
Comment (bahmutov) [inline packages/server/lib/gui/events.coffee]: does this need a check against Element?

Comment (flotwig) [reply packages/server/lib/gui/events.coffee]: it's in the `server`, there can't be an `Element`

File: packages/desktop-gui/src/lib/ipc-bus.js [hunk 2]
```diff
@@ -62,6 +62,18 @@ const ipcBus = (...args) => {
   // get the last argument
   const lastArg = args.pop()
 
+  // remove nodes that cannot be cloned
+  // https://github.com/cypress-io/cypress/issues/6750
+  args = args.map((arg) => {
```
Comment (bahmutov) [inline packages/desktop-gui/src/lib/ipc-bus.js]: is there a test for this?

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: no, i can add tests, just wasn't sure where to add them... probably just need to add tests for the `ipc-bus` file

Comment (bahmutov) [reply packages/desktop-gui/src/lib/ipc-bus.js]: it would be nice to send an object from the browser with functions and elements and ping it back from the server - and the receiver would check if the returned object has invalid fields stripped

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: added ipc_bus specs: https://github.com/cypress-io/cypress/pull/6753/files#diff-0bf397162937f0ddea8c95e4dd3e3033

File: packages/desktop-gui/cypress/integration/ipc_bus_spec.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  beforeEach(() => {
+    cy.stub(Math, 'random').returns(RANDOM_NUMBER)
+    cy.stub(window.ipc, 'on').returns()
+    cy.stub(window.ipc, 'send').returns()
+  })
+
+  it('sends event as expected', () => {
+    ipcBus('foo:bar', 'baz', 'quux')
+
+    expect(window.ipc.send).to.be.calledWith('request', RANDOM_NUMBER, 'foo:bar', 'baz', 'quux')
```
Comment (bahmutov) [inline packages/desktop-gui/cypress/integration/ipc_bus_spec.js]: My Zach, since you don't care about the value of the second argument, you can skip stabbing `Math.random` by using Sinon matchers. See https://docs.cypress.io/api/utilities/sinon.html#match-string and https://sinonjs.org/releases/latest/matchers/ and https://github.com/cypress-io/cypress-example-kitchensink/pull/385/files

File: packages/desktop-gui/cypress/integration/ipc_bus_spec.js [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+  it('removes functions & elements from the args', () => {
+    const obj = {
+      el: document.querySelector('div'),
+      fn: () => {},
+      str: 'foo',
+    }
+
+    ipcBus('bar', obj)
+
+    expect(window.ipc.send).to.be.calledWith('request', RANDOM_NUMBER, 'bar', {
```
Comment (bahmutov) [inline packages/desktop-gui/cypress/integration/ipc_bus_spec.js]: nice

File: packages/desktop-gui/src/lib/ipc-bus.js [hunk 5]
```diff
@@ -108,6 +96,16 @@ const ipcBus = (...args) => {
     }
   }
 
+  // remove nodes that cannot be cloned
+  // https://github.com/cypress-io/cypress/issues/6750
+  args = args.map((arg) => {
```
Comment (bahmutov) [inline packages/desktop-gui/src/lib/ipc-bus.js]: can we move the callback into a named function please?

Comment (bahmutov) [reply packages/desktop-gui/src/lib/ipc-bus.js]: and I think the map could avoid extra function then
```
const nullInvalidValue = (val) => {
  if (_.isFunction(val) || _.isElement(val)) {
    return null
  }
}
const cleanArgument = _.partialRight(_.cloneDeepWith, nullInvalidValue)
args = args.map(cleanArgument)
```

File: packages/desktop-gui/cypress/integration/ipc_bus_spec.js (hunk 3 above)
Comment (flotwig) [reply packages/desktop-gui/cypress/integration/ipc_bus_spec.js]: thanks for the links :) i know about matchers, i just preferred this since it asserts that it's a random number

File: packages/desktop-gui/src/lib/ipc-bus.js (hunk 5 above)
Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: extracted to named function, also switched references to `remove` to `nullify`, since it doesn't technically remove unserializable values, it makes them `null`

File: packages/desktop-gui/src/lib/ipc-bus.js [hunk 6]
```diff
@@ -96,15 +106,7 @@ const ipcBus = (...args) => {
...
-  // remove nodes that cannot be cloned
-  // https://github.com/cypress-io/cypress/issues/6750
-  args = args.map((arg) => {
-    return _.cloneDeepWith(arg, (val) => {
-      if (_.isFunction(val) || _.isElement(val)) {
-        return null
-      }
-    })
-  })
+  args = nullifyUnserializableValues(args)
```
Comment (bahmutov) [inline packages/desktop-gui/src/lib/ipc-bus.js]: wait, this used to be a callback to `args.map`, right. Does `nullifyUnserializableValues` properly handle arrays? Does it just recurse into them?

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: oh oops, good catch

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: not sure if cloneDeep will work with the array

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: yes, it should still work with the array, since it uses cloneDeep

Comment (flotwig) [reply packages/desktop-gui/src/lib/ipc-bus.js]: desktop-gui tests will fail if this is wrong
