### PR TITLE
Fix proxy slowdown with intercepted HTTPS requests

### LINKED ISSUE #6659: Network requests taking a long time to complete
### Current behavior:

For us, network requests are taking an extremely long time to complete.   In our application we're seeing requests become 300+ms when running in cypress compared to 30ms running in chrome.   Some longer requests are 10+ seconds in cypress, compared to 600ms in chrome.

To attempt to to verify this wasn't just our application or server, we tried using your smurf page (https://test-page-speed.cypress.io/index1000.html) outlined in your 3.3 blog post https://www.cypress.io/blog/2019/05/22/how-we-improved-network-speed-by-300-in-cypress-3-3-0

We ran this directly in Chrome, and it took 1578ms.   Running a very basic cypress script like this
```js
it('speed test', () => {
  cy.visit('https://test-page-speed.cypress.io/index1000.html')
})
```

and Cypress took `76570ms` to run the same page, which is significantly longer than the chrome version.

### Desired behavior:

Something much faster.  At the moment, this is pretty much unusable for us :(

When doing some digging, it looks like cypress sets the `Transfer_encoding` to be chunked in its response (thru its proxy?). We guess its something to do with this?

Are there any settings we can try to help speed this up?

### Versions
Cypress 4.1

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6659

### User facing changelog

- Fixed a regression introduced in v3.8.3 where HTTPS requests could experience slowdown.

### Additional details

- in #5446, we set the TLS minimum version to TLSv1
- however, this also caused slowdowns in the proxy, which are visible in the `server-performance-spec`s if you look before and after this got merged
- all *intercepted (not passthru) HTTPS* connections were affected
- this PR makes it so that minVersion is set to TLSv1 only if the initial connection failed with a TLS version mismatch error
- this PR also fixes the `proxy_performance_spec`
    - previously, the heuristics it was using were way too loose, and also easy to misunderstand
	- now, it's as simple as "our proxy should never be more than 3x as slow as regular Chrome, under any conditions"
	- 4.5x for the case where our proxy goes through another HTTPS upstream proxy
- also noticed that requests that used an HTTPS upstream were slower - after adding `setNoDelay(true)`, they are slightly faster, though not as fast as requests with an HTTP upstream

### How has the user experience changed?

- faster for everyone,
- except for people who use TLSv1 - but they're in for a reckoning anyways when Chrome 81 and Firefox 74 deprecate their TLSv1 support: https://portswigger.net/daily-swig/tls-1-0-1-1-end-of-life-countdown-heads-into-the-danger-zone
	- this will result in 1 more socket retry per TLSv1 connection. however, Cypress keeps HTTPS sockets alive, so this is only an upfront cost and is not paid on every single request

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by flotwig** [comment]
Used this script to play with `minVersion` outside of Cypress:

```js
/* eslint-disable no-console */
const _ = require('lodash')
const Bluebird = require('bluebird')
const rp = require('request-promise')
const { Agent } = require('https')

const test = async () => {
  await Bluebird.delay(500)

  let agent = new Agent({ keepAlive: false })

  console.time('making 100 https requests')
  await Bluebird.all(_.times(100, async () => {
    await rp('https://weeny.chary.us/static/5MB.zip', { agent, gzip: false })
  }))

  console.timeEnd('making 100 https requests')

  await Bluebird.delay(500)

  agent = new Agent({ keepAlive: false })
  agent.createConnection = function (options, cb) {
    options.minVersion = 'TLSv1'
    cb(null, Agent.prototype.createConnection.call(agent, options))
  }

  console.time('making 100 https requests with minVersion = TLSv1')
  await Bluebird.all(_.times(100, async () => {
    await rp('https://weeny.chary.us/static/5MB.zip', { agent, gzip: false })
  }))

  console.timeEnd('making 100 https requests with minVersion = TLSv1')
}

Bluebird.mapSeries(_.times(1), test)
```

File: packages/server/test/performance/proxy_performance_spec.js [hunk 1]
```diff
@@ -373,12 +374,18 @@ describe('Proxy Performance', function () {
 
       // slice(1) since first test is used as baseline above
       testCases.slice(1).map((testCase) => {
-        it(`${testCase.name} loads 1000 images, with 75% loading no more than 2x as slow as the slowest baseline request`, function () {
+        let multiplier = 3
+
+        if (testCase.httpsUpstreamProxy) {
+          multiplier *= 1.5
```
Comment (brian-mann) [inline packages/server/test/performance/proxy_performance_spec.js]: might be worth calling out why we're doing this
