### PR TITLE
fix: same site cookie context and duplicate cookies

### LINKED ISSUE #23132: Cookie behavior issue after 10.3.0
### Current behavior

localhost cookies are not sent on separate ports. In example we have the following setup:

Frontend -> localhost:5000
API -> localhost:5002
OAUTH2 -> localhost:5005

The frontend does not send cookies to API after 10.3.0 (see flow in extra information).

### Desired behavior

Frontend should be sending API cookies as normal

### Test code to reproduce

N/A

### Cypress Version

10.3.0

### Other

image

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #23132

### User facing changelog
Fixes an issue introduced in `10.3.0` and further exposed in `10.4.0` that omitted same-site cookies when URL Scheme, Domain, and Top Level Domain match, but the ports are different (same-site).

### Additional details
In #22320 we added improved cookie handling that handles cookie management in the proxy server. When we calculate `SameSiteContext`, we were using `SameOriginPolicy` to calculate the context of the request. This is a bit different than `SameSite`, which cookies use to determine context as subdomains and ports do not need to match to [be considered same-site](https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#section-1-3). 

In #22963 we removed the [isAUTFrame](https://github.com/cypress-io/cypress/pull/22963/files#diff-525d773dc9e405242dbb041d386d3b3e6c6c07bb02bb3b4436fb96de5cdb9072L410) check in `checkIfNeedsCrossOriginHandling`. In the case of https://github.com/cypress-io/cypress/issues/23132#issuecomment-1206842968, I think `isAUTFrame` used to evaluate to `false`  for the fetch/XHR requests being made, which leveraged `Set-Cookie` over `X-Set-Cookie`. After `10.4.0`, the check was removed and `X-Set-Cookie` was being used as it believed the requests needed to handle the cookies in a third party context, when in fact they did not. 

Until #23551 is implemented, we should likely use `Set-Cookie`, even if the setting of the actual cookie fails, as we currently cannot discern the difference between requests that are specified in the browser with [XMLHttpRequest Credentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) or [fetch credentials](https://developer.mozilla.org/en-US/docs/Web/API/fetch#credentials) and once that aren't (or use more strict fetch credentials like `same-origin` or `omit`).

### Steps to test
Unit tests were added for functions `getSameSiteContext` in `@packages/proxy` and `urlOriginsMatch`  in `packages/network` to verify the behavior is what we expect.

Unit tests for verifying duplicate cookie behavior and integration tests with tough-cookie were also added to make sure we integrate correctly.

E2E tests were added in `cookie_behavior.cy.ts` to serve as a base for when we explore #23551 to make sure the correct spec behavior is implemented. There are several tests with `FIXME`s as well as comments to what the assertions should be. In the current context, we may optimistically apply cookies to request, as if each request was called `withCredentials` or with `include`d credentials, which the tests should demonstrate. 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/proxy/lib/http/response-middleware.ts [hunk 1]
```diff
@@ -431,17 +430,17 @@ const CopyCookiesFromIncomingRes: ResponseMiddleware = async function () {
...
   // - In the request middleware, we retrieve the cookies for a given URL
   //   and attach them to the request, like the browser normally would.
   //   tough-cookie handles retrieving the correct cookies based on domain,
   //   path, etc. It also removes cookies from the cookie jar if they've expired.
-  const needsCrossOriginHandling = checkIfNeedsCrossOriginHandling(this)
+  const needsThirdPartyHandling = checkIfCookieNeedsThirdPartyHandling(this)
 
   const appendCookie = (cookie: string) => {
-    const headerName = needsCrossOriginHandling ? 'X-Set-Cookie' : 'Set-Cookie'
+    const headerName = needsThirdPartyHandling ? 'X-Set-Cookie' : 'Set-Cookie'
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/response-middleware.ts:443]: nit: Isn't `needsCrossOriginHandling` still representative here? I assume it could be third part, cross origin and/or both?

Comment (AtofStryker) [reply packages/proxy/lib/http/response-middleware.ts:443]: I figured it would be `thirdParty` since the browser should be able to set first party cookies even on _some_ cross origin requests. That being said I am not thrilled about the name I have here 😅 .

File: packages/network/test/unit/cors_spec.ts [hunk 2]
```diff
@@ -211,6 +211,127 @@ describe('lib/cors', () => {
...
 
+  context('.urlOriginsMatch', () => {
+    beforeEach(function () {
+      this.isFalse = (url1, url2) => {
+        expect(cors.urlOriginsMatch(url1, url2)).to.be.false
+      }
+
+      this.isTrue = (url1, url2) => {
+        expect(cors.urlOriginsMatch(url1, url2)).to.be.true
+      }
```
Comment (chrisbreiding) [inline packages/network/test/unit/cors_spec.ts:222]: Maybe `assertOriginsDontMatch` and `assertOriginsMatch` instead? I feel like `isFalse/isTrue` should return whether the argument is false or true.

These could also be defined in the context's scope so there wouldn't be a need to use `this.` everywhere, e.g.:

```js
  context('.urlOriginsMatch', () => {
    const assertOriginsDontMatch = () => { /* ... */ }
    
    it('test', () => {
      assertOriginsDontMatch('https://foo.bar:443', this.url)
      assertOriginsDontMatch('https://foo.bar:80', this.url)
      // .. and so on ...
    })
  })
```

File: packages/proxy/lib/http/response-middleware.ts [hunk 3]
```diff
@@ -420,7 +419,7 @@ const CopyCookiesFromIncomingRes: ResponseMiddleware = async function () {
     return this.next()
   }
 
-  // Cross-origin Cookie Handling
+  // First/Third Party Cookie Handling
```
Comment (chrisbreiding) [inline packages/proxy/lib/http/response-middleware.ts:422]: What does first party and third party mean in this context?

**Review by chrisbreiding — CHANGES_REQUESTED** [review]
The unit tests are great, but could you add a more e2e-style test? Best place is probably [cookie_login.cy.ts](https://github.com/cypress-io/cypress/blob/6e18996d0211a6ee22ca5fb31561e6f3597b2f78/packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts). We could have passing unit tests for an incorrect implementation. A test that actually runs through the browser will give us a bit more confidence it's correct.

File: packages/network/test/unit/cors_spec.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/network/test/unit/cors_spec.ts]: I like that style a lot better. I went through the other tests in `lib/cors` and refactored them in 8404853381

File: packages/proxy/lib/http/response-middleware.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/response-middleware.ts]: resolving this as it is no longer applicable

File: packages/proxy/lib/http/response-middleware.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/response-middleware.ts]: resolving this at is no longer applicable.

**Comment by AtofStryker** [comment]
> The unit tests are great, but could you add a more e2e-style test? Best place is probably [cookie_login.cy.ts](https://github.com/cypress-io/cypress/blob/6e18996d0211a6ee22ca5fb31561e6f3597b2f78/packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts). We could have passing unit tests for an incorrect implementation. A test that actually runs through the browser will give us a bit more confidence it's correct.

@chrisbreiding the tests in `cookie_login` from what I can see look correct. For the behaviors that could we different or strange, I added a new spec called `cookie_behavior` in the origin directory that tests several different scenarios of how cookies can be applied. Right now, some of those are incorrect and are documented with `FIXME`s, but currently showcase how we currently set/send cookies. It should be really useful when we implement #23551 (which I still need to fill out the description)

File: packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts [hunk 4]
```diff
@@ -0,0 +1,1454 @@
+describe('Cookie Behavior with experimentalSessionAndOrigin=true', () => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts:1]: We should skip any tests we currently expect to fail.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts:1]: I think there is value for keeping the current tests with expected/actual assertions as we know if we change the current behavior, but none of them should currently fail (looks like I need to fix a few tests 😅 ).

Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts:1]: @chrisbreiding only test that I think should be skipped is the one in [5213499](https://github.com/cypress-io/cypress/pull/23438/commits/5213499b8b1e05cb376af553e7986c1a3489df5f), since the extension can set `SameSite=None` with `Secure=false` in firefox.

Comment (chrisbreiding) [reply packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts:1]: My bad, I thought the failing tests were supposed to fail and related to the FIXME comments. So are those FIXME tests currently verifying incorrect behavior?

Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/cookie_behavior.cy.ts:1]: @chrisbreiding correct, with corrective assertions commented out.

File: packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts [hunk 5]
```diff
@@ -191,7 +191,8 @@ describe('cy.origin - cookie login', () => {
       verifyIdpNotLoggedIn({ expectNullCookie: false })
     })
 
-    it('SameSite=None -> not logged in', () => {
+    // FIXME: Currently in Firefox, the default cookie setting in the extension is no_restriction, which can be set with Secure=false.
+    it('SameSite=None -> not logged in', { browser: '!firefox' }, () => {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:195]: is this broken or the tests arn't aligned? should we add a test specifically for firefox?

File: packages/driver/cypress/plugins/server.js [hunk 6]
```diff
@@ -323,10 +344,12 @@ httpPorts.forEach((port) => {
   })
 })
 
-const httpsApp = createApp(httpsPort)
-const httpsServer = httpsProxy.httpsServer(httpsApp)
+httpsPorts.forEach((port) => {
+  const httpsApp = createApp(port)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/plugins/server.js:348]: Do we need to create a full new app for these tests? Could we dumb this down create an express app with the two/three routes needed for this test?

File: packages/network/test/unit/cors_spec.ts [hunk 7]
```diff
@@ -3,46 +3,44 @@ import { expect } from 'chai'
 
 describe('lib/cors', () => {
   context('.parseUrlIntoDomainTldPort', () => {
-    beforeEach(function () {
-      this.isEq = (url, obj) => {
-        expect(cors.parseUrlIntoDomainTldPort(url)).to.deep.eq(obj)
-      }
-    })
+    const assertParsesUrlCorrectly = (url, obj) => {
```
Comment (emilyrohrbough) [inline packages/network/test/unit/cors_spec.ts:6]: nit: named assert but uses expect

File: packages/proxy/lib/http/util/cookies.ts [hunk 8]
```diff
@@ -10,6 +10,47 @@ interface RequestDetails {
...
+ * for more details.
+ */
+export const areUrlsSameSite = (url1: string, url2: string) => {
+  if (!url1 || !url2) return false
+
+  const { port: port1, ...parsedUrl1 } = cors.parseUrlIntoDomainTldPort(url1)
+  const { port: port2, ...parsedUrl2 } = cors.parseUrlIntoDomainTldPort(url2)
+
+  // If HTTPS, ports NEED to match. Otherwise, HTTP ports can be different and are same origin
+  const doPortsPassSameSchemeCheck = port1 !== port2 ? (port1 !== '443' && port2 !== '443') : true
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/cookies.ts:30]: noob question - what does 443 represent?

File: packages/proxy/lib/http/util/cookies.ts [hunk 9]
```diff
@@ -19,15 +60,15 @@ interface RequestDetails {
 // see https://github.com/salesforce/tough-cookie#samesite-cookies
 export const getSameSiteContext = (autUrl: string | undefined, requestUrl: string, isAUTFrameRequest: boolean) => {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/cookies.ts:61]:
```suggestion
export const getSameSiteContext = (autUrl: string | undefined, requestUrl: string, isAUTFrameRequest: boolean): Cypress.SameSiteStatus => {
```

Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/cookies.ts:61]:
```suggestion
export const getSameSiteContext = (autUrl: string | undefined, requestUrl: string, isAUTFrameRequest: boolean): Protocol.Network.CookieSameSite => {
```

File: packages/proxy/lib/http/request-middleware.ts [hunk 10]
```diff
@@ -44,17 +44,15 @@ const MaybeAttachCrossOriginCookies: RequestMiddleware = function () {
     this.req.isAUTFrame,
   )
 
-  const cookies = this.getCookieJar().getCookies(this.req.proxiedUrl, sameSiteContext)
-  const existingCookies = this.req.headers['cookie'] ? [this.req.headers['cookie']] : []
-  const cookiesToAdd = cookies.map((cookie) => `${cookie.key}=${cookie.value}`)
+  const applicableCookiesInCookieJar = this.getCookieJar().getCookies(this.req.proxiedUrl, sameSiteContext)
+  const cookiesOnRequestString = (this.req.headers['cookie'] ? this.req.headers['cookie'] : '').split('; ')
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/request-middleware.ts:48]:
```suggestion
  const cookiesOnRequest = (this.req.headers['cookie'] || '').split('; )
```

File: packages/proxy/lib/http/request-middleware.ts [hunk 11]
```diff
@@ -44,17 +44,15 @@ const MaybeAttachCrossOriginCookies: RequestMiddleware = function () {
     this.req.isAUTFrame,
   )
 
-  const cookies = this.getCookieJar().getCookies(this.req.proxiedUrl, sameSiteContext)
-  const existingCookies = this.req.headers['cookie'] ? [this.req.headers['cookie']] : []
-  const cookiesToAdd = cookies.map((cookie) => `${cookie.key}=${cookie.value}`)
+  const applicableCookiesInCookieJar = this.getCookieJar().getCookies(this.req.proxiedUrl, sameSiteContext)
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/request-middleware.ts:47]: Should `addCookieJarCookiesToRequest` handle pulling the cookie jar cookies?

File: packages/proxy/lib/http/util/cookies.ts [hunk 12]
```diff
@@ -10,6 +10,47 @@ interface RequestDetails {
...
+  const { port: port1, ...parsedUrl1 } = cors.parseUrlIntoDomainTldPort(url1)
+  const { port: port2, ...parsedUrl2 } = cors.parseUrlIntoDomainTldPort(url2)
+
+  // If HTTPS, ports NEED to match. Otherwise, HTTP ports can be different and are same origin
+  const doPortsPassSameSchemeCheck = port1 !== port2 ? (port1 !== '443' && port2 !== '443') : true
+
+  return doPortsPassSameSchemeCheck && _.isEqual(parsedUrl1, parsedUrl2)
+}
+
+export const addCookieJarCookiesToRequest = (applicableCookieJarCookies: Cookie[] = [], requestCookieString: string[] = []): string => {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/cookies.ts:35]:
```suggestion
export const addCookieJarCookiesToRequest = (applicableCookieJarCookies: Cookie[] = [], requestCookies: string[] = []): string => {
```

File: packages/proxy/lib/http/request-middleware.ts (hunk 11 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/request-middleware.ts:47]: I figured not since it really it just a utility and didn't want to make it state aware.

File: packages/proxy/lib/http/util/cookies.ts (hunk 9 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/cookies.ts:61]: I'm not sure we want to pull the CDP types into the proxy, but we could also make a reserved type for this even though it is currently implied

File: packages/proxy/lib/http/util/cookies.ts (hunk 8 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/cookies.ts:30]: default HTTPS port. Only reason I am adding the check here is due to the logic into `parseUrlIntoDomainTldPort`. I am wondering for checking same-site capability if we want to go off the protocol scheme as well, since `443` might be SSL, and there could be other ports that are https.

For example, `https://www.testme.com:8443` and (`https://app.testme.com:4849`|`http://app.testme.com:443`) are all same-site, but this function would evaluate `false` | `true`. Since we infer port from`parseUrlIntoDomainTldPort`, I am not sure this is an issue though

File: packages/network/test/unit/cors_spec.ts (hunk 7 above)
Comment (AtofStryker) [reply packages/network/test/unit/cors_spec.ts]: updated to `expectUrlToBeParsedCorrectly` in a2637b9a76

File: packages/driver/cypress/plugins/server.js (hunk 6 above)
Comment (AtofStryker) [reply packages/driver/cypress/plugins/server.js:348]: The issue is we need a different port on `https`, which we currently do not have to verify same-site cookie behavior for differing ports. The added routes in the server aren't the reason for the new app, which I don't think is obvious at all. I'm thinking some documentation/comments are needed here.

Comment (AtofStryker) [reply packages/driver/cypress/plugins/server.js:350]: added some docs in ec8b751c32

File: packages/proxy/lib/http/util/cookies.ts (hunk 12 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/cookies.ts]: addressed (somewhat) in [99d5ed2](https://github.com/cypress-io/cypress/pull/23438/commits/99d5ed23b824ec8206a6424edec54d010c18ec09). The name was used below so I went with `requestCookieStringArray`

File: packages/proxy/lib/http/request-middleware.ts (hunk 10 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/request-middleware.ts]: addressed in [99d5ed2](https://github.com/cypress-io/cypress/pull/23438/commits/99d5ed23b824ec8206a6424edec54d010c18ec09)

File: packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:195]: What I believe was happening here before is that since this request that sets cookies was seemed "cross-origin", `X-Set-Cookie` was being used in the header and not setting the cookie in the browser. In the server side cookie jar, we [ignore cookies](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/cookies.ts#L114) that are `SameSite=None` and `Secure=false`.

Now, since we use `Set-Cookie` all the time, the cookie is actually set in firefox because we currently allow `SameSite=None` and `Secure=false` to be set in the extension, which actually allows this test to log in.

We can add a test that verifies this behavior, but I am somewhat of the opinion that we shouldn't allow setting insecure samesite none cookies in firefox.

**Review by chrisbreiding — APPROVED** [review]

File: packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts (hunk 5 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:195]: > Now, since we use Set-Cookie all the time, the cookie is actually set in firefox because we currently allow SameSite=None and Secure=false to be set in the extension, which actually allows this test to log in.

I would expect this to be a problem for our user if it works in chrome one way and differently in firefox. Shouldn't we be updating the extension to have the same checks / ignore the same attributes as the server-side cookie jar that is using to manage the cookies for chrome & electron ?

**Review by mjhenkes — APPROVED** [review]
