### PR TITLE
fix: No unnecessary snapshotting

### LINKED ISSUE #18549: Fast memory leak/creep when cy.get fails to find the element, and eventually crashes
### Current behavior

While cy.get() retries to find an element , the memory usage of the tab shoots up quickly

See video https://youtu.be/N5jtyBdd05Q

### Desired behavior

Memory usage should not increase this quickly

### Test code to reproduce

`describe('Memory issue', () => {`
`    it('Simple memory test', () => {`
`        cy.visit('https://www.androidpolice.com')`
`        cy.get('.garbageId')`
`    })`
`})`

### Cypress Version

5.1.0 and latest 8.6.0

### Other

Initially I found this issue while testing my company's website, then I found that it is easily reproducible with other websites as well

image

**Pre-requisistes**
- **numTestsKeptInMemory** has to be set to 1 or higher
- set **defaultCommandTimeout** to a higher value (eg. 50000) so there's more time for the memory to increase

**Steps to reproduce**
1. Visit a website (eg. https://www.androidpolice.com)
2. Use cy.get() to find an non-existent element

As you can see in the video linked above, the memory usage starts shooting up when Cypress is trying to find the element.
When you re-run the test without closing the tab, the memory doesn't reset and keeps adding up. Eventually when the usage reaches 4GB, the tab crashes with the "Aw snap" message.

This issue is a lot more apparent if the test is longer with more steps, which can put the memory usage close to the ceiling of 4GB.

So far the reliable workaround is to set **numTestsKeptInMemory** to 0, which stops the memory creep altogether.

Very occasionally I can observe the garbage collection kicking in and reducing the memory usage, however the cy.get() still rapidly increases the memory usage after

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes #18549

### User facing changelog
Bugfix: Prevent unnecessary snapshotting when running default assertions that would unnecessarily increase CPU use in `cypress open` mode and lead to out of memory crashes on certain browsers.

### Additional details
Ensure that we don't snapshot while verifying implicit assertions, the same way that we don't snapshot when verifying upcoming explicit assertions

### How has the user experience changed?
Improved performance, reducing both CPU and memory usage while waiting for assertions to pass. In certain versions of Chromium / Chrome / Electron, this also fixes a serious memory leak for failing tests.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 1]
```diff
@@ -2927,4 +2927,23 @@ describe('src/cy/commands/assertions', () => {
       cy.get('.foo').should('not.exist')
     })
   })
+
+  context('implicit assertions', () => {
+    // https://github.com/cypress-io/cypress/issues/18549
+    it('only snapshots once when failing to find DOM elements', (done) => {
+      sinon.spy(cy, 'createSnapshot')
```
Comment (brian-mann) [inline packages/driver/cypress/integration/commands/assertions_spec.js:2934]: you can work off of the event that cypress fires when it retries in order to count the number of retries that happened

- on the first retry, spy on cy.createSnapshot
- and then make sure that after it fails, there was only a single call to cy.createSnapshot
- and then it retried >1 times

that would tell you it took a snapshot on the final “error” state and not during the interstitial retries

its like... `cy.on('retry', ...)` or `cy.on('command:retry', ...)` I can't remember but there are other tests that use this event to count things.

that’ll give you a consistent and deterministic way to ensure that it both retried AND only created 1 snapshot and that test should obviously fail if we reverted the fix

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 2]
```diff
@@ -2927,4 +2927,23 @@ describe('src/cy/commands/assertions', () => {
...
+      cy.on('fail', (err) => {
+        // We have a regression where snapshots are being taken for every failed retry on implicit assertions
+        // for element existence. The exact number expected is unclear (and this test should be updated with a
+        // more exact assertion once we've solved the regression) - but it definitely shouldn't be above 5!
+        expect(cy.createSnapshot.callCount).to.be.lessThan(5)
+
+        cy.createSnapshot.restore()
```
Comment (brian-mann) [inline packages/driver/cypress/integration/commands/assertions_spec.js:2941]: you don't need to do this, cypress automatically cleans up all mocks/stubs in between tests, so its impossible to leak. you only need to restore if you need to restore and then mock it again for some reason within *the same test*, which is virtually and effectively "never"

File: packages/driver/cypress/integration/commands/assertions_spec.js (hunk 1 above)
Comment (BlueWinds) [reply packages/driver/cypress/integration/commands/assertions_spec.js]: Reworked this into a more generic utility listening to cypress events, and added an event for snapshoting since we didn't already have one.

I also split the test into two pieces, one which precisely pinpoints the problem (a failing DOM assertion is taking three snapshots outside the context of retries, two of them because of `ensureElExistence`), and one which demonstrates it more dramatically (these calls because of `ensureElExistence` repeat with every retry, resulting in hundreds of snapshots).

File: packages/driver/src/cy/assertions.ts [hunk 3]
```diff
@@ -324,6 +326,10 @@ export const create = (Cypress, cy) => {
       // bail if we have no assertions and apply
       // the default assertions if applicable
       if (!cmds.length) {
+        cy.state('overrideAssert', function (...args) {
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/assertions.ts:329]: how does is this handled when [cmdHadFuncArg](https://github.com/cypress-io/cypress/blob/bc06bdc68de0dea448e782c58f9d3a5dc762843d/packages/driver/src/cy/assertions.ts#L442)?

I see the default behavior checks for a `cy.state('overrideAssert')` function.

**Comment by emilyrohrbough** [comment]
Could be a bit off here on the flow so if my comments seem way off, sorry in advance!
I have a few questions....
1. Mind adding a few more details on how override the assertion method is fixing this? It's not 100% apparent.
1. >  Ensure that we don't snapshot for assertions that fail our retry logic already takes a snapshot at the end when a test actually fails.

Is this true when retries are set to 0 in the configuration? Does your fix handle this scenario?

2. Did you consider updating [the retries logic here](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/retries.ts#L57-L65) to account for this given the [finishAssertions callback](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cypress/cy.ts#L250-L254) provided to the retries class which uses the [assertion class' finishAssertion method which also takes the snapshot](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/assertions.ts#L205)? 
```diff
      // snapshot the DOM since we are bailing so the user can see the state we're in
      // when we fail
-      if (log) {
-        log.snapshot()
-      }

      const assertions = options.assertions

      if (assertions) {
        finishAssertions(assertions)
      }
+    else if (log) {
+        log.snapshot()
+    }
```

4. Inverse of the previous thought (prob better to keep implementation details separate), could we update the [assertion class' finishAssertion method](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/assertions.ts#L205) to determine when it should take a snaphot? (i.e. when retries === false?)
```diff
+ // by default the retries handle will take the snapshot for us
+  const finishAssertions = (assertions, shouldTakeSnapshot = false) => {
-  const finishAssertions = (assertions) => {
-     return _.each(assertions, (log) => {
+     if (shouldTakeSnapshot) {
      log.snapshot()
```
Then updating [this case](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/assertions.ts#L507) to pass in "yes should take screenshot"

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 4]
```diff
@@ -1,6 +1,39 @@
 const { assertLogLength } = require('../../support/utils')
 const { $, _ } = Cypress
 
+const captureCommands = () => {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/integration/commands/assertions_spec.js:4]: Do we not manage / track the number of snapshots taken during a test? I assumed this data was reported to the dashboard?

Comment (BlueWinds) [reply packages/driver/cypress/integration/commands/assertions_spec.js:4]: These DOM snapshots are the ones visible when you hover over test steps and it displays how the application looked at that point in time. They're very ephemeral - we only take them in open mode, and they live in the browser running tests, not even sent to the cypress server. We discard the snapshots regularly (if the number of tests run is greater than `numTestsKeptInMemory`, whenever we rerun tests, etc).

We didn't even have an internal event for counting them until I added it in this PR (`Cypress.action('cy:snapshot', name)`) so this utility could listen for it.

Comment (BlueWinds) [reply packages/driver/cypress/integration/commands/assertions_spec.js:4]: > Could be a bit off here on the flow so if my comments seem way off, sorry in advance! I have a few questions....
> 
>     1. Mind adding a few more details on how override the assertion method is fixing this? It's not 100% apparent.

Yeah, the key here is that I'm not doing something new, I'm *covering another case* and doing the same thing we were already doing in the other location.

`verifyUpcomingAssertions` has two exit points. It can return on either line 328 if there are no upcoming commands:
```
if (!cmds.length) {
        return Promise
        .try(ensureExistence)
        .then(onPassFn)
        .catch(onFailFn)
}
```

or it can return on line 490:

```
     cy.state('overrideAssert', overrideAssert)

      return Promise
      .reduce(fns, assertions, [subject])
      .then(() => {
        restore()
        ...
      }).catch(() => {
        restore()
        ...
     })
```

When there *are* upcoming commands in the queue - when we're verifying assertions like ".should('have.class', 'foo')", then we override the assert function in a way that passes in `verifying: true` - line 442 inside `overrideAssert`. This PR makes the same thing happen for implicit assertions.

So to try and put it in English a bit better: In general, when an assertion fails, we want to take a snapshot, so we can show the users what went wrong. But when we're when we're in the middle of `cy.get()` checking to see if we should move on to following commands or sit here retrying cy.get() - that is to say we're *verifyingUpcomingAssertions* - then we execute the assertion code every 50ms, but we're only doing to to *see if we're ready to move on* - not in order to pass or fail the assertion itself!

That's why what `verifying = false | true` on line 128 in `assertFn` represents. If it's false, we are actually executing an assertion - we do things like put an error on the log message and take a snapshot. If we're only verifying upcoming assertions, then we still execute the assertion code - but verifying = true tells us not to do things that we only want to do once at the very end (eg, take a snapshot to display to the user).

>     2. > Ensure that we don't snapshot for assertions that fail our retry logic already takes a snapshot at the end when a test actually fails.
> 
> 
> Is this true when retries are set to 0 in the configuration? Does your fix handle this scenario?

I'll update the PR description here - I wrote it based on an earlier misunderstanding of the bug. It's what the first test I added, with `timeout: 0` is demonstrating - we were taking extra snapshots *unrelated to retries.*

Retries are not the cause of the bug, they just make it way more obvious. Setting {timeout: 0} in that first test ensures that no retries occur - but if you run that test against develop (or comment out the code additions in this branch), you'll see that three snapshots were occurring even though there were 0 retries.

>     2. Did you consider updating [the retries logic here](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/retries.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L57-L65) to account for this given the [finishAssertions callback](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cypress/cy.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L250-L254) provided to the retries class which uses the [assertion class' finishAssertion method which also takes the snapshot](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/assertions.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L205)?

Yeah, my initial attempt to fix this was in the retries logic - but that's why the first test is so important. It demonstrates the problem outside the context of retries. If we're triple snapshoting without retries, then making sure we only do three snapshots is still not the correct solution - there should only be one!

I really should have updated the description before sending this over.

**Comment by BlueWinds** [comment]
> Could be a bit off here on the flow so if my comments seem way off, sorry in advance! I have a few questions....
> 
>     1. Mind adding a few more details on how override the assertion method is fixing this? It's not 100% apparent.

Yeah, the key here is that I'm not doing something new, I'm *covering another case* and doing the same thing we were already doing in the other location.

`verifyUpcomingAssertions` has two exit points. It can return on either line 328 if there are no upcoming commands:
```
if (!cmds.length) {
        return Promise
        .try(ensureExistence)
        .then(onPassFn)
        .catch(onFailFn)
}
```

or it can return on line 490:

```
     cy.state('overrideAssert', overrideAssert)

      return Promise
      .reduce(fns, assertions, [subject])
      .then(() => {
        restore()
        ...
      }).catch(() => {
        restore()
        ...
     })
```

When there *are* upcoming commands in the queue - when we're verifying assertions like ".should('have.class', 'foo')", then we override the assert function in a way that passes in `verifying: true` - line 442 inside `overrideAssert`. This PR makes the same thing happen for implicit assertions.

So to try and put it in English a bit better: In general, when an assertion fails, we want to take a snapshot, so we can show the users what went wrong. But when we're when we're in the middle of `cy.get()` checking to see if we should move on to following commands or sit here retrying cy.get() - that is to say we're *verifyingUpcomingAssertions* - then we execute the assertion code every 50ms, but we're only doing to to *see if we're ready to move on* - not in order to pass or fail the assertion itself!

That's why what `verifying = false | true` on line 128 in `assertFn` represents. If it's false, we are actually executing an assertion - we do things like put an error on the log message and take a snapshot. If we're only verifying upcoming assertions, then we still execute the assertion code - but verifying = true tells us not to do things that we only want to do once at the very end (eg, take a snapshot to display to the user).

>     2. > Ensure that we don't snapshot for assertions that fail our retry logic already takes a snapshot at the end when a test actually fails.
> 
> 
> Is this true when retries are set to 0 in the configuration? Does your fix handle this scenario?

I'll update the PR description here - I wrote it based on an earlier misunderstanding of the bug. It's what the first test I added, with `timeout: 0` is demonstrating - we were taking extra snapshots *unrelated to retries.*

Retries are not the cause of the bug, they just make it way more obvious. Setting {timeout: 0} in that first test ensures that no retries occur - but if you run that test against develop (or comment out the code additions in this branch), you'll see that three snapshots were occurring even though there were 0 retries.

>     2. Did you consider updating [the retries logic here](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/retries.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L57-L65) to account for this given the [finishAssertions callback](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cypress/cy.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L250-L254) provided to the retries class which uses the [assertion class' finishAssertion method which also takes the snapshot](https://github.com/cypress-io/cypress/blob/issue-18549-no-unnecessary-snapshotting/packages/driver/src/cy/assertions.ts?rgh-link-date=2021-12-16T21%3A42%3A37Z#L205)?

Yeah, my initial attempt to fix this was in the retries logic - but that's why the first test is so important. It demonstrates the problem outside the context of retries. If we're triple snapshoting without retries, then making sure we only do three snapshots is still not the correct solution - there should only be one!

I really should have updated the description before sending this over.

**Review by mjhenkes — DISMISSED** [review]
Succinct solution to a deep problem. Thanks for the detailed description in the comment, without that i'd have had no idea what this was doing.

**Review by emilyrohrbough — APPROVED** [review]

File: packages/driver/src/cy/assertions.ts (hunk 3 above)
Comment (chrisbreiding) [reply packages/driver/src/cy/assertions.ts:329]: @BlueWinds Could you add a comment here explaining why this is overriding the assertFn and adding `true` as the last arg? I understand it in the context of this PR, but it would be useful for future readers of the code.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/assertions.ts [hunk 5]
```diff
@@ -143,9 +143,19 @@ export const create = (Cypress, cy) => {
       obj.$el = $dom.wrap(value)
     }
 
-    // if we are simply verifying the upcoming
-    // assertions then do not immediately end or snapshot
-    // else do
+    // `verifying` represents whether we're deciding whether or not to resolve
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/assertions.ts:146]: maybe out of scope, but thoughts on renaming `verifying` to something a little more self-explanatory.... idea might be `isVerifyingUpcomingAssertions` (the terminology you emphasized in your log description).

Comment (BlueWinds) [reply packages/driver/src/cy/assertions.ts:146]: I think I'd like to save renaming things for a later date. My real goal would be to make a flowchart of the logic and consider a refactor of this area of code - Brian spoke to some regrets that we didn't just re-implement parts of Chai, rather than weaving in and out of 3rd party code and keeping track of state internally to make it behave as we want.

**Review by chrisbreiding — DISMISSED** [review]

**Review by brian-mann — DISMISSED** [review]
- call a method on `testCommands` which returns an immutable command state to assert on in order to prevent those assertions from mutating the command state
- try out `chai-match-pattern` to create more flexibility in the assertions of the command state

**Comment by BlueWinds** [comment]
> * call a method on `testCommands` which returns an immutable command state to assert on in order to prevent those assertions from mutating the command state
> 
>     * try out `chai-match-pattern` to create more flexibility in the assertions of the command state

Both done in latest commit. Turns out we already have `chai-subset` which serves the same purpose (but neither of us could remember the name while on the call).

**Review by emilyrohrbough — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
Mind expanding the User Facing Changelog a bit to expand on what you mean by "churn"

**Review by mjhenkes — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@BlueWinds Nice job on the changelog update.  👍🏻  I think it is cleared to an end-user what this change means for them.
