### PR TITLE
Fix bug where a click on a wrapped inline element would miss

### LINKED ISSUE #7012: click does not work if an element has zero width / height element inside of it
Cypress 4.4.0

HTML

```html
<a href='#' className='learn-more' onClick={openProjectIdHelp}>
   <i className='fas fa-info-circle'></i>{' '}
   Learn more
</a>
```

Test code

```js
cy.contains('a', 'Learn more').click()
```

The click command happens BUT it does not reach the `onClick` handler in the `a` element. 

Screen Shot 2020-04-14 at 1 01 02 PM

Seems the mouse click happens on the edge of the found element, not inside of it

Screen Shot 2020-04-14 at 1 01 58 PM

and thus the click event goes into parent "div"

Screen Shot 2020-04-14 at 1 02 23 PM

After digging into the mouse click handlers got to `coordinates.js`

```js
const getElementPositioning = ($el) => {
  ...
  const rect = el.getClientRects()[0] || el.getBoundingClientRect()
```

For our element, `el.getClientRects()` returns _two rectangles_.

Screen Shot 2020-04-14 at 1 06 09 PM

The first rectangle is from `<i>` element with no width, the second from the text inside the `a` element.

Screen Shot 2020-04-14 at 1 07 45 PM

We can recreate the behavior by putting an empty span

```html
<a href='#' className='learn-more' onClick={openProjectIdHelp}>
  <span></span>
  Learn more
</a>
```

Screen Shot 2020-04-14 at 1 09 13 PM

## Proposal

- look at the list of returned client rectangles, not just at the first one. A simple check would be to skip the rectangles with `width:0` or `height:0`. A more robust check would be to get the coordinates and then check which element at those coordinates would receive the event. In our case, it would be parent `div`, because the first element has zero dimension.

### LINKED ISSUE #7343: For inline elements that wrap lines, the click funtion misses when the first child element has no width
### Current behavior:

For inline elements that wrap lines, sometimes the center of the bounding rect is not actually part of the element. So the first client rect is used in order to ensure that the `click` function does not miss when it attempts to click the element. In rare cases, this element may actually have no width, which results in a missed click as well.

### Desired behavior:

The `click` function should always properly click the element.

### Test code to reproduce

```html
<div style="width: 30px; line-height: 2;">
  <a href="#" id="overflow-link-width">
    <i style="display: inline-block;"></i>
    foofoofoofoofoo bar
  </a>
</div>
```

```javascript
cy.get('#overflow-link-width').click()
```

### Versions

4.5.0

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7343
- Closes #7012 

### User facing changelog

Fixes a bug where a click on a wrapped inline element would miss if the first child element did not have a width or height

### Additional details

Ensures that any element child that is attempted to be clicked on has both a height and a width.

#### Before

Screen Shot 2020-05-18 at 2 33 08 PM

#### After

Screen Shot 2020-05-18 at 2 36 24 PM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
I don't think this is addressing the original issue. In the original issue, the click command was successful (did not throw error about visibility), but did not trigger the `onclick` handler. TBH, I couldn't recreate this behavior from the example provided in #7012 (I added a comment).

Running the example in the test you provided prior to this PR throws a visibility error about being covered by HTML and does not issue the click. I'm not sure if this is fixing an existing opened issue, but it does fix the example given in the test, so maybe your new issue was required.

**Comment by panzarino** [comment]
@jennifer-shehane what do you propose as the course of action here? Should I re-open my issue that this PR solves or should I wait for a reproducible example on #7012 and attempt to address that issue in this PR?

**Comment by Bkucera** [comment]
https://github.com/cypress-io/cypress/issues/7012 will likely be fixed by this PR - if only we had a reproducible

**Comment by jennifer-shehane** [comment]
Any update here? I was never able to recreate the issue this is supposedly fixing.

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 1]
```diff
@@ -965,6 +965,10 @@ describe('src/cy/commands/actions/click', () => {
         cy.get('#overflow-link').find('.wrapped').click()
       })
 
+      it('can click on inline elements that wrap lines where the first rect has no width', () => {
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js:968]: can you add the issue link

**Review by kuceb — CHANGES_REQUESTED** [review]

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 1 above)
Comment (panzarino) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js:968]: I've reopened https://github.com/cypress-io/cypress/issues/7343. However, I still feel that this may also fix #7012, which might be worth investigating before merging (and then forgetting about it).

**Review by kuceb — APPROVED** [review]
