### PR TITLE
Display full specfile(s) in stdout during cypress run

### LINKED ISSUE #4977: Full path to failed specfile is not viewable from stdout
### Current behavior:

The specfiles are truncated in the stdout results of a run, making it difficult for users to track down which test file results they are looking at. 

Screen Shot 2019-08-13 at 4 20 09 PM

### Desired behavior:

Some suggestions

- Make this configurable somehow
- Have a better way to display the full specfile name (maybe return the line to print the entire length)

### Versions

Cypress 3.4.1

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #4977 

### User facing changelog

Stdout printed during `cypress run` no longer truncates text such a filenames and instead wraps the text to fit within the width of the terminal.

### Additional details

The way tables are printed in stdout has been refactored.

##### Paths now insert newlines

- Previously, paths would extend beyond the width of the terminal or (even less ideal) would truncate the path with `...`, now we have a new method `formatPath` that when passed the width of the table's column it will be drawn within, will add newlines at the width so that the path will return. 

https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/lib/modes/run.js#L115

- Many places where we were just doing `console.log('path/to/thing')` have now been replaced with tables so we can properly wrap depending on the set column width.

https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/lib/modes/run.js#L859

##### Leftover width when < 100 width 

- Before, the algorithm was naive about throwing extra leftover sizing into the width of the *first* column, which would be confusing if you assigned the width of the column to `3` (1 left padding, 1 width, 1 right padding), it would sometimes print out at a width of `10` because if the other columns did not take up a width of `100` - they would throw the extra width into the first column. 
- Now the algorithm respects the width assigned and subtracts the width taken up by borders from the *widest* column. 

https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/lib/util/terminal.js#L161

##### Snapshots

- Many of the snapshot replacements have been updated in order to not disrupt the 100 width of the original table. When replacing text from a snapshot like `1028x468`, we now replace it with the smallest possible width (in this case a screenshot could be `0x0` at it's smallest) and add padding to equal the length of the original screenshot, so we replace the text like: `_.startPad('YxZ', p1.length)`. 

https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/test/support/helpers/e2e.coffee#L77

- Additionally, in one area replacing the text in the snapshot was *too late*. The width of the tables had already been calculated and drawn (with the newline returns), so replacing the text at that point would mess up all of the table alignments. This is when the stdout is printing the current working directory. In this case, we pass a `FAKE_CWD_PATH` env var during test execution - that when present during `run`, replaces the current working directory path *before* we insert the newlines. 

https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/lib/modes/run.js#L120

##### Bug in cli-table-3

I found a bug with cli-table-3 where padding passed to a cell is ignored if set to `0`. Opened an issue here: https://github.com/cli-table/cli-table3/issues/124

#### Run Header

**Before**

Screen Shot 2019-10-17 at 9 47 23 AM

**After**

Screen Shot 2019-10-17 at 9 38 55 AM

### Run Results

**Before**

Screen Shot 2019-10-17 at 9 47 36 AM

**After**

Screen Shot 2019-10-17 at 9 38 30 AM

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/util/terminal.js [hunk 1]
```diff
@@ -39,30 +25,26 @@ const getBordersLength = (left, right) => {
 }
 
 const convertDecimalsToNumber = function (colWidths, cols) {
-  let diff
-  const sum = _.sum(colWidths)
+  // const sum = _.sum(colWidths)
```
Comment (bahmutov) [inline packages/server/lib/util/terminal.js]: a few commented out lines

Comment (jennifer-shehane) [reply packages/server/lib/util/terminal.js]: Thanks for pointing this out. I removed this while experimenting - need to add back.

Comment (jennifer-shehane) [reply packages/server/lib/util/terminal.js]: Actually, I might just remove this 😬

**Review by brian-mann — DISMISSED** [review]
- We need to leave the truncation in place for displaying the number of found spec files - because using a `specPattern` would list out potentially dozens or even hundreds of tests - which is not what the user wants.
- Add margin-right space back in for displaying the Running spec

File: packages/server/lib/util/newlines.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+const addNewlineAtEveryNChar = (str, n) => {
```
[the remark this answers is not in the document]
Comment (jennifer-shehane) [reply packages/server/lib/util/newlines.js]: Added a test and updated function to ramda splitEvery

**Comment by bahmutov** [comment]
by the way, small pure functions the `addNewlineAtEveryNChar` are perfect for data -driven testing already built into `snap-shot-it`, https://github.com/bahmutov/snap-shot-it#data-driven-testing

**Comment by jennifer-shehane** [comment]
So, the snapshots are really weird now, where I can't tell if the columns are lining up when there is a projectPath part of the new truncation. 

I implemented this change, where I replace the tmpDir and projectPath with the same num of chars of `XXXXX`: https://github.com/cypress-io/cypress/pull/5120/commits/50bc51744c20fe4075c2183636b32b1da75e09d1

But, I just realized this is really naive because when run on a different system with a different relative directory it will change the num of chars. 

So, I'm not sure what we want to do.

**Comment by jennifer-shehane** [comment]
~Ok, so @brian-mann 	is suggesting that instead of trying to strip out the current Directory path later, that we just change the current working directory when running our internal tests.~

~I should look at the run code for video compression when our `--fake-cwd-path` env var is set.~

~Pass env var for `--fake-cwd-path`, if set then override `process.stdout.write` so that it will replace the current working directory returned from `console.log`.~

Pass env var for `--fake-cwd-path`, if set then within the cli-table3 tool, we should strip out the current working directory and replace it with a fake dir before calculating the newlines. This needs to be done in the `formatPath` function of the `run.js`

**Comment by jennifer-shehane** [comment]
Why 😭  😭  😭  😭  😭  😭  😭 

Screen Shot 2019-10-10 at 5 42 38 PM

**Comment by jennifer-shehane** [comment]
Exactly same issue after updating the startPadding for the `(X seconds)`

Screen Shot 2019-10-16 at 9 10 21 AM

**Comment by jennifer-shehane** [comment]
Found the culprit, not sure how I didn't notice the video names were being replaced before. https://github.com/cypress-io/cypress/blob/issue-4977-specfiles-in-stdout/packages/server/test/support/helpers/e2e.coffee#L100

File: packages/server/test/support/helpers/e2e.coffee [hunk 3]
```diff
@@ -84,25 +90,35 @@ normalizeStdout = (str, options = {}) ->
...
+  .replace(/(Cypress\:\s+)(\d\.\d\.\d)/g, "$1" + "1.2.3") 
+  ## Node Version: 10.2.3 (Users/jane/node) -> Node Version: XXXXX (foo/bar/node)
+  .replace(/(Node Version\:\s+v)(\d+\.\d+\.\d+)( \(.*\)\s+)/g, replaceNodeVersion) 
+  ## 15 seconds -> X second
   .replace(/(Duration\:\s+)(\d+\sminutes?,\s+)?(\d+\sseconds?)(\s+)/g, replaceDurationSeconds)
-  .replace(/(duration\=\')(\d+)(\')/g, replaceDurationFromReporter) ## replace duration='1589'
-  .replace(/\((\d+ minutes?,\s+)?\d+ seconds?\)/g, "(X seconds)")
+  ## duration='1589' -> duration='XXXX'
+  .replace(/(duration\=\')(\d+)(\')/g, replaceDurationFromReporter) 
+  ## (15 seconds) -> (XX seconds)
```
Comment (flotwig) [inline packages/server/test/support/helpers/e2e.coffee]: thanks for adding these much-needed comments

File: packages/server/test/support/helpers/e2e.coffee [hunk 4]
```diff
@@ -57,19 +57,25 @@ replaceDurationSeconds = (str, p1, p2, p3, p4) ->
...
 replaceDurationFromReporter = (str, p1, p2, p3) ->
   ## duration='1589'
-
   p1 + _.padEnd("X", p2.length, "X") + p3
 
 replaceNodeVersion = (str, p1, p2, p3) ->
-  ## Node Version: 1.2.3
-
+  ## Node Version: 10.2.3
   return p1 + _.padEnd("X", p2.length, "X") + ' (/foo/bar/node)' + ' '.repeat(p3.length - 16)
```
Comment (flotwig) [inline packages/server/test/support/helpers/e2e.coffee]: doesn't this make the replacement text size depend on the underlying node version?

Node 12.0.0 will become Node XXXXXX, Node 12.11.0 will become XXXXXXX

probably not worth too much time to fix since there's only 1 or 2 tests that use custom Node, but it will come up whenever the Node version string on CI changes length.

File: packages/server/lib/util/terminal.js [hunk 5]
```diff
@@ -151,13 +128,11 @@ const wrapBordersInGray = (chars) => {
...
 
     return char
-
   })
 }
 
 const table = function (options = {}) {
-  const { colWidths, type } = options
-
+  let { colWidths, type } = options
```
Comment (flotwig) [inline packages/server/lib/util/terminal.js]: `type` can still be `const`, right?

File: packages/server/test/support/helpers/e2e.coffee [hunk 6]
```diff
@@ -57,19 +57,25 @@ replaceDurationSeconds = (str, p1, p2, p3, p4) ->
...
 
 replaceDurationInTables = (str, p1, p2) ->
   ## when swapping out the duration, ensure we pad the
   ## full length of the duration so it doesn't shift content
   _.padStart("XX:XX", p1.length + p2.length)
 
+replaceParenTime = (str, p1) ->
+  ## could be (1 second) or (10 seconds)
+  ## need to account for shortest and longest
+  return _.padStart("(X second)", p1.length)
```
Comment (flotwig) [inline packages/server/test/support/helpers/e2e.coffee]: this makes all the snapshots say `(X second)`, which reads a little weird, in normal English it would be `(X seconds)` since X is a variable

**Review by flotwig — DISMISSED** [review]
New stdout looks awesome! I noticed some minor things you might want to fix but all in all this looks great.

File: packages/server/test/support/helpers/e2e.coffee (hunk 4 above)
Comment (jennifer-shehane) [reply packages/server/test/support/helpers/e2e.coffee]: Yes, I know 😞 I didn't want to make anymore changes. 😓 I'll fix it

File: packages/server/test/support/helpers/e2e.coffee (hunk 6 above)
Comment (jennifer-shehane) [reply packages/server/test/support/helpers/e2e.coffee]: Yeah, this is what I came up with.

Do you have a suggestion for writing this so that it replaces all variants below with a single replacement?

```
(2 seconds)
(1 second)
(10 seconds)
```

File: packages/server/test/support/helpers/e2e.coffee (hunk 4 above)
Comment (flotwig) [reply packages/server/test/support/helpers/e2e.coffee]: i think `1_system_node_spec` will be the only snapshot that changes

File: packages/server/test/support/helpers/e2e.coffee (hunk 6 above)
Comment (flotwig) [reply packages/server/test/support/helpers/e2e.coffee]: ah, i see what the issue is, you can't replace `(1 second)` with `(X seconds)` without messing other stuff up. i guess you could update the regex to grab some extra whitespace from the beginning of the string, but that's beginning to feel really hacky. just doing `(X second)` is probably the best way then

**Review by flotwig — APPROVED** [review]
