### PR TITLE
Set `form: true` when using form Content-Type and object body

### LINKED ISSUE #2923: Error upon request
### Current behavior:

Upon `cy.request` with a seemingly valid header, following is the stack trace of the error.  Note that changing the header key "content-type" to "ContentType" makes the error go away.  

```
TypeError: str.replace is not a function
    at Querystring.rfc3986 (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\lib\querystring.js:43:14)
    at Request.json (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:1293:30)
    at Request.init (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:406:10)
    at Request.RP$initInterceptor [as init] (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\request.js:127:8)
    at request (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\index.js:53:10)
    at C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\request\index.js:100:12
    at Object.create (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\lib\request.js:170:18)
    at C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\lib\request.js:364:26
    at tryCatcher (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Brad Wood\AppData\Local\Cypress\Cache\3.1.3\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### Desired behavior:

Network call made.  I realize now that "form":true is the accepted method of setting that content type; still minor bug.

Create this options object:
```js
const options = {
  "method": "POST",
  "url": "some valid url",
  "headers": {
    "Accept": "application/json",
    "content-type": "application/x-www-form-urlencoded"
  },
  "body": {
    "scope": "my_scope"
  }
};

cy.request(options).then // ...
```

### Versions

3.1.3

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #2923 

Currently, when a user is using `Content-Type: application/x-www-form-urlencoded` with an object body as described in the issue, Cypress will set the `json` option to true because an object is set as the `body`. This causes the `request` library to try to parse the `body` object as a string:

https://github.com/request/request/blob/master/request.js#L1284

This PR fixes that unexpected behavior/edge case by setting the `form` option to true if the `Content-Type` header equals `application/x-www-form-urlencoded` and `json` is not already set by a user. This means the cryptic `request` library error can no longer be reached unless a user purposefully sets `json` and `form` at the same time.

### CODE REVIEW

File: packages/driver/src/cy/commands/request.coffee [hunk 1]
```diff
@@ -118,6 +118,11 @@ module.exports = (Commands, Cypress, cy, state, config) ->
       if not $Location.isFullyQualifiedUrl(options.url)
         $utils.throwErrByPath("request.url_invalid")
 
+      ## if a user has `x-www-form-urlencoded` content-type set with an object body, they meant to do this
+      ## https://github.com/cypress-io/cypress/issues/2923
+      if _.isObject(options.body) and not options.json and 'content-type' == _.toLower(_.findKey(options.headers, (v) -> v == 'application/x-www-form-urlencoded'))
```
Comment (brian-mann) [inline packages/driver/src/cy/commands/request.coffee]: extract this into a named function for clarity...

something like `isBodySetWithFormUrlEncodedHeaders(...)`
