### PR TITLE
fix: truncate text to fix layout

### LINKED ISSUE #21755: Browser icons and longer names in the dropdown menu don't display correctly
Two things…

Very low priority but the launchpad browser tile design & associated list doesn’t support longer names. I don’t know of many other than FF Developer Edition. But maybe can truncate the text after a max char count to prevent this. 

Also, notice the non-standard Edge logos being squished in the app dropdown.

Screen Shot 2022-03-02 at 5 19 10 PM

Screen Shot 2022-03-02 at 5 16 57 PM

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/UNIFY-1234) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11433">Screen Shot 2022-03-02 at 5.16.57 PM.png</a> | <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11432">Screen Shot 2022-03-02 at 5.19.10 PM.png</a>
┆author: Paul Jaffre
┆epic: UI/UX Improvements
┆friendlyId: UNIFY-1234
┆priority: Lowest
┆sprint: Unification Release Backlog
┆taskType: Bug

[UNIFY-1234]: https://cypress-io.atlassian.net/browse/UNIFY-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UNIFY-1234]: https://cypress-io.atlassian.net/browse/UNIFY-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
- Closes [issue-21755](https://github.com/cypress-io/cypress/issues/21755)

### User-facing changelog

It truncates the browser name in the UI in order to avoid layout issues when the browser name is too long.

### Additional details

N/A

### Steps to test

- Install Firefox Developer Edition browser.
- Launch Cypress.

### How has the user experience changed?

An ellipsis will be added if the browser name is too long. Ellipsis will be added if the browser name is more than 16 characters.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
@elevatebart @marktnoonan Could you re-review this PR from @Manuel-Suarez-Abascal ? You both initially provided feedback on https://github.com/cypress-io/cypress/pull/24831 which was closed and replaced with this PR to fix the CLA issue.

File: packages/launchpad/src/setup/OpenBrowserList.vue [hunk 1]
```diff
@@ -56,7 +56,7 @@
             >
           </div>
           <div
-            class="font-medium pt-2 text-18px leading-28px"
+            class="font-medium pt-2 text-18px leading-28px truncate"
```
Comment (marktnoonan) [inline packages/launchpad/src/setup/OpenBrowserList.vue]: I think we need one more tweak to avoid the text running right up against the card border on the left:

```suggestion
            class="font-medium p-2 text-18px leading-28px truncate"
```

Before change:
no padding

After change:
with padding

After that we can merge :)

**Review by marktnoonan — CHANGES_REQUESTED** [review]
Hi @Manuel-Suarez-Abascal & thank you for addressing the CLA issue, I think we actually need one other small CSS change to the same line to correct a spacing issue, then we can approve and merge. I'm made a comment with a padding change that works.

**Review by marktnoonan — APPROVED** [review]

File: packages/launchpad/src/setup/OpenBrowserList.vue (hunk 1 above)
Comment (Manuel-Suarez-Abascal) [reply packages/launchpad/src/setup/OpenBrowserList.vue]: @marktnoonan I have addressed the PR comment. Good catch! 👍🏻

File: packages/launchpad/src/setup/OpenBrowserList.vue [hunk 2]
```diff
@@ -56,7 +56,7 @@
             >
           </div>
           <div
-            class="font-medium pt-2 text-18px leading-28px"
+            class="font-medium p-2 text-18px leading-28px truncate"
```
Comment (warrensplayer) [inline packages/launchpad/src/setup/OpenBrowserList.vue]:
```suggestion
            class="font-medium pt-2 px-2 text-18px leading-28px truncate"
```
Changing the `pt-2` to `p-2` also adds bottom padding where there did not used to be any.  This pushes the `div` containing the browser version down and adds 2px to the height of the box.  To keep the vertical spacing the same, you can keep the `pt-2` and just add `px-2` to give the needed padding on the left and right.

Comment (Manuel-Suarez-Abascal) [reply packages/launchpad/src/setup/OpenBrowserList.vue]: @warrensplayer I have addressed your PR comments.

**Review by elevatebart — APPROVED** [review]

**Review by warrensplayer — APPROVED** [review]
