### PR TITLE
simulated type fixes

### LINKED ISSUE #2166: cy.get('button').type() only works if button has `tabindex` specified
### Current behavior:

When calling `cy.type()` on a `<button>` element, Cypress throws:

```
CypressError: cy.type() failed because it requires a valid typeable element.
```

However if the `<button>` has a `tabindex` attribute of any value specified, then calling `cy.type()` will succeed.

### Desired behavior:

`cy.type()` should succeed in any case, since `<buttons>` are naturally focusable.

### Steps to reproduce:

Call `cy.type()` on `<button>` (will throw).
Call `cy.type()` on `<button tabindex="-1">` (will succeed).
Call `cy.type()` on `<button tabindex="0">` (will succeed).
Call `cy.type()` on `<button tabindex="1">` (will succeed).

### Versions

Cypress 3.0.2

### LINKED ISSUE #2240: cy.type should follow activeElement
During `cy.type()`, if a typeable element is focused other than the command's subject, Cypress should start typing into the newly focused element

This is a patch change, despite cypress behavior changing, because previously `cy.type` would continue to type into the subject, despite other elements gaining focus

### LINKED ISSUE #2613: Cannot type on datetime-local input
Hi, i'm trying to type on an input of `datetime-local` type.
On the documentation, it says that `datetime-local` is supported but nothing was never typed, no matter how I tried to type it `type.('10102019{rightarrow1010pm}'`,`type.('000000000000pm}')`. 
Also, in this #1366 issue has a workaround. but both did not work. 
It does select the input, but never types.

### LINKED ISSUE #3316: cy.type does not fire events for modifier keys
Currently, using a modifier key (ctrl, shift, etc) with `cy.type` only sets the property on subsequent type/click events. For example, `cy.get('body').type('{ctrl}a')` will only fire keyup/keydown/events for the `a` with `ctrlKey: true`. 

It should also fire those events for the control key itself. This means `cy.get('body').type('{ctrl}')` essentially does nothing.

We should fire the appropriate events, so the events fired for `{ctrl}a` look something like:

```
keydown ctrl
keydown a
keyup a
keyup ctrl
```

See the [related conversation here](https://github.com/cypress-io/cypress/issues/486#issuecomment-460287614) for more context.

### LINKED ISSUE #3405: type('{enter}') doesn't fire input event
### Current behavior:

I'm trying to test an app with the ace editor ( https://ace.c9.io/ ), which uses a `textarea`, but I'm running into a problem:

```js
describe('textarea', () => {
  it('can type the enter key', () => {
    cy.visit('http://ace.c9.io/build/kitchen-sink.html');
    cy.get('#editor-container .ace_editor textarea').type('foo{enter}', {force: true});
  });
});

```

It types 'foo' but does not press the Enter key.

### Desired behavior:

Using `{enter}` in `type` should press the Enter key.

### Steps to reproduce: (app code and test code)

See above.

### Versions

3.1.5, Chrome 72, MacOS

### LINKED ISSUE #3661: Cannot type into a, link, or select element
Cypress should be able to type into any focusable element, in case users want to test event listeners attached to the element

### LINKED ISSUE #3722: cy.type doesn't fill in KeyboardEvent.code
### Current behavior:

The `KeyboardEvent` object generated when using the `type` command doesn't contain the `code` property.

### Desired behavior:

The `KeyboardEvent` object generated when using the `type` command should contain the `code` property.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

### Versions

3.1.5

### LINKED ISSUE #4587: Filling forms using Hyperform
I encountered issues filling form fields with type() when the form is "enhanced" with Hyperform (https://hyperform.js.org/).

### Current behavior:
The form field is not filled.

### Desired behavior:
The form field shoud be filled.

### Steps to reproduce: (app code and test code)
No app code needed.

Test code:
```js
describe('Hyperform basic test', function() {
  it('it should be possible to fill a form field', function() {
    cy.visit('https://hyperform.js.org/examples.html#file=simple')
    cy.get('input').type('This will never appear')
  })
})
```

### Versions
Cypress 3.3.0 and 3.3.1
Chromium 69 and Electron 61

### LINKED ISSUE #4767: cannot `type` negative number into number input with text selection
Cannot `type` negative number into number input with text selection

Relevant issue description: https://github.com/cypress-io/cypress/issues/2173#issuecomment-513099254

### LINKED ISSUE #5424: cy.type should not insert text when non-shift modifier key is pressed
Current Behavior:
`cy.get('input').type('{meta}a')` 
sends `keypress`, `input`, and inserts 'a' into the input

Desired Behavior:
`cy.get('input').type('{meta}a')` 
should only send `keydown`/`keyup` and not insert the charater 'a' into the input

> This could be seen as a breaking change if fixed, but I'd say it could go in as  a patch

versions: -`3.4.1`

### PR DESCRIPTION
**Pull request by kuceb**
- [x] type validation during every character input, type following activeElement/focus
fix #2240
- [x] fix not borrowing property getter for `maxLength` during type validation
fix #4587
- [x] allow targeting any focusable element during `cy.type`
fix #2166
fix #3661
- [x] not updating value in `datetime-local` input
fix #2613
- [x] allow typing minus(`-`) sign into number field if entire field is selected
fix #4767 
- [x] fire input event when {enter} inserts newline
fix #3405
- [x] don't input text when non-shift modifier is pressed
fix #5424
- [x] fire 'code' property on keyboard events
fix #3722

- [x] ~use KeyboardEvent constructor instead of Event from app frame~ _forcing certain property values on the event during and after construction is not stable (does not work in chrome 63)_
- [x] use host contenteditable as focusable element when targeting element inside contenteditable (should help with rich text editors)
- [x] remove need to intercept `select` command and keep cypress cursor state on form elements

### Tasks
- [x] waiting on #3030 to be merged
- [x] wait on #5383 moving many typescript specific changes from this PR into there to make this diff manageable
- [x] wait on #5382  eslint config changes in separate PR (typescript-eslint changes)
- [x] fix error message for `cy.type`, use definition of `isFocusable`

### UX Changes:
error message on not typeable element
- before:
- after:

error message on not clearable element
- before:
- after:
image

type follows focus

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cy/keyboard.ts [hunk 1]
```diff
@@ -0,0 +1,1156 @@
...
+
+  performSimulatedDefault (el: HTMLElement, key: KeyDetails, options: any) {
+    debug('performSimulatedDefault', key.key)
+    const simulatedDefault = this.getSimulatedDefaultForKey(key)
+
+    // const isBody = $elements.isBody(el)
+    // const isFocusable = $elements.isFocusable($dom.wrap(el))
+    // const isTextLike = $elements.isTextLike(el)
+
+    // const isTypeableButNotTextLike = !isTextLike && isFocusable
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/keyboard.ts]: remove this commented out code

File: packages/driver/src/cy/keyboard.ts [hunk 2]
```diff
@@ -0,0 +1,1156 @@
...
+  const isClearChars = _.startsWith(chars.toLowerCase(), clearChars)
+
+  //# TODO: tabindex can't be -1
+  //# TODO: can't be readonly
+
+  if (isBody) {
+    return {}
+  }
+
+  if (!isFocusable && !isTextLike) {
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/keyboard.ts]: These 2 if statements are confusing. We're going to throw an error if `!isFocusable`, then we are further distinguishing the error shown by whether `isTextLike` or not. So, maybe:

```suggestion
  if (!isFocusable) {
   const node = $dom.stringify($el)
   const errMsg = isTextLike ? 'not_actionable_textlike' : 'not_on_typeable_element' 

    $utils.throwErrByPath(`type.${errMsg}`, {
      onFail,
      args: { node },
    })
 
  }
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/commands/actions/type.js [hunk 3]
```diff
@@ -65,520 +65,538 @@ module.exports = function (Commands, Cypress, cy, state, config) {
...
+    }
 
-      const isBody = options.$el.is('body')
-      const isTextLike = $dom.isTextLike(options.$el)
-      const isDate = $dom.isType(options.$el, 'date')
-      const isTime = $dom.isType(options.$el, 'time')
-      const isMonth = $dom.isType(options.$el, 'month')
-      const isWeek = $dom.isType(options.$el, 'week')
-      const hasTabIndex = $dom.isSelector(options.$el, '[tabindex]')
+    // const verifyElementForType = ($el) => {
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/commands/actions/type.js]: There's a lot of commented out code in this file too, can this be removed??

File: packages/driver/src/cypress/error_messages.coffee [hunk 4]
```diff
@@ -915,6 +924,7 @@ module.exports = {
     invalid_month: "Typing into a month input with #{cmd('type')} requires a valid month with the format 'yyyy-MM'. You passed: {{chars}}"
     invalid_week: "Typing into a week input with #{cmd('type')} requires a valid week with the format 'yyyy-Www', where W is the literal character 'W' and ww is the week number (00-53). You passed: {{chars}}"
     invalid_time: "Typing into a time input with #{cmd('type')} requires a valid time with the format 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS', where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999. You passed: {{chars}}"
+    invalid_dateTime: "Typing into a datetime input with #{cmd('type')} requires a valid datetime with the format 'yyyy-MM-ddThh:mm', for example '2017-06-01T08:30'. You passed: {{chars}}"
     multiple_elements: "#{cmd('type')} can only be called on a single element. Your subject contained {{num}} elements."
     not_on_typeable_element: """
```
Comment (jennifer-shehane) [inline packages/driver/src/cypress/error_messages.coffee]: refactor these error messages like we said - listing out what we consider 'isFocusable' elements - throw a more specific error message if the element is `[disabled]` and then list the other elements we check (with disabled excluded) for the error message if not already caught.

Comment (eps1lon) [reply packages/driver/src/cypress/error_messages.coffee]: This may seem very naive since I've spent barely any time with the implementation. I'm concerned about the kind of tests the current API allows with regard to accessibility:

Why do you even check focusability? The user agent already takes care of this and any custom logic you have will require maintenance. Simply forwarding `type` to something like `document.activeElement.dispatchEvent` seems like a simpler implementation that isn't subject to any confusion as to which elements are able to receive keyboard events.

The testing API shouldn't allow specifying the element that receives the keyboard event in the first place (or only when enabling a nasty sounding flag like `unsafe` or `force`). Otherwise you can construct test cases that are unreachable by a  real user.

Comment (jennifer-shehane) [reply packages/driver/src/cypress/error_messages.coffee]: >The user agent already takes care of this

I'm not sure what you mean by this. As browser automation software, Cypress has to programmatically automate everything, there is not a real user clicking, etc. Knowing what allows a focus event is a necessary part of any browser automation software. You're maybe thinking that Native browser events support would be better? https://github.com/cypress-io/cypress/issues/311 We agree and this is one of the requirements for moving forward with that.

Comment (eps1lon) [reply packages/driver/src/cypress/error_messages.coffee]: Hm maybe I'm misunderstanding something about the architecture but you do use the DOM provided by Chrome or electron no?

These user agents already prevent focus on an element that can't receive focus e.g.

```html
<main>try focusing me</main>
```

```js
console.assert(document.activeElement === document.body);

const main = document.querySelector('main');
main.focus();

console.assert(document.activeElement === document.body);
```
does already work. You do not have to implement any custom logic to only allow focus on e.g. elements with tabindex or `<button />` etc. So if you do have access to the DOM of a user agent such as chrome or electron there's no need for a custom focus filter.

Comment (Bkucera) [reply packages/driver/src/cypress/error_messages.coffee]: > Why do you even check focusability? The user agent already takes care of this and any custom logic you have will require maintenance.

@eps1lon this is a very common misconception that the user agent will perform default actions (inserting text, moving focus, moving cursor) by using `dispatchEvent`. This isn't true, and we must implement the default actions ourselves. The only case where the browser will react to a synthetic event sent through `dispatchEvent` is a checkbox can be toggled with the `click` event.

Comment (Bkucera) [reply packages/driver/src/cypress/error_messages.coffee]: @eps1lon also, when the browser is out of focus, `document.activeElement` will be updated, but focus events are queued until the window focus is regained. Because of this we need to "polyfill" focus events in some cases

Comment (eps1lon) [reply packages/driver/src/cypress/error_messages.coffee]: > this is a very common misconception that the user agent will perform default actions (inserting text, moving cursor) by using dispatchEvent.

I understand that. I'm specifically talking about `HTMLElement.focus()` not `dispatchEvent(new FocusEvent())`. See https://github.com/cypress-io/cypress/pull/4870#discussion_r328651245

**Comment by jennifer-shehane** [comment]
Need to fix some conflicts. 😢

File: packages/driver/src/cy/retries.coffee [hunk 5]
```diff
@@ -7,6 +7,10 @@ $utils = require("../cypress/utils")
 create = (Cypress, state, timeout, clearTimeout, whenStable, finishAssertions) ->
   return {
     retry: (fn, options, log) ->
+      ## FIXME: remove this debugging code
```
Comment (Bkucera) [inline packages/driver/src/cy/retries.coffee]: remove this before merge

File: packages/driver/src/cy/keyboard.ts [hunk 6]
```diff
@@ -1,44 +1,103 @@
...
+  shiftKey?: string
+  shiftText?: string
+  shiftKeyCode?: number
+  simulatedDefault?: SimulatedDefault
+  simulatedDefaultOnly?: boolean
+  events: {
+    [key in KeyEventType]?: boolean;
+  }
+}
+// const $Cypress = require('../cypress')
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: comment

File: packages/driver/src/cy/keyboard.ts [hunk 7]
```diff
@@ -47,680 +106,1010 @@ const toModifiersEventOptions = (modifiers) => {
...
-const fromModifierEventOptions = (eventOptions) => {
-  return _.pickBy({
-    alt: eventOptions.altKey,
-    ctrl: eventOptions.ctrlKey,
-    meta: eventOptions.metaKey,
-    shift: eventOptions.shiftKey,
+const fromModifierEventOptions = (eventOptions: {
+  [key: string]: string
+}): keyboardModifiers => {
+  const modifiers = _.pickBy(
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: tighten up

File: packages/driver/src/cy/keyboard.ts [hunk 8]
```diff
@@ -47,680 +106,1010 @@ const toModifiersEventOptions = (modifiers) => {
...
-        _.extend(event, {
-          location: 0,
-          repeat: false,
+      options.onAfterType()
+
+      return
+    }
+
+    return Promise.each(typeKeyFns, (fn) => {
+      return Promise.try(() => {
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: tighten up

File: packages/driver/src/dom/elements.ts [hunk 9]
```diff
@@ -23,7 +23,19 @@ const focusableSelectors = [
   '[tabindex]',
   '[contenteditable]',
 ]
-const inputTypeNeedSingleValueChangeRe = /^(date|time|month|week)$/
+const focusableWhenNotDisabledSelectors = [
```
Comment (brian-mann) [inline packages/driver/src/dom/elements.ts]: rename

File: packages/driver/src/dom/selection.ts [hunk 10]
```diff
@@ -128,130 +118,105 @@ const getHostContenteditable = function (el) {
...
-const deleteSelectionContents = function (el) {
+// const _getSelectionRangeByEl = function (el) {
+//   const sel = _getSelectionByEl(el)
+
+//   if (sel.rangeCount > 0) {
+//     return sel.getRangeAt(0)
+//   }
+
+//   throw new Error('No selection in document')
+// }
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: commented code

**Review by brian-mann — COMMENTED** [review]
The following fixes are not annotated anywhere in the code, or in the tests that test that they're working. Please update the source code + tests to link out to these issues.

fix #4587 fix not borrowing property getter for maxLength during type validation
fix #2166 allow targeting any focusable element during cy.type
fix #2613 not updating value in datetime-local input
fix #4767 allow typing minus(-) sign into number field if entire field is selected

**Review by brian-mann — CHANGES_REQUESTED** [review]
See my comment here: https://github.com/cypress-io/cypress/pull/4870#pullrequestreview-305447476

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 11]
```diff
@@ -378,6 +378,49 @@ describe('src/cy/commands/actions/click', () => {
       cy.getAll('div', 'pointerover pointerenter pointerdown mousedown pointerup mouseup click').each(shouldBeCalled)
     })
 
+    it('events when element removed on pointerdown', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]: @Bkucera why is this code here? this feels like code from the other `click` PR and not type related?

Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: snuck in during merge, fixed

**Comment by Bkucera** [comment]
@brian-mann added links to issues in the tests, used #3661 instead of #2116

File: packages/driver/test/cypress/integration/commands/waiting_spec.coffee [hunk 12]
```diff
@@ -632,6 +632,7 @@ describe "src/cy/commands/waiting", ->
           .wait("@getUsers").then (xhr) ->
             expect(xhr.url).to.include "/users?num=4"
             expect(xhr.responseBody).to.deep.eq resp
+      null
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/waiting_spec.coffee]: this is to make eslint OK with skipping the last test in suite

File: packages/driver/src/cy/keyboard.ts (hunk 6 above)
Comment (Bkucera) [reply packages/driver/src/cy/keyboard.ts]: fixed

File: packages/driver/src/cypress/cy.coffee [hunk 13]
```diff
@@ -82,8 +82,8 @@ create = (specWindow, Cypress, Cookies, state, config, log) ->
   jquery = $jQuery.create(state)
   location = $Location.create(state)
   focused = $Focused.create(state)
-  keyboard = $Keyboard.create(state)
-  mouse = $Mouse.create(state, keyboard, focused)
+  keyboard = new $Keyboard(state)
```
Comment (brian-mann) [inline packages/driver/src/cypress/cy.coffee]: go back to to using `create`

File: packages/driver/src/dom/selection.ts [hunk 14]
```diff
@@ -274,26 +229,22 @@ const moveCursorLeft = function (el) {
     return setSelectionRange(el, start - 1, start - 1)
   }
 
-  if ($elements.isContentEditable(el)) {
-    const selection = _getSelectionByEl(el)
+  // if ($elements.isContentEditable(el)) {
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: comment

File: packages/driver/src/dom/selection.ts [hunk 15]
```diff
@@ -274,26 +229,22 @@ const moveCursorLeft = function (el) {
...
-    return $elements.callNativeMethod(selection, 'modify', 'move', 'backward', 'character')
-  }
+  return $elements.callNativeMethod(
+    selection,
+    'modify',
+    'move',
+    'backward',
+    'character'
+  )
+  // }
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: comment

File: packages/driver/src/dom/selection.ts [hunk 16]
```diff
@@ -419,77 +379,111 @@ const selectAll = function (el) {
...
-    let lastTextNode = _getInnerLastChild(hostContenteditable)
+  if ($elements.canSetSelectionRangeElement(el)) {
+    let cursorPosition
 
-    if (lastTextNode.tagName === 'BR') {
-      lastTextNode = lastTextNode.parentNode
+    if (toStart) {
+      cursorPosition = 0
+    } else {
+      cursorPosition = $elements.getNativeProp(el, 'value').length
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: tighten up

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 17]
```diff
@@ -785,16 +771,13 @@ describe('src/cy/commands/actions/type', () => {
           fired = true
         })
 
-        fired = false
         cy.get('[contenteditable]:first')
         .invoke('html', 'foobar')
-        .type('{selectAll}{rightarrow}{del}')
-        .then(() => {
+        .type('{movetoend}')
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: this is new functionality right? this needs a referenced issue

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 18]
```diff
@@ -167,6 +167,18 @@ describe('src/cy/commands/actions/type', () => {
       })
     })
 
+    it('can type into element that redirects focus', () => {
+      cy.$$('div[tabindex]:first').on('focus', () => {
+        cy.$$('input:first').focus()
+      })
+
+      cy.get('div[tabindex]:first').type('foobar')
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: what is the subject here? did it change to the new element? or stay as the old one?

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 19]
```diff
@@ -1518,6 +1667,43 @@ describe('src/cy/commands/actions/type', () => {
             cy.get('input').eq(1).should('have.value', 'bar')
           })
         })
+
+        it('follows focus into date input', () => {
+          let charCount = 0
+
+          cy.$$('input:first').on('input', (e) => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: `_.after(3, () => {})`

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 20]
```diff
@@ -1518,6 +1667,43 @@ describe('src/cy/commands/actions/type', () => {
...
+        it('validates input after following focus change', (done) => {
+          cy.on('fail', (err) => {
+            expect(err.message).contain('fooBAR')
+            expect(err.message).contain('requires a valid date')
+            done()
+          })
+
+          let charCount = 0
+
+          cy.$$('input:first').on('input', (e) => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: `_.after(3, () => {})`

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 21]
```diff
@@ -2822,6 +3018,10 @@ describe('src/cy/commands/actions/type', () => {
           expect($input).to.have.value('FoO')
         })
       })
+
+      it('{shift} does not capitalize characters', () => {
+        cy.get('input:first').type('{shift}foo').should('have.value', 'foo')
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: likely need a note here to describe our implementation logic of why we consider this to be correct

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 22]
```diff
@@ -4373,13 +4601,15 @@ https://on.cypress.io/type`)
...
       })
 
-      _.each(['Ω≈ç√∫˜µ≤≥÷', '2.2250738585072011e-308', '田中さんにあげて下さい',
-        '<foo val=`bar\' />', '⁰⁴⁵₀₁₂', '🐵 🙈 🙉 🙊',
-        '<script>alert(123)</script>', '$USER'], (val) => {
-        it(`allows typing some naughtly strings (${val})`, () => {
-          cy
-          .get(':text:first').type(val)
-          .should('have.value', val)
+      describe('naughtly strings', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: naughtly lol

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/keyboard.ts (hunk 7 above)
Comment (brian-mann) [reply packages/driver/src/cy/keyboard.ts]: `_.pickBy` uses `_.identity` as the default

File: packages/driver/src/cy/keyboard.ts [hunk 23]
```diff
@@ -47,680 +105,1010 @@ const toModifiersEventOptions = (modifiers) => {
...
-          if (charsBetweenCurlyBracesRe.test(chars)) {
-          // allow special chars and modifiers to be case-insensitive
-            return chars.toLowerCase()
-          }
+    onKeyNotFound(key, _.keys(getKeymap()).join(', '))
 
-          return chars
-        })
-      }
+    throw Error(`Not a valid key: ${key}`)
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: i'm not sure this error can ever be hit

File: packages/driver/src/cy/keyboard.ts [hunk 24]
```diff
@@ -47,680 +105,1010 @@ const toModifiersEventOptions = (modifiers) => {
...
+    if ($elements.isTextLike(el)) {
+      if ($elements.isInput(el) || $elements.isTextarea(el)) {
+        const curText = $elements.getNativeProp(el, 'value')
+
+        simulatedDefault(el, key, options)
+        if (key.events.input !== false) {
+          options.onValueChange(curText, el)
+        } else {
+          // key.events.textInput = false
         }
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: weird commented out `else` condition

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js (hunk 18 above)
Comment (brian-mann) [reply packages/driver/test/cypress/integration/commands/actions/type_spec.js]: does not change

File: packages/driver/src/cy/keyboard.ts [hunk 25]
```diff
@@ -47,680 +107,1010 @@ const toModifiersEventOptions = (modifiers) => {
...
+          debug('returning null')
+
+          return null
         }
+      }
+    )
 
-        default: null
+    const modifierKeys = _.filter(keyDetailsArr, (key) => {
+      return isModifier(key)
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: tighten up

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/keyboard.ts (hunk 23 above)
Comment (Bkucera) [reply packages/driver/src/cy/keyboard.ts]: It cannot
