### PR TITLE
fix: adding timeout option to writeFile command

### LINKED ISSUE #3350: cy.writeFile timesout but also runs writeFile beyond the timeout.
### Current behavior:
The documentation says it is technically possible for `cy.writeFile` to timeout but it shouldn't, however, it did for me today. I know it was the `cy.writeFile` that timedout because it is the only cy.Command in my `aftereach` hook.

#### The Error Output:
```
  20) EditAndBranching
       "after each" hook for "Tag And Frog":
     Error: Cypress command timeout of '4000ms' exceeded.

Because this error occurred during a 'after each' hook we are skipping all of the remaining tests.
      at http://localhost:5050/__cypress/runner/cypress_runner.js:66264:25
```

### Desired behavior:
I think Cypress should provide a way to override the timeout or fix it so it can't timeout.

I also think Cypress should not stop running the remaining tests when one fails in the `aftereach` hook. That is a harsh punishment for an intermittent failure. In fact that also is a good case for not failing all tests in the `aftereach` since one failure does not necessarily mean they all will fail. Perhaps this needs a rethink as well. 

### Steps to reproduce: (app code and test code)

`"Issues without reproducible steps will get closed."` -- How am I supposed to give you code to reproduce this? Do I have to write some OS hook to intercept the writeFile command and make it take longer than 4 seconds?

Sorry but I don't have the time to work up some sort of repro steps...this requirement on obvious flaws is an impedance to filing a bug. I've reported the bug, if you all want to just close and do nothing then so be it.

### Versions

Cypress package version: 3.0.3
Cypress binary version: 3.0.3
OS Name:	Microsoft Windows 10 Enterprise
OS Version:	10.0.17763 Build 17763
Browser: Electron 59 (headless)

### PR DESCRIPTION
**Pull request by tbiethman**
- Closes #3350

### User facing changelog

A `timeout` option has been added to the writeFile command, with a default value of `defaultCommandTimeout`.
The default `maxHttpBufferSize` for the internal socket server has been increased to its maximum value.

### Additional details

During the investigation of #3350, it was discovered that writing large files could take a long time and cause the command to fail due to a non-specific Mocha timeout error. Typically, this failure was the result of us spending a long time encoding a very large file or overflowing the maximum size of the HTTP buffer as defined by the socket server.

The writeFile command has been updated to receive an explicit timeout option to give users more direct control over the command timeouts. It also uses a custom timeout implementation rather than relying on the default Mocha timeout; this allows us to report a more accurate error message when a timeout does occur. The default timeout value remains the `defaultCommandTimeout` value from the Cypress config.

The readFile command already receives a timeout option, but it is only used as part of its associated assertion retry logic. I added a custom timeout for readFile as well to ensure that we can report the appropriate error messages when the readFile command itself times out. This doesn't require a user-facing API change.

### How has the user experience changed?

Old error message:
Screen Shot 2021-12-02 at 10 26 58 AM

New error message:
Screen Shot 2021-12-02 at 10 23 07 AM

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? [Link](https://github.com/cypress-io/cypress-documentation/pull/4244)
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] ~~Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?~~

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -2228,7 +2228,7 @@ declare namespace Cypress {
     })
     ```
      */
-    writeFile<C extends FileContents>(filePath: string, contents: C, options?: Partial<WriteFileOptions>): Chainable<C>
+    writeFile<C extends FileContents>(filePath: string, contents: C, options?: Partial<WriteFileOptions & Timeoutable>): Chainable<C>
```
Comment (tbiethman) [inline cli/types/cypress.d.ts:2231]: Note: readFile's option type already includes Timeoutable, but it is not used in the existing implementation beyond logging.

File: packages/server/lib/files.js [hunk 2]
```diff
@@ -2,45 +2,93 @@ const path = require('path')
...
+    let readFileTimeout
+
+    if (options.timeout !== undefined) {
+      readFileTimeout = setTimeout(() => {
+        readFileAbortController.abort()
+      }, options.timeout)
+    }
+
+    try {
+      // graceful-fs does not support the standard fs Promise API.
```
Comment (mjhenkes) [inline packages/server/lib/files.js:30]: What benefit is graceful-fs giving us?

Comment (flotwig) [reply packages/server/lib/files.js:30]: mainly, `graceful-fs` automatically queues/retries on `EMFILE` errors, which is the error thrown when there are too many open file handles. occasionally Cypress hits this (so I've been told, I've never seen it), so that's why we use graceful-fs.

That being said... graceful-fs seems to be no longer maintained, so we should probably move away from it at the first excuse we get.

File: packages/driver/cypress/integration/commands/files_spec.js [hunk 3]
```diff
@@ -394,7 +443,7 @@ describe('src/cy/commands/files', () => {
       Cypress.backend.resolves(okResponse)
 
       cy.writeFile('foo.txt', 'contents').then((subject) => {
-        expect(subject).to.not.exist
+        expect(subject).to.eq(null)
```
Comment (tbiethman) [inline packages/driver/cypress/integration/commands/files_spec.js:446]: Made this more explicit. I had a bug where I was yielding undefined and this test continued to pass.

**Review by mjhenkes — DISMISSED** [review]

File: packages/driver/src/cy/commands/files.ts [hunk 4]
```diff
@@ -43,57 +47,71 @@ export default (Commands, Cypress, cy) => {
...
+          } else if (err.name === 'TimeoutError') {
+            return $errUtils.throwErrByPath('files.timed_out', {
+              onFail: options._log,
+              args: { cmd: 'readFile', file, timeout: options.timeout },
+            })
+          } else {
+            return $errUtils.throwErrByPath('files.unexpected_error', {
+              onFail: options._log,
+              args: { cmd: 'readFile', action: 'read', file, filePath: err.filePath, error: err.message },
+            })
```
Comment (flotwig) [inline packages/driver/src/cy/commands/files.ts:70]: nit: there's no reason to use `else` here

File: cli/types/cypress.d.ts (hunk 1 above)
Comment (flotwig) [reply cli/types/cypress.d.ts:2231]: It yields `null`, so is this...

```suggestion
    writeFile(filePath: string, contents: FileContents, options?: Partial<WriteFileOptions & Timeoutable>): Chainable<null>
```

?

**Review by flotwig — CHANGES_REQUESTED** [review]

File: cli/types/cypress.d.ts (hunk 1 above)
Comment (tbiethman) [reply cli/types/cypress.d.ts:2231]: Oh good call, I'll get this and the other definitions updated.

File: packages/driver/src/cy/commands/files.ts (hunk 4 above)
Comment (tbiethman) [reply packages/driver/src/cy/commands/files.ts:70]: Without the else, we'll throw in the case of a ENOENT error, which we're trying to avoid. I could restructure this a bit to be more clear?

**Review by flotwig — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

**Review by mjhenkes — DISMISSED** [review]

**Review by mjhenkes — APPROVED** [review]

File: packages/driver/src/cy/commands/files.ts [hunk 5]
```diff
@@ -43,21 +43,33 @@ export default (Commands, Cypress, cy) => {
         })
       }
 
+      // We clear the default timeout so we can handle
+      // the timeout ourselves
+      cy.clearTimeout()
+
       const verifyAssertions = () => {
-        return Cypress.backend('read:file', file, _.pick(options, 'encoding'))
+        return Cypress.backend('read:file', file, _.pick(options, 'encoding')).timeout(options.timeout)
```
Comment (flotwig) [inline packages/driver/src/cy/commands/files.ts:51]: So no server-side timeout?

**Review by flotwig — APPROVED** [review]
@tbiethman is there going to be a separate PR for #19142?

**Comment by tbiethman** [comment]
@flotwig regarding #19142, yes. #19275 has been opened in a draft state for testing

File: packages/driver/src/cy/commands/files.ts (hunk 5 above)
Comment (tbiethman) [reply packages/driver/src/cy/commands/files.ts:51]: Not with this PR, no. I'm going to log a separate issue to track and evaluate how we want to handle command/server timeouts and increase the determinism of those workflows.
