### PR TITLE
fix: Check custom config file during language detection

### LINKED ISSUE #24781: When running cypress against a docker image on CI pipeline(using Codefresh) the image hangs for quite a while if using prettier-eslint cli without typescript installed on the detect Resolved typescript step
### Current behavior

When Typescript is not installed as a dev dependency in package.json. The image hangs in codefresh stuck on the detect detect for a few minutes before continuing.
`cypress:scaffold-config:detect Resolved typescript from /node_modules/typescript/lib/typescript.js +0ms`
After removing the prettier-eslint library we noticed that the message changed and the CI Pipeline continues without hanging with this message.
`cypress:scaffold-config:detect No typescript installed - using js +0ms`
Looking in the cypress repo it seems to be this change here listed in the below PR. It seems that the check was changed to check for a typescript lib in the nodemodules library and defaults to typescript even though the package we are using is using typescript but our cypress project was using javascript.
https://github.com/cypress-io/cypress/commit/309c31f89905809d9a4122a86e5d289e9f6c95a1#diff-ce8622dde6ed83c3ceb55b5766f02a3dd06e26b84a51e0de44083e9246a768bfR123-R140

### Desired behavior

If the cypress repo is a javascript repo and we have a package is that using typescript we should not need to install typescript as a dependency in the package.json file

### Test code to reproduce

Step to Repro:

1. Create a javascript test repo
2. Install prettier-eslint-cli 
3. Setup a config file
4. Create Docker Image
5. Run in a CI pipeline with the command `cypress run  --spec "cypress/e2e/start.spec.js" --browser chrome`

DockerFile
`FROM cypress/included:10.0.2`

### Cypress Version

10.0.2 - 11.1.0

### Node version

16.16

### Operating System

Docker Image on Linux in CI environment

### Debug Logs

```shell
After removing prettier-eslint-cli
`
cypress:scaffold-config:detect No typescript installed - using js +0ms
  cypress:server:video using ffmpeg from /root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg +0ms
  cypress:server:performance-benchmark elapsed time at run mode ready: 461.424ms +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/', '--file', '/cypress-rbc.config.js' ], childOptions: { stdio: 'pipe', cwd: '/', execPath: '/usr/local/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc no typescript found, just use regular Node.js +0ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +7ms
  cypress:lifecycle:child:run_require_async_child:286 configFile: /cypress-rbc.config.js +0ms
  cypress:lifecycle:child:run_require_async_child:286 projectRoot: / +0ms
  cypress:lifecycle:child:run_require_async_child:286 try loading /cypress-rbc.config.js +2ms
  cypress:lifecycle:child:run_require_async_child:286 Loading file /cypress-rbc.config.js +0ms
`

Before removing Prettier-eslint-cli

`
Cypress:scaffold-config:detect Resolved typescript from /node_modules/typescript/lib/typescript.js +0ms
  cypress:server:video using ffmpeg from /root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg +0ms
  cypress:server:performance-benchmark elapsed time at run mode ready: 485421.722ms +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/', '--file', '/cypress-rbc.config.js' ], childOptions: { stdio: 'pipe', cwd: '/', execPath: '/usr/local/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc found typescript in / +1ms
  cypress:lifecycle:ProjectConfigIpc using cjs with --require /root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/register_ts_node.js +0ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +162ms
  cypress:server:register-ts-node executing register_ts_node with args { _: [ '/usr/local/bin/node', '/root/.cache/Cypress/11.1.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js' ], projectRoot: '/', file: '/cypress-rbc.config.js' } +0ms
  cypress:server:register-ts-node registering ts-node for projectRoot: / and file: /cypress-rbc.config.js +2ms
  cypress:server:ts-node projectRoot path: / +0ms
  cypress:server:ts-node registeredFile: /cypress-rbc.config.js +0ms
  cypress:server:plugins resolving typescript with projectRoot '/' +0ms
  cypress:server:plugins resolved typescript /node_modules/typescript/lib/typescript.js +0ms
  cypress:server:ts-node typescript path: /node_modules/typescript/lib/typescript.js +0ms
  cypress:server:ts-node registering project TS with options { compiler: '/node_modules/typescript/lib/typescript.js', compilerOptions: { module: 'commonjs' }, dir: '/', transpileOnly: true } +173ms
Couldn't find tsconfig.json. tsconfig-paths will be skipped
`
```

### Other

The fix for us was to also install typescript into our node packages even though we have a javascript cypress project.
Before
`
 "devDependencies": {
    "@babel/core": "^7.13.1",
    "@babel/eslint-parser": "^7.13.4",
    "@babel/eslint-plugin": "^7.13.0",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@cypress/instrument-cra": "^1.4.0",
    "@cypress/skip-test": "^2.6.0",
    "@cypress/snapshot": "^2.1.7",
    "@testing-library/cypress": "^8.0.2",
    "axe-core": "^4.5.2",
    "babel-plugin-istanbul": "^6.0.0",
    "cypress": "^11.1.0",
    "cypress-audit": "^0.3.0",
    "cypress-postgres": "^1.1.1",
    "cypress-recurse": "^1.23.0",
    "cypress-repeat": "^2.2.1",
    "eslint-plugin-cypress": "^2.11.2",
    "eslint-plugin-unused-imports": "^2.0.0",
    "gmail-tester": "^1.3.1",
    "husky": "^6.0.0",
    "junit-report-merger": "^3.0.6",
    "nyc": "^15.1.0",
    "prettier-eslint-cli": "^5.0.1"
  },
`
After
`
"devDependencies": {
    "@babel/core": "^7.13.1",
    "@babel/eslint-parser": "^7.13.4",
    "@babel/eslint-plugin": "^7.13.0",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@cypress/instrument-cra": "^1.4.0",
    "@cypress/skip-test": "^2.6.0",
    "@cypress/snapshot": "^2.1.7",
    "@testing-library/cypress": "^8.0.2",
    "axe-core": "^4.5.2",
    "babel-plugin-istanbul": "^6.0.0",
    "cypress": "^11.1.0",
    "cypress-audit": "^0.3.0",
    "cypress-postgres": "^1.1.1",
    "cypress-recurse": "^1.23.0",
    "cypress-repeat": "^2.2.1",
    "eslint-plugin-cypress": "^2.11.2",
    "eslint-plugin-unused-imports": "^2.0.0",
    "gmail-tester": "^1.3.1",
    "husky": "^6.0.0",
    "junit-report-merger": "^3.0.6",
    "nyc": "^15.1.0",
    "prettier-eslint-cli": "^7.1.0",
    "typescript": "^4.9.3"
  },
`

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #24781 

### User facing changelog
Fixes delay on Cypress startup when using a custom config file location.

### Additional details
Original issue presented as a multi-minute hang while determining whether project is JS/TS-based when running within Docker. Investigation indicates that the user was providing a custom Cypress config file location and was using the `cypress:included:*` image root as their project directory. Existing logic checks whether there is a `cypress.config.*` file present at the project root, if not it then falls back to doing recursive filesystem scans for TS files. The scan ignores `node_modules` but was likely scanning into OS and browser-related directories since it was running from the image root, and being on Docker exacerbates filesystem slowness.

This PR adds logic to consider the custom config file argument (if provided) then fall back to the default config file. This would mitigate the issue the user observed, but a delay could still present in several situations:
- First project launch - no custom config provided, no `cypress.config.*` file generated yet
- User provides incorrect custom config param or has mis-named default config
- User attempts to use `.mjs` or other non-standard extension for config file

Not sure if there's a guaranteed fix since we can't provide a full set of exclusion directories (Windows, Unix, Mac, etc all have lots of different stuff at OS root), but maybe we could print a warning if `projectDirectory === '/'`? Or potentially print a warning if we can't find custom or default config and have to fall back to filesystem scan?

### Steps to test
1. Create an empty project:
`mkdir test`
`cd test`
`npm init`
2. Launch Cypress: `DEBUG=cypress:scaffold-config:detect yarn cypress:open --project test`
3. Observe debug logging - no config file found, no typescript installed, defaults to JS
4. Launch Cypress, providing a custom TS config file location: `DEBUG=cypress:scaffold-config:detect yarn cypress:open --project test --config-file my-config.ts`
5. Observe debug logging that project lang is `ts` based off custom config file
6. Launch Cypress, providing a custom JS config file location: `DEBUG=cypress:scaffold-config:detect yarn cypress:open --project test --config-file my-config.js`
7. Observe debug logging that project lang is `js` based off custom config file
8. Create JS config file: `touch test/cypress.config.js`
9. Launch: `DEBUG=cypress:scaffold-config:detect yarn cypress:open --project test`
10. Observe Cypress resolves 'js' from default config file
11. Delete JS config file: `rm test/cypress.config.js`
12. Create TS config file: `touch test/cypress.config.ts`
13. Launch: `DEBUG=cypress:scaffold-config:detect yarn cypress:open --project test`
14. Observe Cypress resolves 'ts' from default config file

### How has the user experience changed?
No visible change, performance improvement on launch

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/scaffold-config/src/detect.ts [hunk 1]
```diff
@@ -88,7 +88,12 @@ export async function detectFramework (projectPath: string): Promise<DetectFrame
  * If `cypress.config` exists, we derive the language
  * from the extension.
  *
- * IF HAS_CYPRESS_CONFIG
+ * IF HAS_CUSTOM_CYPRESS_CONFIG
```
Comment (lmiller1990) [inline packages/scaffold-config/src/detect.ts:91]: Thank you for updating this!

File: packages/scaffold-config/src/detect.ts [hunk 2]
```diff
@@ -113,8 +118,34 @@ export async function detectFramework (projectPath: string): Promise<DetectFrame
...
   try {
+    if (customConfigFile) {
+      debug('Evaluating custom Cypress config file \'%s\'', customConfigFile)
+      if (/.ts$/.test(customConfigFile)) {
+        debug('Custom config file is Typescript - using TS')
+
+        return 'ts'
+      }
+
+      if (/.js$/.test(customConfigFile)) {
```
Comment (lmiller1990) [inline packages/scaffold-config/src/detect.ts]: We might need to widen this check, we also support `cjs` and `mjs` (and soon `mts`, I hope, some people asked for that).

Here's the default list of files we look for with the extensions we support: https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/data/ProjectLifecycleManager.ts#L37-L42

Comment (mike-plummer) [reply packages/scaffold-config/src/detect.ts]: @lmiller1990 Excellent point - pushed an update that expands the checks for both default and custom config file extensions to support `cjs`, `mjs`, and `mts`. I know `mts` isn't officially supported yet, but I believe it should be safe to include here since this is just trying to figure out what language the project is trying to use - failure to actually parse/support the config file will occur elsewhere. Please let me know if you disagree

File: packages/scaffold-config/test/unit/detect.spec.ts [hunk 3]
```diff
@@ -265,162 +265,219 @@ describe('detectFramework', () => {
...
+      removeAllTsFilesExcept(projectRoot, 'plugins')
 
-    const actual = detectLanguage({ projectRoot, pkgJson })
+      const actual = detectLanguage({ projectRoot, pkgJson: {} as PkgJson })
 
-    expect(actual).to.eq('js')
+      expect(actual).to.eq('ts')
+    })
+
+    it('cwith a TypeScript integration specs', async () => {
```
Comment (astone123) [inline packages/scaffold-config/test/unit/detect.spec.ts]: Is this test the same as the one below it? I don't see a difference between the two

**Review by astone123 — APPROVED** [review]
Looks good 👍🏻

File: packages/scaffold-config/test/unit/detect.spec.ts (hunk 3 above)
Comment (mike-plummer) [reply packages/scaffold-config/test/unit/detect.spec.ts]: Good catch - appears to have been a duplicate, just a slightly different name. Removed

File: packages/scaffold-config/src/detect.ts (hunk 2 above)
Comment (lmiller1990) [reply packages/scaffold-config/src/detect.ts]: Sounds good. `mts` probably won't work yet, but adding this now will save us doing it later on when do we support `mts`.

**Review by lmiller1990 — APPROVED** [review]
