### PR TITLE
fix: set the value of testingType in project-ct

### LINKED ISSUE #16860: Forced to return config in the plugins file even I don't change it
### Current behavior
In component testing, if my `plugins/index.js` files function does not return config (see below), the command log displays a "no tests found" error see #16812

```js
// faulty cypress/plugins/index.js
module.exports = (on, config) => {
  on('dev-server:start', (options) => {
    return startDevServer({ options, webpackConfig })
  })
}
```

### Versions

cypress 7.5.0

### PR DESCRIPTION
**Pull request by elevatebart**
- Closes #16860

### User facing changelog
Before this PR launching cypress open-ct (Component Testing) with the function exported by `cypress/plugins/index.js` returning nothing would yield a "No test found" error.
Now we can omit this `return config` if it is not changed in the function.

### Additional details

```js
const path = require('path')
const { startDevServer } = require('../dist')

module.exports = (on, config) => {
  on('dev-server:start', async (options) => {
    return startDevServer({
      options,
      viteConfig: {
        configFile: path.resolve(__dirname, '..', 'vite.config.ts'),
      },
    })
  })

  return config; // << this statement is not necessary anymore
}
```

The main file to review is the last one: [project-ct.ts](https://github.com/cypress-io/cypress/pull/16885/files#diff-1973eee6e4c774537a1f964ab8d6bb83b8f9d81be34ddcb2fe484439050d90cb)
The rest are examples updates and changes to scaffolding with `create cypress-tests` to reflect the simplified setup.

### How has the user experience changed?
**Before**: with no return config every spec file would yield the error below
Screen Shot 2021-06-09 at 5 02 24 PM

**After**: tests are running with or without the `return config`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server-ct/src/project-ct.ts [hunk 1]
```diff
@@ -89,6 +89,13 @@ export class ProjectCt extends ProjectBase<ServerCt> {
 
       updatedConfig.componentTesting = true
```
Comment (lmiller1990) [inline packages/server-ct/src/project-ct.ts:90]: So this was the problem!

Interesting. I think it's still a good practice to encourage people to return the config regardless, but good job tracking this one down.

File: npm/create-cypress-tests/src/component-testing/templates/_shared/vite.ts [hunk 2]
```diff
@@ -10,7 +10,6 @@ export const ViteTemplate: Template = {
   dependencies: ['@cypress/vite-dev-server'],
   getPluginsCodeAst: () => {
     return {
-      requiresReturnConfig: true,
```
Comment (lmiller1990) [inline npm/create-cypress-tests/src/component-testing/templates/_shared/vite.ts:13]: Even if this isn't technically required, I think it's probably still good to leave it in. `return config` won't break anything, and we generally recommend it in all our documentation. Any compelling reason *not* to return it?

**Review by lmiller1990 — COMMENTED** [review]
LGTM, one comment!

File: packages/server-ct/src/project-ct.ts (hunk 1 above)
Comment (elevatebart) [reply packages/server-ct/src/project-ct.ts:90]: Why is that a good practice? I don't understand.

File: npm/create-cypress-tests/src/component-testing/templates/_shared/vite.ts (hunk 2 above)
Comment (elevatebart) [reply npm/create-cypress-tests/src/component-testing/templates/_shared/vite.ts:13]: Because it is not necessary and could be mutated "by mistake". 
My philosophy for APIs and best practices is if you cannot explain why you would add a line of code, or why not, you should probably not have it. 

Less code, less questions, less bugs

**Review by lmiller1990 — APPROVED** [review]
