### PR TITLE
fix(route2): empty arrays are correctly JSONified in all circumstances

### LINKED ISSUE #8532: cy.route2 does not automatically JSONify an empty array handler
### Current behavior:
This is not automatically JSONified:

```js
cy.route2('/favorite-fruits', [])
```

This is:

```js
cy.route2('/favorite-fruits', ['foo'])
```

### Desired behavior:
Empty arrays are automatically JSONified.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #8532

### User facing changelog

- Fixed an issue with `cy.route2` where stubbing a response with an empty array did not work as expected.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -480,6 +496,45 @@ describe('network stubbing', function () {
...
+            expect(responseJson).to.deep.eq([])
+            expect(xhr.getResponseHeader('content-type')).to.eq('application/json')
+
+            done()
+          })
+        }
+      }
+
+      it('with explicit StaticResponse', function (done) {
+        cy.route2({
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:514]: how about matching to the non-empty test
```
cy.route2({ url: '*' }, [])
```

File: packages/driver/src/cy/net-stubbing/static-response-utils.ts [hunk 2]
```diff
@@ -111,5 +111,5 @@ export function getBackendStaticResponse (staticResponse: Readonly<StaticRespons
 }
 
 export function hasStaticResponseKeys (obj: any) {
-  return _.intersection(_.keys(obj), STATIC_RESPONSE_KEYS).length || _.isEmpty(obj)
+  return !_.isArray(obj) && (_.intersection(_.keys(obj), STATIC_RESPONSE_KEYS).length || _.isEmpty(obj))
```
Comment (bahmutov) [inline packages/driver/src/cy/net-stubbing/static-response-utils.ts:114]: as hairy as Hagrid from Harry Potter

**Review by bahmutov — APPROVED** [review]
thank you
