### PR TITLE
fix: Improve cross-origin cookie handling

### LINKED ISSUE #20685: Multi-domain: Improve cookie handling
### What would you like?

The SameSite cookie handling implemented in https://github.com/cypress-io/cypress/pull/20450 is a stop-gap measure to make it work for the experimental release of multi-domain, coercing multi-domain cookies to have `SameSite=None`. 

For the GA release of multi-domain support, instead of mutating cookies, the strategy should be the following:

- Recognize multi-domain cookies that the browser won't set but would be set if the user's app were not in an iframe
- Capture those cookies in our own cookie jar*
- Change the header to `X-Set-Cookie` so it's clear the cookies are not being set by standard means
- When a request is made to a domain for which we have stored cookies and it's appropriate to attach them based on its SameSite policy, do so

* I did a proof of concept where I set the cookies on the browser's cookie jar. In that case, they do get set but still aren't attached to requests, so we still have to attach them ourselves. Getting the cookies from automation to attach them worked fine in Chrome, but would not work in Firefox. Further investigation into fixing that could be done, but there's also increased latency per request involved in that approach too, whereas using our own cookie jar should be much faster. We just need to make sure it behaves like the browser's (e.g. unsetting the cookie when expired).

### Why is this needed?

We need cookies to work as they would normally for the sake of authentication in multi-domain. The experimental release version is not ideal, since it relies on mutating all cookies to be `SameSite=None` and also needs a potentially brittle workaround for Firefox localhost cookies. 

The proposed solution can be more nuanced. It can set cookies from responses and attach cookies to requests the way the browser would in a non-iframe situation. The user will still be able to see the cookies in the DevTools Network tab on requests as they were sent by the response instead of our mutated version. 

### Other

_No response_

### LINKED ISSUE #21363: Cypress 9.6.0- Unable to login to applications via Github using cy.origin
### Current behavior

I am trying to use cy.origin to login to CircleCi(https://circleci.com/vcs-authorize/). Also, have 2Factor disabled on my GitHub Id. **My login is successful and authorized via GitHub but after then it is failing to redirect me to the CircleCi dashboard**(https://app.circleci.com/).

A similar issue is happening on Netlify. I am able to login to github from cy.origin but then it is not redirecting me to the netlify home page(https://app.netlify.com/).

I am trying to replicate what is mentioned in the cypress blog. It is mentioned that cy.origin can be used for third part login such as Auth0 and Github. I need your investigation.

https://cypress.io/blog/2022/04/25/cypress-9-6-0-easily-test-multi-domain-workflows-with-cy-origin/
Screenshot 2022-05-05 at 6 12 14 PM

Screenshot 2022-05-05 at 6 18 33 PM

### Desired behavior

After successful login from Github, user should be redirected to the application under test. 

### Test code to reproduce

```
describe("Test visiting multiple domains in single test", () => 

  it("should login to circle ci with github", () => {
    //visit circleci login page
    cy.visit("https://circleci.com/vcs-authorize/");

    //click on sign in link
    cy.contains("Log In with GitHub").click({ force: true });

    //click on 'login with Github' button
    cy.origin("https://github.com", () => {
      cy.get("#login_field").type("************");
      cy.get("#password").type("********");
      cy.get("input").contains("Sign in").click();
    });

    // should load circleci app with logged in user
    cy.url().should("contain", "https://app.circleci.com/");
  });

  it("should login to netlify with github", () => {
    //visit netlify
    cy.visit("https://www.netlify.com/");
    
    // click on menu option
    cy.get(".icon-hamburger").click({ force: true });

    //click on login 
    cy.contains("Log in").click({ force: true });
   
    //click on 'login with Github' button
    cy.contains("GitHub").click({ force: true });

    //enter login credentials for github
    cy.origin("https://github.com", () => {
      cy.get("#login_field").type("************");
      cy.get("#password").type("********");
      cy.get("input").contains("Sign in").click();
      cy.wait(10000);
    });

    // should load netlify app with logged in user
    cy.url().should("contain", "https://app.netlify.com/");
  });
});

```

### Cypress Version

9.6.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #20685
- Closes #21363

### User facing changelog

- Fixed various issues with cookies when testing across multiple origins

### Additional details

Previously, we worked around handling cross-origin cookie limitations by forcing all cookies to be `SameSite=None`. This introduces a new approach where all cookies are captured in a server-side cookie jar and, where needed, cookies are attached to cross-origin requests to simulate what the browser would do if the AUT were in the top frame.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/automation/automation.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { Cookies } from './cookies'
 import { Screenshot } from './screenshot'
 import type { BrowserPreRequest } from '@packages/proxy'
 import type { AutomationMiddleware, OnRequestEvent } from '@packages/types'
+import { removeAllCookies, removeCookie } from '../cookie-jar'
```
Comment (emilyrohrbough) [inline packages/server/lib/automation/automation.ts:7]: without lookin into this deeply, why not merge the cookie jar and the cookies class? the names make it sound like one or the other could leverage each other and/or they could be merged?

Seems like the Cookies class might be able to.

File: packages/proxy/lib/http/response-middleware.ts [hunk 2]
```diff
@@ -393,101 +393,105 @@ const MaybePreventCaching: ResponseMiddleware = function () {
...
+  try {
+    await this.getAutomation().request('set:cookies', addedCookies, () => {})
+  } catch (err) {
+    this.debug('failed setting cookies via automation: %s', err.message)
+  } finally {
+    this.next()
+  }
 }
 
+// TODO: error if this.next() is called twice in same block if possible
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/response-middleware.ts:493]: will this TODO be handled in this PR? or do we need to log a followup issue?

File: packages/server/lib/cookie-jar.ts [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    cookieJar.store.removeCookie(
+      cookieData.domain,
+      cookieData.path || '/',
+      cookieData.name,
+      () => {},
+    )
+  }
+
+  removeAllCookies () {
+    this._cookieJar.removeAllCookiesSync()
```
Comment (emilyrohrbough) [inline packages/server/lib/cookie-jar.ts:47]: Does this need to be sync?

File: packages/server/lib/automation/automation.ts (hunk 1 above)
Comment (chrisbreiding) [reply packages/server/lib/automation/automation.ts:7]: They serve different purposes. 

`lib/cookie-jar` is a stateful wrapper around tough-cookie's cookie implementation and stores cookies in memory for the sake of cross-origin testing. 

`lib/automation/cookies` is a stateless wrapper around automating cookies. It's more about taking actions with cookies than storing them.

I don't really see anything that can be shared between them and I think it makes sense to keep their concerns separate.

File: packages/server/lib/cookie-jar.ts (hunk 3 above)
Comment (chrisbreiding) [reply packages/server/lib/cookie-jar.ts:47]: It doesn't need to, but there's no reason for it not to be sync. The cookie store is kept in memory, so all [this ends up doing](https://github.com/salesforce/tough-cookie/blob/b8d751188da697157e5eed81fa1e5f806fdfb541/lib/memstore.js#L148-L151) is basically `cookieJar.cookies = {}`. There's no sync file system access to worry about or anything.

File: packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts [hunk 4]
```diff
@@ -1,95 +1,629 @@
...
+      cy.get('[data-cy="cookie-login"]').click()
+      cy.origin('http://foobar.com:3500', { args: { username } }, ({ username }) => {
+        cy.get('[data-cy="username"]').type(username)
+        cy.get('[data-cy="login"]').click()
+      })
+
+      cy.clearCookies()
+      cy.reload()
+      verifyLocalhostNotLoggedIn()
+    })
```
Comment (mjhenkes) [inline packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:143]: Is this test a duplicate?

Comment (chrisbreiding) [reply packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:143]: A duplicate of the one above it? That covers _cy.clearCookie()_ (clearing a single cookie) and this one covers _cy.clearCookie**s**()_ (clearing all cookies).

Comment (mjhenkes) [reply packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:143]: I missed the lone `s`! 😭

File: packages/driver/src/cy/commands/sessions/manager.ts [hunk 5]
```diff
@@ -131,6 +131,7 @@ export default class SessionsManager {
       await Promise.all([
         this.sessions.clearStorage(),
         this.sessions.clearCookies(),
+        this.Cypress.backend('clear:cross:origin:cookies', null),
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cy/commands/sessions/manager.ts]: Good call. Addressed in [`d34f408` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/d34f408d0e3c599caa43e50cd8e192d7ae8528a5)

File: packages/proxy/lib/http/response-middleware.ts (hunk 2 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts]: Yes! Forgot about that one. Addressed in [`3c81b36` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/3c81b364c0ec56bbe1c769e4cd417fff51a19214)

**Review by mjhenkes — APPROVED** [review]

File: packages/proxy/lib/http/util/cookies.ts [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+  const toughCookie = Cookie.parse(cookie)
+
+  if (!toughCookie) return
+
+  // fixes tough-cookie defaulting undefined/invalid SameSite to 'none'
+  // https://github.com/salesforce/tough-cookie/issues/191
+  const hasUnspecifiedSameSite = toughCookie.sameSite === 'none' && !sameSiteNoneRe.test(cookie)
+
+  if (hasUnspecifiedSameSite) {
+    toughCookie.sameSite = 'lax'
```
Comment (mschile) [inline packages/proxy/lib/http/util/cookies.ts:54]: Not all browsers default to 'lax'. Does that matter here?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#browser_compatibility

File: packages/proxy/lib/http/util/cookies.ts [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+
+    const parsedRequestUrl = new URL(request.url)
+
+    this.defaultDomain = parsedRequestUrl.hostname
+  }
+
+  async capturePreviousCookies () {
+    // this plays a part in adding cross-origin cookies to the browser via
+    // automation. if the request doesn't need cross-origin handling, this
+    // is a nooop
```
Comment (mschile) [inline packages/proxy/lib/http/util/cookies.ts:119]:
```suggestion
    // is a noop
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 8]
```diff
@@ -0,0 +1,156 @@
...
+    if (!this.request.needsCrossOriginHandling) return
+
+    this.previousCookies = this.cookieJar.getAllCookies()
+  }
+
+  async getAddedCookies () {
+    // this plays a part in adding cross-origin cookies to the browser via
+    // automation. if the request doesn't need cross-origin handling, this
+    // is a nooop
```
Comment (mschile) [inline packages/proxy/lib/http/util/cookies.ts:128]:
```suggestion
    // is a noop
```

File: packages/server/lib/socket-base.ts [hunk 9]
```diff
@@ -474,6 +476,8 @@ export class SocketBase {
               return this.localBus.emit('cross:origin:release:html')
             case 'cross:origin:finished':
               return this.localBus.emit('cross:origin:finished', args[0])
+            case 'url:changed':
```
Comment (mschile) [inline packages/server/lib/socket-base.ts:479]: Is this related to cookies or something that was missed previously?

**Review by mschile — CHANGES_REQUESTED** [review]

File: packages/proxy/lib/http/util/cookies.ts (hunk 7 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: I just wanted to emphasize that this does nooothing in that situation 😅

File: packages/proxy/lib/http/util/cookies.ts (hunk 6 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:56]: That's true, but I think it's fine to err on the side of what the standard is, which is stricter and where browsers are heading anyway. I added a comment to explain this in the code too.

File: packages/server/lib/socket-base.ts (hunk 9 above)
Comment (chrisbreiding) [reply packages/server/lib/socket-base.ts]: No, this is vestigial from a previous implementation. I just missed removing it. Addressed in [`3c558b5` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/3c558b503b4437bbd7e476b9b552c2ad1c10e0c4).

File: packages/proxy/lib/http/util/cookies.ts (hunk 6 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:56]: Addressed in [`52b6874` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/52b6874742ee589ed9c40b90792f3074bbf4d426).

File: packages/proxy/lib/http/util/cookies.ts (hunk 7 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`52b6874` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/52b6874742ee589ed9c40b90792f3074bbf4d426).

File: packages/proxy/lib/http/util/cookies.ts (hunk 8 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`52b6874` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/52b6874742ee589ed9c40b90792f3074bbf4d426).

File: packages/server/lib/automation/automation.ts (hunk 1 above)
Comment (emilyrohrbough) [reply packages/server/lib/automation/automation.ts]: hmm okay. Since the names are so similar, thoughts on updating both files to add a quick blur that describes their intent?

Comment (chrisbreiding) [reply packages/server/lib/automation/automation.ts]: Good idea. Added in [`ab6e987` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/ab6e98756701b1451c8d69dd6193cfbf0f0ac965)

File: packages/proxy/lib/http/response-middleware.ts [hunk 10]
```diff
@@ -393,99 +393,99 @@ const MaybePreventCaching: ResponseMiddleware = function () {
...
+  //   (e.g. cy.getCookie). This is only done for cross-origin responses, since
+  //   non-cross-origin responses will be successfully set in the browser
+  //   automatically.
+  // - In the request middleware, we retrieve the cookies for a given URL
+  //   and attach them to the request, like the browser normally would.
+  //   tough-cookie handles retrieving the correct cookies based on domain,
+  //   path, etc. It also removes cookies from the cookie jar if they've expired.
+  const needsCrossOriginHandling = checkNeedsCrossOriginHandling(this)
+
+  const appendCookie = (cookie) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/response-middleware.ts:441]:
```suggestion
  const appendCookie = (cookie: string) => {
```

File: packages/proxy/lib/http/response-middleware.ts [hunk 11]
```diff
@@ -393,99 +393,99 @@ const MaybePreventCaching: ResponseMiddleware = function () {
...
-}
-
-const cookieSameSiteRegex = /SameSite=(\w+)/i
-const cookieSecureRegex = /(^|\W)Secure(\W|$)/i
-const cookieSecureSemicolonRegex = /;\s*Secure/i
-
-const ensureSameSiteNone = ({ cookie, browser, isLocalhost, url, ctxDebug }: EnsureSameSiteNoneProps) => {
-  ctxDebug('original cookie: %s', cookie)
+const CopyCookiesFromIncomingRes: ResponseMiddleware = async function () {
+  const cookies: string | string[] | undefined = this.incomingRes.headers['set-cookie']
```
Comment (AtofStryker) [inline packages/proxy/lib/http/response-middleware.ts:415]: in what case is this a single string vs an array of strings?

File: packages/proxy/lib/http/util/cookies.ts [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+
+// Sets SameSite context to match what it would be in the browser
+// see https://github.com/salesforce/tough-cookie#samesite-cookies
+export const getSameSiteContext = (autUrl: string | undefined, requestUrl: string, isAUTFrameRequest: boolean) => {
+  // if there's no AUT URL, it's a request for the first URL visited,
+  // so there would be no cross-origin concerns
+  // if the request origin matches the AUT origin, cookies can be handled
+  // in a strict fashion
+  if (!autUrl || cors.urlOriginsMatch(autUrl, requestUrl)) {
+    return 'strict'
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:33]: How does this work if I say have a site `foobar.com` and a cookie that I set `SameSite=none` in a first party context? If `foobar.com` sends requests to the `foobar.com` domain, they will be set as `SameSite=strict` cookies, but if I say do a cross origin navigation to `barbaz.com`, and send a request to `foobar.com`, would the cookie then be `SameSite=none`? Hopefully that made some sort of sense 😅

File: packages/proxy/lib/http/util/cookies.ts [hunk 13]
```diff
@@ -0,0 +1,166 @@
...
+  }
+
+  // being an AUT frame request means it's from navigation, so the context is
+  // 'lax'. otherwise, 'none' indicates a non-navigation cross-origin request
+  return isAUTFrameRequest ? 'lax' : 'none'
+}
+
+const sameSiteNoneRe = /; +samesite=(?:'none'|"none"|none)/i
+
+export const parseCookie = (cookie) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:43]:
```suggestion
export const parseCookie = (cookie: string) => {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 14]
```diff
@@ -0,0 +1,166 @@
...
+const comparableCookieString = (toughCookie) => {
+  return _(toughCookie)
+  .pick('key', 'value', 'domain', 'path')
+  .toPairs()
+  .sortBy(([key]) => key)
+  .map(([key, value]) => `${key}=${value}`)
+  .join('; ')
+}
+
+const areCookiesEqual = (cookieA, cookieB) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:70]:
```suggestion
const areCookiesEqual = (cookieA: Cookie, cookieB: Cookie) => {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 15]
```diff
@@ -0,0 +1,166 @@
...
+  // not all browsers currently default to lax, but they're heading in that
+  // direction since it's now the standard, so this is more future-proof
+  if (hasUnspecifiedSameSite) {
+    toughCookie.sameSite = 'lax'
+  }
+
+  return toughCookie
+}
+
+const comparableCookieString = (toughCookie) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:61]: The string return type I think is implicitly typed here, but I wonder if it's good to explicitly note it here to note you are doing a deep comparison of sorts?
```suggestion
const comparableCookieString = (toughCookie: Cookie): string => {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 16]
```diff
@@ -0,0 +1,166 @@
...
+  .sortBy(([key]) => key)
+  .map(([key, value]) => `${key}=${value}`)
+  .join('; ')
+}
+
+const areCookiesEqual = (cookieA, cookieB) => {
+  return comparableCookieString(cookieA) === comparableCookieString(cookieB)
+}
+
+const matchesPreviousCookie = (previousCookies, cookie) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:74]:
```suggestion
const matchesPreviousCookie = (previousCookies: Cookie[], cookie: Cookie) => {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 17]
```diff
@@ -0,0 +1,166 @@
...
+  return !!previousCookies.find((previousCookie) => {
+    return areCookiesEqual(previousCookie, cookie)
+  })
+}
+
+const toughCookieToAutomationCookie = (toughCookie, defaultDomain) => {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:80]:
```suggestion
const toughCookieToAutomationCookie = (toughCookie: Cookie, defaultDomain: string): AutomationCookie => {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 18]
```diff
@@ -0,0 +1,166 @@
...
+    this.request = request
+    this.debug = debug
+    this.sameSiteContext = getSameSiteContext(currentAUTUrl, request.url, request.isAUTFrame)
+
+    const parsedRequestUrl = new URL(request.url)
+
+    this.defaultDomain = parsedRequestUrl.hostname
+  }
+
+  async capturePreviousCookies () {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:124]:
```suggestion
  async captureAndSetPreviousCookies () {
```

Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:124]:
```suggestion
 capturePreviousCookies () {
```

File: packages/proxy/lib/http/util/cookies.ts [hunk 19]
```diff
@@ -0,0 +1,166 @@
...
+    // this plays a part in adding cross-origin cookies to the browser via
+    // automation. if the request doesn't need cross-origin handling, this
+    // is a noop
+    if (!this.request.needsCrossOriginHandling) return
+
+    this.previousCookies = this.cookieJar.getAllCookies()
+  }
+
+  async getAddedCookies () {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:133]:
```suggestion
 getAddedCookies () {
```

File: packages/proxy/test/unit/http/request-middleware.spec.ts [hunk 20]
```diff
@@ -11,6 +11,7 @@ describe('http/request-middleware', () => {
     expect(_.keys(RequestMiddleware)).to.have.ordered.members([
       'LogRequest',
       'ExtractIsAUTFrameHeader',
+      'CopyCrossOriginCookies',
```
Comment (AtofStryker) [inline packages/proxy/test/unit/http/request-middleware.spec.ts:14]: can we add some tests here that verify the attaching of cross origin cookies from the cookie jar to cross origin requests?

File: packages/proxy/test/unit/http/response-middleware.spec.ts [hunk 21]
```diff
@@ -31,6 +31,36 @@ describe('http/response-middleware', function () {
...
+      this.next()
+    }
+
+    return testMiddleware([middleware1, middleware2], {
+      onError () {
+        throw new Error('onError should not be called')
+      },
+    })
+  })
+
```
Comment (AtofStryker) [inline packages/proxy/test/unit/http/response-middleware.spec.ts:63]: Can we add some tests that exercise the `CopyCookiesFromIncomingRes` middleware to make sure the behavior we expect happens, like skipping if the experimental flag is off or setting the right header depending on the cookie or graceful failures?

File: packages/server/lib/automation/cookies.ts [hunk 22]
```diff
@@ -142,13 +146,19 @@ export class Cookies {
...
-    return automate('set:cookies', cookies)
-    // .tap(console.log)
+    return automate(eventName, cookies)
     .return(cookies)
   }
 
+  // set:cookies will clear cookies first in browsers that use CDP. this is the
+  // same as set:cookies in Firefox, but will only add cookies and not clear
+  // them in Chrome, etc.
+  addCookies (cookies, automate) {
```
Comment (AtofStryker) [inline packages/server/lib/automation/cookies.ts:158]:
```suggestion
  addCookies (cookies: AutomationCookie[], automate: (eventName: string, cookies: AutomationCookie[]) => Bluebird.Promise<AutomationCookie[]>) {
```

File: packages/server/lib/automation/cookies.ts [hunk 23]
```diff
@@ -130,7 +134,7 @@ export class Cookies {
     })
   }
 
-  setCookies (cookies, automate) {
+  setCookies (cookies, automate, eventName = 'set:cookies') {
```
Comment (AtofStryker) [inline packages/server/lib/automation/cookies.ts:137]: Not sure if these typings are correct, but I think they go a long way to help understand how the function works.
```suggestion
  setCookies (cookies: AutomationCookie[], automate: (eventName: string, cookies: AutomationCookie[]) => Bluebird.Promise<AutomationCookie[]>, eventName: 'set:cookies' | 'add:cookies' = 'set:cookies') {
```

File: packages/server/lib/browsers/cdp_automation.ts [hunk 24]
```diff
@@ -300,6 +300,11 @@ export class CdpAutomation {
           return this.getCookie(data)
         })
 
+      case 'add:cookies':
+        setCookie = data.map((cookie) => normalizeSetCookieProps(cookie))
```
Comment (AtofStryker) [inline packages/server/lib/browsers/cdp_automation.ts:304]: can we add the `Protocol.Network.SetCookieRequest[]` type to `setCookie`?

File: packages/server/lib/server-base.ts [hunk 25]
```diff
@@ -176,6 +179,14 @@ export abstract class ServerBase<TSocket extends SocketE2E | SocketCt> {
 
       this.socket.toDriver('cross:origin:delaying:html', request)
     })
+
+    this._eventBus.on('cross:origin:automation:cookies', (cookies) => {
```
Comment (AtofStryker) [inline packages/server/lib/server-base.ts:183]:
```suggestion
    this._eventBus.on('cross:origin:automation:cookies', (cookies: AutomationCookie[]) => {
```

**Review by AtofStryker — CHANGES_REQUESTED** [review]
Obligatory Cookie Monster GIF

File: packages/proxy/package.json [hunk 26]
```diff
@@ -23,6 +23,7 @@
     "lodash": "^4.17.19",
     "pumpify": "1.5.1",
     "through": "2.3.8",
+    "tough-cookie": "^4.0.0",
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/proxy/package.json]: I'm not sure I understand. Why would we treat it differently than any other dependency?

File: packages/proxy/lib/http/util/cookies.ts (hunk 12 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:33]: This property (sameSiteContext) gets tough-cookie on the same page as the browser, so it can simulate what the browser would do, not to be confused with the SameSite property of the cookie itself. Once tough-cookie has that context, it can evaluate whether a cookie should be set or retrieved based on the sameSiteContext, the request url, and the domain of the cookie.

This is the way I mentally translate the sameSiteContext:
- strict: first-party, top-level navigation
- lax: cross-origin, top-level navigation
- none: any navigation or nested resources

Comment (AtofStryker) [reply packages/proxy/lib/http/util/cookies.ts:33]: I think I am still a bit confused by this. Based on the code it looks like the scenario I mentioned would set the cookie context to `strict` instead of `none`. I think tests here might go a long way to show those unfamiliar with the code how the cookie jar is supposed to function in some of these use cases which would also serve as a documentation artifact.

File: packages/driver/cypress.config.ts [hunk 27]
```diff
@@ -15,5 +16,6 @@ export default defineConfig({
       return require('./cypress/plugins')(on, config)
     },
     'baseUrl': 'http://localhost:3500',
+    'experimentalSessionAndOrigin': true,
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/cypress.config.ts]: No, I did not 😅 Fixed in [`f45b180` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/f45b1805eec681e15e993e9d810747426e9aacf3)

File: packages/server/lib/browsers/cdp_automation.ts (hunk 24 above)
Comment (chrisbreiding) [reply packages/server/lib/browsers/cdp_automation.ts]: Yep. Addressed in [`db8684a` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/db8684ab6c3f49fda2961344dcb23972701465b9)

File: packages/server/lib/automation/cookies.ts (hunk 23 above)
Comment (chrisbreiding) [reply packages/server/lib/automation/cookies.ts]: Addressed in [`db8684a` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/db8684ab6c3f49fda2961344dcb23972701465b9)

File: packages/server/lib/automation/cookies.ts (hunk 22 above)
Comment (chrisbreiding) [reply packages/server/lib/automation/cookies.ts]: Addressed in [`db8684a` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/db8684ab6c3f49fda2961344dcb23972701465b9)

File: packages/proxy/lib/http/response-middleware.ts [hunk 28]
```diff
@@ -393,99 +393,101 @@ const MaybePreventCaching: ResponseMiddleware = function () {
   this.next()
 }
 
-const determineIfNeedsCrossOriginHandling = (ctx: HttpMiddlewareThis<ResponseMiddlewareProps>) => {
-  const previousAUTRequestUrl = ctx.getPreviousAUTRequestUrl()
+const checkNeedsCrossOriginHandling = (ctx: HttpMiddlewareThis<ResponseMiddlewareProps>) => {
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts [hunk 29]
```diff
@@ -1,95 +1,631 @@
...
+        cy.get('[data-cy="login"]').click()
+      })
+
+      cy.wait(1000) // give cookie time to expire
+      cy.reload()
+      verifyLocalhostNotLoggedIn()
+    })
+
+    // expiring cookies set by automatoin don't seem to get unset appropriately
+    // in Firefox. this issue doesn't seem to be specific to cross-origin tests,
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/cypress/e2e/e2e/origin/cookie_login.cy.ts:476]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/util/cookies.ts (hunk 16 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/util/cookies.ts (hunk 15 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/util/cookies.ts (hunk 14 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/util/cookies.ts (hunk 13 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/response-middleware.ts (hunk 10 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts:415]: Honestly, I don't know. I'm just going off the prior art for this header.

File: packages/driver/src/cypress/cy.ts [hunk 30]
```diff
@@ -364,6 +364,30 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
...
+    Cypress.on('cross:origin:automation:cookies', (cookies) => {
+      const existingCookies = state('cross:origin:automation:cookies') || []
+
+      this.state('cross:origin:automation:cookies', existingCookies.concat(cookies))
+
+      Cypress.backend('cross:origin:automation:cookies:received')
+    })
+
+    Cypress.on('before:stability:release', (stable) => {
+      const cookies = state('cross:origin:automation:cookies')
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cypress/cy.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/driver/src/cypress/cy.ts [hunk 31]
```diff
@@ -364,6 +364,30 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
...
+
+    Cypress.on('cross:origin:automation:cookies', (cookies) => {
+      const existingCookies = state('cross:origin:automation:cookies') || []
+
+      this.state('cross:origin:automation:cookies', existingCookies.concat(cookies))
+
+      Cypress.backend('cross:origin:automation:cookies:received')
+    })
+
+    Cypress.on('before:stability:release', (stable) => {
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cypress/cy.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/driver/src/cypress/cy.ts [hunk 32]
```diff
@@ -364,6 +364,30 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
     Cypress.on('enqueue:command', (attrs: Cypress.EnqueuedCommand) => {
       this.enqueue(attrs)
     })
+
+    Cypress.on('cross:origin:automation:cookies', (cookies) => {
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cypress/cy.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/driver/src/cypress/cy.ts [hunk 33]
```diff
@@ -364,6 +364,30 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
...
+      const existingCookies = state('cross:origin:automation:cookies') || []
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cypress/cy.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/package.json (hunk 26 above)
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/proxy/package.json]: This is actually an outdated diff, as I ended up not adding `tough-cookie` as a dep to the proxy. I only utilize the server package's dep now, which does have it pinned to 4.0.0.

File: packages/proxy/lib/http/util/cookies.ts (hunk 19 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/lib/http/request-middleware.ts [hunk 34]
```diff
@@ -30,6 +31,31 @@ const ExtractIsAUTFrameHeader: RequestMiddleware = async function () {
   this.next()
 }
 
+const CopyCrossOriginCookies: RequestMiddleware = function () {
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/proxy/lib/http/request-middleware.ts]: Addressed in [`95124a3` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/95124a38297f4924a8a11dec21668171fa50d514)

File: packages/proxy/test/unit/http/request-middleware.spec.ts (hunk 20 above)
Comment (chrisbreiding) [reply packages/proxy/test/unit/http/request-middleware.spec.ts]: Added in [`c22269b` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/c22269bb0d5bc43a1841b0a56de80b70e68f2550)

File: packages/proxy/test/unit/http/response-middleware.spec.ts (hunk 21 above)
Comment (chrisbreiding) [reply packages/proxy/test/unit/http/response-middleware.spec.ts:63]: Added in [`c22269b` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/c22269bb0d5bc43a1841b0a56de80b70e68f2550)

File: packages/proxy/lib/http/util/cookies.ts (hunk 12 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:22]: It's confusing because tough-cookie is using the same values as SameSite for this sameSiteContext property, even though they're not the same thing. Not sure I can explain it any better than the [tough-cookie doc](https://github.com/salesforce/tough-cookie#samesite-cookies) I linked to above this function. I'm not sure tests would help since they'd just be testing the logic, which is pretty straightforward from the code itself. I'll update to the comments to hopefully make things a little clearer.

Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:26]: Updated the comments in [`4903cb1` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/4903cb11b3012b3e9cd3ccff1a807d4615643a3f)

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts:415]: I would guess it may be a string if there's a single `Set-Cookie` header and it's an array if there's more than one.

**Review by mschile — APPROVED** [review]

File: packages/proxy/lib/http/request-middleware.ts [hunk 35]
```diff
@@ -30,6 +31,31 @@ const ExtractIsAUTFrameHeader: RequestMiddleware = async function () {
...
+  )
+
+  const cookies = this.getCookieJar().getCookies(this.req.proxiedUrl, sameSiteContext)
+  const existingCookies = this.req.headers['cookie'] ? [this.req.headers['cookie']] : []
+  const cookiesToAdd = cookies.map((cookie) => `${cookie.key}=${cookie.value}`)
+
+  this.debug('existing cookies on request: %s', existingCookies.join('; '))
+  this.debug('add cookies to request: %s', cookiesToAdd.join('; '))
+
+  this.req.headers['cookie'] = existingCookies.concat(cookiesToAdd).join('; ')
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/proxy/lib/http/request-middleware.ts]: I looked into this and it appears that if there are two or more cookies with the same key, the first cookie found is preferred. I changed it to prepend the added cookies, since I think it's correct that they take preference. Fixed it and added a test in [`235764f` (#22320)](https://github.com/cypress-io/cypress/pull/22320/commits/235764f07d03324fead704de8bfe0a229a70d9b6).

File: packages/proxy/lib/http/util/cookies.ts (hunk 12 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/cookies.ts:26]: OK I think this is finally clicking. The goal of SameSiteContext is to understand the context of which a request is made to see if a cookie applies, so if I make a request on `foobar.com` and I have cookies

```
key | value | samesite | domain

foo    bar      none     foobar.com  
baz    quux     strict   foobar.com
``` 

and the request is to `foobar.com`, the `SameSiteContext` is `strict`, but both cookies are sent, because that is what the browser would do. Hopefully I am getting it 😅 .

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/response-middleware.ts:415]: That makes sense. I was wondering if the code would accidentally treat the string as a character array, but it looks like it handles it just as well if `cookies` happened to be a string.

File: packages/server/lib/browsers/cdp_automation.ts [hunk 36]
```diff
@@ -300,6 +300,11 @@ export class CdpAutomation {
           return this.getCookie(data)
         })
 
+      case 'add:cookies':
+        setCookie = data.map((cookie) => normalizeSetCookieProps(cookie)) as Protocol.Network.SetCookieRequest[]
```
Comment (AtofStryker) [inline packages/server/lib/browsers/cdp_automation.ts:304]: Wonder if there is additional benefit to specifying the setCookie type to show it might be a single SetCookieRequest or an array of them on line 278, and then the consuming code just casts it, though I don't think this has a lot of benefit from a typings perspective.

```
let setCookie: Protocol.Network.SetCookieRequest | Protocol.Network.SetCookieRequest[]
```

**Review by AtofStryker — APPROVED** [review]

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts:415]: That's where the `[].concat(cookies)` idiom comes in to make sure it's an array before we loop through it.

File: packages/proxy/lib/http/util/cookies.ts (hunk 12 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/util/cookies.ts:26]: Yeah, I think you've got it. Took me a while to grok it as well.
