### PR TITLE
Fix a variety of character encoding issues

### LINKED ISSUE #1543: Character problems with character encoding of iso-8859-1 sites
- Operating System: Mac OS
- Cypress Version: Last
- Browser Version: Chrome and Electron

Hello, 

My site is not yet in utf8 and i have Character problems for accented characters (`doctype iso-8859-1`) when I use cypress. It's not really blocking except when doing regular expression searches  : 

HTML HEADER CHARSET : 
```
meta http-equiv="content-type" content="text/html; charset=iso-8859-1"
```

Result : 
```
Les sites ont bien ï¿½tï¿½ supprimï¿½s
ï¿½ Tous droits rï¿½servï¿½s ï¿½ 
```

Thanks
Regards

### LINKED ISSUE #3479: Non english characters (Korean) encoding is broken
cypress-screenshot
Hello. My cypress test is works very well in local. But on the CircleCI, all of non english characters(Korean, hangul, 한글) are broke out. So I change browser from electron to chrome69 browser but it was broke out again. Is this issue caused by the CircleCI machine? or Cypress Orb browser? Thanks.

### LINKED ISSUE #3650: Chrome Cypress browser adds "charset=utf-8" to the content-type in the response header
### Current behavior:

Some of my website's HTTP requests are failing only in the Cypress browser (e.g. signing up for a new account). After debugging, it was discovered this was due to the response header returning a different `content-type` in the Cypress browser.

Chrome browser:
```
content-type: application/json
```

Cypress browser (not running headlessly):
```
Content-type: application/json; charset=utf-8
```

Cypress is adding `"charset=utf-8"` to the `content-type`.

### Desired behavior:

Return the same `content-type` as the Chrome browser.

### Versions

3.1.5
Chrome 72

### PR DESCRIPTION
**Pull request by flotwig**
- [x] Adds e2e tests for various charsets with and without gzip
	- [x] iso-8859 (latin1)
		- Fixes #1543 
	- [x] euc-kr (korean)
		- Fixes #3479
	- [x] shift-jis (japanese)
	- [x] GB2312 (chinese)
- [x] Auto-detects charset from headers or meta tags
- [x] Ensures that content is injected and sent using the detected content type
- [x] Prevents Express from always sending `content-type: text/html;charset=utf-8` :roll_eyes: 	
	- Fixes #3650
	- https://github.com/expressjs/express/blob/0a48e18056865364b2461b2ece7ccb2d1075d3c9/lib/response.js#L164-L172
	- if you write a string, it will send it as utf-8 always, had to monkey-patch it out

### CODE REVIEW

File: packages/server/lib/controllers/proxy.coffee [hunk 1]
```diff
@@ -14,6 +16,7 @@ conditional   = require("../util/conditional_stream")
 
 REDIRECT_STATUS_CODES = [301, 302, 303, 307, 308]
 NO_BODY_STATUS_CODES = [204, 304]
+HTTP_EQUIV_CHARSET_RE = /<\s*meta\s+http-equiv=['"]content-type['"][^>]*content\s*=\s*['"]text\/html;\s*charset=([^'"]+)/i
```
Comment (flotwig) [inline packages/server/lib/controllers/proxy.coffee]: can this be moved into `charset`?

File: packages/server/lib/controllers/proxy.coffee [hunk 2]
```diff
@@ -247,6 +278,16 @@ module.exports = {
     onResponse = (str, incomingRes) =>
       {headers, statusCode} = incomingRes
 
+      res.originalSetHeader = res.setHeader
```
Comment (flotwig) [inline packages/server/lib/controllers/proxy.coffee]: use `call` like we do in other places

**Comment by flotwig** [comment]
@brian-mann On second inspection, `charset` works fine with the existing test cases, I must have gotten confused early on and thought it wasn't working. Removed the regex workaround and updated the Express patching to use .call.
