### PR TITLE
Fix race condition when there's an early asynchronous error in plugins file

### LINKED ISSUE #6570: Race condition when there's an asynchronous error in plugins file
### Current behavior:

It's possible for certain errors to be uncaught in the plugins process. If the error occurs soon after we create the plugins process and is asynchronous, it will not be caught. Such an error should cause the main Cypress process to fail, but it does not.

### Desired behavior:

Any errors thrown in the plugins process should fail the main Cypress process.

### Test code to reproduce

Add this to the plugins file and run a simple test:

```javascript
setTimeout(() => {
  throw new Error('Root async error from plugins file')
})

module.exports = () => {}
```

Since it's a race condition, the issue might not always occur and the error will be properly displayed. But it will reproduce the issue if run a few times.

### Versions

Cypress: 4.0.2
OS: MacOS 10.14.6
Browser: Any

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #6570

### User facing changelog

* Fixed a race condition where an asynchronous error could fail to be caught when running the plugins file process

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by flotwig** [comment]
@chrisbreiding is this the flaky issue we were seeing right before the 4.0.0 release that you patched by only allowing 1 error to be thrown by a plugin?

File: packages/server/__snapshots__/3_plugins_spec.js [hunk 1]
```diff
@@ -402,3 +343,121 @@ An invalid configuration value returned from the plugins file: \`cypress/plugins
 Expected \`viewportWidth\` to be a number. Instead the value was: \`"foo"\`
 
 `
+
+exports['e2e plugins fails when there is an async error at the root 1'] = `
+
+The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (\`/foo/bar/.projects/plugins-root-async-error/cypress/plugins/index.js\`)
```
Comment (flotwig) [inline packages/server/__snapshots__/3_plugins_spec.js]: this error says "We stopped running your tests...", but then a few lines later, we say "Run Starting" - i think this could be confusing. maybe we should always print the "Run Starting" heading first.

**Comment by chrisbreiding** [comment]
> is this the flaky issue we were seeing right before the 4.0.0 release that you patched by only allowing 1 error to be thrown by a plugin?

I don't think so. I found this issue months ago and implemented the fix as part of #5356, but decided this should be on its own, so I pulled it out into this PR. But I also don't remember that issue with flakiness, so I'm not really sure 😅

File: packages/server/__snapshots__/3_plugins_spec.js (hunk 1 above)
Comment (chrisbreiding) [reply packages/server/__snapshots__/3_plugins_spec.js]: That's a good point. The timing with these things is always tricky since it's an error that occurs asynchronously and could occur at any given time, but I agree, we shouldn't say the run is starting if it's already failed. Probably should be able to prevent 'Run Starting' from printing altogether in that case.

Comment (flotwig) [reply packages/server/__snapshots__/3_plugins_spec.js]: That sounds good, either preventing it from starting, or putting it before this error message

**Comment by chrisbreiding** [comment]
@flotwig I fixed the logging so it waits until "Run starting" is logged to display the error. Please take another look.

File: packages/server/__snapshots__/3_plugins_spec.js [hunk 2]
```diff
@@ -402,3 +343,121 @@ An invalid configuration value returned from the plugins file: \`cypress/plugins
...
+  │ Specs:      1 found (app_spec.js)                                                              │
+  │ Searched:   cypress/integration/app_spec.js                                                    │
+  └────────────────────────────────────────────────────────────────────────────────────────────────┘
+
+
+────────────────────────────────────────────────────────────────────────────────────────────────────
+                                                                                                    
+  Running:  app_spec.js                                                                     (1 of 1)
+
+The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (\`/foo/bar/.projects/plugins-root-async-error/cypress/plugins/index.js\`)
```
Comment (flotwig) [inline packages/server/__snapshots__/3_plugins_spec.js]: nice, much clearer
