### PR TITLE
fix: declare used babel dependencies

### LINKED ISSUE #24768: dependency issue after webpack-preprocessor 5.12.2
### Current behavior

After updating @cypress/webpack-preprocessor@5.12.2 to any newer version, Cypress 11.1.0 won't run anymore.

I am using yarn 3.2.3, by the way.

### Desired behavior

I desire Cypress to run together with latest webpack-preprocessor (and yarn 3).

### Test code to reproduce

[My `cypress.config.js` looks like this.](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/webpack-cjs/cypress.config.js)
```
yarn --version # 3.2.3
yarn add cypress@11.1.0
yarn add @cypress/webpack-preprocessor@5.15.5
yarn add @badeball/cypress-cucumber-preprocessor@14.0.0
yarn cypress run
```

### Cypress Version

11.1.0

### Node version

16.16.0

### Operating System

Windows 10

### Debug Logs

```shell
Oops...we found an error preparing this test file:

  > cypress\support\e2e.ts

The error was:

Error: Webpack Compilation Error
Module build failed (from ./.yarn/__virtual__/@cypress-webpack-preprocessor-virtual-27935e964b/0/cache/@cypress-webpack-preprocessor-npm-5.15.5-09e14ee4bd-7d09e96a35.zip/node_modules/@cypress/webpack-preprocessor/dist/lib/cross-origin-callback-loader.js):
Error: @cypress/webpack-preprocessor tried to access @babel/traverse, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/traverse (via "@babel\traverse")
Required by: @cypress/webpack-preprocessor@virtual:1a94a3626686405d7f1bd2ac51272f55fefd14751613f78923df5a48bcae42eacc44e27bd5152e0eeaf662ec45a1f8b10c4bfa2dd6b827aeb3948ade2860dead#npm:5.15.5 (via C:\Users\...\.yarn\__virtual__\@cypress-webpack-preprocessor-virtual-27935e964b\0\cache\@cypress-webpack-preprocessor-npm-5.15.5-09e14ee4bd-7d09e96a35.zip\node_modules\@cypress\webpack-preprocessor\dist\lib\)
...
```

### Other

Workaround:
```
yarn add @babel/traverse
yarn add @babel/generator
```

### PR DESCRIPTION
**Pull request by mjhenkes**
- Closes #24768

### User facing changelog

* declared babel dependencies that are used, but not declared.

### Additional details

Dependencies used here: 
https://github.com/cypress-io/cypress/blob/c4fbfe35a6a1069b1b9d59cb72d3013e2a290644/npm/webpack-preprocessor/lib/cross-origin-callback-loader.ts#L3-L4

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

File: npm/grep/cypress/e2e/unit.js [hunk 1]
```diff
@@ -137,15 +151,17 @@ describe('utils', () => {
...
       const parsed = parseTagsGrep(',, @tag1,-@tag2,, ,, ,')
+
       expect(parsed).to.deep.equal([
         [{ tag: '@tag1', invert: false }],
         [{ tag: '@tag2', invert: true }],
       ])
     })
 
-    // would need to change the tokenizer
+    // TODO: would need to change the tokenizer
```
Comment (mjhenkes) [inline npm/grep/cypress/e2e/unit.js:161]: This hasn't changed in quite a while but it's now getting linted so i added the TODO

**Review by chrisbreiding — APPROVED** [review]
