### PR TITLE
fix: ensure that chromium based browsers do not send out a lot of font requests when global styles change

### LINKED ISSUE #28150: Scrolling elements into view broken when using scroll-behavior: smooth
### Current behavior

Starting with version 13.3, the scrolling of elements into view, triggered e.g. by "click" no longer works when using scroll-behavior: smooth. This causes actionability checks to fail.

We are setting scroll-behavior: smooth directly on the "html" tag.

I noticed that there were some changes done in that area in the 13.3 version which are probably causing the issue.
https://github.com/cypress-io/cypress/pull/27860/files#diff-10c3dbee8439d9d33f63478cc0b81d1e87bf6e50530c3669f159bdf5c97bb7a6

### Desired behavior

Scrolling should work as it has worked until version 13.2

### Test code to reproduce

no repo, sorry

### Cypress Version

13.3

### Node version

20.2

### Operating System

Windows 11

### Debug Logs

_No response_

### Other

_No response_

### LINKED ISSUE #28215: Protocol: [Performance] Fix font request flooding
We are seeing issues where fonts flood as a result of various things that are either done by an application or by Cypress.

Chrome has [some behavior](https://github.com/chromium/chromium/blob/118.0.5993.117/third_party/blink/renderer/core/css/css_font_face_src_value.cc#L170-L177) that triggers reloading of in-memory font assets when global style sheets are updated. This has the effect of triggering all font requests to reload. Even though they are in-memory, this produces a flood of CDP events which backs up proxy correlations and bloats the test replay data being captured.

We can fix this by ensuring that the in memory cache is only used in a given context via the `ScopeMemoryCachePerContext` feature. This will ensure that the resource is in a local cache and it won't replay the CDP events (https://github.com/chromium/chromium/blob/118.0.5993.117/third_party/blink/renderer/platform/loader/fetch/resource_fetcher.cc#L2650-L2652). 

Note that we initially tried to fix this issue via https://github.com/cypress-io/cypress/pull/27860 when we thought it was something that Cypress was inherently doing as part of actionability. This did not resolve the issue as frameworks in the apps themselves can be causing the problem as well. As a result as a part of fixing this, we should undo: https://github.com/cypress-io/cypress/pull/27860

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28215
- Closes #28150

### Additional details

We are seeing issues where fonts flood as a result of various things that are either done by an application or by Cypress.

Chrome has [some behavior](https://github.com/chromium/chromium/blob/118.0.5993.117/third_party/blink/renderer/core/css/css_font_face_src_value.cc#L170-L177) that triggers reloading of in-memory font assets when global style sheets are updated. This has the effect of triggering all font requests to reload. Even though they are in-memory, this produces a flood of CDP events which backs up proxy correlations and bloats the test replay data being captured.

We can fix this by ensuring that the in memory cache is only used in a given context via the ScopeMemoryCachePerContext feature. This will ensure that the resource is in a local cache and it won't replay the CDP events (https://github.com/chromium/chromium/blob/118.0.5993.117/third_party/blink/renderer/platform/loader/fetch/resource_fetcher.cc#L2650-L2652).

Note that we initially tried to fix this issue via https://github.com/cypress-io/cypress/pull/27860 when we thought it was something that Cypress was inherently doing as part of actionability. This did not resolve the issue as frameworks in the apps themselves can be causing the problem as well. As a result as a part of fixing this, we should undo: https://github.com/cypress-io/cypress/pull/27860

### Steps to test

The additional system test covers this scenario

### How has the user experience changed?

You will no longer be seeing large #'s of font requests in dev tools or in Test Replay when global styles are messed with.

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/cypress.js [hunk 1]
```diff
@@ -164,19 +164,23 @@ module.exports = {
...
       debug('scaling electron app in headless mode')
       // scale the electron browser window
       // to force retina screens to not
       // upsample their images when offscreen
       // rendering
-      require('./util/electron-app').scale()
+      electronApp.scale()
     }
 
+    electronApp.setScopeMemoryCachePerContext()
```
Comment (ryanthemanuel) [inline packages/server/lib/cypress.js:179]:
```suggestion
    // control memory caching per execution context so that font flooding does not occur: https://github.com/cypress-io/cypress/issues/28215
    electronApp.setScopeMemoryCachePerContext()
```

File: system-tests/test/protocol_spec.js [hunk 2]
```diff
@@ -36,13 +36,14 @@ describe('capture-protocol', () => {
   enableCaptureProtocol()
 
   describe('e2e', () => {
-    it('verifies the protocol events are correct', function () {
+    it(`verifies the protocol events are correct`, function () {
```
Comment (ryanthemanuel) [inline system-tests/test/protocol_spec.js]:
```suggestion
    it('verifies the protocol events are correct', function () {
```

File: system-tests/test/protocol_spec.js [hunk 3]
```diff
@@ -51,7 +52,7 @@ describe('capture-protocol', () => {
       }).then(() => {
         const protocolEvents = fs.readFileSync(getFilePath('e9e81b5e-cc58-4026-b2ff-8ae3161435a6.db'), 'utf8')
 
-        systemTests.snapshot('e2e events', normalizeEvents(protocolEvents))
+        systemTests.snapshot(`e2e events`, normalizeEvents(protocolEvents))
```
Comment (ryanthemanuel) [inline system-tests/test/protocol_spec.js]:
```suggestion
        systemTests.snapshot('e2e events', normalizeEvents(protocolEvents))
```

File: system-tests/test/protocol_spec.js [hunk 4]
```diff
@@ -60,7 +61,7 @@ describe('capture-protocol', () => {
 
   describe('component', () => {
     [true, false].forEach((experimentalSingleTabRunMode) => {
-      it('verifies the protocol events are correct', function () {
+      it(`verifies the protocol events are correct - experimentalSingleTabRunMode: ${experimentalSingleTabRunMode ? 'On' : 'Off'}`, function () {
```
Comment (ryanthemanuel) [inline system-tests/test/protocol_spec.js]:
```suggestion
      it('verifies the protocol events are correct', function () {
```

File: packages/driver/cypress/e2e/dom/visibility.cy.ts [hunk 5]
```diff
@@ -53,7 +53,7 @@ describe('src/cypress/dom/visibility', () => {
       expect(fn()).to.be.true
     })
 
-    it('returns false if window and body < window height', () => {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/dom/visibility.cy.ts:56]: why are the visibility tests removed?

File: packages/server/lib/browsers/chrome.ts [hunk 6]
```diff
@@ -427,6 +427,9 @@ export = {
     args.push(`--remote-debugging-port=${port}`)
     args.push('--remote-debugging-address=127.0.0.1')
 
+    // control memory caching per execution context so that font flooding does not occur: https://github.com/cypress-io/cypress/issues/28215
+    args.push('--enable-features=ScopeMemoryCachePerContext')
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/chrome.ts:431]: Is this only impacting replay & chrome/electron browsers?

File: packages/driver/cypress/e2e/dom/visibility.cy.ts (hunk 5 above)
Comment (ryanthemanuel) [reply packages/driver/cypress/e2e/dom/visibility.cy.ts:56]: This is work to undo: https://github.com/cypress-io/cypress/pull/27860 in order to fix a regression caused by that (https://github.com/cypress-io/cypress/issues/28150)

File: packages/server/lib/browsers/chrome.ts (hunk 6 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/chrome.ts:431]: This issue is very specific to chrome/electron in terms of how they handle memory caches, etc. There may be additional nuances to firefox and webkit but I have not noticed the exact same behavior. I can clarify that this fix is only for chrome/electron though.

File: cli/CHANGELOG.md [hunk 7]
```diff
@@ -6,6 +6,7 @@ _Released 11/7/2023 (PENDING)_
 **Bugfixes:**
 
 - Fixed an issue determining visibility when an element is hidden by an ancestor with a shared edge. Fixes [#27514](https://github.com/cypress-io/cypress/issues/27514).
+- Fixed an issue where global style updates can trigger flooding of font face requests in DevTools and Test Replay. This can affect performance due to the flooding of messages in CDP. Fixes [#28150](https://github.com/cypress-io/cypress/issues/28150) and [#28215](https://github.com/cypress-io/cypress/issues/28215).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue where in chromium based browsers, global style updates can trigger flooding of font face requests in DevTools and Test Replay. This can affect performance due to the flooding of messages in CDP. Fixes [#28150](https://github.com/cypress-io/cypress/issues/28150) and [#28215](https://github.com/cypress-io/cypress/issues/28215).
```

File: packages/driver/cypress/e2e/commands/actions/click.cy.js [hunk 8]
```diff
@@ -1678,16 +1678,12 @@ describe('src/cy/commands/actions/click', () => {
         it('can scroll to and click elements in html with scroll-behavior: smooth', () => {
```
Comment (ryanthemanuel) [inline packages/driver/cypress/e2e/commands/actions/click.cy.js:1678]: This file's changes involve undoing https://github.com/cypress-io/cypress/pull/27860

File: packages/driver/cypress/e2e/dom/visibility.cy.ts [hunk 9]
```diff
@@ -53,7 +53,7 @@ describe('src/cypress/dom/visibility', () => {
       expect(fn()).to.be.true
```
Comment (ryanthemanuel) [inline packages/driver/cypress/e2e/dom/visibility.cy.ts:53]: This file's changes involve undoing https://github.com/cypress-io/cypress/pull/27860

File: packages/driver/src/cy/actionability.ts [hunk 10]
```diff
@@ -8,7 +8,6 @@ import $utils from './../cypress/utils'
 import type { ElWindowPostion, ElViewportPostion, ElementPositioning } from '../dom/coordinates'
```
Comment (ryanthemanuel) [inline packages/driver/src/cy/actionability.ts:8]: This file's changes involve undoing https://github.com/cypress-io/cypress/pull/27860

File: packages/driver/src/dom/elements/complexElements.ts [hunk 11]
```diff
@@ -290,12 +290,6 @@ export const isScrollable = ($el) => {
     return false
```
Comment (ryanthemanuel) [inline packages/driver/src/dom/elements/complexElements.ts:290]: This file's changes involve undoing https://github.com/cypress-io/cypress/pull/27860

File: packages/driver/src/dom/elements/nativeProps.ts [hunk 12]
```diff
@@ -207,7 +207,6 @@ const nativeGetters = {
   body: descriptor('Document', 'body').get,
```
Comment (ryanthemanuel) [inline packages/driver/src/dom/elements/nativeProps.ts:207]: This file's changes involve undoing https://github.com/cypress-io/cypress/pull/27860

File: packages/driver/src/cy/actionability.ts [hunk 13]
```diff
@@ -461,46 +460,24 @@ const verify = function (cy, $el, config, options, callbacks: VerifyCallbacks) {
...
-          }
-        }
-
-        parent = $dom.getFirstScrollableParent(parent)
-      } while (parent)
+      style = doc.createElement('style')
+      style.innerHTML = '* { scroll-behavior: inherit !important; }'
+      // there's guaranteed to be a <script> tag, so that's the safest thing
+      // to query for and add the style tag after
+      doc.querySelector('script').after(style)
```
Comment (cacieprins) [inline packages/driver/src/cy/actionability.ts:473]: Could we use adopted stylesheets to insert this rule without modifying the DOM itself?

**Review by cacieprins — APPROVED** [review]

**Review by chrisbreiding — APPROVED** [review]

File: packages/driver/src/cy/actionability.ts (hunk 13 above)
Comment (ryanthemanuel) [reply packages/driver/src/cy/actionability.ts:473]: This was existing code that was reverted. I think this is something we could explore, but I'd rather revert the code to where it was previously and maybe explore this separately.

File: cli/CHANGELOG.md [hunk 14]
```diff
@@ -6,6 +6,7 @@ _Released 11/7/2023 (PENDING)_
 **Bugfixes:**
 
 - Fixed an issue determining visibility when an element is hidden by an ancestor with a shared edge. Fixes [#27514](https://github.com/cypress-io/cypress/issues/27514).
+- Fixed an issue where in chromium based browsers, global style updates can trigger flooding of font face requests in DevTools and Test Replay. This can affect performance due to the flooding of messages in CDP. Fixes [#28150](https://github.com/cypress-io/cypress/issues/28150) and [#28215](https://github.com/cypress-io/cypress/issues/28215).
 - Fixed an issue with 'other' targets (e.g. pdf documents embedded in an object tag) not fully loading. Fixes [#28228](https://github.com/cypress-io/cypress/issues/28228)
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue with 'other' targets (e.g. pdf documents embedded in an object tag) not fully loading. Fixes [#28228](https://github.com/cypress-io/cypress/issues/28228) and [#28162](https://github.com/cypress-io/cypress/issues/28162).
```
