### PR TITLE
fix: rerunning spec in open mode w/ after hook

### LINKED ISSUE #6619: Rerunning spec in open mode hangs with after hook
In open mode, if you click the stop/restart button or update your spec code, sometimes the rerun test run will hang on the first test and show all tests as queued:

image

this happens if you have an after hook, which ends up causing an uncaught exception in the console (only with debug logs enabled: `localStorage.debug = 'cypress:*'`)

```js
 listeners - with args: Uncaught Error: runnable must have an id
```

### PR DESCRIPTION
**Pull request by kuceb**
- fix #6619 

### User facing changelog
fix a bug causing specs to hang after rerunning in open mode

### Unrelated Tasks
- [x] allow e2e test script to accept `--no-exit` through the cli

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/test/scripts/run.js [hunk 1]
```diff
@@ -144,6 +144,10 @@ if (options.browser) {
   env.BROWSER = options.browser
 }
 
+if (options.exit != null) {
+  env.EXIT = options.exit
+}
+
```
Comment (Bkucera) [inline packages/server/test/scripts/run.js]: allows e2e tests to pass `--no-exit` thru the cli

File: packages/driver/src/cypress.js [hunk 2]
```diff
@@ -31,6 +31,7 @@ const $SelectorPlayground = require('./cypress/selector_playground')
 const $utils = require('./cypress/utils')
 const $errUtils = require('./cypress/error_utils')
 const browserInfo = require('./cypress/browser')
+const debug = require('debug')('cypress-events:driver')
```
Comment (flotwig) [inline packages/driver/src/cypress.js]: why does this not follow the normal debug semantics?

```suggestion
const debug = require('debug')('cypress:driver:cypress')
```

later on...

```js
debug('action fired: %o', { eventName })
```

File: packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js [hunk 3]
```diff
@@ -4,9 +4,21 @@ const _ = require('lodash')
...
 const Promise = require('bluebird')
-const performance = require('../../../../test/support/helpers/performance')
 
 module.exports = (on, config) => {
+  let performance = {
+    track: () => Promise.resolve(),
+  }
+
+  // TODO: fix this - in open mode, this will throw an error
+  // since the relative path is different in open vs run mode
```
Comment (flotwig) [inline packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js]: :laughing:

File: packages/server/test/support/helpers/e2e.js [hunk 4]
```diff
@@ -286,6 +286,7 @@ const localItFn = function (title, opts = {}) {
   opts.browser = normalizeToArray(opts.browser)
 
   const DEFAULT_OPTIONS = {
+    exit: process.env.EXIT != null ? process.env.EXIT : null,
```
Comment (flotwig) [inline packages/server/test/support/helpers/e2e.js]: when will `process.env.EXIT` be null? AFAIK, members of `process.env` can only ever be `undefined` or a `string`

File: packages/server/test/e2e/2_controllers_spec.coffee [hunk 5]
```diff
@@ -14,3 +14,12 @@ describe "e2e plugins", ->
...
     })
+
+  ## this tests open mode behavior
+  ## when the user hits the 'reload' button in open mode
+  ## https://github.com/cypress-io/cypress/issues/6619
+  e2e.it 'can reload during spec run', {
+    spec: "reload-spec.spec.js"
+    snapshot: true
+    timeout: 15000
+  }
```
Comment (chrisbreiding) [inline packages/server/test/e2e/2_controllers_spec.coffee]: Why put this in the controllers spec?

File: packages/driver/src/cypress/runner.js [hunk 6]
```diff
@@ -66,6 +67,7 @@ const RUNNABLE_PROPS = 'id order title root hookName hookId err state failedFrom
 // }
 
 const fire = function (event, runnable, Cypress) {
+  debug('fire:', event)
```
Comment (flotwig) [inline packages/driver/src/cypress/runner.js]:
```suggestion
  debug('fire: %o', { event })
```

**Review by flotwig — DISMISSED** [review]
looks good, just a few really minor things

can you briefly explain the cause of this issue, and why this fix in `runner.js` works? i think i understand what is happening, but i want to hear it from the source :smile:

File: packages/server/test/e2e/2_controllers_spec.coffee (hunk 5 above)
Comment (Bkucera) [reply packages/server/test/e2e/2_controllers_spec.coffee]: idk what a controller is in this case, figured "spec does not exit" was the closest thing to this. I could create a `1_runner_spec.js` though

File: packages/server/test/support/helpers/e2e.js (hunk 4 above)
Comment (Bkucera) [reply packages/server/test/support/helpers/e2e.js]: well `!= null` is just how I check for `undefined` :^) 

its what coffeescript converts existent checks to

Comment (flotwig) [reply packages/server/test/support/helpers/e2e.js]: image

Comment (chrisbreiding) [reply packages/server/test/support/helpers/e2e.js]: It's a loose check that means "not `undefined` or `null`". If anything, shouldn't we be coercing it into a boolean?

File: packages/server/test/e2e/2_controllers_spec.coffee (hunk 5 above)
Comment (chrisbreiding) [reply packages/server/test/e2e/2_controllers_spec.coffee]: The controller facilitates serving the file to the browser, so the other test is concerned with the spec file not existing and how the spec controller handles that. 

Probably make sense to have this be an "issue" spec, like all the `3_issue_*` ones, since it's addressing a specific issue and isn't a feature or anything.

File: packages/server/test/support/helpers/e2e.js (hunk 4 above)
Comment (Bkucera) [reply packages/server/test/support/helpers/e2e.js]: fine

**Review by chrisbreiding — APPROVED** [review]
