### PR TITLE
fix(studio): more resilient saving to file

### LINKED ISSUE #14767: Studio: failed to save commands
### Test code to reproduce

I created a new repo, added cypress, did cypress open, deleted examples, created a new spec:
```
describe('soak test', () => {
 	it('logs in', () => { 
		cy.visit('internal url'); 
	}); 
});
```

Then I opened studio, typed into an input and clicked save.

The page refreshes so I needed to use animation capture to see the error.

How can I provide more details on the exact error? I don't see anything in the debug log but I will attach it here.

### Versions

6.3.0
windows 10

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #14767, GROW-227

### User facing changelog
Reduced occurrence of "Studio failed to save commands" error message

### Additional details
Sometimes studio would fail to save tests when there was no source maps or way to get the invocation details for a test/suite. These changes introduce a backup saving algorithm that matches based on the title of the test/suite in the case that the test cannot be found from the invocation details.

The backup plan will search through all of the test files in the spec to match by test/suite title. This still isn't a perfect solution since there could be two tests with the same name, in which case it doesn't save anything right now (as opposed to accidentally saving to the wrong test). A potential improvement to this is to match based on the `_testPath` (which includes the name of all parent suites), but that also can be problematic since it won't be able to find tests that aren't directly nested in the AST (ex. if there's a function that calls the `it` from a different file) and there's no `_testPath` for suites. We could also attempt to match by test body in addition to title but that seems more trouble than its worth right now (plus suites don't have a `body`). Perhaps we can add that in another update before Studio goes GA. Combined with copy to clipboard as a backup, this should hopefully make the Studio experience much better for users getting that error message.

I also cleaned up how Studio state gets persisted mid-test (eg. when a user enters a different url and the browser needs to reload) which turned out to not be relevant to this update but nice to have (which is why there's a bunch of updates to unrelated tests)

### How has the user experience changed?
Hopefully less error messages

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/runner-shared/src/event-manager.js [hunk 1]
```diff
@@ -482,13 +484,23 @@ export const eventManager = {
...
+        }
+
+        if (studioRecorder.suiteId) {
+          if (test.parent && test.parent.id !== 'r1') {
+            studioRecorder.setRunnableTitle(test.parent.title)
+          }
+        } else {
+          studioRecorder.setRunnableTitle(test.title)
+        }
       }
```
Comment (chrisbreiding) [inline packages/runner-shared/src/event-manager.js:504]: I think it would be good to abstract these lines into a `studioRecorder` method or another utility. We should try to keep the responsibility of this file to managing events and move any logic into separate places.

File: packages/runner-shared/src/event-manager.js [hunk 2]
```diff
@@ -555,35 +567,30 @@ export const eventManager = {
...
+
+      if (studio.suiteId) {
+        studioRecorder.setSuiteId(studio.suiteId)
+      }
 
-    if (state.studioUrl) {
-      studioRecorder.setUrl(state.studioUrl)
+      if (studio.url) {
+        studioRecorder.setUrl(studio.url)
+      }
```
Comment (chrisbreiding) [inline packages/runner-shared/src/event-manager.js:583]: Another instance we could abstract into a `studioRecorder` method.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

**Comment by panzarino** [comment]
@chrisbreiding updated

File: packages/runner-shared/src/event-manager.js (hunk 1 above)
Comment (chrisbreiding) [reply packages/runner-shared/src/event-manager.js:502]: Could you move these lines (486-502) into `studioRecorder` as well? 

I think the litmus test for abstracting out of this file is whether there is `if/else` logic involved. There are a couple other places in this file that still have `if/else`, but they're unrelated to this PR, so of course don't need to be taken care of now.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

**Comment by panzarino** [comment]
@chrisbreiding Oops, missed that one - I moved that over now and added some extra unit tests for good measure (in addition to being tested through integration and e2e tests)

**Review by chrisbreiding — APPROVED** [review]
Looks good 👍
