### PR TITLE
accept `options.ensure` to disable actionability checks

### LINKED ISSUE #4874: Cannot click on 'readonly' inputs / textarea
### Current behavior:

As noted initially from this comment https://github.com/cypress-io/cypress/pull/4783#issuecomment-516174805, Cypress now errors since 3.4.1 release when attempting to click on a `readonly` input or textarea. 

### Desired behavior:

Unlike an input being `disabled`, having a `readonly` attribute does not restrict clicking, focusing, selecting, or triggering events on the element. These actions should be allowed and only typing should be restricted.

### Steps to reproduce: (app code and test code)

```js
cy.get('input[readonly]`).click()
```

### Versions

Cypress 3.4.1

### PR DESCRIPTION
**Pull request by kuceb**
fix #4874

### tasks
- [x] rename ensureReceivability -> ensureNotDisabled

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by brian-mann** [comment]
What do you think of calling this option `validate` vs `ensure` ?

**Comment by jennifer-shehane** [comment]
I like `ensure` better, since `validate` has it's own very specific meaning in the DOM - `ensure` causes less confusion that it's actually associated with DOM validation in some way.

**Comment by Bkucera** [comment]
another question is whether we want this exposed in our command options API, similar to how users can do `waitForAnimations`.

If we do want to expose this in options API, we should probably do so in a similar verbiage to `waitForAnimations`, since that is configuring very similar behavior

**Comment by Bkucera** [comment]
I think this should go in. This does not affect end-user API and only changes one command file

File: packages/driver/src/cy/actionability.coffee [hunk 1]
```diff
@@ -232,17 +244,23 @@ verify = (cy, $el, options, callbacks) ->
 
     runAllChecks = ->
       if force isnt true
+        ## ensure its 'receivable'
+        if (options.ensure.receivability) then cy.ensureReceivability($el, _log)
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/actionability.coffee]: I know this naming convention is already in develop, but...I hate this name, I have to look directly at the method every time. And all is reasonably does is check that the el is not disabled. If we're adding options like `notReadonly` and `notCovered`, can't we just update this to say `notDisabled` and `ensureNotDisabled`?

File: packages/driver/src/dom/elements.js [hunk 2]
```diff
@@ -363,6 +345,30 @@ const isFocused = (el) => {
   }
 }
 
+const isFocusedOrInFocused = (el) => {
```
Comment (jennifer-shehane) [inline packages/driver/src/dom/elements.js]: is this supposed to be `isFocusedOrInFocused` or `isFocusedOrInFocus`, cause currently the method sounds like it is checking if the element is `focused` or if if it an element located as a child of a `focused element.

**Review by jennifer-shehane — COMMENTED** [review]
Have some notes on possibly changing the names of a couple methods, logic looks good though. 👍

File: packages/driver/src/dom/elements.js (hunk 2 above)
Comment (Bkucera) [reply packages/driver/src/dom/elements.js]: bingo, is focused or inside focused element

File: packages/driver/src/cy/actionability.coffee (hunk 1 above)
Comment (Bkucera) [reply packages/driver/src/cy/actionability.coffee]: agreed, i should either adopt the "ensureWritable" name for readonly as you had in the original PR, or change this to `ensureNotDisabled`.

Which is  better?

Comment (Bkucera) [reply packages/driver/src/cy/actionability.coffee]: renamed to `ensureNotDisabled`

**Review by jennifer-shehane — APPROVED** [review]

**Review by jennifer-shehane — APPROVED** [review]

File: packages/driver/test/cypress/integration/commands/actions/focus_spec.coffee [hunk 3]
```diff
@@ -153,6 +153,14 @@ describe "src/cy/commands/actions/focus", ->
       cy.get("[data-cy=rect]").focus().then ->
         expect(onFocus).to.be.calledOnce
 
+    it "can focus on readonly inputs", ->
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/focus_spec.coffee]: Because this is **the test** that is effectively testing this entire PR - it needs a link above the issue to the issue that it's fixing.
