### PR TITLE
fix(proxy): don't use `responseTimeout` as timeout for all requests

### LINKED ISSUE #6426: XHR requests are cancelled and re-issued if they don't return in 30 seconds
### Current behavior:

When an XHR request takes more than 30 seconds to complete, Cypress cancels the request and issues it again. Depending on what the server does with those requests, this can cause all sorts of problems (e.g. creating duplicate things, or directly resulting in failed tests when the server replies with a 5xx error that it wouldn't have issued if the request hadn't been sent twice).

### Desired behavior:

Cypress should never retry an XHR request on its own, because it cannot know what the effects of a duplicate request could be.

### Test code to reproduce

[cypress-bug.zip](https://github.com/cypress-io/cypress/files/4189923/cypress-bug.zip) (also contains the video generated by Cypress for the failing test).

I used the code in that zip file to generate the screen recording below. The idea is to set up a web server with an API call that takes 34 seconds to reply, then run a Cypress test that visits the home of the web server (which just issues an XHR call to the API method) and waits for the API response, with a timeout longer than the time it takes for the API to respond. You'll see on the logs of the webserver that the API method gets called twice, the second one pretty much exactly 30 seconds after the first one.

To work with the code:

- run `npm i` on both the `webserver` and `tester` folders
- run `node index.js` from the `webserver` folder
- once it's running, `npm run cypress` from the `tester` folder

You'll see that the webserver logs one call to `/`, one to `/api`, and ~30 seconds later another call to `/api`. Cypress then reports a failed test.

### Versions

The issue happens starting with Cypress 3.8.0 (tested with 3.6.1, 3.7.0, 3.8.0, 4.0.1)
Windows 10
Headless tests with Electron

### Additional information

I originally discovered this with the Cypress Docker images. In the project where I found it I could even see Nginx reporting that the client (Cypress running tests) had closed the connection, right before receiving the duplicate request.

Screen recording of the code above showing the issue.

cypress retries request

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6426 

### User facing changelog

- Fixed a bug where requests taking longer than `responseTimeout` (by default, 30 seconds) could be prematurely canceled by the Cypress proxy layer.

### Additional details

- i believe this behavior was undocumented, so no docs updates are needed
- also decaffeinated related request specs

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/server.js [hunk 1]
```diff
@@ -197,10 +197,8 @@ class Server {
 
       logger.setSettings(config)
 
-      // generate our request instance
-      // and set the responseTimeout
-      // TODO: might not be needed anymore
-      this._request = Request({ timeout: config.responseTimeout })
+      // TODO: does not need to be an instance anymore
```
Comment (flotwig) [inline packages/server/lib/server.js:200]: `Request` can now be used statically, no remaining invocations provide options in the constructor

in a future PR, `request.js` and usages can be refactored, which will simplify how we do HTTP requests in general

**Comment by flotwig** [comment]
@panzarino I believe we're trying to move towards smaller, task-focused PRs, but feel free to open an issue to track the bug you noticed. It does not sound related to the changes in this PR - this PR doesn't touch driver-side code.

**Comment by panzarino** [comment]
@flotwig You're correct, it was not related. Issue: #7881, fix: #7882
