### PR TITLE
Fix browser detection with multiline `--version`s

### LINKED ISSUE #6669: Unable to detect firefox on RHEL Linux 7
### Current behavior:
firefox is installed (ran successfully with protractor)

run `cypress run --browser firefox`

error message: only detected browser: chrome, electron

specifying launch path `--browser /bin/firefox`  does not work either

### Test code to reproduce

similiar to [this](https://github.com/cypress-io/cypress/issues/6355)

### Versions

4.1

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6669 

### User facing changelog

- Fixed a bug where some installations of Firefox were not detected correctly.

### Additional details

- I guess `--version` output can be multiline, which we didn't anticipate
- Although the original issue was for Firefox, this adds multiline to *all* versionRegexes, presumably this could happen with other browsers as well

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/launcher/test/unit/linux_spec.ts [hunk 1]
```diff
@@ -42,6 +43,24 @@ describe('linux browser detection', () => {
     return linuxHelper.detect(goal).then(checkBrowser)
   })
 
+  // https://github.com/cypress-io/cypress/issues/6669
+  it('detects browser if the --version stdout is multiline', () => {
+    stdout.withArgs('multiline-foo', ['--version'])
+    .resolves('Running without a11y support!\nfoo-browser v9001.1.2.3')
```
Comment (bahmutov) [inline packages/launcher/test/unit/linux_spec.ts]: can you please just use string template (strip indent) instead of `\n`, since that one is so simple to miss.

File: packages/launcher/test/unit/linux_spec.ts [hunk 2]
```diff
@@ -42,6 +43,24 @@ describe('linux browser detection', () => {
...
+    const checkBrowser = (browser) => {
+      expect(browser).to.deep.equal({
+        name: 'foo-browser',
+        path: 'multiline-foo',
+        version: '9001.1.2.3',
+      })
+    }
+
+    // @ts-ignore
+    return linuxHelper.detect(goal).then(checkBrowser)
```
Comment (bahmutov) [inline packages/launcher/test/unit/linux_spec.ts]: I think in 2020 we can write this test as `async`

```
const found = await linuxHelper.detect(goal)
expect(found).to.deep.equal(...)
```

Comment (bahmutov) [reply packages/launcher/test/unit/linux_spec.ts]: or at least use 
```
return expect(linuxHelper.detect(goal)).to.eventually.deep.equal({...})
```

File: packages/launcher/test/unit/linux_spec.ts (hunk 1 above)
Comment (flotwig) [reply packages/launcher/test/unit/linux_spec.ts]: eh... every time i use the common-tags, i have to manually check that they do what i expect, since i've been burned before by assuming that they do what it says on the can - see "stripIndent" and "stripIndents" doing different things, for example

File: packages/launcher/test/unit/linux_spec.ts (hunk 2 above)
Comment (flotwig) [reply packages/launcher/test/unit/linux_spec.ts]: sure sure, this is mostly a copy of the test above it, which was written in the dark ages of JS (2017)

File: packages/launcher/test/unit/linux_spec.ts (hunk 1 above)
Comment (flotwig) [reply packages/launcher/test/unit/linux_spec.ts]: it also helps that vscode highlights escape sequences for you, so in an editor, this will be clear. looks like github's syntax highlighting isn't there yet :/
