### PR TITLE
fix: issue with 'other' targets not fully loading

### LINKED ISSUE #28162: Issue with  loading webassembly dlls (non cached- performance) in version 13.3.2 and issue showing pdf preview in version 13.3.3
### Current behavior

Hi,

I previously created issue #28054 .This one should be fixed and therefore I updated to V13.3.2
V13.3.2 solves the issue for the cached calls, but not when the dlls are not yet cached (and the webassembly calls are resulting in 200 response codes). The duration of these calls is still about 2000 ms. But after waiting a long time the pdf preview is shown .

I updated to V13.3.3 since I saw some of shared worker / performance issues are fixed in this version. But now the pdf preview is not loading /showing the pdf at all.
Could you please have a look into this

### Desired behavior

All situations etc are working as expected without any negative impact on the performance .

- situation as described in #28054 
- situation as described in Current Behevior part of this issue
-- showing the pdf preview file
-- no negative impact on performance for webAssembly dlls that are not cached yet

V13.3.0 is working fine.

### Test code to reproduce

Not available

### Cypress Version

13.3.2 and 13.3.3

### Node version

16.20.0

### Operating System

Windows

### Debug Logs

_No response_

### Other

_No response_

### LINKED ISSUE #28228: 'other' targets (e.g. pdf documents embedded in an object tag) may not fully load
### Current behavior

PDFs embedded in `object` tags will not fully load and this can cause cy.visit to timeout

### Desired behavior

cy.visit should not timeout

### Test code to reproduce

**Test Code**

```
context('Test', () => {
  it('visit site with unsupported content', () => {
    cy.visit('http://localhost:1515/other_target.html')
  })
})
```

**HTML**

```
<!DOCTYPE html>
<html>
  <head>
    <title>mask-unsupported-content</title>
  </head>
  <body>
    <!-- Video Player -->
    <h2>Video Player</h2>
    <video width="640" height="360" controls>
      <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm" type="video/mp4" />
      Your browser does not support the video tag.
    </video>

    <!-- Objects -->
    <h2>Objects</h2>
    <object type="application/pdf" data="/other-target.pdf" width="250" height="200"></object>
  </body>
</html>
```

### Cypress Version

13.3.2 and greater

### Node version

any

### Operating System

any

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28228 
- Closes #28162 28162

### Additional details

`other` targets can't be Network.enable. We don't get an exception or anything, it just hangs out there. As a result we were never resuming those targets. We fix this by not `Network.enable`ing them.

### Steps to test

There's now a new system test for this scenario.

### How has the user experience changed?

PDFs embedded `object` tags will fully load

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 1]
```diff
@@ -260,7 +260,8 @@ export class BrowserCriClient {
     debug('Target.attachedToTarget %o', event.targetInfo)
 
     try {
-      if (event.targetInfo.type !== 'page') {
+      // We don't track child tabs/page network traffic. 'other' targets can't have network enabled
+      if (event.targetInfo.type !== 'page' && event.targetInfo.type !== 'other') {
```
Comment (chrisbreiding) [inline packages/server/lib/browsers/browser-cri-client.ts:281]: Out of curiosity, have you found a place where all the possible values of `targetInfo.type` are enumerated/documented? It's unfortunate that [here](https://vanilla.aslushnikov.com/?Target.TargetInfo) it's only typed as a "string".

File: system-tests/projects/e2e/other_target.html [hunk 2]
```diff
@@ -0,0 +1,18 @@
+<!DOCTYPE html>
+<html>
+  <head>
+    <title>mask-unsupported-content</title>
+  </head>
+  <body>
+    <!-- Video Player -->
+    <h2>Video Player</h2>
+    <video width="640" height="360" controls>
+      <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm" type="video/mp4" />
```
Comment (chrisbreiding) [inline system-tests/projects/e2e/other_target.html]: Will the test using this fail if this resource is not available? It might be better to include a small webm video in the repo instead.

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 1 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/browser-cri-client.ts:281]: I've found this: https://github.com/chromium/chromium/blob/main/content/browser/devtools/devtools_agent_host_impl.cc#L127-L140, but it unfortunately doesn't do a great job of indicating *what* each of those corresponds to.

File: system-tests/projects/e2e/other_target.html (hunk 2 above)
Comment (ryanthemanuel) [reply system-tests/projects/e2e/other_target.html]: I couldn't get the test to fail without the fix unless this was something external. Annoyed me for sure. I may play around with it a bit more.

Comment (chrisbreiding) [reply system-tests/projects/e2e/other_target.html]: What about if it's served from a fully qualified URL like `http://localhost:1234`? Or if it's on a different port from the AUT?

Comment (ryanthemanuel) [reply system-tests/projects/e2e/other_target.html]: Yeah that's a good idea. I was going to try that next.

Comment (ryanthemanuel) [reply system-tests/projects/e2e/other_target.html]: Took some weird tweaking, but got it working.

**Review by chrisbreiding — APPROVED** [review]

File: system-tests/test/other_target_spec.js [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+      port: 1515,
+      onServer,
+    }, {
+      https: true,
+      port: 1516,
+      onServer,
+    }],
+  })
+
+  systemTests.it.only(`executes a page with a target type of 'other'`, {
```
Comment (ryanthemanuel) [inline system-tests/test/other_target_spec.js]:
```suggestion
  systemTests.it(`executes a page with a target type of 'other'`, {
```

File: system-tests/test/other_target_spec.js [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+      port: 1516,
+      onServer,
+    }],
+  })
+
+  systemTests.it(`executes a page with a target type of 'other'`, {
+    project: 'e2e',
+    spec: 'other_target.cy.js',
+    headed: true,
+    noExit: true,
```
Comment (ryanthemanuel) [inline system-tests/test/other_target_spec.js]:
```suggestion
```

File: system-tests/projects/e2e/cypress/e2e/other_target.cy.js [hunk 5]
```diff
@@ -0,0 +1,5 @@
+context('Test', () => {
+  it('visit site with unsupported content', () => {
```
Comment (emilyrohrbough) [inline system-tests/projects/e2e/cypress/e2e/other_target.cy.js:4]: I'm not sure we will know the intention of this test in the future without reviewing the page being loaded. Its a problem in alot of our tests IMO. A blurb or link to the issue this is solving might help give context but maybe its fine.

**Review by emilyrohrbough — APPROVED** [review]

File: system-tests/test/other_target_spec.js [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+      port: 1515,
+      onServer,
+    }, {
+      https: true,
+      port: 1516,
+      onServer,
+    }],
+  })
+
+  systemTests.it(`executes a page with a target type of 'other'`, {
```
Comment (ryanthemanuel) [inline system-tests/test/other_target_spec.js]:
```suggestion
  // The goal of this test is to load a page containing a target type of 'other' (e.g. embedded pdfs)
  // This is to ensure that we don't hang on the cy.visit (https://github.com/cypress-io/cypress/issues/28228)
  systemTests.it(`executes a page containing a target type of 'other'`, {
```

File: system-tests/projects/e2e/cypress/e2e/other_target.cy.js [hunk 7]
```diff
@@ -0,0 +1,5 @@
+context('Test', () => {
```
Comment (ryanthemanuel) [inline system-tests/projects/e2e/cypress/e2e/other_target.cy.js:3]:
```suggestion
// The goal of this test is to load a page containing a target type of 'other' (e.g. embedded pdfs)
// This is to ensure that we don't hang on the cy.visit (https://github.com/cypress-io/cypress/issues/28228)
context('Test', () => {
```

File: system-tests/projects/e2e/cypress/e2e/other_target.cy.js (hunk 5 above)
Comment (ryanthemanuel) [reply system-tests/projects/e2e/cypress/e2e/other_target.cy.js:4]: Added some comments
