### PR TITLE
fix: fix loading redirects with TE: chunked

### LINKED ISSUE #8497: Some Calls to cy.visit() Fail with a Parse Error when experimentalNetworkStubbing is Turned On
### Current behavior:
Some (but not all) of my calls `cy.visit` are failing with a generic `Parse Error` when I have `experimentalNetworkStubbing` turned on. One such failing call is in the provided below.

### Desired behavior:
Calls to `cy.visit` succeed regardless of whether or not `experimentalNetworkStubbing` is on.

### Test code to reproduce:
```js
it('Issue with cy.visit when experimentalNetworkStubbing is On', function () {
  // This test will pass when experimentalNetworkStubbing is off, but will fail when it is on.
  cy.visit('https://secure.vidyard.com/user/sign_in')
})
```

image

### Versions:
Cypress version 5.1.0 on macOS 10.14.6 using Chrome 85.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #8497 

### User facing changelog

- Fixed an issue where, with `experimentalNetworkStubbing` enabled, `cy.visit`s to URLs that redirect and set `Transfer-Encoding: chunked` would fail in Cypress with a "Parse Error".

### Additional details

- Cypress was setting the erroneous transfer-encoding header
- Still doesn't fix the case where the user has actually set both Content-Length and Transfer-Encoding: chunked - we cannot fix this case without modifying the HTTP parser, see https://github.com/nodejs/llhttp/issues/69

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -411,6 +411,16 @@ describe('network stubbing', function () {
...
 
   context('network handling', function () {
+    // @see https://github.com/cypress-io/cypress/issues/8497
+    it('can load transfer-encoding: chunked redirects', function () {
+      const url4 = 'http://localhost:3501/fixtures/generic.html'
+      const url3 = `http://localhost:3501/redirect?href=${encodeURIComponent(url4)}`
+      const url2 = `https://localhost:3502/redirect?chunked=1&href=${encodeURIComponent(url3)}`
+      const url1 = `https://localhost:3502/redirect?chunked=1&href=${encodeURIComponent(url2)}`
+
+      cy.visit(url1)
```
Comment (Bkucera) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:421]: should there be an assertion that url is url4?

Comment (flotwig) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:421]: sure, why not, added

**Review by Bkucera — APPROVED** [review]
