### PR TITLE
fix: Alias name for `req.alias` containing a dot fail to intercept

### LINKED ISSUE #14444: Alias name for `req.alias` containing a dot fail to intercept
### Current behavior

This was first mentioned here: https://github.com/cypress-io/cypress/issues/3512#issuecomment-754544578

Alias names containing a dot in the `req.alias` (like `get.url`) cause the `cy.wait()` to timeout. 

This does not occur when setting the alias name within an `.as()` command (`.as('get.url')`).

### Test code to reproduce

```js
it('alias without dot', () => {
  cy.intercept('/users', (req) => {
    req.alias = 'getUrl'
    req.reply('foo')
  })
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  // ✅ passes
  cy.wait('@getUrl')
})

it('alias with dot', () => {
  cy.intercept('/users', (req) => {
    req.alias = 'get.url'
    req.reply('foo')
  })
  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  // ❗️ fails, cy.wait() times out
  cy.wait('@get.url')
})
```

Screen Shot 2021-01-07 at 4 04 08 PM

### Versions

Cypress 6.2.1

### PR DESCRIPTION
**Pull request by sainthkh**
TR-620
- Closes #14444

### User facing changelog

When there was a dot in `req.alias`, it failed. This PR fixes this problem. 

### Additional details
- Why was this change necessary? => adding dot for `req.alias` failed without reason. 
- What is affected by this change? => N/A
- Any implementation details to explain? => I only allowed the exception for `request` and `response`. 

### How has the user experience changed?

N/A

### Documentation problem. 

`request` and `response` are reserved. But it is not documented in [`cy.wait`](https://docs.cypress.io/api/commands/wait.html),  [`cy.intercept`](https://docs.cypress.io/api/commands/intercept.html#Comparison-to-cy-route), [`cy.route`](https://docs.cypress.io/api/commands/route.html#Syntax) docs. 

Only documentation I could find was [0.5.10 changelog](https://docs.cypress.io/guides/references/changelog.html#0-5-10). I think it should be added to avoid confusion. 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? => Added a section above to get feedback.

### CODE REVIEW

File: packages/driver/src/cy/commands/waiting.js [hunk 1]
```diff
@@ -100,11 +100,16 @@ module.exports = (Commands, Cypress, cy, state) => {
       _.keys(cy.state('aliases')).includes(str.slice(1))) {
         specifier = null
       } else {
-        // potentially request, response or index
+        // potentially request, response
```
Comment (sainthkh) [inline packages/driver/src/cy/commands/waiting.js:103]: `index` part is added at #4248. As far as I researched, there was no test to use a number with `cy.wait`. It's for `cy.get`.

Maybe I might be wrong.

**Review by flotwig — APPROVED** [review]
