### PR TITLE
test: replace cypress-test-example-repos coverage + remove bump

### LINKED ISSUE #19954: Fix broken test-example-repos job on darwin/win32
On September 14th 2021 CircleCI removed the Xcode 10.1.0 runner: https://discuss.circleci.com/t/xcode-deprecation-notice-9-4-1-10-0-0-10-1-0-and-10-2-1/40515

This broke the Mac testing workflow for cypress-test-example-repos since we use that version: https://app.circleci.com/pipelines/github/cypress-io/cypress-test-example-repos/9669/workflows/31dc5128-0eda-4241-9b86-dd6f56796f12

There is also some issue causing the status check on the cypress repo to erroneously report "passed" even though the tests did not run because the AppVeyor job is reporting "passed": https://ci.appveyor.com/project/cypress-io/cypress-test-example-repos/builds/42364888

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #19954

### User facing changelog

n/a

### Additional details

- For UNIFY-998
- Removes test-example-repos. As outlined in [the Whimsical](https://whimsical.com/app-other-projects-ci-G7s7k8gd3nYKKm7PeZzrjQ) it is only adding coverage via `test-example-recipes`.
- Adds `test-example-recipes` coverage directly in test-binary jobs.

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

Post merge

- [ ] Archive cypress-test-example-repos
- [ ] Archive cypress-example-reporters
- [ ] Archive cypress-example-piechopper
- [ ] Archive cypress-example-phonecat
- [ ] Ensure https://github.com/cypress-io/cypress-documentation/pull/4352 makes it in

### CODE REVIEW

File: scripts/binary/bump.js [hunk 1]
```diff
@@ -19,13 +19,6 @@ const _PROVIDERS = {
       'cypress-io/cypress-test-module-api',
       'cypress-io/cypress-test-node-versions',
```
Comment (emilyrohrbough) [inline scripts/binary/bump.js:20]: long terem, will the plan be to remove all of these projects from bump.js to the circleci jobs or maybe expand to these repos to run for linux, darwin and win32?

**Review by emilyrohrbough — APPROVED** [review]

File: scripts/binary/bump.js (hunk 1 above)
Comment (flotwig) [reply scripts/binary/bump.js:20]: I'd like to eventually get rid of this "bump" stuff altogether. We can test almost everything inside of this monorepo's CircleCI where it's much easier for developers to debug failures/add new tests/understand the system. The only thing that `bump` adds is the ability for us to e2e test Cypress running in response to a git push that triggered a CI run. Theoretically this would allow us to test against multiple CI providers, but practically, we don't run against multiple CI providers in CI anyways because it was too much to maintain. Plus, we have plenty of tests that cover specific CI provider functionality in the `server`.

I'm spiking into extending system-tests to run against built Cypress and/or with Docker containers, so that we don't need `bump.js` to run node-versions and ci-environments.

Comment (emilyrohrbough) [reply scripts/binary/bump.js:20]: it'd be amazing if we could drop this! It's def a hidden test case, especially since it only runs on a few branches.

**Comment by jennifer-shehane** [comment]
@flotwig It looks like the cypress-test-node-versions is failing with a Cypress 10.0 error about there being a cypress.json error. Why would that be triggering here?

**Comment by flotwig** [comment]
@jennifer-shehane it's also failing in `develop`, I'm not sure, it shouldn't be erroring with that at all... I'll check it out

**Review by ryanthemanuel — APPROVED** [review]
