### PR TITLE
fix: AttemptResult object

### LINKED ISSUE #24110: Wrong 'AttemptResult' TS type
### Current behavior

Hi and thank you for this great work.

Just want to report a **tiny issue** with the `CommandLine.AttemptResult` type. The [type definition](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress-npm-api.d.ts#L183) is:

```js
interface AttemptResult {
  state: string
  error: TestError | null
  startedAt: dateTimeISO
  duration: ms
  videoTimestamp: ms
  screenshots: ScreenshotInformation[]
}
```

But `duration` and `startedAt` don't exist in the actual object, instead the following should be defined `wallClockDuration` and `wallClockStartedAt` respectively, I've attached a sample `AttemptResult` object.

Not sure if `screenshots` property exist in the actual object, and there is `failedFromHookId` and `timings` missing in the type definition which exist. Anyway, if this is confirmed, I could take a look into fixing it. 👍 

### Desired behavior

_No response_

### Test code to reproduce

Here is a TS example accessing mentioned properties:

```js
export default (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('after:spec', async (spec, results) => {
    results.tests.forEach(cypressTestResult => {
      const attempt = cypressTestResult.attempts.pop();
      console.log(attempt);
      // This will complain that the property doesn't exist
      const wallClockDuration = attempt.wallClockDuration;
      // This will complain that the property doesn't exist
      const wallClockStartedAt = attempt.wallClockStartedAt;
    });
  });
}
```

### Cypress Version

10.9.0

### Node version

16.3.0

### Operating System

macOS 12.1

### Debug Logs

```shell
{
  state: 'passed',
  error: null,
  timings: { lifecycle: 7, test: { fnDuration: 9805, afterFnDuration: 0 } },
  failedFromHookId: null,
  wallClockStartedAt: '2022-10-04T10:39:19.792Z',
  wallClockDuration: 9817,
  videoTimestamp: 1584
}
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by itiarom**
- Closes https://github.com/cypress-io/cypress/issues/24110

### Additional details

* Fields are added to AttempResult object
* This change is necessary in order to correspond to the current TestResult properties

### Steps to test

* Create a test with retries
* Log the `currentTestResult`
* Check the object's properties

### PR tasks

* Changed duartion to wallClockDuration
* Changed startedAt to wallClockStartedAt
* Added failedFromHookId
* Added timings
* TODO: Should Timings object be created?
* TODO: Should documentation be updated?

### Questions for reviewers

* Should a Timings object be created?
* Should additional properties be added to AttemptResult object other than those specified in the issue?
image

### CODE REVIEW

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by itiarom** [comment]
Hello, I will keep on working on this issue I have just been busy with work and school. I am picking it up again soon.

**Comment by jnovoadeuna** [comment]
@Ioanna2001 Thank you very much for your interest in solving this problem. I'm currently having the same problem that you solve with this PR, I'm looking forward to it being merged. Thanks again for your contribution.

**Comment by mike-plummer** [comment]
@Ioanna2001 I made a few updates based on a quick look at the code; seems like the `timings` and `hookInformation` fields can potentially be `null`, and there's sometimes a `hookId` field supplied to a Timing based on how it's triggered. Also made a tweak to the changelog entry. LMK if you disagree with any of it.

I'll track down another approver and get this merged assuming everything on CI comes back green

**Review by mike-plummer — APPROVED** [review]

File: cli/types/cypress-npm-api.d.ts [hunk 1]
```diff
@@ -184,13 +184,24 @@ declare namespace CypressCommandLine {
     attempts: AttemptResult[]
   }
 
+  interface Timings {
+    lifecycle: number
+    test: {
+      hookId?: any
```
Comment (lmiller1990) [inline cli/types/cypress-npm-api.d.ts]: This should be `string` - that said, these are internal properties that is not part of our public API, I am not sure we should be defining types for this? It could change at any moment.

Alternatively, they could be marked as `@private`, but rather than having an internal property `hookId` that is nullable and `any`, maybe we should remove these. Considering this is from the Mocha test runner, and they can change this at any time - we do not control it.

File: cli/types/cypress-npm-api.d.ts [hunk 2]
```diff
@@ -184,13 +184,24 @@ declare namespace CypressCommandLine {
...
+      afterFnDuration: number
+    }
+  }
+
   interface AttemptResult {
     state: string
     error: TestError | null
-    startedAt: dateTimeISO
-    duration: ms
+    wallClockStartedAt: dateTimeISO
```
Comment (lmiller1990) [inline cli/types/cypress-npm-api.d.ts:190]: These seem correct.

File: cli/types/cypress-npm-api.d.ts (hunk 1 above)
Comment (lmiller1990) [reply cli/types/cypress-npm-api.d.ts]: WDYT @mike-plummer ?

Comment (mike-plummer) [reply cli/types/cypress-npm-api.d.ts]: Good callout @lmiller1990 , from the writeup it seems like `timings` and `failedFromHookId` aren't actually being relied on but were added here because the fields were seen as "present" when inspecting the result. Probably best to remove them both unless a specific external need for them is identified, especially since the internal mocha-derived types aren't typed very well as-is.

**Review by lmiller1990 — APPROVED** [review]

File: cli/types/cypress-npm-api.d.ts (hunk 1 above)
Comment (lmiller1990) [reply cli/types/cypress-npm-api.d.ts]: Done.

**Comment by mike-plummer** [comment]
@Ioanna2001 Thanks for the contribution, sorry it took us a while to get it merged in. This will be included in our next release

**Comment by itiarom** [comment]
@mike-plummer Thank you for the help and the update, I'm really glad I was able to help. Looking forward for the release!
