### PR TITLE
fix: Improve document.cookie patch

### LINKED ISSUE #23531: Fix issue with the timing of setting cookies in the browser
Currently, if a cross-origin request sets a cookie and the app attempts to read the cookie via `document.cookie` synchronously on page load, the `document.cookie` value will not be correct / up-to-date.

Spec:

```js
it('document.cookie includes cookie set by http request', () => {
  cy.get('[data-cy="cookie-login-land-on-document-cookie"]').click()
  cy.origin('http://foobar.com:3500', { args: { username } }, ({ username }) => {
    cy.get('[data-cy="username"]').type(username)
    cy.get('[data-cy="login"]').click()
  })

  cy.origin('http://idp.com:3500', { args: { username } }, ({ username }) => {
    cy.get('[data-cy="document-cookie"]').invoke('text')
    .should('include', `user=${username}`)
  })
})
```

App:

```html
<p>
  <strong>document.cookie:</strong>
  <span data-cy="document-cookie"></span>
</p>
<script>
  document.querySelector('[data-cy="document-cookie"]').textContent = document.cookie;
</script>
```

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #23531

### User facing changelog

- Fixed an issue where, in certain circumstances, `document.cookie` would not reflect the correct value in cross-origin tests

### Additional details

Previously, the document.cookie patch would have to wait ~250ms to be up-to-date with cookies stored in the browser because it polls automation for them. This could result in document.cookie not being accurate if a page read its value on page load.

This fixes the issue by updating the document.cookie patch's value before the page loads by sending the cookies down from the proxy when the response is intercepted. This makes the correct value available on page load.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 1]
```diff
@@ -1,3 +1,46 @@
+const parseCookieString = (cookieString) => {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:1]: This file is going to be interesting to convert into an injection time patch when the spec bridge isn't attached yet.

Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:1]: Is this a replacement for the tough cookie parsing or are they parsing different cookie string formats?

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 2]
```diff
@@ -13,43 +56,59 @@
...
 //   updates to the cookie jar (via http requests, cy.setCookie, etc) are
 //   reflected in the document.cookie value.
-export const patchDocumentCookie = (Cypress, window) => {
-  const setAutomationCookie = (toughCookie) => {
-    const { superDomain } = Cypress.Location.create(window.location.href)
-    const automationCookie = Cypress.Cookies.toughCookieToAutomationCookie(toughCookie, superDomain)
+export const handleDocumentCookie = (Cypress) => {
+  // if cookies were sent before the spec bridge was created, they'll come
+  // through as state('crossOriginCookies'), so use them then reset them
+  const cookies = Cypress.state('crossOriginCookies')
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:62]: is this state unique per spec bridge or could we get this state from the primary cypress instance through a post message?

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 3]
```diff
@@ -77,4 +136,30 @@ export const patchDocumentCookie = (Cypress, window) => {
...
+    updateCookies([cookie])
+  })
+
+  Cypress.on('clear:cookie', (name) => {
+    documentCookieValue = clearCookie(documentCookieValue, name)
+  })
+
+  Cypress.on('clear:cookies', () => {
+    reset()
+  })
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:164]: It looks like these could wait to be hooked up until a spec bridge is attached.

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 4]
```diff
@@ -77,4 +136,30 @@ export const patchDocumentCookie = (Cypress, window) => {
   }
 
   window.addEventListener('unload', onUnload)
+
+  Cypress.on('window:before:load', patch)
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:140]: Are we patching here to ensure that state is setup first? We will have to come up with something else if there isn't a spec bridge attached.

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 5]
```diff
@@ -77,4 +136,30 @@ export const patchDocumentCookie = (Cypress, window) => {
...
+
+  Cypress.specBridgeCommunicator.on('cross:origin:cookies', (cookies) => {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/patches/cookies.js:142]: This updates the cookies in the cross origin aut with changes pushed from the primary cypress instance? This should be pretty easy to not rely on cypress for.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 2 above)
Comment (mjhenkes) [reply packages/driver/src/cross-origin/patches/cookies.js:62]: instead of passing state here, could we call out to the primary cypress instance to retrieve these cookies?

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 6]
```diff
@@ -62,7 +121,7 @@ export const patchDocumentCookie = (Cypress, window) => {
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/patches/cookies.js:121]: I think we need the full `hostname` here since `Cypress.Location` omits the subdomain. If we have cookies set on `www.example.com` and we call the automation API to get cookies for `.example.com`, are the cookies from `www.example.com` omitted? 

UPDATE: looks like cookies from `.www.example.com` are included with super domain `.example.com`. My guess is that this would also mean that other subdomains might get applied to `document.cookie` when we might not want them to, like `app.example.com`.

If we inject the AUTWindow into the patch, we should be able to use `window.location.hostname` to get the domain with the subdomain in it.

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 7]
```diff
@@ -13,43 +56,59 @@
...
+        const cookie = Cypress.Cookies.parse(newValue)
 
-    set (newValue) {
-      const cookie = Cypress.Cookies.parse(newValue)
+        // If cookie is undefined, it was invalid and couldn't be parsed
+        if (!cookie) return documentCookieValue
 
-      // If cookie is undefined, it was invalid and couldn't be parsed
-      if (!cookie) return documentCookieValue
+        documentCookieValue = mergeCookies(documentCookieValue, [{
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/patches/cookies.js:93]: I don't think this currently preserves duplicates, such as 

```
const merged = mergeCookies('foo=bar; foo=bar', [{
  name: 'foo',
  value: 'baz',
}])

// merged is 'foo=baz', where I would expect something like 'foo=bar; foo=baz'
```

I played around with some cookies in chrome and firefox to spoof the following





I think we need more to go off of to set the cookie here properly, such as cookie domain and path, which it looks like we get from the `get:cookies` automation response.

Screen Shot 2022-09-08 at 4 25 46 PM

I wonder if we can take the cookies from the `setInterval` , i.e `Cypress.automation('get:cookies', { domain })` and store those within the `handleDocumentCookie` closure similar to how we store the `documentCookieValue`. Then, when a user gets `document.cookie`, we just stringify the cookies from the automation response. When a user sets a cookie, we can take the cookies from the variable that has the reference to the `get:cookies` stored variable and make sure we overwrite the correct cookie. The default should be the full `hostname` with path `/`, which I think `tough-cookie` handles but I can't remember off the top of my head.

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 8]
```diff
@@ -77,4 +136,30 @@ export const patchDocumentCookie = (Cypress, window) => {
...
+  Cypress.on('set:cookie', (cookie) => {
+    updateCookies([cookie])
+  })
+
+  Cypress.on('clear:cookie', (name) => {
+    documentCookieValue = clearCookie(documentCookieValue, name)
+  })
+
+  Cypress.on('clear:cookies', () => {
+    reset()
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/patches/cookies.js:163]: I wonder if we still need to do this if we store the reference to `get:cookies`, or just clear the reference out?

File: packages/proxy/lib/http/response-middleware.ts [hunk 9]
```diff
@@ -485,11 +485,13 @@ const CopyCookiesFromIncomingRes: ResponseMiddleware = async function () {
     return this.next()
   }
 
-  this.serverBus.once('cross:origin:automation:cookies:received', () => {
+  const origin = cors.getOriginPolicy(this.req.proxiedUrl)
```
Comment (AtofStryker) [inline packages/proxy/lib/http/response-middleware.ts:488]: I think when it comes to `getOriginPolicy` for cookies, we need to factor in the subdomain. I think this method was originally intended for the `document.domain` matching to prevent AUT reloads, but we might need a different method here all together, as well as rename this method. I am going to try some sorts of a rename effort in #23728

**Review by AtofStryker — CHANGES_REQUESTED** [review]
any idea if this fixes the issues inside the `cookie_behavior` tests with trying to get/set cookies inside `cy.origin` using the cypress api?

I think we might need to change the patch a little bit to work with cookies of the same key, but different domains/paths (which are apparently more common than I would have thought), but I think there is something we can try that I suggested below!

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 2 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js:62]: The trick is we need them synchronously on page load. Post message won't work because it's async. I think what we'll need to do is hold on to them server-side and include them directly in the injection when we render it.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 4 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js:140]: It's here because it needs to be done on before the page loads. If we move this into the injection it will just work since the injection is the first script run.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 5 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js:142]: This ultimately comes from the proxy. If the spec bridge is already set up, it sends this event to pass in the cookies to the patch before the page load that might potentially use them via document.cookie.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js:1]: I had converted it to TypeScript and then converted it back when it became evident it would need to go into the injection, thinking it couldn't be TypeScript for that. Looking into it now, it seems that's not an actual limitation of code going into the injection, so I'll convert it to TypeScript once again.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 2 above)
Comment (mjhenkes) [reply packages/driver/src/cross-origin/patches/cookies.js:62]: We can do that. I already do it for modify obstructive code config.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 6 above)
Comment (mjhenkes) [reply packages/driver/src/cross-origin/patches/cookies.js:121]: lucky for us, once we move the patch to the injection window, will be the AUT window!

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 4 above)
Comment (mjhenkes) [reply packages/driver/src/cross-origin/patches/cookies.js:140]: oh, that makes sense.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 1 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: Essentially they're different. Tough cookie will only parse a single cookie string, namely the one in `Set-Cookie` response headers. This is for parsing the `document.cookie` string, which includes multiple cookies in the format `key1=value1; key2=value2`.

[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: Addressed in [`e728aed` (#23643)](https://github.com/cypress-io/cypress/pull/23643/commits/e728aed89f661e9ebaf7936e0899669e9214f028)

File: packages/driver/src/cross-origin/patches/cookies.js [hunk 10]
```diff
@@ -13,43 +56,59 @@
...
+  Cypress.state('crossOriginCookies', [])
 
-    Cypress.automation('set:cookie', automationCookie)
-    .catch(() => {
+  const patch = (window) => {
+    // Cookies added to the server-side cookie jar are optimistically
+    // added here so that if a cross-origin request sets cookies, they're
+    // available via document.cookie synchronously on page load
+    const setAutomationCookie = (toughCookie) => {
+      const { superDomain } = Cypress.Location.create(window.location.href)
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: Now using [`location.hostname` instead](https://github.com/cypress-io/cypress/pull/23643/files#diff-0e98d845aa0ebdbe6c8b598f18dc81cc8f0ea4c09e7894ea32000e0ba4d116daR59).

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 6 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: Now using [`location.hostname` instead](https://github.com/cypress-io/cypress/pull/23643/files#diff-0e98d845aa0ebdbe6c8b598f18dc81cc8f0ea4c09e7894ea32000e0ba4d116daR59).

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 7 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: Fixed and [added a test](https://github.com/cypress-io/cypress/pull/23643/files#diff-6bf45b7f9903569c8f01830b58bfeac19264dc6b4eee767155d1b6484492b25fR854). Now use a `tough-cookie` cookie jar to track the cookies, so it applies the correct logic for handling duplicate cookie keys.

File: packages/driver/src/cross-origin/patches/cookies.js (hunk 8 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/patches/cookies.js]: This is to optimistically clear out the cookies when a user calls `cy.clearCookies()` so there's no delay/race condition waiting to sync with the automation cookies. There's actually no longer any polling to sync with automation cookies. It just caused issues and now all cases of cookies changing in automation are taken care of in a more deterministic fashion

File: packages/proxy/lib/http/response-middleware.ts (hunk 9 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts]: No longer using the origin here, so this shouldn't be a concern.

File: packages/proxy/lib/http/response-middleware.ts [hunk 11]
```diff
@@ -372,10 +373,23 @@ const MaybePreventCaching: ResponseMiddleware = function () {
   this.next()
 }
 
+const setSimulatedCookies = (ctx: HttpMiddlewareThis<ResponseMiddlewareProps>) => {
+  const defaultDomain = (new URL(ctx.req.proxiedUrl)).hostname
+  const allCookiesForRequest = ctx.getCookieJar()
```
Comment (AtofStryker) [inline packages/proxy/lib/http/response-middleware.ts:380]: should be put these variable declarations inside the `if` block since they are a no-op without it?

File: packages/proxy/lib/http/util/rewriter.ts [hunk 12]
```diff
@@ -16,35 +17,56 @@ export type InjectionOpts = {
...
   wantsInjection: CypressWantsInjection
   wantsSecurityRemoved: any
+  simulatedCookies: AutomationCookie[]
 }
 
-const doctypeRe = /(<\!doctype.*?>)/i
-const headRe = /(<head(?!er).*?>)/i
-const bodyRe = /(<body.*?>)/i
-const htmlRe = /(<html.*?>)/i
+const doctypeRe = /<\!doctype.*?>/i
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/rewriter.ts:23]: Did removing the capture group here have any side effects / why did we need to remove it? Just redundant?

Comment (AtofStryker) [reply packages/proxy/lib/http/util/rewriter.ts:23]: I think I answered my own question after seeing the refactor for `insertBefore`/`insertAfter` 😄

File: packages/runner/injection/patches/cookies.ts [hunk 13]
```diff
@@ -0,0 +1,133 @@
...
+
+    return {
+      name: name.trim(),
+      value: value.trim(),
+      domain: location.hostname,
+      expiry: null,
+      httpOnly: false,
+      maxAge: null,
+      path: null,
+      sameSite: 'lax',
```
Comment (AtofStryker) [inline packages/runner/injection/patches/cookies.ts:23]: This is done synchronously to seed the cookie jar with the simulated cookies on the initial response? I think ideally we could get these cookies out of CDP and set them here, but we need to do that async, and the only thing I think we get out of it is accurate `path`, `sameSite`, etc... I think these should be sane defaults, right?

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/response-middleware.ts:380]: or is there a side effect here?

File: packages/driver/src/cross-origin/cypress.ts [hunk 14]
```diff
@@ -165,21 +165,18 @@ const attachToWindow = (autWindow: Window) => {
 
   const cy = Cypress.cy
 
+  // this communicates to the injection code that Cypress is now available so
+  // it can safely subscribe to Cypress events, etc
+  // @ts-ignore
+  autWindow.__attachToCypress(Cypress)
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/cypress.ts:171]: lol, I have basically this same thing in my PR: https://github.com/cypress-io/cypress/pull/24243

File: packages/driver/src/cross-origin/communicator.ts [hunk 15]
```diff
@@ -113,6 +113,10 @@ export class PrimaryOriginCommunicator extends EventEmitter {
     debug('Unexpected postMessage:', data)
   }
 
+  isConnectedToSpecBridge (originPolicy: string) {
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/communicator.ts]: I think we just want to call this origin @AtofStryker 

```suggestion
  isConnectedToSpecBridge (origin: string) {
```

File: packages/runner/injection/cross-origin.js [hunk 16]
```diff
@@ -92,13 +94,28 @@ const timers = createTimers()
 
 timers.wrap()
 
-const Cypress = findCypress()
+const attachToCypress = (Cypress) => {
```
Comment (mjhenkes) [inline packages/runner/injection/cross-origin.js:97]: I borrowed your function name but have a slightly different spin on the function which i've setup to self destruct and remove itself from window after it's called.

File: packages/driver/src/cross-origin/communicator.ts (hunk 15 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/communicator.ts]: Realized I don't even use this method anymore so I removed it in https://github.com/cypress-io/cypress/pull/23643/commits/12277d6678d964cc1bf759ff834d7aeed13c0649

File: packages/driver/src/cross-origin/cypress.ts (hunk 14 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/cypress.ts:171]: Great minds and all 🧠

File: packages/proxy/lib/http/response-middleware.ts (hunk 11 above)
Comment (chrisbreiding) [reply packages/proxy/lib/http/response-middleware.ts:380]: Good call. Addressed in https://github.com/cypress-io/cypress/pull/23643/commits/5b7822e6544df861848f07ef711c272b04df06c3

File: packages/driver/src/cross-origin/events/cookies.ts [hunk 17]
```diff
@@ -0,0 +1,47 @@
...
+  let cookiesToSend: AutomationCookie[] = []
+  let waitingToSend = false
+
+  Cypress.on('cross:origin:cookies', (cookies: AutomationCookie[]) => {
+    Cypress.backend('cross:origin:cookies:received')
+
+    cookiesToSend = cookiesToSend.concat(cookies)
+
+    const onBeforeStabilityRelease = (stable: boolean) => {
+      if (!stable) return
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/events/cookies.ts]: It's so weird that 'before:stability:release' can get called with false stability, i would have thought that this action would be called when stability is false but just before it is set to true.

File: packages/runner/injection/patches/cookies.ts (hunk 13 above)
Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts:23]: Right, it's to grab any value currently in document.cookie so if a user reads it, it's still there. If it's originally read from `document.cookie`, its path/sameSite/etc must match already, so it makes sense for it to be read from `document.cookie` subsequently, right?

File: packages/driver/src/cross-origin/events/cookies.ts (hunk 17 above)
Comment (chrisbreiding) [reply packages/driver/src/cross-origin/events/cookies.ts]: Good point. Changed it to behave like that: https://github.com/cypress-io/cypress/pull/23643/commits/f1441f0c59522b19d6b9a05863f852fc2bf2c7e1

File: packages/driver/src/cross-origin/events/cookies.ts [hunk 18]
```diff
@@ -0,0 +1,45 @@
...
+        // errors here can be ignored as they're not user-actionable
+      })
+    }
+
+    if (!waitingToSend) {
+      waitingToSend = true
+      // this event allows running a handler before stability is released.
+      // this prevents subsequent commands from running until the cookies
+      // are set via automation
+      Cypress.on('before:stability:release', onBeforeStabilityRelease)
```
Comment (mjhenkes) [inline packages/driver/src/cross-origin/events/cookies.ts]: With your changes i think you could make this a `Cypress.once` and remove the `Cypress.off` call to clean it up inside the function.

Comment (chrisbreiding) [reply packages/driver/src/cross-origin/events/cookies.ts]: Addressed in https://github.com/cypress-io/cypress/pull/23643/commits/8c9d60f077eb12e18de078ffec11ff122494ba2b

File: packages/runner/injection/patches/cookies.ts [hunk 19]
```diff
@@ -0,0 +1,133 @@
+import { AutomationCookie } from '@packages/server/lib/automation/cookies'
```
Comment (mjhenkes) [inline packages/runner/injection/patches/cookies.ts]: Could we break automationCookie out into its own file? This import is pulling in an awful lot just to grab the interface.

```js
import _ from 'lodash'
import Debug from 'debug'
import extension from '@packages/extension'
import { isHostOnlyCookie } from '../browsers/cdp_automation'
```

Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts]: Changed it to use `import type`, so it shouldn't pull anything in to the bundle. Addressed in https://github.com/cypress-io/cypress/pull/23643/commits/7b91ba5cde2a1fb690c3e08642e7909c5fd4522a

File: packages/runner/injection/patches/cookies.ts [hunk 20]
```diff
@@ -0,0 +1,133 @@
...
+// if the user's app was run in top.
+//
+// The general strategy is:
+// - Keep the document.cookie value (`documentCookieValue`) available so
+//   the document.cookie getter can synchronously return it.
+// - Optimistically update that value when document.cookie is set, so that
+//   subsequent synchronous calls to get the value will work.
+// - On an interval, get the browser's cookies for the given domain, so that
+//   updates to the cookie jar (via http requests, cy.setCookie, etc) are
+//   reflected in the document.cookie value.
```
Comment (mjhenkes) [inline packages/runner/injection/patches/cookies.ts]: Does this comment need to be updated? I don't think we still get cookies on an interval

Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts]: Moved most of this comment into separate ones closer to where they're relevant: https://github.com/cypress-io/cypress/pull/23643/commits/1c91af77313d0e558d05668625c33088272ae8bb

File: packages/runner/injection/patches/cookies.ts [hunk 21]
```diff
@@ -0,0 +1,127 @@
...
+
+      return getDocumentCookieValue()
+    },
+  })
+
+  const reset = () => {
+    cookieJar.removeAllCookies()
+  }
+
+  const bindCypressListeners = (Cypress: Cypress.Cypress) => {
```
Comment (mjhenkes) [inline packages/runner/injection/patches/cookies.ts:108]: Do we need to listen for cookies changes even before a cypress instance attaches?

for example, would the following test work? (I haven't run this so it probably doesn't work without modifications)

```js
it('might need to listen without a cypress instance', () => {
  visit('localhost')
  visit('http://www.foobar.com:3500')
  cy.setCookie('foo', 'bar', {domain: foobar.com})
  cy.origin('foobar.com:3500', () => {
    cy.window((win) => {
      expect(win.document.cookies).to.eq('foo=bar')
    }
  })
}
```

File: packages/runner/injection/patches/cookies.ts [hunk 22]
```diff
@@ -0,0 +1,127 @@
...
+    },
+  }, '*')
+}
+
+// document.cookie monkey-patching
+// -------------------------------
+// We monkey-patch document.cookie when in a cross-origin injection, because
+// document.cookie runs into cross-origin restrictions when the AUT is on
+// a different origin than top. The goal is to make it act like it would
+// if the user's app was run in top.
```
Comment (mjhenkes) [inline packages/runner/injection/patches/cookies.ts:47]: In the case outside of cy.origin where we are same-site but cross-origin, would we want to apply this patch?
We may need to check on this for #24275

@AtofStryker

File: packages/runner/injection/patches/cookies.ts (hunk 21 above)
Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts:108]: Currently that fails with `The command was expected to run against origin http://localhost:3500 but the application is at origin http://www.foobar.com:3500`. I think it makes sense that the user should put it inside the origin callback in that case and then the listeners will be set up as well.

File: packages/runner/injection/patches/cookies.ts (hunk 22 above)
Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts:47]: Good to keep in mind. I'll defer to Bill on that one.

**Review by mjhenkes — APPROVED** [review]

File: packages/runner/injection/patches/cookies.ts (hunk 21 above)
Comment (mjhenkes) [reply packages/runner/injection/patches/cookies.ts:108]: I think we may want to revisit throwing that error:
>The command was expected to run against origin http://localhost:3500 but the application is at origin http://www.foobar.com:3500

I added the limitation that cy.cookies could only be run when the aut was same-site as top, I don't think thats correct anymore since we will be allowing cy.cookies to be set on any domain (i think it can be done now?) and we should probably think about changing this behaviour in #24264

File: packages/runner/injection/patches/cookies.ts (hunk 22 above)
Comment (AtofStryker) [reply packages/runner/injection/patches/cookies.ts:47]: I believe so, at least for `hostname` specific cookies

File: packages/runner/injection/patches/cookies.ts (hunk 13 above)
Comment (AtofStryker) [reply packages/runner/injection/patches/cookies.ts:23]: I think so. Does this get updated to the known values once the automation cookies sync in?

**Review by AtofStryker — APPROVED** [review]
Do we know if this fixes some of cookie assertions in `cookie_behavior.cy.ts`? I think most of those are fixed with https://github.com/cypress-io/cypress/issues/24264?

File: packages/runner/injection/patches/cookies.ts (hunk 13 above)
Comment (chrisbreiding) [reply packages/runner/injection/patches/cookies.ts:23]: It no longer polls to sync with the automation cookies, since that leads to race conditions and was pretty non-deterministic.

**Comment by chrisbreiding** [comment]
> Do we know if this fixes some of cookie assertions in cookie_behavior.cy.ts? I think most of those are fixed with https://github.com/cypress-io/cypress/issues/24264?

I don't think so because this only fixes timing issues with `document.cookie`, not with cookies being available via automation. To fix those issues, we probably need to move Firefox to use CDP for cookies and ensure they're set before an cookie-setting requests are allowed to proceed.

File: packages/runner/injection/patches/cookies.ts (hunk 13 above)
Comment (AtofStryker) [reply packages/runner/injection/patches/cookies.ts:23]: oh duh 🤦🏻 . I wonder in the future if we can get automation cookies w/ simulated cookies to know these values upon injection. Otherwise though I feel like the defaults are sane and fine.
