### PR TITLE
fix: Fix issue with cy.contains when scoped inside shadow root

### LINKED ISSUE #8494: Querying shadow dom with cy.contains when within shadow root does not find elements
### Current behavior:

Querying shadow dom with `cy.contains` when already within a shadow root does not find the element with the specified text.

Screen Shot 2020-09-08 at 10 52 11 AM

### Desired behavior:

Querying the shadow dom should work using `cy.contains`.

### Test code to reproduce

_cypress.json_

```json
{
  "experimentalShadowDomSupport": true
}
```

_cypress/fixures/shadow-dom.html_

```html
<html>
<body>
  <div id="outer">
    <div id="host"></div>
  </div>

  <script>
    document
    .getElementById('host')
    .attachShadow({ mode: 'open' })
    .innerHTML = '<div class="in-shadow-dom">In Shadow DOM</div>'
  </script>
</body>
</html>
```

_spec.js_

```javascript
it('fails querying shadow dom in cy.within', () => {
  cy.visit('/cypress/fixures/shadow-dom.html')
  cy
  .get('#host')
  .shadow()
  .contains('In Shadow DOM')
  .should('have.class', 'in-shadow-dom')
})
```

### Versions

Cypress 4.8.0+

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #8494

### User facing changelog

- Fixed an issue where using `cy.contains()` within a shadow root would not yield the correct element

### Additional details

In addition to fixing the issue, this adds a couple more tests to ensure `cy.contains()` works correctly when the element being queried is in the shadow dom

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/querying_shadow_dom_spec.js [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+    })
+
+    // https://github.com/cypress-io/cypress/issues/7676
+    it('does not error when querySelectorAll is wrapped and snapshots are off', () => {
+      cy.visit('/fixtures/shadow-dom.html?wrap-qsa=true')
+      cy.get('.shadow-1', { includeShadowDom: true })
+    })
+  })
+
+  context('#contains', () => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/commands/querying_shadow_dom_spec.js:77]: These are the tests that I added. The rest were just moved.

**Review by flotwig — APPROVED** [review]
