### PR TITLE
fix: move from getos to systeminformation to fix OS distro/release info

### LINKED ISSUE #30533: Module API `results.osVersion` contains only Linux distribution without release version
### Current behavior

When running on Linux, the Cypress [Module API](https://docs.cypress.io/app/references/module-api) `results.osVersion` contains only the name of the Linux distribution, e.g. 
- `Debian - `
- `Fedora - `
- `Ubuntu - `

The Linux release version e.g. `24.04` is missing from `results.osVersion` when run under Cypress `11.0.0` and above. This issue is a regression compared to Cypress `10.11.0`.

### Desired behavior

When running on Linux, the Cypress [Module API](https://docs.cypress.io/app/references/module-api) `results.osVersion` should contain both the Linux distribution name and release version, e.g. `Ubuntu - 24.04`. This is how it worked in Cypress `10.11.0`.

`cypress info` displays both the Linux distribution name and release version,e.g. `Ubuntu - 24.04` as in the following output:

```text
Cypress Version: 13.15.1 (stable)
System Platform: linux (Ubuntu - 24.04)
System Memory: 8.28 GB free 6.61 GB
```

### Test code to reproduce

https://github.com/MikeMcC399/cypress-test-tiny/tree/30533-module-api-osversion

On Ubuntu `24.04.2` LTS, Node.js `v22.15.0` LTS, execute:

```shell
git clone --branch 30533-module-api-osversion https://github.com/MikeMcC399/cypress-test-tiny
cd cypress-test-tiny
npm ci
npm test
```

### Cypress Version

First reported on version: `13.15.1`
Reproducible also on `15.0.0`

### Node version

~~`v22.13.0` LTS~~ `v22.18.0` LTS

### Operating System

Ubuntu `24.04.3` LTS

### Debug Logs

Preparation as in "Test code to reproduce" above, then execute:

```shell
npm run test:debug
```

excerpt only:

```text
cypressVersion: '13.15.1', endedTestsAt: 2024-11-03T12:51:59.448Z, osName: 'linux', osVersion: 'Ubuntu - '
```

### Other

See [cli/types/cypress-npm-api.d.ts](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress-npm-api.d.ts)

https://github.com/cypress-io/cypress/blob/b8a5280fd36adea8f046465a0aa3fc0e62f70f8c/cli/types/cypress-npm-api.d.ts#L271-L294

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes https://github.com/cypress-io/cypress/issues/30533

### Additional details

We were not getting the correct release for some distros and releases. We were using `getos` which is an npm package that hasn't been updated in 3 years.

The format returned should be `os.platform os.distro - os.release`, but was often only getting values that often returned:
- `os.platform -`
- `os.platform - os.release`

This PR further centralizes our use of the `systeminformation` package to get OS information.

### Steps to test

1. Put a Module API file within the root of the `cypress` directory
2. Run `node module-api.js` and see what osVersion is printed

```js
/* @ts-ignore */
import cypress from './cli/lib/cypress.js'

const run = cypress.run

run({
  spec: './system-tests/projects/e2e/cypress/e2e/simple.cy.js',
  testingType: 'e2e',
  project: './system-tests/projects/e2e',
  /* @ts-ignore */
  dev: true,
}).then((results) => {
  // eslint-disable-next-line no-console
  console.log(results)
})

```

#### Before

[Cloud run](https://cloud.cypress.io/projects/ypt4pf/runs/64851/properties)

Screenshot 2025-08-21 at 10 19 38 AM

Local Module API

Screenshot 2025-08-21 at 12 20 39 PM

#### After

[Cloud run](https://cloud.cypress.io/projects/ypt4pf/runs/64784/properties)

Screenshot 2025-08-21 at 10 19 08 AM

Local Module API

Screenshot 2025-08-21 at 12 15 16 PM

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/lib/util.js [hunk 1]
```diff
@@ -411,17 +409,16 @@ const util = {
...
-
-      return os.release()
+      return si.osInfo()
+      .then((osInfo) => {
+        if (osInfo.distro && osInfo.release) {
+          return `${osInfo.distro} - ${osInfo.release}`
+        }
+
+        return os.release()
+      }).catch(() => {
```
Comment (AtofStryker) [inline cli/lib/util.js:419]: likely could be a `finally` but not worth the effort to test

**Review by AtofStryker — APPROVED** [review]
