### PR TITLE
fix: retry instance creation when the Cloud request fails

### LINKED ISSUE #31002: Revert logic for instance call failures so that they retry again (after Cloud updates)
### What would you like?

Revert or enhance logic from https://github.com/cypress-io/cypress/pull/30697 to retry after the Cloud updates this endpoint to be retry-able

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/31002

### Additional details
Retrying the request to create an instance during recorded or parallel runs was disabled in 13.16.1 to prevent false negative test results, as specs could be skipped if that request was retried. Retrying this request will no longer result in skipped specs. This is a manual revert of https://github.com/cypress-io/cypress/pull/30697, with error message modifications left intact.

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: system-tests/__snapshots__/record_spec.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ exports['e2e record passing passes 1'] = `
                                                                                                     
   Running:  record_error.cy.js                                                              (1 of 4)
   Estimated: X second(s)
+Still waiting to connect to Chrome, retrying in X second(s)(attempt 18/62)
```
Comment (AtofStryker) [inline system-tests/__snapshots__/record_spec.js]: should this diff be checked in?

Comment (cacieprins) [reply system-tests/__snapshots__/record_spec.js]: resolved in https://github.com/cypress-io/cypress/pull/31019/commits/4e778fa8a782700c693c40f6b6bf9e5bfb508cb1

**Review by AtofStryker — APPROVED** [review]

**Review by mschile — APPROVED** [review]
