### PR TITLE
Handle --project "" command line argument

### LINKED ISSUE #7743: empty --project "" string crashes Cypress NPM CLI
4.8.0 and develop

```
~/git/cypress on develop
$ yarn dev --project ''
yarn run v1.22.4
$ node ./scripts/start.js --project ''
s.indexOf is not a function
TypeError: s.indexOf is not a function
    at hasStrayEndQuote (/Users/gleb/git/cypress/packages/server/lib/util/args.js:20:21)
    at normalizeBackslash (/Users/gleb/git/cypress/packages/server/lib/util/args.js:30:7)
    at /Users/gleb/git/cypress/packages/server/lib/util/args.js:47:27
    at Array.forEach (<anonymous>)
    at normalizeBackslashes (/Users/gleb/git/cypress/packages/server/lib/util/args.js:45:18)
    at Object.toObject (/Users/gleb/git/cypress/packages/server/lib/util/args.js:277:15)
    at Object.start (/Users/gleb/git/cypress/packages/server/lib/cypress.js:117:27)
    at launchOrFork (/Users/gleb/git/cypress/packages/server/index.js:49:45)
    at Object.<anonymous> (/Users/gleb/git/cypress/packages/server/index.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/gleb/git/cypress/scripts/start.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Similarly, when using Cypress NPM module API

```
const cypress = require('cypress')
cypress.run({
  project: ''
})
// crash
```

The empty string params are common when interfacing with other systems, like github actions https://github.com/cypress-io/github-action/pull/163

### PR DESCRIPTION
**Pull request by bahmutov**
- Closes #7743

### User facing changelog

- `cypress run` will no longer crash when provided an empty string to the `--project` flag.

### Additional details

Our string normalization did not check if the parameter is a string before proceeding. This fix makes it more robust.

### How has the user experience changed?

No crashing

### PR Tasks

- [x] Have tests been added/updated?
  * [x] test `args` normalize method and related functions
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
So, what happens if I pass `--project ''`, because this is not technically a valid project? 

I see it's no longer crashing, but when I tried running it within the Cypress repo `yarn cypress:run --project ''` it opened Cypress in global mode - did not do `cypress run` behavior at all. I dunno if that'a a quirk from it being `--dev` locally or not.

**Comment by flotwig** [comment]
Yeah, `yarn cypress:run --project ''` seems to open Cypress in global mode. I'd expect it to throw an error about how project can't be an empty string.

**Review by flotwig — COMMENTED** [review]
Yeah, `yarn cypress:run --project ''` seems to open Cypress in global mode. I'd expect it to throw an error about how project can't be an empty string.

**Comment by bahmutov** [comment]
@flotwig right now if you install Cypress v4.8.0 (not running it from the monorepo's root) you get a crash

```
~/git/line-height-picker on visual-testing*
$ npx cypress run --project ''
s.indexOf is not a function
TypeError: s.indexOf is not a function
    at hasStrayEndQuote (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:20:21)
    at normalizeBackslash (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:30:7)
    at /Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:47:27
    at Array.forEach (<anonymous>)
    at normalizeBackslashes (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:45:18)
    at Object.toObject (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/args.js:277:15)
    at Object.start (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/cypress.js:117:27)
    at launchOrFork (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/index.js:53:45)
    at Object.<anonymous> (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/packages/server/index.js:56:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/Library/Caches/Cypress/4.8.0/Cypress.app/Contents/Resources/app/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5842:12)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5849:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
    at electron/js2c/browser_init.js:87:10
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:699:15)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1038:10)
    at internal/main/run_main_module.js:17:11
```

Same with using NPM module 

```js
cypress.run({
  project: ''
})
```

So at least it won't crash any more.

If you want to open in global mode you have to be explicit `--project false`

Screen Shot 2020-06-18 at 2 19 47 PM

**Comment by flotwig** [comment]
@bahmutov `cypress run --project ''` does open it in global mode for me. I don't see how this is better than crashing, since it's still unexpected behavior.

Can you add whatever validation is needed to make it exit with an error if the project path is empty? Or maybe figure out why `--project ''` launches it in open mode and fix that?

**Comment by bahmutov** [comment]
So is the final consensus due to more and more unexpected behavior found the following:

- `npx cypress run --project ''` should error and exit (right now it crashes)
- `npx cypress run --project false` should error and exit (right now it _opens GUI in global mode and waits_)

File: cli/lib/errors.js [hunk 1]
```diff
@@ -9,13 +9,36 @@ const state = require('./tasks/state')
...
+  description: 'Unknown Cypress CLI error',
+  solution: genericErrorSolution,
+}
+
+const invalidRunProjectPath = {
+  description: 'Invalid --project path',
+  solution: stripIndent`
+    Provide valid project path.
+
+    Read our documentation for ${chalk.cyan('cypress run')} command at:
```
Comment (jennifer-shehane) [inline cli/lib/errors.js:36]:
```suggestion
    Please provide a valid project path.

    Learn more about ${chalk.cyan('cypress run')} at:
```

File: cli/lib/errors.js [hunk 2]
```diff
@@ -9,13 +9,36 @@ const state = require('./tasks/state')
 
 const docsUrl = 'https://on.cypress.io'
 const requiredDependenciesUrl = `${docsUrl}/required-dependencies`
+const runDocumentationUrl = `${docsUrl}/command-line#cypress-run`
```
Comment (jennifer-shehane) [inline cli/lib/errors.js:12]: This should be a new on link, since the hashes could change - this link would break.

File: cli/test/lib/cypress_spec.js [hunk 3]
```diff
@@ -147,5 +147,17 @@ describe('cypress', function () {
...
+    it('rejects if project is an empty string', () => {
+      return expect(cypress.run({ project: '' })).to.be.rejected
+    })
+
+    it('rejects if project is true', () => {
+      return expect(cypress.run({ project: true })).to.be.rejected
+    })
+
+    it('rejects if project is false', () => {
+      return expect(cypress.run({ project: true })).to.be.rejected
```
Comment (jennifer-shehane) [inline cli/test/lib/cypress_spec.js:160]: 😝 

```suggestion
      return expect(cypress.run({ project: false })).to.be.rejected
```

**Review by jennifer-shehane — DISMISSED** [review]

File: cli/lib/errors.js (hunk 2 above)
Comment (bahmutov) [reply cli/lib/errors.js:12]: But the link would still go to `cypress run` CLI page, right. So it would not be that bad I feel

File: cli/test/lib/cypress_spec.js (hunk 3 above)
Comment (bahmutov) [reply cli/test/lib/cypress_spec.js:160]: ughh

File: cli/lib/errors.js (hunk 2 above)
Comment (bahmutov) [inline cli/lib/errors.js:12]:
```suggestion
const runDocumentationUrl = `${docsUrl}/cypress-run`
```

Comment (bahmutov) [reply cli/lib/errors.js:12]: Adding this redirect in https://github.com/cypress-io/cypress-services/pull/2714

Comment (bahmutov) [reply cli/lib/errors.js]: Updated, adding redirects in https://github.com/cypress-io/cypress-services/pull/2714

**Comment by flotwig** [comment]
@bahmutov after pulling your changes down and rebuilding cli, `yarn cypress:run --project ''` still opens cypress in global mode for me

**Comment by flotwig** [comment]
```
yarn run v1.19.1
$ yarn ensure-deps
$ ./scripts/ensure-dependencies.sh
success Folder in sync.
$ node $(yarn bin cypress) run --dev --project ''
  cypress:cli:cli cli starts with arguments ["/home/flotwig/.n/bin/node","/home/flotwig/Projects/cypress/cypress/node_modules/.bin/cypress","run","--dev","--project",""] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +1ms
  cypress:cli:cli running Cypress with args [ Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object: null prototype], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 19, exit: true, dev: true, project: '' } ] +1ms
  cypress:cli:cli variable-length opts parsed { args: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/node_modules/.bin/cypress', 'run', '--dev', '--project', '' ], opts: Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object: null prototype], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 19, exit: true, dev: true, project: '' } } +73ms
  cypress:cli parsed cli options { dev: true, project: '' } +76ms
  cypress:cli:run processing run options { dev: true, project: '', key: null, spec: null, reporter: null, reporterOptions: null } +0ms
  cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY +0ms
  cypress:cli:run run to spawn.start args ["--run-project",""] +0ms
  cypress:cli DISPLAY environment variable is set to :1 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli 
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +0ms
  cypress:cli in dev mode the args became [ '/home/flotwig/Projects/cypress/cypress/scripts/start.js', '--', '--run-project', '', '--cwd', '/home/flotwig/Projects/cypress/cypress' ] +1ms
  cypress:cli passing DISPLAY :1 +3ms
  cypress:cli spawning Cypress with executable: node +0ms
  cypress:cli spawn args [ '/home/flotwig/Projects/cypress/cypress/scripts/start.js', '--', '--run-project', '', '--cwd', '/home/flotwig/Projects/cypress/cypress' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +0ms
  cypress:cli piping child STDERR to process STDERR +3ms
  cypress:ts register TypeScript project /home/flotwig/Projects/cypress/cypress/packages/ts/tsconfig.json fast? true +0ms
  cypress:server:util:node_options NODE_OPTIONS check passed, not forking { NODE_OPTIONS: '--max-http-header-size=1048576 --http-parser=legacy' } +0ms
  cypress:server:util:node_options not restoring NODE_OPTIONS since not yet in Electron +2ms
  cypress:server environment error Cannot read property 'commandLine' of undefined +0ms
  cypress:server:cypress starting cypress with argv [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js', '--', '--run-project', '', '--cwd', '/home/flotwig/Projects/cypress/cypress' ] +0ms
  cypress:server:args argv array: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js', '--run-project', '--cwd', '/home/flotwig/Projects/cypress/cypress' ] +0ms
  cypress:server:args argv parsed: { _: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js' ], runProject: true, cwd: '/home/flotwig/Projects/cypress/cypress', invokedFromCli: true } +3ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js' ], cwd: '/home/flotwig/Projects/cypress/cypress', invokedFromCli: true, config: {} } +1ms
  cypress:server:args argv options: { _: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js' ], cwd: '/home/flotwig/Projects/cypress/cypress', invokedFromCli: true, config: {} } +1ms
  cypress:server:cypress from argv [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js', '--run-project', '--cwd', '/home/flotwig/Projects/cypress/cypress' ] got options { _: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js' ], cwd: '/home/flotwig/Projects/cypress/cypress', invokedFromCli: true, config: {} } +6ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development +0ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development +0ms
  cypress:server:appdata symlink folder from /home/flotwig/.config/Cypress/cy to /home/flotwig/Projects/cypress/cypress/packages/server/.cy +0ms
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/flotwig/.n/bin/node', '/home/flotwig/Projects/cypress/cypress/scripts/start.js' ], cwd: '/home/flotwig/Projects/cypress/cypress', invokedFromCli: true, config: {} } +12ms
  cypress:server:cypress starting Electron +0ms
  cypress:server:cypress electron open arguments [ '--config={}', '--cwd=/home/flotwig/Projects/cypress/cypress' ] +9ms
  cypress:electron opening . +0ms
  cypress:electron appPath /home/flotwig/Projects/cypress/cypress/packages/server +1ms
  cypress:electron dest path /home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/resources/app +0ms
  cypress:electron appPath exists /home/flotwig/Projects/cypress/cypress/packages/server +0ms
  cypress:electron making symlink from /home/flotwig/Projects/cypress/cypress/packages/server to /home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/resources/app of type dir +0ms
  cypress:electron spawning /home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress with args [
  '--max-http-header-size=1048576 --http-parser=legacy',
  '--config={}',
  '--cwd=/home/flotwig/Projects/cypress/cypress'
] +1ms
Gtk-Message: 12:18:15.026: Failed to load module "appmenu-gtk-module"
  cypress:ts register TypeScript project /home/flotwig/Projects/cypress/cypress/packages/ts/tsconfig.json fast? true +0ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development/browsers +0ms
  cypress:server:util:node_options NODE_OPTIONS check passed, not forking { NODE_OPTIONS: '--max-http-header-size=1048576 --http-parser=legacy' } +0ms
  cypress:server:util:node_options restoring NODE_OPTIONS { NODE_OPTIONS: '--max-http-header-size=1048576 --http-parser=legacy', ORIGINAL_NODE_OPTIONS: undefined } +1ms
  cypress:server:cypress starting cypress with argv [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress', '--max-http-header-size=1048576 --http-parser=legacy', '--config={}', '--cwd=/home/flotwig/Projects/cypress/cypress', '--enable-logging' ] +0ms
  cypress:server:args argv array: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress', '--max-http-header-size=1048576 --http-parser=legacy', '--config={}', '--cwd=/home/flotwig/Projects/cypress/cypress', '--enable-logging' ] +0ms
  cypress:server:args argv parsed: { _: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: '{}', cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true } +3ms
  cypress:server:util:proxy found proxy environment variables {} +0ms
  cypress:server:args options { _: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true } +1ms
  cypress:server:args argv options: { _: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true } +0ms
  cypress:server:cypress from argv [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress', '--max-http-header-size=1048576 --http-parser=legacy', '--config={}', '--cwd=/home/flotwig/Projects/cypress/cypress', '--enable-logging' ] got options { _: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true } +5ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development +163ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development +1ms
  cypress:server:appdata symlink folder from /home/flotwig/.config/Cypress/cy to /home/flotwig/Projects/cypress/cypress/packages/server/.cy +0ms
  cypress:server:cypress starting in mode interactive with options { _: [ '/home/flotwig/Projects/cypress/cypress/packages/electron/dist/Cypress/Cypress' ], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true } +88ms
  cypress:server:cypress running Electron currently +0ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development +42ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development/cache +311ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '44056'     │     0      │       0        │  149.83  │    149.83    │   149.83    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '44059, 44061' │     0      │       0        │  48.72   │    48.72     │    48.72    │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '44204, 44205' │     0      │       0        │   3.46   │     3.46     │    3.46     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │      '-'       │     0      │       0        │   202    │     202      │     202     │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:server:saved_state making saved state from /home/flotwig/Projects/cypress/cypress/packages/server +0ms
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +2ms
  cypress:server:appdata path: /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +2s
  cypress:server:saved_state full state path /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:saved_state making new state file around /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file get values from /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file attempt to get lock on /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +2ms
  cypress:server:file getting lock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +6ms
  cypress:server:file read /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file read succeeded or failed for /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +5ms
  cypress:server:file attempt to unlock /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file unlock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/projects/__global__/state.json +2ms
  cypress:server:windows creating electron window with options { backgroundColor: '#dfe2e4', width: 783, height: 564, minWidth: 458, minHeight: 400, x: 1619, y: 1658, type: 'INDEX', devTools: false, trackState: { width: 'appWidth', height: 'appHeight', x: 'appX', y: 'appY', devTools: 'isAppDevToolsOpen' }, onBlur: [Function: onBlur], onFocus: [Function: onFocus], onClose: [Function: onClose], show: true, frame: true, transparent: false, icon: NativeImage {}, webPreferences: { preload: '/home/flotwig/Projects/cypress/cypress/packages/server/lib/ipc/ipc.js', partition: null, webSecurity: false, nodeIntegration: false, backgroundThrottling: false, backgroundColor: '#dfe2e4', transparent: false }, url: 'file:///home/flotwig/Projects/cypress/cypress/packages/desktop-gui/dist/index.html', contextMenu: false, recordFrameRate: null, onCrashed: [Function: onCrashed], onNewWindow: [Function: onNewWindow] } +0ms
[44056:0622/121818.265481:INFO:CONSOLE(21258)] "%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq font-weight:bold", source: cypress:////home/flotwig/Projects/cypress/cypress/node_modules/react-dom/cjs/react-dom.development.js (21258)
  cypress:server:events got request for event: on:menu:clicked, undefined +0ms
  cypress:server:events got request for event: get:options, undefined +0ms
  cypress:server:events got request for event: get:current:user, undefined +1ms
  cypress:server:file get values from /home/flotwig/.config/Cypress/cy/development/cache +416ms
  cypress:server:file attempt to get lock on /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:server:events sending ipc data { type: 'get:options', data: { id: 0.7403133670846158, data: { _: [Array], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true, onFocusTests: null, os: 'linux', version: '4.8.0' } }, originalData: { id: 0.7403133670846158, data: { _: [Array], 'max-http-header-size': '1048576 --http-parser=legacy', config: {}, cwd: '/home/flotwig/Projects/cypress/cypress', 'enable-logging': true, invokedFromCli: true, onFocusTests: [Function: onFocusTests], os: 'linux', version: '4.8.0' } } } +3ms
  cypress:server:file getting lock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +3ms
  cypress:server:file read /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:server:file read succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +1ms
  cypress:server:file attempt to unlock /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:server:file unlock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:server:events sending ipc data { type: 'get:current:user', data: { id: 0.8342733061789969, data: {} }, originalData: { id: 0.8342733061789969, data: {} } } +3ms
  cypress:server:events got request for event: get:projects, undefined +14ms
  cypress:server:file transaction for /home/flotwig/.config/Cypress/cy/development/cache +15ms
  cypress:server:events got request for event: updater:check, undefined +1ms
  cypress:server:updater checking for new version of Cypress. current version is 4.8.0 +0ms
[44740:0622/121818.406827:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
  cypress:server:file attempt to get lock on /home/flotwig/.config/Cypress/cy/development/cache +14ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://download.cypress.io/desktop.json' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'download.cypress.io', port: 443 } +0ms
  cypress:server:file getting lock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +9ms
  cypress:server:file write /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:server:file write succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +1ms
  cypress:server:file attempt to unlock /home/flotwig/.config/Cypress/cy/development/cache +1ms
  cypress:server:file unlock succeeded or failed for /home/flotwig/.config/Cypress/cy/development/cache +0ms
  cypress:network:connect got addresses { hostname: 'download.cypress.io', port: 443, addresses: [ { address: '172.67.69.12', family: 4 }, { address: '104.26.7.176', family: 4 }, { address: '104.26.6.176', family: 4 }, { address: '2606:4700:20::681a:7b0', family: 6 }, { address: '2606:4700:20::681a:6b0', family: 6 }, { address: '2606:4700:20::ac43:450c', family: 6 } ] } +14ms
  cypress:server:events sending ipc data { type: 'get:projects', data: { id: 0.8419167695395617, data: [ [Object], [Object], [Object], [Object] ] }, originalData: { id: 0.8419167695395617, data: [ [Object], [Object], [Object], [Object] ] } } +35ms
  cypress:network:agent got family { family: 4, href: 'https://download.cypress.io/desktop.json' } +19ms
  cypress:server:updater latest version of Cypress is: 4.8.0 +194ms
  cypress:server:updater new version of Cypress does not exist +0ms
  cypress:server:events sending ipc data { type: 'updater:check', data: { id: 0.9167495857203454, data: false }, originalData: { id: 0.9167495857203454, data: false } } +160ms
  cypress:server:events got request for event: get:project:statuses, [ { path: '/home/flotwig/Projects/cypress/issue-687-net-mocking/packages/driver/test', id: null }, { path: '/home/flotwig/Projects/cypress/issue-6771-tls-regression/repro', id: undefined }, { path: '/home/flotwig/Projects/cypress/test-tiny', id: undefined }, { path: '/tmp/mozilla_flotwig0', id: null } ] +36ms
  cypress:server:project get project statuses for 4 projects +0ms
  cypress:server:file get values from /home/flotwig/.config/Cypress/cy/development/cache +207ms
  cypress:server:events send error: Error: You're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get (/home/flotwig/Projects/cypress/cypress/packages/server/lib/errors.js:946:15) at /home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:71:28     at processImmediate (internal/timers.js:439:21) From previous event: at Object.ensureAuthToken (/home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:60:23) at Function.getProjectStatuses (/home/flotwig/Projects/cypress/cypress/packages/server/lib/project.js:733:17) at IpcMainImpl.handleEvent (/home/flotwig/Projects/cypress/cypress/packages/server/lib/gui/events.js:219:22) at apply (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:478:17) at IpcMainImpl.wrapper (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:5317:16)     at IpcMainImpl.emit (events.js:210:5)     at WebContents.<anonymous> (electron/js2c/browser_init.js:3853:15)     at WebContents.emit (events.js:210:5) { isCypressErr: true, type: 'NOT_LOGGED_IN', details: undefined, isApiError: true } +4ms
  cypress:server:events sending ipc data { type: 'get:project:statuses', data: { id: 0.5345095050911466, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/home/flotwig/Projects/cypress/cypress/packages/server/lib/errors.js:946:15)\n' + '    at /home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:71:28\n' + '    at processImmediate (internal/timers.js:439:21)\n' + 'From previous event:\n' + '    at Object.ensureAuthToken (/home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:60:23)\n' + '    at Function.getProjectStatuses (/home/flotwig/Projects/cypress/cypress/packages/server/lib/project.js:733:17)\n' + '    at IpcMainImpl.handleEvent (/home/flotwig/Projects/cypress/cypress/packages/server/lib/gui/events.js:219:22)\n' + '    at apply (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:478:17)\n' + '    at IpcMainImpl.wrapper (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:5317:16)\n' + '    at IpcMainImpl.emit (events.js:210:5)\n' + '    at WebContents.<anonymous> (electron/js2c/browser_init.js:3853:15)\n' + '    at WebContents.emit (events.js:210:5)', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } }, originalData: { id: 0.5345095050911466, __error: { type: 'NOT_LOGGED_IN', name: 'Error', stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' + '    at Object.get (/home/flotwig/Projects/cypress/cypress/packages/server/lib/errors.js:946:15)\n' + '    at /home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:71:28\n' + '    at processImmediate (internal/timers.js:439:21)\n' + 'From previous event:\n' + '    at Object.ensureAuthToken (/home/flotwig/Projects/cypress/cypress/packages/server/lib/user.js:60:23)\n' + '    at Function.getProjectStatuses (/home/flotwig/Projects/cypress/cypress/packages/server/lib/project.js:733:17)\n' + '    at IpcMainImpl.handleEvent (/home/flotwig/Projects/cypress/cypress/packages/server/lib/gui/events.js:219:22)\n' + '    at apply (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:478:17)\n' + '    at IpcMainImpl.wrapper (/home/flotwig/Projects/cypress/cypress/node_modules/lodash/lodash.js:5317:16)\n' + '    at IpcMainImpl.emit (events.js:210:5)\n' + '    at WebContents.<anonymous> (electron/js2c/browser_init.js:3853:15)\n' + '    at WebContents.emit (events.js:210:5)', message: "You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.', isCypressErr: true, details: undefined, isApiError: true } } } +1ms

```

**Comment by bahmutov** [comment]
@flotwig can you check again? Did you run `yarn` before trying?

Screen Shot 2020-06-22 at 12 57 48 PM

**Comment by flotwig** [comment]
PEBKAC, I swear I ran `yarn` the first time. Seems to work fine now :+1:

**Review by flotwig — APPROVED** [review]
