### PR TITLE
fix: sourcemap/stack traces for v8 snapshots

### LINKED ISSUE #22983: Ensure that Stack Traces Are Aligned when Using Snapshots
### What would you like?

Stack traces do not currently point to the right line of code in various scenarios

### Why is this needed?

To aid in troubleshooting

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #22983 

### User facing changelog

n/a

### Additional details

This PR reenables tests that were failing due to stack trace inconsistencies. Specifically, some new lines needed to be changed to be consistent. In addition, we are no longer going to be showing Cypress require stacks in error messages since we typically try to hide Cypress code from production call stacks and it's not easily possible to get the require stack to node since we are handling requires within the snapshot for Cypress code.

Originally, we were going to both fix the spacing issues *and* ensure that source maps were used to convert the stack traces to point to original files. We determined that the current tools we were using to convert the source maps were too memory intensive and since we typically hide Cypress code from consumer stacks anyway, we decided to scope out sourcemapping for now. As a result, I deleted a bunch of the code that is not currently being used around using the snapshots. I did leave the code that generates the source maps so that we can potentially use them if issues come in with stack traces that we need to convert.

### Steps to test

No real new functionality here, but the main thing is that the uncommented tests now need to pass.

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: tooling/v8-snapshot/src/setup/install-snapshot.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ function getSnapshotGenerator ({
     previousDeferred,
     previousHealthy,
     previousNoRewrite,
+    sourcemapEmbed: true,
```
Comment (ryanthemanuel) [inline tooling/v8-snapshot/src/setup/install-snapshot.ts]:
```suggestion
    // sourcemapEmbed: true,
```

File: tooling/v8-snapshot/src/setup/install-snapshot.ts [hunk 2]
```diff
@@ -60,6 +60,7 @@ function getSnapshotGenerator ({
     previousDeferred,
     previousHealthy,
     previousNoRewrite,
+    // sourcemapEmbed: true,
```
Comment (ryanthemanuel) [inline tooling/v8-snapshot/src/setup/install-snapshot.ts]: Reminder to swap this back

File: packages/packherd-require/src/sourcemap-support.ts [hunk 3]
```diff
@@ -226,18 +212,8 @@ class SourcemapSupport {
...
-
-      frame.getFunctionName = function () {
-        if (state.nextPos == null) {
-          return originalFunctionName()
-        }
-
-        return state.nextPos.name ?? originalFunctionName()
-      }
-
       frame.getFileName = function getFileName () {
```
Comment (ryanthemanuel) [inline packages/packherd-require/src/sourcemap-support.ts:215]: These changes are still necessary to get accurate line numbers for typescript files in development

File: scripts/run-postInstall.js [hunk 4]
```diff
@@ -3,7 +3,7 @@ const { execSync } = require('child_process')
 const executionEnv = process.env.CI ? 'ci' : 'local'
 
 const postInstallCommands = {
-  local: 'patch-package && yarn-deduplicate --strategy=highest && yarn clean && gulp postinstall && yarn build && yarn build-v8-snapshot-dev',
+  local: 'patch-package && yarn-deduplicate --strategy=highest && yarn clean && gulp postinstall && yarn build && DEBUG=cypress:snapgen:info yarn build-v8-snapshot-dev',
```
Comment (AtofStryker) [inline scripts/run-postInstall.js:6]: Do we intentionally want to keep the debug logs on for snapgen when we do a post install?
```suggestion
  local: 'patch-package && yarn-deduplicate --strategy=highest && yarn clean && gulp postinstall && yarn build && yarn build-v8-snapshot-dev',
```

File: tooling/v8-snapshot/src/blueprint/custom-require.js [hunk 5]
```diff
@@ -147,37 +147,27 @@ function customRequire (
...
-          //      cache, otherwise we use the module we constructed above and fill
-          //      in the exports
-          const cachedMod = require.cache[fullPath]
-
-          if (cachedMod != null) {
-            mod = cachedMod
-          } else {
-            mod.exports = exports
-          }
+      if (!snapshotting) {
```
Comment (AtofStryker) [inline tooling/v8-snapshot/src/blueprint/custom-require.js:150]: we don't we need the try/catch here any longer?

File: scripts/run-postInstall.js (hunk 4 above)
Comment (ryanthemanuel) [reply scripts/run-postInstall.js:6]: I added this so that there would be some level of progress as this was being generated. I don't want people to think that things are hanging for some reason

File: tooling/v8-snapshot/src/blueprint/custom-require.js (hunk 5 above)
Comment (ryanthemanuel) [reply tooling/v8-snapshot/src/blueprint/custom-require.js:150]: Correct. The error should actually just be thrown as normal no matter what. Previously we were adding in our own custom error message, but I think the built in one is fine (and it was breaking a system test)

File: system-tests/projects/v8-snapshot/deferred-from-healthy/app.js [hunk 6]
```diff
@@ -2,4 +2,7 @@ const healthy = require('./healthy')
 
 // This entry invokes a function on healthy which would require a deferred module to be resolved.
 // Therefore while healthy can be included in the snapshot, this entry module cannot.
+//
+// snapshotAuxiliaryData is generated by @tooling/v8-snapshot
+// eslint-disable-next-line no-undef
```
Comment (ryanthemanuel) [inline system-tests/projects/v8-snapshot/deferred-from-healthy/app.js]:
```suggestion
```

Stale comment

File: system-tests/__snapshots__/plugin_run_events_spec.ts.js [hunk 7]
```diff
@@ -167,4 +167,5 @@ The error we received was:
 
 Error: error thrown in before:spec
       [stack trace lines]
+
```
Comment (ryanthemanuel) [inline system-tests/__snapshots__/plugin_run_events_spec.ts.js:170]:
```suggestion


```

File: system-tests/test/pause_headed_exit_spec.ts [hunk 8]
```diff
@@ -17,6 +18,9 @@ describe('cy.pause() in run mode', () => {
     onSpawn: (cp) => {
       cp.stdout.on('data', (buf) => {
         if (buf.toString().includes('not exiting due to options.exit being false')) {
+          // systemTests.it spawns a new node process which then spawns the actual cypress process
+          // Killing just the new node process doesn't kill the cypress process so we find it and kill it manually
+          childProcess.execSync(`kill $(pgrep -P ${cp.pid} | awk '{print $1}')`)
```
Comment (mschile) [inline system-tests/test/pause_headed_exit_spec.ts:23]: 🎉

**Review by mschile — APPROVED** [review]

File: packages/packherd-require/src/sourcemap-support.ts [hunk 9]
```diff
@@ -226,18 +212,8 @@ class SourcemapSupport {
...
-        return pos.source
+        return pos.source || pos.name || null
```
Comment (AtofStryker) [inline packages/packherd-require/src/sourcemap-support.ts:216]:
```suggestion
        return this.getScriptNameOrSourceURL() || null
```

**Review by AtofStryker — APPROVED** [review]
