### PR TITLE
fix: v8 snapshots on windows

### LINKED ISSUE #23122: Support Windows with V8 Snapshots

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #23122

### User facing changelog

n/a 

### Additional details

This PR fixes several issues with Windows:

* the loader cache needs to be keyed off of a POSIX style path: https://github.com/cypress-io/cypress/pull/23925/files#diff-8cc8f4b0f27fb00985d9a07659dd1b6d59d5f06dccfbb7d56e1b7f9a3e85f686R654
* when recreating the __filename and __dirname values the directory needs to be converted to architecture-specific style: https://github.com/cypress-io/cypress/pull/23925/files#diff-8cc8f4b0f27fb00985d9a07659dd1b6d59d5f06dccfbb7d56e1b7f9a3e85f686R654

### Steps to test

Mainly this is tested by the existing windows tests (which are now uncommented).

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: tooling/v8-snapshot/src/blueprint/custom-require.js [hunk 1]
```diff
@@ -226,7 +226,7 @@ function resolvePathsAndParent (
   }
 
   if (snapshotting || !modulePathFromAppRoot.startsWith('.')) {
-    filename = modulePathFromAppRoot
+    filename = modulePathFromAppRoot.split('/').join(PATH_SEP)
```
Comment (ryanthemanuel) [inline tooling/v8-snapshot/src/blueprint/custom-require.js:230]:
```suggestion
    // Have to hard code / here since we can't use `path` in the snapshot
    filename = modulePathFromAppRoot.split('/').join(PATH_SEP)
```

**Review by mjhenkes — APPROVED** [review]

**Review by mschile — APPROVED** [review]
