### PR TITLE
fix(server): use correct property for spec name in CLI

### LINKED ISSUE #22304: I really miss full path in spec names in cy run report
### What would you like?

To have option to enable full path with spec name (e.g. AP/admin/customers/informationBar.ts) like it used to be before version 10, insted of just spec name (informationBar.cy.ts). Setting in cypress.config.ts would be ideal.

### Why is this needed?

I have large number of specs with identical names which are scattered over dozens of folders. Now cy run report is almost useless to me - I cannot tell whether AP/admin/customers/informationBar.ts failed or was it Vendor/responseRepresentative/informationBar.cy.ts

### Other

_No response_

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/22304

### User facing changelog

Improve the output of `cypress run` by showing the path of a spec, not just the name.

### Additional details

In Cypress 9 we would show the spec name minus the `integrationFolder` in the run report. Here's an image from [this user](https://github.com/cypress-io/cypress/issues/22304#issuecomment-1155301230) showing left (Cypress 10, now) right (Cypress 9).

image

When we merged `integrationFolder` and `testFiles` into `specPattern`, we DID account for this, but we are using the wrong property in the report - `baseName` is the spec name (no directory). We want `relativeToCommonRoot`, which is the closest thing to Cypress 9 - remove the common prefix (like `cypress/e2e`) and just show the spec path from there.

### Steps to test

You can do

```sh
cd packages/frontend-shared
yarn cypress:run:ct --config video=false --spec "**/Co*"       
```

in the monorepo to see the difference. Or look below. 

### How has the user experience changed?

Including screenshots and text. Left is BEFORE (develop) right is AFTER (this branch). The main difference is the **report** - the specs names are now all unique, including the file path, not just the file name.

image

image

Example from monorepo:

```sh
cd packages/frontend-shared
yarn cypress:run:ct --config video=false --spec "**/Co*"       
```

## Before

```sh
yarn run v1.22.11
$ cross-env TZ=America/New_York node ../../scripts/cypress run --component --project . --config video=false --spec '**/Co*'

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.7.0                                                                         │
  │ Browser:        Electron 102 (headless)                                                        │
  │ Node Version:   v16.17.0 (/home/lachlan/.nvm/versions/node/v16.17.0/bin/node)                  │
  │ Specs:          4 found (CodeTag.cy.tsx, Collapsible.cy.tsx, CopyText.cy.tsx, CopyButton.cy.ts │
  │                 x)                                                                             │
  │ Searched:       **/Co*                                                                         │
  │ Experiments:    experimentalSingleTabRunMode=true                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  CodeTag.cy.tsx                                                                  (1 of 4)


  <CodeTag />
    ✓ looks good in code
    ✓ displays colored code
    ✓ displays colored code on a background


  3 passing (207ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     CodeTag.cy.tsx                                                                   │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  Collapsible.cy.tsx                                                              (2 of 4)


  <Collapsible />
    ✓ renders the target and content slots (262ms)
    ✓ does not render default slot if lazy (222ms)
    ✓ overflows properly (159ms)
    ✓ does not toggle when clicking on content (223ms)
    ✓ playground
    initiallyOpen
      ✓ defaults to closed
      ✓ can be set to open initially
    slotProps
      toggle
        ✓ passes the toggle slot prop to the default slot (217ms)
      open
        ✓ passes the open slot props to the header and default slots (152ms)


  9 passing (1s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      9                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     Collapsible.cy.tsx                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  CopyText.cy.tsx                                                                 (3 of 4)


  <CopyText />
    ✓ renders without overflow
    ✓ overflows nicely


  2 passing (231ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     CopyText.cy.tsx                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  CopyButton.cy.tsx                                                               (4 of 4)


  <CopyButton />
    ✓ copies text to clipboard (288ms)
    ✓ noIcon hides the icon


  2 passing (361ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     CopyButton.cy.tsx                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  CodeTag.cy.tsx                           204ms        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  Collapsible.cy.tsx                       00:01        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  CopyText.cy.tsx                          227ms        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  CopyButton.cy.tsx                        357ms        2        2        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:02       16       16        -        -        -  


```

## After

```
==================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.7.0                                                                         │
  │ Browser:        Electron 102 (headless)                                                        │
  │ Node Version:   v16.17.0 (/home/lachlan/.nvm/versions/node/v16.17.0/bin/node)                  │
  │ Specs:          4 found (components/CodeTag.cy.tsx, components/Collapsible.cy.tsx, components/ │
  │                 CopyText.cy.tsx, gql-components/CopyButton.cy.tsx)                             │
  │ Searched:       **/Co*                                                                         │
  │ Experiments:    experimentalSingleTabRunMode=true                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  components/CodeTag.cy.tsx                                                       (1 of 4)


  <CodeTag />
    ✓ looks good in code
    ✓ displays colored code
    ✓ displays colored code on a background


  3 passing (187ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     components/CodeTag.cy.tsx                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  components/Collapsible.cy.tsx                                                   (2 of 4)


  <Collapsible />
    ✓ renders the target and content slots (262ms)
    ✓ does not render default slot if lazy (217ms)
    ✓ overflows properly (157ms)
    ✓ does not toggle when clicking on content (222ms)
    ✓ playground
    initiallyOpen
      ✓ defaults to closed
      ✓ can be set to open initially
    slotProps
      toggle
        ✓ passes the toggle slot prop to the default slot (205ms)
      open
        ✓ passes the open slot props to the header and default slots (140ms)


  9 passing (1s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      9                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     components/Collapsible.cy.tsx                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  components/CopyText.cy.tsx                                                      (3 of 4)


  <CopyText />
    ✓ renders without overflow
    ✓ overflows nicely


  2 passing (232ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     components/CopyText.cy.tsx                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  gql-components/CopyButton.cy.tsx                                                (4 of 4)


  <CopyButton />
    ✓ copies text to clipboard (484ms)
    ✓ noIcon hides the icon


  2 passing (561ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     gql-components/CopyButton.cy.tsx                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


==================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  components/CodeTag.cy.tsx                186ms        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  components/Collapsible.cy.tsx            00:01        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  components/CopyText.cy.tsx               229ms        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  gql-components/CopyButton.cy.tsx         557ms        2        2        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:02       16       16        -        -        -  

Done in 30.50s.
$                                                                                     issue-22304


```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by Narretz** [comment]
@lmiller1990 thanks! Tested the change locally and it's great

File: system-tests/__snapshots__/stdout_spec.js [hunk 1]
```diff
@@ -275,15 +275,15 @@ exports['e2e stdout displays fullname of nested specfile 1'] = `
   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
   │ Cypress:    1.2.3                                                                              │
   │ Browser:    FooBrowser 88                                                                      │
-  │ Specs:      3 found (spec.cy.js, stdout_specfile.cy.js, stdout_specfile_display_spec_with_a_re │
-  │             ally_long_name_that_never_has_a_line_break_or_new_line.cy.js)                      │
-  │ Searched:   cypress/e2e/nested-1/nested-2/nested-3/*                                           │
+  │ Specs:      4 found (spec.cy.js, stdout_specfile.cy.js, stdout_specfile_display_spec_with_a_re │
```
Comment (lmiller1990) [inline system-tests/__snapshots__/stdout_spec.js:278]: I was expecting a lot of snapshots to break but no - the directory structure for all our system-tests projects is very flat so we didn't notice when this regressed - only this one had any changes.

I guess this one snapshot got lost/missed in the original review that caused this regression in the first place.

**Review by rachelruderman — APPROVED** [review]
Nicely done!

**Review by chrisbreiding — APPROVED** [review]
