### PR TITLE
fix: the shadow root container element is ignored when clicking an element in it.

### LINKED ISSUE #18008: Elements inside shadow dom are hidden by its host (causing them to not be interactable)
### Current behavior

Currently when trying to click an element inside slotted shadow DOM Cypress incorrectly believes the element is covered by its host element.

```
Timed out retrying after 4050ms: cy.click() failed because this element:

<button data-test-id="my-button">...</button>

is being covered by another element:

<my-custom-element id="element">Click me!</my-custom-element>

Fix this problem, or use {force: true} to disable error checking.Learn more
```

### Desired behavior

Cypress should correctly be able to figure out if the shadow dom element is a descendent of the element that is covering it.

### Test code to reproduce

https://github.com/TomCaserta/cypress-shadow-reproduction 

You can find all the test case code in the `index.html` file (which can be run via `npm run start`). The failing tests can be found in the `error.spec.js` file.

### Cypress Version

8.3.1

### Other

All cypress versions prior to 8.3.1 (and after Shadow DOM support was added) have been problematic.

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #18008

### User facing changelog

- Shadow DOM elements are no longer falsely reported as hidden by their host

### Additional details
- Why was this change necessary? => When clicking an element inside a custom element, it shows the error message that it is covered by its custom element container. 
- What is affected by this change? => N/A

### Any implementation details to explain?
* I added a condition to bypass error when the element is inside a shadow root and covered by it.
* It fixes the "covering" problem. But it doesn't solve "event messages are not sent" problem (#17531). I added a new fixture for later tests. 

### How has the user experience changed?

**Before:**

image

**After:**

No Error.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Review by tbiethman — DISMISSED** [review]

File: packages/driver/src/cy/ensures.ts [hunk 1]
```diff
@@ -331,6 +331,15 @@ export default {
       const cmd = state('current').get('name')
 
       if (!$dom.isDescendent($el1, $el2)) {
+        // https://github.com/cypress-io/cypress/issues/18008
+        // when an element inside a shadow root is covered by its shadow host
+        if (
+          $dom.isWithinShadowRoot($el1.get(0)) &&
+          $el1.get(0).getRootNode() === $el2.get(0).shadowRoot
```
Comment (chrisbreiding) [inline packages/driver/src/cy/ensures.ts:338]:
```suggestion
          $el1.get(0).getRootNode() === $el2?.get(0).shadowRoot
```

`$el2` could possibly be undefined, in which case this would throw an exception.

File: packages/driver/cypress/fixtures/shadow-dom-button.html [hunk 2]
```diff
@@ -0,0 +1,38 @@
+<!DOCTYPE html>
```
Comment (chrisbreiding) [inline packages/driver/cypress/fixtures/shadow-dom-button.html:1]: Any reason to have this be a separate file and not add it to `fixtures/shadow-dom.html`?

File: packages/driver/cypress/integration/commands/actions/click_spec.js [hunk 3]
```diff
@@ -3985,6 +3985,13 @@ describe('shadow dom', () => {
 
     cy.get('#shadow-element-1').click()
   })
+
+  // https://github.com/cypress-io/cypress/issues/18008
+  it('ignores the covering shadow host', () => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/commands/actions/click_spec.js:3990]:
```suggestion
  it('does not fail actionability check when element is covered by its shadow host', () => {
```

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/integration/commands/actions/click_spec.js (hunk 3 above)
Comment (sainthkh) [reply packages/driver/cypress/integration/commands/actions/click_spec.js:3990]: Done

File: packages/driver/src/cy/ensures.ts (hunk 1 above)
Comment (sainthkh) [reply packages/driver/src/cy/ensures.ts:338]: Done

File: packages/driver/cypress/fixtures/shadow-dom-button.html (hunk 2 above)
Comment (sainthkh) [reply packages/driver/cypress/fixtures/shadow-dom-button.html:1]: There are 2 reasons:

1. `shadow-dom.html` creates shadow elements with `innerHTML` but it is a bit unintuitive in this case because we need to attach a listener in the constructor. We need to add another version of test element and it might make the fixture a bit cluttered.
2. As I said above, this fixture can be used for other failures like #17531.

**Review by chrisbreiding — APPROVED** [review]

**Review by tbiethman — APPROVED** [review]
