### PR TITLE
Fix using Chromium installed via snapcraft

### LINKED ISSUE #7020: Launch Hanging on Ubuntu when `snap` version of Chromium is installed
### Current behavior:

`cypress open` does not open Cypress.
`cypress run` just seems to hang.

Logs:
https://pastebin.com/ULZwQEj8

Snapshot of behavior and logs:

System:
image

### Desired behavior:

Should be able to run tests.

### Test code to reproduce

As this is happening prior to Cypress running I don't think its anything I can give reproduction steps for.

`DEBUG=* $(npm bin)/cypress open`
`DEBUG=* $(npm bin)/cypress run`

Are the commands I am running.

### Versions

v4.3.0 and v4.4.0

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #7020 

### User facing changelog

- Fixed a bug preventing Cypress from launching on systems where Chromium was installed via Snapcraft.

### Additional details

- in `cypress open`, project would never load and spinner would run forever. on `cypress run`, no output is printed to the console (browser detection runs before anything is printed)
- mysteriously, execa would hang on --version when used with the snap
- switched to using cp instead since execa is only really used for windows benefits and it works fine
- added a 5s timeout to getVersionString since it should never take that long
- [x] still having issue due to snap sandboxing, cannot create browser profile: https://github.com/cypress-io/cypress/issues/7020#issuecomment-614737938
	- instead of writing to the usual appdata dir, write to `$HOME/snap/chromium/current/Cypress` since that's the only place this chromium can write
	- [x] tested locally, would also like @Bkucera to test on his system

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/launcher/lib/linux/index.ts [hunk 1]
```diff
@@ -36,22 +44,30 @@ function getLinuxBrowser (
     throw notInstalledErr(binary)
   }
 
+  const maybeSetSnapProfilePath = (versionString: string) => {
+    if (os.platform() === 'linux' && name === 'chromium' && versionString.endsWith('snap')) {
+      // when running as a snap, chromium can only write to one directory
+      // @see https://cs.chromium.org/chromium/src/chrome/installer/linux/snap/snapcraft.yaml.in?l=59-61&rcl=6fb05bb3738f37392dde9cd2783637f09d5aa3f4
```
Comment (flotwig) [inline packages/launcher/lib/linux/index.ts:50]: the dir this yaml file indicates actually isn't writable from inside the sandbox - but this `~/snap/chromium/current` symlink is

**Comment by Bkucera** [comment]
verified this works for me. After installing snap chromium cypress hangs. with these changes it's fixed. :+1:

File: packages/launcher/lib/linux/index.ts [hunk 2]
```diff
@@ -36,22 +44,30 @@ function getLinuxBrowser (
     throw notInstalledErr(binary)
   }
 
+  const maybeSetSnapProfilePath = (versionString: string) => {
+    if (os.platform() === 'linux' && name === 'chromium' && versionString.endsWith('snap')) {
+      // when running as a snap, chromium can only write to certain directories
+      // @see https://github.com/cypress-io/cypress/issues/7020
+      foundBrowser.profilePath = path.join(os.homedir(), 'snap', 'chromium', 'current')
```
Comment (jennifer-shehane) [inline packages/launcher/lib/linux/index.ts:51]: It'd be great to also add a debug log here to know we're modifying the path because of this.
