### PR TITLE
collect GitLab pipeline id and url for #2343

### LINKED ISSUE #2343: Missing or incorrect GitLab environment variables for parallelization
Cypress 3.1.0

I created a GitLab project https://gitlab.com/bahmutov/kitchensink (branch `3.1.0`) and ran it with `--parallel` flag

The config file defined 3 jobs

```
1x-electron:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - /root/.npm
    - /root/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - $(npm bin)/print-env CI
    - npm run start:ci &
    - npm run e2e:record -- --parallel --group 1x-electron

2x-electron-1:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - /root/.npm
    - /root/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - $(npm bin)/print-env CI
    - npm run start:ci &
    - npm run e2e:record -- --parallel --group 2x-electron

2x-electron-2:
  image: cypress/base:10
  stage: test

  # cache NPM modules using branch name
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - /root/.npm
    - /root/.cache

  before_script:
    - npm ci
    - npm run cy:verify

  script:
    - $(npm bin)/print-env CI
    - npm run start:ci &
    - npm run e2e:record -- --parallel --group 2x-electron
```

## problem 1

Alls builds created separate runs in the dashboard

screen shot 2018-08-14 at 2 08 49 pm

## problem 2

Also, the branch is missing, see https://dashboard.cypress.io/#/projects/4b7344/runs/2061/specs

screen shot 2018-08-14 at 2 04 55 pm

## GitLab environment variables

GitLab injects the following environment variables during build: https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables

I printed all variables that start with `CI_` and here they are from several jobs in the same pipeline https://gitlab.com/bahmutov/kitchensink/pipelines/27836952

screen shot 2018-08-14 at 2 11 33 pm

### 1ex-electron

https://gitlab.com/bahmutov/kitchensink/-/jobs/89078654

```
$ $(npm bin)/print-env CI
CI=true
CI_BUILD_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_BUILD_ID=89078654
CI_BUILD_NAME=1x-electron
CI_BUILD_REF=f8fc41d3e35203497326365d3a8e264fa207226d
CI_BUILD_REF_NAME=3.1.0
CI_BUILD_REF_SLUG=3-1-0
CI_BUILD_STAGE=test
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_COMMIT_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_COMMIT_DESCRIPTION=
CI_COMMIT_MESSAGE=it is ci-build-id

CI_COMMIT_REF_NAME=3.1.0
CI_COMMIT_REF_SLUG=3-1-0
CI_COMMIT_SHA=f8fc41d3e35203497326365d3a8e264fa207226d
CI_COMMIT_TITLE=it is ci-build-id
CI_CONFIG_PATH=.gitlab-ci.yml
CI_DISPOSABLE_ENVIRONMENT=true
CI_JOB_ID=89078654
CI_JOB_NAME=1x-electron
CI_JOB_STAGE=test
CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_JOB_URL=https://gitlab.com/bahmutov/kitchensink/-/jobs/89078654
CI_PIPELINE_ID=27836952
CI_PIPELINE_IID=11
CI_PIPELINE_SOURCE=push
CI_PIPELINE_URL=https://gitlab.com/bahmutov/kitchensink/pipelines/27836952
CI_PROJECT_DIR=/builds/bahmutov/kitchensink
CI_PROJECT_ID=7930861
CI_PROJECT_NAME=kitchensink
CI_PROJECT_NAMESPACE=bahmutov
CI_PROJECT_PATH=bahmutov/kitchensink
CI_PROJECT_PATH_SLUG=bahmutov-kitchensink
CI_PROJECT_URL=https://gitlab.com/bahmutov/kitchensink
CI_PROJECT_VISIBILITY=public
CI_REGISTRY=registry.gitlab.com
CI_REGISTRY_IMAGE=registry.gitlab.com/bahmutov/kitchensink
CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
CI_REGISTRY_USER=gitlab-ci-token
CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/bahmutov/kitchensink.git
CI_RUNNER_DESCRIPTION=shared-runners-manager-3.gitlab.com
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_RUNNER_ID=44028
CI_RUNNER_REVISION=081978aa
CI_RUNNER_TAGS=docker, east-c, gce, git-annex, linux, mongo, mysql, postgres, ruby, shared
CI_RUNNER_VERSION=11.1.0
CI_SERVER=yes
CI_SERVER_NAME=GitLab
CI_SERVER_REVISION=7996ef5
CI_SERVER_TLS_CA_FILE=/builds/bahmutov/kitchensink.tmp/CI_SERVER_TLS_CA_FILE
CI_SERVER_VERSION=11.2.0-rc2-ee
```

### 2x-electron-1

https://gitlab.com/bahmutov/kitchensink/-/jobs/89078655

```
CI=true
CI_BUILD_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_BUILD_ID=89078655
CI_BUILD_NAME=2x-electron-1
CI_BUILD_REF=f8fc41d3e35203497326365d3a8e264fa207226d
CI_BUILD_REF_NAME=3.1.0
CI_BUILD_REF_SLUG=3-1-0
CI_BUILD_STAGE=test
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_COMMIT_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_COMMIT_DESCRIPTION=
CI_COMMIT_MESSAGE=it is ci-build-id

CI_COMMIT_REF_NAME=3.1.0
CI_COMMIT_REF_SLUG=3-1-0
CI_COMMIT_SHA=f8fc41d3e35203497326365d3a8e264fa207226d
CI_COMMIT_TITLE=it is ci-build-id
CI_CONFIG_PATH=.gitlab-ci.yml
CI_DISPOSABLE_ENVIRONMENT=true
CI_JOB_ID=89078655
CI_JOB_NAME=2x-electron-1
CI_JOB_STAGE=test
CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_JOB_URL=https://gitlab.com/bahmutov/kitchensink/-/jobs/89078655
CI_PIPELINE_ID=27836952
CI_PIPELINE_IID=11
CI_PIPELINE_SOURCE=push
CI_PIPELINE_URL=https://gitlab.com/bahmutov/kitchensink/pipelines/27836952
CI_PROJECT_DIR=/builds/bahmutov/kitchensink
CI_PROJECT_ID=7930861
CI_PROJECT_NAME=kitchensink
CI_PROJECT_NAMESPACE=bahmutov
CI_PROJECT_PATH=bahmutov/kitchensink
CI_PROJECT_PATH_SLUG=bahmutov-kitchensink
CI_PROJECT_URL=https://gitlab.com/bahmutov/kitchensink
CI_PROJECT_VISIBILITY=public
CI_REGISTRY=registry.gitlab.com
CI_REGISTRY_IMAGE=registry.gitlab.com/bahmutov/kitchensink
CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
CI_REGISTRY_USER=gitlab-ci-token
CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/bahmutov/kitchensink.git
CI_RUNNER_DESCRIPTION=shared-runners-manager-5.gitlab.com
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_RUNNER_ID=380986
CI_RUNNER_REVISION=081978aa
CI_RUNNER_TAGS=gce, docker
CI_RUNNER_VERSION=11.1.0
CI_SERVER=yes
CI_SERVER_NAME=GitLab
CI_SERVER_REVISION=7996ef5
CI_SERVER_TLS_CA_FILE=/builds/bahmutov/kitchensink.tmp/CI_SERVER_TLS_CA_FILE
CI_SERVER_VERSION=11.2.0-rc2-ee
```

### 2x-electron-2

https://gitlab.com/bahmutov/kitchensink/-/jobs/89078656

```
CI=true
CI_BUILD_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_BUILD_ID=89078656
CI_BUILD_NAME=2x-electron-2
CI_BUILD_REF=f8fc41d3e35203497326365d3a8e264fa207226d
CI_BUILD_REF_NAME=3.1.0
CI_BUILD_REF_SLUG=3-1-0
CI_BUILD_STAGE=test
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_COMMIT_BEFORE_SHA=32086b3a147d81e186c4131f6372844273c8e204
CI_COMMIT_DESCRIPTION=
CI_COMMIT_MESSAGE=it is ci-build-id

CI_COMMIT_REF_NAME=3.1.0
CI_COMMIT_REF_SLUG=3-1-0
CI_COMMIT_SHA=f8fc41d3e35203497326365d3a8e264fa207226d
CI_COMMIT_TITLE=it is ci-build-id
CI_CONFIG_PATH=.gitlab-ci.yml
CI_DISPOSABLE_ENVIRONMENT=true
CI_JOB_ID=89078656
CI_JOB_NAME=2x-electron-2
CI_JOB_STAGE=test
CI_JOB_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_JOB_URL=https://gitlab.com/bahmutov/kitchensink/-/jobs/89078656
CI_PIPELINE_ID=27836952
CI_PIPELINE_IID=11
CI_PIPELINE_SOURCE=push
CI_PIPELINE_URL=https://gitlab.com/bahmutov/kitchensink/pipelines/27836952
CI_PROJECT_DIR=/builds/bahmutov/kitchensink
CI_PROJECT_ID=7930861
CI_PROJECT_NAME=kitchensink
CI_PROJECT_NAMESPACE=bahmutov
CI_PROJECT_PATH=bahmutov/kitchensink
CI_PROJECT_PATH_SLUG=bahmutov-kitchensink
CI_PROJECT_URL=https://gitlab.com/bahmutov/kitchensink
CI_PROJECT_VISIBILITY=public
CI_REGISTRY=registry.gitlab.com
CI_REGISTRY_IMAGE=registry.gitlab.com/bahmutov/kitchensink
CI_REGISTRY_PASSWORD=xxxxxxxxxxxxxxxxxxxx
CI_REGISTRY_USER=gitlab-ci-token
CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/bahmutov/kitchensink.git
CI_RUNNER_DESCRIPTION=shared-runners-manager-5.gitlab.com
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_RUNNER_ID=380986
CI_RUNNER_REVISION=081978aa
CI_RUNNER_TAGS=gce, docker
CI_RUNNER_VERSION=11.1.0
CI_SERVER=yes
CI_SERVER_NAME=GitLab
CI_SERVER_REVISION=7996ef5
CI_SERVER_TLS_CA_FILE=/builds/bahmutov/kitchensink.tmp/CI_SERVER_TLS_CA_FILE
CI_SERVER_VERSION=11.2.0-rc2-ee
```

It seems that the common id is the `CI_PIPELINE_ID`, `CI_PIPELINE_URL` and for each job we have separate `CI_JOB_ID` and `CI_JOB_URL`

### PR DESCRIPTION
**Pull request by bahmutov**
- close #2343 
- [x] passes pipeline id and url
- [x] what's up with missing branch name ... - hmm, the variable `CI_COMMIT_REF_NAME` is there in the environment variables on GitLab, why isn't it in the dashboard (fixed GitLab detection predicate function)
- [x]  branch name on Appveyor (need to fix commit-info logic to allow environment variables to work)

### CODE REVIEW

File: packages/server/lib/modes/record.coffee [hunk 1]
```diff
@@ -219,6 +219,18 @@ updateInstance = (options = {}) ->
     else
       null
 
+getCommitFromGitOrCi = (git) ->
+  la(check.object(git), 'expected git information object', git)
+  ciProvider.commitDefaults({
```
Comment (bahmutov) [inline packages/server/lib/modes/record.coffee]: fills any properties that have null value

File: packages/server/package.json [hunk 2]
```diff
@@ -81,7 +81,7 @@
   },
   "dependencies": {
     "@cypress/browserify-preprocessor": "1.1.0",
-    "@cypress/commit-info": "^1.2.2",
+    "@cypress/commit-info": "2.0.0",
```
Comment (bahmutov) [inline packages/server/package.json]: v2 returns `null` for values it could not determine, breaking `gift` compatibility, but making it simple to fill values using CI environment variables
