### PR TITLE
fix(net-stubbing): fix cy.get(alias) with cy.intercept()

### LINKED ISSUE #9306: cy.get('@aliasOfIntercept) return null
### Current behavior
Till now (before v6) i could get data eg `request.body` using `cy.get(aliasOf cy.route)` if request occurs.  Now I get on the same code which works before.

```
Timed out retrying: cy.its() errored because your subject is: null. You cannot access any properties such as request on a null value.
If you expect your subject to be null, then add an assertion such as:
cy.wrap(null).should('be.null')
```

### Desired behavior
I should get data from request

### Test code to reproduce
```js
 cy.intercept('PATCH', ${uriPatch}`).as('update_success')
 cy.wait('@update_success').its('response.statusCode').should('eq', 200)
        if (Array.isArray(bodyJson)) {
            cy.get('@update_success').its('request.body').should('deep.equal', bodyJson)    <- here I get this null, works till v6
        } else {
            cy.get('@update_success').its('request.body').should('deep.include', bodyJson)  <- here I get this null, works till v6
        }
```

### Versions
6.0.0

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #9306 
### User facing changelog

- Fixed an issue where using `cy.get` for an alias of `cy.intercept` would always yield null.

### Additional details

- added explicit support for `cy.get('@alias')`, `@alias.all`, and `@alias.[index]`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/commands/querying.js [hunk 1]
```diff
@@ -246,6 +274,26 @@ module.exports = (Commands, Cypress, cy, state) => {
             return requests
           }
 
+          if (['route2', 'intercept'].includes(command.get('name'))) {
```
Comment (bahmutov) [inline packages/driver/src/cy/commands/querying.js:277]: poor `route` gets no respect here

File: packages/driver/src/cy/commands/querying.js [hunk 2]
```diff
@@ -246,6 +274,26 @@ module.exports = (Commands, Cypress, cy, state) => {
...
+            const requests = getAliasedRequests(alias, state)
+            const specifier = /\.(all|[\d]+)$/.exec(selector)
```
Comment (bahmutov) [inline packages/driver/src/cy/commands/querying.js:279]: ughh, it would be nice to comment or extract this

File: packages/driver/src/cy/net-stubbing/aliasing.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  // dynamic aliasing is possible if a route with dynamic interception has been defined
+  return _.find(state('routes'), (route) => {
+    return _.isFunction(route.handler)
+  })
+}
+
+export function getAliasedRequests (alias: string, state: Cypress.State): Interception[] {
+  // Start with request-level (req.alias = '...') aliases that could be a match.
+  const requests = _.filter(state('aliasedRequests'), { alias })
+  .map(({ request }) => request)
```
Comment (bahmutov) [inline packages/driver/src/cy/net-stubbing/aliasing.ts:17]: `.map(_.property('request'))`

**Review by bahmutov — APPROVED** [review]
It does solve the problem with `cy.wait() cy.get()` I had in https://glebbahmutov.com/blog/cypress-intercept-problems/#cywait-uses-the-intercept

File: packages/driver/src/cy/commands/querying.js (hunk 2 above)
Comment (flotwig) [reply packages/driver/src/cy/commands/querying.js:279]:
```suggestion
            // detect alias.all and alias.index
            const specifier = /\.(all|[\d]+)$/.exec(selector)
```
