### PR TITLE
fix: discover CT community definitions in monorepos with hoisted dependencies

### LINKED ISSUE #25993: Cypress does not resolve CT Framework Definition in monorepo with hoisted node_modules
### Current behavior

Cypress does not resolve CT Framework Definition correctly in monorepos with hoisted modules.

### Desired behavior

Should correctly resolve.

### Test code to reproduce

Use a monorepo, eg https://github.com/lmiller1990/ct-monorepo-bug

- yarn install
- notice `@lmiller1990/cypress-ct-solid-js` is in the root node_modules
- `cd packages/foo`
- `yarn cypress open`
- Select CT
- Notice Solid.js is NOT shown in the list

Problem is we can't just `require.resolve` - we first need to find all node_modules matching the `cypress-ct-` glob. We currently do this by globbing the projectRoot - that's where the Cypress project is currently, so in this case it'll be `packages/foo/node_modules/cypress-ct-*`. Code here: https://github.com/cypress-io/cypress/blob/e674f43040ad95d2745601aa0f36eab4703c837e/packages/scaffold-config/src/ct-detect-third-party.ts#L49-L56

We need to recursively check up to the workspace root, I think - how you identify this, I'm not sure (eg if we are in an Nx repo, how to know the top level? Yarn monorepo? Other type of repo)?

### Cypress Version

12.7.0

### Node version

v16.17

### Operating System

All

### Debug Logs

```shell
n/a
```

### Other

n/a

### PR DESCRIPTION
**Pull request by astone123**
- Closes #25993

### Additional details

Right now when we detect CT community framework modules during the Launchpad setup, we only check the `projectRoot` `node_modules/` and then return. This doesn't work if you have a monorepo that hoists dependencies to the repository root. 

This PR adds logic to search from the project root to the repository root for community framework modules and return all of the ones that are found.

We use a variety of methods to determine whether or not we've found the repository root:
- Looking for platform-specific configuration files (eg `lerna.json`, `nx.json`, etc)
- Looking for a `.git/` directory (meaning that Git has been configured at this level, indicating a repository root)
- `package.json` having a `workspace` entry in it

This isn't a fool-proof way of determining the repository root but it should work for most projects. I basically copied what Vite does https://github.com/vitejs/vite/blob/0f6de4dcff783ec21fada47651d564cd5e2631b2/packages/vite/src/node/server/searchRoot.ts#L59

### Steps to test

Use a monorepo, eg https://github.com/lmiller1990/ct-monorepo-bug

- yarn install
- notice @lmiller1990/cypress-ct-solid-js is in the root node_modules
- cd packages/foo
- open yarn in global mode `yarn cypress:open`
- open `ct-monorepo-bug/packages/foo` in Cypress
- select CT
- verify that Solid shows up in the list as a community framework

### PR Tasks

- [x] Have tests been added/updated? - I'm still working on this, will add another test for automatically testing monorepo support
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by astone123** [comment]
I still need to add a test to automatically verify that we will find third party dependencies for monorepos, but I'm looking for some feedback in the mean time

File: packages/scaffold-config/src/ct-detect-third-party.ts [hunk 1]
```diff
@@ -25,6 +26,46 @@ const thirdPartyDefinitionPrefixes = {
   globalPrefix: 'cypress-ct-',
 }
 
+const ROOT_PATHS = [
```
Comment (lmiller1990) [inline packages/scaffold-config/src/ct-detect-third-party.ts:29]: Nit... should this be `ROOT_FILES`?

File: packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts [hunk 2]
```diff
@@ -49,6 +49,63 @@ describe('isThirdPartyDefinition', () => {
...
+  it('returns true if there is a Git directory', async () => {
+    await fs.mkdir('./tmp/.git')
+
+    const isCurrentRepositoryRoot = await isRepositoryRoot(path.resolve('./tmp'))
+
+    expect(isCurrentRepositoryRoot).to.be.true
+  })
+
+  it('returns false if there is a package.json without workspaces field', async () => {
+    await fs.writeFile('./tmp/package.json', `{
```
Comment (lmiller1990) [inline packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts]: Won't this make a bunch of files in the local repo?

Could use something like

```
path.join(os.tmpdir(), 'some-temp-dir')
```

To make something in `/tmp` - I've seen this pattern elsewhere in the code base.

File: packages/scaffold-config/src/ct-detect-third-party.ts [hunk 3]
```diff
@@ -46,14 +87,46 @@ export async function detectThirdPartyCTFrameworks (
...
+
+      const newPackagePaths = await globby(fullPathGlobs)
+
+      if (newPackagePaths.length > 0) {
+        debug('found third-party dependencies %o', newPackagePaths)
+      }
+
+      packageJsonPaths = [...packageJsonPaths, ...newPackagePaths]
+
+      const isCurrentRepositoryRoot = await isRepositoryRoot(directory)
```
Comment (lmiller1990) [inline packages/scaffold-config/src/ct-detect-third-party.ts:111]: I can give this PR a test later, but definitely will be good to see some tests around this full functionality (whether it's Cy-in-Cy, or just an elaborate unit/integration test in this package).

File: packages/scaffold-config/src/ct-detect-third-party.ts (hunk 1 above)
Comment (astone123) [reply packages/scaffold-config/src/ct-detect-third-party.ts:29]: I used the term paths because some of them are directories and some are files, for example `.git` is a directory.

File: packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts (hunk 2 above)
Comment (astone123) [reply packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts]: I have beforeEach and afterEach hooks on these tests that create and delete the directory that is created which should clean up any files that are created

Comment (lmiller1990) [reply packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts]: I still think it's probably better to just use `/tmp` (via `os.tmpdir()`) that's kind of what it's intended for, for the odd case that the files might not be cleaned up (who knows...) 

One benefit would be cross OS compat - eg, does this test run as expected on windows? Probably not, since it's assuming posix when you do `/`, which isn't the case on windows. The core Node.js module `os` handles all this messiness out of the box.

The `os.tmpdir()` is pattern used throughout the code base when we need to create on-the-fly file system fixtures - what do you think? It should be a fairly quick refactor.

**Review by lmiller1990 — COMMENTED** [review]
Tested it out, seems to be working as expected for the minimal reproduction.

Also, might be a good chance to make a little OSS module like `find-project-root` or something -- what do you think? Seems like something that'd be pretty useful.

**Review by marktnoonan — COMMENTED** [review]
Testing this went fine @astone123, I see you have a few open comments from @lmiller1990 so feel free to tag me for re-review

File: packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts (hunk 2 above)
Comment (marktnoonan) [reply packages/scaffold-config/test/unit/ct-detect-third-party.spec.ts]: `os.tmpdir()` sounds like a good idea since `afterEach` is not guaranteed to run.

**Review by marktnoonan — APPROVED** [review]

File: packages/scaffold-config/src/ct-detect-third-party.ts (hunk 3 above)
Comment (astone123) [reply packages/scaffold-config/src/ct-detect-third-party.ts:111]: I added a unit test in this package, let me know what you think

File: packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts [hunk 4]
```diff
@@ -404,7 +404,15 @@ async function makeE2ETasks () {
       }
     },
     async __internal_openProject ({ argv, projectName }: InternalOpenProjectArgs): Promise<ResetOptionsResult> {
-      if (!scaffoldedProjects.has(projectName)) {
+      let projectMatched = false
```
Comment (astone123) [inline packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts:407]: Had to re-work this in order to call `cy.openProject` with a directory inside of a project like `<projectName>/packages/foo` to test monorepos

File: packages/frontend-shared/cypress/support/e2e.ts [hunk 5]
```diff
@@ -235,8 +235,10 @@ function openGlobalMode (options: OpenGlobalModeOptions = {}) {
   })
 }
 
-function openProject (projectName: ProjectFixtureDir, argv: string[] = []) {
-  if (!fixtureDirs.includes(projectName)) {
+type WithPrefix<T extends string> = `${T}${string}`;
```
Comment (astone123) [inline packages/frontend-shared/cypress/support/e2e.ts:238]: Same here, this allows us to open Cypress from **within** a project to support monorepo testing

File: packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts (hunk 4 above)
Comment (lmiller1990) [reply packages/frontend-shared/cypress/e2e/e2ePluginSetup.ts:407]: Shame we lose the auto completion :(

Let's do it for now, but I wonder if we can find a way to keep the completion 🤔

File: packages/launchpad/cypress/e2e/scaffold-component-testing.cy.ts [hunk 6]
```diff
@@ -232,5 +232,22 @@ describe('scaffolding component testing', {
 
       verifyConfigFile('cypress.config.js')
     })
+
+    it('Scaffolds component testing for monorepos with hoisted dependencies', () => {
+      cy.scaffoldProject('ct-monorepo-unconfigured')
+      cy.openProject('ct-monorepo-unconfigured/packages/foo')
```
Comment (lmiller1990) [inline packages/launchpad/cypress/e2e/scaffold-component-testing.cy.ts:238]: Random idea to keep the autocompletion on the project name:

```ts
cy.openProject('ct-monorepo-unconfigured', { package: 'packages/foo' })
```

**Review by lmiller1990 — APPROVED** [review]
Looks good, quick commit since I think this will break windows CI without `path.join` https://github.com/cypress-io/cypress/pull/26066/commits/b172a098edf73b92ea73439dc7426cf8af6ea75a
