### PR TITLE
fix(types): Fix Types on CyHttpMessages.BaseMessage.headers

### LINKED ISSUE #16734: Update typing `CyHttpMessages.BaseMessage.headers`
### What would you like?

This should be fairly straightforward, but the `headers` dictionary field in `CyHttpMessages.BaseMessage` within `packages/net-stubbing/lib/external-types.ts` can be expanded to include `string[]` as a valid value type (in addition to just `string`).

 An example of when this might occur is when the server returns a `set-cookie` header that includes multiple cookies. This results in a value of `string[]` where each cookie is its own `string`.

### Why is this needed?

This improves typing in IDEs/Editors and also prevents TS2339 wherein calling `.filter` on `headers` is flagged as problematic when it is not.

### PR DESCRIPTION
**Pull request by andercs**
- Closes #16734

### User facing changelog

Fixes typing on `CyHttpMessages.BaseMessage.headers` such that methods like `filter`, `slice`, etc. are accurately suggested by an IDE / Intellisense Code Editor.

### Additional details

Improves typing accuracy in IDEs for people working with "set-cookie" headers.

### How has the user experience changed?

N/A (Dev facing only)

### PR Tasks

N/A

### CODE REVIEW

**Review by flotwig — CHANGES_REQUESTED** [review]
@andercs Thanks for opening a PR. Check `create-build-artifacts`, there appears to be a legitimate typecheck failure related to the type change.

This issue is related, setting multiple headers for a single key will not work even with this types change: https://github.com/cypress-io/cypress/issues/14368

**Comment by andercs** [comment]
@flotwig oh this wasn't intended to get Cypress's set cookie capability to create multiple set-cookie headers. This is the current observed behavior when the server sends back multiple `set-cookie` headers. They get collapsed into a single `set-cookie` header that yields a `string[]` as the value, rather than a single `string`.

I would agree that putting a `set-cookie` key in a dict / map / hash / <insert_synonym_here> multiple times isn't particularly possible.

**Comment by flotwig** [comment]
All good, I was just linking it since it's related.

**Comment by andercs** [comment]
@flotwig I think this is good to go at this point?

File: packages/net-stubbing/lib/server/util.ts [hunk 1]
```diff
@@ -241,7 +241,8 @@ export function getBodyEncoding (req: CyHttpMessages.IncomingRequest): BodyEncod
 
   // a simple heuristic for detecting UTF8 encoded requests
   if (req.headers && req.headers['content-type']) {
-    const contentType = req.headers['content-type'].toLowerCase()
+    const contentTypeHeader = req.headers['content-type'] as string
+    const contentType = contentTypeHeader.toLowerCase()
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/util.ts:245]:
```suggestion
    const contentTypeHeader = req.headers['content-type'] as string
    const contentType = contentTypeHeader.toLowerCase()
```

ehh, this is not quite right, the request will error out if for example it passes two `content-type` headers:

```
content-type: foo
content-type: bar
```

...`.toLowerCase` will not exist on the `Array` type.

but hey, it's okay, since that's not valid content-type according to the HTTP spec.

**Review by flotwig — APPROVED** [review]

**Comment by flotwig** [comment]
Thank you for opening a PR @andercs !
