### PR TITLE
fix: detect chrome browser process and tab crashes to no longer hang in CI

### LINKED ISSUE #6170: Detect browser/renderer crashes
### Current behavior:

Cypress doesn't know if the browser tab crashes during a test.

### Desired behavior:

Cypress detects browser tab crashes/browser crashes and exits cleanly after printing some debug information.

Dependency of: #349 

### Issues that this would make easier to debug

* Random hanging in Docker: https://github.com/cypress-io/cypress/issues/8206

### PR DESCRIPTION
**Pull request by mjhenkes**
- Closes #6170
- Related to #22631

### User facing changelog
* When a chromium based browser tab or process crashes, Cypress will no longer hang indefinitely but close fail the current test and move on to the next.

### Additional details

We are detecting tab crashes when cdp tells us it crashed and process crashes when the process exits with specific code/signal combinations.

This affects run mode much more than open mode. In run mode we will move on to the next spec. In open mode we will re-launch the browser to the home screen if it crashes.

### Steps to test

I've created to specs that use CDP to crash the browser process and tab in the system tests e2e project. These work for any chromium based browser. This fix 'may' work for firefox but we have no way to test to see what signal/code combination we should be handling.

### How has the user experience changed?

Browser tab crash - before: process hangs indefinitely 

https://user-images.githubusercontent.com/1588747/197219147-305298dc-2673-4cb4-93f1-f4666558d5f0.mov

Browser tab crash - after: process fails current spec and moves on to the next.

https://user-images.githubusercontent.com/1588747/197216997-dee9f4d7-82bc-4109-b159-2c83779995ce.mov

Browser process crash - before: process hangs indefinitely 

https://user-images.githubusercontent.com/1588747/197219174-9d4a4e3d-cd77-43c1-adab-8e92a24583a8.mov

Browser process crash - after: process fails current spec and moves on to the next.

https://user-images.githubusercontent.com/1588747/197217877-8dd96604-d436-4ad5-89f5-28ee87278eeb.mov

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/errors/src/errors.ts [hunk 1]
```diff
@@ -570,7 +570,6 @@ export const AllCypressErrors = {
         This can happen for a number of different reasons:
 
         - You wrote an endless loop and you must fix your own code
-        - There is a memory leak in Cypress (unlikely but possible)
```
Comment (mjhenkes) [inline packages/errors/src/errors.ts:573]: Removing this to not first plant the idea that the user isn't at fault. They may not be at fault, but we'd like more investigation before they reach that conclusion.

File: packages/server/lib/browsers/index.ts [hunk 2]
```diff
@@ -155,13 +156,36 @@ export = {
...
-    instance.once('exit', () => {
+    instance.once('exit', async (code, signal) => {
       ctx.browser.setBrowserStatus('closed')
       // TODO: make this a required property
       if (!options.onBrowserClose) throw new Error('onBrowserClose did not exist in interactive mode')
 
+      const browserDisplayName = instance?.browser?.displayName || 'unknown'
+
       options.onBrowserClose()
+      browserLauncher.clearInstanceState()
```
Comment (mjhenkes) [inline packages/server/lib/browsers/index.ts:167]: we clear the instance state here because we don't 'kill' the browser since it's already dead.

File: packages/server/lib/project-base.ts [hunk 3]
```diff
@@ -103,7 +103,9 @@ export class ProjectBase<TServer extends Server> extends EE {
     this.options = {
       report: false,
       onFocusTests () {},
-      onError () {},
+      onError (error) {
```
Comment (mjhenkes) [inline packages/server/lib/project-base.ts:106]: this is a change to ensure that we're logging errors in open mode and not losing them or logging them twice.

File: packages/server/lib/browsers/electron.ts [hunk 4]
```diff
@@ -146,9 +146,10 @@ export = {
       onCrashed () {
         const err = errors.get('RENDERER_CRASHED')
 
-        errors.log(err)
```
Comment (mjhenkes) [inline packages/server/lib/browsers/electron.ts:149]: by default 'onError' is defined in open mode, but it was defined as an empty function. this would lead to duplicate logging of errors in run mode. I modified the default onError to log errors and removed this call to remove the duplicate logs.

File: system-tests/projects/e2e/cypress/e2e/chrome_process_crash.cy.js [hunk 5]
```diff
@@ -0,0 +1,4 @@
+it('crashes the chrome process', () => {
+  Cypress.automation('remote:debugger:protocol', { command: 'Browser.crash', params: {} })
```
Comment (mjhenkes) [inline system-tests/projects/e2e/cypress/e2e/chrome_process_crash.cy.js:2]: this uses cdp to crash the browser process

File: system-tests/projects/e2e/cypress/e2e/chrome_tab_crash.cy.js [hunk 6]
```diff
@@ -0,0 +1,4 @@
+it('crashes the chrome tab', () => {
+  Cypress.automation('remote:debugger:protocol', { command: 'Page.navigate', params: { url: 'chrome://crash', transitionType: 'typed' } })
```
Comment (mjhenkes) [inline system-tests/projects/e2e/cypress/e2e/chrome_tab_crash.cy.js:2]: this uses cdp to crash the browser tab

File: packages/errors/src/errors.ts (hunk 1 above)
Comment (ryanthemanuel) [inline packages/errors/src/errors.ts:573]: Is this no longer a concern?

File: packages/server/lib/browsers/index.ts [hunk 7]
```diff
@@ -155,13 +156,36 @@ export = {
     // TODO: normalizing opening and closing / exiting
     // so that there is a default for each browser but
     // enable the browser to configure the interface
-    instance.once('exit', () => {
+    instance.once('exit', async (code, signal) => {
       ctx.browser.setBrowserStatus('closed')
       // TODO: make this a required property
       if (!options.onBrowserClose) throw new Error('onBrowserClose did not exist in interactive mode')
 
+      const browserDisplayName = instance?.browser?.displayName || 'unknown'
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/index.ts:164]: Would Electron be the fallback here or when would we not know this value? User defied browser instance?

File: packages/errors/src/errors.ts (hunk 1 above)
Comment (mjhenkes) [reply packages/errors/src/errors.ts:573]: Removing this to not first plant the idea that the user isn't at fault. They may not be at fault, but we'd like more investigation before they reach that conclusion.

File: packages/server/lib/browsers/index.ts [hunk 8]
```diff
@@ -155,13 +156,36 @@ export = {
...
+
       options.onBrowserClose()
+      browserLauncher.clearInstanceState()
       instance = null
+
+      // We are being very narrow on when to restart the browser here. The only case we can reliably test the 'SIGTRAP' signal.
+      // We want to avoid adding signals in here that may intentionally be caused by a user.
+      // For example exiting firefox through either force quitting or quitting via cypress will fire a 'SIGTERM' event which
+      // would result in constantly relaunching the browser went he user actively wants to quit.
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/index.ts]:
```suggestion
      // would result in constantly relaunching the browser when the user actively wants to quit.
```

File: packages/server/lib/browsers/index.ts (hunk 7 above)
Comment (mjhenkes) [reply packages/server/lib/browsers/index.ts:164]: I'm really not sure in what cases we don't have the display name, just following typescripts lead to be honest. If we don't have a browser or a display name available i honestly don't know what could be happening.

File: packages/server/lib/browsers/index.ts [hunk 9]
```diff
@@ -155,13 +156,36 @@ export = {
...
 
+      const browserDisplayName = instance?.browser?.displayName || 'unknown'
+
       options.onBrowserClose()
+      browserLauncher.clearInstanceState()
       instance = null
+
+      // We are being very narrow on when to restart the browser here. The only case we can reliably test the 'SIGTRAP' signal.
+      // We want to avoid adding signals in here that may intentionally be caused by a user.
+      // For example exiting firefox through either force quitting or quitting via cypress will fire a 'SIGTERM' event which
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/index.ts:172]: > quitting via cypress will fire a 'SIGTERM' event which

Is this quitting like a hard kill app quit? I notice an errors randomly this when we click the close button or ctrl + c in the terminal for Cypress unexpectedly killing

Comment (mjhenkes) [reply packages/server/lib/browsers/index.ts:172]: Yeah sigterm is what you get when you hard kill the app. Specifically in this case we hard kill firefox. But we can't use the sigterm signal because when we force exit firefox via the app, we get cause the sigterm signal and you end up in a loop where you can never kill firefox because we restart it.

File: packages/server/lib/open_project.ts [hunk 10]
```diff
@@ -186,6 +186,8 @@ export class OpenProject {
         return await browsers.connectToNewSpec(browser, { onInitializeNewBrowserTab, ...options }, automation)
```
Comment (emilyrohrbough) [inline packages/server/lib/open_project.ts:186]: Do we need to update `connectToNewSpec` as well to create a new browser instance if one doesn't exist? Currently the browser instance doesn't exist, `browsers.connectToNewSpec` will see this isn't defined and throw:
```js
  async connectToNewSpec (browser: Browser, options: BrowserNewTabOpts, automation: Automation) {
    debug('connecting to new chrome tab in existing instance with url and debugging port', { url: options.url })

    const browserCriClient = this._getBrowserCriClient()

    if (!browserCriClient) throw new Error('Missing browserCriClient in connectToNewSpec')
```

File: system-tests/test/browser_crash_handling_spec.js [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+
+  // It should fail the chrome_tab_crash spec, but the simple spec should run and succeed
+  context('when the tab crashes in electron', () => {
+    systemTests.it('fails', {
+      browser: 'electron',
+      spec: 'chrome_tab_crash.cy.js,simple.cy.js',
+      snapshot: true,
+      expectedExitCode: 1,
+    })
+  })
```
Comment (emilyrohrbough) [inline system-tests/test/browser_crash_handling_spec.js:28]:
```suggestion
  context('when the tab crashes', () => {
    systemTests.it('fails', {
      browser: ['chrome', 'electron']
      spec: 'chrome_tab_crash.cy.js,simple.cy.js',
      snapshot: true,
      expectedExitCode: 1,
    })
  })
```

File: packages/server/lib/browsers/index.ts (hunk 8 above)
Comment (ryanthemanuel) [inline packages/server/lib/browsers/index.ts]:
```suggestion
      // would result in constantly relaunching the browser went the user actively wants to quit.
```

File: packages/server/lib/browsers/index.ts [hunk 12]
```diff
@@ -155,13 +156,36 @@ export = {
...
+      // would result in constantly relaunching the browser went he user actively wants to quit.
+      // On windows the crash produces 2147483651 as an exit node. We should add to the list of crashes we handle as we see them.
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/index.ts]:
```suggestion
      // On windows the crash produces 2147483651 as an exit code. We should add to the list of crashes we handle as we see them.
```

File: system-tests/test/browser_crash_handling_spec.js [hunk 13]
```diff
@@ -0,0 +1,49 @@
...
+
+  // If chrome crashes, all of cypress crashes when in electron
+  context('when the browser process crashes in electron', () => {
+    systemTests.it('fails', {
+      browser: 'electron',
+      spec: 'chrome_process_crash.cy.js,simple.cy.js',
+      snapshot: true,
+      expectedExitCode: 1,
+    })
+  })
```
Comment (emilyrohrbough) [inline system-tests/test/browser_crash_handling_spec.js:48]:
```suggestion
  // It should fail the chrome_tab_crash spec, but the simple spec should run and succeed
  context('when the browser process crashes ', () => {
    systemTests.it('fails', {
      browser: ['chrome', 'electron],
      spec: 'chrome_process_crash.cy.js,simple.cy.js',
      snapshot: true,
      expectedExitCode: 1,
    })
  })
```

File: packages/server/lib/open_project.ts (hunk 10 above)
Comment (mjhenkes) [reply packages/server/lib/open_project.ts:186]: connectToNewSpec isn't run because 'options.shouldLaunchNewTab' is false, so we fall into the browser.open flow

Comment (emilyrohrbough) [reply packages/server/lib/open_project.ts:186]: When does this get reset to false? I thought this was set to true when it wasn't the first spec

Comment (mjhenkes) [reply packages/server/lib/open_project.ts:186]: i assume in onError which end up calling 'onEarlyExit' in run.ts. Theres a lot of redirections.

File: system-tests/test/browser_crash_handling_spec.js (hunk 13 above)
Comment (mjhenkes) [reply system-tests/test/browser_crash_handling_spec.js:48]: I tried this and it seemed like it got confused and was trying to match the snapshots of the two runs against each other. So i aborted and reverted to the current method.

File: system-tests/test/browser_crash_handling_spec.js (hunk 11 above)
Comment (mjhenkes) [reply system-tests/test/browser_crash_handling_spec.js:28]: I tried this and it seemed like it got confused and was trying to match the snapshots of the two runs against each other. So i aborted and reverted to the current method.

**Review by ryanthemanuel — APPROVED** [review]

File: system-tests/test/browser_crash_handling_spec.js [hunk 14]
```diff
@@ -0,0 +1,49 @@
...
+  systemTests.setup({
+    settings: {
+      e2e: {},
+    },
+  })
+
+  // It should fail the chrome_tab_crash spec, but the simple spec should run and succeed
+  context('when the tab crashes in chrome', () => {
+    systemTests.it('fails', {
+      browser: 'chrome',
```
Comment (AtofStryker) [inline system-tests/test/browser_crash_handling_spec.js:13]: should we add one for edge too? Guessing no since we treat chrome/edge the same?

**Review by AtofStryker — APPROVED** [review]
Gave the system tests a run on Mac and Windows. looks like everything behaves the way I would expect!

File: system-tests/test/browser_crash_handling_spec.js (hunk 14 above)
Comment (mjhenkes) [reply system-tests/test/browser_crash_handling_spec.js:13]: Yeah, edge and chrome behave the same, no harm in testing it though 🤔

Comment (mjhenkes) [reply system-tests/test/browser_crash_handling_spec.js:13]: Apparently edge isn't available in system tests? 🤷‍♂️

Comment (emilyrohrbough) [reply system-tests/test/browser_crash_handling_spec.js:13]: @mjhenkes Its likely because we don't run test on a window instance in CI

**Review by emilyrohrbough — APPROVED** [review]
