### PR TITLE
fix: change binary of VS Code editor found on windows to match default install

### LINKED ISSUE #15080: VSCode not auto discovered for file opener preference in Windows 10
### Current behavior

When changing the File Opener Preference from the test runner GUI on my Windows 10 machine I must manually specify the path to the executable for VSCode.

### Desired behavior

VSCode should be auto discovered and listed as an option. I believe this is because Cypress expects the VSCode executable to be named `code.exe` as defined in [`env-editors.ts`](https://github.com/cypress-io/cypress/blob/4d76049d2c419d77968beafcdda45585744fc542/packages/server/lib/util/env-editors.ts#L132). However on my Windows 10 machine the VSCode cli command is installed as `code` with no `.exe` extension. 
```
U:\>where code
C:\Users\npalmer\AppData\Local\Programs\Microsoft VS Code\bin\code
C:\Users\npalmer\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd

U:\>where code.exe
INFO: Could not find files for the given pattern(s).
```
I don't recall having modified this so I assume this is the same for other VSCode users on Windows 10. 

### Versions
Cypress 6.4.0
VSCode 1.53.2 (user setup)
Windows 10 (18363.1256)

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Close #15080 

### User facing changelog

Cypress will now detect the default installation location of the Visual Studio Code editors on Windows machines.

### Additional details

- I just set up a Windows VM and this was where VS Code installs by default, with no `.exe` extension. 
- I manually tested that this change detects VS Code on my Windows VM now by default.

#### Before

Didn’t detect my VS Code in Windows

Screen Shot 2021-05-05 at 2 07 34 PM

#### After

Now detects my VS Code in Windows

Screen Shot 2021-05-05 at 2 29 03 PM

### PR Tasks

- [x] Tests? I manually tested, not sure there’s much to do beyond that
- [ ] Zenhub release tag

### CODE REVIEW

File: packages/server/lib/util/env-editors.ts [hunk 1]
```diff
@@ -129,7 +129,7 @@ const windowsEditors = [
     name: 'Brackets',
   }, {
     id: 'code',
-    binary: 'Code.exe',
+    binary: 'code',
```
Comment (flotwig) [inline packages/server/lib/util/env-editors.ts:132]: weird that there's no `.exe`, but was there one before? i.e. is this going to break code detection for older vscode users?

Comment (jennifer-shehane) [reply packages/server/lib/util/env-editors.ts:132]: Pft, I dunno, was going to ask @chrisbreiding how he determined the list to begin with.

Comment (chrisbreiding) [reply packages/server/lib/util/env-editors.ts:132]: I don't remember exactly where this list came from. I thought I had left comments in the code pointing the source, but I guess not. I think I compiled it from a few different sources, like [env-editor](https://github.com/sindresorhus/env-editor), but I'm not sure where precisely I got the VSCode binary value for Windows. I didn't manually test out each editor on each OS, so it's possible it has always been wrong, or it's equally possible it has changed at some point from `Code.exe` to `Code` since this was implemented.

**Review by chrisbreiding — APPROVED** [review]
