### PR TITLE
fix: Recovered Error Handling and Session Recovered Errors

### LINKED ISSUE #21398: [sessions] Improve Validation Error UI in Recreated Session
### What would you like?

The `cy.session` command is re-using the test error component to share details when a session failed validation and the `cy.session` command catches the error to then recreate the session. This is a bit unexpected in the UI and we'd like to update the UI to display these details differently.

Current UI (10.0 visuals): 

Screen Shot 2022-05-09 at 9 20 22 AM

### Designs
https://www.figma.com/file/E86dG4e1dcuyRe33B2j3zU/app-reporter%3A-sessions?node-id=17733%3A151907

### LINKED ISSUE #24205: Remove handling `return false` from validate
1. Remove clearing the page before the validate (on create)
    1. Users don’t understand that validate purges the cache
    2. Users will DRY up code

### LINKED ISSUE #24593: [sessions] cy.session validate() TypeScript Types not consistent with documentation
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

The `cy.session` documentation says:
> If the validate function return false, throws an exception, **returns a Promise that resolves to false or rejects**, or contains any failing Cypress command, the session will be considered invalid, and setup will be re-run.

However, the return type of the validate function is actually `false | void`, so it is not possible to *return a Promise that resolves to false or rejects*
```ts
cy.session( [user, pwd] => {
    /**/
}, {
    /* Typescript complains about this as the return type of validate is `false | void` */
    validate: () => Promise.reject('Invalid session)
}
```

I've assumed this is a documentation issue, but I might be wrong. I'd be up to submitting a PR if needed.

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #21398
- Closes #24205
- Closes #24593

There PR has a few set of changes going on:
- Correct `cy.session()` error messaging for both created and restored/created with test coverage
	- updated messaging
	- proper code frames
	- handles the following failed validation scenarios: yield false, rejects, resolve false, thrown cy command, thrown err
	- REMOVED support for return false
- Fix Session Instrument Panel Tag color
- Enhance `cy.session()` console props output to include sessionStorage details and add step information to help with debuggin
- Fix verifying upcoming assertions log handling (and associated tests) - this was need to prevent duplicate error logging in recreated sessions
- Update command queue to be recursive to allow queue failures to always be collected when `onQueueFailed` (previously `onCommandFailed`) to ensure all failures can be collected on a 2nd session validation failure and/or when multiple session commands are used in a test.
- Correctly end log groups when `on:fail` handlers to make additional assertions visible 

### User facing changelog
TO DO

### Steps to test
It would be solid to pull this branch down and run various tests yourself to verify changes to logs and to ensure we don't hanging logs and that things appear to be correct. 

### How has the user experience changed?
Will comment screenshots here & throughout the code. 

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4842
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/reporter/src/sessions/sessions.tsx [hunk 1]
```diff
@@ -31,13 +31,11 @@ const SessionRow = ({ name, isGlobalSession, id, state, status, testId }: Sessio
...
           {name}
         </span>
-        <span className='session-tag'>
-          <Tag
-            customClassName='session-status'
-            content={status}
-            type={`${state === 'failed' ? 'failed' : 'successful'}-status`}
-          />
-        </span>
+        <Tag
```
Comment (emilyrohrbough) [inline packages/reporter/src/sessions/sessions.tsx:34]: | Before | After |
|--|--|
|Screen Shot 2022-11-02 at 4 24 09 PM| Screen Shot 2022-11-02 at 4 24 43 PM |

File: system-tests/projects/session-and-origin-e2e-specs/cypress/e2e/session/session.cy.js [hunk 2]
```diff
@@ -387,12 +387,6 @@ function SuiteWithValidateFn (id, fn) {
   })
 }
 
-describe('options.validate reruns steps when returning false', () => {
```
Comment (emilyrohrbough) [inline system-tests/projects/session-and-origin-e2e-specs/cypress/e2e/session/session.cy.js:390]: No longer valid failure mechanism (https://github.com/cypress-io/cypress/issues/24205)

File: packages/reporter/src/commands/command.tsx [hunk 3]
```diff
@@ -402,7 +401,15 @@ class Command extends Component<Props> {
...
         </li>
         {model.err?.isRecovered && (
-          <li><TestError err={model.err} testId={model.testId} commandId={model.id} groupLevel={groupLevel}/></li>
+          <li>
+            <TestError
+              err={model.err}
+              testId={model.testId}
+              commandId={model.id}
+              // if the err is recovered and the current command is a log group, nest the test error within the group
+              groupLevel={this.props.groupId && groupLevel === this.props.groupId ? ++groupLevel : groupLevel}
```
Comment (emilyrohrbough) [inline packages/reporter/src/commands/command.tsx]: Meant to ensures `reject false` case has the correct group in a recreated session and will collapse when the group is closed, but looks like this logic is broken. Meant to fix this case (whoops!)
Screen Shot 2022-11-02 at 4 33 20 PM

File: packages/driver/src/cypress/runner.ts [hunk 4]
```diff
@@ -1520,6 +1520,8 @@ export default {
             // the test.run(fn)
             return null
           }).catch((err) => {
+            // once we complete callback with the
+            // original err
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/runner.ts]:
```suggestion
```

File: packages/driver/src/cypress/runner.ts [hunk 5]
```diff
@@ -1492,7 +1492,7 @@ export default {
           // attach error right now
           // if we have one
           if (err) {
-            const PendingErrorMessages = ['sync skip', 'async skip call', 'async skip; aborting execution']
+            const PendingErrorMessages = ['sync skip', 'sync skip; aborting execution', 'async skip call', 'async skip; aborting execution']
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/runner.ts:1495]: This test case in our repo produced this error: https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cy/skipping_async.cy.js#L36

File: packages/driver/src/cypress/log.ts [hunk 6]
```diff
@@ -401,14 +398,15 @@ export class Log {
...
-    // current log was responsible to creating the current log group so end the current group
+    // current log was responsible for creating the current log group so end the current group
     if (_.last(logGroupIds) === this.attributes.id) {
       this.endGroup()
     }
 
     this.set({
       ended: true,
       error: err,
+      _error: undefined,
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/log.ts:409]: clean up stale `_error` attribute set by verify upcoming assertions.

File: packages/driver/src/cypress/cy.ts [hunk 7]
```diff
@@ -1096,27 +1084,6 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
     return this.Cypress.action('app:navigation:changed', `page navigation event (${event})`)
   }
 
-  private cleanup () {
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/cy.ts:1099]: The command_queue handles this clean up now since it's setting & managing these values.

File: packages/driver/src/cypress/cy.ts [hunk 8]
```diff
@@ -691,19 +692,6 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
 
   runQueue () {
     cy.queue.run()
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/cy.ts:694]: The command_queue is handling its errors and when it ends.

File: packages/driver/src/cypress/cy.ts [hunk 9]
```diff
@@ -471,6 +470,8 @@ export class $Cy extends EventEmitter2 implements ITimeouts, IStability, IAssert
     // 1. callback with state("done") when async
     // 2. throw the error for the promise chain
     try {
+      this.Cypress.state('logGroupIds', []) // reset log groups so assertions are at the top level
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/cy.ts:473]: | Before | After |
| --|--|
| Screen Shot 2022-11-02 at 4 43 26 PM|Screen Shot 2022-11-02 at 4 43 55 PM|

File: packages/driver/src/cypress/command.ts [hunk 10]
```diff
@@ -3,9 +3,11 @@ import utils from './utils'
 
 export class $Command {
   attributes!: Record<string, any>
+  state: 'queued' | 'pending' | 'passed' | 'recovered' | 'failed' | 'skipped'
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/command.ts:6]: Transparency - this helped with debugging. All we really need to care about is `skipped` & `passed`.

File: packages/driver/cypress/e2e/commands/assertions.cy.js [hunk 11]
```diff
@@ -368,7 +368,7 @@ describe('src/cy/commands/assertions', () => {
 
         cy.on('log:added', (attrs, log) => {
           if (log.get('name') === 'assert') {
-            logs.push(log)
+            logs?.push(log)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/assertions.cy.js:371]: I was seeing a ton of errors for cannot pushed to defined throughout our tests.

File: packages/driver/cypress/e2e/commands/assertions.cy.js [hunk 12]
```diff
@@ -416,34 +416,40 @@ describe('src/cy/commands/assertions', () => {
...
-          expect(this.logs[3].get('state')).to.eq('failed')
-          expect(this.logs[3].get('error')).to.eq(err)
+          expect(this.logs[3].get('state')).to.eq('passed')
+          expect(this.logs[3].get('error')).to.be.undefined
 
           expect(this.logs[4].get('name')).to.eq('assert')
           expect(this.logs[4].get('state')).to.eq('failed')
-          expect(this.logs[4].get('error').name).to.eq('AssertionError')
+          expect(this.logs[4].get('error').name).to.eq('CypressError')
+          expect(this.logs[4].get('error')).to.eq(err)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/assertions.cy.js:428]: Get `.get('button')` is no longer marked as failed because it resolved correctly and the assertion was the failure.

| Before | After |
| -- | -- |
|Screen Shot 2022-11-02 at 5 00 15 PM|Screen Shot 2022-11-02 at 4 53 54 PM

File: packages/driver/cypress/e2e/commands/connectors.cy.js [hunk 13]
```diff
@@ -1562,14 +1569,21 @@ describe('src/cy/commands/connectors', () => {
         })
 
         it('throws the traversalErr as precedence when property does not exist even if the additional assertions fail', function (done) {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/connectors.cy.js:1571]: TODO: emily revisit this scenario again.

EDIT: the cy.on('fail') in the before hook was executing when taking screenshots so it looked like the command failed but the test passes (soooo it was working as expected just not for my screenshot!)

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 14]
```diff
@@ -860,6 +863,43 @@ describe('src/cy/commands/querying', () => {
         cy.get('div:first').should('not.be.visible')
       })
 
+      it('fails get command when element is not found', function (done) {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:882]: Error is the same.
| Before | After |
| -- | -- |
| Screen Shot 2022-11-02 at 5 16 49 PM|Screen Shot 2022-11-02 at 7 10 20 PM|

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 15]
```diff
@@ -860,6 +863,43 @@ describe('src/cy/commands/querying', () => {
...
+          expect(lastLog.get('state')).to.eq('failed')
+          expect(lastLog.get('error')).to.eq(err)
+
+          done()
+        })
+
+        cy.get('does_not_exist', { timeout: 1 })
+      })
+
+      it('fails get command when element is not found and has chained assertions', function (done) {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:899]: | Before | After |
| -- | -- |
| Screen Shot 2022-11-02 at 5 20 17 PM|Screen Shot 2022-11-02 at 7 09 51 PM |

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 16]
```diff
@@ -1779,27 +1825,47 @@ space
...
+          const assertionLog = this.logs[1]
+
           expect(err.message).to.eq('`cy.contains()` cannot be passed a `length` option because it will only ever return 1 element.')
           expect(err.docsUrl).to.eq('https://on.cypress.io/contains')
 
+          expect(containsLog.get('state')).to.eq('passed')
+          expect(containsLog.get('error')).to.be.undefined
+
+          expect(assertionLog.get('state')).to.eq('failed')
+          expect(err.message).to.include(assertionLog.get('error').message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:1893]: | Before | After |
| -- | -- |
| Screen Shot 2022-11-02 at 5 25 25 PM | Screen Shot 2022-11-02 at 5 25 55 PM |

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 17]
```diff
@@ -962,16 +1002,24 @@ describe('src/cy/commands/querying', () => {
...
+          expect(getLog.get('error')).to.be.undefined
+          expect(getLog.get('$el').get(0)).to.eq(button.get(0))
+          const consoleProps = getLog.invoke('consoleProps')
 
           expect(consoleProps.Yielded).to.eq(button.get(0))
           expect(consoleProps.Elements).to.eq(button.length)
 
+          expect(assertionLog.get('state')).to.eq('failed')
+          expect(err.message).to.include(assertionLog.get('error').message)
+
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:1041]: Get .get('button') is no longer marked as failed because it resolved correctly and the assertion was the failure.
|Before | After| 
| -- | -- |
|Screen Shot 2022-11-02 at 7 15 42 PM|Screen Shot 2022-11-02 at 7 18 00 PM|

File: packages/driver/cypress/e2e/commands/querying/querying.cy.js [hunk 18]
```diff
@@ -1779,27 +1825,47 @@ space
...
+          expect(containsLog.get('state')).to.eq('passed')
+          expect(containsLog.get('error')).to.be.undefined
+          expect(containsLog.get('$el').get(0)).to.eq(button.get(0))
+          const consoleProps = containsLog.invoke('consoleProps')
 
           expect(consoleProps.Yielded).to.eq(button.get(0))
           expect(consoleProps.Elements).to.eq(button.length)
 
+          expect(assertionLog.get('state')).to.eq('failed')
+          expect(err.message).to.include(assertionLog.get('error').message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/querying/querying.cy.js:1871]: `cy.contains('button')` is no longer marked as failed because it resolved correctly and the assertion was the failure.
|Before | After| 
| -- | -- |
|Screen Shot 2022-11-02 at 7 19 57 PM| Screen Shot 2022-11-02 at 7 15 18 PM|

File: packages/driver/cypress/e2e/commands/assertions.cy.js [hunk 19]
```diff
@@ -416,34 +416,40 @@ describe('src/cy/commands/assertions', () => {
...
-          expect(this.logs[0].get('state')).to.eq('failed')
-          expect(this.logs[0].get('error')).to.eq(err)
+          expect(this.logs[0].get('state')).to.eq('passed')
+          expect(this.logs[0].get('error')).to.be.undefined
 
           expect(this.logs[1].get('name')).to.eq('assert')
           expect(this.logs[1].get('state')).to.eq('failed')
-          expect(this.logs[1].get('error').name).to.eq('AssertionError')
+          expect(this.logs[1].get('error').name).to.eq('CypressError')
+          expect(this.logs[1].get('error')).to.eq(err)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/assertions.cy.js:453]: | Before | After| 
| -- | --|
|Screen Shot 2022-11-03 at 8 10 02 AM|Screen Shot 2022-11-03 at 8 11 24 AM |

File: packages/driver/cypress/e2e/commands/connectors.cy.js [hunk 20]
```diff
@@ -1562,14 +1569,21 @@ describe('src/cy/commands/connectors', () => {
...
             expect(err.message).to.include('`cy.wrap({ foo: \'bar\' }).its(\'quux\').should(\'not.exist\')`')
+            expect(err.docsUrl).to.eq('https://on.cypress.io/its')
+
+            expect(itsLog.get('state')).to.eq('passed')
+            expect(itsLog.get('error')).to.be.undefined
 
+            expect(lastLog.get('name')).to.eq('assert')
+            expect(lastLog.get('state')).to.eq('failed')
+            expect(lastLog.get('message')).to.contain('to be true')
             expect(lastLog.get('error').message).to.include(err.message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/connectors.cy.js:1587]: prob incorrect

| Before | After |
| -- | -- |
| Screen Shot 2022-11-03 at 8 14 30 AM | Screen Shot 2022-11-03 at 8 14 16 AM|

File: packages/driver/cypress/e2e/commands/connectors.cy.js [hunk 21]
```diff
@@ -1579,14 +1593,21 @@ describe('src/cy/commands/connectors', () => {
...
             expect(err.message).to.include('`cy.wrap({ foo: undefined }).its(\'foo\').should(\'be.undefined\')`')
             expect(err.docsUrl).to.eq('https://on.cypress.io/its')
+
+            expect(itsLog.get('state')).to.eq('passed')
+            expect(itsLog.get('error')).to.be.undefined
+
+            expect(lastLog.get('name')).to.eq('assert')
+            expect(lastLog.get('state')).to.eq('failed')
+            expect(lastLog.get('message')).to.contain('to be true')
             expect(lastLog.get('error').message).to.include(err.message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/connectors.cy.js:1611]: | Before | After |
| -- | -- |
|Screen Shot 2022-11-03 at 8 14 54 AM| Screen Shot 2022-11-03 at 8 15 07 AM|

File: packages/driver/cypress/e2e/commands/connectors.cy.js [hunk 22]
```diff
@@ -1606,11 +1627,18 @@ describe('src/cy/commands/connectors', () => {
...
+            expect(itsLog.invoke('consoleProps').Property).to.eq('.foo.bar.baz')
+
+            expect(itsLog.get('state')).to.eq('passed')
+            expect(itsLog.get('error')).to.be.undefined
+
+            expect(lastLog.get('name')).to.eq('assert')
+            expect(lastLog.get('state')).to.eq('failed')
+            expect(lastLog.get('message')).to.contain('expected **[Function]** to equal **baz**')
             expect(lastLog.get('error').message).to.include(err.message)
-            expect(lastLog.invoke('consoleProps').Property).to.eq('.foo.bar.baz')
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/connectors.cy.js:1642]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 18 27 AM|Screen Shot 2022-11-03 at 8 18 38 AM

File: packages/driver/cypress/e2e/commands/connectors.cy.js [hunk 23]
```diff
@@ -1757,9 +1784,16 @@ describe('src/cy/commands/connectors', () => {
...
 
             expect(err.message).to.include('Timed out retrying after 200ms: expected \'bar\' to equal \'baz\'')
+
+            expect(itsLog.get('state')).to.eq('passed')
+            expect(itsLog.get('error')).to.be.undefined
+
+            expect(lastLog.get('name')).to.eq('assert')
+            expect(lastLog.get('state')).to.eq('failed')
+            expect(lastLog.get('message')).to.contain('to equal')
             expect(lastLog.get('error').message).to.include(err.message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/connectors.cy.js:1797]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 18 44 AM|Screen Shot 2022-11-03 at 8 18 49 AM

File: packages/driver/cypress/e2e/commands/files.cy.js [hunk 24]
```diff
@@ -325,11 +325,16 @@ describe('src/cy/commands/files', () => {
...
-          expect(lastLog.get('error')).to.eq(err)
-          expect(lastLog.get('state')).to.eq('failed')
+          const assertLog = logs.find((log) => log.get('name') === 'assert')
+
+          expect(fileLog.get('state')).to.eq('passed')
+          expect(fileLog.get('error')).to.be.undefined
+
+          expect(assertLog.get('name')).to.eq('assert')
+          expect(assertLog.get('error')).to.eq(err)
+          expect(assertLog.get('state')).to.eq('failed')
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/files.cy.js:343]: `cy.readFile()` resolved correct, the assertion is what failed.

| Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 23 04 AM|Screen Shot 2022-11-03 at 8 23 12 AM

File: packages/driver/cypress/e2e/commands/files.cy.js [hunk 25]
```diff
@@ -349,11 +354,15 @@ describe('src/cy/commands/files', () => {
...
-          expect(lastLog.get('error')).to.eq(err)
-          expect(lastLog.get('state')).to.eq('failed')
+          expect(fileLog.get('state')).to.eq('passed')
+          expect(fileLog.get('error')).to.be.undefined
+
+          const assertLog = logs.find((log) => log.get('name') === 'assert')
+
+          expect(assertLog.get('error')).to.eq(err)
+          expect(assertLog.get('state')).to.eq('failed')
           expect(err.message).to.eq('Timed out retrying after 50ms: expected \'foo\' to equal \'contents\'')
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/files.cy.js:372]: `cy.readFile()` successfully resolved, assertion failed.

| Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 25 22 AM|Screen Shot 2022-11-03 at 8 25 32 AM

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 26]
```diff
@@ -12,8 +21,10 @@ describe('src/cy/commands/sessions/utils.ts', () => {
 
       const consoleProps = getConsoleProps(sessionState)
 
+      logForDebugging(consoleProps)
+      expect(consoleProps.Warning).to.eq('⚠️ There are no cookies, local storage or session storage associated to this session.')
       expect(consoleProps.id).to.eq('session1')
-      expect(consoleProps.table).to.have.length(0)
+      expect(consoleProps.groups).to.have.length(0)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:27]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 31 52 AM | Screen Shot 2022-11-03 at 8 28 08 AM |

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 27]
```diff
@@ -26,12 +37,19 @@ describe('src/cy/commands/sessions/utils.ts', () => {
...
+      expect(consoleProps.groups).to.have.length(1)
+      expect(consoleProps.groups[0].name).to.eq('localhost data:')
+      expect(consoleProps.groups[0].groups).to.have.length(1)
+
+      const cookieData = consoleProps.groups[0].groups[0]
 
-      expect(cookiesTable.name).to.contain('Cookies - localhost (1)')
-      expect(cookiesTable.data).to.deep.eq(sessionState.cookies)
+      expect(cookieData.name).to.contain('Cookies - (1)')
+      expect(cookieData.items).to.deep.eq(sessionState.cookies)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:52]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 32 01 AM | Screen Shot 2022-11-03 at 8 29 08 AM

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 28]
```diff
@@ -43,13 +61,43 @@ describe('src/cy/commands/sessions/utils.ts', () => {
...
+      expect(consoleProps.groups[0].name).to.eq('localhost data:')
+      expect(consoleProps.groups[0].groups).to.have.length(1)
 
-      expect(localStorageTable.name).to.contain('Storage - localhost (1)')
-      expect(localStorageTable.data).to.have.length(1)
-      expect(localStorageTable.data).to.deep.eq([{ key: 'stor-foo', value: 's-f' }])
+      const localStorageData = consoleProps.groups[0].groups[0]
+
+      expect(localStorageData.name).to.contain('Local Storage - (1)')
+      expect(localStorageData.items).to.deep.eq({ 'stor-foo': 's-f' })
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:76]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 32 10 AM|Screen Shot 2022-11-03 at 8 29 19 AM

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 29]
```diff
@@ -43,13 +61,43 @@ describe('src/cy/commands/sessions/utils.ts', () => {
...
+      expect(consoleProps.Domains).to.eq('This session captured data from localhost.')
+
+      expect(consoleProps.groups).to.have.length(1)
+      expect(consoleProps.groups[0].name).to.eq('localhost data:')
+      expect(consoleProps.groups[0].groups).to.have.length(1)
+
+      const sessionStorageData = consoleProps.groups[0].groups[0]
+
+      expect(sessionStorageData.name).to.contain('Session Storage - (1)')
+      expect(sessionStorageData.items).to.deep.eq({ 'stor-foo': 's-f' })
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:100]: Prev didn't log session storage details

| Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 37 04 AM|Screen Shot 2022-11-03 at 8 29 30 AM

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 30]
```diff
@@ -65,18 +113,23 @@ describe('src/cy/commands/sessions/utils.ts', () => {
...
-      expect(table.data).to.deep.eq(sessionState.cookies)
+      expect(cookieData.name).to.contain('Cookies - (1)')
+      expect(cookieData.items).to.deep.eq(sessionState.cookies)
 
-      table = consoleProps.table[1]()
-      expect(table.name).to.contain('Storage - localhost (1)')
-      expect(table.data).to.have.length(1)
-      expect(table.data).to.deep.eq([{ key: 'stor-foo', value: 's-f' }])
+      expect(localStorageData.name).to.contain('Local Storage - (1)')
+      expect(localStorageData.items).to.deep.eq({ 'stor-foo': 's-f' })
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:132]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 32 17 AM|Screen Shot 2022-11-03 at 8 29 38 AM

File: packages/driver/cypress/e2e/commands/sessions/utils.cy.js [hunk 31]
```diff
@@ -94,23 +147,31 @@ describe('src/cy/commands/sessions/utils.ts', () => {
...
+
+      expect(consoleProps.groups[1].name).to.eq('example.com data:')
+      expect(consoleProps.groups[1].groups).to.have.length(1)
+
+      localStorageData = consoleProps.groups[1].groups[0]
+
+      expect(localStorageData.name).to.contain('Local Storage - (1)')
+      expect(localStorageData.items).to.deep.eq({ 'random': 'hi' })
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/utils.cy.js:174]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 32 26 AM| Screen Shot 2022-11-03 at 8 29 52 AM

File: packages/driver/cypress/e2e/commands/traversals.cy.js [hunk 32]
```diff
@@ -346,17 +346,28 @@ describe('src/cy/commands/traversals', () => {
...
+        expect(findLog.get('state')).to.eq('passed')
+        expect(findLog.get('error')).to.be.undefined
+        expect(findLog.get('$el').get(0)).to.eq(button.get(0))
+        const consoleProps = findLog.invoke('consoleProps')
 
         expect(consoleProps.Yielded).to.eq(button.get(0))
         expect(consoleProps.Elements).to.eq(button.length)
 
+        expect(assertionLog.get('state')).to.eq('failed')
+        expect(err.message).to.include(assertionLog.get('error').message)
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/traversals.cy.js:369]: Found with this test, we had missing test cases in query.cy.ts, hence the added tests

| Before | After |
| - | - |
| Screen Shot 2022-11-03 at 8 42 42 AM|Screen Shot 2022-11-03 at 8 43 09 AM

File: packages/driver/src/cy/commands/agents.ts [hunk 33]
```diff
@@ -68,7 +68,7 @@ const onInvoke = function (Cypress, obj, args) {
   const logProps: Record<string, any> = {
     name: agentName,
     message: obj.message,
-    error: obj.error,
+    state: obj.error ? 'failed' : 'passed',
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/commands/agents.ts:71]: Allows the command queue to handle reporting the error. This is a weird one in general because of how stubs can be created. Fake call throughs with assertions are where this was needed. It's odd because this is logged after the sync func completes, but if it's an async func or a stubbed API this appears to be fine.
Given:
```js
 validate.callsFake(() => {
    expect(true).to.be.false
  })

cy.sessoin('id', () =>, { validate })
```

| Without Change | With Change |
| - | - |
| Screen Shot 2022-11-03 at 8 49 12 AM|Screen Shot 2022-11-03 at 8 49 41 AM

File: packages/driver/src/cy/commands/querying/within.ts [hunk 34]
```diff
@@ -23,16 +23,14 @@ export default (Commands, Cypress, cy, state) => {
...
-    const restoreCmdIndex = state('index') + 1
+    const restoreCmdIndex = cy.queue.index + 1
 
     cy.queue.insert(restoreCmdIndex, $Command.create({
       args: [subject],
       name: 'within-restore',
       fn: (subject) => subject,
     }))
 
-    state('index', restoreCmdIndex)
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/commands/querying/within.ts:34]: The queue handles moving on to the next item, which is the commands that are added from the within callback.

File: packages/driver/cypress/e2e/commands/assertions.cy.js (hunk 11 above)
Comment (mjhenkes) [reply packages/driver/cypress/e2e/commands/assertions.cy.js:371]: I'm curious. How is `this.logs` undefined when it's defined above?

File: packages/driver/src/cy/commands/sessions/index.ts [hunk 35]
```diff
@@ -159,29 +162,42 @@ export default function (Commands, Cypress, cy) {
...
+                    Step: statusMap.stepName(step),
+                    Error: err?.stack || err?.message,
+                  }
+                },
+              })
+
               setSessionLogStatus('failed')
 
-              $errUtils.modifyErrMsg(err, `\n\nThis error occurred while creating session. Because the session setup failed, we failed the test.`, _.add)
+              $errUtils.modifyErrMsg(err, `\n\nThis error occurred while creating the session. Because the session setup failed, we failed the test.`, _.add)
```
Comment (emilyrohrbough) [inline packages/driver/src/cy/commands/sessions/index.ts]: Fix Error Recreating
|Before | After |
|-- | --|
|Screen Shot 2022-11-03 at 9 05 32 AM|Screen Shot 2022-11-03 at 9 01 27 AM

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 36]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+          cy.get('@example_test')
+          .find('.attempt-error-region')
+          .contains('Expected to find element')
+          .contains(recreatedErrPostfix)
+        })
+
+        describe('failed validation', () => {
+          [
+            {
+              testCase: 'has failing Cypress command',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:662]: **Before**

https://user-images.githubusercontent.com/14099737/199744672-16ebfb96-d73e-4a03-b7f9-7217a4996d11.mov

**After** 

https://user-images.githubusercontent.com/14099737/199744826-2b7aeffb-d37e-4e04-af76-3cf4e01e0fce.mov

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 37]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+              systemTestTitle: 'validate - has failing Cypress command',
+              errMessage: 'failed because it requires a DOM element',
+            },
+            {
+              testCase: 'command yields false',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:667]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 9 19 17 AM|Screen Shot 2022-11-03 at 9 19 41 AM

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 38]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+              systemTestTitle: 'validate - command yields false',
+              errMessage: 'callback yielded false.',
+            },
+            {
+              testCase: 'has multiple commands and yields false',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:672]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 9 20 42 AM|Screen Shot 2022-11-03 at 9 20 52 AM

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 39]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+              systemTestTitle: 'validate - has multiple commands and yields false',
+              errMessage: 'callback yielded false.',
+            },
+            {
+              testCase: 'rejects with false',
+              systemTestTitle: 'validate - rejects with false',
+              errMessage: 'rejected with false.',
+            },
+            {
+              testCase: 'promise resolved false',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:682]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 9 23 56 AM|Screen Shot 2022-11-03 at 9 24 12 AM

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 40]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+              systemTestTitle: 'validate - command yields false',
+              errMessage: 'callback yielded false.',
+            },
+            {
+              testCase: 'has multiple commands and yields false',
+              systemTestTitle: 'validate - has multiple commands and yields false',
+              errMessage: 'callback yielded false.',
+            },
+            {
+              testCase: 'rejects with false',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:677]: | Before | After |
| - | - |
| Screen Shot 2022-11-03 at 9 22 24 AM|Screen Shot 2022-11-03 at 9 22 46 AM

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts [hunk 41]
```diff
@@ -315,34 +313,375 @@ describe('runner/cypress sessions.ui.spec', {
...
+              systemTestTitle: 'validate - rejects with false',
+              errMessage: 'rejected with false.',
+            },
+            {
+              testCase: 'promise resolved false',
+              systemTestTitle: 'validate - promise resolves false',
+              errMessage: 'promise resolved false.',
+            },
+            {
+              testCase: 'throws an error',
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/sessions.ui.cy.ts:687]: Looks like I have lost the stack trace.. But still better

**Before**

https://user-images.githubusercontent.com/14099737/199747581-3f6d600c-c0e7-4067-b571-2033fc582e9a.mov

**After**

https://user-images.githubusercontent.com/14099737/199747622-d31788fb-92c7-4c29-91a3-fdfb2acbec21.mov

File: packages/driver/cypress/e2e/commands/assertions.cy.js (hunk 11 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/commands/assertions.cy.js:371]: I seemed to happen it was when I'd change a file or the spec file and Cypress would start to rerun the spec. 🤷🏻‍♀️Maybe the previous cy.on listener is still attached when the page is loading?? Seems a bit odd to me, but was tired of getting `uncaught exception` logs when debugging 😬

File: packages/driver/src/cypress/state.ts [hunk 42]
```diff
@@ -31,7 +31,6 @@ export interface StateFunc {
   (k: 'runnable', v?: CypressRunnable): CypressRunnable
   (k: 'isStable', v?: boolean): boolean
   (k: 'whenStable', v?: null | (() => Promise<any>)): () => Promise<any>
-  (k: 'index', v?: number): number
```
Comment (mjhenkes) [inline packages/driver/src/cypress/state.ts:34]: yay less state 🎉

File: packages/driver/src/cypress/utils.ts [hunk 43]
```diff
@@ -397,6 +397,7 @@ export default {
   },
 
   isPromiseLike (ret) {
-    return ret && _.isFunction(ret.then)
+    // @ts-ignore
```
Comment (mjhenkes) [inline packages/driver/src/cypress/utils.ts:407]: why ignore?

File: packages/driver/src/util/queue.ts [hunk 44]
```diff
@@ -81,7 +87,7 @@ export class Queue<T> {
       }
     })
     .catch(onError)
-    .finally(onFinish)
+    .then(onFinish)
```
Comment (mjhenkes) [inline packages/driver/src/util/queue.ts:86]: Does .then fire after .catch if there is an error? I'd be a little nervous that some cleanup might not be getting handled.

File: packages/reporter/src/sessions/sessions.tsx (hunk 1 above)
Comment (mjhenkes) [reply packages/reporter/src/sessions/sessions.tsx:34]: that before is very confusing 'failed' messaging

File: packages/driver/src/util/queue.ts (hunk 44 above)
Comment (emilyrohrbough) [reply packages/driver/src/util/queue.ts:86]: No `.then` will not fire, however if we are failing the test in `onError` (error wasn't recovered) we call cleanup first: [`sessions-in-test-errors`#diff-02efec9036](https://github.com/cypress-io/cypress/compare/sessions-in-test-errors#diff-02efec9036c83904d36d921d427ce2d5801607c61a18d180ea40e061183531e1R464)

**Review by mjhenkes — APPROVED** [review]

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts (hunk 36 above)
Comment (chrisbreiding) [reply packages/app/cypress/e2e/runner/sessions.ui.cy.ts:662]: It doesn't seem correct that `cy.get()` failing is reported as an `AssertionError`. That should be a `CypressError`.

File: packages/driver/src/cypress/utils.ts (hunk 43 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/utils.ts:407]: Typescript linting was yelling at me....and since we are determine if something is a promise seemed okay to ignore 😅  this was the error:
```bash
src/cypress/utils.ts(400,55): error TS2339: Property 'then' does not exist on type 'object'.
src/cypress/utils.ts(400,81): error TS2339: Property 'catch' does not exist on type 'object'.
```

File: packages/driver/cypress/e2e/commands/files.cy.js [hunk 45]
```diff
@@ -165,23 +165,28 @@ describe('src/cy/commands/files', () => {
...
 
       it('throws when file argument is absent', function (done) {
         cy.on('fail', (err) => {
-          const { lastLog } = this
+          const { fileLog } = this
 
-          assertLogLength(this.logs, 1)
-          expect(lastLog.get('error')).to.eq(err)
-          expect(lastLog.get('state')).to.eq('failed')
+          expect(fileLog.get('error')).to.eq(err)
```
Comment (chrisbreiding) [inline packages/driver/cypress/e2e/commands/files.cy.js:191]: Why no longer assert the log length in these tests?

File: packages/driver/src/cypress/command.ts (hunk 10 above)
Comment (chrisbreiding) [reply packages/driver/src/cypress/command.ts:6]: 💯

File: packages/driver/src/cypress/stack_utils.ts [hunk 46]
```diff
@@ -482,16 +482,19 @@ const normalizedUserInvocationStack = (userInvocationStack) => {
   // add/$Chainer.prototype[key] (cypress:///../driver/src/cypress/chainer.js:30:128)
   // whereas Chromium browsers have the user's line first
   const stackLines = getStackLines(userInvocationStack)
-  const winnowedStackLines = _.reject(stackLines, (line) => {
-    // WARNING: STACK TRACE WILL BE DIFFERENT IN DEVELOPMENT vs PRODUCTOIN
+  const windowedStackLines = _.reject(stackLines, (line) => {
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/stack_utils.ts]:
```suggestion
  const nonCypressStackLines = _.reject(stackLines, (line) => {
```

"winnowed", as in "removed", was originally intended but doesn't seem appropriate now that I think about it, since we're getting the lines we want and not the removed lines.

File: packages/driver/src/cypress/stack_utils.ts [hunk 47]
```diff
@@ -482,16 +482,19 @@ const normalizedUserInvocationStack = (userInvocationStack) => {
...
     //     at cypressErr (http://localhost:3500/isolated-runner/cypress_runner.js:173123:17)
-    return line.includes('cy[name]') || line.includes('Chainer.prototype[key]') || line.includes('cy.<computed>') || line.includes('$Chainer.<computed>')
+    return line.includes('cy[name]')
+    || line.includes('Chainer.prototype[key]')
+    || line.includes('cy.<computed>')
+    || line.includes('$Chainer.<computed>')
   }).join('\n')
 
-  return normalizeStackIndentation(winnowedStackLines)
+  return normalizeStackIndentation(windowedStackLines)
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/stack_utils.ts]:
```suggestion
  return normalizeStackIndentation(nonCypressStackLines)
```

File: packages/driver/src/cypress/utils.ts (hunk 43 above)
Comment (chrisbreiding) [reply packages/driver/src/cypress/utils.ts:407]: I think the way to make TypeScript happy about this is to add `'then' in ret` and `'catch' in ret` checks before referencing `ret.then` and `ret.catch`.

File: packages/driver/src/util/queue.ts [hunk 48]
```diff
@@ -45,13 +46,18 @@ export class Queue<T> {
...
     this.queueables.length = 0
   }
 
   stop () {
     this._stopped = true
   }
 
+  hasNext () {
+    return this.index < this.length
+  }
```
Comment (chrisbreiding) [inline packages/driver/src/util/queue.ts]: This doesn't seem to be used anywhere. Is it needed?

File: packages/driver/src/cypress/command_queue.ts [hunk 49]
```diff
@@ -394,15 +445,31 @@ export class CommandQueue extends Queue<$Command> {
...
+      this.cleanup()
 
       return this.fail(err)
     }
 
     const { promise, reject, cancel } = super.run({
       onRun: next,
       onError,
-      onFinish: this.cleanup,
+      onFinish: this.run,
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/command_queue.ts:472]: The 2 layers of recursion are messing with me a bit. Could we pass `next` here instead and achieve the same thing?

File: packages/driver/cypress/e2e/commands/assertions.cy.js (hunk 11 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/commands/assertions.cy.js:371]: should we drop a comment there to explain this behavior incase someone runs into it again and thinks the optional chainer isn't necessary?

File: packages/driver/cypress/e2e/commands/assertions.cy.js (hunk 12 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/commands/assertions.cy.js:428]: If the assertion fails, I would expect an `AssertionError` to be thrown here and not a `CypressError`. What was the rason that changed? Or is it that the argument into the assertion is bad?

File: packages/driver/src/cy/commands/sessions/manager.ts [hunk 50]
```diff
@@ -10,15 +10,25 @@ import {
 type ActiveSessions = Cypress.Commands.Session.ActiveSessions
 type SessionData = Cypress.Commands.Session.SessionData
 
-const getLogProperties = (displayName) => {
+const LOGS = {
+  clearCurrentSessionData: {
+    displayName: 'Clear cookies, localStorage and sessionStorage',
+    consoleProps: {
+      Event: 'Cypress.session.clearCurrentSessionData()',
+      Details: 'Clearing the cookies, localStorage and sessionStorage across all domains. This ensures the session is created in clean browser context.',
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/sessions/manager.ts:18]:
```suggestion
      Details: 'Clearing the cookies, localStorage and sessionStorage across all domains. This ensures the session is created in a clean browser context.',
```

File: packages/driver/src/cy/commands/sessions/utils.ts [hunk 51]
```diff
@@ -97,39 +98,48 @@ const setPostMessageLocalStorage = async (specWindow, originOptions) => {
...
-    ]
   })
 
-  return {
-    id: sessState.id,
-    table: _.compact(tables),
+  const props = {
+    id: session.id,
+    ...(!groupsByDomain.length && {
+      Warning: '⚠️ There are no cookies, local storage or session storage associated to this session.',
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/sessions/utils.ts]: would this read better?
```suggestion
      Warning: '⚠️ There are no cookies, local storage nor session storage associated with this session.',
```

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts (hunk 36 above)
Comment (emilyrohrbough) [reply packages/app/cypress/e2e/runner/sessions.ui.cy.ts:662]: 👍🏻 Fixed: [cypress-io/cypress@`28f6add` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/28f6add42b8146c1fb95ea01f1e48d868d0a5f5e)

**Review by AtofStryker — COMMENTED** [review]
gave the app and driver tests a run and things didn't look to hang and appeared correctly. Just a few questions/suggestions on my end

**Comment by AtofStryker** [comment]
actually have a few failures in the app tests that I scrolled past. Is that expected currently?

**Comment by AtofStryker** [comment]
never mind I clicked something out of the frame causing a UI issue 😬

File: packages/driver/src/cypress/command_queue.ts (hunk 49 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/command_queue.ts:472]: I just retested to verify if we could use `next` instead. Its def weird, however because we are storing the promise, reject & cancel func in state to bail out, if we pass `next` here instead we don't create another a new promise chain to handle further errors:

When passing `next` | when passing `this.run`
--|--
Screen Shot 2022-11-04 at 2 08 26 PM|Screen Shot 2022-11-04 at 2 08 06 PM

File: packages/driver/src/cypress/stack_utils.ts (hunk 46 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/stack_utils.ts]: Oh thanks! figured it was a typo!

File: packages/driver/cypress/e2e/commands/files.cy.js (hunk 45 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/commands/files.cy.js:191]: We initially only collected the file log, so it didn't seem overly valuable. I'll re-add with the updates for how these are collected

File: packages/driver/cypress/e2e/commands/assertions.cy.js (hunk 12 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/commands/assertions.cy.js:428]: I thought that at first too, but this is one of our own errors:
- thrown here https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/chai.ts#L375
- error message: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/error_messages.ts#L178

File: packages/driver/cypress/e2e/commands/files.cy.js (hunk 45 above)
Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/commands/files.cy.js:191]: [`4fe9cf0` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f)

File: packages/driver/src/cypress/stack_utils.ts (hunk 46 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/stack_utils.ts]: [`4fe9cf0` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f)

File: packages/driver/src/cypress/stack_utils.ts (hunk 47 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/stack_utils.ts]: [`4fe9cf0` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f)

File: packages/driver/src/cypress/utils.ts (hunk 43 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/utils.ts:407]: https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f

File: packages/driver/src/cy/commands/sessions/manager.ts (hunk 50 above)
Comment (emilyrohrbough) [reply packages/driver/src/cy/commands/sessions/manager.ts:18]: [`4fe9cf0` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f)

File: packages/driver/src/cy/commands/sessions/utils.ts (hunk 51 above)
Comment (emilyrohrbough) [reply packages/driver/src/cy/commands/sessions/utils.ts]: [`4fe9cf0` (#24511)](https://github.com/cypress-io/cypress/pull/24511/commits/4fe9cf0ae1644bea7ea2fc00fa06d3986e63195f)

**Review by chrisbreiding — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

File: packages/app/cypress/e2e/runner/sessions.ui.cy.ts (hunk 36 above)
Comment (emilyrohrbough) [reply packages/app/cypress/e2e/runner/sessions.ui.cy.ts:662]: Reverted this change. Seeing weird issues with StackTraces. Since this change hasn't been straightforward, I removed them since its already outside of the scope of how Cypress behaves today with reporting this as an AssertionError.
