### PR TITLE
misc: replace marionette-client with geckodriver as b2g marionette client is no longer supported

### LINKED ISSUE #30217: misc: Remove Firefox marionette-client in favor of Geckodriver
### What would you like?

I would like to remove references to the forked `marionnete-client` and replace it with a modern alternative like Geckodriver

### Why is this needed?

the originally [forked/copied marionette client](https://github.com/cypress-io/marionette-client) is no longer supported by the Mozilla team ([see bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1604723)). The recommended approach is to replace the Webdriver Classic and extension methods (to add the Cypress web extension) with Geckodriver). This is a prerequisite to Webdriver BiDi support

### Other

Geckodriver will be used by Firefox with or without BiDi support as we need it to create the WebDriver Session. Cypress needs to release this change first to make sure there are no regressions with the switch from marionette to geckodriver

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #30217

### Additional details

As a precursor to supporting [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/), Cypress needs to replace the older [marionette-client](https://github.com/cypress-io/marionette-client) with [geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html). This is the current recommendation from the Mozilla team as `marionette-client` is no longer supported (see [Cypress migration bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1604723)).

Currently, the responsibilities of the current `geckodriver` implementation and the older `marionette-client`:
* To create a [`WebDriver Classic`](https://www.w3.org/TR/webdriver2/) session.
* Use `WebDriver Classic` to navigate the browser. This will be replaced by BiDi in the future.
* Use `Marionette` to install the [Cypress Web Extension](https://github.com/cypress-io/cypress/tree/develop/packages/extension).

This is outlined in the added `README` in this PR as well as some other useful information. This information will be updated as we implement `BiDi`.

NOTE: right now, the WebDriver Classic methods are implementing the spec through HTTP instead of using a package or a client. This was chosen to keep the package change minimal in this PR and we will likely be moving to some type of client to reduce the overhead needed to maintain WebDriver.  This will be either an OSS package like [webdriverio/webdriver](https://www.npmjs.com/package/webdriver) or we implement our own (work for either scoped to https://github.com/cypress-io/cypress/issues/30219)

It is worth noting that we patch the [`geckodriver`](https://github.com/webdriverio-community/node-geckodriver#readme) package to coincide with our debug logs in order to not print extraneous messages to the console that could disrupt end user experience as well as impact our system tests. We also need to patch top-level awaits to correctly build the app and feed in process args that are needed (such as the `MOZ_` prefix variables) when spawning firefox.

To consume [`GeckoDriver`](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html), this code installs the [`geckodriver`](https://github.com/webdriverio-community/node-geckodriver#readme) package, a lightweight wrapper around the [geckodriver binary](https://github.com/mozilla/geckodriver), to connect to the Firefox browser.  `geckodriver` will be downloaded automatically to the user's `tmp` directory if not already downloaded, and will be started and managed by the Cypress server.

### Bugfixes found while testing

* Windows machines not killing the Firefox browser process when user triggers `SIGINT` from `ctrl+c` in the terminal (fixed in https://github.com/cypress-io/cypress/pull/30250/commits/192204dab7c1afa77c1c635229ea35f33351481e)
* Browser no longer maximized in headed mode by default since `xulstore.json` no longer has the same effect since geckodriver is creating a full profile (fixed in https://github.com/cypress-io/cypress/pull/30250/commits/ae36a24b13f1f4b02a160b6b8bb84ae3b68ea647). this will only take effect when headed and if the user does NOT supply a width or height to the browser

### Steps to test

Unit tests have been updated to reflect the replaced client, as well as tests added for our `geckodriver` wrapper.

The `system-tests` and `integration` tests serve as a regression suite to help guarantee this change works.

Manual testing should also be completed on `linux`, `mac`, and `windows` in open/run mode permutations to verify the code and client changes work universally. The app team will be participating in a small bughunt to identify issues we may have not already found.

### How has the user experience changed?

Ideally, this change should NOT impact the end user. This is an internal swap of a client used to automate the browser and should not affect the end user in any way.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] is the bughunt completed?
- [ ] are the v8 snapshots up to date?

### CODE REVIEW

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+   *
+   * @param {string} handle - the context ID of the window handle
+   * @returns {Promise<null>}
+   */
+  async switchToWindow (handle: string): Promise<null> {
+    const switchToWindowUrl = `http://${this.#host}:${this.#port}/session/${this.sessionId}/window`
+
+    const headers = new Headers()
+
+    headers.append('Content-Type', 'application/json')
```
Comment (cacieprins) [inline packages/server/lib/browsers/webdriver-classic/index.ts]: Since this is static, headers can be an object literal inlined to the fetch `RequestInit` param

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 2]
```diff
@@ -0,0 +1,272 @@
...
+  }
+
+  /**
+   * Gets available windows handles in the browser. The order in which the window handles are returned is arbitrary.
+   * @see https://www.w3.org/TR/webdriver2/#get-window-handles
+   *
+   * @returns {Promise<string[]>} All the available top-level contexts/handles
+   */
+  async getWindowHandles (): Promise<string[]> {
+    const getWindowHandles = `http://${this.#host}:${this.#port}/session/${this.sessionId}/window/handles`
```
Comment (cacieprins) [inline packages/server/lib/browsers/webdriver-classic/index.ts:110]: `sessionId` can be null - is this still valid?

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 3]
```diff
@@ -0,0 +1,272 @@
+import debugModule from 'debug'
+// using cross fetch to make unit testing easier to mock
+import crossFetch from 'cross-fetch'
+
+const debug = debugModule('cypress:server:browsers:webdriver')
+
+type InstallAddOnArgs = {
+  extensionPath: string
+  isTemporary: boolean
+}
```
Comment (cacieprins) [inline packages/server/lib/browsers/webdriver-classic/index.ts]:
```suggestion
type InstallAddOnArgs = {
  path: string
  temporary: boolean
}
```
simplifies the fn body of `installAddOn`

File: packages/server/test/unit/browsers/firefox_spec.ts [hunk 4]
```diff
@@ -99,29 +66,24 @@ describe('lib/browsers/firefox', () => {
...
+    this.browserInstance = {
+      // should be high enough to not kill any real PIDs
+      pid: Number.MAX_SAFE_INTEGER,
+    }
 
-      this.options = {
-        onError: () => {},
-      }
-    })
+    sinon.stub(geckoDriver.GeckoDriver, 'create').returns(this.browserInstance)
```
Comment (cacieprins) [inline packages/server/test/unit/browsers/firefox_spec.ts]: A lot of these GeckoDriver and WebDriverClassic methods are async - stubs should probably `resolves` instead of `returns`

File: packages/server/test/unit/browsers/firefox_spec.ts [hunk 5]
```diff
@@ -99,29 +66,24 @@ describe('lib/browsers/firefox', () => {
...
 
-    it('calls connectToNewSpec in firefoxUtil', function () {
-      sinon.stub(firefoxUtil, 'connectToNewSpec').withArgs(50505, this.options, this.automation).resolves()
+    sinon.stub(webDriverClassic.WebDriverClassic.prototype, 'createSession').returns({ capabilities: {
```
Comment (cacieprins) [inline packages/server/test/unit/browsers/firefox_spec.ts]: stubbing the constructor and returning a `SinonStubbedInstance` from it may make this a little easier, rather than stubbing out the prototype - that way you can be sure of which instance they're being called on in your assertions below


e.g., 

```
wdInstance = sinon.createStubInstance(webdriverClassic.WebDriverClassic, {
  createSession: Promise.resolve({...etc}),
})

sinon.stub(webDriverClassic, 'WebDriverClassic').callsFake(() => wdInstance)

/* .... */

expect(wdInstance.navigate).to.have.been.calledWith('about:blank')

```

File: cli/CHANGELOG.md [hunk 6]
```diff
@@ -13,6 +13,7 @@ _Released 9/24/2024 (PENDING)_
 
 **Misc:**
 
+- Cypress now consumes [geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html) to help automate the Firefox browser instead of [marionette-client](https://github.com/cypress-io/marionette-client). Addresses [#30217](https://github.com/cypress-io/cypress/issues/30217). Addressed in [#30250](https://github.com/cypress-io/cypress/pull/30250).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]: I don't think you need both the Addresses and Addressed in. I think Addressed in is only there if there's no corresponding issue for the PR

File: cli/lib/exec/spawn.js [hunk 7]
```diff
@@ -236,6 +237,21 @@ module.exports = {
...
 
+        if (isPlatform('win32')) {
+          const rl = readline.createInterface({
+            input: process.stdin,
+            output: process.stdout,
+          })
+
+          // on windows, SIGINT does not propagate to the child process when ctrl+c is pressed
+          // this makes sure all nested processes are closed(ex: firefox inside the server)
+          rl.on('SIGINT', function () {
```
Comment (ryanthemanuel) [inline cli/lib/exec/spawn.js:248]: Do we need to handle anything else?  `SIGTERM`? `SIGUSR1` or `SIGUSR2`?

File: cli/CHANGELOG.md (hunk 6 above)
Comment (AtofStryker) [reply cli/CHANGELOG.md]: I think semantic pull request was complaining about it because I wanted the 'addressed in', but complained that I didnt link the issue. I should be able to remove the later

File: cli/lib/exec/spawn.js (hunk 7 above)
Comment (AtofStryker) [reply cli/lib/exec/spawn.js:248]: not that I am aware of but Im not sure on all the scenarios the process could be killed in the terminal. Either way it should be pretty easy to add support for if needed if a regression is detected that we missed

File: cli/package.json [hunk 8]
```diff
@@ -60,6 +60,7 @@
     "semver": "^7.5.3",
     "supports-color": "^8.1.1",
     "tmp": "~0.2.3",
+    "tree-kill": "1.2.2",
```
Comment (AtofStryker) [inline cli/package.json:63]: @jennifer-shehane should we mention in the changelog that we are adding the `tree-kill` dependency to the CLI since we mention dependency updates?

File: packages/server/lib/browsers/firefox.ts [hunk 9]
```diff
@@ -546,40 +509,116 @@ export async function open (browser: Browser, url: string, options: BrowserLaunc
...
+      },
+    },
   })
 
+  const wdcInstance = new WebDriverClassic('127.0.0.1', geckoDriverPort)
+
+  debug('launch in firefox', { url, args: launchOptions.args })
+
+  const capabilitiesToSend = {
+    // browser capabilities are going here as exact
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/firefox.ts]: I'm not sure what this comment is saying.

File: packages/server/lib/browsers/firefox.ts [hunk 10]
```diff
@@ -546,40 +509,116 @@ export async function open (browser: Browser, url: string, options: BrowserLaunc
...
+        // @see https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#moz-debuggeraddress
+        // we specify the debugger address option for Webdriver, which will return us the CDP address when the capability is returned.
+        'moz:debuggerAddress': true,
+      },
+    },
+  }
+
   try {
-    browserCriClient = await firefoxUtil.setup({ automation, extensions: launchOptions.extensions, url, foxdriverPort, marionettePort, remotePort, onError: options.onError })
+    debug(`sending capabilities %s`, JSON.stringify(capabilitiesToSend.capabilities))
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/firefox.ts]: Maybe:

```suggestion
    debug(`creating session %s`, JSON.stringify(capabilitiesToSend.capabilities))
```

File: packages/server/lib/browsers/geckodriver/index.ts [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+  marionetteHost: string
+  marionettePort: number
+  webdriverBidiPort: number
+  profilePath: string
+  binaryPath: string
+  spawnOpts?: SpawnOpt
+}
+
+/**
+ * Class with static methods of the GeckoDriver as it returns a ChildProcess
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/geckodriver/index.ts]: I think this comment could be re-worded.

File: packages/server/lib/browsers/geckodriver/index.ts [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+ */
+export class GeckoDriver {
+  // We resolve this package in such a way to packherd can discover it, meaning we are re-declaring the types here to get typings support =(
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/geckodriver/index.ts]:
```suggestion
  // We resolve this package in such a way that packherd can discover it, meaning we are re-declaring the types here to get typings support =(
```

File: packages/server/lib/browsers/firefox.ts (hunk 9 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts]: I can probably just delete it

File: packages/server/lib/browsers/firefox.ts (hunk 10 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts]: maybe `creating session with capabilities`?

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 13]
```diff
@@ -0,0 +1,272 @@
...
+
+      return getWindowHandlesRespBody.value
+    } catch (e) {
+      debug(`unable to get classic webdriver window handles: ${e}`)
+      throw e
+    }
+  }
+
+  /**
+   * Switching window will select session's current top-level browsing context used as the target for all subsequent commands.
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/webdriver-classic/index.ts]:
```suggestion
   * Switching windows will select the session's current top-level browsing context as the target for all subsequent commands.
```

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 14]
```diff
@@ -0,0 +1,272 @@
...
+    }
+  }
+
+  /**
+   * maximizes the current window
+   * @see https://www.w3.org/TR/webdriver2/#maximize-window
+   *
+   * @returns {Promise<null>}
+   */
+  async maximizeWindow (): Promise<null> {
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/webdriver-classic/index.ts:171]: A lot of this code seems similar from method to method. Wondering if we can DRY it up a bit.

File: system-tests/projects/plugin-before-browser-launch-deprecation/cypress/e2e/app.cy.js [hunk 15]
```diff
@@ -8,5 +8,5 @@ it('asserts on browser args', () => {
     return
   }
 
-  cy.task('assertPsOutput')
+  cy.task('assertPsOutput', Cypress.browser.name)
```
Comment (ryanthemanuel) [inline system-tests/projects/plugin-before-browser-launch-deprecation/cypress/e2e/app.cy.js:11]: Why was this needed again?

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 14 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts:171]: probably. I don't think its worth the effort though since this code is going to be removed in the near future

File: system-tests/projects/plugin-before-browser-launch-deprecation/cypress/e2e/app.cy.js (hunk 15 above)
Comment (AtofStryker) [reply system-tests/projects/plugin-before-browser-launch-deprecation/cypress/e2e/app.cy.js:11]: because we cannot pass extraneous arguments into the webdriver session or firefox will fail to start

File: packages/server/lib/browsers/geckodriver/README.md [hunk 16]
```diff
@@ -0,0 +1,35 @@
+# GeckoDriver
+
+## Purpose
+
+Cypress uses [GeckoDriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html) to drive [classic WebDriver](https://www.w3.org/TR/webdriver2/) methods, as well as interface with Firefox's [Marionette Protocol](https://firefox-source-docs.mozilla.org/testing/marionette/Intro.html). This is necessary to automate the Firefox browser in such cases:
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/geckodriver/README.md]:
```suggestion
Cypress uses [GeckoDriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html) to drive [classic WebDriver](https://www.w3.org/TR/webdriver2/) methods, as well as interface with Firefox's [Marionette Protocol](https://firefox-source-docs.mozilla.org/testing/marionette/Intro.html). This is necessary to automate the Firefox browser in the follow cases:
```

File: packages/server/lib/browsers/geckodriver/README.md [hunk 17]
```diff
@@ -0,0 +1,35 @@
...
+* Patch top-level awaits to correctly build the app.
+* Pass process spawning arguments to the geckodriver process (which is a child process of the main process) in order to set `MOZ_` prefixed environment variables in the browser. These cannot be set through the [env capability](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#env_object) and must be done through `geckodriver` as `geckodriver` spawns the `firefox` process. Please see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1604723#c20) for more details.
+
+Currently, since the use of WebDriver Classic is so miniscule, the methods are implemented in an HTTP fashion inside the [WebDriver Classic Class](../webdriver-classic/index.ts). It's important to note that, unlike Chrome, Firefox is launched via the WebDriver [newSession command](https://www.w3.org/TR/webdriver2/#new-session) As BiDi develop occurs and to reduce maintenance cost, using an already implemented client like [`webdriver`](https://www.npmjs.com/package/webdriver) will be explored.
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/geckodriver/README.md]:
```suggestion
Currently, since the use of WebDriver Classic is so miniscule, the methods are implemented using direct fetch calls inside the [WebDriver Classic Class](../webdriver-classic/index.ts). It's important to note that, unlike Chrome, Firefox is launched via the WebDriver [newSession command](https://www.w3.org/TR/webdriver2/#new-session) As BiDi development occurs and to reduce maintenance cost, using an already implemented client like [`webdriver`](https://www.npmjs.com/package/webdriver) will be explored.
```

Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/README.md]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/geckodriver/README.md (hunk 16 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/README.md]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 13 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/geckodriver/index.ts (hunk 12 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/index.ts]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/geckodriver/index.ts (hunk 11 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/index.ts]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/firefox.ts (hunk 10 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts]: addressed in fb54eaaa9a

File: packages/server/lib/browsers/firefox.ts (hunk 9 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts]: deleted in fb54eaaa9a

File: cli/CHANGELOG.md (hunk 6 above)
Comment (AtofStryker) [reply cli/CHANGELOG.md]: removed the 'addressed in' in d7fba61c6f

File: packages/launcher/lib/browsers.ts [hunk 18]
```diff
@@ -9,6 +9,7 @@ export const debug = Debug('cypress:launcher:browsers')
 /** starts a found browser and opens URL if given one */
 export type LaunchedBrowser = cp.ChildProcessByStdio<null, Readable, Readable>
 
+// NOTE: firefox uses geckodriver to launch the browser
```
Comment (whimboo) [inline packages/launcher/lib/browsers.ts]: Just to clarify Firefox doesn't use geckodriver but it's the other way around. So maybe the following change would be clearer:

```suggestion
// NOTE: For Firefox geckodriver is used to launch the browser
```

File: packages/server/lib/browsers/firefox.ts [hunk 19]
```diff
@@ -546,40 +510,115 @@ export async function open (browser: Browser, url: string, options: BrowserLaunc
...
-    // sets headless resolution to 1280x720 by default
-    // user can overwrite this default with these env vars or --height, --width arguments
+  // resolution of exactly 1280x720
+  // (height must account for firefox url bar, which we can only shrink to 1px ,
+  // and the total size of the window url and tab bar, which is 85 pixels for a total offset of 86 pixels)
+  const BROWSER_ENVS = {
+    MOZ_REMOTE_SETTINGS_DEVTOOLS: '1',
     MOZ_HEADLESS_WIDTH: '1280',
-    MOZ_HEADLESS_HEIGHT: '721',
+    MOZ_HEADLESS_HEIGHT: '806',
```
Comment (whimboo) [inline packages/server/lib/browsers/firefox.ts:521]: Above you mention a total offset of 86px but this change is 85px only. Not sure if that matters but wanted to just mention.

File: packages/server/lib/browsers/firefox.ts [hunk 20]
```diff
@@ -546,40 +510,115 @@ export async function open (browser: Browser, url: string, options: BrowserLaunc
...
+  }
+
+  debug('launching geckodriver with browser envs %o', BROWSER_ENVS)
+
+  // create the geckodriver process, which we will use WebDriver Classic to open the browser
+  const geckoDriverInstance = await GeckoDriver.create({
+    host: '127.0.0.1',
+    port: geckoDriverPort,
+    marionetteHost: '127.0.0.1',
+    marionettePort,
```
Comment (whimboo) [inline packages/server/lib/browsers/firefox.ts:532]: I assume this can be defined by the user? Please note that if set to `0` Firefox will automatically select a free port on the system.

File: packages/server/lib/browsers/geckodriver/README.md [hunk 21]
```diff
@@ -0,0 +1,35 @@
+# GeckoDriver
+
+## Purpose
+
+Cypress uses [GeckoDriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html) to drive [classic WebDriver](https://www.w3.org/TR/webdriver2/) methods, as well as interface with Firefox's [Marionette Protocol](https://firefox-source-docs.mozilla.org/testing/marionette/Intro.html). This is necessary to automate the Firefox browser in the following cases:
```
Comment (whimboo) [inline packages/server/lib/browsers/geckodriver/README.md]: The living document you can actually find at https://w3c.github.io/webdriver. This is always up-to-date. The reference you used above might not always reflect the current state (it still misses the notion of navigables) and as you can see is already outdated - last update in July this year.

File: packages/server/lib/browsers/geckodriver/README.md [hunk 22]
```diff
@@ -0,0 +1,35 @@
...
+
+Since we patch the [`geckodriver`](https://github.com/webdriverio-community/node-geckodriver#readme) package, we [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) the dependency. This mostly works with sub-dependencies, but one of the dependencies, `pump@^3.0.0` (from `geckodriver` -> `tar-fs` -> `pump`) is missing from the binary. To workaround this, we install `pump` in `@packages/server` and `nohoist` the dependency so it is available in the binary as a production dependency.
+
+## Debugging
+
+To help debug `geckodriver` and `firefox`, the `DEBUG=cypress-verbose:server:browsers:geckodriver` can be used when launching `cypress`. This will
+ * Enable full `stdout` and `stderr` for `geckodriver` (including startup time) and the `firefox` process. The logs will **NOT** be truncated so they may get quite long.
```
Comment (whimboo) [inline packages/server/lib/browsers/geckodriver/README.md:32]: Please note that geckodriver also accepts a `-vv` argument which will enable [trace level logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) for Firefox as well. This is pretty helpful in case you see some broken behavior or misbehavior by our implementation which needs to be investigated.

File: packages/server/lib/browsers/geckodriver/index.ts [hunk 23]
```diff
@@ -0,0 +1,119 @@
...
+        spawnOpts: opts.spawnOpts || {},
+      })
+
+      // using a require statement to make this easier to test with mocha/mockery
+      const waitPort = require('wait-port')
+
+      await Bluebird.resolve(waitPort({
+        port: opts.port,
+        // add 1 second to the timeout so the timeout throws first if the limit is reached
+        timeout: timeout + 1000,
```
Comment (whimboo) [inline packages/server/lib/browsers/geckodriver/index.ts:94]: I assume this is waiting for a connection? Geckodriver itself waits up to 60s internally after Firefox is launched for the socket to Marionette and then fails & kills the browser process. Not sure if that would help you if you have a shorter timeout. There is [no command line argument for that yet](https://github.com/mozilla/geckodriver/issues/1660).

File: packages/server/lib/browsers/webdriver-classic/index.ts [hunk 24]
```diff
@@ -0,0 +1,272 @@
...
+namespace WebDriver {
+  export namespace Session {
+    export type NewResult = {
+      capabilities: {
+        acceptInsecureCerts: boolean
+        browserName: string
+        browserVersion: string
+        platformName: string
+        pageLoadStrategy: 'normal'
+        strictFileInteractability: boolean
```
Comment (whimboo) [inline packages/server/lib/browsers/webdriver-classic/index.ts:21]: There is also the `unhandledPromptBehavior` you probably might be interested in and I don't see listed here.

**Review by whimboo — COMMENTED** [review]
Hi @AtofStryker. It's great to see the progress you've made over the past days. I hope it's fine when I just added a couple of minor comments and suggestions. You can find those all inline. I'm kinda looking forward to see it working, and especially the removal of the Marionette JS client usage.

File: packages/server/lib/browsers/firefox.ts (hunk 19 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts:521]: It's 85 plus whatever the height for the shrunken url bar, which is the 1 px already aded to the 721 here

File: packages/server/lib/browsers/firefox.ts (hunk 20 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts:532]: we define this on their behalf. We just find an available port on the machine to run it

File: packages/server/lib/browsers/geckodriver/README.md (hunk 21 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/README.md]: good to know! I will update the README (and other) references from `https://www.w3.org/TR/webdriver2/` to `https://w3c.github.io/webdriver/`

File: packages/server/lib/browsers/geckodriver/index.ts (hunk 23 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/index.ts:94]: correct. This is just waiting for geckodriver to be running before we proceed. If we reach the timeout threshold, we will the process if once exists, which ultimately just results in the app process tree being killed

File: packages/server/lib/browsers/geckodriver/README.md (hunk 22 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/README.md:32]: does this have the same effect as setting `--log=trace`?

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 24 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts:21]: added the type in fdcde2dd7c

File: packages/launcher/lib/browsers.ts (hunk 18 above)
Comment (AtofStryker) [reply packages/launcher/lib/browsers.ts]: updated in fdcde2dd7c

**Comment by AtofStryker** [comment]
> Hi @AtofStryker. It's great to see the progress you've made over the past days. I hope it's fine when I just added a couple of minor comments and suggestions. You can find those all inline. I'm kinda looking forward to see it working, and especially the removal of the Marionette JS client usage.

Thank you for the review @whimboo! Once we get this in, I should have more updates to post on the bugzilla thread as far as progress / next steps.

File: packages/server/lib/browsers/geckodriver/README.md (hunk 21 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/README.md]: updated in fdcde2dd7c

File: packages/server/lib/browsers/geckodriver/README.md (hunk 22 above)
Comment (whimboo) [reply packages/server/lib/browsers/geckodriver/README.md:32]: Yes, one provides a string while for easier use we added the `-v[v]` argument.

File: packages/server/lib/browsers/geckodriver/index.ts (hunk 23 above)
Comment (whimboo) [reply packages/server/lib/browsers/geckodriver/index.ts:94]: Just to be sure it's waiting for geckodriver running and allowing connections on its HTTP port, right? Thanks.

Comment (AtofStryker) [reply packages/server/lib/browsers/geckodriver/index.ts:94]: yes that is correct to the best of my knowledge. [wait-port](https://www.npmjs.com/package/wait-port) should wait for the http endpoint on the port to response as well as the record to be available in the DNS.

Comment (whimboo) [reply packages/server/lib/browsers/geckodriver/index.ts:94]: Thanks.

File: packages/launcher/lib/browsers.ts [hunk 25]
```diff
@@ -9,6 +9,7 @@ export const debug = Debug('cypress:launcher:browsers')
 /** starts a found browser and opens URL if given one */
 export type LaunchedBrowser = cp.ChildProcessByStdio<null, Readable, Readable>
 
+// NOTE: For Firefox geckodriver is used to launch the browser
```
Comment (ryanthemanuel) [inline packages/launcher/lib/browsers.ts]:
```suggestion
// NOTE: Firefox geckodriver is used to launch the browser
```

**Review by ryanthemanuel — APPROVED** [review]

File: packages/launcher/lib/browsers.ts (hunk 25 above)
Comment (mschile) [reply packages/launcher/lib/browsers.ts]: Or

```suggestion
// NOTE: For Firefox, geckodriver is used to launch the browser
```

File: packages/server/lib/browsers/firefox.ts [hunk 26]
```diff
@@ -406,36 +387,27 @@ async function recordVideo (videoApi: RunModeVideoApi) {
...
   if (browser.isHeadless) {
     defaultLaunchOptions.args.push('-headless')
     // we don't need to specify width/height since MOZ_HEADLESS_ env vars will be set
     // and the browser will spawn maximized. The user may still supply these args to override
-    // defaultLaunchOptions.args.push('--width=1920')
-    // defaultLaunchOptions.args.push('--height=1081')
+    // defaultLaunchOptions.args.push('-width=1920')
+    // defaultLaunchOptions.args.push('-height=1081')
+  } else if (os.platform() === 'win32' || os.platform() === 'darwin') {
+    // lets the browser come into focus. Only works on Windows or Mac
```
Comment (mschile) [inline packages/server/lib/browsers/firefox.ts:409]: Maybe a small blurb on what happens in `linux` if you pass it so if someone in the future tests is out they know what to look for. Does firefox still come to the foreground? If so, maybe mention that as well.

File: packages/server/patches/geckodriver+4.4.2.patch [hunk 27]
```diff
@@ -0,0 +1,311 @@
...
+-import logger from '@wdio/logger';
++import debugModule from 'debug';
+ import { download as downloadDriver } from './install.js';
+ import { hasAccess, parseParams } from './utils.js';
+ import { DEFAULT_HOSTNAME } from './constants.js';
+-const log = logger('geckodriver');
++const debug = debugModule('cypress-verbose:server:browsers:geckodriver');
+ export async function start(params) {
+-    const { cacheDir, customGeckoDriverPath, ...startArgs } = params;
++    const { cacheDir, customGeckoDriverPath, spawnOpts, ...startArgs } = params;
```
Comment (mschile) [inline packages/server/patches/geckodriver+4.4.2.patch:252]: Looks like your contribution has also been released so we can probably remove this portion of the patch.

**Review by whimboo — APPROVED** [review]
As an outsider who doesn't know the code I cannot give a real code review, but the changes look fine to me from the geckodriver usage perspective.

Thanks again for working on it!

**Review by mschile — APPROVED** [review]

File: packages/server/patches/geckodriver+4.4.2.patch (hunk 27 above)
Comment (AtofStryker) [reply packages/server/patches/geckodriver+4.4.2.patch:252]: im gonna patch this in with https://github.com/cypress-io/cypress/issues/30301 since I need to update it anyway

File: packages/server/lib/browsers/firefox.ts (hunk 26 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/firefox.ts:409]: added in 66b5de67fe

File: packages/launcher/lib/browsers.ts (hunk 25 above)
Comment (AtofStryker) [reply packages/launcher/lib/browsers.ts]: updated in 66b5de67fe

File: packages/server/lib/browsers/geckodriver/index.ts [hunk 28]
```diff
@@ -0,0 +1,122 @@
...
+        output: debugModule.enabled(GECKODRIVER_DEBUG_NAMESPACE_VERBOSE) ? 'dots' : 'silent',
+      })).timeout(timeout)
+
+      debug('geckodriver started!')
+
+      // For whatever reason, we NEED to bind to stderr/stdout in order
+      // for the geckodriver process not to hang, even though the event effectively
+      // isn't doing anything without debug logs enabled.
+      geckoDriverChildProcess.stdout?.on('data', (buf) => {
```
Comment (AtofStryker) [inline packages/server/lib/browsers/geckodriver/index.ts:103]: @whimboo do you have any idea why the above comment would happen? @mschile and I tried gating the `stdout`/`stderr` behind an if statement and it looks to cause the process to almost freeze (is still running but appears stuck). We tested this on Firefox 125/130 with geckodriver `0.35.0`. Is it possible the driver is timing out or something like that?

**Review by cacieprins — CHANGES_REQUESTED** [review]

File: packages/server/test/unit/browsers/firefox_spec.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/server/test/unit/browsers/firefox_spec.ts]: this should be addressed in 91442cddb9de7869b9d12caf3c26fd45f05e85dd

File: packages/server/test/unit/browsers/firefox_spec.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/server/test/unit/browsers/firefox_spec.ts]: this should be addressed in 91442cddb9de7869b9d12caf3c26fd45f05e85dd

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts]: addressed in 721100a489

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts:110]: I don't think so anymore. I set it to null when ending the session but since we have to wait for that and we just kill the process, I removed the end session method. So this is just a string now. Fixed in 721100a489

File: packages/server/lib/browsers/webdriver-classic/index.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/server/lib/browsers/webdriver-classic/index.ts]: updated in 721100a489. should make the cutover to [webdriver](https://www.npmjs.com/package/webdriver) cleaner too

**Review by cacieprins — APPROVED** [review]

File: packages/server/lib/browsers/geckodriver/index.ts (hunk 28 above)
Comment (whimboo) [reply packages/server/lib/browsers/geckodriver/index.ts:103]: No I don't know why that happens. If you may have the time and could create a minimal stand-alone testcase to reproduce this behavior it would be great. We haven't heard about it yet. 

One thing which could happen is if a pipe was setup for stdout/stderr but nothing is read from it. That means that geckodriver will run into an overflow slowing down massively first. We had something similar in the past for Puppeteer when logging was enabled but the pipe was not read. It was fixed via https://github.com/puppeteer/puppeteer/pull/7644.

File: cli/package.json (hunk 8 above)
Comment (jennifer-shehane) [reply cli/package.json:63]: I can't recall adding a line for added dependencies before
