### PR TITLE
Use win.destroy to destroy Electron windows, log more events

### LINKED ISSUE #2118: Electron browser hangs/errors on apps with window.onbeforeunload alerts
### Current behavior:
When running a test using the Electron browser on a webpage that contains a `window.onbeforeunload` script and trying to navigate away, Cypress will fail to load the next page. The test will eventually fail after a PageLoadTimeout exception. This occurs when using any kind of navigation such as `cy.reload()`, `cy.visit()`, or interacting with an element that contains an `href` linking to somewhere else. 

Test run with Electron 59:
screen shot 2018-07-10 at 10 41 18 am

### Desired behavior:
Test run with Chrome 67:
screen shot 2018-07-10 at 10 37 28 am

### Steps to reproduce:

```js
describe('Electron 59 alert prompt bug', function() {
  it('Should navigate away from the page', function() {
    cy.on('window:confirm', function() {
      return true;
    });
    cy.visit('http://localhost:8080/');
    cy.visit('http://localhost:8080/form');
  });
  it('Should reload the page', function() {
    cy.visit('http://localhost:8080/');
    cy.reload();
  });
});
```

The page under test needs to contain a `window.onbeforeunload` function which alters the returnValue. To reproduce, I use `http-server` to serve a barebones HTML file
```html
<!DOCTYPE html>

<script>
  window.onbeforeunload = function (e) {
    e.returnValue = 'Dialog';
    return;
  }
</script>
```

### Versions
Cypress: `3.0.2`
MacOS: `High Sierra 10.13.5`
Browsers: `Chrome 67`, `Electron 59`

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #2118

### User facing changelog

Fixed a long-standing bug where runs using Electron would sometimes hang at the end if there is an `onbeforeload` dialog blocking the window from closing.

### Additional details

- Before, we used `win.close`, which is just like clicking X on the window - if an `onbeforeload` handler is triggered, it will wait for that to be resolved before `closed` is emitted and the window is really closed
- With this PR...
	- `win.destroy` is used to kill the window, which is analogous to how we `cp.kill` chrome's process
	- Child windows will be `win.destroy`d once the parent closes
	- Added logs for `close, responsive, session-end, unresponsive` events

#### Before

Logs would continue on forever after

Screen Shot 2019-11-07 at 9 33 37 AM

#### After

Screen Shot 2019-11-07 at 9 37 33 AM

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/server/lib/browsers/electron.coffee [hunk 1]
```diff
@@ -62,6 +71,12 @@ module.exports = {
           _win.on "close", ->
             if not child.isDestroyed()
               child.close()
+
+            ## give the child up to 1 second to close, then destroy it
+            setTimeout ->
+              if not child.isDestroyed()
+                child.destroy()
+            , 1000
```
Comment (brian-mann) [inline packages/server/lib/browsers/electron.coffee]: let's just always destroy the `child` window until we give users new API's to programmatically control whether or not they want the browser to accept the `beforeunload` dialog

**Comment by jennifer-shehane** [comment]
The situations Brian is mentioning that require coverage in tests:

```js
window.onbeforeunload = function(){
  return 'Are you sure you want to leave?';
};
```

```js
window.addEventListener('beforeunload', function(){
  return 'Are you sure you want to leave?';
};
```

**Comment by flotwig** [comment]
Ok, I think I added the appropriate tests in `packages/driver/test/cypress/integration/e2e/abort*`. @brian-mann ready for re-review
