### PR TITLE
fix: use srcRoot for angular build context

### LINKED ISSUE #24827: Unable to change the source root
### Current behavior

There is an error opening cypress component testing if the source root folder is not called "src"

In my case the "src" folder is named "ui"
The sourceRoot folder setting is updated in angular.json to reflect the folder name.

`      "root": "",
      "sourceRoot": "ui",
      "prefix": "app",`

When I open cypress and go to component testing, I get the following error.  I can reproduce this on a brnad new angular application. 

image

### Desired behavior

_No response_

### Test code to reproduce

Brand new angular app.

Change name of "src" folder to "ui"

update angular.json sourceRoot setting

open cypress

goto component tests

### Cypress Version

11.2.0

### Node version

16.15.0

### Operating System

macOS 12.5.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ZachJW34**
- Closes #24827

### User facing changelog
Fix issue with Angular CT where custom srcRoot was not being respected.

### Additional details
We were passing in `root` rather than `srcRoot`, causing some path issues.

I wasn't able to reproduce the exact issue the user is having. I'm building the binaries for this PR and will share to the user.

### Steps to test

1. `npm i @angular/cli -g` (you'll need a global version >=13 and <= 15)
2. `ng new` Choose default options
3. Rename `src` folder to `ui`
4. Rename all instances of `src` in `tsconfig.app.json` and `angular.json` to `ui`
5. Verify app still serves with `ng serve`
6. `npm i -D cypress && npx cypress open`
7. Walk through component setup, should error when loading config
8. Kill Cypress, check out this branch and run `yarn workspace @cypress/webpack-dev-server build`
9. `yarn cypress:open --project <path-to-angular-project>`
10. Click on CT, no error when loading config.

### How has the user experience changed?

https://user-images.githubusercontent.com/25158820/206742467-bbc0f1a3-e500-4eee-91a9-1be1fb0da980.mov

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: system-tests/projects/angular-custom-root/ui/main.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'
```
Comment (lmiller1990) [inline system-tests/projects/angular-custom-root/ui/main.ts:1]: I wonder if we need a basic Angular project in `project-fixtures` at some point, so we iterate over it like we do for React in system tests, testing against each supported major :thinking:

File: npm/webpack-dev-server/src/helpers/angularHandler.ts [hunk 2]
```diff
@@ -217,7 +217,7 @@ function createFakeContext (projectRoot: string, defaultProjectConfig: Cypress.A
     getProjectMetadata: () => {
       return {
         root: defaultProjectConfig.root,
-        sourceRoot: defaultProjectConfig.root,
```
Comment (lmiller1990) [inline npm/webpack-dev-server/src/helpers/angularHandler.ts:220]: Did this API change between majors? Should we check `defaultProjectConfig.root ?? defaultProjectConfig.sourceRoot`

**Review by lmiller1990 — APPROVED** [review]
Some QoL comments, no obvious problems - sure would be nice to see if this works for the user.

It's also possible

File: npm/webpack-dev-server/src/helpers/angularHandler.ts (hunk 2 above)
Comment (ZachJW34) [reply npm/webpack-dev-server/src/helpers/angularHandler.ts:220]: No it didn't change, I believe it was just a mistake on our part.

File: system-tests/projects/angular-custom-root/ui/main.ts (hunk 1 above)
Comment (ZachJW34) [reply system-tests/projects/angular-custom-root/ui/main.ts:1]: We do have one, but this project felt different enough that I thought I'd make a new one. If I was to reuse the `angular` project-fixture, I'd have had to overwrite almost every file (every config file + the src code is in a different directory)

**Review by astone123 — APPROVED** [review]
Looks good 👍🏻 would be nice to confirm that this solves the user's issue specifically

File: system-tests/projects/angular-custom-root/ui/main.ts (hunk 1 above)
Comment (jordanpowell88) [reply system-tests/projects/angular-custom-root/ui/main.ts:1]: I agree with @ZachJW34  that this is worth a different project since the source root is pretty fundamental part of the app.

**Review by jordanpowell88 — APPROVED** [review]
Great job with this. This was certainly an oversight on our end

**Comment by ZachJW34** [comment]
Going to hold off on merging for a day or so, hoping the original poster of the issue has a chance to try out the binary

**Comment by ZachJW34** [comment]
Going to go ahead and get this merged.
