### PR TITLE
fix: Handle more argument types in privileged commands

### LINKED ISSUE #27163: cy.task not working with ArrayBuffer
### Current behavior

When using a task with a ArrayBuffer as argument, I get the error message `cy.task() must only be invoked from the spec file or support file.` 

Using an array or a string as an argument works fine.

This is a problem when using cy.intercept and trying to send the `intercept.body.response` as an argument for a task, like validating the content of a intercepted pdf file.

This worked fine in Cypress 12.14.0

### Desired behavior

Cypress should also allow ArrayBuffer to be passed as an argument. Alternatively there should be an explaination+documentation why ArrayBuffer is no longer supported as an argument, as the current error message is misleading.

### Test code to reproduce

`spec.cy.js`

```
describe("Test for bug ", () => {
    it(`doesnt work`, () => {
        			
		const buffer = new ArrayBuffer(10);				
		cy.task("log", buffer)
		
    })
		
    it(`works`, () => {
        			
		const array = new Array(10);
		cy.task("log", array)
		
    })
	
});
```

`cypress.config.js`

```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  e2e: {
    setupNodeEvents(on, config) {
      on('task', {
        log(message) {
          console.log(message)

          return null
        },
      })
    },
  },
})
```

### Cypress Version

12.16.0

### Node version

v18.12.1

### Operating System

Win11

### Debug Logs

_No response_

### Other

Worked fine with older versions, the fix in 12.16.0 didn't help.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #27163 

### Additional details

Privileged command argument comparison was failing with types like ArrayBuffer because the invocation argument hashing was done client-side while the execution argument hashing was done server-side. I moved the execution hashing to the client-side, which ensures that the argument hashes will be equal for equal arguments.

I checked the types of arguments each privileged command accepts and added tests to ensure they are all covered.

### PR Tasks

- [x] Have tests been added/updated?
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -6364,7 +6364,18 @@ declare namespace Cypress {
...
+  | Uint8Array
+  | Uint8ClampedArray
+  | Int16Array
+  | Uint16Array
+  | Int32Array
+  | Uint32Array
+  | Float32Array
+  | Float64Array
+
+  type FileReference = string | BufferType | FileReferenceObject | TypedArray
```
Comment (chrisbreiding) [inline cli/types/cypress.d.ts:6378]: This is a correction for this type.`cy.selectFile()` can take a `TypedArray` as an argument.

File: packages/driver/src/util/privileged_channel.ts [hunk 2]
```diff
@@ -22,20 +22,51 @@ interface RunPrivilegedCommandOptions {
...
+    h2 = Math.imul(h2 ^ ch, 1597334677)
+  }
+  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507)
+  h1 ^= Math.imul(h2 ^ (h2 >>> 13), 3266489909)
+  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507)
+  h2 ^= Math.imul(h1 ^ (h1 >>> 13), 3266489909)
+
+  return `${4294967296 * (2097151 & h2) + (h1 >>> 0)}`
+}
+
```
Comment (chrisbreiding) [inline packages/driver/src/util/privileged_channel.ts:47]: Moved here without change from the server

File: packages/driver/src/cy/commands/files.ts [hunk 3]
```diff
@@ -25,7 +25,7 @@ export default (Commands, Cypress, cy, state) => {
       // privileged commands need to send any and all args, even if not part
       // of their API, so they can be compared to the args collected when the
       // command is invoked
-      const userArgs = trimUserArgs([file, encoding, _.isObject(userOptions) ? { ...userOptions } : undefined, ...extras])
+      const userArgs = [file, encoding, _.isObject(userOptions) ? { ...userOptions } : undefined, ...extras]
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/files.ts:28]: Trimming (and hashing) the user args has been moved into the `runPrivilegedCommand` function.

**Review by AtofStryker — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
