### PR TITLE
Fix issue with finding elements in shadow dom under specific conditions

### LINKED ISSUE #7676: TypeError: Cannot read property 'length' of undefined when run test by cypress run
### Current behavior:

I have testing site with shadow DOM.

```javascript
it('test', () => {
  cy
    .get('div[class="oneAppNavContainer"]')
    .find('one-appnav')
    .find('span[title="          Config"]', {includeShadowDom: true})
    .contains('          Config');
});
```

It's code work correctly when I use cypress open.

Screenshot 2020-06-11 at 10 53 53

But not work when I use cypress run.

```
TypeError: Cannot read property 'length' of undefined
    at superMatcher (https://example.com/__cypress/runner/cypress_runner.js:86701:17)
    at Sizzle.select (https://example.com/__cypress/runner/cypress_runner.js:86897:44)
    at Function.Sizzle [as find] (https://example.com/__cypress/runner/cypress_runner.js:85065:9)
    at jQuery.fn.init.find (https://example.com/__cypress/runner/cypress_runner.js:87096:11)
    at find (https://example.com/__cypress/runner/cypress_runner.js:153939:31)
    at getEl (https://example.com/__cypress/runner/cypress_runner.js:154030:18)
    at getElements (https://example.com/__cypress/runner/cypress_runner.js:154058:17)
    at Context.<anonymous> (https://example.com/__cypress/runner/cypress_runner.js:154082:14)
    at Context.<anonymous> (https://example.com/__cypress/runner/cypress_runner.js:163288:21)
    at https://example.com/__cypress/runner/cypress_runner.js:162724:15
    at tryCatcher (https://example.com/__cypress/runner/cypress_runner.js:10161:23)
    at Promise._settlePromiseFromHandler (https://example.com/__cypress/runner/cypress_runner.js:8096:31)
    at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:8153:18)
    at Promise._settlePromiseCtx (https://example.com/__cypress/runner/cypress_runner.js:8190:10)
    at _drainQueueStep (https://example.com/__cypress/runner/cypress_runner.js:4872:12)
```

### Desired behavior:

What I do wrong?
### Versions

Cypress: 4.8.0
Chrome Canary 85

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7676

### User facing changelog

- Fixed a bug where querying shadow dom could cause the error `Cannot read property 'length' of undefined` in run mode

### Additional details

The root cause of this issue is that the framework Salesforce uses (_Aura_) wraps the native `document.querySelectorAll`. jQuery (via Sizzle) [determines that `document.querySelectorAll` is not available](https://github.com/jquery/sizzle/blob/af163873d7cdfc57f18b16c04b1915209533f0b1/src/sizzle.js#L796) in that case, because it doesn't think it's native (even though _Aura_ calls the native method within its wrapper). This causes jQuery to fall back to other methods of querying, which don't work well with shadow dom and result in the error at issue. 

Why does it only happen in run mode? Because there is no snapshotting. In interactive mode, an early XHR causes a snapshot, which queries the dom, which makes jQuery determine `querySelectorAll` support before the _Aura_ code runs. This can also be reproduced in open mode with `Cypress.config('numTestsKeptInMemory', 0)`. 

This leads to the solution seen in this PR. When a page is loaded, before user scripts are run, we do a noop query (`cy.$$('body')`) to make jQuery check for `querySelectorAll` early and determine that it's there and it's native. From then on, it appropriately uses it for querying the dom.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/commands/querying.js [hunk 1]
```diff
@@ -276,42 +276,38 @@ module.exports = (Commands, Cypress, cy, state) => {
...
         let $el
 
         try {
-          // only support shadow traversal if we're not searching
-          // within a subject and have been explicitly told to ignore
-          // boundaries.
-          if (!options.includeShadowDom) {
-            $el = cy.$$(selector, options.withinSubject)
-          } else {
+          let scope = options.withinSubject
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/querying.js:282]: This is all refactor and not related to the fix.

File: packages/driver/cypress/fixtures/shadow-dom.html [hunk 2]
```diff
@@ -35,6 +35,13 @@
           }
         })
       }
+
+      if (window.location.search.includes('wrap-qsa')) {
+        const qsa = document.querySelectorAll;
```
Comment (JessicaSachs) [inline packages/driver/cypress/fixtures/shadow-dom.html:40]:
```suggestion
        const realQuerySelectorAll = document.querySelectorAll;
```

File: packages/driver/cypress/fixtures/shadow-dom.html [hunk 3]
```diff
@@ -35,6 +35,13 @@
...
+        document.querySelectorAll = function (...args) {
+          return qsa.apply(document, args);
```
Comment (JessicaSachs) [inline packages/driver/cypress/fixtures/shadow-dom.html:42]:
```suggestion
          return realQuerySelectorAll.apply(document, args);
```
