### PR TITLE
fix: Back out of axios switchover for the createInstance cloud API request

### LINKED ISSUE #31485: With certain proxy configurations, the create instance Cloud API requests will fail
### Current behavior

With certain proxy configurations, a crucial step in recording test runs to the cloud will fail.

### Desired behavior

Recording to the cloud works with these proxy configurations

### Test code to reproduce

N/A

### Cypress Version

14.2.0

### Node version

20.18.1

### Operating System

n/a

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/31485

### Additional details
Axios may need additional configuration to support certain proxy configurations. This switches back to the `@cypress/request` method until that can be addressed. Axios implementation is still included in the codebase, but is not used.

### PR Tasks

- [NA] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/cloud/api/index.ts [hunk 1]
```diff
@@ -443,7 +444,33 @@ export default {
     .catch(tagError)
   },
 
-  createInstance,
+  createInstance (options) {
```
Comment (tgriesser) [inline packages/server/lib/cloud/api/index.ts:447]:
```suggestion
  createInstance (runId, options) {
```

File: packages/server/lib/cloud/api/index.ts [hunk 2]
```diff
@@ -443,7 +444,33 @@ export default {
...
+    const { runId, timeout } = options
```
Comment (tgriesser) [inline packages/server/lib/cloud/api/index.ts]:
```suggestion
  createInstance (runId, options) {
    const { timeout } = options
```

File: packages/server/lib/cloud/api/index.ts [hunk 3]
```diff
@@ -25,7 +25,8 @@ import type { ProjectBase } from '../../project-base'
 import type { AfterSpecDurations } from '@packages/types'
 import { PUBLIC_KEY_VERSION } from '../constants'
 
-import { createInstance } from './create_instance'
+// axios implementation disabled until proxy issues can be diagnosed/fixed
+//import { createInstance } from './create_instance'
```
Comment (AtofStryker) [inline packages/server/lib/cloud/api/index.ts:30]: do we have an issue we can link to here?

File: packages/server/lib/cloud/api/index.ts (hunk 2 above)
Comment (AtofStryker) [reply packages/server/lib/cloud/api/index.ts]: probably out of scope but typing this would also help with the expected types

Comment (cacieprins) [reply packages/server/lib/cloud/api/index.ts]: Addressed in https://github.com/cypress-io/cypress/pull/31486/commits/0a81f9312cb46ba54e7d7d6e3a31a3d425cd6b6d - unit tests now test both methods to ensure compatibility. The only difference in the behavior now is that the axios path will throw an aggregate error for multiple retries, while the request/promise path will just throw the most recent error.

File: packages/server/lib/cloud/api/index.ts (hunk 3 above)
Comment (cacieprins) [reply packages/server/lib/cloud/api/index.ts:30]: addressed in https://github.com/cypress-io/cypress/pull/31486/commits/6a693639d64c9b7b1a86f13e2c32ed671a5ab9c2

**Review by tgriesser — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]
