### PR TITLE
misc: ACI empty state slideshows

### LINKED ISSUE #26181: ACI - Run page and Debug page empty state updates
Update the empty states for both the Runs page and Debug page to use the new promotional slideshow design

image

### Summary
For both pages, the new designs will affect the following states:
* Not logged in
* Need to record a run

### New components
Add a new components to be shared between the Runs and Debug pages that follows the core concepts here: https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=641-34870&t=qyIiAUnBzPBxzvgY-0

_Card with header_
* Should have card type component with header and body
* Header should have
  * Title
  * Subtitle
  * CTA button
  * Should float CTA button at larger widths
  * Should wrap button under subtitle at smaller widths
  * Body should be a container with a slot for content
  * [Figma](https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=608%3A10886&t=l3hWJOOBLNpE6p5a-1)

_Promo_ 
* 2 column layout when wide enough
* Stacked vertically when narrow
* Elements
  * title
  * description
  * Promo/secondary action section - [Figma](https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=435%3A6962&t=l3hWJOOBLNpE6p5a-1)
    * 3 styles of CTA
      * `x of n` with a next button
      * reset icon with "Reset" button
      * graduation cap with "View Tour" button
  * content slot (where the skeleton states go)

---

### Runs Page

Update component to use the new components above 

[Figma](https://www.figma.com/file/2OOJAfoCGBUct1RRImottI/Runs-Page-v1.0-%40latest?node-id=416%3A8385&t=BTiO1VVSF3PrYETD-1) 

#### `<RunsConnect />`

Title: `Connect to view your recorded runs`
Subtitle: `Cypress Cloud is built for teams who need to do testing at scale.`
CTA: Should be the `<CloudConnectButton />`

_Promo steps_

| Step | Title | Description | CTA | Skeleton | 
| ----- | ---- | ----------- | ---- | -------- |
| 1 (Beta) | Get instant visibility into your test runs that are recorded to Cypress Cloud |  Browse detailed information about the most recent test runs recorded to Cypress Cloud from your branch. | `1 of 3` with next button | Shows running build with skeletons below |
| 2 (Gamma) | Monitor test failures in real time | Uncover high-risk failed and flaky tests in CI before they become a problem in production. | `2 of 3` with next button | Shows failed test with skeletons below |
| 3 (Omega) | Build, test, and ship with confidence 🚀 | With Cypress Cloud, you can proactively identify, investigate, and resolve failures, and be a quality champion. | Restart icon and button | Passing test above failed test with skeletons |

Copy can also be seen in this document: https://docs.google.com/document/d/10gh-EQWfE6Hk9Y4Dqj9QY3mUnEmNz4_cndHuTVPGBKY/edit#heading=h.sf5sy5wn0ivo

_Animation_ [Figma Flow](https://www.figma.com/proto/2OOJAfoCGBUct1RRImottI/Runs-Page-v1.0-%40latest?node-id=436-37896&scaling=scale-down&page-id=2%3A126&starting-point-node-id=436%3A37896&show-proto-sidebar=1) 
* text should do a fade between steps
* skeletons
  * MVP - fade between skeletons
  * Extra credit - (not sure how hard these are to do)
    * Step 1 should show the animating running icon that then slows to a stop after 2 seconds and grays out
    * Moving from step 1 to step 2 should fade between the two
    * Moving from step 2 to step 3 should slide down the first run and then animate in the passing run
    * **NOTE** Currently the Figma flow does not show all of these animations due to a bug

#### `<RunsEmpty />`

When in the state that shows the `<RunsEmpty />` component, this step will be shown first.  Clicking the "View tour" button will go to Step 1 and clicking "Reset" at the end will go back to this step.

Title: `Copy the command below to record your first run`
Subtitle: `Record your first test run to Cypress Cloud`
CTA:  Use the `<RecordPromptAdaptor />`

_Added promo step_

The following step should be added to the beginning of the promo steps in this state. 

|Step | Title | Description | CTA | Skeleton | 
| -- | ---- | ----------- | ---- | -------- |
| Alpha | Record your first test run to Cypress Cloud | You’re almost there! Start recording your test runs to Cypress Cloud by running the command below in your local or CI terminal. | View tour | Skeleton Terminal and CI config |

[Figma](https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=641%3A25381&t=qyIiAUnBzPBxzvgY-1)

### Record viewed events

Match the logic in the Debug page for the empty states to send campaign viewed events for the following empty states:

The medium should be `Runs Tab`

| State | Campaign name |
| -- | -- |
| Not logged in | `Runs Login Empty State` | 
| No project connected | `Runs Connect Project Empty State` | 
| No runs recorded | `Runs Record Run Empty State` |

---

### Debug page

Update component to use the new components above 

Currently, the existing carousel (i.e. `<Debug Slide />` component) is shown on every empty state page.  The new designs call for it to only be on the `<DebugNotLoggedIn />` page.

#### `<DebugNotLoggedIn />`

Title: `Connect to debug your tests`
Subtitle: `Cypress Cloud is built for teams who need to do testing at scale.`
CTA: Should be the `<CloudConnectButton />`

_Promo steps_

| Step | Title | Description | CTA | Skeleton | 
| ----- | ---- | ----------- | ---- | -------- |
| 1 (Beta) | Review how many tests failed during a CI test run| The Debug page shows the latest completed test run for your current checked out commit. | `1 of 3` with next button | Skeleton showing run failure count |
| 2 (Gamma) | Check if failed CI test runs also fail locally | Use the Test Runner to run only the tests that failed in your last recorded test run. | `2 of 3` with next button | Skeleton showing "Run Failures" button  |
| 3 (Omega) | Locally debug failed test runs with visual artifacts | Easily review screenshots, videos, and logs from your tests. | Restart icon and button | Skeleton showing artifact links |

_Convert Skeletons from images to HTML_
Currently, the skeletons shown on the Debug page are static images.  They will need to be converted to HTML so that they can be responsive in the new designs.

_Animation_ 
* text should do a fade between steps
* skeletons
  * fade between steps

[Figma](https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=449%3A11186&t=qyIiAUnBzPBxzvgY-1)

#### `<DebugNoRuns />`

**NOTE** This is the same step shown in the <RunsEmpty/> component.  Duplicating here for the Debug page.

Title: `Copy the command below to record your first run`
Subtitle: `Record your first test run to Cypress Cloud`
CTA:  Use the `<RecordPromptAdaptor />`

_Additional promo step_

When in the state that shows the `<DebugNoRuns />` component, this step will be shown first.  Clicking the "View tour" button will go to Step 1 and clicking "Reset" at the end will go back to this step.

| Step | Title | Description | CTA | Skeleton | 
| -- | ---- | ----------- | ---- | -------- |
| Alpha | Record your first test run to Cypress Cloud | You’re almost there! Start recording your test runs to Cypress Cloud by running the command below in your local or CI terminal. | View tour | Skeleton Terminal and CI config |

### Resources

Clickup - https://app.clickup.com/t/18033298/PM-2889
Figma files
* [Design Patterns](https://www.figma.com/file/AE8KK3Hx2ZCDLlK3FkOd4k/Design-Patterns%2C-v1.x---%40latest?node-id=435-6688&t=tcS32TzBzJv4EONY-0)
* [Runs Page](https://www.figma.com/file/2OOJAfoCGBUct1RRImottI/Runs-Page-v1.0-%40latest?node-id=2-126&t=BTiO1VVSF3PrYETD-0) 
* [Debug Page](https://www.figma.com/file/2OOJAfoCGBUct1RRImottI/Runs-Page-v1.0-%40latest?node-id=2-126&t=BTiO1VVSF3PrYETD-0)

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #26181 

### Additional details
Replacing four views with a new slideshow design from Figma (see referenced issue for links)

* Debug: Not Logged In
* Debug: No Recorded Runs
* Runs: No Recorded Runs
* Runs: Not Logged In and/or Project Not Connected

For slides I just did the MVP of cross-slide fade for now, described "extra credit" enhancements can be implemented later if determined to be worth it.

Each `Promo` will record an event when it is seen, CTAs & links include UTM params to determine source.

### Steps to test
Easiest way to test this is to use `DebugEmptyStates.cy.tsx` and `RunsContainer.cy.tsx` specs

### How has the user experience changed?

**Debug: Not Logged In**

https://github.com/cypress-io/cypress/assets/11482842/cfe9a197-b510-469b-9002-c08625771b8b

**Debug: No Recorded Runs**
_Note:_ Mocked state for this video so no record key is showing in command

https://github.com/cypress-io/cypress/assets/11482842/deb79af0-ea55-43a7-909a-cd5c24c7f890

**Runs: Not Connected**

https://github.com/cypress-io/cypress/assets/11482842/d3bf1c1f-3cbc-424b-81a2-8e6cd2a65d34

**Runs: No Recorded Runs**
_Note:_ Mocked state for this video so no record key is showing in command

https://github.com/cypress-io/cypress/assets/11482842/9169dd47-7bd2-4668-bb4e-3ec018f94e63

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/debug/empty/DebugNoRuns.vue [hunk 1]
```diff
@@ -1,24 +1,73 @@
...
 <script lang="ts" setup>
-import DebugEmptyView from './DebugEmptyView.vue'
 import { useI18n } from '@cy/i18n'
+import { computed } from 'vue'
+import { DEBUG_PROMO_CAMPAIGNS, DEBUG_TAB_MEDIUM } from '../utils/constants'
+import Promo from '@packages/frontend-shared/src/gql-components/promo/Promo.vue'
+import PromoHeader from '@packages/frontend-shared/src/gql-components/promo/PromoHeader.vue'
 import RecordPromptAdapter from '@cy/gql-components/RecordPromptAdapter.vue'
-import { DEBUG_SLIDESHOW } from '../utils/constants'
+import GuideCard1 from '../guide/GuideCard1.vue'
```
Comment (lmiller1990) [inline packages/app/src/debug/empty/DebugNoRuns.vue]: Just a suggestion for future PRs, I think we can do this like you often see in React using a namespace:

```ts
export const Guide = {
  Card1,
  Card2
}

// ...
<template>
  <Guide.Card1 />
  <Guide.Card2 />
</template>
```

Comment (lmiller1990) [reply packages/app/src/debug/empty/DebugNoRuns.vue]: This is fine too, though 👍

File: packages/app/src/debug/guide/GuideCard1.vue [hunk 2]
```diff
@@ -0,0 +1,35 @@
+<template>
+  <PromoCard
+    :title="t('debugPage.emptyStates.slideshow.step1.title')"
+    :body="t('debugPage.emptyStates.slideshow.step1.description')"
+  >
+    <template #image>
+      <Illustration />
+    </template>
+    <template #action>
```
Comment (lmiller1990) [inline packages/app/src/debug/guide/GuideCard1.vue:9]: This looks generally fine, but one other options might to be have 1 components and define the options in an array, like:

```
const guideCards = [
  {
      action: goForward,
      title: t('...'),
      leftLabel: ...
  }
]

// ...
<GuideCard v-for="card of guideCards" :body="card.body" />
// ... or ...
<GuideCard v-for="card of guideCards" :card="card" />
```

Not fussed, but might be a good way to save a bit of duplication. WDYT?

File: packages/app/src/runs/guide/TourCard.vue [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import PromoAction from '@packages/frontend-shared/src/gql-components/promo/PromoAction.vue'
+
+import { IconObjectTassel } from '@cypress-design/vue-icon'
+
+import RecordGuideImage from '../../assets/record-guide.svg'
+
+const { t } = useI18n()
+
+defineProps<{
+  action: () => void
```
Comment (lmiller1990) [inline packages/app/src/runs/guide/TourCard.vue:33]: We've got this `defineProps` a lot. It's quite simple, but might be worth trying to find an abstraction (I suggested one, but it might not work here - I didn't try it yet).

Wouldn't  consider this to be a blocker, but food for thought - do you think these duplication is worth the effort to avoid?

File: packages/frontend-shared/src/components/Slideshow.vue [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+  <div class="relative">
+    <!-- leave-to classes are marked absolute to allow the entering component to
+    animate on top of the leaving component, creating a fading animation with no thrashing -->
+    <transition
+      enter-from-class="opacity-0"
+      enter-active-class="transition duration-300 ease-out"
+      enter-to-class="opacity-100"
+      leave-from-class="opacity-100 absolute"
+      leave-active-class="transition duration-300 ease-in absolute"
+      leave-to-class="opacity-0 absolute"
```
Comment (lmiller1990) [inline packages/frontend-shared/src/components/Slideshow.vue]: The tailwind + `<transition>` combo sure is nice!

Comment (lmiller1990) [reply packages/frontend-shared/src/components/Slideshow.vue]: I thought we already have a slideshow abstraction somewhere - we definitely have other slideshows in the app. 

Edit... this is the slideshow, it got moved from app to frontend shared? What was the reason for that?

File: packages/frontend-shared/src/gql-components/promo/Promo.vue [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+  medium: string
+  cohort?: string
+}>()
+
+const query = useQuery({ query: PromoDocument })
+const promoSeenMutation = useMutation(Promo_PromoSeenDocument)
+
+const promoInstanceId = nanoid()
+
+watch([query.data.value], ([queryResult]) => {
```
Comment (lmiller1990) [inline packages/frontend-shared/src/gql-components/promo/Promo.vue]: Seems like just want to run this once - as soon as the query data is available - is that correct?

Could we do

```ts
useQuery().then(res => {
  // we know it's resolved, do the check and mutation
})
```

Eg - do we expect this re-trigger (do we need to `watch`)?

**Review by lmiller1990 — COMMENTED** [review]
Some basic comments/questions, looking good.

File: packages/frontend-shared/src/gql-components/promo/Promo.vue [hunk 6]
```diff
@@ -0,0 +1,80 @@
+<template>
+  <div class="promo-box flex flex-col items-center border-gray-100 rounded-lg w-full max-w-[1004px] m-auto">
```
Comment (warrensplayer) [inline packages/frontend-shared/src/gql-components/promo/Promo.vue]: Need border class to set the border width of 1px
```suggestion
  <div class="promo-box flex flex-col items-center border border-gray-100 rounded-lg w-full max-w-[1004px] m-auto">
```

File: packages/frontend-shared/src/gql-components/promo/PromoAction.vue [hunk 7]
```diff
@@ -0,0 +1,80 @@
+<template>
+  <component
+    :is="wrapperComponent"
+    data-cy="promo-action"
+    class="flex flex-row items-center gap-[12px] h-[32px] bg-gray-50 border border-gray-100 rounded w-fit text-sm"
+    :class="wrapperClasses"
+    v-bind="wrapperProps"
+    @click="action"
```
Comment (warrensplayer) [inline packages/frontend-shared/src/gql-components/promo/PromoAction.vue]: The design calls for the right side of this component to be a Button.  There is a trick to see some of this component hierarchy in Figma by using the right click menu to select the right layer [see screenshot]

image

This shows in Figma as `Button / Outline / Grey-Light` but I think is the style `outline-light` in the design system component button.  

This will give it the appropriate keyboard accessibility and hover/focus styles.  I think just making the right side of the component the button would allow using the design system button but you would have to see if you can override the border radius of the left hand side.  If that does not work, then you might have to use a raw button that you style. Glad to pair on this if needed.

File: packages/frontend-shared/src/gql-components/promo/PromoCard.vue [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+          <p>{{ body }}</p>
+        </div>
+        <div>
+          <slot name="action" />
+        </div>
+      </div>
+      <div class="flex-auto basis-1/2">
+        <slot name="image" />
+      </div>
+    </div>
```
Comment (warrensplayer) [inline packages/frontend-shared/src/gql-components/promo/PromoCard.vue]: Should be able to accomplish this with `grid` to avoid duplicating DOM

See example: https://jsbin.com/loxuxahude/2/edit?html,css,output

**Review by warrensplayer — COMMENTED** [review]
A few layout/component comments while I continue to review the code.

File: packages/app/src/runs/RunsConnect.vue [hunk 9]
```diff
@@ -1,50 +1,50 @@
...
-    </h2>
-    <div class="flex gap-[32px]">
-      <div
-        v-for="(block, i) in notions"
-        :key="i"
-      >
-        <component
-          :is="block.icon"
-          class="mx-auto h-[120px] w-[120px]"
+  <div class="m-[10%]">
```
Comment (warrensplayer) [inline packages/app/src/runs/RunsConnect.vue]: Using `flex h-full` to center this will work a bit better than the 10% margin.

File: packages/app/src/debug/empty/DebugNoRuns.vue (hunk 1 above)
Comment (mike-plummer) [reply packages/app/src/debug/empty/DebugNoRuns.vue]: Love it, definitely will restructure. I knew exactly how I would structure all of this state & these components in React but was struggling to map that into the "Vue way"

File: packages/app/src/debug/guide/GuideCard1.vue (hunk 2 above)
Comment (mike-plummer) [reply packages/app/src/debug/guide/GuideCard1.vue:9]: This is how `Slideshow` was originally structured, but I backed away from that since there are now a number of different permutations for slides. It got unweildy to map all those thru via `props`, so I ended up with different components to keep the props manageable (and testable). I'll do a little restructuring to get the cards better managed and we can see how it feels at that point

File: packages/frontend-shared/src/components/Slideshow.vue (hunk 4 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/components/Slideshow.vue]: Correct, `Promo` is just a thin presentational layer atop the existing `Slideshow` component. At the beginning I had thought this might be potentially useful as a "base" component (eventually used in launchpad, maybe) so I moved it, but that's aspirational thinking so I'll shift this back into `app`

File: packages/frontend-shared/src/gql-components/promo/PromoAction.vue (hunk 7 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/gql-components/promo/PromoAction.vue]: Argh, was going back and forth on which made more sense - guessed wrong. I think it will be a bit of a struggle to get the border rounding to work correctly but I'll figure something out

File: packages/app/src/debug/empty/DebugNoProject.vue [hunk 10]
```diff
@@ -3,7 +3,6 @@
     :title="t('debugPage.emptyStates.debugDirectlyInCypress')"
     :description="t('debugPage.emptyStates.reviewRerunAndDebug')"
     :example-test-name="t('debugPage.emptyStates.noProjectTestMessage')"
-    :slideshow-campaign="DEBUG_SLIDESHOW.campaigns.connectProject"
     :help-link-sr-text="t('debugPage.emptyStates.learnAboutProjectSetupSrText')"
     help-link-href="https://on.cypress.io/adding-new-project"
   >
```
Comment (warrensplayer) [inline packages/app/src/debug/empty/DebugNoProject.vue]: Sorry if I was not clear in the issue, but this `DebugNoProject.vue` should be just like the `DebugNotLoggedIn.vue` and show the promo.  The only thing that changes is the `CloudConnectButton` should automatically update its text to show "Connect a Cypress Cloud project"

File: packages/app/src/runs/RunsConnect.vue [hunk 11]
```diff
@@ -1,50 +1,50 @@
...
-    />
+      </template>
+    </Promo>
   </div>
 </template>
 
 <script lang="ts" setup>
-import SmartIcon from '~icons/cy/illustration-gear_x120.svg'
-import DebugIcon from '~icons/cy/illustration-debug_x120.svg'
-import ChartIcon from '~icons/cy/illustration-chart_x120.svg'
```
Comment (warrensplayer) [inline packages/app/src/runs/RunsConnect.vue:30]: If these SVGs are no longer used, they can be deleted.

File: packages/frontend-shared/src/gql-components/promo/Promo.vue (hunk 5 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/gql-components/promo/Promo.vue]: Much better, didn't realize `useQuery` was Promise-like 👍

File: packages/frontend-shared/src/gql-components/promo/PromoCard.vue (hunk 8 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/gql-components/promo/PromoCard.vue]: Ha, yeah, `flex` is my crutch. I need to hammer `layout: grid` into my brain

File: packages/frontend-shared/src/gql-components/promo/PromoAction.vue (hunk 7 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/gql-components/promo/PromoAction.vue]: Reworked to use the DS Button and restrict actionability to the right side. Not sure on the styling - per Figma we're using the `outline-light` variant, but the hocus styles for that are pretty subdued in this context. Will take a closer look once the tests settle down on the latest commits

File: packages/app/src/components/promo/PromoCard.vue [hunk 12]
```diff
@@ -0,0 +1,27 @@
+<template>
+  <div class="w-full">
+    <div class="grid lg:grid-cols-2 p-[40px] gap-[16px]">
+      <div>
+        <h2 class="text-xl font-semibold">
+          {{ title }}
+        </h2>
+        <p>{{ body }}</p>
```
Comment (warrensplayer) [inline packages/app/src/components/promo/PromoCard.vue]:
```suggestion
        <p class="text-grey-700">{{ body }}</p>
```

Comment (warrensplayer) [inline packages/app/src/components/promo/PromoCard.vue]:
```suggestion
        <p class="text-gray-700">{{ body }}</p>
```

File: packages/app/src/components/promo/PromoCard.vue [hunk 13]
```diff
@@ -0,0 +1,27 @@
+<template>
+  <div class="w-full">
+    <div class="grid lg:grid-cols-2 p-[40px] gap-[16px]">
+      <div>
+        <h2 class="text-xl font-semibold">
```
Comment (warrensplayer) [inline packages/app/src/components/promo/PromoCard.vue]:
```suggestion
        <h2 class="text-xl font-semibold text-gray-900">
```

File: packages/app/src/debug/empty/DebugNoRuns.vue (hunk 1 above)
Comment (lmiller1990) [reply packages/app/src/debug/empty/DebugNoRuns.vue]: Sure, no problem - not sure why this is less common in Vue world, same patterns should generally work.

Comment (lmiller1990) [reply packages/app/src/debug/empty/DebugNoRuns.vue]: LMK when you do this (or if you decide not to) and I can approve, everything else is looking pretty good to me.

**Review by lmiller1990 — COMMENTED** [review]
Works great, left a few comments, ping me for a re-review when you are happy with the stater of things @mike-plummer 💯

File: packages/app/src/components/promo/PromoHeader.vue [hunk 14]
```diff
@@ -0,0 +1,50 @@
+<template>
+  <div class="flex flex-col bg-gray-50 border-gray-100 py-[16px] px-[24px] rounded-t-[8px] gap-16px items-start w-full">
+    <div class="promo-header flex flex-row w-full items-center flex-wrap gap-[16px]">
```
Comment (warrensplayer) [inline packages/app/src/components/promo/PromoHeader.vue]:
```suggestion
    <div class="flex flex-row w-full items-center flex-wrap gap-[16px]">
```

Doesn't look like `promo-header` is used anywhere

File: packages/app/src/components/promo/PromoAction.vue [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+          class="flex flex-row items-center font-medium mx-[12px] whitespace-nowrap"
+        >
+          {{ rightLabel }}
+          <component
+            :is="rightIcon"
+            v-if="rightIcon"
+            class="ml-[8px]"
+          />
+        </span>
+      </ExternalLink>
```
Comment (warrensplayer) [inline packages/app/src/components/promo/PromoAction.vue]: Is this `ExternalLink` part ever used? I only see the `href` prop being used in a test.

File: packages/app/src/components/promo/PromoAction.vue [hunk 16]
```diff
@@ -0,0 +1,69 @@
+<template>
+  <div
+    data-cy="promo-action"
+    class="flex flex-row items-center gap-[12px] h-[32px] bg-gray-50 border border-gray-100 rounded w-fit text-sm"
```
Comment (warrensplayer) [inline packages/app/src/components/promo/PromoAction.vue]: Forcing a fix height here is forcing the button to overflow due to the button's height plus border.  I am playing around with some options, but not there yet.

**Review by warrensplayer — COMMENTED** [review]
More style comments.  Trying to figure out how far to take this.  Still some odd responsive behavior between breakpoints where the image gets shrunk pretty far and then seems overly large once the component stacks vertically.

File: packages/app/src/components/promo/PromoHeader.vue (hunk 14 above)
Comment (mike-plummer) [reply packages/app/src/components/promo/PromoHeader.vue]: It's actually applying a class from the `style` block in this component - I didn't realize that Tailwind has support for [arbitrary box shadow declarations](https://tailwindcss.com/docs/box-shadow#arbitrary-values) though, so I'll refactor to use that

File: packages/app/src/components/promo/PromoAction.vue (hunk 16 above)
Comment (mike-plummer) [reply packages/app/src/components/promo/PromoAction.vue]: I had noticed that too and tried to hack it with the `py-[5px]` class on `Button` to offset the button's padding to account for the border pixels

File: packages/app/src/components/promo/PromoAction.vue (hunk 15 above)
Comment (mike-plummer) [reply packages/app/src/components/promo/PromoAction.vue]: I had originally thought the "Tour" button was a link out to the docs site so I built that version of the button, but I never circled back to remove it. It's valid and tested, but currently dead code. Ever envision us needing this? If not I'll go ahead and remove

File: packages/app/src/debug/empty/DebugNoRuns.vue (hunk 1 above)
Comment (mike-plummer) [reply packages/app/src/debug/empty/DebugNoRuns.vue]: I ended up writing a simple wrapper for each of the sets of cards (`DebugGuide`, `DebugTour`, etc) so the card components don't have to be referenced en-masse outside that directory. Given how the different slideshows were structured I didn't end up seeing much organizational benefit from the namespacing suggestion

File: packages/app/src/components/promo/PromoAction.vue (hunk 15 above)
Comment (warrensplayer) [reply packages/app/src/components/promo/PromoAction.vue]: I don't see a reason at this time to keep it. There was a variant of the designs at one point that did have that as a link out, but it was scratched.

**Comment by warrensplayer** [comment]
@mike-plummer Played around with styles and came up with this PR into this branch: https://github.com/cypress-io/cypress/pull/26733 

Let me know what you think.  

I still want to go through the code one more time and verify the telemetry and links, but getting close.  Also, we should grab Chris France to do quick acceptance test.

**Comment by lmiller1990** [comment]
I'm going to out, so I won't be able to respond to any comments in a timely fashion - I played with the PR a bit more and it's looking good. I'll leave a tentative approval just to avoid needing a third person to go through the entire thing. I hadn't caught the weirdness with the responsive design in my first pass, but glad we got it fixed.

**Review by lmiller1990 — APPROVED** [review]

**Review by lmiller1990 — APPROVED** [review]

**Review by warrensplayer — APPROVED** [review]
Looks good to me.  Still a strange issue with scrolling when the viewport is too short where it will not scroll into view the bottom padding.  I think it has something to do with the nested divs that all have to have height of 100% in order to center the component.  Not worth fighting any. more.
