### PR TITLE
test: retry proxy_spec tests that flake

### LINKED ISSUE #30649: Flaky test: address flake in proxy integration tests
### Link to Cypress Cloud or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/65640/workflows/6733c6d5-534f-40b4-a826-ca1fa121e1c9/jobs/2726858/tests

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/develop/packages/https-proxy/test/integration/proxy_spec.js

### Analysis

n/a

### Cypress Version

13.15.2

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes https://github.com/cypress-io/cypress/issues/30649

### Additional details

* Addressed one test that was flaking because the socket close event was already fired prior to the listener being added
* Added a retry on the `generating certificates` tests that appear to be flaky
* Changed the `9001` port to `2222` so it wouldn't conflict with the locally running services port

### Steps to test

n/a

### How has the user experience changed?

n/a

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/https-proxy/test/integration/proxy_spec.js [hunk 1]
```diff
@@ -90,29 +90,31 @@ describe('Proxy', () => {
...
-      const socket = net.connect.getCalls()[0].returnValue
+    // ensure the outgoing socket created for this connection was destroyed
+    expect(net.connect).calledOnce
 
-      return new Promise((resolve) => {
+    const socket = net.connect.getCalls()[0].returnValue
+
+    // sometimes the close event happens before we can attach the listener, causing this test to flake
+    if (!socket.destroyed || !socket.readyState === 'closed') {
+      await new Promise((resolve) => {
```
Comment (AtofStryker) [inline packages/https-proxy/test/integration/proxy_spec.js:110]: guessing if this promise never resolves the test just times out, right?

**Review by AtofStryker — APPROVED** [review]

File: packages/https-proxy/test/integration/proxy_spec.js (hunk 1 above)
Comment (mschile) [reply packages/https-proxy/test/integration/proxy_spec.js:110]: Yep, times out after two seconds.
