### PR TITLE
fix: remove some CT functions and props

### LINKED ISSUE #24328: Removal of erraneous functionality in CT
We want to remove functionality that was deemed as erraneous with regards to critical functionality in Component Testing. Use the `no-dead-code` paradigm when practical to ensure users don't experience unnecessary blockers. 

### Global
- deprecate style injections (including impl in `mount-utils`).

### React
- `mountHook` function
- `unmount` function should no longer be exported
- Auto aliasing of mounted component

### Vue
- Remove mount callback

### PR DESCRIPTION
**Pull request by astone123**
- Closes #24328

### User facing changelog

- Styles, CSS and Stylesheet injections into `mount` have been removed
- `cypress/react` `mountHook` function no longer exists
- `cypress/react` `unmount` function is no longer exported
- Mounted React components are no longer aliased by default
- `cypress/vue` and `cypress/vue2` no longer export `mountCallback`. Use `mount` directly
- `cypress/react` no longer exports `mount` as a default export. Use destructuring: `import { mount } from 'cypress/react'`.

### Additional details

For GA we're taking the opportunity to make breaking changes to clean things up and remove functionality that we don't need anymore. This PR does the following:

- Removes the ability to inject styles into components via `mount`
    - Styles should either be defined in the spec file, the component support file, or in the component file itself
- Removes `mountHook` and related examples and tests from `cypress/react`
- Makes `unmount` internal only for React - no longer exported for use outside of the `cypress/react` package
- Removes the aliasing of mounted React components by default
- Removes `mountCallback` from `cypress/vue` and `cypress/vue2`
    - `mount` should be used directly instead

**NOTE**: There are a bunch of example tests in `npm/vue` that we're not running in CI, and I can't get them to pass. I decided to leave all of those as they were (some are still injecting styles and/or using `mountCallback` which is now invalid as of this PR). I created an issue to handle these tests here https://github.com/cypress-io/cypress/issues/24423

### Steps to test

I tried to break these up into small commits since there are a fair amount of changes here. It starts pretty clean in the top commits but towards the end things get a little more messy once I realized that I had broken some tests.

A lot of these are documentation changes so there's not much to test there, but it would be good to review the Percy snapshot changes and of course, the code changes.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? **I looked through the docs and I didn't see anything that needed to be updated based on these changes**
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/react/src/createMount.ts [hunk 1]
```diff
@@ -109,9 +96,7 @@ export const makeMountFn = (
     }
 
     return (
-      // Separate alias and returned value. Alias returns the component only, and the thenable returns the additional functions
       cy.wrap<React.ReactNode>(userComponent, { log: false })
```
Comment (ZachJW34) [inline npm/react/src/createMount.ts:103]: This line can be removed, the wrap was only for the alias

File: npm/react/src/mount.ts [hunk 2]
```diff
@@ -47,6 +47,6 @@ export function mount (jsx: React.ReactNode, options: MountOptions = {}, rerende
   return makeMountFn('mount', jsx, { ReactDom: ReactDOM, ...options }, rerenderKey, internalOptions)
 }
 
-export function unmount (options = { log: true }) {
```
Comment (ZachJW34) [inline npm/react/src/mount.ts:53]: This is a dead-end, we should still export it but throw an error in the exported version.

File: npm/react/src/createMount.ts [hunk 3]
```diff
@@ -109,9 +96,7 @@ export const makeMountFn = (
...
-      .as(displayName)
       .then(() => {
         return cy.wrap<MountReturn>({
```
Comment (ZachJW34) [inline npm/react/src/createMount.ts:105]: I'd say we should remove `unmount` from this return, I don't see a use-case for it.

**Review by ZachJW34 — CHANGES_REQUESTED** [review]
Most of the changes look good, but the `unmount` export needs to stick around if we are following the `no-dead-end` philosophy.

File: npm/react/docs/styles.md [hunk 4]
```diff
@@ -84,67 +103,3 @@ describe('footer component', () => {
   })
 })
 ```
-
-The component looks nice:
-
-![Footer component](../images/footer.png)
-
```
Comment (warrensplayer) [inline npm/react/docs/styles.md]: Did you mean to remove this part?  Looks like it belongs to the remaining section above.

File: npm/react/docs/styles.md [hunk 5]
```diff
@@ -41,6 +41,25 @@ it('is stylish', () => {
 })
 ```
 
+## Import from support file
+
+If you have stylesheets that should apply to all of your components, you can import those from your component support file.
```
Comment (warrensplayer) [inline npm/react/docs/styles.md]:
```suggestion
If you have stylesheets that should apply to all of your components, you can import those in your component support file.
```

File: npm/react/cypress/component/advanced/tutorial/square.cy.jsx [hunk 6]
```diff
@@ -37,16 +38,13 @@ describe('Square', () => {
...
-      cssFile: 'cypress/component/advanced/tutorial/tic-tac-toe.css',
-    })
+    mount(<Square />)
 
     // pause to show it
     cy.wait(1000)
     cy.get('.square').click()
     cy.wait(1000)
 
-    // check if style was applied
```
Comment (warrensplayer) [inline npm/react/cypress/component/advanced/tutorial/square.cy.jsx:49]: Could probably leave this comment.

File: npm/react/cypress/component/basic/unmount/README.md [hunk 7]
```diff
@@ -1,21 +0,0 @@
-# unmount
```
Comment (warrensplayer) [inline npm/react/cypress/component/basic/unmount/README.md]: There are other tests that were changed to remove the `unmount` command and replace it with mounting a new test component instead to cause the original mounted component to unmount.  Should we keep this `unmount` directory here and rewrite the examples to explicitly show how to test `unmount` functionality in a component or do those other examples suffice?

File: npm/react18/src/index.ts [hunk 8]
```diff
@@ -42,6 +42,6 @@ export function mount (jsx: React.ReactNode, options: MountOptions = {}, rerende
   return makeMountFn('mount', jsx, { ReactDom: ReactDOM, ...options }, rerenderKey, internalOptions)
 }
 
-export function unmount (options: UnmountArgs = { log: true }) {
+function unmount (options: UnmountArgs = { log: true }) {
```
Comment (warrensplayer) [inline npm/react18/src/index.ts]: @ZachJW34 Should this do the same as you suggested for `react`?  Still export but change the body to throw an error?

File: npm/mount-utils/src/index.ts [hunk 9]
```diff
@@ -1,42 +1,3 @@
-/**
```
Comment (lmiller1990) [inline npm/mount-utils/src/index.ts:1]: I am going to miss this a lot. I think we should reconsider deprecating this.

If we do, I think we should warn and **not** throw - I use this API heavily in my tests, and I think a lot other people do, too. Either way, it'd be nice to be able to upgrade to v11 without making major changes to my tests - if we could simply warn and deprecate in v12, that'd be nice, at least from my point of view.

File: npm/mount-utils/src/index.ts [hunk 10]
```diff
@@ -220,6 +31,38 @@ export function setupHooks (optionalCallback?: Function) {
...
 }
+
+/**
+ * Remove any style or extra link elements from the iframe placeholder
+ * left from any previous test
+ *
+ * @deprecated Removed as of Cypress 11.0.0
+ */
+export function cleanupStyles () {
+  throw new Error('cleanupStyles has been removed')
```
Comment (lmiller1990) [inline npm/mount-utils/src/index.ts]: This is pretty jarring - I think we need either

- deprecate but don't error - just warn?
- or something like "`cleanupStyles` is deprecated. Consider <link to useful migration docs with recommendations".

File: npm/react/README.md [hunk 11]
```diff
@@ -87,12 +72,7 @@ You may also specify the `ReactDOM` package to use. This can be useful in comple
 // if you have multiple versions of ReactDom in your monorepo
 import ReactDom from 'react-dom'
 
-mount(<Todo todo={todo} />, {
-  stylesheets: [
-    'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css',
-  ],
-  ReactDom
-})
+mount(<Todo todo={todo} />, { ReactDom })
```
Comment (lmiller1990) [inline npm/react/README.md]: I think this is named `reactDom`? (small `r`).

File: npm/react/src/mount.ts (hunk 2 above)
Comment (lmiller1990) [reply npm/react/src/mount.ts:53]: Should we deprecate and warn -> remove in v12? Just to make migration a bit smoother.

File: npm/vue/src/index.ts [hunk 12]
```diff
@@ -417,7 +415,7 @@ export function mountCallback (
   options: any = {},
 ): () => Cypress.Chainable {
   return () => {
-    return mount(component, options)
+    throw new Error('mountCallback has been removed')
```
Comment (lmiller1990) [inline npm/vue/src/index.ts]: Same here, let's as least recommend how to use `mount` and point somewhere useful. Maybe "`mountCallback` has been deprecated. Consider using `mount` with a `beforeEach` hook to mount your components" or something, perhaps?

**Review by lmiller1990 — COMMENTED** [review]
Left some comments, going to post a little more in Slack.

File: npm/react/src/mount.ts (hunk 2 above)
Comment (warrensplayer) [reply npm/react/src/mount.ts:53]: I think marking as `deprecated` as Lachlan suggests makes sense.  As far as erroring or warning, my vote is to stay with erroring based on the assumption that someone calling `unmount` is either wanting to test the "unmount" behavior or perform some sort of cleanup.  Not erroring would most likely cause some sort of other error or problem that would be harder to track down.  I could be swayed otherwise though.

**Review by warrensplayer — COMMENTED** [review]
A few comments and suggestions...

File: npm/react/src/mount.ts (hunk 2 above)
Comment (lmiller1990) [reply npm/react/src/mount.ts:53]: Fine with a straight up deprecation and error *if we have a obvious alternative/migration strategy* - a straight up deprecation without a recommendation is like "your test is broken now, good luck fixing it" which is not a nice DX.

File: npm/mount-utils/src/index.ts (hunk 9 above)
Comment (lmiller1990) [reply npm/mount-utils/src/index.ts:1]: Edit, talked in slack, we will deprecate but we need a good blog post or docs explaining "here's how you should do it now, and this is why it's better".

File: npm/react/cypress/component/basic/unmount/README.md (hunk 7 above)
Comment (lmiller1990) [reply npm/react/cypress/component/basic/unmount/README.md]: Yes, agreed, I was thinking this same thing, I'm going to revive this directory and explain the migration path.

**Comment by lmiller1990** [comment]
Okay, pushed two commits.

1. https://github.com/cypress-io/cypress/pull/24419/commits/b253b7f70100873bd3aacf62c65f4d68c49aee94
 
- added back `unmount` test and show how to handle it without `unmount`
- exported `getContainerEl` from `cypress/react` - needed for migrating `unmount`

I also wrote a list of deprecations and how to migrate, we should publish this somewhere and link to it as part of the error messages.

https://docs.google.com/document/d/1n4H0ADl0QNBWqbtGiKg4AzC0v8pQ8wZL0YLZeOCOg94/edit#heading=h.1mpc0zpa6u62

2. Improved errors https://github.com/cypress-io/cypress/pull/24419/commits/e8af254b28368c07e270dab9c6ea0b7a92e12387

Errors now link to migration guide. This is a better DX - it gives the user something actionable.

File: npm/react/src/mount.ts (hunk 2 above)
Comment (lmiller1990) [reply npm/react/src/mount.ts:53]: @ZachJW34 @astone123 @warrensplayer I thought about this a bit more. Here's my recommendations. I added some commits to make sure everything works (seems fine).

1. Export this, but error. The error contains a link to the migration guide. [Added here](https://github.com/cypress-io/cypress/pull/24419/commits/e8af254b28368c07e270dab9c6ea0b7a92e12387).
2. Have a non exported `unmount` (I called it `internalUnmount`) we use for unmounting the component.
3. Provide a migration strategy. I added an example showing [how to unmount without `unmount` here](https://github.com/cypress-io/cypress/pull/24419/commits/b253b7f70100873bd3aacf62c65f4d68c49aee94#diff-67b4f03fe5a8e7deb9b4055c2d8e04b8bce37642571d970d474fd11e0e14094bR18-R30) and in my [migration docs](https://docs.google.com/document/d/1n4H0ADl0QNBWqbtGiKg4AzC0v8pQ8wZL0YLZeOCOg94/edit#).

File: npm/mount-utils/src/index.ts (hunk 9 above)
Comment (lmiller1990) [reply npm/mount-utils/src/index.ts:1]: done https://github.com/cypress-io/cypress/pull/24419/commits/e8af254b28368c07e270dab9c6ea0b7a92e12387

File: npm/vue/src/index.ts (hunk 12 above)
Comment (lmiller1990) [reply npm/vue/src/index.ts]: https://github.com/cypress-io/cypress/pull/24419/commits/e8af254b28368c07e270dab9c6ea0b7a92e12387

File: npm/react/cypress/component/basic/unmount/README.md (hunk 7 above)
Comment (lmiller1990) [reply npm/react/cypress/component/basic/unmount/README.md]: done https://github.com/cypress-io/cypress/commit/b253b7f70100873bd3aacf62c65f4d68c49aee94

File: npm/react/docs/styles.md (hunk 4 above)
Comment (lmiller1990) [reply npm/react/docs/styles.md]: Added back

File: npm/mount-utils/src/index.ts (hunk 10 above)
Comment (lmiller1990) [reply npm/mount-utils/src/index.ts]: https://github.com/cypress-io/cypress/pull/24419#issuecomment-1298048924

File: npm/react/src/createMount.ts (hunk 3 above)
Comment (lmiller1990) [reply npm/react/src/createMount.ts:105]: Let's error instead and point to the migration guide? We can remove completely in Cypress 12. WDYT?

```js
      cy.wrap<React.ReactNode>(userComponent, { log: false })
      .then(() => {
        return cy.wrap<MountReturn>({
          // ...
          unmount: () => {
            throw new Error('unmount is no longer supported. See https://docs.cypress.io/guides/references/migration-guide#Component-Testing-Changes to migrate.')
          },
        }, { log: false })
```

Comment (ZachJW34) [reply npm/react/src/createMount.ts:105]: No dead ends!! Makes sense thanks for catching this

File: npm/react/src/createMount.ts [hunk 13]
```diff
@@ -109,14 +96,14 @@ export const makeMountFn = (
     }
 
     return (
-      // Separate alias and returned value. Alias returns the component only, and the thenable returns the additional functions
       cy.wrap<React.ReactNode>(userComponent, { log: false })
-      .as(displayName)
```
Comment (ZachJW34) [inline npm/react/src/createMount.ts:114]: We are removing the alias, we should also remove the type for it in `src/types.ts`

Comment (lmiller1990) [reply npm/react/src/createMount.ts:114]: Done

File: npm/react18/src/index.ts (hunk 8 above)
Comment (lmiller1990) [reply npm/react18/src/index.ts]: Done

File: npm/react/src/createMount.ts [hunk 14]
```diff
@@ -1,24 +1,12 @@
...
 import type { InternalMountOptions, MountOptions, MountReturn, UnmountArgs } from './types'
 
-/**
- * Inject custom style text or CSS file or 3rd party style resources
- */
-const injectStyles = (options: MountOptions) => {
-  return (): HTMLElement => {
-    const el = getContainerEl()
-
-    return injectStylesBeforeElement(options, document, el)
```
Comment (ZachJW34) [inline npm/react/src/createMount.ts:18]: Rather than removing outright, we should check the options for any of the `StyleOptions` properties and throw an error if still in use so that users are more aware of the removal of this functionality

File: npm/react/src/createMount.ts [hunk 15]
```diff
@@ -109,14 +95,14 @@ export const makeMountFn = (
...
-      // Separate alias and returned value. Alias returns the component only, and the thenable returns the additional functions
       cy.wrap<React.ReactNode>(userComponent, { log: false })
-      .as(displayName)
       .then(() => {
         return cy.wrap<MountReturn>({
           component: userComponent,
           rerender: (newComponent) => makeMountFn('rerender', newComponent, options, key, internalMountOptions),
-          unmount: internalMountOptions.unmount,
+          unmount: () => {
+            throw new Error('unmount is no longer supported. See https://docs.cypress.io/guides/references/migration-guide#Component-Testing-Changes to migrate.')
```
Comment (ZachJW34) [inline npm/react/src/createMount.ts]: Let's format this error based on our discussion with Brian (docsUrl, onLink, open-mode hyperlink vs run-mode)

File: npm/react/src/createMount.ts (hunk 13 above)
Comment (ZachJW34) [reply npm/react/src/createMount.ts:114]: Revisiting this, we should throw an error if the user passed in `cy.mount(<MyComponent />, { alias: 'MyComponent' })`

**Review by ZachJW34 — COMMENTED** [review]
For the Vue3 `cy.mount` yield change, we should use a Proxy to verify that the user is using the destructured `{wrapper, component}` properties and throw an error if they are using any other keys.

File: npm/react/src/createMount.ts (hunk 13 above)
Comment (lmiller1990) [reply npm/react/src/createMount.ts:114]: https://github.com/cypress-io/cypress/pull/24419/commits/e4b9943d4e98bfdb2312ae80902b126ed57255cd

File: npm/react/src/createMount.ts (hunk 14 above)
Comment (lmiller1990) [reply npm/react/src/createMount.ts:18]: https://github.com/cypress-io/cypress/pull/24419/commits/4af263a7534003b00d7c291abf444592b1b1b014

I could not get the for loop style testing working with the Svelte test. You cannot use `expect(() => ).to.throw` for custom commands (like `cy.mount`). You need to do Cypress.on...

I was not able to get this working with a for loop like the others due to how we queue up everything, the `on` listener was overriding each time. Either way, I think we've got good coverage for this error handling.

**Comment by lmiller1990** [comment]
@ZachJW34 proxy https://github.com/cypress-io/cypress/pull/24419/commits/299efd84a7607913ecc72adc0a11e9c37236fe6b

**Comment by lmiller1990** [comment]
On links: https://github.com/cypress-io/cypress/pull/24419/commits/6e9829512376750891666bd0bf1910db69e59a47

Consolidated in the same place in the same fashion as E2E does it.

**Comment by lmiller1990** [comment]
Note: on links appear like this (note they have a "Learn More" link pointing to `on.cypress.io...`

image

File: npm/mount-utils/src/index.ts [hunk 16]
```diff
@@ -220,6 +39,40 @@ export function setupHooks (optionalCallback?: Function) {
...
     optionalCallback?.()
-    cleanupStyles()
   })
 }
+
+/**
+ * Remove any style or extra link elements from the iframe placeholder
+ * left from any previous test
+ *
+ * @ Removed as of Cypress 11.0.0
```
Comment (rockindahizzy) [inline npm/mount-utils/src/index.ts]:
```suggestion
 * Removed as of Cypress 11.0.0
```

File: npm/mount-utils/src/index.ts [hunk 17]
```diff
@@ -220,6 +39,40 @@ export function setupHooks (optionalCallback?: Function) {
...
+ */
+export function cleanupStyles () {
```
Comment (rockindahizzy) [inline npm/mount-utils/src/index.ts:52]: Should this also have a link to the docs?

File: npm/react/cypress/component/advanced/renderless/mouse.cy.jsx [hunk 18]
```diff
@@ -23,7 +23,8 @@ describe('Renderless component', () => {
       expect(onMoved).to.have.been.calledWith(true)
     })
 
-    unmount()
+    // mount something else to trigger unmount
+    mount(<div>Test Component</div>)
```
Comment (rockindahizzy) [inline npm/react/cypress/component/advanced/renderless/mouse.cy.jsx:27]: Just a random thought, should we use our suggested recommendation for unmounting post v11 in this test?

`cy.then(() => ReactDom.unmountComponentAtNode(getContainerEl()))`

File: npm/react/cypress/component/advanced/set-timeout-example/loading-indicator.cy.jsx [hunk 19]
```diff
@@ -73,7 +73,9 @@ describe('LoadingIndicator', () => {
       )
 
       cy.tick(2010)
-      unmount()
+
+      // mount something else to trigger unmount
+      mount(<div>Test Component</div>)
```
Comment (rockindahizzy) [inline npm/react/cypress/component/advanced/set-timeout-example/loading-indicator.cy.jsx:78]: Should we use the suggested alternative:
`cy.then(() => ReactDom.unmountComponentAtNode(getContainerEl()))`

File: npm/react/cypress/component/advanced/timers/card-without-effect.cy.jsx [hunk 20]
```diff
@@ -28,7 +28,8 @@ it('should cleanup on being removed', () => {
     expect(onSelect).to.not.have.been.called
   })
 
-  unmount()
+  // mount something else so that unmount is called
+  mount(<div>Test Component</div>)
```
Comment (rockindahizzy) [inline npm/react/cypress/component/advanced/timers/card-without-effect.cy.jsx:32]: Should we use the suggested alternative:
`cy.then(() => ReactDom.unmountComponentAtNode(getContainerEl()))`

File: npm/react/cypress/component/advanced/timers/card-without-effect.cy.jsx [hunk 21]
```diff
@@ -44,7 +45,8 @@ it('should cleanup on being removed (using unmount)', () => {
...
```
Comment (rockindahizzy) [inline npm/react/cypress/component/advanced/timers/card-without-effect.cy.jsx:49]: Should we use the suggested alternative:
`cy.then(() => ReactDom.unmountComponentAtNode(getContainerEl()))`

File: npm/vue2/docs/styles.md [hunk 22]
```diff
@@ -1,60 +1,47 @@
...
+</template>
+
+<style lang="scss">
+  @import "./src/styles/main.css";
+</style>
+```
+
+You can also load styles in the following ways:
+
+## Import from spec
```
Comment (warrensplayer) [inline npm/vue2/docs/styles.md]:
```suggestion
## Import in the spec file
```

File: npm/vue2/docs/styles.md [hunk 23]
```diff
@@ -1,60 +1,47 @@
...
 
-mount(myComponent, {
-  style: string, // load inline style CSS
-  stylesheets: string | string[] // load external stylesheets
-})
+mount(myComponent)
 ```
 
-## Inline styles
+## Import from support file
```
Comment (warrensplayer) [inline npm/vue2/docs/styles.md]:
```suggestion
## Import in the component support file
```

File: npm/react/src/getDisplayName.ts [hunk 24]
```diff
@@ -1,4 +1,4 @@
-import { JSX } from './createMount'
+type JSX = Function & { displayName: string }
```
Comment (rockindahizzy) [inline npm/react/src/getDisplayName.ts:1]: Just out of curiosity: What is the reason we define it this way?

File: npm/mount-utils/src/index.ts [hunk 25]
```diff
@@ -220,6 +39,40 @@ export function setupHooks (optionalCallback?: Function) {
...
+ * Removed as of Cypress 11.0.0.
+ * @see https://on.cypress.io/migration-11-0-0-component-testing-updates
+ */
+export const injectStylesBeforeElement = (
+  options: Partial<StyleOptions & { log: boolean }>,
+  document: Document,
+  el: HTMLElement | null,
+) => {
+  Cypress.utils.throwErrByPath('mount.inject_styles_before_element')
+}
```
Comment (warrensplayer) [inline npm/mount-utils/src/index.ts:79]: The original function returned 'HTMLElement'.  Does this version that throws the error preserve that return type?

File: npm/react18/src/index.ts [hunk 26]
```diff
@@ -35,13 +36,26 @@ export function mount (jsx: React.ReactNode, options: MountOptions = {}, rerende
...
+ * Removed as of Cypress 11.0.0.
+ * @see https://on.cypress.io/migration-11-0-0-component-testing-updates
+ */
+export function unmount (options: UnmountArgs = { log: true }) {
+  // @ts-expect-error - undocumented API
+  Cypress.utils.throwErrByPath('mount.unmount')
+}
+
+// Re-export this to help with migrating away from `unmount`
+export {
```
Comment (rockindahizzy) [inline npm/react18/src/index.ts:63]: Do we export get `getContainerEl` in other frameworks? 

To me, it seems like we are removing unmount, but exporting something new so unmounting is still possible, which seems counter intuitive. It almost seems better to leave unmount in that case.

File: npm/react/docs/styles.md [hunk 27]
```diff
@@ -41,6 +41,25 @@ it('is stylish', () => {
 })
 ```
 
+## Import from support file
```
Comment (warrensplayer) [inline npm/react/docs/styles.md]:
```suggestion
## Import in the component support file
```

File: npm/react18/src/index.ts (hunk 26 above)
Comment (ZachJW34) [reply npm/react18/src/index.ts:63]: I'd say it feels a bit strange but having a solution to ease migration makes up for it. Plus, this is a primitive of all our other mounting frameworks which I don't really see as part of the `mount` API, just a utility for migration purposes.

Comment (rockindahizzy) [reply npm/react18/src/index.ts:63]: That helps it make sense in my brain. Just wanted to bring it up!

File: system-tests/project-fixtures/react/src/Unmount.cy.jsx [hunk 28]
```diff
@@ -17,10 +17,10 @@ describe('Comp with componentWillUnmount', () => {
     cy.contains('My component')
 
     // after we have confirmed the component exists let's remove it
-    // unmount() command is automatically enqueued
-    cy.unmount()
+    // mount something else so that unmount is called
+    cy.mount(<div>Test Component</div>)
```
Comment (rockindahizzy) [inline system-tests/project-fixtures/react/src/Unmount.cy.jsx:21]: Should we use the suggested alternative:
`cy.then(() => ReactDom.unmountComponentAtNode(getContainerEl()))`

**Review by rockindahizzy — COMMENTED** [review]
Added some minor things, overall this looks close!

File: npm/vue/src/index.ts [hunk 29]
```diff
@@ -427,12 +426,29 @@ export function mount (componentOptions: any, options: any = {}) {
...
+            // @ts-expect-error - internal API
+            Cypress.utils.throwErrByPath('mount.vue_yielded_value')
+          }
+
+          if (prop === 'then') {
+            return {
+              wrapper,
+              component: wrapper.vm,
+            }
+          }
```
Comment (warrensplayer) [inline npm/vue/src/index.ts]: Is the 'then' ever called?  The `chainable` will wrap this returned Proxy, but the returned value will not have a `then` on it.

File: npm/vue/src/index.ts [hunk 30]
```diff
@@ -427,12 +426,29 @@ export function mount (componentOptions: any, options: any = {}) {
...
+
+          if (prop === 'wrapper') {
+            return wrapper
+          }
+
+          if (prop === 'component') {
+            return wrapper.vm
+          }
+        },
+      })
```
Comment (warrensplayer) [inline npm/vue/src/index.ts]:
```suggestion
      const returnVal = {
        wrapper,
        component: wrapper.vm
      }
      
      return new Proxy(Object.create(returnVal), {
        get (obj, prop) {
        // throw an error if it looks like the caller is trying to call a method on the VueWrapper that was originally returned
          if (Reflect.get(wrapper, prop)) {
            // @ts-expect-error - internal API
            Cypress.utils.throwErrByPath('mount.vue_yielded_value')
          }

          return Reflect.get(obj, prop)
        },
      })
```

This implementation would handle adding a new property to the `returnVal` without having to also add an `if` clause in the proxy for it.  This is still just a suggestion.

File: packages/driver/src/cypress/error_messages.ts [hunk 31]
```diff
@@ -977,6 +977,42 @@ export default {
...
+    unmount: {
+      message: `\`unmount\` is no longer supported.`,
+      docsUrl: 'https://on.cypress.io/migration-11-0-0-component-testing-updates',
+    },
+    mount_callback: {
+      message: `\`mountCallback\` is no longer supported.`,
+      docsUrl: 'https://on.cypress.io/migration-11-0-0-component-testing-updates',
+    },
+    vue_yielded_value: {
+      message: 'As of Cypress 11, mount now yields an object with VueWrapper as a property. Destructure using `{ wrapper }` to access the VueWrapper.',
```
Comment (warrensplayer) [inline packages/driver/src/cypress/error_messages.ts]: Should this message also mention that the object has the `component` on it too?

**Review by warrensplayer — COMMENTED** [review]
Mostly small stuff.  I really like the checks and the error messages for all the removed items.  This going to make it super easy for anyone to fix any issues they have after upgrading.

File: npm/vue/src/index.ts (hunk 30 above)
Comment (ZachJW34) [reply npm/vue/src/index.ts]: This makes sense. The previous behavior did not allow for `cy.mount(...).its('component')`, your suggested implementation fixes this.

File: npm/mount-utils/src/index.ts (hunk 17 above)
Comment (astone123) [reply npm/mount-utils/src/index.ts:52]: @rockindahizzy it looks like this does link to the v11 CT migration guide
```js
    cleanup_styles: {
      message: `\`cleanupStyles\` is no longer supported.`,
      docsUrl: 'https://on.cypress.io/migration-11-0-0-component-testing-updates',
    }
```

Comment (rockindahizzy) [reply npm/mount-utils/src/index.ts:52]: Sorry I should have clarified. In the jsdoc we should add 
`* @see https://on.cypress.io/migration-11-0-0-component-testing-updates`

File: npm/mount-utils/src/index.ts (hunk 25 above)
Comment (astone123) [reply npm/mount-utils/src/index.ts:79]: No it doesn't. I don't think it can preserve that return type since we're throwing now

**Review by warrensplayer — APPROVED** [review]
Looking good to me.

**Review by rockindahizzy — APPROVED** [review]
My concerns were addressed. Thanks for all the hard work on this!

**Review by ZachJW34 — APPROVED** [review]
Ship it!
