### PR TITLE
Addresses #2953

### LINKED ISSUE #2953: validate inputs to "cy" commands better
## Cypress 3.1.3 on Mac

I have discovered this bad behavior while renaming `cy.contains(selector, text)` to `cy.get(...)` and leaving two strings there accidentally 

## bug

Try passing invalid arguments to `cy.get`, for example two strings and you will get error like ` TypeError: Cannot read property 'set' of undefined` without any explanation.

Example spec file

```js
it('calls cy get with 2 strings', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('.foo', 'bar')
})
it('calls cy get with string and number', () => {
  // TypeError: Cannot read property 'set' of undefined
  cy.get('.foo', 42)
})
it('calls cy get with string and a function', () => {
  // works (no warnings)
  cy.get('.foo', () => {})
})
it('calls cy get with string and empty object', () => {
  // works
  cy.get('.foo', {})
})
```

Here is screenshot of Cypress 3.1.3 running these tests

screen shot 2018-12-17 at 10 30 03 am

The first two tests should fail, but keep spinning on `GET` command. They fail with cryptic error message. The first test passes function instead of options object and does not complain, which is also weird. The last test fails correctly.

I have placed this spec into branch `get-args` at https://github.com/cypress-io/cypress-test-tiny/tree/get-args

## What should happen

Each command should validate the inputs at runtime and assert that the arguments are of expected type at runtime. I suggest using `check-more-types` and `lazy-ass` to generate meaningful user-friendly errors if the user passes incorrect arguments to each cy command.

### PR DESCRIPTION
**Pull request by ryan-snyder**
- Closes #2953

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?

### CODE REVIEW

**Comment by ryan-snyder** [comment]
I tried to match the wording of other errors as best I could. But the exact wording can of course be changed

**Comment by ryan-snyder** [comment]
Thanks for the feedback! Everything should be good now. What's the process in regards to the `issue/2953_spec.js` tests?

**Comment by jennifer-shehane** [comment]
@ryan-snyder I'm not exactly sure what you're question is. If the tests pass, it's good to merge after I rereview.

File: packages/driver/src/cy/commands/querying.coffee [hunk 1]
```diff
@@ -68,7 +70,10 @@ module.exports = (Commands, Cypress, cy, state, config) ->
 
     get: (selector, options = {}) ->
       ctx = @
-
+      ## can't get this error output any nicer as far as I know
+      if options is null or (typeIsArray options) or typeof options isnt 'object' then return $utils.throwErrByPath "get.invalid_options", {
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/commands/querying.coffee]: This is...sadly ideal. I don't totally understand the necessity behind the `typeIsArray` function. Why is `Array.isArray(options)` not sufficient?

Comment (flotwig) [reply packages/driver/src/cy/commands/querying.coffee]: Also, you can use `_.isArray` here instead since lodash is already included: https://lodash.com/docs/4.17.15#isArray

Comment (ryan-snyder) [reply packages/driver/src/cy/commands/querying.coffee]: Ah, I see. Not that familar with lodash or coffescript so I just googled coffescript isArray check and that was the first result.
