### PR TITLE
fix: cypress hang caused in run mode when test:before:run handler throws

### LINKED ISSUE #23039: [driver] errors thrown from test:before:run are incorrectly handled
### Current behavior

Errors thrown from `test:before:run` handlers are not propagated correctly and cause inconsistent behaviors in run vs open mode.

- in open mode: the error is reported for each test
- in run mode: the error is swallowed, no tests start and Cypress hangs indefinitely 

This failure occurs [here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L1548) in which the runner will catch the error [here](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L1564), however since the [runnable has not been set ](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L1559) the runnable (hook or test) technically hasn't officially starts which I think it causing the inconsistency with the finally handler which is in place to try to log the test results/errors and ensure the `after:test:run` and `after:test:run:async` events are emitted.

### Desired behavior

When errors thrown from `test:before:run` handlers, reports it correctly and consistently between run/open mode without hangs.

### Test code to reproduce

https://github.com/cypress-io/cypress-test-tiny/compare/verify-unhandled-err

CI job which timed out: https://ci.appveyor.com/project/cypress-io/cypress-test-tiny/builds/44331388

### Cypress Version

10.3.1

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #23039 

When in runMode, and a test fails, we will generate the before & after snapshots. We are relying on the reporter's UI to update to indicate when the before snapshot has been taken. Because `before:test:run` has yet to start the runnable, no logs have been updated and the reporter UI is essentially static and won't be updated, which means the snapshot callback was never executed, which caused the hang.

### User facing changelog
Fixed an edge-case bug where Cypress would hang in run-mode if an error was through from a `test:before:run` event handler. Fixed [#23039](https://github.com/cypress-io/cypress/issue/23039).

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cypress/runner.ts [hunk 1]
```diff
@@ -1426,23 +1434,27 @@ export default {
 
         const isHook = runnable.type === 'hook'
 
+        let runnableName = 'test'
+        let runnableId = runnable.id
+
+        if (isHook) {
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/runner.ts:1440]: this was more clean-up....

File: packages/reporter/src/test/test-model.ts [hunk 2]
```diff
@@ -163,6 +163,10 @@ export default class Test extends Runnable {
   }
 
   @action update (props: UpdatableTestProps, cb: UpdateTestCallback) {
+    if (this.state === 'processing' && !props.state) {
```
Comment (emilyrohrbough) [inline packages/reporter/src/test/test-model.ts:166]: this was the root-cause of this hang.

File: packages/driver/src/cypress/runner.ts [hunk 3]
```diff
@@ -1534,6 +1546,23 @@ export default {
...
+        // then override the test function to associate the error to the test
+        const handleBeforeTestEventError = (err: Error): boolean => {
+          const { fn } = runnable
+
+          const restore = () => {
+            return runnable.fn = fn
+          }
+
+          runnable.fn = () => {
+            restore()
```
Comment (mjhenkes) [inline packages/driver/src/cypress/runner.ts:1559]: Could this line just be resetting runnable.fn to fn instead of calling the restore function?
```suggestion
            runnable.fn = fn
```

**Review by mjhenkes — APPROVED** [review]

File: packages/driver/src/cypress/runner.ts [hunk 4]
```diff
@@ -1534,6 +1546,23 @@ export default {
...
 
+        // if either the TEST_BEFORE_RUN_EVENT or TEST_BEFORE_RUN_ASYNC_EVENT throws
+        // then override the test function to associate the error to the test
+        const handleBeforeTestEventError = (err: Error): boolean => {
+          const { fn } = runnable
+
+          const restore = () => {
+            return runnable.fn = fn
+          }
+
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/runner.ts:1557]:
```suggestion
```

**Review by AtofStryker — APPROVED** [review]
