### PR TITLE
fix: prevent timing out on short/skipped videos

### LINKED ISSUE #27898: 'Warning: We failed capturing this video' error when tests are very short duration (2 secs or less) or skipped
### Current behavior

When video is enabled and all tests on a spec are skipped, we get the following error in standard output:

```
Warning: We failed capturing this video.

This error will not affect or change the exit code.

TimeoutError: operation timed out
    at afterTimeout (/Users/ryanm/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/ryanm/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

### Desired behavior

In 12, we actually captured a video with no real information in this scenario but it didn't fail.

### Test code to reproduce

Any project really will work for this. Video needs to be enabled and a spec needs to have all tests skipped.

### Cypress Version

13.2.0

### Node version

v18.15.0

### Operating System

macOS 13.4.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #27898

This change prevents timing out when creating videos for short or skipped specs. This change will:
1. if the spec was skipped by the cloud , immediately end- we know no more frames are coming
2. otherwise, wait for 3000 ms for at least frames, then end regardless of frames written

The originally timeout logic was introduced because ffmpeg crashes in firefox if less than 2 frames were written to the input stream. This changed technically could resurfaces #6408, where the error `We failed to record the video` was observed for less than 2 frames. However, under the circumstances additional frames were never written, the fix to handle the `We failed to record the video` error was just replaced the `We failed to capture ... TimeoutError` error reported in #27898.

To handle the known scenario where ffmpeg did not receive enough frames, the error message has been updated to provide context to the Cypress issue.

Before | After 
--|--
Screen Shot 2024-01-05 at 2 00 17 PM|Screen Shot 2024-01-05 at 12 27 10 PM

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/video_capture.ts [hunk 1]
```diff
@@ -252,7 +259,7 @@ export function start (options: StartOptions) {
         .inputFPS(18)
 
         // 'vsync vfr' (variable framerate) works perfectly but fails on top page navigation
-        // since video timestamp resets to 0, timestamps already written will be dropped
+        // since video timest amp resets to 0, timestamps already written will be dropped
```
Comment (emilyrohrbough) [inline packages/server/lib/video_capture.ts]:
```suggestion
        // since video timestamp resets to 0, timestamps already written will be dropped
```

File: packages/server/test/integration/video_capture_spec.ts [hunk 2]
```diff
@@ -108,4 +90,45 @@ describe('Video Capture', () => {
...
+    })
+
+    it('ends immediately if more than two frames written', async () => {
+      const { writeVideoFrame, endVideoCapture } = await startSpiedVideoCapture(tmpFilename)
+
+      writeVideoFrame(fse.readFileSync(image1Path))
+      writeVideoFrame(fse.readFileSync(image2Path))
+      writeVideoFrame(fse.readFileSync(image3Path))
+
+      await endVideoCapture(false)
```
Comment (AtofStryker) [inline packages/server/test/integration/video_capture_spec.ts]: nit: mostly to keep the same readability style
```suggestion
      const waitForMoreFrames = false
      await endVideoCapture(waitForMoreFrames)
```

**Review by AtofStryker — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

File: packages/server/test/integration/video_capture_spec.ts [hunk 3]
```diff
@@ -108,4 +90,46 @@ describe('Video Capture', () => {
...
+    })
+
+    it('ends immediately if more than two frames written', async () => {
+      const { writeVideoFrame, endVideoCapture } = await startSpiedVideoCapture(tmpFilename)
+
+      writeVideoFrame(fse.readFileSync(image1Path))
+      writeVideoFrame(fse.readFileSync(image2Path))
+      writeVideoFrame(fse.readFileSync(image3Path))
+
+      const waitForMoreFrames = false
```
Comment (emilyrohrbough) [inline packages/server/test/integration/video_capture_spec.ts:108]:
```suggestion
      const waitForMoreFrames = false

```
