### PR TITLE
fix: `Cypress.testingType` should not be `undefined`.

### LINKED ISSUE #17664: Cypress.testingType is undefined
### Current behavior

Trying to use `Cypress.testingType` according to the docs https://docs.cypress.io/api/cypress-api/testing-type but getting `undefined` in Cypress v8.2.0

Screen Shot 2021-08-09 at 19 45 43

### Desired behavior

_No response_

### Test code to reproduce

Reproducible example https://github.com/bahmutov/test-testing-type

### Cypress Version

8.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #17664

### User facing changelog

`Cypress.testingType` should be one of `'e2e'` or `'component'`. But it was `undefined` in `e2e` tests.

### Additional details
- Why was this change necessary? => `Cypress.testingType` wasn't working as defined.
- What is affected by this change? => N/A
- Any implementation details to explain? => `testingType` value wasn't passed from the server to the client.

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by sainthkh** [comment]
flaky failures.

File: packages/server-ct/src/routes-ct.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ export interface InitializeRoutes {
   networkProxy: NetworkProxy
   getRemoteState: () => any
   onError: (...args: unknown[]) => any
+  testingType: 'component' | 'e2e'
```
Comment (lmiller1990) [inline packages/server-ct/src/routes-ct.ts:25]: Can grab the type here to avoid duplication: https://github.com/cypress-io/cypress/blob/bf6560691436a5a953f7e03e0ea3de38f3d2a632/cli/types/cypress.d.ts#L11

**Review by lmiller1990 — COMMENTED** [review]
Just one comment

File: packages/server-ct/src/routes-ct.ts (hunk 1 above)
Comment (lmiller1990) [reply packages/server-ct/src/routes-ct.ts:25]: `Cypress['TestingType']`

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Tested it out, seems fine! Thanks.

image
