### PR TITLE
fix(cypress/webpack-dev-server): correct path for `indexHtmlFile`

### LINKED ISSUE #26400: Custom location of cypress.config.ts crash on spec update in component tests
### Current behavior

The `onSpecsChange` handler in the `CypressCTWebpackPlugin` file calculates the location of the `indexHtmlFile` based on the project root, not the location of the `cypress.config.ts` file.
If the config file is located at a location other than the project root, trying to update the spec file while it's opened in the runner results in a crash with an error provided in the logs section below (rarely it doesn't fail on the first attempt but then fails on the second one).

### Desired behavior

The `indexHtmlFile` location is calculated based on the location of the `cypress.config.ts` file where it's declared. not the project root which may be a completely different path

### Test code to reproduce

I cannot provide our project code, however, you can scaffold any component testing structure where the config file is not located in the project root and try to update the spec that's being run by the runner at the moment

For example, our structure is as follows
```
package.json,
package-lock.json
src,
test
  cypress
    specs
    cypress.config.ts
    support
      component-index.html
    ...otherFiles
```

and `indexHtmlFile` in the `cypress.config.ts` file is set to `support/component-index.html`

### Cypress Version

12.9.0

### Node version

v18.15.0

### Operating System

macOS Ventura 13.3

### Debug Logs

```shell
Error: ENOENT: no such file or directory, utime '/Users/{user}/work/{repo}/support/component-index.html'
    at utimesSync (node:fs:2061:3)
    at EventEmitter.CypressCTWebpackPlugin.onSpecsChange (/Users/{user}/Library/Caches/Cypress/12.9.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-dev-server/dist/CypressCTWebpackPlugin.js:70:13)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at EventEmitter. (/Users/{user}/Library/Caches/Cypress/12.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/dev-server.js:9:21)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process. (/Users/{user}/Library/Caches/Cypress/12.9.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/{user}/Library/Caches/Cypress/12.9.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Other

This issue was actually already reported but discussion stopped: https://github.com/cypress-io/cypress/issues/24398#issuecomment-1450641033
I did some debugging and found the issue at the path `/Users/{user}/Library/Caches/Cypress/12.9.0/Cypress.app/Contents/Resources/app/node_modules/@cypress/webpack-dev-server/dist/CypressCTWebpackPlugin.js` line 70 where the project root (which is always the project root folder where `package.json` and `package-lock.json` are located) and the `indexHtmlFile` property in our case is `indexHtmlFile: support/component-index.html` are concatenated and the result is `/Users/{user}/work/{repo-name}/support/component-index.html` which doesn't exist in our project structure
image
From what I gathered, changes done in [this PR](https://github.com/cypress-io/cypress/issues/24398) influence this

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/26400

### Additional details

We are not passing the correct path to the `indexHtmlFile`. If `cypress.config.js` is not in the root of the project, the path is wrong and webpack errors.

### Steps to test

I added a test. Alternatively test against my minimal reproduction https://github.com/lmiller1990/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-26400?expand=1

### How has the user experience changed?

Can have `cypress.config` in a directory that is not the root of the project.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ export function makeCypressWebpackConfig (
     },
     plugins: [
       new (HtmlWebpackPlugin as typeof import('html-webpack-plugin-5'))({
-        template: indexHtmlFile,
+        template: path.join(projectRoot, indexHtmlFile),
```
Comment (lmiller1990) [inline npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts]: This is the fix.

File: system-tests/project-fixtures/react/webpack.config.js [hunk 2]
```diff
@@ -18,6 +18,11 @@ module.exports = {
         exclude: /node_modules/,
         use: {
           loader: 'babel-loader',
+          options: {
```
Comment (lmiller1990) [inline system-tests/project-fixtures/react/webpack.config.js]: I had to add these, I'm not sure why it was not picking up the `.babelrc`. Either way, it's unrelated to this bug fix - although there might be another, unrelated issue around babel-loader not automatically finding `.babelrc` (that was not introduced by this PR).

If that is an issue, can look into fixing it separately - no bandwidth to go deeper into specifics right now.

Comment (warrensplayer) [reply system-tests/project-fixtures/react/webpack.config.js]: Was this working before the changes in this PR?   How did you know that babel was not loading correctly?  Did you see an error?

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts (hunk 1 above)
Comment (warrensplayer) [reply npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts]: Some tests are failing on this line: https://app.circleci.com/pipelines/github/cypress-io/cypress/54632/workflows/e04d8993-cb44-42a9-9061-e7b37bef32f2/jobs/2257912

Looks like they are missing setting the `indexHtmlFile` value

File: system-tests/project-fixtures/react/cypress/cypress-webpack-dev-server-function.config.ts [hunk 3]
```diff
@@ -0,0 +1,17 @@
+import { defineConfig } from 'cypress'
```
Comment (warrensplayer) [inline system-tests/project-fixtures/react/cypress/cypress-webpack-dev-server-function.config.ts]: Can the original file this was copied from be removed now?  It looks like it is no longer used by anything.

File: npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts [hunk 4]
```diff
@@ -14,7 +14,7 @@ describe('Config options', () => {
 
   it('supports @cypress/webpack-dev-server', () => {
     cy.scaffoldProject('webpack5_wds4-react')
-    cy.openProject('webpack5_wds4-react', ['--config-file', 'cypress-webpack-dev-server-function.config.ts'])
+    cy.openProject('webpack5_wds4-react', ['--config-file', 'cypress/cypress-webpack-dev-server-function.config.ts'])
     cy.startAppServer('component')
```
Comment (warrensplayer) [inline npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts]: I know that adding system tests makes the test runs take longer, but wondering if this original test should be left alone and add a new test that calls out that it is just testing having the config file in another location.  Without knowing the history of this issue, it would be confusing as to why this test in this file is the only one that has the config file under the `cypress` directory.  At the very least, a good comment for this test explaining that it is combining testing the `devServer` parameter as a function and testing the config file being somewhere other than the root would be nice.

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts (hunk 1 above)
Comment (astone123) [reply npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts]: I think I fixed this in https://github.com/cypress-io/cypress/pull/27320/commits/b557e6e722f3fd1851c8540457146ecfdd6239fd. If `indexHtmlFile` is undefined, we'll just pass undefined like we've been doing. Otherwise we'll call `join` to create the path

File: npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts (hunk 4 above)
Comment (lmiller1990) [reply npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts]: Sure thing - I can do this. I like to keep the amount of test projects small, but this seems reasonable.

File: system-tests/project-fixtures/react/webpack.config.js (hunk 2 above)
Comment (lmiller1990) [reply system-tests/project-fixtures/react/webpack.config.js]: It is complaining about not knowing about JSX - I think what's happening is some other part of the toolchain (webpack) expects `.babelrc` to exist in the same directory where the process is running, which is now a **nested** directory (in `cypress/` in this case.

I am not sure if this going to impact users. It's likely this is a problem no-one has encountered, since you can't current run with a nested config file, anyway.

Either way, I will create a more minimal project are requested that will side step this issue. Projects using babel and relying on `.babelrc` might run into this, but it'll be a separate and unrelated bug...

Comment (lmiller1990) [reply system-tests/project-fixtures/react/webpack.config.js]: I pushed a simple project that won't deal with this. The fact webpack relies on the cwd to find the `babelrc` might be an issue but I'm not sure that's even our problem to solve.

File: npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts (hunk 4 above)
Comment (lmiller1990) [reply npm/webpack-dev-server/cypress/e2e/webpack-dev-server.cy.ts]: Done

**Review by astone123 — APPROVED** [review]
Looks good 👍🏻

**Review by jordanpowell88 — APPROVED** [review]
