### PR TITLE
Fix formatting in Command Log test results.

### LINKED ISSUE #25: Commands UI assert errors should clearly delineate integers from strings.
The ASSERT error (in red background) on the commands UI does not signify whether my value is a string or not. The AssertionError (in yellow background) more clearly defines my error (that the integer 25 does not equal "25").

**Example**
screen shot 2015-04-20 at 11 57 25 am

### To reproduce:

```js
it('test', () => {
  expect(25).to.eq('25')
})
```

### LINKED ISSUE #753: Incorrectly formatted log message for "have.all.keys" assertion
All versions of Cypress when making this assertion

```js
it('expect - assert shape of an object', function(){
  const person = {
    name: 'Joe',
    age: 20
  }
  expect(person).to.have.all.keys('name', 'age')
})
```
Look at the reporter message - looks very weird

have all keys

I added example test to https://github.com/cypress-io/cypress-example-kitchensink/pull/17

### LINKED ISSUE #1360: asterisks displaying instead of single quotes in Command Log assertion
### Current behavior:
Command Log for assertion chain includes confusing asterisks. I suspect it may be replacing `\n` with `**`. 

screen shot 2018-02-21 at 2 24 08 pm

**Even displays in passing tests**
screen shot 2018-02-21 at 2 27 27 pm

### Desired behavior:

Error in Command Log should display as: 

`expected '<div.duration>' to have text '37:46', but the text was ' 37:46 '`

**Code to reproduce**
```js
cy.get(".duration").should("include.text", "37:46")
```

- Cypress Version: 2.0.3
- Browser Version: Crome

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #25
- Closes #753
- Closes #1360

I fixed these 3 issues together because implementing one logic can affect other issues. 

### User facing changelog

* Formats number strings in test results in quotes. In other words, 25 -> '25'.
* Formats keys properly. 
* Formats when there are empty spaces between \*\* and \*\*. 

##### Issue #1360

> Command Log for assertion chain includes confusing asterisks. I suspect it may be replacing \n with **.
>
> 

#### What is affected by this change?

Not much. I added a few tests to show this case clearly. 

#### Any implementation details to explain?

Not much. Just fixed some regexes. 

### How has the user experience changed?

Before: above.

After:

Screenshot from 2019-11-07 10-56-15

Screenshot from 2019-11-11 11-36-39

### PR Tasks

- [x] Have tests been added/updated?
- ~~Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? ~~
- ~~Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?~~
- ~~Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?~~

### CODE REVIEW

**Comment by brian-mann** [comment]
Let's get some eyes on this and get this out in `3.6.1` @cypress-io/test-runner team

**Comment by Bkucera** [comment]
We'll need actual assertions on the output during the tests that have been added. Right now there's no way for them to fail

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 1]
```diff
@@ -976,6 +976,57 @@ describe('src/cy/commands/assertions', () => {
...
+
+    it('formats keys properly for "have.all.keys"', function () {
+      const person = {
+        name: 'Joe',
+        age: 20,
+      }
+
+      expect(person).to.have.all.keys('name', 'age')
+    })
+  })
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: would these have failed before the src changes? We should add assertions on the log output to turn these into valid tests

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 2]
```diff
@@ -976,6 +976,57 @@ describe('src/cy/commands/assertions', () => {
...
+    })
+
+    it('preserves quotation marks in empty string', function () {
+      try {
+        expect(42).to.eq('')
+      } catch (error) {} /* eslint-disable-line no-empty */
+    })
+
+    it('preserves quotation marks if escaped', function () {
+      expect('\'cypress\'').to.eq('\'cypress\'')
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: we should use template literals instead of having to escape the single quotes

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 3]
```diff
@@ -976,6 +976,57 @@ describe('src/cy/commands/assertions', () => {
...
+      })
+    })
+
+    it('preserves quotation marks in empty string', function () {
+      try {
+        expect(42).to.eq('')
+      } catch (error) {} /* eslint-disable-line no-empty */
+    })
+
+    it('preserves quotation marks if escaped', function () {
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: prefer arrow syntax

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 1 above)
Comment (chrisbreiding) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: Agreed. We need tests that actually verify this behavior. It might be worthwhile to move out and expose the `removeOrKeepSingleQuotesBetweenStars` and `replaceArgMessages` so they can be tested unit-style.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 4]
```diff
@@ -976,6 +976,57 @@ describe('src/cy/commands/assertions', () => {
...
+      expect({ foo: 'bar' }).to.deep.eq({ foo: 'bar' })
+    })
+
+    it('formats keys properly for "have.all.keys"', function () {
+      const person = {
+        name: 'Joe',
+        age: 20,
+      }
+
+      expect(person).to.have.all.keys('name', 'age')
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: this one's showing up for me without the bold 
image

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 1 above)
Comment (sainthkh) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: I've checked the tests in `assertions_spec.js` and mimicked the tests it uses to validate messages.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 2 above)
Comment (sainthkh) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: Done.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 4 above)
Comment (sainthkh) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: I've added tests for "boldness". Review them please.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 3 above)
Comment (sainthkh) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: Done

**Comment by sainthkh** [comment]
1. Added one more issue: #1360. Because I thought it is also related with this PR. 
2. build-binary failed because of tar.extract. It seems that it's unrelated to this PR.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 5]
```diff
@@ -976,6 +976,110 @@ describe('src/cy/commands/assertions', () => {
...
+        } catch (error) {} /* eslint-disable-line no-empty */
+      },
+      `expected **42** to equal **''**`,
+      done)
+    })
+
+    it('preserves quotation marks if escaped', (done) => {
+      expectMarkdown(
+        () => expect(`\'cypress\'`).to.eq(`\'cypress\'`),
+        // ****'cypress'**** -> ** for emphasizing result string  + ** for emphasizing the entire result.
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: thanks for adding this comment :pray:

Comment (sainthkh) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: Actually, when I saw this, I was too wondering why this happened. 

And thought many developers who will read this code later would be confused when they saw `****`. That's why I've added this comment.

**Comment by Bkucera** [comment]
Awesome job @sainthkh!
