### PR TITLE
fix: disable automatic request retries

### LINKED ISSUE #19043: Failed requests retry 25 times
### Current behavior

Failed requests will retry 25 times. 

From my understanding previously chrome would not retry failed requests during automation. So cypress implemented our own retry logic. Since that time it seems that chrome has enabled retries for automation. It seems that the combination of our retries and chromes retries end up causing failed requests to retry 25 times. I think that we will retry 5 times for each time chrome retries.

Current location of chrome's auto reloading code: https://source.chromium.org/chromium/chromium/src/+/main:components/error_page/content/browser/net_error_auto_reloader.cc;l=22;drc=a618b831a17a7d178f56ee720e55483e7403b01e

### Desired behavior

I believe tests should retry only 5 times, but we're going to have to also investigate the retry behviour in firefox and webkit to find out what the optimal solution is.

#### Possibilities

*disable browser retries and handle it with cypress
*disable cypress retries and let the browsers handle it.

We also need to identify when this change was made and determine if we wish to support reties for older versions of chrome.

### Test code to reproduce

Using branch [mimatched-xhr-calls](https://github.com/cypress-io/cypress/tree/mismatched-xhr-calls)
I've created a test case called '[retry_spec](https://github.com/cypress-io/cypress/blob/mismatched-xhr-calls/packages/driver/cypress/integration/e2e/retry_spec.js)` in the driver to showcase the problem.

The test introduces a route that will fail x number of times before succeeding. When set lower than 25 it will eventually succeed. Higher than 24, it will fail.

Also these tests can be enabled to check on chrome browser retry behavior.
https://github.com/cypress-io/cypress/blob/develop/system-tests/test/network_error_handling_spec.js#L257 

### Cypress Version

9.0.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #19043 
- Makes #19039 less likely to occur by reversing order that pre-requests are matched in: 6292de3

### User facing changelog

- Removed automatic retries for failed HTTP requests through the proxy. This fixes an issue where failed requests could be re-sent too many times in some conditions. This change could increase the number of failed requests that your app sees.
- Reduced the occurrence of an issue where logs for `fetch` and `xhr` requests could be associated with the wrong request.

### Additional details

- This disables the proxy layer's automatic retries.
	- Rationale: https://github.com/cypress-io/cypress/issues/19043#issuecomment-983006710
- Automatic retries are still used for `cy.visit`'s `resolve:url` and `cy.request`, since those are not retriable by the browser.
- Fully removing automatic retries is a breaking change b/c we expose retryOnNetworkFailure and retryOnStatusCodeFailure as opts on cy.request, cy.visit
- Has the potential to 

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/request.js [hunk 1]
```diff
@@ -118,6 +118,11 @@ const maybeRetryOnNetworkFailure = function (err, options = {}) {
     // https://github.com/cypress-io/cypress/pull/6705
     debug('detected TLS version error, setting min version to TLSv1')
     opts.minVersion = 'TLSv1'
+
+    if (retryIntervals.length === 0) {
+      // normally, this request would not be retried, but we need to retry in order to support TLSv1
+      return onNext(0, 1)
```
Comment (mjhenkes) [inline packages/server/lib/request.js:124]: what does `onNext(0, 1)` do? Is there a way we could make the code more descriptive?

File: packages/driver/src/cy/commands/request.ts [hunk 2]
```diff
@@ -28,6 +28,7 @@ const REQUEST_DEFAULTS = {
   timeout: null,
   followRedirect: true,
   failOnStatusCode: true,
+  retryIntervals: [0, 100, 200, 200],
```
Comment (mjhenkes) [inline packages/driver/src/cy/commands/request.ts:31]: Why are we adding retry intervals here and above?

File: packages/server/lib/request.js (hunk 1 above)
Comment (flotwig) [reply packages/server/lib/request.js]: https://github.com/cypress-io/cypress/blob/9e4c13a6c181689ee832606fd74e3c1b8ae1ce69/packages/server/lib/request.js#L284-L288

So this runs a single `retry` instantly.

> Is there a way we could make the code more descriptive?

So many ways. :smile: I started refactoring this file and it became a much bigger task, so I decided to keep this PR to the bare minimum changes. For now I pushed a commit to clean up `onNext`/`onElse` specifically: 5df0b86

File: packages/driver/src/cy/commands/request.ts (hunk 2 above)
Comment (flotwig) [reply packages/driver/src/cy/commands/request.ts:31]: Previously this would inherit from the defaults in `server/lib/request`, but now it has to set its own. 

Automatic retries are still used for `cy.visit`'s `resolve:url` and `cy.request`, since those are not retriable by the browser. Fully removing automatic retries is a breaking change b/c we expose retryOnNetworkFailure and retryOnStatusCodeFailure as opts on cy.request, cy.visit

**Review by mjhenkes — APPROVED** [review]

File: packages/server/lib/request.js [hunk 3]
```diff
@@ -281,7 +286,7 @@ const createRetryingRequestStream = function (opts = {}) {
     const reqStream = r(opts)
     let didReceiveResponse = false
 
-    const retry = function (delay, attempt) {
+    const retry = function ({ delay, attempt }) {
```
Comment (tbiethman) [inline packages/server/lib/request.js:289]: 👍  to destructuring refactor

**Review by tbiethman — APPROVED** [review]
