### PR TITLE
Fix for issue-1226 - preserve styles for empty style tags - css-in-js

### LINKED ISSUE #1226: Snapshots Don't Preserver injected style tags (css-in-js)
- Operating System: MacOS 10.12.6
- Cypress Version: 1.4.1
- Browser Version: Chrome 63

### Current behavior:
My project uses a css-in-js library (in this case [cxs](https://github.com/jxnblk/cxs)) to apply styling. The cxs library appends a style tag to the `<head>` at runtime and adds style definitions to this injected tag.
When tests run normally, styling appears as expected.
However, when switching between snapshots, injected style tags (css-in-js) is not preserved and styling is broken on the page

### Desired behavior:
Styles should be preserved, or the javascript bundle should be reran so that styles can be injected again.

(although the second option sounds less likely to be reliable given the nature of snapshotting).

### How to reproduce:
Run Cypress with a project that uses a css-in-js library that appends a style tags in `<head>` at run time.

### Additional Info (images, stack traces, etc)
(pseudo) DOM structure while tests are running (correct behavior):

```html
<iframe id="Your App: 'my app name'">
  ...
  <head>
    ...
    < !-- style tag injected by cxs -->
    <style id="_cxs_"></style>
    ...
  </head>
  ...
</iframe>
```

(pseudo) DOM structure while navigating between snapshots after tests have finished:

```html
<iframe id="Your App: 'my app name'">
  ...
  <head>
    ...
    <!-- I did notice that there is still a style tag in the head 
    that _could_ be the injected style tag, but its missing
    its style declarations, and no longer has the `_cxs_` id, so this could just be a red herring -->
    <style></style>
    ...
  </head>
  ...
</iframe>
```

### PR DESCRIPTION
**Pull request by przemuh**
closes #1226

### CODE REVIEW

File: packages/driver/src/cy/snapshots.coffee [hunk 1]
```diff
@@ -47,7 +47,11 @@ getStylesFor = (doc, $$, stylesheets, location) ->
       }
     else
       ## otherwise, it's a style tag, and we can just grab its content
-      makePathsAbsoluteToDoc(doc, $$(stylesheet).text())
+      styleRules = $$(stylesheet).text() ||
```
Comment (chrisbreiding) [inline packages/driver/src/cy/snapshots.coffee]: Is it possible a stylesheet could have text inside it and inserted rules? If so, we should account for that case too.

Comment (przemuh) [reply packages/driver/src/cy/snapshots.coffee]: If <style> has text inside then text is converted into style rules:

image

I didn't want to change it only for `sheet.rules.map()` because already existing tests were not pass (as you can see browser optimises css rule, add `;` and change colour values.

What do you think ?

Comment (przemuh) [reply packages/driver/src/cy/snapshots.coffee]: @chrisbreiding Check the latest commit and let me know what do you think.

Comment (chrisbreiding) [reply packages/driver/src/cy/snapshots.coffee]: Looks good to me. Thanks!

**Comment by przemuh** [comment]
🎉
