### PR TITLE
fix: issue with proxy correlations and web/shared workers

### LINKED ISSUE #28104: Requests that are cached in web and shared workers can be improperly correlated in the proxy
### Current behavior

This is a similar issue to https://github.com/cypress-io/cypress/issues/28056. Basically we are not tracking on the web/shared worker targets and thus any requests coming from those targets are not tracked in CDP and thus not correlated properly in the proxy. This can cause delays of 2 seconds for these requests.

### Desired behavior

Correlate these requests properly

### Test code to reproduce

Issue a request from a shared/web worker

### Cypress Version

13.3.2

### Node version

v18.15.0

### Operating System

any

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28104

### Additional details

We fixed service workers on #28060 however it appears that workers need to be handled differently in terms of target tracking (we need to use Target.setAutoAttach instead of Target.setDiscoverTargets). This PR handles web workers in that fashion and ensures that shared workers work as well.

### Steps to test

I added a few system tests to cover all of the scenarios.

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by chrisbreiding — APPROVED** [review]

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 1]
```diff
@@ -151,9 +151,10 @@ export class BrowserCriClient {
         onAsynchronousError,
         onReconnect,
         protocolManager,
+        fullyManageTabs,
       })
 
-      const browserCriClient = new BrowserCriClient(browserClient, versionInfo, host!, port, browserName, onAsynchronousError, protocolManager)
+      const browserCriClient = new BrowserCriClient(browserClient, versionInfo, host!, port, browserName, onAsynchronousError, protocolManager, fullyManageTabs)
```
Comment (cacieprins) [inline packages/server/lib/browsers/browser-cri-client.ts]: There are quite a few parameters to this constructor now - should we refactor to a parameter object for better readability?

File: packages/server/lib/browsers/utils.ts [hunk 2]
```diff
@@ -419,6 +419,18 @@ const listenForDownload = () => {
   }
 }
 
+const getNetworkEnableOptions = (protocolManager: ProtocolManagerShape | undefined) => {
```
Comment (cacieprins) [inline packages/server/lib/browsers/utils.ts]: could this be a method on the protocol manager itself?

**Review by cacieprins — CHANGES_REQUESTED** [review]

File: cli/CHANGELOG.md [hunk 3]
```diff
@@ -1,4 +1,10 @@
 <!-- See the ../guides/writing-the-cypress-changelog.md for details on writing the changelog. -->
+## 13.3.3
+
+_Released 10/24/2023 (PENDING)_
+
+- Fixed a performance regression in `13.3.1` with proxy correlation timeouts and requests issued from web and shared workers. Fixes [#28104](https://github.com/cypress-io/cypress/issues/28104).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md:8]:
```suggestion
**Bugfixes:**

- Fixed a performance regression in `13.3.1` with proxy correlation timeouts and requests issued from web and shared workers. Fixes [#28104](https://github.com/cypress-io/cypress/issues/28104).
```

File: packages/server/lib/browsers/utils.ts (hunk 2 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/utils.ts]: Good call: [`0d5cad4` (#28105)](https://github.com/cypress-io/cypress/pull/28105/commits/0d5cad4fe2c7e55e625e54d410ba14aceed04f60)

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 1 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/browser-cri-client.ts]: Good call. This is somewhat existing code, but good time for a cleanup: [`0d5cad4` (#28105)](https://github.com/cypress-io/cypress/pull/28105/commits/0d5cad4fe2c7e55e625e54d410ba14aceed04f60)

**Review by cacieprins — APPROVED** [review]
