### PR TITLE
fix: does not show more than one .should('contain') assertion when chained after .should('be.visible')

### LINKED ISSUE #16006: Does not show more than one .should('contain') assertion when chained after .should('be.visible')
### Current behavior
Test runner shows misleading info when more than one `.should('contain')` assertion is chained after `.should('be.visible')`
Consider following code

```js
 cy.get('[data-cy=mobile-payments-template]')
        .should('be.visible')
        .should('contain', 'Something')
        .should('contain', '+420 737 799 983');
```
This is displayed incorrectly in Test runner (notice the replaced `to contain Something` with `to be visible`)
image

When I delete the `should('be.visible')` assertion, it's displayed properly
image

### Desired behavior
Display `to contain Something`
image

### Versions
6.8.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #16006

### User facing changelog

Cypress now correctly shows all `.should('contain')` assertions when chained after `.should('be.visible')`.

### Additional details
- Why was this change necessary? => Cypress showed some messages like `should('contain')` twice and hid other assertions.
- What is affected by this change? => N/A
- Any implementation details to explain? => When `applyChainer` in `asserting.js` triggered `assert` in `chai_jquery.js` every time `memo[value]` is called. I limited it to be called once. 

### How has the user experience changed?

```js
cy.get('#x')
  .should('be.visible')
  .should('contain', 'Something')
  .should('contain', '+123')
```

#### Before

Screen Shot 2021-04-28 at 12 04 35 PM

#### After

Screen Shot 2021-04-28 at 12 03 34 PM

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 1]
```diff
@@ -2492,7 +2503,7 @@ describe('src/cy/commands/assertions', () => {
 
         cy.get('button:first').should('have.focus')
         .then(() => {
-          expect(stub).to.be.calledThrice
+          expect(stub).to.be.calledTwice
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/assertions_spec.js:2506]: It should be called twice because it was checked twice in L2502 and L2504. But before this PR, it was called twice in L2504, that's why it was thrice.

**Comment by sainthkh** [comment]
flaky failures?

**Comment by jennifer-shehane** [comment]
@sainthkh This Desktop-gui failure is a bug in Cypress, so sometimes our tests fail with this error. See https://github.com/cypress-io/cypress/issues/15101

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 2]
```diff
@@ -127,6 +127,17 @@ describe('src/cy/commands/assertions', () => {
       }).should('deep.eq', { foo: 'baz' })
     })
 
+    // https://github.com/cypress-io/cypress/issues/16006
+    it(`does not show more than one .should('contain') assertion when chained after .should('be.visible')`, function () {
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/commands/assertions_spec.js:131]: I feel like this is not accurate to what was happening. The problem was that it would show multiple 'visible' assertions when there was only 1 visible assertion and only show one of the contains assertions even though there were 2 contains assertions. 
```suggestion
    it(`shows all .should('contain') assertions when chained after .should('be.visible')`, function () {
```

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 3]
```diff
@@ -127,6 +127,17 @@ describe('src/cy/commands/assertions', () => {
...
+      cy.get('#data-number')
+      .should('be.visible')
+      .should('contain', 'span')
+      .should('contain', 'with')
+      .then(function () {
+        expect(this.logs[2].get('message')).to.contain('**span**')
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/commands/assertions_spec.js:137]: Maybe this is already tested elsewhere. 

```suggestion
        expect(this.logs[2].get('message')).to.contain('**span**')
        expect(this.logs[3].get('message')).to.contain('**with**')
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]

**Review by jennifer-shehane — APPROVED** [review]
