### PR TITLE
fix(errors): better error message when element is detached during actionability

### LINKED ISSUE #4946: Correct reason not visible when element is detached from DOM
Currently, if an element gets detached/removed from the DOM during actionability, you get:
```
'This element '...' is not visible because it has an effective width and height of: '0 x 0' pixels' 
```

This happens when element is removed or re-rendered on scroll, for example.

We should provide a more precise error message so that this issue can be better resolved: #695

### PR DESCRIPTION
**Pull request by kuceb**
- don't fix but address #695
- fix #4946

- add call to `ensureAttached` before `ensureVisibility` during `actionability`, which will give correct detached error message if element is detached.
- also check for detached in `getReasonIsHidden` in `visibility`
### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub? 

### review tasks
- [x] fix not passing `name` arg in `ensures.coffee`
- [x] cleanup test code

### TODO
- [ ] add before/after screenshots indicating the change to the user given the situation that causes this to happen

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
LGTM. 👍

**Comment by Bkucera** [comment]
ok, I'm going to wait for @brian-mann here in case there was a reason we didn't call `ensureAttached` during actionability

**Comment by brian-mann** [comment]
Note for self: ensure that when detached from the DOM during the actionability algorithm that we **retry** finding the element if possible.

On second thought this may not be currently possible without redesigning the command queue logic.

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 1]
```diff
@@ -1470,14 +1470,30 @@ describe('src/cy/commands/actions/click', () => {
...
 
+      it('throws when subject is detached during actionability', (done) => {
+        cy.on('fail', (err) => {
+          expect(err.message).to.include('cy.click() failed because this element is detached from the DOM')
+
+          done()
+        })
+
+        cy.get('input:first')
+        .should(($el) => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]: shouldn't go in a `.should` because a `.should` is called multiple times. instead this should be added outside of the `.should` via a `cy.$$` or a `.then`

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/ensures.coffee [hunk 2]
```diff
@@ -27,7 +27,7 @@ create = (state, expect) ->
         ## if this is an element then ensure its currently attached
         ## to its document context
         if $dom.isElement(subject)
-          ensureAttached(subject, name)
+          ensureAttached(subject)
```
Comment (brian-mann) [inline packages/driver/src/cy/ensures.coffee]: this feels wrong... why was this removed? all the other ensures utilize this...?

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 1 above)
Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: only if it throws. `should` is a convenient way to preserve the subject, but i guess since nothing is returned a `.then` would sufice

File: packages/driver/src/cy/ensures.coffee (hunk 2 above)
Comment (Bkucera) [reply packages/driver/src/cy/ensures.coffee]: they do not, check out ensureNotReadOnly, ensureNotDisabled, and ensureVisibility

**Review by brian-mann — APPROVED** [review]

**Review by jennifer-shehane — APPROVED** [review]
Brian has approved this.

**Comment by christemple** [comment]
> Note for self: ensure that when detached from the DOM during the actionability algorithm that we **retry** finding the element if possible.
> 
> On second thought this may not be currently possible without redesigning the command queue logic.

@brian-mann I'd be interested in helping find a solution to this retry feature because our Cypress tests are suffering from detached elements due to the setting of `innerHTML` on a vanilla JS component.  I believe it would make the tests more reliable for others and be a big benefit as the retry-ability feature of Cypress is what draws a lot of developers to the tool :+1:
