### PR TITLE
fix(runner-ct): viewport scaling during screenshots

### LINKED ISSUE #15934: runner-ct: cy.screenshot wrong for very long viewports
### Current behavior

Left: e2e runner with viewport set to 200, 2000
Right: CT runner with viewport set to 200, 2000

image

Screenshot persisted is also wrong, but in a different way:

image

### Desired behavior

Should be what you would expect.

### LINKED ISSUE #16478: runner-ct: Component test cy.screenshot has unneeded background
Before migrating to cypress `v7` when I used to make full page screenshot it was only mounted component full screen
After migrating I get some background over component 

is that expected and if possible to remove this background having only component?

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/16478
- Closes https://github.com/cypress-io/cypress/issues/15934

### User facing changelog

`cy.screenshot` was incorrectly capturing parts of the runner UI during screenshots.

### Additional details

A lack of thorough testing around the `cy.screenshot` feature in CT runner led to some bugs and incorrect behavior. Runner CT now matches the behavior specified in the Cypress documentation and E2E runner, including:

- respect the `capture` option to `cy.screenshot` correctly (both `fullPage`, which is the default, and `viewport`).
- correctly remove scaling the AUT (the `<iframe>`) correctly during screenshot capture
- now able to uncomment this test, since it works correctly: https://github.com/cypress-io/cypress/blob/8700ecf39b09c803eaeabcc22aa502aa11612334/packages/runner-ct/cypress/component/screenshot.spec.tsx#L57

Several things contributed to the problems:

1. `scale` applied the AUT during screenshotting. 
2. AUT needs to be scrollable (via `scroll: overflow`) during screenshot. That's why we had the problem [in this ticket](https://github.com/cypress-io/cypress/issues/15934) - the driver was trying to scroll to capture the entire viewport, but could not, since `overflow: scroll` was not set.

## Figure 1: Regular 500x500 viewport

Notes: no change. The basic use case was fine.

Before:

image

After:

image

## Figure 2: 750x750 viewport

Notes: depending on the size of the runner during the time of screenshot, this was okay. If you resize the browser window, though, certain sizings give you the gray background.

Before:

image

After:

image

## Figure 3: component 1500px x 1000px, viewport 850x1000. `cy.screenshot({ capture: 'viewport' })`

This is how it looks in the runner UI:

image

Notes: "before" screenshot is completely wrong. It's capturing the entire page, not just the viewport, and there is a lot of the gray background showing. "after" is correct. Since we are specifying `viewport`, it is now correctly NOT capturing the hidden part (outside viewport).

Before:

image

After:

image

## Figure 4: component 1500px x 1000px, viewport 850x1000. `cy.screenshot({ capture: 'fullPage' })`

Notes: it correctly scrolls and captures the entire page now.

Before:

image

After:

image

## Figure 5: Regression from user project

See bug report here: https://github.com/cypress-io/cypress/issues/16478

When the browser is this size:

image

After:

image

Another bug was if I make the runner CT really small, like this:

image

Produced:

image

This isn't what the e2e runner was doing:

image

Now it's working correctly in CT:

image

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/runner-ct/src/app/useScreenshotHandler.tsx [hunk 1]
```diff
@@ -25,6 +25,10 @@ export function useScreenshotHandler ({ eventManager, state, splitPaneRef }: {
 
     splitPaneRef.current.splitPane.firstElementChild.classList.remove('d-none')
     splitPaneRef.current.splitPane.querySelector('[role="presentation"]').classList.remove('d-none')
+
+    const iframe = document.querySelector<HTMLIFrameElement>('.aut-iframe')
+
+    iframe.classList.remove('aut-iframe-screenshotting')
```
Comment (lmiller1990) [inline packages/runner-ct/src/app/useScreenshotHandler.tsx:31]: This is pretty dirty, but unfortunately the `<iframe>` is not controlled by React. It's initialized [here](https://github.com/cypress-io/cypress/blob/8700ecf39b09c803eaeabcc22aa502aa11612334/packages/runner-ct/src/iframe/iframes.jsx#L60), and actually created [here](https://github.com/cypress-io/cypress/blob/8700ecf39b09c803eaeabcc22aa502aa11612334/packages/runner-ct/src/iframe/aut-iframe.js#L17) using jquery, so I don't any better way to do this. We need some specific styling to be applied during screenshotting to make everything look correct.

Comment (agg23) [reply packages/runner-ct/src/app/useScreenshotHandler.tsx:31]: This might be OK temporarily, but the iframe code lives entirely inside `runner-ct`, so we can refactor it to be rendered via React.

File: packages/runner-ct/src/app/RunnerCt.scss [hunk 2]
```diff
@@ -32,6 +32,11 @@ body, html {
    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1IiBoZWlnaHQ9IjUiPgo8cmVjdCB3aWR0aD0iNSIgaGVpZ2h0PSI1IiBmaWxsPSIjZGJkYmRiIj48L3JlY3Q+CjxwYXRoIGQ9Ik0wIDVMNSAwWk02IDRMNCA2Wk0tMSAxTDEgLTFaIiBzdHJva2U9IiNjNGM0YzQiIHN0cm9rZS13aWR0aD0iMSI+PC9wYXRoPgo8L3N2Zz4=");
 }
 
+.aut-iframe-screenshotting {
+  height: min(100vh, 100%) !important;
+  overflow: scroll !important;
+}
+
```
Comment (agg23) [inline packages/runner-ct/src/app/RunnerCt.scss:39]: What styles is this conflicting with? I particularly don't understand the `min(100vh, 100%)`. Is the 100% the intrinsic content size, not the iframe parent's size?

File: packages/runner-ct/src/iframe/iframes.jsx [hunk 3]
```diff
@@ -45,7 +45,8 @@ export default class Iframes extends Component {
           style={{
             height: viewportHeight,
             width: viewportWidth,
-            transform: `scale(${scale})`,
+            transform: `scale(${screenshotting ? 1 : scale})`,
+            transformOrigin: `${screenshotting ? 'top left' : ''}`,
```
Comment (agg23) [inline packages/runner-ct/src/iframe/iframes.jsx:49]: ```transform: !screenshotting ? `scale(${scale}` : undefined```

And I don't think you'll need `transformOrigin`

File: packages/runner-ct/src/iframe/iframes.scss [hunk 4]
```diff
@@ -16,4 +16,5 @@
 .size-container {
   overflow: auto;
   box-shadow: shadow(m);
+  max-width: 100%;
```
Comment (agg23) [inline packages/runner-ct/src/iframe/iframes.scss:19]: Why do we want to limit against the `viewportWidth`? Can't this lead to situations where `viewportWidth` is larger than the window size, and the iframe will end up being smaller (or is `viewportWidth` the actual current browser size, in which case I'm not sure why this style is necessary)?

**Review by agg23 — COMMENTED** [review]
Really nice to see these fixes. I have several questions about what this is doing.

File: packages/runner-ct/src/app/useScreenshotHandler.tsx (hunk 1 above)
Comment (lmiller1990) [reply packages/runner-ct/src/app/useScreenshotHandler.tsx:31]: Agreed

**Review by elevatebart — DISMISSED** [review]
LGTM

File: packages/runner-ct/src/app/RunnerCt.scss (hunk 2 above)
Comment (lmiller1990) [reply packages/runner-ct/src/app/RunnerCt.scss:39]: I figured this out just by creating lots of use cases and observing the output. Here's the use case this solves. Consider this example:

image

Without this CSS, the screenshot is like this. Note the default behvior of `cy.screenshot`, which is `cy.screenshot({ capture: 'fullPage' })` (as opposed to `cy.screenshot({ capture: 'viewport' })`.

image

This is the desired output - scroll down the page, stitch together the screenshot:

image.

We need `overflow: scroll` to be applied. If `overflow: scroll` is not applied, Cypress tries to scroll, take a screenshot, and stitch them together. That's why you end up with that weird duplicating behavior in the first image above.

`scroll: overflow` is only applied if you have a static height set - `height: 100%` won't work. By doing `min(100%, 100vh)` it will apply `height 100vh` to components with a height greater than the viewport (100%). This supports the desired behavior.

I have some ideas on a much less hacky way to do this moving forward, I will send you a message.

File: packages/runner-ct/src/app/useScreenshotHandler.tsx (hunk 1 above)
Comment (lmiller1990) [reply packages/runner-ct/src/app/useScreenshotHandler.tsx:31]: The real value of this PR is we now have some Percy screenshots that are correct, so we can safely refactor.

File: packages/runner-ct/src/iframe/iframes.jsx (hunk 3 above)
Comment (lmiller1990) [reply packages/runner-ct/src/iframe/iframes.jsx:49]: You were right - I didn't need `transformOrigin`. Nice catch.

Not sold on the `transform` refactor. Isn't an explicit `scale(1)` much more clear? Also, I think that `if X then Y else Z` is more clear than `if not X then Z else Y` syntax - ie, putting a negative at the start of the ternary feels a little weird, at least to me.

File: packages/runner-ct/src/iframe/iframes.scss (hunk 4 above)
Comment (lmiller1990) [reply packages/runner-ct/src/iframe/iframes.scss:19]: Good question. This might *not* be the right behavior. I added this to match the existing behavior in both the e2e  runner and fix the regression reported by [this comment](https://github.com/cypress-io/cypress/issues/16478#issuecomment-842423403).

I pulled his project and ran it. It looks like this in my browser.

Normal viewport:

image

Narrow viewport:

image

For reference, in CT runner it looks like this:

image

Without `max-width: 100%` we get the following screenshot. This just seems wrong (and a regression?)

image

With `max-width: 100%`:

image

File: packages/runner-ct/src/app/RunnerCt.scss (hunk 2 above)
Comment (agg23) [reply packages/runner-ct/src/app/RunnerCt.scss:39]: Thank you for this detailed explanation.

File: packages/runner-ct/src/iframe/iframes.jsx (hunk 3 above)
Comment (agg23) [reply packages/runner-ct/src/iframe/iframes.jsx]: Why emit HTML when you could not?

I suggested the ternary be written like that because I don't like having a falsy case be in the middle (the true case). Just a weird style preference of mine.

**Review by agg23 — APPROVED** [review]
