### PR TITLE
fix: `change`, `input` events are not fired when the same option is selected again. 

### LINKED ISSUE #19494: In a select element, the onChange event fires even when selecting the currently chosen option
### Current behavior

In a select element, the onChange event fires even when clicking on the option which is already selected. This behavior is not consistent with what actually happens in browsers (I tested this only on Chrome).

### Desired behavior

In a select element, the onChange event should only fire when the value of the select element actually changes. When clicking on an option that is already selected, it should not fire.

### Test code to reproduce

Here is a [repo](https://github.com/YishaiBerg/cypress-test-tiny) with a failing test. The code for the AUT can be found [here](https://github.com/YishaiBerg/cypress-onchange-bug/blob/main/index.html).

### Cypress Version

9.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #19494

### User facing changelog

`change`, `input` events are not fired when the same option is selected again. 

### Additional details
- Why was this change necessary? => When the same `<option>` is selected, `change`, `input` events are not be fired in browsers, but Cypress does. 
- What is affected by this change? => N/A
- Any implementation details to explain? => I cache the selected old values and check them.

### How has the user experience changed?

**Before:** `cy.select` doesn't follow the browser behavior.
**After:** `cy.select` follows it. 

### PR Tasks
- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/commands/actions/select.ts [hunk 1]
```diff
@@ -279,6 +299,15 @@ export default (Commands, Cypress, cy) => {
               options.$el[0].selectedIndex = selectedIndex
             }
 
+            // https://github.com/cypress-io/cypress/issues/19494
```
Comment (BlueWinds) [inline packages/driver/src/cy/commands/actions/select.ts:302]: So I'm a bit confused here why we're using state() to store values. Would not a simpler implementation be to just store the actually selected DOM index beforehand, then compare to see if it's the same DOM element after selecting the new one? Eg:

```
const oldValue = options.$el[0].selectedIndex

options.$el.val(values)
if (notAllUniqueValues) { ... }

if (options.$el[0].selectedIndex === oldValue) {
  return;
}
```

It seems like this more cleanly encapsulates the desired behavior - "if the selected element hasn't changed, don't fire any events." Not sure why we need Cypress state here?

Comment (BlueWinds) [reply packages/driver/src/cy/commands/actions/select.ts:302]: As an example of a problem with the current approach, consider:
```
  <select class='ice-cream' name='ice-cream'>
    <option value=''>Select One …</option>
    <option value='chocolate' selected>Chocolate</option>
  </select>

        cy.visit('fixtures/select-event-counter.html')
        cy.get('.ice-cream').select('Chocolate')
        cy.get('#change-result').should('not.have.text', 'Number of times onChange event fired: 1')
        cy.get('#input-result').should('not.have.text', 'Number of times input event fired: 1')
```

This fails because the change event fires, which doesn't match browser behavior. No change should fire because chocolate had the "selected" attribute, so was selected when the fixture opened (and cy.select() doesn't change the selected element).

**Review by BlueWinds — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/commands/actions/select.ts (hunk 1 above)
Comment (tbiethman) [reply packages/driver/src/cy/commands/actions/select.ts:302]: We might also run into inconsistencies if those elements in state are detached between selections.

Comment (sainthkh) [reply packages/driver/src/cy/commands/actions/select.ts:284]: Thank you. Your solution is much better. I changed the code in that way. I also added your test case.

File: packages/driver/cypress/integration/commands/actions/select_spec.js [hunk 2]
```diff
@@ -365,7 +384,7 @@ describe('src/cy/commands/actions/select', () => {
           done()
         })
 
-        cy.get('#select-maps').select('de_dust2').select('de_aztec')
+        cy.get('#select-maps').select('de_aztec').select('de_dust2')
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/actions/select_spec.js:387]: 2 tests that use `#select-maps` have been changed because it tries to select the already-selected first option. I changed them to select the second one.

**Comment by sainthkh** [comment]
system-tests failed because CircleCI doesn't end some tests for me. It's also happening in #19837

**Review by tbiethman — APPROVED** [review]
