### PR TITLE
fix: update newProject ref when switching between organizations in SelectCloudProjectModal

### LINKED ISSUE #25520: Connect project banner default state not correct
On the Debug page, when opening the "Connect a project banner", the option for which project to connect should default to the "New project" state if no projects are detected.

This is possibly a regression to the overall modal, but may be related to how it is implemented in the Debug page.

https://user-images.githubusercontent.com/1702361/215817089-40a25a38-2057-472d-8b5f-6a23156eef8d.mov

Original slack conversation: https://cypressio.slack.com/archives/C04H2022N0J/p1674068029789909

### PR DESCRIPTION
**Pull request by astone123**
- Closes #25520 

### Additional details

We weren't updating the `newProject` ref when the user switched Cloud organizations in the SelectCloudProjectModal dropdown. This lead to a state where if your first organization when you opened the modal **did** have at least one project, and then you switched to an organization that didn't have any projects, you would still see the "connect project" button and the modal state would be incorrect. See the original issue for a video.

### Steps to test

- Set up two organizations in Cypress Cloud - one with at least one project, and one without **any** projects (delete the default project as well)
- Open a project that is not connected to Cypress Cloud
- Open the cloud connection modal (either from the specs list, runs page, or debug page)
- Verify that when you switch between these organizations in the modal dropdown, you are correctly prompted to create a new project in your organization that doesn't have any, and are correctly prompted to connect to an existing project in the organization that does have projects

Also take a look at the tests in `SelectCloudProjectModal.cy.tsx` to understand the flow

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by astone123** [comment]
We're setting a default value for the `newProject` ref [here](https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue#L336), but then that value doesn't update when we have a new `projectOptions`.

File: packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue [hunk 1]
```diff
@@ -348,6 +348,8 @@ watch(projectOptions, (newVal, oldVal) => {
   } else {
     pickedProject.value = projectOptions.value.find((p) => p.name === projectName.value)
   }
+
+  newProject.value = projectOptions.value.length === 0
```
Comment (astone123) [inline packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue]: There are a couple of other places that we could probably do this, but I figure any time `projectOptions` changes, we want to make sure that `newProject` has the correct value since it's being derived from there

**Review by ZachJW34 — APPROVED** [review]
Looks good!

File: packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue (hunk 1 above)
Comment (mike-plummer) [reply packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue]: Super nitpicky, but we should probably be using `newVal` within this callback rather than referencing the prop value. That's probably what's making the `immedate` param on this `watch` necessary.

Comment (astone123) [reply packages/frontend-shared/src/gql-components/modals/SelectCloudProjectModal.vue]: yeah that's a good point. I think we have `immediate` here as a way to set the initial value of `pickedProject`. My understanding is that we don't set a default value for the ref, so we need this to run immediately to set that value if there is an existing project

**Review by mike-plummer — APPROVED** [review]
