### PR TITLE
Reporter error improvements

### LINKED ISSUE #881: better stack trace/ sourceMaps
Currently, there's no useful stack trace on failure. If the failure is an critical exception of sorts (e.g. command was written incorrectly, or wrong args supplied), the stack trace leads to cypress reporters (not useful), and if the failure is a regular assertion failure or similar, there's no stack trace at all.

If a test has 30+ similar commands, it's very hard to narrow down which command is failing. Multiply this across several files, and updating failing specs e.g. due to regression/API changes is a nightmare.

What we need is some **mapping between commands in command log, and the source code.**

Is this something on the roadmap?

### LINKED ISSUE #1761: Improve Uncaught Errors
on `Uncaught Errors`
- if there is no `err.stack`, e.g syntax error,  construct a better error
- if there is a stack, cut out the cypress related lines

image

### LINKED ISSUE #3762: Improve Test Runner error experience
# Goal

The goal is to make the process of debugging tests and code easier.

# Why
1. Spending less time debugging and deciphering errors means more time for users to do what they _want_ to be doing (e.g. writing more tests, writing more code, stopping writing code because they’ve achieved their goals).
2. When users can solve their own problems, this reduces the time our team spends on support.
3. Better errors makes software easier to use for everyone, especially beginners or non-traditional users who might not have context on how to debug issues outside of what error messages instruct them to do. 

# Implementation

## Current design of error within Command Log

error-design-7

## Current design applied to types of errors

error-designs-8

### Cypress Error (one code frame)

```js
{
  name: "CypressError",
  message: "", // Error message (logged in console, used in run mode)
  stack: "",
  mdMessage: "", // Error message with escaped markdown (used in GUI)
  codeFrames: [
    {
      frame: "", // Code frame string
      filePath: "" // Path to open file
    }
  ],
  docs: "", // Either full URL or path after on.cypress.io
  template: "cypress-single-frame" // Template type, used to compose full error
}
```

### Cypress Error (two code frames)

```js
{
  name: "CypressError",
  message: "",
  stack: "",
  mdMessage: "",
  codeFrames: [
    { // Code frame to be displayed first, likely the spec code
      frame: "",
      filePath ""
    },
    { // Code frame to be displayed second, such as the plugins code
      frame: "",
      filePath ""
    }
  ],
  docs: "",
  template: "cypress-multiple-frames"
}
```

### Assertion Error

```js
{
  name: "AssertionError",
  message: "",
  stack: "",
  expected: "",
  actual: "",
  diff: "",
  codeFrames: [
    {
      frame: "",
      filePath: ""
    }
  ],
  docs: "",
  template: "assertion"
}
```

### Spec/Application Error

```js
{
  name: "",
  message: "",
  stack: "",
  codeFrames: [
    {
      frame: "",
      filePath: ""
    }
  ],
  docs: "",
  template: "other"
}
```

# Existing Issues

There are a number of existing issues that might make sense to address under the umbrella of “error improvement" (I’m sure there are more): 

* Add retry to `baseUrl` not present warning https://github.com/cypress-io/cypress/issues/3284
* Better messaging when failing by type https://github.com/cypress-io/cypress/issues/2050
* Failed assertion UI in open mode https://github.com/cypress-io/cypress/issues/3129
* Module API doesn’t fail the promise with Cypress error message https://github.com/cypress-io/cypress/issues/3216
* Root level `after` hooks don’t error https://github.com/cypress-io/cypress/issues/3348
* Improve printing error messages in Test Runner https://github.com/cypress-io/cypress/issues/1664
* better stack trace/ sourceMaps https://github.com/cypress-io/cypress/issues/881
* asterisks appearing in command log https://github.com/cypress-io/cypress/issues/1360
* Add support for backticks in command log https://github.com/cypress-io/cypress/issues/3608
* Exceptions in global 'after' are not shown correctly in UI https://github.com/cypress-io/cypress/issues/3904
* Exceptions in after() don't show up in UI https://github.com/cypress-io/cypress/issues/3348
* Exception in root level after() doesn't fail test run in interactive mode https://github.com/cypress-io/cypress/issues/2296
* Improve uncaught errors https://github.com/cypress-io/cypress/issues/1761
* TypeError: Cannot read property 'replace' of undefined" at Object.appendErrMsg https://github.com/cypress-io/cypress/issues/1669
* .should('deep.equal') does not show a full diff comparison on failures https://github.com/cypress-io/cypress/issues/4084
* err when cy.visit('file://..') https://github.com/cypress-io/cypress/issues/4452
* Show warning message in command log https://github.com/cypress-io/cypress/issues/4917
* Add warning to command log for 'uncaught exception' https://github.com/cypress-io/cypress/issues/4933
* Capture stack traces from spec frame https://github.com/cypress-io/cypress/issues/4932

### LINKED ISSUE #3966: Utilize source maps
As part of adding code frames for the [improved error experience](https://github.com/cypress-io/cypress/issues/3762), we need to do the following:

* Enable source maps (unless the user has explicitly disabled them) in the preprocessor
* Gracefully handle the case where the user has disabled source maps
* For errors with a stack:
  - Translate the stack into source code stack
* For command errors:
  - Capture the stack when a command runs
  - If the command fails, use the source maps to trace the command back to the source spec file
  - Pull out the line from the spec file and one two above and below it to display in the error code frame
* For assertion errors:
  - Same as commands but point to and show the assertion
* For reporter UI:
  - Capture the stack when an `it` runs
  - Display a button in the UI next to the test name that opens the file at that line when clicked

Related: #881

### LINKED ISSUE #6924: Broken error rendering for custom Mocha reporters
### Current behavior:

I believe version 4.3.0 broke the error output with customer reporters. I think it might be coming from one of these snippets (L140 for the 1st, L111 for the 2nd):

https://github.com/cypress-io/cypress/blob/36866da64d86dc7e162489e357d7fc814ff025bb/packages/driver/src/cypress/error_utils.js#L139-L143

https://github.com/cypress-io/cypress/blob/689bef002ca0794ae3758076a6707bebeb8aa4ce/packages/server/lib/reporter.coffee#L103-L119

On a simple test that visits a page that doesn’t exist (HTTP 404), the output looks like this now:

Screenshot 2020-04-02 at 18 08 33

Text version:

```
~/Sites/test-cypress  $ npx cypress run  --reporter reporter.js

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.3.0                                                                              │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      1 found (examples/index.js)                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  examples/index.js                                                               (1 of 1)
{
  message: [String: '`cy.visit()` failed trying to load:\n' +
    '\n' +
    'https://example.com/dgfkdgkj\n' +
    '\n' +
    'The response we received from your web server was:\n' +
    '\n' +
    '  > 404: Not Found\n' +
    '\n' +
    'This was considered a failure because the status code was not `2xx`.\n' +
    '\n' +
    'If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`'] {
    match: [Function]
  },
  name: 'CypressError',
  stack: 'CypressError: `cy.visit()` failed trying to load:\n' +
    '\n' +
    'https://example.com/dgfkdgkj\n' +
    '\n' +
    'The response we received from your web server was:\n' +
    '\n' +
    '  > 404: Not Found\n' +
    '\n' +
    'This was considered a failure because the status code was not `2xx`.\n' +
    '\n' +
    'If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`\n' +
    '    at cypressErr (https://example.com/__cypress/runner/cypress_runner.js:146180:16)\n' +
    '    at cypressErrByPath (https://example.com/__cypress/runner/cypress_runner.js:146189:10)\n' +
    '    at Object.throwErrByPath (https://example.com/__cypress/runner/cypress_runner.js:146152:11)\n' +
    '    at https://example.com/__cypress/runner/cypress_runner.js:134410:34\n' +
    '    at visitFailedByErr (https://example.com/__cypress/runner/cypress_runner.js:133923:12)\n' +
    '    at https://example.com/__cypress/runner/cypress_runner.js:134391:22\n' +
    '    at tryCatcher (https://example.com/__cypress/runner/cypress_runner.js:9059:23)\n' +
    '    at Promise._settlePromiseFromHandler (https://example.com/__cypress/runner/cypress_runner.js:6994:31)\n' +
    '    at Promise._settlePromise (https://example.com/__cypress/runner/cypress_runner.js:7051:18)\n' +
    '    at Promise._settlePromise0 (https://example.com/__cypress/runner/cypress_runner.js:7096:10)\n' +
    '    at Promise._settlePromises (https://example.com/__cypress/runner/cypress_runner.js:7172:18)\n' +
    '    at _drainQueueStep (https://example.com/__cypress/runner/cypress_runner.js:3766:12)\n' +
    '    at _drainQueue (https://example.com/__cypress/runner/cypress_runner.js:3759:9)\n' +
    '    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://example.com/__cypress/runner/cypress_runner.js:3775:5)\n' +
    '    at Async.drainQueues (https://example.com/__cypress/runner/cypress_runner.js:3645:14)'
}

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 second                                                                         │
  │ Spec Ran:     examples/index.js                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  examples/index.js                        00:01        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:01        1        -        1        -        -  

```

Note the weird:

```
{
  message: [String: '`cy.visit()` failed trying to load:\n' +
    '\n' +
    'https://example.com/dgfkdgkj\n' +
    '\n' +
    'The response we received from your web server was:\n' +
    '\n' +
    '  > 404: Not Found\n' +
    '\n' +
    'This was considered a failure because the status code was not `2xx`.\n' +
    '\n' +
    'If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`'] {
    match: [Function]
  },
```

### Desired behavior:

The main problem with this is that it doesn’t seem to be possible to get the original error message anymore. So a custom reporter is now stuck with Cypress’ hack without the ability to use the actual error message that was thrown. 

My assumption is that this patching/String serialisation (L111) is happening too early. The given input is not a string, it seems to be JavaScript intended to compose a string through concatenation. Not sure. Doing a `typeof` on `error.message` also yields `object` instead of `string` which is a problem as well.

### Test code to reproduce

Consider the following setup:

```json
{ "baseUrl": "https://example.com" }
```

```js
describe("Test", () => {
  it("visit", () => cy.visit("/dgfkdgkj"))
})
```

```js
function Reporter(runner) {
  runner.on("fail", (test, error) => {
    console.log(error);
  });
}

module.exports = Reporter;
```

```sh
npx cypress run  --reporter reporter.js
```

### Versions

4.3.0.

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Close #3762
- Close #881 	
- Close #3966 
- Close #6924
- Close #1761

### User facing changelog

We've improved the display of errors in the Test Runner's Command Log. Errors now show a code frame preview with the highlighted line where the error occurred. You can now click links to files relevant to the errors that can be opened on your computer or in your preferred editor at the exact line of code. You can also click to expand the stack trace inline in the Command Log. 

### Additional details

- Split up error messages into separate DOM elements
- Allow driver errors to return object including docsUrl
- Update all error messages to include markdown where appropriate
- Refactor error specific utils into their own file
- Cover errors with more tests

#### Before

Screen Shot 2020-01-10 at 3 33 19 PM

#### After

Code frame with highlighted line where err is being thrown

Screen Shot 2020-01-10 at 2 58 33 PM

Expandable stack trace
Screen Shot 2020-01-17 at 1 31 54 PM

'Learn more' link in err message if relevant documentation to link to

Screen Shot 2020-01-10 at 3 47 25 PM

Clear 'print error to console' button

Screen Shot 2020-01-10 at 3 00 49 PM

Select File opener Preference (including OS-specific file opener)

Screen Shot 2020-01-17 at 1 13 13 PM

Error if no path given for Other

Screen Shot 2020-01-17 at 1 14 02 PM

Select / change file opener preference from Settings 

Screen Shot 2020-01-17 at 1 17 29 PM

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2584
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

## Implementation Notes

```
The various error scenarios Cypress can encounter and how to address them

Error: err.name
Uncaught: whether it's an uncaught error
Codeframe: what the code frame should display
Original stack: what does the error stack include before we've modified it at all
Replace: whether we should replace the stack with the user invocation stack
Translate: whether we should translate the stack to point to source files instead of the built files served to the browser
Append: whether we should append all or part of the original error stack to the newly replaced stack

====
Scenario 1: command assertion errors
====
cy.wrap({ foo: 'foo' })
  .should('have.property', 'foo')
  .should('equal', 'bar')
//
cy.get('#non-existent') // default assertion

- Error: AssertionError
- Uncaught: false
- Codeframe: cy.should, cy.get
- Original Stack: cypress internals
- Replace: yes, with command invocation stack
- Translate: yes
- Append: no


====
Scenario 2: exceptions
====
// at root level
foo.bar()
// in test
foo.bar()
// at root or in test
setTimeout(() => {
  foo.bar()
}, 20)
cy.wait(10000)
//
cy.wrap({}).should(() => {
  foo.bar()
})
//
Cypress.Commands.add('foo', () => {
  foo.bar()
})
cy.foo()

- Error: ReferenceError, etc
- Uncaught: true/false
- Codeframe: foo.bar()
- Original Stack: spec callsite
- Replace: no
- Translate: yes
- Append: no


====
Scenario 3: assertion errors
====
// at root
expect(true).to.be.false
// in test
expect(true).to.be.false
//
cy.wrap({}).then(() => {
  expect(true).to.be.false
})
//
cy.wrap({}).should(() => {
  expect(true).to.be.false
})

- Error: AssertionError
- Uncaught: true/false
- Codeframe: expect()
- Original Stack: cypress internals
- Replace: yes, with assertion invocation stack
- Translate: yes
- Append: no


====
Scenario 4: validation errors
====
cy.viewport() // invalid args
// double visit
cy.visit('/test.html')
cy.visit('https://google.com')

cy.get('div:first').then(($el) => {
  $el.hide()
})
.click()

expect(true).to.be.nope

- Error: CypressError, Error<Chai validation>
- Uncaught: false
- Codeframe: cy.viewport
- Original Stack: cypress internals / chai internals
- Replace: yes
- Translate: yes
- Append: yes


====
Scenario 5: app sync uncaught errors
====
cy.visit('/visit_error.html') // error synchronously
cy
.visit('/error_on_click.html')
.get('p').click() // error on click event

- Error: ReferenceError, etc
- Uncaught: true
- Codeframe: none (but want to show app code + maybe cy.visit/cy.click)
- Original Stack: app code
- Replace: no
- Translate: yes (but can't now)
- Append: no


====
Scenario 6: app async uncaught errors
====
cy.visit('/html/visit_error.html') // error asynchronously

- Error: ReferenceError, etc
- Uncaught: true
- Codeframe: none (but want to show app code, don't show cy.visit)
- Original Stack: app code
- Replace: no
- Translate: yes (but can't now)
- Append: no


====
Scenario 7: network errors
====
cy.visit('/404')
cy.request('http://localhost:12345')

- Error: RequestError, etc - wrapped in CypressError
- Uncaught: false
- Codeframe: cy.visit
- Original Stack: node, cypress internals
- Replace: yes, with command invocation stack
- Translate: yes
- Append: yes, append both node and cypress internals

====
Rules:
====
- if assertion error, don't append original stack because the rules of why it errored are explicit
- if internal cypress error, append original stack so users can use it to understand the source of the error
- if internal cypress error originating from node, append node stack and internal cypress stack


TODO:
- if visit synchronously fails in app code, point to cy.visit in spec code
  - add 2nd code frame that points to app code
- don't hide stack trace by default, because now it's actually useful and not overly verbose with internal crap
- profile how much time Bluebird spends when we enable longStackTraces (cypress.js) and maybe turn it always off or always on
- splice out cypress internals when there's a user error (Scenario 2 when error is in a command callback)
```

### CODE REVIEW

File: packages/server/lib/reporter.coffee [hunk 1]
```diff
@@ -86,7 +86,7 @@ safelyMergeRunnable = (hookProps, runnables) ->
   _.extend({}, runnables[hookProps.id], hookProps)
 
 mergeErr = (runnable, runnables, stats) ->
-  { err } = runnable.err
+  { err } = runnable
```
Comment (jennifer-shehane) [inline packages/server/lib/reporter.coffee]: Thanks! 🙈

**Comment by jennifer-shehane** [comment]
oh wow, the tests are passing. 🎉

**Comment by jennifer-shehane** [comment]
Current state of this PR, since I know we've all forgotten:

## Alias error

### Before

Screen Shot 2019-08-01 at 5 11 21 PM


### After
Screen Shot 2019-08-01 at 4 55 50 PM

## Chai errors

### Before

Screen Shot 2019-08-01 at 5 11 41 PM

### After
Screen Shot 2019-08-01 at 4 56 38 PM

## Click error

### Before

Screen Shot 2019-08-01 at 5 12 01 PM

Screen Shot 2019-08-01 at 5 12 43 PM

### After
Screen Shot 2019-08-01 at 4 57 35 PM

Screen Shot 2019-08-01 at 5 01 02 PM

## DOM errors

### Before

Screen Shot 2019-08-01 at 5 17 07 PM



### After
Screen Shot 2019-08-01 at 5 01 43 PM



## Misc error

### Before

Screen Shot 2019-08-01 at 5 13 05 PM


### After

Screen Shot 2019-08-01 at 5 02 24 PM

## Outside test error

### Before

### After

Screen Shot 2019-08-01 at 5 03 12 PM

## Navigation errors

### Before

Screen Shot 2019-08-01 at 5 13 39 PM


### After

Screen Shot 2019-08-01 at 5 04 09 PM

## Request errors

### Before

Screen Shot 2019-08-01 at 5 14 03 PM


### After

Screen Shot 2019-08-01 at 5 04 44 PM

## Subject errors

### Before

Screen Shot 2019-08-01 at 5 14 25 PM


### After

Screen Shot 2019-08-01 at 5 05 37 PM
Screen Shot 2019-08-01 at 5 05 25 PM

## Task errors

### Before

Screen Shot 2019-08-01 at 5 14 43 PM


### After

Screen Shot 2019-08-01 at 5 06 05 PM

## Uncaught errors

### Before

Screen Shot 2019-08-01 at 5 14 58 PM


### After

Screen Shot 2019-08-01 at 5 06 38 PM

## Visit errors

### Before

Screen Shot 2019-08-01 at 5 15 25 PM


### After

Screen Shot 2019-08-01 at 5 07 31 PM

**Comment by brian-mann** [comment]
Headsup: the changes to the spec files (like `type_spec.coffee`) are about to be in conflict because we're merging in a decaffeinated version of them today.

**Comment by brian-mann** [comment]
There appears to be a some missing backticks on the errors - and others have backticks but are not highlighted correctly.

I also think the "Learn More" gets lost because it's styled as `red` like the other content and doesn't appear to be a link.

**Comment by jennifer-shehane** [comment]
@brian-mann Yeah, I'm working on getting more backticks correct and pulling on docsUrls since that work wasn't finished. I didn't want to touch the errors anymore with the big changes/conflicts before - that have been fixed. 

I'll fix the merge conflicts as well.

File: packages/driver/test/cypress/integration/commands/files_spec.coffee [hunk 2]
```diff
@@ -229,7 +229,7 @@ describe "src/cy/commands/files", ->
 
           `/path/to/foo.json`
           """)
-          expect(err.docsUrl).to.eq("httos://on.cypress.io/readfile")
+          expect(err.docsUrl).to.eq("https://on.cypress.io/readfile")
```
Comment (jennifer-shehane) [inline packages/driver/test/cypress/integration/commands/files_spec.coffee]: oh gosh, that will cause it to fail 🤦‍♀

**Comment by chrisbreiding** [comment]
From discussion with @brian-mann on 9/18/19:

* Add `print to console` button to errors
* Add `copy to clipboard` button to errors

**Comment by jennifer-shehane** [comment]
These conflicts 😭

**Comment by chrisbreiding** [comment]
Yes, handling merge conflicts for this branch is very time-consuming and painful. I'm planning to merge https://github.com/cypress-io/cypress/pull/4041 into this and do one final merge of develop closer to when it's ready to be completed.

**Comment by sainthkh** [comment]
@jennifer-shehane Can I help? It seems that many of the conflicts are caused by my decaffs.

**Comment by jennifer-shehane** [comment]
@sainthkh I'm not sure. The problem with conflicts on this branch is just a consequence of working on this PR entirely too long. We should move towards pushing smaller deliverable features out along the way instead of working 7 months on a single branch.

**Comment by jennifer-shehane** [comment]
I fix and improved a bunch of the stylings. See my main comment on the PR for images of the new changes. 

Overall, this is really cool and I forgot how cool it was.

@chrisbreiding Probably my one complaint is having to select 'Open in computer and Open in Editor' every single time. I would rather this be a global preference or something since I literally will NEVER select 'Open in computer' and it is just irritating once you start to actually use them.

Was there any other stylings that I needed to look at? I might have missed something important. Let me know.

**Comment by chrisbreiding** [comment]
> Probably my one complaint is having to select 'Open in computer and Open in Editor' every single time. I would rather this be a global preference or something since I literally will NEVER select 'Open in computer' and it is just irritating once you start to actually use them.

That's a good point. Do you think we should have the action take place on clicking the link and add `On computer` as another option to the editor picker?

> Why do the editors on my system show 'Vim' and all of these 'GNU' editors? Is it just going to show those for everyone because I never explicitly downloaded any of those.

Those are terminal editors that are installed by default, at least on MacOS. Linux and Windows may have different ones. I'd err on the side of keeping them, since one of them may be a user's preferred editor even if they didn't explicitly download it. Also, I don't think there's a way to differentiate between ones that a user has intentionally downloaded or not. We [use this library and its list of commonly used editors](https://github.com/sindresorhus/env-editor/blob/master/index.js#L4), then check to see which are available on the user's system and display those.

> * Was there any other stylings that I needed to look at? I might have missed something important. Let me know.

The editor picker in the modal for the reporter has some validation, so if you hit `Set Editor` without choosing an editor or if you select `Other` without inputting a path, it displays a validation error. Did you take a look at that styling? That's the only other thing I can think of.

**Comment by jennifer-shehane** [comment]
@chrisbreiding 

>That's a good point. Do you think we should have the action take place on clicking the link and add On computer as another option to the editor picker?

Yes, I think this makes a lot more sense. If someone has a deep problem with this decision later on, they will open an issue and we can rethink, but I think this will err on the side of providing the happy path for the majority of people. 

The VIM thing is fine, was just wondering. 

>The editor picker in the modal for the reporter has some validation, so if you hit Set Editor without choosing an editor or if you select Other without inputting a path, it displays a validation error. Did you take a look at that styling? That's the only other thing I can think of.

Let me take a look at this today.

**Comment by jennifer-shehane** [comment]
@chrisbreiding K, so I was trying to check the stylings and apparently the typing within the 'Other' selection does not work at all. I type and nothing happens. 

Screen Shot 2020-01-13 at 2 27 28 PM


It looks like the tests for this don't actually test typing into the field. 

https://github.com/cypress-io/cypress/blob/jen/reporter-error-templates-fix/packages/ui-components/cypress/integration/editor-picker_spec.jsx#L88:L88

**Comment by chrisbreiding** [comment]
@jennifer-shehane Should we maybe not close #3762 with this PR? Does it makes sense to leave that as the Epic and create sub-issues for what this covers and for additional improvements we want to make based on this work?

**Comment by jennifer-shehane** [comment]
@chrisbreiding I would close the issue and make new smaller issues for the things we want to address so they can be picked up in smaller, deliverable PRs.

**Comment by jennifer-shehane** [comment]
1. K, I was trying to see this 'error message' that is supposed to show when you type an incorrect path in the 'Other'? (which I realize now is not what you were describing). So I input the path `/foo/bar` into 'Other' and clicked 'set preference and open file' and Cypress crashes. So there should probably be some better handling of incorrect paths as I imagine so many people will not put the correct path if they have to input 'Other'. 

This error is throwing on the 'open' action of the file because now every time I click to open the file again it crashes because my 'editor' is set to `/foo/bar`

Full logs with `DEBUG`

```
  cypress:server:socket set user editor: { id: 'other', name: 'Other', openerId: '/foo/bar', isOther: true, description: "Enter the full path to your editor's executable" } +11s
  cypress:server:saved_state making saved state from /Users/jennifer/Dev/cypress/packages/server +10s
  cypress:server:saved_state missing project path, looking for project here +0ms
  cypress:server:saved_state state path for global mode +1ms
  cypress:server:appdata path: /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +10s
  cypress:server:saved_state full state path /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file set values in /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +10s
  cypress:server:file attempt to get lock on /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file gettin lock succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file read /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file read succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file attempt to unlock /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file unlock succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file attempt to get lock on /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file gettin lock succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file write /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file write succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +1ms
  cypress:server:file attempt to unlock /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:file unlock succeeded or failed for /Users/jennifer/Library/Application Support/Cypress/cy/development/projects/__global__/state.json +0ms
  cypress:server:socket open file: { where: { id: 'other', name: 'Other', openerId: '/foo/bar', isOther: true, description: "Enter the full path to your editor's executable" }, file: '/Users/jennifer/Dev/cypress-test-error-messages/cypress/integration/driver/alias-errors.js', line: 6, column: 8 } +11ms
  cypress:server:socket open with editor: /foo/bar +0ms
Error:
Your $EDITOR environment variable is not set.
Set it to the command/path of your editor in ~/.zshenv or ~/.bashrc:

  export EDITOR=atom

    at Object.module.exports.defaultEditor (/Users/jennifer/Dev/cypress/packages/server/node_modules/env-editor/index.js:158:9)
    at make (/Users/jennifer/Dev/cypress/packages/server/node_modules/open-editor/index.js:12:82)
    at ChildProcess.<anonymous> (/Users/jennifer/Dev/cypress/packages/server/node_modules/open-editor/index.js:65:18)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

- There's a `description` field that is set in the `state.json` for `Other` that is only also set for 'On computer' and not other editor preferences. I think the content of the description is the weird thing. Because I'm ok with 'On Computer' description: `"description": "Opens the file in your system's file management application (e.g. Finder, File Explorer)"`

```
  "preferredOpener": {
    "id": "other",
    "name": "Other",
    "openerId": "/foo/bar",
    "isOther": true,
    "description": "Enter the full path to your editor's executable"
  }
```

2. For the error if you just click 'set' with no input. Why not just disable the submit button until they select something/input? Not totally necessary but an idea that would match the behavior of the Dashboard & other modals in the Desktop-GUI.

3. The tooltip for 'On Computer' does not work on hover within the Desktop-GUI preferences. 

Screen Shot 2020-01-16 at 1 04 55 PM

**Comment by chrisbreiding** [comment]
>     1. K, I was trying to see this 'error message' that is supposed to show when you type an incorrect path in the 'Other'? (which I realize now is not what you were describing). So I input the path `/foo/bar` into 'Other' and clicked 'set preference and open file' and Cypress crashes. So there should probably be some better handling of incorrect paths as I imagine so many people will not put the correct path if they have to input 'Other'.
>        This error is throwing on the 'open' action of the file because now every time I click to open the file again it crashes because my 'editor' is set to `/foo/bar`

Looking into this, I'm realizing the `open-editor` package we're using to open files is not very good... It doesn't allow any error handling and I discovered that [if the user chooses a terminal-based editor like vim and then closes the file, it closes Cypress as well](https://github.com/sindresorhus/open-editor/blob/master/index.js#L76)! So, I'm going to look into other options like [`launch-editor`](https://github.com/yyx990803/launch-editor) or possibly fork `open-editor`.

>     2. There's a `description` field that is set in the `state.json` for `Other` that is only also set for 'On computer' and not other editor preferences. I think the content of the description is the weird thing. Because I'm ok with 'On Computer' description: `"description": "Opens the file in your system's file management application (e.g. Finder, File Explorer)"`

I see what you mean. Originally, the "description" for `Other` was hard-coded into the JSX. It's more of an instruction for the input that only appears when `Other` is selected. When I introduced the `description` property for the sake of `On Computer`, I thought I'd re-use the concept for `Other` and have it part of its data instead of it being hard-coded. It's only how we store the data and not really seen by the user, so I'm on the fence as to how important it is for it to entirely make sense. I could either change the text to something like `The full path to your editor's executable` so it reads more like a description, or move it to another property called `instruction`, or move it back to being hard-coded. I don't feel that strongly about any option.

>     3. For the error if you just click 'set' with no input. Why not just disable the submit button until they select something/input? Not totally necessary but an idea that would match the behavior of the Dashboard & other modals in the Desktop-GUI.

I'd considered that. My only issue with that sort of validation is it can be confusing to the user why the form isn't valid without some sort of message. What about having a tooltip over the disabled enter button that has the validation error in it?

**Comment by jennifer-shehane** [comment]
Reviewed this with @brian-mann, he's pretty happy with it and glad to see it's nearly finished. Some notes from our meeting that I will address. 

- Add hover style to ‘learn more’ in error improvement
- Remove ‘cursor: pointer’ for the entire error block other than where it is actually clickable and actionable.		
- Tooltip style is broken within the reporter modal on ‘On Computer' (I might've broken this in my latest commits.
- Change ‘on computer’ to ‘in file system (actually, we know their OS so we could just say ‘Finder’ for Mac, ‘File Explorer’ for Windows. ‘File System’ for Linux)
- ‘Settings’ tab within file explorer modal in reporter should be clickable link to go to ‘Settings’ in the TR GUI (I don't necessarily feel like this is high priority however if this is difficult)
- Maybe try moving 2nd paragraph of description text in 'file preference' modal to be below the option selections so that people don't skim over it as easily.
- Fix spacing to the left of code frame - it’s way too big (I fixed this before so I'm not sure why it's back to being really wide)
- Just remove the idea of ‘Global settings’ overall and replace it with ‘File preference’ make it a top level expandable setting. People don't care about the concepts of 'global' or not and when we add more settings we can rearrange them however fits in the future.

**Comment by chrisbreiding** [comment]
@jennifer-shehane I addressed everything mentioned except the following.

> ‘Settings’ tab within file explorer modal in reporter should be clickable link to go to ‘Settings’ in the TR GUI (I don't necessarily feel like this is high priority however if this is difficult)

I'll look into this but I think it might be out of scope and something we can add later.

I'm also going to look into handling errors for erroneous user-input paths. It seems we get back an error with the new package I'm using, so we can probably tell the user it's no good before allowing them to set it.

File: packages/driver/src/cy/commands/actions/scroll.coffee [hunk 3]
```diff
@@ -26,16 +27,11 @@ module.exports = (Commands, Cypress, cy, state, config) ->
   Commands.addAll({ prevSubject: "element" }, {
     scrollIntoView: (subject, options = {}) ->
       if !_.isObject(options)
-        $utils.throwErrByPath("scrollIntoView.invalid_argument", {args: { arg: options }})
-
-      ## ensure the subject is not window itself
-      ## cause how are you gonna scroll the window into view...
-      if subject is state("window")
-        $utils.throwErrByPath("scrollIntoView.subject_is_window")
```
Comment (brian-mann) [inline packages/driver/src/cy/commands/actions/scroll.coffee]: is this intentional or not?

File: packages/driver/src/cy/retries.coffee [hunk 4]
```diff
@@ -30,11 +30,11 @@ create = (Cypress, state, timeout, clearTimeout, whenStable, finishAssertions) -
       })
 
       { error } = options
-      
+
       ## TODO: remove this once the codeframe PR is in since that
```
Comment (brian-mann) [inline packages/driver/src/cy/retries.coffee]: TODO referring to this PR?

File: packages/driver/src/cypress/commands.coffee [hunk 5]
```diff
@@ -115,6 +116,12 @@ create = (Cypress, cy, state, config) ->
         obj = options
         options = {}
 
+      ## this is a bit of a hack. we need to know if a command is built-in or
+      ## custom for error display purposes. almost all built-in commands go through
+      ## this method and it's undocumented for users, so we use it to mark them
+      ## as not being custom
+      options.isCustom = false
```
Comment (brian-mann) [inline packages/driver/src/cypress/commands.coffee]: maybe `isBuiltIn` or something, since its the default, typically associated with `true` as opposed to "off", which is the lesser likely scenario

File: packages/driver/src/cypress/cy.js [hunk 6]
```diff
@@ -673,13 +677,50 @@ const create = function (specWindow, Cypress, Cookies, state, config, log) {
...
 
-  const fail = function (err, runnable) {
+  const getInvocationStack = (err) => {
+    const current = state('current')
+    const currentName = current && current.get('name')
+
+    if (err.stack && (
+      // cy.then will not error on its own, but will have an
+      // invocation stack, so we need to prefer the actual error's stack
+      (currentName === 'then') ||
```
Comment (brian-mann) [inline packages/driver/src/cypress/cy.js]: rather than anchor ourselves to `then` we should come up with a pattern to detect when callback functions are invoked - the same should apply for `cy.each()`

TODO: create a custom command which takes a callback and verify its stack trace is correct

File: packages/server/__snapshots__/1_caught_uncaught_hook_errors_spec.coffee.js [hunk 7]
```diff
@@ -43,18 +43,21 @@ exports['e2e caught and uncaught hooks errors failing1 1'] = `
      AssertionError: Timed out retrying: Expected to find element: \`.does-not-exist\`, but never found it.
 
 Because this error occurred during a \`before each\` hook we are skipping the remaining tests in the current suite: \`s1a\`
+  Timed out retrying: Expected to find element: \`.does-not-exist\`, but never found it.
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/1_caught_uncaught_hook_errors_spec.coffee.js]: These changes don't seem right.

File: packages/server/test/support/fixtures/projects/e2e/cypress/integration/various_failures_spec.js [hunk 8]
```diff
@@ -0,0 +1,409 @@
+/**
```
Comment (chrisbreiding) [inline packages/server/test/support/fixtures/projects/e2e/cypress/integration/various_failures_spec.js]: TODO: Add failures with `cy.each` and other commands that takes a callback function.

File: packages/desktop-gui/cypress/integration/settings_spec.js [hunk 9]
```diff
@@ -522,48 +522,6 @@ describe('Settings', () => {
     })
   })
 
-  describe('errors', () => {
```
Comment (chrisbreiding) [inline packages/desktop-gui/cypress/integration/settings_spec.js]: These tests were duplicates. They already exist below.

File: packages/server/__snapshots__/1_caught_uncaught_hook_errors_spec.coffee.js [hunk 10]
```diff
@@ -150,6 +150,8 @@ This behavior is configurable, and you can choose to turn this off by listening
 
 https://on.cypress.io/uncaught-exception-from-application
 
+https://on.cypress.io/uncaught-exception-from-application
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/1_caught_uncaught_hook_errors_spec.coffee.js]: These duplicate docs URLs aren't right...

File: packages/server/__snapshots__/1_async_timeouts_spec.coffee.js [hunk 11]
```diff
@@ -26,11 +26,11 @@ exports['e2e async timeouts failing1 1'] = `
   2 failing
 
   1) async bar fails:
-     Error: Timed out after \`100ms\`. The \`done()\` callback was never invoked!
+     CypressError: Timed out after \`100ms\`. The \`done()\` callback was never invoked!
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/1_async_timeouts_spec.coffee.js:29]: Is this right to be a CypressError?

File: packages/server/__snapshots__/1_commands_outside_of_test_spec.coffee.js [hunk 12]
```diff
@@ -82,16 +82,17 @@ exports['e2e commands outside of test / fails on failing assertions'] = `
...
-This error originated from your test code, not from Cypress.
+  > expected true to be false
 
 When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
 
 Cypress could not associate this error to any specific test.
 
 We dynamically generated a new test to display this failure.
-  
+  AssertionError: expected true to be false
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/1_commands_outside_of_test_spec.coffee.js:94]: This isn't right. The message isn't getting replaced properly in the stack.

File: packages/server/__snapshots__/1_commands_outside_of_test_spec.coffee.js [hunk 13]
```diff
@@ -164,24 +165,29 @@ exports['e2e commands outside of test / fails on cy commands'] = `
...
-This error originated from your test code, not from Cypress.
-
 When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
 
 Cypress could not associate this error to any specific test.
 
 We dynamically generated a new test to display this failure.
-
-https://on.cypress.io/cannot-execute-commands-outside-test
+  CypressError: Cannot call \`cy.viewport()\` outside a running test.
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/1_commands_outside_of_test_spec.coffee.js:183]: This doesn't look right.

File: packages/server/__snapshots__/6_uncaught_support_file_spec.coffee.js [hunk 14]
```diff
@@ -22,16 +22,17 @@ exports['e2e uncaught support file errors failing 1'] = `
...
-This error originated from your test code, not from Cypress.
+  > bar
 
 When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
 
 Cypress could not associate this error to any specific test.
 
 We dynamically generated a new test to display this failure.
-  
+  Error: bar
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/6_uncaught_support_file_spec.coffee.js:34]: Another case of the original message not getting properly replaced in the stack.

File: packages/server/__snapshots__/6_visit_spec.coffee.js [hunk 15]
```diff
@@ -123,7 +123,7 @@ The stack trace for this error is:
 Error: connect ECONNREFUSED 127.0.0.1:16795
     [stack trace lines]
 
-  
+      [stack trace lines]
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/6_visit_spec.coffee.js:126]: These all don't look right.

Comment (chrisbreiding) [reply packages/server/__snapshots__/6_visit_spec.coffee.js:126]: Actually, I think these are fine because the error message includes the original errors' stack trace and then we have our own stack trace now that points to where this occurred in the user's spec file.

The entire error looks like this:

```
CypressError: `cy.visit()` failed trying to load:

http://localhost:16795/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:16795

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED 127.0.0.1:16795
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1:1)

      at Context.eval (http://localhost:51748/__cypress/tests?p=cypress/integration/visit_http_network_error_failing_spec.coffee:4:15)
```

File: packages/driver/src/cypress/error_utils.js [hunk 16]
```diff
@@ -168,174 +166,169 @@ const warnByPath = (errPath, options = {}) => {
...
+  }
+
   const getMsg = function (args = {}) {
     return _.reduce(args, (message, argValue, argKey) => {
-      return message.replace(new RegExp(`\{\{${argKey}\}\}`, 'g'), argValue)
+      if (_.isArray(message)) {
+        return _.map(message, (str) => replace(str, argValue, argKey))
+      }
+
+      return replace(message, argValue, argKey)
```
Comment (brian-mann) [inline packages/driver/src/cypress/error_utils.js:224]: You can normalize this and DRY it up a bit more like this...

```js
const replace = (argValue, argKey) => {
  return (str) => {
    return str.replace(new RegExp(`\{\{${argKey}\}\}`, 'g'), argValue)
  }
}

return _
.chain(message)
.concat([]) // normalize into array
.map(replace(argValue, argKey))
.thru((val) => {
  if (_.isArray(message)) {
    return val[0]
  }
  
  return val
})
.value()
```

Comment (chrisbreiding) [reply packages/driver/src/cypress/error_utils.js:224]: I don't think this does the same thing. It needs to return a string if `message` is a string and return an array if it's an array. This seems to always return an array and only include the first value if it is an array?

File: packages/runner/src/lib/event-manager.js [hunk 17]
```diff
@@ -197,40 +209,44 @@ const eventManager = {
...
+    return Cypress.initialize({
+      $autIframe,
+      onSpecReady: () => {
+        // get the current runnable in case we reran mid-test due to a visit
+        // to a new domain
+        ws.emit('get:existing:run:state', (state = {}) => {
+          const runnables = Cypress.normalizeAll(state.tests)
+          const run = () => {
+            performance.mark('initialize-end')
+            performance.measure('initialize', 'initialize-start', 'initialize-end')
```
Comment (brian-mann) [inline packages/runner/src/lib/event-manager.js:221]: did we mean to keep this in production?

File: packages/reporter/src/errors/error-stack.tsx [hunk 18]
```diff
@@ -0,0 +1,74 @@
+import _ from 'lodash'
+import { observer } from 'mobx-react'
+import React, { ReactElement } from 'react'
+
+import ErrorFilePath from './error-file-path'
+import Err from './err-model'
+
+const cypressLineRegex = /(cypress:\/\/|cypress_runner\.js)/
```
Comment (brian-mann) [inline packages/reporter/src/errors/error-stack.tsx:8]: i don't believe this is sufficient for production builds of cypress.


The `cypress://` protocol is only in development.

Comment (brian-mann) [reply packages/reporter/src/errors/error-stack.tsx:8]: wait nevermind, it has `cypress_runner.js` in there

Comment (chrisbreiding) [reply packages/reporter/src/errors/error-stack.tsx:8]: That's what the `cypress_runner.js` part is for.

File: packages/runner/src/lib/event-manager.js (hunk 17 above)
Comment (chrisbreiding) [reply packages/runner/src/lib/event-manager.js:221]: That wasn't introduced here. The indentation changed, that's the reason it's in the diff.

File: packages/driver/test/cypress/integration/commands/xhr_spec.coffee [hunk 19]
```diff
@@ -828,11 +828,12 @@ describe "src/cy/commands/xhr", ->
         e = new Error("onreadystatechange caused this error")
 
         cy.on "fail", (err) =>
+          debugger
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/xhr_spec.coffee:831]: debugger

File: packages/driver/test/cypress/plugins/index.js [hunk 20]
```diff
@@ -10,6 +10,9 @@ const webpack = require('@cypress/webpack-preprocessor')
 process.env.NO_LIVERELOAD = '1'
 const webpackOptions = require('@packages/runner/webpack.config.ts').default
 
+// get rid of prismjs plugin. the driver doesn't need it
+webpackOptions.module.rules[1].use.options.plugins.pop()
```
Comment (brian-mann) [inline packages/driver/test/cypress/plugins/index.js:14]: this seems really brittle

File: packages/reporter/src/errors/error-code-frame.tsx [hunk 21]
```diff
@@ -0,0 +1,36 @@
...
+  componentDidMount () {
+    Prism.highlightAllUnder(this.refs.codeFrame as ParentNode)
+  }
+
+  render () {
+    const { line, frame, language } = this.props.codeFrame
+
+    // since we pull out 2 lines above the highlighted code, it will always
+    // be the 3rd line unless it's at the top of the file (lines 1 or 2)
+    const highlightLine = line < 3 ? line : 3
```
Comment (brian-mann) [inline packages/reporter/src/errors/error-code-frame.tsx:23]: `Math.min(line, 3)`

File: packages/runner/webpack.config.ts [hunk 22]
```diff
@@ -1,6 +1,17 @@
...
-import commonConfig, { HtmlWebpackPlugin } from '@packages/web-config/webpack.config.base'
+import getCommonConfig, { HtmlWebpackPlugin } from '@packages/web-config/webpack.config.base'
 import path from 'path'
+import webpack from 'webpack'
+
+const commonConfig = getCommonConfig()
+
+// @ts-ignore
+commonConfig.module.rules[1].use.options.plugins.push([require.resolve('babel-plugin-prismjs'), {
+  'languages': ['javascript'],
```
Comment (brian-mann) [inline packages/runner/webpack.config.ts:10]: why do we set this here but then also set this in `reporter` and use different `languages` options?

https://github.com/cypress-io/cypress/pull/3930/files#diff-79efa94cf0c17d7e9b81ba8d6f3fce37R3

File: packages/server/__snapshots__/5_cdp_spec.ts.js [hunk 23]
```diff
@@ -39,7 +39,7 @@ The CDP port requested was 7777.
 Error details:
 
 Error: connect ECONNREFUSED 127.0.0.1:7777
-    [stack trace lines]
+      [stack trace lines]
```
Comment (brian-mann) [inline packages/server/__snapshots__/5_cdp_spec.ts.js:42]: im noticing a ton of snapshots that have extra indentations here... is this intended? seems like this shouldn't be the case

File: packages/server/lib/reporter.coffee [hunk 24]
```diff
@@ -123,16 +119,6 @@ mergeErr = (runnable, runnables, stats) ->
   ##
   ## Here's the code we're patching in the mocha version currently being used (7.0.1):
   ## https://github.com/mochajs/mocha/blob/2a8594424c73ffeca41ef1668446372160528b4a/lib/reporters/base.js#L208
```
Comment (brian-mann) [inline packages/server/lib/reporter.coffee:121]: can also remove these comments

File: packages/server/lib/util/shell.js [hunk 25]
```diff
@@ -94,6 +95,18 @@ const getShell = function (shell) {
   return findBash()
 }
 
+const commandExists = (command) => {
+  return Promise.resolve(commandExistsModule(command))
+  .then(() => true)
```
Comment (brian-mann) [inline packages/server/lib/util/shell.js:100]: `.return(true)`

File: packages/server/lib/util/shell.js [hunk 26]
```diff
@@ -94,6 +95,18 @@ const getShell = function (shell) {
...
+  .catch((err) => {
+    // commandExists rejects with no error if command does not exist
+    if (!err) return false
+
+    // otherwise, it's a legitimate error
+    throw err
+  })
+}
```
Comment (brian-mann) [inline packages/server/lib/util/shell.js:108]: `.catchReturn(_.isNil, false)`

File: packages/runner/webpack.config.ts (hunk 22 above)
Comment (chrisbreiding) [reply packages/runner/webpack.config.ts:10]: The `add-prism-transform.js` was added before switching to webpack and can be removed.

File: packages/server/__snapshots__/5_cdp_spec.ts.js (hunk 23 above)
Comment (chrisbreiding) [reply packages/server/__snapshots__/5_cdp_spec.ts.js:42]: Yes, this is because the e2e helper now normalizes the whitespace for stack lines. It was too inconsistent between Firefox and Chrome and the various types of errors.

**Comment by Saibamen** [comment]
Nice :)
Wait for next release

**Comment by kentcdodds** [comment]
This is terrific! It doesn't appear to show the codeframe in the terminal output when running headlessly with  `cypress run`. Is that supposed to be supported as well?

**Comment by chrisbreiding** [comment]
@kentcdodds Displaying the code frame in terminal output is not currently supported, but we're planning on adding that in the future.

**Comment by kentcdodds** [comment]
Good to hear! Is there an issue for tracking that? Or should I open a new one?

**Comment by chrisbreiding** [comment]
We have it listed in [this Epic issue for the next phase of error improvements](https://github.com/cypress-io/cypress/issues/7202). Feel free to create an individual issue for it though. It would help us gauge community interest in it and prioritize it.

**Comment by kentcdodds** [comment]
https://github.com/cypress-io/cypress/issues/7819 👍
