### PR TITLE
Control Chrome cookies through CDP

### LINKED ISSUE #5142: cy.setCookie is broken with chrome 77
### Current behavior:

image

### Desired behavior:
image

### Steps to reproduce: (app code and test code)
run the following test: it will fail:
```javascript
/// <reference types="Cypress" />

context('Window', () => {
  beforeEach(() => {
    cy.visit('http://google.com')
  })

  it('cy.window() - can set cookies', () => {
    // https://on.cypress.io/window
    cy.setCookie('cookieKey', 'angelfoobar', {
  		domain: '.google.com',
  		path: '/',
  		httpOnly: true,
  		secure: true,
  	});
  })

})


```

If you remove the domain it works:

```javascript

/// <reference types="Cypress" />

context('Window', () => {
  beforeEach(() => {
    cy.visit('http://google.com')
  })

  it('cy.window() - can set cookies', () => {
    // https://on.cypress.io/window
    cy.setCookie('cookieKey', 'angelfoobar', {
  		path: '/',
  		httpOnly: true,
  		secure: true,
  	});
  })

})


```

NOTE: this works fine on chrome 76. it broke with chrome 77 upgrade.
### Versions

Max OS 10.14.6
Chrome 77
Cypress 3.4.1

### LINKED ISSUE #5206: Use Chrome DevTools Protocol to set cookies in Chrome
Now that #4720 is merged, Cypress is controlling Electron's cookies API using CDP.

~~Once~~ Now that #4628 is merged, Cypress ~~will have~~ has access to Chrome's CDP as well.

We should unify the Electron/Chrome cookies code ~~when that happens~~ to cut down on issues that only occur in one or the other and simplify the code somewhat.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5142
- Closes #5206

### User facing changelog

* Improved the way that cookies are handled for Chrome-family browsers. Fixes setting a cookie with a domain beginning with a leading dot in Chrome 77. Closes #5142, #5206.
* Added RFC 6265 compliant validation of cookie names and values in `cy.setCookie`. An error will be thrown if an invalid name or value is supplied to `cy.setCookie`.

### Additional details

* [x] Waiting on #4628
* [x] Add tests that errors from automation still reach driver:
	- in chrome (develop), you can do cy.setCookie('foo', '        bar') and it fails saying failed to set cookie, and cookie not set
	- in electron, you do not get error, but cookie is not set
	- cookie should not be set and error should be thrown
* Added validation for names+values supplied to cy.setCookie. 
	* Invalid cookies would still error once they reach the automation, but this allows us to give the user a higher-fidelity error than just "idk, Chrome didn't like ur cookie `¯\_(ツ)_/¯` "
    * [x] waiting on charmander/strict-cookie-parser#1
* Moved the CDP implementation for Electron to new `cdp_automation` file
* Hooked Electron + Chrome's CRI from #4628 up to `cdp_automation`
* Changed Chrome and Electron's automation to use `Page.captureScreenshot` instead of the extension or Electron APIs for `take:screenshot`
* Left in the extension code, since it might be used for #1359 (WebExtension support should be the same across browsers) 
	* I think that now, all that the extension does is add a change listener for cookies, which is not possible in DevTools: https://github.com/cypress-io/cypress/blob/1afb6b630eb051de57914276dbed585f9b4a6239/packages/extension/app/background.coffee#L19-L21

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/src/cypress/error_messages.coffee [hunk 1]
```diff
@@ -812,7 +812,14 @@ module.exports = {
     unavailable: "The XHR server is unavailable or missing. This should never happen and likely is a bug. Open an issue if you see this message."
 
   setCookie:
+    backend_error: """
+    #{cmd('setCookie')} had an unexpected error setting the requested cookie in {{browserDisplayName}}.
+
+    {{errStack}}
+    """
     invalid_arguments: "#{cmd('setCookie')} must be passed two string arguments for name and value."
+    invalid_name: "#{cmd('setCookie')} must be passed an RFC-6265-compliant cookie name. You passed:\n\n`{{name}}`"
```
Comment (flotwig) [inline packages/driver/src/cypress/error_messages.coffee]: I wonder if this warning should apply to all the other cookie commands that take a 'name' option as well.

**Comment by brian-mann** [comment]
@flotwig can we also fix this issue with this PR? https://github.com/cypress-io/cypress/issues/5099

File: packages/server/lib/browsers/cri-client.ts [hunk 2]
```diff
@@ -86,7 +140,21 @@ export const initCriClient = async (debuggerUrl: websocketUrl): Promise<CRIWrapp
         throw err
       })
     },
-
+    takeScreenshot: () => {
+      return ensureMinimumProtocolVersion('1.3')
+      .catch((err) => {
+        throw new Error(`Taking a screenshot requires at least Chrome 64.\n\nDetails:\n${err.message}`)
```
[the remark this answers is not in the document]
Comment (flotwig) [reply packages/server/lib/browsers/cri-client.ts]: We should probably just throw even earlier if the version is < 1.3, since `Network.setCookie` (required for Cypress to work) is only available starting with 1.3.

[the remark this answers is not in the document]
Comment (flotwig) [reply packages/server/lib/browsers/cri-client.ts]: 7fd44a200670d407c39246ac7dacf41c15347702

File: packages/driver/src/cypress/error_messages.coffee (hunk 1 above)
Comment (flotwig) [reply packages/driver/src/cypress/error_messages.coffee]: 1aabc5925

File: packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js [hunk 3]
```diff
@@ -25,16 +30,33 @@ module.exports = (on) => {
...
+      .toNumber()
+      .value()
     }
-
-    return args
   })
 
   on('task', {
+    'set:device:metrics' () {
+      if (cdpPort) {
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js]: should specifically throw here if `cdpPort` should be defined and this is chrome - this guards against a situation where something else changes the logic and then this falls through because `cdpPort` is not set as we expect to

File: packages/server/lib/browsers/cdp_automation.ts [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+    // @ts-ignore
+    return cookie
+  }
+
+  const normalizeGetCookies = function (cookies: cdp.Network.Cookie[]) {
+    return _.map(cookies, normalizeGetCookieProps)
+  }
+
+  const normalizeSetCookieProps = function (cookie: CyCookie): cdp.Network.SetCookieRequest {
+    cookie.name || (cookie.name = '') // name can't be undefined/null
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: _.defaults()

File: packages/server/lib/browsers/cdp_automation.ts [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+    return cookie
+  }
+
+  const getAllCookies = function (data) {
+    return invokeViaDebugger('Network.getAllCookies').then(function (result: cdp.Network.GetAllCookiesResponse) {
+      return normalizeGetCookies(result.cookies).filter(function (cookie: CyCookie) {
+        return _.every([
+          !data.domain || tough.domainMatch(cookie.domain, data.domain),
+          !data.path || tough.pathMatch(cookie.path, data.path),
+          !data.name || data.name === cookie.name,
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: this is an extremely dense function that likely needs to be extracted into a method that describes what this is doing

File: packages/server/lib/browsers/cdp_automation.ts [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+  const getCookiesByUrl = function (url) {
+    return invokeViaDebugger('Network.getCookies', {
+      urls: [url],
+    }).then(function (result: cdp.Network.GetCookiesResponse) {
+      return normalizeGetCookies(result.cookies)
+    })
+  }
+
+  const getCookie = function (data): Promise<cdp.Network.Cookie> {
+    return getAllCookies(data).then(_.partialRight(_.get, 0, null))
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: `.get(0)`

File: packages/server/lib/browsers/cdp_automation.ts [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+      case 'get:cookie':
+        return getCookie(data)
+      case 'set:cookie':
+        setCookie = normalizeSetCookieProps(data)
+
+        return invokeViaDebugger('Network.setCookie', setCookie).then(function (result: cdp.Network.SetCookieResponse) {
+          if (!result.success) {
+            // i wish CDP provided some more detail here, but this is really it in v1.3
+            // @see https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie
+            throw new Error('Failed to set cookie via Network.setCookie.')
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: might want to `JSON.stringify()` the cookie props so we at least get those as part of the error

File: packages/server/lib/browsers/cdp_automation.ts [hunk 8]
```diff
@@ -0,0 +1,130 @@
...
+          }
+
+          return getCookie(data)
+        })
+      case 'clear:cookie':
+        return getCookie(data).then(function (cookieToBeCleared) { // so we can resolve with the value of the removed cookie
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: `.tap()`

File: packages/server/lib/browsers/chrome.coffee [hunk 9]
```diff
@@ -315,18 +325,24 @@ module.exports = {
         .then (criClient) =>
           la(criClient, "expected Chrome remote interface reference", criClient)
 
-          ## monkey-patch the .kill method to that the CDP connection is closed
-          originalBrowserKill = launchedBrowser.kill
+          criClient.ensureMinimumProtocolVersion('1.3')
+          .catch (err) =>
+            throw new Error("Cypress requires at least Chrome 64.\n\nDetails:\n#{err.message}")
```
Comment (brian-mann) [inline packages/server/lib/browsers/chrome.coffee]: curious why you're re-throwing the error here when there's already a specific error being handled by `CDP_VERSION_TOO_OLD`

File: packages/server/lib/browsers/chrome.coffee [hunk 10]
```diff
@@ -315,18 +325,24 @@ module.exports = {
...
+              debug("closing remote interface client")
 
-            criClient.close()
-            .then =>
-              debug("closing chrome")
-              originalBrowserKill.call(launchedBrowser, args...)
+              criClient.close()
+              .then =>
+                debug("closing chrome")
+                originalBrowserKill.call(launchedBrowser, args...)
```
Comment (brian-mann) [inline packages/server/lib/browsers/chrome.coffee]: `.apply(launchedBrowser, args)`

File: packages/server/lib/browsers/cri-client.ts [hunk 11]
```diff
@@ -109,21 +119,52 @@ export const create = async (debuggerUrl: websocketUrl): Promise<CRIWrapper> =>
...
 
+  let cachedProtocolVersionP
+
+  const ensureMinimumProtocolVersion = (protocolVersion: string): Promise<void> => {
+    return getProtocolVersion()
+    .then((actual) => {
+      const minimum = getMajorMinorVersion(protocolVersion)
+
+      const hasVersion = actual.major > minimum.major
+         || (actual.major === minimum.major && actual.minor >= minimum.minor)
```
Comment (brian-mann) [inline packages/server/lib/browsers/cri-client.ts]: dense logic, extract to a named function for clarity

File: packages/server/lib/browsers/cri-client.ts [hunk 12]
```diff
@@ -109,21 +119,52 @@ export const create = async (debuggerUrl: websocketUrl): Promise<CRIWrapper> =>
...
+      if (!hasVersion) {
+        errors.throw('CDP_VERSION_TOO_OLD', protocolVersion, actual)
+      }
+    })
+  }
+
+  const getProtocolVersion = () => {
+    if (!cachedProtocolVersionP) {
+      cachedProtocolVersionP = cri.send('Browser.getVersion')
+      .catch(() => {
```
Comment (brian-mann) [inline packages/server/lib/browsers/cri-client.ts]: `.catchReturn`

File: packages/server/lib/browsers/cdp_automation.ts [hunk 13]
```diff
@@ -0,0 +1,130 @@
...
+      let parsedDomain = cors.parseDomain(cookie.domain)
+
+      // not a top-level domain (localhost, ...) or IP address
+      if (parsedDomain && parsedDomain.tld !== cookie.domain) {
+        cookie.domain = `.${cookie.domain}`
+      }
+    }
+
+    delete cookie.hostOnly
+    delete cookie.expirationDate
```
Comment (brian-mann) [inline packages/server/lib/browsers/cdp_automation.ts]: this logic is really opaque, would be nice to comment what we're doing here and why. this is obviously handling a bunch of different situations, so either point to the tests that cover this - or try to describe it succinctly (or both)

File: packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js [hunk 14]
```diff
@@ -25,16 +30,33 @@ module.exports = (on) => {
...
+        // force chrome to 1x and 1280x720
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js]:
```
// so screenshot sizes are consistent on all user environments and runtimes
```

File: packages/server/lib/browsers/chrome.coffee [hunk 15]
```diff
@@ -315,18 +325,24 @@ module.exports = {
         .then (criClient) =>
           la(criClient, "expected Chrome remote interface reference", criClient)
 
-          ## monkey-patch the .kill method to that the CDP connection is closed
-          originalBrowserKill = launchedBrowser.kill
+          criClient.ensureMinimumProtocolVersion('1.3')
```
Comment (brian-mann) [inline packages/server/lib/browsers/chrome.coffee]: there are no tests verifying this function is ever called. there's tests on the actual `ensureMinimumProtocolVersion` function, but no tests that `_writeExtension` ever calls this.

There's likely existing `integration/cypress_spec` tests that test things very close to this - or you could write a unit tests for `browsers/chrome`

File: packages/server/lib/browsers/chrome.coffee (hunk 9 above)
Comment (flotwig) [reply packages/server/lib/browsers/chrome.coffee]: The CDP version warning isn't really actionable to the user, but "upgrade to chrome 64+" is, so I felt it would be best to wrap it with that.

File: packages/server/lib/browsers/cdp_automation.ts (hunk 6 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: Need this to return `null` if it's unset, not `undefined`

File: packages/server/lib/browsers/cdp_automation.ts (hunk 13 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: i'm having deja vu, i'm 99% sure i put the link to the chromium codesearch in here back when we did this the first time... let me see if i can find it again

File: packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js (hunk 14 above)
Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js]: 33228d241

File: packages/server/lib/browsers/cdp_automation.ts (hunk 7 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: true, b2825a693

File: packages/server/lib/browsers/cdp_automation.ts (hunk 5 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: b2825a693

File: packages/server/lib/browsers/cdp_automation.ts (hunk 4 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: b2825a693

File: packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js (hunk 3 above)
Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js]: 33228d241

File: packages/server/lib/browsers/chrome.coffee (hunk 10 above)
Comment (flotwig) [reply packages/server/lib/browsers/chrome.coffee]: a4b8167bb

File: packages/server/lib/browsers/chrome.coffee (hunk 15 above)
Comment (flotwig) [reply packages/server/lib/browsers/chrome.coffee]: There is a test that the error is thrown here: https://github.com/cypress-io/cypress/blob/b2825a6936d1b6fe86a46b30b3d783b5d634471e/packages/server/test/unit/browsers/chrome_spec.coffee#L142-L145

Added an assertion that @criClient.ensureMinimumProtocol version was called in every #open call: a4b8167bb

File: packages/server/lib/browsers/cdp_automation.ts (hunk 13 above)
Comment (flotwig) [reply packages/server/lib/browsers/cdp_automation.ts]: b2323e059

File: packages/server/lib/browsers/cri-client.ts (hunk 11 above)
Comment (flotwig) [reply packages/server/lib/browsers/cri-client.ts]: b2323e059

File: packages/server/lib/browsers/cri-client.ts [hunk 16]
```diff
@@ -1,10 +1,13 @@
...
 import debugModule from 'debug'
 import _ from 'lodash'
 
 const chromeRemoteInterface = require('chrome-remote-interface')
+
 const debugVerbose = debugModule('cypress-verbose:server:browsers:cri-client')
-const debugVerboseSend = debugModule('cypress-verbose:server:browsers:cri-client:[-->]')
-const debugVerboseReceive = debugModule('cypress-verbose:server:browsers:cri-client:[<--]')
+const debugVerboseSend = debugModule('cypress-verbose:server:browsers:cri-client:send')
+const debugVerboseReceive = debugModule('cypress-verbose:server:browsers:cri-client:recv')
```
Comment (brian-mann) [inline packages/server/lib/browsers/cri-client.ts]:
```
cypress-verbose:server:browsers:cri-client:send:[-->]
cypress-verbose:server:browsers:cri-client:recv:[<--]
```

Comment (flotwig) [reply packages/server/lib/browsers/cri-client.ts]: Neither `DEBUG=cypress-verbose:server:browsers:cri-client:send:*` nor `DEBUG=cypress-verbose:server:browsers:cri-client:send` produce output, and `DEBUG=cypress-verbose:server:browsers:cri-client:send:[-->]` breaks `debug`: 

```
$ DEBUG=cypress-verbose:server:browsers:cri-client:send:[-->] npm run test-e2e -- --spec 1_base_url_spec.coffee
/home/flotwig/Projects/cypress/cypress3/node_modules/snapdragon/node_modules/debug/src/debug.js:153
      exports.names.push(new RegExp('^' + namespaces + '$'));
                         ^

SyntaxError: Invalid regular expression: /^cypress-verbose:server:browsers:cri-client:send:[--$/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Function.enable (/home/flotwig/Projects/cypress/cypress3/node_modules/snapdragon/node_modules/debug/src/debug.js:153:26)
    at Object.<anonymous> (/home/flotwig/Projects/cypress/cypress3/node_modules/snapdragon/node_modules/debug/src/node.js:248:9)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/flotwig/Projects/cypress/cypress3/node_modules/snapdragon/node_modules/debug/src/index.js:9:20)
```

**Comment by goktugy** [comment]
I ma afraid #5142 is still happening. If I don't use "domain" then set cookie works but it fails otherwise.  When setting the cookie I can't set the domain information. Can someone please kindly look into this issue?

**Comment by flotwig** [comment]
@goktugy Please open a new issue and supply all the requested information, we can't really do anything with comments left on closed issues.
