### PR TITLE
fix(server): increase timeout when making Marionette connection

### LINKED ISSUE #7159: Firefox randomly failing to start in CI
### Current behavior:

When running tests with Firefox in CI (GitHub Actions), it randomly fails to start with this error:
```
Cypress could not connect to Firefox.

An unexpected error was received from Marionette connection:

Error: cannot open socket

To avoid this error, ensure that there are no other instances of Firefox launched by Cypress running.
```

It may be linked to #6504 , but because the environment seems to be different, I think a new issue is more appropriate.

### Desired behavior:

Cypress runs reliably everytime.

### Test code to reproduce

Repository: https://github.com/Seb-C/test-cypress-action
CI script: https://github.com/Seb-C/test-cypress-action/blob/master/.github/workflows/tests.yml
(all tests are the default one when we first do `cypress open` in a new project)

Runs history (showing the randomness): https://github.com/Seb-C/test-cypress-action/actions
Logs of a failed run: https://github.com/Seb-C/test-cypress-action/runs/625344325?check_suite_focus=true

### Versions

- GitHub actions
- Ubuntu 18.04.4 LTS
- Firefox 74.0.1
- Cypress 4.4.1

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #7159 

### User facing changelog

- Increased the timeout for launching Firefox from 2.5 seconds to 50 seconds. Previously, users hitting this limit would encounter a "cannot open socket" error; now, the error will be wrapped.
- Increased the timeout for launching Chrome from 20 seconds to 50 seconds.

### Additional details

- Previously, retries were deferred to the Marionette library, which only retried for 2.5 seconds.
- Now, it will retry for up to ~~20~~ 50 seconds, which matches what we do for Foxdriver and CDP.
- Also, errors from Foxdriver + Marionette connections are now wrapped.
- [x] Verified that the 50 second timeout is enough for GitHub actions (2 failures from unrelated flake in specs): https://github.com/flotwig/test-cypress-action/commits/master
	- with 20 seconds, there were times where Marionette had not yet started listening

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/browsers/firefox-util.ts [hunk 1]
```diff
@@ -220,7 +222,13 @@ export default {
...
 
   async setupMarionette (extensions, url, port) {
-    const driver = new Marionette.Drivers.Promises({ port })
+    await protocol._connectAsync({
+      host: '127.0.0.1',
+      port,
+      getDelayMsForRetry,
+    })
+
+    const driver = new Marionette.Drivers.Promises({ port, tries: 1 })
```
Comment (Bkucera) [inline packages/server/lib/browsers/firefox-util.ts:231]: can you add a comment on this

File: packages/server/lib/browsers/firefox.ts [hunk 2]
```diff
@@ -281,6 +282,8 @@ const defaultPreferences = {
   // allow getUserMedia APIs on insecure domains
   'media.devices.insecure.enabled':	true,
   'media.getusermedia.insecure.enabled': true,
+
+  'marionette.log.level': process.env.DEBUG ? 'Debug' : undefined,
```
Comment (Bkucera) [inline packages/server/lib/browsers/firefox.ts:286]: how verbose is this going to be?

Comment (flotwig) [reply packages/server/lib/browsers/firefox.ts:286]: after running the 19 example spec files, it looks like the extra logs tagged with Marionette amount to 309 lines: https://github.com/flotwig/test-cypress-action/runs/679150446

without this log level, there are 38 lines: https://github.com/flotwig/test-cypress-action/runs/678939258

do you think it should be removed? i added it because it helped me see the logs from when the TCP server is started: https://searchfox.org/mozilla-central/rev/3ce874dc2703831af3e5ef3a1d216ffd08057fa5/testing/marionette/components/marionette.js#508

Comment (flotwig) [reply packages/server/lib/browsers/firefox.ts:286]: note, this will still only log out if the user has enabled `cypress:launcher` logs, since it prints to Firefox's stderr. we don't pipe browser stdio to Cypress stdio directly

Comment (Bkucera) [inline packages/server/lib/browsers/firefox.ts:286]:
```suggestion
  'marionette.log.level': debug.enabled ? 'Debug' : undefined,
```

Comment (Bkucera) [reply packages/server/lib/browsers/firefox.ts:286]: I think its good

Comment (flotwig) [reply packages/server/lib/browsers/firefox.ts:286]: this would be...

```suggestion
  'marionette.log.level': debug('cypress:launcher').enabled ? 'Debug' : undefined,
```

since stderr is piped in launcher:

https://github.com/cypress-io/cypress/blob/8df8bb446213265cd922f8cfa6cb18c5df9897e2/packages/launcher/lib/browsers.ts#L124-L126

but i figured process.env.DEBUG would be better than debug('cypress:launcher'), because it will still be correct even if the launcher's debug setup is changed, or if we ever move browser spawning to happen elsewhere

Comment (flotwig) [reply packages/server/lib/browsers/firefox.ts:286]: ooh i can just use the `log.ts` module exported from launcher instead, i'll do that

File: packages/server/test/unit/browsers/firefox_spec.ts [hunk 3]
```diff
@@ -313,10 +310,33 @@ describe('lib/browsers/firefox', () => {
...
+      .then((wrapperErr) => {
+        expect(wrapperErr.message).to.include('Cypress failed to make a connection to Firefox.')
+        expect(wrapperErr.message).to.include(err.message)
+      })
+    })
   })
 
   context('firefox-util', () => {
     context('#setupMarionette', () => {
+      it('attaches geckodriver after testing connection', async () => {
```
Comment (Bkucera) [inline packages/server/test/unit/browsers/firefox_spec.ts:329]: issue link comment
