### PR TITLE
fix: `res.send` of `cy.intercept` doesn't override json-related content types

### LINKED ISSUE #17084: Intercept resets compatible content type when body is an object
### Current behavior

The following test passes:

```javascript
const axios = require('axios');

it('overwrites the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    // A variant of the normal json content type specifically designed
                    // for error messages.
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                body: {
                    status: 500,
                    title: 'Internal Server Error',
                },
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            // Note that this asserts the standard json content type
            expect(error.response.headers['content-type']).to.equal('application/json');
        });
});
```

image

### Desired behavior

`.intercept()` should not overwrite the content type if I explicitly provide one. Especially if my content type matches the response body.

Or, in other words. The following test should pass:

<details>
  <summary>The test</summary>
  
  ```javascript
const axios = require('axios');

it('does not overwrite the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                body: {
                    status: 500,
                    title: 'Internal Server Error',
                },
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            // Now asserts the content type for Problem JSON
            expect(error.response.headers['content-type']).to.equal('application/problem+json');
        });
});

  ```
  
</details>

### Test code to reproduce

As above :)

I also have a random server up at `http://localhost:3000`. Since we're replacing the response of the server anyway, it really doesn't matter what's running there. My server is an Express Hello World :)

```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    res.send('Hello World!')
})

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})
```

### Versions

Cypress: 7.5.0

### Workaround

I already found a workaround. I'll share it in case it helps someone else.

This only happens when your response body is an object, so all you have to do is stringify it like so:

```javascript
const axios = require('axios');

it('overwrites the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                // Stringify as a workaround. This issue only happens when body is an
                // object. `JSON.stringify` turns it into a string instead.
                body: JSON.stringify({
                    status: 500,
                    title: 'Internal Server Error',
                }),
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            expect(error.response.headers['content-type']).to.equal('application/problem+json');
        });
});
```

### PR DESCRIPTION
**Pull request by flotwig**
Reverts cypress-io/cypress#17400

Re-adds #17199

Closes #17084

### User facing changelog

`res.send` of `cy.intercept` doesn't override json-related content types.

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -2685,6 +2685,30 @@ describe('network stubbing', { retries: 2 }, function () {
...
+              title: 'Internal Server Error',
+            },
+          })
+        })
+      })
+
+      fetch('/json-content-type')
+      .then((res) => {
+        expect(res.headers.get('content-type')).to.eq('application/problem+json')
+      })
```
Comment (flotwig) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:2709]: This will pass even if the expectation failures because the promise is not returned:

```suggestion
      return fetch('/json-content-type')
      .then((res) => {
        expect(res.headers.get('content-type')).to.eq('application/problem+json')
      })
```

File: packages/driver/src/cy/net-stubbing/events/response.ts [hunk 2]
```diff
@@ -75,7 +75,14 @@ export const onResponse: HandlerFn<CyHttpMessages.IncomingResponse> = async (Cyp
...
 
-        _.defaults(_staticResponse.headers, res.headers)
+        _staticResponse.headers = _.defaults({}, _staticResponse.headers, res.headers)
+
+        // https://github.com/cypress-io/cypress/issues/17084
+        // When a user didn't provide content-type,
+        // we remove the content-type provided by the server
+        if (!staticResponse.headers || !staticResponse.headers['content-type']) {
+          delete _staticResponse.headers['content-type']
+        }
```
Comment (flotwig) [inline packages/driver/src/cy/net-stubbing/events/response.ts:85]: This code block is causing https://app.circleci.com/pipelines/github/cypress-io/cypress/22275/workflows/eb6fc6d5-607e-4bf1-8cc6-c17ae12b0e03/jobs/817100 to fail when attempting to override the content-type of a .csv. Check out this spec: https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/integration/location-href-spec.js

**Review by flotwig — COMMENTED** [review]
@sainthkh this was causing a CI failure in `develop` that looks legitimate, can you please take a look at the review comments on this PR and resolve them?

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts (hunk 1 above)
Comment (sainthkh) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:2709]: :+1:

File: packages/driver/src/cy/net-stubbing/events/response.ts (hunk 2 above)
Comment (sainthkh) [reply packages/driver/src/cy/net-stubbing/events/response.ts:85]:
```suggestion
        _staticResponse.headers = _.defaults({}, _staticResponse.headers, res.headers)

        // https://github.com/cypress-io/cypress/issues/17084
        // When a user didn't provide content-type,
        // and they provided body as an object,
        // we remove the content-type provided by the server
        if (!staticResponse.headers || !staticResponse.headers['content-type']) {
          if (typeof _staticResponse.body === 'object') {
            delete _staticResponse.headers['content-type']
          }
        }
```

I don't have an authority to push commits to this branch. So, I leave this suggestion. 

These lines of code had to be added because when a user doesn't provide content-type, the server-provided content-type was used and the returned type of content was string when user provided the `object` body. 

But this removes legitimate `content-type`s provided by the server. So, I added a condition to remove the `content-type` only when user-provided `body` type is `object`.

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 3]
```diff
@@ -2685,6 +2685,30 @@ describe('network stubbing', { retries: 2 }, function () {
...
+              title: 'Internal Server Error',
+            },
+          })
+        })
+      })
+
+      return fetch('/json-content-type')
+      .then((res) => {
+        expect(res.headers.get('content-type')).to.eq('application/problem+json')
+      })
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:2709]:
```suggestion
      cy.intercept('/json-content-type', (req) => {
        req.on('response', (res) => {
          res.send({
            statusCode: 500,
            headers: {
              'content-type': 'application/problem+json',
              'access-control-allow-origin': '*',
            },
            body: {
              status: 500,
              title: 'Internal Server Error',
            },
          })
        })
      })
      .then(() => {
        return fetch('/json-content-type')
        .then((res) => {
          expect(res.headers.get('content-type')).to.eq('application/problem+json')
        })
      })
```

The test should be written like above. Otherwise, Firefox and others shows a warning.
