### PR TITLE
fix: additionally set electron user agent through CDP

### LINKED ISSUE #23597: User agent in Electron isn't fully overridden when providing the `experimentalModifyObstructiveThirdPartyCode` option
### Current behavior

Inside Electron, it looks like some requests, in particular document requests, have the incorrect UA associated with the request. 

### Desired behavior

Cypress should override the user agent as expected in #22958 in all cases when Electron is run with `experimentalModifyObstructiveThirdPartyCode` option set to true

### Test code to reproduce

Adding the following code after [this line](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/electron.ts#L437) seems to resolve the issue, via setting the UA optimistically via CDP:

```
 webContents.debugger.sendCommand('Network.setUserAgentOverride', {
   userAgent,
 })
```

### Cypress Version

10.6.0

### Node version

v16.15.0

### Operating System

macOS 12.4 (Monterey)

### Debug Logs

```shell
Not Needed in this case as code is reproducible
```

### Other

This doesn't seem to have an impact on Google login, which means the behavior may have changed

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #23597

### User facing changelog
Additionally overrides the electron user agent via CDP if the [userAgent](https://docs.cypress.io/guides/references/configuration#Browser) config option is provided or `experimentalModifyObstructiveThirdPartyCode` is enabled.

### Additional details

It looks like the changes in #22958 did not fully override the electron user agent as expected (see #23597). In addition to setting the userAgent via the Electron's [webContents.session](https://www.electronjs.org/docs/latest/api/session#sessetuseragentuseragent-acceptlanguages) API, we now optimistically set the user agent via CDP, which resolves the issue entirely.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by chrisbreiding — APPROVED** [review]

File: packages/server/lib/browsers/electron.ts [hunk 1]
```diff
@@ -437,6 +437,11 @@ export = {
     // set both because why not
     webContents.userAgent = userAgent
 
+    // In addition to the session, also set the user optimistically through CDP. @see https://github.com/cypress-io/cypress/issues/23597
```
Comment (mschile) [inline packages/server/lib/browsers/electron.ts:440]:
```suggestion
    // In addition to the session, also set the user-agent optimistically through CDP. @see https://github.com/cypress-io/cypress/issues/23597
```

**Review by mschile — APPROVED** [review]
