### PR TITLE
breaking: Normalize results from module api, after:run, and after:spec

### LINKED ISSUE #23805: after:spec result does not match specification
### Current behavior

My plugin listens to the `after:spec` event and reports on the results it receives. The `stats` property of `results` has the following properties:
```js
{
  suites: 1,
  tests: 1,
  passes: 1,
  pending: 0,
  skipped: 0,
  failures: 0,
  wallClockStartedAt: '2022-09-13T15:47:03.696Z',
  wallClockEndedAt: '2022-09-13T15:47:05.123Z',
  wallClockDuration: 1427
}
```

### Desired behavior

According to https://github.com/cypress-io/cypress/blob/566a1a208cb51d193fd1838a4c35ab872a729fe7/cli/types/cypress.d.ts#L5565, the `results` type is `CypressCommandLine.RunResult`.

The `RunResult` interface describes `stats` as:
```
    stats: {
      suites: number
      tests: number
      passes: number
      pending: number
      skipped: number
      failures: number
      startedAt: dateTimeISO
      endedAt: dateTimeISO
      duration: ms
    }
```

This does not match the actual object's properties that I'm receiving. 

In particular:
- startedAt vs wallClockStartedAt
- endedAt vs wallClockEndedAt
- duration vs wallClockDuration

### Test code to reproduce

Simply listen to the `after:spec` event and inspect the results.

### Cypress Version

10.7.0

### Node version

v16.13.0

### Operating System

macOS 12.4

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #23805

### Additional details

See [ClickUp requirements](https://app.clickup.com/18033298/docs/h6amj-46207/h6amj-55367) and [final desired run object](https://app.clickup.com/18033298/docs/h6amj-46207/h6amj-57691)

Updates the results returned by the module API and provided to the handlers for the `after:run` and `after:spec` events to be more consistent and remove extra properties that are used internally and not useful for end users. Also removes those properties from debug logs and events emitted to mocha. 

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/5379
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/__snapshots__/run_spec.js [hunk 1]
```diff
@@ -1,25 +0,0 @@
-exports['enabled experiments'] = `
```
Comment (chrisbreiding) [inline packages/server/__snapshots__/run_spec.js:1]: The spec for this snapshot no longer exists.

File: system-tests/test/module_api_spec.js [hunk 2]
```diff
@@ -42,17 +42,15 @@ describe('e2e spec_isolation', () => {
       expectCorrectModuleApiResult(json, {
         e2ePath, runs: 4, video: false,
       })
-
-      systemTests.snapshot(json, { allowSharedSnapshot: true })
```
Comment (chrisbreiding) [inline system-tests/test/module_api_spec.js:46]: These snapshots have been superseded by the `results_spec`

**Comment by jordanpowell88** [comment]
@chrisbreiding Can we build a binary for this so to send to 3rd party lib authors? @barbados-clemens  from Nx was asking specifically

**Comment by chrisbreiding** [comment]
> Can we build a binary for this so to send to 3rd party lib authors?

@jordanpowell88 Certainly! It's built for the [latest commit](https://github.com/cypress-io/cypress/commit/22a0f23ffd4c779bfce351a3806c0f4fd91c793d#comments).

**Comment by barbados-clemens** [comment]
> > Can we build a binary for this so to send to 3rd party lib authors?
> 
> @jordanpowell88 Certainly! It's built for the [latest commit](https://github.com/cypress-io/cypress/commit/22a0f23ffd4c779bfce351a3806c0f4fd91c793d#comments).

Thank you @chrisbreiding, didn't notice any issue on our side!

**Review by mjhenkes — APPROVED** [review]

File: cli/types/cypress-npm-api.d.ts [hunk 3]
```diff
@@ -216,87 +195,97 @@ declare namespace CypressCommandLine {
...
-      /**
-       * resolved filename of the spec
-       */
-      absolute: string
-      relativeToCommonRoot: string
-    }
-    skippedSpec: boolean
+  }
+
+  type PublicConfig = Omit<Cypress.ResolvedConfigOptions, 'additionalIgnorePattern' | 'autoOpen' | 'browser' | 'browsers' | 'browserUrl' | 'clientRoute' | 'cypressEnv' | 'devServerPublicPathRoute' | 'morgan' | 'namespace' | 'proxyServer' | 'proxyUrl' | 'rawJson' | 'remote' | 'repoRoot' | 'report' | 'reporterRoute' | 'reporterUrl' | 'resolved' | 'setupNodeEvents' | 'socketId' | 'socketIoCookie' | 'socketIoRoute' | 'specs' | 'state' | 'supportFolder'> & {
```
Comment (lmiller1990) [inline cli/types/cypress-npm-api.d.ts:257]: More a style thing, but should we use `Pick` instead? IF we add a new property to `Cypress.ResolvedConfigOptions`, it'll be public by default. Using `Pick` would make us consciously opt in to exposing any new properties.

File: packages/server/lib/modes/run.ts [hunk 4]
```diff
@@ -989,7 +958,29 @@ async function runSpec (config, spec: SpecWithRelativeRoot, options: { project:
...
+  outputPath: string
+  parallel: boolean
+  projectRoot: string
+  quiet: boolean
+  record: boolean
+  socketId: string
+  spec: string | RegExp | string[]
+  tag: string
+  testingType: TestingType
+  webSecurity: boolean
```
Comment (lmiller1990) [inline packages/server/lib/modes/run.ts:980]: Yes, thanks for doing this!

File: system-tests/lib/resultsUtils.ts [hunk 5]
```diff
@@ -240,25 +240,23 @@ export const expectCorrectModuleApiResult = (json, opts: {
     expectStartToBeBeforeEnd(run, 'stats.startedAt', 'stats.endedAt')
```
Comment (lmiller1990) [inline system-tests/lib/resultsUtils.ts:240]: Was it intentional to delete the entire file above, `system-tests/__snapshots__/spec_isolation_spec.js`?

File: system-tests/test/results_spec.ts [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+
+// source: https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/
+const isoDateRegex = /"([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?"/g
+const numberRegex = /"(duration|totalDuration|port)": \d+/g
+const osNameRegex = /"(osName|platform)": "[^"]+"/g
+const archRegex = /"arch": "[^"]+"/g
+const versionRegex = /"(browserVersion|cypressVersion|osVersion|resolvedNodeVersion|version)": "[^"]+"/g
+const majorVersionRegex = /"(majorVersion)": [0-9]+/g
+const pathRegex = /"(absolute|projectRoot|downloadsFolder|fileServerFolder|fixturesFolder|resolvedNodePath|screenshotsFolder|videosFolder|cypressBinaryRoot|path)": "[^"]+"/g
+const stackLineRegex = /"displayError": (.*)at .*/g
```
Comment (lmiller1990) [inline system-tests/test/results_spec.ts:14]: Which is the best test to look at to see if these are doing what they are supposed to? I looked at the snapshots and don't see anything off. Would that be enough to be confident these are correct?

**Review by lmiller1990 — APPROVED** [review]
I don't see any major blockers. I left a few comments and asked a few questions, primarily to make sure I understand everything that's going on. Thanks for this!

File: system-tests/test/module_api_spec.js (hunk 2 above)
Comment (lmiller1990) [reply system-tests/test/module_api_spec.js:46]: Right, just saw this. I commented about the snapshots. Same goes for the isolation spec snapshots, I'm assuming.

File: system-tests/lib/resultsUtils.ts [hunk 7]
```diff
@@ -240,25 +240,23 @@ export const expectCorrectModuleApiResult = (json, opts: {
...
+      wallClocks + 600, // add 600ms to account for padding
       1234,
     )
 
     expectDurationWithin(
       run,
       'reporterStats.duration',
       wallClocks,
-      wallClocks + 400, // add 400ms to account for padding
+      wallClocks + 600, // add 600ms to account for padding
```
Comment (AtofStryker) [inline system-tests/lib/resultsUtils.ts:259]: any idea why we needed to increase the padding here?

File: system-tests/test/results_spec.ts [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+
+describe('module api, after:spec, and after:run results', () => {
+  systemTests.setup()
+
+  const projectPath = Fixtures.projectPath('results')
+  const outputPath = path.join(projectPath, 'module-api-results.json')
+
+  systemTests.it('has expected properties and values', {
+    project: 'results',
+    browser: 'electron',
```
Comment (AtofStryker) [inline system-tests/test/results_spec.ts:47]: should we execute this test in other browsers as well to make sure the results are normalized as expected or do we think it adds unnecessary overhead?

**Review by AtofStryker — APPROVED** [review]

File: cli/types/cypress-npm-api.d.ts (hunk 3 above)
Comment (chrisbreiding) [reply cli/types/cypress-npm-api.d.ts:257]: This mirrors how it's implemented in the code, which is what actually determines what is exposed or not. Whereas most of the results have to be purposefully allow-listed, I intentionally made the properties for the config a block-list instead. When anything outside these omitted properties are added/removed/changed, the [results snapshot](https://github.com/cypress-io/cypress/blob/normalize-api-results/system-tests/__snapshots__/results_spec.ts.js) will no longer match, so new properties can't be added without a conscious choice to update that snapshot with them.

All of these omitted properties are internal ones we've glommed onto the config even though a user can't configure them. Most new properties we add to the config these days are public ones that should be included in the results.

Additionally, there's already a lot of boilerplate that needs to change when a new config property is added. I was trying to reduce that by using `Omit` instead of `Pick` here. The worst-case scenario is that, if we add a new internal property that should be omitted and forget to omit it in the type here, the type will not match what's actually in the results. The same risk exists for using `Pick` where we could forget to add a new property and there will be a mismatch.

File: packages/server/lib/modes/run.ts (hunk 4 above)
Comment (chrisbreiding) [reply packages/server/lib/modes/run.ts:980]: Yeah, I'm not a fan of massive (i.e. having more than maybe 2 properties) inline types 😄

File: system-tests/lib/resultsUtils.ts (hunk 5 above)
Comment (chrisbreiding) [reply system-tests/lib/resultsUtils.ts:240]: Yes, the stdout snapshot doesn't provide any real value and the results snapshot is made redundant by the `results_spec.js` snapshot.

File: system-tests/lib/resultsUtils.ts (hunk 7 above)
Comment (chrisbreiding) [reply system-tests/lib/resultsUtils.ts:259]: I found it liable to be a bit flaky. I even saw this fail in an unrelated branch.

File: system-tests/test/module_api_spec.js (hunk 2 above)
Comment (chrisbreiding) [reply system-tests/test/module_api_spec.js:46]: I renamed `spec_isolation_spec` to be this file, based off the comment that was at the top and my agreement that it's a more appropriate name. I had looked for a spec like this when I started this work and totally missed this one. If it had been named `module_api_spec` to begin with, I probably would have found i.t

File: system-tests/test/results_spec.ts (hunk 6 above)
Comment (chrisbreiding) [reply system-tests/test/results_spec.ts:14]: I'd say so. The snapshot would fail either on a subsequent run where the durations are concerned and on a different system, like CI, where paths and OS/browser details are concerned.

File: system-tests/test/results_spec.ts (hunk 8 above)
Comment (chrisbreiding) [reply system-tests/test/results_spec.ts:47]: I'd say it's unnecessary overhead. This test is primarily concerned with which properties are included in the results, which should not vary between browsers. Other tests are more appropriate for asserting on the values of the properties as they may relate to differences between browsers.
