### PR TITLE
fix: Add reporter options

### LINKED ISSUE #7877: Missing reporterOptions from the ResolvedConfigOptions in cypress
### Current behavior:
reporterOptions is missing from [cypress.d.ts](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)

### Desired behavior:
reporterOptions should be added

### Test code to reproduce
N/A these are typescript types

### Versions
4.9.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-252) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by admmasters**
* Closes #7877

### User facing changelog
adds reporterOptions to the typescript typings

### Additional details
* Change was needed so we can pass reporterOptions.
* Adds the reporterOptions.
* We are using a dictionary with a value of "any" to capture all the potential reporter options.

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-225) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -2352,9 +2352,14 @@ declare namespace Cypress {
      * @default "spec"
      */
     reporter: string
+    /**
+     * Some reporters accept [reporterOptions](https://docs.cypress.io/guides/tooling/reporters.html#Reporter-Options) that customize their behavior
+     * @default "spec"
+     */
+    reporterOptions: { [key: string]: any }
     /**
      * Whether to take a screenshot on test failure when running headlessly or in CI
```
Comment (jennifer-shehane) [inline cli/types/cypress.d.ts:2361]: Old comment leftover from copy/paste. 

```suggestion
     * Customize reporter behavior by passing options
```

File: cli/types/cypress.d.ts [hunk 2]
```diff
@@ -2352,9 +2352,14 @@ declare namespace Cypress {
      * @default "spec"
      */
     reporter: string
+    /**
+     * Some reporters accept [reporterOptions](https://docs.cypress.io/guides/tooling/reporters.html#Reporter-Options) that customize their behavior
```
Comment (jennifer-shehane) [inline cli/types/cypress.d.ts:2356]: Use quicklink as this link could go stale

```suggestion
     * Some reporters accept [reporterOptions](https://on.cypress.io/reporters) that customize their behavior
```

File: cli/types/cypress.d.ts [hunk 3]
```diff
@@ -2353,8 +2353,13 @@ declare namespace Cypress {
...
     /**
-     * Whether to take a screenshot on test failure when running headlessly or in CI
-     * @default true
+     * Some reporters accept [reporterOptions](https://on.cypress.io/reporters) that customize their behavior
+     * @default "spec"
+     */
+    reporterOptions: { [key: string]: any }
+    /**
+     * Customize reporter behavior by passing options
+     * @default null
```
Comment (jennifer-shehane) [inline cli/types/cypress.d.ts:2362]: Actually, this description is for `watchForFileChanges` below and has been incorrect for a while apparently. 

```suggestion
     * Whether Cypress will watch and restart tests on test file changes
     * @default true
```

**Comment by jennifer-shehane** [comment]
I'm going to merge this in - the build keeps failing for irrelevant reasons due to develop/5.0 release.
