### PR TITLE
fix: allow cypress config.port to override devServer.port for proxying assets

### LINKED ISSUE #27675: Setting port on cypress config does not propagate to component devServers
### Current behavior

When `config.port` is set and `devServer.port` is set Cypress opens it will open on the `devServer.port` but will not be able to proxy requests to the devServer.

### Desired behavior

Cypress should open on 9999 and be able to proxy requests into the component devServer.

### Test code to reproduce

```js
// cypress.config.js
module.exports = {
  port: 9999,
  component: {
    devServer: {
       bundler: 'webpack',
       framework: '...',
       webpackConfig: {
          port: 8888
       }
    }
  }
}

### Cypress Version

12.17.4

### Node version

default

### Operating System

all

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by brian-mann**
- Closes #27675

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/vite-dev-server/src/resolveConfig.ts [hunk 1]
```diff
@@ -122,6 +125,7 @@ function makeCypressViteConfig (config: ViteDevServerConfig, vite: Vite): Inline
           vite.searchForWorkspaceRoot?.(process.cwd()),
         ],
       },
+      port: vitePort,
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/resolveConfig.ts:128]: Could just be `port` - if `port` is provided, it's a number, otherwise it'll be undefined. No need for the `vitePort` variable

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts [hunk 2]
```diff
@@ -106,6 +109,7 @@ export function makeCypressWebpackConfig (
     return {
       ...finalConfig,
       devServer: {
+        port: webpackDevServerPort,
```
Comment (lmiller1990) [inline npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts:112]: Again just `port` is okay, but this is more explicit

File: packages/data-context/src/data/ProjectLifecycleManager.ts [hunk 3]
```diff
@@ -240,6 +240,11 @@ export class ProjectLifecycleManager {
 
           const devServerOptions = await this.ctx._apis.projectApi.getDevServer().start({ specs: this.ctx.project.specs, config: finalConfig })
 
+          // if we received a cypressConfig.port we want to null it out
+          // because we propagated it into the devServer.port and it is
+          // later set as baseUrl which cypress is launched into
```
Comment (lmiller1990) [inline packages/data-context/src/data/ProjectLifecycleManager.ts:245]: May be worth adding a link to the issue that explain this

File: system-tests/lib/normalizeStdout.ts [hunk 4]
```diff
@@ -114,7 +115,7 @@ export const normalizeStdout = function (str: string, options: any = {}) {
 
   // remove all of the dynamic parts of stdout
   // to normalize against what we expected
-  str = str
+  str = stripAnsi(str)
```
Comment (lmiller1990) [inline system-tests/lib/normalizeStdout.ts]: How come we need to change this to stripAnsi here

**Review by lmiller1990 — APPROVED** [review]

**Comment by mschile** [comment]
Would a user ever have another service running that is expecting the `devServer` to be at the `port` defined in the `devServer` config? Would if make more sense to throw an error if there are conflicting values?

File: npm/vite-dev-server/src/resolveConfig.ts (hunk 1 above)
Comment (brian-mann) [reply npm/vite-dev-server/src/resolveConfig.ts:128]: No it’s needed because of types. Cypress provided types are number or null. Vite is number or undefined. Switch it and it’ll yell at you.

File: npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts (hunk 2 above)
Comment (brian-mann) [reply npm/webpack-dev-server/src/makeDefaultWebpackConfig.ts:112]: Types problem without coercing to undefined

File: system-tests/project-fixtures/react/cypress-vite.config.ts [hunk 5]
```diff
@@ -9,12 +10,25 @@ declare global {
   }
 }
 
+const port = 8888
+
+const viteConfig = require('./webpack.config.js')
```
Comment (AtofStryker) [inline system-tests/project-fixtures/react/cypress-vite.config.ts]: @mschile did you mean to require the webpack config here?

File: system-tests/project-fixtures/react/cypress-vite.config.ts [hunk 6]
```diff
@@ -9,12 +10,25 @@ declare global {
...
+
+viteConfig.server ??= {}
```
Comment (AtofStryker) [inline system-tests/project-fixtures/react/cypress-vite.config.ts:17]: does this have the same effect as `viteConfig.server = viteConfig.server ?? {}`?

File: system-tests/project-fixtures/react/cypress-vite.config.ts (hunk 5 above)
Comment (mschile) [reply system-tests/project-fixtures/react/cypress-vite.config.ts]: No, that's what I get for changing it right at the end. Updated to vite. [0bda09b](https://github.com/cypress-io/cypress/pull/27677/commits/0bda09bf8d9a2fea81a013a150e57defe44f7c74)

File: system-tests/project-fixtures/react/cypress-vite.config.ts (hunk 6 above)
Comment (mschile) [reply system-tests/project-fixtures/react/cypress-vite.config.ts:17]: Yes, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment

File: system-tests/test/vite_dev_server_fresh_spec.ts [hunk 7]
```diff
@@ -18,11 +19,18 @@ describe('@cypress/vite-dev-server', function () {
           browser: 'chrome',
           snapshot: true,
           expectedExitCode: 7,
-          onStdout: (stdout) => {
-            return stdout.replace(/http:\/\/localhost:\d+/g, 'http://localhost:xxxx')
-          },
         })
       })
+
+      systemTests.it.only(`executes all of the tests for ${project} when port is statically configured`, {
```
Comment (AtofStryker) [inline system-tests/test/vite_dev_server_fresh_spec.ts]:
```suggestion
      systemTests.it(`executes all of the tests for ${project} when port is statically configured`, {
```

Comment (AtofStryker) [reply system-tests/test/vite_dev_server_fresh_spec.ts]: CI looks to be complaining about it

**Comment by lmiller1990** [comment]
> Would a user ever have another service running that is expecting the `devServer` to be at the `port` defined in the `devServer` config? Would if make more sense to throw an error if there are conflicting values?

Just to clarify are you suggesting we check if the `port` is available that the user asked for, and if it's not, we error instead of auto increment (this is what vite/webpack seem to do).

**Review by ryanthemanuel — APPROVED** [review]

File: system-tests/project-fixtures/react/cypress-vite-default.config.ts [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+declare global {
+  namespace Cypress {
+    interface DefineDevServerConfig {
+      viteConfig?: vite.UserConfig
+    }
+  }
+}
+
+export default defineConfig({
+  videoCompression: false, // turn off video compression for CI
```
Comment (mschile) [inline system-tests/project-fixtures/react/cypress-vite-default.config.ts:14]: Probably not needed since it's off by default.

```suggestion
export default defineConfig({
```

**Review by mschile — APPROVED** [review]
