### PR TITLE
fix: properly detect `cy.intercept(url, routeMatcher, handler)` overload

### LINKED ISSUE #16117: Unexpected error when stubbing a request with `cy.intercept(string, { headers: {} })`
### Current behavior

In Cypress 7, the `cy.intercept(url, routeMatcher)` overload was added. Now, when doing the following:

```
cy.intercept('/url', { headers: { foo: 'bar' }, body: '' })
```

or a variation, you get the following error:

> When invoking cy.intercept() with a RouteMatcher as the second parameter, a handler (function or StaticResponse) must be specified as the third parameter. If you intended to stub out a response body by passing an object as the 2nd parameter, pass an object with a body property containing the desired response body instead.

image

Obviously this is not quite the case, since the object DOES have a `body` property.

### Desired behavior

2nd argument is treated as StaticResponse in this case

This check: `      if (_.isString(matcher) && hasRouteMatcherKeys(handler)) {` should probably do `hasONLYRouteMatcherKeys(handler)` to avoid this problem.

### Versions

Cypress 7.0.0

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #16117

### User facing changelog

- Fixed an issue in 7.0 where users could get a misleading "must pass a handler as the 3rd argument" error when using `cy.intercept`.
- Improved types for `cy.intercept()`.

### PR Tasks

- [na] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/net-stubbing/add-command.ts [hunk 1]
```diff
@@ -19,14 +19,17 @@ import {
...
-  hasRouteMatcherKeys,
 } from './static-response-utils'
 import { registerEvents } from './events'
 import $errUtils from '../../cypress/error_utils'
 import $utils from '../../cypress/utils'
 
 const lowercaseFieldNames = (headers: { [fieldName: string]: any }) => _.mapKeys(headers, (v, k) => _.toLower(k))
 
+export function hasOnlyRouteMatcherKeys (obj: any) {
+  return !_.isEmpty(obj) && !_.isArray(obj) && _.isEmpty(_.omit(obj, _.concat(PLAIN_FIELDS, STRING_MATCHER_FIELDS, DICT_STRING_MATCHER_FIELDS)))
```
Comment (Bkucera) [inline packages/driver/src/cy/net-stubbing/add-command.ts:30]: will this be truthy if obj is a function?

Comment (flotwig) [reply packages/driver/src/cy/net-stubbing/add-command.ts:30]: like this?

```js
cy.intercept('/url', () => {})
cy.intercept('/url', function () {})


nope, see `net_stubbing_spec` for examples of such usage

**Review by Bkucera — APPROVED** [review]
great
