### PR TITLE
docs: Fix config option example typo in tooltip

### LINKED ISSUE #28173: Wrong spelling for `viewportWidth` configuration option example in `defineConfig()` tooltip in VSCode
### Current behavior

When I hover over the `defineConfig()` function located in the file **cypress.config.js** it shows a tooltip with the definition and example of using the function.
In the example it uses the configuration option of `viewportWidth: 400`
However, there is a typo and it is written as `viewportWith` rather than `viewportWidth` (letter 'd' is missing).

defineConfigTooltip

### Desired behavior

It should display as:
```
module.exports = defineConfig({
  viewportWidth: 400
})
```

### Test code to reproduce

```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

### Cypress Version

13.3.3

### Node version

v20.9.0

### Operating System

Linux Mint 21.2

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by LeggoTM**
- Closes https://github.com/cypress-io/cypress/issues/28173

### Additional details
Fix typo of `viewportWith: 400` to `viewportWidth: 400` in the **cypress-npm-api.d.ts** file.

### Steps to test

- Create a new cypress project
- Open cypress.config,js file in VSCode
- Hover over the defineConfig() function

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]

File: cli/types/cypress-npm-api.d.ts [hunk 1]
```diff
@@ -382,7 +382,7 @@ declare module 'cypress' {
      * recommend wrapping your config object with `defineConfig()`
      * @example
      * module.exports = defineConfig({
-     *   viewportWith: 400
+     *   viewportWidth: 400
```
Comment (emilyrohrbough) [inline cli/types/cypress-npm-api.d.ts]:
```suggestion
     *    viewportWidth: 400
```
