### PR TITLE
fix(ui): improve "Routes" display for cy.intercept

### LINKED ISSUE #9403: "Routes" display does not provide details on non-`url` RouteMatchers
### Current behavior

The "Routes" UI is designed for `cy.route` still, so in the case that there is no `url` for a RouteMatcher, it will display `*`, which is not useful:

image

### Desired behavior

`RouteMatcher`s are accurately depicted in "Routes".

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #9403

### User facing changelog

- Improved the way that `cy.intercept` matchers are displayed in the command log when using RouteMatcher properties besides `url` and `method`.

### Additional details

- [x] should we rename the column from 'Url' to something else? `Matcher`? `RouteMatcher/URL`? `Matcher (RouteMatcher, url, etc...)`?

### How has the user experience changed?

Compared to #9403, now routes that use non-url properties are displayed in a better way

image

See unit tests for more examples of stringification:

https://github.com/cypress-io/cypress/blob/d85db41b8526ae2947c661a7edb07af43ec59582/packages/driver/cypress/integration/commands/net_stubbing_spec.ts#L3244-L3258

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@flotwig Yah the header should likely be changed, it should make sense with all the examples below. I think currently it's a little weird, although not completely unclear like before. I think `RouteMatcher` would make sense to replace 'Url'.

```js
cy.intercept('/users/**')
cy.intercept('GET', '/users*')
cy.intercept({ method: 'get', url: '/users*', hostname: 'localhost' })
```

#### Before

Screen Shot 2021-05-11 at 2 42 01 PM


#### After

Screen Shot 2021-05-11 at 2 44 42 PM

**Comment by jennifer-shehane** [comment]
Yah, "Route Matcher" seems ok. It's not a perfect solution, but it's better than 'URL'.

File: packages/driver/src/cy/net-stubbing/route-matcher-log.ts [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+import {
+  RouteMatcherOptions,
+  StaticResponse,
+} from '@packages/net-stubbing/lib/types'
+import $utils from '../../cypress/utils'
+
+// properties that, if they are the only ones set, make sense to display as the display url
+const standaloneDisplayUrlProps: Array<keyof RouteMatcherOptions> = ['url', 'path', 'pathname']
+
+export function _getDisplayUrlMatcher (matcher: RouteMatcherOptions): string {
```
Comment (chrisbreiding) [inline packages/driver/src/cy/net-stubbing/route-matcher-log.ts:12]: Prefixing a function name with an underscore should indicate that it's a private function. I'd suggest removing the underscore, since an exported function is not private.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]
Other than the one nitpick, looks good to me!

File: packages/driver/src/cy/net-stubbing/route-matcher-log.ts (hunk 1 above)
Comment (flotwig) [reply packages/driver/src/cy/net-stubbing/route-matcher-log.ts]: I've seen the underscore notation used elsewhere in our codebase to denote something that is only exported for use in tests, but I guess not in the `driver` as much. Updated.

Comment (chrisbreiding) [reply packages/driver/src/cy/net-stubbing/route-matcher-log.ts]: I've certainly done that before, but I think the distinction is that the function needs to not just be exported only for the test, but it also should only be _used_ in the test. Since this function is actually utilized outside of a test, it doesn't meet that criteria.

For example, I know I have added a `__reset` method to a singleton so that its state can be reset or to reset global state, since there's no other way to accomplish it, but it's only used in the test and not in the standard execution of the code. So it's basically using an anti-pattern to compensate for an anti-pattern 😅. With newer code, I think we're better about not creating singletons or global state, so hopefully it's not as necessary.

**Review by chrisbreiding — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@flotwig Did you have percy snapshots to approve for this? Just wondering if they're running correctly because this should have updated at least one snapshot I would think.

**Comment by flotwig** [comment]
> @flotwig Did you have percy snapshots to approve for this? Just wondering if they're running correctly because this should have updated at least one snapshot I would think.

@jennifer-shehane There was 1 snapshot update, I'm not sure if someone already approved it or if it's gonna appear soon...

**Comment by chrisbreiding** [comment]
There was one. I approved it as it looked like the right change.

**Comment by chrisbreiding** [comment]
You can see it here: https://percy.io/cypress-io/cypress/builds/10388025/changed/584634301?browser=chrome&browser_ids=16&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=400&widths=400
