### PR TITLE
Move stack trace below code frame in runner

### LINKED ISSUE #7563: Move stack trace to below code frame
- Below the code frame should be a div where View Stack Trace accordion will live
  - The div will be split for View Stack Trace and Print to Console
    - The View Stack Trace area will take up the majority of the row of the div
  - View Stack Trace will appear on the left side of the div
    - Hover state background color should be #fee0e3
  - Print to console will appear on the right side
    - Remove tooltip on print to console icon that exists currently
    - Hover state background color should be #fee0e3
  - Background color of the div should be #ffeaec

Desired results:

Screen Shot 2020-06-02 at 12 55 03 AM

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7563

### User facing changelog

Moves the location of the stack trace and print to console button to below the code frame in an error message

### How has the user experience changed?

Before:
Screen Shot 2020-06-02 at 7 02 05 PM

After:
Screen Shot 2020-06-03 at 12 51 01 AM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2853

### CODE REVIEW

File: packages/reporter/src/collapsible/collapsible.tsx [hunk 1]
```diff
@@ -5,9 +5,11 @@ import { onEnterOrSpace } from '../lib/util'
 
 interface Props {
   isOpen?: boolean
+  headerWrapperClass?: string
```
Comment (chrisbreiding) [inline packages/reporter/src/collapsible/collapsible.tsx:8]: Instead of adding a separate `headerWrapperClass` prop, let's only use the `headerClass` and move it to the wrapper. Then any usage that needs to target the 'header' in css can use `.<headerClass> .collapsible-header`.

Comment (panzarino) [reply packages/reporter/src/collapsible/collapsible.tsx:8]: @chrisbreiding I tried to accomplish something like this, but I was struggling because I need to apply different styles to the wrapper and where the existing header is. The only style needed for the wrapper is `display: flex`, but when this is applied it causes some slight display differences with other collapsible. Alternatively, I think the best option might be to apply `display: flex` to the wrapper no matter what, and easily update the styles for other collapsibles so that they play nicely with this wrapper.
