### PR TITLE
fix: improve memory management for chromium-based browsers

### LINKED ISSUE #23391: Out of memory issue after update a browsers to version 104+ (Chrome&Edge)
### Current behavior

We have configured build to run UI tests on both Edge and Chrome browsers.
Last time I noticed that on Edge test are not executed and finished after 6h (pipeline timeout).
Now we have the same situation on Chrome, that test are not executed.
Without any error/log etc.

What interesting both starting to timeout after update Edge from version 103 to 104 and Chrome from version 103 to 104.
No any code changes between update from 103 to 104, so same code base failing after update to 104.

I run it locally and always have "Out of memory" issue screen during execution. --headed flag added to investigate
I try it on different versions, and always have same issue.

### Desired behavior

Same code should working on browsers version 103 and 104.

### Test code to reproduce

No any code, test are not running, because of out of memory issue.

### Cypress Version

 9.3.1, 9.7.0, 10.0

### Node version

16.16.0

### Operating System

Windows Azure Virtual Machine

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #23391

### User facing changelog

* Added new `experimentalMemoryManagement` flag to improve memory management in Chromium-based browsers.

### Additional details

Algorithm:
 
 * When the test run starts:
    1. set total mem limit for the container/host by reading off cgroup memory limits (if available) otherwise use os.totalmem()
    2. turn on memory profiler
 
 * On a defined interval (e.g. 1s):
    1. set current mem available for the container/host by reading off cgroup memory usage (if available) otherwise use si.mem().available
    3. set current renderer mem usage
    4. set max avail render mem to minimum of v8 heap size limit and total available mem (current available mem + current renderer mem usage)
    5. calc % of memory used, current renderer mem usage / max avail render mem
 
 * Before each test:
    1. if any interval exceeded the defined memory threshold, then do a GC prior in between running the next test
 * After the test run ends:
     1. turn off memory profiler

Since the manual GC is run before each test, if a single test consumes enough memory, it is still possible to reach an OOM scenario.

### Steps to test

Run a spec that consumes enough memory to cause an OOM error and then turn on the experimental flag and verify the spec now passes.

### How has the user experience changed?

Ran the following spec on Chromium 107 in run mode:

```
describe('memory', () => {
  for (let index = 0; index < 200; index++) {
    it(`test ${index + 1}`, () => {
      cy.visit('https://earth.google.com/web/')
    })
  }
})
```

Before (OOM crash at test 85):
Screen Shot 2023-01-13 at 12 05 42 PM

After (No OOM crash):
Screen Shot 2023-01-13 at 12 03 06 PM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/electron.ts [hunk 1]
```diff
@@ -471,14 +474,14 @@ export = {
...
-   * Clear instance state for the electron instance, this is normally called in on kill or on exit for electron there isn't state to clear.
+   * Clear instance state for the electron instance, this is normally called on kill or on exit, for electron there isn't any state to clear.
    */
   clearInstanceState () {},
 
   async connectToNewSpec (browser: Browser, options: ElectronOpts, automation: Automation) {
     if (!options.url) throw new Error('Missing url in connectToNewSpec')
 
-    await this.open(browser, options.url, options, automation)
+    return await this.open(browser, options.url, options, automation)
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/electron.ts]:
```suggestion
    return this.open(browser, options.url, options, automation)
```

File: packages/server/lib/browsers/index.ts [hunk 2]
```diff
@@ -124,8 +124,13 @@ export = {
   async connectToNewSpec (browser: Browser, options: BrowserNewTabOpts, automation: Automation): Promise<BrowserInstance | null> {
     const browserLauncher = await getBrowserLauncher(browser, options.browsers)
 
-    // Instance will be null when we're dealing with electron. In that case we don't need a browserCriClient
-    await browserLauncher.connectToNewSpec(browser, options, automation)
+    const newInstance = await browserLauncher.connectToNewSpec(browser, options, automation)
+
+    // if a new instance was returned, update our instance to use the new one
+    if (newInstance) {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/index.ts:130]: use _setInstance()?

File: packages/driver/cypress/e2e/commands/sessions/sessions.cy.js [hunk 3]
```diff
@@ -59,7 +59,7 @@ describe('cy.session', { retries: 0 }, () => {
         .then(async () => {
           cy.spy(Cypress, 'action').log(false)
 
-          await Cypress.action('runner:test:before:run:async', {})
+          await Cypress.action('runner:test:before:run:async', {}, Cypress.state('test'))
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/commands/sessions/sessions.cy.js]: need this change?

File: packages/server/lib/browsers/memory/cgroup-v1.ts [hunk 4]
```diff
@@ -0,0 +1,47 @@
+import { exec } from 'child_process'
+import util from 'util'
+
+const execAsync = util.promisify(exec)
+
+const getTotalMemoryLimit = async () => {
+  return Number((await execAsync('cat /sys/fs/cgroup/memory/memory.limit_in_bytes', { encoding: 'utf8' })).stdout)
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/cgroup-v1.ts:11]: are these paths the same on all machines? seeing similar paths throughout the file

Comment (mschile) [reply packages/server/lib/browsers/memory/cgroup-v1.ts:11]: I believe for Linux cgroup v1 they are.

File: packages/driver/cypress/e2e/commands/sessions/sessions.cy.js (hunk 3 above)
Comment (mschile) [reply packages/driver/cypress/e2e/commands/sessions/sessions.cy.js]: Some of the test details are now used, thus, these tests needed to pass the test to the action.

Comment (emilyrohrbough) [reply packages/driver/cypress/e2e/commands/sessions/sessions.cy.js]: I'm only seeing changes in this file around `runner:test:before:run:async`, are we passing this in other places already?

File: packages/server/lib/browsers/index.ts (hunk 2 above)
Comment (mschile) [reply packages/server/lib/browsers/index.ts:130]: Hmm, the rest of the file doesn't use the `_setInstance()` function, presumably because it was just exposed for testing.

File: packages/errors/src/errors.ts [hunk 5]
```diff
@@ -601,8 +601,12 @@ export const AllCypressErrors = {
...
         - You wrote an endless loop and you must fix your own code
         - You are running Docker (there is an easy fix for this: see link below)
-        - You are running lots of tests on a memory intense application
-        - You are running in a memory starved VM environment
+        - You are running lots of tests on a memory intense application.
+            - Try enabling ${fmt.highlight('experimentalMemoryManagement')} in your config file.
+            - Try lowering ${fmt.highlight('numTestsKeptInMemory')} in your config file.
+        - You are running in a memory starved VM environment.
+            - Try enabling ${fmt.highlight('experimentalMemoryManagement')} in your config file.
+            - Try lowering ${fmt.highlight('numTestsKeptInMemory')} in your config file.
```
Comment (mjhenkes) [inline packages/errors/src/errors.ts:609]: Nice, i hope this messaging helps raise awareness of this feature.

File: packages/server/lib/browsers/chrome.ts [hunk 6]
```diff
@@ -119,6 +120,9 @@ const DEFAULT_ARGS = [
   // write shared memory files into '/tmp' instead of '/dev/shm'
   // https://github.com/cypress-io/cypress/issues/5336
   '--disable-dev-shm-usage',
+
+  // enable precise memory info so performance.memory returns more accurate values
+  '--enable-precise-memory-info',
```
Comment (mjhenkes) [inline packages/server/lib/browsers/chrome.ts:125]: should/can we enable this based on the experimental flag?

Comment (mschile) [reply packages/server/lib/browsers/chrome.ts:125]: I believe we could, I don't think it's really worth it though.

Comment (mjhenkes) [reply packages/server/lib/browsers/chrome.ts:125]: Theres no cost to enabling the flag?

File: packages/server/lib/browsers/chrome.ts [hunk 7]
```diff
@@ -608,9 +612,11 @@ export = {
     const browserCriClient = this._getBrowserCriClient()
 
     // Handle chrome tab crashes.
-    pageCriClient.on('Inspector.targetCrashed', () => {
+    pageCriClient.on('Inspector.targetCrashed', async () => {
       const err = errors.get('RENDERER_CRASHED')
 
+      await memory.endProfiling()
```
Comment (mjhenkes) [inline packages/server/lib/browsers/chrome.ts:618]: Here is another place where we handle the browser crashing (the whole thing, not just the tab), should we end profiling here too?

https://github.com/cypress-io/cypress/blob/e973fa3901bbf22cdab323b91c19f11816fbefcd/packages/server/lib/browsers/index.ts#L182-L194

File: packages/server/lib/browsers/memory/cgroup-v1.ts [hunk 8]
```diff
@@ -0,0 +1,47 @@
+import { exec } from 'child_process'
+import util from 'util'
+
+const execAsync = util.promisify(exec)
+
+const getTotalMemoryLimit = async () => {
```
Comment (mjhenkes) [inline packages/server/lib/browsers/memory/cgroup-v1.ts:10]: For these new 'memory' files, could you go through and add code comments and js doc for the functions? I'm sure theres context currently in your head that would help us manage and understand these methods in the future.

File: packages/server/lib/browsers/chrome.ts (hunk 6 above)
Comment (mschile) [reply packages/server/lib/browsers/chrome.ts:125]: The memory information is updated more often but I haven't noticed any impact on performance.

File: packages/server/lib/browsers/memory/index.ts [hunk 9]
```diff
@@ -0,0 +1,293 @@
...
+ * Algorithm:
+ *
+ * When the test runs starts:
+ *   1. set total mem limit for the container/host by reading off cgroup memory limits (if available) otherwise use os.totalmem()
+ *
+ * On a defined interval (e.g. 1s):
+ *   1. set current mem available for the container/host by reading off cgroup memory usage (if available) otherwise use si.mem().available
+ *   2. set current renderer mem usage
+ *   3. set max avail render mem to minimum of v8 heap size limit and total available mem (current available mem + current renderer mem usage)
+ *   4. calc % of memory used, current renderer mem usage / max avail render mem
```
Comment (mjhenkes) [inline packages/server/lib/browsers/memory/index.ts:54]: Should we add a step to do an emergency GC during the test if the memory threshold exceeds a higher percent something like 95%?

File: packages/app/src/runner/event-manager.ts [hunk 10]
```diff
@@ -569,8 +581,13 @@ export class EventManager {
       this.localBus.emit('script:error', err)
     })
 
-    Cypress.on('test:before:run:async', (_attr, test) => {
+    Cypress.on('test:before:run:async', async (_attr, test) => {
       this.studioStore.interceptTest(test)
+
+      // if the experimental flag is on and we are in a chromium based browser, determine if garbage collection is needed
+      if (Cypress.config('experimentalMemoryManagement') && Cypress.isBrowser({ family: 'chromium' })) {
+        await Cypress.backend('maybe:collect:garbage', { test: { title: test.title, order: test.order, currentRetry: test.currentRetry() } })
```
Comment (mjhenkes) [inline packages/app/src/runner/event-manager.ts]: How about `request:collect:garbage`, because requests can be denied

```suggestion
        await Cypress.backend('request:collect:garbage', { test: { title: test.title, order: test.order, currentRetry: test.currentRetry() } })
```

or focus less on the outcome? `check:memory:pressure` and if that pressure happens to be high also GC?
```suggestion
        await Cypress.backend('check:memory:pressure', { test: { title: test.title, order: test.order, currentRetry: test.currentRetry() } })
```

🤷‍♂️ , i dunno just not a fan of maybe statements.

File: .circleci/workflows.yml [hunk 11]
```diff
@@ -1357,6 +1357,40 @@ jobs:
...
+      <<: *defaultsParameters
+      resource_class:
+        type: string
+        default: medium
+    resource_class: << parameters.resource_class >>
+    parallelism: 1
+    steps:
+      - restore_cached_workspace
+      - run:
+          name: Run memory tests in Cypress
```
Comment (emilyrohrbough) [inline .circleci/workflows.yml]:
```suggestion
          name: Driver memory tests in Electron
```

File: packages/server/lib/browsers/memory/index.ts [hunk 12]
```diff
@@ -73,8 +82,13 @@ const measure = (func: (...args) => any, opts: { name?: string, save?: boolean }
   }
 }
 
-export const getJsHeapSizeLimit = measure(async (automation: Automation): Promise<number> => {
-  let heapLimit
+/**
+ * Retrieves the JS heap size limit for the browser.
+ * @param automation the automation client to use
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]:
```suggestion
 * @param automation - the automation client to use
```

File: packages/server/lib/browsers/memory/index.ts [hunk 13]
```diff
@@ -103,13 +120,21 @@ export const getMemoryHandler = async (): Promise<MemoryHandler> => {
   return (await import('./default')).default
 }
 
+/**
+ * Attempts to find the browser's renderer process running the Cypress tests.
+ * @param processes all of the system processes
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]:
```suggestion
 * @param processes - all of the system processes
```

File: packages/server/lib/browsers/memory/index.ts [hunk 14]
```diff
@@ -120,7 +145,13 @@ const findRendererProcess = (processes: si.Systeminformation.ProcessesData) => {
   return maxRendererProcess
 }
 
+/**
+ * Retrieves the memory usage for the renderer process.
+ * @returns the memory usage for the renderer process or null if there is no renderer process
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]:
```suggestion
 * @returns the memory usage in bytes for the renderer process or null if there is no renderer process
```

File: packages/server/lib/browsers/memory/index.ts [hunk 15]
```diff
@@ -130,25 +161,38 @@ export const getRendererMemoryUsage: () => Promise<number | null> = measure(asyn
...
+    // assume it's gone and clear it out so we can find it again
     rendererProcess = null
 
     return getRendererMemoryUsage()
   }
 }, { name: 'getRendererMemoryUsage', save: true })
 
+/**
+ * Retrieves the available memory for the container/host.
+ * @returns the available memory for the container/host
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]: this also in bytes?

File: packages/server/lib/browsers/memory/index.ts [hunk 16]
```diff
@@ -130,25 +161,38 @@ export const getRendererMemoryUsage: () => Promise<number | null> = measure(asyn
...
+ */
 export const getAvailableMemory: () => Promise<number> = measure(() => {
   return handler.getAvailableMemory(totalMemoryLimit, statsLog)
 }, { name: 'getAvailableMemory', save: true })
 
+/**
+ * Calculates the memory stats used to determine if garbage collection should be run.
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]:
```suggestion
 * Calculates the memory stats used to determine if garbage collection should be run before the next test starts.
```

File: packages/server/lib/browsers/memory/index.ts [hunk 17]
```diff
@@ -160,84 +204,130 @@ export const gatherMemoryStats: () => Promise<void> = measure(async () => {
...
 
   addCumulativeStats(gcLog)
+
+  // clear the flag so we don't collect garbage on every test
+  collectGarbageOnNextTest = false
 }
 
-const maybeCollectGarbage = measure(async ({ automation }: { automation: Automation }) => {
+/**
+ * Collects garbage if needed.
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]:
```suggestion
 * Collects the browser's garbage if it previously exceeded the threshold when it was measured.
```

File: packages/server/lib/browsers/memory/index.ts [hunk 18]
```diff
@@ -160,84 +204,130 @@ export const gatherMemoryStats: () => Promise<void> = measure(async () => {
...
+ */
 async function startProfiling (automation: Automation, spec: { fileName: string }) {
   if (started) {
     return
   }
 
   debugVerbose('start memory profiler')
 
+  // ensure we are starting from a clean state
   reset()
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]: In open mode, is this correctly reset when switching between e2e and component testing and a new browser is launched?

File: packages/server/lib/browsers/memory/index.ts [hunk 19]
```diff
@@ -160,84 +204,130 @@ export const gatherMemoryStats: () => Promise<void> = measure(async () => {
...
 
+/**
+ * Adds the memory stats to the cumulative stats.
+ * @param stats memory stats to add to the cumulative stats
+ */
 const addCumulativeStats = (stats: { [key: string]: any }) => {
   debugVerbose('memory stats: %o', stats)
 
-  if (['1', 'true'].includes(process.env.CYPRESS_INTERNAL_SAVE_MEMORY_STATS as string)) {
+  if (['1', 'true'].includes(process.env.CYPRESS_INTERNAL_SAVE_MEMORY_STATS?.toLowerCase() as string)) {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/memory/index.ts]: This is used twice...Set as a const at the top?

```
const saveMemoryStats = ['1', 'true'].includes(process.env.CYPRESS_INTERNAL_SAVE_MEMORY_STATS?.toLowerCase() as string)
```

File: packages/server/lib/browsers/chrome.ts (hunk 7 above)
Comment (mschile) [reply packages/server/lib/browsers/chrome.ts:618]: Updated to listen for the `exit` event and end profiling there. [d0daff0](https://github.com/cypress-io/cypress/pull/25462/commits/d0daff04839e9229a9bb9a1f250473a46a4f07eb)

File: packages/server/lib/browsers/memory/cgroup-v1.ts (hunk 8 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/cgroup-v1.ts:10]: added documentation: [5507f19](https://github.com/cypress-io/cypress/pull/25462/commits/5507f19535d97bd0e67db3a69ce6688b62f11eef)

File: packages/app/src/runner/event-manager.ts (hunk 10 above)
Comment (mschile) [reply packages/app/src/runner/event-manager.ts]: I'm fine with using `maybe` as it matches other functions within the codebase but if others want it changed, I'm fine with updating it.

File: packages/server/lib/browsers/memory/index.ts (hunk 12 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: The formatting is automatically applied (at least in VSCode):
Screen Shot 2023-01-17 at 8 58 45 AM

File: packages/server/lib/browsers/memory/index.ts (hunk 19 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: updated: [47476a6](https://github.com/cypress-io/cypress/pull/25462/commits/47476a6574205785f10484cfc32d38f2859d3f6a)

File: packages/server/lib/browsers/memory/index.ts (hunk 15 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: Yep, updated: [47476a6](https://github.com/cypress-io/cypress/pull/25462/commits/47476a6574205785f10484cfc32d38f2859d3f6a)

File: packages/server/lib/browsers/memory/index.ts (hunk 12 above)
Comment (emilyrohrbough) [reply packages/server/lib/browsers/memory/index.ts]: what view is this?

Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: Hovering over the function

Comment (emilyrohrbough) [reply packages/server/lib/browsers/memory/index.ts]: I must not have this extension or configured? I was just taking from reading through it. It's a nit really but makes it easier to read IMO

Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: updated [6541f7d](https://github.com/cypress-io/cypress/pull/25462/commits/6541f7dfdc7b4fd8e90e99734358c01a2fee4fea)

File: packages/server/lib/browsers/memory/index.ts (hunk 13 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: updated [6541f7d](https://github.com/cypress-io/cypress/pull/25462/commits/6541f7dfdc7b4fd8e90e99734358c01a2fee4fea)

File: packages/driver/cypress/e2e/commands/sessions/sessions.cy.js (hunk 3 above)
Comment (mschile) [reply packages/driver/cypress/e2e/commands/sessions/sessions.cy.js]: Yes, Cypress code passes the `runnable`. Updated to `runnable` instead of `test` https://github.com/cypress-io/cypress/pull/25462/commits/c90abe77a969469ca8ed7a039441c10f28c05f35

File: packages/server/lib/browsers/electron.ts (hunk 1 above)
Comment (mschile) [reply packages/server/lib/browsers/electron.ts]: Updated https://github.com/cypress-io/cypress/pull/25462/commits/c90abe77a969469ca8ed7a039441c10f28c05f35

File: packages/server/lib/browsers/memory/index.ts (hunk 18 above)
Comment (mschile) [reply packages/server/lib/browsers/memory/index.ts]: Yes, it resets correctly when switching between modes.

File: packages/server/lib/environment.js [hunk 20]
```diff
@@ -66,6 +66,9 @@ try {
   // https://github.com/cypress-io/cypress/pull/20271
   app.commandLine.appendSwitch('disable-ipc-flooding-protection')
 
+  // ensure we get the most accurate memory usage
+  app.commandLine.appendSwitch('enable-precise-memory-info')
```
Comment (emilyrohrbough) [inline packages/server/lib/environment.js:70]: Should we only enable this launch option when when the experiment is enabled?

Comment (mschile) [reply packages/server/lib/environment.js:70]: This was discussed here: https://github.com/cypress-io/cypress/pull/25462#discussion_r1070018967

File: packages/app/src/runner/event-manager.ts [hunk 21]
```diff
@@ -540,6 +540,18 @@ export class EventManager {
       })
     })
 
+    Cypress.on('run:start', async () => {
+      if (Cypress.config('experimentalMemoryManagement') && Cypress.isBrowser({ family: 'chromium' })) {
+        await Cypress.backend('start:memory:profiling', Cypress.config('spec'))
```
Comment (emilyrohrbough) [inline packages/app/src/runner/event-manager.ts:545]: If this fails, we aren't logging anything to indicate something when wrong.Seems like something we should add server-side to ensure the full picture is available in the logs. The error is being swallowed here

Comment (mschile) [reply packages/app/src/runner/event-manager.ts:545]: There is a [debug](https://github.com/cypress-io/cypress/blob/mschile/chrome_memory_fix/packages/server/lib/browsers/memory/index.ts#L341) log that gets generated if it fails to start. Are you looking for something else?

Comment (emilyrohrbough) [reply packages/app/src/runner/event-manager.ts:545]: I guess this partially covers its - this try-catch is partially around the startProfiling implementation. There isn't any under endProfiling or maybeCollectMemory profiling though at the top level to ensure we don't accidentally bonk out.

Comment (mschile) [reply packages/app/src/runner/event-manager.ts:545]: Saving the file is the only thing that can fail in `endProfiling` and that is handled [here](https://github.com/cypress-io/cypress/blob/mschile/chrome_memory_fix/packages/server/lib/browsers/memory/index.ts#L354). I also catch potential errors when gathering the memory stats [here](https://github.com/cypress-io/cypress/blob/mschile/chrome_memory_fix/packages/server/lib/browsers/memory/index.ts#L289). I'll add something to `maybeCollectGarbage`.

Comment (mschile) [reply packages/app/src/runner/event-manager.ts:545]: updated [0a00475](https://github.com/cypress-io/cypress/pull/25462/commits/0a004751178122988dcc43ef6fecf70d9ae23dc7)

File: packages/app/src/runner/event-manager.ts (hunk 10 above)
Comment (mschile) [reply packages/app/src/runner/event-manager.ts]: renamed to `check:memory:pressure` [9e7ee14](https://github.com/cypress-io/cypress/pull/25462/commits/9e7ee14ed4b032d6dec6fc6f3e08b475de57ef32)

File: packages/server/lib/browsers/memory/index.ts (hunk 9 above)
Comment (mjhenkes) [reply packages/server/lib/browsers/memory/index.ts:54]: This probably requires more discussion and doesn't need to be addressed on this PR.

**Review by mjhenkes — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]
