### PR TITLE
fix: proxy issues with service workers and clean up at end of specs

### LINKED ISSUE #28054: Loading webassembly dlls is a lot slower after updating Cypress V13.3.0 to V13.3.1
### Current behavior

In our application we are generating and previewing pdf's and for this purpose we are using Webassembly .
I updated Cypress from V13.3.0 to V13.3.1
Getting the dll's needed from Webassembly takes a lot longer than before (on my local environment it takes 2000ms (V13.3.1) per dll instead of 500ms in V13.3.0)
(using chrome browser V118.0.5993.70 )

### Desired behavior

Updating to a higher version should not impact the performance of loading the Webassembly dlls

### Test code to reproduce

No specific test code to reproduce upgrading and downgrading from the stated versions results in the behaviour

### Cypress Version

13.3.1

### Node version

v16.20.0

### Operating System

Windows 10 Enterprise 10.0.1904b Build 19045

### Debug Logs

```shell
example with Cypress V13.3.0 getting some of these dlls:

GET /js/wasm/managed/System.Threading.Thread.dll 304 563.580 ms - -
GET /js/wasm/managed/System.Threading.ThreadPool.dll 304 563.870 ms - -
GET /js/wasm/managed/System.Threading.Timer.dll 304 564.543 ms - -
GET /js/wasm/managed/System.Threading.dll 304 562.591 ms - -

example with Cypress V13.3.1 getting same dlls:
GET /js/wasm/managed/System.Threading.Thread.dll 304 2049.957 ms - -
GET /js/wasm/managed/System.Threading.ThreadPool.dll 304 2066.895 ms - -
GET /js/wasm/managed/System.Threading.Timer.dll 304 2062.693 ms - -
GET /js/wasm/managed/System.Threading.dll 304 2063.532 ms - -
```

### Other

_No response_

### LINKED ISSUE #28056: Requests that are cached in service workers can be improperly correlated in the proxy
### Current behavior

It appears what's getting received here is:

**Browser**
Test 1
* Request for A - request normally made from document
* Request for B - request made from the service worker in order to cache (the way service workers work, you don't start using the cache until the next load of the site)
Test 2
* Request for C

**Proxy**
Test 1
* A
* B
Test 2 (Nothing. Since now everything is cached)

**CDP**
Test 1 (B doesn't arrive. Seems like service worker requests don't go through CDP)
* A
Test 2
* C

So B ends up timing out during the correlation phase.

### Desired behavior

We should either find a way to ignore requests that are being made from service workers in terms of correlation. Or we need to get the request information somewhere else.

### Cypress Version

13.3.1

### Node version

18.15.0

### Operating System

any

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28056
- Closes #28054 

### Additional details

This PR fixes a performance regression with proxy correlations and service workers. Specifically this PR:

* Ensures to track on CDP for service worker traffic (note that this only works in chrome - #28079)
  * This is done by attaching to service worker targets when they are spawned and then enabling Network traffic
* Clears service worker information in between specs (note that this was causing some problems where cached data would leak between specs in electron)
* Ensures that redirected requests that don't have expected CDP traffic (right now only downloads) have their redirects also respect the lack of expected CDP traffic

### Steps to test

Several system tests were added to cover the scenarios involved

### How has the user experience changed?

Performance should improve in scenarios where there are service workers

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by chrisbreiding — APPROVED** [review]

File: packages/server/lib/browsers/cri-client.ts [hunk 1]
```diff
@@ -252,6 +254,30 @@ export const create = async (
       debug('crash detected')
       crashed = true
     })
+
+    if (host) {
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/cri-client.ts:267]: Add a comment here on why we want to only do this if host is present.

File: packages/server/lib/project-base.ts [hunk 2]
```diff
@@ -436,6 +436,10 @@ export class ProjectBase extends EE {
   setCurrentSpecAndBrowser (spec, browser: FoundBrowser) {
     this.spec = spec
     this.browser = browser
+
+    if (this.browser.family !== 'chromium') {
+      this._server?.setPreRequestTimeout(500)
```
Comment (ryanthemanuel) [inline packages/server/lib/project-base.ts:443]:
```suggestion
      // If we're not in chromium, our strategy for correlating service worker prerequests doesn't work in non-chromium browsers (https://github.com/cypress-io/cypress/issues/28079)
      // in order to not hang for 2 seconds, we override the prerequest timeout to be 500 ms (which is what it has been historically)
      this._server?.setPreRequestTimeout(500)
```

File: packages/server/lib/browsers/cri-client.ts (hunk 1 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/cri-client.ts:267]:
```suggestion
    // We only want to try and add service worker traffic if we have a host set. This indicates that this is the child cri client.
    if (host) {
```

File: packages/server/lib/browsers/electron.ts [hunk 3]
```diff
@@ -307,7 +307,9 @@ export = {
         cdpSocketServer?.attachCDPClient(cdpAutomation),
         videoApi && recordVideo(cdpAutomation, videoApi),
         this._handleDownloads(win, options.downloadsFolder, automation),
-        await utils.handleDownloadLinksViaCDP(pageCriClient, automation),
+        utils.handleDownloadLinksViaCDP(pageCriClient, automation),
+        pageCriClient.send('Storage.clearDataForOrigin', { origin: '*', storageTypes: 'all' }),
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/electron.ts:312]:
```suggestion
        // Ensure to clear browser state in between runs. This is handled differently in browsers when we launch new tabs, but we don't have that concept in electron
        pageCriClient.send('Storage.clearDataForOrigin', { origin: '*', storageTypes: 'all' }),
```

File: packages/proxy/lib/http/response-middleware.ts [hunk 4]
```diff
@@ -656,6 +656,10 @@ const MaybeSendRedirectToClient: ResponseMiddleware = function () {
     return this.next()
   }
 
+  if (this.req.noPreRequestExpected) {
```
Comment (ryanthemanuel) [inline packages/proxy/lib/http/response-middleware.ts:660]: If we're redirecting from a request that doesn't expect to have a preRequest (e.g. download links), we need to treat the redirected url as such as well.

File: packages/proxy/lib/http/util/prerequests.ts [hunk 5]
```diff
@@ -196,6 +217,16 @@ export class PreRequests {
   }
 
   get (req: CypressIncomingRequest, ctxDebug, callback: GetPreRequestCb) {
+    if (req.headers['sec-fetch-dest'] === 'serviceworker') {
```
Comment (mschile) [inline packages/proxy/lib/http/util/prerequests.ts:223]: Suggest adding a comment here.

Comment (ryanthemanuel) [inline packages/proxy/lib/http/util/prerequests.ts:223]:
```suggestion
    // The initial request that loads the service worker does not get sent to CDP and it happens prior
    // to the service worker target being added. Thus, we need to explicitly ignore it. We determine 
    // it's the service worker request via the `sec-fetch-dest` header
    if (req.headers['sec-fetch-dest'] === 'serviceworker') {
```

Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts:223]: Added: [`3681bb7` (#28060)](https://github.com/cypress-io/cypress/pull/28060/commits/3681bb71a46f348460ae523e166506460339e321)

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 6]
```diff
@@ -265,7 +264,7 @@ export class BrowserCriClient {
         throw new Error(`Could not find url target in browser ${url}. Targets were ${JSON.stringify(targets)}`)
       }
 
-      this.currentlyAttachedTarget = await create(target.targetId, this.onAsynchronousError, this.host, this.port)
+      this.currentlyAttachedTarget = await create(target.targetId, this.onAsynchronousError, this.host, this.port, undefined, this.protocolManager)
```
Comment (mschile) [inline packages/server/lib/browsers/browser-cri-client.ts]: We should update these to accept an object at some point so we don't need to pass `undefined`.

File: packages/proxy/lib/http/response-middleware.ts (hunk 4 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/response-middleware.ts:660]:
```suggestion
  // If we're redirecting from a request that doesn't expect to have a preRequest (e.g. download links), we need to treat the redirected url as such as well.
  if (this.req.noPreRequestExpected) {
```

File: packages/server/lib/browsers/cri-client.ts [hunk 7]
```diff
@@ -252,6 +254,31 @@ export const create = async (
       debug('crash detected')
       crashed = true
     })
+
+    // We only want to try and add service worker traffic if we have a host set. This indicates that this is the child cri client.
+    if (host) {
+      await cri.send('Target.setDiscoverTargets', { discover: true })
```
Comment (mschile) [inline packages/server/lib/browsers/cri-client.ts]: Should this be after the `targetCreated` listener? Also, do we really need to `await` this call?

File: packages/server/lib/browsers/electron.ts [hunk 8]
```diff
@@ -307,7 +307,10 @@ export = {
         cdpSocketServer?.attachCDPClient(cdpAutomation),
         videoApi && recordVideo(cdpAutomation, videoApi),
         this._handleDownloads(win, options.downloadsFolder, automation),
-        await utils.handleDownloadLinksViaCDP(pageCriClient, automation),
+        utils.handleDownloadLinksViaCDP(pageCriClient, automation),
+        // Ensure to clear browser state in between runs. This is handled differently in browsers when we launch new tabs, but we don't have that concept in electron
+        pageCriClient.send('Storage.clearDataForOrigin', { origin: '*', storageTypes: 'all' }),
+        pageCriClient.send('Network.clearBrowserCache'),
```
Comment (mschile) [inline packages/server/lib/browsers/electron.ts:313]: So were we not clearing session/local storage in electron between specs? Is there a test for this?

File: cli/CHANGELOG.md [hunk 9]
```diff
@@ -5,6 +5,7 @@ _Released 10/25/2023 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed a performance regression with proxy correlation timeouts and requests issued from service workers. Fixed an issue where proxy correlation would leak over from a previous spec. Fixed an issue where redirects of requests that knowingly don't have CDP traffic should also be assumed to not have CDP traffic. Fixes [#28054](https://github.com/cypress-io/cypress/issues/28054) and [#28056](https://github.com/cypress-io/cypress/issues/28056).
```
Comment (mschile) [inline cli/CHANGELOG.md]: I feel like these should be split up into 3 different bullet points.

Comment (mschile) [inline cli/CHANGELOG.md]: Typically we reference the version where the regression was introduced.

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: I don't think the changelog parser will like that but we'll see.

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: Ah I can make it work

File: packages/server/lib/browsers/electron.ts (hunk 8 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/electron.ts:313]: IndexedDB and service workers were added to this test: https://github.com/cypress-io/cypress/pull/28060/files#diff-218614ae013c9499068762e74b5ae5c29ad34236f32ffc71fa73fbd745815a3cR20-R37 which demonstrates the problem

File: packages/server/lib/browsers/cri-client.ts (hunk 7 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/cri-client.ts]: Yes good catch (though I don't think it ultimately matters since we won't get new service workers til later). Will update. We do want to await it as we don't want to progress to start the runs until we're done setting this.

**Review by mschile — APPROVED** [review]

File: packages/server/lib/browsers/cri-client.ts (hunk 7 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/cri-client.ts]: [`987f3d3` (#28060)](https://github.com/cypress-io/cypress/pull/28060/commits/987f3d32c7cc87e0163f174f6ba458b577eac597)

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 6 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/browser-cri-client.ts]: [`987f3d3` (#28060)](https://github.com/cypress-io/cypress/pull/28060/commits/987f3d32c7cc87e0163f174f6ba458b577eac597)

File: cli/CHANGELOG.md (hunk 9 above)
Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: [`281f61c` (#28060)](https://github.com/cypress-io/cypress/pull/28060/commits/281f61c40f7baa1c098c8b33c5c18059188d30c9)

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: [`281f61c` (#28060)](https://github.com/cypress-io/cypress/pull/28060/commits/281f61c40f7baa1c098c8b33c5c18059188d30c9)
