### PR TITLE
fix: properly replace integrity tags in script resources when experimentalModifyObstructiveThirdPartyCode is true

### LINKED ISSUE #23647: Unable to complete e2e test using paypal payment (on sanbox test website)
### Current behavior

I am using cyress 10.7.0 in order to perform E2E tests on a selfcare webapp that provides also the possibilty to perform payment through paypal.
In the test environment we can use sandbox test paypal website
As soon as the user is redirected to sandbox in order to confirm the paypal credentials then the cypress runner disappears and the test get stuck.

I added the following configurations into cypress.config.js file:

chromeWebSecurity: false,
  defaultCommandTimeout: 20000,
  pageLoadTimeout: 60000,
  watchForFileChanges: false,

See linked issue: 
https://github.com/cypress-io/cypress/issues/22186

I tryed also to add the "experimentalModifyObstructiveThirdPartyCode" parameter into the cypress.config.js file:

  experimentalModifyObstructiveThirdPartyCode: true

but with this configuration ALL my test specs fail with the following error:

as soos as the cy.visit("...") command is invoked I got an unexpected exception "(uncaught exception)SyntaxError: Invalid left-hand side in assignment", see attached screenshot.

image

### Desired behavior

_No response_

### Test code to reproduce

You have to use a website which redirects the user to perform payment on paypal test website (sandbox)

### Cypress Version

10.7.0

### Node version

16.17.0

### Operating System

macOS 12.5.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #23647

### User facing changelog
Fixes an error with incorrect JS source rewriting when the `experimentalModifyObstructiveThirdPartyCode` flag is enabled

### Additional details
When running their test suite with `experimentalModifyObstructiveThirdPartyCode` enabled, user was getting a left hand assignment syntax error, which was the result of a third party recaptcha script being rewritten to nullify script integrity, resulting in the below error:

```
// results in a syntax error
obj.cypress-stripped-integrity='sha384-XiV6bRRw9OEpsWSumtD1J7rElgTrNQro4MY/O4IYjhH+YGCf1dHaNGZ3A2kzYi/C'
```

With added tests and changed to the regex-rewritter, this is now yeilding the following correctly:
```
obj['cypress-stripped-integrity']='sha384-XiV6bRRw9OEpsWSumtD1J7rElgTrNQro4MY/O4IYjhH+YGCf1dHaNGZ3A2kzYi/C'
```

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by AtofStryker** [comment]
does not look to have an impact on recaptchas in regards to #23728

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 1]
```diff
@@ -49,7 +62,7 @@ export function stripStream ({ modifyObstructiveThirdPartyCode }: Partial<Securi
         jiraTopWindowGetterRe,
         jiraTopWindowGetterUnMinifiedRe,
         ...(modifyObstructiveThirdPartyCode ? [
-          integrityTagReplacementRe,
+          buildIntegrityReplacementRe(isHtml),
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/regex-rewriter.ts]: can buildIntegrityReplacementRe &  returnReplacedIntegrityExpression return the array ?
```js
...(modifyObstructiveThirdPartyCode ?   buildIntegrityReplacementRe(isHtml) : []
```

**Review by emilyrohrbough — APPROVED** [review]

File: packages/proxy/lib/http/util/regex-rewriter.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: They cannot since they need to be used in the regular strip function above, which doesn't leverage arrays to replace. The good part is once this does become GA with `modifyObstructiveCode`, we can just merge this into the already flat array

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 2]
```diff
@@ -17,10 +17,22 @@ const topOrParentLocationOrFramesRe = /([^\da-zA-Z\(\)])?(\btop\b|\bparent\b)([.
 const jiraTopWindowGetterRe = /(!function\s*\((\w{1})\)\s*{\s*return\s*\w{1}\s*(?:={2,})\s*\w{1}\.parent)(\s*}\(\w{1}\))/g
 const jiraTopWindowGetterUnMinifiedRe = /(function\s*\w{1,}\s*\((\w{1})\)\s*{\s*return\s*\w{1}\s*(?:={2,})\s*\w{1}\.parent)(\s*;\s*})/g
 
-const integrityTagReplacementRe = new RegExp(`(${STRIPPED_INTEGRITY_TAG}|integrity)(=(?:\"|\')sha(?:256|384|512)-.*?(?:\"|\'))`, 'g')
+const buildIntegrityReplacementRe = (isHtml = true) => {
+  if (!isHtml) {
+    // only replace integrity if a trailing period (.) or string exists inside JS/Other resources
```
Comment (mjhenkes) [inline packages/proxy/lib/http/util/regex-rewriter.ts]: Could you add more code comments here to help explain why there is a difference? My head already hurts just trying to parse these regexes.

Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: I can give it a shot. I am having issues thinking of something useful though so I'm going to try typing my thoughts out 😆 . The main goal here is only replace integrity in JavaScript if the word `integrity` or `cypress-stripped-integrity` is preceded by a `.` or quotes. So something like 

```
foo.integrity = 'sha256-some-hash'
var integrity = 'sha256-some-hash'
```

becomes
```
foo['cypress-stripped-integrity'] = 'sha256-some-hash'
var integrity = 'sha256-some-hash'

```

It isn't so much what we match on as much as it is what we replace it with (the brackets vs the tagname). At some point in the future I am starting to think we might want to apply both of these because JS like above could be in HTML, but I am a bit hesitant to try it because it could have side effects we aren't testing for, and we haven't run into that problem yet. Now that I think about it I might want to go. Did any of that make sense or is it more of a jumbled ramble?

Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: I gave it ago and it's complicated with some added lookbacks 😄. I think we might want to hold off on that for now  until it actually surfaces as a problem (if it even is one). Maybe we can meet up on Monday to see if we can improve the documentation?

Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: I actually got it to work! I tried adding some docs in 41e82c835d86888f5aae2c71cc1d81f5b9977252 but I don't think they are really great. It also means the regex is more complicated, but handles more cases correctly without sacrificing performance. Regardless of resource type, both regex functions need to execute because HTML can have nested javascript inside of it, and both regexes need to run to rewrite correctly

**Review by mjhenkes — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 3]
```diff
@@ -16,8 +16,18 @@ const topOrParentLocationOrFramesRe = /([^\da-zA-Z\(\)])?(\btop\b|\bparent\b)([.
 
 const jiraTopWindowGetterRe = /(!function\s*\((\w{1})\)\s*{\s*return\s*\w{1}\s*(?:={2,})\s*\w{1}\.parent)(\s*}\(\w{1}\))/g
 const jiraTopWindowGetterUnMinifiedRe = /(function\s*\w{1,}\s*\((\w{1})\)\s*{\s*return\s*\w{1}\s*(?:={2,})\s*\w{1}\.parent)(\s*;\s*})/g
-
-const integrityTagReplacementRe = new RegExp(`(${STRIPPED_INTEGRITY_TAG}|integrity)(=(?:\"|\')sha(?:256|384|512)-.*?(?:\"|\'))`, 'g')
+/**
+ * Matches the word integrity if being set on an object, such as foo.integrity. This MUST be preceded by a valid hash to match. This is replaced with
```
Comment (mschile) [inline packages/proxy/lib/http/util/regex-rewriter.ts]:
```suggestion
 * Matches the word integrity if being set on an object, such as foo.integrity. This MUST be followed by a valid hash to match. This is replaced with
```

Comment (mschile) [inline packages/proxy/lib/http/util/regex-rewriter.ts]: or
```suggestion
 * Matches the word integrity if being set on an object, such as foo.integrity. This MUST precede a valid hash to match. This is replaced with
```

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 4]
```diff
@@ -16,8 +16,18 @@ const topOrParentLocationOrFramesRe = /([^\da-zA-Z\(\)])?(\btop\b|\bparent\b)([.
...
+ * foo['cypress-stripped-integrity']
+ */
+const javaScriptIntegrityReplacementRe = new RegExp(`[\\.](${STRIPPED_INTEGRITY_TAG}|integrity)((\\s?=\\s?)(?:"|')sha(?:256|384|512)-.*?(?:"|'))`, 'g')
+/**
+ * Does a negative lookback to see a variable is being declared, such as var let or const (the nst is back end of const since lookbacks need a fixed width). This can then
```
Comment (mschile) [inline packages/proxy/lib/http/util/regex-rewriter.ts]:
```suggestion
 * Does a negative lookback to see a variable is being declared, such as var let or const (the 'nst' is back end of const since lookbacks need a fixed width). This can then
```

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 5]
```diff
@@ -16,8 +16,18 @@ const topOrParentLocationOrFramesRe = /([^\da-zA-Z\(\)])?(\btop\b|\bparent\b)([.
...
+ * be preceded by any optional character that isn't a period, space, single or double quote. This MUST be preceded by a valid hash to match. A space preceding the integrity tag can still be matched,
```
Comment (mschile) [inline packages/proxy/lib/http/util/regex-rewriter.ts]:
```suggestion
 * be preceded by any optional character that isn't a period, space, single or double quote. This MUST be followed by a valid hash to match. A space preceding the integrity tag can still be matched,
```

File: packages/proxy/lib/http/util/regex-rewriter.ts [hunk 6]
```diff
@@ -16,8 +16,18 @@ const topOrParentLocationOrFramesRe = /([^\da-zA-Z\(\)])?(\btop\b|\bparent\b)([.
...
+ * but the match only starts at the word integrity, and not the character preceding it. In these cases, we always replace the word integrity with cypress-stripped-integrity.
+ * The match for cypress-stripped-integrity is if we are replacing in the stripStream, and the replaced text is rematched no essentially complete a no op
```
Comment (mschile) [inline packages/proxy/lib/http/util/regex-rewriter.ts]:
```suggestion
 * The match for cypress-stripped-integrity is if we are replacing in the stripStream, and the replaced text is rematched to essentially complete a no op
```

**Review by mschile — CHANGES_REQUESTED** [review]

File: packages/proxy/lib/http/util/regex-rewriter.ts (hunk 6 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: addressed in [81650c2](https://github.com/cypress-io/cypress/pull/23820/commits/81650c2536581b64ea66f12d4ca20e68f0cde8f5)

File: packages/proxy/lib/http/util/regex-rewriter.ts (hunk 5 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: addressed in [81650c2](https://github.com/cypress-io/cypress/pull/23820/commits/81650c2536581b64ea66f12d4ca20e68f0cde8f5)

File: packages/proxy/lib/http/util/regex-rewriter.ts (hunk 4 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: addressed in [81650c2](https://github.com/cypress-io/cypress/pull/23820/commits/81650c2536581b64ea66f12d4ca20e68f0cde8f5)

File: packages/proxy/lib/http/util/regex-rewriter.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: addressed in [81650c2](https://github.com/cypress-io/cypress/pull/23820/commits/81650c2536581b64ea66f12d4ca20e68f0cde8f5). Went with `follow` as it seemed to sound better to me at least.

Comment (AtofStryker) [reply packages/proxy/lib/http/util/regex-rewriter.ts]: addressed in [81650c2](https://github.com/cypress-io/cypress/pull/23820/commits/81650c2536581b64ea66f12d4ca20e68f0cde8f5)

**Review by mschile — APPROVED** [review]
