### PR TITLE
Issue 6231 use more information from gitlab

### LINKED ISSUE #6231: Missing CI information from GitLab
It seems that the project URL and default branch are not utilized correctly by the runner. Due to this, some 3rd party tools may not work properly when they expect `remoteOrigin` and `defaultBranch`  in `commitParams` for runs recorded by Cypress running as GitLab job.

### PR DESCRIPTION
**Pull request by TomaszG**
- Closes #6231 

### User facing changelog

We're collecting more environment variables when running Cypress with GitLab CI.

### Additional details

One of my projects required this to correctly create a commit URL. I'm not able to debug this on the Cypress Dashboard, however, I suspect that the commit link for GitLab may be incorrect.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/server/lib/util/ci_provider.js [hunk 1]
```diff
@@ -445,8 +446,8 @@ const _providerCommitParams = () => {
       message: env.CI_COMMIT_MESSAGE,
       authorName: env.GITLAB_USER_NAME,
       authorEmail: env.GITLAB_USER_EMAIL,
-      // remoteOrigin: ???
-      // defaultBranch: ???
+      remoteOrigin: env.CI_PROJECT_URL,
```
Comment (jennifer-shehane) [inline packages/server/lib/util/ci_provider.js]: The `remoteOrigin` should be the url of the Git repo, not Gitlab's CI url. The `remoteOrigin` value should actually be mapped to `CI_REPOSITORY_URL`

**Comment by TomaszG** [comment]
@jennifer-shehane 

So the thing is that I'm not using the Cypress Dashboard (mostly because even the highest plan wouldn't be sufficient), and instead of it I'm using a self-hosted alternative called [sorry-cypress](https://github.com/agoldis/sorry-cypress). Due to the missing commit params which currently aren't sent for GitLab some functions of it don't work properly so I tried to fix it at the source - Cypress CLI. Assuming that Cypress Dashboard correctly creates the commit link for GitLab provider it probably means that it doesn't use `remoteOrigin` commit param and instead of it, there's probably some condition implemented to use one of `ciParams` to create the link (instead of `commitParams`). I've looked at the runner code and I've seen `???` for those GitLab CI params so I decided to fix them as GitLab offers them in their pipeline runs.

So if only commit link on Cypress Dashboard works properly then there's no change from the user's perspective. It's only a cosmetical change to keep things in order and keep consistency.

File: packages/server/lib/util/ci_provider.js (hunk 1 above)
Comment (TomaszG) [reply packages/server/lib/util/ci_provider.js]: You're right, fixed it, thanks!
