### PR TITLE
fix: build better-sqlite3

### LINKED ISSUE #27891: electron-rebuild better-sqlite3 deprecation warnings starting with v13.2.0
### Current behavior

Building Cypress from source with `yarn` results in multiple deprecation and other warnings such as `V8_DEPRECATED` at the step:

```text
electron-rebuild -o better-sqlite3
```

This is a regression compared to Cypress `v13.1.0`.

### Desired behavior

The current default branch https://github.com/cypress-io/cypress should install without deprecation and other warnings and produce output similar to

```text
$ electron-rebuild -o better-sqlite3
✔ Rebuild Complete
```

as was the case in [Cypress 13.1.0](https://docs.cypress.io/guides/references/changelog#13-1-0) before the Electron upgrade from `21.0.0` to `25.8.0` in [Cypress 13.2.0](https://docs.cypress.io/guides/references/changelog#13-2-0).

#### Prerequisites

```bash
npm install yarn@latest -g
sudo apt install g++ make cmake
```

#### Execute

```bash
git clone https://github.com/cypress-io/cypress
cd cypress

git checkout v13.1.0
n auto # or similar to set node to 16.16.0
yarn # no issue with electron-rebuild -o better-sqlite3

git checkout v13.2.0
n auto # or similar to set node to 18.15.0
yarn # multiple deprecation warnings for electron-rebuild -o better-sqlite3

git checkout develop
n auto # or similar to set node to 18.15.0
git clean -x -d -f
yarn # multiple deprecation warnings also for develop branch
```

### Cypress Version

First reported on version: `13.2.0`
Reproducible also on version: `13.3.0`

### Node version

`18.15.0`

### Operating System

Ubuntu `22.04.3` LTS

### Debug Logs

```text
$ electron-rebuild -o better-sqlite3
⠦ Building module: better-sqlite3, Completed: 0make: Entering directory '/home/mike/github/cypress-io/cypress/node_modules/better-sqlite3/build'
  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
⠇ Building module: better-sqlite3, Completed: 0  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
⠦ Building module: better-sqlite3, Completed: 0  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
⠧ Building module: better-sqlite3, Completed: 0  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
⠼ Building module: better-sqlite3, Completed: 0In file included from /home/mike/.electron-gyp/25.8.1/include/node/v8-object.h:10,
                 from /home/mike/.electron-gyp/25.8.1/include/node/v8-array-buffer.h:13,
                 from /home/mike/.electron-gyp/25.8.1/include/node/v8.h:24,
                 from /home/mike/.electron-gyp/25.8.1/include/node/node.h:79,
                 from ./src/better_sqlite3.lzz:11,
                 from ../src/better_sqlite3.cpp:4:
/home/mike/.electron-gyp/25.8.1/include/node/v8-persistent-handle.h:245:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  245 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/home/mike/.electron-gyp/25.8.1/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
⠧ Building module: better-sqlite3, Completed: 0In file included from ../src/better_sqlite3.cpp:4:
./src/util/macros.lzz:31:69: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
In file included from /home/mike/.electron-gyp/25.8.1/include/node/v8-object.h:10,
                 from /home/mike/.electron-gyp/25.8.1/include/node/v8-array-buffer.h:13,
                 from /home/mike/.electron-gyp/25.8.1/include/node/v8.h:24,
                 from /home/mike/.electron-gyp/25.8.1/include/node/node.h:79,
                 from ./src/better_sqlite3.lzz:11,
                 from ../src/better_sqlite3.cpp:4:
/home/mike/.electron-gyp/25.8.1/include/node/v8-persistent-handle.h:244:48: note: declared here
  244 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
⠇ Building module: better-sqlite3, Completed: 0In file included from ./src/better_sqlite3.lzz:11,
                 from ../src/better_sqlite3.cpp:4:
/home/mike/.electron-gyp/25.8.1/include/node/node.h:1013:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>)’ to ‘node::addon_context_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*)’} [-Wcast-function-type]
 1013 |       (node::addon_context_register_func) (regfunc),                  \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mike/.electron-gyp/25.8.1/include/node/node.h:1031:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’
 1031 |   NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mike/.electron-gyp/25.8.1/include/node/node.h:1062:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’
 1062 |   NODE_MODULE_CONTEXT_AWARE(NODE_GYP_MODULE_NAME,                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
./src/better_sqlite3.lzz:67:1: note: in expansion of macro ‘NODE_MODULE_INIT’
./src/objects/database.lzz: In static member function ‘static void Database::JS_new(const v8::FunctionCallbackInfo<v8::Value>&)’:
./src/objects/database.lzz:180:21: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
⠹ Building module: better-sqlite3, Completed: 0./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_stmt*, int, bool)’:
./src/util/data.lzz:73:92: warning: this statement may fall through [-Wimplicit-fallthrough=]
./src/util/data.lzz:73:197: note: here
./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_value*, bool)’:
./src/util/data.lzz:77:81: warning: this statement may fall through [-Wimplicit-fallthrough=]
./src/util/data.lzz:77:175: note: here
⠋ Building module: better-sqlite3, Completed: 0  SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node
⠙ Building module: better-sqlite3, Completed: 0  COPY Release/better_sqlite3.node
⠹ Building module: better-sqlite3, Completed: 0  CC(target) Release/obj.target/test_extension/deps/test_extension.o
⠸ Building module: better-sqlite3, Completed: 0  SOLINK_MODULE(target) Release/obj.target/test_extension.node
  COPY Release/test_extension.node
rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
make: Leaving directory '/home/mike/github/cypress-io/cypress/node_modules/better-sqlite3/build'
✔ Rebuild Complete
```

#### Versions

- `electron@25.8.1`
- `better-sqlite3@8.2.0`

#### Suggestions

It seems that a minimum of [better-sqlite3@8.5.0](https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.5.0) would be needed. The latest version for consideration is currently [better-sqlite3@8.6.0](https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.6.0).

[better-sqlite3/releases/tag/v8.5.0](https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.5.0) mentions "Add support for electron v25 prebuilds". This is the version of Electron bundled with Cypress `13.2.0`.

### LINKED ISSUE #27902: Test Replay - Failed Capturing - `GLIBC_2.29' not found (better-sqlite3)
### Current behavior

Hi, recently I've been testing v13's Test Replay.
After the CI run, I saw the report on the dashboard, but the `Tests for review` section in the overview is empty.
Checking the pipeline logs, I found the following error:

`Test Replay - Failed Capturing - /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by /root/.cache/Cypress/13.2.0/Cypress/resources/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node)`

Is it because the image I'm using is not supported ? Thank you

### Desired behavior

_No response_

### Test code to reproduce

N/A

### Cypress Version

13.2.0

### Node version

v18.4.0

### Operating System

N/A

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
Closes #27902
Closes #27891

### Additional details

Build `better-sqlite3` on centos 7 to ensure a wider range of compatibility in the binary. The approach here is to use the `centos7-builder.Dockerfile` as the image to use when building and then mirror the [build commands](https://github.com/WiseLibs/better-sqlite3/blob/master/.github/workflows/build.yml#L17) used for `better-sqlite3`. In the wrong run, we could host this Dockerfile in docker hub and potentially have some additional optimizations, but in the spirit of getting folks fixed faster, this approach is good for now.

### Steps to test

You can test this by running the binaries attached to the branches on various OS's.

### How has the user experience changed?

n/a

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: scripts/binary/build.ts [hunk 1]
```diff
@@ -139,7 +139,7 @@ export async function buildCypressApp (options: BuildCypressAppOpts) {
     ...packageJsonContents,
     scripts: {
       // After the `yarn --production` install, we need to patch packages and trigger a server build to rebuild native bindings for `better-sqlite3`
```
Comment (astone123) [inline scripts/binary/build.ts]:
```suggestion
      // After the `yarn --production` install, we need to patch packages
```

File: centos7-builder.Dockerfile [hunk 2]
```diff
@@ -0,0 +1,9 @@
+FROM centos:7
+# Install dependencies for building the addon and setting devtoolset-8 as the default compiler
+RUN yum -y install centos-release-scl curl python3 make atk-devel atk java-atk-wrapper at-spi2-atk gtk3 libXt libdrm mesa-libgbm Xvfb && yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++
+RUN echo >> /etc/profile.d/devtoolset-8.sh 'source scl_source enable devtoolset-8'
+RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
+RUN echo >> /etc/profile.d/nvm.sh 'source ~/.nvm/nvm.sh'
+# Node 16 is the most recent version that supports CentOS 7. We only need it to call the
+# build script for lib/addon, so there should be minimal risk of security issues.
```
Comment (astone123) [inline centos7-builder.Dockerfile]:
```suggestion
# Node 16 is the most recent version that supports CentOS 7. We only need it to
# re-build better-sqlite, so there should be minimal risk of security issues.
```

File: centos7-builder.Dockerfile [hunk 3]
```diff
@@ -0,0 +1,9 @@
+FROM centos:7
+# Install dependencies for building the addon and setting devtoolset-8 as the default compiler
```
Comment (astone123) [inline centos7-builder.Dockerfile]:
```suggestion
# Install dependencies for re-building better-sqlite and setting devtoolset-8 as the default compiler
```

File: .circleci/workflows.yml [hunk 4]
```diff
@@ -2522,10 +2565,13 @@ jobs:
 linux-x64-workflow: &linux-x64-workflow
   jobs:
     - node_modules_install
+    - build-better-sqlite3:
+        requires:
+          - node_modules_install
```
Comment (astone123) [inline .circleci/workflows.yml]: My only concern here is that we're adding like a 4-minute blocking job to the top of our already extremely long workflow. How often is this dependency going to change? Could we at least cache it in CircleCI? Seems unnecessary to re-build it every single time

File: scripts/binary/trigger-publish-binary-pipeline.js [hunk 5]
```diff
@@ -10,6 +10,7 @@ const { getNextVersionForBinary } = require('../get-next-version')
   const { nextVersion } = await getNextVersionForBinary()
 
   const body = JSON.stringify({
+    branch: 'ryanm/fix/better-sqlite3',
```
Comment (chrisbreiding) [inline scripts/binary/trigger-publish-binary-pipeline.js]: Does this need to be removed before this is merged?

Comment (ryanthemanuel) [reply scripts/binary/trigger-publish-binary-pipeline.js]: Yep. Good reminder.

File: .circleci/workflows.yml (hunk 4 above)
Comment (ryanthemanuel) [reply .circleci/workflows.yml]: @astone123 good call. I reswizzled a bit and now things are caching. Basically the node modules cache now depends on the centos image as well. And we only build better sqlite if the version of electron or better sqlite3 has changed.

File: .circleci/workflows.yml [hunk 6]
```diff
@@ -355,7 +353,7 @@ commands:
           command: node ./scripts/get-platform-key.js > platform_key
       - restore_cache:
           name: Restore cache state, to check for known modules cache existence
-          key: v{{ checksum ".circleci/cache-version.txt" }}-{{ checksum "platform_key" }}-state-of-node-modules-cache-{{ checksum "circle_cache_key" }}
```
Comment (astone123) [inline .circleci/workflows.yml:358]: One thing about this cache key - if the Dockerfile changes, it'll invalidate the node_modules cache for all of the operating system workflows. I wonder if we could have it use different cache keys based on whether or not `<<parameters.build-better-sqlite3>>` is true.

Also, if we're going to be restoring the cache with this key, we also need to update the key under the ["Saving node-modules cache state key" step](https://github.com/cypress-io/cypress/pull/27968/files#diff-7bf091450b804ea25dc3d11ac28c50202d19178f7b53f54a02ad59c946afa6a7R406) to match, otherwise we'll never hit the cache

**Review by astone123 — CHANGES_REQUESTED** [review]
Need to fix the cache keys

File: cli/CHANGELOG.md [hunk 7]
```diff
@@ -8,6 +8,11 @@ _Released 10/03/2023 (PENDING)_
 - Fixed an issue where requests were correlated in the wrong order in the proxy. This could cause an issue where the wrong request is used for `cy.intercept` or assets (e.g. stylesheets or images) may not properly be available in Test Replay. Addressed in [#27892](https://github.com/cypress-io/cypress/pull/27892).
 - Fixed an issue where a crashed Chrome renderer can cause the Test Replay recorder to hang. Addressed in [#27909](https://github.com/cypress-io/cypress/pull/27909).
 - Fixed an issue where multiple responses yielded from calls to `cy.wait()` would sometimes be out of order. Fixes [#27337](https://github.com/cypress-io/cypress/issues/27337).
+- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixes [#27902](https://github.com/cypress-io/cypress/issues/27902).
+
+**Dependency Updates:**
+
+- Update dependency `better-sqlite3` to 8.7.0. Addressed in [#27902](https://github.com/cypress-io/cypress/issues/27902).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
```

File: cli/CHANGELOG.md [hunk 8]
```diff
@@ -8,6 +8,8 @@ _Released 10/03/2023 (PENDING)_
 - Fixed an issue where requests were correlated in the wrong order in the proxy. This could cause an issue where the wrong request is used for `cy.intercept` or assets (e.g. stylesheets or images) may not properly be available in Test Replay. Addressed in [#27892](https://github.com/cypress-io/cypress/pull/27892).
 - Fixed an issue where a crashed Chrome renderer can cause the Test Replay recorder to hang. Addressed in [#27909](https://github.com/cypress-io/cypress/pull/27909).
 - Fixed an issue where multiple responses yielded from calls to `cy.wait()` would sometimes be out of order. Fixes [#27337](https://github.com/cypress-io/cypress/issues/27337).
+- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixes [#27902](https://github.com/cypress-io/cypress/issues/27902).
+
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
```

File: .circleci/workflows.yml (hunk 6 above)
Comment (ryanthemanuel) [reply .circleci/workflows.yml:358]: Doh good catch. I've updated to do both.

File: .circleci/workflows.yml [hunk 9]
```diff
@@ -488,6 +510,61 @@ commands:
...
+  # of the container because the host running docker does not have access to the project directory so volume mounts are
+  # not possible. The built plugin is copied to the project directory so it can be injected into the final binary.  
+  build-better-sqlite3:
+    description: Build better-sqlite3 for CentOS 7
+    steps:
+      - setup_remote_docker
+      - restore_cache:
+          keys:
+            - cypress-centos7-builder-{{ checksum "centos7-builder.Dockerfile" }}
+      - run:
```
Comment (astone123) [inline .circleci/workflows.yml:530]: Seems like we could make a slight optimization here... We're restoring this cache and loading the Docker image (which is taking like almost 1 minute) here every time, even when we're not going to re-build better-sqlite.

I wonder if we could do these steps conditionally based on whether `better_sqlite3.node` is restored from cache? I've had trouble doing this type of thing in the past, so I'm not sure it's possible.

One thing that I think we might be able to do is store `centos7-builder.tar` and `better_sqlite3.node` under the same cache key, since we know that we'll only need the Docker image if we need to re-build `better_sqlite3.node`. Then, restore the cache and if the file doesn't exist, load the image in and re-build better_sqlite3. 

Just something to look into. Let me know if you want to talk it out over a call. Would be nice to make this as efficient as possible since our CI is already super long

Comment (ryanthemanuel) [reply .circleci/workflows.yml:530]: I think I found a good way to do this. Thoughts?

**Review by astone123 — APPROVED** [review]
Looks good!

**Review by chrisbreiding — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@ryanthemanuel 

From your comments I understood that this is intended to be a temporary measure only. That would fit with the following constraints:

The Docker image [centos:7](https://hub.docker.com/layers/library/centos/7/images/sha256-dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f) appears to be deprecated.

According to https://hub.docker.com/_/centos

image

CentOS 7 has a limited remaining 8 month lifetime until June 30, 2024 (see https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/).

Strangely CentOS is not listed under https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System,  which only refers to the following as being supported by Cypress

> Linux Ubuntu 12.04 and above, Fedora 21 and Debian 8 (x86_64 or Arm 64-bit (x64 or arm64)) (see [Linux Prerequisites](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) down below)

**Comment by MikeMcC399** [comment]
- This PR would also close https://github.com/cypress-io/cypress/issues/27891 as it updates to `"better-sqlite3": "8.7.0"` (current latest).

File: scripts/binary/trigger-publish-binary-pipeline.js (hunk 5 above)
Comment (ryanthemanuel) [reply scripts/binary/trigger-publish-binary-pipeline.js]:
```suggestion
```

File: cli/CHANGELOG.md [hunk 10]
```diff
@@ -8,6 +8,7 @@ _Released 10/03/2023 (PENDING)_
 - Fixed an issue where requests were correlated in the wrong order in the proxy. This could cause an issue where the wrong request is used for `cy.intercept` or assets (e.g. stylesheets or images) may not properly be available in Test Replay. Addressed in [#27892](https://github.com/cypress-io/cypress/pull/27892).
 - Fixed an issue where a crashed Chrome renderer can cause the Test Replay recorder to hang. Addressed in [#27909](https://github.com/cypress-io/cypress/pull/27909).
 - Fixed an issue where multiple responses yielded from calls to `cy.wait()` would sometimes be out of order. Fixes [#27337](https://github.com/cypress-io/cypress/issues/27337).
+- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixes [#27902](https://github.com/cypress-io/cypress/issues/27902).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixes [#27902](https://github.com/cypress-io/cypress/issues/27902).
- Fixed deprecation warnings during the rebuild of better-sqlite3. Fixes [#27891](https://github.com/cypress-io/cypress/issues/27891).
```

File: cli/CHANGELOG.md [hunk 11]
```diff
@@ -8,6 +8,7 @@ _Released 10/03/2023 (PENDING)_
 - Fixed an issue where requests were correlated in the wrong order in the proxy. This could cause an issue where the wrong request is used for `cy.intercept` or assets (e.g. stylesheets or images) may not properly be available in Test Replay. Addressed in [#27892](https://github.com/cypress-io/cypress/pull/27892).
 - Fixed an issue where a crashed Chrome renderer can cause the Test Replay recorder to hang. Addressed in [#27909](https://github.com/cypress-io/cypress/pull/27909).
 - Fixed an issue where multiple responses yielded from calls to `cy.wait()` would sometimes be out of order. Fixes [#27337](https://github.com/cypress-io/cypress/issues/27337).
+- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixed deprecation warnings during the rebuild of better-sqlite3. Fixes [#27902](https://github.com/cypress-io/cypress/issues/27902). Fixes [#27891](https://github.com/cypress-io/cypress/issues/27891).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue where Test Replay couldn't record tests due to issues involving `GLIBC`. Fixed deprecation warnings during the rebuild of better-sqlite3. Fixes [#27891](https://github.com/cypress-io/cypress/issues/27891) and [#27902](https://github.com/cypress-io/cypress/issues/27902).
```
