### PR TITLE
Fix `run_plugins_spec` test leaking into other tests, other flake in `request_spec`

### LINKED ISSUE #4481: `run_plugins_spec` test is leaking into other tests
`@ipc.send` in `run_plugins_spec` is somehow leading to failing tests later on:

https://github.com/cypress-io/cypress/blob/bbff24dc6799a2e9464eebff8e1f9ad468fa5635/packages/server/test/unit/plugins/child/run_plugins_spec.coffee#L67-L80

https://circleci.com/gh/cypress-io/cypress/123148#tests/containers/1 -
```
AssertionError: expected 'error' to equal 'load:error'
    at Object.ipc.send (/root/cypress/packages/server/test/unit/plugins/child/run_plugins_spec.coffee:76:26)
    at process.on (/root/cypress/packages/server/lib/plugins/child/run_plugins.js:1:1)
    at emitOne (events.js:1:1)
    at process.emit (events.js:1:1)
    at process.emit (/root/cypress/packages/ts/node_modules/source-map-support/source-map-support.js:1:1)
    at processEmit (/root/cypress/packages/server/node_modules/signal-exit/index.js:1:1)
    at processEmit [as emit] (/root/cypress/packages/launcher/node_modules/signal-exit/index.js:1:1)
    at process._fatalException (bootstrap_node.js:1:1)
```

https://circleci.com/gh/cypress-io/cypress/128235#tests/containers/1

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #4481

Also increases the timeout on the 4x retry test for ECONNRESET, I could never get it to flake locally, only in CI, assuming it's just random slowdown. Bumping timeout from 100 to 250ms should fix this.

### CODE REVIEW

File: packages/server/test/unit/plugins/child/run_plugins_spec.coffee [hunk 1]
```diff
@@ -72,7 +72,7 @@ describe "lib/plugins/child/run_plugins", ->
       @ipc.on.withArgs("load").yields({})
       runPlugins(@ipc, "plugins-file")
 
-      @ipc.send = (event, errorType, pluginsFile, stack) ->
+      @ipc.send = _.once (event, errorType, pluginsFile, stack) ->
```
Comment (brian-mann) [inline packages/server/test/unit/plugins/child/run_plugins_spec.coffee]: I'm approving but why can't we use `sinon` to handle the mocking behavior since it's automatically torn down at the end of the test?

If that doesn't work - then we have something else still running async in the background causing the leak into another test - and likely the code needs to be refactored to properly handle this.
