### PR TITLE
fix: Cypress.cookies.debug() regression

### LINKED ISSUE #15032: Cypress.cookies.debug() does not log anything to console.
### Current behavior

`Cypress.cookies.debug()` no longer logs to the console in Cypress 6.3.0+

It seems this issue is introduced in this PR? https://github.com/cypress-io/cypress/pull/14182

- **Working** (chore: release @cypress/webpack-batteries-included-preprocessor-v2.1.4): https://github.com/cypress-io/cypress/commit/4c9ea6c50deafc7e4052efe0ca55db916930356c
- **Broken** (build: properly use local npm packages for development and binary build) https://github.com/cypress-io/cypress/commit/3eb3bfa487eae9723f65b071ca02f18014174be6

#### Before

Screen Shot 2021-02-11 at 10 29 48 AM

#### After

Screen Shot 2021-02-11 at 10 35 15 AM

### Test code to reproduce

```js
/// <reference types="cypress" />

context('Cookies', () => {
  beforeEach(() => {
    Cypress.Cookies.debug(true)

    cy.visit('https://example.cypress.io/commands/cookies')

    // clear cookies again after visiting to remove
    // any 3rd party cookies picked up such as cloudflare
    cy.clearCookies()
  })

  it('cy.getCookie() - get a browser cookie', () => {
    // https://on.cypress.io/getcookie
    cy.get('#getCookie .set-a-cookie').click()

    // cy.getCookie() yields a cookie object
    cy.getCookie('token').should('have.property', 'value', '123ABC')
  })

  it('cy.getCookies() - get browser cookies', () => {
    // https://on.cypress.io/getcookies
    cy.getCookies().should('be.empty')

    cy.get('#getCookies .set-a-cookie').click()

    // cy.getCookies() yields an array of cookies
    cy.getCookies().should('have.length', 1).should((cookies) => {
      // each cookie has these properties
      expect(cookies[0]).to.have.property('name', 'token')
      expect(cookies[0]).to.have.property('value', '123ABC')
      expect(cookies[0]).to.have.property('httpOnly', false)
      expect(cookies[0]).to.have.property('secure', false)
      expect(cookies[0]).to.have.property('domain')
      expect(cookies[0]).to.have.property('path')
    })
  })

  it('cy.setCookie() - set a browser cookie', () => {
    // https://on.cypress.io/setcookie
    cy.getCookies().should('be.empty')

    cy.setCookie('foo', 'bar')

    // cy.getCookie() yields a cookie object
    cy.getCookie('foo').should('have.property', 'value', 'bar')
  })

  it('cy.clearCookie() - clear a browser cookie', () => {
    // https://on.cypress.io/clearcookie
    cy.getCookie('token').should('be.null')

    cy.get('#clearCookie .set-a-cookie').click()

    cy.getCookie('token').should('have.property', 'value', '123ABC')

    // cy.clearCookies() yields null
    cy.clearCookie('token').should('be.null')

    cy.getCookie('token').should('be.null')
  })

  it('cy.clearCookies() - clear browser cookies', () => {
    // https://on.cypress.io/clearcookies
    cy.getCookies().should('be.empty')

    cy.get('#clearCookies .set-a-cookie').click()

    cy.getCookies().should('have.length', 1)

    // cy.clearCookies() yields null
    cy.clearCookies()

    cy.getCookies().should('be.empty')
  })
})
```

### Versions

6.3.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #15032

### User facing changelog

`Cypress.cookies.debug(true)` doesn't show cookie-related messages on the console window. 

### Additional details
- Why was this change necessary? => Fix regression.
- What is affected by this change? => N/A

### Any implementation details to explain?

* This happened because Chrome extensions cannot parse version name like "0.0.0-development". Cypress extension wasn't loaded and the `automation:push:request` message wasn't sent. 
* Chrome extensions doesn't allow "eval". I had to change the bundling policy of the webpack. 

### How has the user experience changed?

N/A

### Problem: How should I test this?

As far as I know, there is no way to test correct message is shown on the console window. In the current project setup, we're testing the mocks. We suppose that the extension is loaded successfully. But this bug happened because the loading failed. 

### PR Tasks
- [ ] Have tests been added/updated? => Is this possible?

### CODE REVIEW

File: packages/extension/gulpfile.ts [hunk 1]
```diff
@@ -16,7 +16,15 @@ const manifest = (done) => {
...
-      json.version = pkg.version
+      let version: string = pkg.version
+
+      // https://github.com/cypress-io/cypress/issues/15032
+      // '-development' inside version string makes Chrome fail to load the extension
+      if (version.endsWith('-development')) {
+        version = version.split('-')[0]
+      }
+
+      json.version = version
```
Comment (flotwig) [inline packages/extension/gulpfile.ts:27]: so... this is always `0.0.0`, right? why do we need to modify `version` here at all? it looks like it's already `0.0.0` inside of `manifest.json`:

https://github.com/cypress-io/cypress/blob/2fe5556322f8630bb0df1096f30f0bc9de284ae7/packages/extension/app/manifest.json#L40-L40

can we just... not update the version at all? delete lines 17-31?

**Review by flotwig — CHANGES_REQUESTED** [review]
seems to make sense, but it could be simpler i think

File: packages/extension/gulpfile.ts (hunk 1 above)
Comment (sainthkh) [reply packages/extension/gulpfile.ts:27]: You're right. It's always 0.0.0. I first thought that it would be changed on every release. So, I removed the code.

**Comment by sainthkh** [comment]
Flaky failures.

**Review by flotwig — APPROVED** [review]
