### PR TITLE
fix: Add missing `filter` parameter to `nextUntil` command

### LINKED ISSUE #24772: Types for `nextUntil` are missing the `filter` parameter
### Current behavior

Providing a filter works, but is shown as invalid.

### Desired behavior

Types should be updated to match `prevUntil`, `parentUntil`

### Test code to reproduce

n/a

### Cypress Version

11.0.1

### Node version

16.15.1

### Operating System

macOS 13.0.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #24772 

### User facing changelog
* Fixes Typescript typings for the `nextUntil` command to include the `filter` parameter

### Additional details
Aligning TS typings for `nextUntil` to align with `prevUntil` and `parentsUntil` - will now match [documented contract](https://docs.cypress.io/api/commands/nextuntil). Also fixing incorrect 'on' links in jsdoc

### PR Tasks

- [na] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -1589,19 +1589,19 @@ declare namespace Cypress {
...
      */
-    nextUntil<K extends keyof HTMLElementTagNameMap>(selector: K, options?: Partial<Loggable & Timeoutable>): Chainable<JQuery<HTMLElementTagNameMap[K]>>
+    nextUntil<K extends keyof HTMLElementTagNameMap>(selector: K, filter?: string, options?: Partial<Loggable & Timeoutable>): Chainable<JQuery<HTMLElementTagNameMap[K]>>
     /**
      * Get all following siblings of each DOM element in a set of matched DOM elements up to, but not including, the element provided.
      *
      * @see https://on.cypress.io/nextuntil
      */
-    nextUntil<E extends HTMLElement = HTMLElement>(options?: Partial<Loggable & Timeoutable>): Chainable<JQuery<E>>
+    nextUntil<E extends Node = HTMLElement>(selector: string, filter?: string, options?: Partial<Loggable & Timeoutable>): Chainable<JQuery<E>>
```
Comment (emilyrohrbough) [inline cli/types/cypress.d.ts:1598]: can we add a couple of type tests to ensure only selector, selector + filter, and selector + options, and selector + filter _ options are applied without error?

Comment (mike-plummer) [reply cli/types/cypress.d.ts:1598]: @emilyrohrbough Sure thing. Do we have a place we're putting those sorts of tests? I don't recall seeing them but I don't spend much time in this area

Comment (emilyrohrbough) [reply cli/types/cypress.d.ts:1598]: These guys would live somewhere in here: https://github.com/cypress-io/cypress/blob/develop/cli/types/tests/cypress-tests.ts
They aren't always added but some of the more complicated one I think it's helpful to add tests for.

**Review by chrisbreiding — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]
