### PR TITLE
misc: update `playwright-webkit` from `1.24.2` to `1.56.1` and `base-internal` image from Debian Bullseye to Debian Trixie

### LINKED ISSUE #29954: Update WebKit testing to 26.x
### What would you like?

Test Cypress with current WebKit ~~`17.x`~~ ~~`18.x`~~ `26.x` instead of `16.0`.

### Why is this needed?

The current version of WebKit is ~~`17.4`~~ ~~`18.x`~~ `26.x`.

CircleCI tests with WebKit `16.0` in

- `system-tests-webkit`
- `driver-integration-tests-webkit`

derived from `playwright-webkit@1.24.2`, released on July 29, 2022.

This is not representative of expected current usage of WebKit.

### Other

The latest version of [playwright](https://www.npmjs.com/package/playwright) is 

~~`1.45.3`, [released](https://github.com/microsoft/playwright/releases) July 22, 2024~~ 

`1.55.0`, [released](https://github.com/microsoft/playwright/releases) Aug 20, 2025.

- WebKit `17.0` was introduced with [Playwright 1.36](https://playwright.dev/docs/release-notes#version-136) [released](https://github.com/microsoft/playwright/releases/tag/v1.36.0) on July 11, 2023
- WebKit `18.0` was introduced with [Playwright 1.46](https://playwright.dev/docs/release-notes#version-146) [released](https://github.com/microsoft/playwright/releases/tag/v1.46.0) on Aug 5, 2024
- WebKit `26.0` was introduced with [Playwright 1.54](https://playwright.dev/docs/release-notes#version-154) [released](https://github.com/microsoft/playwright/releases/tag/v1.54.0) on Jul 10, 2024
- [Playwright 1.37](https://playwright.dev/docs/release-notes#version-137) [released](https://github.com/microsoft/playwright/releases/tag/v1.37.0) on Aug 11, 2023, is the minimum version required to support Debian 12 used in previous Cypress Docker images.
- [Playwright 1.45.0](https://playwright.dev/docs/release-notes#version-145) [released](https://github.com/microsoft/playwright/releases/tag/v1.45.0) on Jun 25, 2024, with WebKit `17.4` is the minimum version required to support Ubuntu 24.04.
- [Playwright 1.55.0](https://playwright.dev/docs/release-notes#version-155) [released](https://github.com/microsoft/playwright/releases/tag/v1.55.0) on Aug 20, 2025, with WebKit `26.0` is the minimum version required to support Debian 13 used in Cypress Docker images.

### LINKED ISSUE #29973: WebKit 26 fails driver-integration-tests-webkit (cookies.cy.js)
### Current behavior

If an attempt is made to update [playwright-webkit](https://www.npmjs.com/package/playwright-webkit) to the latest version in Cypress source code, it fails the Cypress test spec

- [packages/driver/cypress/e2e/commands/cookies.cy.js](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/commands/cookies.cy.js)

which is part of `driver-integration-tests-webkit`.

This is reproducible on Ubuntu with versions of [playwright-webkit](https://www.npmjs.com/package/playwright-webkit) starting with `1.37.0` and extending to the current version (with WebKit ~~`17.4`~~ ~~`18.0`~~ `26.x`).

Cypress is currently configured to use [playwright-webkit@1.24.2](https://github.com/microsoft/playwright/releases/tag/v1.24.2) released in July 2022:

https://github.com/cypress-io/cypress/blob/d8884e0a342e92a41fb3e187a807ae7babab3cc7/package.json#L189

### Desired behavior

WebKit should pass all tests from `driver-integration-tests-webkit` when using the latest version of `playwright-webkit`.

- Qualify if this is due to bug(s) in Playwright/WebKit or Cypress
- Depending on outcome, report bugs to [Playwright](https://github.com/microsoft/playwright/issues) and / or fix bugs in Cypress

### Test code to reproduce

```shell
npm install yarn@latest -g
git clone https://github.com/cypress-io/cypress
cd cypress
yarn add playwright-webkit@latest -D -W
yarn playwright install-deps webkit # Linux only
```

then

```shell
yarn workspace @packages/driver cypress:run --browser webkit --spec cypress/e2e/commands/cookies.cy.js
```

or

```shell
yarn workspace @packages/driver cypress:open --e2e --browser webkit
```

and select `cypress/e2e/commands/cookies.cy.js` to run in UI.

### Playwright Version

First reported on [playwright-webkit@1.45.3](https://github.com/microsoft/playwright/releases/tag/v1.45.3)
Continues to be reproducible on [playwright-webkit@1.55.0](https://github.com/microsoft/playwright/releases/tag/v1.55.0)

### Cypress Version

First reported on `13.13.2`
Continues to be reproducible on `15.0.0`

### Node version

~~`v18.17.1`~~ `v20.18.1` and `v22.18.0`

### Operating System

~~Ubuntu `22.04.4` LTS~~
Ubuntu `22.04.5` LTS and
Ubuntu `24.04.3` LTS

### Debug Logs

See failures in CircleCI at
https://app.circleci.com/pipelines/github/cypress-io/cypress/63152/workflows/e49a5390-7dc4-432e-abce-391b205c080b/jobs/2615104

```text
  1) src/cy/commands/cookies - no stub
       #getCookies
         returns cookies for the specified domain:

      AssertionError: expected 'key2' to equal 'key1'
      + expected - actual

      -'key2'
      +'key1'

      at  ([native code])
      at  (http://www.barbaz.com:3500/__cypress/tests:1717:41)
  getRet@
  tryCatcher@
  @
  thenFn@
  @
  tryCatcher@
  @
  @
  @
  _drainQueueStep@
  _drainQueue@
  @
  @

  2) src/cy/commands/cookies - no stub
       #getCookie
         returns the cookie from the specified domain:

      AssertionError: expected 'foobar.com value' to equal 'www.foobar.com value'
      + expected - actual

      -'foobar.com value'
      +'www.foobar.com value'

      at  ([native code])
      at  (http://www.barbaz.com:3500/__cypress/tests:1870:38)
  getRet@
  tryCatcher@
  @
  thenFn@
  @
  tryCatcher@
  @
  @
  @
  _drainQueueStep@
  _drainQueue@
  @
  @

  3) src/cy/commands/cookies
       #setCookie
         can set cookies with sameSite:

      AssertionError: expected { Object (name, value, ...) } to have property 'sameSite' of 'no_restriction', but got 'lax'
      + expected - actual

      -'lax'
      +'no_restriction'

      at  ([native code])
  applyChainer@
  arrayReduce@
  reduce@
  applyChainers@
  tryCatcher@
  @
  shouldFn@
  @
  tryCatcher@
  @
  @
  @
  _drainQueueStep@
  _drainQueue@
  @
  @
```

### Other

- See [WebKit (Experimental)](https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental)
- https://playwright.dev/docs/browsers#webkit
- See https://github.com/cypress-io/cypress/pull/29955 for failed attempt to update.

### LINKED ISSUE #30392: Update the CircleCI executors to use a newer cypress/browsers-internal image
### What would you like?

In order to stay-up-to-date, we should be updating the docker images we use in our CircleCI builds. At the time of this writing, the latest `cypress/browser-internal` images is [node20.18.0-chrome129-ff131](https://hub.docker.com/layers/cypress/browsers-internal/node20.18.0-chrome129-ff131/images/sha256-79b067e82fbff078e283bb5c3ae727f5636f99ebb9157e9bc375351db54ab911?context=explore). We should at a minimum update to this version or if necessary create a newer image to use.

Updating to this image will require addressing:
* https://github.com/cypress-io/cypress/issues/29954
* https://github.com/cypress-io/cypress/issues/29973

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #29973
- Closes #29954
- Closes #30392

### Additional details

Updates WebKit to version 26 as previous versions are no longer available. There are some behavior changes with the update, some which are commented on the PR. 

It looks like there is some cookie ordering inconsistencies between the linux/mac builds of webkit. In order to make this consistent, we check for a strict domain match when running `getCookie` and if no match is found, we then fall back to the apex domain.

Additionally, now that we are updating WebKit, we can now update from Debian Bullseye (Debian 11) to Debian Trixie (Debian 13). The `cypress-docker-images` PR to add `trixie` `base-internal` images is https://github.com/cypress-io/cypress-docker-images/pull/1440

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

---

> [!NOTE]
> Upgrades WebKit (playwright-webkit) and switches CI/Docker images to Debian Trixie, adding strict-domain cookie matching with apex fallback and updating tests/changelog accordingly.
> 
> - **WebKit / Cookies**:
>   - Update `playwright-webkit` to `1.56.1` (and lockfile).
>   - Implement strict-domain cookie matching in `cookieMatches()` (optional `{ strictDomain: true }`).
>   - `webkit-automation`: `getCookie()` first matches exact domain, falls back to apex; normalize cookie props unchanged.
> - **CI/CD & Docker**:
>   - Migrate base images from Bullseye to Trixie: new anchors `base-internal-trixie`, `base-internal-yarn-berry` in `.circleci` and image refs in `docker-compose.yml` and system tests.
>   - Minor pipeline comment fix regarding Debian 11 glibc note.
> - **Tests**:
>   - Add unit tests for strict domain matching; adjust cookie tests (stable sorting) and system test image refs.
> - **Docs/Changelog**:
>   - Changelog: WebKit now prefers fully qualified cookie domain, falls back to apex.
>   - Electron upgrade doc: update image name examples to `-trixie`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2e64deb26a46dc3f415fdd9702056e1b4ce7b943. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@AtofStryker 

- Did you consider https://github.com/cypress-io/cypress/issues/32192 ? Would this be a barrier to updating to Debian 13 trixie?

**Comment by AtofStryker** [comment]
> @AtofStryker
> 
> * Did you consider [V8 Snapshot build failure on newer Linux OS like Debian 13 #32192](https://github.com/cypress-io/cypress/issues/32192) ? Would this be a barrier to updating to Debian 13 trixie?

@MikeMcC399 I don't think for the `cypress-io/cypress` jobs this is a blocker but could be wrong, but it's likely a blocker when we build the binary. Going to confirm with @ryanthemanuel.

File: packages/server/lib/automation/util.ts [hunk 1]
```diff
@@ -12,8 +12,9 @@ export type CyCookie = Pick<chrome.cookies.Cookie, 'name' | 'value' | 'expiratio
 // @ts-ignore
 export type CyCookieFilter = chrome.cookies.GetAllDetails
 
-export const cookieMatches = (cookie: CyCookie | playwright.Cookie, filter?: CyCookieFilter) => {
-  if (filter?.domain && !domainMatch(filter?.domain, cookie.domain)) {
+export const cookieMatches = (cookie: CyCookie | playwright.Cookie, filter?: CyCookieFilter, options?: { strictDomain: boolean }) => {
+  if (filter?.domain) {
+    if (options?.strictDomain ? filter?.domain !== cookie.domain : !domainMatch(filter?.domain, cookie.domain))
```
Comment (jennifer-shehane) [inline packages/server/lib/automation/util.ts:17]: @AtofStryker Does this change require a changelog entry?

**Review by jennifer-shehane — APPROVED** [review]
@AtofStryker Question around whether this requires a changelog entry.

**Review by cacieprins — APPROVED** [review]

File: packages/server/lib/automation/util.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/server/lib/automation/util.ts:17]: going to add a `misc` changelog item

**Comment by AtofStryker** [comment]
@MikeMcC399 it looks like the v8 snapshot issues are a runtime issue and not a build issue and doesn't appear to block building of the binary, so this should go ahead and work, though it doesn't close #32192

File: cli/CHANGELOG.md [hunk 2]
```diff
@@ -20,6 +20,7 @@ _Released 10/20/2025 (PENDING)_
 - Add top padding for command log labels. Addressed in [#32774](https://github.com/cypress-io/cypress/pull/32774).
 - The hitbox for expanding a grouped command has been widened. Addresses [#32778](https://github.com/cypress-io/cypress/issues/32778). Addressed in [#32783](https://github.com/cypress-io/cypress/pull/32783).
 - Have cursor on hover of the AUT URL to show as pointer. Addresses [#32777](https://github.com/cypress-io/cypress/issues/32777). Addressed in [#32782](https://github.com/cypress-io/cypress/pull/32782).
+- Webkit now prefers a cookie's fully qualified `domain` when requesting a cookie value via [`cy.getCookie()`](https://docs.cypress.io/api/commands/getcookie). If none are found, the cookie's apex domain will be used as a fallback. Addressed in [#32852](https://github.com/cypress-io/cypress/pull/32852).
```
Comment (MikeMcC399) [inline cli/CHANGELOG.md]:
```suggestion
- WebKit now prefers a cookie's fully qualified `domain` when requesting a cookie value via [`cy.getCookie()`](https://docs.cypress.io/api/commands/getcookie). If none are found, the cookie's apex domain will be used as a fallback. Addressed in [#32852](https://github.com/cypress-io/cypress/pull/32852).
```

Reference: https://webkit.org/
