### PR TITLE
fix: exit correctly so that darwin does not generate crash report when ctrl+c

### LINKED ISSUE #29228: Cypress crashes on SIGINT
### Current behavior

I'm running cypress and a few other commands using foreman. After tests have run, I Ctrl+C to quit foreman. This used to work fine, but now I'm always receiving a crash report for cypress when exiting. The crash happens when no tests are run as well. This message now displays in the logs for cypress:

> We detected that the Chrome browser process closed unexpectedly.
We have failed the current spec and aborted the run.

### Desired behavior

Cypress and Chrome should quit gracefully.

### Test code to reproduce

.

### Cypress Version

13.7.0

### Node version

v18.19.1

### Operating System

macOS 14.3.1

### Debug Logs

_No response_

### Other

I verified the desired behavior with v13.6.6, so this may have something to do with the recently upgraded `signal-exit` package.

### LINKED ISSUE #29232: Spurious failed spec error closing Cypress Runner window (Electron)
### Current behavior

An error message is output when closing the Cypress Runner using the runner menu although there was no test running.

> We detected that the electron tab running Cypress tests closed unexpectedly.
>
> We have failed the current spec and aborted the run.

### Desired behavior

If the Cypress Runner is closed without aborting any tests, such as by using the runner menu (File > Close Window), then no error message should be output.

### Test code to reproduce

Execute

```shell
cd $(mktemp -d)
git init
npm init -y
npm install cypress
npx cypress open
```

(Select Continue, if first time using Cypress)
Select E2E Testing
Select Continue
Select Electron
Select "Start E2E Testing in Electron"
In Cypress Runner select File > Close Window

image

Note error message:
> We detected that the electron tab running Cypress tests closed unexpectedly.
>
> We have failed the current spec and aborted the run.

### Cypress Version

First reported for versions: `13.0.0` through `13.7.1`
Also reproducible on: `14.5.2` and `15.0.0` to `15.12.0`

### Node version

~~`v20.11.1`~~ `v20.18.0` LTS , `v22.18.0` LTS and `v24.14.0` LTS

### Operating System

Ubuntu `22.04.4` LTS and Ubuntu `24.04.4` LTS
Windows 11

### Debug Logs

```text
cypress:server:browsers:electron close fired on the BrowserWindow { browserWindowUrl: 'http://localhost:33217/__/' } +12s
  cypress:server:browsers:electron closed event fired +6ms
  cypress:server:windows error removing all extensions { err: TypeError: Object has been destroyed at Object.j (<embedded>:4291:111741) at BrowserWindow.<anonymous> (<embedded>:4291:125370)     at Object.onceWrapper (node:events:629:26)     at BrowserWindow.emit (node:events:526:35), extensions: undefined } +29s
  cypress:server:browsers browser instance exit event received { code: undefined, signal: undefined } +10s
  cypress:server:browsers:electron closing remote interface client { options: {} } +1ms
  cypress:server:browsers:cri-client closing cri client { closed: false, target: 'BE5D0EC6AE749684900A400BC823B24D' } +12s
  cypress:server:browsers:browser-cri-client Target.targetDestroyed { event: { targetId: 'BE5D0EC6AE749684900A400BC823B24D' }, closing: true, closed: false, resettingBrowserTargets: false } +12s
  cypress:server:browsers:cri-client not closing, cri client is already closed { closed: true, target: 'BE5D0EC6AE749684900A400BC823B24D' } +23ms
  cypress:server:browsers:cri-client closed cri client { closed: true, target: 'BE5D0EC6AE749684900A400BC823B24D' } +4ms
  cypress:server:browsers:cri-client closing cri client { closed: false, target: 'ws://127.0.0.1:44319/devtools/browser/8e4ecb82-0413-4e70-9dbc-85b1f4070961' } +3ms
  cypress:server:browsers:cri-client closed cri client { closed: true, target: 'ws://127.0.0.1:44319/devtools/browser/8e4ecb82-0413-4e70-9dbc-85b1f4070961' } +7ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 60652 } +5s
  cypress:server:browsers:browser-cri-client browser websocket did not close, page was closed { targetId: 'BE5D0EC6AE749684900A400BC823B24D' } +512ms
We detected that the electron tab running Cypress tests closed unexpectedly.

We have failed the current spec and aborted the run.
```

### Other

- This issue is related to https://github.com/cypress-io/cypress/issues/29228.
- It is a regression from Cypress `12.7.4`.

Edit: replaced repro screenshot

### LINKED ISSUE #33367: Cypress printing raw characters after CTRL C of cypress open
### Current behavior

Launch cypress open on Linux x64
Pick a browser 
On the specs page
Do a CTRL+C on the terminal 

Pressing the up key with show raw characters for that

### Desired behavior

_No response_

### Test code to reproduce

N/A

### Cypress Version

15.10.0

### Debug Logs

```shell

```

### Other

Doesn't occur with Cypress 13.6.6
First occurs with Cypress 13.7.0

Unable to reproduce in dev mode
But getting this behavior with the binaries

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes [#29228](https://github.com/cypress-io/cypress/issues/29228)
- Closes [#29232](https://github.com/cypress-io/cypress/issues/29232)
- Closes [#33367](https://github.com/cypress-io/cypress/issues/33367)

### Additional details
The child (electron) process's `close`/`exit` handler used to call `await getError()` (which called `await getPlatformInfo()`). Doing that async work during teardown can cause process trees to exit out of order, and trigger OS crash reporting.

The stdin `'error'` handler used to `throw err` for unexpected errors. Throwing inside the spawn promise causes an unhandled exception during teardown.

In development mode, Cypress is wrapped by `gulp` so that it can relaunch when files in `@packages/data-context` or `@packages/server` change. The signal handler in `gulpRegistry` was async, and could cause an incorrect teardown order. This could leave the terminal in a bad state, where raw characters would print to the terminal. In windows, the entire process tree must be manually killed because CTRL_C_EVENT (which node interprets as SIGINT)  does not necessarily propagate to child processes.

As well, Cypress was not correctly exiting the `gulp` process when the electron launchpad window was closed. The `beforeExit` event does not fire when the electron window is closed. Gulp now relies on the restart state (triggered by file changes) to determine if it should self-exit or not.

**Gulp (develop mode):** The signal handler in `gulpRegistry` was async and called `await exitAllProcesses()`. Signal handlers must not rely on async work completing. Fix: make the handler synchronous—set `hasExited`, on Windows synchronously kill the process tree (new `psTreeSync` using `pgrep`/`wmic`) with the same signal, then `process.exit(128 + code)`. In `gulpCypress` watch mode, the `isClosing` flag and `beforeExit`-driven logic were removed; the child `exit` handler now exits the gulp process when the child exits unless a restart is in progress, so closing the Electron window in develop mode no longer leaves the gulp process running. `childProcessUtils` now resolves the exit deferred when the child exits so callers observe the exit correctly.
With no async work in these paths and no unhandled throws during teardown, the process and its children shut down in a consistent order and the OS no longer treats it as a crash.

### Steps to test
1. **SIGINT / Ctrl+C (headless):** Run `npx cypress run`, let specs start or run, then press Ctrl+C. Cypress should exit without a crash report and without "Chrome browser process closed unexpectedly" as the last message.
2. **SIGINT / Ctrl+C (open mode):** Run `npx cypress open`, pick a project and browser, then press Ctrl+C in the terminal. There should be no macOS/OS crash report dialog and no raw escape characters when typing in the terminal afterward.
3. **Close runner window:** Run `npx cypress open`, start E2E in Electron, then close the runner via File > Close Window (or equivalent). There should be no spurious "We have failed the current spec and aborted the run" / "closed unexpectedly" message.
4. **Develop mode:** Run the Cypress dev workflow `yarn cypress:open`. When the Electron window opens, close it via the window close button. The gulp process should exit instead of staying running.

### How has the user experience changed?
**Before:** Ctrl+C or closing the runner could trigger a crash report (e.g. "Cypress quit unexpectedly" / Problem Report on macOS), a misleading "Chrome/electron closed unexpectedly" message, or a terminal left showing raw characters. In develop mode, closing the Electron window left the gulp process running.
**After:** Cypress and the browser exit cleanly on Ctrl+C or closing the runner; no crash report and no broken terminal state. In develop mode, closing the Electron window exits the gulp process.

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

---

> [!NOTE]
> **Medium Risk**
> Changes process spawning and signal-handling/teardown paths across CLI and gulp dev workflows, which can impact cross-platform shutdown behavior. Risk is mitigated by added/updated unit tests, but failures would show up as hangs, crash reports, or incorrect exit codes.
> 
> **Overview**
> Ensures Cypress exits cleanly on SIGINT and runner window close by removing async work from critical teardown paths.
> 
> CLI spawn error reporting now precomputes platform info and formats “child process killed” errors synchronously (`getErrorSync`/`syncFormErrorText`), and unexpected `process.stdin` stream errors now reject the spawn promise instead of throwing.
> 
> In `gulp` develop/watch mode, shutdown logic is adjusted so closing the Electron window exits the gulp process unless a restart is in progress, and signal handling is made synchronous; Windows additionally kills the full process tree via new `psTreeSync` (using `pgrep`/`wmic`). Changelog entries and spawn tests are updated accordingly.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit cd2c23b018abbba0fe1b8f10c71740e7466789a8. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: scripts/gulp/tasks/gulpCypress.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export async function startCypressWatch () {
     child = await spawnCypressWithMode('open', 'dev', ENV_VARS.DEV)
 
     child.on('exit', (code) => {
-      if (isClosing) {
+      if (isClosing || !isRestarting) {
```
Comment (cacieprins) [inline scripts/gulp/tasks/gulpCypress.ts]: This is so the gulp process exits appropriately when you x out of the launchpad

File: cli/lib/exec/spawn.ts [hunk 2]
```diff
@@ -131,27 +131,37 @@ function createSpawnFunction (
       debug('spawn args %o %o', args, _.omit(stdioOptions, 'env'))
       debug('spawning Cypress with executable: %s', executable)
 
+      const platform = await util.getPlatformInfo()
+
       const child = cp.spawn(executable, args, stdioOptions)
 
       function resolveOn (event: any): any {
-        return async function (code: any, signal: any): Promise<any> {
+        return function (code: any, signal: NodeJS.Signals): void {
```
Comment (cacieprins) [inline cli/lib/exec/spawn.ts:141]: These callbacks cannot be asynchronous; especially in cases where you want to handle `sigint` correctly.

The callback begins execution during `sigint` but code past the first `await` will not execute - it is unreachable.

**Review by mschile — APPROVED** [review]
