### PR TITLE
chore: fix AUT discovery if frame name is not present

### LINKED ISSUE #32124: Cypress 15: Could not find AUT frame
### Current behavior

[Reproducible example in Slack thread](https://cypressio.slack.com/archives/C094W6ANTC4/p1753991791319469?thread_ts=1753883859.102099&cid=C094W6ANTC4)

```
Error: Could not find AUT frame

This error occurred while validating the created session. Because validation failed immediately after creating the session, we failed the test.
```

Suspect it's related to this change: https://github.com/cypress-io/cypress/pull/31862

Failing around here: https://github.com/cypress-io/cypress/blob/release/15.0.0/packages/server/lib/browsers/cdp_automation.ts#L494

```
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        15.0.0                                                                         │
  │ Browser:        Electron 136                                                                   │
  │ Node Version:   v24.4.1               │
  │ Experiments:    experimentalMemoryManagement=true,experimentalStudio=true                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Desired behavior

Should not error

### Test code to reproduce

Happening during code similar to:
```js
cy.location('pathname', {timeout: 10000}).should('eq', '/customer/account')
```

### Cypress Version

15.0.0

### Node version

24.4.1

### Operating System

Mac

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #32124

### Additional details

In certain cases, the AUT frame name is missing from the CDP `getFrameTree` payload. In the case of the Cypress app, the AUT frame should always be the first frame, followed by the spec fame as it is the order they are created in. This fix falls back to the first child frame if Cypress cannot discover the frame by name. 

Screenshot 2025-08-04 at 12 37 46 PM

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/cdp_automation.ts [hunk 1]
```diff
@@ -492,7 +492,13 @@ export class CdpAutomation implements CDPClient, AutomationMiddleware {
       }
 
       if (!frame) {
-        throw new Error('Could not find AUT frame')
+        // if for whatever reason we cannot identify the AUT frame by name, we will fall back ot the first child frame that exists.
```
Comment (jennifer-shehane) [inline packages/server/lib/browsers/cdp_automation.ts]:
```suggestion
        // if for whatever reason we cannot identify the AUT frame by name, we will fall back to the first child frame that exists.
```

**Review by jennifer-shehane — APPROVED** [review]
The original example is now properly erroring instead of throwing this AUT frame error.
