### PR TITLE
fix: cross-origin logs getting too many snapshots

### LINKED ISSUE #28609: Some Secondary Origin Logs are Getting Too Many Screenshots
### Current behavior

Logs that should create one snapshot when the log is created, like `cy.clock()` or `expect(something).to.be(something)` is incorrectly creating two logs when the logs originate from a secondary origin. 

See some examples:

Primary Origin | Secondary Origin
--|--
|Screen Shot 2023-12-28 at 2 57 45 PM|Screen Shot 2023-12-28 at 2 57 05 PM
Screen Shot 2023-12-28 at 2 58 08 PM|Screen Shot 2023-12-28 at 2 58 51 PM

### Desired behavior

Secondary origin logs should log the same attributes as a primary origin log.

### Test code to reproduce

```
it('primary origin log', () => {
   cy.clock().tick()
   .then(() => {
        expect(true).to.be.true 
    })
})

it('secondary origin', () => {
   cy.origin('secondary', () => {
      cy.visit('secondary')
  })

   cy.clock().tick()
   .then(() => {
        expect(true).to.be.true 
    })
})
```

### Cypress Version

13.6.2

### Node version

16.16.0

### Operating System

MacOS 12.5.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #28609 

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cypress/log.ts [hunk 1]
```diff
@@ -403,24 +409,6 @@ export class Log {
       this.set('next', null)
     }
 
-    if (!Cypress.isCrossOriginSpecBridge) {
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/log.ts:406]: We no longer "pull" for the snapshot from the secondary origin as it can already "push" snapshots.

File: packages/driver/src/cypress/log.ts [hunk 2]
```diff
@@ -384,17 +385,22 @@ export class Log {
...
 
     return this
   }
 
   snapshot (name?, options: any = {}) {
-    // bail early and don't snapshot if we're in headless mode
-    // or we're not storing tests and the protocol is not enabled
-    if ((!this.config('isInteractive') || (this.config('numTestsKeptInMemory') === 0)) && !this.config('protocolEnabled')) {
+    // bail early and don't snapshot if
+    // 1. we're in headless mode, we are
```
Comment (mjhenkes) [inline packages/driver/src/cypress/log.ts]:
```suggestion
    // 1. we're in headless mode
```

**Review by mjhenkes — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]
Seems to be working as expected. @emilyrohrbough do you know when we changed this behavior because I remember we used to have to explicitly get the snapshot from the spec bridge and serialize it. Now it just comes with the log message?

**Comment by emilyrohrbough** [comment]
@AtofStryker I'm not sure what changed, but it appears the snapshot logic handles serializing when it is captured by the log and then the log snapshot is updated and the log is emitting the updated log attributes, which includes the snapshot.

**Review by AtofStryker — APPROVED** [review]
