### PR TITLE
fix: remove private properties, move screenshots in module API results

### LINKED ISSUE #8076: Remove unintentionally exposed private properties from `Module API`
we have several properties on `Module API` test run results that are not useful to users:
`timings`
`testId`
`failedFromHookId`

reasons for removing:
- these properties were not created for use by end users 
- unintentionally couples public `Module API` to dashboard API 
- when we make changes to dashboard API,  we don't want to affect public API

### PR DESCRIPTION
**Pull request by kuceb**
- Closes #8076 

### User facing changelog
- remove unintentionally exposed properties on `Module API`
- `Module API` results now list screenshots nested under each test `attempt` object instead of on the higher level `run` object 

### Additional details
- move e2e tests around timing from 5_spec_isolation to 7_record_spec since timings are no longer on module API result json

### PR Tasks
- [x] wait for merge #3968 

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress-npm-api.d.ts [hunk 1]
```diff
@@ -154,39 +160,36 @@ declare module 'cypress' {
...
-    wallClockStartedAt: dateTimeISO
-    wallClockDuration: ms
+    displayError: string | null
+    attempts: AttemptResult[]
+  }
+
+  interface AttemptResult {
+    state: string
+    error: TestError | null
+    startedAt: dateTimeISO
```
Comment (jennifer-shehane) [inline cli/types/cypress-npm-api.d.ts:182]: attempts have a `startedAt` but don’t have an `endedAt`, is that true or just a type definition error? Just seems to not follow the convention of the rest of the data in run results.

Comment (Bkucera) [reply cli/types/cypress-npm-api.d.ts:182]: that's true, we only have startedAt and duration

File: packages/server/test/e2e/7_record_spec.js [hunk 2]
```diff
@@ -228,185 +229,188 @@ describe('e2e record', () => {
...
-        const firstInstance = requests[1]
-
-        expect(firstInstance.body.groupId).to.eq(groupId)
-        expect(firstInstance.body.machineId).to.eq(machineId)
-        expect(firstInstance.body.spec).to.eq(
-          'cypress/integration/record_error_spec.coffee',
-        )
 
-        const firstInstancePut = requests[2]
+      console.log(stdout)
```
Comment (brian-mann) [inline packages/server/test/e2e/7_record_spec.js:242]: comment

**Review by brian-mann — APPROVED** [review]
