### PR TITLE
fix: lower-cased HTTP methods can be used with cy.intercept.

### LINKED ISSUE #9313: cy.intercept does not work with lowercase HTTP methods
Cypress v6.0.0 with new `cy.intercept` should match the behavior of `cy.route`

* it should understand both lowercase and uppercase HTTP methods

Reproducible example from https://github.com/cypress-io/cypress-example-recipes/tree/get-vs-GET

file examples/stubbing-spying__intercept/cypress/integration/spy-on-fetch-spec.js

```js
describe.only('get vs GET', () => {
  context('cy.route', () => {
    let polyfill

    // grab fetch polyfill from remote URL, could be also from a local package
    before(() => {
      const polyfillUrl = 'https://unpkg.com/unfetch/dist/unfetch.umd.js'

      cy.request(polyfillUrl)
      .then((response) => {
        polyfill = response.body
      })
    })

    it('works with GET', function () {
      cy.server()
      cy.route('get', '/favorite-fruits').as('fruits')
      cy.visit('/', {
        onBeforeLoad (win) {
          delete win.fetch
          win.eval(polyfill)
          win.fetch = win.unfetch
        },
      })

      cy.wait('@fruits')
    })

    it('works with get', function () {
      cy.server()
      cy.route('get', '/favorite-fruits').as('fruits')
      cy.visit('/', {
        onBeforeLoad (win) {
          delete win.fetch
          win.eval(polyfill)
          win.fetch = win.unfetch
        },
      })

      cy.wait('@fruits')
    })
  })

  context('cy.intercept', () => {
    it('works with GET', function () {
      cy.intercept('GET', '/favorite-fruits').as('fruits')
      cy.visit('/')

      cy.wait('@fruits')
    })

    // NOTE: does NOT work with "get"
    it.skip('works with get', function () {
      cy.intercept('get', '/favorite-fruits').as('fruits')
      cy.visit('/')

      cy.wait('@fruits')
    })
  })
})
```

if we run just the skipped test

```js
it.only('works with get', function () {
  cy.intercept('get', '/favorite-fruits').as('fruits')
  cy.visit('/')

  cy.wait('@fruits')
})
```

The wait times out

The network call does happen

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #9313 

### User facing changelog
Lower-cased HTTP methods can be used with cy.intercept. 

### Additional details
* Why was this change necessary? => `cy.intercept` only allowed upper-cased HTTP methods. 
* What is affected by this change? => N/A
* Any implementation details to explain? => N/A

### How has the user experience changed?
N/A

### PR Tasks
* [x] Have tests been added/updated?
* [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky failure.

File: packages/driver/src/cy/net-stubbing/add-command.ts [hunk 1]
```diff
@@ -279,7 +279,7 @@ export function addCommand (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy,
         handler = arg2
 
         return {
-          method: matcher,
+          method: matcher.toUpperCase(),
```
Comment (flotwig) [inline packages/driver/src/cy/net-stubbing/add-command.ts:282]: this doesn't account for the use case `cy.intercept({ method: 'some-lowercase-method' })`, only the shorthand `cy.intercept('some-lowercase-method')` - updated to lowercase on the backend instead

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 2]
```diff
@@ -209,6 +209,21 @@ describe('network stubbing', { retries: 2 }, function () {
       cy.wait('@create')
     })
 
+    // https://github.com/cypress-io/cypress/issues/9313
+    it('lower-cased method works', () => {
+      cy.intercept('post', 'http://dummy.restapiexample.com/api/v1/create').as('create')
```
Comment (flotwig) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:214]: in the future, we should try to use the internal server for tests only, not 3rd party - updated this + the earlier test

**Review by flotwig — APPROVED** [review]
thanks @sainthkh  :)
