### PR TITLE
fix: support ESM projects using TypeScript with ts-node/esm

### LINKED ISSUE #21939: Investigate adding support for ts-node/esm
### Current behavior

In 10.0 using `package.json` with `"type": "module"` with `.ts` will not work out of the box without `esbuild` installed.

### Desired behavior

Cypress should use the `ts-node/esm` builder to support loading `.ts` from esmodules. https://github.com/TypeStrong/ts-node#commonjs-vs-native-ecmascript-modules

### Test code to reproduce

```
cd system-tests
yarn test config_modules_spec
```

`config-cjs-and-esm/config-with-ts-module` fails but it should pass

### Cypress Version

10.0

### Other

Related to #21574

### LINKED ISSUE #22074: Never uses esbuild to process cypress.config
### Current behavior

Attempts to use esbuild but never actually does so successfully.

### Details

**EDIT**: I removed the `esbuild` code path for now, as part of this PR https://github.com/cypress-io/cypress/pull/22118 where we use `ts-node/esm` to handle ES modules. You can reference that if/when we decided to work on this issue and revisit how we use esbuild in Cypress.

On this part of the code:

https://github.com/cypress-io/cypress/blob/a264373df7ebf74bdf02dcc44f3664d50ab48fab/packages/server/lib/plugins/child/run_require_async_child.js#L120-L122

We do:

```js
try {
  require.resolve('esbuild', { paths: [process.cwd()] })

  const { bundleRequire } = require('bundle-require')

  return (await bundleRequire({ filepath: file })).mod
} catch (err) {
  if (err.stack.includes(`Cannot find module 'esbuild'`)) {
    // ...
  }

  throw err
}
```

The problem is this will **almost always** fail - we check if `esbuild` is in the user's `node_modules`, via `process.cwd` (which is going to be `projectRoot`) but then require `bundle-require` from the binary's `node_modules`, which also assumes `esbuild` is present in the binary's `node_modules` (which it never is - we do not ship `esbuild` with the binary).

For this to work, we would need to `esbuild` with the binary. It's around 8MB:

```sh
/Users/lachlan/code/dump/cypress10-upgrade-issue
$ du -h node_modules/esbuild                                                                            
8.0M	node_modules/esbuild/bin
4.0K	node_modules/esbuild/node_modules/.bin
4.0K	node_modules/esbuild/node_modules
100K	node_modules/esbuild/lib
8.1M	node_modules/esbuild
```

### Desired behavior

Either we ship `esbuild` or find some way to utilise the user's `esbuild` (cannot think of one). Or, just don't have this code (it's not doing anything). 

It's also not clear why we even include esbuild - Node supports native ES modules now, I'm not sure this is really necessary.

### Test code to reproduce

- Grab project from https://github.com/lmiller1990/cypress-esbuild-never-used
- Attempt to run it, using `DEBUG=cypress:life* yarn cypress open`
- You can see it thinks `esbuild` is available by looking in the user's `node_modules`, but then fails with "could not find module esbuild".

Here is the output.

```
  cypress:lifecycle:child:run_require_async_child:56066 User is loading an ESM config file +14ms
  cypress:lifecycle:child:run_require_async_child:56066 Trying to use esbuild to run their config file. +0ms
  cypress:lifecycle:child:run_require_async_child:56066 They have esbuild, so we'll load the configFile via bundleRequire +2ms
  cypress:lifecycle:child:run_require_async_child:56066 User doesn't have esbuild. Going to use native node imports. +9ms
```

Larger output:

```sh
$ /Users/lachlan/code/dump/cypress-mjs/node_modules/.bin/cypress open
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/Users/lachlan/Library/Caches/Cypress/10.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/Users/lachlan/code/dump/cypress-mjs', '--file', '/Users/lachlan/code/dump/cypress-mjs/cypress.config.js' ], childOptions: { stdio: 'pipe', cwd: '/Users/lachlan/code/dump/cypress-mjs', execPath: '/Users/lachlan/.nvm/versions/node/v16.14.2/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +8ms
  cypress:lifecycle:child:run_require_async_child:56066 configFile: /Users/lachlan/code/dump/cypress-mjs/cypress.config.js +0ms
  cypress:lifecycle:child:run_require_async_child:56066 projectRoot: /Users/lachlan/code/dump/cypress-mjs +1ms
  cypress:lifecycle:child:run_require_async_child:56066 register typescript for required file +0ms
  cypress:lifecycle:child:run_require_async_child:56066 try loading /Users/lachlan/code/dump/cypress-mjs/cypress.config.js +25ms
  cypress:lifecycle:child:run_require_async_child:56066 User is loading an ESM config file +14ms
  cypress:lifecycle:child:run_require_async_child:56066 Trying to use esbuild to run their config file. +0ms
  cypress:lifecycle:child:run_require_async_child:56066 They have esbuild, so we'll load the configFile via bundleRequire +2ms
  cypress:lifecycle:child:run_require_async_child:56066 User doesn't have esbuild. Going to use native node imports. +9ms
  cypress:lifecycle:child:run_require_async_child:56066 loaded config file /Users/lachlan/code/dump/cypress-mjs/cypress.config.js +257ms
  cypress:lifecycle:child:run_require_async_child:56066 loaded config from /Users/lachlan/code/dump/cypress-mjs/cypress.config.js { e2e: { setupNodeEvents: [Function: setupNodeEvents] } } +1ms
  cypress:lifecycle:ProjectConfigIpc loadConfig:reply +2s
  cypress:lifecycle:ProjectConfigManager config is loaded for file /Users/lachlan/code/dump/cypress-mjs/cypress.config.js null +0ms
```

### Cypress Version

10.0.2

### Other

_No response_

### LINKED ISSUE #22096: Initializing Cypress v10 on a "type": "module" project with TypeScript results in an `[ERR_UNKNOWN_FILE_EXTENSION]` error
### Current behavior

Initializing Cypress v10 on a new Next.js + TypeScript project results in an `[ERR_UNKNOWN_FILE_EXTENSION]` error.

As far as I can tell, this issue doesn't appear to be:

- Specific to the OS
- Specific to the contents of the `package.json` dependencies
- Specific to the contents of the `tsconfig.json` file

I tried changing all 3 but it didn't appear to have an impact, I still get the `[ERR_UNKNOWN_FILE_EXTENSION]` error.

### Desired behavior

Set up E2E testing in a TypeScript project in a way where this error doesn't occur.

### Test code to reproduce

1. `npx create-next-app@latest foobar --ts`
2. Add `{ "type": "module" }` to the `package.json`
3. Change `next.config.js` to use ESM (just change `module.exports` to `export default`)
4. `npm install cypress@10.0.2`
5. `npx cypress open`
6. Choose "E2E Testing"
7. Scroll down, click "Continue"
8. Error!

Screen Shot 2022-06-02 at 10 13 07 PM

### Cypress Version

v10.0.2

### Other

Originally I had [this issue](https://github.com/cypress-io/cypress/issues/22038):

```
Error [ERR_REQUIRE_ESM]: require() of ES Module cypress.config.js
```

After the release of 10.0.2, I have [this issue](https://github.com/cypress-io/cypress/issues/21997): 

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for cypress.config.ts
```

---

This issue is closely related to [this issue](https://github.com/cypress-io/cypress/issues/22071), but I'm adding Cypress to a new project rather than doing an upgrade.

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/22096
- Closes https://github.com/cypress-io/cypress/issues/21939

### User facing changelog

Support TypeScript projects using `"type": "module"` using `ts-node/esm`.

### Additional details

The problem is if you are using `"type": "module"`, Node.js will use it's ESM loader to load your code. If you are using a `ts` extension, which Node.js does not know about out of the box, you get the various errors we've seen reported.

The original solution was to use `esbuild` to try load TS files if the initial `require('cypress.config...`) failed, but it's not working as expected, as [explained here](https://github.com/cypress-io/cypress/issues/22074#issuecomment-1147097883). I removed the `esbuild` code path for now. I noted this [here](https://github.com/cypress-io/cypress/issues/22074) so we can bring it back in the future, if needed.

The solution introduced here is to use the [ESM support that `ts-node` ships](https://github.com/TypeStrong/ts-node/issues/1007), as recommended in #21939. We rely on `ts-node` in the project and already ship it, so it makes sense to continue to use it where we can.

### Steps to test

0. Reproduce https://github.com/cypress-io/cypress/issues/22096/ with the latest binary from npm and verify problem
1. Grab this branch and build the binary locally
2. Open the repro with the new binary, it should work now

### How has the user experience changed?

Can correctly load `cypress.config.ts` for `"type": "module"` projects.

## The workflow is now:

image

## The old workflow (shows problem):

<details>
<summary>Show old workflow diagram</summary>
image
</details>

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/data-context/src/data/ProjectConfigManager.ts [hunk 1]
```diff
@@ -260,10 +260,17 @@ export class ProjectConfigManager {
...
+        this.options.ctx.nodePath,
+        this.options.projectRoot,
+        this.configFilePath,
+        this.options.configFile,
+        (cypressError: CypressError, title?: string | undefined) => {
+          this._state = 'errored'
+          this.options.ctx.onError(cypressError, title)
+        },
+        this.options.ctx.onWarning,
+      )
```
Comment (lmiller1990) [inline packages/data-context/src/data/ProjectConfigManager.ts:273]: Code is the same, I just spaced it out so it's easier to read.

File: packages/server/lib/plugins/child/run_plugins.js [hunk 2]
```diff
@@ -1,4 +1,3 @@
-// @ts-check
 // this module is responsible for loading the plugins file
```
Comment (lmiller1990) [inline packages/server/lib/plugins/child/run_plugins.js:1]: For some reason this caused errors to be raised when using `ts-node/esm`, I don't quite know why, so I just removed the `@ts-check`. These files are not very type safe anyway, I don't think the `ts-check` is doing too much with the very lax `tsconfig.json` in `packages/server`, anyway. We can work on making it nice and strict in the future.

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 3]
```diff
@@ -238,6 +240,37 @@ export class ProjectConfigIpc extends EventEmitter {
 
     debug('fork child process %o', { CHILD_PROCESS_FILE_PATH, configProcessArgs, childOptions: _.omit(childOptions, 'env') })
 
+    let isProjectUsingESModules = false
```
Comment (mjhenkes) [inline packages/data-context/src/data/ProjectConfigIpc.ts:243]: With this solution should any code be removed? I'm not super familiar with this code, but it seems like we might have some dead references esbuild code if this block takes over that responsibility. You mention a couple of places in your [explanation](https://github.com/cypress-io/cypress/issues/22074#issuecomment-1147097883), can we clean any of those up?

File: system-tests/projects/config-cjs-and-esm/config-with-ts-module/tsconfig.json [hunk 4]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (AtofStryker) [inline system-tests/projects/config-cjs-and-esm/config-with-ts-module/tsconfig.json:1]: Any idea why the linter did not get run against this? Either way that's an easy one to clear up 😅

**Review by ZachJW34 — COMMENTED** [review]
I'm a bit confused with how we are dealing with esm. This PR adds the `ts-node/esm`loader to [where we start the config process](https://github.com/cypress-io/cypress/blob/e3f65fb01fdfa79f56fe055de020c28eb2636ac6/packages/data-context/src/data/ProjectConfigIpc.ts#L243), but we still register [ts-node in the child process](https://github.com/cypress-io/cypress/blob/b83bdc2000144126d9b0caf959be0ced01e44e6e/packages/server/lib/plugins/child/run_require_async_child.js#L27) and then still use [esbuild to require the user's config](/Users/zachjw/work/cypress/packages/server/lib/plugins/child/run_require_async_child.js). We now have three places where configure ts/esm...
Can we not have one place for all this ts/esm logic?

File: packages/data-context/src/data/ProjectConfigIpc.ts (hunk 3 above)
Comment (lmiller1990) [reply packages/data-context/src/data/ProjectConfigIpc.ts:243]: I do think we can clean up some of the `esbuild` code (it's not working properly; we could delete it all, if we decide not to go down the esbuild route).

I figured I'd leave it untouched and make the changes as minimal as possible here. Having read your comment, I'm thinking we could probably delete it, and bring it back when re-visiting https://github.com/cypress-io/cypress/issues/22074.

File: system-tests/projects/config-cjs-and-esm/config-with-ts-module/tsconfig.json (hunk 4 above)
Comment (lmiller1990) [reply system-tests/projects/config-cjs-and-esm/config-with-ts-module/tsconfig.json:1]: Something in here I think... https://github.com/cypress-io/cypress/blob/develop/.eslintignore
Cleaned it up :+1:

**Comment by lmiller1990** [comment]
@ZachJW34 good point on the "register `ts-node/esm` then register `ts-node`. I think we should just run the entire sub-process with `ts-node` or `ts-node/esm` - one place to do the `ts-node` things. I'll see if there are any downsides to this.

As for `esbuild`, as alluded to https://github.com/cypress-io/cypress/issues/22074 and https://github.com/cypress-io/cypress/pull/22118#discussion_r890161200, that code path actually doesn't do anything in prod (a bug which we did not realize until now).

File: packages/data-context/src/data/ProjectConfigIpc.ts (hunk 3 above)
Comment (lmiller1990) [reply packages/data-context/src/data/ProjectConfigIpc.ts:245]: I tried removing the `esbuild` code path here: https://github.com/cypress-io/cypress/pull/22118/commits/f1ed50824aa7ebb5b38b439b7403bf70835614d2. We can revisit how best to use esbuild, if users want to use it, in the near future.

**Comment by lmiller1990** [comment]
@ZachJW34 I tried to improve the module loading logic and move it to one place. Here's what I came up with: https://github.com/cypress-io/cypress/blob/dcd80ae558dafa6230dc8b43f8bd6c30fecba02a/packages/data-context/src/data/ProjectConfigIpc.ts#L260-L290

Now instead of registering `ts-node` by calling `tsNodeUtil.register()` in the `run_require_async_child`, we register it using Node's `--require` hook (basically the same thing, from my understanding). Using `--require` is one of the two ways discussed [in their docs](https://typestrong.org/ts-node/docs/usage#node-flags-and-other-tools), along with `--loader` (more experimental, but that's how they recommend using their `ts-node/esm` code.

File: packages/server/lib/plugins/child/run_require_async_child.js [hunk 5]
```diff
@@ -110,25 +96,16 @@ function run (ipc, file, projectRoot) {
     debug('User is loading an ESM config file')
 
     try {
-      debug('Trying to use esbuild to run their config file.')
```
Comment (lmiller1990) [inline packages/server/lib/plugins/child/run_require_async_child.js:113]: I've removed this for now, we can definitely integration w/ the user's esbuild, but I think that should be done separately, since there's some unknowns.

I've called out this code deletion and referenced it in the `esbuild` issue so we don't forget about it: https://github.com/cypress-io/cypress/issues/22074

File: packages/server/test/unit/plugins/child/run_require_async_child_spec.js [hunk 6]
```diff
@@ -17,28 +15,6 @@ describe('lib/plugins/child/run_require_async_child', () => {
...
-        'cypress.config.js',
-      )
-
-      expect(tsNodeUtil.register).to.be.calledOnce
-    })
-
-    // FIXME: need to validate that TS is checked once when ts is not found as well
-    it.skip('checks for typescript only once if typescript module was not found')
-  })
-
```
Comment (lmiller1990) [inline packages/server/test/unit/plugins/child/run_require_async_child_spec.js:41]: We don't register ts-node in the child process anymore, instead, we run the child process with `--require server/lib...../register_ts_node`. This also means we don't need the check to avoid the double registration anymore.

File: system-tests/projects/config-cjs-and-esm/config-with-ts-module/package.json [hunk 7]
```diff
@@ -1,6 +1,7 @@
 {
   "dependencies": {
-    "find-up": "6.3.0"
+    "find-up": "6.3.0",
+    "typescript": "4.7.3"
```
Comment (lmiller1990) [inline system-tests/projects/config-cjs-and-esm/config-with-ts-module/package.json:4]: A lot of these system tests are very misleading - you cannot have a typescript without `typescript` in the `dependencies`, for example.

**Review by tgriesser — CHANGES_REQUESTED** [review]

**Comment by jordanpowell88** [comment]
👀

**Comment by lmiller1990** [comment]
@tgriesser trying `ts-node/esm/transpile-only` https://github.com/cypress-io/cypress/pull/22118/commits/b8ca9555db201fd4d1e61be671b2da9436bf401b thanks!

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 8]
```diff
@@ -107,6 +111,16 @@ export class ProjectConfigIpc extends EventEmitter {
...
+  hasTypeScriptInstalled () {
+    try {
+      require.resolve('typescript', { paths: [this.projectRoot] })
+
+      return true
+    } catch (e) {
+      return false
+    }
+  }
+
```
Comment (mjhenkes) [inline packages/data-context/src/data/ProjectConfigIpc.ts:123]: Can we share this function with the above file so we just have one implementation of it?

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 9]
```diff
@@ -238,6 +252,59 @@ export class ProjectConfigIpc extends EventEmitter {
...
+    }
+
+    if (!childOptions.env) {
+      childOptions.env = {}
+    }
+
+    // If they've got TypeScript installed, we can use
+    // ts-node for CommonJS
+    // ts-node/esm for ESM
+    if (this.hasTypeScriptInstalled()) {
```
Comment (mjhenkes) [inline packages/data-context/src/data/ProjectConfigIpc.ts:273]: This function is pretty similar to what we have above in `MigrationActions.ts`. Is there any way we could share the code? Is using ESModules not a possibility in `MigrationActions.ts`?

**Comment by lmiller1990** [comment]
- TODO: binary tests
- TODO: "module": "esnext" and CommonJS conflict?

File: packages/data-context/src/actions/MigrationActions.ts [hunk 10]
```diff
@@ -88,6 +100,23 @@ export async function processConfigViaLegacyPlugins (projectRoot: string, legacy
     const configProcessArgs = ['--projectRoot', projectRoot, '--file', cwd]
     const CHILD_PROCESS_FILE_PATH = require.resolve('@packages/server/lib/plugins/child/require_async_child')
 
+    // use ts-node if they've got typescript installed
+    // this matches the 9.x behavior, which is what we want for
+    // processing legacy pluginsFile (we never supported `"type": "module") in 9.x.
+    if (hasTypeScriptInstalled(projectRoot)) {
```
Comment (lmiller1990) [inline packages/data-context/src/actions/MigrationActions.ts:106]: We can share `hasTypeScriptInstalled`?

Comment (lmiller1990) [reply packages/data-context/src/actions/MigrationActions.ts:106]: Can we share this with the other implementation?

**Review by ZachJW34 — APPROVED** [review]
Gave it thorough test across packages with TS and `"type": "module"` and it works like a charm. We synced on this, going to ✅

File: packages/data-context/src/data/ProjectConfigIpc.ts (hunk 9 above)
Comment (lmiller1990) [reply packages/data-context/src/data/ProjectConfigIpc.ts:273]: I thought about this a bit more and 9.x did **not** support ES Modules, and the plugin resolution needs to match exactly what 9.x did to work the same - I see some potential risk in sharing this code, since it means we'd be doing something slightly differently and there might be some edge cases around migrating projects we haven't considered.

File: packages/data-context/src/data/ProjectConfigIpc.ts (hunk 8 above)
Comment (lmiller1990) [reply packages/data-context/src/data/ProjectConfigIpc.ts:123]: Done.

File: packages/data-context/src/actions/MigrationActions.ts [hunk 11]
```diff
@@ -67,6 +69,16 @@ export function getDiff (oldConfig: any, newConfig: any) {
...
+function hasTypeScriptInstalled (projectRoot: string) {
+  try {
+    require.resolve('typescript', { paths: [projectRoot] })
+
+    return true
+  } catch (e) {
+    return false
+  }
+}
+
```
[the remark this answers is not in the document]
Comment (lmiller1990) [reply packages/data-context/src/actions/MigrationActions.ts:81]: Done.

**Comment by lmiller1990** [comment]
I address comments and everything is green. This is a pretty big change in terms of additional complexity - we've got good coverage and I did a bunch of manual testing of the binary. 

I also noticed we sometimes were propagating incorrect errors, so I fixed that, too. For example, we correctly warn if you try importing ESM only in a CJS environment (were not doing this before).

**Review by mjhenkes — APPROVED** [review]

**Review by tgriesser — APPROVED** [review]

**Comment by ZachJW34** [comment]
Looks like we have a legit [windows failure](https://app.circleci.com/pipelines/github/cypress-io/cypress/39163/workflows/d16af602-4bdc-4b69-9d92-b8ce4cc8ab37/jobs/1597177/steps). I was able to reproduce this by creating a simple cypress + typescript + type=module on windows. There is an error loading the config, not related to migration. I'll spend some time today looking into what's going on

**Comment by lmiller1990** [comment]
@ZachJW34 bizarrely it was a test only failure - I did what the test is supposed to do and it was fine.

Either way, this seems to have fixed it, bizarrely ... https://github.com/cypress-io/cypress/pull/22118/commits/9c37ba6d6c2338a1a647de2affe293583faef774

Windows CI is still tanking but I watched every single one of those specs pass on my local windows machine - I'm not sure what's going on but lately Windows CI is not in a good place. I'll do some more testing but I don't think any of those failures or flake are from this PR.

**Comment by lmiller1990** [comment]
<details><summary>Run windows tests locally #1</summary>
```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  cypress-in-cypress-component.cy.ts       01:03        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  cypress-in-cypress-e2e.cy.ts             01:26       13       13        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  cypress-in-cypress-run-mode.cy.ts        00:17        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  cypress-in-cypress.cy.ts                 01:09       11       11        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  cypress-origin-communicator.cy.ts        00:33        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  reporter_header.cy.ts                    00:25        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  runs.cy.ts                               02:55       28       28        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  settings.cy.ts                           01:27       21       21        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  sidebar_navigation.cy.ts                 01:11       20       19        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specs.cy.ts                              03:22       28       28        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specs_list_actual_git_repo.cy.ts         00:15        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specs_list_component.cy.ts               00:30        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specs_list_e2e.cy.ts                     01:05       20       18        -        2        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specs_list_no_git_repo.cy.ts             00:07        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  top-nav.cy.ts                            01:45       23       22        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  logger.cy.ts                             153ms        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  reporter.errors.cy.ts                    03:34       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  reporter.hooks.cy.ts                     00:35        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  retries.mochaEvents.cy.ts                00:56        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  retries.ui.cy.ts                         01:46       18       17        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  runner.mochaEvents.cy.ts                 00:46        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  runner.ui.cy.ts                          02:16       24       23        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  sessions.ui.cy.ts                        00:43        7        7        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  authChange-subscription.cy.ts            00:58        6        5        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  baseErrorChange-subscription.cy.ts       00:12        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  configChange-subscription.cy.ts          00:18        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  createCloudOrgModal-subscription.cy      00:22        1        1        -        -        - │
  │    .ts                                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  specChange-subscription.cy.ts            01:00       13       13        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  issue-18042.cy.js                        00:11        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  issue-9162.cy.js                         00:11        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  2 of 30 failed (7%)                      31:32      313      306        2        5        -
```
</details>

**Comment by chinchang** [comment]
Even after this fix, I still get `Your configFile is invalid: /home/runner/work/..../cypress.config.ts` error.
Are there any post-upgrade changes required to support a ts project?

**Comment by hanna-becker** [comment]
We changed the target in cypress's tsconfig from "es5" to "es2019" to get it to work.

**Comment by lmiller1990** [comment]
> Even after this fix, I still get `Your configFile is invalid: /home/runner/work/..../cypress.config.ts` error. Are there any post-upgrade changes required to support a ts project?
> 
> I am using this on a nextJS project. It doesn't/can't have `type:module` in package.json.

@chinchang can you open a new issue with a reproduction? This issue was specifically for ESM support, which means projects with `"type": "module"`.

No changes should be required. If it's not working as expected, it's a bug and I will fix it for you. I've used Cypress 10 with Next.js projects before, but Next.js projects come in many different configurations - please share your reproduction in a new issue. 🙏

**Comment by a-churchill** [comment]
I also see the `Your configFile is invalid` error, with the message:
```txt
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" 
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:244:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Loader.import (internal/modules/esm/loader.js:178:17)
```

This is in a project that worked fine with v10.0.3; I made no changes other than upgrading to 10.3.0 and I see this issue.

We use yarn v2 and TypeScript - maybe this is related to yarn v2's different behavior with `require.resolve`/`require`?

Happy to give more info if it's helpful, let me know what I can do!

**Comment by lmiller1990** [comment]
@a-churchill a minimal reproduction would be super useful. If you could provide that, I can definitely take a look.

**Comment by andrei-dascalu** [comment]
In my case, with a default Cypress setup in an evironment that doesn't provide typescript will result in this error. If typescript is provided (either in locap package.json or linked globally), it's all good.
It's strange though that the official docker image of Cypress doesn't provide typescript globally since the default config is now TS.

**Comment by lmiller1990** [comment]
The default config is only TS if you have it installed, otherwise we default to JS.

A default setup should definitely not error. How do I repro - just create a new project, install Cypress, and open it? This works for me -- what Node.js version do you have?
