### PR TITLE
fix: Exit when both --e2e and --component flags are passed in

### LINKED ISSUE #18846: Error/warn when passing both --e2e and --component flags together
### What would you like?

For `cypress run`, it should error and exit 1.

For `cypress open`, it should display the e2e/component picker in the launchpad wizard and show a warning that you can't pass both flags.

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes #18846 

### User facing changelog
When incompatible flags are passed in, we exit rather than assuming which the user preferred.
`cypress open --e2e --component`
and 
`cypress run --e2e --component`
are both now errors and exit immediately.

### How has the user experience changed?
Previously, we would assume end-to-end, and run/open cypress in that mode. Now, we exit with an error:

image

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: cli/lib/util.js [hunk 1]
```diff
@@ -241,6 +241,14 @@ const parseOpts = (opts) => {
 
   debug('parsed cli options %o', cleanOpts)
 
+  if (cleanOpts.component && cleanOpts.e2e) {
+    util.logErrorExit1(new Error(stripIndent`
+      Error: You passed both --component and --e2e, but only one can be provided.
+
+      See https://docs.cypress.io/ for more information on testing types.
```
Comment (BlueWinds) [inline cli/lib/util.js:248]: This is the same link Launchpad uses when you click "need help" on the "learn more about testing types" dialog. Hopefully we'll have a better documentation link at some point, but for now this was the best I could find.

Comment (jennifer-shehane) [reply cli/lib/util.js:248]: Needs to be an on link. I don't think this doc exists, but they should be creating 'on' links so that they can later link them to a generated doc. I'll talk to the CT team about this. 

```suggestion
      See https://on.cypress.io/ for more information on testing types.
```

File: cli/lib/util.js [hunk 2]
```diff
@@ -241,6 +241,14 @@ const parseOpts = (opts) => {
 
   debug('parsed cli options %o', cleanOpts)
 
+  if (cleanOpts.component && cleanOpts.e2e) {
```
Comment (emilyrohrbough) [inline cli/lib/util.js:244]: Can we move the error text to https://github.com/cypress-io/cypress/blob/develop/cli/lib/errors.js?

File: cli/lib/util.js (hunk 1 above)
Comment (BlueWinds) [reply cli/lib/util.js]: Looks like the launchpad isn't quite as consistent with this as it should be:

image

**Review by jennifer-shehane — APPROVED** [review]
This is good from a product standpoint. I talked to Brian about this.

File: cli/lib/util.js (hunk 2 above)
Comment (BlueWinds) [reply cli/lib/util.js]: Done.

I had not realized exactly how many different ways we have to throw errors in the command line. It might be a worthwhile project to examine and consider unifying at some point.

**Review by emilyrohrbough — APPROVED** [review]
