### PR TITLE
Ignore invalid Set-Cookie values

### LINKED ISSUE #6890: [Cypress version 4.3.0]TypeError: Cannot read property 'key' of undefined
@flotwig 
### Current behavior:
So when I load our live site using cy.visit('https://onlinedoctor.lloydspharmacy.com') using cypress version 4.3.0 - I get the below error. 
image
image

### Desired behavior:

I expect to be able to load our public site without any issues. 

### Test code to reproduce

I think to repproduce this issue just simply access our live site using cy.visit('https://onlinedoctor.lloydspharmacy.com');
Please try and replicate with the version set up 

### Versions

Cypress version - 4.3.0
Chrome - 80
Windows 10 - 64 bit
Node 12.16.1

I was expecting for it to work after the bug fix for this ticket - https://github.com/cypress-io/cypress/issues/5602

image

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6890

### User facing changelog

- Fixed an issue where invalid `Set-Cookie` values could cause requests to fail with a "cannot read property key of undefined" error. Now, invalid `Set-Cookie` values will be ignored.

### Additional details

- previously, this error was hidden behind the "Parse Error: Invalid header character", which was fixed in #5988 
- some users who were experiencing that error before 4.3.0 are now seeing this error
- correct way forward is to ignore the invalid values: https://github.com/cypress-io/cypress/issues/6890#issuecomment-609913483

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/request.coffee [hunk 1]
```diff
@@ -504,14 +508,18 @@ module.exports = (options = {}) ->
...
+        automationCmd = 'set:cookie'
 
-        cookie.sameSite = convertSameSiteToughToExtension(cookie.sameSite, cyCookie)
+        if expiry <= 0
+          automationCmd = 'clear:cookie'
 
-        automationFn('set:cookie', cookie)
+        automationFn(automationCmd, cookie)
+        .catch (err) ->
+          debug('automation failed clearing cookie %o', { automationCmd, cookie, err })
```
Comment (flotwig) [inline packages/server/lib/request.coffee:522]:
```suggestion
          debug('automation threw an error during cookie change %o', { automationCmd, cyCookie, cookie, err })
```

File: packages/server/lib/request.coffee [hunk 2]
```diff
@@ -489,6 +489,10 @@ module.exports = (options = {}) ->
 
         debug('parsing cookie %o', { cyCookie, toughCookie: cookie })
 
+        if not cookie
+          debug('tough-cookie failed to parse, ignoring')
```
Comment (jennifer-shehane) [inline packages/server/lib/request.coffee:493]:
```suggestion
          // ignore invalid cookies (same as browser behavior)
          // https://github.com/cypress-io/cypress/issues/6890
          debug('tough-cookie failed to parse, ignoring')
```
