### PR TITLE
fix: ensure that we capture service worker requests

### LINKED ISSUE #28516: Protocol: Fix issue with assets routed to the service worker being captured by protocol
### Current Behavior

Correlating requests that route through service workers will sometimes mismatch and have the proxy request from the service worker get matched with a CDP request from the page. This will have the practical effect of causing correlation timeouts to occur, or assets to not be properly captured for Test Replay (which may cause things like styles to not apply properly).

### Desired Behavior

All requests should be correlated properly

### Cypress Version
13.3.2

### Node version
v18.15.0

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28516

### Additional details

The root of this problem is that when requests are controlled by a service worker, CDP will receive:

1. Request from the Page
2. Request from the Service Worker

However, the proxy will only receive the request from the Service Worker. Since prerequest correlation operates as a queue, the proxy request from the Service Worker will incorrectly get correlated with the CDP request from the Page.

To fix this, we have to know when a request is controlled by a service worker and in that case, we ensure that the CDP request from the page is not marked for correlation since we know that it will be actually triggered by the Service Worker. To determine that the request is controlled by a Service Worker, we will start using the ServiceWorker CDP domain and use it in combination with the initiators of the CDP requests to determine when a given request is scoped to be controlled by the Service Worker

### Steps to test

I have added system tests to cover these scenarios.

### How has the user experience changed?

Test Replay will properly correlate assets when they are routed through a Service Worker

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/proxy/lib/http/index.ts [hunk 1]
```diff
@@ -429,10 +430,13 @@ export class Http {
     }
   }
 
-  reset () {
+  reset (options: { fullReset?: boolean } = {}) {
```
Comment (mschile) [inline packages/proxy/lib/http/index.ts]: How would someone know if something belongs in a `fullReset`? Would it be better to just explicitly call out reseting prerequests (i.e. `resetPrerequests: boolean`)?

File: packages/proxy/lib/http/util/prerequests.ts [hunk 2]
```diff
@@ -157,8 +160,23 @@ export class PreRequests {
   }
 
   addPending (browserPreRequest: BrowserPreRequest) {
-    metrics.browserPreRequestsReceived++
     const key = `${browserPreRequest.method}-${tryDecodeURI(browserPreRequest.url)}`
+
+    // The initial request that loads the service worker does not always get sent to CDP. Thus, we need to explicitly ignore it. We determine
+    // it's the service worker request via the `service-worker` header
+    if (browserPreRequest.headers?.['Service-Worker'] === 'script') {
+      debugVerbose('Ignoring service worker script since we are not guaranteed to receive it', key)
```
Comment (mschile) [inline packages/proxy/lib/http/util/prerequests.ts]: What happens if we do receive it?

File: packages/proxy/lib/http/util/prerequests.ts [hunk 3]
```diff
@@ -157,8 +160,23 @@ export class PreRequests {
...
+
+      return
+    }
+
+    if (this.serviceWorkerManager.processBrowserPreRequest(browserPreRequest)) {
+      debugVerbose('Not correlating request since it is fully controlled by service worker and the correlation will happen within the service worker', key)
```
Comment (mschile) [inline packages/proxy/lib/http/util/prerequests.ts]:
```suggestion
      debugVerbose('Not correlating request since it is fully controlled by the service worker and the correlation will happen within the service worker', key)
```

File: packages/proxy/lib/http/util/prerequests.ts [hunk 4]
```diff
@@ -157,8 +160,23 @@ export class PreRequests {
   }
 
   addPending (browserPreRequest: BrowserPreRequest) {
-    metrics.browserPreRequestsReceived++
     const key = `${browserPreRequest.method}-${tryDecodeURI(browserPreRequest.url)}`
+
+    // The initial request that loads the service worker does not always get sent to CDP. Thus, we need to explicitly ignore it. We determine
+    // it's the service worker request via the `service-worker` header
+    if (browserPreRequest.headers?.['Service-Worker'] === 'script') {
```
Comment (mschile) [inline packages/proxy/lib/http/util/prerequests.ts]: Suggest moving these two `if` statements into their own function.

File: packages/proxy/lib/http/util/prerequests.ts [hunk 5]
```diff
@@ -230,11 +248,10 @@ export class PreRequests {
...
 
   get (req: CypressIncomingRequest, ctxDebug, callback: GetPreRequestCb) {
-    // The initial request that loads the service worker does not get sent to CDP and it happens prior
-    // to the service worker target being added. Thus, we need to explicitly ignore it. We determine
-    // it's the service worker request via the `sec-fetch-dest` header
-    if (req.headers['sec-fetch-dest'] === 'serviceworker') {
-      ctxDebug('Ignoring request with sec-fetch-dest: serviceworker', req.proxiedUrl)
+    // The initial request that loads the service worker does not always get sent to CDP. Thus, we need to explicitly ignore it. We determine
+    // it's the service worker request via the `service-worker` header
+    if (req.headers?.['service-worker'] === 'script') {
```
Comment (mschile) [inline packages/proxy/lib/http/util/prerequests.ts]: Since this is the same as above, maybe create a `hasServiceWorkerHeader` function?

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+export class ServiceWorkerManager {
+  private serviceWorkerRegistrations: Map<string, ServiceWorkerRegistration> = new Map<string, ServiceWorkerRegistration>()
+  private pendingInitiators: Map<string, string> = new Map<string, string>()
+
+  /**
+   * Registers the given service worker with the given scope. Will not overwrite an existing registration.
+   */
+  registerServiceWorker ({ registrationId, scopeURL }: RegisterServiceWorkerOptions) {
+    // Only register service workers if they haven't already been registered
+    if (this.serviceWorkerRegistrations.has(registrationId) && this.serviceWorkerRegistrations.get(registrationId)?.scopeURL === scopeURL) {
```
Comment (mschile) [inline packages/proxy/lib/http/util/service-worker-manager.ts]:
```suggestion
    if (this.serviceWorkerRegistrations.get(registrationId)?.scopeURL === scopeURL) {
```

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+
+  /**
+   * Adds an initiator URL to a service worker. If the service worker has not yet been activated, the initiator URL is added to a pending list and will
+   * be added to the service worker when it is activated.
+   */
+  addInitiatorToServiceWorker ({ scriptURL, initiatorURL }: AddInitiatorToServiceWorkerOptions) {
+    let initiatorAdded = false
+
+    this.serviceWorkerRegistrations.forEach((registration) => {
+      if (registration.activatedServiceWorker && registration.activatedServiceWorker.scriptURL === scriptURL) {
```
Comment (mschile) [inline packages/proxy/lib/http/util/service-worker-manager.ts]:
```suggestion
      if (registration.activatedServiceWorker?.scriptURL === scriptURL) {
```

File: packages/server/lib/automation/automation.ts [hunk 8]
```diff
@@ -14,7 +14,7 @@ export class Automation {
   private cookies: Cookies
   private screenshot: { capture: (data: any, automate: any) => any }
 
-  constructor (cyNamespace?: string, cookieNamespace?: string, screenshotsFolder?: string | false, public onBrowserPreRequest?: OnBrowserPreRequest, public onRequestEvent?: OnRequestEvent, public onRequestServedFromCache?: (requestId: string) => void, public onRequestFailed?: (requestId: string) => void, public onDownloadLinkClicked?: (downloadUrl: string) => void) {
+  constructor (cyNamespace?: string, cookieNamespace?: string, screenshotsFolder?: string | false, public onBrowserPreRequest?: OnBrowserPreRequest, public onRequestEvent?: OnRequestEvent, public onRequestServedFromCache?: (requestId: string) => void, public onRequestFailed?: (requestId: string) => void, public onDownloadLinkClicked?: (downloadUrl: string) => void, public onServiceWorkerRegistrationUpdated?: OnServiceWorkerRegistrationUpdated, public onServiceWorkerVersionUpdated?: OnServiceWorkerVersionUpdated, public onServiceWorkerClientSideRegistrationUpdated?: OnServiceWorkerClientSideRegistrationUpdated) {
```
Comment (mschile) [inline packages/server/lib/automation/automation.ts]: Sooo loooooong.....

File: packages/server/lib/browsers/utils.ts [hunk 9]
```diff
@@ -398,46 +398,99 @@ const throwBrowserNotFound = function (browserName, browsers: FoundBrowser[] = [
 // Chromium browsers and webkit do not give us pre requests for download links but they still go through the proxy.
```
Comment (mschile) [inline packages/server/lib/browsers/utils.ts]: Seems like this comment should be updated.

Comment (ryanthemanuel) [reply packages/server/lib/browsers/utils.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/server/lib/automation/automation.ts (hunk 8 above)
Comment (ryanthemanuel) [reply packages/server/lib/automation/automation.ts]: Updated to pull these out to their own object type: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/service-worker-manager.ts (hunk 7 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/service-worker-manager.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/service-worker-manager.ts (hunk 6 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/service-worker-manager.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/prerequests.ts (hunk 5 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/prerequests.ts (hunk 4 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/prerequests.ts (hunk 3 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/util/prerequests.ts (hunk 2 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: Updated with some clarification as to what is going on here: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

File: packages/proxy/lib/http/index.ts (hunk 1 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: Updated: https://github.com/cypress-io/cypress/pull/28517/commits/956dd0aa92c8e7cdb0ee1284be92bdeeb52426a3

**Review by mschile — APPROVED** [review]

File: cli/CHANGELOG.md [hunk 10]
```diff
@@ -5,6 +5,7 @@ _Released 12/19/2023 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed asset capture for Test Replay (which will potentially affect styles) specifically for requests that are routed through service workers. Fixes [#28516](https://github.com/cypress-io/cypress/issues/28516).
```
Comment (emilyrohrbough) [inline cli/CHANGELOG.md]: > which will potentially affect styles

what does this mean/entail? what should on expect by from this?

File: packages/proxy/lib/http/index.ts [hunk 11]
```diff
@@ -429,10 +430,13 @@ export class Http {
     }
   }
 
-  reset () {
+  reset (options: { resetPrerequests?: boolean } = {}) {
     this.buffers.reset()
     this.setAUTUrl(undefined)
-    this.preRequests.reset()
+
+    if (options.resetPrerequests) {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/index.ts]: can you add a note on when one would not want to reset prerequests?

Comment (emilyrohrbough) [reply packages/proxy/lib/http/index.ts]: actually, is adding this option needed? it seems this reset is only called in one place within the server code

File: packages/proxy/lib/http/util/prerequests.ts [hunk 12]
```diff
@@ -330,4 +361,27 @@ export class PreRequests {
     this.pendingRequests = new QueueMap<PendingRequest>()
     this.pendingUrlsWithoutPreRequests = new QueueMap<PendingUrlWithoutPreRequest>()
   }
+
+  private static hasServiceWorkerHeader (headers: Record<string, string | string[] | undefined>) {
+    return headers?.['service-worker'] === 'script' || headers?.['Service-Worker'] === 'script'
+  }
+
+  private shouldIgnorePendingRequest (browserPreRequest: BrowserPreRequest) {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/prerequests.ts]: It feels like this check & the serviceworker pass-throughs should be de-coupled from the prerequests this file and  moved into `http/index.ts` to pass directly to the service worker manger.

https://github.com/cypress-io/cypress/blob/ryanm/fix/service-worker-capture/packages/proxy/lib/http/index.ts#L442-L443
``` diff
  // http/index.ts
  addPendingBrowserPreRequest (browserPreRequest: BrowserPreRequest) {
+    if (!this.serviceWorkerManager.willHandleRequest(browserPreRequest)) {
      this.preRequests.addPending(browserPreRequest)
+    }
  }
...
  reset () {
    this.buffers.reset()
    this.setAUTUrl(undefined)
    this.preRequests.reset()
+  this.serviceWorkerManager = new ServiceWorkerManager()
  }
```

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+    this.serviceWorkerRegistrations.delete(registrationId)
+  }
+
+  /**
+   * Adds an activated service worker to the manager.
+   */
+  addActivatedServiceWorker ({ registrationId, scriptURL }: AddActivatedServiceWorkerOptions) {
+    const registration = this.serviceWorkerRegistrations.get(registrationId)
+
+    if (registration) {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/service-worker-manager.ts]: would it be helpful to log a debug message if worker not found?

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 14]
```diff
@@ -0,0 +1,155 @@
...
+      const initiatorURL = this.pendingInitiators.get(scriptURL)
+
+      registration.activatedServiceWorker = {
+        registrationId,
+        scriptURL,
+        controlledURLs: new Set<string>(),
+        initiatorURL: initiatorURL || registration.activatedServiceWorker?.initiatorURL,
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/service-worker-manager.ts]: If `registration.activatedServiceWorker?.initiatorURL` has already been set, won't this override the `controlledURLs` set if there were already url that had been added? Should we only update this if this has not already been defined?

Comment (emilyrohrbough) [reply packages/proxy/lib/http/util/service-worker-manager.ts]: NVM - the handshake below seems to handle the scenario I was concerned about

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 15]
```diff
@@ -0,0 +1,155 @@
...
+ * Manages service worker registrations and their controlled URLs.
+ *
+ * The basic lifecycle is as follows:
+ *
+ * 1. A service worker is registered via `registerServiceWorker`.
+ * 2. The service worker is activated via `addActivatedServiceWorker`.
+ *
+ * At some point while 1 and 2 are happening:
+ *
+ * 3. We receive a message from the browser that a service worker has been registered with the `addInitiatorToServiceWorker` method.
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/service-worker-manager.ts]: registered or initiated? 
```suggestion
 * 3. We receive a message from the browser that a service worker has been initiated with the `addInitiatorToServiceWorker` method.
```

File: packages/proxy/lib/http/util/service-worker-manager.ts [hunk 16]
```diff
@@ -0,0 +1,155 @@
...
+   */
+  addInitiatorToServiceWorker ({ scriptURL, initiatorURL }: AddInitiatorToServiceWorkerOptions) {
+    let initiatorAdded = false
+
+    this.serviceWorkerRegistrations.forEach((registration) => {
+      if (registration.activatedServiceWorker?.scriptURL === scriptURL) {
+        registration.activatedServiceWorker.initiatorURL = initiatorURL
+
+        initiatorAdded = true
+      }
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/service-worker-manager.ts:98]:
```suggestion
         break
      }
```

File: packages/server/lib/browsers/cdp_automation.ts [hunk 17]
```diff
@@ -261,6 +266,14 @@ export class CdpAutomation implements CDPClient {
     this.automation.onRequestEvent?.('response:received', browserResponseReceived)
   }
 
+  private onWorkerRegistrationUpdated = (params: Protocol.ServiceWorker.WorkerRegistrationUpdatedEvent) => {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/cdp_automation.ts]:
```suggestion
  private onServiceWorkerRegistrationUpdated = (params: Protocol.ServiceWorker.WorkerRegistrationUpdatedEvent) => {
```

File: packages/server/lib/browsers/cdp_automation.ts [hunk 18]
```diff
@@ -261,6 +266,14 @@ export class CdpAutomation implements CDPClient {
...
+    this.automation.onServiceWorkerRegistrationUpdated?.(params)
+  }
+
+  private onWorkerVersionUpdated = (params: Protocol.ServiceWorker.WorkerVersionUpdatedEvent) => {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/cdp_automation.ts]:
```suggestion
  private onServiceWorkerVersionUpdated = (params: Protocol.ServiceWorker.WorkerVersionUpdatedEvent) => {
```

**Review by emilyrohrbough — COMMENTED** [review]
I understand this change is wired up for Chromium browsers and for protocol asset capturing. There are changes to the proxy prerequest correlation logic -- have we observed any changes in how firefox / webkit tests behave when there are service workers on the page?

**Comment by ryanthemanuel** [comment]
> I understand this change is wired up for Chromium browsers and for protocol asset capturing. There are changes to the proxy prerequest correlation logic -- have we observed any changes in how firefox / webkit tests behave when there are service workers on the page?

We have system tests that run with service workers in all browsers and they are still good to go: https://github.com/cypress-io/cypress/blob/develop/system-tests/test/service_worker_spec.js. The main fix here is that we're ensuring that things get correlated properly. Things are not correlated properly today outside of chromium but they never were (this is part of why we keep the correlation timeout down at 500ms for non chromium browsers). It'll be a problem that we have to fix at a later date.

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: NetworkProxy.reset is called:

* in between tests - https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-base.ts#L475
* in between specs - https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-base.ts#L620
* onResolveUrl - https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-base.ts#L732

We only want to reset the prerequests in between specs.

File: packages/server/lib/browsers/cdp_automation.ts (hunk 18 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/cdp_automation.ts]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/server/lib/browsers/cdp_automation.ts (hunk 17 above)
Comment (ryanthemanuel) [reply packages/server/lib/browsers/cdp_automation.ts]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/util/service-worker-manager.ts (hunk 16 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/service-worker-manager.ts:98]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/util/service-worker-manager.ts (hunk 15 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/service-worker-manager.ts]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/util/service-worker-manager.ts (hunk 13 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/service-worker-manager.ts]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/util/prerequests.ts (hunk 12 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: I like this idea. Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: Added a note: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: cli/CHANGELOG.md (hunk 10 above)
Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: Resolved here: [`04617eb` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/04617eb1b3565c380ac89d12f575f2e731cba4f6)

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (emilyrohrbough) [reply packages/proxy/lib/http/index.ts]: Ahh I searched on just networkProxy.reset() and didn't check for networkProxy **?** .reset()

Comment (emilyrohrbough) [reply packages/proxy/lib/http/index.ts]: Why do we only care about resetting prerequests once per spec now? Do we really only care about this for resetting the service worker manager?

File: packages/proxy/lib/http/index.ts [hunk 19]
```diff
@@ -456,15 +465,25 @@ export class Http {
   }
 
   updateServiceWorkerRegistrations (data: Protocol.ServiceWorker.WorkerRegistrationUpdatedEvent) {
-    this.preRequests.updateServiceWorkerRegistrations(data)
+    data.registrations.forEach((registration) => {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/index.ts]: sorry - curious again, why not let the server worker manager handle iteration and messaging of this data?

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: This is something that was added somewhat recently (and incorrectly). When test isolation is off for example, we wouldn't want to just drop requests that were happening in a previous test. Only when we start a fresh new session in a new browser tab do we want to reset them.

File: packages/proxy/lib/http/util/prerequests.ts [hunk 20]
```diff
@@ -230,11 +232,10 @@ export class PreRequests {
...
 
   get (req: CypressIncomingRequest, ctxDebug, callback: GetPreRequestCb) {
-    // The initial request that loads the service worker does not get sent to CDP and it happens prior
-    // to the service worker target being added. Thus, we need to explicitly ignore it. We determine
-    // it's the service worker request via the `sec-fetch-dest` header
-    if (req.headers['sec-fetch-dest'] === 'serviceworker') {
-      ctxDebug('Ignoring request with sec-fetch-dest: serviceworker', req.proxiedUrl)
+    // The initial request that loads the service worker does not always get sent to CDP. Thus, we need to explicitly ignore it. We determine
+    // it's the service worker request via the `service-worker` header
+    if (hasServiceWorkerHeader(req.headers)) {
```
Comment (emilyrohrbough) [inline packages/proxy/lib/http/util/prerequests.ts]: We should just bump this out to http/index as well

File: packages/proxy/lib/http/index.ts (hunk 19 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: I think I was mainly just trying to keep the ServiceWorker sort of pure and not dependent on CDP API specifics. I could go either way on passing that logic one layer deep though I guess.

Comment (emilyrohrbough) [reply packages/proxy/lib/http/index.ts]: My thought would be that it would contains all the of the service work data/logic expectations in one file and test coverage vs needing to trace it through out.

File: packages/proxy/lib/http/util/prerequests.ts (hunk 20 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/util/prerequests.ts]: Good call: [`74c14f0` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/74c14f0e8c10c531b5ddb03e14d3ef0aea5a050f)

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (emilyrohrbough) [reply packages/proxy/lib/http/index.ts]: Gottchya - Sound this be called out in the changelog as well? do we have an issue for this?

File: packages/proxy/package.json [hunk 21]
```diff
@@ -36,6 +36,7 @@
     "@packages/server": "0.0.0-development",
     "@types/express": "4.17.2",
     "@types/supertest": "2.0.10",
+    "devtools-protocol": "0.0.927104",
```
Comment (chrisbreiding) [inline packages/proxy/package.json:39]: This may need to be nohoisted or it could lead to type errors liked I found with https://github.com/cypress-io/cypress/pull/28372

**Review by chrisbreiding — APPROVED** [review]

File: packages/proxy/lib/http/index.ts (hunk 11 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: I can add a comment in the changelog. There's no issue for this, it's just something I found in the process of fixing this. I can add an issue though.

File: packages/proxy/package.json (hunk 21 above)
Comment (ryanthemanuel) [reply packages/proxy/package.json:39]: Good catch: [`bf92f82` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/bf92f825c87e6502deb70ce56631877b39c758b4)

File: packages/proxy/lib/http/index.ts (hunk 19 above)
Comment (ryanthemanuel) [reply packages/proxy/lib/http/index.ts]: Updated: [`bf92f82` (#28517)](https://github.com/cypress-io/cypress/pull/28517/commits/bf92f825c87e6502deb70ce56631877b39c758b4)

File: cli/CHANGELOG.md [hunk 22]
```diff
@@ -5,6 +5,7 @@ _Released 12/19/2023 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed asset capture for Test Replay for requests that are routed through service workers and for requests that span tests when test isolation is off. This addresses an issue where styles would not being applied properly in Test Replay or `cy.intercept` would not work properly. Fixes [#28516](https://github.com/cypress-io/cypress/issues/28516) and [#28545](https://github.com/cypress-io/cypress/issues/28545).
```
Comment (MikeMcC399) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed asset capture for Test Replay for requests that are routed through service workers and for requests that span tests when test isolation is off. This addresses an issue where styles were not being applied properly in Test Replay and `cy.intercept` was not working properly for requests in this scenario. Fixes [#28516](https://github.com/cypress-io/cypress/issues/28516) and [#28545](https://github.com/cypress-io/cypress/issues/28545).
```

Not sure if this is a complete correction of the second sentence. Please cross-check!

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: Thanks @MikeMcC399. Updated.

**Review by CloneOfAlex — APPROVED** [review]
Nice

**Review by CloneOfAlex — APPROVED** [review]
nice smoke changes

**Review by emilyrohrbough — APPROVED** [review]

File: cli/CHANGELOG.md [hunk 23]
```diff
@@ -5,6 +5,8 @@ _Released 12/19/2023 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed asset capture for Test Replay for requests that are routed through service workers and for requests that span tests when test isolation is off. This addresses an issue where styles were not being applied properly in Test Replay and `cy.intercept` was not working properly for requests in this scenario. Fixes [#28516](https://github.com/cypress-io/cypress/issues/28516) and [#28545](https://github.com/cypress-io/cypress/issues/28545).
+- Cypress no longer errors during `cypress run` or `cypress open` when using Typescript 5.3.2+ with `extends` in `tsconfig.json`. Fixes [#28385](https://github.com/cypress-io/cypress/issues/28385).
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
```

**Comment by jordanpowell88** [comment]
We've had issues getting Mock Service Worker to work with CT. Any chance this fix would fix that?

**Comment by ryanthemanuel** [comment]
> We've had issues getting Mock Service Worker to work with CT. Any chance this fix would fix that?

It's possible. I'd need to know what types of problems we were seeing with that.

**Review by CloneOfAlex — APPROVED** [review]

**Review by CloneOfAlex — APPROVED** [review]
Nice
