### PR TITLE
env config settings is displayed correctly

### LINKED ISSUE #5859: Configuration shows `env` variables as `undefined`
Settings Panel does not show env variables

Screenshot 2019-12-03 at 14 21 06

`cypress/config/foo.json` file content

```
{
  "baseUrl": "http://localhost:8081/",
  "env": {
    "login.email": "foo",
    "login.password": "baz",
    "bar": "bar"
  }
}
```

### Desired behavior:

The Settings panel should show all environments as they are defined in the selected config file.

### Steps to reproduce: (app code and test code)
1. `cypress open` or `cypress open --config-file _PATH_TO_CONFIG_FILE` (applies for both, with default or with custom config file)
2. As soon as the panel shows up, switch to Settings tab (top-left corner)
3. Open `Configuration` accordion
4. `env` key shows `undefined` and no source item when hovering

### Versions
Node: 12.0.0
Cypress: 3.7.0

Note: Running the exact configuration with cypress 3.6.1 works as expected.

### PR DESCRIPTION
**Pull request by andrew-codes**
- Closes #5859

### User facing changelog

`env` configuration option displays properly within the settings panel. Previously, setting env options would incorrectly render `"undefined"` as the value.

### Additional details

The resolved config has metadata around where the value comes from. For example, `blacklistHosts`'s value is an object with a `from` and `value` key. The component rendering the config accepts a normal object, so we do not want to include this additional metadata. Prior to passing it along, the resolved config is normalized without the metadata. However, the `env` value turned out to be a special case; with its value being the actual value instead of a `from` and `value` object. Due to this, the process of normalizing the resolved config stripped this out entirely; leaving an undefined value.

Now, the resolved config is processed to strip metadata and then the `env` key is explicitly added back.

Tests were also added to ensure the existence of env data is rendered properly; both initially, expanded, and with the correct tooltip information.

#### Before Screenshot
image

#### After Screenshot
image
image

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by andrew-codes** [comment]
Let me pull a screenshot of before and after. Thank you for the feedback @jennifer-shehane

**Comment by chrisbreiding** [comment]
Is this what we want when `env` _is_ undefined? I feel like it shouldn't be there or should say `null` or `undefined` instead of being blank.

Screen Shot 2019-12-05 at 1 39 43 PM

**Comment by andrew-codes** [comment]
Good catch @chrisbreiding. Let me add a test and resolve the issue when there is no env value.

File: packages/desktop-gui/cypress/integration/settings_spec.js [hunk 1]
```diff
@@ -181,6 +182,55 @@ describe('Settings', () => {
...
+        cy.get('@config').then(({ resolved }) => {
+          const getEnvKeys = flow([
+            get('env'),
+            toPairs,
+            map(([key]) => key),
+            sortBy(get('')),
+          ])
+
+          cy.contains('.line', 'env').contains(flow([getEnvKeys, join(', ')])(resolved))
+          cy.contains('.line', 'env').click()
```
Comment (brian-mann) [inline packages/desktop-gui/cypress/integration/settings_spec.js]: these lines should go below the `const ... =` assignments because the execute async.

It's generally better to group the sync/async code together

File: packages/desktop-gui/cypress/integration/settings_spec.js [hunk 2]
```diff
@@ -181,6 +182,79 @@ describe('Settings', () => {
...
+
+        this.ipc.openProject.onCall(2).resolves(setConfigEnv(this.config, {}))
+        this.ipc.onConfigChanged.yield()
+
+        cy.contains('.line', 'env:null')
+
+        this.ipc.openProject.onCall(3).resolves(setConfigEnv(this.config, undefined))
+        this.ipc.onConfigChanged.yield()
+
+        cy.contains('.line', 'env:null')
```
Comment (brian-mann) [inline packages/desktop-gui/cypress/integration/settings_spec.js]: i don't believe you're coordinating the stubs + the cypress commands correctly here because the cypress commands are async and the `this.ipc.onConfigChanged.yield()` is synchronous. I believe it's synchronously firing the `onConfigChanged` immediately (three times), and so the final `undefined` value is being flushed to the DOM, and then the three `cy.contains(...)` are running only against the last render of the DOM (which is `undefined`).

To fix this you need to use a `.then()` so that the IPC events are fired after the `cy.contains()`

Comment (andrew-codes) [reply packages/desktop-gui/cypress/integration/settings_spec.js]: Thanks for pointing this out and going over it with me. Consequently, the implementation passes for each use case, `null`, `undefined`, and `{}`. However, even with the new code changes to the test that we worked on, I get strange behavior. I broke them into 3 separate E2E test cases, but I don't much like it. I'd love if anyone has any insights on how to combine them into a single test case.
