### PR TITLE
fix: hide 'open in IDE' button from command log in CT

### LINKED ISSUE #24366: (component) Clicking "Open in IDE" is broken
### Current behavior

Clicking "Open in IDE"  in the reporter does not take user to hook/test definition that ran.

In Prod - this does nothing. It doesn't open the IDE or launch to the file that ran. See video:

https://user-images.githubusercontent.com/14099737/197545580-7280e228-7018-438c-9077-436ece1fe3d0.mov

In dev - this opens to the current IDE / branch & opens the stack_utils file in the driver. See video:

https://user-images.githubusercontent.com/14099737/197545624-5512a12a-2a74-43f4-b6e8-0e9d52aa2907.mov

### Desired behavior

Opens to hook / test when "Open in IDE" is clicked.

### Test code to reproduce

Open any CT test and click "Open in IDE" after test runs.

### Cypress Version

10.10.0

### Node version

16.16.0

### Operating System

MacOS 12.5.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by astone123**
- Closes #24366

### User facing changelog

User will no longer see "Open in IDE" in the command log for component tests

### Additional details

This button doesn't work for CT. As a part of the GA effort, we should remove this button from CT so that users don't try to click it. We'll actually fix it and re-enable it with #24549

### Steps to test

1. Run Cypress
2. Open e2e tests
3. Run a spec
4. While the spec is running, hover over the "test body" section of the command log and verify that you still see the "Open in IDE" button on hover
5. Click the button and verify that you are taken to the spec file in your configured IDE
6. Open Component Testing
7. Run a CT spec
8. While the spec is running, hover over the same spot in the command log and verify that the "Open in IDE" button is **not** rendered

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/reporter/src/hooks/hooks.tsx [hunk 1]
```diff
@@ -59,14 +59,16 @@ const StudioNoCommands = () => (
...
 
-const Hook = observer(({ model, showNumber }: HookProps) => (
+const Hook = observer(({ model, showNumber, testType }: HookProps) => (
   <li className={cs('hook-item', { 'hook-failed': model.failed, 'hook-studio': model.isStudio })}>
     <Collapsible
       header={<HookHeader model={model} number={showNumber ? model.hookNumber : undefined} />}
       headerClass='hook-header'
-      headerExtras={model.invocationDetails && <HookOpenInIDE invocationDetails={model.invocationDetails} />}
+      // Temporarily removed from CT since it doesn't work. Will be re-enabled in https://github.com/cypress-io/cypress/issues/24549
+      headerExtras={model.invocationDetails && testType !== 'component' && <HookOpenInIDE invocationDetails={model.invocationDetails} />}
```
Comment (ZachJW34) [inline packages/reporter/src/hooks/hooks.tsx]: Could we have used the global Cypress here and not have had to change so many files?
```suggestion
      headerExtras={model.invocationDetails && Cypress.testingType !== 'component' && <HookOpenInIDE invocationDetails={model.invocationDetails} />}
```

Comment (astone123) [reply packages/reporter/src/hooks/hooks.tsx]: Nice! I didn't realize we had a global with that info

**Review by marktnoonan — APPROVED** [review]
Nice

**Review by ZachJW34 — APPROVED** [review]

**Review by warrensplayer — APPROVED** [review]
