### PR TITLE
Only send `cy.visit()` `auth` options to correct protection space

### LINKED ISSUE #4267: Using auth option in visit method sets authorization headers in all subrequests
### Current behavior:

We have overridden Visit method and adding there auth option (because app we are testing is behind basic http auth). But these headers are sent NOT ONLY to page which is defined in visit method, but also to all sub requests, like for example images and js, which are loaded on page. Is this normal behaviour? Because we have problems with CDN, which is just refusing requests with such header.

### Desired behavior:

I would expect authorization header is sent only to defined visit page, not to all requests on page.

### Steps to reproduce: (app code and test code)

It seems this is done inside cypress proxy, because if you take a look inside browser there is no header in requests, but if you see logs on server, there is actually Authorization header.

### Versions

Cypress 3.3.0

### PR DESCRIPTION
**Pull request by flotwig**
[RFC 7235 section 2.2](https://tools.ietf.org/html/rfc7235#section-2.2) defines the "protection space" of an authorization as the scheme + the fully-qualified domain + port of the URL for which the authorization occurred. 

Previously, Cypress would send `auth` to any URLs that match the CORS origin of the original `auth`. This PR corrects that behavior by only sending the `auth` headers when there is an exact match on the protection space.

Fixes #4267

### CODE REVIEW

File: packages/server/test/integration/http_requests_spec.coffee [hunk 1]
```diff
@@ -1673,58 +1673,88 @@ describe "Routes", ->
...
+          }
 
-        nock("http://localhost:8080")
-        .get("/index")
-        .matchHeader("authorization", existing)
-        .reply(200, "")
+          nock("http://localhost:8080")
+          .get("/index")
+          .matchHeader("authorization", existing)
+          .reply(200, "")
```
Comment (Bkucera) [inline packages/server/test/integration/http_requests_spec.coffee]: strange whitespace

**Comment by voslartomas** [comment]
@flotwig Any news here?

File: packages/server/test/integration/http_requests_spec.coffee (hunk 1 above)
Comment (flotwig) [reply packages/server/test/integration/http_requests_spec.coffee]: looks right to me, what am I missing?

**Comment by flotwig** [comment]
@voslartomas This fixes the problem, it should be out in the next bugfix release (3.3.2)

File: packages/server/test/integration/http_requests_spec.coffee (hunk 1 above)
Comment (Bkucera) [reply packages/server/test/integration/http_requests_spec.coffee]: nvm, didn't see you had changed the scope

**Comment by voslartomas** [comment]
@flotwig Any news?

File: packages/server/lib/controllers/proxy.coffee [hunk 2]
```diff
@@ -312,14 +300,14 @@ module.exports = {
...
-
-      ## if we have auth headers and this request matches our origin policy
-      if (a = remoteState.auth) and resMatchesOriginPolicy()
-        ## and no existing Authentication headers
-        if not req.headers["authorization"]
-          base64 = Buffer.from(a.username + ":" + a.password).toString("base64")
-          req.headers["authorization"] = "Basic #{base64}"
+        opts.url = req.proxiedUrl
+
+      ## if we have auth headers and this request matches our origin protection space
```
Comment (brian-mann) [inline packages/server/lib/controllers/proxy.coffee]: When we are fixing edge cases like this, always try to remember to leave a comment point to the github issue that it represents. You usually do, just pointing it out.

File: packages/server/lib/util/uri.js [hunk 3]
```diff
@@ -1,44 +1,53 @@
...
-  //# grab host which is 'hostname:port' only
+  // grab host which is 'hostname:port' only
   const { host, hostname, port } = url.parse(urlToCheck)
 
-  //# if we have a default port for 80 or 443
-  //# then just return the hostname
-  if (DEFAULT_PORTS.includes(port)) {
+  // if we have a default port for 80 or 443
+  // then just return the hostname
+  if (_.values(DEFAULT_PORTS).includes(port)) {
```
Comment (brian-mann) [inline packages/server/lib/util/uri.js]: Since we use the values here twice (and they are a constant) we should set another constant at the top next to `DEFAULT_PORTS` called like `DEFAULT_PORT_VALUES`

File: packages/server/lib/controllers/proxy.coffee [hunk 4]
```diff
@@ -100,9 +91,6 @@ module.exports = {
   getHttpContent: (thr, req, res, remoteState, config, request) ->
     process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"
 
-    ## prepends req.url with remoteState.origin
-    remoteUrl = req.proxiedUrl
```
Comment (brian-mann) [inline packages/server/lib/controllers/proxy.coffee]: curious what your thought process was removing this

**Comment by brian-mann** [comment]
BTW: great link for describing the parts and segments that make up a URL:

https://nodejs.org/api/url.html#url_url_strings_and_url_objects

**Comment by brian-mann** [comment]
@flotwig 	take a look at my commits. You'll see some gnarly edge cases that the unit tests did in fact catch!

File: packages/server/lib/controllers/proxy.coffee (hunk 4 above)
Comment (flotwig) [reply packages/server/lib/controllers/proxy.coffee]: `req.proxiedUrl` was used in some places and `remoteUrl` in others, figured it was a potential point of confusion ("wait, is proxiedUrl the same as remoteUrl?") so I just normalized all the references to it
