### PR TITLE
fix: implement new graphql fields for spec counts

### LINKED ISSUE #25647: Debug M1.1 - Use new Cloud fields for spec counts for running builds
**Current behavior**
In `RelevantRunSpecsDataSource`, [file](https://github.com/cypress-io/cypress/blob/develop/packages/data-context/src/sources/RelevantRunSpecsDataSource.ts) the logic for calculating the spec counts used to show the progress of a running build in Cypress Cloud is in the `#calculateSpecMetadata` method.  It makes a best attempt to figure out the status by looking across the statuses of each group. This is not the same way the cloud does it, so when looking at the Debug page or in the Cloud, the counts will not match up.

**Desired behavior**
The Cloud team is adding two new fields to the `CloudRun` type to supply the counts instead of having them be calculated in the app.  That work will be done here: https://cypress-io.atlassian.net/browse/CYCLOUD-860

**NOTE** Cloud story is scheduled for Cloud sprint starting 2/8/23. Consider reaching out to the Cloud team when working on this (Tyler B).

The two new fields are documented as `completedInstanceCount` and `totalInstanceCount`.  These values should be used in RelevantRunSpecsDataSource` instead of pulling the `specs` field and trying to calculate the value with filtering, etc.

_Additional refactors_

* Refactor subscription and poller to only watch one runNumber
  ~~* The poller setup in this file in the `pollForSpecs` function backs the `relevantRunSpecChange` subscription.  This subscription is used by both the `DebugNewRelevantRunBar` and the `DebugPendingRunSplash`.  The `DebugNewRelevantRunBar` asks for the `next` field and the `DebugPendingRunSplash` asks for the `current` field, but the query will ask the Cloud for both if both a current and next run number has been calculated by the `RelevantRunsDataSource`.  Refactor this datasource to take a parameter for the subscription that will just poll for the runNumber that is important to the component that subscribes.  This will remove the need for having to alias `runByNumber` to both current and next.~~ **implemented this but removed changes after review with Stokes, based on upcoming work in same area**
* Only invalidate if watching current
  * Currently the poller in `RelevantRunSpecsDataSource` will call `cache.invalidate` if it detects a status change of either build it is watching  (current or next).  When the subscription is being used to watch the "next" run and the Debug page is showing the `DebugNewRelevantRunBar`,  it does not need to perform the cache invalidation because the front end has not cached any queries.  Currently, this use case causes the Debug page to flash the loading skeleton when the `DebugNewRelevantRunBar` transitions from the running to completed state.  With the refactor in the previous bullet, update the cache invalidation to only happen on a status change when watching the `current` run.
* Update comments
  * The comments for the class and the `getRelevantRunSpecs` method are incorrect.  They were copy/pasted from the `RelevantRunsDataSource`.  They should be updated to reflect what this file does.

### PR DESCRIPTION
**Pull request by marktnoonan**
- Closes #25647

### Additional details

This PR 

- adds unit tests for RelevantRunSpecsDataSource
- modifies it to use the new fields and removes the old `#calculateSpecMetadata` function since we are now getting that information from the cloud
- modifies it to only clear cache when polling the `current` run
- updates some conditional display logic in the Debug Container component to make it more clear that the New Run banner and the First Run splash components do not render at the same time. 

#### Use of the new fields

The main thing to verify is that the spec counts are consistent with the cloud now. I test this by recording tests locally from a small project and comparing with the cloud. They poll at different rates so won't be totally in sync, but the total should be the same and we should not reach a state where the app shows "24 of 24" while the cloud is not completed, which was possible in the past.

Screen Shot 2023-02-10 at 8 28 28 AM

Similarly, if I delete the Project ID and set up a new one, I should see the same thing when I record the first ever run in that project:

Screen Shot 2023-02-10 at 8 36 16 AM

#### Cache clearing fix

Here we want to see that the transition between the banner's "in progress" state and the final "view run" state does not involve a cycle through the loading screen.

The place to watch this is at the end of a run and the transition happens.

Here is the old transition:

https://user-images.githubusercontent.com/8340719/218170117-482bd70b-ee95-4062-a3cd-bed04c2c3216.mov

And here is the new one:

https://user-images.githubusercontent.com/8340719/218170101-c0d3652b-bb8a-438d-b290-494320f7159b.mov

#### Logic update in `DebugContainer`
This is currently only possible in the component test for this. The update is small and mostly there for developer-facing clarity since the front end logic previously allowed two components to render at the same time that are mutually exclusive in real life. Even though the server side logic did not lead to them rendering at the same time, it's confusing for the front end to have configurations that are _possible_ that aren't valid states of the application.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
> The main thing to verify is that the spec counts are consistent with the cloud now.

Sounds like this is a bug fix?

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts [hunk 1]
```diff
@@ -208,7 +210,9 @@ export class RelevantRunSpecsDataSource {
           debug('Run statuses changed')
           const projectSlug = await this.ctx.project.projectId()
 
-          if (projectSlug) {
+          const wasWatchingCurrentProject = this.#cached.statuses.current === 'RUNNING'
+
+          if (projectSlug && wasWatchingCurrentProject) {
```
Comment (marktnoonan) [inline packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: This is the change that avoids a flash of the full page loading skeleton when a `next` run transitions from "running" to "completed".

Ideally we would have an end-to-end test for this, I'm working on one that can form part of a separate PR if this merges first. It's also the kind of test that will be much easier to write if we have improvements coming in the test infra soon.

Comment (warrensplayer) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: I don't think the `wasWatchingCurrentProject` check will work at its current location. The `#cached` variable is getting set on line 201, and the `statusesChanged` variable is calculated before that.  When the code gets to the `wasWatchingCurrentProject` calculation, the `#cached.statues.current` will no longer be RUNNING.

**Review by warrensplayer — COMMENTED** [review]
Still looking at this, but wanted to add the other comment to look at in the mean time.

File: packages/data-context/test/unit/sources/RelevantRunSpecsDataSource.spec.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
+import { expect } from 'chai'
+import sinon from 'sinon'
+
+import { DataContext } from '../../../src'
+import { createTestDataContext } from '../helper'
+import { RelevantRunSpecsDataSource, SPECS_EMPTY_RETURN } from '../../../src/sources'
+import { FAKE_PROJECT_ONE_RUNNING_RUN_ONE_COMPLETED_THREE_SPECS, FAKE_PROJECT_ONE_RUNNING_RUN_ONE_SPEC } from './fixtures/graphqlFixtures'
+
+describe('RelevantRunsDataSource', () => {
```
Comment (warrensplayer) [inline packages/data-context/test/unit/sources/RelevantRunSpecsDataSource.spec.ts]:
```suggestion
describe('RelevantRunSpecsDataSource', () => {
```

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts (hunk 1 above)
Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: Good point. It's how the code was in the video I put in the PR description where it's having the intended effect, let me take a look at why exactly that's the case.

**Review by warrensplayer — COMMENTED** [review]
Just a name update for the test

File: cli/CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@ _Released 02/14/2023 (PENDING)_
 
 - Fixed an issue with the Cloud project selection modal not showing the correct prompts. Fixes [#25520](https://github.com/cypress-io/cypress/issues/25520).
 - Fixed an issue in middleware where error-handling code could itself generate an error and fail to report the original issue. Fixes [#22825](https://github.com/cypress-io/cypress/issues/22825).
+- Fixed an issue in the Debug page where in-progress runs displayed a different count of specs locally compared to the count in Cypress Cloud. Fixes [#25647](https://github.com/cypress-io/cypress/issues/25647).
```
Comment (mike-plummer) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue that could cause the Debug page to display a different number of specs for in-progress runs than shown in Cypress Cloud. Fixes [#25647](https://github.com/cypress-io/cypress/issues/25647).
```

Comment (mike-plummer) [reply cli/CHANGELOG.md]: Just trying to rework to remove the reference to "locally". Since this is the App changelog everything in here is implicitly "local"

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts [hunk 4]
```diff
@@ -153,22 +139,38 @@ export class RelevantRunSpecsDataSource {
...
       }
 
-      if (cloudProject.current && cloudProject.current.runNumber && cloudProject.current.status) {
+      const { current, next } = cloudProject
+
+      if (
+        current
+         && current.runNumber
+         && current.status
+         && typeof current.totalInstanceCount === 'number'
```
Comment (mike-plummer) [inline packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: You could use `Number.isFinite(...)` as well to save a few chars and exclude edge cases like `*Ininity` and `NaN`

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts [hunk 5]
```diff
@@ -153,22 +139,38 @@ export class RelevantRunSpecsDataSource {
...
-          ...this.#calculateSpecMetadata(cloudProject.next.specs || []),
-          runNumber: cloudProject.next.runNumber,
+          totalSpecs: next.totalInstanceCount,
+          completedSpecs: next.completedInstanceCount,
+          runNumber: next.runNumber,
         }
 
-        runSpecsToReturn.statuses.next = cloudProject.next.status
+        runSpecsToReturn.statuses.next = next.status
       }
```
Comment (mike-plummer) [inline packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: This block is pretty much a duplicate of the one above, worth extracting to a fn?

Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: I was marginal on whether to do this or not, and we are about to be right back in here in the next sprint or two doing further modifications. So seems slightly easier on all sides to leave this logic repeated, make the diff super simple, and the shortly we'll combine them in a way that meets the needs we are about to have.

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts (hunk 4 above)
Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: Cool, sure 👍

File: cli/CHANGELOG.md (hunk 3 above)
Comment (marktnoonan) [reply cli/CHANGELOG.md]: Yeah this is better.

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts (hunk 5 above)
Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: I went ahead and made a helper: [`f138cc3` (#25757)](https://github.com/cypress-io/cypress/pull/25757/commits/f138cc379d606c1c286aaec0c59d44cb60d21356)

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts (hunk 1 above)
Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: Updated to move this earlier in the flow, everything seems good anyway.

File: packages/app/src/debug/DebugContainer.cy.tsx [hunk 6]
```diff
@@ -255,6 +257,51 @@ describe('<DebugContainer />', () => {
...
+        onResult: (result) => {
+          if (result.currentProject?.cloudProject?.__typename === 'CloudProject') {
+            const test = result.currentProject.cloudProject.runByNumber
+
+            // Testing this to confirm we are "making impossible states impossible" in the UI,
+            // and document the expectation in this scenario. For clarity,
+            // we do not expect a 'RUNNING` current and next run at the same time, so
+            // the data below represents an invalid state.
+
+            result.currentProject.cloudProject.runByNumber = {
```
Comment (lmiller1990) [inline packages/app/src/debug/DebugContainer.cy.tsx:277]: Instead of modifying this on the fly, should we use the fixtures you added such as `FAKE_PROJECT_MULTIPLE_COMPLETED`?

I find the modified on the fly ones kind of hard to read - you need to have a mental modal of exactly what you are modifying in the first place. How about you?

**Review by lmiller1990 — APPROVED** [review]
Left a comment on the test style, we need to get our graphql testing practices in order - still figuring out what those are.

I would say this is a non-blocking change, though.

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts [hunk 7]
```diff
@@ -141,35 +141,27 @@ export class RelevantRunSpecsDataSource {
...
-          runNumber: current.runNumber,
+      const formatCloudRunInfo = (cloudRunDetails: Partial<CloudRun>) => {
+        const { runNumber, totalInstanceCount, completedInstanceCount } = cloudRunDetails
+
+        if (runNumber && Number.isFinite(totalInstanceCount) && Number.isFinite(completedInstanceCount)) {
+          return {
+            totalSpecs: totalInstanceCount!,
+            completedSpecs: completedInstanceCount!,
+            runNumber,
+          }
```
Comment (warrensplayer) [inline packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: I am still wrapping my head around the best way to do type checking in scenarios like this to confirm that variables are defined.  It stinks that you had to use the `!` to tell typescript that these variables have a value since the `Number.isFinite` does not do that for you.  

This is just a comment and not a blocking request.

**Review by warrensplayer — APPROVED** [review]

File: packages/data-context/src/sources/RelevantRunSpecsDataSource.ts (hunk 7 above)
Comment (mike-plummer) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: Yuck, hadn't considered the typecheck loss. Could use `_.isNumber` which has an appropriate type guard, but that accepts `NaN` and `*Infinity` which isn't ideal. I think we'd have to build a custom type guard to handle our definition of a valid number to get the TS compiler to handle this automatically:

```
function isValidNumber(value: unknown): value is number {
  return Number.isFinite(value)
}
...
if (runNumber && isValidNumber(totalInstanceCount) && isValidNumber(completedInstanceCount)) {
  return {
    totalSpecs: totalInstanceCount,
    completedSpecs: completedInstanceCount,
    runNumber,
  }
}
```

Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: Yeah that seems better than the `!`

Comment (marktnoonan) [reply packages/data-context/src/sources/RelevantRunSpecsDataSource.ts]: updated
