### PR TITLE
fix: Implement { log: false } for clearLocalStorage Issue #6342

### LINKED ISSUE #6342: {log:false} of clearLocalStorage doesn't work.
### Current behavior:

`cy.clearLocalStorage({log:false})` should not show the command on the reporter. But it does. 

### Desired behavior:

It should not show the command.

### Test code to reproduce

```js
it('test', () => {
  cy.clearLocalStorage({log:false})
})
```

Result:

Screenshot from 2020-02-06 15-42-33

### Versions

3.8.3

### PR DESCRIPTION
**Pull request by maddhruv**
- Closes #6342 

### User facing changelog
 add `options` in `clearLocalStorage` for disabling log - https://docs.cypress.io/api/commands/clearlocalstorage.html#Arguments

### Additional details
It's a bugfix enabling the `log` options for `clearLocalStorage` command

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/commands/local_storage.coffee [hunk 1]
```diff
@@ -30,17 +30,20 @@ module.exports = (Commands, Cypress, cy, state, config) ->
...
         $errUtils.throwErrByPath("clearLocalStorage.invalid_argument")
 
       remote = clearLocalStorage(state, keys)
 
-      Cypress.log
-        name: "clear ls"
-        snapshot: true
-        end: true
+      if options.log isnt false
+        options._log = Cypress.log
```
Comment (sainthkh) [inline packages/driver/src/cy/commands/local_storage.coffee]:
```suggestion
      if options.log
        Cypress.log
```

How about removing unnecessary `isnt false` and `options._log`?

Comment (maddhruv) [reply packages/driver/src/cy/commands/local_storage.coffee]: Update in https://github.com/cypress-io/cypress/pull/6495/commits/fc5aacfdbfd00fc584336ec413febc486f2b430e

**Comment by maddhruv** [comment]
@jennifer-shehane Added a test here - https://github.com/cypress-io/cypress/pull/6495/commits/4fff1bdbc473425d5bc207f0c0d461ab968e5e91

File: packages/driver/src/cy/commands/local_storage.coffee [hunk 2]
```diff
@@ -30,17 +30,20 @@ module.exports = (Commands, Cypress, cy, state, config) ->
       null
 
   Commands.addAll({
-    clearLocalStorage: (keys) ->
+    clearLocalStorage: (keys, options = {}) ->
+      _.defaults options, {log: true}
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/local_storage.coffee]: The signature for this can also be `cy.clearLocalStorage(options)`, so we need to handle that case. Something like:

```coffeescript
if _.isPlainObject(keys)
  options = keys
  keys = null
```

Comment (chrisbreiding) [reply packages/driver/src/cy/commands/local_storage.coffee]: Please add a test for this too.

Comment (maddhruv) [reply packages/driver/src/cy/commands/local_storage.coffee]: Sorry for the late reply!

@chrisbreiding I couldn't understand what you are recommending, `options = keys` did you mean if keys are not present treat the first param as options?
Then maybe we should put a check as well `if (typeof keys is object) then options = keys`
Correct me if I am wrong

Comment (chrisbreiding) [reply packages/driver/src/cy/commands/local_storage.coffee]: Yes, that's right. The possible signatures are:

```javascript
cy.clearLocalStorage()
cy.clearLocalStorage(key)
cy.clearLocalStorage(options)
cy.clearLocalStorage(keys, options)
```

Here's an example with `cy.screenshot()`: 

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.coffee#L335

I think it's better to use `_.isPlainObject` though, so it should look like:

```coffeescript
if _.isPlainObject(keys)
  options = keys
  keys = null
```

Comment (maddhruv) [reply packages/driver/src/cy/commands/local_storage.coffee]: @chrisbreiding Did the changes, can you have a look again and review?

**Comment by maddhruv** [comment]
@chrisbreiding can you merge the PR now?
