### PR TITLE
fix: global hooks cause duplicated hooks after domain navigation

### LINKED ISSUE #17705: hooks can rerun on unrelated tests after top navigation
### Current behavior

example: session_spec running hooks multiple times after navigation: https://app.circleci.com/pipelines/github/cypress-io/cypress/22975/workflows/4a639267-6eda-4e78-84b6-5c1f3426f04e/jobs/845803/parallel-runs/7

This occurs when a global before/after hook is present
### Desired behavior

before/after hooks should only be run once and on correct suite

### Test code to reproduce

n/a

### Cypress Version

8.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by Bkucera**
- Closes #17705  
### Additional details
- when tests are resumed after top navigation a global before hook no longer causes already run hooks to rerun
- tested by adding a global hook to `runnable-run-counts.spec`, which would fail without this patch

### PR Tasks
- [x] fix ci

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cypress/runner.js [hunk 1]
```diff
@@ -1341,7 +1348,7 @@ const create = (specWindow, mocha, Cypress, cy, state) => {
       // move to the next runnable - this will be our async seam
       const _next = args[0]
 
-      const test = getTest() || getTestFromRunnable(runnable)
+      const test = getTestFromRunnable(runnable)
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/runner.js:1351]: What's the significance of this change?

Comment (Bkucera) [reply packages/driver/src/cypress/runner.js:1351]: thanks, I'll add a comment

**Review by chrisbreiding — APPROVED** [review]
