### PR TITLE
fix: changes to correct typescript detection behavior

### LINKED ISSUE #22034: System generated cypress.config.ts issue
### Current behavior

upgraded successfully to cypress ver 10

after running cypress open

Select e2e Testing (not configured)

It recommends the following changes 

1. cypress.config.ts
3. cypress\support\e2e.ts
4. cypress\support\commands.ts

click continue
Throws Syntax error eventhough the default cypress.config.ts was system generated

--cypress.config.ts--
```ts
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
}); 
```

### Desired behavior

IT should continue successfully

### Test code to reproduce

SyntaxError
```
Your configFile is invalid: C:\GuiAutomation\cypress.config.ts

It threw an error when required, check the stack trace below:

[Stack trace](http://localhost:54487/__launchpad/index.html#)
C:\GuiAutomation\cypress.config.ts:1

import { defineConfig } from "cypress";
^^^^^^
Your configFile is invalid: C:\GuiAutomation\cypress.config.ts

It threw an error when required, check the stack trace below:

[Stack trace](http://localhost:54487/__launchpad/index.html#)
C:\GuiAutomation\cypress.config.ts:1
import { defineConfig } from "cypress";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadFile (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:103:14)
    at EventEmitter. (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:146:38)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:467:12)
    at process. (C:\Users\santh_lfly\AppData\Local\Cypress\Cache\10.0.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:467:12)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
### Cypress Version

v10.0.1

### Other

Cypress package version: 10.0.1
Cypress binary version: 10.0.1
Electron version: 18.0.4
Bundled Node version:
16.13.2

### PR DESCRIPTION
**Pull request by tgriesser**
- Closes #22034, #21997

### User facing changelog

- Changes the detection to ensure `typescript` actually exists (via `require.resolve`) and is specified in `dependencies` / `devDependencies` before migrating a project to use it. 
- Improves the checks to match the algorithm of whether we should use the `*tsconfig.json` glob, which should only happen when we're creating a new project, not migrating an existing one. If we're migrating, looking at the existing files in the cypress folder should be enough info to make the determination.
- Ensures we explicitly don't include `.d.ts` files when making the determination of JS vs. TS project

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/scaffold-config/src/detect.ts [hunk 1]
```diff
@@ -120,7 +120,22 @@ export function detectLanguage (projectRoot: string, pkgJson: PkgJson): 'js' | '
     debug('Did not find cypress.config file')
   }
 
-  if ('typescript' in (pkgJson.dependencies || {}) || 'typescript' in (pkgJson.devDependencies || {})) {
+  // If we can't find an installed TypeScript or ESBuild, there's no way we can assume the project is using TypeScript,
+  // because it won't work on the next step of installation anyway
+  try {
+    debug('Resolved typescript from %s', require.resolve('typescript', { paths: [projectRoot] }))
```
Comment (mjhenkes) [inline packages/scaffold-config/src/detect.ts:126]: nit, it seems a little weird to be doing the required operation within a debug statement. Not knowing what 'debug' does I don't know if require.resolve is executed or ignored when debug mode is disabled.

```suggestion
    const typescriptFile=  require.resolve('typescript', { paths: [projectRoot] })
    debug('Resolved typescript from %s', typescriptFile )
```

Comment (tgriesser) [reply packages/scaffold-config/src/detect.ts:126]: Fair enough, yeah since it's an argument to `debug` there's nothing about being in debug mode that would change the evaluation of it, but it does read out a bit confusing.

File: packages/scaffold-config/src/detect.ts [hunk 2]
```diff
@@ -83,27 +83,27 @@ export function detectFramework (projectPath: string): DetectFramework {
...
+ *   IF `typescript` dependency in `package.json` AND `tsconfig.json` in `projectRoot/*`
  *     HAS TYPESCRIPT
  *   ELSE
  *     DOES NOT HAVE TYPESCRIPT
  *   END
  * END
  */
 
-export function detectLanguage (projectRoot: string, pkgJson: PkgJson): 'js' | 'ts' {
+export function detectLanguage (projectRoot: string, pkgJson: PkgJson, isMigrating = false): 'js' | 'ts' {
```
Comment (mjhenkes) [inline packages/scaffold-config/src/detect.ts:106]: Consider converting this to take an object instead of a list of params. It's my prefered method instead of adding a boolean parameter. Then you get named arguments instead of a random 'true' at the end of the function and have to look it up to find out what the parameter does.(Maybe typescript helps with this?)

```js
detectLanguage({projectRoot, pkgJson: {}, isMigrating: true})
```

instead of
```js
detectLanguage(projectRoot, {} as PkgJson, true)
```

**Review by mjhenkes — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

File: packages/scaffold-config/src/detect.ts [hunk 3]
```diff
@@ -120,7 +120,24 @@ export function detectLanguage (projectRoot: string, pkgJson: PkgJson): 'js' | '
     debug('Did not find cypress.config file')
   }
 
-  if ('typescript' in (pkgJson.dependencies || {}) || 'typescript' in (pkgJson.devDependencies || {})) {
+  // If we can't find an installed TypeScript or ESBuild, there's no way we can assume the project is using TypeScript,
```
Comment (ZachJW34) [inline packages/scaffold-config/src/detect.ts:123]: nit: `or ESBuild` I don't see anywhere we are checking for ESBuild

**Review by ZachJW34 — APPROVED** [review]
Ran through all the scenarios, works great.

**Review by estrada9166 — APPROVED** [review]
