### PR TITLE
fix(sessions): correct when page is cleared in cy.session()

### LINKED ISSUE #21397: [sessions] Evaluate & Update Clear Page System Event Logs
### What would you like?

Sync notes:
- Clear Page
- Redesign or remove this? TBD
    - *Brian: i think we should keep this*
- Why is there an extra Clear Page at the very end of the session?

### Why is this needed?

Clearly indicate to users when and why we are clearing the page and removing session data. Current messaging and number of clear pages are confusing.

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #21397

### User facing changelog
The session command no longer clears the page between setup and validation and will now always clear the page at the end of the command when test isolation is `on`. Fixes [#21397](https://github.com/cypress-io/cypress/issues/21397).

### How has the user experience changed?

The session command no longer clear the page between setup and validation and will now alway clear the page at the end of the command when test isolation is `on`.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4841
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by chrisbreiding — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

File: packages/driver/src/cy/commands/sessions/utils.ts [hunk 1]
```diff
@@ -194,13 +194,18 @@ const getPostMessageLocalStorage = (specWindow, origins): Promise<any[]> => {
 }
 
 function navigateAboutBlank (session: boolean = true) {
```
Comment (mschile) [inline packages/driver/src/cy/commands/sessions/utils.ts:196]:
```suggestion
function maybeNavigateAboutBlank (session: boolean = true) {
```
