### PR TITLE
fix: fixed issue with CT + electron + run mode not exiting properly

### LINKED ISSUE #25568: Cypress 12.4.0: cypress run --component fails to terminate at end of tests
### Current behavior

In Cypress 12.4.0, running command `cypress run --component` runs all our component tests, but it never terminates.

### Desired behavior

In Cypress 12.3.0, command would terminate when all tests had run.

### Test code to reproduce

1. Write component tests
2. run command `cypress run --component`

### Cypress Version

12.4.0

### Node version

v16.18.0

### Operating System

macOS 12.6.2

### Debug Logs

```shell
cypress:server:browsers killing browser process +2s
  cypress:server:socket-base socket-disconnecting transport close +97ms
  cypress:server:socket-base socket-disconnect transport close +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 63768 } +1s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 63758 } +0ms
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 63780 } +0ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'plugin'      │      2       │ '88712, 89179' │    16.1    │      16.1      │  924.61  │    924.61    │   924.61    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │    '88698'     │    14.8    │      38.3      │  369.33  │    331.74    │   369.33    │
  cypress:server:util:process_profiler │    2    │    'launchpad'    │      1       │    '89658'     │    39.2    │      39.2      │  326.66  │    326.66    │   326.66    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │ '88700, 89157' │    8.8     │      8.8       │  86.23   │    86.23     │    86.23    │
  cypress:server:util:process_profiler │    4    │      'other'      │      1       │    '89680'     │     0      │       0        │    2     │     2.05     │    2.09     │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      7       │      '-'       │    78.9    │     70.35      │ 1708.83  │   1002.54    │   1708.83   │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'plugin'      │      2       │ '88712, 89179' │    0.1     │      8.1       │  807.72  │    866.16    │   924.61    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │    '88698'     │     0      │     25.53      │  369.27  │    344.25    │   369.33    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      2       │ '89157, 88700' │     0      │      4.4       │  85.89   │    86.06     │    86.23    │
  cypress:server:util:process_profiler │    3    │      'other'      │      1       │    '89778'     │     0      │       0        │    2     │     2.03     │    2.09     │
  cypress:server:util:process_profiler │    4    │      'TOTAL'      │      6       │      '-'       │    0.1     │     46.93      │ 1264.88  │   1089.99    │   1708.83   │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │      pids      │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'plugin'      │      2       │ '88712, 89179' │     0      │      5.4       │  807.75  │    846.69    │   924.61    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │    '88698'     │     0      │     19.15      │  373.33  │    351.52    │   373.33    │
  cypress:server:util:process_profiler │    2    │ 'electron-shared' │      2       │ '89157, 88700' │     0      │      2.93      │  86.14   │    86.09     │    86.23    │
  cypress:server:util:process_profiler │    3    │      'other'      │      1       │    '89795'     │     0      │       0        │    2     │     2.02     │    2.09     │
  cypress:server:util:process_profiler │    4    │      'TOTAL'      │      6       │      '-'       │     0      │      35.2      │ 1269.22  │   1134.79    │   1708.83   │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #25568

### Additional details

Removed unneeded code that was causing component tests to hang in `electron` when running multiple specs in `run` mode.

Prior to d1dc1258eafa6ff047abc913ebb930984e02a38d, after running the first spec in electron, the browser instance is [cleared](https://github.com/cypress-io/cypress/blob/8d3a6eed9293c72109bd10a77b2a79e922962705/packages/server/lib/browsers/index.ts#L173) and never set again even after a new spec is started. When `openProject.closeBrowser()` was called, the instance was [null](https://github.com/cypress-io/cypress/blob/8d3a6eed9293c72109bd10a77b2a79e922962705/packages/server/lib/browsers/index.ts#L21) and the promise resolved.

After d1dc1258eafa6ff047abc913ebb930984e02a38d, after running the first spec in electron, the browser instance is [cleared](https://github.com/cypress-io/cypress/blob/8d3a6eed9293c72109bd10a77b2a79e922962705/packages/server/lib/browsers/index.ts#L173) but then it is set to the [new browser instance](https://github.com/cypress-io/cypress/blob/8d3a6eed9293c72109bd10a77b2a79e922962705/packages/server/lib/browsers/index.ts#L130) when the new spec is started. The instance is not cleared again after that. Thus, when `openProject.closeBrowser()` was called, the instance was [not null](https://github.com/cypress-io/cypress/blob/8d3a6eed9293c72109bd10a77b2a79e922962705/packages/server/lib/browsers/index.ts#L21) and the promise never resolved causing the hang.

### Steps to test

* Run multiple component specs in `run` mode in `electron` and verify the process is correctly exited.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/modes/run.ts [hunk 1]
```diff
@@ -814,10 +814,6 @@ async function runSpecs (options: { config: Cfg, browser: Browser, sys: any, hea
     })),
   })
 
-  if (testingType === 'component') {
```
Comment (ZachJW34) [inline packages/server/lib/modes/run.ts:817]: E2E and CT should be closing the browser equivalently so this removal looks good to me!

**Review by ZachJW34 — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

**Review by lmiller1990 — APPROVED** [review]
