### PR TITLE
fix(webpack): allow load custom asset on windows

### LINKED ISSUE #16097: webpack external ressources loading on windows fail with bad path
### Current behavior
When importing a custom font within a css file, the path to load the said font is malformed (see repro)

### Desired behavior
Be able to use custom fonts on tests windows

### Test code to reproduce
On windows
Checkout https://github.com/elevatebart/cy-load-fonts
yarn install
yarn cy

### Versions

```
"cypress": "^7.1.0",
"@cypress/vue": "^2.0.0",
"@cypress/webapck-dev-server": "^1.1.3",
```

### PR DESCRIPTION
**Pull request by elevatebart**
- closes #16097

### User facing changelog
On windows, before this fix, fonts and other assets (images) could not be used since their path was not hitting the `__cypress/src/` root

### Additional details
Was discovered with Jason Fairchild on Discord

### How has the user experience changed?
Before the fix
bug

### CODE REVIEW

File: npm/webpack-dev-server/src/makeWebpackConfig.ts [hunk 1]
```diff
@@ -33,7 +33,10 @@ export async function makeWebpackConfig (userWebpackConfig: webpack.Configuratio
 
   const entry = path.resolve(__dirname, './browser.js')
 
+  // The second line here replaces backslashes on windows with posix compatible slash
+  // See https://github.com/cypress-io/cypress/issues/16097
   const publicPath = path.join(devServerPublicPathRoute, '/')
+  .replace(/\\/g, '/')
```
Comment (agg23) [inline npm/webpack-dev-server/src/makeWebpackConfig.ts:39]: Replacing like this is not safe. Backslashes are valid in POSIX paths. Instead, you should do this
`string.split(path.sep).join('/')` or `string.replace(path.sep, '/')`

**Review by agg23 — CHANGES_REQUESTED** [review]

File: npm/webpack-dev-server/src/makeWebpackConfig.ts (hunk 1 above)
Comment (elevatebart) [reply npm/webpack-dev-server/src/makeWebpackConfig.ts:39]: OK, I will update.

File: npm/webpack-dev-server/src/makeWebpackConfig.ts [hunk 2]
```diff
@@ -22,6 +22,9 @@ interface MakeWebpackConfigOptions extends CypressCTOptionsPluginOptions, UserWe
   isOpenMode: boolean
 }
 
+const OsSeparatorRE = RegExp(`\\${path.sep}`, 'g')
```
Comment (agg23) [inline npm/webpack-dev-server/src/makeWebpackConfig.ts:25]: What is the intention with this regex? I think it's invalid, because the first backslash is escaped `\\`, and the second (if Windows) is not `\`.

This is why I said you should do `string.replace(path.sep, '/'`. If:
* POSIX - Replace all forward slashes with forward slashes. Backslashes will stay in place. Nothing wrong
* Windows - Replace all backslashes with forward slashes. All backslashes should directly translate into a POSIX path, with perhaps the exception of the drive letter (`C:\\` -> `C://`). Nothing wrong

Also, if you don't want `/` as a magic value, I believe you can get it with `path.posix.sep` or something like that

Comment (lmiller1990) [reply npm/webpack-dev-server/src/makeWebpackConfig.ts:25]: These regexps are quite hard to read, this might be a good opportunity for some focused unit tests to make it clear what substitution is actually happening.

I am guessing this was tested on an actual windows machine so I have no doubt it works correctly.

**Review by lmiller1990 — APPROVED** [review]
I am really surprised we have to do this manually - is there no library that handles all these edge cases? I thought `fs` would do that.

File: npm/webpack-dev-server/src/makeWebpackConfig.ts (hunk 2 above)
Comment (agg23) [reply npm/webpack-dev-server/src/makeWebpackConfig.ts:25]: This regex _will_ have problems on POSIX

**Review by agg23 — APPROVED** [review]
