### PR TITLE
fix: add cy.then timeouts to cy.session

### LINKED ISSUE #29496: cy.session failure that didn't come from my code
### Current behavior

I got this failure once. Unfortunately it did not fail the second time, so it is not easily repeatable.

As far as I can tell, the failure came from within cypress, and not from my code.

```
2024-05-09 12:06:40      1 failing
2024-05-09 12:06:40    
2024-05-09 12:06:40      1) cloud deployment smoke tests
2024-05-09 12:06:40           should successfully log in to the customer portal and select a tenant:
2024-05-09 12:06:40         CypressError: `cy.then()` timed out after waiting `10000ms`.
2024-05-09 12:06:40    
2024-05-09 12:06:40    Your callback function returned a promise that never resolved.
2024-05-09 12:06:40    
2024-05-09 12:06:40    The callback function was:
2024-05-09 12:06:40    
2024-05-09 12:06:40    async () => {
2024-05-09 12:06:40              setSessionLogStatus(_utils__WEBPACK_IMPORTED_MODULE_6__.statusMap.inProgress(_utils__WEBPACK_IMPORTED_MODULE_6__.SESSION_STEPS.restore));
2024-05-09 12:06:40              await (0,_utils__WEBPACK_IMPORTED_MODULE_6__.navigateAboutBlank)();
2024-05-09 12:06:40              await sessions.clearCurrentSessionData();
2024-05-09 12:06:40              return restoreSession(existingSession);
2024-05-09 12:06:40            }
2024-05-09 12:06:40    
2024-05-09 12:06:40    [https://on.cypress.io/then](https://on.cypress.io/then%1B[0m%1B[90m)
2024-05-09 12:06:40          at <unknown> ([...]__cypress/runner/cypress_runner.js:118823:75)
2024-05-09 12:06:40          at tryCatcher ([...]__cypress/runner/cypress_runner.js:1807:23)
2024-05-09 12:06:40          at <unknown> ([...]__cypress/runner/cypress_runner.js:4186:41)
2024-05-09 12:06:40          at tryCatcher ([...]__cypress/runner/cypress_runner.js:1807:23)
2024-05-09 12:06:40          at Promise._settlePromiseFromHandler ([...]__cypress/runner/cypress_runner.js:1519:31)
2024-05-09 12:06:40          at Promise._settlePromise ([...]__cypress/runner/cypress_runner.js:1576:18)
2024-05-09 12:06:40          at Promise._settlePromise0 ([...]__cypress/runner/cypress_runner.js:1621:10)
2024-05-09 12:06:40          at Promise._settlePromises ([...]__cypress/runner/cypress_runner.js:1697:18)
2024-05-09 12:06:40          at _drainQueueStep ([...]__cypress/runner/cypress_runner.js:2407:12)
2024-05-09 12:06:40          at _drainQueue ([...]__cypress/runner/cypress_runner.js:2400:9)
2024-05-09 12:06:40          at Async._drainQueues ([...]__cypress/runner/cypress_runner.js:2416:5)
2024-05-09 12:06:40          at Async.drainQueues ([...]__cypress/runner/cypress_runner.js:2286:14)
```

### Desired behavior

_No response_

### Test code to reproduce

Here is a snippet of my test:

```js
    cy.session([email, sessionCacheId], () => {
      cy.visit(this.url);

      cy.origin(
        this.b2cSigninUrl,
        { args: { email, password }},
        // eslint-disable-next-line @typescript-eslint/no-shadow
        ({ email, password }) => {
          cy.url().should('match', new RegExp(`^${Cypress.env('b2cHostUrl')}`));

          cy.get('[id="signInName"]').clear();
          cy.get('[id="signInName"]').type(email);

          cy.get('[id="password"]').clear();
          cy.get('[id="password"]').type(password);

          cy.get('[id="next"]').click();
        });

      cy.url().should('match', new RegExp(`^${this.url}`));
      cy.url().should('not.contain', '/id/signin');

      cy.window().then((win) => {
        // ensure selected tenant is not cached in session
        win.sessionStorage.removeItem(this.tenantStorageKey);
      });
    }, {
      cacheAcrossSpecs: true
    });
```

### Cypress Version

13.9.0

### Node version

20.12.2

### Operating System

Ubuntu 22.04

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes https://github.com/cypress-io/cypress/issues/29496

### Additional details

We've observed cases where the load event for navigating to `about:blank` has taken more than 4 seconds but does eventually resolve. This can cause the `cy.session` command to fail since we don't define our own timeouts for the `cy.then` calls within `cy.session`. In order to resolve this issue, we are adding a timeout of 20s to the internal `cy.then` calls. Long term, we will probably want to investigate removing some of the internal `cy.then` calls since they may not be needed.

Custom debug logs showing the `about:blank` page taking ~6s to load:
> 10:59:49.7158097Z cypress:aut-iframe: Setting iframe src to about:blank
10:59:49.7171870Z cypress:useEventManager: Page loading state changed: true
10:59:56.0246856Z cypress:aut-iframe: Blank page loaded

### Steps to test

* I forced loading the `about:blank` page to take longer than the `defaultCommandTimeout` and verified it failed before and passes with the new timeouts.

### How has the user experience changed?

Before:
Screenshot 2025-05-27 at 11 46 27 AM

After:
Screenshot 2025-05-27 at 11 45 18 AM

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/runner/aut-iframe.ts [hunk 1]
```diff
@@ -126,6 +126,8 @@ export class AutIframe {
   visitBlankPage = (testIsolation?: boolean) => {
     return new Promise<void>((resolve) => {
       if (!this.$iframe) {
+        resolve()
+
         return
```
[the remark this answers is not in the document]
Comment (mschile) [reply packages/app/src/runner/aut-iframe.ts:131]: I don't really follow this recommendation, the `resolve` and `return` are already enclosed in the `if` statement's braces.

File: packages/driver/src/cy/commands/sessions/index.ts [hunk 2]
```diff
@@ -21,6 +21,8 @@ import {
  *  - session data SHOULD be cleared between specs in run mode
  */
 export default function (Commands, Cypress, cy) {
+  const COMMAND_TIMEOUT = 20000
```
[the remark this answers is not in the document]
Comment (mschile) [reply packages/driver/src/cy/commands/sessions/index.ts]: added comment: [15b1a02](https://github.com/cypress-io/cypress/pull/31788/commits/15b1a025f53e9f2392c82b3867688be7430626fd)

File: packages/driver/src/cy/commands/sessions/index.ts [hunk 3]
```diff
@@ -21,6 +21,9 @@ import {
  *  - session data SHOULD be cleared between specs in run mode
  */
 export default function (Commands, Cypress, cy) {
+  // 20s timeout used for internal cy commands within the session command
+  const COMMAND_TIMEOUT = 20_000
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/commands/sessions/index.ts]: Maybe this should be named INTERNAL_COMMAND_TIMEOUT? I could see this being confusing for a future dev possibly just looking at the code below alone.

**Review by jennifer-shehane — APPROVED** [review]
whew, that's a lot of thens 😞

File: packages/driver/src/cy/commands/sessions/index.ts (hunk 3 above)
Comment (mschile) [reply packages/driver/src/cy/commands/sessions/index.ts]: renamed: [e205112](https://github.com/cypress-io/cypress/pull/31788/commits/e2051127bf6dbbdd6cd8f768d148d2d2df77d249)

File: cli/CHANGELOG.md [hunk 4]
```diff
@@ -3,6 +3,10 @@
 
 _Released 6/3/2025 (PENDING)_
 
+**Bugfixes:**
+
+- Fixed an issue where `cy.session` may fail internally if navigating to `about:blank` takes longer than the `defaultCommandTimeout`. Addresses [#29496](https://github.com/cypress-io/cypress/issues/29496).
```
Comment (AtofStryker) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue where `cy.session()` may fail internally if navigating to `about:blank` takes longer than the `defaultCommandTimeout`. Addresses [#29496](https://github.com/cypress-io/cypress/issues/29496).
```

**Review by AtofStryker — APPROVED** [review]
