### PR TITLE
fix: next trace error

### LINKED ISSUE #17992: Next.js ^11.1.1 : webpack error + bundling step timeout
### Current behavior

Using the [create next app webpack 5 example](https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-next-app-webpack-5) setup, with `"next": "latest"` that resolves to `^11.1.1`. 

Result in a TypeError and a timeout on the bundling step
```
✖ ｢wdm｣: TypeError: Cannot read property 'traceChild' of undefined
...
ℹ ｢wdm｣: wait until bundle finished: /__cypress/src/index.html
```

### Desired behavior

_No response_

### Test code to reproduce

[create next app webpack 5 example](https://github.com/cypress-io/cypress-component-testing-examples/tree/main/create-next-app-webpack-5) setup with `"next": "latest"` (`11.1.1` or `11.1.2`)

### Cypress Version

^8.3.0

## workaround / temporary solution :

use exact version at `11.1.0`

```
"next": "11.1.0"
```

tnx https://github.com/cypress-io/cypress/discussions/17883#discussioncomment-1233406

### PR DESCRIPTION
**Pull request by ZachJW34**
- Closes #17992 

### User facing changelog
Fix webpack error with next >= 11.1.1

### Additional details
Next introduced tracing in v11.1.1. The trace is a required option for `getNextJsBaseWebpackConfig`, so this PR adds that. If trace doesn't exist, it's a no-op.

### How to test
I tested this by creating a branch inside `cypress-component-testing-examples` (the deps are slightly out of date so I updated most of them, plus `create-next-app` doesn't use Webpack 4 so I forced it). You can run:
```
// On this branch
yarn workspace @cypress/react build-prod

git clone https://github.com/cypress-io/cypress-component-testing-examples.git
git checkout next-trace-error
cd ./create-next-app-webpack-5 && yarn
npx cypress open-ct # Will error with traceChild
# Copy and paste dist and plugins folder from newly built @cypress/react into local node_modules (yarn add -D @cypress/react@file:path-to-react package was hanging so I don't have a better way to test this)
npx cypress open-ct # Will pass!
```

You can repeat the above inside of `create-next-app` which will test Webpack 4. Also, you can change the Next version to `11.1.0` and verify that this change isn't breaking previous versions.

### How has the user experience changed?
Next with Webpack 5 and Next >= 11.1.1 works

### PR Tasks
NA

### CODE REVIEW

File: npm/react/plugins/next/findNextWebpackConfig.js [hunk 1]
```diff
@@ -3,6 +3,7 @@
 const debug = require('debug')('@cypress/react')
 const getNextJsBaseWebpackConfig = require('next/dist/build/webpack-config').default
 const { findPagesDir } = require('../../dist/next/findPagesDir')
+const { getRunWebpackSpan } = require('../../dist/next/getRunWebpackSpan')
```
Comment (elevatebart) [inline npm/react/plugins/next/findNextWebpackConfig.js:6]: Can we avoid referencing the `dist` folder from the plugins?
My 2 reasons:
- `dist` does not always exist (sometimes it's called `out` sometimes build)
- It took me a good 10 min to fin out why I could not test your repo as I thought plugins were not transpiled.

If we choose to transpile the plugins. We should do it entirely.
I believe this is confusing.

Instead could you replace your ts code with js code.

Another piece of info you might need: @cowboy and the DX team plan on moving all those "plugins" in their own package as soon as they can. I would hold off refactoring everything too fast.

**Review by elevatebart — CHANGES_REQUESTED** [review]
For some reason I still have the following traceChild error 
```
[webpack-dev-middleware] TypeError: Cannot read property 'traceChild' of undefined
    at /Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/build/webpack/plugins/profiling-plugin.js:31:45
    at Hook.eval [as callAsync] (eval at create (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:33832:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:33634:14)
    at Compiler.compile (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:48339:28)
    at /Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75800:19
    at Hook.eval [as callAsync] (eval at create (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:33832:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:33634:14)
    at run (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75754:33)
    at /Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75749:6
    at Compiler.readRecords (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:48176:11)
    at run (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75745:26)
    at Watching._go (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75804:3)
    at Watching._invalidate (/Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75981:9)
    at /Users/bart/Documents/exp/next-wp-5-cy/node_modules/next/dist/compiled/webpack/bundle5.js:75667:28
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Here is the repo I use https://github.com/elevatebart/next-wp-5-cy

File: npm/react/plugins/next/findNextWebpackConfig.js (hunk 1 above)
Comment (ZachJW34) [reply npm/react/plugins/next/findNextWebpackConfig.js:6]: I'm following the advice based on the review of [this PR](https://github.com/cypress-io/cypress/pull/18009#pullrequestreview-748333727). I personally think adding a small amount of javascript is fine with the context of fixing a small bug but I've already started writing typescript so I carried on that trend for this PR.

**Comment by ZachJW34** [comment]
@elevatebart I checked out your repo and didn't see the `traceChild` error after copying the new `next/plugins` code. Can you provide some steps on how you tested the local code in your repo?

File: npm/react/plugins/next/findNextWebpackConfig.js (hunk 1 above)
Comment (elevatebart) [reply npm/react/plugins/next/findNextWebpackConfig.js:6]: I see, sorry about the confusion. 
I will check directly with her.

**Review by elevatebart — APPROVED** [review]
@ZachJW34 I swear I saw it fail.

It worked, sorry fo the weirdness I guessed I missed a file to copy.

**Comment by lmiller1990** [comment]
I tried following the instructions here and in the original issue but I can't reproduce the problem. Looks like @elevatebart did though. Are we good to merge?

Kind of curious why I wasn't seeing the error. Weird.

**Comment by elevatebart** [comment]
This fixed worked for me, it is not introducing regressions
@ZachJW34 let's merge!

LGTM

File: npm/react/plugins/next/findNextWebpackConfig.js (hunk 1 above)
Comment (JessicaSachs) [reply npm/react/plugins/next/findNextWebpackConfig.js:6]: This isn't different than the existing patterns we have. Yes, we will be redoing these servers but not in the next 3 months.
