### PR TITLE
Better handle reserved key CYPRESS_ENV being set by users to valid values

### LINKED ISSUE #6436: Warn when using reserved key `CYPRESS_ENV` with non production value
### Current behavior: 

`CYPRESS_ENV` is a reserved key used to internally point to the API database to be used for communication from the Test Runner. 

We previously included erroring when invalid keys were sent to `CYPRESS_ENV` because a very unexpected crash would happen in these cases: https://github.com/cypress-io/cypress/issues/1621

But, we do not warn users when setting the `CYPRESS_ENV` to a valid value that this is a reserved key. This is likely a very small use case (although we had two customers do this), but the consequences are very, very confusing - there is no indication that setting the `CYPRESS_ENV` would have been a mistake on their part.

### Desired behavior:

**Why is someone doing this?**

They simply want to access an environment variable with the name `env`. This is a legitimate use case and this is [not the first person to set `CYPRESS_ENV` environment variable](https://github.com/cypress-io/cypress/issues/1614). For example, if you do `CYPRESS_HOST=foo`, you can then access this later using `CYPRESS.env('HOST')` which will be 'foo'. 

Unfortunately, this will not work as intended since `CYPRESS_ENV` is reserved for internal uses. 

We need to **warn** when using `CYPRESS_ENV` to set a value other than `production`, that this is a reserved key and will not do what they intend. We cannot throw because our internal team needs to  continue connecting to these API databases for testing and development. 

### Test code to reproduce

Mostly this problem is exhibited the worst during `record` since we hit our databases to record then. One example below:

```shell
CYPRESS_ENV=test cypress run --record --key abc123
```

### Versions

4.0.1

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes #6436

### User facing changelog

- We now warn when setting the reserved key `CYPRESS_INTERNAL_ENV` to a non-production value. 

### Additional details

- I've renamed the `CYPRESS_ENV` variable to `CYPRESS_INTERNAL_ENV`. The use of this keyword is not *frequent*, but the consequences of accidentally setting it are complete blocker for users *trying to record* and it a real headache to debug from within support.
- We were previously only erroring and exiting on invalid values, but a user could pass valid, non-production values that would result in unexpected consequences. We now warn in this situation so they would at least get some indication that they did something wrong.
- The check for 'non-production' values includes a check for `undefined` which will set our default and I don't suspect anyone would set 'undefined' anyway. 

See https://github.com/cypress-io/cypress-services/issues/2194

#### Before: Can't find projectID

The most optimistic error is that it can't find the projectId (because the project doesn't exist in staging) - this results in a string of emails to support because their project definitely exists!

```
$ CYPRESS_ENV=staging cypress run --record --key abc123
We could not find a project with the ID: f0paa2

This projectId came from your 'cypress.json' file or an environment variable.

Please log into the Dashboard and find your project.

We will list the correct projectId in the 'Settings' tab.

Alternatively, you can create a new project using the Desktop Application.

https://on.cypress.io/dashboard
```

#### Before: recording to staging db 😬 

If their project is found, it could just record to staging - this results in a string of emails to support because they see it recording but do not see the recordings in their Dashboard!

```
$ CYPRESS_ENV=staging cypress run --record --key abc123

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.8.3                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      1 found (api_spec.js)  
  │ Params:     Tag: false, Group: false, Parallel: false                                          │
  │ Run URL:    https://dashboard-staging.cypress.io/projects/123456/runs/3777                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

#### After: 

The `CYPRESS_ENV` is now `CYPRESS_INTERNAL_ENV, which is less likely to be set by users for their own use.

#### After: Warning when setting to not `production` or `undefined`

```
$ CYPRESS_INTERNAL_ENV=staging cypress run --record --key abc123

⚠ Warning: It looks like you're passing CYPRESS_INTERNAL_ENV=staging

The environment variable "CYPRESS_INTERNAL_ENV" is reserved and should only be used internally.

Unset the "CYPRESS_INTERNAL_ENV" environment variable and run Cypress again.
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2587
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: cli/lib/cli.js [hunk 1]
```diff
@@ -167,14 +167,32 @@ module.exports = {
       args = process.argv
     }
 
-    if (!util.isValidCypressEnvValue(process.env.CYPRESS_ENV)) {
-      debug('invalid CYPRESS_ENV value', process.env.CYPRESS_ENV)
+    const CYPRESS_INTERNAL_ENV = process.env.CYPRESS_INTERNAL_ENV
```
Comment (bahmutov) [inline cli/lib/cli.js]: just to avoid repetition
```js
const {CYPRESS_INTERNAL_ENV} = process.env
```

**Review by bahmutov — DISMISSED** [review]
nice, will avoid the unnecessary confusion
