### PR TITLE
Automatically retry verify and run commands on Linux if suspect DISPLAY problem

### LINKED ISSUE #4034: Presence of DISPLAY env var causes "Cypress failed to start"
### Current behavior:

1. Have `DISPLAY` env var set
1. `cypress run`:

```
Verifying Cypress can run /root/.cache/Cypress/3.2.0/Cypress [failed]
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Command failed: /root/.cache/Cypress/3.2.0/Cypress/Cypress --smoke-test --ping=177
----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.2.0
```

### Desired behavior:

`cypress run` runs regardless of presence of `DISPLAY` variable.

### Steps to reproduce: (app code and test code)
 
* Stock [Cypress Docker image](https://docs.cypress.io/examples/examples/docker.html#Images).
* Running on [Semaphore 2.0](https://semaphoreci.com/blog/2018/11/06/semaphore-2-0-launched.html)
* `--config baseUrl=www.example.com`

This **was working** until a few days ago when we started observing `Cypress failed to start`.
Inspecting logs we noticed that Semaphore had began injecting a `DISPLAY` env var. We reached out to Semaphore and they confirmed:

> Thanks for reporting this.
>
> The $DISPLAY=:99 change was introduced two days ago as a part of improvements and fixes activities. This change helps with some workflows that are using Selenium/Chrome combination. Since this positively affected a given group of our users, we introduced this change.
> 
> I shared this message with the platform team and we will let you know as soon as we have any new information. Until then, please use the workaround you described.
> 
> Thanks for your patience.

### Versions

* Stock [Cypress Docker image](https://docs.cypress.io/examples/examples/docker.html#Images)
* `npm install` Cypress 3.2.0
* Running on [Semaphore 2.0](https://semaphoreci.com/blog/2018/11/06/semaphore-2-0-launched.html) using Docker image (per [Semaphore docs](https://docs.semaphoreci.com/article/78-working-with-docker-images#using-a-public-docker-image-in-cicd-jobs))

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #4034 
- if the first verify retry fails, reruns with our XVFB. If still fails, shows error message with first and second errors
- [x] should display a warning message if gets a display error on the first verify attempt
- [x] should retry `cypress run` if there is suspected display error (shows warning as well)

`cypress run` warning on Linux if DISPLAY is set before re-running with our XVFB

```
⚠ Warning: Cypress process has finished very quickly with an error,
which might be related to a potential problem with how the DISPLAY is configured.

DISPLAY was set to "test-display"

We will attempt to spin our XVFB server and run Cypress again.
```

Note: to see how it performs, spin a Docker container (instructions in a comment below) and 

- to see cypress verify use

```
node -e 'require("./cli/lib/tasks/verify").start({force: true})'
```

- to see spawn cypress run use 

```
node -e 'require("./cli/lib/exec/spawn").start(["--run-project", "."], {dev: true})
```

### CODE REVIEW

File: cli/test/lib/errors_spec.js [hunk 1]
```diff
@@ -29,5 +30,51 @@ describe('errors', function () {
...
+      .then((text) => {
+        snapshot(text)
+        expect(solution).to.have.been.calledOnce
+      })
+    })
+
+    it('expects solution to be a string', () => {
+      const error = {
+        description: 'description',
+        solution: 42,
```
Comment (bahmutov) [inline cli/test/lib/errors_spec.js]: 42 is never a good answer

**Comment by bahmutov** [comment]
ughh, what is going on with Win32 build
```
15:00:18 #buildPackages win32
npm run all build -- --serial --skip-packages cli
> cypress@3.3.0 all C:\projects\cypress
> node ./scripts/run.js "build" "--serial" "--skip-packages" "cli"
npm ERR! file undefined
npm ERR! path undefined
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn undefined
npm ERR! cypress@3.3.0 all: `node ./scripts/run.js "build" "--serial" "--skip-packages" "cli"`
npm ERR! spawn undefined ENOENT
npm ERR! 
npm ERR! Failed at the cypress@3.3.0 all script.
```

**Comment by bahmutov** [comment]
found that we can detect X11 problem using a flag

```
root@eabed8eaef87:/cypress/cli# ../packages/electron/dist/Cypress/Cypress --enable-logging
[215:0509/165930.091489:WARNING:browser_main_loop.cc(275)] <unknown>: Could not open X display
[215:0509/165930.091727:WARNING:browser_main_loop.cc(275)] Gtk: cannot open display: 99
root@eabed8eaef87:/cypress/cli# 
```

so need to switch this PR to enable logging during verify step

**Comment by bahmutov** [comment]
the way to see this locally (via Docker)
- run Docker in the cypress root folder
```
docker run -it -v $PWD:/cypress -w /cypress cypress/browsers:node8.9.3-chrome73
```
- in the container install global Cypress binary (so you have something to verify)
```
npm i -g cypress@3.2.0
```
- set binary as environment variable pointing at the newly installed binary
```
export CYPRESS_RUN_BINARY=/root/.cache/Cypress/3.2.0/Cypress/Cypress
```
- set DISPLAY variable to something and start node
```
export DISPLAY=99
node
```
- load verify task module and execute it
```js
var verify = require('./cli/lib/tasks/verify')
verify.start({force: true})
```
If the verify code uses `--enable-logging` then you should see the good message
```
  cypress:cli smoke test command: /root/.cache/Cypress/3.2.0/Cypress/Cypress --smoke-test --ping=471 --enable-logging +1ms
  cypress:cli Smoke test failed: { Error: Command failed: /root/.cache/Cypress/3.2.0/Cypress/Cypress --smoke-test --ping=471 --enable-logging
[769:0509/181151.619094:WARNING:browser_main_loop.cc(258)] Gtk: cannot open display: 99


    at makeError (/cypress/cli/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/cypress/cli/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '[769:0509/181151.619094:WARNING:browser_main_loop.cc(258)] Gtk: cannot open display: 99\n',
  failed: true,
  signal: null,
  cmd: '/root/.cache/Cypress/3.2.0/Cypress/Cypress --smoke-test --ping=471 --enable-logging',
  timedOut: false,
  killed: false } +82ms
 ✖  Verifying Cypress can run /root/.cache/Cypress/3.2.0/Cypress
   → Cypress Version: 0.0.0
Unhandled rejection Error: Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

We have noticed that DISPLAY variable is set to "99"
This might be a problem if X11 server is not responding.

https://github.com/cypress-io/cypress/issues/4034

Try deleting the DISPLAY variable and running the command again.

----------

[769:0509/181151.619094:WARNING:browser_main_loop.cc(258)] Gtk: cannot open display: 99

----------

Platform: linux (Debian - 8.11)
Cypress Version: 0.0.0
```

File: cli/lib/exec/xvfb.js [hunk 2]
```diff
@@ -41,7 +43,33 @@ module.exports = {
...
-    return os.platform() === 'linux' && !process.env.DISPLAY
+    if (os.platform() !== 'linux') {
+      return false
+    }
+
+    if (process.env.DISPLAY) {
+      const issueUrl = util.getGitHubIssueUrl(4034)
+
+      const message = stripIndent`
+        DISPLAY environment variable is set to ${process.env.DISPLAY} on Linux
```
Comment (bahmutov) [inline cli/lib/exec/xvfb.js]: being verbose is good, hopefully, someone reads it and understand the problem, even if we work around it using our XVFB

**Comment by bahmutov** [comment]
uggh, if we enable Cypress logging during full `cypress spawn`, there is a lot of extra stuff displayed
```
  cypress:server:cypress starting cypress with argv [ '/cypress/packages/electron/dist/Cypress/Cypress', '--cwd=/cypress', '--config={}', '--enable-logging' ] +0ms
[4598:0509/220121.170576:ERROR:bus.cc(395)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
  cypress:server:cypress starting in mode interactive +3s
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
[4598:0509/220139.987910:ERROR:bus.cc(395)] Failed to connect to the bus: Address does not contain a colon
[4598:0509/220140.032274:ERROR:bus.cc(395)] Failed to connect to the bus: Address does not contain a colon
[4598:0509/220140.630393:INFO:CONSOLE(73528)] "%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq", source: file:///cypress/packages/desktop-gui/dist/app.js (73528)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(Cypress:4598): dconf-WARNING **: failed to commit changes to dconf: Address element '/dev/null' does not contain a colon (:)
[4598:0509/220233.220295:ERROR:bus.cc(395)] Failed to connect to the bus: Address does not contain a colon
GET /__/ 200 217.315 ms - -
```

File: cli/__snapshots__/errors_spec.js [hunk 3]
```diff
@@ -16,18 +27,54 @@ Cypress Version: 1.2.3
 `
 
 exports['errors individual has the following errors 1'] = [
```
Comment (bahmutov) [inline cli/__snapshots__/errors_spec.js]: the names of the errors are now sorted before snapshotting

File: cli/__snapshots__/errors_spec.js [hunk 4]
```diff
@@ -1,3 +1,14 @@
+exports['errors .errors.formErrorText calls solution if a function 1'] = `
```
Comment (bahmutov) [inline cli/__snapshots__/errors_spec.js]: added ability to have error solution being a function, not just static text

File: cli/__snapshots__/install_spec.js [hunk 5]
```diff
@@ -95,6 +95,9 @@ https://on.cypress.io/installing-cypress
 exports['invalid cache directory 1'] = `
 Error: Cypress cannot write to the cache directory due to file permissions
 
+See discussion and possible solutions at
+https://github.com/cypress-io/cypress/issues/1281
```
Comment (bahmutov) [inline cli/__snapshots__/install_spec.js]: filled missing solution for this error, pointing at the GH issue

File: cli/__snapshots__/verify_spec.js [hunk 6]
```diff
@@ -159,7 +159,7 @@ Error: Cypress verification timed out.
 
 This command failed with the following output:
 
-/cache/Cypress/1.2.3/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=222
+/cache/Cypress/1.2.3/Cypress.app/Contents/MacOS/Cypress --smoke-test --ping=222 --enable-logging
```
Comment (bahmutov) [inline cli/__snapshots__/verify_spec.js]: when verifying Cypress enable logging so we can tell if this is display error

File: cli/lib/errors.js [hunk 7]
```diff
@@ -102,6 +108,39 @@ const smokeTestFailure = (smokeTestCommand, timedOut) => {
   }
 }
 
+const invalidDisplayError = {
```
Comment (bahmutov) [inline cli/lib/errors.js]: a complex error that has both the display error and the follow-up error

File: cli/lib/errors.js [hunk 8]
```diff
@@ -118,7 +157,10 @@ const missingDependency = {
 
 const invalidCacheDirectory = {
   description: 'Cypress cannot write to the cache directory due to file permissions',
-  solution: '',
+  solution: stripIndent`
+    See discussion and possible solutions at
+    ${chalk.blue(util.getGitHubIssueUrl(1281))}
```
Comment (bahmutov) [inline cli/lib/errors.js]: at least give the relevant issue url

File: cli/lib/errors.js [hunk 9]
```diff
@@ -205,20 +245,41 @@ function formErrorText (info, msg) {
...
-    add(`
-      ${obj.description}
+    la(is.unemptyString(obj.description),
+      'expected error description to be text', obj.description)
 
-      ${obj.solution}
+    // assuming that if there the solution is a function it will handle
+    // error message and (optional previous error message)
+    if (is.fn(obj.solution)) {
+      const text = obj.solution(msg, prevMessage)
```
Comment (bahmutov) [inline cli/lib/errors.js]: if error solution property is a function, let it form the full error text

File: cli/lib/exec/spawn.js [hunk 10]
```diff
@@ -91,6 +96,12 @@ module.exports = {
           options = _.extend({}, options, { windowsHide: false })
         }
 
+        if (os.platform() === 'linux' && process.env.DISPLAY) {
+          // make sure we use the latest DISPLAY variable if any
+          debug('passing DISPLAY', process.env.DISPLAY)
+          options.env.DISPLAY = process.env.DISPLAY
```
Comment (bahmutov) [inline cli/lib/exec/spawn.js]: otherwise a new value from XVFB will not take effect

File: cli/lib/exec/spawn.js [hunk 11]
```diff
@@ -101,17 +112,21 @@ module.exports = {
...
-
-          // bail if this is warning line garbage
-          if (isXlibOrLibudevRe.test(str) || isHighSierraWarningRe.test(str)) {
-            return
-          }
-
-          // else pass it along!
-          process.stderr.write(data)
-        })
+        child.stderr &&
```
Comment (bahmutov) [inline cli/lib/exec/spawn.js]: just a little bit of reformatting

File: cli/lib/exec/spawn.js [hunk 12]
```diff
@@ -133,18 +148,55 @@ module.exports = {
...
     if (needsXvfb) {
-      return xvfb.start()
-      .then(userFriendlySpawn)
-      .finally(xvfb.stop)
+      return spawnInXvfb()
     }
 
-    return userFriendlySpawn()
-
+    return userFriendlySpawn(os.platform() === 'linux')
```
Comment (bahmutov) [inline cli/lib/exec/spawn.js]: if we are on Linux, and there is a display problem, we should attempt handling it once

File: cli/lib/tasks/verify.js [hunk 13]
```diff
@@ -89,25 +130,34 @@ const runSmokeTest = (binaryDir, options) => {
...
       .catch(onXvfbError)
     })
   }
 
+  if (needsXvfb) {
+    return spinXvfbAndVerify()
+  }
+
   return spawn()
+  .catch({ displayError: true, platform: 'linux' }, (e) => {
```
Comment (bahmutov) [inline cli/lib/tasks/verify.js]: handle display error once

File: cli/test/lib/errors_spec.js [hunk 14]
```diff
@@ -29,5 +29,48 @@ describe('errors', function () {
...
+      }
+
+      return expect(formErrorText(error)).to.be.rejected
```
Comment (bahmutov) [inline cli/test/lib/errors_spec.js]: chai-as-promised is nice

File: package.json [hunk 15]
```diff
@@ -33,6 +33,7 @@
     "clean-deps": "npm run all clean-deps && rm -rf node_modules",
     "docker": "./scripts/run-docker-local.sh",
     "lint-js": "eslint --fix scripts/*.js packages/ts/*.js cli/*.js cli/**/*.js",
+    "lint-changed": "git diff --name-only | grep '\\.js$' | xargs npx eslint --fix",
```
Comment (bahmutov) [inline package.json]: little utility to fix all changes JS files before committing

File: packages/electron/lib/electron.coffee [hunk 16]
```diff
@@ -72,6 +72,10 @@ module.exports = {
 
       debug("spawning %s with args", execPath, argv)
 
+      if debug.enabled
+        # let's see everything Electron spits back
+        argv.push("--enable-logging")
```
Comment (bahmutov) [inline packages/electron/lib/electron.coffee]: when running with `DEBUG=cypress:electron` it would be nice to see everything

File: packages/server/lib/cypress.coffee [hunk 17]
```diff
@@ -54,12 +61,32 @@ module.exports = {
...
         new Promise (resolve) ->
           cypressElectron = require("@packages/electron")
+          electronStarted = Number(new Date())
           fn = (code) ->
             ## juggle up the totalFailed since our outer
             ## promise is expecting this object structure
             debug("electron finished with", code)
-            resolve({totalFailed: code})
-          cypressElectron.open(".", require("./util/args").toArray(options), fn)
+            electronFinished = Number(new Date())
```
Comment (bahmutov) [inline packages/server/lib/cypress.coffee]: detect display or missing dependency problem by noticing how quickly Electron exits. If we suspect display or missing dependency problem then return a special exit code

File: cli/__snapshots__/errors_spec.js [hunk 18]
```diff
@@ -16,18 +27,54 @@ Cypress Version: 1.2.3
...
+  "smokeTestFailure",
+  "unexpected",
+  "versionMismatch"
 ]
+
+exports['invalid display error'] = `
+Cypress failed to start.
+
+First, we have tried to start Cypress using your DISPLAY settings
+but his the following problem:
```
Comment (Bkucera) [inline cli/__snapshots__/errors_spec.js]: typo

**Review by kuceb — DISMISSED** [review]

**Review by kuceb — APPROVED** [review]

**Comment by Bkucera** [comment]
Did the same driver-integration test just fail twice?

**Comment by bahmutov** [comment]
did it?
```
1) src/cy/commands/actions/type #type value changing [contenteditable] can type into an iframe with designmode = 'on':
     CypressError: Timed out retrying: expected false to equal true
```
