### PR TITLE
fix: add support for checking multiple hosts when connecting to CDP

### LINKED ISSUE #23897: Cypress cannot connect to `Firefox 105`
### Current behavior

Updated to Firefox 105 locally and in CI and now Cypress 10.7.0 and 10.8.0 cannot connect to the browser.

```
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
```

### Desired behavior

Cypress should continue being able to connect to and utilize the latest version of Firefox.

### Test code to reproduce

Locally using Cypress UI.

* Close Cypress
* Update to Firefox 105 (latest at the time I write this)
* Open Cypress
* Choose E2E
* Select Firefox v105
* Click `Start E2E Testing in Firefox`
* Observe FF physically opens but the page is empty

### Cypress Version

10.8.0

### Node version

v16.17.0

### Operating System

macOS 12.6

### Debug Logs

```shell
cypress:lifecycle:ProjectConfigManager call event before:browser:launch for invocation id inv1 +12s
  cypress:lifecycle:child:RunPlugins:86362 execute plugin event: before:browser:launch ({ invocationId: 'inv1', eventId: 2 }) +12s
  cypress:lifecycle:ProjectConfigManager promise resolved for id 'inv1' with value {
  extensions: [],
  preferences: {
    'app.normandy.api_url': '',
    'app.update.checkInstallTime': false,
    'app.update.disabledForTesting': true,
    'apz.content_response_timeout': 60000,
    'browser.contentblocking.features.standard': '-tp,tpPrivate,cookieBehavior0,-cm,-fp',
    'browser.dom.window.dump.enabled': true,
    'browser.newtabpage.activity-stream.feeds.section.topstories': false,
    'browser.newtabpage.enabled': false,
    'browser.pagethumbnails.capturing_disabled': true,
    'browser.safebrowsing.blockedURIs.enabled': false,
    'browser.safebrowsing.downloads.enabled': false,
    'browser.safebrowsing.malware.enabled': false,
    'browser.safebrowsing.passwords.enabled': false,
    'browser.safebrowsing.phishing.enabled': false,
    'browser.search.update': false,
    'browser.sessionstore.resume_from_crash': false,
    'browser.shell.checkDefaultBrowser': false,
    'browser.startup.homepage': 'about:blank',
    'browser.startup.homepage_override.mstone': 'ignore',
    'browser.startup.page': 0,
    'browser.startup.couldRestoreSession.count': 0,
    'browser.tabs.disableBackgroundZombification': false,
    'browser.tabs.warnOnCloseOtherTabs': false,
    'browser.tabs.warnOnOpen': false,
    'browser.uitour.enabled': false,
    'browser.urlbar.suggest.searches': false,
    'browser.usedOnWindows10.introURL': '',
    'browser.warnOnQuit': false,
    'datareporting.healthreport.about.reportUrl': '',
    'datareporting.healthreport.documentServerURI': '',
    'datareporting.healthreport.logging.consoleEnabled': false,
    'datareporting.healthreport.service.enabled': false,
    'datareporting.healthreport.service.firstRun': false,
    'datareporting.healthreport.uploadEnabled': false,
    'datareporting.policy.dataSubmissionEnabled': false,
    'datareporting.policy.dataSubmissionPolicyAccepted': false,
    'datareporting.policy.dataSubmissionPolicyBypassNotification': true,
    'devtools.jsonview.enabled': false,
    'dom.disable_open_during_load': false,
    'dom.file.createInChild': true,
    'dom.ipc.reportProcessHangs': false,
    'dom.max_chrome_script_run_time': 0,
    'dom.max_script_run_time': 0,
    'extensions.autoDisableScopes': 0,
    'extensions.enabledScopes': 5,
    'extensions.getAddons.cache.enabled': false,
    'extensions.installDistroAddons': false,
    'extensions.screenshots.disabled': true,
    'extensions.update.enabled': false,
    'extensions.update.notifyUser': false,
    'extensions.webservice.discoverURL': '',
    'focusmanager.testmode': true,
    'general.useragent.updates.enabled': false,
    'geo.provider.testing': true,
    'geo.wifi.scan': false,
    'hangmonitor.timeout': 0,
    'javascript.options.showInConsole': true,
    'media.gmp-manager.updateEnabled': false,
    'network.cookie.cookieBehavior': 0,
    'network.http.prompt-temp-redirect': false,
    'network.http.speculative-parallel-limit': 0,
    'network.manage-offline-status': false,
    'network.sntp.pools': '',
    'plugin.state.flash': 0,
    'privacy.trackingprotection.enabled': false,
    'remote.enabled': true,
    'security.certerrors.mitm.priming.enabled': false,
    'security.fileuri.strict_origin_policy': false,
    'security.notification_enable_delay': 0,
    'services.settings.server': '',
    'signon.autofillForms': false,
    'signon.rememberSignons': false,
    'startup.homepage_welcome_url': 'about:blank',
    'startup.homepage_welcome_url.additional': '',
    'toolkit.cosmeticAnimations.enabled': false,
    'toolkit.telemetry.server': "''",
    'toolkit.startup.max_resumed_crashes': -1,
    'network.proxy.type': 1,
    'devtools.debugger.remote-enabled': true,
    'devtools.debugger.remote-host': '127.0.0.1',
    'devtools.debugger.prompt-connection': false,
    'devtools.chrome.enabled': true,
    'app.update.auto': false,
    'app.update.enabled': false,
    'browser.displayedE10SNotice': 4,
    'browser.download.manager.showWhenStarting': false,
    'browser.EULA.override': true,
    'browser.EULA.3.accepted': true,
    'browser.link.open_external': 2,
    'browser.link.open_newwindow': 2,
    'browser.offline': false,
    'browser.reader.detectedFirstArticle': true,
    'browser.selfsupport.url': '',
    'browser.tabs.warnOnClose': false,
    'devtools.errorconsole.enabled': true,
    'extensions.blocklist.enabled': false,
    'extensions.checkCompatibility.nightly': false,
    'extensions.logging.enabled': true,
    'javascript.enabled': true,
    'network.http.phishy-userpass-length': 255,
    'offline-apps.allow_by_default': true,
    'prompts.tab_modal.enabled': false,
    'security.fileuri.origin_policy': 3,
    'toolkit.networkmanager.disable': true,
    'toolkit.telemetry.prompted': 2,
    'toolkit.telemetry.enabled': false,
    'toolkit.telemetry.rejected': true,
    'xpinstall.signatures.required': false,
    'xpinstall.whitelist.required': false,
    'browser.laterrun.enabled': false,
    'browser.newtab.url': 'about:blank',
    'dom.report_all_js_exceptions': true,
    'network.captive-portal-service.enabled': false,
    'security.csp.enable': false,
    webdriver_accept_untrusted_certs: true,
    webdriver_assume_untrusted_issuer: true,
    'toolkit.legacyUserProfileCustomizations.stylesheets': true,
    'browser.tabs.drawInTitlebar': false,
    'media.autoplay.default': 0,
    'browser.safebrowsing.enabled': false,
    'media.getusermedia.browser.enabled': true,
    'media.navigator.permission.disabled': true,
    'dom.min_background_timeout_value': 4,
    'dom.timeout.enable_budget_timer_throttling': false,
    'media.devices.insecure.enabled': true,
    'media.getusermedia.insecure.enabled': true,
    'marionette.log.level': 'Debug',
    'browser.download.folderList': 2,
    'browser.helperApps.neverAsk.saveToDisk': 'application/andrew-inset,application/applixware,application/atom+xml,application/atomcat+xml,application/atomdeleted+xml,application/atomsvc+xml,application/atsc-dwd+xml,application/atsc-held+xml,application/atsc-rsat+xml,application/bdoc,application/calendar+xml,application/ccxml+xml,application/cdfx+xml,application/cdmi-capability,application/cdmi-container,application/cdmi-domain,application/cdmi-object,application/cdmi-queue,application/cu-seeme,application/dash+xml,application/davmount+xml,application/docbook+xml,application/dssc+der,application/dssc+xml,application/ecmascript,application/emma+xml,application/emotionml+xml,application/epub+zip,application/exi,application/fdt+xml,application/font-tdpfr,application/geo+json,application/gml+xml,application/gpx+xml,application/gxf,application/gzip,application/hjson,application/hyperstudio,application/inkml+xml,application/ipfix,application/its+xml,application/java-archive,application/java-serialized-object,application/java-vm,application/javascript,application/json,application/json5,application/jsonml+json,application/ld+json,application/lgr+xml,application/lost+xml,application/mac-binhex40,application/mac-compactpro,application/mads+xml,application/manifest+json,application/marc,application/marcxml+xml,application/mathematica,application/mathml+xml,application/mbox,application/mediaservercontrol+xml,application/metalink+xml,application/metalink4+xml,application/mets+xml,application/mmt-aei+xml,application/mmt-usd+xml,application/mods+xml,application/mp21,application/mp4,application/mrb-consumer+xml,application/mrb-publish+xml,application/msword,application/mxf,application/n-quads,application/n-triples,application/node,application/octet-stream,application/oda,application/oebps-package+xml,application/ogg,application/omdoc+xml,application/onenote,application/oxps,application/p2p-overlay+xml,application/patch-ops-error+xml,application/pdf,application/pgp-encrypted,application/pgp-signature,application/pics-rules,application/pkcs10,application/pkcs7-mime,application/pkcs7-signature,application/pkcs8,application/pkix-attr-cert,application/pkix-cert,application/pkix-crl,application/pkix-pkipath,application/pkixcmp,application/pls+xml,application/postscript,application/provenance+xml,application/prs.cww,application/pskc+xml,application/raml+yaml,application/rdf+xml,application/reginfo+xml,application/relax-ng-compact-syntax,application/resource-lists+xml,application/resource-lists-diff+xml,application/rls-services+xml,application/route-apd+xml,application/route-s-tsid+xml,application/route-usd+xml,application/rpki-ghostbusters,application/rpki-manifest,application/rpki-roa,application/rsd+xml,application/rss+xml,application/rtf,application/sbml+xml,application/scvp-cv-request,application/scvp-cv-response,application/scvp-vp-request,application/scvp-vp-response,application/sdp,application/senml+xml,application/sensml+xml,application/set-payment-initiation,application/set-registration-initiation,application/shf+xml,application/sieve,application/smil+xml,application/sparql-query,application/sparql-results+xml,application/srgs,application/srgs+xml,application/sru+xml,application/ssdl+xml,application/ssml+xml,application/swid+xml,application/tei+xml,application/thraud+xml,application/timestamped-data,application/toml,application/ttml+xml,application/ubjson,application/urc-ressheet+xml,application/urc-targetdesc+xml,application/vnd.1000minds.decision-model+xml,application/vnd.3gpp.pic-bw-large,application/vnd.3gpp.pic-bw-small,application/vnd.3gpp.pic-bw-var,application/vnd.3gpp2.tcap,application/vnd.3m.post-it-notes,application/vnd.accpac.simply.aso,application/vnd.accpac.simply.imp,application/vnd.acucobol,application/vnd.acucorp,application/vnd.adobe.air-application-installer-package+zip,application/vnd.adobe.formscentral.fcdt,application/vnd.adobe.fxp,application/vnd.adobe.xdp+xml,application/vnd.adobe.xfdf,application/vnd.ahead.space,application/vnd.airzip.filesecure.azf,application/vnd.airzip.filesecure.azs,application/vnd.amazon.ebook,application/vnd.americandynamics.acc,application/vnd.amiga.ami,application/vnd.android.package-archive,application/vnd.anser-web-certificate-issue-initiation,application/vnd.anser-web-funds-transfer-initiation,application/vnd.antix.game-component,application/vnd.apple.installer+xml,application/vnd.apple.keynote,application/vnd.apple.mpegurl,application/vnd.apple.numbers,application/vnd.apple.pages,application/vnd.apple.pkpass,application/vnd.aristanetworks.swi,application/vnd.astraea-software.iota,application/vnd.audiograph,application/vnd.balsamiq.bmml+xml,application/vnd.blueice.multipass,application/vnd.bmi,application/vnd.businessobjects,application/vnd.chemdraw+xml,application/vnd.chipnuts.karaoke-mmd,application/vnd.cinderella,application/vnd.citationstyles.style+xml,application/vnd.claymore,application/vnd.cloanto.rp9,application/vnd.clonk.c4group,application/vnd.cluetrust.cartomobile-config,application/vnd.cluetrust.cartomobile-config-pkg,application/vnd.commonspace,application/vnd.contact.cmsg,application/vnd.cosmocaller,application/vnd.crick.clicker,application/vnd.crick.clicker.keyboard,application/vnd.crick.clicker.palette,application/vnd.crick.clicker.template,application/vnd.crick.clicker.wordbank,application/vnd.criticaltools.wbs+xml,application/vnd.ctc-posml,application/vnd.cups-ppd,application/vnd.curl.car,application/vnd.curl.pcurl,application/vnd.dart,application/vnd.data-vision.rdz,application/vnd.dbf,application/vnd.dece.data,application/vnd.dece.ttml+xml,application/vnd.dece.unspecified,application/vnd.dece.zip,application/vnd.denovo.fcselayout-link,application/vnd.dna,application/vnd.dolby.mlp,application/vnd.dpgraph,application/vnd.dreamfactory,application/vnd.ds-keypoint,application/vnd.dvb.ait,application/vnd.dvb.service,application/vnd.dynageo,application/vnd.ecowin.chart,application/vnd.enliven,application/vnd.epson.esf,application/vnd.epson.msf,application/vnd.epson.quickanime,application/vnd.epson.salt,application/vnd.epson.ssf,application/vnd.eszigno3+xml,application/vnd.ezpix-album,application/vnd.ezpix-package,application/vnd.fdf,application/vnd.fdsn.mseed,application/vnd.fdsn.seed,application/vnd.flographit,application/vnd.fluxtime.clip,application/vnd.framemaker,application/vnd.frogans.fnc,application/vnd.frogans.ltf,application/vnd.fsc.weblaunch,application/vnd.fujitsu.oasys,application/vnd.fujitsu.oasys2,application/vnd.fujitsu.oasys3,application/vnd.fujitsu.oasysgp,application/vnd.fujitsu.oasysprs,application/vnd.fujixerox.ddd,application/vnd.fujixerox.docuworks,application/vnd.fujixerox.docuworks.binder,application/vnd.fuzzysheet,application/vnd.genomatix.tuxedo,application/vnd.geogebra.file,application/vnd.geogebra.tool,application/vnd.geometry-explorer,application/vnd.geonext,application/vnd.geoplan,application/vnd.geospace,application/vnd.gmx,application/vnd.google-apps.document,application/vnd.google-apps.presentation,application/vnd.google-apps.spreadsheet,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz,application/vnd.grafeq,application/vnd.groove-account,application/vnd.groove-help,application/vnd.groove-identity-message,application/vnd.groove-injector,application/vnd.groove-tool-message,application/vnd.groove-tool-template,application/vnd.groove-vcard,application/vnd.hal+xml,application/vnd.handheld-entertainment+xml,application/vnd.hbci,application/vnd.hhe.lesson-player,application/vnd.hp-hpgl,application/vnd.hp-hpid,application/vnd.hp-hps,application/vnd.hp-jlyt,application/vnd.hp-pcl,application/vnd.hp-pclxl,application/vnd.hydrostatix.sof-data,application/vnd.ibm.minipay,application/vnd.ibm.modcap,application/vnd.ibm.rights-management,application/vnd.ibm.secure-container,application/vnd.iccprofile,application/vnd.igloader,application/vnd.immervision-ivp,application/vnd.immervision-ivu,application/vnd.insors.igm,application/vnd.intercon.formnet,application/vnd.intergeo,application/vnd.intu.qbo,application/vnd.intu.qfx,application/vnd.ipunplugged.rcprofile,application/vnd.irepository.package+xml,application/vnd.is-xpr,application/vnd.isac.fcs,application/vnd.jam,application/vnd.jcp.javame.midlet-rms,application/vnd.jisp,application/vnd.joost.joda-archive,application/vnd.kahootz,application/vnd.kde.karbon,application/vnd.kde.kchart,application/vnd.kde.kformula,application/vnd.kde.kivio,application/vnd.kde.kontour,application/vnd.kde.kpresenter,application/vnd.kde.kspread,application/vnd.kde.kword,application/vnd.kenameaapp,application/vnd.kidspiration,application/vnd.kinar,application/vnd.koan,application/vnd.kodak-descriptor,application/vnd.las.las+xml,application/vnd.llamagraphics.life-balance.desktop,application/vnd.llamagraphics.life-balance.exchange+xml,application/vnd.lotus-1-2-3,application/vnd.lotus-approach,application/vnd.lotus-freelance,application/vnd.lotus-notes,application/vnd.lotus-organizer,application/vnd.lotus-screencam,application/vnd.lotus-wordpro,application/vnd.macports.portpkg,application/vnd.mcd,application/vnd.medcalcdata,application/vnd.mediastation.cdkey,application/vnd.mfer,application/vnd.mfmp,application/vnd.micrografx.flo,application/vnd.micrografx.igx,application/vnd.mif,application/vnd.mobius.daf,application/vnd.mobius.dis,application/vnd.mobius.mbk,application/vnd.mobius.mqy,application/vnd.mobius.msl,application/vnd.mobius.plc,application/vnd.mobius.txf,application/vnd.mophun.application,application/vnd.mophun.certificate,application/vnd.mozilla.xul+xml,application/vnd.ms-artgalry,application/vnd.ms-cab-compressed,application/vnd.ms-excel,application/vnd.ms-excel.addin.macroenabled.12,application/vnd.ms-excel.sheet.binary.macroenabled.12,application/vnd.ms-excel.sheet.macroenabled.12,application/vnd.ms-excel.template.macroenabled.12,application/vnd.ms-fontobject,application/vnd.ms-htmlhelp,application/vnd.ms-ims,application/vnd.ms-lrm,application/vnd.ms-officetheme,application/vnd.ms-outlook,application/vnd.ms-pki.seccat,applicat'... 13463 more characters,
    'network.proxy.allow_hijacking_localhost': true,
    'network.proxy.http': 'localhost',
    'network.proxy.ssl': 'localhost',
    'network.proxy.http_port': 51438,
    'network.proxy.ssl_port': 51438,
    'network.proxy.no_proxies_on': '',
    'browser.download.dir': '/Users/cgraham/Dev/academy-ui/cypress/downloads',
    'devtools.debugger.remote-port': 51499,
    'marionette.port': 51500
  },
  args: [
    '-marionette',
    '-new-instance',
    '-foreground',
    '-start-debugger-server',
    '-no-remote',
    '--remote-debugging-port=51498'
  ]
} +17ms
  cypress:server:browsers:utils copied extension +61ms
  cypress:server:browsers:firefox firefox directories { path: '/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive', cacheDir: '/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive/CypressCache', extensionDest: '/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive/CypressExtension' } +75ms
  cypress:server:browsers:firefox launch in firefox {
  url: 'https://staging.rstudioacademy.com/__/',
  args: [
    '-marionette',
    '-new-instance',
    '-foreground',
    '-start-debugger-server',
    '-no-remote',
    '--remote-debugging-port=51498',
    '-profile',
    '/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive'
  ]
} +4ms
  cypress:launcher:browsers launching browser { browser: { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '105.0', path: '/Applications/Firefox.app/Contents/MacOS/firefox', minSupportedVersion: 86, majorVersion: '105', isHeaded: true, isHeadless: false }, url: 'about:blank' } +0ms
  cypress:launcher:browsers spawning browser with args { args: [ 'about:blank', '-marionette', '-new-instance', '-foreground', '-start-debugger-server', '-no-remote', '--remote-debugging-port=51498', '-profile', '/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive' ] } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51499     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51499 } } +12s
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51500     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51500 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 0, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51499     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51499 } } +104ms
  cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51500     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51500 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 1, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 2, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51499     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51499 } } +102ms
  cypress:network:connect received error on connect, retrying { iteration: 2, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51500     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51500 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 2, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +0ms
  cypress:network:connect received error on connect, retrying { iteration: 3, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51499     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51499 } } +100ms
  cypress:network:connect received error on connect, retrying { iteration: 3, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51500     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51500 } } +1ms
  cypress:network:connect received error on connect, retrying { iteration: 3, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +0ms
  cypress:launcher:browsers firefox stdout: 1663682947650       RemoteAgent     DEBUG   WebDriver BiDi enabled +343ms
  cypress:launcher:browsers firefox stdout: 1663682947650       RemoteAgent     DEBUG   CDP enabled
1663682947650   Marionette      INFO    Marionette enabled +0ms
  cypress:launcher:browsers firefox stdout: 1663682947651       RemoteAgent     DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false +1ms
  cypress:network:connect received error on connect, retrying { iteration: 4, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51499     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51499 } } +105ms
  cypress:network:connect received error on connect, retrying { iteration: 4, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51500     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51500 } } +1ms
  cypress:network:connect received error on connect, retrying { iteration: 4, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +0ms
  cypress:launcher:browsers firefox stdout: 1663682947764       Marionette      INFO    Listening on port 51500
1663682947764   Marionette      DEBUG   Marionette is listening +114ms
  cypress:launcher:browsers firefox stdout: Started devtools server on 51499 +30ms
  cypress:network:connect successfully connected { opts: { host: '127.0.0.1', port: 51499, getDelayMsForRetry: [Function: getDelayMsForRetry] }, iteration: 5 } +104ms
  cypress:network:connect successfully connected { opts: { host: '127.0.0.1', port: 51500, getDelayMsForRetry: [Function: getDelayMsForRetry] }, iteration: 5 } +1ms
  cypress:server:browsers:firefox-util firefox: navigating page with webdriver +0ms
  cypress:network:connect received error on connect, retrying { iteration: 5, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1ms
  cypress:launcher:browsers firefox stderr: 2022-09-20 10:09:07.901 plugin-container[87262:4624938] nil host used in call to allowsSpecificHTTPSCertificateForHost +106ms
  cypress:launcher:browsers firefox stderr: 2022-09-20 10:09:07.902 plugin-container[87262:4624938] nil host used in call to allowsAnyHTTPSCertificateForHost: +1ms
  cypress:launcher:browsers firefox stderr: 2022-09-20 10:09:07.926 plugin-container[87262:4624938] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-09-20 10:09:07.926 plugin-container[87262:4624938] nil host used in call to allowsAnyHTTPSCertificateForHost: +24ms
  cypress:launcher:browsers firefox stderr: 2022-09-20 10:09:07.926 plugin-container[87262:4624961] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-09-20 10:09:07.926 plugin-container[87262:4624961] nil host used in call to allowsAnyHTTPSCertificateForHost: +1ms
  cypress:network:connect received error on connect, retrying { iteration: 6, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +100ms
  cypress:network:connect received error on connect, retrying { iteration: 7, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +102ms
  cypress:network:connect received error on connect, retrying { iteration: 8, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +105ms
  cypress:launcher:browsers firefox stderr: WebDriver BiDi listening on ws://[::1]:51498 +253ms
  cypress:launcher:browsers firefox stdout: 1663682948181       CDP     DEBUG   Waiting for initial application window +1ms
  cypress:launcher:browsers firefox stdout: 1663682948182       Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:51517 +1ms
  cypress:launcher:browsers firefox stdout: 1663682948191       Marionette      DEBUG   Accepted connection 1 from 127.0.0.1:51520 +9ms
  cypress:network:connect received error on connect, retrying { iteration: 9, delay: 100, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +101ms
  cypress:launcher:browsers firefox stdout: 1663682948310       Marionette      DEBUG   Closed connection 0 +119ms
  cypress:network:connect received error on connect, retrying { iteration: 10, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +100ms
  cypress:launcher:browsers firefox stdout: 1663682948355       Marionette      DEBUG   1 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true}] +45ms
  cypress:launcher:browsers firefox stdout: 1663682948356       RemoteAgent     WARN    TLS certificate errors will be ignored for this session +1ms
  cypress:launcher:browsers firefox stdout: 1663682948356       Marionette      DEBUG   Waiting for initial application window +0ms
  cypress:network:connect received error on connect, retrying { iteration: 11, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +505ms
  cypress:network:connect received error on connect, retrying { iteration: 12, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +504ms
  cypress:server:server-base Got CONNECT request from content-signature-2.cdn.mozilla.net:443 +14s
  cypress:https-proxy Writing browserSocket connection headers { url: 'content-signature-2.cdn.mozilla.net:443', headLength: 0, headers: { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0', 'proxy-connection': 'keep-alive', connection: 'keep-alive', host: 'content-signature-2.cdn.mozilla.net:443' } } +14s
  cypress:https-proxy Got first head bytes { url: 'content-signature-2.cdn.mozilla.net:443', head: '\x16\x03\x01\x00�\x01\x00\x00�\x03\x03\x1FX~\x01�����FH9\x06��l���\x12\x13?[O8c�\\���\x00\x00\x1C�+�/̨̩�,�0�\n�\t�\x13�\x14\x00' } +1ms
  cypress:https-proxy Making intercepted connection to 51440 +2ms
  cypress:network:connect successfully connected { opts: { port: 51440, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +169ms
  cypress:https-proxy received upstreamSocket callback for request { port: 51440, hostname: 'localhost', err: undefined } +8ms
  cypress:server:util:socket_allowed allowing socket { localPort: 51538 } +0ms
  cypress:server:server-base Got CONNECT request from firefox.settings.services.mozilla.com:443 +144ms
  cypress:https-proxy Writing browserSocket connection headers { url: 'firefox.settings.services.mozilla.com:443', headLength: 0, headers: { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0', 'proxy-connection': 'keep-alive', connection: 'keep-alive', host: 'firefox.settings.services.mozilla.com:443' } } +132ms
  cypress:https-proxy Got first head bytes { url: 'firefox.settings.services.mozilla.com:443', head: '\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03�K����0b���>\x17y\x04��v�\x0E��.�/L�f\b\t� �3\x1E�Ȓ�$±iP��\x1E"\x0F�:\x1A(�_' } +2ms
  cypress:https-proxy Making intercepted connection to 51440 +2ms
  cypress:network:connect successfully connected { opts: { port: 51440, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +138ms
  cypress:https-proxy received upstreamSocket callback for request { port: 51440, hostname: 'localhost', err: undefined } +1ms
  cypress:server:util:socket_allowed allowing socket { localPort: 51540 } +137ms
  cypress:launcher:browsers firefox stderr: DevTools listening on ws://[::1]:51498/devtools/browser/c88abee1-0348-45c3-b4f1-a4ac971aa68b +1s
  cypress:launcher:browsers firefox stdout: 1663682949764       Marionette      DEBUG   1 <- [1,1,null,{"sessionId":"17981870-21e1-4382-8548-24939ef3923e","capabilities":{"browserName":"firefox","browserVersion":"105.0 ... ownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"proxy":{}}}] +2ms
  cypress:launcher:browsers firefox stdout: 1663682949772       Marionette      DEBUG   1 -> [0,2,"Addon:Install",{"path":"/Users/cgraham/Library/Application Support/Cypress/cy/production/browsers/firefox-stable/interactive/CypressExtension","temporary":true}] +9ms
  cypress:launcher:browsers firefox stderr: JavaScript warning: moz-extension://d030c60e-024f-1846-9320-af4afbceefd0/background.js, line 5566: unreachable code after return statement +72ms
  cypress:network:connect received error on connect, retrying { iteration: 13, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +194ms
  cypress:launcher:browsers firefox stdout: 1663682949870       Marionette      DEBUG   1 <- [1,2,null,{"value":"automation-extension@cypress.io"}] +25ms
  cypress:server:server-base Got CONNECT request from localhost:51438 +222ms
  cypress:https-proxy Writing browserSocket connection headers { url: 'localhost:51438', headLength: 0, headers: { 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0', 'proxy-connection': 'keep-alive', connection: 'keep-alive', host: 'localhost:51438' } } +218ms
  cypress:https-proxy Got first head bytes { url: 'localhost:51438', head: 'GET /__socket/?EIO=4&transport=websocket HTTP/1.1\r\nHost: localho' } +0ms
  cypress:https-proxy Making intercepted connection to 51438 +0ms
  cypress:network:connect successfully connected { opts: { port: 51438, host: 'localhost', getDelayMsForRetry: [Function: getDelayForRetry] }, iteration: 0 } +25ms
  cypress:https-proxy received upstreamSocket callback for request { port: 51438, hostname: 'localhost', err: undefined } +1ms
  cypress:server:util:socket_allowed allowing socket { localPort: 51543 } +219ms
  cypress:server:server-base Got UPGRADE request from /__socket/?EIO=4&transport=websocket +2ms
  cypress:server:util:socket_allowed is incoming request allowed? { isAllowed: true, reqUrl: '/__socket/?EIO=4&transport=websocket', remotePort: 51543, remoteAddress: '127.0.0.1' } +1ms
  cypress:server:socket-base socket connected +0ms
  cypress:server:socket-base automation:client connected +2ms
  cypress:network:cors Parsed URL { port: '443', tld: 'net', domain: 'mozilla' } +3s
  cypress:server:remote-states getting remote state: undefined for: https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2022-10-09-23-18-04.chain +3s
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +1ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +1ms
  cypress:server:stream_buffer stream buffer writeable final called +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2022-10-09-23-18-04.chain' } +15s
  cypress:network:connect beginning getAddress { hostname: 'content-signature-2.cdn.mozilla.net', port: 443 } +179ms
  cypress:network:connect got addresses { hostname: 'content-signature-2.cdn.mozilla.net', port: 443, addresses: [ { address: '99.84.208.53', family: 4 }, { address: '99.84.208.114', family: 4 }, { address: '99.84.208.6', family: 4 }, { address: '99.84.208.33', family: 4 } ] } +31ms
  cypress:network:agent got family { family: 4, href: 'https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2022-10-09-23-18-04.chain' } +43ms
  cypress:server:request received status code & headers on request { requestId: 'request2', statusCode: 200, headers: { 'content-type': 'binary/octet-stream' } } +0ms
  cypress:server:request successful response received { requestId: 'request2' } +1ms
  cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/chains/remote-settings.content-signature.mozilla.org-2022-10-09-23-18-04.chain' }, request: undefined } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +105ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +105ms
  cypress:network:cors Parsed URL { port: '443', tld: 'net', domain: 'mozilla' } +1ms
  cypress:network:cors Parsed URL { port: '443', tld: 'net', domain: 'mozilla' } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +0ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +2ms
  cypress:network:cors Parsed URL { port: '443', tld: 'net', domain: 'mozilla' } +1ms
  cypress:network:cors Parsed URL { port: '443', tld: 'net', domain: 'mozilla' } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +1ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +2ms
GET /chains/remote-settings.content-signature.mozilla.org-2022-10-09-23-18-04.chain 200 615.991 ms - -
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'mozilla' } +7ms
  cypress:server:remote-states getting remote state: undefined for: https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US +6ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +0ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +0ms
  cypress:server:stream_buffer stream buffer writeable final called +112ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US' } +69ms
  cypress:network:connect beginning getAddress { hostname: 'firefox.settings.services.mozilla.com', port: 443 } +81ms
  cypress:network:connect got addresses { hostname: 'firefox.settings.services.mozilla.com', port: 443, addresses: [ { address: '52.85.132.46', family: 4 }, { address: '52.85.132.85', family: 4 }, { address: '52.85.132.97', family: 4 }, { address: '52.85.132.7', family: 4 } ] } +3ms
  cypress:network:agent got family { family: 4, href: 'https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US' } +16ms
  cypress:server:request received status code & headers on request { requestId: 'request3', statusCode: 200, headers: { 'content-type': 'application/json' } } +76ms
  cypress:server:request successful response received { requestId: 'request3' } +0ms
  cypress:net-stubbing:server:intercept-response InterceptResponse { req: { url: '/v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US' }, request: undefined } +74ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +64ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +64ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'mozilla' } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'mozilla' } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +0ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'mozilla' } +1ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'mozilla' } +0ms
  cypress:network:cors Parsed URL { port: '443', tld: 'com', domain: 'rstudioacademy' } +0ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'https://staging.rstudioacademy.com', strategy: 'http', fileServer: null, domainName: 'rstudioacademy.com', props: { port: '443', tld: 'com', domain: 'rstudioacademy' } } for: https://rstudioacademy.com +1ms
GET /v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-US 200 568.125 ms - -
  cypress:network:connect received error on connect, retrying { iteration: 14, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +182ms
  cypress:network:connect received error on connect, retrying { iteration: 15, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +505ms
  cypress:network:connect received error on connect, retrying { iteration: 16, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +504ms
  cypress:network:connect received error on connect, retrying { iteration: 17, delay: 500, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +505ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
  cypress:network:connect received error on connect, retrying { iteration: 18, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +507ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 19/62)
  cypress:network:connect received error on connect, retrying { iteration: 19, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 20/62)
  cypress:network:connect received error on connect, retrying { iteration: 20, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51538 } +5s
  cypress:server:util:socket_allowed allowed socket closed, removing { localPort: 51540 } +71ms
Still waiting to connect to Firefox, retrying in 1 second (attempt 21/62)
  cypress:network:connect received error on connect, retrying { iteration: 21, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 22/62)
  cypress:network:connect received error on connect, retrying { iteration: 22, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 23/62)
  cypress:network:connect received error on connect, retrying { iteration: 23, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬─────────────────────────────────────────────────────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │                            pids                             │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼─────────────────────────────────────────────────────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │      'other'      │      9       │ '87258, 87272, 87271, 87270, 87266, 87265 ... 3 more items' │    57.3    │     14.33      │  485.67  │    123.53    │   485.67    │
  cypress:server:util:process_profiler │    1    │     'cypress'     │      1       │                           '86336'                           │     0      │     28.83      │  214.86  │    184.81    │   214.86    │
  cypress:server:util:process_profiler │    2    │    'launchpad'    │      1       │                           '86587'                           │    9.3     │      4.33      │  144.14  │    139.56    │   144.14    │
  cypress:server:util:process_profiler │    3    │ 'electron-shared' │      2       │                       '86343, 86456'                        │    6.1     │      2.7       │  97.77   │    73.22     │    97.77    │
  cypress:server:util:process_profiler │    4    │     'plugin'      │      1       │                           '86362'                           │     0      │      0.03      │  92.07   │    95.16     │   101.56    │
  cypress:server:util:process_profiler │    5    │      'TOTAL'      │      14      │                             '-'                             │    72.7    │     49.13      │  1034.5  │    557.61    │   1034.5    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴─────────────────────────────────────────────────────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +10s
Still waiting to connect to Firefox, retrying in 1 second (attempt 24/62)
  cypress:network:connect received error on connect, retrying { iteration: 24, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 25/62)
  cypress:network:connect received error on connect, retrying { iteration: 25, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 26/62)
  cypress:network:connect received error on connect, retrying { iteration: 26, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 27/62)
  cypress:network:connect received error on connect, retrying { iteration: 27, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 28/62)
  cypress:network:connect received error on connect, retrying { iteration: 28, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
Still waiting to connect to Firefox, retrying in 1 second (attempt 29/62)
  cypress:network:connect received error on connect, retrying { iteration: 29, delay: 1000, err: Error: connect ECONNREFUSED 127.0.0.1:51498     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 51498 } } +1s
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #23897

### User facing changelog

* Fixed issue with Cypress not being able to connect to Firefox v105.

### Additional details

See https://bugzilla.mozilla.org/show_bug.cgi?id=1792088

In Firefox 105, when determining the address for localhost, an IPv6 address of `::1` may be returned instead of the IPv4 `127.0.0.1`. Cypress assumes the IPv4 address and thus can't connect to the remote agent. In this change, I am attempting to create a connection on both `127.0.0.1` and `::1`. If one of them succeeds the other is then cancelled.

### Steps to test

Install Firefox 105 and verify Cypress can connect.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/firefox-util.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ async function connectToNewSpec (options, automation: Automation, browserCriClie
 }
 
 async function setupRemote (remotePort, automation, onError, options): Promise<BrowserCriClient> {
-  const browserCriClient = await BrowserCriClient.create(remotePort, 'Firefox', onError)
+  const browserCriClient = await BrowserCriClient.create(['127.0.0.1', '::1'], remotePort, 'Firefox', onError)
```
Comment (flotwig) [inline packages/server/lib/browsers/firefox-util.ts:138]: Does this fix also need to apply to the Marionette or Foxdriver connections?

Comment (mschile) [reply packages/server/lib/browsers/firefox-util.ts:138]: I didn't observe any connection issues for Marionette or Foxdriver as they both were started on 127.0.0.1.

```
  cypress:network:connect successfully connected { opts: { host: '127.0.0.1', port: 64061, getDelayMsForRetry: [Function: getDelayMsForRetry] }, iteration: 2 } +103ms
  cypress:server:browsers:firefox-util foxdriver: { host: '127.0.0.1', port: 64061 } +0ms
  cypress:network:connect successfully connected { opts: { host: '127.0.0.1', port: 64062, getDelayMsForRetry: [Function: getDelayMsForRetry] }, iteration: 2 } +1ms
  cypress:server:browsers:firefox-util marionette: { host: '127.0.0.1', port: 64062 } +1ms
```

**Review by chrisbreiding — APPROVED** [review]

File: packages/network/lib/connect.ts [hunk 2]
```diff
@@ -90,6 +90,12 @@ export function createRetryingSocket (
         return cb(err)
       }
 
+      if (delay === -1) {
+        debug('cancelling any additional retries %o', { opts })
+
+        return cb(err)
+      }
```
Comment (flotwig) [inline packages/network/lib/connect.ts]: isn't this what the code path above already does, except with `undefined` instead of `-1`?

File: packages/network/test/unit/connect_spec.ts [hunk 3]
```diff
@@ -24,4 +29,34 @@ describe('lib/connect', () => {
...
+
+  context('createRetryingSocket', () => {
+    it('cancels retries', (done) => {
+      const getDelayMsForRetry = (iteration) => {
+        if (iteration < 2) {
+          return 1
+        }
+
+        // return -1 to cancel any additional retries
+        return -1
```
Comment (flotwig) [inline packages/network/test/unit/connect_spec.ts]:
```suggestion
        // return undefined to cancel any additional retries
        return undefined
```

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 4]
```diff
@@ -23,23 +26,39 @@ const getMajorMinorVersion = (version: string): Version => {
...
 
-const ensureLiveBrowser = async (port: number, browserName: string) => {
+const tryBrowserConnection = async (host: string, port: number, browserName: string): Promise<string | undefined> => {
   const connectOpts = {
-    host: HOST,
+    host,
     port,
     getDelayMsForRetry: (i) => {
+      // if we successfully connected to a different host, cancel any remaining connection attempts
+      if (connected) return -1
```
Comment (flotwig) [inline packages/server/lib/browsers/browser-cri-client.ts]:
```suggestion
      if (connected) return undefined
```

File: packages/network/lib/connect.ts (hunk 2 above)
Comment (mschile) [reply packages/network/lib/connect.ts]: My initial intention was to differentiate between cancelling early and exhausting the retries but on second thought, I think you're right, they really are the same. Updated [037fe44](https://github.com/cypress-io/cypress/pull/24155/commits/037fe444520a1ba0930046c8fd729230d2ec7684)

File: packages/network/test/unit/connect_spec.ts (hunk 3 above)
Comment (mschile) [reply packages/network/test/unit/connect_spec.ts]: Updated [037fe44](https://github.com/cypress-io/cypress/pull/24155/commits/037fe444520a1ba0930046c8fd729230d2ec7684)

File: packages/server/lib/browsers/browser-cri-client.ts (hunk 4 above)
Comment (mschile) [reply packages/server/lib/browsers/browser-cri-client.ts]: Updated [037fe44](https://github.com/cypress-io/cypress/pull/24155/commits/037fe444520a1ba0930046c8fd729230d2ec7684)

**Review by flotwig — APPROVED** [review]

**Comment by HappyMan0001** [comment]
I'm seeing the same issue on Cypress 13.1.0; Firefox version 131.0 is up to date. it is just not working on Firefox
firefoxFailure
firefoxFailureAbout

**Comment by jennifer-shehane** [comment]
@HappyMan0001 Open a new issue, providing a reproducible example and steps here: https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&projects=&template=1-bug-report.yml
