### PR TITLE
fix: ensure that requests to the same resource will be properly intercepted even if they are sent in rapid succession

### LINKED ISSUE #30375: Flaky test: network stubbing - waiting and aliasing - yields the expected interception when two requests are raced.
### What would you like?

Address flake in this test, could try adding retries to start. [CircleCI failure](https://app.circleci.com/pipelines/gh/cypress-io/cypress/64463/workflows/35d027ee-edeb-4c10-9835-af89a580c06f/jobs/2675113)

Screenshot 2024-10-08 at 10 51 13 AM

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #30375 

### Additional details

When requests go through the proxy, they execute the following middleware functions that affect `matchingRoutes` that get attached to the request:

- SetMatchingRoutes - determines the set of matching requests and attaches it to the `req` object
- SendToDriver - uses the matching requests to determine whether or not this particular request should be proxy logged
- InterceptRequest - does the actual interception logic (if necessary)

Today, the set of matching requests gets set and then we associate subscriptions [here](https://github.com/cypress-io/cypress/blob/develop/packages/net-stubbing/lib/server/intercepted-request.ts#L55). We then proceed synchronously until we [await the request body](https://github.com/cypress-io/cypress/blob/develop/packages/net-stubbing/lib/server/middleware/request.ts#L139). In that time we could receive other requests that get their subscriptions defined. If the first request is supposed to surpass the maximum number of requests that a given interception can handle, it is supposed to not be available for the second one. However, since they've both had their associated subscriptions defined prior to being handled, this causes the first interception to apply to both requests.

This change removes the gap that can occur when multiple requests for the same resource occur in rapid succession by moving the subscription association to after the async awaiting of the request body. We then do a sanity check when adding the subscriptions to ensure the routes we are using are not disabled. 

### Steps to test

Added some unit tests for this as it is very difficult to reliably test in a more integrated fashion

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/net-stubbing/lib/server/middleware/request.ts [hunk 1]
```diff
@@ -138,6 +138,8 @@ export const InterceptRequest: RequestMiddleware = async function () {
 
   await ensureBody()
 
+  request.addDefaultSubscriptions()
```
Comment (ryanthemanuel) [inline packages/net-stubbing/lib/server/middleware/request.ts:144]:
```suggestion
  // Note that this needs to happen after the `ensureBody` call to ensure that we proceed synchronously to
  // where we update the state of the routes:
  // https://github.com/cypress-io/cypress/blob/aafac6a6104b689a118f4c4f29f948d7d8a35aef/packages/net-stubbing/lib/server/intercepted-request.ts#L167-L169
  request.addDefaultSubscriptions()
```

**Review by mschile — APPROVED** [review]

File: packages/net-stubbing/test/unit/intercepted-request-spec.ts [hunk 2]
```diff
@@ -60,5 +62,57 @@ describe('InterceptedRequest', () => {
...
+        expect(subEventName).to.eq('before:request')
+        expect(frame).to.deep.include({
+          subscription: {
+            eventName: 'before:request',
+            await: true,
+            routeId: '2',
+          },
+        })
+
+        state.pendingEventHandlers[frame.eventId](frame.data)
```
Comment (AtofStryker) [inline packages/net-stubbing/test/unit/intercepted-request-spec.ts:113]: do we need a `done` handler here or something similar in the case the fake for some reason is not called and the test passes when it shouldn't?

File: cli/CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,7 @@ _Released 10/1/2024 (PENDING)_
 **Bugfixes:**
 
 - Patched [find-process](https://github.com/yibn2008/find-process) to fix an issue where trying to clean up browser profiles can throw an error on Windows. Addresses [#30378](https://github.com/cypress-io/cypress/issues/30378).
+- Fixed an issue where requests to the same resource in rapid succession may not have the appropriate static response intercept applied if there are multiple intercepts that apply for that resource.
```
Comment (AtofStryker) [inline cli/CHANGELOG.md]: I think you need to link the PR or associated issue to make the semantic PR job happy

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: Doh. I was in the process of adding this but forgot to push it.

Comment (ryanthemanuel) [reply cli/CHANGELOG.md]: [`339a450` (#30435)](https://github.com/cypress-io/cypress/pull/30435/commits/339a450fe3ade676b440489e52971e0dd0706dd0)

File: packages/net-stubbing/test/unit/intercepted-request-spec.ts (hunk 2 above)
Comment (ryanthemanuel) [reply packages/net-stubbing/test/unit/intercepted-request-spec.ts:113]: You can't mix and match promises and done, but I figured a better way to ensure this is getting called: [`339a450` (#30435)](https://github.com/cypress-io/cypress/pull/30435/commits/339a450fe3ade676b440489e52971e0dd0706dd0)
