### PR TITLE
fix: Launchpad perpetual loading state, in certain circumstances

### LINKED ISSUE #29486: Flaky tests: Launchpad: Setup Project (project-setup.cy.ts)
### What would you like?

We have some tests that continues the [flakiest tests](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests) in our suite. You can see examples of this in several tests:

- [takes the user to first step of ct setup when switching from app](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?att=1&branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=be36fa2b-51fd-4972-8587-f8655cc4242f&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&ts=1715093917695.3171&viewBy=TEST_CASE)
- [skips the setup page when choosing e2e tests to run](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?att=1&branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=c0152e65-5f83-41d8-9060-949a1ddb56da&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&ts=1715008417167.053&viewBy=TEST_CASE)
- [shows the configuration setup page when selecting e2e tests](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?att=1&branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=68055a16-3a41-4259-b76a-d3b61ea44b4d&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&ts=1715022560775.1204&viewBy=TEST_CASE)
- [can reconfigure config after CT has been set up](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?att=1&branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=4254ab2e-409f-4442-9b1b-d390a3cd3f04&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&ts=1715009764757.3438&viewBy=TEST_CASE)
- [can skip setup CT testing for an E2E project](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?att=1&branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=243b5df4-d4a2-415b-adc2-cb068d5f15f1&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&ts=1715022588386.0894&viewBy=TEST_CASE)
- [opens docs link in the default browser](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?branches=%5B%7B%22value%22%3A%22develop%22%2C%22label%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&replayTestId=1ea01fdb-a1a8-4c5e-8efc-4347362c0414&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222024-04-30%22%2C%22endDate%22%3A%222024-05-07%22%7D&viewBy=TEST_CASE)
- [skips the setup steps when choosing component tests to run](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests/db4ec55e-e0e0-a19e-38ee-37625b5268dd-9fb3abd7-e8b9-628c-1f01-e030d7f46b4e)

It will most often exhibit as a loading spinner never going away after opening a project and visiting the launchpad, when the tests specifically are testing a flow where e2e or ct tests have already been chosen and configured.

```
expected <svg.spinner> not to exist in the DOM
```

Screenshot 2024-05-07 at 3 49 42 PM

In these situations, when comparing a passing and failing Test Replay, you can see one critical difference. 

- When this test passes, the response body of `POST /__launchpad/graphql/query-MainLaunchpadQuery` has `data.currentProject.isCTConfigured` or `data.currentProject.isE@EConfigured` as `true` (depending on the testing flow you were testing. 
- When this test fails, the response body of `POST /__launchpad/graphql/query-MainLaunchpadQuery` has `data.currentProject.isCTConfigured` and `data.currentProject.isE@EConfigured` as both `false`. 

**Passes**
Screenshot 2024-05-07 at 3 54 05 PM

**Fails**
Screenshot 2024-05-07 at 3 51 20 PM

The Launchpad is not coded to expect a situation where the 'currentTestingType' shows a specific testing type, yet the `isE2EConfigured` or `isCTConfigured` is not `true` as it should be, so it just sits forever in this loading state. 

I was unable to determine if this was an issue with how we mock our data for the tests or an actual issue in our App. This needs to be investigated. 

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/29486

### Additional details
This bug was evidenced by the flaky tests in the linked issue, but may have other manifestations that will clear up with this PR.

The `currentProject` schema on the `MainLaunchpadQuery` GraphQL query, used by Launchpad's `Main.vue`, has a field named `isLoadingConfigFile`. This is a boolean field, and both true and false fields are valid for it.

Previous to this PR, if this field was true for the first `MainLaunchpadQuery` request, the main launchpad UI would get stuck in a loading state: the rest of the launchpad cannot operate properly if the config file has not yet loaded, so we gate a lot of functionality behind that field.

In the linked flaky tests, we execute two custom tasks: `scaffoldProject` and `openProject`.

`scaffoldProject` initializes one of the projects from `system-tests`, and installs dependencies for it. `openProject` spawns the Cypress process that will execute against the scaffolded project, and initializes some data contexts. That kicks off the process that loads the config file, but the task does not wait for that loading to be complete before resolving. Sometimes the config file loads quickly - before the outer e2e runner can load the launchpad under test - and the flaky tests pass. Other times the config file loads during or just after the `MainLaunchpadQuery` request, which causes the flaky tests to fail - the inner loading spinner in `Main.vue` is never removed, because `isLoadingConfigFile` is false on first render of the query's data.

This is labeled as a `fix` rather than `flake` because this path, from what I can tell, is possible for end users to experience, though it is likely a rare occurrence.

The solution implemented is simply to poll (with a geometrically increasing delay) the `MainLaunchpadQuery` until the config file loads. This does not have a max count, because the `baseError` of this query is set up as a subscription - if the config file fails to load, the error gets propagated and the spinner is replaced with an error message.

Another option to consider would be to make config (and related fields in the `@packages/graphql` schema) a first-class type and resolver, where the root resolver would `await` the process of loading the config file. This was determined to be a fairly large change, however, when a simple poll would fix the manifestation of the bug.

### Steps to test
Execute the `config loading state` block in `@packages/launchpad`'s `project-setup.cy.ts` spec. The first request to the `MainLaunchpadQuery` resolves with `isLoadingConfigFile: true`, while the second request resolves with `isLoadingConfigFile: false`. Any subsequent calls will throw an error.

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/launchpad/src/Main.vue [hunk 1]
```diff
@@ -193,6 +193,50 @@ const resetErrorAndLoadConfig = (id: string) => {
...
+const refetchCount = ref(0)
+
+/*
+ * Sometimes the config file has not been loaded by the DataConntext's config manager by the
+ * time the MainLaunchpadQueryDocument request is sent off. The server ends up resolving
+ * the isLoadingConfigFile field as false. In certain situations, there can be a race between
+ * opening the project and the DataContext completing its retrieval of the configuration.
+ * In these cases, we want to retry the query until the config file is fully loaded.
+ *
+ * If the ProjectConfigIPC encounteres an error while loading the config, it will update the
```
Comment (ryanthemanuel) [inline packages/launchpad/src/Main.vue]:
```suggestion
 * If the ProjectConfigIPC encounters an error while loading the config, it will update the
```

File: packages/launchpad/src/Main.vue [hunk 2]
```diff
@@ -193,6 +193,50 @@ const resetErrorAndLoadConfig = (id: string) => {
...
+watch(
+  [currentProject, query.fetching],
+  ([currentProject, isFetchingProject]) => {
+    const isLoadingConfig = currentProject?.isLoadingConfigFile
+
+    /*
+     * conditions for refetch are:
+     * - There is a current project, but Config file has not yet loaded
+     * - There are no pending (delayed) refetches, or fetches in progress
+     * - There is no baseError - we don't want to continue to refetch if
```
Comment (ryanthemanuel) [inline packages/launchpad/src/Main.vue:221]: Do we want to have a test for the error scenario?

Comment (cacieprins) [reply packages/launchpad/src/Main.vue:221]: Addressed in https://github.com/cypress-io/cypress/pull/29597/commits/c15a55d4d1cf2886f903c4c17a5282db2f9e4243 - thanks, it found a bug!

File: cli/CHANGELOG.md [hunk 3]
```diff
@@ -9,6 +9,7 @@ _Released 6/4/2024 (PENDING)_
 
 **Bugfixes:**
 
+- Fixes situations where Launchpad would hang if the project config had not been loaded when the Launchpad Main.vue first queries the current project. Fixes [#29486](https://github.com/cypress-io/cypress/issues/29486).
```
Comment (AtofStryker) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed a situation where the Launchpad would hang if the project config had not been loaded when the Launchpad first queries the current project. Fixes [#29486](https://github.com/cypress-io/cypress/issues/29486).
```

File: packages/launchpad/cypress/e2e/project-setup.cy.ts [hunk 4]
```diff
@@ -694,4 +694,56 @@ describe('Launchpad: Setup Project', () => {
...
     })
   })
+
+  describe('config loading state', () => {
+    describe('when currentProject config loading state changes from loading to loaded after the first query', () => {
+      beforeEach(() => {
+        let responseCount = 0
+
+        cy.intercept('POST', '/__launchpad/graphql/query-MainLaunchpadQuery', (req) => {
+          req.reply(async (res) => {
```
Comment (AtofStryker) [inline packages/launchpad/cypress/e2e/project-setup.cy.ts]:
```suggestion
          req.reply((res) => {
```

File: packages/launchpad/src/Main.vue [hunk 5]
```diff
@@ -193,6 +193,56 @@ const resetErrorAndLoadConfig = (id: string) => {
 }
 const query = useQuery({ query: MainLaunchpadQueryDocument })
 const currentProject = computed(() => query.data.value?.currentProject)
+const hasBaseError = computed(() => !!query.data.value?.baseError)
+
+const refetchDelaying = ref(false)
+const refetchCount = ref(0)
+
+/*
+ * Sometimes the config file has not been loaded by the DataConntext's config manager by the
```
Comment (AtofStryker) [inline packages/launchpad/src/Main.vue]:
```suggestion
 * Sometimes the config file has not been loaded by the DataContext's config manager by the
```

**Review by ryanthemanuel — APPROVED** [review]

File: packages/launchpad/cypress/e2e/project-setup.cy.ts [hunk 6]
```diff
@@ -694,4 +694,56 @@ describe('Launchpad: Setup Project', () => {
...
+        let callCount = 0
+        let resWithBaseError: number | undefined
+
+        cy.intercept('POST', '/__launchpad/graphql/query-MainLaunchpadQuery', (req) => {
+          if (resWithBaseError && callCount >= resWithBaseError) {
+            throw new Error('Too many calls to MainLaunchpadQuery')
+          }
+
+          callCount++
+          req.reply(async (res) => {
```
Comment (AtofStryker) [inline packages/launchpad/cypress/e2e/project-setup.cy.ts]:
```suggestion
          req.reply((res) => {
```

**Review by AtofStryker — APPROVED** [review]

**Review by mschile — APPROVED** [review]
