### PR TITLE
Fix internal driver tests exiting with wrong exitCode

### LINKED ISSUE #7052: CircleCI exits as passing when Cypress tests have failed in our development
### Current behavior:

For our own internal tests, sometimes the CircleCI job will pass even though there was a failure within a Cypress test. The CircleCI is falsely passing. There is some suspicious that maybe `lerna` is suppressing the exit code. 

Example: https://github.com/cypress-io/cypress/pull/7014

CircleCI Jobs that should have failed but didn't (these are just random ones I clicked on):

- https://circleci.com/gh/cypress-io/cypress/302013
- https://circleci.com/gh/cypress-io/cypress/302036
- https://circleci.com/gh/cypress-io/cypress/302011
- https://circleci.com/gh/cypress-io/cypress/302019

Screen Shot 2020-04-16 at 1 44 45 PM

Screen Shot 2020-04-17 at 11 50 23 AM

### Desired behavior:

CircleCI jobs to fail when any tests fail.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #7052

### Additional details
- https://github.com/cypress-io/cypress/commit/abf4d858694e1be3ae6b93da42c6678ad22ba290#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R138 upgraded execa, from execa 2.0.0+ onwards, errors no longer have a `code` prop, only an `exitCode` prop
- affected `cypress` script used by `driver`'s `cypress:run`
- did not add a verify:mocha:results stage to driver tests

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: scripts/cypress.js [hunk 1]
```diff
@@ -16,10 +16,12 @@ debug('starting the CLI in dev mode with args %o', {
...
 
-const exit = ({ code }) => {
-  process.exit(code)
-}
-
 execa(pathToCli, args, { stdio: 'inherit' })
-.then(exit)
-.catch(exit)
+.then(({ code }) => {
+  debug('exiting normally %o', { code })
```
Comment (bahmutov) [inline scripts/cypress.js:21]: so ... if we got burnt by this once, let's not have it repeat it again. Imagine `execa` changes and ALSO does `code -> exitCode` for normal execution. Then this will again silently pass, even if `exitCode: 1`. 

```js
.then(({ code }) => {
  if (typeof code !== 'number') {
    console.error('Problem: missing exit code: code)
    process.exit(1)
  }
  // normal thing
})
```
