### PR TITLE
3.5.0 - send keyboard events for single value change inputs

### LINKED ISSUE #5476: Date/time input broken (no input events) since 3.5.0
### Current behavior:

Date inputs are not emitting *input* events since version 3.5.0.

### Desired behavior:

When typing into a date input field,  I expect the field to emit an input event (works in <= 3.4.1).

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress-test-tiny/pull/52/files

image

### Versions

3.5.0

### PR DESCRIPTION
**Pull request by kuceb**
regression, introduced in 3.5.0
- [x] send all keyboard events to single value change inputs
fix #5476

### User facing changelog
- we now send all the proper events to input elements with type `date`, `time`, and `datetime-local` #5476

### How has the user experience changed?
When typing into certain inputs (like date), we now send all keyboard events as we did prior to `3.5.0`. Some frameworks were reacting to this bug by seemingly deleting the value after it's been typed

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 1]
```diff
@@ -25,42 +29,12 @@ const mouseHoverEvents = [
...
-const attachListeners = (listenerArr) => {
-  return (els) => {
-    _.each(els, (el, elName) => {
-      return listenerArr.forEach((evtName) => {
-        el.on(evtName, cy.stub().as(`${elName}:${evtName}`))
-      })
-    })
-  }
-}
-
```
Comment (andrew-codes) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]: I like that this was pulled out into `support/utils`. Are there any other places in tests that do similar logic that can be replaced with `support/utils`? The rest of the comment is predicated on the assumption that there are additional places that could utilize this functionality. If there are not, then there's nothing to see here. ;-)

I ask because when I (any dev really) come back and reference one of these specs to use as an example to create a new, yet similar spec, it would be ideal if the pattern is using `support/utils`; instead of having potentially two ways do it.

**Review by andrew-codes — COMMENTED** [review]
I suspect my only commented question is that there are **not** other places that could be updated, but I wanted to ask just in case that is not correct.

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 1 above)
Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: similar logic can be moved here, sure

File: packages/driver/src/cy/keyboard.ts [hunk 2]
```diff
@@ -703,8 +705,9 @@ export class Keyboard {
             debug('skipping validation due to *skipCheckUntilIndex*', _skipCheckUntilIndex)
           }
 
-          if (key.simulatedDefaultOnly && key.simulatedDefault) {
-            key.simulatedDefault(activeEl, key, options)
+          // simulatedDefaultOnly keys will not send any events, and cannot be canceled
+          if (key.simulatedDefaultOnly) {
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/keyboard.ts]: This is my first time looking at this code. I was looking where this is used and I have to admit I'm still confused by the naming of this variable. What does `simulatedDefaultOnly` mean?? I think I understand the `simulatedDefault` part, but the `Only` means..?? It's doing absolutely nothing but the simulated default action?

**Review by jennifer-shehane — DISMISSED** [review]
This does fix the bug detailed in the PR. I'm still confused by what this is doing though, purely reading this code from having never looked at it before - it's not very clear.

File: packages/driver/src/cy/keyboard.ts (hunk 2 above)
Comment (Bkucera) [reply packages/driver/src/cy/keyboard.ts]: correct. this is used for special sequence `{selectall}` for example, since it represents ONLY an action, not any key presses

File: packages/driver/src/cy/keyboard.ts [hunk 3]
```diff
@@ -681,7 +681,9 @@ export class Keyboard {
               const keysToType = keyDetailsArr.slice(currentKeyIndex, currentKeyIndex + _skipCheckUntilIndex)
 
               _.each(keysToType, (key) => {
-                key.simulatedDefaultOnly = true
+                // singleValueChange inputs must have their value set once at the end
```
Comment (Bkucera) [inline packages/driver/src/cy/keyboard.ts]: this is what fixed the bug, setting this prop prevents keyboard events from being sent

File: packages/driver/src/cy/keyboard.ts [hunk 4]
```diff
@@ -681,7 +681,9 @@ export class Keyboard {
               const keysToType = keyDetailsArr.slice(currentKeyIndex, currentKeyIndex + _skipCheckUntilIndex)
 
               _.each(keysToType, (key) => {
-                key.simulatedDefaultOnly = true
```
Comment (Bkucera) [inline packages/driver/src/cy/keyboard.ts]: this is what fixed the bug, setting this prop prevents keyboard events from being sent
