### PR TITLE
fix: typedefs for isBrowser

### LINKED ISSUE #6447: incorrect type definition for isBrowser
isBrowser accepts a matcher object as well as a browser name

### PR DESCRIPTION
**Pull request by kuceb**
- Closes #6447
### User facing changelog
Fix incorrect type definition for `Cypress.isBrowser()` api

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

### CODE REVIEW

File: cli/types/tests/cypress-tests.ts [hunk 1]
```diff
@@ -338,3 +338,15 @@ namespace CypressLocationTests {
   cy.location('path') // $ExpectError
   cy.location('pathname') // $ExpectType Chainable<string>
 }
+
+namespace CypressBrowserTests {
+  Cypress.isBrowser('chrome')// $ExpectType boolean
+  Cypress.isBrowser('firefox')// $ExpectType boolean
+  Cypress.isBrowser('edge')// $ExpectType boolean
+  Cypress.isBrowser('brave')// $ExpectType boolean
```
Comment (bahmutov) [inline cli/types/tests/cypress-tests.ts]: I would add `Cypress.isBrowser('safari') // $ExpectError` and `Cypress.isBrowser('IE11') // $ExpectError`

File: cli/types/index.d.ts [hunk 2]
```diff
@@ -75,7 +75,7 @@ declare namespace Cypress {
     (task: 'firefox:force:gc'): Promise<void>
   }
 
-  type BrowserName = 'electron' | 'chrome' | 'chromium' | 'firefox' | string
+  type BrowserName = 'electron' | 'chrome' | 'chromium' | 'firefox' | 'edge' | 'brave' | string
```
Comment (flotwig) [inline cli/types/index.d.ts]: i think the enumerated BrowserNames should be limited to the ones we support out of the box, so:

```suggestion
  type BrowserName = 'electron' | 'chrome' | 'chromium' | 'firefox' | 'edge' | string

```

File: cli/types/index.d.ts [hunk 3]
```diff
@@ -335,11 +335,12 @@ declare namespace Cypress {
     isCy(obj: any): obj is Chainable
 
     /**
-     * Checks if you're running in the supplied browser family.
-     * e.g. isBrowser('Chrome') will be true for the browser 'Canary'
-     * @param name browser family name to check
+     * Returns true if currently running the supplied browser name or matcher object.
+     * @example isBrowser('chrome') will be true for the browser 'chrome:canary' and 'chrome:stable'
+     * @example isBrowser({ name: 'firefox' channel: 'dev' }) will be true only for the browser 'firefox:dev' (Firefox Developer Edition)
```
Comment (flotwig) [inline cli/types/index.d.ts]:
```suggestion
     * @example isBrowser({ name: 'firefox', channel: 'dev' }) will be true only for the browser 'firefox:dev' (Firefox Developer Edition)

```

**Review by flotwig — CHANGES_REQUESTED** [review]

File: cli/types/tests/cypress-tests.ts (hunk 1 above)
Comment (Bkucera) [reply cli/types/tests/cypress-tests.ts]: well, we don't currently error on those. the way the typedefs are made allow `| string`

File: cli/types/index.d.ts (hunk 2 above)
Comment (Bkucera) [reply cli/types/index.d.ts]: so no `| string` ?

Comment (flotwig) [reply cli/types/index.d.ts]: the `| string` can stay, so we can have correct types for user-supplied browsers

**Review by bahmutov — DISMISSED** [review]

**Review by flotwig — APPROVED** [review]
