### PR TITLE
CI should fail when something went wrong.

### LINKED ISSUE #5771: CI should fail when something went wrong.
### Current behavior:

Like #5734 and #5770, CI sometimes don't fail even when something went wrong. 
### Desired behavior:

CI should fail when something fails.

### Steps to reproduce: (app code and test code)

Check issues above.

### Versions

develop branch.

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #5771

* This PR will never pass until #5775 is merged. 

### User facing changelog

CI for coffeelint for server, mocha tests for reporter and runner should fail when something went wrong. 

### Additional details

- Why was this change necessary?

Even when something went wrong in coffeelint for server, mocha tests for reporter and runner, CI doesn't alert that. 

- What is affected by this change?

CI will fail when something fails.

- Any implementation details to explain?

* Removed bin-up for coffeelint in `server`. For some reason, bin-up ignores the failure. 
* Created wrapper runner for mocha tests for reporter and runner. They run twice for showing and checking results each. It doesn't affect CI speed because unit-test is fast enough. 

### How has the user experience changed?

N/A

### PR Tasks

- [NA] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: scripts/test-unit.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  await sleep(500)
+
+  if (log.match(/[0-9]+ passing.*\n\s*[0-9]+ failing/g) !== null) {
+    process.exit(1)
+  }
+
+  process.exit(0)
+})
+
+function sleep (ms) {
```
Comment (chrisbreiding) [inline scripts/test-unit.js]: Pull in Bluebird for the Promise (instead of the native one) and use [Promise.delay](http://bluebirdjs.com/docs/api/promise.delay.html) instead.

File: packages/server/test/unit/ci_provider_spec.coffee [hunk 2]
```diff
@@ -60,7 +60,7 @@ describe "lib/util/ci_provider", ->
       APPVEYOR_ACCOUNT_NAME: "appveyorAccountName"
       APPVEYOR_PROJECT_SLUG: "appveyorProjectSlug"
       APPVEYOR_BUILD_VERSION: "appveyorBuildVersion"
-      APPVEYOR_BUILD_NUMBER: "appveyorBuildNumber"
+      APPVEYOR_BUILD_NUMBER: "appveyorBuildNumber"
```
Comment (chrisbreiding) [inline packages/server/test/unit/ci_provider_spec.coffee]: This added whitespace is causing linting to fail.

**Comment by chrisbreiding** [comment]
Great work - thanks a lot!
