### PR TITLE
Fix Domain-specific cookies set on non-public TLDs

### LINKED ISSUE #6628: Issue with `cy.request` and cookies
### Current behavior:
Cookies received in response to `cy.request()` call, with a Domain value set to the parent domain of the target domain, are not being sent in subsequent `cy.request()` or `cy.visit()` calls.
This started happening with Cypress 3.5.0 and it's still happening with newer 4.x versions

**First `cy.request()` sets the cookie:**
Screenshot from 2020-03-03 16-27-13

**Second `cy.request()` doesn't send the cookie:**
Screenshot from 2020-03-03 16-27-26

### Desired behavior:

The cookies should be sent, like it is doing with Cypress 3.4.1

### Test code to reproduce

https://github.com/vfernandestoptal/cypress-broken-cookies

### Versions
Manjaro Linux kernel 5.5.6-1
Cypress 3.5.0 and higher
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6628 

### User facing changelog

- Fixed an issue where cookies set with a Domain containing a unknown TLD would not be sent along with certain requests. For example, a cookie like `foo=bar; Domain=.cypress.test` would not be sent with a `cy.request` to `http://local.cypress.test`.

### Additional details

- two-part change:
	- update our `customTlds` regex to capture `[^.]+$` as a fallback for any unrecognized TLD
	- patch our fork of `parse-domain` to fallback to `customTlds`, so that public suffixes can continue to work. otherwise, domains like `foo.co.uk` would have a tld of `uk`, not `co.uk`.
		- check out change here: https://github.com/cypress-io/parse-domain/commit/ba641cd9698e840c1dfa23b2c23deb6ba30fa86c

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cypress/location.coffee [hunk 1]
```diff
@@ -13,9 +13,9 @@ UrlParse = require("url-parse")
 ## and we need to move this to use
 ## node over websockets so we dont
 ## have to send it to the client
-parseDomain = require("parse-domain")
+parseDomain = require("@cypress/parse-domain")
 
-ipAddressRe = /^[\d\.]+$/
+customTldsRe = /(^[\d\.]+$|\.[^\.]+$)/
```
Comment (brian-mann) [inline packages/driver/src/cypress/location.coffee]: can we synchronize this change between the `driver` and the `network`?

File: packages/network/lib/cors.ts [hunk 2]
```diff
@@ -1,11 +1,11 @@
 import _ from 'lodash'
 import * as uri from './uri'
 import debugModule from 'debug'
-import _parseDomain, { ParsedDomain } from 'parse-domain'
+import _parseDomain, { ParsedDomain } from '@cypress/parse-domain'
 
 const debug = debugModule('cypress:network:cors')
 
-const ipAddressRe = /^[\d\.]+$/
+const customTldsRe = /(^[\d\.]+$|\.[^\.]+$)/
```
Comment (brian-mann) [inline packages/network/lib/cors.ts]: can we synchronize this change between the `driver` and the `network`?

File: packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_baseurl.coffee [hunk 3]
```diff
@@ -205,7 +205,8 @@ describe "cookies", ->
                 value: 'foo'
               })
 
-            cy.request('/requestCookies').its('body').should('include', { 'domaincookie': 'foo' })
+            cy.request("#{Cypress.config('baseUrl')}/requestCookies").its('body').should('include', { 'domaincookie': 'foo' })
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_baseurl.coffee]: move the `"#{Cypress.config('baseUrl')}/requestCookies"` to a `const` and reuse in all the subsequent places
