### PR TITLE
fix: set explicit screen when spawning own xvfb

### LINKED ISSUE #6184: Cypress verify command failing
### Current behavior:
After an apt update of ubuntu 18.04 (yesterday 16/01/2020), the following cypress command return an error.
`npx cypress verify`

> It looks like this is your first time using Cypress: 3.8.2
> 
>  ✖  Verifying Cypress can run /root/.cache/Cypress/3.8.2/Cypress
>    → Cypress Version: 3.8.2
> Cypress failed to start.
> 
> This is usually caused by a missing library or dependency.
> 
> The error below should indicate which dependency is missing.
> 
> https://on.cypress.io/required-dependencies
> 
> If you are using Docker, we provide containers with all required dependencies installed.
> 
> ----------
> 
> Command failed: /root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=24
> 
> ----------
> 
> Platform: linux (Ubuntu Linux - 18.04)
> Cypress Version: 3.8.2

`/root/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=24`

> (Cypress:20915): Gtk-WARNING **: 12:20:46.593: cannot open display:

### Desired behavior:
cypress verify should pass

### Versions
Ubuntu Linux - 18.04
Cypress Version: 3.8.2

#### Packages Versions :
`apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb`

> libgtk2.0-0 is already the newest version (2.24.32-1ubuntu1).
> libnotify-dev is already the newest version (0.7.7-3).
> libxss1 is already the newest version (1:1.2.2-1).
> libxtst6 is already the newest version (2:1.2.3-1).
> xauth is already the newest version (1:1.0.10-1).
> libgconf-2-4 is already the newest version (3.2.6-4ubuntu1).
> libasound2 is already the newest version (1.1.3-5ubuntu0.2).
> libgtk-3-0 is already the newest version (3.22.30-1ubuntu4).
> libnss3 is already the newest version (2:3.35-2ubuntu2.7).
> xvfb is already the newest version (2:1.19.6-1ubuntu4.3).

### PR DESCRIPTION
**Pull request by isnotgood**
- Closes #6184

### User facing changelog

Fixes `cypress verify` crash on some systems caused by not defined `-screen`. 

### Additional details

`cypress verify` crashes in a docker image with this environment: 

```console
root@6c2f9da07ecd:/app# uname -a 
Linux 6c2f9da07ecd 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@6c2f9da07ecd:/app# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
root@6c2f9da07ecd:/app# apt list xvfb 
Listing... Done
xvfb/bionic-updates,now 2:1.19.6-1ubuntu4.3 amd64 [installed]
N: There are 2 additional versions. Please use the '-a' switch to see them.
root@6c2f9da07ecd:/app# node -v 
v10.14.2
root@6c2f9da07ecd:/app# ./node_modules/.bin/cypress -v 
Cypress package version: 3.8.2
Cypress binary version: 3.8.2
root@6c2f9da07ecd:/app# file /root/.cache/Cypress/3.8.2/Cypress/Cypress 
/root/.cache/Cypress/3.8.2/Cypress/Cypress: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=5b4fa88bff30493405377c54ef4308de9e5db705, stripped
```

When I run it with `ELECTRON_ENABLE_STACK_DUMPING` I get this: 

```console 
root@6c2f9da07ecd:/app# ELECTRON_ENABLE_STACK_DUMPING=1 ./node_modules/.bin/cypress verify 
It looks like this is your first time using Cypress: 3.8.2

 ✖  Verifying Cypress can run /root/.cache/Cypress/3.8.2/Cypress
   → Cypress Version: 3.8.2
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Received signal 11 SEGV_MAPERR fffff4109b7ba15a
#0 0x55720269a3d9 (/root/.cache/Cypress/3.8.2/Cypress/Cypress+0x35d13d8)
r8: 0000000000000000  r9: 00007ffc516aaa30 r10: 00007ffc516aa988 r11: 000000000000000e
r12: 00007ffc516aaadc r13: 00007fa6dfe4f720 r14: fffff4109b7ba12a r15: 00007fa6e1448200
di: 0000000000000000  si: 0000000000000020  bp: 0000000000000000  bx: 00000bedcf1caf20
dx: 0000000000000001  ax: 0000000000000030  cx: 0000000000000001  sp: 00007ffc516aaab0
ip: 00007fa6e142c2dd efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000005
trp: 000000000000000e msk: 0000000000000000 cr2: fffff4109b7ba15a
[end of stack trace]
Calling _exit(1). Core file will not be generated.

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.8.2
```

Directly running `Xvfb` and invoking cypress binary from node works well:

```console
root@6c2f9da07ecd:/app# Xvfb :1 -screen 0 1280x800x24 &
[1] 9546
root@6c2f9da07ecd:/app# node -e "require('child_process').spawnSync('/root/.cache/Cypress/3.8.2/Cypress/Cypress', ['--no-sandbox', '--smoke-test', '--ping=89'], { env: { DISPLAY: ':1' }, stdio: 'inherit' });"
It looks like you are running the Cypress binary directly.

This is not the recommended approach, and Cypress may not work correctly.

Please install the 'cypress' NPM package and follow the instructions here:

https://on.cypress.io/installing-cypress
89
```

Even checked with `xwd` what is in the framebuffer and all fine. 

So I got suspicious Xvfb is not working and added `ps aux` before and after smoke test is executed and turned out that Xvfb is missing `-screen`. Not sure if this should not be handled in `@cypress/xvfb`, up to maintainers.

Feel free to cancel if you already have fix elsewhere.

### How has the user experience changed?

**Before**
Screenshot 2020-01-20 23 24 20

**After**
Screenshot 2020-01-20 23 24 35

### PR Tasks

- [ ] Have tests been added/updated?

### CODE REVIEW

File: cli/lib/exec/xvfb.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ const util = require('../util')
 
 const xvfb = Promise.promisifyAll(new Xvfb({
   timeout: 30000, // milliseconds
+  xvfb_args: ['-screen', '0', '1280x1024x24'], // need to explicitly define screen otherwise electron will crash
```
Comment (isnotgood) [inline cli/lib/exec/xvfb.js]: I took this value from [freedesktop/xorg-xserver](https://github.com/freedesktop/xorg-xserver/blob/master/hw/vfb/InitOutput.c#L277) but there has to be something rotten with ubuntu's xvfb, because it's mentioned in man as well as in [code](https://github.com/freedesktop/xorg-xserver/blob/2a2234ad1a0fe88400c1511fea67741e4ad09f7f/hw/vfb/InitOutput.c#L273) that `-screen` is default to `1280x1024x24` 🤔

Comment (isnotgood) [reply cli/lib/exec/xvfb.js]: Actualyl ubuntu uses this packag [bionic/xvfb](https://packages.ubuntu.com/bionic/xvfb) contains older version with: 

```c
#define VFB_DEFAULT_WIDTH      1280
#define VFB_DEFAULT_HEIGHT     1024
#define VFB_DEFAULT_DEPTH         8
```

So I thought that Electron is freaking out because of the bit depth, but when I start Xvbf with 8bits electron is still fine with that even without `-screen` at all 🤷‍♂

Comment (isnotgood) [reply cli/lib/exec/xvfb.js]: So latest development indicates that it could be problem somewhere else and this is just red herring:

```console
[2031:0121/105922.460578:FATAL:memory.cc(22)] Out of memory. size=65536
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.
(...)
```

File: cli/lib/exec/spawn.js [hunk 2]
```diff
@@ -119,6 +119,9 @@ module.exports = {
           electronArgs.unshift('--no-sandbox')
         }
 
+        // docker containers have 64M by default, sometimes even less
+        electronArgs.push('--disable-dev-shm-usage')
```
Comment (isnotgood) [inline cli/lib/exec/spawn.js]: For some reason recent builds are pressing memory much harder, if I add `--disable-dev-shm` it will crash later.

Comment (isnotgood) [reply cli/lib/exec/spawn.js]: That cures just one symptom and not very well, reverting.

**Comment by bahmutov** [comment]
I have built `cypress/base:ubuntu18-node12.14.1` in https://github.com/cypress-io/cypress-docker-images/pull/211 and verified that this fix solves the problem. Also this fix still works in previous image `cypress/base:13.6.0` for example.

**Comment by bahmutov** [comment]
Added small unit test in https://github.com/cypress-io/cypress/commit/9ac5fe3935a3ab3c527218721d881e70d4caf450

**Comment by isnotgood** [comment]
Awesome, thank you @bahmutov 🙇
