### PR TITLE
fix: prevent vite from crashing where there are no support files or specs found

### LINKED ISSUE #17373: TypeError when launching `cypress open-ct`
### Current behavior

I'm trying to launch the UI in component test mode, using @cypress/vite-dev-server. It crashes before it can start with this error:

```
  cypress:server:plugins call event dev-server:start for invocation id inv1 +3ms
  cypress:server:plugins:child execute plugin event: dev-server:start ({ eventId: 2, invocationId: 'inv1' }) +105ms
  cypress:vite-dev-server:start starting vite dev server +0ms
  cypress:vite-dev-server:start the resolved server config is {
  cypress:vite-dev-server:start   "base": "/__cypress/src/",
  cypress:vite-dev-server:start   "root": "/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app",
  cypress:vite-dev-server:start   "plugins": [
  cypress:vite-dev-server:start     {
  cypress:vite-dev-server:start       "name": "cypress-transform-html",
  cypress:vite-dev-server:start       "enforce": "pre"
  cypress:vite-dev-server:start     }
  cypress:vite-dev-server:start   ],
  cypress:vite-dev-server:start   "resolve": {},
  cypress:vite-dev-server:start   "server": {
  cypress:vite-dev-server:start     "port": 3000
  cypress:vite-dev-server:start   },
  cypress:vite-dev-server:start   "optimizeDeps": {
  cypress:vite-dev-server:start     "entries": [
  cypress:vite-dev-server:start       false
  cypress:vite-dev-server:start     ]
  cypress:vite-dev-server:start   }
  cypress:vite-dev-server:start } +12ms
  cypress:vite-dev-server:plugin transformIndexHtml with base /__cypress/src/ +0ms
  cypress:server:plugins promise rejected for id inv1 ':' TypeError: Patterns must be a string (non empty) or an array of strings
    at assertPatternsInput (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/fast-glob/out/index.js:64:15)
    at glob (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/fast-glob/out/index.js:9:5)
    at globEntries (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/vite/src/node/optimizer/scan.ts:118:10)
    at scanImports (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/vite/src/node/optimizer/scan.ts:55:21)
    at optimizeDeps (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/vite/src/node/optimizer/index.ts:156:33)
    at runOptimize (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/vite/src/node/server/index.ts:541:46)
    at Server.httpServer.listen (/Users/ericwagoner/iinteractive/neochromosome/rf/packages/int-app/node_modules/vite/src/node/server/index.ts:555:15) +0ms
```

### Desired behavior

I'm just trying to start the UI in Component Testing mode

### Test code to reproduce

My plugins `index.ts` is very bare-bones:

```js
import { startDevServer } from "@cypress/vite-dev-server";

module.exports = (on, config) => {
  on("dev-server:start", (options) =>
    startDevServer({
      options,
      viteConfig: {},
    })
  );

  return config;
};
```

### Cypress Version

7.7.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by elevatebart**
When there is no values, in the optimization array,
supportFile can be a boolean. the final optimized entry passed to
fast-glog is then `[false]` whic crashes cypress.

This protects against the no-spec issue

closes #17373

## How to reproduce

- create a vite app (`yarn create vite-app`)
- create cypress component testings around it (`yarn create cypress-tests`) 
- in the `cypress.json` set `supportFile` to `false` and make sure there is no spec files.

Here is the crash.

### CODE REVIEW

File: npm/vite-dev-server/src/startServer.ts [hunk 1]
```diff
@@ -59,7 +59,9 @@ const resolveServerConfig = async ({ viteConfig, options }: StartDevServerOption
   // Ask vite to pre-optimize all dependencies of the specs
   finalConfig.optimizeDeps = finalConfig.optimizeDeps || {}
 
-  finalConfig.optimizeDeps.entries = [...options.specs.map((spec) => spec.relative), supportFile]
+  if (options.specs.length || supportFile) {
```
Comment (JessicaSachs) [inline npm/vite-dev-server/src/startServer.ts:62]: Should probably make sure that if specs is undefined, make sure that we don't crash.

Comment (elevatebart) [reply npm/vite-dev-server/src/startServer.ts:62]: OK I'll add this protection

Comment (elevatebart) [reply npm/vite-dev-server/src/startServer.ts]: Done 7b012b2

**Review by ewagoner — APPROVED** [review]

**Review by JessicaSachs — APPROVED** [review]
