### PR TITLE
fix: test config overrides leak for .only execution

### LINKED ISSUE #18959: Test Configuration data leaking into configuration for describe.only & it.only blocks
### Current behavior

@davidmunechika discovered the test configuration was not applying correctly for single suite/test execution. When Cyress starts, the [runner normalize's the mocha runnables](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L1302), which is where we determine the expected test configuration. When the [runner filters](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/runner.ts#L669) for a suite or test that has marked as the only one that should run, the runner re-normalizes the mocha runnables. At this point, the test configuration has been formatted with the invocation details to determine where the configuration has been passed if the configuration fails its validation. 

### Desired behavior

The test configuration should not leak the testConfigList or unverifiedTestOverrides data onto the configuration when a suite or test is marked as the only block to execute.

### Test code to reproduce

```js
describe('my suite', () => {
  describe.only('my nested suite', () => {
    it('my test', () => {
      expect(Cypress.config('testConfigList')).to.be.undefined
      expect(Cypress.config('unverifiedTestConfig')).to.be.undefined
    })
  })
})
```

```js
describe('my suite', () => {
  it.only('my test', () => {
    expect(Cypress.config('testConfigList')).to.be.undefined
    expect(Cypress.config('unverifiedTestConfig')).to.be.undefined
  })
})
```

### Cypress Version

9.0.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #18959 

Recent change to add configuration validation required updates to include the invocation details to throw an invalidation configuration error with the correct line number of where the configuration was passed in for suite/test configuration. These changed did not account for single suite/test execution which was normalized more than once.

### How has the user experience changed?

The configuration appears to have been applying correctly, so should be minimal to no impact on consumers.

### PR Tasks

- [x] Have tests been added/updated?
- [] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: system-tests/test/testConfigOverrides_spec.ts [hunk 1]
```diff
@@ -33,6 +33,24 @@ describe('testConfigOverrides', () => {
...
+  })
+
+  systemTests.it(`correctly applies overrides when valid configuration for it.only`, {
+    spec: 'testConfigOverrides-it-only-valid.js',
+    snapshot: true,
+    expectedExitCode: 0,
+    config: {
+      video: false,
+    },
+  })
```
Comment (flotwig) [inline system-tests/test/testConfigOverrides_spec.ts:52]: I think these don't need to be system tests, they can be regular driver Cypress tests instead, right? Since we run one test file at a time in `cypress run`, it should work the same. `packages/driver/cypress/integration/e2e` would be a good place.

Avoid adding system tests if possible since they're a lot heavier, resource-wise. And since we're just running the test and the snapshot doesn't have any additional info in it, it should be fine to make these regular Cypress tests.

Comment (emilyrohrbough) [reply system-tests/test/testConfigOverrides_spec.ts]: hmmm good point. Updated: [`96e4e80` (#18961)](https://github.com/cypress-io/cypress/pull/18961/commits/96e4e80b4fe75f10da49b386c0ec33b01a8f0a02)

**Review by davidmunechika — APPROVED** [review]

**Review by flotwig — APPROVED** [review]
