### PR TITLE
fix type when previous selection in input in some cases

### LINKED ISSUE #5703: 3.5.0-3.6.1 regression - cy.type() may skip a character on a autofocussing textbox
### Current behavior:

When typing '10' into a textbox with text selected and that text is '1', the textbox doesn't lose the selection upon typing the first '1' so when the '0' is typed the textbox ends up with '0' but if a user types it, we get '10'

### Steps to reproduce: (app code and test code)

https://github.com/cypress-io/cypress-test-tiny/pull/54

### Versions

3.6.1, windows

@Bkucera I guess this is a regression from your type() changes.

### PR DESCRIPTION
**Pull request by Bkucera**
- Closes #5703

### User facing changelog
- fixes issue with `.type` not respecting previous selection in non-selectionRange input element (email, number) (only way to change selection is with `.select()`)
- fixes issue with `.type` not respecting previous selection if current value of the input is same as key

### Additional details
- code from firefox branch was pulled in, causing the large amount of files changed. This will help reduce changes needed for firefox as well

#### when attempting to use `.type` on a number or email input that has a text selection (or is selected in a focus handler):
before (incorrect): text is appended to the current selection
after (correct): text replaces current selection

#### when attempting to use `.type` on an input that has a text selection (or is selected in a focus handler) of 1 character equal to the key typed:
before (incorrect): ignores current key, next character replaces selection 
after (correct): text replaces current selection, next character is typed after

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cy/keyboard.ts [hunk 1]
```diff
@@ -246,6 +246,27 @@ const shouldUpdateValue = (el: HTMLElement, key: KeyDetails) => {
...
 
+    const isNumberInputType = $elements.isInput(el) && $elements.isInputType(el, 'number')
+
+    if (isNumberInputType) {
+      const needsValue = options.prevVal || ''
+      const needsValueLength = (needsValue && needsValue.length) || 0
+      const curVal = $elements.getNativeProp(el, 'value')
+      const bounds = $selection.getSelectionBounds(el)
+
+      const potentialValue = $selection.insertSubstring(curVal + needsValue, key.text, [bounds.start + needsValueLength, bounds.end + needsValueLength])
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: i feel like this needs an explanation... its so opaque why this is necessary

File: packages/driver/src/cy/keyboard.ts [hunk 2]
```diff
@@ -309,12 +330,12 @@ const validateTyping = (
   let isDateTime = false
 
   if ($elements.isInput(el)) {
-    isDate = $dom.isInputType(el, 'date')
-    isTime = $dom.isInputType(el, 'time')
-    isMonth = $dom.isInputType(el, 'month')
-    isWeek = $dom.isInputType(el, 'week')
+    isDate = $elements.isAttrType(el, 'date')
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]: worth noting why the `isAttrType` is necessary here.

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 3]
```diff
@@ -985,6 +985,51 @@ describe('src/cy/commands/actions/type', () => {
...
+      it('overwrites text when selectAll in focus handler', () => {
+        const input = cy.$$('#input-without-value')
+
+        input
+        .val('f')
+        .on('focus', (e) => {
+          e.currentTarget.select()
+        })
+
+        // input[0].setSelectionRange(0,0)
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: delete

File: packages/driver/src/dom/selection.ts [hunk 4]
```diff
@@ -430,54 +467,58 @@ const _moveSelectionTo = function (toStart: boolean, doc: Document, options = {}
...
-  _replaceSelectionContentsWithExecCommand(doc, key)
-
   return false
 }
 
 const getCaretPosition = function (el) {
   const bounds = getSelectionBounds(el)
 
-  if (bounds.start == null) {
+  if ((bounds.start == null)) {
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: parenths

File: packages/driver/src/dom/selection.ts [hunk 5]
```diff
@@ -388,17 +425,17 @@ const selectAll = function (doc) {
...
       return _getSelectionBoundsFromTextarea(el)
-    case !!$elements.isContentEditable(el):
+    case !$elements.isContentEditable(el):
       return _getSelectionBoundsFromContentEditable(el)
     default:
       return {
-        start: 0,
-        end: 0,
+        start: null,
+        end: null,
```
Comment (brian-mann) [inline packages/driver/src/dom/selection.ts]: switch back to `switch (true)`

File: packages/driver/src/dom/elements.ts [hunk 6]
```diff
@@ -505,6 +505,16 @@ const isInputType = function (el: JQueryOrEl<HTMLElement>, type) {
...
 
+const isAttrType = function (el: HTMLInputElement, type: string) {
+  const elType = (el.getAttribute('type') || '').toLowerCase()
+
+  if (elType === type) {
+    return true
+  }
+
+  return false
+}
```
Comment (brian-mann) [inline packages/driver/src/dom/elements.ts]: https://github.com/cypress-io/cypress/pull/1359#discussion_r341870379

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 7]
```diff
@@ -985,6 +985,49 @@ describe('src/cy/commands/actions/type', () => {
...
+        .on('focus', (e) => {
+          e.currentTarget.select()
+        })
+
+        cy.get('#number-without-value')
+        .type('10')
+        .should('have.value', '10')
+      })
+
+      it('overwrites text when selectAll in focus handler in date', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: `email` not date
