### PR TITLE
fix: activate main tab before detecting iframe focus in firefox/bidi implementation of cy.press()

### LINKED ISSUE #31466: In Firefox, `cy.press()` only works in the first spec of a run
### Current behavior

In firefox, when used in a spec that is not first in a run, `cy.press()` will fail with an error similar to:

```
no such window: WebDriverError: Browsing context has been discarded when running "element" with method "POST" and args "{"using":"css selector","value":"iframe.aut-iframe"}"
    at FetchRequest._request (file:///root/cypress/packages/server/node_modules/webdriver/build/node.js:1791:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bidiKeyPress (<embedded>:704266:29)
    at async onRequest (<embedded>:708443:17)
From previous event:
    at <unknown> (<embedded>:705562:57)
    at <unknown> (<embedded>:705632:20)
From previous event:
    at Automation.normalize (<embedded>:705601:53)
    at Automation.request (<embedded>:705657:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Desired behavior

`cy.press()` executes correctly in firefox

### Test code to reproduce

`packages/driver/cypress/e2e/commands/actions/press.cy.ts` occasionally fails in CI with this error:

https://app.circleci.com/pipelines/github/cypress-io/cypress/69359/workflows/7ce399ab-4569-4830-9e07-452f48098e6b/jobs/2850470/tests#failed-test-0

### Cypress Version

14.3.0

### Node version

20.18.1

### Operating System

darwin

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/31466

### Additional details
The webdriver classic window reference does not sync with the webdriver bidi active context automatically; between specs we clear out all of the tabs and create a new one, so webdriver classic needs to be informed of which window/tab needs to be active. The webdriver classic methods in use are in order to determine if the AUT iframe has focus (will receive key press events).

### Steps to test

In run mode, execute any spec prior to executing the `cypress/e2e/commands/actions/press.cy.ts` spec (or any other spec that includes the `cy.press()` command. The `cy.press()` command should not error.

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/automation/commands/key_press.ts [hunk 1]
```diff
@@ -104,24 +104,63 @@ export const BIDI_VALUE: KeyCodeLookup = {
   'Tab': '\uE004',
 }
 
+async function hasActiveWindow (client: Client) {
+  try {
+    return !!(await client.getWindowHandle())
+  } catch (e) {
+    return false
```
Comment (AtofStryker) [inline packages/server/lib/automation/commands/key_press.ts]: maybe a debug statement here on the error to see why this would fail?

File: packages/server/lib/automation/commands/key_press.ts [hunk 2]
```diff
@@ -104,24 +104,63 @@ export const BIDI_VALUE: KeyCodeLookup = {
...
+  }
+}
+
+async function activateTopWindow (client: Client, autContext: string): Promise<void> {
+  const { contexts: [{ context: topLevelContext }] } = await client.browsingContextGetTree({
+    maxDepth: Infinity,
```
Comment (AtofStryker) [inline packages/server/lib/automation/commands/key_press.ts]: any reason we need the `Infinity` max depth if we are only getting the top context?

File: packages/server/lib/automation/commands/key_press.ts [hunk 3]
```diff
@@ -104,24 +104,63 @@ export const BIDI_VALUE: KeyCodeLookup = {
...
-    )
+  const needsWindowActivation = !(await hasActiveWindow(client))
+
+  // TODO: refactor for Cy15 https://github.com/cypress-io/cypress/issues/31480
+  if (needsWindowActivation) {
+    debug('Primary window is not currently active; attempting to activate')
+    try {
+      await activateTopWindow(client, autContext)
+    } catch (e) {
+      debug('Error while attempting to activate main browser tab:', e)
```
Comment (AtofStryker) [inline packages/server/lib/automation/commands/key_press.ts:131]: nvrmind the other comment looks like we have what we need here on the debugging

File: packages/server/lib/automation/commands/key_press.ts (hunk 2 above)
Comment (cacieprins) [reply packages/server/lib/automation/commands/key_press.ts]: ope, nice catch thank you

Comment (cacieprins) [reply packages/server/lib/automation/commands/key_press.ts]: addressed in https://github.com/cypress-io/cypress/pull/31481/commits/162bd219b1cb020d6affff6bdc3f6b9053893112

File: packages/server/lib/automation/commands/key_press.ts [hunk 4]
```diff
@@ -104,24 +104,61 @@ export const BIDI_VALUE: KeyCodeLookup = {
...
+async function hasActiveWindow (client: Client) {
+  try {
+    return !!(await client.getWindowHandle())
+  } catch (e) {
+    return false
+  }
+}
+
+async function activateTopWindow (client: Client, autContext: string): Promise<void> {
+  const { contexts: [{ context: topLevelContext }] } = await client.browsingContextGetTree({})
```
Comment (AtofStryker) [inline packages/server/lib/automation/commands/key_press.ts]: can we just eliminate this function and just call `client.switchToWindow(topLevelContext)` or remove the `autContext` arg? I don't think `autContext` is used, but my guess is this was looking up the top context before but no longer is?

**Review by AtofStryker — CHANGES_REQUESTED** [review]

File: packages/server/lib/automation/commands/key_press.ts (hunk 4 above)
Comment (cacieprins) [reply packages/server/lib/automation/commands/key_press.ts]: Addressed in https://github.com/cypress-io/cypress/pull/31481/commits/e0421b25fd802426029bacae61c6e83cb3227791

File: packages/server/test/unit/automation/commands/key_press.spec.ts [hunk 5]
```diff
@@ -226,7 +250,19 @@ describe('key:press automation command', () => {
...
     })
 
+    describe('when webdriver classic has no active window', () => {
+      beforeEach(() => {
+        client.getWindowHandle.rejects(new Error())
+      })
+
+      it('activates the top level context window', async () => {
+        await bidiKeyPress({ key }, client as WebdriverClient, autContext, 'idSuffix')
+        expect(client.switchToWindow).to.have.been.calledWith(topLevelContext)
```
Comment (AtofStryker) [inline packages/server/test/unit/automation/commands/key_press.spec.ts:282]: Probably also testing the case when the top level context is already active and we don't need to call `switchToWindow` if that test doesn't already exist

**Review by AtofStryker — APPROVED** [review]

File: packages/server/test/unit/automation/commands/key_press.spec.ts (hunk 5 above)
Comment (cacieprins) [reply packages/server/test/unit/automation/commands/key_press.spec.ts:282]: Definitely - also the case where there is an active window, but it's not our `top`. Addressed in https://github.com/cypress-io/cypress/pull/31481/commits/944b91344e425400a6db630a348678f3361f8ede
