### PR TITLE
fix: pass all chromium flags through to Electron

### LINKED ISSUE #27939: Works in Electron but hangs when using Chrome and Firefox
### Description

I've created a very simple e2e test for the login page. The issue is that the test only works in Electron.

### URL of Issue(s)

http://localhost:8080

### Steps to replicate

nuxeo-cypress

### Browser

Chrome 117, Electron 114

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

```js
// cypress/e2e/spec.cy.js
describe('template spec', () => {
    it('passes', () => {
        cy.visit('http://localhost:8080');
        cy.get('.idItem > a').click();
        cy.get('#username').type('Administrator');
        cy.get('#password').type('Nuxeo20!9'); // silly password for my local env only
        cy.get('#login_button').click();
    })
})
```

Terminal Logs for **Chrome 117**

```
GET /__cypress/iframes/cypress%2Fe2e%2Fspec.cy.js?browserFamily=chromium 200 1.276 ms - -
GET /__cypress/tests?p=cypress/e2e/spec.cy.js 200 1.159 ms - -
GET /__cypress/tests?p=cypress/support/e2e.js 200 1.816 ms - -
GET / 200 2.975 ms - -
GET /nuxeo 302 2.817 ms - 58
GET /nuxeo/ 302 8.332 ms - 106
GET /nuxeo/ui/ 401 4.286 ms - -
GET /nuxeo/login.jsp?requestedUrl=ui%2F 200 18.871 ms - -
POST /nuxeo/startup 302 147.118 ms - 106
GET /nuxeo/ui/ 200 7.299 ms - -
GET /nuxeo/ui/config.jsp 200 97.572 ms - -
GET /nuxeo/json/cmis 200 13.198 ms - -
POST /nuxeo/api/v1/automation/login 200 3.081 ms - -
GET /nuxeo/api/v1/user/Administrator 200 12.654 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 514.260 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 506.556 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 512.514 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 507.320 ms - -
```

Terminal Logs for **Electron 114**

```
GET /__cypress/iframes/cypress%2Fe2e%2Fspec.cy.js?browserFamily=chromium 200 0.973 ms - -
GET /__cypress/tests?p=cypress/e2e/spec.cy.js 200 0.933 ms - -
GET /__cypress/tests?p=cypress/support/e2e.js 200 1.944 ms - -
GET / 200 2.175 ms - -
GET /nuxeo 302 3.065 ms - 58
GET /nuxeo/ 302 6.713 ms - 106
GET /nuxeo/ui/ 401 6.641 ms - -
GET /nuxeo/login.jsp?requestedUrl=ui%2F 200 5.644 ms - -
POST /nuxeo/startup 302 26.366 ms - 106
GET /nuxeo/ui/ 200 12.532 ms - -
GET /nuxeo/ui/config.jsp 200 129.543 ms - -
HEAD /nuxeo/ui/themes/default/theme.html 200 4.471 ms - -
GET /nuxeo/json/cmis 200 54.580 ms - -
POST /nuxeo/api/v1/automation/login 200 4.310 ms - -
GET /nuxeo/api/v1/user/Administrator 200 189.781 ms - -
POST /nuxeo/api/v1/automation/NuxeoDrive.GetRoots 200 7.677 ms - -
GET /nuxeo/api/v1/task?currentPageIndex=0&pageSize=1&userId=Administrator 200 45.092 ms - -
POST /nuxeo/api/v1/automation/User.GetUserWorkspace 200 109.918 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 505.312 ms - -
GET /nuxeo/api/v1/path/default-domain/MasterData/Notifications/Notification 200 73.951 ms - -
GET /nuxeo/api/v1/search/pp/gvl_pp/execute?currentPageIndex=0&pageSize=40 200 26.750 ms - -
GET /nuxeo/api/v1/search/pp/stockSearch_pp/execute?currentPageIndex=0&pageSize=40 200 30.499 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=gvl_pp 200 63.946 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=stockSearch_pp 200 61.803 ms - -
GET /nuxeo/api/v1/search/pp/scriptureReference_pp/execute?currentPageIndex=0&pageSize=40 200 10.283 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=productionAssetsSearch_pp 200 85.922 ms - -
GET /nuxeo/api/v1/token?application=Nuxeo%20Drive 200 21.839 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=scriptureReference_pp 200 39.501 ms - -
GET /nuxeo/api/v1/search/pp/productionAssetsSearch_pp/execute?currentPageIndex=0&pageSize=40 200 196.928 ms - -
GET /nuxeo/api/v1/task?currentPageIndex=0&offset=0&pageSize=16&userId=Administrator 200 74.969 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 508.175 ms - -
POST /nuxeo/api/v1/automation/Favorite.Fetch 200 125.947 ms - -
GET /nuxeo/api/v1/search/pp/domain_documents/execute?currentPageIndex=0&offset=0&pageSize=16&queryParams=%2F 200 139.121 ms - -
GET /nuxeo/api/v1/path/ 200 11.965 ms - -
GET /nuxeo/api/v1/search/pp/default_content_collection/execute?currentPageIndex=0&offset=0&pageSize=16&queryParams=bef63beb-7509-4767-bf91-7ed54e5b6283 200 22.250 ms - -
GET /nuxeo/api/v1/search/pp/nxql_search/execute?currentPageIndex=0&pageSize=20&queryParams=SELECT%20*%20FROM%20Document%20WHERE%20ecm%3AparentId%20%3D%20%2700000000-0000-0000-0000-000000000000%27%20AND%20ecm%3AmixinType%20%3D%20%27Folderish%27%20AND%20ecm%3AmixinType%20!%3D%20%27HiddenInNavigation%27%20AND%20ecm%3AisVersion%20%3D%200%20AND%20ecm%3AisTrashed%20%3D%200 200 50.276 ms - -
GET /es2020/userflow.js?ts=1695750496935 200 615.142 ms - -
GET /es2020/flow-condition-types.95a68e08.js?ts=1695750496935 200 538.300 ms - -
GET /es2020/z-index.3189a525.js?ts=1695750496935 200 558.728 ms - -
GET /es2020/index.7d3437e2.js?ts=1695750496935 200 554.882 ms - -
GET /es2020/ResourceCenterApp.87f1ec4b.js?ts=1695750496935 200 569.189 ms - -
GET /es2020/BubbleToolbar.a0340e00.js?ts=1695750496935 200 570.212 ms - -
GET /es2020/ui.9c8f1fd3.js?ts=1695750496935 200 584.371 ms - -
GET /es2020/stylesheets.f23f55c3.js?ts=1695750496935 200 544.305 ms - -
GET /es2020/logomark.9bde6266.js?ts=1695750496935 200 560.344 ms - -
GET /es2020/ChecklistUI.c151c139.js?ts=1695750496935 200 565.134 ms - -
GET /es2020/Trigger.cc553eba.js?ts=1695750496935 200 556.815 ms - -
GET /es2020/LauncherApp.52884b06.js?ts=1695750496935 200 565.169 ms - -
GET /es2020/FlowChrome.7a810f94.js?ts=1695750496935 200 564.828 ms - -
GET /es2020/flow-host.f1352f71.css 200 34.154 ms - -
GET /es2020/bubble-frame.aaec9943.css 200 32.552 ms - -
GET /es2020/iframe-reset.3b2212c0.css 200 35.288 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 514.421 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 512.067 ms - -
```

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes https://github.com/cypress-io/cypress/issues/27939

### Additional details

[This issue](https://github.com/cypress-io/cypress/issues/27939) highlighted that there are some differences in how Electron's Chromium browser runs vs Chrome's browser due to the same Chrome flags/switches not all being passed to Electron. 

You can see in many cases where we fixed a bug by passing a new Chrome flag, then later had to followup to fix another bug in Electron with the same flag. 
- Example of Chrome flag added: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L94
- Example of Electron flag later added: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/environment.js#L59C33-L59C62

We should send the same flags to Electron as we do Chrome.

### Steps to test

- I added some unit tests around the formatting of the flags.
- I added a specific test to ensure that the `navigator.webdriver` is `true` (there is a bug with Webkit honoring this logged [here](https://github.com/cypress-io/cypress/issues/29446)) This test *indirectly* tests that there is an `--enable-automation` flag being passed to Electron, Chrome, and Firefox. So it's not a pure test to ensure our flags are being passed correctly.

### How has the user experience changed?

This should resolve some situations where there's a difference in behavior between the 2 browsers. This may fix some bugs for people in Electron, but it might also introduce 'unwanted' changes in behavior (such as the [original `navigator.webdriver` behavior](https://github.com/cypress-io/cypress/issues/27939) changing which could cause user's applications to no longer load in Electron - although this is the correct behavior)

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/environment.js [hunk 1]
```diff
@@ -43,31 +44,10 @@ try {
...
-  app.commandLine.appendSwitch('disable-dev-shm-usage')
-
-  // prevent navigation throttling when navigating in the browser rapid fire
-  // https://github.com/cypress-io/cypress/pull/20271
-  app.commandLine.appendSwitch('disable-ipc-flooding-protection')
-
-  // ensure we get the most accurate memory usage
-  app.commandLine.appendSwitch('enable-precise-memory-info')
+  DEFAULT_ELECTRON_FLAGS.forEach(({ name, value }) => {
+    debug('appending default switches for electron: %O', DEFAULT_ELECTRON_FLAGS)
```
Comment (mschile) [inline packages/server/lib/environment.js]:
```suggestion
  debug('appending default switches for electron: %O', DEFAULT_ELECTRON_FLAGS) 
  DEFAULT_ELECTRON_FLAGS.forEach(({ name, value }) => {
```

File: packages/server/lib/environment.js [hunk 2]
```diff
@@ -43,31 +44,10 @@ try {
...
+    value ? app.commandLine.appendSwitch(name) : app.commandLine.appendSwitch(name, value)
```
Comment (mschile) [inline packages/server/lib/environment.js]: Isn't this backwards?
```suggestion
    value ? app.commandLine.appendSwitch(name, value) : app.commandLine.appendSwitch(name)
```

**Review by mschile — CHANGES_REQUESTED** [review]
Added a couple comments.

File: packages/server/lib/environment.js (hunk 2 above)
Comment (jennifer-shehane) [reply packages/server/lib/environment.js]: Yes, probably why a better test around this would be good. [`b66fc3d` (#29443)](https://github.com/cypress-io/cypress/pull/29443/commits/b66fc3d2654d5156d2aff4ec4904b5034d9059c7)

File: packages/server/lib/environment.js (hunk 1 above)
Comment (jennifer-shehane) [reply packages/server/lib/environment.js]: Addressed here: [`e7e6cd9` (#29443)](https://github.com/cypress-io/cypress/pull/29443/commits/e7e6cd9ec0b522c47185da4223f8f1c4bc31cd8b)

**Review by mschile — APPROVED** [review]

File: packages/server/test/unit/util/chromium_flags_spec.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
+require('../../spec_helper')
+
+const { formatChromeFlags } = require(`../../../lib/util/chromium_flags`)
+const { formatElectronFlags } = require(`../../../lib/util/chromium_flags`)
```
Comment (AtofStryker) [inline packages/server/test/unit/util/chromium_flags_spec.js]:
```suggestion
const { formatChromeFlags, formatElectronFlags } = require(`../../../lib/util/chromium_flags`)
```

**Review by AtofStryker — APPROVED** [review]
