### PR TITLE
chore: fix cy.location() not retrying chained `its()` then chained `should()` 

### LINKED ISSUE #31841: Failing test in Electron 35/6: Studio
### Link to Cypress Cloud or CircleCI failure

[Test Replay](https://cloud.cypress.io/projects/ypt4pf/runs/63130/overview/44ab215c-3dac-4b20-89fa-2813af000ffd/replay?roarHideRunsWithDiffGroupsAndTags=1&ts=1750263025892.5999&att=1)

### Analysis

Needs analysis

### Cypress Version

15.0.0-pre

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #31841

### Additional details

With the changes to having an async query for `cy.location()`, one of the studio tests was failing due to `cy.location().its('hash').should('contain', 'foo')` was failing. This has to do with the location changing mid navigation, which is accounted for in `cy.location()`m but not in chainers that invoke a retry of the query. This is a problem if `its()` was used as it just grabs the already cached property already and will never update

This change is to make it that the url is refetched if the `cy.location()` query is rerun after fetching the initial value. This way retries off any chainer or even fail handlers are now called to update the object.

This should only be an issue with `cy.location()` from the added commands as it is the only one the yields and object.

### Steps to test

Unit tests have been added. I did not add an e2e test for this change as I am thinking its a bit hard to consistenly do deterministically.

### How has the user experience changed?

Keeps the behavior the same as to what is currently in Cypress 14 to the end user

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by ryanthemanuel — APPROVED** [review]

File: packages/driver/src/cy/commands/helpers/location.ts [hunk 1]
```diff
@@ -59,8 +58,29 @@ export function getUrlFromAutomation (Cypress: Cypress.Cypress, options: Partial
...
+      // In some cases, Cypress will want to retry fetching the url object after it is resolved.
+      // For instance, in the case of the command yielding an object, like cy.location().
+
+      // If cy.location().its('url').should('equal', 'https://www.foobar.com') initially fails the 'should' assertion,
+      // Cypress will want to retry fetching the url object as the onFail handler is NOT called when the subject is chained after 'its'.
+
+      // This does NOT apply if the assertion is chained directly after the command, like cy.location().should('equal', 'https://www.foobar.com').
+      // This examples DOES call the onFail handler and fetching the url will be retried from the context of the onFail handler.
+      if (options?.retryAfterResolve && hasBeenInitiallyResolved) {
+        // tslint:disable-next-line no-floating-promises
```
Comment (cacieprins) [inline packages/driver/src/cy/commands/helpers/location.ts:76]: 😬

**Review by cacieprins — APPROVED** [review]

File: packages/driver/src/cy/commands/helpers/location.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/driver/src/cy/commands/helpers/location.ts:76]: not great, but works without a lot of additional complexity 🤷🏻
