### PR TITLE
fix: ignore dash, underscore and space in search

### LINKED ISSUE #25303: Search should ignore dashes or spaces
### What would you like?

Tests files are often name with "-" or "_" between words like "products-details" or "products_details". Search specs bar should be able to find those when you type "products details".

### Why is this needed?

I want this because it will be a lot easier to find desire specs.

### Other

_No response_

### PR DESCRIPTION
**Pull request by janlengyel**
- Closes #25303

### Additional details
As requested in issue, spec search bar now correctly searches specs, if the search value contains space, but spec name contains dash or underscore.
E.g. User searches "cloud debug", which finds spec "cloud-debug-filter.cy.ts"

### Steps to test
n/a

### How has the user experience changed?
Before
image

After
image

### PR Tasks

- [x] Have tests been added/updated?
- n/a Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- n/a Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/specs/spec-utils.ts [hunk 1]
```diff
@@ -1,14 +1,20 @@
...
 import { FuzzyFoundSpec, getPlatform } from './tree/useCollapsibleTree'
 
 export function fuzzySortSpecs <T extends FuzzyFoundSpec> (specs: T[], searchValue: string) {
-  const normalizedSearchValue = getPlatform() === 'win32' ? searchValue.replaceAll('/', '\\') : searchValue
+  const normalizedSearchValue = normalizeSpecName(searchValue)
+
+  const clonedSpecs = cloneDeep(specs).map((spec) => {
+    return {
+      ...spec,
+      baseName: normalizeSpecName(spec.baseName) }
```
Comment (mschile) [inline packages/app/src/specs/spec-utils.ts]: We will probably want to apply the same normalization logic to the `relative` property so folders are included.

File: packages/app/src/specs/spec-utils.ts [hunk 2]
```diff
@@ -1,14 +1,20 @@
...
 import { ComputedRef, Ref, ref, watch } from 'vue'
-import _ from 'lodash'
+import _, { cloneDeep } from 'lodash'
 import { FuzzyFoundSpec, getPlatform } from './tree/useCollapsibleTree'
 
 export function fuzzySortSpecs <T extends FuzzyFoundSpec> (specs: T[], searchValue: string) {
-  const normalizedSearchValue = getPlatform() === 'win32' ? searchValue.replaceAll('/', '\\') : searchValue
+  const normalizedSearchValue = normalizeSpecName(searchValue)
+
+  const clonedSpecs = cloneDeep(specs).map((spec) => {
```
Comment (mschile) [inline packages/app/src/specs/spec-utils.ts]: Instead of cloning the specs, I think it would make more sense to add two new properties (`normalizedBaseName` and `normalizedRelative`) to `FuzzyFoundSpec` and populate them in the `makeFuzzyFoundSpec` function.

**Review by mschile — CHANGES_REQUESTED** [review]
Hi @janlengyel 👋, thanks for taking the time to open this PR. I've requested changes to expand the normalization logic to the `relative` property as well.

**Review by mschile — APPROVED** [review]

**Review by chrisbreiding — APPROVED** [review]
