### PR TITLE
Issue #6216 -- have .its() receive the number 0 as parameter

### LINKED ISSUE #6216: An Its() function cannot access index of zero.
### Current behavior:

From the tutorial on the official website (https://docs.cypress.io/api/commands/its.html) when I have used with an array following the example I have found an issue of the function. The function could access indices from indices `one` to last indices of the array. However, when I have used the indices `zero` with the function the compiler have an error.

### Desired behavior:

The function have been access by  indices `zero` to the last indices of the example array.

### Test code to reproduce
```js
cy.wrap(['Wai Yan', 'Yu']).its(1).should('eq', 'Yu') // true
cy.wrap(['Wai Yan', 'Yu']).its(0).should('eq', 'Yu') // CypressError: cy.its() expects the propertyName argument to have a value.
```

### Versions

Cypress version (Installed via npm) : 3.8.2
Os: Windows 10

### PR DESCRIPTION
**Pull request by datner**
- Closes #6216 

### User facing changelog

`its()` now supports 0 as a value for indexes or object keys

### Additional details

Many times a developer will intuitively reach for the first item in an array for tests or checks
(or for anything if I'm honest), and until now trying to reach that property using `.its(0)` threw an error.
Now developers world-wide would be able to check the first index of their array in a cypress environment. Well, I'm sure you could still have done it with `.its("0")` but just isn't as cool.

The tests check for edge cases, other than that I didn't do anything unexpected

### How has the user experience changed?
this didn't work, now it does, it's the intuitive thing to do, so it's pretty chill
```javascript
 cy.wrap(["cake","hamburger"]).its(0).should("eq","cake");
```

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 

Is there anything to add to cypress-documentation? This now works as planned, I didn't add any new features to the mental model of how `.its()` operates

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/connectors_spec.coffee [hunk 1]
```diff
@@ -813,6 +813,11 @@ describe "src/cy/commands/connectors", ->
       it "works with numerical indexes", ->
         cy.wrap(['foo', 'bar']).its(1).should('eq', 'bar')
 
+      it "works with 0 as a value if object has property 0", ->
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/connectors_spec.coffee]: add a test for `cy.invoke`, since it uses the same `connectors` logic, `cy.invoke(0)` *should* work too

File: packages/driver/src/cy/commands/connectors.coffee [hunk 2]
```diff
@@ -179,7 +179,8 @@ module.exports = (Commands, Cypress, cy, state, config) ->
         consoleProps: ->
           Subject: subject
 
-    if not str
+    ## check for false positive (negative?) with 0 given as index
+    if not str and str isnt 0
```
Comment (flotwig) [inline packages/driver/src/cy/commands/connectors.coffee]: since this logic is shared between line 256 and this line, move it to a named function for clarity. maybe something like this:

```coffee
isObjectKey = (i) =>
	i or i is 0
```

File: packages/driver/src/cy/commands/connectors.coffee [hunk 3]
```diff
@@ -251,9 +252,12 @@ module.exports = (Commands, Cypress, cy, state, config) ->
       previousProp = pathsArray[index - 1]
       valIsNullOrUndefined = _.isNil(acc)
 
+      ## to allow the falsy value 0 to be used
+      propIsValid = !!prop or prop is 0
```
Comment (flotwig) [inline packages/driver/src/cy/commands/connectors.coffee]: see comment on line 183

**Comment by bahmutov** [comment]
The check for index - what does it do if one passes “-1”? Ughh JavaScript allows so much stuff

**Comment by datner** [comment]
@bahmutov 
I am still waiting for a reply on what to do on that occasion, my guess would be to just ignore it? it'll return undefined every time and thats not an issue, it's reality. Also lets object with the key "-1" still work

**Comment by datner** [comment]
image

Uhhh.. I am not really sure what to do about this.... I used the same computer and user and repo and set up, nothing changed between the commits..?

File: packages/driver/test/cypress/integration/commands/connectors_spec.coffee (hunk 1 above)
Comment (datner) [reply packages/driver/test/cypress/integration/commands/connectors_spec.coffee]: Done

File: packages/driver/src/cy/commands/connectors.coffee (hunk 2 above)
Comment (datner) [reply packages/driver/src/cy/commands/connectors.coffee]: Done

File: packages/driver/src/cy/commands/connectors.coffee (hunk 3 above)
Comment (datner) [reply packages/driver/src/cy/commands/connectors.coffee]: And done.

**Comment by flotwig** [comment]
> Uhhh.. I am not really sure what to do about this.... I used the same computer and user and repo and set up, nothing changed between the commits..?

It looks like you made the first commits with a gmail email address, then you made the last two commits with an email address (contact [at] datner [dot] me) which is not yet linked to your GitHub account.

Add this email to your GitHub account and confirm it, then ask the CLA assistant to retry, it should work once the 2nd email is associated with your GitHub: https://github.com/settings/emails

**Comment by flotwig** [comment]
Thanks!

**Comment by datner** [comment]
> It looks like you made the first commits with a gmail email address, then you made the last two commits with an email address (contact [at] datner [dot] me) which is not yet linked to your GitHub account.
> 

Very odd.. I never used that email for git. But done
