### PR TITLE
test: fix flaky migration test 

### LINKED ISSUE #25377: Flaky test: migrates 2 projects in global mode
### Link to Cypress Cloud or CircleCI failure

[Cloud Link](https://cloud.cypress.io/projects/ypt4pf/analytics/flaky-tests?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22migration.cy.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22e6c80ce8-4c20-8a85-d1d5-98333850f65b%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222022-12-30%22%2C%22endDate%22%3A%222023-01-06%22%7D&viewBy=TEST_CASE)

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/4baad8eb6b2591b8199c2cac48c9f30488915c73/packages/launchpad/cypress/e2e/migration.cy.ts#L84

### Analysis

Looks to be related to the re-execution of the base Migration query, likely due to `toLaunchpad` calls that trigger a refetch of all active queries. We should rely on gql-subscriptions here.

### Cypress Version

12.3.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by ZachJW34**
Closes https://github.com/cypress-io/cypress/issues/25377

### Additional details
Changes how the Migration flow is kicked off. Before, it was invoked when a project was clicked which lead to an initial query loading with `null` values. Now, the query is what kicks off the migration.

Most of the optimizations are around reducing the number of `toLaunchpad` calls the app was making, causing the query to re-execute multiple times.

It was hard to reproduce this failure locally as it seems to be influenced by machine resources. 

### Steps to test
Run the `migrations.cy.ts` e2e test in Launchpad

### How has the user experience changed?
Screenshots show a reduced number of the migration query

Screen Shot 2023-02-01 at 1 26 07 PM

Screen Shot 2023-02-01 at 1 31 21 PM

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/data-context/src/data/ProjectLifecycleManager.ts [hunk 1]
```diff
@@ -103,6 +103,11 @@ export class ProjectLifecycleManager {
 
   async getProjectId (): Promise<string | null> {
     try {
+      // No need to kick off config initialization if we need to migrate
+      if (this.ctx.migration.needsCypressJsonMigration()) {
```
Comment (lmiller1990) [inline packages/data-context/src/data/ProjectLifecycleManager.ts:107]: General question - if the test is only flaky, I wouldn't expect we need to touch production code to fix it. WDYT? Is there any additional risk here? Is the test hitting a scenario that's impossible in prod?

**Review by lmiller1990 — COMMENTED** [review]
Quick question before doing an in depth review

File: packages/data-context/src/data/ProjectLifecycleManager.ts (hunk 1 above)
Comment (lmiller1990) [reply packages/data-context/src/data/ProjectLifecycleManager.ts:107]: Or is this just a general QOL improvement since it's purely optimizations?

File: packages/data-context/src/data/ProjectConfigManager.ts [hunk 2]
```diff
@@ -135,6 +135,12 @@ export class ProjectConfigManager {
           ...loadConfigReply.requires,
           this.configFilePath,
         ])
+
+        // Only call "to{App,Launchpad}" once the config is done loading.
+        // Calling this in a "finally" would trigger this emission for every
+        // call to get the config (which we do a lot)
+        this.options.ctx.emitter.toLaunchpad()
```
Comment (lmiller1990) [inline packages/data-context/src/data/ProjectConfigManager.ts:142]: Nice, I noticed we have a lot of excess gql calls in general, hope we can find a good way to monitor/track these eventually... no idea how other apps handle this, or do they just have lots of requests 🤔 

Nice thing about REST is you are very deliberate about requests - just thinking out loud here, gql sure is nice but man it has some trade-offs (complexity, hard to really know what/when a call is triggered).

**Review by lmiller1990 — APPROVED** [review]
If CI is good this is fine, just some question questions - I'll approve as no to block this for too long, not wanting to spend too much time on flaky fix - quick fix is a good fix

File: packages/data-context/src/data/ProjectLifecycleManager.ts (hunk 1 above)
Comment (ZachJW34) [reply packages/data-context/src/data/ProjectLifecycleManager.ts:107]: I think this test was particularly flaky because it migrated two projects, and the number of queries re-executed was doubled/tripled. Hard to reproduce locally but in slow CI environments I think a call might have been dropped in between states and caused the test to fail.

I don't think there is a fix for this outside touching production code. The number of requeries is a sign we aren't doing something correct so most of the changes was to reduce this behavior.

File: packages/data-context/src/data/ProjectConfigManager.ts (hunk 2 above)
Comment (ZachJW34) [reply packages/data-context/src/data/ProjectConfigManager.ts:142]: I think it all boils down the the `toLaunchpad` calls. This causes every active query to retrigger. If properly designed, we could probably get away with removing this altogether. Or we could rely more heavily on subscriptions to update data.

File: packages/data-context/src/data/ProjectLifecycleManager.ts (hunk 1 above)
Comment (marktnoonan) [reply packages/data-context/src/data/ProjectLifecycleManager.ts:107]: > if the test is only flaky, I wouldn't expect we need to touch production code to fix it. WDYT?

I see this a bit differently, a flaky test is often telling us about non-determinism in the app code that we don't see locally due to different system resources, OS, etc.

File: packages/launchpad/cypress/e2e/migration.cy.ts [hunk 3]
```diff
@@ -82,7 +82,7 @@ function renameSupport (lang: 'js' | 'ts' | 'coffee' = 'js') {
 describe('global mode', () => {
   // TODO: Figure out why it is flaky. Seems to be due to MigrationWizard query being executed multiple times
   // see: https://github.com/cypress-io/cypress/issues/25377
```
Comment (marktnoonan) [inline packages/launchpad/cypress/e2e/migration.cy.ts]:
```suggestion
```

**Review by marktnoonan — APPROVED** [review]
