### PR TITLE
fix: include cypress version in header to anon-collect endpoint 

### LINKED ISSUE #24157: fix: include cypress version in header to anon-collect endpoint
### Current behavior

Calling the `anon-collect` endpoint in `EventCollectorActions.ts` does not include a 'x-cypress-version' header like other cloud endpoints include. 

### Desired behavior

Include a 'x-cypress-version' header when calling the `anon-collect` endpoint in `EventCollectorActions.ts` like other cloud endpoints. 

### Test code to reproduce

The original issue was released here: https://github.com/cypress-io/cypress/pull/23691

Testing this update will require coordinating with the cloud team to verify the header is being captured.

### Cypress Version

10.9.0

### Node version

n/a

### Operating System

n/a

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by warrensplayer**
- Closes https://github.com/cypress-io/cypress/issues/24157

### User facing changelog

n/a

### Additional details

Including a version header was part of the original requirements for the call to the `/anon-collect` endpoint but was not included

### Steps to test

Follow instructions on the PR that implemented this feature.  https://github.com/cypress-io/cypress/pull/23691

### How has the user experience changed?

n/a

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by estrada9166 — APPROVED** [review]
Looks good to me

File: packages/data-context/src/actions/EventCollectorActions.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import type { DataContext } from '..'
 import Debug from 'debug'
 
+const pkg = require('@packages/root')
```
Comment (mike-plummer) [inline packages/data-context/src/actions/EventCollectorActions.ts:4]: I think this is already maintained in the context, so this may be duplicative. Could you do something like:

`'x-cypress-version': (await this.ctx.versions.versionData()).current.version`?

Comment (warrensplayer) [reply packages/data-context/src/actions/EventCollectorActions.ts:4]: I was just following the pattern from `VersionsDataSounce`.  It gets the version this way

**Review by ZachJW34 — APPROVED** [review]
