### PR TITLE
fix cy.its() not awaiting undefined, improve default retry + error handling for cy.its() / cy.invoke()

### LINKED ISSUE #3837: cy.its() no longer waits on undefined
### Current behavior:

`cy.its()` yields `undefined`.

```javascript
cy.window().its('__store__').then((store) => {
    ...
    /* `store` is undefined as value is yielded before my application gets a chance to set `window.__store__ = myStore;` */
});
```

### Desired behavior:
Docs state:

> .its() will automatically retry itself until the property exists on the subject.

https://docs.cypress.io/api/commands/its.html#Assertions

### Steps to reproduce: (app code and test code)

Interestingly, asserting that the yielded property exists resolves this issue:

```javascript
cy.window().its('__store__').should('exist').then((store) => {
    ...
    /* `store` is *not* `undefined` 👌 */
});
```

I suspect all that is required is that the documentation needs to be updated to indicate that by default it will yield `undefined` unless there's a subsequent command that triggers the retry behaviour/state.

### Versions

Cypress 3.2.0
macOS: 10.14.3
Chrome 73

### PR DESCRIPTION
**Pull request by brian-mann**
fixes #3837

### CODE REVIEW

File: packages/driver/src/cy/assertions.coffee [hunk 1]
```diff
@@ -111,6 +111,10 @@ create = (state, queue, retryFn) ->
 
     state("upcomingAssertions", cmds)
 
+    ## we're applying the default assertion in the
+    ## case where there are no upcoming assertion commands
+    isDefaultAssertionErr = cmds.length is 0
```
Comment (Bkucera) [inline packages/driver/src/cy/assertions.coffee]: is this used anywhere?

Comment (brian-mann) [reply packages/driver/src/cy/assertions.coffee]: no - but it could / should / needs to be which is why i sent it in. other assertion code could be refactored to utilize it which would clean up a bunch of other areas
