### PR TITLE
fix: cy.log only shows the first 2 args.

### LINKED ISSUE #16068: Cy.log only logs first 2 parameters when more then 2 are passed
### Current behavior
When passing 2+ parameters to cy.log function only the first 2 are displayed

### Desired behavior
All the passed parameters are logged
In the gist bellow, I am passing 4 strings to cy.log function but only the first 2 are being logged

### Test code to reproduce
link to gist - https://gist.github.com/okyrylenko/190d880dc5ca4b6808d57c5cc29240eb

### Versions

6.8

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #16068

### User facing changelog

`cy.log()` will show all the arguments, not the first 2.

### Additional details
- Why was this change necessary? => `cy.log` didn't behave as the document. 
- What is affected by this change? => N/A
- Any implementation details to explain? => Use `...` operator for the args.

### How has the user experience changed?

**before:**

image

**after:**

Screenshot from 2021-04-28 11-23-28

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/misc_spec.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ describe('src/cy/commands/misc', () => {
         return cy.log('foobarbaz', [{}]).then(function () {
           expect(this.lastLog.invoke('consoleProps')).to.deep.eq({
             Command: 'log',
-            args: [{}],
+            args: [[{}]],
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/misc_spec.js:70]: `args` is now an array, not a value.

**Review by jennifer-shehane — APPROVED** [review]
Looks good. Thanks again @sainthkh 💯
