### PR TITLE
fix: use open instead of connectToNewSpec in electron

### LINKED ISSUE #26900: Cypress crash with "There was an error reconnecting to the Chrome DevTools protocol"
### Current behavior

Cypress in version 12.12 and version 12.13, randomly crash with the following error
```
There was an error reconnecting to the Chrome DevTools protocol.
Please restart the browser.
```
Also reported in stackoverflow [https://stackoverflow.com/questions/76302675/cypress-there-was-an-error-reconnecting-to-the-chrome-devtools-protocol/76371091#76371091] and reproduced by different users.

Resolved downgrading to version 12.11

### Desired behavior

Cypress should not crash

### Test code to reproduce

Any test

### Cypress Version

12.12 / 12.13

### Node version

18.4.0

### Operating System

MacOs 12.5 / Ubuntu 20.04.6 LTS

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #26900

### Additional details

Electron doesn't support multiple tabs/windows so calling `connectToNewSpec` in electron doesn't make sense. This change will call `open` instead which will ensure all the shutdown and startup logic associated with launching a new electron window is properly handled.

### How has the user experience changed?

Potentially shutdown and startup issues are now properly handled.

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/open_project.ts [hunk 1]
```diff
@@ -174,7 +174,9 @@ export class OpenProject {
         return await browsers.connectToExisting(browser, options, automation)
       }
 
-      if (options.shouldLaunchNewTab) {
+      // if we should launch a new tab and we are not running in electron (which does not support connecting to a new spec)
+      // then we can connect to the new spec
+      if (options.shouldLaunchNewTab && browser.name !== 'electron') {
```
Comment (AtofStryker) [inline packages/server/lib/open_project.ts:179]: we might need to check and some tests with https://github.com/cypress-io/cypress/pull/27116 or this (whatever goes in first) to make sure the behavior is expected, but I think the behavior should play nicely together.

**Review by AtofStryker — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
