### PR TITLE
fix: Update visibility check for `position: fixed` combined with `pointer-events: none`

### LINKED ISSUE #6675: `position: fixed` elements having parent with `pointer-events: none` mistakenly display as not visible / covered by another el
### Current behavior:
Hi, 
Currently, when testing out the visibility of `.spinner` for [nprogress](https://ricostacruz.com/nprogress/), it shows as being not visible due to the position being fixed although the spinning circle loader is certainly visible on the page. I'm aware of the complexity of the current algorithm used to determine visibility so I thought this might help give a simple, reproducible example of where this may (if I'm understanding correctly) fail. It says that it's being covered by the html wrapper itself, but the element has a z-index set to 1031.

### Desired behavior:
It should be considered visible as it's not being covered by any element in the DOM.

### Test code to reproduce
https://github.com/josh-byster/cypress-visibility

There is a `visibility.spec.js` which has a basic assertion of visibility in there that should show the issue.
If there's any trouble with reproducibility, it can probably be tested directly at the [nprogress website](https://ricostacruz.com/nprogress/) to check if the spinner is visible.

### Versions

Cypress 4.1.0
Mac OS X Catalina 10.15.3

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-84) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #6675

### User facing changelog

Fixes a bug where `position: fixed` combined with `pointer-events: none` can cause an element to be reported as hidden when it is actually visible

### Additional details

`document.elementFromPoint` ignores elements that have `pointer-events: none`, and gets the element underneath instead. Previously, we would just check that that element was the same element or a descendant of the one we were trying to check. This adds another check if the element is a parent, which covers the case that the click fell through (and due to the other checks beforehand, does not accidentally misreport a hidden element as visible).

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/dom/visibility_spec.ts [hunk 1]
```diff
@@ -289,6 +295,18 @@ describe('src/cypress/dom/visibility', () => {
 <div id="none" style='display: none;'>
   <span>parent display: none</span>
 </div>\
+`)
+
+      this.$parentPointerEventsNone = add(`\
+<div style="pointer-events: none;">
+  <span style="position: fixed; top: 20px;">parent pointer-events: none</span>
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/dom/visibility_spec.ts:302]: Can't tell this HTML from the HTML below it on the page since it's the same content.

```suggestion
  <span style="position: fixed; top: 20px;">parent pointer-events: none; top: 20px</span>
```

File: packages/driver/cypress/integration/dom/visibility_spec.ts [hunk 2]
```diff
@@ -702,6 +720,21 @@ describe('src/cypress/dom/visibility', () => {
...
         expect(this.$parentPosAbs.find('span')).to.not.be.visible
       })
+
+      it('is visible if position: fixed and parent has pointer-events: none', function () {
+        expect(this.$parentPointerEventsNone.find('span')).to.be.visible
+        expect(this.$parentPointerEventsNone.find('span')).to.not.be.hidden
+      })
+
+      it('is not visible if covered when position: fixed and parent has pointer-events: none', function () {
+        expect(this.$parentPointerEventsNoneCovered.find('span')).to.be.hidden
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/dom/visibility_spec.ts:730]: I don't understand why this example is hidden - it seems it's dependent on some HTML structure outside of what's defined in `parentPointerEventsNoneCovered`? This span is visible by itself when I just add this HTML. If it's dependent on some other HTML on the page, it should probably be encapsulated into the DOM example so someone else doesn't change the outside HTML and break this test.

```html
<div style="pointer-events: none;">
  <span style="position: fixed;">parent pointer-events: none</span>
</div>
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Fixes the original issue. 👍  Just had some comments about the tests.

File: packages/driver/cypress/integration/dom/visibility_spec.ts (hunk 2 above)
Comment (panzarino) [reply packages/driver/cypress/integration/dom/visibility_spec.ts:731]: Yeah it was being covered by a different element on the page, I've changed it now so that its entirely self-contained.

File: packages/driver/cypress/integration/dom/visibility_spec.ts (hunk 1 above)
Comment (panzarino) [reply packages/driver/cypress/integration/dom/visibility_spec.ts:302]: Should be updated now with the self-contained covering element.

**Review by jennifer-shehane — APPROVED** [review]
Great! Much clearer now in the tests.

**Comment by jennifer-shehane** [comment]
Ignoring percy visual change as it is a timing issue - the collapsible is not fully opened, so that'll need to be addressed elsewhere.
