### PR TITLE
fix: escape backslashes in downloadFolder for Firefox on Windows #17896

### LINKED ISSUE #17896: Cypress is not downloading files in the cypress/downloads folder on Firefox (Windows)
### Current behavior

Even though I explicitly wrote "downloadsFolder": "cypress/downloads", on my cypress.json file, the files are not being **downloaded inside this default folder** when I am running my tests on **Firefox** locally in both headless and headed.

### Desired behavior

The file should be downloaded inside the default folder, which is cypress/downloads (It is working normally on Chrome and Edge)

### Test code to reproduce

Do it on Firefox (On Chrome based browsers it works):
- Create a test to click in some link/button that will **download a file** (In my case it is a CSV file)
- Observe the file is downloaded, but it is **not being downloaded** in the default **cypress/downloads folder**

### Cypress Version

8.3.0

### Other

- It was observed in both UI and CI mode on **Windows 10 Pro edition**.
- When I run it in my **Bitbucket pipeline** (with **Linux** machines) this issue is not found. Therefore, I believe it is a specific **Windows issue with Firefox** and so the file is not downloaded in the default **cypress/downloads folder**.

### PR DESCRIPTION
**Pull request by mirobo**
- Closes #17896

### User facing changelog
n/a

### Steps to test
- Clear Firefox Cypress profile (important!.. a correct folder path may have been set there..)
- In https://github.com/mirobo/cypress-fiddle/blob/main/cypress/plugins/index.js remove the workaround for downloadDir
- Start the test firefox-download.spec.js that downloads a file (doesnt assert anything).. you'll see the wrong folder. Activate workaround and it works. Tested it briefly by changing the JS-file in the Cypress app dir directly.

### How has the user experience changed?
no

### PR Tasks
- [ ] Have tests been added/updated? _No, there aren't any tests at all.._
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/firefox.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import getPort from 'get-port'
 import path from 'path'
 import urlUtil from 'url'
 import { debug as launcherDebug, launch, LaunchedBrowser } from '@packages/launcher/lib/browsers'
+import { doubleEscape } from '@packages/launcher/lib/windows/index'
```
Comment (AtofStryker) [inline packages/server/lib/browsers/firefox.ts:9]:
```suggestion
import { doubleEscape } from '@packages/launcher/lib/windows'
```

**Review by AtofStryker — CHANGES_REQUESTED** [review]
Hey @mirobo. Thanks for submitting this pull request to fix your issue! Would you be able to add a test in `firefox_spec.ts` that covers the expected behavior? The existing tests should give a good base for adding the `downloadsFolder` to the options and you should be able to stub out the `os.platform` similar to some of the tests in the [launcher](https://github.com/cypress-io/cypress/blob/develop/packages/launcher/test/unit/windows_spec.ts#L101).

**Comment by mirobo** [comment]
> Hey @mirobo. Thanks for submitting this pull request to fix your issue! Would you be able to add a test in `firefox_spec.ts` that covers the expected behavior? The existing tests should give a good base for adding the `downloadsFolder` to the options and you should be able to stub out the `os.platform` similar to some of the tests in the [launcher](https://github.com/cypress-io/cypress/blob/develop/packages/launcher/test/unit/windows_spec.ts#L101).

I'd like to but there are some big issues for me
1) The build on develop has so many failures that didn't have anything to do with my changes and it's hard to figure out what actually went wrong. I merged like 4 times and the build still isn't green. Since the downloadFolder wasn't tested yet, this change should produce a green build. If the import is not working, the build should show me this somehow. I'm occupying resources with those builds that produce almost only failures..

2) I cannot even start Cypress in development mode with "yarn start". It will start the Cypress window with the message "Not Found". I've run "yarn clean" but it doesn't help. Some of the system-tests actually require a binary which I cannot build on Windows because of commands like "ls -al" in one of the build scripts. I'd be happy to contribute more if local Cypress development would actually work.. shouldn't be that hard..

I'm in timezone GMT+1 (but can also get up during the night) if there is any possibility of a "Cypress development setup fixing session"..

**Comment by AtofStryker** [comment]
> I'd like to but there are some big issues for me
> 
> 1. The build on develop has so many failures that didn't have anything to do with my changes and it's hard to figure out what actually went wrong. I merged like 4 times and the build still isn't green. Since the downloadFolder wasn't tested yet, this change should produce a green build. If the import is not working, the build should show me this somehow. I'm occupying resources with those builds that produce almost only failures..

We currently have some flake occurring in the build, to the point where getting a green build on a first time run is extremely rare. This obviously isn't great, but the good news is we are starting to address the flake this week and hopefully get ourselves to greener builds in the near future 😄 . 

> 2. I cannot even start Cypress in development mode with "yarn start". It will start the Cypress window with the message "Not Found". I've run "yarn clean" but it doesn't help. Some of the system-tests actually require a binary which I cannot build on Windows because of commands like "ls -al" in one of the build scripts. I'd be happy to contribute more if local Cypress development would actually work.. shouldn't be that hard..

Interesting. I wonder if there are issues running in global mode on Windows. What version of Windows are you developing on and have you followed all the windows instructions in the [contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started)? Just want to make sure we can rule some things out. Might be good to try `yarn` then run some of the driver tests via `yarn workspace @packages/driver cypress:open` and see if you get the same issues?

The good news to write server unit tests is they are run with mocha inside a node context, and you can run those in the package directory. To test this, you could right something like:

```
it.only('runs my test, () => {
    expect(true).to.be.true
})
```

you can change directories to `packages/server` and run `yarn test-unit firefox_spec` and you should see only your test executed in the console. Then you can implement your test. I took a quick look and think it might be difficult to assert on the profile, so my guess is it will look something like this:

```
    it('escapes the downloadsFolders path correctly when running in windows', function () {
      this.options.proxyServer = 'http://proxy-server:1234'
      this.options.downloadsFolder = 'C:/Users/test/Downloads/My Test Downloads Folder'
      sinon.stub(os, 'platform').resolves('win32')
      const executeBeforeBrowserLaunchSpy = sinon.spy(utils, 'executeBeforeBrowserLaunch')

      return firefox.open(this.browser, 'http://', this.options, this.automation).then(() => {
        expect(executeBeforeBrowserLaunchSpy).to.have.been.calledWith(this.browser, sinon.match({
          preferences: {
            'browser.download.dir': 'THE_EXPECTED_PATH',
          },
        }), this.options)
      })
    })
```

> I'm in timezone GMT+1 (but can also get up during the night) if there is any possibility of a "Cypress development setup fixing session"..

Hopefully I can provide enough guidance on the thread to get you going 😄 . I have a windows 10 instance so if you are running into issues I can see if I can reproduce or provide a solution.

**Comment by mirobo** [comment]
> > 3\. I cannot even start Cypress in development mode with "yarn start". It will start the Cypress window with the message "Not Found". I've run "yarn clean" but it doesn't help. Some of the system-tests actually require a binary which I cannot build on Windows because of commands like "ls -al" in one of the build scripts. I'd be happy to contribute more if local Cypress development would actually work.. shouldn't be that hard..
> 
> Interesting. I wonder if there are issues running in global mode on Windows. What version of Windows are you developing on and have you followed all the windows instructions in the [contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started)? Just want to make sure we can rule some things out. Might be good to try `yarn` then run some of the driver tests via `yarn workspace @packages/driver cypress:open` and see if you get the same issues?

Yes, I followed the guide

NPM 8.11.0
Node 16.16.0 (also tried with 16.14.2)
Yarn: v1.22.19

In scripts\binary\build.ts I commented out this because it will never run in Windows:
```
  const { stdout } = await execa('ls', ['-la', meta.buildDir()])
  console.log(stdout)
```

I added CYPRESS_INTERNAL_VITE_DEV=1 to .npmrc

When running "yarn" the script just continues and you wouldn't even see the following error (I googled a lot regarding this error and I couldn't find any solution):

```
yarn run v1.22.19
$ C:\Dev\mirobo\cypress\node_modules\.bin\vite build --outDir dist
$ C:\Dev\mirobo\cypress\node_modules\.bin\vite build --outDir dist
[vite:build-app:34748]: failed to load config from C:\Dev\mirobo\cypress\packages\app\vite.config.mjs
[vite:build-app:34748]: error during build:
[vite:build-app:34748]: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[vite:build-app:34748]:     at new NodeError (node:internal/errors:372:5)
[vite:build-app:34748]:     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
[vite:build-app:34748]:     at defaultResolve (node:internal/modules/esm/resolve:1200:3)
[vite:build-app:34748]:     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
[vite:build-app:34748]:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
[vite:build-app:34748]:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
[vite:build-app:34748]:     at link (node:internal/modules/esm/module_job:78:36)
[vite:build-launchpad:27192]: failed to load config from C:\Dev\mirobo\cypress\packages\launchpad\vite.config.mjs
[vite:build-launchpad:27192]: error during build:
[vite:build-launchpad:27192]: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[vite:build-launchpad:27192]:     at new NodeError (node:internal/errors:372:5)
[vite:build-launchpad:27192]:     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
[vite:build-launchpad:27192]:     at defaultResolve (node:internal/modules/esm/resolve:1200:3)
[vite:build-launchpad:27192]:     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
[vite:build-launchpad:27192]:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
[vite:build-launchpad:27192]:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
[vite:build-launchpad:27192]:     at link (node:internal/modules/esm/module_job:78:36)

```

This failure is probably why Cypress only shows "not found". The launchpad-server itself is running and it also shows "not found" when I open the URL in a normal browser.

I also added this script to packages/launchpad/package.json to quickly start the vite build.. 
"build-dev": "vite build --mode development --minify false --watch",
..it shows the same error.

When running "yarn check --integrity", everything is fine but running "yarn check" gives me 32 errors.. can't be true that there are so many discrepancies after running yarn?

```
PS C:\Dev\mirobo\cypress> yarn check
yarn check v1.22.19
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
warning Resolution field "@typescript-eslint/eslint-plugin@4.18.0" is incompatible with requested version "@typescript-eslint/eslint-plugin@^2.2.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^27.0.2"
warning Pattern ["source-map@0.7.3"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-source-map-fast-0.7.3-5302f8169031735226544092e64981f751750383-integrity\\node_modules\\source-map-fast" as pattern ["source-map@^0.7.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["source-map@~0.7.2"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-source-map-fast-0.7.3-5302f8169031735226544092e64981f751750383-integrity\\node_modules\\source-map-fast" as pattern ["source-map@^0.7.3"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@definitelytyped/typescript-versions@latest"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@definitelytyped-typescript-versions-0.0.71-08c791e3bf3c2861611edee8f28c72d2db0fb02e-integrity\\node_modules\\@definitelytyped\\typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.71","@definitelytyped/typescript-versions@^0.0.71","@definitelytyped/typescript-versions@^0.0.71"]. This could result in non-deterministic behavior, skipping.
warning nuclide-format-js@0.0.36: The engine "atom" appears to be invalid.
warning Workspaces can only be enabled in private projects.
warning "@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@babel/preset-typescript##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@npmcli/run-script##@npmcli/node-gyp@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\node-gyp@2.0.0"
error "@vitejs/plugin-vue##vite@^2.5.10" doesn't satisfy found match of "vite@3.0.3"
warning "pacote#@npmcli/git@^3.0.0" could be deduped from "3.0.1" to "@npmcli\\git@3.0.1"
error "@percy/cypress##cypress@>=3" doesn't satisfy found match of "cypress@0.0.0-development"
error "@semantic-release/changelog##semantic-release@>=15.8.0 <18.0.0" doesn't satisfy found match of "semantic-release@19.0.3"
error "@semantic-release/git##semantic-release@>=16.0.0 <18.0.0" doesn't satisfy found match of "semantic-release@19.0.3"
error "@cypress/schematic#@angular-devkit/core##source-map@0.7.3" doesn't satisfy found match of "source-map@0.6.1"
warning "cypress#@types/chai-jquery##@types/chai@*" could be deduped from "4.2.15" to "@types\\chai@4.2.15"
warning "cypress#@types/chai-jquery##@types/jquery@*" could be deduped from "3.3.31" to "@types\\jquery@3.3.31"
warning "cypress#@types/jquery##@types/sizzle@*" could be deduped from "2.3.2" to "@types\\sizzle@2.3.2"
warning "cypress#@types/sinon-chai##@types/chai@*" could be deduped from "4.2.15" to "@types\\chai@4.2.15"
warning "cypress#@types/sinon##@types/sinonjs__fake-timers@*" could be deduped from "8.1.1" to "@types\\sinonjs__fake-timers@8.1.1"
error "@types/webpack#@types/webpack-sources##source-map@^0.7.3" doesn't satisfy found match of "source-map@0.6.1"
warning "@typescript-eslint/parser#@typescript-eslint/typescript-estree##@typescript-eslint/visitor-keys@4.18.0" could be deduped from "4.18.0" to "@typescript-eslint\\visitor-keys@4.18.0"
warning "pacote#cacache#@npmcli/move-file@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\move-file@2.0.0"
warning "@packages/driver#express##body-parser@1.19.0" could be deduped from "1.19.0" to "body-parser@1.19.0"
warning "@packages/driver#express##methods@~1.1.2" could be deduped from "1.1.2" to "methods@1.1.2"
warning "@packages/driver#method-override##methods@~1.1.2" could be deduped from "1.1.2" to "methods@1.1.2"
warning "@packages/rewriter#parse5-html-rewriting-stream##parse5@^5.1.1" could be deduped from "5.1.1" to "parse5@5.1.1"
warning Resolution field "@typescript-eslint\\eslint-plugin@4.18.0" is incompatible with requested version "@cypress/webpack-preprocessor#react-scripts#@typescript-eslint/eslint-plugin@^2.2.0"
warning "@cypress/webpack-preprocessor#react-scripts#babel-jest@^24.9.0" could be deduped from "24.9.0" to "babel-jest@24.9.0"
warning "@cypress/webpack-preprocessor#react-scripts#jest@24.9.0" could be deduped from "24.9.0" to "jest@24.9.0"
error "c8#v8-to-istanbul#source-map@^0.7.3" doesn't satisfy found match of "source-map@0.6.1"
warning "@packages/ui-components#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/ui-components#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/plugin-proposal-object-rest-spread##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@babel/preset-react#@babel/plugin-transform-react-jsx-development##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@babel/preset-react#@babel/plugin-transform-react-jsx##@babel/plugin-syntax-jsx@^7.16.7" could be deduped from "7.16.7" to "@babel\\plugin-syntax-jsx@7.16.7"
warning "@babel/preset-react#@babel/plugin-transform-react-jsx##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/server#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/ui-components#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@tooling/system-tests#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/ui-components#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/register##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
error "@cypress/vue#@cypress/code-coverage##cypress@*" doesn't satisfy found match of "cypress@0.0.0-development"
warning "@packages/reporter#@cypress/react-tooltip##prop-types@^15.7.2" could be deduped from "15.8.1" to "prop-types@15.8.1"
warning "@packages/runner-ct#@cypress/react-tooltip##prop-types@^15.7.2" could be deduped from "15.8.1" to "prop-types@15.8.1"
error "@packages/app#@intlify/vite-plugin-vue-i18n##vite@^2.3.6" doesn't satisfy found match of "vite@3.0.3"
error "@packages/app#@intlify/vite-plugin-vue-i18n##vue-i18n@^9.1.6" doesn't satisfy found match of "vue-i18n@9.2.0-beta.7"
error "@packages/app#@testing-library/cypress##cypress@^2.1.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0" doesn't satisfy found match of "cypress@0.0.0-development"
error "@cypress/vue#@vitejs/plugin-vue##vite@^2.5.10" doesn't satisfy found match of "vite@3.0.3"
error "@packages/frontend-shared#cypress-axe#cypress@^3 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9" doesn't satisfy found match of "cypress@0.0.0-development"
warning "@packages/driver#cypress-multi-reporters##debug@^4.1.1" could be deduped from "4.3.4" to "debug@4.3.4"
warning "@packages/driver#cypress-multi-reporters##lodash@^4.17.15" could be deduped from "4.17.21" to "lodash@4.17.21"
error "@packages/app#cypress-real-events#cypress@^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x" doesn't satisfy found match of "cypress@0.0.0-development"
error "@packages/frontend-shared#graphql-relay#graphql@^15.5.3" doesn't satisfy found match of "graphql@15.5.1"
error "@packages/driver#react-dom-15.6.1##react@^15.6.1" doesn't satisfy found match of "react@16.8.6"
error "enzyme-adapter-react-16#react-test-renderer#react@^16.14.0" doesn't satisfy found match of "react@16.8.6"
warning "@packages/extension#ts-loader##webpack@*" could be deduped from "4.46.0" to "webpack@4.46.0"
error "@packages/app#unplugin-icons#@svgr/core@>=5.5.0" doesn't satisfy found match of "@svgr\\core@4.3.3"
error "@packages/app#vite-plugin-components#vite@^2.0.0-beta.69" doesn't satisfy found match of "vite@3.0.3"
error "@cypress/vite-dev-server#vite-plugin-inspect#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
error "@packages/launchpad#vite-plugin-optimize-persist#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
error "@packages/launchpad#vite-plugin-package-config#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
error "@packages/app#vite-plugin-vue-layouts#vite@^2.5.0" doesn't satisfy found match of "vite@3.0.3"
error "@packages/app#vite#terser@^5.4.0" doesn't satisfy found match of "terser@4.8.0"
error "@packages/driver#vite##terser@^5.4.0" doesn't satisfy found match of "terser@4.8.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@testing-library/cypress#@testing-library/dom##pretty-format@^27.0.2"
warning "@packages/rewriter#@types/parse5-html-rewriting-stream#@types/parse5-sax-parser##@types/parse5@*" could be deduped from "5.0.3" to "@types\\parse5@5.0.3"
warning "cypress#@types/sinon-chai#@types/sinon##@types/sinonjs__fake-timers@*" could be deduped from "8.1.1" to "@types\\sinonjs__fake-timers@8.1.1"
warning "@typescript-eslint/experimental-utils#@typescript-eslint/typescript-estree##@typescript-eslint/visitor-keys@4.18.0" could be deduped from "4.18.0" to "@typescript-eslint\\visitor-keys@4.18.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-cli#jest-config#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-cli#jest-config##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-cli#jest-validate#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-cli#jest-validate##pretty-format@^24.9.0"
warning "@semantic-release/npm#npm#@isaacs/string-locale-compare@^1.1.0" could be deduped from "1.1.0" to "@isaacs\\string-locale-compare@1.1.0"
warning "@semantic-release/npm#npm#@npmcli/arborist@^5.0.4" could be deduped from "5.2.1" to "@npmcli\\arborist@5.2.1"
warning "@semantic-release/npm#npm#@npmcli/ci-detect@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\ci-detect@2.0.0"
warning "@semantic-release/npm#npm#@npmcli/config@^4.1.0" could be deduped from "4.1.0" to "@npmcli\\config@4.1.0"
warning "@semantic-release/npm#npm#@npmcli/fs@^2.1.0" could be deduped from "2.1.0" to "@npmcli\\fs@2.1.0"
warning "@semantic-release/npm#npm#@npmcli/map-workspaces@^2.0.3" could be deduped from "2.0.3" to "@npmcli\\map-workspaces@2.0.3"
warning "@semantic-release/npm#npm#@npmcli/package-json@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\package-json@2.0.0"
warning "@semantic-release/npm#npm#@npmcli/run-script@^3.0.1" could be deduped from "3.0.3" to "@npmcli\\run-script@3.0.3"
warning "@semantic-release/npm#npm#abbrev@~1.1.1" could be deduped from "1.1.1" to "abbrev@1.1.1"
warning "@semantic-release/npm#npm#archy@~1.0.0" could be deduped from "1.0.0" to "archy@1.0.0"
warning "@semantic-release/npm#npm#chownr@^2.0.0" could be deduped from "2.0.0" to "chownr@2.0.0"
warning "@semantic-release/npm#npm#cli-columns@^4.0.0" could be deduped from "4.0.0" to "cli-columns@4.0.0"
warning "@semantic-release/npm#npm#cli-table3@^0.6.2" could be deduped from "0.6.2" to "cli-table3@0.6.2"
warning "@semantic-release/npm#npm#columnify@^1.6.0" could be deduped from "1.6.0" to "columnify@1.6.0"
warning "@semantic-release/npm#npm#fastest-levenshtein@^1.0.12" could be deduped from "1.0.12" to "fastest-levenshtein@1.0.12"
warning "@semantic-release/npm#npm#graceful-fs@^4.2.10" could be deduped from "4.2.10" to "graceful-fs@4.2.10"
warning "@semantic-release/npm#npm#is-cidr@^4.0.2" could be deduped from "4.0.2" to "is-cidr@4.0.2"
warning "@semantic-release/npm#npm#json-parse-even-better-errors@^2.3.1" could be deduped from "2.3.1" to "json-parse-even-better-errors@2.3.1"
warning "@semantic-release/npm#npm#libnpmaccess@^6.0.2" could be deduped from "6.0.3" to "libnpmaccess@6.0.3"
warning "@semantic-release/npm#npm#libnpmdiff@^4.0.2" could be deduped from "4.0.3" to "libnpmdiff@4.0.3"
warning "@semantic-release/npm#npm#libnpmexec@^4.0.2" could be deduped from "4.0.6" to "libnpmexec@4.0.6"
warning "@semantic-release/npm#npm#libnpmfund@^3.0.1" could be deduped from "3.0.2" to "libnpmfund@3.0.2"
warning "@semantic-release/npm#npm#libnpmhook@^8.0.2" could be deduped from "8.0.3" to "libnpmhook@8.0.3"
warning "@semantic-release/npm#npm#libnpmorg@^4.0.2" could be deduped from "4.0.3" to "libnpmorg@4.0.3"
warning "@semantic-release/npm#npm#libnpmpack@^4.0.2" could be deduped from "4.1.0" to "libnpmpack@4.1.0"
warning "@semantic-release/npm#npm#libnpmpublish@^6.0.2" could be deduped from "6.0.4" to "libnpmpublish@6.0.4"
warning "@semantic-release/npm#npm#libnpmsearch@^5.0.2" could be deduped from "5.0.3" to "libnpmsearch@5.0.3"
warning "@semantic-release/npm#npm#libnpmteam@^4.0.2" could be deduped from "4.0.3" to "libnpmteam@4.0.3"
warning "@semantic-release/npm#npm#libnpmversion@^3.0.1" could be deduped from "3.0.4" to "libnpmversion@3.0.4"
warning "@semantic-release/npm#npm#make-fetch-happen@^10.1.6" could be deduped from "10.1.7" to "make-fetch-happen@10.1.7"
warning "@semantic-release/npm#npm#minipass@^3.1.6" could be deduped from "3.1.6" to "minipass@3.1.6"
warning "@semantic-release/npm#npm#minipass-pipeline@^1.2.4" could be deduped from "1.2.4" to "minipass-pipeline@1.2.4"
warning "@semantic-release/npm#npm#mkdirp-infer-owner@^2.0.0" could be deduped from "2.0.0" to "mkdirp-infer-owner@2.0.0"
warning "@semantic-release/npm#npm#ms@^2.1.2" could be deduped from "2.1.3" to "ms@2.1.3"
warning "@semantic-release/npm#npm#nopt@^5.0.0" could be deduped from "5.0.0" to "nopt@5.0.0"
warning "@semantic-release/npm#npm#npm-audit-report@^3.0.0" could be deduped from "3.0.0" to "npm-audit-report@3.0.0"
warning "@semantic-release/npm#npm#npm-install-checks@^5.0.0" could be deduped from "5.0.0" to "npm-install-checks@5.0.0"
warning "@semantic-release/npm#npm#npm-pick-manifest@^7.0.1" could be deduped from "7.0.1" to "npm-pick-manifest@7.0.1"
warning "@semantic-release/npm#npm#npm-profile@^6.0.3" could be deduped from "6.0.3" to "npm-profile@6.0.3"
warning "@semantic-release/npm#npm#npm-registry-fetch@^13.1.1" could be deduped from "13.1.1" to "npm-registry-fetch@13.1.1"
warning "@semantic-release/npm#npm#npm-user-validate@^1.0.1" could be deduped from "1.0.1" to "npm-user-validate@1.0.1"
warning "@semantic-release/npm#npm#opener@^1.5.2" could be deduped from "1.5.2" to "opener@1.5.2"
warning "@semantic-release/npm#npm#pacote@^13.6.0" could be deduped from "13.6.0" to "pacote@13.6.0"
warning "@semantic-release/npm#npm#parse-conflict-json@^2.0.2" could be deduped from "2.0.2" to "parse-conflict-json@2.0.2"
warning "@semantic-release/npm#npm#proc-log@^2.0.1" could be deduped from "2.0.1" to "proc-log@2.0.1"
warning "@semantic-release/npm#npm#qrcode-terminal@^0.12.0" could be deduped from "0.12.0" to "qrcode-terminal@0.12.0"
warning "@semantic-release/npm#npm#read@~1.0.7" could be deduped from "1.0.7" to "read@1.0.7"
warning "@semantic-release/npm#npm#read-package-json-fast@^2.0.3" could be deduped from "2.0.3" to "read-package-json-fast@2.0.3"
warning "@semantic-release/npm#npm#readdir-scoped-modules@^1.1.0" could be deduped from "1.1.0" to "readdir-scoped-modules@1.1.0"
warning "@semantic-release/npm#npm#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
warning "@semantic-release/npm#npm#ssri@^9.0.1" could be deduped from "9.0.1" to "ssri@9.0.1"
warning "@semantic-release/npm#npm#tar@^6.1.11" could be deduped from "6.1.11" to "tar@6.1.11"
warning "@semantic-release/npm#npm#text-table@~0.2.0" could be deduped from "0.2.0" to "text-table@0.2.0"
warning "@semantic-release/npm#npm#tiny-relative-date@^1.3.0" could be deduped from "1.3.0" to "tiny-relative-date@1.3.0"
warning "@semantic-release/npm#npm#treeverse@^2.0.0" could be deduped from "2.0.0" to "treeverse@2.0.0"
warning "@packages/rewriter#parse5-html-rewriting-stream#parse5-sax-parser##parse5@^5.1.1" could be deduped from "5.1.1" to "parse5@5.1.1"
warning "@packages/ui-components#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@packages/web-config#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@vitejs/plugin-react#@babel/plugin-transform-react-jsx-self##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@vitejs/plugin-react#@babel/plugin-transform-react-jsx-source##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@graphql-codegen/cli#graphql-config#@endemolshinegroup/cosmiconfig-typescript-loader##cosmiconfig@>=6" could be deduped from "7.0.1" to "@graphql-codegen\\cli#cosmiconfig@7.0.1"
warning "react-scripts#babel-eslint#eslint@>= 4.12.1" could be deduped from "7.22.0" to "eslint@7.22.0"
warning "react-scripts#babel-jest#babel-preset-jest@^24.9.0" could be deduped from "24.9.0" to "babel-preset-jest@24.9.0"
warning "react-scripts#babel-loader#@babel/core@^7.0.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "react-scripts#babel-loader#webpack@>=2" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#babel-plugin-named-asset-import#@babel/core@^7.1.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning Resolution field "@typescript-eslint\\eslint-plugin@4.18.0" is incompatible with requested version "react-scripts#eslint-config-react-app#@typescript-eslint/eslint-plugin@2.x"
warning "react-scripts#eslint-config-react-app#babel-eslint@10.x" could be deduped from "10.1.0" to "babel-eslint@10.1.0"
warning "react-scripts#eslint-config-react-app#eslint-plugin-import@2.x" could be deduped from "2.25.4" to "eslint-plugin-import@2.25.4"
warning "react-scripts#eslint-config-react-app#eslint-plugin-react@7.x" could be deduped from "7.22.0" to "eslint-plugin-react@7.22.0"
warning "react-scripts#eslint-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#eslint-plugin-flowtype#eslint@>=5.0.0" could be deduped from "7.22.0" to "eslint@7.22.0"
warning "react-scripts#file-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#html-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#mini-css-extract-plugin#webpack@^4.4.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#optimize-css-assets-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#sass-loader#webpack@^3.0.0 || ^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#style-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#terser-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
error "unplugin-vue-components#unplugin#vite@^2.3.0" doesn't satisfy found match of "vite@3.0.3"
error "unplugin-icons#unplugin#vite@^2.3.0" doesn't satisfy found match of "vite@3.0.3"
warning "react-scripts#url-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
error "@cypress-design/css#vite-plugin-windicss#vite@^2.0.1" doesn't satisfy found match of "vite@3.0.3"
warning "react-scripts#webpack-dev-server#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#webpack-manifest-plugin#webpack@2 || 3 || 4" could be deduped from "4.46.0" to "webpack@4.46.0"
warning "react-scripts#workbox-webpack-plugin#webpack@^2.0.0 || ^3.0.0 || ^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
error "npm#cacache" is wrong version: expected "16.1.1", got "16.1.0"
warning "npm#cacache#@npmcli/fs@^2.1.0" could be deduped from "2.1.0" to "@npmcli\\fs@2.1.0"
warning "npm#cacache#@npmcli/move-file@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\move-file@2.0.0"
warning "npm#cacache#chownr@^2.0.0" could be deduped from "2.0.0" to "chownr@2.0.0"
warning "npm#cacache#fs-minipass@^2.1.0" could be deduped from "2.1.0" to "fs-minipass@2.1.0"
warning "npm#cacache#infer-owner@^1.0.4" could be deduped from "1.0.4" to "infer-owner@1.0.4"
warning "npm#cacache#minipass@^3.1.6" could be deduped from "3.1.6" to "minipass@3.1.6"
warning "npm#cacache#minipass-collect@^1.0.2" could be deduped from "1.0.2" to "minipass-collect@1.0.2"
warning "npm#cacache#minipass-flush@^1.0.5" could be deduped from "1.0.5" to "minipass-flush@1.0.5"
warning "npm#cacache#minipass-pipeline@^1.2.4" could be deduped from "1.2.4" to "minipass-pipeline@1.2.4"
warning "npm#cacache#promise-inflight@^1.0.1" could be deduped from "1.0.1" to "promise-inflight@1.0.1"
warning "npm#cacache#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
warning "npm#cacache#ssri@^9.0.0" could be deduped from "9.0.1" to "ssri@9.0.1"
warning "npm#cacache#tar@^6.1.11" could be deduped from "6.1.11" to "tar@6.1.11"
warning "npm#cacache#unique-filename@^1.1.1" could be deduped from "1.1.1" to "unique-filename@1.1.1"
warning "npm#chalk#ansi-styles@^4.1.0" could be deduped from "4.3.0" to "ansi-styles@4.3.0"
warning "npm#glob#fs.realpath@^1.0.0" could be deduped from "1.0.0" to "fs.realpath@1.0.0"
warning "npm#glob#inflight@^1.0.4" could be deduped from "1.0.6" to "inflight@1.0.6"
warning "npm#glob#inherits@2" could be deduped from "2.0.4" to "inherits@2.0.4"
warning "npm#glob#once@^1.3.0" could be deduped from "1.4.0" to "once@1.4.0"
warning "npm#init-package-json#promzard@^0.3.0" could be deduped from "0.3.0" to "promzard@0.3.0"
warning "npm#init-package-json#read@^1.0.7" could be deduped from "1.0.7" to "read@1.0.7"
warning "npm#init-package-json#validate-npm-package-license@^3.0.4" could be deduped from "3.0.4" to "validate-npm-package-license@3.0.4"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-config##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-config#jest-jasmine2#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-config#jest-jasmine2##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-validate##pretty-format@^24.9.0"
warning "npm#node-gyp#graceful-fs@^4.2.6" could be deduped from "4.2.10" to "graceful-fs@4.2.10"
warning "npm#node-gyp#make-fetch-happen@^10.0.3" could be deduped from "10.1.7" to "make-fetch-happen@10.1.7"
warning "npm#node-gyp#nopt@^5.0.0" could be deduped from "5.0.0" to "nopt@5.0.0"
warning "npm#node-gyp#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
warning "npm#node-gyp#tar@^6.1.2" could be deduped from "6.1.11" to "tar@6.1.11"
warning "npm#npmlog#console-control-strings@^1.1.0" could be deduped from "1.1.0" to "console-control-strings@1.1.0"
warning "npm#npmlog#set-blocking@^2.0.0" could be deduped from "2.0.0" to "set-blocking@2.0.0"
warning "npm#read-package-json#json-parse-even-better-errors@^2.3.1" could be deduped from "2.3.1" to "json-parse-even-better-errors@2.3.1"
warning "npm#read-package-json#npm-normalize-package-bin@^1.0.1" could be deduped from "1.0.1" to "npm-normalize-package-bin@1.0.1"
error "@cypress/webpack-dev-server#html-webpack-plugin-5#html-minifier-terser#terser##source-map@~0.7.2" doesn't satisfy found match of "source-map@0.6.1"
warning "npm#which#isexe@^2.0.0" could be deduped from "2.0.0" to "isexe@2.0.0"
warning "npm#write-file-atomic#imurmurhash@^0.1.4" could be deduped from "0.1.4" to "imurmurhash@0.1.4"
warning "npm#write-file-atomic#signal-exit@^3.0.7" could be deduped from "3.0.7" to "signal-exit@3.0.7"
warning "@cypress/browserify-preprocessor#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-proposal-numeric-separator##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@cypress/browserify-preprocessor#@babel/plugin-proposal-object-rest-spread##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-proposal-optional-chaining##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-transform-flow-strip-types##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@cypress/browserify-preprocessor#@babel/plugin-transform-runtime##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/plugin-transform-runtime##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@cypress/browserify-preprocessor#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@cypress/browserify-preprocessor#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "react-scripts#@typescript-eslint/parser#@typescript-eslint/experimental-utils##eslint@*" could be deduped from "7.22.0" to "eslint@7.22.0"
error "react-scripts#babel-jest#babel-preset-jest" not installed
warning "@cypress/browserify-preprocessor#babelify##@babel/core@^7.0.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "npm#npmlog#are-we-there-yet#delegates@^1.0.0" could be deduped from "1.0.0" to "delegates@1.0.0"
warning "npm#npmlog#gauge#aproba@^1.0.3 || ^2.0.0" could be deduped from "2.0.0" to "aproba@2.0.0"
warning "npm#npmlog#gauge#color-support@^1.1.3" could be deduped from "1.1.3" to "color-support@1.1.3"
warning "npm#npmlog#gauge#console-control-strings@^1.1.0" could be deduped from "1.1.0" to "console-control-strings@1.1.0"
warning "npm#npmlog#gauge#has-unicode@^2.0.1" could be deduped from "2.0.1" to "has-unicode@2.0.1"
warning "npm#npmlog#gauge#signal-exit@^3.0.7" could be deduped from "3.0.7" to "signal-exit@3.0.7"
warning "npm#npmlog#gauge#string-width@^4.2.3" could be deduped from "4.2.3" to "string-width@4.2.3"
warning "npm#node-gyp#glob#fs.realpath@^1.0.0" could be deduped from "1.0.0" to "fs.realpath@1.0.0"
warning "npm#node-gyp#glob#inflight@^1.0.4" could be deduped from "1.0.6" to "inflight@1.0.6"
warning "npm#node-gyp#glob#inherits@2" could be deduped from "2.0.4" to "inherits@2.0.4"
warning "npm#node-gyp#glob#once@^1.3.0" could be deduped from "1.4.0" to "once@1.4.0"
warning "npm#node-gyp#glob#path-is-absolute@^1.0.0" could be deduped from "1.0.1" to "path-is-absolute@1.0.1"
warning "react-scripts#jest-cli#jest-config#babel-jest@^24.9.0" could be deduped from "24.9.0" to "babel-jest@24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-cli#jest-config#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot#jest-diff##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-each#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-each##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-config#jest-jasmine2##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-runner#jest-leak-detector##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-matcher-utils#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-matcher-utils##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot#jest-matcher-utils##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-snapshot#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-snapshot##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-cli#jest-validate#pretty-format@^24.9.0"
warning "npm#read-package-json#normalize-package-data#is-core-module@^2.8.1" could be deduped from "2.9.0" to "is-core-module@2.9.0"
warning "npm#read-package-json#normalize-package-data#validate-npm-package-license@^3.0.4" could be deduped from "3.0.4" to "validate-npm-package-license@3.0.4"
warning "npm#cacache#p-map#aggregate-error@^3.0.0" could be deduped from "3.1.0" to "aggregate-error@3.1.0"
warning "babel-preset-react-app#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "babel-preset-react-app#@babel/preset-react#@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
warning "@types/webpack-dev-middleware#webpack#terser-webpack-plugin##webpack@^5.1.0" could be deduped from "5.72.0" to "@types\\webpack-dev-middleware#webpack@5.72.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-config##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-config##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-matcher-utils#jest-diff#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-matcher-utils#jest-diff##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-jasmine2#jest-each##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-config#jest-jasmine2#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-jasmine2##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-leak-detector##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-snapshot##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runtime#jest-snapshot##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-validate##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runtime#jest-validate##pretty-format@^24.9.0"
warning "npm#are-we-there-yet#readable-stream#inherits@^2.0.3" could be deduped from "2.0.4" to "inherits@2.0.4"
warning "npm#are-we-there-yet#readable-stream#util-deprecate@^1.0.1" could be deduped from "1.0.2" to "util-deprecate@1.0.2"
warning "npm#gauge#strip-ansi#ansi-regex@^5.0.1" could be deduped from "5.0.1" to "ansi-regex@5.0.1"
error "@types/webpack-dev-middleware#terser-webpack-plugin#terser##source-map@~0.7.2" doesn't satisfy found match of "source-map@0.6.1"
warning "npm#gauge#wide-align#string-width@^1.0.2 || 2 || 3 || 4" could be deduped from "4.2.3" to "string-width@4.2.3"
warning "npm#node-gyp#minimatch#brace-expansion#concat-map@0.0.1" could be deduped from "0.0.1" to "concat-map@0.0.1"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-snapshot#jest-diff##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-snapshot#jest-diff##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-each#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-jasmine2#jest-each##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-config#jest-jasmine2##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-matcher-utils#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-jasmine2#jest-matcher-utils##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-snapshot#jest-matcher-utils##pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-snapshot#pretty-format@^24.9.0"
warning "npm#readable-stream#string_decoder#safe-buffer@~5.2.0" could be deduped from "5.2.1" to "safe-buffer@5.2.1"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-matcher-utils#jest-diff#pretty-format@^24.9.0"
warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-jasmine2#jest-each##pretty-format@^24.9.0"
info Found 244 warnings.
error Found 32 errors.
```

**Comment by mirobo** [comment]
Back to a problem I already had and never got resolved:

It starts a Cypress.exe in the background but it is said that system-tests should not generally required a Cypress.exe build?

```
PS C:\Dev\mirobo\cypress\system-tests> yarn test downloads_spec
yarn run v1.22.19
$ node ./scripts/run.js --glob-in-dir="{test,test-binary}" downloads_spec
cwd: C:\Dev\mirobo\cypress\system-tests
specfiles: [ '{test,test-binary}\\**\\*downloads_spec*' ]
test command:
mocha {test,test-binary}\**\*downloads_spec* --max-http-header-size=1048576 --timeout 10000 --recursive -r @packages/ts/register --reporter mocha-multi-reporters --reporter-options configFile=C:\Dev\mirobo\cypress\system-tests\scripts\mocha-reporter-config.json --extension=js,ts --exit


  e2e downloads
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                e2e downloads / handles various file downloads [electron]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    10.3.1                                                                             │
  │ Browser:    Electron 102 (headless)                                                            │
  │ Specs:      1 found (downloads.cy.ts)                                                          │
  │ Searched:   /XXX/XXX/XXX\cypress\e2e\downloads.cy.ts                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  downloads.cy.ts                                                                 (1 of 1)

Timed out waiting for the browser to connect. Retrying...
    1) handles various file downloads [electron]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                 e2e downloads / handles various file downloads [chrome]                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Remove failed for C:\Users\root\AppData\Local\Temp\cy-projects due to EBUSY. Skipping on Windows.


Timed out waiting for the browser to connect. Retrying again...

```


Also why can't I just run some download tests in "system-tests\projects\downloads" with the UI started with "yarn dev"?

image


I think for my issue I could also call some tests as in "system-tests\test\downloads_spec.ts" because to me it only matters that the file is downloaded to the configured directory. Or can't we just dynamically run all tests in "downloads_spec.ts" on Firefox, Electron and Google Chrome?

**Comment by AtofStryker** [comment]
> **Update**
> 
> Just after writing this I pulled from develop again and I was able to run "yarn dev". Holy moly :-)
> 
> Let's see how long this holds up :D
> 
> > > 3. I cannot even start Cypress in development mode with "yarn start". It will start the Cypress window with the message "Not Found". I've run "yarn clean" but it doesn't help. Some of the system-tests actually require a binary which I cannot build on Windows because of commands like "ls -al" in one of the build scripts. I'd be happy to contribute more if local Cypress development would actually work.. shouldn't be that hard..
> > 
> > 
> > Interesting. I wonder if there are issues running in global mode on Windows. What version of Windows are you developing on and have you followed all the windows instructions in the [contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started)? Just want to make sure we can rule some things out. Might be good to try `yarn` then run some of the driver tests via `yarn workspace @packages/driver cypress:open` and see if you get the same issues?
> 
> Yes, I followed the guide
> 
> NPM 8.11.0 Node 16.16.0 (also tried with 16.14.2) Yarn: v1.22.19

What version of Windows are you running? It is still unclear to me  if you ran `yarn` proceeded by attempting to run the driver tests via `yarn workspace @packages/driver cypress:open` all inside the root?.Are you saying you did both those things and still had no luck?

Also to be clear, you did run `yarn config set script-shell "C:\\Windows\\system32\\cmd.exe"`  to prevent any path issues when running?

Any reason you are using `yarn dev` in particular? Is there a reason you need to bypass the CLI?

> In scripts\binary\build.ts I commented out this because it will never run in Windows:
> 
> ```
>   const { stdout } = await execa('ls', ['-la', meta.buildDir()])
>   console.log(stdout)
> ```

Why do you need to build the binary?  This change shouldn't be necessary

> I added CYPRESS_INTERNAL_VITE_DEV=1 to .npmrc

This shouldn't make a difference, only if you are making changes to client side bundle aspects of Cypress. This flag is just going to use
> When running "yarn" the script just continues and you wouldn't even see the following error (I googled a lot regarding this error and I couldn't find any solution):
> 
> ```
> yarn run v1.22.19
> $ C:\Dev\mirobo\cypress\node_modules\.bin\vite build --outDir dist
> $ C:\Dev\mirobo\cypress\node_modules\.bin\vite build --outDir dist
> [vite:build-app:34748]: failed to load config from C:\Dev\mirobo\cypress\packages\app\vite.config.mjs
> [vite:build-app:34748]: error during build:
> [vite:build-app:34748]: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
> [vite:build-app:34748]:     at new NodeError (node:internal/errors:372:5)
> [vite:build-app:34748]:     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
> [vite:build-app:34748]:     at defaultResolve (node:internal/modules/esm/resolve:1200:3)
> [vite:build-app:34748]:     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
> [vite:build-app:34748]:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
> [vite:build-app:34748]:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
> [vite:build-app:34748]:     at link (node:internal/modules/esm/module_job:78:36)
> [vite:build-launchpad:27192]: failed to load config from C:\Dev\mirobo\cypress\packages\launchpad\vite.config.mjs
> [vite:build-launchpad:27192]: error during build:
> [vite:build-launchpad:27192]: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
> [vite:build-launchpad:27192]:     at new NodeError (node:internal/errors:372:5)
> [vite:build-launchpad:27192]:     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
> [vite:build-launchpad:27192]:     at defaultResolve (node:internal/modules/esm/resolve:1200:3)
> [vite:build-launchpad:27192]:     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
> [vite:build-launchpad:27192]:     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
> [vite:build-launchpad:27192]:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
> [vite:build-launchpad:27192]:     at link (node:internal/modules/esm/module_job:78:36)
> ```
> 
> This failure is probably why Cypress only shows "not found". The launchpad-server itself is running and it also shows "not found" when I open the URL in a normal browser.
> 
> I also added this script to packages/launchpad/package.json to quickly start the vite build.. "build-dev": "vite build --mode development --minify false --watch", ..it shows the same error.
> 
> When running "yarn check --integrity", everything is fine but running "yarn check" gives me 32 errors.. can't be true that there are so many discrepancies after running yarn?

There are some nested dependencies that have a few semver violations. This shouldn't be an issue for getting you up and running.
> ```
> PS C:\Dev\mirobo\cypress> yarn check
> yarn check v1.22.19
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^24.9.0"
> warning Resolution field "@typescript-eslint/eslint-plugin@4.18.0" is incompatible with requested version "@typescript-eslint/eslint-plugin@^2.2.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "pretty-format@^27.0.2"
> warning Pattern ["source-map@0.7.3"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-source-map-fast-0.7.3-5302f8169031735226544092e64981f751750383-integrity\\node_modules\\source-map-fast" as pattern ["source-map@^0.7.3"]. This could result in non-deterministic behavior, skipping.
> warning Pattern ["source-map@~0.7.2"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-source-map-fast-0.7.3-5302f8169031735226544092e64981f751750383-integrity\\node_modules\\source-map-fast" as pattern ["source-map@^0.7.3"]. This could result in non-deterministic behavior, skipping.
> warning Pattern ["@definitelytyped/typescript-versions@latest"] is trying to unpack in the same destination "C:\\Users\\root\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@definitelytyped-typescript-versions-0.0.71-08c791e3bf3c2861611edee8f28c72d2db0fb02e-integrity\\node_modules\\@definitelytyped\\typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.71","@definitelytyped/typescript-versions@^0.0.71","@definitelytyped/typescript-versions@^0.0.71"]. This could result in non-deterministic behavior, skipping.
> warning nuclide-format-js@0.0.36: The engine "atom" appears to be invalid.
> warning Workspaces can only be enabled in private projects.
> warning "@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@babel/preset-typescript##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@npmcli/run-script##@npmcli/node-gyp@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\node-gyp@2.0.0"
> error "@vitejs/plugin-vue##vite@^2.5.10" doesn't satisfy found match of "vite@3.0.3"
> warning "pacote#@npmcli/git@^3.0.0" could be deduped from "3.0.1" to "@npmcli\\git@3.0.1"
> error "@percy/cypress##cypress@>=3" doesn't satisfy found match of "cypress@0.0.0-development"
> error "@semantic-release/changelog##semantic-release@>=15.8.0 <18.0.0" doesn't satisfy found match of "semantic-release@19.0.3"
> error "@semantic-release/git##semantic-release@>=16.0.0 <18.0.0" doesn't satisfy found match of "semantic-release@19.0.3"
> error "@cypress/schematic#@angular-devkit/core##source-map@0.7.3" doesn't satisfy found match of "source-map@0.6.1"
> warning "cypress#@types/chai-jquery##@types/chai@*" could be deduped from "4.2.15" to "@types\\chai@4.2.15"
> warning "cypress#@types/chai-jquery##@types/jquery@*" could be deduped from "3.3.31" to "@types\\jquery@3.3.31"
> warning "cypress#@types/jquery##@types/sizzle@*" could be deduped from "2.3.2" to "@types\\sizzle@2.3.2"
> warning "cypress#@types/sinon-chai##@types/chai@*" could be deduped from "4.2.15" to "@types\\chai@4.2.15"
> warning "cypress#@types/sinon##@types/sinonjs__fake-timers@*" could be deduped from "8.1.1" to "@types\\sinonjs__fake-timers@8.1.1"
> error "@types/webpack#@types/webpack-sources##source-map@^0.7.3" doesn't satisfy found match of "source-map@0.6.1"
> warning "@typescript-eslint/parser#@typescript-eslint/typescript-estree##@typescript-eslint/visitor-keys@4.18.0" could be deduped from "4.18.0" to "@typescript-eslint\\visitor-keys@4.18.0"
> warning "pacote#cacache#@npmcli/move-file@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\move-file@2.0.0"
> warning "@packages/driver#express##body-parser@1.19.0" could be deduped from "1.19.0" to "body-parser@1.19.0"
> warning "@packages/driver#express##methods@~1.1.2" could be deduped from "1.1.2" to "methods@1.1.2"
> warning "@packages/driver#method-override##methods@~1.1.2" could be deduped from "1.1.2" to "methods@1.1.2"
> warning "@packages/rewriter#parse5-html-rewriting-stream##parse5@^5.1.1" could be deduped from "5.1.1" to "parse5@5.1.1"
> warning Resolution field "@typescript-eslint\\eslint-plugin@4.18.0" is incompatible with requested version "@cypress/webpack-preprocessor#react-scripts#@typescript-eslint/eslint-plugin@^2.2.0"
> warning "@cypress/webpack-preprocessor#react-scripts#babel-jest@^24.9.0" could be deduped from "24.9.0" to "babel-jest@24.9.0"
> warning "@cypress/webpack-preprocessor#react-scripts#jest@24.9.0" could be deduped from "24.9.0" to "jest@24.9.0"
> error "c8#v8-to-istanbul#source-map@^0.7.3" doesn't satisfy found match of "source-map@0.6.1"
> warning "@packages/ui-components#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/ui-components#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/plugin-proposal-object-rest-spread##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@babel/preset-react#@babel/plugin-transform-react-jsx-development##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@babel/preset-react#@babel/plugin-transform-react-jsx##@babel/plugin-syntax-jsx@^7.16.7" could be deduped from "7.16.7" to "@babel\\plugin-syntax-jsx@7.16.7"
> warning "@babel/preset-react#@babel/plugin-transform-react-jsx##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/server#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/ui-components#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@tooling/system-tests#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/ui-components#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/register##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> error "@cypress/vue#@cypress/code-coverage##cypress@*" doesn't satisfy found match of "cypress@0.0.0-development"
> warning "@packages/reporter#@cypress/react-tooltip##prop-types@^15.7.2" could be deduped from "15.8.1" to "prop-types@15.8.1"
> warning "@packages/runner-ct#@cypress/react-tooltip##prop-types@^15.7.2" could be deduped from "15.8.1" to "prop-types@15.8.1"
> error "@packages/app#@intlify/vite-plugin-vue-i18n##vite@^2.3.6" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/app#@intlify/vite-plugin-vue-i18n##vue-i18n@^9.1.6" doesn't satisfy found match of "vue-i18n@9.2.0-beta.7"
> error "@packages/app#@testing-library/cypress##cypress@^2.1.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0" doesn't satisfy found match of "cypress@0.0.0-development"
> error "@cypress/vue#@vitejs/plugin-vue##vite@^2.5.10" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/frontend-shared#cypress-axe#cypress@^3 || ^4 || ^5 || ^6 || ^7 || ^8 || ^9" doesn't satisfy found match of "cypress@0.0.0-development"
> warning "@packages/driver#cypress-multi-reporters##debug@^4.1.1" could be deduped from "4.3.4" to "debug@4.3.4"
> warning "@packages/driver#cypress-multi-reporters##lodash@^4.17.15" could be deduped from "4.17.21" to "lodash@4.17.21"
> error "@packages/app#cypress-real-events#cypress@^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x" doesn't satisfy found match of "cypress@0.0.0-development"
> error "@packages/frontend-shared#graphql-relay#graphql@^15.5.3" doesn't satisfy found match of "graphql@15.5.1"
> error "@packages/driver#react-dom-15.6.1##react@^15.6.1" doesn't satisfy found match of "react@16.8.6"
> error "enzyme-adapter-react-16#react-test-renderer#react@^16.14.0" doesn't satisfy found match of "react@16.8.6"
> warning "@packages/extension#ts-loader##webpack@*" could be deduped from "4.46.0" to "webpack@4.46.0"
> error "@packages/app#unplugin-icons#@svgr/core@>=5.5.0" doesn't satisfy found match of "@svgr\\core@4.3.3"
> error "@packages/app#vite-plugin-components#vite@^2.0.0-beta.69" doesn't satisfy found match of "vite@3.0.3"
> error "@cypress/vite-dev-server#vite-plugin-inspect#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/launchpad#vite-plugin-optimize-persist#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/launchpad#vite-plugin-package-config#vite@^2.0.0" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/app#vite-plugin-vue-layouts#vite@^2.5.0" doesn't satisfy found match of "vite@3.0.3"
> error "@packages/app#vite#terser@^5.4.0" doesn't satisfy found match of "terser@4.8.0"
> error "@packages/driver#vite##terser@^5.4.0" doesn't satisfy found match of "terser@4.8.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@testing-library/cypress#@testing-library/dom##pretty-format@^27.0.2"
> warning "@packages/rewriter#@types/parse5-html-rewriting-stream#@types/parse5-sax-parser##@types/parse5@*" could be deduped from "5.0.3" to "@types\\parse5@5.0.3"
> warning "cypress#@types/sinon-chai#@types/sinon##@types/sinonjs__fake-timers@*" could be deduped from "8.1.1" to "@types\\sinonjs__fake-timers@8.1.1"
> warning "@typescript-eslint/experimental-utils#@typescript-eslint/typescript-estree##@typescript-eslint/visitor-keys@4.18.0" could be deduped from "4.18.0" to "@typescript-eslint\\visitor-keys@4.18.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-cli#jest-config#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-cli#jest-config##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-cli#jest-validate#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-cli#jest-validate##pretty-format@^24.9.0"
> warning "@semantic-release/npm#npm#@isaacs/string-locale-compare@^1.1.0" could be deduped from "1.1.0" to "@isaacs\\string-locale-compare@1.1.0"
> warning "@semantic-release/npm#npm#@npmcli/arborist@^5.0.4" could be deduped from "5.2.1" to "@npmcli\\arborist@5.2.1"
> warning "@semantic-release/npm#npm#@npmcli/ci-detect@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\ci-detect@2.0.0"
> warning "@semantic-release/npm#npm#@npmcli/config@^4.1.0" could be deduped from "4.1.0" to "@npmcli\\config@4.1.0"
> warning "@semantic-release/npm#npm#@npmcli/fs@^2.1.0" could be deduped from "2.1.0" to "@npmcli\\fs@2.1.0"
> warning "@semantic-release/npm#npm#@npmcli/map-workspaces@^2.0.3" could be deduped from "2.0.3" to "@npmcli\\map-workspaces@2.0.3"
> warning "@semantic-release/npm#npm#@npmcli/package-json@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\package-json@2.0.0"
> warning "@semantic-release/npm#npm#@npmcli/run-script@^3.0.1" could be deduped from "3.0.3" to "@npmcli\\run-script@3.0.3"
> warning "@semantic-release/npm#npm#abbrev@~1.1.1" could be deduped from "1.1.1" to "abbrev@1.1.1"
> warning "@semantic-release/npm#npm#archy@~1.0.0" could be deduped from "1.0.0" to "archy@1.0.0"
> warning "@semantic-release/npm#npm#chownr@^2.0.0" could be deduped from "2.0.0" to "chownr@2.0.0"
> warning "@semantic-release/npm#npm#cli-columns@^4.0.0" could be deduped from "4.0.0" to "cli-columns@4.0.0"
> warning "@semantic-release/npm#npm#cli-table3@^0.6.2" could be deduped from "0.6.2" to "cli-table3@0.6.2"
> warning "@semantic-release/npm#npm#columnify@^1.6.0" could be deduped from "1.6.0" to "columnify@1.6.0"
> warning "@semantic-release/npm#npm#fastest-levenshtein@^1.0.12" could be deduped from "1.0.12" to "fastest-levenshtein@1.0.12"
> warning "@semantic-release/npm#npm#graceful-fs@^4.2.10" could be deduped from "4.2.10" to "graceful-fs@4.2.10"
> warning "@semantic-release/npm#npm#is-cidr@^4.0.2" could be deduped from "4.0.2" to "is-cidr@4.0.2"
> warning "@semantic-release/npm#npm#json-parse-even-better-errors@^2.3.1" could be deduped from "2.3.1" to "json-parse-even-better-errors@2.3.1"
> warning "@semantic-release/npm#npm#libnpmaccess@^6.0.2" could be deduped from "6.0.3" to "libnpmaccess@6.0.3"
> warning "@semantic-release/npm#npm#libnpmdiff@^4.0.2" could be deduped from "4.0.3" to "libnpmdiff@4.0.3"
> warning "@semantic-release/npm#npm#libnpmexec@^4.0.2" could be deduped from "4.0.6" to "libnpmexec@4.0.6"
> warning "@semantic-release/npm#npm#libnpmfund@^3.0.1" could be deduped from "3.0.2" to "libnpmfund@3.0.2"
> warning "@semantic-release/npm#npm#libnpmhook@^8.0.2" could be deduped from "8.0.3" to "libnpmhook@8.0.3"
> warning "@semantic-release/npm#npm#libnpmorg@^4.0.2" could be deduped from "4.0.3" to "libnpmorg@4.0.3"
> warning "@semantic-release/npm#npm#libnpmpack@^4.0.2" could be deduped from "4.1.0" to "libnpmpack@4.1.0"
> warning "@semantic-release/npm#npm#libnpmpublish@^6.0.2" could be deduped from "6.0.4" to "libnpmpublish@6.0.4"
> warning "@semantic-release/npm#npm#libnpmsearch@^5.0.2" could be deduped from "5.0.3" to "libnpmsearch@5.0.3"
> warning "@semantic-release/npm#npm#libnpmteam@^4.0.2" could be deduped from "4.0.3" to "libnpmteam@4.0.3"
> warning "@semantic-release/npm#npm#libnpmversion@^3.0.1" could be deduped from "3.0.4" to "libnpmversion@3.0.4"
> warning "@semantic-release/npm#npm#make-fetch-happen@^10.1.6" could be deduped from "10.1.7" to "make-fetch-happen@10.1.7"
> warning "@semantic-release/npm#npm#minipass@^3.1.6" could be deduped from "3.1.6" to "minipass@3.1.6"
> warning "@semantic-release/npm#npm#minipass-pipeline@^1.2.4" could be deduped from "1.2.4" to "minipass-pipeline@1.2.4"
> warning "@semantic-release/npm#npm#mkdirp-infer-owner@^2.0.0" could be deduped from "2.0.0" to "mkdirp-infer-owner@2.0.0"
> warning "@semantic-release/npm#npm#ms@^2.1.2" could be deduped from "2.1.3" to "ms@2.1.3"
> warning "@semantic-release/npm#npm#nopt@^5.0.0" could be deduped from "5.0.0" to "nopt@5.0.0"
> warning "@semantic-release/npm#npm#npm-audit-report@^3.0.0" could be deduped from "3.0.0" to "npm-audit-report@3.0.0"
> warning "@semantic-release/npm#npm#npm-install-checks@^5.0.0" could be deduped from "5.0.0" to "npm-install-checks@5.0.0"
> warning "@semantic-release/npm#npm#npm-pick-manifest@^7.0.1" could be deduped from "7.0.1" to "npm-pick-manifest@7.0.1"
> warning "@semantic-release/npm#npm#npm-profile@^6.0.3" could be deduped from "6.0.3" to "npm-profile@6.0.3"
> warning "@semantic-release/npm#npm#npm-registry-fetch@^13.1.1" could be deduped from "13.1.1" to "npm-registry-fetch@13.1.1"
> warning "@semantic-release/npm#npm#npm-user-validate@^1.0.1" could be deduped from "1.0.1" to "npm-user-validate@1.0.1"
> warning "@semantic-release/npm#npm#opener@^1.5.2" could be deduped from "1.5.2" to "opener@1.5.2"
> warning "@semantic-release/npm#npm#pacote@^13.6.0" could be deduped from "13.6.0" to "pacote@13.6.0"
> warning "@semantic-release/npm#npm#parse-conflict-json@^2.0.2" could be deduped from "2.0.2" to "parse-conflict-json@2.0.2"
> warning "@semantic-release/npm#npm#proc-log@^2.0.1" could be deduped from "2.0.1" to "proc-log@2.0.1"
> warning "@semantic-release/npm#npm#qrcode-terminal@^0.12.0" could be deduped from "0.12.0" to "qrcode-terminal@0.12.0"
> warning "@semantic-release/npm#npm#read@~1.0.7" could be deduped from "1.0.7" to "read@1.0.7"
> warning "@semantic-release/npm#npm#read-package-json-fast@^2.0.3" could be deduped from "2.0.3" to "read-package-json-fast@2.0.3"
> warning "@semantic-release/npm#npm#readdir-scoped-modules@^1.1.0" could be deduped from "1.1.0" to "readdir-scoped-modules@1.1.0"
> warning "@semantic-release/npm#npm#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
> warning "@semantic-release/npm#npm#ssri@^9.0.1" could be deduped from "9.0.1" to "ssri@9.0.1"
> warning "@semantic-release/npm#npm#tar@^6.1.11" could be deduped from "6.1.11" to "tar@6.1.11"
> warning "@semantic-release/npm#npm#text-table@~0.2.0" could be deduped from "0.2.0" to "text-table@0.2.0"
> warning "@semantic-release/npm#npm#tiny-relative-date@^1.3.0" could be deduped from "1.3.0" to "tiny-relative-date@1.3.0"
> warning "@semantic-release/npm#npm#treeverse@^2.0.0" could be deduped from "2.0.0" to "treeverse@2.0.0"
> warning "@packages/rewriter#parse5-html-rewriting-stream#parse5-sax-parser##parse5@^5.1.1" could be deduped from "5.1.1" to "parse5@5.1.1"
> warning "@packages/ui-components#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@packages/web-config#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@vitejs/plugin-react#@babel/plugin-transform-react-jsx-self##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@vitejs/plugin-react#@babel/plugin-transform-react-jsx-source##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@graphql-codegen/cli#graphql-config#@endemolshinegroup/cosmiconfig-typescript-loader##cosmiconfig@>=6" could be deduped from "7.0.1" to "@graphql-codegen\\cli#cosmiconfig@7.0.1"
> warning "react-scripts#babel-eslint#eslint@>= 4.12.1" could be deduped from "7.22.0" to "eslint@7.22.0"
> warning "react-scripts#babel-jest#babel-preset-jest@^24.9.0" could be deduped from "24.9.0" to "babel-preset-jest@24.9.0"
> warning "react-scripts#babel-loader#@babel/core@^7.0.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "react-scripts#babel-loader#webpack@>=2" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#babel-plugin-named-asset-import#@babel/core@^7.1.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning Resolution field "@typescript-eslint\\eslint-plugin@4.18.0" is incompatible with requested version "react-scripts#eslint-config-react-app#@typescript-eslint/eslint-plugin@2.x"
> warning "react-scripts#eslint-config-react-app#babel-eslint@10.x" could be deduped from "10.1.0" to "babel-eslint@10.1.0"
> warning "react-scripts#eslint-config-react-app#eslint-plugin-import@2.x" could be deduped from "2.25.4" to "eslint-plugin-import@2.25.4"
> warning "react-scripts#eslint-config-react-app#eslint-plugin-react@7.x" could be deduped from "7.22.0" to "eslint-plugin-react@7.22.0"
> warning "react-scripts#eslint-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#eslint-plugin-flowtype#eslint@>=5.0.0" could be deduped from "7.22.0" to "eslint@7.22.0"
> warning "react-scripts#file-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#html-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#mini-css-extract-plugin#webpack@^4.4.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#optimize-css-assets-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#sass-loader#webpack@^3.0.0 || ^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#style-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#terser-webpack-plugin#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> error "unplugin-vue-components#unplugin#vite@^2.3.0" doesn't satisfy found match of "vite@3.0.3"
> error "unplugin-icons#unplugin#vite@^2.3.0" doesn't satisfy found match of "vite@3.0.3"
> warning "react-scripts#url-loader#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> error "@cypress-design/css#vite-plugin-windicss#vite@^2.0.1" doesn't satisfy found match of "vite@3.0.3"
> warning "react-scripts#webpack-dev-server#webpack@^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#webpack-manifest-plugin#webpack@2 || 3 || 4" could be deduped from "4.46.0" to "webpack@4.46.0"
> warning "react-scripts#workbox-webpack-plugin#webpack@^2.0.0 || ^3.0.0 || ^4.0.0" could be deduped from "4.46.0" to "webpack@4.46.0"
> error "npm#cacache" is wrong version: expected "16.1.1", got "16.1.0"
> warning "npm#cacache#@npmcli/fs@^2.1.0" could be deduped from "2.1.0" to "@npmcli\\fs@2.1.0"
> warning "npm#cacache#@npmcli/move-file@^2.0.0" could be deduped from "2.0.0" to "@npmcli\\move-file@2.0.0"
> warning "npm#cacache#chownr@^2.0.0" could be deduped from "2.0.0" to "chownr@2.0.0"
> warning "npm#cacache#fs-minipass@^2.1.0" could be deduped from "2.1.0" to "fs-minipass@2.1.0"
> warning "npm#cacache#infer-owner@^1.0.4" could be deduped from "1.0.4" to "infer-owner@1.0.4"
> warning "npm#cacache#minipass@^3.1.6" could be deduped from "3.1.6" to "minipass@3.1.6"
> warning "npm#cacache#minipass-collect@^1.0.2" could be deduped from "1.0.2" to "minipass-collect@1.0.2"
> warning "npm#cacache#minipass-flush@^1.0.5" could be deduped from "1.0.5" to "minipass-flush@1.0.5"
> warning "npm#cacache#minipass-pipeline@^1.2.4" could be deduped from "1.2.4" to "minipass-pipeline@1.2.4"
> warning "npm#cacache#promise-inflight@^1.0.1" could be deduped from "1.0.1" to "promise-inflight@1.0.1"
> warning "npm#cacache#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
> warning "npm#cacache#ssri@^9.0.0" could be deduped from "9.0.1" to "ssri@9.0.1"
> warning "npm#cacache#tar@^6.1.11" could be deduped from "6.1.11" to "tar@6.1.11"
> warning "npm#cacache#unique-filename@^1.1.1" could be deduped from "1.1.1" to "unique-filename@1.1.1"
> warning "npm#chalk#ansi-styles@^4.1.0" could be deduped from "4.3.0" to "ansi-styles@4.3.0"
> warning "npm#glob#fs.realpath@^1.0.0" could be deduped from "1.0.0" to "fs.realpath@1.0.0"
> warning "npm#glob#inflight@^1.0.4" could be deduped from "1.0.6" to "inflight@1.0.6"
> warning "npm#glob#inherits@2" could be deduped from "2.0.4" to "inherits@2.0.4"
> warning "npm#glob#once@^1.3.0" could be deduped from "1.4.0" to "once@1.4.0"
> warning "npm#init-package-json#promzard@^0.3.0" could be deduped from "0.3.0" to "promzard@0.3.0"
> warning "npm#init-package-json#read@^1.0.7" could be deduped from "1.0.7" to "read@1.0.7"
> warning "npm#init-package-json#validate-npm-package-license@^3.0.4" could be deduped from "3.0.4" to "validate-npm-package-license@3.0.4"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-config##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-config#jest-jasmine2#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-config#jest-jasmine2##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-validate##pretty-format@^24.9.0"
> warning "npm#node-gyp#graceful-fs@^4.2.6" could be deduped from "4.2.10" to "graceful-fs@4.2.10"
> warning "npm#node-gyp#make-fetch-happen@^10.0.3" could be deduped from "10.1.7" to "make-fetch-happen@10.1.7"
> warning "npm#node-gyp#nopt@^5.0.0" could be deduped from "5.0.0" to "nopt@5.0.0"
> warning "npm#node-gyp#rimraf@^3.0.2" could be deduped from "3.0.2" to "rimraf@3.0.2"
> warning "npm#node-gyp#tar@^6.1.2" could be deduped from "6.1.11" to "tar@6.1.11"
> warning "npm#npmlog#console-control-strings@^1.1.0" could be deduped from "1.1.0" to "console-control-strings@1.1.0"
> warning "npm#npmlog#set-blocking@^2.0.0" could be deduped from "2.0.0" to "set-blocking@2.0.0"
> warning "npm#read-package-json#json-parse-even-better-errors@^2.3.1" could be deduped from "2.3.1" to "json-parse-even-better-errors@2.3.1"
> warning "npm#read-package-json#npm-normalize-package-bin@^1.0.1" could be deduped from "1.0.1" to "npm-normalize-package-bin@1.0.1"
> error "@cypress/webpack-dev-server#html-webpack-plugin-5#html-minifier-terser#terser##source-map@~0.7.2" doesn't satisfy found match of "source-map@0.6.1"
> warning "npm#which#isexe@^2.0.0" could be deduped from "2.0.0" to "isexe@2.0.0"
> warning "npm#write-file-atomic#imurmurhash@^0.1.4" could be deduped from "0.1.4" to "imurmurhash@0.1.4"
> warning "npm#write-file-atomic#signal-exit@^3.0.7" could be deduped from "3.0.7" to "signal-exit@3.0.7"
> warning "@cypress/browserify-preprocessor#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-proposal-class-properties##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-proposal-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-proposal-numeric-separator##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@cypress/browserify-preprocessor#@babel/plugin-proposal-object-rest-spread##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-proposal-optional-chaining##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-transform-flow-strip-types##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@cypress/browserify-preprocessor#@babel/plugin-transform-runtime##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/plugin-transform-runtime##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@cypress/browserify-preprocessor#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/preset-env##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@cypress/browserify-preprocessor#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/preset-react##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "react-scripts#@typescript-eslint/parser#@typescript-eslint/experimental-utils##eslint@*" could be deduped from "7.22.0" to "eslint@7.22.0"
> error "react-scripts#babel-jest#babel-preset-jest" not installed
> warning "@cypress/browserify-preprocessor#babelify##@babel/core@^7.0.0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "npm#npmlog#are-we-there-yet#delegates@^1.0.0" could be deduped from "1.0.0" to "delegates@1.0.0"
> warning "npm#npmlog#gauge#aproba@^1.0.3 || ^2.0.0" could be deduped from "2.0.0" to "aproba@2.0.0"
> warning "npm#npmlog#gauge#color-support@^1.1.3" could be deduped from "1.1.3" to "color-support@1.1.3"
> warning "npm#npmlog#gauge#console-control-strings@^1.1.0" could be deduped from "1.1.0" to "console-control-strings@1.1.0"
> warning "npm#npmlog#gauge#has-unicode@^2.0.1" could be deduped from "2.0.1" to "has-unicode@2.0.1"
> warning "npm#npmlog#gauge#signal-exit@^3.0.7" could be deduped from "3.0.7" to "signal-exit@3.0.7"
> warning "npm#npmlog#gauge#string-width@^4.2.3" could be deduped from "4.2.3" to "string-width@4.2.3"
> warning "npm#node-gyp#glob#fs.realpath@^1.0.0" could be deduped from "1.0.0" to "fs.realpath@1.0.0"
> warning "npm#node-gyp#glob#inflight@^1.0.4" could be deduped from "1.0.6" to "inflight@1.0.6"
> warning "npm#node-gyp#glob#inherits@2" could be deduped from "2.0.4" to "inherits@2.0.4"
> warning "npm#node-gyp#glob#once@^1.3.0" could be deduped from "1.4.0" to "once@1.4.0"
> warning "npm#node-gyp#glob#path-is-absolute@^1.0.0" could be deduped from "1.0.1" to "path-is-absolute@1.0.1"
> warning "react-scripts#jest-cli#jest-config#babel-jest@^24.9.0" could be deduped from "24.9.0" to "babel-jest@24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-cli#jest-config#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot#jest-diff##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-each#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-each##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-config#jest-jasmine2##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-runner#jest-leak-detector##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-matcher-utils#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-matcher-utils##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-snapshot#jest-matcher-utils##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-jasmine2#jest-snapshot#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-jasmine2#jest-snapshot##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-cli#jest-validate#pretty-format@^24.9.0"
> warning "npm#read-package-json#normalize-package-data#is-core-module@^2.8.1" could be deduped from "2.9.0" to "is-core-module@2.9.0"
> warning "npm#read-package-json#normalize-package-data#validate-npm-package-license@^3.0.4" could be deduped from "3.0.4" to "validate-npm-package-license@3.0.4"
> warning "npm#cacache#p-map#aggregate-error@^3.0.0" could be deduped from "3.1.0" to "aggregate-error@3.1.0"
> warning "babel-preset-react-app#@babel/plugin-proposal-decorators#@babel/plugin-syntax-decorators##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "babel-preset-react-app#@babel/preset-react#@babel/plugin-transform-react-display-name##@babel/core@^7.0.0-0" could be deduped from "7.17.9" to "@babel\\core@7.17.9"
> warning "@types/webpack-dev-middleware#webpack#terser-webpack-plugin##webpack@^5.1.0" could be deduped from "5.72.0" to "@types\\webpack-dev-middleware#webpack@5.72.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-config##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-config##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "jest#jest-matcher-utils#jest-diff#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@cypress/eslint-plugin-dev#jest-matcher-utils#jest-diff##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/core#jest-jasmine2#jest-each##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-config#jest-jasmine2#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-jasmine2##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runner#jest-leak-detector##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-snapshot##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runtime#jest-snapshot##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-runtime#jest-validate##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-runtime#jest-validate##pretty-format@^24.9.0"
> warning "npm#are-we-there-yet#readable-stream#inherits@^2.0.3" could be deduped from "2.0.4" to "inherits@2.0.4"
> warning "npm#are-we-there-yet#readable-stream#util-deprecate@^1.0.1" could be deduped from "1.0.2" to "util-deprecate@1.0.2"
> warning "npm#gauge#strip-ansi#ansi-regex@^5.0.1" could be deduped from "5.0.1" to "ansi-regex@5.0.1"
> error "@types/webpack-dev-middleware#terser-webpack-plugin#terser##source-map@~0.7.2" doesn't satisfy found match of "source-map@0.6.1"
> warning "npm#gauge#wide-align#string-width@^1.0.2 || 2 || 3 || 4" could be deduped from "4.2.3" to "string-width@4.2.3"
> warning "npm#node-gyp#minimatch#brace-expansion#concat-map@0.0.1" could be deduped from "0.0.1" to "concat-map@0.0.1"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-snapshot#jest-diff##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-snapshot#jest-diff##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-each#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-jasmine2#jest-each##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-config#jest-jasmine2##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-matcher-utils#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/test-sequencer#jest-jasmine2#jest-matcher-utils##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-snapshot#jest-matcher-utils##pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-jasmine2#jest-snapshot#pretty-format@^24.9.0"
> warning "npm#readable-stream#string_decoder#safe-buffer@~5.2.0" could be deduped from "5.2.1" to "safe-buffer@5.2.1"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "react-scripts#jest-matcher-utils#jest-diff#pretty-format@^24.9.0"
> warning Resolution field "pretty-format@26.4.0" is incompatible with requested version "@jest/reporters#jest-jasmine2#jest-each##pretty-format@^24.9.0"
> info Found 244 warnings.
> error Found 32 errors.
> ```

**Comment by mirobo** [comment]
> > Yes, I followed the guide
> > NPM 8.11.0 Node 16.16.0 (also tried with 16.14.2) Yarn: v1.22.19
> 
> What version of Windows are you running? It is still unclear to me if you ran `yarn` proceeded by attempting to run the driver tests via `yarn workspace @packages/driver cypress:open` all inside the root?.Are you saying you did both those things and still had no luck?

- Windows 21H1 19043.1826 Home
- I now can successfully run "yarn"
- Running `yarn workspace @packages/driver cypress:open`
Gives me this error:
image

And it shows version 10.3.1 but I guess thats because version was not updated in the root package.json

Running `yarn start` and opening this project "system-tests\projects\downloads" gives me this error probably because of the version in "system-tests\package.json". Are those tests never runnable via UI?

image

When I run ` yarn test downloads_spec` it starts Cypress.exe from `C:\Dev\mirobo\cypress\packages\electron\dist\Cypress`

It starts a Cypress.exe in the background but it is said that system-tests should not generally required a Cypress.exe build? Doesn't make sense to me. Why is it built during "yarn" if it's not required?

```
PS C:\Dev\mirobo\cypress\system-tests> yarn test downloads_spec
yarn run v1.22.19
$ node ./scripts/run.js --glob-in-dir="{test,test-binary}" downloads_spec
cwd: C:\Dev\mirobo\cypress\system-tests
specfiles: [ '{test,test-binary}\\**\\*downloads_spec*' ]
test command:
mocha {test,test-binary}\**\*downloads_spec* --max-http-header-size=1048576 --timeout 10000 --recursive -r @packages/ts/register --reporter mocha-multi-reporters --reporter-options configFile=C:\Dev\mirobo\cypress\system-tests\scripts\mocha-reporter-config.json --extension=js,ts --exit


 
  e2e downloads
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                e2e downloads / handles various file downloads [electron]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    10.3.1                                                                             │
  │ Browser:    Electron 102 (headless)                                                            │
  │ Specs:      1 found (downloads.cy.ts)                                                          │
  │ Searched:   /XXX/XXX/XXX\cypress\e2e\downloads.cy.ts                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  downloads.cy.ts                                                                 (1 of 1)

Timed out waiting for the browser to connect. Retrying...
    1) handles various file downloads [electron]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                 e2e downloads / handles various file downloads [chrome]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Remove failed for C:\Users\root\AppData\Local\Temp\cy-projects due to EBUSY. Skipping on Windows.


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    10.3.1                                                                             │
  │ Browser:    Chrome 103 (headless)                                                              │
  │ Specs:      1 found (downloads.cy.ts)                                                          │
  │ Searched:   /XXX/XXX/XXX\cypress\e2e\downloads.cy.ts                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  downloads.cy.ts                                                                 (1 of 1)

Timed out waiting for the browser to connect. Retrying again...

Timed out waiting for the browser to connect. Retrying...

The browser never connected. Something is wrong. The tests cannot run. Aborting...

The browser never connected. Something is wrong. The tests cannot run. Aborting...

```

> Also to be clear, you did run `yarn config set script-shell "C:\\Windows\\system32\\cmd.exe"` to prevent any path issues when running?

When I use this setting, I get this error when I run "yarn start":
```
C:\Dev\mirobo\cypress>yarn start
yarn run v1.22.19
$ yarn ensure-deps
$ ./scripts/ensure-dependencies.sh
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.
```

When I remove the script-shell setting, I can at least start Cypress UI.

> Any reason you are using `yarn dev` in particular? Is there a reason you need to bypass the CLI?

I just tried whatever I could xD.. But I guess the "dev" mode is just "yarn start" for normal occasions.

> > In scripts\binary\build.ts I commented out this because it will never run in Windows:
> > ```
> >   const { stdout } = await execa('ls', ['-la', meta.buildDir()])
> >   console.log(stdout)
> > ```
> 
> Why do you need to build the binary? This change shouldn't be necessary

When I run "yarn" the binary is actually built.

I now ran "yarn clean" and manually deleted "node_modules" (because "yarn clean-deps" doesn't work on Windows) to start from scratch.

When I run "yarn start" it still starts just the exe from `C:\Dev\mirobo\cypress\packages\electron\dist\Cypress`. 

When I run "yarn watch" and then "yarn cypress:open" in a separate terminal and open a project I get the same error:

image

When running "yarn watch" I can make changes to a vue-File but it will not be reflected on the UI (I had the idea of adding like a toggle button in the spec list to show only changed or added files from Git and thought this was a good exercise to get to know the UI)

> > I added CYPRESS_INTERNAL_VITE_DEV=1 to .npmrc
> 
> This shouldn't make a difference, only if you are making changes to client side bundle aspects of Cypress. This flag is just going to use

In Angular the dev build is built faster than the prod build so I wanted also to have the dev build for Vite. 


Step by step... I hope I'm getting there and I won't give up that fast :D

**Comment by AtofStryker** [comment]
> * Windows 21H1 19043.1826 Home
> * I now can successfully run "yarn"
> * Running `yarn workspace @packages/driver cypress:open`
>   Gives me this error:
>   image

Looks like Windows 10 Home, shouldn't be any issues there. Almost looks like an issue with the webapp building

> And it shows version 10.3.1 but I guess thats because version was not updated in the root package.json

No worries this is expected

> Running `yarn start` and opening this project "system-tests\projects\downloads" gives me this error probably because of the version in "system-tests\package.json". Are those tests never runnable via UI?

we usually execute these through `cypress run`, which you can run headfully with the `--headed` flag, sometimes the `--no-exit` flag is also useful. We do not run them via `cypress open`.

> image
> 
> When I run ` yarn test downloads_spec` it starts Cypress.exe from `C:\Dev\mirobo\cypress\packages\electron\dist\Cypress`
> 
> It starts a Cypress.exe in the background but it is said that system-tests should not generally required a Cypress.exe build? Doesn't make sense to me. Why is it built during "yarn" if it's not required?
> 
> ```
> PS C:\Dev\mirobo\cypress\system-tests> yarn test downloads_spec
> yarn run v1.22.19
> $ node ./scripts/run.js --glob-in-dir="{test,test-binary}" downloads_spec
> cwd: C:\Dev\mirobo\cypress\system-tests
> specfiles: [ '{test,test-binary}\\**\\*downloads_spec*' ]
> test command:
> mocha {test,test-binary}\**\*downloads_spec* --max-http-header-size=1048576 --timeout 10000 --recursive -r @packages/ts/register --reporter mocha-multi-reporters --reporter-options configFile=C:\Dev\mirobo\cypress\system-tests\scripts\mocha-reporter-config.json --extension=js,ts --exit
> 
What is happening is that the `yarn test downloads_spec` is globing the binary test directory as well. Inside system tests, we have `test-binary` which actually tests the `cypress` command, and `system-tests` which launches cypress via the server through spawning a child node process. Since there is no downloads test for the binary, the binary tests shouldn't execute  
>   e2e downloads
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                e2e downloads / handles various file downloads [electron]
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> ====================================================================================================
> 
>   (Run Starting)
> 
>   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
>   │ Cypress:    10.3.1                                                                             │
>   │ Browser:    Electron 102 (headless)                                                            │
>   │ Specs:      1 found (downloads.cy.ts)                                                          │
>   │ Searched:   /XXX/XXX/XXX\cypress\e2e\downloads.cy.ts                                           │
>   └────────────────────────────────────────────────────────────────────────────────────────────────┘
> 
> 
> ────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   Running:  downloads.cy.ts                                                                 (1 of 1)
> 
> Timed out waiting for the browser to connect. Retrying...
>     1) handles various file downloads [electron]
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                 e2e downloads / handles various file downloads [chrome]
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Remove failed for C:\Users\root\AppData\Local\Temp\cy-projects due to EBUSY. Skipping on Windows.
> 
> 
> ====================================================================================================
> 
>   (Run Starting)
> 
>   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
>   │ Cypress:    10.3.1                                                                             │
>   │ Browser:    Chrome 103 (headless)                                                              │
>   │ Specs:      1 found (downloads.cy.ts)                                                          │
>   │ Searched:   /XXX/XXX/XXX\cypress\e2e\downloads.cy.ts                                           │
>   └────────────────────────────────────────────────────────────────────────────────────────────────┘
> 
> 
> ────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   Running:  downloads.cy.ts                                                                 (1 of 1)
> 
> Timed out waiting for the browser to connect. Retrying again...
> 
> Timed out waiting for the browser to connect. Retrying...
> 
> The browser never connected. Something is wrong. The tests cannot run. Aborting...
> 
> The browser never connected. Something is wrong. The tests cannot run. Aborting...
> ```
> 
> > Also to be clear, you did run `yarn config set script-shell "C:\\Windows\\system32\\cmd.exe"` to prevent any path issues when running?
> 
> When I use this setting, I get this error when I run "yarn start":
> 
> ```
> C:\Dev\mirobo\cypress>yarn start
> yarn run v1.22.19
> $ yarn ensure-deps
> $ ./scripts/ensure-dependencies.sh
> Der Befehl "." ist entweder falsch geschrieben oder
> konnte nicht gefunden werden.
> error Command failed with exit code 1.
> ```

Now that is weird. Going to try a fresh dev setup of Cypress on windows hopefully this weekend. I want to see if I run into a similar problem. Just to check are you executing this through DOS or PowerShell?

> When I remove the script-shell setting, I can at least start Cypress UI.
> 
> > Any reason you are using `yarn dev` in particular? Is there a reason you need to bypass the CLI?
> 
> I just tried whatever I could xD.. But I guess the "dev" mode is just "yarn start" for normal occasions.
> 
> > > In scripts\binary\build.ts I commented out this because it will never run in Windows:
> > > ```
> > >   const { stdout } = await execa('ls', ['-la', meta.buildDir()])
> > >   console.log(stdout)
> > > ```
> > 
> > 
> > Why do you need to build the binary? This change shouldn't be necessary
> 
> When I run "yarn" the binary is actually built.
> 
> I now ran "yarn clean" and manually deleted "node_modules" (because "yarn clean-deps" doesn't work on Windows) to start from scratch.
> 
> When I run "yarn start" it still starts just the exe from `C:\Dev\mirobo\cypress\packages\electron\dist\Cypress`.
> 
> When I run "yarn watch" and then "yarn cypress:open" in a separate terminal and open a project I get the same error:
> 
> image
> 
> When running "yarn watch" I can make changes to a vue-File but it will not be reflected on the UI (I had the idea of adding like a toggle button in the spec list to show only changed or added files from Git and thought this was a good exercise to get to know the UI)

> 
> In Angular the dev build is built faster than the prod build so I wanted also to have the dev build for Vite.

Definitely faster for sure! Just figure we can get you up and running without throwing in more variables 😅 .

> Step by step... I hope I'm getting there and I won't give up that fast :D

We will get this ironed out!

**Comment by AtofStryker** [comment]
unfortunately didn't get a chance to look at this over the weekend, but hoping this afternoon to see if I yield similar results

**Comment by mirobo** [comment]
> unfortunately didn't get a chance to look at this over the weekend, but hoping this afternoon to see if I yield similar results

I'll try it also on an older laptop.. not sure how far I'll get :D (i5 2540M with a new SSD and 16 GB RAM)

**Comment by mirobo** [comment]
> > unfortunately didn't get a chance to look at this over the weekend, but hoping this afternoon to see if I yield similar results
> 
> I'll try it also on an older laptop.. not sure how far I'll get :D (i5 2540M with a new SSD and 16 GB RAM)

Update: It works on the other laptop. I guess the failing connection to Cypress.exe that I posted previously may have something to do with the fact that Cypress 10+ freezes from time to time on my regular PC 🤔. I'll create a separate issue for this including the crash dump.

Now I need to figure out why the tests in place don't fail. Are all the Cypress tests only executed on a Unix system and never on MacOS or Windows? That would explain why the tests don't fail in CI..

**Comment by AtofStryker** [comment]
@mirobo I had a few minutes today and added in the test I was talking about in https://github.com/cypress-io/cypress/issues/17896#issuecomment-1209664718. Going to work on getting this reviewed through support rotation.

**Review by rockindahizzy — APPROVED** [review]

**Review by rachelruderman — APPROVED** [review]
Looks great and tests great, thank you for your contribution!

**Comment by mirobo** [comment]
> Looks great and tests great, thank you for your contribution!

Huge thanks to @AtofStryker!

**Comment by AtofStryker** [comment]
@mirobo glad I could help! This should make its way into the next release.
