### PR TITLE
Strip document-domain directive from feature-policy header when…

### LINKED ISSUE #6480: Can't log/intercept/mock requests when document-domain is disabled by Feature Policy
### Current behavior:

I have a site running on https, its server serving resources with the `Feature Policy` header `document-domain` directive set to `none`

```
Feature Policy: document-domain 'none'
```

As expected, not setting 

```json
"chromeWebSecurity": false
```
in cypress.json will result in Cypress failing to even reaching the site

If I set `chromeWebSecurity` to `true`, Cypress will be able to reach and perform actions on the site (in this case, logging in), but

1. In the console I can still see an error being thrown about `document.domain` being disabled by the `Feature Policy`
2. no XHR requests are being logged on the test runner
3. most importantly, no XHR requests get intercepted by `cy.route()`, meaning that it's impossible to wait for them, or inspect their response, or mock their response

If I get rid of the `document-domain` directive, then the error is gone and the XHR requests are getting logged and intercepted as expected

### Desired behavior:

The desired behaviour would be that setting

```
"chromeWebSecurity": false
```

would bypass the `document-domain: none` directive

### Versions

cypress: 4.0.2
OS: macOS Catalina 10.15.3
browser: Chrome 80

### PR DESCRIPTION
**Pull request by AkA84**
- Closes #6480 

### User facing changelog

Cypress will now strip the [`document-domain`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/document-domain) directive from the [`Feature-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) response header, as its allowlist could prevent the tests from running properly (see #6480)

#### Why was this change necessary?
If a server was set up to serve resources with the `document-domain 'none'` directive, Cypress would either fail to run the test (with `"chromeWebSecurity": true`) or fail to log/intercept/mock requests and responses (with `"chromeWebSecurity": false`)

#### What is affected by this change?
Any response given by the server is stripped of the aforementioned directive, if present

#### Any implementation details to explain?
I went for the quicker route of stripping the whole header instead of just the directive. If this is too broad a stroke I can change the implementation and strip only the directive instead (but I would probably need some pointers re where to do it, I'm not sure if `OmitProblematicHeaders` would be the right place for that)

**UPDATE** We now only strip the `document-domain` directive, leaving the other header's directives in place

#### Before
before

_(with `"chromeWebSecurity": true`)_

#### After
after

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?

### CODE REVIEW

**Comment by AkA84** [comment]
@flotwig I've created a new middleware, `MaybeStripDocumentDomainFeaturePolicy` (couldn't come up with something less verbose, sorry!)

The tests all pass fine, but it seems that when I run Cypress the middleware gets completely ignored, maybe I skipped a step? I looked at other middlewares and it doesn't seem I need to do anything else other than export it?

I've wrote two simple functions that parse and stringify the Feature-Policy header directives (`parseFeaturePolicy`, `stringifyFeaturePolicy`). There is a bit of duplication between the source code and the tests suite in that regard (as in, the tests have the same parse/stringify code), not sure if that warrants the creation of a helper file to share the functions between the two

I'll wait to amend the PR description until I get some feedback from you that I'm at least headed on the right direction, if that's ok with you

> By the way, are you using a framework or library that sets that Feature-Policy? If so, what is it?

Not that I'm aware of, but I'll let you know if I find out otherwise!

File: packages/proxy/lib/http/response-middleware.ts [hunk 1]
```diff
@@ -383,4 +414,5 @@ export default {
   MaybeRemoveSecurity,
   GzipBody,
   SendResponseBodyToClient,
+  MaybeStripDocumentDomainFeaturePolicy,
```
Comment (flotwig) [inline packages/proxy/lib/http/response-middleware.ts:417]: These are evaluated in key-order, so move this to be right after `MaybePreventCaching`

File: packages/proxy/lib/http/response-middleware.ts [hunk 2]
```diff
@@ -225,6 +225,37 @@ const SetInjectionLevel: ResponseMiddleware = function () {
...
+
+    return _.fromPairs(pairs)
+  }
+
+  // { autoplay: "*", "document-domain": "'none'" } => "autoplay *; document-domain 'none'"
+  const stringifyFeaturePolicy = (policy: any): string => {
+    const pairs = _.toPairs(policy)
+
+    return pairs.map((directive) => directive.join(' ')).join('; ')
+  }
```
Comment (flotwig) [inline packages/proxy/lib/http/response-middleware.ts:242]: nit: other functions in this file are declared at the top and then used later on in the middlewares, you may want to follow that pattern just for consistency's sake. not a big deal

File: packages/proxy/lib/http/response-middleware.ts [hunk 3]
```diff
@@ -225,6 +225,37 @@ const SetInjectionLevel: ResponseMiddleware = function () {
...
+
+  if (featurePolicy) {
+    const directives = parseFeaturePolicy(<string>featurePolicy)
+
+    if (directives['document-domain']) {
+      delete directives['document-domain']
+
+      this.res.set('feature-policy', stringifyFeaturePolicy(directives))
+    }
+  }
```
Comment (flotwig) [inline packages/proxy/lib/http/response-middleware.ts:254]: nice, this should be safer!

**Comment by AkA84** [comment]
@flotwig thanks for the review again, I've made additional changes and updated the PR description

**Comment by AkA84** [comment]
@flotwig the `packages/server/test/e2e/2_images_spec.coffee` test failed, but I tested it on my local and it seems that the test itself is a bit flaky, could you confirm? Thanks!

File: packages/proxy/lib/http/response-middleware.ts [hunk 4]
```diff
@@ -225,6 +239,23 @@ const SetInjectionLevel: ResponseMiddleware = function () {
...
+const MaybeStripDocumentDomainFeaturePolicy: ResponseMiddleware = function () {
+  const { 'feature-policy': featurePolicy } = this.incomingRes.headers
+
+  if (featurePolicy) {
+    const directives = parseFeaturePolicy(<string>featurePolicy)
+
+    if (directives['document-domain']) {
+      delete directives['document-domain']
+
+      this.res.set('feature-policy', stringifyFeaturePolicy(directives))
```
Comment (flotwig) [inline packages/proxy/lib/http/response-middleware.ts:252]: If the user passes `Feature-Policy: document-domain 'none'`, this will cause `Feature-Policy:` to be set instead. I believe it's invalid to set an empty HTTP header, so can this be updated to just completely remove the header if `stringifyFeaturePolicy(directives)` is empty?

Comment (AkA84) [reply packages/proxy/lib/http/response-middleware.ts:252]: @flotwig will do! About adding a test for this scenario: will a unit test suffice or do you want me to write an integration test as well?

Comment (flotwig) [reply packages/proxy/lib/http/response-middleware.ts:252]: Unit would be fine

Comment (AkA84) [reply packages/proxy/lib/http/response-middleware.ts]: @flotwig all done, you can check again whenever you have time :)

**Comment by flotwig** [comment]
Thanks!
