### PR TITLE
fix: `cy.contains` and `should('contain')` handle backslash correctly.

### LINKED ISSUE #19116: cy.wrap(element).should('contain', textWithBackslash) fails
### Current behavior

I have an email form input field which displays a (real-time) error message beneath if invalid input is detected, to the effect of:
"[value] is not a valid email"

I use Cypress to run a lot of simultaneous checks (i.e. make sure the form is disabled, there's an error indicator somewhere on the page, the text is red, etc, etc, etc). Somewhere along the way, Cypress also checks that the error message itself contains the input the user entered... and this is where it falls over.

I've provided the smallest sample code I could make which reproduced the problem consistently

The error stack trace is as follows:

```
Error: Timed out retrying after 15000ms: Syntax error, unrecognized expression: :contains('\"<OE_D]dQ\'), [type='submit'][value~='\"<OE_D]dQ\']
    at Function.Sizzle.error (http://localhost/__cypress/runner/cypress_runner.js:109207:8)
    at Sizzle.tokenize (http://localhost/__cypress/runner/cypress_runner.js:109859:11)
    at Sizzle.compile (http://localhost/__cypress/runner/cypress_runner.js:110253:12)
    at Sizzle.select (http://localhost/__cypress/runner/cypress_runner.js:110343:16)
    at Sizzle (http://localhost/__cypress/runner/cypress_runner.js:108511:9)
    at Function.Sizzle.matchesSelector (http://localhost/__cypress/runner/cypress_runner.js:109170:9)
    at tryFn (http://localhost/__cypress/runner/cypress_runner.js:149438:30)
    at tryCatchFinally (http://localhost/__cypress/runner/cypress_runner.js:149409:12)
    at Function.../driver/src/config/jquery.ts.jquery__WEBPACK_IMPORTED_MODULE_0___default.a.find.matchesSelector (http://localhost/__cypress/runner/cypress_runner.js:149436:10)
    at Function.jQuery.filter (http://localhost/__cypress/runner/cypress_runner.js:110515:22)
    at winnow (http://localhost/__cypress/runner/cypress_runner.js:110501:21)
    at jQuery.fn.init.is (http://localhost/__cypress/runner/cypress_runner.js:110554:12)
    at Proxy.<anonymous> (http://localhost/__cypress/runner/cypress_runner.js:150897:25)
    at Proxy.overwritingChainableMethodWrapper (http://localhost/__cypress/runner/cypress_runner.js:103745:34)
    at Proxy.chainableMethodWrapper (http://localhost/__cypress/runner/cypress_runner.js:102369:49)
    at applyChainer (http://localhost/__cypress/runner/cypress_runner.js:154696:24)
From previous event:
    at Context.shouldFn (http://localhost/__cypress/runner/cypress_runner.js:154756:63)
    at Context.should (http://localhost/__cypress/runner/cypress_runner.js:154774:23)
    at http://localhost/__cypress/runner/cypress_runner.js:150222:39
    at assertions (http://localhost/__cypress/runner/cypress_runner.js:150551:16)
From previous event:
    at $Cy.verifyUpcomingAssertions (http://localhost/__cypress/runner/cypress_runner.js:150566:62)
    at resolveWrap (http://localhost/__cypress/runner/cypress_runner.js:157060:21)
    at whenStable (http://localhost/__cypress/runner/cypress_runner.js:167461:63)
    at http://localhost/__cypress/runner/cypress_runner.js:166959:14
logError @ cypress_runner.js:193303
(anonymous) @ cypress_runner.js:191740
emit @ cypress_runner.js:69233
(anonymous) @ cypress_runner.js:188385
emit @ cypress_runner.js:69233
emit @ cypress_runner.js:188446
onPrint @ cypress_runner.js:187275
_onPrintClick @ cypress_runner.js:187280
(anonymous) @ cypress_runner.js:188617
executeAction @ cypress_runner.js:66991
n @ cypress_runner.js:66991
ca @ cypress_runner.js:77581
ja @ cypress_runner.js:77582
ka @ cypress_runner.js:77582
wa @ cypress_runner.js:77584
Aa @ cypress_runner.js:77585
ya @ cypress_runner.js:77585
Da @ cypress_runner.js:77588
Ad @ cypress_runner.js:77651
Gi @ cypress_runner.js:77817
Kb @ cypress_runner.js:77606
Dd @ cypress_runner.js:77653
(anonymous) @ cypress_runner.js:77818
../../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:82406
Ii @ cypress_runner.js:77818
Cd @ cypress_runner.js:77652
```

image
**NB**: despite the appearance in the screenshot, there is definitely a backslash at the end of the problematic string. Cypress is also parsing error messages so this is why it's being hidden (see #18800 for how this affects other text formatting)

### Desired behavior

Not encounter an error... and confirm whether the selected element contains the text or not

### Test code to reproduce

```
const nastyString = '"<OE_D]dQ\\'
const tag = Cypress.$('<span />').text(nastyString).appendTo(document.body)
cy.wrap(tag).should('contain', nastyString) // fails here

// cy.wrap(v).should('contain', nastyString.replace('\\', '\\\\')) // this succeeds
```

### Cypress Version

9.1.0

### Other

Platform: Win 11
Node: 17.1 (nodeVersion: bundled - it'll crash otherwise, see #18914 )

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #19116

### User facing changelog

`cy.contains` and `should('contain')` handle backslash correctly.

### Additional details
- Why was this change necessary? => Using backslash in `cy.contains` and `should('contain')` doesn't work.
- What is affected by this change? => N/A

### Any implementation details to explain? 

Using backslash breaks the Sizzle selectors below:

https://github.com/cypress-io/cypress/blob/b0fe8bf0dd90d302e51b8d75782edb3b19d5af3e/packages/driver/src/cy/chai.ts#L282

https://github.com/cypress-io/cypress/blob/b0fe8bf0dd90d302e51b8d75782edb3b19d5af3e/packages/driver/src/dom/elements/find.ts#L277

For example, strings like `<asdf\` escape the quotation marks and breaks the query.

So, I escaped the quotation marks. 

But I had to solve a few more problems like:

* redundant `escapeQuotes` functions. => create `utils/escape.ts` file and move them there.
* `should('contain')` message are not shown correctly. => I had to escape the double quotes first. 

### How has the user experience changed?

```js
cy.get('#backslashes').contains('"<OE_D]dQ\\')
cy.get('#escape-backslashes').should('contain', '"<OE_D]dQ\\')
```

**Before:** Fails.
**After:** Passes.

### PR Tasks
- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/assertions_spec.js [hunk 1]
```diff
@@ -1277,6 +1277,36 @@ describe('src/cy/commands/assertions', () => {
     })
   })
 
+  // TODO: this suite should be merged with the suite above
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/assertions_spec.js:1280]: `TODO` is here because the test codes should be refactored a bit later. 

The suite above `format quotation marks` actually has 3 subcategories:

* format quotation marks
* format strings
* escape markdown

The name doesn't explain well about the tests. 

It'll be handled after this PR is merged.

**Review by BlueWinds — APPROVED** [review]

File: packages/driver/src/cy/chai.ts [hunk 2]
```diff
@@ -29,6 +30,8 @@ const trailingWhitespaces = /\s*'\*\*/g
 const whitespace = /\s/g
 const valueHasLeadingOrTrailingWhitespaces = /\*\*'\s+|\s+'\*\*/g
 const imageMarkdown = /!\[.*?\]\(.*?\)/g
+const doubleslashRe = /\\\\/g
+const escapedDoubleslashRe = /__doulbe_slash__/g
```
Comment (davidmunechika) [inline packages/driver/src/cy/chai.ts:34]:
```suggestion
const escapedDoubleslashRe = /__double_slash__/g
```

File: packages/driver/src/cy/chai.ts [hunk 3]
```diff
@@ -103,6 +106,9 @@ chai.use((chai, u) => {
     return
   })
 
+  const escapeDoubleSlash = (str: string) => str.replace(doubleslashRe, '__doulbe_slash__')
```
Comment (davidmunechika) [inline packages/driver/src/cy/chai.ts:109]:
```suggestion
  const escapeDoubleSlash = (str: string) => str.replace(doubleslashRe, '__double_slash__')
```

File: packages/driver/src/cy/chai.ts (hunk 2 above)
Comment (sainthkh) [reply packages/driver/src/cy/chai.ts]: Done.

File: packages/driver/src/cy/chai.ts (hunk 3 above)
Comment (sainthkh) [reply packages/driver/src/cy/chai.ts]: Done.

**Review by davidmunechika — APPROVED** [review]
