### PR TITLE
handle cy.contains selector with comma separated dom els

### LINKED ISSUE #2407: `contains` doesn't work with a selector that contains a comma
### Current behavior:

I expect the second line to have equivalent behaviour to the first:

```js
  cy.get('body').find('a,button').contains("Search").click();
  cy.contains('a,button', "Search").click();
```

Instead, it finds the first `a` and ignores the value. It appears the `,` is causing issues.

I'm very new to Cypress, so perhaps this expectation is unfounded.

### Versions

3.1.0, Chrome 68, Ubuntu 18

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #2407 
- split filter arg on commas and generate 'contains' selector using all els
- write test with comma-separated dom els in filter arg.

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/querying_spec.coffee [hunk 1]
```diff
@@ -1204,6 +1204,15 @@ describe "src/cy/commands/querying", ->
       cy.contains("form", "click me").then ($form) ->
         expect($form.get(0)).to.eq form.get(0)
 
+    it "searches all elements in comma separated filter", ->
+      cy.contains("a,button", "Naruto").then ($el) ->
```
Comment (bahmutov) [inline packages/driver/test/cypress/integration/commands/querying_spec.coffee]: will the same work if there are spaces like `cy.contains('a, button')`?

Comment (jennifer-shehane) [reply packages/driver/test/cypress/integration/commands/querying_spec.coffee]: I did write a test for this, and it passed, so I removed it...because I thought the same thing and thought maybe we needed to strip the spaces.

But, the more I think about it, I think the test I wrote was likely a false positive...so let me write a better test for this.

Comment (jennifer-shehane) [reply packages/driver/test/cypress/integration/commands/querying_spec.coffee]: Wrote a test, trimmed string

**Comment by xaviershay** [comment]
Hooray! Thank you! 🎉
