### PR TITLE
fix(server): handle more CDP connection errors

### LINKED ISSUE #6518: Error: could not find CRI target
### Current behavior:

Error: could not find CRI target when running on chrome

Note : Tests run successfully in electron and firefox
### Desired behavior:

Tests should run in Chome browser
### Test code to reproduce
Run Integration/example tests using command
```
 node_modules\.bin\cypress run  --browser chrome
```
```
could not find CRI target
Error: could not find CRI target
    at lazyAssLogic (C:\Users\nidhi\AppData\Local\Cypress\Cache\4.0.2\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:110:14)
    at lazyAss (C:\Users\nidhi\AppData\Local\Cypress\Cache\4.0.2\Cypress\resources\app\packages\server\node_modules\lazy-ass\index.js:115:28)
    at findStartPage (C:\Users\nidhi\AppData\Local\Cypress\Cache\4.0.2\Cypress\resources\app\packages\server\lib\browsers\protocol.js:55:3)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

### Versions

Cypress:    4.0.2 
Browser:    Chrome 80 
Windows 10

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #6518 (provides a better error when there is some issue launching Chrome)

### User facing changelog

- Improved error handling when Cypress launches Chromium-family browsers.

### Additional details

Moving this .catch statement to clean up errors, for example, the error that occurs in #6518 will now be wrapped by this.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/browsers/protocol.js [hunk 1]
```diff
@@ -116,8 +113,9 @@ const getWsTargetFor = (port) => {
 
     return retry()
   })
-  .tapCatch((err) => {
+  .catch((err) => {
     debug('failed to connect to CDP %o', { connectOpts, err })
+    errors.throw('CDP_COULD_NOT_CONNECT', port, err)
```
Comment (bahmutov) [inline packages/server/lib/browsers/protocol.js:118]: wouldn't this change behavior in the case when `findStartPageTarget` throws an error? I mean I like this change, just needs tests update I think

Comment (flotwig) [reply packages/server/lib/browsers/protocol.js:118]: ok, will add tests. yeah, it will catch that error and wrap it, which is (i think) what we want - right now the raw error is confusing to the user, like, "what is a CRI target?"

File: packages/server/test/unit/browsers/protocol_spec.ts [hunk 2]
```diff
@@ -43,24 +43,44 @@ describe('lib/browsers/protocol', () => {
   })
 
   context('.getWsTargetFor', () => {
+    const expectedCdpFailedError = stripIndents`
+      Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds.
```
Comment (bahmutov) [inline packages/server/test/unit/browsers/protocol_spec.ts:47]: hardcoded time limit ;)

File: packages/server/test/unit/browsers/protocol_spec.ts [hunk 3]
```diff
@@ -43,24 +43,44 @@ describe('lib/browsers/protocol', () => {
...
+
+      This usually indicates there was a problem opening the Chrome browser.
+
+      The CDP port requested was ${chalk.yellow('12345')}.
```
Comment (bahmutov) [inline packages/server/test/unit/browsers/protocol_spec.ts:51]: nice port number

File: packages/server/test/unit/browsers/protocol_spec.ts (hunk 2 above)
Comment (flotwig) [reply packages/server/test/unit/browsers/protocol_spec.ts:47]: indeed. now that foxdriver and marionette contain similar logic, i want to refactor this whole area of "connecting to browser-specific automation protocols"... but for now, this hard-coded time limit is still correct 🤷
