### PR TITLE
fix: correct dashboard result when successful spec run and videoUploadOnPasses=false

### LINKED ISSUE #2939: Dashboard should not show a video link if no video has been uploaded
### Current behavior:

If you set `videoUploadOnPasses` to false, Cypress will not upload a video for successful tests. However, a video link is still shown in the dashboard for these tests and if you click it, you will get a page with the message `The media could not be loaded, either because the server or network failed or because the format is not supported`

### Desired behavior:

If no video was uploaded there should be no video link in the dashboard

### Steps to reproduce: (app code and test code)

Set the `videoUploadOnPasses` option to false and run a successful test. No video will be uploaded. Go to the dashboard and locate this test. It will have a link to play a video. If you click on the link you will get the message posted above

### Versions

Cypress 3.1.3

### images

This is what we see for a successful test. Notice the video button which can be clicked

screen shot 2018-12-12 at 20 24 15

Then when the button is pressed, we get this:
screen shot 2018-12-12 at 20 25 32

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #2939

### User facing changelog

- Correct the spec results that are pushed to the Dashboard to correctly show whether a video of the spec was uploaded to review.

### How has the user experience changed?

When a video failed to upload or if the configuration includes `videoUploadOnPasses: false` and a video was not uploaded, the dashboard will no longer show the view below because we indicated a video should exist.

screen shot 2018-12-12 at 20 25 32

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
@conversaShawn Tested this out & verified this is working how they expected. Moving to "Ready for Review".

File: packages/server/lib/modes/run.ts [hunk 1]
```diff
@@ -645,7 +647,14 @@ function waitForTestsToFinishRunning (options: { project: Project, screenshots:
...
         ffmpegChaptersConfig,
       )
-      .catch(warnVideoRecordingFailed)
+      .catch((err) => {
+        videoCaptureFailed = true
+        warnVideoRecordingFailed(err)
+      })
+    }
+
+    if (videoCaptureFailed) {
```
Comment (AtofStryker) [inline packages/server/lib/modes/run.ts:656]: does the `await` above also wait for the catch? I would think the `if` would fun first then the possible catch. Wonder if it is a better/more readable to cut this over to a try/catch/finally?

**Review by chrisbreiding — APPROVED** [review]

File: packages/server/lib/modes/run.ts (hunk 1 above)
Comment (emilyrohrbough) [reply packages/server/lib/modes/run.ts:656]: @AtofStryker Sorry, which `await`? Theres a couple things happening in the after test run handler.

**Review by AtofStryker — APPROVED** [review]
