### PR TITLE
fix: testIsolation Typescript types

### LINKED ISSUE #23911: TS2345 error: testIsolation not in cypress.d.ts -> TestConfigOverrides
### Current behavior

When trying to use `testIsolation` option in test suite at describe level like mentioned in https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-Isolation, typescript check marks it with below error:

`TS2345: Argument of type '{ testIsolation: string; }' is not assignable to parameter of type 'TestConfigOverrides'.   Object literal may only specify known properties, and 'testIsolation' does not exist in type 'TestConfigOverrides'.`

Even though - it is working fine when `testIsolation:'strict'` is added there and it utilizes this function properly.

### Desired behavior

`tsc` using `cypress.d.ts` not complaining about it.

### Test code to reproduce

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.cy.ts"]
}

// test.cy.ts
describe('test name', { testIsolation: 'strict' }, () => {})
```

### Cypress Version

10.8.0

### Node version

v16.14.0

### Operating System

macOS 12.6

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #23911

### User facing changelog
- Fix `testIsolation` Typescript types. Fixes [#23911](https://github.com/cypress-io/cypress/issues/23911).

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -3074,7 +3074,16 @@ declare namespace Cypress {
...
+  interface SuiteConfigOverrides extends Partial<
+    Pick<ConfigOptions, 'animationDistanceThreshold' | 'blockHosts' | 'defaultCommandTimeout' | 'env' | 'execTimeout' | 'includeShadowDom' | 'numTestsKeptInMemory' | 'pageLoadTimeout' | 'redirectionLimit' | 'requestTimeout' | 'responseTimeout' | 'retries' | 'screenshotOnRunFailure' | 'slowTestThreshold' | 'scrollBehavior' | 'taskTimeout' | 'viewportHeight' | 'viewportWidth' | 'waitForAnimations' | 'experimentalSessionAndOrigin'>
+  >, Partial<Pick<ResolvedConfigOptions, 'baseUrl' | 'testIsolation'>> {
+    browser?: IsBrowserMatcher | IsBrowserMatcher[]
+    keystrokeDelay?: number
+  }
+
+  interface TestConfigOverrides extends Partial<
```
Comment (BlueWinds) [inline cli/types/cypress.d.ts:3084]: Can SuiteConfigOverrides be something like `TestConfigOverrides & { testIsolation?: bool }`, rather than relisting everything that's shared between the two? My eyes crossed trying to find the difference between these two.

File: cli/types/tests/cypress-tests.ts [hunk 2]
```diff
@@ -29,19 +29,20 @@ namespace CypressAutomationTests {
...
-  Cypress.config('baseUrl') // $ExpectType string | null
+  Cypress.config('baseUrl') // $ExpectType string | null | undefined
   Cypress.config().baseUrl // $ExpectType string | null
 
   // setters
   Cypress.config('baseUrl', '.') // $ExpectType void
-  Cypress.config({ e2e: { baseUrl: '.' }}) // $ExpectType void
-  Cypress.config({ e2e: { baseUrl: null }}) // $ExpectType void
-  Cypress.config({ e2e: { baseUrl: '.', }}) // $ExpectType void
+  Cypress.config({ e2e: { baseUrl: '.' }}) // $ExpectError
```
Comment (BlueWinds) [inline cli/types/tests/cypress-tests.ts:37]: Why is defining `e2e.baseUrl` now a type error?

Comment (emilyrohrbough) [reply cli/types/tests/cypress-tests.ts:37]: Cypress.config({ e2e: ...}) isn't actually valid:

Screen Shot 2022-11-08 at 12 30 07 PM

File: cli/types/cypress.d.ts (hunk 1 above)
Comment (emilyrohrbough) [reply cli/types/cypress.d.ts:3084]: I have left it like this because I had a similar suggestion and the Typescript 'hover' message wasn't super clear
|  (Similar to) your suggestion | As Is |
| -- | --|
Screen Shot 2022-11-08 at 11 54 36 AM|Screen Shot 2022-11-08 at 3 21 38 PM

Thoughts? I don't have a strong opinion.

Comment (BlueWinds) [reply cli/types/cypress.d.ts:3084]: I'll be honest: I can't make heads or tails of *either* of those errors. Typestcript errors are always unreadable. :woman_shrugging: 

I'm fine leaving it as is if it looks clearer to you.

**Review by BlueWinds — APPROVED** [review]

**Review by chrisbreiding — APPROVED** [review]
