### PR TITLE
fix: Show better error message during `cypress cache list` when no cache 

### LINKED ISSUE #6303: Handle better cache list if there are no binaries installed
Cypress v3.8.3 on CI

If we skill installing Cypress binary with `CYPRESS_INSTALL_BINARY: 0` env variable, then `cypress cache path` returns a folder name, but the folder does not exist. Then `cypress cache list` throws an error, yet exits with 0

https://github.com/bahmutov/cypress-gh-action-split-install/runs/423294744?check_suite_focus=true

## Proposal
`cypress cache list` should show a good warning message if the cache folder does not exist. It should still exit with zero code since there might not be any versions installed

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes #6303 

### User facing changelog

- A clearer error is printed during `cypress cache list` when no cached versions are found.

### Additional Details

- Just trying to close an issue 🤷‍♀️ 

#### Before

Screen Shot 2020-10-29 at 5 18 26 PM

#### After

Screen Shot 2020-10-29 at 5 18 15 PM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Review by chrisbreiding — DISMISSED** [review]

File: cli/lib/cli.js [hunk 1]
```diff
@@ -408,8 +408,14 @@ module.exports = {
           size: opts.size,
         })
 
-        return cache.list(opts.size).catch((e) => {
+        return cache.list(opts.size)
+        .catch({ code: 'ENOENT' }, () => {
+          logger.always('No binary cached versions were found.')
```
Comment (Bkucera) [inline cli/lib/cli.js:413]:
```suggestion
          logger.always('No cached binary versions were found.')
```

**Review by kuceb — CHANGES_REQUESTED** [review]

File: cli/__snapshots__/cli_spec.js [hunk 2]
```diff
@@ -451,3 +451,7 @@ exports['cli version and binary version with npm log warn'] = `
 Cypress package version: 1.2.3
 Cypress binary version: X.Y.Z
 `
+
+exports['prints explanation when no cache'] = `
+No binary cached versions were found.
```
Comment (Bkucera) [inline cli/__snapshots__/cli_spec.js:456]:
```suggestion
No cached binary versions were found.
```

**Review by kuceb — CHANGES_REQUESTED** [review]

File: cli/__snapshots__/cli_spec.js (hunk 2 above)
Comment (jennifer-shehane) [reply cli/__snapshots__/cli_spec.js:456]: 🙃

**Review by kuceb — APPROVED** [review]
