### PR TITLE
fix(socket): update serialization for circular binary socket messages

### LINKED ISSUE #15101: RangeError: Maximum call stack size exceeded at _deconstructPacket in CI Pipeline
### Current behavior
Upgrading to cypress version 6.5.0 and running it on Bitbucket Pipeline CI via parallel tests, the error is encountered:
```
RangeError: Maximum call stack size exceeded
    at _deconstructPacket (/root/.cache/Cypress/6.5.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/binary.js:21:28)
    at _deconstructPacket (/root/.cache/Cypress/6.5.0/Cypress/resources/app/packages/socket/node_modules/socket.io-parser/dist/binary.js:40:32)
...
at _deconstructPacket (/root/.cache/Cypress/6.5.0/Cypress/resources/app/packages/socket/node_modules/socket.io-The Test Runner unexpectedly exited via a exit event with signal SIGILL
```

I've checked similar issues in the past and they have been fixed by succeeding Cypress versions. Could it be on the package.json and package-lock.json having the latest version Cypress `v6.5.0` while my docker image is still pointing to `cypress/base:14.15.4`

### Desired behavior
The Test runner should not exit in the CI pipeline and continue to generate test results.

### Test code to reproduce
`bitbucket-pipelines.yml`
```yaml
image: cypress/base:14.15.4
options:
  max-time: 20

tests: &tests
  name: Run tests
  caches:
    - node
    - cypress
  script:
    - set +e # continue executing next steps regardless of errors
    - cypress_version=$HOST npx cypress run --record --key $CYPRESS_DASHBOARD_KEY --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER
  artifacts:
    - cypress/screenshots/**
    - cypress/videos/**
    - cypress/test-reports/mocha/*.json
    - cypress/test-reports/junit.xml

pipelines:
  default:
  - step:
      name: Prepare dependencies
      caches:
        - npm
        - cypress
        - node
      script:
        - npm ci
        - npx @bahmutov/print-env BITBUCKET # let's see the environment variables right away
  - parallel: # run N steps in parallel
    - step:
        <<: *tests
    - step:
        <<: *tests
    - step:
        <<: *tests
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
```

### Versions
Cypress version 6.5.0
Running locally on MacOS works fine.
Running on Bitbucket pipeline CI is when the issue is encountered.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #15101

### User facing changelog

- Fixed an issue that could cause Cypress to crash with a "RangeError: Maximum call stack size exceeded at _deconstructPacket" error. Most commonly, this occurred when handling network errors with `cy.request()`.

### Additional details

- socket.io v3 upgrade for CT introduced this issue: https://github.com/cypress-io/cypress/issues/15101#issuecomment-828663361
- we only had tests for socket messages containing plaintext
- we missed the path that handles binary messages, which is kinda separate from simpler messages
- this PR adds/fixes encoding/decoding socket messages containing binary, including the request errors that most users see this with
- also upgrades socket.io to v4 - relatively minor breaking change, doesn't affect us, only bumps socket.io-parser from 4.0.2 to 4.0.4

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/request_spec.js [hunk 1]
```diff
@@ -1316,6 +1316,20 @@ describe('src/cy/commands/request', () => {
 
           cy.request({ url: 'http://localhost:1234/foo', timeout: 50 })
         })
+
+        // @see https://github.com/cypress-io/cypress/issues/15101
+        it('can receive timeout errors from the backend', (done) => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/commands/request_spec.js:1321]: I tried this test out on `develop` and it passes, so while it seems like a legit test, I'm not sure it tests this issue.

File: packages/driver/src/cypress/utils.js [hunk 2]
```diff
@@ -194,7 +194,11 @@ module.exports = {
         return `Object{${len}}`
       }
 
-      return this.stringifyActualObj(value)
+      try {
+        return this.stringifyActualObj(value)
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/utils.js:198]: What would cause this to error? Maybe we should have a test for that case.

File: packages/driver/cypress/integration/commands/request_spec.js (hunk 1 above)
Comment (flotwig) [reply packages/driver/cypress/integration/commands/request_spec.js:1321]: Good call, this repro actually was working reliably for me at the start but... I guess something changed at some point, this no longer reliably reproduces the issue.

I've noticed the 2 user-supplied repos are flaky to fail too: https://github.com/iondrimba/cypress_maximum_call_stack https://github.com/TimVee/deconstructPacked-bug

I reverted this test and created a @packages/socket test instead to reliably reproduce the issue.

File: packages/socket/patches/socket.io-parser+4.0.4.patch [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+         return data;
+     if (is_binary_1.isBinary(data)) {
+@@ -26,18 +26,27 @@ function _deconstructPacket(data, buffers) {
+         buffers.push(data);
+         return placeholder;
+     }
+-    else if (Array.isArray(data)) {
++    else if (retvals.has(data)) {
++        return retvals.get(data)
++    }
```
Comment (flotwig) [inline packages/socket/patches/socket.io-parser+4.0.4.patch:27]: this allows us to get a handle on the `newData` objects - socket.io takes care not to modify the incoming packet, so to keep these references correct in a circular object scenario, we must keep a map of data <=> newdata

File: packages/driver/src/cypress/utils.js (hunk 2 above)
Comment (flotwig) [reply packages/driver/src/cypress/utils.js:198]: I noticed while debugging this issue that any circular object logged to command log will cause the test to fail because `stringifyActual` recurses infinitely. This probably isn't the handsomest fix, but it prevents the driver from failing the test due to a max call stack error. I added a test that this succeeds.

**Review by chrisbreiding — APPROVED** [review]

**Comment by iondrimba** [comment]
:trophy: :trophy: :trophy: :trophy: :trophy:

**Comment by pyymenta** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:
