### PR TITLE
Fix gzipped utf-8 .js files getting corrupted

### LINKED ISSUE #1746: Random failures over Regexp: Invalid regular expression
I get very strange non-deterministic errors when opening my website in Cypress. It complains about a failing Regexp, but the weird thing is that this never causes a problem in a normal browser, and in fact, even within the Cypress browser, if I open a new tab and reload the code, it works perfectly. And I also added on Cypress.on('uncaught.exception') to my code, which does not seem to help.

Here's my test script:
```js
const uuid = require('cuid');
Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});

describe('My First Test', function() {
  it('finds the content "type"', function() {
    const id = uuid();
    // cy.wait(30000 * Math.random());
    cy.visit(`https://icchilisrv3.epfl.ch:7000/w948?login=${id}`);

    cy.get('video', { timeout: 90000 });
    cy
      // .wait(10000)
      .then(() => cy.wrap(Cypress.$('video')[0].networkState).should('eq', 2));
    cy.wait(180000);
  });
});
```

Here you see two tabs of the same browser, consistently showing completely different behaviour (even when reloading etc). What's very strange is that when I deploy this in 30 different browsers using Kubernetes, I get half of them failing with this error, and the other half working normally! Perhaps this is a timing issue (the reason for the non-determinism) with some interaction between my code and Cypress test code?

screen shot 2018-05-20 at 14 21 31
screen shot 2018-05-20 at 14 21 00

Here you see examples of failing and successful Cypress runs - these are exactly the same code in different Kubernetes containers: 

screen shot 2018-05-20 at 14 27 06

(in this case, I don't get the error exceptions, because of the uncaught.exception setting, but the behaviour is exactly the same as in interactive mode, making me believe that the problem is identical). 

Reference to [Cypress dashboard run](https://dashboard.cypress.io/#/projects/32bbwc/runs/ba1f5eeb-9b17-4088-a8e7-d6c0c18fd44a/output)

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #1746

The way that we do JS interception is not UTF-8 aware. It can break on character boundaries:

https://github.com/cypress-io/cypress/blob/0e2eb738c6bb45415e9cc7d1bf1819130b508bd8/packages/server/lib/controllers/proxy.coffee#L250-L260

https://github.com/cypress-io/cypress/blob/0e2eb738c6bb45415e9cc7d1bf1819130b508bd8/packages/server/lib/util/security.js#L19-L26

This PR adds utf8-stream to only stream chunks across grapheme boundaries, and implements a replace-stream that will not split graphemes in half.

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/util/replace_stream.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+// UTF-8 grapheme aware stream replacer
+// https://github.com/cypress-io/cypress/pull/4984
+function replaceStream (pattern, replacement, options = { maxTailLength: 100 }) {
+  let tail = ''
+
+  return through(function write (chunk) {
+    chunk = chunk.toString('utf8')
+
+    tail = tail + chunk
+    tail = tail.replace(pattern, replacement)
```
Comment (Halt001) [inline packages/server/lib/util/replace_stream.js]: Without knowing much about Node.js streams or what is actually replaced here, I wonder how are replacements handled that fall over the edge of a chunk?

Comment (Halt001) [reply packages/server/lib/util/replace_stream.js]: I'm not talking about splitting Unicode graphemes on the chunk boundaries, I'm talking about the string replacement here. If the matching string has the first half in one chunk and the second half in the next, the `tail.replace(pattern, replacement)` won't find it. 'chunk boundary friendliness' is one of the features of the original _replacestream_ library.

Comment (Halt001) [reply packages/server/lib/util/replace_stream.js]: After staring at the code some more I see what you mean. Sorry to have bothered you.

File: packages/server/lib/util/replace_stream.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+const splitter = new GraphemeSplitter()
+
+/**
+ * UTF-8 grapheme aware stream replacer
+ * https://github.com/cypress-io/cypress/pull/4984
+ */
+function replaceStream (patterns: RegExp | RegExp[], replacements: string | string[], options = { maxTailLength: 100 }) {
+  if (!Array.isArray(patterns)) {
+    patterns = [patterns]
```
Comment (brian-mann) [inline packages/server/lib/util/replace_stream.ts]: maybe this is typescript foo but can't you just do `patterns = [].concat(patterns)` without the check on the `if(...)` ?

Comment (flotwig) [reply packages/server/lib/util/replace_stream.ts]: If you do that, TS complains because it expects the first arg to `.concat` to be an array, but patterns could be a RegExp.

File: packages/server/test/integration/http_requests_spec.coffee [hunk 3]
```diff
@@ -1007,6 +1009,44 @@ describe "Routes", ->
...
+        .then =>
+          @rp({
+            url: "http://localhost:12345"
+            gzip: true
+          })
+          .then (res) ->
+            expect(res.statusCode).to.eq(200)
+            expect(res.body).to.deep.eq(js)
+
+            Promise.fromCallback (cb) =>
```
Comment (brian-mann) [inline packages/server/test/integration/http_requests_spec.coffee]: This code will NOT execute here if the expectations fail above it - which wouldn't close the server, and could possibly cause additional failures in downstream tests.

If you need to guarantee the server is closed regardless of whether or not the test passes either add a `.finally(...)` or move the server instantiation to a property on the test context like `@server = ...` and close it in an `afterEach` via `if (@server) ...`

File: packages/server/test/unit/LICENSE.md [hunk 4]
```diff
@@ -0,0 +1,34 @@
+Unless mentioned below, all tests are covered by the license in the root of this
```
Comment (brian-mann) [inline packages/server/test/unit/LICENSE.md]: Move this bit into the top of the `replace_stream_spec.js` file since that's the only place that uses it. No need to create an external file, so you can remove this `LICENSE.md` file.

File: packages/server/test/integration/http_requests_spec.coffee [hunk 5]
```diff
@@ -2619,20 +2659,6 @@ describe "Routes", ->
               ## shouldn't be more than 500ms
               expect(reqTime).to.be.lt(500)
 
-              # b = res.body
```
Comment (brian-mann) [inline packages/server/test/integration/http_requests_spec.coffee]: So... I should have left a note indicating why this stuff is here - back in the day I wanted the ability to make modifications to the JS rewriting code and then test out its affect on performance. 

Back then we didn't have a way to capture the performance timings easily - but now we do. Instead of commenting out this code can we write it out to the performance API? Also, it may be worth converting this into another p95 kind of test - because small changes to the regex can have a dramatic impact on the network performance. We actually caused a severe regression that the tests didn't pick up, which is when I wrote this code.

I think there is some test somewhere but its not super sensitive - it basically just checks to ensure that the tests finish within a given time range threshold, which would catch really bad regressions, but it's still not sensitive enough to tell us small changes to the performance. By capturing all the timings via the Performance API we would know when those small changes occurred.

File: packages/server/test/integration/http_requests_spec.coffee (hunk 3 above)
Comment (flotwig) [reply packages/server/test/integration/http_requests_spec.coffee]: good point, switched to using a .finally

File: packages/server/test/integration/http_requests_spec.coffee (hunk 5 above)
Comment (flotwig) [reply packages/server/test/integration/http_requests_spec.coffee]: Does it need to happen in this PR? I can open an issue/add this to the proxy refactor branch (https://github.com/cypress-io/cypress/pull/5136) since it also changes the rewriting stuff somewhat

Comment (brian-mann) [reply packages/server/test/integration/http_requests_spec.coffee]: yes thats fine
