### PR TITLE
fix: change default options for sourceMaps inside WBIP

### LINKED ISSUE #29614: `Eval`ed UserInvocationStack is sometimes off for projects using Typescript 5
### Current behavior

Currently, when a user is running cypress commands that are wrapped inside serializable closures that throw errors, the stack trace line/column is slightly off when running typescript 5 projects. This can be seen inside our `@packages/app` tests when running stack trace validation when validating `cy.intercept()` stack errors inside `reporter.command_errors.cy.ts` 

#### in cypress command log (typescript 5)
Screenshot 2024-06-03 at 2 49 17 PM

#### stack trace when opened in IDE (slight mismatch)  (typescript 5)
Screenshot 2024-06-04 at 12 43 22 PM

This was realized when we updated the monorepo to typescript 5. see https://github.com/cypress-io/cypress/pull/29568/files#r1613972217

### Desired behavior

The code snippet in the command log should match the stack trace that is visited to the user's IDE

#### in cypress command log (typescript 4)
Screenshot 2024-06-04 at 12 48 25 PM

#### stack trace when opened in IDE (slight mismatch)  (typescript 4)
Screenshot 2024-06-04 at 12 48 40 PM

### Test code to reproduce

see `@packages/app` tests when running stack trace validation when validating `cy.intercept()` stack errors inside `reporter.command_errors.cy.ts` 

### Cypress Version

13.10.0

### Node version

v18.17.1

### Operating System

macOS 14.3

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #29614
### Additional details

When updating the monorepo to TypeScript 5 last year, I noticed that the error code frames source maps did not seem quite right. We filed #29614 with the intent to fix it. It turns out that `inlineSourceMap` is what is responsible for this inaccuracy, as it is inlining the transpiled TypeScript into the spec file and not the pure TypeScript source map. To fix this, we are enabling `sourceMap` to `true` for all user configs that are using `@cypress/webpack-preprocessor` (`@cypress/webpack-batteries-included-preprocessor` gets this via downstream impact as it uses `@cypress/webpack-preprocessor`) and setting `inlineSourceMap` to `false`. 

This does NOT fix the custom preprocessor use case, for which we are adding documentation in https://github.com/cypress-io/cypress-documentation/pull/6122 to guide users on how to configure their cypress `tsconfig.json`.This is mainly due to it being very difficult to hook into the TypeScript API to override defaults. The reason `createProgram` inside `@cypress/webpack-preprocessor` was not getting called in TypeScript 5 was because the package is now a true ES Module and exports are no longer modifiable (which is the case with the `esbuild` implemented specification). I have modified `@cypress/webpack-preprocessor` to check for the presence of TypeScript 4 to try and patch `createProgram`, but avoid it for newer versions as we know it will not be successful. I have also improved the logging around `@cypress/webpack-preprocessor` to help diagnose further issues if needed.

 Ideally, we want to find a way to accomplish this in all cases, but for now we are mitigating through the default preprocessor and guiding users on how to configure their source maps. For instance, this doesn't work if the user is on TypeScript 5 and is using `babel-loader` with the `@babel/preset-typescript` configuration. The user in this case would need to set `sourceMap` in their actual config. 

On a semi related note, we only pass a [subset of options](https://github.com/cypress-io/cypress/issues/29614#issuecomment-2722071332) to `ts-loader`, where we should be sending the full user config. Since this change is fairly disruptive, we will be including it in Cypress 15 with #31282

### Steps to test

run the tests in the project with the default `@cypress/webpack-batteries-included-preprocessor`/`@cypress/webpack-preprocessor` or run a standalone project with TypeScript configured and have a command fail inside your cypress test. The codeframe should now be much more accurate

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/6122
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/webpack-batteries-included-preprocessor/index.js [hunk 1]
```diff
@@ -60,14 +26,21 @@ const addTypeScriptConfig = (file, options) => {
...
-  // package using require('tsconfig'), so we alias it as 'tsconfig-aliased-for-wbip'
-  const configFile = require('tsconfig-aliased-for-wbip').findSync(path.dirname(file.filePath))
 
-  const compilerOptions = getTSCompilerOptionsForUser(configFile)
+  const getTsConfig = require('get-tsconfig')
+
+  // returns null if tsconfig cannot be found in the path/parent hierarchy
+  const configFile = getTsConfig.getTsconfig(file.filePath)
+
+  configFile ? debug(`found user tsconfig.json at ${configFile?.path} with compilerOptions: ${JSON.stringify(configFile?.config?.compilerOptions)}`) : debug('no user tsconfig.json found')
```
Comment (AtofStryker) [inline npm/webpack-batteries-included-preprocessor/index.js:43]: we aren't doing anything with this until #31282 except feeding the webpack plugin the tsconfig file path

File: npm/webpack-batteries-included-preprocessor/index.js [hunk 2]
```diff
@@ -77,7 +50,6 @@ const addTypeScriptConfig = (file, options) => {
         loader: require.resolve('ts-loader'),
         options: {
           compiler: options.typescript,
-          compilerOptions,
```
Comment (AtofStryker) [inline npm/webpack-batteries-included-preprocessor/index.js:80]: delegated to @cypress/webpack-preprocessor

File: npm/webpack-preprocessor/index.ts [hunk 3]
```diff
@@ -7,6 +7,39 @@ import webpack from 'webpack'
 import utils from './lib/utils'
 import { overrideSourceMaps } from './lib/typescript-overrides'
 
+const getTsLoaderIfExists = (rules) => {
```
Comment (AtofStryker) [inline npm/webpack-preprocessor/index.ts:10]: any idea if webpack has some type of config utility parsing? This is a bit tedious

File: cli/CHANGELOG.md [hunk 4]
```diff
@@ -7,6 +7,10 @@ _Released 3/12/2025_
 
 - [`Cypress.stop()`](https://on.cypress.io/cypress-stop) is now available to stop the Cypress App on the current machine while tests are running. This can be useful for stopping test execution upon failures or other predefined conditions. Addresses [#518](https://github.com/cypress-io/cypress/issues/518). Addressed in [#31225](https://github.com/cypress-io/cypress/pull/31225).
 
+**Bugfixes:**
```
Comment (jennifer-shehane) [inline cli/CHANGELOG.md]: @AtofStryker Need to move this to a new release.

File: npm/webpack-batteries-included-preprocessor/package.json [hunk 5]
```diff
@@ -27,9 +27,8 @@
     "debug": "^4.3.4",
     "domain-browser": "^4.22.0",
     "events": "^3.3.0",
-    "fs-extra": "^9.1.0",
```
Comment (cacieprins) [inline npm/webpack-batteries-included-preprocessor/package.json:30]: 🎉

File: npm/webpack-preprocessor/index.ts (hunk 3 above)
Comment (cacieprins) [reply npm/webpack-preprocessor/index.ts:10]: Unfortunately, not that I can find. I was hoping to find a JOI or Zod schema, but wasn't able to find anything obvious

**Review by cacieprins — APPROVED** [review]

File: npm/webpack-preprocessor/index.ts [hunk 6]
```diff
@@ -7,6 +7,39 @@ import webpack from 'webpack'
...
+        return use.loader && use.loader.includes('ts-loader')
+      })
+
+      tsLoaderRule = foundRule
+
+      return tsLoaderRule
+    }
+
+    if (_.isObject(rule.use) && rule.use.loader && rule.use.loader.includes('ts-loader')) {
+      // it's an Object
```
Comment (mschile) [inline npm/webpack-preprocessor/index.ts]: Not sure this comment is really that helpful...

File: npm/webpack-preprocessor/index.ts [hunk 7]
```diff
@@ -7,6 +7,39 @@ import webpack from 'webpack'
 import utils from './lib/utils'
 import { overrideSourceMaps } from './lib/typescript-overrides'
 
+const getTsLoaderIfExists = (rules) => {
+  let tsLoaderRule
+
+  rules.some((rule) => {
```
Comment (mschile) [inline npm/webpack-preprocessor/index.ts:13]: Are you able to use `.find` instead of `.some`?

File: npm/webpack-preprocessor/lib/typescript-overrides.ts [hunk 8]
```diff
@@ -1,61 +1,79 @@
...
+          // to generate the right sourcemaps
+          options.sourceMap = sourceMap
 
-    patched = true
+          delete options.inlineSources
+          delete options.inlineSourceMap
+
+          debug('typescript modified createProgram options %o', options)
+
+          // @ts-ignore
```
Comment (mschile) [inline npm/webpack-preprocessor/lib/typescript-overrides.ts]:
```suggestion
          // @ts-expect-error
```

**Review by mschile — APPROVED** [review]
Looks good overall! Added a few comments.

File: npm/webpack-preprocessor/index.ts (hunk 6 above)
Comment (AtofStryker) [reply npm/webpack-preprocessor/index.ts]: i need to add some better comments in here as to what we are checking for

File: npm/webpack-preprocessor/index.ts (hunk 7 above)
Comment (AtofStryker) [reply npm/webpack-preprocessor/index.ts:13]: not exactly, mainly because the way the rules can be configured wouldn't be uniform, which is why `tsLoaderRule` is more so the normalized rule regardless of how its defined. `.some()` gets us the same effect though as it should shortcircuit once found.

File: npm/webpack-preprocessor/lib/typescript-overrides.ts (hunk 8 above)
Comment (AtofStryker) [reply npm/webpack-preprocessor/lib/typescript-overrides.ts]: I think I can remove this entirely!
