### PR TITLE
fix: hasBinary flakiness

### LINKED ISSUE #16476: Cypress runner crashes after a cy.request() command times out
### Current behaviour
The Cypress test runner crashes with a "RangeError: Maximum call stack size exceeded" error a few seconds after a cy.request() command times out.

This happens with both `cypress open` and `cypress run`.

### Desired behavior
cy.request() commands that time out should not crash the test runner.

### Test code to reproduce
Demo repo and instructions here: [demo repo](https://github.com/gabi-dobritescu/exceed-stack-size/tree/master)

Here's a copy of the relevant files from the project:

package.json
```javascript
{
  "name": "stack-size-exceeded",
  "version": "1.0.0",
  "description": "A demo project to show the stack size exceeded error with Cypress",
  "main": "index.js",
  "author": "Gabi Dobritescu",
  "license": "MIT",
  "private": true,
  "scripts": {
    "start": "node app.js",
    "cypress:open": "node_modules\\.bin\\cypress open"
  },
  "devDependencies": {
    "cypress": "^7.3.0",
    "express": "^4.17.1"
  }
}
```

cypress.json
```javascript
{
  "responseTimeout": 2000
}
```

app.js
```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  setTimeout(() => {
    res.send('Hello World!')
  }, 5000)

})

app.listen(port, () => {
  console.log("Example app listening at http://localhost:${port}")
})
```

quick-test.spec.js
```javascript
describe("Demo test for the exceed stack size error", () => {
  it("should gracefully fail the test when api request times out", () => {
    cy.request("http://localhost:3000/").then(response => {
      expect(response.body).to.equal("Hello World!");
    })
  })
})
```

To reproduce the issue:

`yarn install`

`yarn start`

`yarn cypress:open`

Run the `quick-test.spec` test. After the test completes (failing as expected because the request timed out before the server responded) wait for a few seconds (anywhere between 2 to 5 second usually).
The runner crashes with the following error and stacktrace:

```javascript
RangeError: Maximum call stack size exceeded
    at isBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:23:18)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:46:9)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    ...
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:40:17)
    at Object.hasBinary (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\is-binary.js:55:63)
    at Encoder.encode (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io-parser\dist\index.js:38:29)
    at Client._packet (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\client.js:169:44)
    at Socket.packet (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:160:21)
    at C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\socket\node_modules\socket.io\dist\socket.js:274:18
    at C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\lib\socket-base.js:325:28
    at tryCatcher (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\dobrites\AppData\Local\Cypress\Cache\7.3.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

### Versions
7.3.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #16476 

### User facing changelog

Fixes flaky `hasBinary` infinite recursive call.

### Additional details
- Why was this change necessary? => In some CI platforms and Windows, infinite recursive `hasBinary` call crashes runner.
- What is affected by this change? => N/A
- Any implementation details to explain? => It seems that in some platforms and some cases, `Error` objects are cyclic. I removed the cyclic references.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated? => it's flaky and I believe it would be hard to create a test for this.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@sainthkh This is a user facing issue documented here: https://github.com/cypress-io/cypress/issues/16476 For some reason, this error occurs in our tests, but seems to be isolated to outside contributors (which is why you likely see it all the time). It doesn't occur in our internal PRs and we're not sure why that is.

File: packages/server/lib/socket-base.ts [hunk 1]
```diff
@@ -394,7 +395,35 @@ export class SocketBase {
...
+                },
+                indent,
+              )
+
+              cache = null
+
+              return retVal
+            }
+
+            error = JSON.parse(safeStringify(error))
```
Comment (sainthkh) [inline packages/server/lib/socket-base.ts:423]: * I didn't create any utility function for this feature because it is used once here. 
* I didn't put this part into `errors.clone()` because I guess we don't need to run `isCircular` every time when there is an error.

**Comment by sainthkh** [comment]
flaky failures.

**Review by flotwig — CHANGES_REQUESTED** [review]
@sainthkh we maintain a patch for `socket.io-parser` to allow it to send circular objects through socket.io: https://github.com/cypress-io/cypress/blob/develop/packages/socket/patches/socket.io-parser%2B4.0.4.patch

It relies on using `circular-json` and on preventing infinite recursion where applicable. There are tests in `@packages/socket` that test this behavior as well.

Instead of using `isCircular` and breaking circles when errors are serialized, I think it should be fixed at the root of the issue by figuring out what's wrong with the patch to `hasBinary`.

You can regenerate the patch file by running `yarn patch-package socket.io-parser` inside of `@packages/socket` after making changes to the files in `node_modules`.

File: packages/server/lib/socket-base.ts [hunk 2]
```diff
@@ -394,7 +395,35 @@ export class SocketBase {
...
+              let cache: any[] | null = []
+              const retVal = JSON.stringify(
+                obj,
+                (key, value) => {
+                  return typeof value === 'object' && value !== null
+                    ? cache!.includes(value)
+                      ? undefined // Duplicate reference found, discard key
+                      : cache!.push(value) && value // Store value in our collection
+                    : value
+                },
```
Comment (flotwig) [inline packages/server/lib/socket-base.ts:414]: most likely we need to do this exact same type of thing, but in the `socket.io-parser` patch

Comment (sainthkh) [reply packages/server/lib/socket-base.ts]: It wasn't necessary. I explained why below.

File: packages/socket/patches/socket.io-parser+4.0.4.patch [hunk 3]
```diff
@@ -146,7 +146,11 @@ index 4b7c234..95469f7 100644
 +    known.push(obj)
      if (Array.isArray(obj)) {
          for (let i = 0, l = obj.length; i < l; i++) {
-             if (hasBinary(obj[i])) {
+-            if (hasBinary(obj[i])) {
++            if (hasBinary(obj[i], known)) {
+                 return true;
+             }
+         }
```
Comment (sainthkh) [inline packages/socket/patches/socket.io-parser+4.0.4.patch:153]: The cause of the problem was the incorrect recursive call of `hasBinary` inside check Array section. Without `known` argument being passed, when checking arrays that have circular references, `hasBinary` always starts from fresh.

Comment (flotwig) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:153]: :facepalm: x 10000000

**Comment by pyymenta** [comment]
:pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray: :pray:

File: packages/socket/patches/socket.io-parser+4.0.4.patch [hunk 4]
```diff
@@ -146,7 +146,11 @@ index 4b7c234..95469f7 100644
...
 @@ -43,10 +49,10 @@ function hasBinary(obj, toJSON) {
      if (obj.toJSON &&
```
Comment (amakhrov) [inline packages/socket/patches/socket.io-parser+4.0.4.patch:155]: Random observation: this `if` condition is always false, because it assumes the `hasBinary` funciton can be called with only one argument. It was possible in the original code (optional `toJson` argument) , but not possible with the patched version

Comment (sainthkh) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: I don't think so.

The full code is like below:

```js
function hasBinary(obj, known = []) {
    if (!obj || typeof obj !== "object") {
        return false;
    }
    if (known.includes(obj)) {
        return false
    }
    known.push(obj)
    if (Array.isArray(obj)) {
        for (let i = 0, l = obj.length; i < l; i++) {
            if (hasBinary(obj[i], known)) {
                return true;
            }
        }
        return false;
    }
    if (isBinary(obj)) {
        return true;
    }
    if (obj.toJSON &&
        typeof obj.toJSON === "function" &&
        arguments.length === 1) {
        return hasBinary(obj.toJSON(), known);
    }
    for (const key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key) && hasBinary(obj[key], known)) {
            return true;
        }
    }
    return false;
}
```

When we pass `[1, {}]` as `obj`. `hasBinary(1, [[1, {}]])` returns `false` but `hasBinary({}, [[1, {}], 1])` returns `true`.

Comment (amakhrov) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: Sorry I probably was not very clear. I specifically meant the `if` condition that handles a very special use case, when an object has `toJSON` method to be called.
This `if` condition checks that `aruments.length === 1` - which is never the case in the patched version (both your examples have `arguments.length === 2` because of the `known` argument).

Comment (sainthkh) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: I checked [the original code here](https://github.com/socketio/socket.io-parser/blob/75530b4dcdced9138d51a0b7b782c8f89cdf3899/lib/is-binary.ts#L33-L66) and it seems that the second arg, `toJson` is a dead arg (it doesn't affect the flow of the code) and it might exist because of the backward compatibility. 

```ts
export function hasBinary(obj: any, toJSON?: boolean) {
  if (!obj || typeof obj !== "object") {
    return false;
  }

  if (Array.isArray(obj)) {
    for (let i = 0, l = obj.length; i < l; i++) {
      if (hasBinary(obj[i])) {
        return true;
      }
    }
    return false;
  }

  if (isBinary(obj)) {
    return true;
  }

  if (
    obj.toJSON &&
    typeof obj.toJSON === "function" &&
    arguments.length === 1
  ) {
    return hasBinary(obj.toJSON(), true);
  }

  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key) && hasBinary(obj[key])) {
      return true;
    }
  }

  return false;
}
```

As for an object which has `toJSON` function, it's properly handled with the code below:

```js
    if (obj.toJSON &&
        typeof obj.toJSON === "function" &&
        arguments.length === 1) {
        return hasBinary(obj.toJSON(), known);
    }
```

Comment (sainthkh) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: Sorry. Forget the old comment. I misunderstood your comment again. 

I believe this can be fixed by removing `arguments.length === 1`. Maybe I need to create a new test case.

Comment (sainthkh) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: @amakhrov I opened the issue at #17988.

Comment (amakhrov) [reply packages/socket/patches/socket.io-parser+4.0.4.patch:155]: awesome!
