### PR TITLE
Fix cy.clearCookie, fix HTTP redirect behavior, fix cy.visit HTTPS baseurl behavior

### LINKED ISSUE #4990: Bad crash loading a site in Chrome v76
Cypress v3.4.1 on Mac

- clone https://github.com/cypress-io/3rd-party-error
- `npm install`
- `npm run cy:open`
- pick Chrome 76
- click on `spec.js`

The website starts loading and then Chrome just crashes. Running with all debug logs shows this

```
  cypress:server:server Getting remote state: { auth: undefined, props: { port: '443', tld: 'com', domain: 'theguardian' }, origin: 'https://www.theguardian.com', strategy: 'http', visiting: undefined, domainName: 'theguardian.com', fileServer: null } +0ms
  cypress:server:server sending request with options { auth: null, failOnStatusCode: true, retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, method: 'GET', body: null, headers: { accept: 'text/html,*/*' }, timeout: 30000, gzip: false, url: 'https://www.theguardian.com/uk/', onBeforeReqInit: [Function: runPhase], followRedirect: [Function: followRedirect] } +2ms
  cypress:server:cookies getting:cookies { url: 'https://www.theguardian.com/uk/' } +54ms
  cypress:server:cookies received get:cookies [] +3ms
  cypress:server:request sending request as stream { auth: null, failOnStatusCode: true, retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, method: 'GET', body: null, headers: { accept: 'text/html,*/*', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' }, timeout: 30000, gzip: false, url: 'https://www.theguardian.com/uk/', onBeforeReqInit: [Function: runPhase] } +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://www.theguardian.com/uk/' } +10s
  cypress:network:connect beginning getAddress { hostname: 'www.theguardian.com', port: 443 } +222ms
  cypress:network:connect got addresses { hostname: 'www.theguardian.com', port: 443, addresses: [ { address: '151.101.1.111', family: 4 }, { address: '151.101.65.111', family: 4 }, { address: '151.101.129.111', family: 4 }, { address: '151.101.193.111', family: 4 } ] } +35ms
  cypress:network:agent got family { family: 4, href: 'https://www.theguardian.com/uk/' } +47ms
  cypress:server:request setting request jar cookies [ { key: 'GU_mvt_id', value: '11457', expires: '2019-11-13T15:11:05.000Z', domain: 'theguardian.com', path: '/', secure: true, hostOnly: false, creation: '2019-08-15T15:11:05.348Z', lastAccessed: '2019-08-15T15:11:05.348Z', url: 'https://www.theguardian.com/uk/' }, { key: 'GU_geo_continent', value: 'NA', domain: 'www.theguardian.com', path: '/', secure: true, hostOnly: true, creation: '2019-08-15T15:11:05.352Z', lastAccessed: '2019-08-15T15:11:05.352Z', url: 'https://www.theguardian.com/uk/' } ] +207ms
  cypress:server:cookies set:cookie { name: 'GU_mvt_id', value: '11457', path: '/', domain: 'theguardian.com', secure: true, expirationDate: 1573657865, url: 'https://www.theguardian.com/uk/' } +213ms
  cypress:server:cookies received set:cookie { name: 'GU_mvt_id', value: '11457', path: '/', domain: '.theguardian.com', secure: true, httpOnly: false, expiry: 1573657865 } +3ms
  cypress:server:cookies set:cookie { name: 'GU_geo_continent', value: 'NA', path: '/', secure: true, url: 'https://www.theguardian.com/uk/' } +0ms
  cypress:server:cookies received set:cookie { name: 'GU_geo_continent', value: 'NA', path: '/', domain: 'www.theguardian.com', secure: true, httpOnly: false } +3ms
  cypress:server:cookies getting:cookies { url: 'http://www.theguardian.com/uk' } +0ms
  cypress:server:cookies received get:cookies [] +3ms
  cypress:server:request setting request jar cookies [ { key: 'GU_mvt_id', value: '11457', expires: '2019-11-13T15:11:05.000Z', domain: 'theguardian.com', path: '/', secure: true, hostOnly: false, creation: '2019-08-15T15:11:05.348Z', lastAccessed: '2019-08-15T15:11:05.348Z', url: 'https://www.theguardian.com/uk/' }, { key: 'GU_geo_continent', value: 'NA', domain: 'www.theguardian.com', path: '/', secure: true, hostOnly: true, creation: '2019-08-15T15:11:05.352Z', lastAccessed: '2019-08-15T15:11:05.408Z', url: 'http://www.theguardian.com/uk' } ] +56ms
  cypress:server:cookies set:cookie { name: 'GU_mvt_id', value: '11457', path: '/', domain: 'theguardian.com', secure: true, expirationDate: 1573657865, url: 'https://www.theguardian.com/uk/' } +42ms
  cypress:server:cookies received set:cookie { name: 'GU_mvt_id', value: '11457', path: '/', domain: '.theguardian.com', secure: true, httpOnly: false, expiry: 1573657865 } +3ms
  cypress:server:cookies set:cookie { name: 'GU_geo_continent', value: 'NA', path: '/', secure: true, url: 'http://www.theguardian.com/uk' } +1ms
  cypress:server:file get values from /Users/gleb/Library/Application Support/Cypress/cy/production/cache +10s
  cypress:server:file attempt to get lock on /Users/gleb/Library/Application Support/Cypress/cy/production/cache +1ms
  cypress:server:file gettin lock succeeded or failed for /Users/gleb/Library/Application Support/Cypress/cy/production/cache +1ms
  cypress:server:file read /Users/gleb/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:file read succeeded or failed for /Users/gleb/Library/Application Support/Cypress/cy/production/cache +1ms
  cypress:server:file attempt to unlock /Users/gleb/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:file unlock succeeded or failed for /Users/gleb/Library/Application Support/Cypress/cy/production/cache +0ms
  cypress:server:api request to url: POST https://api.cypress.io/exceptions with params: {"body":{"err":{"name":"","message":"Failed to parse or set cookie named \"GU_geo_continent\".","stack":""},"version":"3.4.1","osName":"darwin","osVersion":"16.7.0","osCpus":[{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":78434340,"nice":0,"sys":49035920,"idle":433832150,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":10064400,"nice":0,"sys":5712330,"idle":545318150,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":68456150,"nice":0,"sys":27425700,"idle":465285890,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":10342860,"nice":0,"sys":5694470,"idle":545033540,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":68563630,"nice":0,"sys":27420570,"idle":465158450,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":10351460,"nice":0,"sys":5674280,"idle":545022680,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":68428900,"nice":0,"sys":27303080,"idle":465386820,"irq":0}},{"model":"Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz","speed":2500,"times":{"user":10352590,"nice":0,"sys":5673090,"idle":545007160,"irq":0}}],"osMemory":{"free":50679808,"total":17179869184}},"headers":{"x-os-name":"darwin","x-cypress-version":"3.4.1"}} and token: undefined +0ms
  cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/exceptions' } +176ms
  cypress:network:connect beginning getAddress { hostname: 'api.cypress.io', port: 443 } +189ms
{ [Error: Failed to parse or set cookie named "GU_geo_continent".] name: undefined }
undefined
  cypress:server:browsers killing browser process +4s
  cypress:network:connect got addresses { hostname: 'api.cypress.io', port: 443, addresses: [ { address: '104.25.214.23', family: 4 }, { address: '104.25.215.23', family: 4 }, { address: '2606:4700:20::6819:d617', family: 6 }, { address: '2606:4700:20::6819:d717', family: 6 } ] } +19ms
```

### LINKED ISSUE #5367: cy.visit does not send headers / change HTTP method when baseUrl contains `:80`
### Current behavior:

`cy.visit({ url, method, headers })` does not appear to honour the `method`, or `headers`

### Desired behavior:

`cy.visit({ url, method, headers })` should send the specified method and headers.

### Steps to reproduce: (app code and test code)

```
cy.visit({ 
  url: '/ui', 
  method: 'POST',
  headers: {
    'mock-user': JSON.stringify(mockUser)
  }
});
```

I include an annotated Cypress debug log:

debug-log

Changing the method to `GET` still results in the headers not being sent 

### Versions

I tested Cypress 3.4.1 and 3.2.0.
Ubuntu LTS
Chrome 77

### UPDATE: Cause tracked down to: https://github.com/cypress-io/cypress/issues/5367#issuecomment-542329058

### LINKED ISSUE #5432: Cookies not being sent in redirect in 3.5.0
### Current behavior:

I'm not sure what the issue is, but our Single Sign On Recipe is failing here: https://dashboard.cypress.io/#/projects/6p53jw/runs/32571/failures 

Screen Shot 2019-10-23 at 6 21 12 PM

### Desired behavior:

The Single Sign On should log in and reroute to dashboard page.

### Steps to reproduce: (app code and test code)

1. Pull down https://github.com/cypress-io/cypress-example-recipes
2. Bump `cypress` dependency to `3.5.0`
3. `npm i` in root directory
4. `cd examples/logging-in__single-sign-on`
5. `npm start`
6. in a new tab `npm run cypress:open`

Smallest amount of code to run:

```js
it('can authenticate with cy.request', function () {
  cy.getCookie('cypress-session-cookie').should('not.exist')
  cy.request({
    method: 'POST',
    url: 'http://auth.corp.com:7075/login',
    qs: {
      redirectTo: 'http://localhost:7074/set_token',
    },
    form: true,
    body: {
      username: 'jane.lane',
      password: 'password123',
    },
  })
  .then((resp) => {
    expect(resp.status).to.eq(200)
    expect(resp.body).to.include('<h1>Welcome to the Dashboard!</h1>')
  })
})
```

### Versions

3.5.0

### LINKED ISSUE #5436: cy.request() fails in 3.5.0
### Current behavior:

A simple cy.request() test failed after upgrading to 3.5.0. 
The URL has two 302 redirects.

https://XXX/backoffice  (302)-> https://XXX/backoffice/  (302)-> https://XXX/backoffice/login.zul (200)

```js
          cy.request({
            url: link,
            retryOnStatusCodeFailure: true,
            retryOnNetworkFailure: true,
          });
```

Cypress Error:

```
CypressError: cy.request() failed trying to load:

https://XXX/backoffice

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > true

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://XXX/backoffice

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: true
    at maybeWrapAsError (C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\nodeback.js:38:50
    at Chrome._handleMessage (C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:194:13)
    at Receiver.receiverOnMessage (C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:194:13)
    at Receiver.dataMessage (C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:422:14)
    at C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\ws\lib\receiver.js:379:23
    at C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:298:9
    at C:\Users\mriehema\AppData\Local\Cypress\Cache\3.5.0\Cypress\resources\app\packages\server\node_modules\ws\lib\permessage-deflate.js:376:7
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:560:8)
```

### Desired behavior:

The same tests works in Cypress 3.4.1. 
Calling the URL https://XXX/backoffice manually works too (200 after two 302).

### Versions

Cypress 3.5.0 with Chrome
Windows 10 and macOS

### LINKED ISSUE #5453: `clearCookie` not working anymore in 3.5.0 under certain baseUrls
Our code used to do exactly what the documentation states:

```js
cy.setCookie('foo', 'bar')
cy.clearCookie('foo')
cy.getCookie('foo').should('be.null')
```

This works with 3.4.1 and started failing with 3.5.0. 

Since there are tickets about `clearCookies` not working this was the only way we actually could delete a specific cookie. Now even that doesn't work any longer.

### PR DESCRIPTION
**Pull request by flotwig**
- Really closes #5432
- Closes #5453
- Closes #5436
- Closes #5367
- Closes #4990

### User facing changelog

* Fixed a bug where `cy.clearCookie` would not act as expected under certain `baseUrl`s. #.5453
* Fixed a bug where HTTP redirects could cause strange behavior, including cookies not being set as expected, leading to authentication issues and other problems in tests. #.5436, #.5432
* Fixed a bug where Cypress would not send the expected headers or request body in a `cy.visit` to an HTTPS URL using the default port, 443. #.5367
* Fixed a bug where Cypress would crash with the error `Failed to parse or set cookie named "foo".` when loading certain websites. #.4990 

### Additional details

- Previously, when doing Network.deleteCookies in response to a `clear:cookie` request, we would directly use the user-supplied domain.
	- However, the real domain Chrome expects may be different.
	- This PR changes `clear:cookie` to use the result of Network.getAllCookies to get the correct `domain` parameter for the Network.deleteCookies call
- [x] Even after #.5432 was fixed, there was still an issue with setting cookies on redirects
	- This is because something was seriously wrong with the way we were doing req.init - after a request finished all of it's redirects, I could see the entire redirect stack being popped off, as if the redirects were happening again in reverse
	- This really messed up setting cookies on the correct domain
	- I found a PR to `request` that would let us return a Promise from `options.followRedirect`, so we don't need our undocumented, hard-to-understand `req.init` hack anymore: https://github.com/request/request/pull/2647
	- Created a cypress-io/request repository to hold patches to `request`, now that the real `request` is unmaintained: https://github.com/cypress-io/request
	- After updating the redirect code in request.coffee to simply return a Promise instead of doing the `req.init` stuff, it works as desired: 7c0304f 
	- This should fix #.5436
- [x] It looks like `cy.getCookies` is only returning cookies for the current domain, not all domains. This is probably wrong. #1547
	- [x] Does this also affect `cy.clearCookies`? #408 
	- It appears that the Cypress cookies commands are forced to use the current superdomain as the domain for all cookie operations, which seems like an error - how are users supposed to see cookies not for the exact current superdomain?
	- Talked to @brian-mann about this. It's due to the old limitations from the extension API for why it's like this today, so any changes would need to be backwards-compatible with current API usage.
		- Added `cy.clear/getCookies({ domain: null })` to clear/return ALL cookies for testing
- [x] Fixed #.5367 by ensuring that `buffers` always adds the default port to a URL when storing/retrieving a buffer
- Fixed a bug where the behavior of setting cookies could differ depending on if `cy.visit` caused a navigation or not.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/server/test/e2e/2_cookies_spec.coffee [hunk 1]
```diff
@@ -65,23 +65,118 @@ onServer = (app) ->
...
+          }
+          spec: "cookies_spec_baseurl.coffee"
+          snapshot: true
+          expectedExitCode: 0
+          onRun: (exec) =>
+            exec({
+              originalTitle: "e2e cookies with baseurl"
+              onStdout: (stdout) ->
+                stdout.replace(new RegExp(otherDomain, 'g'), '<2nd domain>')
+                .replace(new RegExp(baseDomain, 'g'), '<base domain>')
```
Comment (brian-mann) [inline packages/server/test/e2e/2_cookies_spec.coffee]: i think this can go away right

**Comment by nids2307** [comment]
which cypress version will have this fix incorporated?

**Comment by flotwig** [comment]
@nids2307 3.6.1, which will be released later today.
