### PR TITLE
fix: cy.intercept adds access-control-expose-headers for cors requests

### LINKED ISSUE #15050: Stubbing requests via cy.intercept doesnt work the same way as cy.route
### Current behavior

The request I want to stub looks like so with the old cy.route
```js
cy.route({
			method: 'POST',
			url: '**/sessions',
			status: 200,
			response: {
				success: true,
			},
			headers: {
				'x-token': "token",
			},
		})
```
With this, I get the "x-token" returned as a header back to the client. alongside other headers.
```
connection: "keep-alive"
content-length: "16"
content-type: "application/json; charset=utf-8"
date: "Thu, 11 Feb 2021 12:58:34 GMT"
vary: "Accept-Encoding",
x-token: "token"
```

Trying out the new cy.intercept API, 

```js
cy.intercept('**/sessions', {
			body: { success: true },
			headers: {
				x-token: "token"
			},
		})
```

This is what I get back

```
content-type: "application/json"
```
### Desired behavior

I expect the x-token to be part of the headers returned in the response. 
If Im missing anything, please let me know, thanks

### Test code to reproduce

https://github.com/Tevinthuku/cypress-test-tiny
https://codesandbox.io/s/modest-hofstadter-gl5xj?file=/src/App.js

### Versions

Cypress v 6.4.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #15050

### User facing changelog

`cy.intercept()` adds `access-control-expose-headers` header for CORS requests. 

### Additional details
- Why was this change necessary? => This causes some unnecessary confusion for some use cases. 
- What is affected by this change? => N/A
- Any implementation details to explain? => When there is a custom header, we add `access-control-expose-headers` automatically to avoid confusion.

### How has the user experience changed?

**Before:** If it's a CORS request, you need to remember to add `access-control-expose-headers` to get header information from `cy.intercept()`.

```js
cy
.intercept('/cors*', {
  body: { success: true },
  headers: {
    'access-control-expose-headers': 'x-token', // This line is required
    'x-token': 'token',
  },
})
```

**After:** Cypress automatically handles it.

```js
cy
.intercept('/cors*', {
  body: { success: true },
  headers: {
    // It isn't necessary.
    'x-token': 'token',
  },
})
```

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/net-stubbing/lib/server/util.ts [hunk 1]
```diff
@@ -104,6 +104,28 @@ export function setDefaultHeaders (req: CypressIncomingRequest, res: IncomingMes
...
+      'content-type',
+      'expires',
+      'last-modified',
+      'pragma',
+    ].includes(header.toLowerCase())
+  })
+
+  // We should not override the user's access-control-expose-headers setting.
+  if (hasCustomHeader && !res.headers['access-control-expose-headers']) {
+    setDefaultHeader('access-control-expose-headers', _.constant('*'))
```
Comment (flotwig) [inline packages/net-stubbing/lib/server/util.ts:126]: since we're already iterating through the headers object, it seems like this could actually be set to the list of custom header names, but this works fine too
