### PR TITLE
Warn when a percent-encoded URL is passed to cy.route

### LINKED ISSUE #2372: cy.route() doesn't recognize % sign
### Current behavior:

When an XHR request to a route with a param that contains a `%` sign is done, a route that's configured to look for this request doesn't see it. Note that when I try this in my environment I can actually see the XHR request going out, when I try to reproduce it based on the example I can't even see the XHR request.

### Desired behavior:

Routes with a `%` sign in the param are recognized.

### Steps to reproduce:

See branch https://github.com/RikBoeykens/cypress-test-tiny/tree/route-percentage-ssie

### Versions

Cypress 3.1.0

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #2372

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Just kind of seems like if we can detect that it's encoded then why not just decode it for them?

**Comment by flotwig** [comment]
@jennifer-shehane What if the user is literally trying to do `cy.route('%25')`, to match URLs like "http://example.com/%25" (encoded: "http://example.com/%2525")? There would be no way to express that if we decoded it for them.

File: packages/driver/src/cy/commands/xhr.coffee [hunk 1]
```diff
@@ -403,6 +403,14 @@ module.exports = (Commands, Cypress, cy, state, config) ->
           ## aliases subject
           options.response = aliasObj.subject
 
+        url = getUrl(options)
+
+        urlString = url.toString()
+
+        ## https://github.com/cypress-io/cypress/issues/2372
+        if (decodedUrl = decodeURI(urlString)) and urlString != decodedUrl
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/commands/xhr.coffee]: I think you need to handle malformed URIs here, at least I don't see this being handled before this code. `decodeURI` will throw on a malformed URI. 

Can you write a test when passing in `http://example.com/%E0%A4%A` to the url option? If not being handled here...it should be handled somewhere...

Comment (flotwig) [reply packages/driver/src/cy/commands/xhr.coffee]: Ooh, good point. It seems to throw if you percent-encode an unsupported codepoint: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

I guess the good thing to do would be to just continue if decodeURI throws, assuming that because they have potentially "invalid codepoints" in the URI, they're not intending to use percent-encoding anyways and there's no need to warn.
