### PR TITLE
Forcibly select disabled selects + warn on select when optgroup disabled

### LINKED ISSUE #107: Allow {force: true} option to disable error checking on select & select options
Allow `{force: true}` to be passed to `cy.select` (just as type & check commands), that disables error checking so that you can "select" a disabled select or option.

**Example Code**

`index.html`

```html
<html>
<body>
  <select id="disabled-select" disabled>
    <option value="456">apples</option>
    <option value="457">oranges</option>
    <option value="458">bananas</option>
  </select>

  <select id="disabled-option">
    <option value="456">apples</option>
    <option value="457" disabled>oranges</option>
    <option value="458">bananas</option>
  </select>
</body>
</html>
```

`spec.js`

``` javascript
it('test disabled select', () => {
  cy.visit('index.html')
  cy.get('#disabled-select').select('oranges')
})

it('test disabled option', () => {
  cy.visit('index.html')
  cy.get('#disabled-option').select('oranges')
})
```

Screen Shot 2020-04-27 at 10 13 05 AM

### LINKED ISSUE #7226: When calling `.select()` on an option that's in a disabled optgroup - does not select option
### Current behavior:

We warn when attempting to select a disabled select or option, but not when option is within a disabled optgroup. So if you try to select an option within a disabled optgroup - it just has a `null` value. 

### Desired behavior:

If the option is within an optgroup that is disabled, the option is also disabled and should be warned. 

### Test code to reproduce

`spec.js`

```js
it('works', () => {
  cy.visit('index.html')
  cy.get('#optgroup-enabled').select('okra')
    .invoke('val').should('eq', 'okra')   // passes
  cy.get('#optgroup-disabled').select('banana')
    .invoke('val').should('eq', 'banana') // fails
})
```

`index.html`

```html
<html>
<body>
  <select id="optgroup-enabled">
    <optgroup label="Veggies">
      <option value="okra">Okra</option>
      <option value="zucchini">Zucchini</option>
    <optgroup>
  </select>
  <select id="optgroup-disabled">
    <optgroup label="Fruits" disabled>
      <option value="banana">Banana</option>
      <option value="apple">Apple</option>
    <optgroup>
  </select>
  <script>
  </script>
</body>
</html>
```

Screen Shot 2020-05-05 at 11 15 34 AM

### Versions

4.5.0

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- closes #7226 
- partially addresses #107 

### User facing changelog

- We now throw an error when attempting to `.select()` an `<option>` within a disabled `<optgroup>`.
- You can now pass `force: true` to `.select()` to select options within a disabled `<select>`.

### Additional details

- **You still cannot force select a `<select>` where the `<option>` or `<optgroup>` is disabled. This will error.**
- This was initially an attempt to address #107, but selecting disabled options and optgroups turned out to be more effort than initially thought. The UI will look like it's selected it, but in actuality the `<select>` value will not be set to any option value that is `disabled`. 
- Removed this from scope of the PR and just pushed some other minor fixes that were found.

#### Disabled optgroups before

Screen Shot 2020-05-05 at 11 18 54 AM

#### Disabled optgroups after

Screen Shot 2020-05-05 at 11 18 24 AM

#### Force select a disabled `<select>` before

Screen Shot 2020-05-05 at 11 27 01 AM

#### Force select a disabled `<select>` after

Screen Shot 2020-05-05 at 11 26 18 AM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2779

### CODE REVIEW

File: packages/driver/src/cy/commands/actions/select.js [hunk 1]
```diff
@@ -150,6 +150,16 @@ module.exports = (Commands, Cypress, cy) => {
           }
         })
 
+        _.each(optionEls, ($el) => {
+          if ($el.parent('optgroup').prop('disabled')) {
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/actions/select.js:154]:
```suggestion
          if ($el.closest('optgroup').prop('disabled')) {
```

It might not be valid html, but I tried it out and it's possible to have an `<option>` nested deeper inside an `optgroup`, so we should guard against that and not assume it's a direct child.

File: packages/driver/src/cy/commands/actions/select.js [hunk 2]
```diff
@@ -246,7 +256,9 @@ module.exports = (Commands, Cypress, cy) => {
 
             change.initEvent('change', true, false)
 
-            return options.$el.get(0).dispatchEvent(change)
+            options.$el.get(0).dispatchEvent(change)
+
+            return undefined
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/actions/select.js:261]: Not returning at all returns undefined, so this seems superfluous.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]
For the changelog, it says

> We now warn when attempting to .select() an <option> within a disabled <optgroup>.

But I think it would be more accurate to say we improved the error message in that case, since it's not really a warning.

**Comment by jennifer-shehane** [comment]
@chrisbreiding Yeah, well, actually we were never erroring before so it's a brand new error, but yes, the terminology should be 'error' instead of 'warn'.

File: packages/driver/src/cy/commands/actions/select.js (hunk 2 above)
Comment (jennifer-shehane) [reply packages/driver/src/cy/commands/actions/select.js:261]: Yeah, I guess I prefer being specific about intended returns.

**Review by chrisbreiding — APPROVED** [review]
