### PR TITLE
Electron upgrade

### LINKED ISSUE #5475: Cypress headless hangs in second spec after previous goes back in history
### Current behavior:

In **headless** electron (headed electron works fine), the process hangs forever when doing the below steps.

Basically, you do something like this in `a.spec.js`:

```js
cy.visit(`https://google.com`)
cy.window().then(win => {
  win.history.pushState({}, null, `/`)
});
cy.go(-1);
```

and in `b.spec.js` you retrieve an elem:

```js
cy.get('.item');
```

I know that the 2nd spec file isn't really a valid use case (since we haven't yet loaded a page), but I've wanted to create the smallest reproducible test case.

I'm not really sure what's going on, but there are several significant things that must be done:

1. load some page
2. push a new state to history
3. go back `window.location.go(-1)`
4. and in the next spec (**must be a different file so that Cypress runner closes & opens new window**), retrieve a DOM elem.
    
    This last step is weird because before I managed to narrow it down to this smallest reproduction, I've been doing much more in my real-world spec, and it failed only on one particular DOM retrieval. Don't have a clue, but it also reproduces when I simply query the DOM, without loading a page.
5. hangs, forever (?). `DEBUG=cypress:*` doesn't show anything interesting, I think --- no new messages are logged after it hangs.

### Desired behavior:

Should not hang.

### Steps to reproduce: (app code and test code)

https://github.com/dwelle/cypress-test-tiny/tree/dwelle_hang

and run:

```
npx cypress run --spec cypress/integration/a.spec.js,cypress/integration/b.spec.js
```

The url links to the branch directly. Refer to README, if need be.

### Versions

- cypress `3.5.0` (`3.4.1` works)
- Win 7

### LINKED ISSUE #5852: Upgrade Electron to 7.1.4
PR: https://github.com/cypress-io/cypress/pull/5849

### Current behavior:

Electron version is 5.0.10

### Desired behavior:

Latest Electron is 7.1.4, use Electron 7.1.4

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5475 
- Closes #5852

### User facing changelog

- Upgraded Electron to 7.1.4. This bumps the internal Node version to 12.8.1 and the internal Chromium version to 78.0.3904.113.

### Additional details

- [x] depends on #5850 getting merged - most of the diff is this

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/browsers/electron.coffee [hunk 1]
```diff
@@ -148,6 +142,23 @@ module.exports = {
       debug("debugger attached")
     catch err
       debug("debugger attached failed %o", { err })
+      throw err
+
+    originalSendCommand = webContents.debugger.sendCommand
```
Comment (chrisbreiding) [inline packages/server/lib/browsers/electron.coffee]: You could use [_.wrap](https://lodash.com/docs/4.17.15#wrap) here. 

```coffeescript
webContents.debugger.sendCommand = _.wrap(webContents.debugger.sendCommand, (originalSendCommand, message, data) -> 
```

Comment (flotwig) [reply packages/server/lib/browsers/electron.coffee]: I kinda prefer doing it without lodash, it's only 1 more line of code and it doesn't require the reader to know the function signature of `_.wrap` or how `_.wrap` binds the wrapped function.

File: circle.yml [hunk 2]
```diff
@@ -19,11 +28,12 @@ defaults: &defaults
     COLUMNS: 100
     LINES: 24
 
+
 executors:
   # the Docker image with Cypress dependencies and Chrome browser
   cy-doc:
     docker:
-      - image: cypress/browsers:node12.0.0-chrome73
+      - image: cypress/browsers:node12.8.1-chrome78-ff70
```
Comment (jennifer-shehane) [inline circle.yml]: Is this PR updating the Node version? Aren't we using 12.0.0, don't we want to test against that?

Also, if this is a convenience thing - probably highlights why our docker images combinations are problematic for our own users. :P

Comment (flotwig) [reply circle.yml]: This PR updates the bundled Node version to 12.8.1 (Electron 5 -> 7). The `node` version we use in CI needs to match this, since the unit + integrations tests (of Electron code) all run in `node` in CI, not `electron`. We could use `electron-mocha` to eliminate this requirement, but currently that's the way it is.
