### PR TITLE
fix(fixtures): cache null and undefined encodings separately

### LINKED ISSUE #32274: Cache keys collide between `null` and `undefined` encodings
### Current behavior

https://github.com/cypress-io/cypress/pull/32151#discussion_r2264007120

### Desired behavior

There should be no collisions.

### Test code to reproduce

https://github.com/cypress-io/cypress/pull/32151#discussion_r2264007120

### Cypress Version

N/A

### Node version

N/A

### Operating System

N/A

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by adamalston**
- Closes https://github.com/cypress-io/cypress/issues/32274

### Additional details

This change restores the correct behavior that was inadvertently changed in https://github.com/cypress-io/cypress/pull/32151. I added testing to verify the fix and prevent another regression.

### Steps to test

Revert the fix and check that the test fails.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [~] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [~] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@adamalston Can you allow outside updates to your PR? There are conflicts with current dev that need to be resolved.

File: packages/driver/src/cy/commands/fixtures.ts [hunk 1]
```diff
@@ -100,7 +100,7 @@ export default (Commands, Cypress, cy, state, config) => {
         options.encoding = args[0]
       }
 
-      const cacheKey = `${fixture}${NULL_SEP}${options.encoding || ''}`
+      const cacheKey = `${fixture}${NULL_SEP}${options.encoding}`
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/fixtures.ts:103]: my fault on this one 🥴 . Thank you for fixing this!

**Review by AtofStryker — APPROVED** [review]

**Comment by adamalston** [comment]
> Can you allow outside updates to your PR? There are conflicts with current dev that need to be resolved.

I'd like to clarify before enabling that option.

When I allowed edits from maintainers on https://github.com/cypress-io/cypress/pull/32151, a regression was committed directly to my branch without my consultation. This pull request exists specifically to fix that regression. I'm trying to take more ownership of these changes so that doesn't happen again.

The contributing docs create a contradictory situation:

- https://github.com/cypress-io/cypress/blob/01683b8f80eea3e334d48ce3ab92efa5b85e0b54/CONTRIBUTING.md?plain=1#L485
- https://github.com/cypress-io/cypress/blob/01683b8f80eea3e334d48ce3ab92efa5b85e0b54/CONTRIBUTING.md?plain=1#L488

How can I be responsible for resolving conflicts if I'm required to allow others to make changes I cannot review or control?

I'd prefer to resolve the conflicts myself and push an update to maintain accountability and ownership. This ensures:

- I can review all changes before they're committed.
- No regressions are introduced without my knowledge.
- Code quality remains consistent with my intent.

I recognize there are scenarios where I can't resolve conflicts due to issues elsewhere in the repo (e.g., https://github.com/cypress-io/cypress/pull/32161#issuecomment-3171913544). I'm still not sure why the fix for that issue was committed to my branch instead of being submitted in another pull request to `develop`, since that's where the issue originated. In those cases, why can't I explicitly call them out and ask for assistance rather than granting blanket write access?

I previously asked in https://github.com/cypress-io/cypress/pull/32151#issuecomment-3152163185:

> Why can't contributors trigger CI?

Understanding the technical constraints here would help me better navigate these situations. If there are specific limitations that require maintainer intervention, I'd appreciate knowing what they are so I can be a better contributor. I appreciate the tools and technologies you guys have created. We can't work together effectively, though, if I operate in a black box as a contributor.

Allowing edits is what created this problem in the first place. I want to work collaboratively through the review process while maintaining control over the changes to ensure quality and prevent regressions.

**Comment by AtofStryker** [comment]
@adamalston I am sorry I missed your comments in https://github.com/cypress-io/cypress/pull/32151#discussion_r2263330697 . I likely missed the notification as the team and myself are prepping for Cypress 15. 

I am going to explain some of these details the best I can. The reason contributors are not allowed to trigger CI directly because there is a possibility of security issues being injected into the code that could have broader ramifications before maintainers have a chance to review the code. This is to protect everyone.

Contributors take a different flow in CI all together, which was some of the issues with failures unrelated to your changes (i.e. component tests failing due to vite refreshing optimized dependencies), which I fixed directly on your branch, as with the develop merge issue, because frankly it's convenient and hard to reproduce some contributor issues from a maintainer context. 

I am sorry the regression was introduced, but there were issues on some of the other PRs that you stated you were unable to address. As a maintainer, I am going to use my best judgement and commit fixes directly to your branch and notify you about them, likely as a comment with a git commit references. If the change was significantly large, I would open a PR to your branch, but honestly, this seems unnecessary given the size and scope of the changes. 

This is a partnership. I took time out of my day to make several changes to your code to make sure there were no regressions for windows users and the code works as expected. We have a duty to make sure enhancements work for everyone. In the future, if you'd like to maintain total protection over the branch without being able to make the necessary fixes, we will likely have no choice but to close the PR.

**Comment by adamalston** [comment]
Thank you for the response. I will keep those details in mind in the future.
