### PR TITLE
fix: don't display run passing status if Cloud org is over run limit

### LINKED ISSUE #26528: Improve/correct Debug Page UI when viewing run with no failures but organization is over the record limit
*Current behavior*

If a Cloud organization has gone over the record limit for the subscription they have, then the Debug page will not return any failed tests in the `testsForReview` field. The UI will show a message indicating that the account is over the limit and provide a CTA for how to upgrade the account.  

When viewing a run on the Debug page with no failures, then a success message is shown to indicate that all tests have passed.  If both of these states occur at the same time, then the messages are stacked.  This UI does not look good and is confusing to users. (see screenshot)

*Desired behavior*

Only show the `DebugOverLimit` component and hide the `DebugPassed` component in this scenario.  This code is in the `DebugPageDetails` component.

https://github.com/cypress-io/cypress/blob/39bd67e3829602842cc7812f10d7dfe8b009e160/packages/app/src/debug/DebugPageDetails.vue#L25-L32

### PR DESCRIPTION
**Pull request by astone123**
- Closes #26528

### Additional details

When a run's results are hidden because the cloud organization is over its test result limit for the month, we shouldn't show the passing state and should only show the "over limit" message on the debug page for that run. Having both messages on screen doesn't look great and could be confusing.

### Steps to test

Check out the test that I wrote. Alternatively, spin up a project and record enough runs to go over your free limit on Cypress Cloud. Verify that when you have a passing run selected that is hidden because you are over the limit, that you don't see the passing message of "Well Done! All your tests passed." on screen, and only see the over limit message.

### How has the user experience changed?

Before: look at the attached issue

After:
Screenshot 2023-04-18 at 11 23 20 AM

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/debug/DebugPageDetails.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
     v-if="['PASSED', 'OVERLIMIT'].includes(status) || isHidden"
     class="flex flex-col flex-grow w-full p-12 justify-center items-center align-middle "
   >
-    <DebugPassed v-if="status === 'PASSED'" />
+    <DebugPassed v-if="status === 'PASSED' && !isHidden" />
```
Comment (lmiller1990) [inline packages/app/src/debug/DebugPageDetails.vue:25]: I tried to take look to find out what constitutes `isHidden` - looks like this comes from the Cloud, going to assume that this value is correctly calculated (validating it is outside the scope of this repo and PR).

Do you have any context/knowledge of how this is calculated?

Code looks good!

**Review by lmiller1990 — APPROVED** [review]

File: packages/app/src/debug/DebugPageDetails.vue (hunk 1 above)
Comment (warrensplayer) [inline packages/app/src/debug/DebugPageDetails.vue:25]: You could have switched the order with the `DebugOverLimit` below and then added a `v-else-if="status === 'PASSED'"`, but this works just fine.

**Review by warrensplayer — APPROVED** [review]
Looks good.  Just one comment to consider for the future.
