### PR TITLE
fix: clarify svelte 4 is supported

### LINKED ISSUE #27465: CT detect and support Svelte version 4
### What would you like?

Experimental support for Svelte 3 should be extended to support Svelte 4. (See npm module [svelte](https://www.npmjs.com/package/svelte).)

### Why is this needed?

Attempting to update to Svelte 4 with component testing shows a warning.

image

### Other

The example https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/svelte runs successfully with Svelte 4, despite the warning.

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/27465

### Additional details

Svelte 4 seems to work fine.

### Steps to test

Try a Svelte 4 app and scaffold CT

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/scaffold-config/src/dependencies.ts [hunk 1]
```diff
@@ -148,7 +148,7 @@ export const WIZARD_DEPENDENCY_SVELTE: Cypress.CypressComponentDependency = {
   package: 'svelte',
   installer: 'svelte',
   description: 'Cybernetically enhanced web apps',
-  minVersion: '^3.0.0',
+  minVersion: '^3.0.0 || ^=4.0.0',
```
Comment (MikeMcC399) [inline packages/scaffold-config/src/dependencies.ts]: Referring to https://github.com/npm/node-semver I can't work out the significance of the `^=`  construct, although it appears to work, possibly because it says under https://github.com/npm/node-semver#versions:

> A leading "=" or "v" character is stripped off and ignored.

Probably `^4.0.0` is more what is intended, meaning it matches any major version 4 or `4.x.x`.

`^=` is used for the other frameworks too, so perhaps this should be separately revisited?

**Review by MikeMcC399 — COMMENTED** [review]
I successfully checked against a fully configured `svelte@4.1.2` and there was no longer a warning with
`npx cypress run --component`  👍🏻 

I did not check scaffolding from scratch with no component testing configured.

File: packages/scaffold-config/src/dependencies.ts (hunk 1 above)
Comment (MikeMcC399) [inline packages/scaffold-config/src/dependencies.ts]:
```suggestion
  minVersion: '^3.0.0 || ^4.0.0',
```

for simplification.

Comment (mike-plummer) [reply packages/scaffold-config/src/dependencies.ts]: Wow, good 👀 @MikeMcC399 . I think you're right; seems like the `^=` syntax happens to work through a happy little accident, and we've been copy-pasting it as new versions are added.

I vote we keep this as-is for now just so this can go out the door, and I'll write a housekeeping ticket to clean the syntax up

**Review by mike-plummer — APPROVED** [review]

File: packages/scaffold-config/src/dependencies.ts (hunk 1 above)
Comment (mike-plummer) [reply packages/scaffold-config/src/dependencies.ts]: #27475

Comment (MikeMcC399) [reply packages/scaffold-config/src/dependencies.ts]: I checked using `^4.0.0` with Svelte `4.1.2` and it works for both pre-configured Svelte and if Svelte is installed after prompting by Cypress component testing.

Comment (MikeMcC399) [reply packages/scaffold-config/src/dependencies.ts]: @mike-plummer 

- Thanks for cross-checking! I would also not hasten to make changes to something which is currently working, even if the syntax is not correct. Your issue #27475 has captured the problem in any case.

Comment (lmiller1990) [reply packages/scaffold-config/src/dependencies.ts]: Sounds good let's do that

(I just copied the other examples)

**Comment by lmiller1990** [comment]
I committed the recommendation, need one more ✅ and we ship this.

**Review by astone123 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@lmiller1990 

I don't see a [cli/CHANGELOG.md](https://github.com/cypress-io/cypress/blob/develop/cli/CHANGELOG.md) entry. Would you want to add one for the addition of Svelte 4 support with this PR?

**Comment by lmiller1990** [comment]
@MikeMcC399 I suppose - I'm surprised CI is okay, I guess we don't require one for `chore`. Maybe this should be `feat` 🤔 

I don't have too much time to do that and re-run CI, I think this is probably okay.

**Comment by MikeMcC399** [comment]
@lmiller1990 

I wouldn't want to hold up this change, however it does have a (positive) user-visible impact in that the warning for Svelte 4 no longer appears.

According to the docs, Cypress is already supposed to support Svelte 3 and later. Given that it is classified as Alpha support only for component testing, then maybe some of the formalities, like officially declaring a feature minor version, don't need to be handled so strictly?

https://docs.cypress.io/guides/component-testing/svelte/overview

image

It's your call for whatever you think is most practical.

**Comment by lmiller1990** [comment]
Sure, we can add a line in the changelog. I'll do this by end of week and get this merged.

**Comment by MikeMcC399** [comment]
@lmiller1990 

> Sure, we can add a line in the changelog. I'll do this by end of week and get this merged.

This note from last week has not yet been implemented.

**Review by jordanpowell88 — APPROVED** [review]

**Review by jordanpowell88 — APPROVED** [review]

**Review by MikeMcC399 — APPROVED** [review]
All my comments have now been addressed. Thanks!
