### PR TITLE
Catch invalid env variable 1621

### LINKED ISSUE #1621: Setting CYPRESS_ENV to an unexpected value leads to errors
Per this issue: https://github.com/cypress-io/cypress/issues/1614

A user set `process.env.CYPRESS_ENV` to an unexpected value and caused Cypress to error / crash  when talking to the API.

We should check that its set to a valid value and provide a good error message when its set incorrectly.

### PR DESCRIPTION
**Pull request by bahmutov**
I added catching `CYPRESS_ENV` in both cli and server. There is a little bit of code duplication, but since we are not sharing code between CLI and the server I did not want to change it

- close #1621
- prevents #5053

### CODE REVIEW

File: cli/__snapshots__/cli_spec.js [hunk 1]
```diff
@@ -168,3 +168,30 @@ exports['cli -v no binary version 1'] = `
...
+  
+  -------
+
+`
+
+exports['cli CYPRESS_ENV catches environment "foo" 1'] = `
+  code: 11
+  stderr:
+  -------
+  We have detected unknown or unsupported CYPRESS_ENV value
```
Comment (jennifer-shehane) [inline cli/__snapshots__/cli_spec.js]: Taking a shot at this - I know this makes it less descriptive for 'internal' dev, but maybe more descriptive to users.

```
Reserved word "CYPRESS_ENV" was used.

Remove "CYPRESS_ENV" variable and run Cypress again.
```

Comment (bahmutov) [reply cli/__snapshots__/cli_spec.js]: I would change it a little bit because "reserved word" does not really describe it
```
Environment variable with reserved name "CYPRESS_ENV" was used.

Remove "CYPRESS_ENV" variable and run Cypress again.
```

Comment (jennifer-shehane) [reply cli/__snapshots__/cli_spec.js]: @bahmutov ^ I like yours best, especially specifying that it is an environment variable.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
This still needs some work. See notes below:

**Current error**
screen shot 2018-05-15 at 12 37 30 pm

The error should be printed in this red color: 

screen shot 2018-05-15 at 12 40 15 pm

**Recommended error messaging and spacing**
```
$ CYPRESS_ENV=myenv node ./cli/bin/cypress run --dev

Environment variable used with reserved name "CYPRESS_ENV".

Remove the "CYPRESS_ENV" variable and run Cypress again.
----------

CYPRESS_ENV=myenv
----------

Platform: darwin (14.5.0)
Cypress Version: 0.0.0
```

**Comment by bahmutov** [comment]
So our typical error is red because it is thrown as an error. In this case I don't throw an error, but show it and then exit with specific code (which allows us to easily debug and test it). For now, I switched the first part of the error message to red color. I think this is enough for the user to understand.

Screen Shot 2019-08-29 at 5 09 07 PM

File: cli/__snapshots__/cli_spec.js [hunk 2]
```diff
@@ -354,3 +354,32 @@ exports['shows help for run --foo 1'] = `
...
+  
+  -------
+
+`
+
+exports['cli CYPRESS_ENV catches environment "foo" 1'] = `
+  code: 11
+  stderr:
+  -------
+  Environment variable with reserved name "CYPRESS_ENV" was used.
```
Comment (jennifer-shehane) [inline cli/__snapshots__/cli_spec.js]:
```suggestion
  The environment variable with the reserved name "CYPRESS_ENV" is set.
```

File: cli/__snapshots__/cli_spec.js [hunk 3]
```diff
@@ -354,3 +354,32 @@ exports['shows help for run --foo 1'] = `
...
+
+  Remove "CYPRESS_ENV" variable and run Cypress again.
```
Comment (jennifer-shehane) [inline cli/__snapshots__/cli_spec.js]:
```suggestion
  Unset the "CYPRESS_ENV" environment variable and run Cypress again.
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
This is better with the red :D

File: cli/__snapshots__/cli_spec.js (hunk 3 above)
Comment (bahmutov) [reply cli/__snapshots__/cli_spec.js]: I have updated the error message, are there other things to review?

**Review by jennifer-shehane — APPROVED** [review]
