### PR TITLE
fix: Add new flags and preferences for Chrome

### LINKED ISSUE #25608: Disable the "save address" popup in Chrome
### What would you like?

When my tests fills out an address form with Chrome as the browser, the following prompt pops up:
image

It would be great if this could be disabled altogether for cypress.

### Why is this needed?

It overlaps the test window and has to be closed manually each time.

### Other

During my google search, I found different ways this could be implemented:
- [`autofill.profile_enabled`](https://stackoverflow.com/questions/74376413/disabling-save-address-chrome-browser-popups-using-c-sharp-selenium)
- [`profile.default_content_setting_values.notifications`](https://stackoverflow.com/questions/74543316/selenium-how-to-disable-chrome-save-address-prompt)

Not sure if any of those actually work, but might be worth a try.

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes https://github.com/cypress-io/cypress/issues/25608

### Additional details

We kept encountering this address save popup in Chrome when preparing for the CyConf demo. This add Chrome default preferences that include disabling the address and credit card save popups. 

- Additionally, I walked through every flag outlined in [this spreadsheet](https://docs.google.com/spreadsheets/d/1n-vw_PCPS45jX3Jt9jQaAhFqBY6Ge1vWF_Pa0k7dCk4/edit?gid=1265672696#gid=1265672696) and added what may be relevant for us to pass by default. 
- I also walked through [EVERY Chrome preference available](https://source.chromium.org/chromium/chromium/src/+/main:components/policy/test/data/pref_mapping/) to see if any others may be relevant for automation and added ones that seemed relevant. 

### Steps to test

- Pull down https://github.com/cypress-io/cypress-swag
- Run 'npm i'
- Run 'npm run dev'
- Run 'cypress open'
- Choose the only specfile - have tests run and ensure the address popup does not show in this branch.

#### Before

image

#### After

No popup!

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

---

> [!NOTE]
> Disables Chrome autofill popups by introducing default Chrome preferences, merges/writes them before launch, expands default Chromium flags, and adds comprehensive unit tests.
> 
> - **Browser launch (Chrome)**:
>   - Add `'_getDefaultChromePreferences'` and `'_getChromePreferencesWithDefaults'`; merge defaults with on-disk/user prefs via `'_mergeChromePreferences'` and write final prefs before launch (`'_writeChromePreferences'`).
>   - Defaults disable address/credit-card save popups and suppress security/promotions warnings; add debug logs and export new helpers.
> - **Chromium flags**:
>   - Expand disabled features and default flags (e.g., `GlobalMediaControls`, `MediaRouter`, `OptimizationHints`, `InterestFeedContentSuggestions`, `LensOverlay`, `disable-domain-reliability`, `disable-field-trial-config`).
> - **Tests**:
>   - Add unit tests covering default prefs generation, merging, writing behavior, `IGNORE_CHROME_PREFERENCES`, and launch integration; update stubs/protocol usage.
> - **Changelog**:
>   - Note autofill popup suppression and added Chrome flags/preferences under Bugfixes.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4bec6a541799593e5c57a3fb1deec882650a7caf. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/server/lib/browsers/chrome.ts [hunk 1]
```diff
@@ -76,6 +99,12 @@ const _getChromePreferences = (userDir: string): Bluebird<ChromePreferences> =>
       throw err
     })
   }))
+  .then((existingPrefs) => {
+    // Merge default preferences with existing preferences
+    const defaultPrefs = _getDefaultChromePreferences()
+
+    return _mergeChromePreferences(defaultPrefs, existingPrefs)
+  })
```
[the remark this answers is not in the document]
Comment (jennifer-shehane) [reply packages/server/lib/browsers/chrome.ts]: This is intentional to how it should work

File: packages/server/lib/util/chromium_flags.ts [hunk 2]
```diff
@@ -1,12 +1,34 @@
 const disabledFeatures = [
```
Comment (jennifer-shehane) [inline packages/server/lib/util/chromium_flags.ts:1]: Some of this was just alphabetizing and also adding new flags

File: packages/server/test/unit/browsers/chrome_spec.js [hunk 3]
```diff
@@ -955,5 +976,402 @@ describe('lib/browsers/chrome', () => {
...
+      fs.readJson.withArgs('/foo/Local State').resolves({ local: 'value' })
+
+      return chrome._getChromePreferencesWithDefaults('/foo')
+      .then((result) => {
+        expect(result).to.deep.eq(mockDefaults)
+      })
+      .finally(() => {
+        mockDefaultPrefs.restore()
+      })
+    })
```
[the remark this answers is not in the document]
Comment (jennifer-shehane) [reply packages/server/test/unit/browsers/chrome_spec.js:1073]: Already addressed this

File: packages/server/test/unit/browsers/chrome_spec.js [hunk 4]
```diff
@@ -955,5 +956,413 @@ describe('lib/browsers/chrome', () => {
...
+        '/profile/dir/Local State',
+        sinon.match({
+          browser: {
+            fake_local_state: {
+              value: 'value',
+            },
+          },
+        }),
+      )
+    })
```
[the remark this answers is not in the document]
Comment (jennifer-shehane) [reply packages/server/test/unit/browsers/chrome_spec.js:1390]: Already addressed

File: cli/CHANGELOG.md [hunk 5]
```diff
@@ -9,6 +9,8 @@ _Released 10/20/2025 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed an issue where command snapshots were not correctly displayed in Studio. Addressed in [#32808](https://github.com/cypress-io/cypress/pull/32808).
```
Comment (AtofStryker) [inline cli/CHANGELOG.md:12]: is this just adding a missing change item?

File: packages/server/lib/browsers/chrome.ts [hunk 6]
```diff
@@ -78,6 +101,17 @@ const _getChromePreferences = (userDir: string): Bluebird<ChromePreferences> =>
   }))
 }
 
+// Reads raw preferences from disk and merges them with defaults
+const _getChromePreferencesWithDefaults = (userDir: string): Bluebird<ChromePreferences> => {
```
Comment (AtofStryker) [inline packages/server/lib/browsers/chrome.ts]: are we able to make this function async and just await? Really not an immediate concern but this file will need to be refactored likely in the near future

File: packages/server/test/unit/browsers/chrome_spec.js [hunk 7]
```diff
@@ -955,5 +976,419 @@ describe('lib/browsers/chrome', () => {
...
+      const originalPrefs = {
+        default: {},
+        defaultSecure: {},
+        localState: {},
+      }
+
+      // Get the default preferences that should be written
+      const defaultChromePrefs = chrome._getDefaultChromePreferences()
+
+      expect(chrome._writeChromePreferences('/foo', originalPrefs, defaultChromePrefs)).to.eventually.equal()
```
Comment (AtofStryker) [inline packages/server/test/unit/browsers/chrome_spec.js]: is there supposed to be a value in `to.eventually.equal()`?

Comment (AtofStryker) [reply packages/server/test/unit/browsers/chrome_spec.js]: might be cleaner to `await` the output then assert on the prefs

File: cli/CHANGELOG.md (hunk 5 above)
Comment (jennifer-shehane) [reply cli/CHANGELOG.md:12]: I thought that it should be the first item in the Bugfixes as it feels most important, so I moved it.

File: packages/server/test/unit/browsers/chrome_spec.js (hunk 7 above)
Comment (jennifer-shehane) [reply packages/server/test/unit/browsers/chrome_spec.js]: Addressed here: https://github.com/cypress-io/cypress/pull/32811/commits/f2ce594dc8b8c17cfac778ae9bde0836cfc7eab0

File: packages/server/lib/browsers/chrome.ts (hunk 6 above)
Comment (jennifer-shehane) [reply packages/server/lib/browsers/chrome.ts]: Addressed here: https://github.com/cypress-io/cypress/pull/32811/commits/f2ce594dc8b8c17cfac778ae9bde0836cfc7eab0

File: cli/CHANGELOG.md [hunk 8]
```diff
@@ -9,6 +9,8 @@ _Released 10/20/2025 (PENDING)_
...
+- Chrome's autofill popup is now disabled when filling address and credit card forms during test execution. We also added some other Chrome flags and preferences that are common when automating browsers. Fixes [#25608](https://github.com/cypress-io/cypress/issues/25608). Addressed in [#32811](https://github.com/cypress-io/cypress/pull/32811).
 - Fixed an issue where grouped command text jumps up and down when expanding and collapsing in the command log. Addressed in [#32757](https://github.com/cypress-io/cypress/pull/32757).
 - Fixed an issue where command snapshots were not correctly displayed in Studio. Addressed in [#32808](https://github.com/cypress-io/cypress/pull/32808).
```
Comment (jennifer-shehane) [inline cli/CHANGELOG.md]:
```suggestion
```

**Review by AtofStryker — APPROVED** [review]
