### PR TITLE
fix: use 'ca' and 'cafile' npm config options for binary download

### LINKED ISSUE #8825: .npmrc 'cafile' option should be honored by binary postinstall
### Current behavior
When developing, it is very convenient to have a repository-defined `.npmrc` file with all the custom options. We use self-signed certificates for the binary repository mirror which we have set via `cypress_download_mirror` in the `.npmrc`. We also have `cafile` set to our root certificate file and use that when running `npm install` and such.

When running `npm install cypress` - the https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js ignores the `cafile` configuration even if it exists and only takes the environment configuration.

A workaround is to set the `NODE_EXTRA_CA_CERTS` variable, but that is a global solution and we might have several separate cafiles for different projects.

### Desired behavior
https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/download.js should honor the `cafile` configuration and use the specified certificate if it is set in the `.npmrc` configuration when it is being run.

### Test code to reproduce
Not easy to reproduce via a singular repo (requires self-signed certificates and registries). Will try to do it if needed.

### PR DESCRIPTION
**Pull request by minijus**
* Closes #8825

### User facing changelog
fix: use 'ca' and 'cafile' npm config options for binary download in postinstall

### Additional details
It was not possible to use custom `cypress_download_mirror` host that uses self-signed certificate. Honouring/using `ca` and `cafile` options in `.npmrc` will allow such use cases.

### How has the user experience changed?
N/A

### PR Tasks
* [x] Have tests been added/updated?

### CODE REVIEW

**Comment by minijus** [comment]
Tests to be added to https://github.com/cypress-io/cypress/blob/develop/cli/test/lib/tasks/download_spec.js

**Comment by jennifer-shehane** [comment]
Shouldn’t we read the ca values set from npm or yarn for this setting rather than adding an entirely new env var to read?

**Comment by minijus** [comment]
> Shouldn’t we read the ca values set from npm or yarn for this setting rather than adding an entirely new env var to read?

Reading `npm_config_ca` and `npm_config_cafile` would work, but also could introduce breaking changes for people who use custom npm registry (with self-signed certificate), but default mirror for Cypress.

Let me know if I should change it.

**Comment by minijus** [comment]
@jennifer-shehane any feedback on this? Had you a chance to take internal discussion if this should be changed to get it merged?

**Comment by flotwig** [comment]
@minijus does `CYPRESS_DOWNLOAD_MIRROR_CAFILE` accomplish the same thing as setting the `NODE_EXTRA_CA_CERTS` environment variable? If so, I think it would be preferable to document the usage of `NODE_EXTRA_CA_CERTS` to accomplish this, instead of merging this PR.

**Comment by flotwig** [comment]
Docs for NODE_EXTRA_CA_CERTS: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

**Comment by minijus** [comment]
> @minijus does `CYPRESS_DOWNLOAD_MIRROR_CAFILE` accomplish the same thing as setting the `NODE_EXTRA_CA_CERTS` environment variable? If so, I think it would be preferable to document the usage of `NODE_EXTRA_CA_CERTS` to accomplish this, instead of merging this PR.

Working state can be achieved by using `NODE_EXTRA_CA_CERTS`. However, this would require every developer to set it manually. While having distributed `.npmrc` file inside repository with correct configuration does not require anything from developers. This is somewhat an issue in bigger organizations.

I would still argue that certain solution which would allow using self-signed TLS certificate on `CYPRESS_DOWNLOAD_MIRROR` is needed.

As written before, there are at least two options:

- Respect `ca` and `cafile` options from `.npmrc` when custom mirror host used. Could introduce breaking changes, when npm registry uses self-signed cert, but custom Cypress mirror doesn't.
```
ca=...
cafile=./cafile.crt
cypress_download_mirror=https://example.com
```
- Introduce additional options `CYPRESS_DOWNLOAD_MIRROR_CA` and `CYPRESS_DOWNLOAD_MIRROR_CAFILE`. No breaking changes and allows to use self-signed TLS cert on Cypress mirror host while options are distributed via `.npmrc`.
```
cypress_download_mirror_ca=...
cypress_download_mirror_cafile=./cafile.crt
cypress_download_mirror=https://example.com
```

**Comment by minijus** [comment]
@chrisbreiding @Bkucera please let me know if anything should be changed for this implementation. I would gladly fix it according to your feedback.

This issue become real stopper in our organisation where every developer uses corporate proxy and at the same time internal mirror registry uses self-signed certificate.

File: cli/lib/tasks/download.js [hunk 1]
```diff
@@ -54,6 +54,20 @@ const getBaseUrl = () => {
...
 
+const getCA = () => {
+  let ca
+
+  if (util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CA')) {
+    ca = [util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CA')]
+  }
+
+  if (util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CAFILE')) {
+    ca = (ca || []).concat(fs.readFileSync(util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CAFILE')).toString())
```
Comment (flotwig) [inline cli/lib/tasks/download.js:65]: There needs to be error handling around this file read, so the CLI doesn't just crash with ENOENT if the file doesn't exist. Also, use the promise API `fs.readFile` instead of the sync method.

File: cli/lib/tasks/download.js [hunk 2]
```diff
@@ -54,6 +54,20 @@ const getBaseUrl = () => {
   return defaultBaseUrl
 }
 
+const getCA = () => {
+  let ca
+
+  if (util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CA')) {
+    ca = [util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CA')]
```
Comment (flotwig) [inline cli/lib/tasks/download.js:61]: So this is the use case of embedding the entire CA cert in an environment variable? Is that common?

File: cli/lib/tasks/download.js [hunk 3]
```diff
@@ -54,6 +54,20 @@ const getBaseUrl = () => {
   return defaultBaseUrl
 }
 
+const getCA = () => {
+  let ca
+
+  if (util.getEnv('CYPRESS_DOWNLOAD_MIRROR_CA')) {
```
Comment (flotwig) [inline cli/lib/tasks/download.js:60]: How does this read from `.npmrc`?

**Review by flotwig — CHANGES_REQUESTED** [review]
Hey @minijus, sorry for the lack of communication on this PR. I've reread your comments and can see the need for this now. The PR looks solid, just a couple of minor things.

File: cli/lib/tasks/download.js (hunk 3 above)
Comment (minijus) [reply cli/lib/tasks/download.js:60]: When node runs it reads `.npmrc` and sets values on global variable - `process.env.npm_config_*`.
`util.getEnv` already leverages this to retrieve other env settings: https://github.com/cypress-io/cypress/blob/develop/cli/lib/util.js#L455

File: cli/lib/tasks/download.js (hunk 2 above)
Comment (minijus) [reply cli/lib/tasks/download.js:61]: I have followed `npm` config pattern. It accepts either `cafile` or `ca`.

https://docs.npmjs.com/cli/v7/using-npm/config#ca
https://docs.npmjs.com/cli/v7/using-npm/config#cafile

In previous [comment](https://github.com/cypress-io/cypress/pull/8877#issuecomment-721598739) I have explained why using standard `ca` and `cafile` config values from `npm` could potentially be a breaking change. Of course, I am happy to change back to `ca` and `cafile` if you think that following `npm` standard with slight risk of breaking change is better option.

File: cli/lib/tasks/download.js (hunk 1 above)
Comment (minijus) [reply cli/lib/tasks/download.js:65]: Will do the change a bit later tomorrow.

**Review by flotwig — APPROVED** [review]
> In order to make it non-breakable there is new env variable `CYPRESS_DOWNLOAD_USE_CA` introduced that determines if download script reads `ca` and `cafile` options. This env variable could be removed with future major version release making `cypress` honouring npm config out of the box.

Nice, I like where this PR ended up. If you want to open a PR for changing this default, we could mark it for 8.x.

---

This PR LGTM, but could you open up a PR in `cypress-documentation` as well? I think somewhere around this section could use a couple sentences describing how CYPRESS_DOWNLOAD_USE_CA works: https://docs.cypress.io/guides/getting-started/installing-cypress#Mirroring

**Comment by flotwig** [comment]
Whoops, accidentally merged this before getting docs - @minijus don't worry about the docs PR, I'll get it ready, since we're releasing in about 15 minutes over here :sweat_smile:

**Comment by flotwig** [comment]
@minijus I've documented the feature in this commit: https://github.com/cypress-io/cypress-documentation/commit/a2bc7ed2d0b63c7a7dc87884221b785b517f512f If you see an issue with the way it is documented, feel free to open a PR over there.
