### PR TITLE
fix: cy.type in hidden inputs, contenteditable selections

### LINKED ISSUE #5835: cy.clear({ force: true }) only deletes first character of hidden input in 3.5.0
### Current behavior:

`.clear({ force: true })` only deletes the first character of a hidden input's initial `value`.

### Desired behavior:

`.clear({ force: true })` should delete all characters of a hidden input's initial `value`.

### Steps to reproduce: (app code and test code)

https://github.com/mpetrovich/cypress-test-tiny ([compare](https://github.com/cypress-io/cypress-test-tiny/compare/master...mpetrovich:master))

Given:

```html
<input type="text" value="initial value" style="visibility: hidden">
```

This assertion fails:

```js
cy.get('input').clear({ force: true }).should('have.value', '')
```

With error:
```
CypressError: Timed out retrying: expected '<input>' to have value '', but the value was 'nitial value'
```

Note: Issue persists when input is hidden with `style="display: none"` as well.

### Versions

These versions have been confirmed to be affected:
v3.7.0
v3.6.1
v3.6.0
v3.5.0

These versions have been confirmed to NOT be affected:
v3.4.1
v3.4.0
v3.3.2

### PR DESCRIPTION
**Pull request by kuceb**
fix #5835 cy.type with force:true on hidden inputs (regression from 3.5.0)
fix cy.type in contenteditable with selections (regression from #5854 develop, unreleased)

### User facing changelog
- fix regression introduced in `3.5.0` with `.type({ force: true })` on hidden inputs #5835

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 1]
```diff
@@ -2157,14 +2234,6 @@ describe('src/cy/commands/actions/type', () => {
         it('correct events in contenteditable', () => {
           const ce = cy.$$('[contenteditable]:first')
 
-          const keydown = cy.stub().callsFake((e) => {
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: this was redundant, tested above already

**Review by jennifer-shehane — COMMENTED** [review]
I confirmed that the code here does fix the issue originally opened.

**Review by bahmutov — APPROVED** [review]
looks good, and if it fixes Piechopper than it is good to fix `develop`
