### PR TITLE
fix(testIsolation): improve the behavior, clarify config options and sync with session command

### LINKED ISSUE #24206: Change TestIsolation legacy to "on" / false "off" tie specifically to browser context
Change `testIsolation` values from "legacy"/"strict" to "on" / false "off" tie specifically to browser context and update `cy.session()` to inherent the testIsolation configuration to toggle when session clears the the page when the command executes.

### Behavior After Changes
|testIsolation | beforeEach test                         | cy.session                                  |
|----------------|---------------------------------------|------------------------------------|
|on                | clear page, clear cookies & storage in all domains  | clear page, clear cookies & storage in all domains |
|off         | do nothing  to browser context                                 | clear cookies & storage in all domains                    |

### Current Behavior
|testIsolation | beforeEach test                         | cy.session                                  |
|----------------|---------------------------------------|------------------------------------|
|strict                | clear page, clear cookies & storage in all domains  | clear page, clear cookies & storage in all domains |
|legacy         | clear cookies & storage in all domains                                 | clear page, clear cookies & storage in all domains                    |

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #24206 
- Related to #22230

#### ~`experimentalSessionAndOrigin=false`~

~|testIsolation | beforeEach test                         | cy.session                                  |~
~|----------------|---------------------------------------|------------------------------------|~
~|legacy         | clear cookies & local storage in current domain                                | not available                    |~

####  `experimentalSessionAndOrigin=true`
|testIsolation | beforeEach test                         | cy.session                                  |
|----------------|---------------------------------------|------------------------------------|
|on                | clear page, clear cookies & local & session storage in all domains  | clear page, clear cookies & local & session storage in all domains |
|off         | do nothing  to browser context                                 | clear cookies & local & session storage in all domains                    |

### Component Testing
No real impact on Component testing. When sessions & origin goes GA, session storage will also be cleared between tests. Currently only the page, cookies and local storage are cleared.

### User facing changelog

The behavior and implementation of the experimental `strict` test isolation mode has been evaluated per user feedback. `strict` mode has been replaced test isolation `on` and `off`  modes, with `on` mode being the default behavior observed when `experimentalSessionAndOrigin=true` and the `cy.session()` command now inherits the test isolation behavior for the suite it runs in. When enabled, `legacy` mode is not longer a valid mode and to persist the browser context between tests `off` mode can be used.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4797
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
-     *   - strict - applies all resets/clears from legacy, plus clears the page by visiting 'about:blank' to ensure clean app state before each test.
-     * @default "legacy", however, when experimentalSessionAndOrigin=true, the default is "strict"
-     */
-    testIsolation: 'legacy' | 'strict'
+     * The test isolation ensures a clean browser context between tests.
+     *
+     * Cypress will always resets/clears aliases, intercepts, clock, and viewport before each test
+     * to ensure a clean test slate; i.e. this configuration only impacts the browser context.
+     *
+     * Note: the `cy.session()` command will inherent this value to determine where or not the page is
```
Comment (mjhenkes) [inline cli/types/cypress.d.ts]:
```suggestion
     * Note: the `cy.session()` command will inherent this value to determine whether or not the page is
```

**Review by mjhenkes — APPROVED** [review]

File: cli/types/cypress.d.ts [hunk 2]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
     /**
-     * The test isolation level applied to ensure a clean slate between tests.
-     *   - legacy - resets/clears aliases, intercepts, clock, viewport, cookies, and local storage before each test.
-     *   - strict - applies all resets/clears from legacy, plus clears the page by visiting 'about:blank' to ensure clean app state before each test.
-     * @default "legacy", however, when experimentalSessionAndOrigin=true, the default is "strict"
-     */
-    testIsolation: 'legacy' | 'strict'
+     * The test isolation ensures a clean browser context between tests.
+     *
+     * Cypress will always resets/clears aliases, intercepts, clock, and viewport before each test
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]:
```suggestion
     * Cypress always resets/clears aliases, intercepts, clock, and viewport before each test
```

File: cli/types/cypress.d.ts [hunk 3]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
+     * to ensure a clean test slate; i.e. this configuration only impacts the browser context.
+     *
+     * Note: the `cy.session()` command will inherent this value to determine whether or not the page is
+     * cleared when the command executes.
+     *
+     * Options:
+     *   When experimentalSessionAndOrigin=false
+     *   - legacy - "Pass through" to document the default Cypress test isolation behavior. The page is not cleared
+     *          in end-to-end tests and cookies, local storage and session storage in the current domains are
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]: Seems good to have a clean break here?
```suggestion
     *          between tests in end-to-end testing. Cookies, local storage and session storage in the current domains are
```

File: cli/types/cypress.d.ts [hunk 4]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
+     *          cleared before each test. The `cy.session()` command is not available.
+     *          NOTE: this behavior will be changed in the next major release and the new default will be 'on'.
+     *
+     *   When experimentalSessionAndOrigin=true
+     *   - on - The page is cleared and cookies, local storage and session storage in all domains are cleared before each
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]:
```suggestion
     *   - on - The page is cleared between tests in end-to-end testing. Cookies, local storage and session storage in all domains are cleared before each
```

File: cli/types/cypress.d.ts [hunk 5]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
+     *          test. The `cy.session()` command will also clear the page and current browser context when establishing
+     *          the browser session.
+     *   - off - The current browser state will persist between tests. The page does not clear and cookies, local storage and
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]:
```suggestion
     *   - off - The current browser state will persist between tests. The page does not clear between tests in end-to-end testing. Cookies, local storage and
```

Comment (AtofStryker) [reply cli/types/cypress.d.ts]: I feel like we talked about this but how does this affect component testing?

File: cli/types/cypress.d.ts [hunk 6]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
+     *           session storage will be available in the next test. The `cy.session()` command will only clear the current
+     *           browser context when establishing the browser session - the current page will not clear.
+     *
+     * NOTES:
+     *    - Turning test isolation off may improve performance of end-to-end tests, however, previous tests could impact the
+     *      browser state of the next test and cause inconsistency when using .only().
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]: This could also have an impact if the user changes the order of their tests. I think what we are trying to convey is that tests are not guaranteed idempotency when run by themselves and I am not sure that is obvious.

File: cli/types/cypress.d.ts [hunk 7]
```diff
@@ -2808,12 +2808,38 @@ declare namespace Cypress {
...
+     *    - The page is always cleared in component testing to ensure a clean page for rendering isolated components.
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]: What is the impact of cookies, local storage, and session storage here with test isolation? Do they also get cleaned up in CT due to the isolated component nature?

File: packages/config/src/browser.ts [hunk 8]
```diff
@@ -199,6 +203,8 @@ export const validateOverridableAtRunTime = (config: any, isSuiteLevelOverride:
       return
     }
 
+    // TODO: add a hook to ensure valid testing-type configuration is being set at runtime for all configuration values.
```
Comment (AtofStryker) [inline packages/config/src/browser.ts:206]: should we create an issue or link to an issue here to accomplish this work?

Comment (AtofStryker) [reply packages/config/src/browser.ts:206]: is #23093 the issue?

File: packages/config/src/project/utils.ts [hunk 9]
```diff
@@ -401,7 +401,11 @@ export function mergeDefaults (
     config.baseUrl = url.replace(/\/\/+$/, '/')
   }
 
-  const defaultsForRuntime = getDefaultValues(options)
+  const defaultsForRuntime = getDefaultValues({
+    ...options,
+    // TODO: clean this up
```
Comment (AtofStryker) [inline packages/config/src/project/utils.ts]:
```suggestion
    // TODO: clean this up. Fixed with: https://github.com/cypress-io/cypress/issues/21471
```

File: packages/driver/cypress/e2e/commands/sessions/sessions.cy.js [hunk 10]
```diff
@@ -104,248 +88,215 @@ describe('cy.session', { retries: 0 }, () => {
...
-    const handleValidate = () => {
-      // both create & restore session clears page after running
-      cy.contains('Default blank page')
-      cy.contains('This page was cleared by navigating to about:blank.')
+      it('clears the browser context before each run', () => {
+        cy.window()
+        .then((win) => {
+          win.cookie = 'key=value; SameSite=Strict; Secure; Path=/fixtures'
+          win.localStorage.setItem('animal', 'bear')
+          win.sessionStorage.setItem('food', 'burgers')
```
Comment (AtofStryker) [inline packages/driver/cypress/e2e/commands/sessions/sessions.cy.js:113]: I wonder if we need a similar test check if `document.cookie` and the cookie-jar are cleared between tests when going back to `cy.origin`?

**Review by AtofStryker — COMMENTED** [review]
Looks really well tested! Main questions I have are around the comments in `cypress.d.ts` and wonder if we want to reflect similar language in the Docs [PR](https://github.com/cypress-io/cypress-documentation/pull/4797/files)?

File: packages/config/src/browser.ts (hunk 8 above)
Comment (emilyrohrbough) [reply packages/config/src/browser.ts:206]: @AtofStryker No this would be a complete refactor on how we check / set configuration in cypress. Its prob worth just removing this comment since I don't anticipate this work to happen any time soon. I've actually done alot of tis work at one point to try & simplify/unify how we check these through Cypress, but I had concerns with passivity so I put it on the back burner.

**Comment by emilyrohrbough** [comment]
@AtofStryker I tried to match the language to the docs changes while also make it comprehensive in the "what is test isolation" blurb. I'll take a look through your comments, but if you could make notes on the docs PR as well where you feel these diverge, that'd be helpful. I've been thinking/talking about this for so long it all makes sense to me 😄

File: cli/types/cypress.d.ts (hunk 4 above)
Comment (emilyrohrbough) [reply cli/types/cypress.d.ts]: I didn't specify e2e here because the page is cleared for both CT & E2E, just under the hood via wiping the inner html (CT) or visiting about:blank (E2E).

File: packages/config/src/browser.ts (hunk 8 above)
Comment (AtofStryker) [reply packages/config/src/browser.ts:206]: Makes sense. I think keeping the comment in there makes sense. Maybe a placeholder issue that describes the complete refactor and link it here?

File: cli/types/cypress.d.ts (hunk 5 above)
Comment (emilyrohrbough) [reply cli/types/cypress.d.ts]: Test Isolation cannot be configured for Component testing. It will always be "on".

File: cli/types/cypress.d.ts (hunk 6 above)
Comment (emilyrohrbough) [reply cli/types/cypress.d.ts]: > This could also have an impact if the user changes the order of their tests.

This would depend on how the user has written their E2E tests -- you could write basic, repeatable tests that don't impact the state of the next test and could be ran standalone. Though most people may accidentally write tests that do rely on one another. If you / others feel strongly, I'd prefer to elaborate more in about the risks in the documentation vs the Typescript description....It might be worth removing this entire blur and adding an onlink to learn more info.

File: cli/types/cypress.d.ts (hunk 7 above)
Comment (emilyrohrbough) [reply cli/types/cypress.d.ts]: Yeah, component testing uses "on" mode. Will clarify.

**Comment by AtofStryker** [comment]
> @AtofStryker I tried to match the language to the docs changes while also make it comprehensive in the "what is test isolation" blurb. I'll take a look through your comments, but if you could make notes on the docs PR as well where you feel these diverge, that'd be helpful. I've been thinking/talking about this for so long it all makes sense to me 😄

@emilyrohrbough after taking a look, I think the docs capture that context very well. I think some of the updates proposed to the `cypress.d.ts` mirror what is described in your docs PR.

File: cli/types/cypress.d.ts (hunk 4 above)
Comment (AtofStryker) [reply cli/types/cypress.d.ts]: Sounds like if the behavior is the same, then adding the `end-to-end` is just redundant

File: cli/types/cypress.d.ts (hunk 5 above)
Comment (AtofStryker) [reply cli/types/cypress.d.ts]: sounds like adding `end-to-end` is just confusing then. I'd ignore this suggestion 😄

File: cli/types/cypress.d.ts (hunk 7 above)
Comment (AtofStryker) [reply cli/types/cypress.d.ts]: Awesome. It wasn't obvious to me here but I can see that in the [docs pr](https://github.com/cypress-io/cypress-documentation/pull/4797/files#diff-e8c9af19adcec43f11465b5acf72d7cd399b34f8015424b26bfaf9e482624434R694) and that paints a clear picture to me

File: cli/types/cypress.d.ts (hunk 6 above)
Comment (AtofStryker) [reply cli/types/cypress.d.ts]: I think that is pretty clear [here](https://github.com/cypress-io/cypress-documentation/pull/4797/files#diff-e8c9af19adcec43f11465b5acf72d7cd399b34f8015424b26bfaf9e482624434R657) with what you added. I wonder if we want to generalize this more as to your point, this is a TypeScript declaration file and not docs 😄 . Maybe something like:

> Turning test isolation off may improve performance of end-to-end tests, however, previous tests may not be idempotent. @see <LINK_TO_DOCS> 

which would give the clear description of what is meant here when we mention idempotent, since its probably an appropriate word to capture what we mean here, but not suitable for an in depth explanation which the docs provide.

File: cli/types/cypress.d.ts [hunk 11]
```diff
@@ -2808,12 +2808,40 @@ declare namespace Cypress {
...
     /**
-     * The test isolation level applied to ensure a clean slate between tests.
-     *   - legacy - resets/clears aliases, intercepts, clock, viewport, cookies, and local storage before each test.
-     *   - strict - applies all resets/clears from legacy, plus clears the page by visiting 'about:blank' to ensure clean app state before each test.
-     * @default "legacy", however, when experimentalSessionAndOrigin=true, the default is "strict"
-     */
-    testIsolation: 'legacy' | 'strict'
+     * The test isolation ensures a clean browser context between tests.
+     *
+     * Cypress will always resets/clears aliases, intercepts, clock, and viewport before each test
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]:
```suggestion
     * Cypress will always reset/clear aliases, intercepts, clock, and viewport before each test
```

File: cli/types/cypress.d.ts [hunk 12]
```diff
@@ -2808,12 +2808,40 @@ declare namespace Cypress {
...
+     *           storage and session storage will be available in the next test. The `cy.session()` command will only clear the
+     *           current browser context when creating or restoring the browser session - the current page will not clear.
+     *
+     * Tradeoffs:
+     *      Turning test isolation off may improve performance of end-to-end tests, however, previous tests could impact the
+     *      browser state of the next test and cause inconsistency when using .only(). Be mindful to write isolated tests when
+     *      test isolation is off. If a test in the suite impacts the state of other tests and it were to fail, you could see
+     *      misleading errors in later tests which makes debugging clunky. See the [documentation](https://on.cypress.io/test-isolation)
+     *      for more information.
+     *
```
Comment (AtofStryker) [inline cli/types/cypress.d.ts]: should fix the typing job
```suggestion
```

**Review by mjhenkes — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]
