### PR TITLE
fix: Cypress.Commands.add Type Signature for @typescript-eslint/no-misused-promises rule

### LINKED ISSUE #7510: Wrong TS signature for `Cypress.Commands.add`
### Current behavior:
Current signature expect `Cypress.Commands.add` to return `void`.
This is incorrect, as you see by adding the example command you provide in docs:
https://docs.cypress.io/guides/tooling/typescript-support.html#Types-for-custom-commands

That command returns a `Chainable`, which TS marks as error because the signature doesn't expect any return value.

image

image

### Desired behavior:

Avoid TS errors, as it actually works fine.

### Test code to reproduce

Your `dataCy` snippet.

### Versions

TS: 1.8.3
Cypress: 4.7.0
Linux: 18.04

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7510

### User facing changelog

Fix the type signature of Cypress.Commands.add and overwrite.

### Additional details

- Why was this change necessary? Type failure for @typescript-eslint/no-misused-promises rule.
- What is affected by this change? N/A
- Any implementation details to explain? N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky test.

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -345,9 +345,9 @@ declare namespace Cypress {
      * @see https://on.cypress.io/api/commands
      */
     Commands: {
-      add(name: string, fn: (...args: any[]) => void): void
-      add(name: string, options: CommandOptions, fn: (...args: any[]) => void): void
-      overwrite(name: string, fn: (...args: any[]) => void): void
+      add(name: string, fn: (...args: any[]) => void | Chainable): void
```
Comment (bahmutov) [inline cli/types/cypress.d.ts:348]: I almost want to have utility type
```
type CanReturnChainable = void | Chainable
add(name: string, fn => CanReturnChainable): void
```

File: packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/commands.ts [hunk 2]
```diff
@@ -4,3 +4,10 @@
 Cypress.Commands.add('clickLink', (label: string | number | RegExp) => {
   cy.get('a').contains(label).click()
 })
+
+// https://github.com/cypress-io/cypress/issues/7510
+// The code below fails when @typescript-eslint/no-misused-promises is error
+// and the return type of function in Cypress.Commands.add doesn't support Chainable.
+Cypress.Commands.add('dataCy', (value) => {
```
Comment (bahmutov) [inline packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/commands.ts:11]: without the types change this test fails?

Comment (sainthkh) [reply packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/commands.ts:11]: tsc doesn't fail. typescript-eslint fails because of the rule [@typescript-eslint/no-misused-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md)

File: cli/types/cypress.d.ts (hunk 1 above)
Comment (sainthkh) [reply cli/types/cypress.d.ts:348]: Done.
