### PR TITLE
fix: prevent redirect loop when chrome https upgrade is detected

### LINKED ISSUE #25891: cypress reloads in infinite loop when calling cy.visit to http URL that upgrades to https.
### Current behavior

When visiting a page that triggers certain redirects, the test runner keeps reloading and looping endlessly.

https://user-images.githubusercontent.com/39823861/220307457-9c30ff6e-a37d-4abf-b370-2431082d3aae.mp4

### Desired behavior

Not reload the test runner and follow redirects.

### Test code to reproduce

```
describe('example cypress reload issue', () => {
  it('keeps reloading', () => {
    cy.visit('https://enexis.nl/mijn-enexis/mijn-aanvragen')
  })
})
```

### Cypress Version

12.6

### Node version

18.12.1

### Operating System

Win 11

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #25891

### Additional details

When a test visits an `http://` site (e.g. `cy.visit('http://http.badssl.com/')`), Cypress loads its browser app at `http.badssl.com/__/` by utilizing the proxy.

In more recent Chrome versions, [Chrome tries to upgrade any `http://` page to `https://`](https://blog.chromium.org/2023/08/towards-https-by-default.html) after checking if the `https://` version is valid (does 404 or redirect and has a valid cert). 

We run our proxy for both `http://` and `https://`, so any domain ends up valid for both protocols. This leads to an infinite loop of Cypress trying to load the `http://` version because that's what the test wants and Chrome loading the `https://` version because it sees it as valid. Then since the page loaded doesn't match what the test is visiting, Cypress attempts to the load the `http://` version again and the loop continues.

The fix for Cypress is to signal to Chrome that the `https://` version is not valid by replying with a 301 redirect when we detect that it's an https upgrade. We determine this is the case when an `https://` request comes through one of your own proxied routes, but the the primary domain (a.k.a remote state) is the `http://` version of that domain.

### Steps to test

Run the following in the latest Chrome. It should visit the site and not cause a redirect loop.

```js
cy.visit('http://http.badssl.com/')
```

### PR Tasks

- [x] Have tests been added/updated?
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/routes.ts [hunk 1]
```diff
@@ -47,6 +55,64 @@ export const createCommonRoutes = ({
...
+    // it's possible this is undefined if the primary origin has not been
+    // established yet
+    if (!primary?.props) {
+      return next()
+    }
+
+    const primaryHostname = remoteStatesPropsToHostname(primary.props)
+
+    // doamin matches (example.com === example.com), but incoming request is
+    // https:// (established aboved), while the primary origin is http://
```
Comment (mschile) [inline packages/server/lib/routes.ts]:
```suggestion
    // https:// (established above), while the primary origin is http://
```

Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in https://github.com/cypress-io/cypress/pull/28650/commits/74bbe8446b1d560cdb3b38b697f72181ea72cdcd

File: packages/server/lib/routes.ts [hunk 2]
```diff
@@ -47,6 +55,65 @@ export const createCommonRoutes = ({
...
+  // is the http:// version of that domain
+  //
+  // https://github.com/cypress-io/cypress/issues/25891
+  router.use('/', (req, res, next) => {
+    // we can short-circuit early if the request is not one of these paths,
+    // since only these paths will receive the relevant https upgrade check
+    if (
+      (
+        req.path !== '/'
+        && req.path !== '/__/'
```
Comment (mschile) [inline packages/server/lib/routes.ts]: Is this the `clientRoute`? If so, suggest doing `req.path !== clientRoute`.

File: packages/server/lib/routes.ts [hunk 3]
```diff
@@ -47,6 +55,65 @@ export const createCommonRoutes = ({
...
+        && !req.path.startsWith('/__cypress')
```
Comment (mschile) [inline packages/server/lib/routes.ts]: Is this the `namespace`? If so, suggest doing ```req.path.startsWith(`/${namespace}`)```

File: packages/server/lib/routes.ts [hunk 4]
```diff
@@ -47,6 +55,65 @@ export const createCommonRoutes = ({
...
+      )
+      || req.protocol !== 'https'
+    ) {
+      return next()
+    }
+
+    const primary = remoteStates.getPrimary()
+
+    // it's possible this is undefined if the primary origin has not been
+    // established yet
```
Comment (mschile) [inline packages/server/lib/routes.ts]: Wouldn't this fail [here](https://github.com/cypress-io/cypress/blob/d34fdcf60e669e6897f55de6e950404171edd292/packages/server/lib/remote_states.ts#L64) if there wasn't a remote state instead of returning undefined?

File: packages/server/lib/routes.ts [hunk 5]
```diff
@@ -35,6 +35,14 @@ export interface InitializeRoutes {
   testingType: Cypress.TestingType
 }
 
+function remoteStatesPropsToHostname ({ domain, subdomain, tld }: Cypress.RemoteState['props']) {
```
Comment (mschile) [inline packages/server/lib/routes.ts]: I believe most of these helper functions for remote states are in [cors.ts](https://github.com/cypress-io/cypress/blob/develop/packages/network/lib/cors.ts).

**Review by mschile — CHANGES_REQUESTED** [review]

File: packages/server/lib/routes.ts (hunk 2 above)
Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in [`b2e4eba`](https://github.com/cypress-io/cypress/pull/28650/commits/b2e4ebad9583bba57d96a32f566e68075fd8e0bd)

File: packages/server/lib/routes.ts (hunk 3 above)
Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in [`b2e4eba`](https://github.com/cypress-io/cypress/pull/28650/commits/b2e4ebad9583bba57d96a32f566e68075fd8e0bd)

File: packages/server/lib/routes.ts (hunk 4 above)
Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in [`b2e4eba`](https://github.com/cypress-io/cypress/pull/28650/commits/b2e4ebad9583bba57d96a32f566e68075fd8e0bd)

File: packages/server/lib/routes.ts (hunk 5 above)
Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in [`b2e4eba`](https://github.com/cypress-io/cypress/pull/28650/commits/b2e4ebad9583bba57d96a32f566e68075fd8e0bd)

File: packages/server/lib/routes.ts [hunk 6]
```diff
@@ -47,6 +48,63 @@ export const createCommonRoutes = ({
...
+    const primaryHostname = cors.domainPropsToHostname(primary.props)
+
+    // domain matches (example.com === example.com), but incoming request is
+    // https:// (established above), while the domain the user is trying to
+    // visit (a.k.a primary origin) is http://
+    if (
+      primaryHostname === req.hostname
+      && primary.origin.startsWith('http:')
+    ) {
+      // @ts-ignore
```
Comment (mschile) [inline packages/server/lib/routes.ts]: Suggest updating to `// @ts-expect-error` or updating `req` similar to: https://github.com/cypress-io/cypress/blob/d34fdcf60e669e6897f55de6e950404171edd292/packages/server/lib/routes.ts#L175

File: packages/server/test/unit/routes_spec.ts [hunk 7]
```diff
@@ -0,0 +1,230 @@
...
+    beforeEach(() => {
+      sinon.restore()
+
+      routeOptions = {
+        config: {
+          clientRoute: 'clientRoute',
+          namespace: 'namespace',
+        } as Cfg,
+        getSpec: sinon.stub().returns({}),
+        // @ts-ignore
```
Comment (mschile) [inline packages/server/test/unit/routes_spec.ts]:
```suggestion
        // @ts-expect-error
```

File: packages/server/test/unit/routes_spec.ts [hunk 8]
```diff
@@ -0,0 +1,230 @@
...
+        networkProxy: {
+          handleHttpRequest: () => {},
+        } as NetworkProxy,
+        nodeProxy: {} as HttpProxy,
+        onError: () => {},
+        // @ts-ignore
```
Comment (mschile) [inline packages/server/test/unit/routes_spec.ts]:
```suggestion
        // @ts-expect-error
```

**Review by mschile — APPROVED** [review]
Looks good! Had a few additional comments about ts-ignore.

File: packages/server/lib/routes.ts (hunk 6 above)
Comment (chrisbreiding) [reply packages/server/lib/routes.ts]: Addressed in [`8f9cd45`](https://github.com/cypress-io/cypress/pull/28650/commits/8f9cd45dd94c928569fd6401764e7719208b1940)

File: packages/server/test/unit/routes_spec.ts (hunk 7 above)
Comment (chrisbreiding) [reply packages/server/test/unit/routes_spec.ts]: Addressed in [`8f9cd45`](https://github.com/cypress-io/cypress/pull/28650/commits/8f9cd45dd94c928569fd6401764e7719208b1940)

File: packages/server/test/unit/routes_spec.ts (hunk 8 above)
Comment (chrisbreiding) [reply packages/server/test/unit/routes_spec.ts]: Addressed in [`8f9cd45`](https://github.com/cypress-io/cypress/pull/28650/commits/8f9cd45dd94c928569fd6401764e7719208b1940)

File: cli/CHANGELOG.md [hunk 9]
```diff
@@ -11,6 +11,7 @@ _Released 1/16/2024 (PENDING)_
 - Fixed a regression in [`13.6.2`](https://docs.cypress.io/guides/references/changelog/13.6.2) where the `body` element was not highlighted correctly in Test Replay. Fixed in [#28627](https://github.com/cypress-io/cypress/pull/28627).
 - Fixed an issue where some cross-origin logs, like assertions or cy.clock(), were getting too many dom snapshots. Fixes [#28609](https://github.com/cypress-io/cypress/issues/28609).
 - Fixed asset capture for Test Replay for requests that are routed through service workers. This addresses an issue where styles were not being applied properly in Test Replay and `cy.intercept` was not working properly for requests in this scenario. Fixes [#28516](https://github.com/cypress-io/cypress/issues/28516).
+- Fixed an issue where visiting an `http://` site would result in an infinite reload/redirect loop in recent versions of Chrome. Fixes [#25891](https://github.com/cypress-io/cypress/issues/25891).
```
Comment (AtofStryker) [inline cli/CHANGELOG.md]: should we be more specific with the chrome version here for better posterity?

**Review by AtofStryker — APPROVED** [review]

File: cli/CHANGELOG.md (hunk 9 above)
Comment (chrisbreiding) [reply cli/CHANGELOG.md]: Addressed in [`a570959`](https://github.com/cypress-io/cypress/pull/28650/commits/a570959c49267e90aee116e94fe863430e0a1f3a)

Comment (emilyrohrbough) [reply cli/CHANGELOG.md]: does this also fix https://github.com/cypress-io/cypress/issues/27185?

Comment (chrisbreiding) [reply cli/CHANGELOG.md]: @emilyrohrbough That seems to be a different issue

**Comment by DuyNguyen681988** [comment]
@chrisbreiding I meet exactly this issue in cypress 13.3.0 with Chrome 120. Does fix code already deployed to production, so I can get new cypress version to resolve this ?

**Comment by mschile** [comment]
@DuyNguyen681988, yes, this fix was just released with Cypress [13.6.3](https://docs.cypress.io/guides/references/changelog#13-6-3).
