### PR TITLE
fix pollution of :contains pseudo selector

### LINKED ISSUE #6384: cy.contains() falsely failing when using negative assertion 'not.contain'
### Current behavior:

When I use the `not.contain` assertion chained off of `.contains()`, it falsely fails. I suspect this is some regression introduced in https://github.com/cypress-io/cypress/pull/5653 cc @sainthkh 

#### 3.8.3

Screen Shot 2020-02-10 at 1 28 51 PM

#### 4.0.0

Screen Shot 2020-02-10 at 1 25 10 PM

### Desired behavior:

The `div` does not contain the text `new` and should pass.

### Test code to reproduce

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <div>actions.spec.js</div>
</body>
</html>
```

#### This test falsely fails ❌ 

```js
it('repro', () => {
  cy.visit('index.html')
  cy.contains('actions.spec.js')
    .should('not.contain', 'new')
})
```

#### This test passes though ✅ 

This makes me believe it has to do with the return value of `cy.contains()`

```js
it('repro', () => {
  cy.visit('index.html')
  cy.get('div')
    .should('not.contain', 'new') // passes
})
```

#### And this passes though ✅ 

```js
it('repro', () => {
  cy.visit('index.html')
  cy.contains('actions.spec.js').then((el) => {
    
  }).should('not.contain', 'new') // passes
})
```

### Versions

Cypress 4.0.0

### PR DESCRIPTION
**Pull request by kuceb**
- fixes issue introduced by #5653 
- TODO: this should be revisited eventually. Right now there are 2 different `contains` variants - `cy.contains(…)` (which accepts options), and `expect(…).contain(…)` / `cy.get(…).should('contain', …)` (which do not accept options)

- Closes #6384 

### User facing changelog
fix regression introduced in `4.0` causing incorrect assertion when chaining `.should('contain', …)` on a `cy.contains(…)`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
I manually verified that this fixes the original issue.

File: packages/driver/test/cypress/integration/commands/assertions_spec.js [hunk 1]
```diff
@@ -355,6 +355,25 @@ describe('src/cy/commands/assertions', () => {
 
         cy.contains('Nested Find').should('have.length', 2)
       })
+
+      it('can chain contains assertions off of cy.contains', () => {
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/assertions_spec.js]: need to reference the regression/issue that this test is fixing

**Review by brian-mann — CHANGES_REQUESTED** [review]
this PR is a little weird in that its mutating jquery's `$.expr[':']` which will persist **after** the query has run... 

it may be worth deleting the `:cy-contains` selector. 

there is a method in jquery that "compiles" selectors as well, which we may want to do

Also your comment here:

> TODO: this should be revisited eventually. Right now there are 3 different contains variants - cy.contains(...) (which takes options), expect(...).contain(...), and cy.get(...).should('contain', '...')

There are not 3 variants, there are only 2 right? `.should('contain')` is the same thing as `expect(...).to.contain(...)` yeah?

File: packages/driver/test/cypress/integration/commands/assertions_spec.js (hunk 1 above)
Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/assertions_spec.js]: > There are not 3 variants, there are only 2 right?

right
