### PR TITLE
Do not require user gesture for audio and video that has autoplay set

### LINKED ISSUE #2376: Cant start HTML5 Video due to autoplay policy - Cypress should disable requiring user gesture for video
### Current behavior:
Unable to invoke the video play function in cypress but can in chrome dev tools.

### Desired behavior:
When invoking the play function on an html5 video element, it should play.

### Steps to reproduce:
I have tried numerous ways of playing the video. In dev tools, all you need to do is $('video').play(); and that works.

I have tried the below two options, neither plays the video.
```javascript
it('Watch video till the end', () => {
    cy.wait(3000);
    cy.get('video').then(() => {
      const video = Cypress.$('video');
      if (!video) {
        throw new Error('Cant find video');
      }
      video.play();
    });
});
```
```javascript
  it('Watch video till the end', () => {
    cy.get('video#introVideo')
      .then(video => {
        const videoElement = video.get(0);
        return new Promise((resolve) => {
          videoElement.oncanplay = () => {
            videoElement.play();
          };
          videoElement.onended = () => {
            resolve(true);
          }
        });
      })
      .get('button')
      .contains('I have everything ready. Let’s get started!')
      .click();
  });
```

### Versions
Cypress 3.0.2, 3.1.*
Chrome 68

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- There is outdated documentation that claims only
`—no-user-gesture-required` is sufficient, but as of Chrome 66, the
autoplay policy requires flag
`--autoplay-policy=no-user-gesture-required`.
- Should avoid instances of errors “failed because the user didn't
interact with the document first”
- Close #2376
- Addresses #2188

### CODE REVIEW

File: packages/driver/test/cypress/integration/e2e/video_spec.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+describe('video', () => {
+  it('play does not throw error on autoplay', () => {
+    cy.visit('/fixtures/video.html')
+    cy.get('video').then(($video) => {
+      return $video[0].play()
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/e2e/video_spec.js]: No `.then()` or `.catch()` handler is required here because rejected promises will automatically cause the `cy.then` to fail.

Your notes are good but they can just go above the `.play()`

**Review by brian-mann — CHANGES_REQUESTED** [review]
- the `flower.mp4` file is over `1mb` which seems excessive. likely an `.mp4` smaller than `100k` would do the trick and not bloat the repo
- @tgriesser or @amirrustam 	or @bahmutov 	we could also investigate using large git file storage that github has which would potentially enable us to move large binary blobs out

File: packages/driver/test/cypress/integration/e2e/video_spec.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+describe('video', () => {
+  it('play does not throw error on autoplay', () => {
+    cy.visit('/fixtures/video.html')
+    cy.get('video').then(($video) => {
+      // Older browsers may not return a value from play().
+      // Without --autoplay-policy=no-user-gesture-required it throws
+      // DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
+      return $video[0].play()
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/e2e/video_spec.js]: I forgot to mention that a comment should have gone at the top of this spec that points to the github issue as well.

I'm merging this PR, and you can add the comment directly on `develop`

File: packages/server/lib/environment.coffee [hunk 3]
```diff
@@ -19,6 +19,8 @@ try
   app = require("electron").app
   app.commandLine.appendSwitch("disable-renderer-backgrounding", true)
   app.commandLine.appendSwitch("ignore-certificate-errors", true)
+  ## https://github.com/cypress-io/cypress/issues/2376
+  # app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required")
```
Comment (brian-mann) [inline packages/server/lib/environment.coffee]: why is this commented out? won't this fail in electron? this is super confusing

**Review by brian-mann — CHANGES_REQUESTED** [review]

File: packages/server/lib/environment.coffee (hunk 3 above)
Comment (jennifer-shehane) [reply packages/server/lib/environment.coffee]: sorry, yeah, I had issues merging and I think everything just got a bit hectic in the commits.

**Review by brian-mann — APPROVED** [review]
