### PR TITLE
Fix `cy.visit` slowness by removing Electron timers workaround

### LINKED ISSUE #4313: `cy.visit` in 3.3.1 is 2x-4x as slow as 3.2.0
### Current behavior:

Running my tests in 3.2.0 takes 1 hour 54 minutes.
Running my tests in 3.3.1 takes 4 hours 41 minutes.

(This is running on headless electron using `cypress.run` with the [module API](https://docs.cypress.io/guides/guides/module-api.html); I haven't measured it with `cypress open`).

Both cases are running on the same WIndows 10 VM, and not using parallelization.

### Desired behavior:

I'd like my tests to take less than 2 hours.

### Versions

Cypress 3.3.1

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #4313

* [x] changes HttpAgent to override addRequest instead of createSocket (more correct)
* [x] Removes timers fix - this fixes the slowness between addRequest and onResponseReceived
* [x] Does not pass the destination's `Connection` header through proxy to the browser - `Connection` is a [hop by hop header](https://www.freesoft.org/CIE/RFC/2068/143.htm)
* [x] ~Make calls to stdout.write and stderr.write asynchronous to prevent slowdown when TTY is unresponsive~
	- Even when stdio is blocking, it's not enough lag to make a difference unless you're dumping multiple kbps of data into a TTY, so it's not worth it to add this fix here.

### CODE REVIEW

**Comment by flotwig** [comment]
This `navigation_spec` completes quickly, in 9 seconds:

```coffee
    it.only "completes immediately on localhost", ->
      _.times 100, ->
        cy.visit('http://localhost:3500/dump-method')
```

This same test with Python's SimpleHTTPServer takes waaaay too long (60+ seconds).

---

`driver/test` server headers proxied by Cypress:

image

And in a regular browser:

image

---

`SimpleHTTPServer` headers proxied by Cypress:

image

And in a regular browser:

image

**Comment by flotwig** [comment]
I happened to notice that while `SimpleHTTPServer` doesn't support keep-alive, Chrome was forcing the addition of a `Connection: keep-alive` header to the responses, which doesn't really help anything. The agent will keep-alive any request that supports keep-alive, and the browser connection to the proxy is kept alive using `Proxy-Connection: keep-alive`. So I think this chunk of code can be removed: https://github.com/cypress-io/cypress/blob/768381b1c2a834a2f038bfcb78c3abcfc99b8b25/packages/server/lib/request.coffee#L444-L448

**Comment by flotwig** [comment]
Noticed that a few factors appear to influence this slowdown:

* connection: close vs. keep-alive from destination server
* if a large amount of output is being sent to stderr
	* Related: [Node.js halts when console window is scrolled](https://stackoverflow.com/questions/48068773/node-js-halts-when-console-window-is-scrolled)
* if the timers fix is in place or not
* if running headlessly or not

`Connection: close`? | `DEBUG` on? | Timers fix? | Was `cy.visit` fast?
--- | --- | --- | ---
:x: | :x: | :x: | :heavy_check_mark:
:x: | :x: | :heavy_check_mark: | :x:
:x: | :heavy_check_mark: | :x: | :x:
:x: | :heavy_check_mark: | :heavy_check_mark: | :x:
:heavy_check_mark: | :x: | :x: | :heavy_check_mark:<super>*</super>
:heavy_check_mark: | :x: | :heavy_check_mark: | :x:
:heavy_check_mark: | :heavy_check_mark: | :x: | :x:
:heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:

<super>*</super>The visits with `close` were slightly slower (~2ms vs ~1ms) than the visits from `Connection: keep-alive`, probably due to the overhead of creating a new socket connection.

Conclusions:

* `close` vs. `keep-alive` does not affect this behavior
* If a large amount of output is sent to stderr (presumably stdout as well), it will cause a slowdown on Linux/macOS because stderr writes are synchronous on these platforms.
	* Could add a workaround to make writes async. Something like `fs.write(2, 'message')`
		* Downside: Could cause partial output to stderr, interleaved output to stderr
* The timers fix causes a slowdown, not sure why yet.

**Comment by flotwig** [comment]
Notes on trying to figure out what caused this issue:

* Tried to use system Node.js for `timers` in c51b3957e237c8970390dfec897753ada3702faa to see if it made any difference. The delay was still present.
	* Additionally, there's not a delay in the IPC channel created by `cp.fork()` after reviewing the logs carefully.
* Tried to run the timers_spec within Electron v2.0.18 in 8b82f0eeb30eec98288308b30b9cf19e3fb595a8 to see if anything failed, but all tests pass.

**Comment by brian-mann** [comment]
So do we still want to remove the `Connection` headers?

**Comment by flotwig** [comment]
@brian-mann It's a [hop-by-hop header](https://www.freesoft.org/CIE/RFC/2068/143.htm), so I think the proxy should remove it. The browser's connection to the proxy is still keep-alive - check out the Connection IDs in the network log I produced using this branch:

image

**Comment by brian-mann** [comment]
It looks like we're only stripping it on the incoming response from the upstream server - before handing it back to the browser.

Are we still sending it when we make the initial proxied request to the upstream server from the cypress proxy? 

Does the http agent modify the http header and add it? NOTE: i'm not referring to the TCP keepalive mechanism, just the actual HTTP connection header. Can't remember if we have tests around this or not.

**Comment by flotwig** [comment]
Yeah, this is still there: https://github.com/cypress-io/cypress/blob/8e63476da6919b0c2de98b8deee09812da229191/packages/server/lib/request.coffee#L444-L448

If I remove it, then a new socket is opened for each request (net profiler output):

```
[ X connection opened to localhost:33159 by HttpAgent.connect [as createConnection] (net.js:103:35) ]
  1 [ C client connected from 127.0.0.1:38894 to server on localhost:33159 ]
  1 [ C client disconnected ]
[ X connection closed ]
[ X connection opened to localhost:33159 by HttpAgent.connect [as createConnection] (net.js:103:35) ]
  1 [ C client connected from 127.0.0.1:38896 to server on localhost:33159 ]
  1 [ C client disconnected ]
[ X connection closed ]
[ X connection opened to localhost:33159 by HttpAgent.connect [as createConnection] (net.js:103:35) ]
  1 [ C client connected from 127.0.0.1:38898 to server on localhost:33159 ]
  1 [ C client disconnected ]
[ X connection closed ]
[ X connection opened to localhost:33159 by HttpAgent.connect [as createConnection] (net.js:103:35) ]
  1 [ C client connected from 127.0.0.1:38900 to server on localhost:33159 ]
  1 [ C client disconnected ]
[ X connection closed ]
```

With it kept in, there is only one connection established for these requests. Looks like it's still good to have.

File: packages/server/test/support/fixtures/projects/e2e/cypress/integration/fast_visit_spec.coffee [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    if attrs.name is "visit"
+      @lastLog = log
+
+  return null
+
+it "normally finishes in less than 1000ms on localhost with connection: close", ->
+  Cypress._.times 100, ->
+    cy.visit('/close')
+    .then ->
+      expect(@lastLog.get("totalTime")).to.be.lte(1000)
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/integration/fast_visit_spec.coffee]: `1000` seems way too high. shouldn't it be more like <100ms ?

Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/fast_visit_spec.coffee]: The longest request (with the exception of the first request, which took 66ms) finished in less than 25ms on my system. I'll make it 150ms just to prevent any flake from high CPU load in CI or whatever.
