### PR TITLE
fix: WebSocket Connection Closed crashing from BrowserCriClient

### LINKED ISSUE #30100: Websocket Connection Closed: When `BrowserCriClient` destroys an extra target while that target is being initialized, the App crashes
### Current behavior

If `BrowserCriClient`'s `_onTargetDestroyed` event handler is triggered while the `_onAttachToTarget` event handler is pending the `Fetch.enable` CRI command, the app can crash with an uncaught exception, `Error: WebSocket connection closed`.

This is a separate manifestation of the `WebSocket connection closed` issue that was resolved in the `CriClient` class in `v13.13.1`.

### Desired behavior

_No response_

### Test code to reproduce

None currently, but should be reproducible with a unit test in `packages/server/test/unit/browsers/browser-cri-client_spec.ts`

### Cypress Version

13.13.1

### Node version

18.17.1

### Operating System

OSX 14.3

### Debug Logs

```shell
2024-08-23T01:22:08.390Z cypress:server:browsers:browser-cri-client Target.attachedToTarget { targetId: 'EB14338F830B61BC0944C09E4C812677', type: 'page', title: '', url: '', attached: true, canAccessOpener: false, browserContextId: 'BB40F3CCEE2CA5D8CB25D667E5AB23E2' }
2024-08-23T01:22:08.395Z cypress:server:browsers:browser-cri-client Connect as extra target (id: EB14338F830B61BC0944C09E4C812677)
WebSocket connection closed
2024-08-23T01:22:08.434Z cypress:server:browsers:browser-cri-client Target.targetDestroyed { event: { targetId: 'EB14338F830B61BC0944C09E4C812677' }, closing: false, closed: false, resettingBrowserTargets: false }
2024-08-23T01:22:08.434Z cypress:server:browsers:browser-cri-client Close extra target client (id: %s)
Error: WebSocket connection closed
    at _._handleConnectionClose (<embedded>:628:580021)
    at A.<anonymous> (<embedded>:628:578085)
    at Object.onceWrapper (node:events:629:26)
    at A.emit (node:events:514:28)
    at A.emitClose (<embedded>:628:558309)
    at Socket.H (<embedded>:628:565620)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:323:12)
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/30100

### Additional details
When the BrowserCRIClient attaches to a target, it determines if the new target is an "extra target" or not. As a part of this process, it creates a raw CDPClient instance and sends a `Fetch.enable` command. If this extra target is closed before that command can resolve, CDPClient will throw a `WebSocket Connection Closed` error. If this error is uncaught, it will crash Cypress.

To fix this, the command is wrapped in try/catch, and logs a debug entry for the error if an error is encountered.

This could have been fixed by using the more resilient `CRIClient` class, but `BrowserCRIClient` is fairly complex, and this approach has a smaller change footprint. `BrowserCRIClient` is a candidate for similar refactors that were made to `CRIClient`, recently.

### Steps to test
As this error is very difficult to reproduce intentionally, the only test available is a unit test.

### PR Tasks

- [X] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by ryanthemanuel — APPROVED** [review]

File: packages/server/test/unit/browsers/browser-cri-client_spec.ts [hunk 1]
```diff
@@ -278,6 +278,20 @@ describe('lib/browsers/browser-cri-client', function () {
       expect(options.browserClient.send).to.be.calledWith('Runtime.runIfWaitingForDebugger', undefined, 'session-id')
     })
 
+    it('does not throw if Fetch.enable on extra target throws', async () => {
```
Comment (AtofStryker) [inline packages/server/test/unit/browsers/browser-cri-client_spec.ts]:
```suggestion
    it('does not throw if Fetch.enable on extra target throws', () => {
```

**Review by AtofStryker — APPROVED** [review]
