### PR TITLE
fix: Suppress filesystem errors during glob search

### LINKED ISSUE #24109: Cypress does not find any component testing specs when folder matching glob can not be accessed
### Current behavior

Cypress scans directories to gather specs using a glob pattern, if one of those directories or a subdirectory gives a `EACCES` error, the scan is cancelled and no specs are found.

I started with this command:

```
npx cypress run --component -s resources/assets/js/components/Select2.cy.js
```

Relevant debug output:
```
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ 'resources/assets/js/components/Select2.cy.js' ] +31ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/ef2go-docker/easyflex +0ms
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ '**/*.cy.{js,jsx,ts,tsx}' ] +7ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/ef2go-docker/easyflex +0ms
  cypress:data-context:sources:FileDataSource error in getFilesByGlob [Error: EACCES: permission denied, scandir '/home/jeroen.akkerman/ef2go-docker/easyflex/storage/framework/testing/disks'  ] { errno: -13, code: 'EACCES', syscall: 'scandir', path: '/home/jeroen.akkerman/ef2go-docker/easyflex/storage/framework/testing/disks' } +184ms
  cypress:data-context:sources:ProjectDataSource found specs [] +0ms
```

This results in this vague error:

```
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/jeroen.akkerman/ef2go-docker/easyflex/resources/assets/js/components/Select2.cy.js
```

`ll` command output:

```
❯ ll /home/jeroen.akkerman/ef2go-docker/easyflex/resources/assets/js/components/Select2.cy.js
-rw-r--r-- 1 jeroen.akkerman jeroen.akkerman 7.3K Oct  4 11:36 /home/jeroen.akkerman/ef2go-docker/easyflex/resources/assets/js/components/Select2.cy.js
```

The file exists and should be readable by Cypress.
I also tried moving the file around in the project, including `cypress/component` but Cypress keeps missing the spec files.
This also seems to impact the component search function in the GUI.

image

### Desired behavior

When access to a subdirectory is denied, that directory should be skipped and the search should continue normally.

### Test code to reproduce

Can be reproduced with any repository containing a directory that is not readable.

1. `npm init vue@latest`, no to all questions
2. `cd vue-project/`
3. `npm install`
4. `npm install cypress -D`
5. `mkdir -p secret/directory`
6. `touch secret/directory/.gitkeep`
7. `chmod -r secret/directory`
8. `npx cypress open`
9. Let Cypress set up component testing with defaults for everything.
10. You can test the search for components here, it is already broken.
11. Create a spec `WelcomeItem.cy.js` in `src/components`:

```js
import WelcomeItem from './WelcomeItem';

describe('<WelcomeItem />', () => {
    it('mounts', () => {
        cy.mount(<WelcomeItem />);
    });
});
```

12. `npx cypress run --component -s src/components/WelcomeItem.cy.js`

image

### Cypress Version

10.9.0

### Node version

16.14.2

### Operating System

Ubuntu 20.04.5 LTS (through WSL)

### Debug Logs

```shell
  cypress:cli:cli cli starts with arguments ["/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node","/home/jeroen.akkerman/vue-project/node_modules/.bin/cypress","run","--component","-s","src/components/WelcomeItem.cy.js"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli running Cypress with args [ Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/jeroen.akkerman/vue-project/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, component: true, spec: 'src/components/WelcomeItem.cy.js', args: [], [Symbol(kCapture)]: false } ] +1ms
  cypress:cli:cli variable-length opts parsed { args: [ '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', '/home/jeroen.akkerman/vue-project/node_modules/.bin/cypress', 'run', '--component', '-s', 'src/components/WelcomeItem.cy.js' ], opts: Command { _events: [Object: null prototype] { 'option:browser': [Function (anonymous)], 'option:ci-build-id': [Function (anonymous)], 'option:component': [Function (anonymous)], 'option:config': [Function (anonymous)], 'option:config-file': [Function (anonymous)], 'option:e2e': [Function (anonymous)], 'option:env': [Function (anonymous)], 'option:group': [Function (anonymous)], 'option:key': [Function (anonymous)], 'option:headed': [Function (anonymous)], 'option:headless': [Function (anonymous)], 'option:no-exit': [Function (anonymous)], 'option:parallel': [Function (anonymous)], 'option:port': [Function (anonymous)], 'option:project': [Function (anonymous)], 'option:quiet': [Function (anonymous)], 'option:record': [Function (anonymous)], 'option:reporter': [Function (anonymous)], 'option:reporter-options': [Function (anonymous)], 'option:spec': [Function (anonymous)], 'option:tag': [Function (anonymous)], 'option:dev': [Function (anonymous)] }, _eventsCount: 22, _maxListeners: undefined, commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], parent: Command { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, commands: [Array], options: [Array], parent: null, _allowUnknownOption: false, _args: [], rawArgs: [Array], _scriptPath: '/home/jeroen.akkerman/vue-project/node_modules/.bin/cypress', _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: null, _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: undefined, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '<command> [options]', args: [Array], [Symbol(kCapture)]: false }, _allowUnknownOption: false, _args: [], rawArgs: null, _scriptPath: null, _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _actionHandler: [Function: listener], _executableHandler: false, _executableFile: null, _defaultCommandName: null, _exitCallback: null, _aliases: [], _hidden: false, _helpFlags: '-h, --help', _helpDescription: 'display help for command', _helpShortFlag: '-h', _helpLongFlag: '--help', _hasImplicitHelpCommand: 0, _helpCommandName: 'help', _helpCommandnameAndArgs: 'help [command]', _helpCommandDescription: 'display help for command', _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, exit: true, component: true, spec: 'src/components/WelcomeItem.cy.js', args: [], [Symbol(kCapture)]: false } } +147ms
  cypress:cli parsed cli options { component: true, spec: 'src/components/WelcomeItem.cy.js' } +153ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress +4ms
  cypress:cli Binary is executable? : true +3ms
  cypress:cli binaryDir is  /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress +0ms
  cypress:cli Reading binary package.json from: /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 10.9.0 installed in: /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress +7ms
  cypress:cli { verified: true } +7ms
  cypress:cli is Verified ? true +2ms
  cypress:cli:run processing run options { component: true, spec: 'src/components/WelcomeItem.cy.js', key: null, reporter: null, reporterOptions: null, project: '/home/jeroen.akkerman/vue-project' } +0ms
  cypress:cli:run --key is not set, looking up environment variable CYPRESS_RECORD_KEY +0ms
  cypress:cli:run run to spawn.start args ["--run-project","/home/jeroen.akkerman/vue-project","--spec","src/components/WelcomeItem.cy.js","--testing-type","component"] +0ms
  cypress:cli DISPLAY environment variable is set to :0 on Linux
  cypress:cli Assuming this DISPLAY points at working X11 server,
  cypress:cli Cypress will not spawn own Xvfb
  cypress:cli
  cypress:cli NOTE: if the X11 server is NOT working, Cypress will exit without explanation,
  cypress:cli   see https://github.com/cypress-io/cypress/issues/4034
  cypress:cli Solution: Unset the DISPLAY variable and try again:
  cypress:cli   DISPLAY= npx cypress run ... +0ms
  cypress:cli needs to start own Xvfb? false +0ms
  cypress:cli spawning, should retry on display problem? true +1ms
  cypress:cli passing DISPLAY :0 +8ms
  cypress:cli spawn args [ '--no-sandbox', '--', '--run-project', '/home/jeroen.akkerman/vue-project', '--spec', 'src/components/WelcomeItem.cy.js', '--testing-type', 'component', '--cwd', '/home/jeroen.akkerman/vue-project', '--userNodePath', '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', '--userNodeVersion', '16.15.1' ] { detached: false, stdio: [ 'inherit', 'inherit', 'pipe' ] } +0ms
  cypress:cli spawning Cypress with executable: /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress +1ms
  cypress:cli piping child STDERR to process STDERR +4ms
  cypress:ts registering ts-node on directory undefined +0ms
  cypress:ts Running without ts-node hook in environment "production" +89ms
  cypress:server:appdata path: /home/jeroen.akkerman/.config/Cypress/cy/production/cache +0ms
  cypress:server:appdata path: /home/jeroen.akkerman/.config/Cypress/cy/production/browsers +78ms
  cypress:server:cypress starting cypress with argv [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress', '--no-sandbox', '--', '--run-project', '/home/jeroen.akkerman/vue-project', '--spec', 'src/components/WelcomeItem.cy.js', '--testing-type', 'component', '--cwd', '/home/jeroen.akkerman/vue-project', '--userNodePath', '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', '--userNodeVersion', '16.15.1' ] +0ms
  cypress:server:args argv array: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress', '--no-sandbox', '--run-project', '/home/jeroen.akkerman/vue-project', '--spec', 'src/components/WelcomeItem.cy.js', '--testing-type', 'component', '--cwd', '/home/jeroen.akkerman/vue-project', '--userNodePath', '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', '--userNodeVersion', '16.15.1' ] +0ms
  cypress:server:args parsed argv options { options: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, 'run-project': '/home/jeroen.akkerman/vue-project', runProject: '/home/jeroen.akkerman/vue-project', spec: 'src/components/WelcomeItem.cy.js', 'testing-type': 'component', testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1' } } +2ms
  cypress:server:args argv parsed: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: 'src/components/WelcomeItem.cy.js', testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true } +6ms
  cypress:server:util:proxy found proxy environment variables { npm_config_noproxy: '' } +0ms
  cypress:server:args options { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {} } +4ms
  cypress:server:args argv options: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project' } +0ms
  cypress:server:cypress from argv [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress', '--no-sandbox', '--run-project', '/home/jeroen.akkerman/vue-project', '--spec', 'src/components/WelcomeItem.cy.js', '--testing-type', 'component', '--cwd', '/home/jeroen.akkerman/vue-project', '--userNodePath', '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', '--userNodeVersion', '16.15.1' ] got options { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project' } +16ms
  cypress:server:cypress scaling electron app in headless mode +1ms
  cypress:server:appdata path: /home/jeroen.akkerman/.config/Cypress/cy/production +172ms
[1830:1004/122609.885629:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
  cypress:server:cypress starting in mode run with options { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project' } +175ms
  cypress:server:cypress running Electron currently +1ms
[1984:1004/122609.918496:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[1984:1004/122609.923377:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudLatestRunUpdateSpecData +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectBySlug +1ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudProjectsBySlugs +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudSpecByPath +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.cloudViewer +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for Query.versions +0ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for CurrentProject.cloudProject +3ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectResult.data +3ms
  cypress:graphql:nexusDeferIfNotLoadedPlugin Adding nexusDeferIfNotLoadedPlugin for RemoteFetchableCloudProjectSpecResult.data +0ms
  cypress:server:browsers:utils getBrowsers +0ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86, validator: [Function: validator] }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +0ms
  cypress:server:browsers:utils WebKit is enabled, but there was an error constructing the WebKit browser: { err: Error: Cannot find module 'playwright-webkit' Require stack: - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/index.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/util/process_profiler.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/index.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/index.js -     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)     at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)     at Function.resolve (node:internal/modules/cjs/helpers:108:19) at getWebKitBrowser (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js:155:36) at Object.getBrowsers (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js:179:9) at BrowserDataSource.machineBrowsers (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/data-context/src/sources/BrowserDataSource.js:67:45) at ProjectLifecycleManager._setCurrentProject (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/data-context/src/data/ProjectLifecycleManager.js:310:26) at new ProjectLifecycleManager (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/data-context/src/data/ProjectLifecycleManager.js:64:18) at new DataContext (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/data-context/src/DataContext.js:92:33) at makeDataContext (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/makeDataContext.js:28:17) at module.exports (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/modes/index.js:24:82) at /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/cypress.js:86:34 at tryCatcher (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Function.Promise.attempt.Promise.try (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29) at Object.runElectron (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/cypress.js:72:23) at Object.startInMode (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/cypress.js:230:21) at /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/cypress.js:179:19 at tryCatcher (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at Promise._fulfill (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18) at Promise._settlePromise (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21) at Promise._settlePromise0 (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at Promise._fulfill (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18) at Promise._settlePromise (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21) at Promise._settlePromise0 (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at Promise._fulfill (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18) at PromiseArray._resolve (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:127:19) at PromiseArray._promiseFulfilled (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:145:14) at Promise._settlePromise (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:609:26) at Promise._settlePromise0 (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18) at Promise._fulfill (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18) at /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/nodeback.js:42:21 at /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/fs-extra/node_modules/universalify/index.js:22:54 { code: 'MODULE_NOT_FOUND', requireStack: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/index.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/util/process_profiler.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/index.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/index.js', undefined ] } } +4ms
  cypress:data-context:sources:GitDataSource config: { isRunMode: true, projectRoot: '/home/jeroen.akkerman/vue-project', onError: [Function (anonymous)], onBranchChange: [Function: onBranchChange], onGitInfoChange: [Function: onGitInfoChange] } +0ms
  cypress:scaffold-config:detect Detected cypress.config.js - using JS +0ms
  cypress:server:video using ffmpeg from /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg +0ms
  cypress:lifecycle:ProjectConfigIpc fork child process { CHILD_PROCESS_FILE_PATH: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js', configProcessArgs: [ '--projectRoot', '/home/jeroen.akkerman/vue-project', '--file', '/home/jeroen.akkerman/vue-project/cypress.config.js' ], childOptions: { stdio: 'pipe', cwd: '/home/jeroen.akkerman/vue-project', execPath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node' } } +0ms
  cypress:lifecycle:ProjectConfigIpc no typescript found, just use regular Node.js +1ms
  cypress:lifecycle:ProjectConfigIpc trigger the load of the file +7ms
  cypress:lifecycle:child:run_require_async_child:2058 configFile: /home/jeroen.akkerman/vue-project/cypress.config.js +0ms
  cypress:lifecycle:child:run_require_async_child:2058 projectRoot: /home/jeroen.akkerman/vue-project +1ms
  cypress:server:util:process_profiler current & mean memory and CPU usage by process group:
  cypress:server:util:process_profiler ┌─────────┬───────────────────┬──────────────┬──────────────┬────────────┬────────────────┬──────────┬──────────────┬─────────────┐
  cypress:server:util:process_profiler │ (index) │       group       │ processCount │     pids     │ cpuPercent │ meanCpuPercent │ memRssMb │ meanMemRssMb │ maxMemRssMb │
  cypress:server:util:process_profiler ├─────────┼───────────────────┼──────────────┼──────────────┼────────────┼────────────────┼──────────┼──────────────┼─────────────┤
  cypress:server:util:process_profiler │    0    │     'cypress'     │      1       │    '1830'    │     0      │       0        │  133.17  │    133.17    │   133.17    │
  cypress:server:util:process_profiler │    1    │ 'electron-shared' │      2       │ '1832, 1833' │     0      │       0        │   95.1   │     95.1     │    95.1     │
  cypress:server:util:process_profiler │    2    │      'other'      │      2       │ '1973, 1974' │     0      │       0        │   3.31   │     3.31     │    3.31     │
  cypress:server:util:process_profiler │    3    │      'TOTAL'      │      5       │     '-'      │     0      │       0        │  231.58  │    231.58    │   231.58    │
  cypress:server:util:process_profiler └─────────┴───────────────────┴──────────────┴──────────────┴────────────┴────────────────┴──────────┴──────────────┴─────────────┘ +0ms
  cypress:lifecycle:child:run_require_async_child:2058 try loading /home/jeroen.akkerman/vue-project/cypress.config.js +21ms
  cypress:lifecycle:child:run_require_async_child:2058 Loading file /home/jeroen.akkerman/vue-project/cypress.config.js +0ms
  cypress:cli exporting Cypress module interface +0ms
  cypress:launcher:linux Could not extract version from stdout using regex: { stdout: 'Mozilla Firefox 104.0', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m } +0ms
  cypress:lifecycle:child:run_require_async_child:2058 loaded config file /home/jeroen.akkerman/vue-project/cypress.config.js +450ms
  cypress:lifecycle:child:run_require_async_child:2058 loaded config from /home/jeroen.akkerman/vue-project/cypress.config.js { component: { devServer: { framework: 'vue', bundler: 'vite' } } } +1ms
  cypress:lifecycle:ProjectConfigIpc loadConfig:reply +714ms
  cypress:lifecycle:ProjectConfigManager config is loaded for file /home/jeroen.akkerman/vue-project/cypress.config.js null +0ms
  cypress:config:browser validating configuration +0ms
  cypress:config:browser validating configuration +123ms
  cypress:config:project setting config object { cliConfig: {}, projectName: 'vue-project', projectRoot: '/home/jeroen.akkerman/vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', config: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' } }, envFile: {}, options: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project', socketId: 'b4kd6cdtv1', isTextTerminal: true, browser: 'electron', quiet: false, morgan: false, report: true, configFile: 'cypress.config.js' }, configFile: 'cypress.config.js' } +0ms
  cypress:config:project config is { component: { devServer: { framework: 'vue', bundler: 'vite' } }, devServer: { framework: 'vue', bundler: 'vite' } } +0ms
  cypress:config:project:utils merged config with options, got { component: { devServer: { framework: 'vue', bundler: 'vite' } }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true } +0ms
  cypress:config:project:utils using CYPRESS_INTERNAL_ENV production +3ms
  cypress:config:project:utils resolved config is { value: [], from: 'default' } +2ms
  cypress:config:browser validating configuration +8ms
  cypress:server:validation clientCerts: [] +0ms
  cypress:config:project:utils validate that there is no breaking config options before setupNodeEvents +1ms
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ 'cypress/support/component.{js,jsx,ts,tsx}' ] +0ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/vue-project +0ms
  cypress:config:project:utils setting support file /home/jeroen.akkerman/vue-project/cypress/support/component.js +162ms
  cypress:config:project:utils for project root /home/jeroen.akkerman/vue-project +0ms
  cypress:config:project:utils resolved support file /home/jeroen.akkerman/vue-project/cypress/support/component.js +1ms
  cypress:config:project:utils set support folder /home/jeroen.akkerman/vue-project/cypress/support +0ms
  cypress:server:browsers:utils found browsers { browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' } ] } +1s
  cypress:config:browser validating configuration +295ms
  cypress:server:validation clientCerts: [] +295ms
  cypress:server:validation browsers [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ] +0ms
  cypress:lifecycle:child:run_require_async_child:2058 setupTestingType component { additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', animationDistanceThreshold: 5, arch: 'x64', autoOpen: false, baseUrl: null, blockHosts: null, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], chromeWebSecurity: true, clientCertificates: [], clientRoute: '/__/', configFile: '/home/jeroen.akkerman/vue-project/cypress.config.js', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', cypressEnv: 'production', defaultCommandTimeout: 4000, devServer: { framework: 'vue', bundler: 'vite' }, devServerPublicPathRoute: '/__cypress/src', downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSessionAndOrigin: false, experimentalSingleTabRunMode: false, experimentalSourceRewriting: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', hosts: null, includeShadowDom: false, indexHtmlFile: 'cypress/support/component-index.html', isInteractive: true, isTextTerminal: true, keystrokeDelay: 0, modifyObstructiveCode: true, morgan: false, namespace: '__cypress', numTestsKeptInMemory: 0, pageLoadTimeout: 60000, platform: 'linux', port: null, projectId: null, projectName: 'vue-project', projectRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, redirectionLimit: 20, repoRoot: '/home/jeroen.akkerman/vue-project', report: true, reporter: 'spec', reporterOptions: null, reporterRoute: '/__cypress/reporter', requestTimeout: 5000, resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' } }, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', scrollBehavior: 'top', slowTestThreshold: 250, socketId: 'b4kd6cdtv1', socketIoCookie: '__socket', socketIoRoute: '/__socket', specPattern: '**/*.cy.{js,jsx,ts,tsx}', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, version: '10.9.0', video: true, videoCompression: 32, videoUploadOnPasses: true, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, xhrRoute: '/xhrs/', testingType: 'component' } +524ms
  cypress:lifecycle:child:RunPlugins:2058 project root: /home/jeroen.akkerman/vue-project +0ms
  cypress:lifecycle:child:RunPlugins:2058 passing config { additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', animationDistanceThreshold: 5, arch: 'x64', autoOpen: false, baseUrl: null, blockHosts: null, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], chromeWebSecurity: true, clientCertificates: [], clientRoute: '/__/', configFile: '/home/jeroen.akkerman/vue-project/cypress.config.js', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', cypressEnv: 'production', defaultCommandTimeout: 4000, devServer: { framework: 'vue', bundler: 'vite' }, devServerPublicPathRoute: '/__cypress/src', downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSessionAndOrigin: false, experimentalSingleTabRunMode: false, experimentalSourceRewriting: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', hosts: null, includeShadowDom: false, indexHtmlFile: 'cypress/support/component-index.html', isInteractive: true, isTextTerminal: true, keystrokeDelay: 0, modifyObstructiveCode: true, morgan: false, namespace: '__cypress', numTestsKeptInMemory: 0, pageLoadTimeout: 60000, platform: 'linux', port: null, projectId: null, projectName: 'vue-project', projectRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, redirectionLimit: 20, repoRoot: '/home/jeroen.akkerman/vue-project', report: true, reporter: 'spec', reporterOptions: null, reporterRoute: '/__cypress/reporter', requestTimeout: 5000, resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' } }, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', scrollBehavior: 'top', slowTestThreshold: 250, socketId: 'b4kd6cdtv1', socketIoCookie: '__socket', socketIoRoute: '/__socket', specPattern: '**/*.cy.{js,jsx,ts,tsx}', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, version: '10.9.0', video: true, videoCompression: 32, videoUploadOnPasses: true, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, xhrRoute: '/xhrs/', testingType: 'component' } +0ms
  cypress:lifecycle:child:RunPlugins:2058 Loading the RunPlugins +2ms
  cypress:lifecycle:child:RunPlugins:2058 register event _get:task:body with id 0 +1ms
  cypress:lifecycle:child:RunPlugins:2058 register event _get:task:keys with id 1 +0ms
  cypress:lifecycle:child:RunPlugins:2058 Calling setupNodeEvents +1ms
  cypress:lifecycle:child:RunPlugins:2058 register event dev-server:start with id 2 +0ms
  cypress:lifecycle:child:RunPlugins:2058 register default preprocessor +2ms
  cypress:server:plugins resolving typescript with projectRoot '/home/jeroen.akkerman/vue-project' +0ms
  cypress:server:plugins could not resolve typescript, error: Cannot find module 'typescript'
Require stack:
- /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/util/resolve.js
- /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js
- /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js
- /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js +0ms
  cypress:lifecycle:child:RunPlugins:2058 creating webpack preprocessor with options {} +1ms
  cypress:lifecycle:child:RunPlugins:2058 register event file:preprocessor with id 3 +308ms
  cypress:lifecycle:child:RunPlugins:2058 plugins file successfully loaded +0ms
  cypress:lifecycle:ProjectConfigManager register plugins process event _get:task:body with id 0 +815ms
  cypress:lifecycle:EventRegistrar register event '_get:task:body' +0ms
  cypress:lifecycle:ProjectConfigManager register plugins process event _get:task:keys with id 1 +0ms
  cypress:lifecycle:EventRegistrar register event '_get:task:keys' +0ms
  cypress:lifecycle:ProjectConfigManager register plugins process event dev-server:start with id 2 +0ms
  cypress:lifecycle:EventRegistrar register event 'dev-server:start' +0ms
  cypress:lifecycle:ProjectConfigManager register plugins process event file:preprocessor with id 3 +0ms
  cypress:lifecycle:EventRegistrar register event 'file:preprocessor' +0ms
  cypress:config:browser validating configuration +390ms
  cypress:config:project setting config object { cliConfig: {}, projectName: 'vue-project', projectRoot: '/home/jeroen.akkerman/vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', config: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' } }, envFile: {}, options: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project', socketId: 'b4kd6cdtv1', isTextTerminal: true, browser: 'electron', quiet: false, morgan: false, report: true, configFile: 'cypress.config.js' }, configFile: 'cypress.config.js' } +691ms
  cypress:config:project config is { component: { devServer: { framework: 'vue', bundler: 'vite' } }, devServer: { framework: 'vue', bundler: 'vite' } } +0ms
  cypress:config:project:utils merged config with options, got { component: { devServer: { framework: 'vue', bundler: 'vite' } }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true } +521ms
  cypress:config:project:utils using CYPRESS_INTERNAL_ENV production +2ms
  cypress:config:project:utils resolved config is { value: [], from: 'default' } +0ms
  cypress:config:browser validating configuration +2ms
  cypress:server:validation clientCerts: [] +392ms
  cypress:config:project:utils validate that there is no breaking config options before setupNodeEvents +1ms
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ 'cypress/support/component.{js,jsx,ts,tsx}' ] +686ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/vue-project +0ms
  cypress:config:project:utils setting support file /home/jeroen.akkerman/vue-project/cypress/support/component.js +3ms
  cypress:config:project:utils for project root /home/jeroen.akkerman/vue-project +0ms
  cypress:config:project:utils resolved support file /home/jeroen.akkerman/vue-project/cypress/support/component.js +0ms
  cypress:config:project:utils set support folder /home/jeroen.akkerman/vue-project/cypress/support +0ms
  cypress:config:browser validating configuration +5ms
  cypress:server:validation clientCerts: [] +5ms
  cypress:server:validation browsers [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ] +0ms
  cypress:config:project updateWithPluginValues { cfg: { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: [Object], devServer: [Object], envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: null, blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: null, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ [Object], [Object] ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: [Object], arch: [Object], baseUrl: [Object], blockHosts: [Object], chromeWebSecurity: [Object], clientCertificates: [Object], defaultCommandTimeout: [Object], downloadsFolder: [Object], env: {}, execTimeout: [Object], experimentalFetchPolyfill: [Object], experimentalInteractiveRunEvents: [Object], experimentalSessionAndOrigin: [Object], experimentalModifyObstructiveThirdPartyCode: [Object], experimentalSourceRewriting: [Object], experimentalSingleTabRunMode: [Object], experimentalStudio: [Object], experimentalWebKitSupport: [Object], fileServerFolder: [Object], fixturesFolder: [Object], excludeSpecPattern: [Object], includeShadowDom: [Object], keystrokeDelay: [Object], modifyObstructiveCode: [Object], nodeVersion: [Object], numTestsKeptInMemory: [Object], platform: [Object], pageLoadTimeout: [Object], port: [Object], projectId: [Object], redirectionLimit: [Object], reporter: [Object], reporterOptions: [Object], requestTimeout: [Object], resolvedNodePath: [Object], resolvedNodeVersion: [Object], responseTimeout: [Object], retries: [Object], screenshotOnRunFailure: [Object], screenshotsFolder: [Object], slowTestThreshold: [Object], scrollBehavior: [Object], supportFile: [Object], supportFolder: [Object], taskTimeout: [Object], testIsolation: [Object], trashAssetsBeforeRuns: [Object], userAgent: [Object], video: [Object], videoCompression: [Object], videosFolder: [Object], videoUploadOnPasses: [Object], viewportHeight: [Object], viewportWidth: [Object], waitForAnimations: [Object], watchForFileChanges: [Object], specPattern: [Object], browsers: [Object], hosts: [Object], isInteractive: [Object] } }, modifiedConfig: {} } +9ms
  cypress:config:browser validating configuration +3ms
  cypress:config:project validate that there is no breaking config options added by setupNodeEvents +1ms
  cypress:config:project config diffs null +1ms
  cypress:config:project merged config object { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: null, blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: null, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { value: undefined, from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' } } } +1ms
  cypress:config:project merged plugins config { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: null, blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: null, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { value: undefined, from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' } } } +1ms
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ 'src/components/WelcomeItem.cy.js' ] +15ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/vue-project +0ms
  cypress:data-context:sources:FileDataSource globbing pattern(s): [ '**/*.cy.{js,jsx,ts,tsx}' ] +9ms
  cypress:data-context:sources:FileDataSource within directory: /home/jeroen.akkerman/vue-project +0ms
  cypress:data-context:sources:FileDataSource error in getFilesByGlob [Error: EACCES: permission denied, scandir '/home/jeroen.akkerman/vue-project/secret/directory'  ] { errno: -13, code: 'EACCES', syscall: 'scandir', path: '/home/jeroen.akkerman/vue-project/secret/directory' } +13ms
  cypress:data-context:sources:ProjectDataSource found specs [] +0ms
  cypress:lifecycle:EventRegistrar plugin event registered? { eventName: 'dev-server:start', isRegistered: true } +43ms
  cypress:lifecycle:EventRegistrar execute plugin event 'dev-server:start' Node 'v16.14.2' with args: { specs: [], config: { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: [Object], devServer: [Object], envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: null, blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: null, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ [Object], [Object] ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: [Object], arch: [Object], baseUrl: [Object], blockHosts: [Object], chromeWebSecurity: [Object], clientCertificates: [Object], defaultCommandTimeout: [Object], downloadsFolder: [Object], env: {}, execTimeout: [Object], experimentalFetchPolyfill: [Object], experimentalInteractiveRunEvents: [Object], experimentalSessionAndOrigin: [Object], experimentalModifyObstructiveThirdPartyCode: [Object], experimentalSourceRewriting: [Object], experimentalSingleTabRunMode: [Object], experimentalStudio: [Object], experimentalWebKitSupport: [Object], fileServerFolder: [Object], fixturesFolder: [Object], excludeSpecPattern: [Object], includeShadowDom: [Object], keystrokeDelay: [Object], modifyObstructiveCode: [Object], nodeVersion: [Object], numTestsKeptInMemory: [Object], platform: [Object], pageLoadTimeout: [Object], port: [Object], projectId: [Object], redirectionLimit: [Object], reporter: [Object], reporterOptions: [Object], requestTimeout: [Object], resolvedNodePath: [Object], resolvedNodeVersion: [Object], responseTimeout: [Object], retries: [Object], screenshotOnRunFailure: [Object], screenshotsFolder: [Object], slowTestThreshold: [Object], scrollBehavior: [Object], supportFile: [Object], supportFolder: [Object], taskTimeout: [Object], testIsolation: [Object], trashAssetsBeforeRuns: [Object], userAgent: [Object], video: [Object], videoCompression: [Object], videosFolder: [Object], videoUploadOnPasses: [Object], viewportHeight: [Object], viewportWidth: [Object], waitForAnimations: [Object], watchForFileChanges: [Object], specPattern: [Object], browsers: [Object], hosts: [Object], isInteractive: [Object] } } } undefined undefined +1ms
  cypress:lifecycle:ProjectConfigManager call event dev-server:start for invocation id inv1 +45ms
  cypress:lifecycle:child:RunPlugins:2058 execute plugin event: dev-server:start ({ invocationId: 'inv1', eventId: 2 }) +48ms
  cypress:vite-dev-server:getVite resolved viteImportPath as /home/jeroen.akkerman/vue-project/node_modules/vite/index.cjs +0ms
  cypress:vite-dev-server:devServer Creating Vite Server +0ms
  cypress:vite-dev-server:resolve-config resolved config file at /home/jeroen.akkerman/vue-project/vite.config.js using root /home/jeroen.akkerman/vue-project +0ms
  cypress:vite-dev-server:plugins:inspect skipping vite inspect because CYPRESS_INTERNAL_VITE_INSPECT is not set +0ms
  cypress:vite-dev-server:resolve-config The resolved server config is {
  "root": "/home/jeroen.akkerman/vue-project",
  "base": "/__cypress/src/",
  "configFile": "/home/jeroen.akkerman/vue-project/vite.config.js",
  "optimizeDeps": {
    "esbuildOptions": {
      "incremental": true,
      "plugins": [
        {
          "name": "cypress-esbuild-plugin"
        }
      ]
    },
    "entries": [
      "/home/jeroen.akkerman/vue-project/cypress/support/component.js"
    ]
  },
  "server": {
    "fs": {
      "allow": [
        "/home/jeroen.akkerman/vue-project",
        "/home/jeroen.akkerman/vue-project/node_modules",
        "/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app"
      ]
    },
    "host": "127.0.0.1"
  },
  "plugins": [
    {
      "name": "cypress:main",
      "enforce": "pre"
    }
  ]
} +3ms
  cypress:vite-dev-server:devServer Vite server created +261ms
  cypress:vite-dev-server:devServer Successfully launched the vite server on port 5173 +97ms
  cypress:lifecycle:ProjectConfigManager promise resolved for id 'inv1' with value { port: 5173 } +406ms
  cypress:server:browsers:utils searching for browser { nameOrPath: 'electron', filter: { name: 'electron', channel: 'stable' }, knownBrowsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ] } +844ms
  cypress:data-context browser found to set electron +0ms
  cypress:server:run run mode ready with options { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project', socketId: 'b4kd6cdtv1', isTextTerminal: true, browser: 'electron', quiet: false, morgan: false, report: true } +0ms
  cypress:server:browsers:utils getBrowsers +5ms
  cypress:launcher:detect detecting if the following browsers are present [ { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', versionRegex: /Google Chrome (\S+)/m, binary: [ 'google-chrome', 'chrome', 'google-chrome-stable' ], minSupportedVersion: 64 }, { name: 'chromium', family: 'chromium', channel: 'stable', displayName: 'Chromium', versionRegex: /Chromium (\S+)/m, binary: [ 'chromium-browser', 'chromium' ], minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'beta', displayName: 'Chrome Beta', versionRegex: /Google Chrome (\S+) beta/m, binary: 'google-chrome-beta', minSupportedVersion: 64 }, { name: 'chrome', family: 'chromium', channel: 'canary', displayName: 'Canary', versionRegex: /Google Chrome Canary (\S+)/m, binary: 'google-chrome-canary', minSupportedVersion: 64 }, { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', versionRegex: /^Mozilla Firefox ([^\sab]+)$/m, binary: 'firefox', minSupportedVersion: 86, validator: [Function: validator] }, { name: 'firefox', family: 'firefox', channel: 'dev', displayName: 'Firefox Developer Edition', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m, binary: [ 'firefox-developer-edition', 'firefox' ], minSupportedVersion: 86 }, { name: 'firefox', family: 'firefox', channel: 'nightly', displayName: 'Firefox Nightly', versionRegex: /^Mozilla Firefox (\S+a\S*)$/m, binary: [ 'firefox-nightly', 'firefox-trunk' ], minSupportedVersion: 86 }, { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', versionRegex: /Microsoft Edge (\S+)/m, binary: [ 'edge', 'microsoft-edge' ], minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'canary', displayName: 'Edge Canary', versionRegex: /Microsoft Edge Canary (\S+)/m, binary: 'edge-canary', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'beta', displayName: 'Edge Beta', versionRegex: /Microsoft Edge Beta (\S+)/m, binary: 'edge-beta', minSupportedVersion: 79 }, { name: 'edge', family: 'chromium', channel: 'dev', displayName: 'Edge Dev', versionRegex: /Microsoft Edge Dev (\S+)/m, binary: [ 'edge-dev', 'microsoft-edge-dev' ], minSupportedVersion: 79 } ] +2s
  cypress:server:browsers:utils WebKit is enabled, but there was an error constructing the WebKit browser: { err: Error: Cannot find module 'playwright-webkit' Require stack: - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/index.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/util/process_profiler.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/index.js - /home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/index.js -     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)     at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)     at Function.resolve (node:internal/modules/cjs/helpers:108:19) at getWebKitBrowser (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js:155:36) at Object.getBrowsers [as get] (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js:179:9) at ready (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/modes/run.js:747:47) at Object.run (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/modes/run.js:862:16)     at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 'MODULE_NOT_FOUND', requireStack: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/utils.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/browsers/index.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/util/process_profiler.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/index.js', '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/index.js', undefined ] } } +1ms
  cypress:launcher:linux Could not extract version from stdout using regex: { stdout: 'Mozilla Firefox 104.0', versionRegex: /^Mozilla Firefox (\S+b\S*)$/m } +2s
  cypress:server:browsers:utils found browsers { browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' } ] } +894ms
  cypress:server:run found all system browsers [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ] +897ms
  cypress:server:open_project open_project create /home/jeroen.akkerman/vue-project +0ms
  cypress:server:open_project opening project /home/jeroen.akkerman/vue-project +0ms
  cypress:server:open_project and options { socketId: 'b4kd6cdtv1', morgan: false, report: true, isTextTerminal: true, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], onWarning: [Function: onWarning], spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], onError: [Function (anonymous)], onReloadBrowser: [Function: onReloadBrowser], args: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project', socketId:
 'b4kd6cdtv1', isTextTerminal: true, browser: 'electron', quiet: false, morgan: false, report: true, onError: [Function (anonymous)], browsers: [ [Object], [Object] ] } } +0ms
  cypress:server:project Project created { testingType: 'component', projectRoot: '/home/jeroen.akkerman/vue-project' } +0ms
  cypress:server:project opening project instance /home/jeroen.akkerman/vue-project +1ms
  cypress:server:project project open options { report: true, onFocusTests: [Function: onFocusTests], onError: [Function (anonymous)], onWarning: [Function: onWarning], socketId: 'b4kd6cdtv1', morgan: false, isTextTerminal: true, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], onReloadBrowser: [Function: onReloadBrowser], args: { _: [ '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/Cypress' ], sandbox: false, runProject: '/home/jeroen.akkerman/vue-project', spec: [ '/home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js' ], testingType: 'component', cwd: '/home/jeroen.akkerman/vue-project', userNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', userNodeVersion: '16.15.1', invokedFromCli: true, config: {}, projectRoot: '/home/jeroen.akkerman/vue-project', socketId: 'b4kd6cdtv1', isTextTerminal: true, browser: 'electron', quiet: false, morgan: false, report: true, onError: [Function (anonymous)], browsers: [ [Object], [Object] ] }, testingType: 'component' } +0ms
  cypress:server:project project has config { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: 'http://localhost:5173', blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: null, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { value: undefined, from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' }, testingType: { value: 'component' } }, testingType: 'component', componentTesting: true } +0ms
  cypress:server:server-base server open +0ms
  cypress:network:client-certificates loaded client certificates for 0 URL(s) +0ms
  cypress:server:server-base Server listening on  { address: '127.0.0.1', family: 'IPv4', port: 36107 } +13ms
  cypress:server:appdata path: /home/jeroen.akkerman/.config/Cypress/cy/production/proxy +4s
  cypress:https-proxy:ca checking CA version { actualVersion: 1, CA_VERSION: 1 } +0ms
  cypress:https-proxy Created SNI HTTPS Proxy Server { port: 38831 } +0ms
  cypress:network:cors Parsed URL { port: '5173', tld: 'localhost', domain: '' } +0ms
  cypress:network:cors Parsed URL { port: '5173', tld: 'localhost', domain: '' } +1ms
  cypress:server:remote-states setting remote state { auth: undefined, origin: 'http://localhost:5173', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '5173', tld: 'localhost', domain: '' } } for http://localhost:5173 +0ms
  cypress:network:cors Parsed URL { port: '5173', tld: 'localhost', domain: '' } +1ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'http://localhost:5173', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '5173', tld: 'localhost', domain: '' } } for: http://localhost:5173 +1ms
  cypress:server:project project config: { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: 'http://localhost:5173', blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: 36107, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', testingType: 'component', componentTesting: true, remote: {}, browser: null, specs: [], proxyUrl: 'http://localhost:36107', browserUrl: 'http://localhost:5173/__/', reporterUrl: 'http://localhost:5173/__cypress/reporter', xhrUrl: '__cypress/xhrs/', proxyServer: 'http://localhost:36107' } +48ms
  cypress:server:reporter trying to load reporter: spec +0ms
  cypress:server:reporter spec is Mocha reporter +0ms
  cypress:server:saved_state noop saved state +0ms
  cypress:server:project project has config { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: 'http://localhost:5173', blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: 36107, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { value: undefined, from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' }, testingType: { value: 'component' } }, testingType: 'component', componentTesting: true, remote: {}, browser: null, specs: [], proxyUrl: 'http://localhost:36107', browserUrl: 'http://localhost:5173/__/', reporterUrl: 'http://localhost:5173/__cypress/reporter', xhrUrl: '__cypress/xhrs/', proxyServer: 'http://localhost:36107', state: {} } +5ms
  cypress:network:cors Parsed URL { port: '5173', tld: 'localhost', domain: '' } +9ms
  cypress:server:remote-states getting remote state: { auth: undefined, origin: 'http://localhost:5173', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '5173', tld: 'localhost', domain: '' } } for: http://localhost:5173 +8ms
  cypress:server:run project created and opened with config { devServer: { framework: 'vue', bundler: 'vite' }, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project', rawJson: { component: { devServer: [Object] }, devServer: { framework: 'vue', bundler: 'vite' }, envFile: {}, projectRoot: '/home/jeroen.akkerman/vue-project', projectName: 'vue-project', repoRoot: '/home/jeroen.akkerman/vue-project' }, configFile: 'cypress.config.js', morgan: false, isTextTerminal: true, socketId: 'b4kd6cdtv1', report: true, animationDistanceThreshold: 5, arch: 'x64', baseUrl: 'http://localhost:5173', blockHosts: null, chromeWebSecurity: true, clientCertificates: [], defaultCommandTimeout: 4000, downloadsFolder: '/home/jeroen.akkerman/vue-project/cypress/downloads', env: {}, execTimeout: 60000, experimentalFetchPolyfill: false, experimentalInteractiveRunEvents: false, experimentalSessionAndOrigin: false, experimentalModifyObstructiveThirdPartyCode: false, experimentalSourceRewriting: false, experimentalSingleTabRunMode: false, experimentalStudio: false, experimentalWebKitSupport: false, fileServerFolder: '/home/jeroen.akkerman/vue-project', fixturesFolder: '/home/jeroen.akkerman/vue-project/cypress/fixtures', excludeSpecPattern: [ '**/__snapshots__/*', '**/__image_snapshots__/*' ], includeShadowDom: false, keystrokeDelay: 0, modifyObstructiveCode: true, nodeVersion: undefined, numTestsKeptInMemory: 0, platform: 'linux', pageLoadTimeout: 60000, port: 36107, projectId: null, redirectionLimit: 20, reporter: 'spec', reporterOptions: null, requestTimeout: 5000, resolvedNodePath: '/home/jeroen.akkerman/.nvm/versions/node/v16.15.1/bin/node', resolvedNodeVersion: '16.15.1', responseTimeout: 30000, retries: { runMode: 0, openMode: 0 }, screenshotOnRunFailure: true, screenshotsFolder: '/home/jeroen.akkerman/vue-project/cypress/screenshots', slowTestThreshold: 250, scrollBehavior: 'top', supportFile: '/home/jeroen.akkerman/vue-project/cypress/support/component.js', supportFolder: '/home/jeroen.akkerman/vue-project/cypress/support', taskTimeout: 60000, testIsolation: 'legacy', trashAssetsBeforeRuns: true, userAgent: null, video: true, videoCompression: 32, videosFolder: '/home/jeroen.akkerman/vue-project/cypress/videos', videoUploadOnPasses: true, viewportHeight: 500, viewportWidth: 500, waitForAnimations: true, watchForFileChanges: false, specPattern: '**/*.cy.{js,jsx,ts,tsx}', additionalIgnorePattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}', autoOpen: false, browsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104', warning: 'Your project has set the configuration option: `chromeWebSecurity` to `false`.\n' + '\n' + 'This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ], clientRoute: '/__/', cypressBinaryRoot: '/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app', devServerPublicPathRoute: '/__cypress/src', hosts: null, isInteractive: true, namespace: '__cypress', reporterRoute: '/__cypress/reporter', socketIoCookie: '__socket', socketIoRoute: '/__socket', version: '10.9.0', xhrRoute: '/xhrs/', indexHtmlFile: 'cypress/support/component-index.html', cypressEnv: 'production', resolved: { animationDistanceThreshold: { value: 5, from: 'default' }, arch: { value: 'x64', from: 'default' }, baseUrl: { value: null, from: 'default' }, blockHosts: { value: null, from: 'default' }, chromeWebSecurity: { value: true, from: 'default' }, clientCertificates: { value: [], from: 'default' }, defaultCommandTimeout: { value: 4000, from: 'default' }, downloadsFolder: { value: 'cypress/downloads', from: 'default' }, env: {}, execTimeout: { value: 60000, from: 'default' }, experimentalFetchPolyfill: { value: false, from: 'default' }, experimentalInteractiveRunEvents: { value: false, from: 'default' }, experimentalSessionAndOrigin: { value: false, from: 'default' }, experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' }, experimentalSourceRewriting: { value: false, from: 'default' }, experimentalSingleTabRunMode: { value: false, from: 'default' }, experimentalStudio: { value: false, from: 'default' }, experimentalWebKitSupport: { value: false, from: 'default' }, fileServerFolder: { value: '', from: 'default' }, fixturesFolder: { value: 'cypress/fixtures', from: 'default' }, excludeSpecPattern: { value: [Array], from: 'default' }, includeShadowDom: { value: false, from: 'default' }, keystrokeDelay: { value: 0, from: 'default' }, modifyObstructiveCode: { value: true, from: 'default' }, nodeVersion: { value: undefined, from: 'default' }, numTestsKeptInMemory: { value: 0, from: 'config' }, platform: { value: 'linux', from: 'default' }, pageLoadTimeout: { value: 60000, from: 'default' }, port: { value: null, from: 'default' }, projectId: { value: null, from: 'default' }, redirectionLimit: { value: 20, from: 'default' }, reporter: { value: 'spec', from: 'default' }, reporterOptions: { value: null, from: 'default' }, requestTimeout: { value: 5000, from: 'default' }, resolvedNodePath: { value: null, from: 'default' }, resolvedNodeVersion: { value: null, from: 'default' }, responseTimeout: { value: 30000, from: 'default' }, retries: { value: [Object], from: 'default' }, screenshotOnRunFailure: { value: true, from: 'default' }, screenshotsFolder: { value: 'cypress/screenshots', from: 'default' }, slowTestThreshold: { value: 250, from: 'default' }, scrollBehavior: { value: 'top', from: 'default' }, supportFile: { value: 'cypress/support/component.{js,jsx,ts,tsx}', from: 'default' }, supportFolder: { value: false, from: 'default' }, taskTimeout: { value: 60000, from: 'default' }, testIsolation: { value: 'legacy', from: 'default' }, trashAssetsBeforeRuns: { value: true, from: 'default' }, userAgent: { value: null, from: 'default' }, video: { value: true, from: 'default' }, videoCompression: { value: 32, from: 'default' }, videosFolder: { value: 'cypress/videos', from: 'default' }, videoUploadOnPasses: { value: true, from: 'default' }, viewportHeight: { value: 500, from: 'default' }, viewportWidth: { value: 500, from: 'default' }, waitForAnimations: { value: true, from: 'default' }, watchForFileChanges: { value: false, from: 'config' }, specPattern: { value: '**/*.cy.{js,jsx,ts,tsx}', from: 'default' }, browsers: { value: [Array], from: 'runtime' }, hosts: { value: null, from: 'default' }, isInteractive: { value: true, from: 'default' }, testingType: { value: 'component' } }, testingType: 'component', componentTesting: true, remote: { auth: undefined, origin: 'http://localhost:5173', strategy: 'http', fileServer: null, domainName: 'localhost', props: { port: '5173', tld: 'localhost', domain: '' } }, browser:
 null, specs: [], proxyUrl: 'http://localhost:36107', browserUrl: 'http://localhost:5173/__/', reporterUrl: 'http://localhost:5173/__cypress/reporter', xhrUrl: '__cypress/xhrs/', proxyServer: 'http://localhost:36107', state: {} } +59ms
  cypress:server:browsers:utils searching for browser { nameOrPath: 'electron', filter: { name: 'electron', channel: 'stable' }, knownBrowsers: [ { name: 'firefox', family: 'firefox', channel: 'stable', displayName: 'Firefox', version: '104.0', path: 'firefox', minSupportedVersion: 86, majorVersion: '104' }, { name: 'electron', channel: 'stable', family: 'chromium', displayName: 'Electron', version: '102.0.5005.148', path: '', majorVersion: 102 } ] } +63ms
  cypress:server:profilecleaner found 0 profile folders: [] +0ms
  cypress:server:profilecleaner found 0 root level profile matches: [] +2ms
  cypress:server:profilecleaner found 0 profile folders: [] +0ms
  cypress:server:cypress exiting with err Error: Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js
    at ready (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/modes/run.js:778:16)
 {
  isCypressErr: true,
  type: 'NO_SPECS_FOUND',
  details: undefined,
  messageMarkdown: "Can't run because `no spec files` were found.\n" +
    '\n' +
    'We searched for specs matching this glob pattern:\n' +
    '\n' +
    '  > /home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js',
  originalError: undefined,
  stackWithoutMessage: '    at ready (/home/jeroen.akkerman/.cache/Cypress/10.9.0/Cypress/resources/app/packages/server/lib/modes/run.js:778:16)\n'
} +4s
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /home/jeroen.akkerman/vue-project/src/components/WelcomeItem.cy.js
  cypress:server:cypress calling exit 1 +1ms
  cypress:server:cypress about to exit with code 1 +0ms
  cypress:server:browsers browsers.kill called with no active instance +0ms
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 0, immediatelyMatchedRequests: 0, unmatchedRequests: 0, unmatchedPreRequests: 0 } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +6s
```

### Other

This only impacts component testing, e2e testing seem unaffected.

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #24109 

### Additional details
Currently, our glob searches for project specs and components for "Create from Component" will fail if a filesystem error is encountered (such as a permission denied) and return an empty array. This can happen even if there's a deeply nested resource that has nothing to do with Cypress that is permissions-restricted or has a bad symlink. This PR updates the behavior to log and retry the glob search if an error is encountered so the user can at least get partial results even if there is a part of their `specPattern` that cannot be traversed.

Unfortunately there isn't an elegant way to "watch and log" in Globby. It only exposes a "suppress all errors" flag or we can roll our own filesystem adapter which felt heavy for this use case (and wrapping `fs` functions is tricky due to extensive use of callback args for error-handling). The best approach I could find was to try it once and, if an error is encountered, log and try again with errors suppressed. If the retry fails then we bail out with our current behavior of "log and return empty array".

### Steps to test
1. Create a new Cypress CT project using React or Vue. Make sure it has at least one component and at least one spec file
2. Create a new directory within the project and remove read permission from it:
  `mkdir secretDir`
  `chmod -r secretDir`
3. Launch latest Cypress version in CT open mode (`npx cypress open --component`), observe no specs are listed
4. Select "Create from Component", observe no components are listed
5. Close Cypress and re-open project using this branch with `DEBUG=cypress:data-context:sources:FileDataSource`
6. Observe that spec file is listed, retry "Create from Component" and observe component(s) are found
7. Observe that filesystem EACCES error was logged with comment regarding retry

**Note:** This issue also impacts e2e, instructions can be adapted to validate e2e is also impacted/fixed by creating restricted directory under `cypress/e2e` to match default e2e spec pattern

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/data-context/src/sources/FileDataSource.ts [hunk 1]
```diff
@@ -72,7 +72,15 @@ export class FileDataSource {
 
       return files
     } catch (e) {
-      debug('error in getFilesByGlob %o', e)
+      if (!globOptions.suppressErrors) {
+        // Log error and retry with filesystem errors suppressed - this allows us to find partial
+        // results even if the glob search hits permission issues (#24109)
+        debug('Error in getFilesByGlob %o, retrying with filesystem errors suppressed', e)
+
+        return await this.getFilesByGlob(cwd, glob, { ...globOptions, suppressErrors: true })
```
Comment (lmiller1990) [inline packages/data-context/src/sources/FileDataSource.ts:80]: Should we just do this by default instead of the "if it fails, retry and suppress errors"? Any downside to that approach?

Comment (mike-plummer) [reply packages/data-context/src/sources/FileDataSource.ts:80]: That was my original plan, but if we do that we get _zero_ logging of the problem. My fear is that a user will have a spec file within a restricted directory and that spec will just never show up and there will be no logging (debug or otherwise) explaining why which will make it very difficult to troubleshoot.

Taking the "retry with suppress" approach is less performant, but gives us the possibility of debug logs.

**Review by marktnoonan — APPROVED** [review]
Tested as described in the issue and this works great.

**Comment by marktnoonan** [comment]
@mike-plummer is it expected to still have problems _running_ a spec that's now reachable? The spec is not inside the `secretDir` but its existence still appears to be a problem when parsing the support file...

At least this tells the user what the exact problem is so they can fix it.

Screenshot 2023-02-13 at 4 16 34 PM

**Comment by mike-plummer** [comment]
> @mike-plummer is it expected to still have problems _running_ a spec that's now reachable? The spec is not inside the `secretDir` but its existence still appears to be a problem when parsing the support file...
> 
> At least this tells the user what the exact problem is so they can fix it.
> 
@marktnoonan Interesting, I must've only tested this on Webpack because I hadn't seen that issue before. This is intended only to fix the "no specs at all show up" issue in the Specs List. As you point out, the error is appropriately surfaced to the user in this scenario so I'm not concerned

**Review by ZachJW34 — APPROVED** [review]
