### PR TITLE
Have cy.request support urls with specials Unicodes chars

### LINKED ISSUE #5274: cy.request() errors when URL's path contains ’ character
### Current behavior:

Using a `’` character in the Path of the URL passed to `cy.request()` causes a `TypeError: The header content contains invalid characters`.

The apostrophe is not a `'` apostrophe character, it's the `’` character. If I paste the same url into my Chrome browser - the url redirects correctly.

I tried a lot of other characters that did not cause any issue including some emojis 😅 

Why is someone even doing this? Well @oak-wildwood was dynamically pulling content from our docs to generate urls then using `cy.request()` to visit them - so the generated URLs had the `’` character.

Screen Shot 2019-10-02 at 3 41 00 PM

Stack trace

```
RequestError: TypeError: The header content contains invalid characters
    at new RequestError (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.start (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:753:10)
    at Request.end (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:1511:10)
    at end (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/Users/jennifer/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:578:7)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Screen Shot 2019-10-02 at 3 42 12 PM

### Desired behavior:

Requesting this url should not throw an `invalid characters` warning and should instead behave as Chrome does.

### Steps to reproduce: (app code and test code)

```js
it('test', () => {
  cy.request('https://on.cypress.io/key-differences#What-you’ll-learn') // fails
})

it('test a fake url too', () => {
  cy.request('http://’')             // works
  cy.request('http://google.com’')   // works
  cy.request('http://google.com/’')  // fails
})
```

### Versions

Cypress 3.4.1 & 3.5.0 prerelease

### PR DESCRIPTION
**Pull request by avallete**
- Closes #5274 

### User facing changelog

- The `cy.request` command now support urls with specials Unicodes characters in it.

### Additional details

- Providing some urls with some unicode characters (eg: `’`) was throwing an `ERR_UNESCAPED_CHARACTERS` error.

#### Before
```js
cy.request('https://on.cypress.io/key-differences#What-you’ll-learn') // wont work
cy.request(encodeURI('https://on.cypress.io/key-differences#What-you’ll-learn')) // work
```

#### After
```js
cy.request('https://on.cypress.io/key-differences#What-you’ll-learn') // work
cy.request(encodeURI('https://on.cypress.io/key-differences#What-you’ll-learn')) // work
```

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/commands/request.coffee [hunk 1]
```diff
@@ -125,6 +125,15 @@ module.exports = (Commands, Cypress, cy, state, config) ->
       if originOrBase = config("baseUrl") or cy.getRemoteLocation("origin")
         options.url = $Location.qualifyWithBaseUrl(originOrBase, options.url)
 
+      ## Make sure the url unicode characters are properly escaped
+      ## https://github.com/cypress-io/cypress/issues/5274
+      try
+        options.url = decodeURI(options.url)
+      catch URIError
+        # The url is not already encoded just silence the error
```
Comment (flotwig) [inline packages/driver/src/cy/commands/request.coffee]: Can you give me an example of when this will throw a `URIError`? I tried some different inputs but couldn't get it to throw.

File: packages/driver/src/cy/commands/request.coffee [hunk 2]
```diff
@@ -125,6 +125,15 @@ module.exports = (Commands, Cypress, cy, state, config) ->
...
+      finally
+        options.url = encodeURI(options.url)
```
Comment (flotwig) [inline packages/driver/src/cy/commands/request.coffee]: Hmm, this also seems to encode the domain of URLs passed in:

```
>> encodeURI('http://example-漢字.com/?a=漢字')
"http://example-%E6%BC%A2%E5%AD%97.com/?a=%E6%BC%A2%E5%AD%97"
```

I'm not even sure if non-punycoded Unicode domains work in Cypress today, but either way, I don't think that the domain should be urlencoded. Just the `path` component of the URL should be urlencoded, right?

File: packages/driver/src/cy/commands/request.coffee (hunk 1 above)
Comment (avallete) [reply packages/driver/src/cy/commands/request.coffee]: An url with percents value in it like: `http://localhost:1234/%` will trigger this error.

Since the decodeURI will interpret the littéral percent character as the begin of encoding sequence.

File: packages/driver/src/cy/commands/request.coffee (hunk 2 above)
Comment (avallete) [reply packages/driver/src/cy/commands/request.coffee]: You totally right.

Thinking about it, I'm wondering if doing an:
`options.url = new URL()`

Which will percent escape the path and convert the domain Unicode to `xn--example--d44...` into the `.href` attribute would not be a better way to handle this.

File: packages/driver/test/cypress/integration/issues/5274_spec.coffee [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+    cy.request('http://localhost:1234/⍸')
+    cy.request('http://localhost:1234/㇇')
+    cy.request('http://localhost:1234/ヸ')
+    cy.request('http://localhost:1234/ㇻ')
+    cy.request('http://localhost:1234/𓌶')
+    cy.request('http://localhost:1234/🜈')
+    cy.request('http://localhost:1234/🠋')
+    cy.request('http://localhost:1234/👩')
+    cy.request('http://localhost:1234/😀')
+    done()
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/issues/5274_spec.coffee]: calling `done` here will cause the test to immediately pass and it not actually do anything.

File: packages/driver/test/cypress/integration/issues/5274_spec.coffee [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+    cy.request(encodeURI('http://localhost:1234/⍸'))
+    cy.request(encodeURI('http://localhost:1234/㇇'))
+    cy.request(encodeURI('http://localhost:1234/ヸ'))
+    cy.request(encodeURI('http://localhost:1234/ㇻ'))
+    cy.request(encodeURI('http://localhost:1234/𓌶'))
+    cy.request(encodeURI('http://localhost:1234/🜈'))
+    cy.request(encodeURI('http://localhost:1234/🠋'))
+    cy.request(encodeURI('http://localhost:1234/👩'))
+    cy.request(encodeURI('http://localhost:1234/😀'))
+    done()
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/issues/5274_spec.coffee]: calling `done` here will cause the test to immediately pass and it not actually do anything.

File: packages/driver/src/cy/commands/request.coffee (hunk 2 above)
Comment (avallete) [reply packages/driver/src/cy/commands/request.coffee]: I've changed the way I handle the URL, by using the `new URL()`  constructor instead of `encodeURI` allow to both, properly encode unicode in domain (with `xn...`) and percent escape unicode in pathname.

File: packages/driver/test/cypress/integration/issues/5274_spec.coffee (hunk 3 above)
Comment (avallete) [reply packages/driver/test/cypress/integration/issues/5274_spec.coffee]: I've refactored the tests cases to reduce the test with one request by test.

Also, now, the tests are separated into to parts, one who check that there is no 'UNESCAPED_CHARACTER' error, and another one who effectively check if the result value of the url is the one we expect (properly encoded).

File: packages/driver/test/cypress/integration/issues/5274_spec.coffee (hunk 4 above)
Comment (avallete) [reply packages/driver/test/cypress/integration/issues/5274_spec.coffee]: I've refactored the tests cases to reduce the test with one request by test.

Also, now, the tests are separated into to parts, one who check that there is no 'UNESCAPED_CHARACTER' error, and another one who effectively check if the result value of the url is the one we expect (properly encoded).

**Comment by avallete** [comment]
After review comment, I've changed the way I deal with the URL encoding.

I've also refactored the tests to fix the issue raised by @brian-mann

File: packages/driver/test/cypress/integration/issues/5274_spec.coffee [hunk 5]
```diff
@@ -0,0 +1,143 @@
+_ = Cypress._
```
[the remark this answers is not in the document]
Comment (avallete) [reply packages/driver/test/cypress/integration/issues/5274_spec.coffee]: Yes, I totally agree.

I was thinking the same thing but wasn't too sure since I saw a specific 'issue' folder inside the tests.

I've refactored the tests according to your comment :wink:.

File: packages/driver/src/cy/commands/request.coffee [hunk 6]
```diff
@@ -125,6 +125,19 @@ module.exports = (Commands, Cypress, cy, state, config) ->
       if originOrBase = config("baseUrl") or cy.getRemoteLocation("origin")
         options.url = $Location.qualifyWithBaseUrl(originOrBase, options.url)
 
+      ## Make sure the url unicode characters are properly escaped
+      ## https://github.com/cypress-io/cypress/issues/5274
+      try
+        options.url = new URL(options.url).href
+      catch TypeError
```
Comment (brian-mann) [inline packages/driver/src/cy/commands/request.coffee]: this is not doing filtering on the `catch` - it's only yielding the local error instance as `TypeError`

Comment (flotwig) [reply packages/driver/src/cy/commands/request.coffee]: :man_facepalming: at least all the tests pass... @avallete do you want to open up a PR to clean this up, or do you want me to?

Comment (avallete) [reply packages/driver/src/cy/commands/request.coffee]: @brian-mann  Actually my intent here wasn't to filter on the error type because as stated into the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) conditional `catch` based on the type of the error isn't standard. Also, based on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) the only error that a `new URL` failing can throw is a `TypeError` exception. 

So my intent wasn't to filter the error, I do want to globally catch any error raised on this line, and, since the only one who can occur is `TypeError`, I named the variable accordingly.

@flotwig if you do want me to open a PR with specific filtering like: `catch (e if e instanceof TypeError)`

I can do it, no problems ;)

Comment (flotwig) [reply packages/driver/src/cy/commands/request.coffee]: Ah, thank you for clearing that up, we were both scratching our heads trying to figure out the intent here. :sweat_smile:  Opened a PR to clean it up: https://github.com/cypress-io/cypress/pull/5937

Comment (avallete) [reply packages/driver/src/cy/commands/request.coffee]: Nice, sorry for the double work ration for you :stuck_out_tongue:
