### PR TITLE
3.5.0 - fix click events sent to proper element, respect selection changes during cy.click

### LINKED ISSUE #5439: Typing a modifier key anywhere removes selected text from an input in 3.5.0
### Current behavior:

Typing a modifier key ~~into an input~~ anywhere removes selected text in an active input.

### Desired behavior:

Shouldn't touch input value at all.

### Steps to reproduce: (app code and test code)

```js
describe('test', () => {
    it('test', () => {
        cy.document().then(doc => {
            doc.body.innerHTML = `
                <textarea class="one">hello</textarea>
                <textarea class="two">hello</textarea>
                <input class="three" value="hello">
            `;
        });

        // (1) clears whole textarea
        cy.get('.one').type('{selectall}').type('{ctrl}');

        // (2) clears whole textarea
        cy.get('.two').type('{selectall}');
        cy.get('body').type('{ctrl}');

        // (3) removes last letter
        cy.get('.three')
            .focus()
            .then( $input => {
                $input[0].selectionStart = 4;
                $input[0].selectionEnd = 5;
            })
            .type('{ctrl}');
    });
});
```
### Versions

- Cypress `3.5.0`, Win 7, chrome stable 77 (headed) & chrome canary 73 (headless)
- It's possible a regression in older cypress version (I've migrated from `3.3.1` → `3.5.0` directly)

### LINKED ISSUE #5456: 3.5.0 Input select-on-focus no longer working
### Current behavior:

Cypress 3.5.0 is no longer behaving the same way as executing outside of Cypress with regards to an `input` with an `onFocus` handler implemented as `e => e.target.select()` (select-on-focus behavior). It does not appear to select the text (the `onFocus` handler is called, though). The application code has not changed and works "in real life" but fails in Cypress. This worked in Cypress 3.4.1.

### Desired behavior:

The behavior should be consistent with running outside of Cypress, as it was in previous versions.

### Steps to reproduce: (app code and test code)

App code:
```jsx
<input defaultValue="42" onFocus={e => e.target.select()} />
```

Test code:
```js
cy.get('input')
  .should('have.value', '42')
  .click()
  // input has just been focused so its value should now be selected
  // (and thus typing would replace the value, not append to it)
  .type('36')
  // fail - input value is 4236
  .should('have.value', '36');
```

Reproduction repository:
https://github.com/wKovacs64/cypress-350-select-on-focus

### Versions

Cypress 3.5.0
Windows 10, Linux (Circle CI)
Chrome 78, Electron 73

### LINKED ISSUE #5459: 3.5.0 cy.click() behavior change caused broken tests
### Current behavior:

With the update to 3.5.0, Cypress has stopped working with [Select 2](https://select2.github.io/select2/#basics) library, when click() is called on the drop down element, no drop down is shown. @rakhid and I have made a sample test in Cypress and recorded video to show the problem. 

[Video Recording 3.5](https://github.com/leimd/cypress-bug-demo/blob/cypress-35/cypress/videos/test.js.mp4)

### Desired behavior:

When triggering click on the drop down element, a drop down should be shown [Video Recording 3.4](https://github.com/leimd/cypress-bug-demo/blob/cypress-34/cypress/videos/test.js.mp4)

### Steps to reproduce: (app code and test code)

[Here is a sample repo](https://github.com/leimd/cypress-bug-demo) that we made to show the bug, there are two branches: cypress-34 and cypress-35  which has Cypress 3.4.0 and Cypress 3.5.0 in their package.json respectively. By checking out the respective branch and run `npx cypress run`, you can recreate the bug.

### Versions

Cypress 3.5.0
Browser: Chrome & Electron

### PR DESCRIPTION
**Pull request by kuceb**
- [x] fix click during overlay on mousedown, fix selectionchange during focus handler
fix #5459 
- [x] fix no respecting selection changes during click/type
fix #5456
- [x] replacing selection during modifier key
fix #5439

### User facing changelog
- fix click events not being sent to correct elements during `cy.click()` #5459
- fix respect focus selection changes during `cy.type()` #5456 
- fix overwriting selected text while typing a modifer key during `cy.type()` #5439

### Additional details
- [x] links to issues are included

### How has the user experience changed?
- When using cy.type() on input that has handler on focus, and changes selection, we no longer overwrite that selection
- When an element moves in front of the cursor during the `mousedown` event, we no longer send a click to it

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/mouse.js [hunk 1]
```diff
@@ -352,10 +352,14 @@ const create = (state, keyboard, focused) => {
         }
       }
 
-      if ($elements.isInput(el) || $elements.isTextarea(el) || $elements.isContentEditable(el)) {
-        if (!$elements.isNeedSingleValueChangeInputElement(el)) {
+      if (
+        $elements.isElement($elToFocus[0]) &&
+        ($elements.isInput($elToFocus[0]) || $elements.isTextarea($elToFocus[0]) || $elements.isContentEditable($elToFocus[0])) &&
+        $elements.isFocused($elToFocus[0])
+      ) {
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/mouse.js]: should probably pull this out into it's own function, it's a lot of follow. This means: `isTypeableElementWithFocus`?

File: packages/driver/src/cy/mouse.js [hunk 2]
```diff
@@ -404,9 +408,14 @@ const create = (state, keyboard, focused) => {
 
       const mouseUpEvents = mouse.up(fromElViewport, forceEl, skipMouseupEvent, pointerEvtOptionsExtend, mouseEvtOptionsExtend)
 
-      const skipClickEvent = $elements.isDetachedEl(mouseDownEvents.pointerdownProps.el)
+      // Only send click event if the same element received both pointerdown and pointerup, and it's not detached.
+      // This will always be false for force click, so short circuit it here with !forceEl
+      const skipClickEvent = !forceEl && (
+        ($elements.isDetachedEl(mouseDownEvents.pointerdownProps.el) && 'Element was detached') ||
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/mouse.js]: Where does this string `Element was detached` come from? Won't a string always evaluate to true?

Ok, read down to the caller. This is a strange way to me to return an error message. I would rather this be some kind of explicit throw, otherwise I'm sitting here like....what the hell is this string in this comparison operators for? - without the context of the caller this is really weird.

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 3]
```diff
@@ -2467,6 +2543,55 @@ describe('src/cy/commands/actions/click', () => {
...
+            {
+              'Event Name': 'mouseup',
+              'Target Element': { id: 'tabindex' },
+              'Prevented Default?': false,
+              'Stopped Propagation?': false,
+              'Modifiers': null,
+            },
+            {
+              'Event Name': 'click',
+              'Target Element': '⚠️ not fired (Element did not receive pointerup event)',
```
Comment (jennifer-shehane) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]: This is a bit of a strange place to put this warning. I get that we don't have a great place for this now....Also, why is the `pointerup` table logging fine, but then the `click` table mentions the `pointerup` not firing? I would be confused if I read this in the console.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Can you add any links to the bugs this PR is fixing in the tests or code that was added?

Going to pull this down now and actually run it against the open issues.

**Comment by jennifer-shehane** [comment]
I confirmed this fixes https://github.com/cypress-io/cypress/issues/5459 and https://github.com/cypress-io/cypress/issues/5456 when running in this branch.

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 3 above)
Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: different element received pointerup that got pointerdown, would it be more clear to say that?

File: packages/web-config/webpack.config.base.ts [hunk 4]
```diff
@@ -187,7 +187,7 @@ const commonConfig: webpack.Configuration = {
         }),
       ]
     ),
-    ...(liveReloadEnabled ? [new LiveReloadPlugin({ appendScriptTag: 'true', port: 0, hostname: 'localhost' })] : []),
+    ...(liveReloadEnabled ? [new LiveReloadPlugin({ appendScriptTag: 'true', port: 0, hostname: 'localhost', protocol: 'http' })] : []),
```
Comment (Bkucera) [inline packages/web-config/webpack.config.base.ts]: fixes livereload for https domains

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 5]
```diff
@@ -266,7 +268,10 @@ describe('src/cy/commands/actions/click', () => {
     it('will not send mouseEvents/focus if pointerdown is defaultPrevented', () => {
       const $btn = cy.$$('#button')
 
+      // let clicked = false
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]: these are all for debugging purposes, you can comment out 271, 274, and 283 to run the test with a manual click

File: packages/driver/src/cy/mouse.js (hunk 2 above)
Comment (Bkucera) [reply packages/driver/src/cy/mouse.js]: true, I'll clean this up

File: packages/driver/src/cy/mouse.js (hunk 1 above)
Comment (Bkucera) [reply packages/driver/src/cy/mouse.js]: true, let me clean this up

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 6]
```diff
@@ -4146,22 +4273,22 @@ describe('mouse state', () => {
...
         cover.hide()
+        // clicked = true
       })
 
+      attachFocusListeners({ btn, cover })
       attachMouseHoverListeners({ btn, cover })
       attachMouseClickListeners({ btn, cover })
 
       cy.get('#cover').click()
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 7]
```diff
@@ -4146,22 +4273,22 @@ describe('mouse state', () => {
       })
       .appendTo(btn.parent())
 
+      // let clicked = false
+
       cover.on('mouseover', () => {
         cover.hide()
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 8]
```diff
@@ -4146,22 +4273,22 @@ describe('mouse state', () => {
       })
       .appendTo(btn.parent())
 
+      // let clicked = false
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 9]
```diff
@@ -4118,14 +4248,11 @@ describe('mouse state', () => {
       })
 
       cy.get('#cover').click()
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 10]
```diff
@@ -4098,18 +4224,22 @@ describe('mouse state', () => {
...
         height: 50,
         width: 300,
       })
       .appendTo(btn.parent())
 
+      // let clicked = false
+
       cover.on('mouseup', () => {
         cover.hide()
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 11]
```diff
@@ -4098,18 +4224,22 @@ describe('mouse state', () => {
...
-        backgroundColor: 'blue',
+      const cover = cy.$$(/*html*/`<div id='cover'>#cover</div>`).css({
+        backgroundColor: 'salmon',
         position: 'relative',
         height: 50,
         width: 300,
       })
       .appendTo(btn.parent())
 
+      // let clicked = false
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 12]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+
+      // let clicked = false
+
+      btn.on('click', () => {
+        // clicked = true
+        div.css(overlayStyle)
+      })
+
+      cy.contains('button').click()
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 13]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
+
+      btn.on('click', () => {
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 14]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+
+    it('events when element moved on click', () => {
+      const btn = cy.$$('button:first')
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 15]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+
+      btn.on('mouseup', () => {
+        // clicked = true
+        div.css(overlayStyle)
+      })
+
+      cy.contains('button').click()
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 16]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
+
+      btn.on('mouseup', () => {
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 17]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+
+    it('events when element moved on mouseup', () => {
+      const btn = cy.$$('button:first')
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 18]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+
+      btn.on('mousedown', () => {
+        // clicked = true
+        div.css(overlayStyle)
+      })
+
+      cy.contains('button').click()
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 19]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
+
+      btn.on('mousedown', () => {
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 20]
```diff
@@ -378,6 +384,76 @@ describe('src/cy/commands/actions/click', () => {
...
+    // https://github.com/cypress-io/cypress/issues/5459
+    it('events when element moved on mousedown', () => {
+      const btn = cy.$$('button:first')
+      const div = cy.$$('div#tabindex')
+
+      attachFocusListeners({ btn, div })
+      attachMouseClickListeners({ btn, div })
+      attachMouseHoverListeners({ btn, div })
+
+      // let clicked = false
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 21]
```diff
@@ -275,6 +280,7 @@ describe('src/cy/commands/actions/click', () => {
       attachMouseClickListeners({ $btn })
 
       cy.get('#button').click().should('not.have.focus')
+      // cy.wrap(null).should(() => expect(clicked).ok)
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js [hunk 22]
```diff
@@ -266,7 +268,10 @@ describe('src/cy/commands/actions/click', () => {
     it('will not send mouseEvents/focus if pointerdown is defaultPrevented', () => {
       const $btn = cy.$$('#button')
 
+      // let clicked = false
+
       $btn.get(0).addEventListener('pointerdown', (e) => {
+        // clicked = true
```
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 5 above)
Comment (flotwig) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.js]:
```suggestion
```

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 5 above)
Comment (flotwig) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: ah, disregard my comments then, it would be nice if this was commented somewhere in the file but they are in so many places that would still be hard to discover

**Comment by Bkucera** [comment]
@jennifer-shehane I added an issue this fixes, #5439

File: packages/driver/src/cy/mouse.js (hunk 2 above)
Comment (jennifer-shehane) [reply packages/driver/src/cy/mouse.js]: So much clearer. 😅

File: packages/driver/test/cypress/integration/commands/actions/click_spec.js (hunk 3 above)
Comment (jennifer-shehane) [reply packages/driver/test/cypress/integration/commands/actions/click_spec.js]: If the click event is not fired, I would just expect this table to not exist. Is it normal for us to log an event table and say 'not fired'? 

I would probably not log the click event table and in the `pointerup` table maybe log there that the element is a different element than received the `pointerdown`? 😬

**Comment by jennifer-shehane** [comment]
I confirmed this also fixes https://github.com/cypress-io/cypress/issues/5439

File: package.json [hunk 23]
```diff
@@ -47,7 +47,7 @@
     "set-next-ci-version": "node ./scripts/binary.js setNextVersion",
     "prestart": "npm run check-deps-pre",
     "start": "node ./cli/bin/cypress open --dev --global",
-    "stop-only": "npx stop-only --skip .cy,.publish,.projects,node_modules,dist,dist-test,fixtures,lib,bower_components --exclude e2e.coffee",
+    "stop-only": "npx stop-only --skip .cy,.publish,.projects,node_modules,dist,dist-test,fixtures,lib,bower_components,src --exclude e2e.coffee",
```
Comment (jennifer-shehane) [inline package.json]: Does this address this issue? https://github.com/cypress-io/cypress/issues/5518

**Review by jennifer-shehane — APPROVED** [review]

**Review by flotwig — APPROVED** [review]
