### PR TITLE
Fix `cypress run --headless`

### LINKED ISSUE #5949: Running with headless chrome settings opens a visible maximized chrome instance
running `cypress run --headless --browser chrome`  opens a visible maximized (it does not adhere viewportWidth and viewportHeight settings) Chrome instance. I would expect it to run headless with the correct dimensions.

Interestingly, it does report to be running chrome 78 headless:
image

```
Cypress: 3.8.0
OS: Microsoft Windows 10 Enterprise Version 10.0.16299 Build 16299
```

_Originally posted by @Waterstraal in https://github.com/cypress-io/cypress/issues/832#issuecomment-565358299_

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5949

### User facing changelog

- Fixed a bug where `cypress run --headless` would not run Chrome-family browsers headlessly.

### Additional details

- mis-merged a decaffeinated version of `chrome.js` and tests didn't catch it :/

#### Results of Browser.getWindowBounds:  

|    | chrome |
| --- | --- |
| headless | 800x600 |
| headed | 1050x1004 |

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/browsers/chrome.js [hunk 1]
```diff
@@ -118,7 +118,11 @@ const pluginsBeforeBrowserLaunch = function (browser, args) {
   })
 }
 
-const _normalizeArgExtensions = function (dest, args) {
+const _normalizeArgExtensions = function (dest, args, browser) {
```
Comment (bahmutov) [inline packages/server/lib/browsers/chrome.js]: can we have some JSDocs here? or comments if the browser is headless, then we cannot load any extensions, thus we return arguments as is. Because it is unclear what this function does - if the browser is headless we return args - but what if the arguments include `LOAD_EXTENSION`? shouldn't we filter them out?

File: packages/server/test/unit/browsers/chrome_spec.coffee [hunk 2]
```diff
@@ -70,16 +70,17 @@ describe "lib/browsers/chrome", ->
 
     it "does not load extension in headless mode", ->
       plugins.has.returns(false)
+      chrome._writeExtension.restore()
 
       pathToTheme = extension.getPathToTheme()
 
-      chrome.open("chrome", "http://", { isHeadless: true, isHeaded: false }, @automation)
+      chrome.open({ isHeadless: true, isHeaded: false }, "http://", {}, @automation)
```
Comment (bahmutov) [inline packages/server/test/unit/browsers/chrome_spec.coffee]: I feel here it would be helpful to extract arguments into named objects like maybe
```
browserInfo = {
  isHeadless: true,
  isHeaded: false
}
urlToLoad = "http://"
options = {}
chrome.open(browserInfo, urlToLoad, options, @automation)
```

File: packages/server/lib/browsers/chrome.js (hunk 1 above)
Comment (flotwig) [reply packages/server/lib/browsers/chrome.js]: if the plugin returns extensions, they are filtered out elsewhere. in any case, chrome will still successfully launch with `--load-extension` passed, but no extension will really be loaded

Comment (flotwig) [reply packages/server/lib/browsers/chrome.js]: converted the .js to .ts and added documentation: 86969ee

File: packages/server/lib/browsers/chrome.ts [hunk 3]
```diff
@@ -269,14 +295,14 @@ module.exports = {
...
-  _getArgs (options = {}) {
+  _getArgs (options: CypressConfiguration = {}) {
     let ps; let ua
 
     _.defaults(options, {
       browser: {},
     })
 
-    const args = [].concat(defaultArgs)
+    const args = ([] as string[]).concat(defaultArgs)
```
Comment (bahmutov) [inline packages/server/lib/browsers/chrome.ts]: the beauty of TypeScript

File: packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js [hunk 4]
```diff
@@ -1,8 +1,62 @@
...
+        command: 'Browser.getWindowBounds',
+        params: {
+          windowId,
+        },
+      })
+    })
+    .then(({ bounds }) => {
+      expect(bounds).to.include({
+        width: expectedHeadless ? 800 : 1050,
+        height: expectedHeadless ? 600 : 1004,
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: 800x600 is the expected dimensions when running headlessly in CI?

Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: yes, that seems to be the reported "window bounds" when running with `--headless`

Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: it seems to be 800x600 irrespective of where you ran it - i get the same thing running outside of the docker container

Comment (brian-mann) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: This is really weird... maybe leave a comment that this is expected behavior. It makes me think we shouldn't even be writing this test this way - it communicates kind of the wrong thing, and your other two tests already pretty much guarantee that `headless` is correct.

Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: Yeah, the only value this test really adds is to give us a warning if Chrome or Xvfb change their behavior. 

There is already a comment, should I add something to it?

```
    // in CI with Xvfb, Cypress will fill the entire screen, this test is to explicitly
    // assert on the expected dimensions
```

Comment (brian-mann) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: I would probably just remove the test for now

Comment (flotwig) [reply packages/server/test/support/fixtures/projects/e2e/cypress/integration/headless_spec.js]: deleted
