### PR TITLE
fix: browser-skipped tests are correctly recorded to the dashboard

### LINKED ISSUE #23517: Dashboard shows tests for review as modified when they are not modified
### Current behavior

Reported internally, slack discussion here: https://cypressio.slack.com/archives/C9KG9TQBX/p1660156177204799
Corresponding CLOUD issue here: https://cypress-io.atlassian.net/browse/CLOUD-820

Appears in this example that the test runner is skipping some tests when run on Firefox but not skipping on Chrome, but test runner is not reporting the skipped tests to the dashboard. Dashboard does not consider browser when determining modified state so the remove/re-add behavior is being treated as a modification

### Desired behavior

Test runner should send all tests to the dashboard even if they're skipped

### Test code to reproduce

See slack conversation

### Cypress Version

10.6.0

### Node version

16.14.2

### Operating System

macOS 12.5.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #23517

Ensure the test body and original test title is always recorded to the cloud, regardless of browser-skip state, to ensure the cloud does not incorrectly mark the test as "new" or "modified".

### Test Steps:
Verified by recording to Staging & running system-tests/projects/e2e/record_config.cy.js using Edge & Chrome:

```sh
CYPRESS_INTERNAL_ENV=staging yarn cypress:run --dev --project ./system-tests/projects/e2e --spec ./system-tests/projects/e2e/cypress/e2e/config_record.cy.js --config projectId=ypt4pf --record --key <KEY> --browser <BROWSER>
```

**Showing Issue:**
- [First run w Edge](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2649/overview) - 2 ran, 2 pending  - all correctly showing as first seen
- [Test Skip w Chrome](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2650/overview) - 1 ran, 2 pending, 1 pending due to browser - test body is missing so it was marked as modified & has modified tag
- [Adding Browser-specific Suite w/ Edge](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2666/overview) - 4 ran, 2 pending & 2 correctly showing as first seen
- [Suite Skip w Chrome](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2667/overview) -  1 ran, 2 pending, 3 pending due to browser - suite is skipped due to browser (note test is correct here due to partial fix) - all incorrectly marked as first seen because title path was incorrectly restored by the App and body is missing

**Showing Fixes:**
- [First run (accidentally) w/ Chrome](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2668/overview) - one test ran - all correctly showing first seen and all skipped tests have test definition when opening test drawer (opened by clicking on test row).
- [Second run w/ Edge](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2669/overview) - 4 ran, 2 pending  & one legit failure
- [Third run w/ Edge](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2670/overview) -  4 ran, 2 pending & all passed - correctly marked nothing for review
- [Fourth run w/ Chrome](https://dashboard-staging.cypress.io/projects/ypt4pf/runs/2671/overview) - 1 ran, 2 pending, 3 pending due to browser  - correctly marked nothing for review

### User facing changelog
Fixed as issue where browser-skipped tests were incorrectly recorded to the dashboardDashboard which resulted in the Dashboard marking the test as "new" or "modified" when it already existed. Fixes [#23517](https://github.com/cypress-io/cypress/issue/23517).

### How has the user experience changed?

Browser-skipped tests are correctly recorded to the dashboard.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/cypress/e2e/runner/support/mochaEventsUtils.ts [hunk 1]
```diff
@@ -157,9 +150,18 @@ export function runCypressInCypressMochaEventsTest<T> (snapshots: T, snapToCompa
     if (diff !== '') {
       /* eslint-disable no-console */
       console.info('Received snapshot:', JSON.stringify(snapshot, null, 2))
-      throw new SnapshotError(diff)
+
+      cy.fail(new Error(`The captured mocha events did not match the "${String(snapToCompare)}" snapshot.\n${diff}`), { async: false })
+
+      return done()
```
Comment (emilyrohrbough) [inline packages/app/cypress/e2e/runner/support/mochaEventsUtils.ts]:
```suggestion
      return cy.fail(new Error(`The captured mocha events did not match the "${String(snapToCompare)}" snapshot.\n${diff}`), { async: false })
```

File: packages/driver/src/cypress/mocha.ts [hunk 2]
```diff
@@ -35,13 +35,22 @@ const suiteAfterEach = Suite.prototype.afterEach
...
-  ret.originalTitle = originalTitle
+  // attached testConfigOverrides will execute before `runner:test:before:run` event
+  if (_testConfig) {
+    runnable._testConfig = _testConfig
+  }
+
+  if (fnType === 'Test') {
+    // persist the original callback so we can send it to the cloud
+    // to prevent it from being registered as a modified test
+    runnable.body = testCallback.toString()
```
Comment (BlueWinds) [inline packages/driver/src/cypress/mocha.ts:50]: Since testCallback is always defined - either a function or a string (usually an empty string) - it looks like we could remove the if, and just always `runnable.body = testCallback.toString()`, regardless of fnType. Then we'd always have runnable.body defined, and the shape would be more consistent.

Or even better, set `''` as a default argument, and skip the `|| ''`s below in overloadMochaFnForConfig.

File: packages/driver/src/cypress/mocha.ts [hunk 3]
```diff
@@ -35,13 +35,22 @@ const suiteAfterEach = Suite.prototype.afterEach
 delete (window as any).mocha
 delete (window as any).Mocha
 
-function invokeFnWithOriginalTitle (ctx, originalTitle, mochaArgs, fn, _testConfig) {
-  const ret = fn.apply(ctx, mochaArgs)
+type MochaArgs = [string, Function | undefined]
+function createRunnable (ctx, fnType: 'Test' | 'Suite', mochaArgs: MochaArgs, runnableFn: Function, testCallback: Function | string, _testConfig?: Record<string, any>) {
```
Comment (BlueWinds) [inline packages/driver/src/cypress/mocha.ts]: If we set a default value of `_testConfig?: Record<string, any> = {}`, then we'll always have one, and can remove the conditional around `if (_testConfig) {}` both here and later in this file.

In general I'm a fan of default values as a way of avoiding checking if a thing is defined - just make sure it always is, one way or another.

File: packages/driver/src/cypress/runner.ts [hunk 4]
```diff
@@ -147,11 +149,14 @@ const setWallClockDuration = (test) => {
...
 // us from recursively iterating through every
 // parent since we could just return the found test
-const wrap = (runnable) => {
+const wrap = (runnable): Record<string, any> | null => {
   return $utils.reduceProps(runnable, RUNNABLE_PROPS)
 }
 
-const wrapAll = (runnable): any => {
+// Reduce runnable down to its props and collections.
+// Sent the the Reporter to populate command log
```
Comment (BlueWinds) [inline packages/driver/src/cypress/runner.ts]: Sent by who? I'm not really sure what this comment is trying to tell me.

Edit: I think it makes more sense below where wrapAll is used, rather than up here where it's defined.

**Review by BlueWinds — APPROVED** [review]

File: packages/driver/src/cypress/runner.ts (hunk 4 above)
Comment (emilyrohrbough) [inline packages/driver/src/cypress/runner.ts]:
```suggestion
// Sent to the Reporter to populate command log
```

File: packages/driver/src/cypress/mocha.ts [hunk 5]
```diff
@@ -66,40 +75,44 @@ function overloadMochaFnForConfig (fnName, specWindow) {
 
       const origFn = subFn ? _fn[subFn] : _fn
 
+      // fallback to empty string for stubbed runnables written like:
+      // - describe('concept')
+      // - it('does something')
+      let testCallback = args[1] || ''
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/mocha.ts]:
```suggestion
      let testCallback = args[1]
```

File: packages/driver/src/cypress/mocha.ts [hunk 6]
```diff
@@ -66,40 +75,44 @@ function overloadMochaFnForConfig (fnName, specWindow) {
...
         const _testConfig = _.extend({}, args[1]) as any
 
-        const mochaArgs = [args[0], args[2]]
+        const mochaArgs: MochaArgs = [args[0], args[2]]
+        const originalTitle = mochaArgs[0]
+
+        // fallback to empty string for stubbed runnables written like:
+        // - describe('concept')
+        // - it('does something')
+        testCallback = mochaArgs[1] || ''
```
Comment (emilyrohrbough) [inline packages/driver/src/cypress/mocha.ts]:
```suggestion
        testCallback = mochaArgs[1]
```

File: packages/driver/src/cypress/mocha.ts (hunk 3 above)
Comment (emilyrohrbough) [inline packages/driver/src/cypress/mocha.ts]:
```suggestion
function createRunnable (ctx, fnType: 'Test' | 'Suite', mochaArgs: MochaArgs, runnableFn: Function, testCallback: Function | string = '', _testConfig?: Record<string, any>) {
```

File: packages/driver/src/cypress/mocha.ts (hunk 2 above)
Comment (emilyrohrbough) [reply packages/driver/src/cypress/mocha.ts:50]: We only want to set on Test body for now.

File: packages/driver/src/cypress/error_utils.ts [hunk 7]
```diff
@@ -9,7 +9,7 @@ import $stackUtils, { StackAndCodeFrameIndex } from './stack_utils'
 import $utils from './utils'
 import type { HandlerType } from './runner'
 
-const ERROR_PROPS = 'message type name stack parsedStack fileName lineNumber columnNumber host uncaught actual expected showDiff isPending docsUrl codeFrame'.split(' ')
+const ERROR_PROPS = ['message', 'type', 'name', 'stack', 'parsedStack', 'fileName', 'lineNumber', 'columnNumber', 'host', 'uncaught', 'actual', 'expected', 'showDiff', 'isPending', 'docsUrl', 'codeFrame'] as const
```
Comment (mjhenkes) [inline packages/driver/src/cypress/error_utils.ts:12]: ❤️

**Review by mjhenkes — APPROVED** [review]
