### PR TITLE
fix: Fix cross-origin cy.pause()

### LINKED ISSUE #21495: cy.pause in cy.origin
Add support for `cy.pause` within `cy.origin`.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #21495

### User facing changelog

- `cy.pause()` now functions correctly when called within the `cy.origin()` callback

### Additional details

The 'paused' event sent by `cy.pause()` was not making its way to the reporter via the runner, causing the correct UI not to show. The subsequent 'resume:next' and 'resume:all' events also needed to be wired up to be sent back to the spec bridge that sent the 'paused' event.

### Steps to test

Running the following should pause on the `cy.pause()`, with ▶️⏭ buttons in the reporter that function correctly for moving to the next command and resuming.

```js
cy.visit('http://localhost:3500/fixtures/primary-origin.html')
cy.get('a[href="http://www.foobar.com:3500/fixtures/secondary-origin.html"]').click()

cy.origin('http://www.foobar.com:3500', () => {
  cy.pause()
  cy.get('div')
  cy.log('something')
})
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cy/commands/origin/index.ts [hunk 1]
```diff
@@ -64,6 +64,7 @@ export default (Commands, Cypress: Cypress.Cypress, cy: Cypress.cy, state: State
         name: 'origin',
         type: 'parent',
         message: urlOrDomain,
+        timeout: 0,
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/origin/index.ts:67]: This is an incidental fix. I noticed that `cy.origin()` has a visual timer bar that goes across it in the command log (regardless of `cy.pause()` usage, but particularly noticeable with `cy.pause()`. The log for `cy.origin()` shouldn't have a timeout anyway since the command itself does not have a timeout.

File: packages/app/src/runner/event-manager.ts [hunk 2]
```diff
@@ -225,18 +225,6 @@ export class EventManager {
 
     this.reporterBus.on('runner:unpin:snapshot', this._unpinSnapshot.bind(this))
 
-    this.reporterBus.on('runner:resume', () => {
```
Comment (chrisbreiding) [inline packages/app/src/runner/event-manager.ts:228]: Moved all the pause-related events to `runner/events/pausing.ts` to reduce some of the bloat in this file.

File: packages/driver/cypress/e2e/e2e/origin/commands/misc.cy.ts [hunk 3]
```diff
@@ -37,10 +37,22 @@ context('cy.origin misc', { browser: '!webkit' }, () => {
   })
 
   it('.pause()', () => {
+    // ensures the 'paused' event makes it to the event-manager in the primary.
+    // if we get cross-origin cy-in-cy test working, we could potentially make
+    // this even more end-to-end: test out the reporter UI and click the
+    // resume buttons instead of sending the resume:all event
+    Cypress.primaryOriginCommunicator.once('paused', ({ nextCommandName, origin }) => {
```
Comment (mschile) [inline packages/driver/cypress/e2e/e2e/origin/commands/misc.cy.ts:44]: Does the `consoleProps.pause` test in this file also need to be updated?

Comment (chrisbreiding) [reply packages/driver/cypress/e2e/e2e/origin/commands/misc.cy.ts:44]: I think it's okay to leave it as is. It basically short-circuits the communication with the runner, which is fine for the sake of testing out the consoleProps.

**Review by mschile — APPROVED** [review]

File: packages/driver/cypress/e2e/e2e/origin/commands/misc.cy.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/cypress/e2e/e2e/origin/commands/misc.cy.ts:44]: I don't think so since the test only handles the interactive case and I think the only think that actually gets put out in the consoleProps is the command name when running in open mode.

**Review by AtofStryker — APPROVED** [review]
