### PR TITLE
fix: correct invalid stored preference for in-app notifications

### LINKED ISSUE #27228: Cypress v12.17.0 crashes when notifications are enabled
### Current behavior

I've just upgraded Cypress to v12.17.0 on a sample project, to test the desktop notifications.

I've enabled all the possible notifications, and pushed the change with the upgrade.

When the run finished, the Cypress App crashed, closed automatically, and left me with the following error in the logs. Also, now, when I open the Cypress App, it automatically crashes with the same error.

```sh
o.includes is not a function
TypeError: o.includes is not a function
    at m.sendRunCompletedNotification (<embedded>:4344:95669)
    at m.maybeSendRunNotification (<embedded>:4344:94952)
    at D.x (<embedded>:4225:4181)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D.checkRelevantRuns (<embedded>:4225:2179)
    at async g.callback (<embedded>:4225:2495)
    at async g.p (<embedded>:4201:16922)
    at async Timeout._onTimeout (<embedded>:4201:17125)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (22.5.0)
Cypress Version: 12.17.0

 *  The terminal process "/bin/zsh '-c', 'npm run cy:open'" terminated with exit code: 1.
```

### Desired behavior

No crash should happen.

### Test code to reproduce

https://github.com/wlsf82/testes-e2e-com-cypress-tat-v2

### Cypress Version

12.17.0

### Node version

v18.15.0

### Operating System

macOS Ventura 13.4.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by warrensplayer**
- Closes https://github.com/cypress-io/cypress/issues/27228

### Additional details

When navigating to the settings page after enabling in-app notifications with the top banner, the value for the `notifyWhenRunCompletes` setting was not given a chance to load before saving off the value in  a Vue `ref`.  The HTML expected the value to be an array and the backend was trying to default the value to `['failed']`, but it would end up `null` in this case.  If the user attempted to click one of the checkboxes to set the value, then the code would cause the value to get set as a boolean `true` instead of an array of strings.  Finally, if a notification attempted to be fired, or the app was closed and opened again, code that expected the value for `notifyWhenRunCompletes` to be an array would cause the app to crash. 

The fix was to reactively set the value for `notifyWhenRunCompletes` in the `NotifcationSettings` component once it had loaded when navigating from the top banner.  Also, a fix was added to `LocalSettingsActions.refreshLocalSettings()` to make sure to fix this preference value if it was set to a `boolean`.

### Steps to test

_Reproduce the original issue_

* When on the `develop` branch, open the `state.json` file under `~/Library/Application Support/Cypress/cy/production/projects/__global__` and remove the following values:
  * `desktopNotificationsEnabled`
  * `notifyWhenRunCompletes`
  * `notifyWhenRunStartsFailing`
  * `notifyWhenRunStarts`
* Start Cypress in open mode and open the App from the Launchpad
* Click the "Enable desktop notifications" button
* The app will navigate to the "Desktop notifications" part of the Settings page
* Confirm that the "Notify me when a run completes" section has nothing checked
* Check one box and they will all show checked
* Open the `state.json` file from above and notice that the `notifyWhenRunCompletes` value will be `true`
* Close the Cypress app and reopen it
* When the app tries to show the page for selecting the testing type, it will crash

**Before fix**

https://github.com/cypress-io/cypress/assets/1702361/c0f42960-85c2-4556-900a-14004369f8dd

_Testing fix to repair bad value_

* Update to this branch
* Open the app again
* The app should not crash
* Open the `state.json` file from above and notice that the `notifyWhenRunCompletes` value will be an array of strings
* Navigate to the ""Desktop notifications" part of the Settings page and change the values for the "Notify me when a run completes" section
* Confirm those values are saved in the `state.json` file

_Testing new code without existing settings_

* Make sure app is closed
* While on this branch, open the `state.json` file under `~/Library/Application Support/Cypress/cy/production/projects/__global__` and remove the same values as listed above
* Open the app and a testing mode and click the "Enable desktop notifications" button
* The app will navigate to the "Desktop notifications" part of the Settings page
* Confirm that the "Notify me when a run completes" section has only `failed` checked as the default
* Change the options under this section
* Confirm those values are saved in the `state.json` file

**After fix**

https://github.com/cypress-io/cypress/assets/1702361/ab727220-69b5-441b-861f-844e51df105d

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
So far this seems to be working well when testing 👍 - going to try some more scenarios.

Noticed we link to https://docs.cypress.io/guides/cloud/cypress-app-integration#Troubleshooting for troubleshooting, but that URL is 404, if we need to change anything for that we should do it in this PR.

File: packages/app/src/settings/device/NotificationSettings.vue [hunk 1]
```diff
@@ -157,7 +157,14 @@ const switches = [
   },
 ]
 
-const listRef = ref(props.gql.localSettings.preferences.notifyWhenRunCompletes)
+const listRef = ref()
+
+// allow for gql value to load when navigating straight here from EnableNotificationsBanner
+watchEffect(() => {
```
Comment (mike-plummer) [inline packages/app/src/settings/device/NotificationSettings.vue:163]: IIRC there's a `vueuse/core` function that effectively does this a bit more succinctly, but this gets the job done so I'm fine with it

File: cli/CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@ _Released 07/18/2023 (PENDING)_
 
 **Bugfixes:**
 
+- Fixed invalid stored preference for in-app notifications.  Addresses [#27228](https://github.com/cypress-io/cypress/issues/27228).
```
Comment (mike-plummer) [inline cli/CHANGELOG.md]: Should this be "Fixes ..."?

Comment (mike-plummer) [reply cli/CHANGELOG.md]: Also, might want to phrase in a way that would be obvious to the user the impact they would see from adopting this version: "Fixes a potential application crash when enabling in-app notifications."

**Review by mike-plummer — COMMENTED** [review]
No test 😢 ?

**Review by jordanpowell88 — APPROVED** [review]
PR looks good to me. Ideally the `NotifyWhenRunCompletes` would never be a type `boolean` in the first place but this PR certainly accounts for the scenario in which it is.

**Comment by marktnoonan** [comment]
It looks like a [PR](https://github.com/cypress-io/cypress-services/commit/d4cbe3296d1c6ccc40e96be24cce278a611818f3) has already been merged for the on-link that was 404, just hasn't been deployed yet, so no action needed in this branch to get it working.

File: cli/CHANGELOG.md (hunk 2 above)
Comment (warrensplayer) [reply cli/CHANGELOG.md]: See: https://github.com/cypress-io/cypress/pull/27237/commits/986398ae136238cd6907ca9bfa34a04066616b33

**Comment by warrensplayer** [comment]
@mike-plummer 
> No test 😢 ?

Added https://github.com/cypress-io/cypress/pull/27237/commits/dcc13c063418fd6cfa712e442ce57b680a280408

**Review by marktnoonan — APPROVED** [review]
Looks good, glad to have the test, it successfully repaired the state for me.

**Review by mike-plummer — APPROVED** [review]

**Comment by wlsf82** [comment]
Do you have a date for the fix release?

**Comment by lmiller1990** [comment]
First thing next week (July 10)

Sorry, thanks for the interest @wlsf82 🎉
