### PR TITLE
fix: handle async before:spec event handler

### LINKED ISSUE #24403: [setupNodeEvents] on("before:spec", ()=>...) doesn't await the promise returned by the event handler
### Current behavior

The promise returned by the event handler of `before:spec` is not awaited but is run concurrently, alongside the spec.

### Desired behavior

As specified in the docs here: https://docs.cypress.io/api/plugins/before-spec-api#Syntax, `before:spec` is supposed to await the completion of the promise returned by it before running the spec.

### Test code to reproduce

See https://github.com/ioannisNoukakis/cypress_before_spec_promise, contact me if any questions

### Cypress Version

10.11.0

### Node version

v16.17.0

### Operating System

Manjaro 22.0.0 Sikaris - x86_64 Linux 5.15.74-3-MANJARO

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #24403

Correctly await async `before:spec` event handlers per the documentation specifications.

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/socket-base.ts [hunk 1]
```diff
@@ -67,12 +67,14 @@ export class SocketBase {
...
   private _sendFocusBrowserMessage
 
+  protected inRunMode: boolean
   protected supportsRunEvents: boolean
   protected ended: boolean
   protected _io?: socketIo.SocketIOServer
   localBus: EventEmitter
 
   constructor (config: Record<string, any>) {
+    this.inRunMode = config.isTextTerminal
```
Comment (lmiller1990) [inline packages/server/lib/socket-base.ts:56]: Should this just be a getter instead of a duplicate property?

```js
get inRunMode () {
  return config.isTextTerminal
}
```

File: system-tests/test/plugin_run_events_spec.ts [hunk 2]
```diff
@@ -6,29 +6,34 @@ describe('e2e plugin run events', () => {
...
+    snapshot: true,
+    configFile: 'cypress.config.beforeSpec.async.js',
+  })
+
   systemTests.it('handles video being deleted in after:spec', {
     browser: 'electron',
-    project: 'plugin-after-spec-deletes-video',
-    spec: '*',
+    project: 'plugin-run-events',
+    // project: 'plugin-after-spec-deletes-video',
```
Comment (lmiller1990) [inline system-tests/test/plugin_run_events_spec.ts]: Can remove comment

File: packages/app/src/runner/SpecRunnerOpenMode.vue [hunk 3]
```diff
@@ -217,10 +217,9 @@ const isSpecsListOpenPreferences = computed(() => {
 
 const hideCommandLog = runnerUiStore.hideCommandLog
 
-// watch active spec, and re-run if it changes!
-startSpecWatcher()
-
 onMounted(() => {
+  // watch active spec, and re-run if it changes!
+  startSpecWatcher()
```
Comment (lmiller1990) [inline packages/app/src/runner/SpecRunnerOpenMode.vue]: I wonder why we needed to wait until the element was rendered to call this?

File: packages/app/src/runner/event-manager.ts [hunk 4]
```diff
@@ -361,19 +360,31 @@ export class EventManager {
   }
 
   setup (config) {
-    Cypress = this.Cypress = this.$CypressDriver.create(config)
+    this.ws.emit('watch:test:file', config.spec)
```
Comment (lmiller1990) [inline packages/app/src/runner/event-manager.ts:363]: Do we want to watch the test file during run mode? This sounds like an open mode specific thing.

Comment (lmiller1990) [reply packages/app/src/runner/event-manager.ts:363]: Eg should this be under the check on line 365-368?

File: packages/app/src/runner/event-manager.ts [hunk 5]
```diff
@@ -361,19 +360,31 @@ export class EventManager {
...
+        // FIXME: handle surfacing the error to the browser instead of hanging with
+        // 'Your tests are loading...' message. Fix in https://github.com/cypress-io/cypress/issues/23627
+        if (res && res.error) {
+          reject(res.error)
+        }
 
-    this.ws.emit('watch:test:file', config.spec)
+        resolve(null)
+      })
+    }).then(() => {
```
Comment (lmiller1990) [inline packages/app/src/runner/event-manager.ts]: You can (probably) just use `async/await` here (if you want, that is - I don't think this part is impacted by the whole "async doesn't work properly" since this is outside of the driver, but either way is fine by me.

**Comment by lmiller1990** [comment]
I will assign @cypress-io/component-testing, since we are working in this area the most nowdays.

File: packages/app/src/runner/index.ts [hunk 6]
```diff
@@ -61,8 +61,6 @@ export function getEventManager () {
   return _eventManager
 }
```
Comment (emilyrohrbough) [inline packages/app/src/runner/index.ts]:
```suggestion
window.getEventManager = getEventManager

```

File: system-tests/test/plugin_run_events_spec.ts (hunk 2 above)
Comment (emilyrohrbough) [inline system-tests/test/plugin_run_events_spec.ts]:
```suggestion
```

File: packages/app/src/runner/event-manager.ts (hunk 5 above)
Comment (emilyrohrbough) [reply packages/app/src/runner/event-manager.ts]: The `async won't work properly` concept is tied to writing Cypress tests, not the code so await should work fine.

File: packages/app/src/runner/event-manager.ts (hunk 4 above)
Comment (emilyrohrbough) [reply packages/app/src/runner/event-manager.ts:363]: It likely should but that is outside of the scope of this change and would require additionally testing. Going to leave as it for the PR.

File: packages/app/src/runner/SpecRunnerOpenMode.vue (hunk 3 above)
Comment (emilyrohrbough) [inline packages/app/src/runner/SpecRunnerOpenMode.vue]:
```suggestion
  // watch active spec, and re-run if it changes!
  startSpecWatcher()
  
onMounted(() => {
```

Comment (emilyrohrbough) [reply packages/app/src/runner/SpecRunnerOpenMode.vue]: this is left over from attempts in trying to correct this behavior in open mode. changing back for now. but my original thought was there wasn't any. need to watch if a spec was changes from a user in the app if the content wasn't mounted & rendered yet.

File: packages/app/src/runner/SpecRunnerOpenMode.vue [hunk 7]
```diff
@@ -217,9 +217,9 @@ const isSpecsListOpenPreferences = computed(() => {
 
 const hideCommandLog = runnerUiStore.hideCommandLog
 
-// watch active spec, and re-run if it changes!
-startSpecWatcher()
-
+  // watch active spec, and re-run if it changes!
+  startSpecWatcher()
+
```
Comment (emilyrohrbough) [inline packages/app/src/runner/SpecRunnerOpenMode.vue]:
```suggestion

```

File: packages/app/src/runner/SpecRunnerOpenMode.vue [hunk 8]
```diff
@@ -217,9 +217,8 @@ const isSpecsListOpenPreferences = computed(() => {
 
 const hideCommandLog = runnerUiStore.hideCommandLog
 
-// watch active spec, and re-run if it changes!
-startSpecWatcher()
-
+  // watch active spec, and re-run if it changes!
+  startSpecWatcher()
```
Comment (emilyrohrbough) [inline packages/app/src/runner/SpecRunnerOpenMode.vue]:
```suggestion
// watch active spec, and re-run if it changes!
startSpecWatcher()
```

File: packages/app/src/runner/SpecRunnerOpenMode.vue [hunk 9]
```diff
@@ -219,7 +219,6 @@ const hideCommandLog = runnerUiStore.hideCommandLog
 
 // watch active spec, and re-run if it changes!
 startSpecWatcher()
```
Comment (emilyrohrbough) [inline packages/app/src/runner/SpecRunnerOpenMode.vue]:
```suggestion
startSpecWatcher()

```

File: packages/app/src/runner/index.ts [hunk 10]
```diff
@@ -60,7 +60,6 @@ export function getEventManager () {
 
   return _eventManager
 }
-
 window.getEventManager = getEventManager
```
Comment (emilyrohrbough) [inline packages/app/src/runner/index.ts]:
```suggestion

window.getEventManager = getEventManager
```

File: packages/server/lib/socket-base.ts (hunk 1 above)
Comment (emilyrohrbough) [reply packages/server/lib/socket-base.ts:56]: The configuration isn't available on this class outside of initialization. It is lighter pull out this specific property.

File: packages/server/lib/socket-base.ts [hunk 11]
```diff
@@ -553,10 +555,17 @@ export class SocketBase {
...
+        socket.on('plugins:before:spec', (spec, cb) => {
+          runEvents.execute('before:spec', spec)
+          .then(cb)
+          .catch((error) => {
+            if (this.inRunMode) {
+              socket.disconnect()
+              throw error
+            }
+
+            // surfacing the error to the browser in open mode
```
Comment (emilyrohrbough) [inline packages/server/lib/socket-base.ts]:
```suggestion
            // surfacing the error to the app in open mode
```

File: packages/server/lib/socket-base.ts (hunk 1 above)
Comment (lmiller1990) [reply packages/server/lib/socket-base.ts:56]: Right, didn't realize that - no problem.

**Review by lmiller1990 — APPROVED** [review]
Great, looks good to me.

**Review by AtofStryker — APPROVED** [review]
