### PR TITLE
fix: Remove default esModuleInterop option from ts-node and preprocessor

### LINKED ISSUE #7575: Opinionated TS transpilation without overrides is problematic
### Current behavior:
Cypress recently added better native support for TypeScript, a great step forward, thanks!

However, part of this process added the following defaults for `ts-node`:

https://github.com/cypress-io/cypress/blob/bdcfe42f790a6f0e73e8f4ae2133c62df2de349d/packages/server/lib/util/ts-node-options.js#L13

Specifically, `esModuleInterop` is problematic. This is an opinionated transpilation, and cannot be overridden. Typically when working working with a JS / TS mix, you can either use imports such as

```ts
import * as Foo from 'foo';
```

or you can enable `esModuleInterop` and do

```ts
import Foo from 'foo';
```

In my case, I chose the former, to reduce the "magic" that is done by the TypeScript compiler; however, because Cypress enforces the latter, I get lots of errors along the lines of 

```
TypeError: Foo is not a function
```

### Desired behavior:
A test frameworks authors should not enforce an opinion about how I build my application; this `esModuleInterop` value should be possible to override. I tried manually changing it by editing the downloaded Cypress JS code in `~/.cache`, and the tests ran as expected.

### Test code to reproduce
Working on a minimal reproduction, please give me a bit of time :smile: 

### Versions
Cypress: 4.7.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-132) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7575

### User facing changelog

- BREAKING CHANGE: For TypeScript compilation of spec/support files and the plugins file, the `esModuleInterop` option is no longer coerced to `true`. If you need to utilize `esModuleInterop`, set it in your `tsconfig.json`.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3053
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@chrisbreiding Isn't this a duplicate of https://github.com/cypress-io/cypress/pull/7808?

**Comment by chrisbreiding** [comment]
@jennifer-shehane Ah I didn't know that existed. Thanks for pointing it out. I'm doing some refactoring in this PR and also am going to update the preprocessor so the default is changed for spec/support files as well. I think I'll be able to merge @sainthkh's PR into this one.

**Comment by jennifer-shehane** [comment]
@chrisbreiding Nice. I would love links to any docs PRs that are needed or notes you would add for the Migration Guide. The below was previously mentioned for the [Migration guide](https://github.com/cypress-io/cypress-documentation/pull/2905) 

>When a user doesn't have a tsconfig.json file or define esModuleInterop: true, Cypress didn't fail in 4.x, but it might fail after 5.0. Because Cypress now uses the default esModuleInterop setting of TypeScript.
>
>I used 'might', because it wouldn't fail when a user didn't use import syntax.
>https://github.com/cypress-io/cypress/pull/7808#issuecomment-662872699

But providing an example of before / after would be great.

File: packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { expect } from 'chai'
```
Comment (bahmutov) [inline packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts:1]: is this line expected?

Comment (chrisbreiding) [reply packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts:1]: Yes, it's okay in this case to use a local version of chai expect since the test doesn't need anything cypress adds to its global version.

**Comment by chrisbreiding** [comment]
@jennifer-shehane Submitted documentation PR: https://github.com/cypress-io/cypress-documentation/pull/3053

File: packages/server/test/e2e/1_typescript_plugins_spec.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+    })
+  })
+
+  // https://github.com/cypress-io/cypress/issues/7575
+  it('allows esModuleInterop to be overridden', function () {
+    return e2e.exec(this, {
+      project: Fixtures.projectPath('ts-proj-esmoduleinterop-false'),
+    })
+  })
+})
```
Comment (Bkucera) [inline packages/server/test/e2e/1_typescript_plugins_spec.ts:19]: shouldn't the tests around this be:
- one test with `esmoduleinterop: true` (testing that users can override)
- one test with no value set (testing that default is unset, or false)

File: packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts (hunk 1 above)
Comment (Bkucera) [reply packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts:1]:
```suggestion
```
