### PR TITLE
filter out duplicate modifiers from cy.type

### LINKED ISSUE #5622: selectall / unselect regressions in 3.5.0, 3.6
Some regressions were introduced in 3.5 in `type()` behavior when interacting with selection (selectall / unselect).

### Current behavior:

The issue happens in a rich text editor where we are making a text bold by triggering:
- `{selectall}` to select the typed text
- `{ctrl}B` one time to start
- unselecting by triggering {rightarrow}.
- `{ctrl}B` a second time to stop

It seems:
- the content is not unselected by triggering `{rightarrow}`.
- the `{ctrl}` is ignored, only `B` is triggered

### Steps to reproduce: (app code and test code)
 
In a rich text editor supporting this command.

- Type: `Hello{selectall}{ctrl}B{rightarrow}{ctrl}B world!`
- Desired behavior < 3.5: **Hello** World !
- Current behavior >= 3.5: **B** World!

_Work in progress, currently trying to generate a minimum reproduction._

### Sources 

- Upstream issue: https://github.com/opencollective/opencollective-frontend/pull/2943
- Cypress Test: https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/15-tier-page.js#L35
- Sample CI Run: https://circleci.com/gh/opencollective/opencollective-frontend/55483

### Versions

Introduced in Cypress 3.5, still happening in 3.6. Linux / Mac OS.

### PR DESCRIPTION
**Pull request by kuceb**
- this restores behavior in Cypress <3.5.0 where duplicate modifiers in strings passed to `cy.type` are ignored.

- this is an edge case affecting uses of `.type` that mistakenly use duplicate modifiers in one command. This is common when a user does not realize modifiers are active and pressed down during the entire command.

 

- Closes #5622

### User facing changelog
- fix regression introduced in 3.5.0 causing `.type` command to send duplicate modifier keys

### How has the user experience changed?
during cy.type, if a user tries to type multiple of the same modifier:
image

- before (3.5.0+): keydown is sent for each modifier

- after: the modifier is only typed one time, subsequent are ignored (same as <3.5.0)

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/src/cy/keyboard.ts [hunk 1]
```diff
@@ -712,30 +712,14 @@ export class Keyboard {
...
-          return this.simulatedKeyup(getActiveEl(doc), key, options)
-        })
-      }
-
-      options.onAfterType()
-
-      return
-    }
+    // we will only press each modifier once, so only find unique modifiers
+    const modifierKeys = _.uniqBy(_.filter(keyDetailsArr, isModifier), (v) => v.key)
```
Comment (brian-mann) [inline packages/driver/src/cy/keyboard.ts]:
```
const modifierKeys = 
_.chain(keyDetailsArry)
.filter(isModifier)
.uniqBy('key')
.value()
```

**Review by brian-mann — CHANGES_REQUESTED** [review]

**Review by brian-mann — APPROVED** [review]
