### PR TITLE
fix: improve handling of userland injected styles in component testing

### LINKED ISSUE #15879: styles are only loaded for first component test if styled-components is used
### Current behavior

I'm migrating React component tests from Cypress 6.8 to 7.0.1 and I followed the migration instructions. The tests are generally running. However there is a problem with styled-components. The <style></style> element for the styled based css is only present for the first test in a file (even if the it() tests are in different describe() blocks).
If I run just the second test by using it.only() then the styles are present in this test so I'm sure that it's not my testcase itself that's causing this problem.

### Desired behavior

The styles must be loaded in every test.

### Test code to reproduce

see https://github.com/JochenDiekenbrock/dzi-search
Running cypress open-ct will create two screen shots, both should be identical.

### Versions

Cypress 7.0.1
Linux

In a private repo, this problem did not occur with Cypress 6.8.0

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes #15879

### User facing changelog

Injected styles via styled components get cleaned up after each spec. 

### Additional details

We no longer clean up `<head>`. This is more in line with what users expect. If they are using a library like `styled-components`, which injects stylesheets into `<head>`, those will be persisted between tests. We **do** clean up stylesheets injected via the `mount` options.

I also added a `@cypress/mount-utils` package. Now the style injecting/clean up is consistent between both Vue and React. Furthermore, now Vue and React both have the same mounting options for `styles`. This was not the case previously - due to copy-pasting, they were mostly the same, but not quite. This package will be useful moving forward for other adapters, like Angular, [which is discussed here](https://github.com/cypress-io/cypress/issues/15903).

NOTE: These changes will need to be ported to the Vue 3 branch, too. I guess we just do that as soon as this is merged into master and the `@cypress/mount-utils` package is published on npm.

### How has the user experience changed?

Userland styles are not nuked between tests. Subsequent tests are able to retain and use the injected styles.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: npm/mount-utils/src/index.ts [hunk 1]
```diff
@@ -1,4 +1,66 @@
...
+  /**
+   * Creates <link href="..." /> element for each stylesheet
+   * @alias stylesheet
+   */
+  stylesheets: string | string[]
+  /**
+   * Creates <link href="..." /> element for each stylesheet
+   * @alias stylesheets
+   */
+  stylesheet: string | string[]
```
Comment (agg23) [inline npm/mount-utils/src/index.ts:16]: Why do all of these have aliases? What is the point?

**Review by agg23 — DISMISSED** [review]

File: npm/mount-utils/src/index.ts (hunk 1 above)
Comment (JessicaSachs) [reply npm/mount-utils/src/index.ts:16]: Legacy API design. The styles api needs to be deduped and refined.

Comment (lmiller1990) [reply npm/mount-utils/src/index.ts:16]: Can't decide on an API? Why not have them all!

**Review by agg23 — APPROVED** [review]
