### PR TITLE
fix: suppress EventEmitter warnings + other Node warnings in prod

### LINKED ISSUE #1305: Do not display MaxListenersExceededWarning "Warning: Possible EventEmitter memory leak detected." warning message during cypress run
### Current behavior:

After creating 8 spec files warning about EventEmitter memory leak appears (even if specs contain empty `describe()`). After ignoring this warning and continue creating more specs, last added specs don't run, and appears `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

### Desired behavior:

Number of spec files do not affect test run

### How to reproduce:

- Add cypress to project
- At `cypress/integration` folder create 8 spec files with any content inside them it could be only `describe('', () => {});`
- Run created tests using command: cypress run

### Additional Info (images, stack traces, etc)

After adding 8th spec next warning appeared:
memoryleakmessage

Even if there are no tests inside them
zerotestwithmemoryleak

After ignoring this warning and creating more specs got this error:
fatalerror

- Operating System: Linux, MacOS
- Cypress Version: both 1.4.2 and 1.4.1
- Node version: 8.8.1

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #1305

### User facing changelog

- Fixed an issue where "Possible EventEmitter memory leak detected" warnings could appear when running multiple specs.

### Additional details

- increased plugin child ipc listener limit to infinity so the unneeded warning ceases
- fixed an actual event listener leak in electron downloads code
- updated process.emitWarning patching to still log warnings in development, but in production, only log warnings to debug log

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/browsers/electron.js [hunk 1]
```diff
@@ -307,9 +307,16 @@ module.exports = {
...
       })
-    })
+    }
+
+    const { session } = win.webContents
+
+    session.on('will-download', onWillDownload)
+
+    // avoid adding redundant `will-download` handlers if session is reused for next spec
+    win.on('closed', () => session.removeListener('will-download', onWillDownload))
```
Comment (flotwig) [inline packages/server/lib/browsers/electron.js:317]: apparently the session is reused between webContents, because this eventually emits the same max listeners warning after 12 or so specfiles have launched Electron

**Review by chrisbreiding — APPROVED** [review]
Very nice! This has been a nuisance for too long now. Good catch on the download behavior leak too.
