### PR TITLE
fix: handle download from element missing download attribute

### LINKED ISSUE #14857: Clicking anchor link to download file causes page load timeout
i was update Cypress 6.4.0
but i cannot click button download
error_download_file

file source:
error_download_file_2

source:
[cypress_download.zip](https://github.com/cypress-io/cypress/files/5908040/cypress_download.zip)

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #14857

1. Update to handle downloads from links from elements that do not specify `download` attribute. Without the `download` attribute, a `beforeUnload` event was triggered, causing Cypress to become "unstable" and wait for a page-load event. The download behavior does not fire a load event which caused the hang & timeout.
- I did sync with @ryanthemanuel who indicate no protocol changes would be necessary for proxy corrollation.

2. Fix an issue observed while testing were downloading content not found results in a forever pending download event log because we did not fail the event to reflect the canceled or failed download status.

### Additional details
These fixes apply to Chrome/Electron/Firefox. This does not fix issues observed in experimental webkit. Downloads in Safari results in a beforeUnload page event, and then Safari navigates & shows the download in the browser but does not trigger navigation events. Further investigation is needed to account for this divergent behavior but time-boxed this due to webkit being experimental.

Firefox: Firefox is an odd-ball. If the download is invalid - our current FF configuration will follow the link and launch a new window (its also configurable to same tab or new tab in the same window). This results in a new Firefox window being opened on the machine with focus, however Cypress continues to executes tests in the background. Quick testing locally shows this did not seem to impact back-to-back spec executions in run mode. 🤷🏻‍♀️ 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/electron.ts [hunk 1]
```diff
@@ -347,8 +347,14 @@ export = {
...
-      downloadItem.once('done', () => {
-        automation.push('complete:download', {
+      downloadItem.once('done', (_event, state) => {
+        if (state === 'completed') {
+          automation.push('complete:download', {
+            id: downloadItem.getETag(),
+          })
+        }
+
+        automation.push('canceled:download', {
```
Comment (chrisbreiding) [inline packages/server/lib/browsers/electron.ts]: If state is completed, should it push both 'complete:download' _and_ 'canceled:download'?

Comment (emilyrohrbough) [reply packages/server/lib/browsers/electron.ts]: I dont think so - the browser reports these separately. I pulled the canceled state from CDP's states: https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadProgress

Thoughts on why pushing both?

Comment (chrisbreiding) [reply packages/server/lib/browsers/electron.ts]: Isn't that what it's currently doing? It doesn't return early, so it's going to push twice if state is completed.

Comment (emilyrohrbough) [reply packages/server/lib/browsers/electron.ts]: Oh I see what you mean.  yes it should return fast

File: packages/server/lib/browsers/electron.ts [hunk 2]
```diff
@@ -347,8 +347,14 @@ export = {
         url: downloadItem.getURL(),
       })
 
-      downloadItem.once('done', () => {
-        automation.push('complete:download', {
+      downloadItem.once('done', (_event, state) => {
+        if (state === 'completed') {
+          automation.push('complete:download', {
```
Comment (emilyrohrbough) [inline packages/server/lib/browsers/electron.ts]:
```suggestion
          return automation.push('complete:download', {
```

**Review by chrisbreiding — APPROVED** [review]

**Review by cacieprins — APPROVED** [review]
