### PR TITLE
fix: Capture env vars from AWS Code Build

### LINKED ISSUE #8101: Detect and capture env vars from AWS CodeBuild including ciBuildId
The documentation lists CodeBuild under "CI environment variables" in this list here:

https://github.com/cypress-io/cypress-documentation/blame/develop/source/guides/guides/parallelization.md#L246

Which was recently changed in the last month. However, when running cypress with the `--parallel` flag in this environment cypress (`4.11`) puts out this error:

```
962 | You passed the --group or --parallel flag but we could not automatically determine or generate a ciBuildId.
963 |  
964 | The --group flag you passed was: admin
965 | The --parallel flag you passed was: true
966 |  
967 | In order to use either of these features a ciBuildId must be determined.
968 |  
969 | The ciBuildId is automatically detected if you are running Cypress in any of the these CI providers:
970 |  
971 | - appveyor
972 | - azure
973 | - bamboo
974 | - bitbucket
975 | - buildkite
976 | - circle
977 | - codeshipBasic
978 | - codeshipPro
979 | - concourse
980 | - drone
981 | - githubActions
982 | - gitlab
983 | - goCD
984 | - googleCloud
985 | - jenkins
986 | - semaphore
987 | - shippable
988 | - teamfoundation
989 | - travis
990 | - netlify
991 |  
992 | Because the ciBuildId could not be auto-detected you must pass the --ci-build-id flag manually.
```

And in the cypress code it does not list `CodeBuild`:

https://github.com/cypress-io/cypress/blob/4054e72c3bc1ecfb5308156b5c782077d96358dc/packages/server/lib/util/ci_provider.js#L82-L105

I am confused why this documentation has been changed like this when it does not appear to be a supported CI provider?

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-172) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Close #8101 

### User Changelog

- We now collect environment variables for AWS CodeBuild when recording to the Dashboard.

### Additional Details

AWS CodeBuild env vars: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3046

### CODE REVIEW

File: packages/server/lib/util/ci_provider.js [hunk 1]
```diff
@@ -82,6 +88,7 @@ const isWercker = () => {
 const CI_PROVIDERS = {
   'appveyor': 'APPVEYOR',
   'azure': isAzureCi,
+  'awsCodeBuild': isAWSCodeBuild,
```
Comment (bahmutov) [inline packages/server/lib/util/ci_provider.js:91]:
```suggestion
  'awsCodeBuild': 'CODEBUILD_BUILD_ID',
```
we can simply check for this environment variable, why is `isAWSCodeBuild` necessary?

**Review by bahmutov — APPROVED** [review]
I will approve this PR, but see my note about `isAWSCodeBuild` function - it is unnecessary, we should just check a single variable.

File: packages/server/lib/util/ci_provider.js (hunk 1 above)
Comment (jennifer-shehane) [reply packages/server/lib/util/ci_provider.js:91]: Just figure it covers more env vars if they ever change the `CODEBUILD_BUILD_ID` var
