### PR TITLE
reporter: Cache aliasesWithDuplicates to prevent unnecessary re-renders, fixes UI slowdown

### LINKED ISSUE #4411: Cypress tests slow down or fail, UI is unresponsive in 3.3.1
### Current behavior:
I noticed the some of our API, mainly XHR requests were continuously getting looped indefinitely when i upgraded Cypress from 3.2.0 to 3.3.0. So we rolled it back.
Now we hit some other bugs, for which we wanted to upgrade to Cypress 3.3.1, once again i am getting a similar issue.

1. For some of the tests some XHR requests are loading indefinitely.
2. The Timer is not incrementing
3. The Test Runner is not responding
 
cypress_1
cypress_2
cypress_3

```
------------ Configuration -------
{
animationDistanceThreshold: 5,
baseUrl: null,
blacklistHosts: null,
chromeWebSecurity: true,
defaultCommandTimeout: 20000,
env: {
CLIENT: 'demoaccount',
failOnSnapshotDiff: false},
execTimeout: 60000,
fileServerFolder: '',
fixturesFolder: 'cypress/fixtures',
hosts: null,
integrationFolder: 'cypress/integration',
modifyObstructiveCode: true,
numTestsKeptInMemory: 1,
pageLoadTimeout: 60000,
pluginsFile: 'cypress/plugins',
port: null,
reporter: 'spec',
reporterOptions: null,
requestTimeout: 5000,
responseTimeout: 30000,
screenshotsFolder: 'cypress/screenshots',
supportFile: 'cypress/support',
taskTimeout: 60000,
testFiles: '**/*.{spec.js,feature}',
trashAssetsBeforeRuns: true,
userAgent: null,
video: true,
videoCompression: 32,
videoUploadOnPasses: true,
videosFolder: 'cypress/videos',
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true}
-----------
```

Scenario failing- `Validating the time/date picker yields a correct date in the calendar while scheduling email message (we are using cucumber library)`

### Desired behavior:

Things are fine in 3.2.0, except some known issues like forwarding of socket failures related error in HTTP api level, which causes some parse error (Internal Error 500) in cypress.

### Steps to reproduce: (app code and test code)

I am sharing some snippet of the login code, which we use to login. 

```js
Cypress.Commands.add(
	'login',
	{
		prevSubject: 'true'
	},
	(client, user) => {
		cy.logout();
		return cy.visit(`${BASE_URL}`).then(() => {
			return cy.getCookie('csrftoken').then(({ value }) => {
				return cy
					.request({
						url: `${client.url}/accounts/login`,
						form: true,
						method: 'POST',
						body: {
							username: client.users[user].email,
							password: client.users[user].password,
							csrfmiddlewaretoken: value
						}
					})
					.then(() => client);
			});
		});
	}
);
```

### Versions
cypress - 3.3.1
electron - 61
OS - Mac OS Mojave 10.14.5

### Attachments
[cy_3.3.0_debug.log](https://github.com/cypress-io/cypress/files/3276250/cy_3.3.0_debug.log)
[cy_3.3.1_debug.log](https://github.com/cypress-io/cypress/files/3276251/cy_3.3.1_debug.log)

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #4411

Brings total Command re-renders down to 407 from 80,000+

### CODE REVIEW

File: packages/reporter/src/hooks/hook-model.js [hunk 1]
```diff
@@ -32,7 +34,16 @@ export default class Hook {
       return aliases.indexOf(alias) === i && aliases.lastIndexOf(alias) !== i
     })
 
-    return consecutiveDuplicateAliases.concat(nonConsecutiveDuplicateAliases)
+    const aliasesWithDuplicates = consecutiveDuplicateAliases.concat(nonConsecutiveDuplicateAliases)
+
+    // do a deep compare here to see if we can use the cached aliases, which will allow mobx's
+    // @computed identity comparison to pass, preventing unnecessary re-renders
+    // https://github.com/cypress-io/cypress/issues/4411
+    if (!_.isEqual(aliasesWithDuplicates, this._aliasesWithDuplicatesCache)) {
```
Comment (flotwig) [inline packages/reporter/src/hooks/hook-model.js]: I wanted to use `comparer.structural` here (https://mobx.js.org/refguide/computed-decorator.html#builtin-comparers) but it doesn't seem to accomplish the same thing.

File: packages/reporter/src/hooks/hook-model.spec.js [hunk 2]
```diff
@@ -109,23 +109,42 @@ describe('Hook model', () => {
...
+      addCommand('bar')
+      addCommand('foo')
+      addCommand('baz', true)
 
       expect(hook.aliasesWithDuplicates).to.include('foo')
       expect(hook.aliasesWithDuplicates).to.include('baz')
       expect(hook.aliasesWithDuplicates).to.not.include('bar')
     })
+
+    it('returns the same array instance if it has not changed', () => {
```
Comment (brian-mann) [inline packages/reporter/src/hooks/hook-model.spec.js]: can you leave a comment pointing to the github issue that this fixes? it would help correlate the test - as the meaning as to "why" it needs to return the same array is completely lost without that context...

`https://github.com/cypress-io/cypress/issues/4411`

**Comment by chrisbreiding** [comment]
Nice work!
