### PR TITLE
chore(wait): add types and fix issues flagged by types

### LINKED ISSUE #32331: Add types to waiting
### What would you like?

[`packages/driver/src/cy/commands/waiting.ts`](https://github.com/cypress-io/cypress/blob/a8e7fa1b877faf64844bdee9dbcaf2be311decae/packages/driver/src/cy/commands/waiting.ts) is written in TypeScript but has minimal types across nearly 400 lines of code. Add explicit types throughout.

### Why is this needed?

To improve maintainability, and to catch issues at compile time.

### Other

_No response_

### PR DESCRIPTION
**Pull request by adamalston**
- Closes https://github.com/cypress-io/cypress/issues/32331

### Additional details

I’m not certain all of the types are correct, but I’m confident most are.

I’ve left some `TODO`s with questions that hopefully someone can answer.

### Steps to test

Check for type errors in your IDE.

### How has the user experience changed?

N/A

### PR Tasks

- [~] Have tests been added/updated?
- [~] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [~] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cy/commands/waiting.ts [hunk 1]
```diff
@@ -98,15 +113,16 @@ export default (Commands, Cypress, cy, state) => {
...
 
-      const args: [any, any, any, any, any] = [alias, type, index, num, options]
-
       return cy.retry(() => {
-        return checkForXhr.apply(window, args)
-      }, options)
+        return checkForXhr.apply(window, [alias, type, index, num, options])
+      },
+      // TODO: What should `_log`'s type be?
+      // @ts-expect-error - Incompatible types.
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/waiting.ts:120]: I think a lot of this has to do with a mismatch between the internal log and external log type. Could be we just update the declaration types but it isn't likely worth the effort since it isn't consumer facing

**Review by AtofStryker — APPROVED** [review]
