### PR TITLE
fix(config): allow "additionalIgnorePattern" to be an array of strings

### LINKED ISSUE #22551: Cypress component test autoconfig issue with additionalIgnorePattern
### Current behavior

Cypress is already configured to work as e2e testing tool and my cypress.config.ts override the default specPattern to include both cucumber and non cucumber specs:
```typescript
e2e: {
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config)
      on(
          'file:preprocessor',
          createBundler({
            plugins: [nodePolyfills(), createEsbuildPlugin(config)],
          })
      )
    },
    specPattern: ['tests/e2e/**/*.{feature,features}', 'tests/e2e/**/*.cy.{js,jsx,ts,tsx}'],
    viewportHeight: 1080,
    viewportWidth: 1920,
  },
```
Problem is that apparently, even though specPattern correctly recognize and accept a list of string, when you try to have cypress autoconfigure the component testing, this is what you get:
image

Stack trace:
```
Error: An invalid configuration value was set.

Expected additionalIgnorePattern to be a string.

Instead the value was: 

[
  "tests/e2e/**/*.{feature,features}",
  "tests/e2e/**/*.cy.{js,jsx,ts,tsx}"
]
    at /home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/config.js:151:23
    at /home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/config/src/browser.js:114:24
    at /home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/lodash/lodash.js:3032:24)
    at /home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/lodash/lodash.js:9410:14)
    at Object.validate (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/config/src/browser.js:108:29)
    at mergeDefaults (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/config.js:146:17)
    at Object.setupFullConfigWithDefaults (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/server/lib/config.js:78:12)
    at ProjectConfigManager.buildBaseFullConfig (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:279:65)
    at ProjectConfigManager.getFullInitialConfig (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:322:45)
    at ProjectConfigManager.setupNodeEvents (/home/rsaleri/.cache/Cypress/10.2.0/Cypress/resources/app/packages/data-context/src/data/ProjectConfigManager.js:119:28)
```

### Desired behavior

additionalIgnorePattern should work like specPattern, since apparently it's what's using to know which paths discard.

### Test code to reproduce

Trying to configure the component testing with a vue2 project and this cypress.config.ts trigger the issue

```typescript
import {defineConfig} from 'cypress'
const createEsbuildPlugin = require('@badeball/cypress-cucumber-preprocessor/esbuild').createEsbuildPlugin
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor')
const nodePolyfills = require('@esbuild-plugins/node-modules-polyfill').NodeModulesPolyfillPlugin
const addCucumberPreprocessorPlugin = require('@badeball/cypress-cucumber-preprocessor').addCucumberPreprocessorPlugin
export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config) // to allow json to be produced
      // To use esBuild for the bundler when preprocessing
      on(
          'file:preprocessor',
          createBundler({
            plugins: [nodePolyfills(), createEsbuildPlugin(config)],
          })
      )
    },
    specPattern: ['tests/e2e/**/*.{feature,features}', 'tests/e2e/**/*.cy.{js,jsx,ts,tsx}'],
    viewportHeight: 1080,
    viewportWidth: 1920,
  },
})
```

### Cypress Version

10.2.0, 10.1.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by Kocal**
- Closes #22551

### User facing changelog

n/a

### Additional details

If `additionalIgnorePattern` is undefined, then we won't be able to run E2E tests due to another validation fail:
image

That's why we changed its default value to `[]`.

### Steps to test

Follow reproduction from #22551.

Also, is there a way to write a test for `additionalIgnorePattern` option in order to prevent any regression?

### How has the user experience changed?

The user can now run Component tests even if the user uses an array for `e2e.specPattern` option: 
image

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/config/src/options.ts [hunk 1]
```diff
@@ -435,7 +435,7 @@ const runtimeOptions: Array<RuntimeConfigOption> = [
     // we may not be able to get the value to ignore.
     name: 'additionalIgnorePattern',
     defaultValue: (options: Record<string, any> = {}) => options.testingType === 'component' ? defaultSpecPattern.e2e : undefined,
-    validation: validate.isString,
+    validation: validate.isNullOrStringOrArrayOfStrings,
```
Comment (lmiller1990) [inline packages/config/src/options.ts:438]: Not sure what is the most common pattern in this file, but instead of allowing `undefined`, we could simply default to `[]`.

```js
    defaultValue: (options: Record<string, any> = {}) => options.testingType === 'component' ? defaultSpecPattern.e2e ?? [] : [],
``

Comment (Kocal) [reply packages/config/src/options.ts]: That looks so much better, thanks!

**Comment by Kocal** [comment]
I don't think CI failures are related... are they?

**Comment by emilyrohrbough** [comment]
@Kocal Thanks for the fix! While you are updating this configuration to be correct, can you update the types in these places as well?
- https://github.com/cypress-io/cypress/blob/develop/packages/types/src/config.ts#L24
- https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/project-base.ts#L40

Also, it looks like the CI check are currently green ✅ .

**Review by emilyrohrbough — APPROVED** [review]

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Blocked by: https://github.com/cypress-io/cypress/pull/22861

**Comment by Kocal** [comment]
Thanks for merging!
