### PR TITLE
fix: correctly wait for static delayMs w/ cy.intercept

### LINKED ISSUE #14446: Delay for intercepted HTTP routes only works for the first call on that route
### Current behavior
When using `.intercept()` for a HTTP route and stubbing it with a static response with a defined delay, that delay is only used on the first ever occurrence of this call.

### Desired behavior
Every call of this route is delayed

### Test code to reproduce
Given the following HTML:
```html
<!DOCTYPE html>
<head>
    <title>msDelay Test</title>
</head>
<body>
<button id="click-me">Click me</button>
<p id="difference">0</p>
<script type="text/javascript">
    const difference = document.getElementById('difference');
    document.getElementById('click-me').addEventListener('click', () => {
        const before = new Date().getTime();
        fetch('/api/something').then(() => {
            const after = new Date().getTime();
            const diff = after - before;
            difference.innerHTML = `${diff / 1000}`;
        });
    });
</script>
</body>
```

the following Cypress test should work:
```js
describe('Delaying Responses', () => {
  it('should delay every response', () => {
    cy.intercept('GET', '/api/something', { body: {}, delayMs: 5000 }).as('apiRoute');
    cy.visit('msDelay.html');

    cy.get('#click-me').click();
    cy.wait('@apiRoute');
    cy.get('#difference').invoke('text').then(text => expect(parseFloat(text)).to.be.closeTo(5, 0.5));

    cy.get('#click-me').click();
    cy.wait('@apiRoute');
    cy.get('#difference').invoke('text').then(text => expect(parseFloat(text)).to.be.closeTo(5, 0.5));
  });
});
```

However the first assertion goes through just fine and the second one fails with `expected 0.009 to be close to 5 +/- 0.5`

### Versions

6.2.1

### Additional info
From what I can see, this is because in https://github.com/cypress-io/cypress/blob/f43f1c1f26290fc8387697c8122f0f50b6c7cb55/packages/driver/src/cy/net-stubbing/events/response-received.ts the delay is defined as follows and probably is only called on the first occurrence:
```
continueFrame.continueResponseAt = Date.now() + delayMs
```

### LINKED ISSUE #14511: static interception delayMs option measures time from "cy.intercept" command, not from the request timestamp
Cypress v6.2.1 using `cy.intercept` to send a static response. My goal is to clearly see the loading indicator in the UI, thus I want to slow down the server response.

## Situation

Without intercept, the request fires 3 seconds after the page loads

```js
it('use positive then negative assertion', () => {
  cy.visit('/?delay=3000')
  // first, make sure the loading indicator shows up (positive assertion)
  cy.get('.loading').should('be.visible')
  // then assert it goes away (negative assertion)
  cy.get('.loading').should('not.be.visible')
})
```

Notice how quickly the loading message appears and disappears without network control. In fact it passes on the first run, and fails to "catch" the quickly appearing loading element on the second re-run.

https://user-images.githubusercontent.com/2212006/104367851-5bd91a80-54e9-11eb-985e-3512a4f7a54b.mp4

Of course, this is a flakey test and we could use test retries to solve it. But let's make the test better using network control.

## Attempt

So I want to slow down the network request to `GET /todos` to always have the loading indicator stay visible for a period of time.

```js
it('slows down the network response (does not work)', () => {
  cy.intercept('/todos', {
    body: [],
    delayMs: 2000
  })
  cy.visit('/?delay=3000')
  // first, make sure the loading indicator shows up (positive assertion)
  cy.get('.loading').should('be.visible')
  // then assert it goes away (negative assertion)
  cy.get('.loading').should('not.be.visible')
})
```

Hmm, it looks wrong! It looks like the `delayMs` wasn't even applied

https://user-images.githubusercontent.com/2212006/104368454-149f5980-54ea-11eb-860a-44181c1246b5.mp4

## Code

Looking at the code in https://github.com/cypress-io/cypress/blob/f43f1c1f26290fc8387697c8122f0f50b6c7cb55/packages/driver/src/cy/net-stubbing/static-response-utils.ts#L106

I see that we compute the response time using the time when `cy.intercept()` command runs

```js
if (staticResponse.delayMs) {
  backendStaticResponse.continueResponseAt = Date.now() + staticResponse.delayMs
}
```

Ok, let's see. If our application makes the request after 3 seconds, let's set the response to be sent after 5 seconds

https://user-images.githubusercontent.com/2212006/104368736-795ab400-54ea-11eb-923c-ecd0ea60d6fc.mp4

yeah, this works, but is so counterintuitive

## Workaround

Use programmatic reply and not a static response

```js
it('slows down the network response (programmatic)', () => {
  cy.intercept('/todos', req => {
    req.reply({
      body: [],
      delayMs: 2000
    })
  })
  cy.visit('/?delay=3000')
  // first, make sure the loading indicator shows up (positive assertion)
  cy.get('.loading').should('be.visible')
  // then assert it goes away (negative assertion)
  cy.get('.loading').should('not.be.visible')
})
```

BUT this solution also has a bug noted in #14446 - it uses the first time `req.reply` runs to "remember" the response delay :)

## Desired output

when using static intercept, start counting the delay from the moment the network request starts

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #14446 (programmatic delay)
- Closes #14511 (static delay argument)

### User facing changelog

Fixed an issue where using `delayMs` with `cy.intercept` did not wait for the expected amount of time when used in a `StaticResponse`.

### Additional details

- continueResponseAt was an attempt to be more time-accurate, but let's KISS, this works well enough. it will never be ms-accurate anyways

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -1041,6 +1041,29 @@ describe('network stubbing', { retries: 2 }, function () {
...
+          expect(responseText).to.eq('foo')
+        })
+      }
+
+      cy.intercept('/timeout', {
+        statusCode: 200,
+        body: 'foo',
+        delayMs,
+      }).as('get')
+      .then(() => testDelay()).wait('@get')
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1062]: could be
```js
.then(testDelay).wait('@get')
```

**Review by bahmutov — APPROVED** [review]
works, verified solves both issues in https://github.com/cypress-io/testing-workshop-cypress/pull/242
