### PR TITLE
fix: absolute positioning element blackouts in cy.screenshot

### LINKED ISSUE #22173: Blackout area is offset from where it should be when upgrading to 9.7.0 from 9.5.4
### Current behavior

Blackout is not blacking out the specified area in 9.7.0. It seems to be trying, but the blacked out area is offset from where it should be.

This is my blackout area in Cypress 9.5.4:
blackout_9 5 4

I am attempting to upgrade to 9.7.0, and the wrong area is being blacked out. The tests haven't changed. 
blackout_9 7 0

### Desired behavior

Blackout the specified area. 

### Test code to reproduce
         cy.findByAutomationID(`drive`)
            .should(`be.visible`)
            .matchImageSnapshot({ blackout: [`[data-automation-id="drive-item-modified-date"]`] })
### Cypress Version

9.7.0

### Other

I also tried one or two Cypress 9.6 versions and saw the same behavior there. I am unable to upgrade past 9.5.4 since it breaks my visual tests that use blackout. It seems like blackout is still functioning, it's just blacking out the wrong area on the page. These tests have been working properly with all versions of Cypress since July, 2021.
The tests work great in Cypress 9.5.4.

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #22173

### User facing changelog
Fixes a regression in 9.6 where absolute elements that are blacked out with `cy.screenshot` are positioned off the container element and not the body.

### Additional details
This PR attempts to fix a regression when screenshots were refactored for `cy.origin` in #20949 where element dimensions are calculated from the screenshotted element. This works in most cases, but causes some trouble with absolute elements. To fix this, since we no longer have access to the `AutIframe` class, is to reference the body to calculate dimensions for elements. 

### Steps to test
See changes to the `screenshot_viewport_capture_spec.js`

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/driver/src/cy/commands/screenshot.ts [hunk 1]
```diff
@@ -417,7 +417,11 @@ const takeScreenshot = (Cypress, state, screenshotConfig, options: TakeScreensho
     ? subject
     : $dom.wrap(state('document').documentElement)
 
-  return before($el)
+  // get the current body of the AUT to accurately calculate screenshot blackouts
+  // as well as properly enable/disable CSS animations while screenshotting is happening
+  const $body = Cypress.$('body')
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/screenshot.ts:422]: is there possibly a cleaner way to reference the body here?

File: system-tests/projects/e2e/cypress/e2e/screenshot_viewport_capture.cy.js [hunk 2]
```diff
@@ -26,3 +26,61 @@ it('takes consistent viewport captures', () => {
...
 })
+
+it('properly blacks out absolute elements within a relative container', () => {
+  cy.visit('cypress/fixtures/screenshot-blackout.html')
+  .get('.centered-container')
+  .screenshot({
+    blackout: ['.blue'],
+    onBeforeScreenshot () {
+      const blackedOutElementCoordinates = Cypress.$(
+        '#__cypress-animation-disabler+div.__cypress-blackout',
```
Comment (AtofStryker) [inline system-tests/projects/e2e/cypress/e2e/screenshot_viewport_capture.cy.js:37]: I'm open to better selectors here. This seems to be a bit of a coincidence that our blacked out elements are adjacent to the animation disabler element. Also the test assertions below aren't great, but at least should guarantee that the blacked out element is very close to the thing it's trying to black out.

**Review by emilyrohrbough — APPROVED** [review]

File: packages/driver/src/cy/commands/screenshot.ts [hunk 3]
```diff
@@ -337,7 +337,7 @@ const takeScreenshot = (Cypress, state, screenshotConfig, options: TakeScreensho
     }
   }
 
-  const before = ($el) => {
+  const before = ($body, $container) => {
```
Comment (lmiller1990) [inline packages/driver/src/cy/commands/screenshot.ts:340]: Can we incrementally ad types as we go? `HTMLBodyElement` and `HTMLElement`, in this case.

File: packages/driver/src/cy/commands/screenshot.ts (hunk 1 above)
Comment (lmiller1990) [reply packages/driver/src/cy/commands/screenshot.ts:422]: I think this is fine - since the `Cypress` instance is injected to the AUT, and you can only have one instance of `HTMLBodyElement` (or the browser will raise an error) this seems safe to me.

**Review by lmiller1990 — APPROVED** [review]
Nit around types - probably a quick win, but going to approve.

**Review by chrisbreiding — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

File: packages/driver/src/cy/commands/screenshot.ts (hunk 3 above)
Comment (AtofStryker) [reply packages/driver/src/cy/commands/screenshot.ts:340]: Going to create a follow up PR to add types to the screenshot files since it's quite a bit of changes
