### PR TITLE
fix: vite startDevServer needs to return close()

### LINKED ISSUE #16739: Vite-dev-server PluginConfig typescript errors
The new component testing works great so far, but I did get some typescript errors with my plugins/index.ts:

### Current behavior

```
Property 'close' is missing in type 'import("[...]/@cypress/vite-dev-server/dist/index").ResolvedDevServerConfig' but required in type 'Cypress.ResolvedDevServerConfig'
```

and

```
Type 'DevServerOptions' is not assignable to type 'Options'.
  Types of property 'config' are incompatible.
    Type 'ResolvedConfigOptions & RuntimeConfigOptions' is not assignable to type 'Record<string, string>'.
      Index signature is missing in type 'ResolvedConfigOptions & RuntimeConfigOptions'.
startServer.d.ts(13, 5): The expected type comes from property 'options' which is declared here on type 'StartDevServer'
```

### Desired behavior

No typescript errors

### Test code to reproduce

```js
// plugins/index.ts
import { startDevServer } from '@cypress/vite-dev-server'
const plugin: Cypress.PluginConfig = (on, config) => {
  if (config.testingType === 'component') {
    const viteConfig = {}
    on('dev-server:start', async (options) => {
      const server = await startDevServer({ options, viteConfig })
      return server as Cypress.ResolvedDevServerConfig
    })
  }
  return config
}
module.exports = plugin
```

### Versions

```
"@cypress/vite-dev-server": "^1.2.7",
"cypress": "^7.4.0",

### PR DESCRIPTION
**Pull request by elevatebart**
- Closes #16739

### User facing changelog
The types output by the `@cypress/vite-dev-server` need to have a `close` function to match the demanded type in the event `dev-server:start`.

### CODE REVIEW

File: npm/vite-dev-server/src/index.ts [hunk 1]
```diff
@@ -18,5 +19,5 @@ export async function startDevServer (startDevServerArgs: StartDevServer): Promi
 
   debug('Component testing vite server started on port', port)
 
-  return { port, server: app.httpServer }
+  return { port, close: () => app.httpServer.close() }
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/index.ts:22]:
```suggestion
  return { port, close: app.httpServer.close }
```

Perhaps?

**Review by lmiller1990 — DISMISSED** [review]
Approved but left a suggestion

**Review by lmiller1990 — APPROVED** [review]
LGTM
