### PR TITLE
Fix firing 'watched:file:changed' twice on change

### LINKED ISSUE #968: Browserify plugin is firing 'watched:file:changed' twice on change
This is a bug introduced likely somewhere in the plugins refactor.

Whenever you change a spec file I'm getting two 'watched:file:changed' events.

When this happens this causes the Runner to reinstantiate Cypress and to stop the previous one. At this point `this.runner` and `this.cy` are undefined, which is why it fails. We could guard against that there, but there would be hiding the underlying problem.

screen shot 2017-11-27 at 7 52 43 pm

and

screen shot 2017-11-27 at 7 51 45 pm

### PR DESCRIPTION
**Pull request by chrisbreiding**
Fixes #968

### CODE REVIEW

File: packages/server/lib/socket.coffee [hunk 1]
```diff
@@ -67,28 +70,23 @@ class Socket
     ## integration/foo_spec.js becomes cypress/my-integration-folder/foo_spec.js
     log("watch test file #{originalFilePath}")
     filePath = path.join(config.integrationFolder, originalFilePath.replace("integration/", ""))
-    filePath = filePath.replace("#{config.projectRoot}/", "")
+    filePath = path.relative(config.projectRoot, filePath)
```
Comment (bahmutov) [inline packages/server/lib/socket.coffee]: I wonder if this is going to fix watching specs on Windows OS

Comment (brian-mann) [reply packages/server/lib/socket.coffee]: Could be. That would be a freebie win.

Comment (chrisbreiding) [reply packages/server/lib/socket.coffee]: There was also a bug in browserify-preprocessor itself that affected watching regardless of OS (which I'm surprised wasn't reported outside of Windows). That's fixed as well with this PR (bump browserify-preprocessor to 1.0.1), so fingers crossed it takes care of the Windows issue.
