### PR TITLE
fix: Browser will freeze when sync request is intercepted

### LINKED ISSUE #32874: Browser will freeze when sync request is intercepted
Reopening of https://github.com/cypress-io/cypress/issues/29566 @jennifer-shehane 
- originally reported by @kalousmichal

---

### Current behavior

The whole browser will freeze if a tested page uses a synchronous HTTP request and Cypress test intercepts this request.

Steps are:

1. Set test with `cy.intercept('https://httpbin.org/post', (req) => {})`
2. Visit the page and trigger the sync request
3. Browser will freeze

Removing `cy.intercept` from the test will fix the issue.

### Desired behavior

The browser should not freeze.

### Test code to reproduce

Cypress project with a simple reproducible example:

```js
describe('empty spec', () => {
  it('passes', () => {
    cy.intercept('https://httpbin.org/post', (req) => {})
    cy.visit('cypress/fixtures/syncRequest.html')
    cy.log('Browser will freeze in 5s after sending sync request')
    cy.wait(5000);
    cy.get('#sync-request-button').click();
  })
})
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>Sync Request Repro</title>
</head>
<body>
<div>
    <button id="sync-request-button">Test Sync Request</button>
    <div id="counter"></div>
</div>
<script>
    const button = document.querySelector('#sync-request-button');
    button.addEventListener('click', () => {
        let xhr = new window.XMLHttpRequest();
        xhr.open('POST', 'https://httpbin.org/post', false);
        xhr.onload = () => console.log(xhr.status);
        xhr.send();
    });
    let count = 0;
    setInterval(() => {
        document.querySelector('#counter').innerHTML = `${count}`
        count++
    }, 100);
</script>
</body>
</html>
```

### Cypress Version

15.5.0

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by alexsch01**
- Closes https://github.com/cypress-io/cypress/issues/32874

This issue happens when a synchronous request is intercepted and the `routeHandler` argument to cy.intercept is given

---

The second part of this PR ([prevent cross origin cookies from breaking sync requests](https://github.com/cypress-io/cypress/pull/32925/commits/7b4f2e75ce1099585c806e0ae906f1bfeab18931))
- prevents the browser from freezing when a sync request is made through the cross origin runner

---

### Additional details

---

> [!NOTE]
> Avoids freezing by not intercepting synchronous XHRs with route handlers and adds warnings for sync XHR interception/cookie caveats across proxy and runner.
> 
> - **Network/Proxy**:
>   - Skip `cy.intercept()` for synchronous XHRs with a `routeHandler` (`intercepted-request.ts`); emit warning `SYNCHRONOUS_XHR_REQUEST_NOT_INTERCEPTED`.
>   - Detect sync XHR via `x-cypress-is-sync-request` header; plumb through request pipeline (`request-middleware.ts`, `types.ts`).
>   - Warn when cross-origin cookies may not be applied/set for sync XHRs in request/response middleware.
> - **Runner Injection**:
>   - Patch XHR in both primary and cross-origin injections to set `x-cypress-is-sync-request` and avoid awaiting credentials for sync requests; reorganize patches under `patches/cross-origin/*`.
> - **Errors/Schema**:
>   - Add new warnings: `SYNCHRONOUS_XHR_REQUEST_NOT_INTERCEPTED`, `SYNCHRONOUS_XHR_REQUEST_COOKIES_NOT_APPLIED`, `SYNCHRONOUS_XHR_REQUEST_COOKIES_NOT_SET` (errors, snapshots, GraphQL enum).
> - **Tests**:
>   - Add e2e tests for sync XHR interception behavior (including worker and cross-origin) and cookie behavior; update system tests to assert terminal warnings; unit tests for new header handling.
> - **Misc**:
>   - Update CHANGELOG with bugfix; adjust import paths; add `@packages/errors` devDependency in net-stubbing.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 85265148112cc1d08d48f544db43a407fdfa398e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Steps to test

Verify intercepted synchronous XHR requests with a `routeHandler` no longer cause the browser to hang.
Verify a synchronous XHR request from within a `cy.origin` block and a `set-cookie` in the response no longer cause the browser to hang.

### How has the user experience changed?

The browser no longer hangs with synchronous XHR requests.
Screenshot 2025-12-04 at 10 43 35 AM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/6332
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/runner/injection/main.js [hunk 1]
```diff
@@ -32,3 +32,12 @@ Cypress.on('app:timers:pause', timers.pause)
...
 Cypress.action('app:window:before:load', window)
+
+const originalXmlHttpRequestOpen = window.XMLHttpRequest.prototype.open
+window.XMLHttpRequest.prototype.open = function (...args) {
+  const result = originalXmlHttpRequestOpen.apply(this, args)
+  if (args[2] === false) {
+    this.setRequestHeader('x-cypress-is-sync-request', 'true')
+  }
+  return result
+}
```
[the remark this answers is not in the document]
Comment (alexsch01) [reply packages/runner/injection/main.js]: not true since the cross origin runner is a different runner all together

**Comment by mschile** [comment]
Hi @alexsch01 👋🏼, thanks for opening this PR! Just to make sure I understand the proposed changes, this would resolve the freezing issue but the `routeHandler` of the intercepted request would not be executed. Is my understanding correct?

**Comment by alexsch01** [comment]
> Hi @alexsch01 👋🏼, thanks for opening this PR! Just to make sure I understand the proposed changes, this would resolve the freezing issue but the `routeHandler` of the intercepted request would not be executed. Is my understanding correct?

The routeHandler is executed but the request that goes to the server won't be modified 

req.headers["foo"] = "bar"

The server will not get this since it's not resolved, but anything you console.log in the routeHandler will print in DevTools console

**Comment by mschile** [comment]
Ok, I see the `before:request` event is still emitted but since this is a sync request, the event is received after the sync request has already been fully processed. I'm going to discuss this further with the team but my initial thought is that we should skip the adding the subscriptions entirely [here](https://github.com/cypress-io/cypress/blob/af185e22394fcfb84920ac99cca2a8bf22b86392/packages/net-stubbing/lib/server/intercepted-request.ts#L75).

**Comment by alexsch01** [comment]
The second part of the fix (https://github.com/cypress-io/cypress/pull/32925/commits/7b4f2e75ce1099585c806e0ae906f1bfeab18931) fixes a freezing issue when there's a sync request in cy.origin block

The downside is cross-origin cookies most likely won't work in this case

In cases where you must use `cy.origin` due to navigating to a different subdomain, this allows the test to work as expected when there's a sync request

**Comment by mschile** [comment]
Thanks for cross origin explanation. I'll have to look into it further.

**Comment by mschile** [comment]
@alexsch01, I discussed this PR with the rest of the team and we are good with proceeding. We should skip adding the subscriptions entirely [here](https://github.com/cypress-io/cypress/blob/af185e22394fcfb84920ac99cca2a8bf22b86392/packages/net-stubbing/lib/server/intercepted-request.ts#L75) so the `routeHandler` won't get run. We would also like to log out some warnings to the terminal to inform the user that the sync request was not intercepted and for the cross-origin case that cookies may not have been applied.

**Comment by alexsch01** [comment]
@mschile I skipped adding the subscriptions entirely for sync requests and added the 2 warnings

Let me know how that looks

File: packages/runner/injection/patches/xmlHttpRequest.ts [hunk 2]
```diff
@@ -13,22 +13,32 @@ export const patchXmlHttpRequest = (window: Window) => {
       // we need to store a reference here to what we need in the send method
       this._url = captureFullRequestUrl(args[1], window)
     } finally {
-      return originalXmlHttpRequestOpen.apply(this, args as any)
+      const result = originalXmlHttpRequestOpen.apply(this, args as any)
+
+      this._isSyncRequest = args[2] === false
```
[the remark this answers is not in the document]
Comment (alexsch01) [reply packages/runner/injection/patches/xmlHttpRequest.ts]: fixed in https://github.com/cypress-io/cypress/pull/32925/commits/be6a22f413e99400f71df5b35e357b2d3688566d

File: packages/net-stubbing/lib/server/intercepted-request.ts
Comment (mschile) [inline packages/net-stubbing/lib/server/intercepted-request.ts]: Let's more this into the `for` loop so we can check if the route has a `routeHandler`.
```suggestion
    for (const route of this.req.matchingRoutes) {
      if (route.disabled) {
        continue
      }

      // if the request is sync and the route has an interceptor (i.e. routeHandler), then skip the intercept
      // because the we cannot wait on the before:request event when the sync request is blocking
      if (this.req.isSyncRequest && route.hasInterceptor) {
        process.stdout.write(styleText('yellow', `WARNING: sync XHR request was not intercepted for url: ${this.req.proxiedUrl}\n`))

        return
      }

      const subscriptionsByRoute = {
```

File: packages/proxy/lib/http/response-middleware.ts [hunk 3]
```diff
@@ -719,6 +720,14 @@ const MaybeCopyCookiesFromIncomingRes: ResponseMiddleware = async function () {
     return this.next()
   }
 
+  if (this.req.isSyncRequest) {
+    process.stdout.write(styleText('yellow', 'WARNING: cross-origin cookies may not have been applied\n'))
```
Comment (mschile) [inline packages/proxy/lib/http/response-middleware.ts]:
```suggestion
    process.stdout.write(styleText('yellow', `WARNING: cross-origin cookies may not have been applied for sync request: ${this.req.proxiedUrl}\n`))

```

**Review by mschile — CHANGES_REQUESTED** [review]
Looks good overall! Made a few changes. Let's go ahead and add some unit and e2e tests.

**Comment by alexsch01** [comment]
> Looks good overall! Made a few changes. Let's go ahead and add some unit and e2e tests.

made some tests, your changes look good

**Review by mschile — APPROVED** [review]

File: packages/runner/injection/main.js [hunk 4]
```diff
@@ -16,6 +17,8 @@ if (!Cypress) {
 Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue.')
 }
 
+patchXmlHttpRequest(window)
```
Comment (AtofStryker) [inline packages/runner/injection/main.js:20]: @mschile why do we need to patch here? Is this needed for intercept or something similar?

File: packages/driver/src/cross-origin/cypress.ts [hunk 5]
```diff
@@ -22,8 +22,8 @@ import { handleTestEvents } from './events/test'
 import { handleMiscEvents } from './events/misc'
 import { handleUnsupportedAPIs } from './unsupported_apis'
 import { patchFormElementSubmit } from './patches/submit'
-import { patchFetch } from '@packages/runner/injection/patches/fetch'
-import { patchXmlHttpRequest } from '@packages/runner/injection/patches/xmlHttpRequest'
+import { patchFetch } from '@packages/runner/injection/patches/cross-origin/fetch'
+import { patchXmlHttpRequest } from '@packages/runner/injection/patches/cross-origin/xmlHttpRequest'
```
Comment (AtofStryker) [inline packages/driver/src/cross-origin/cypress.ts:26]: this looks to be patched in main now as well so `cross-origin` as a name seems misleading.

File: packages/runner/injection/main.js (hunk 4 above)
Comment (AtofStryker) [reply packages/runner/injection/main.js:20]: This has broader implications then just setting the sync request parameter and I don't believe the full patch is necessary and could also have downstream consequences

**Review by AtofStryker — CHANGES_REQUESTED** [review]
I don't think we need to fully patch XMLHttpRequest in the main injection code as we do in the cross-origin code. if we need to detect a sync request in the main injection, we likely want to create a partial patch as well as add documentation in the code as to why we are patching the main injection code because right now that is not entirely obvious.

**Review by AtofStryker — APPROVED** [review]
So I completely misread the diff where the patches got moved, so the main injection patch really is simple like we need. My fault on that! Rest of the PR looks good on my end

File: packages/runner/injection/main.js (hunk 4 above)
Comment (mschile) [reply packages/runner/injection/main.js:20]: Discussed with @AtofStryker, yes, this is for `cy.intercept` and this is the simple patch and not the one used for cross-origin.

**Comment by alexsch01** [comment]
@mschile in firefox for the driver cookie_misc test, the sync cookie is set so the length of cookies array is 2
Doesn't happen in Chrome

**Comment by mschile** [comment]
> @mschile in firefox for the driver cookie_misc test, the sync cookie is set so the length of cookies array is 2 Doesn't happen in Chrome

Yep, I'm updating the test since Firefox does indeed get the cookie.

**Comment by alexsch01** [comment]
Thank you guys so much on working with me on this!

I just tested the pre-release and it works perfectly
