### PR TITLE
fix(react18): unmount component with react18 API

### LINKED ISSUE #23081: The React18 support in Component Testing doesn't work
### Current behavior

Currently when running a CT using the new entry "cypress/react18" I get the following error:

image

Which is thrown from https://github.com/cypress-io/cypress/blob/c058bf287861f36371ee2c589dd1e08213e5dfa9/npm/react/src/createMount.ts#L172 because the lastMountedReactDom is react-dom/client which only exports createRoot and hydrateRoot (https://github.com/facebook/react/blob/9fcaf88d58cfd942e2fdd303ae8291dbf4828969/packages/react-dom/client.js#L25)

### Desired behavior

_No response_

### Test code to reproduce

~I can't provide a reproduction at the moment but will provide one soon. Using the react18 entry in a CT suite should cause it immediately.~
https://github.com/joshwooding/cypress-react18-repro

### Cypress Version

10.4.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by rockindahizzy**
- Closes #23081

### User facing changelog
- Fixes issue in component testing when using React 18 mount

### Steps to test
- Build `npm/react` and `npm/react18` projects
- Copy the `dist` folders from the projects and place them in a React project under their respective React folders in `node_modules/cypress`
- Run cypress in the React project

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/react/src/createMount.ts [hunk 1]
```diff
@@ -136,40 +135,33 @@ export const makeMountFn = (
...
-                description: 'Unmounts React component',
-                parent: $el[0],
-                home: 'https://github.com/cypress-io/cypress',
-              }
-            },
-          })
-        }
-      }
-    })
+    const wasUnmounted = mountCleanup()
```
Comment (lmiller1990) [inline npm/react/src/createMount.ts:140]: Can this be undefined? I'm surprised we don't need a null check, since the definition is `let mountCleanup: InternalMountOptions['cleanup']`

Should we add a null check? Could just be `mountCleanup?.()`.

File: npm/react/src/mount.ts [hunk 2]
```diff
@@ -1,34 +1,44 @@
...
   makeUnmountFn,
-  lastMountedReactDom,
 } from './createMount'
 import type {
   MountOptions,
   InternalMountOptions,
-  InternalUnmountOptionsReact,
 } from './types'
 
+let lastReactDom: any
```
Comment (lmiller1990) [inline npm/react/src/mount.ts:13]: Could be `typeof ReactDOM`?

File: npm/react18/src/index.ts [hunk 3]
```diff
@@ -23,20 +32,12 @@ export function mount (jsx: React.ReactNode, options: MountOptions = {}, rerende
...
-  const internalOptions: InternalUnmountOptionsReact18 = {
-    // type is ReturnType<typeof ReactDOM.createRoot>
-    unmount: (): boolean => {
-      root.unmount()
-
-      return true
-    },
-  }
-
-  return makeUnmountFn(options, internalOptions)
```
Comment (lmiller1990) [inline npm/react18/src/index.ts:41]: The file below this (`_snapshots__`) has a surprisingly huge diff with a lot of red. Is this right? It seems to be missing the "summary" part of the CLI output.

**Comment by lmiller1990** [comment]
I tried it out (build the new react modules and stuck them in an existing project's node_modules/cypress) and it's working great, nice job :100:

**Review by lmiller1990 — APPROVED** [review]

**Review by ZachJW34 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Nice, second latest job went all green: https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=zachw%2Ffix-react18-unmount

Not sure why the info in the checkbox is showing red, maybe because I canceled the later build (due to the previous one passing). Let's ship it.

**Review by lmiller1990 — APPROVED** [review]
