### PR TITLE
fix: No longer display tags on `stderr` data in component testing

### LINKED ISSUE #32769: webpack info logs less readable with CYPRESS.STDERR annotations - re-open #32569
- Similar issue still occurs with [cypress@15.5.0](https://docs.cypress.io/app/references/changelog#15-5-0)

- Previous issue https://github.com/cypress-io/cypress/issues/32569 was auto-closed by PR https://github.com/cypress-io/cypress/pull/32674

### Current behavior

Logs for component testing with webpack are less readable than they were with Cypress 14 (14.5.4).

There is a block of information which is labeled as errors:

```text
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Project is running at:
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Content not from webpack is served from '/home/mike/github/cypress-io/cypress-component-testing-apps/react-webpack5-js/public' directory
<<<CYPRESS.STDERR.END>>>
```

### Desired behavior

Revert to a more readable information display, as it was in Cypress 14, for example:

```text
DevTools listening on ws://127.0.0.1:35593/devtools/browser/dccfb69b-5d2a-45eb-98f1-97037b49460a
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/mike/github/cypress-io/cypress-component-testing-apps/react-webpack5-js/public' directory
```

### Test code to reproduce

```shell
git clone https://github.com/cypress-io/cypress-component-testing-apps
cd cypress-component-testing-apps
cd react-webpack5-js
npm install cypress@latest
npx cypress run --component
```

### Cypress Version

`15.5.0`

### Debug Logs

```shell
$ npx cypress run --component

DevTools listening on ws://127.0.0.1:45711/devtools/browser/8a82cc1b-ee90-46ab-9370-129639aa6bc7
<<<CYPRESS.STDERR.START>>>Browserslist: browsers data (caniuse-lite) is 6 months old. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Project is running at:
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Content not from webpack is served from '/home/mike/github/cypress-io/cypress-component-testing-apps/react-webpack5-js/public' directory
<<<CYPRESS.STDERR.END>>>
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        15.5.0                                                                         │
  │ Browser:        Electron 138 (headless)                                                        │
  │ Node Version:   v22.20.0 (/home/mike/n/bin/node)                                               │
  │ Specs:          5 found (App.cy.js, components/Button.cy.js, components/InputField.cy.js, comp │
  │                 onents/LoginForm.cy.js, components/Welcome.cy.js)                              │
  │ Searched:       **/*.cy.{js,jsx,ts,tsx}                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  App.cy.js                                                                       (1 of 5)
4 assets
48 modules
webpack 5.97.1 compiled successfully in 2887 ms
6 assets
54 modules
webpack 5.97.1 compiled successfully in 412 ms
```

### Other

Running the following works, however this is using the `--dev` option, which is not used by regular users, only by contributors.

```shell
yarn
yarn cypress:run --project ../cypress-component-testing-apps/react-webpack5-js --component
```

```text
$ yarn cypress:run --project ../cypress-component-testing-apps/react-webpack5-js --component
yarn run v1.22.22
$ yarn ensure-deps
$ ./scripts/ensure-dependencies.sh
success Folder in sync.
$ cypress run --dev --project ../cypress-component-testing-apps/react-webpack5-js --component

DevTools listening on ws://127.0.0.1:43241/devtools/browser/5be3a658-9333-425a-a08d-e3ab0612618b
Browserslist: browsers data (caniuse-lite) is 6 months old. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/mike/github/cypress-io/cypress-component-testing-apps/react-webpack5-js/public' directory

================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        15.5.0                                                                         │
  │ Browser:        Electron 138 (headless)                                                        │
  │ Node Version:   v22.19.0 (/home/mike/n/bin/node)                                               │
  │ Specs:          5 found (App.cy.js, components/Button.cy.js, components/InputField.cy.js, comp │
  │                 onents/LoginForm.cy.js, components/Welcome.cy.js)                              │
  │ Searched:       **/*.cy.{js,jsx,ts,tsx}                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  App.cy.js                                                                       (1 of 5)
<i> [webpack-dev-middleware] wait until bundle finished: /__cypress/src/index.html
7 assets
55 modules
webpack 5.97.1 compiled successfully in 5821 ms
<i> [webpack-dev-middleware] wait until bundle finished: /__cypress/src/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_127_0_0_1_por-4ef4bb.js
<i> [webpack-dev-middleware] wait until bundle finished: /__cypress/src/main.js
7 assets
55 modules
webpack 5.97.1 compiled successfully in 111 ms
```

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes  https://github.com/cypress-io/cypress/issues/32769

### Additional details
When Cypress intentionally writes to `stderr`, it tags the content so that it will be preserved and written to the top level `stderr`. The `@packages/stderr-filtering` package takes care of tagging data and filtering the tags (and untagged data) from the `stderr` stream. This prevents benign `stderr` messages from Electron from surfacing.

In component testing `run` mode with webpack 5, the out stream was getting tagged. Unfortunately, that entrypoint to the binary was *not* captured by the filtering part of `@packages/stderr-filtering`. 

This moves `filter` streaming from `@packages/electron` to the spawn logic in `@packages/cli`, ensuring it wraps the outermost process and filters any tags that come through `stderr`.

---

> [!NOTE]
> **Medium Risk**
> Changes the CLI’s child-process `stderr` piping and introduces packaging-time dependency filtering, which could affect runtime logging/diagnostics and CLI bundling if misconfigured. Also adjusts system-test dependency resolution and fixtures, which may impact CI install behavior for test projects.
> 
> **Overview**
> Prevents internal `stderr` tagging noise from leaking into user-facing CLI output by routing spawned Cypress process `stderr` through `@packages/stderr-filtering` in `cli/lib/exec/spawn.ts` (with pass-through behavior in dev/debug/logging modes).
> 
> Updates CLI packaging to include `@packages/stderr-filtering` for bundling while stripping all `@packages/*` entries from the published `cli/build/package.json`.
> 
> System tests now reference `cypress` from `cli/build` and the dep-installer resolves `file:` workspace deps to absolute paths relative to the project, with lockfiles updated accordingly.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0f5aa8f223889050f388fbe49024405ebc073612. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### Steps to test
1. `yarn binary-build` (choose: overwrite)
2. `yarn binary-package [--skipSigning, if on osx]`
3. With the fresh binary, run component testing in the webpack5/react project in `cypress-component-testing-apps`: https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-webpack5-js
4. Confirm there is no `CYPRESS.STDERR` tags in the output stream

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: system-tests/lib/dep-installer/index.ts [hunk 1]
```diff
@@ -119,23 +119,29 @@ async function normalizeLockFileRelativePaths (opts: { project: string, projectD
...
+          const absPath = path.resolve(__dirname, '../../projects', projectDir, version.replace('file:', ''))
 
-        log(`Setting absolute path in package.json for ${dep}: ${absPath}.`)
+          log(`Setting absolute path in package.json for ${dep} @ ${version}: ${absPath}.`)
 
-        deps[dep] = `file:${absPath}`
-        updatedDeps.push(dep)
+          deps[dep] = `file:${absPath}`
+          updatedDeps.push(dep)
+        }
```
[the remark this answers is not in the document]
Comment (cacieprins) [reply system-tests/lib/dep-installer/index.ts:139]: This is not a regression

File: cli/lib/exec/spawn.ts
Comment (mschile) [inline cli/lib/exec/spawn.ts:1]: I'm still seeing the following output and using the binary I built. Is this expected? This was the same output as I was seeing in the previous version so not sure if the filtering is working.

```
<<<CYPRESS.STDERR.START>>>Browserslist: browsers data (caniuse-lite) is 10 months old. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://127.0.0.1:8080/
<<<CYPRESS.STDERR.END>>><<<CYPRESS.STDERR.START>>><i> [webpack-dev-server] Content not from webpack is served from '/Users/mschile/Projects/cypress-component-testing-apps/react-webpack5-js/public' directory
<<<CYPRESS.STDERR.END>>>4 assets
```
and
```
<<<CYPRESS.STDERR.START>>><i> [webpack-dev-middleware] wait until bundle finished: /__cypress/src/main.js
<<<CYPRESS.STDERR.END>>>6 assets
```

**Review by mschile — CHANGES_REQUESTED** [review]
Added a comment.

**Comment by alexsch01** [comment]
I don't know if this fixes the case with e2e testing as well
if that's true, should the title be changed?

File: cli/lib/exec/spawn.ts
Comment (mschile) [reply cli/lib/exec/spawn.ts:1]: Nevermind, I wasn't running from the `cli` which obviously isn't running the updated code.

**Review by mschile — APPROVED** [review]
