### PR TITLE
fix: cy.log() inside cy.then() doesn't break subject value in command chain.

### LINKED ISSUE #8084: cy.log in cy.fixture(..).then breaks promise-like compatibility
### Current behavior:

I just tried to put a cy.log into cy.fixture.then like this:

```javascript
it.only('test', () => {
    cy
      .fixture('login')
      .then(async (data) => {
        cy.log('count', Object.keys(data).length);
        return await Object.keys(data).length;
      })
      .then((test) => {
        cy.log('test', test);
      })
  })
```
Result:

Capture du 2020-07-24 16-24-42

We get 'count' with a value, but next then, we don't have the value anymore

If I comment / remove cy.log line, i get

Capture du 2020-07-24 16-25-11

Which is the desired behaviour.

### Desired behavior:

We should get the same value as count in test in second then.

### Versions

Cypress 4.10.0 
Ubuntu 18.10
Chrome 84

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #8084

### User facing changelog
cy.log() inside cy.then() doesn't break the subject value in command chain.

### Additional details
* Why was this change necessary? => The behavior of `cy.then()` was weird when `cy.log()` is used inside it. It always returned `null`.
* What is affected by this change? => N/A
* Any implementation details to explain? => I added 'injected` value to command object. It checks if a command is added inside `then()` function.

### How has the user experience changed?
N/A

### PR Tasks
* [x] Have tests been added/updated?
* [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/misc_spec.js [hunk 1]
```diff
@@ -72,6 +72,18 @@ describe('src/cy/commands/misc', () => {
           })
         })
       })
+
+      // https://github.com/cypress-io/cypress/issues/8084
+      it('log does not corrupt the stack and returns subject correctly', () => {
+        cy.wrap({ a: 42 }).then(async (data) => {
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/misc_spec.js:78]: why `async` keyword here?

Comment (bahmutov) [reply packages/driver/cypress/integration/commands/misc_spec.js:78]: ohh, I see, this is from the original issue

**Review by Bkucera — APPROVED** [review]
