### PR TITLE
fix(runner): fix firefox 'Open in IDE', test against prod builds in CI

### LINKED ISSUE #8257: "Open in IDE" button beside test/hooks in Command Log is not visible in Firefox.
#### Chrome/Electron
Upon hover of hook or test, the 'Open in IDE' button appears.

#### Firefox
Upon hover of hook or test, the 'Open in IDE' button does not appear. I'm using Firefox 78.0.1. I checked back to Cypress 4.10.0 when this feature was introduced and this seems to have always been an issue.

### Desired behavior:
Same behavior in all browsers.

I'm quite curious now about our reporter tests - are they not run through all browsers?

### Versions
Cypress 4.12.1

### PR DESCRIPTION
**Pull request by Bkucera**
prod builds have different stack traces than development builds, so this PR also switches CI to running against prod builds

- Closes #8257 

### User facing changelog
Bug Fix: fix missing "Open in IDE" button in Firefox

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cypress/stack_utils.js [hunk 1]
```diff
@@ -200,6 +199,11 @@ const parseLine = (line) => {
 }
 
 const stripCustomProtocol = (filePath) => {
+  // sometimes stack frames won't include a filepath
+  if (!filePath) {
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/stack_utils.js:203]: Can you add a test for this? It fixes this issue, right? https://github.com/cypress-io/cypress/issues/7870

Comment (Bkucera) [reply packages/driver/src/cypress/stack_utils.js:203]: no, that issue is caused by throwing a string literal, it causes a different error than the one I saw. I'll revert this since we have no open issues for it

File: packages/launcher/.gitignore [hunk 2]
```diff
@@ -1,3 +0,0 @@
-# transpiled JS files
```
Comment (chrisbreiding) [inline packages/launcher/.gitignore:1]: Did you mean to remove these `.gitignore` files? We don't want to commit the transpiled files, do we?

Comment (Bkucera) [reply packages/launcher/.gitignore:1]: yes, they were ignoring transpiled js files that get emitted into the src folders. I prefer them untracked so `git clean -df` properly removes them. This also was useful in the CI script

**Review by chrisbreiding — DISMISSED** [review]

**Comment by Bkucera** [comment]
added retries to a test in 7_record_spec since it was flaking so often

**Review by chrisbreiding — APPROVED** [review]
