### PR TITLE
fix(proxy-logging): use constant consoleProps object

### LINKED ISSUE #17656: Regression: clicking a request in the log no longer displays request/response body
### Current behavior

After updating to Cypress 8.2.0, request and/or response bodies are no longer displayed in the console when clicking on certain requests in the log. Example:

image

The selected request has both a request body and a response body, but the information displayed in the console suggests that it has neither. Expanding the `XmlHttpRequest` object does show the response body, but not the request body. This is both misleading and inconvenient when examining requests.

Note that this issue does not seem to affect all requests, but those it does affect, it seems to affect consistently.

### Desired behavior

In Cypress 8.1.0, the request and response bodies are clearly shown in the console output:

image

### Test code to reproduce

```js
it('', () => {
  cy.visit('http://automationpractice.com/index.php?controller=authentication&back=my-account')
  cy.get('#email_create').type('a@b{enter}')
})
```
When the test has finished, open the console and click the `POST 200 /index.php` request at the bottom of the runner log. Note that I do not own or control this website. It appears to be flaky sometimes; if that happens, please try again after a few minutes.

### Cypress Version

8.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #17656 

### User facing changelog

- Fixed a regression introduced in 8.2.0 where certain XMLHttpRequests would not display their response bodies in the DevTools Console when clicked, even though they did before.

### Additional details

- This approach is used elsewhere (ex. commands/querying.js) to propagate consoleProps updates to the console.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cypress/proxy-logging.ts [hunk 1]
```diff
@@ -211,9 +152,89 @@ class ProxyRequest {
...
+            name: 'Initiator',
+            items: [this.stack],
+            label: false,
+          },
+        ]
+      }
+    }
+
+    // ensure these fields are always ordered correctly regardless of when they are added
+    ['Response Status Code', 'Response Headers', 'Response Body', 'Request Headers', 'Request Body'].map((k) => delete consoleProps[k])
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/proxy-logging.ts:206]:
```suggestion
    ['Response Status Code', 'Response Headers', 'Response Body', 'Request Headers', 'Request Body'].forEach((k) => delete consoleProps[k])
```

**Review by chrisbreiding — APPROVED** [review]
