### PR TITLE
fix: updated cy.intercept to automatically parse more JSON MIME types

### LINKED ISSUE #14763: Yield object instead of string in cy.wait when request content-type is valid JSON Mime type (not only application/json)
Possibly a duplicate or related to https://github.com/cypress-io/cypress/issues/14273.

Our back-end services use JSON:API spec (https://jsonapi.org/) which recommends the media type [application/vnd.api+json](https://www.iana.org/assignments/media-types/application/vnd.api+json). They deliver valid JSON in the response body, which should be converted to an object by `cy.wait` to allow for deep assertions.

### Current behavior

If request is intercepted with `cy.intercept()`, then `cy.wait()` yields a string for the response body (related issue: #14273.)

From this comment: https://github.com/cypress-io/cypress/issues/14273#issuecomment-765625317, I believe this is due to the check in https://github.com/cypress-io/cypress/blob/6ee7a9c27e9ea8b7dceee6bae140ce86d816a5e1/packages/driver/src/cy/net-stubbing/events/utils.ts#L4-L20

Due to our back-end sending `content-type: application/vnd.api+json` this check fails, and so the response body is not converted using `JSON.parse`.

### Desired behavior

I believe that if the response to a request is valid JSON, it should be converted to a JS object regardless of the headers. This approach is taken elsewhere in Cypress, ie:
 https://github.com/cypress-io/cypress/blob/dae76a8ec0a149d5f4ca4fbe4d15bea1b5f7449d/packages/server/lib/controllers/xhrs.js#L9-L23

Effectively if `JSON.parse(text)` succeeds without throwing, we can assume that `text` is valid JSON and return the resulting parsed object.

### Test code to reproduce

```js
describe('cy.intercept tests', () => {
  it('test cy.intercept() with application/json', () => {
    cy.intercept('POST', '/users', { foo: 'bar' }).as('postUrl');
    cy.visit('https://example.com');
    cy.then((win) => {
      Cypress.$.ajax({
        url: '/users',
        method: 'POST',
        contentType: 'application/json',
        data: JSON.stringify({ name: 'XYZ' }),
      });
    });

    cy.wait('@postUrl')
      .should((interception) => {
        expect(typeof interception.response.body).to.eq('object');
        expect(interception.response.body).to.deep.eq({ foo: 'bar' })
      });
  });

  it('test cy.intercept() with application/vnd.api+json', () => {
    // temporary API endpoint at mocky.io that responds with 'content-type: application/vnd.api+json'
    cy.intercept('GET', 'https://run.mocky.io/v3/5c528eae-f3c0-4dbe-b9cb-7b12a00320ad').as('jsonApiUrl');
    cy.visit('https://example.com');
    cy.then((win) => {
      Cypress.$.ajax({
        url: 'https://run.mocky.io/v3/5c528eae-f3c0-4dbe-b9cb-7b12a00320ad',
        method: 'GET',
      });
    });

    cy.wait('@jsonApiUrl')
      .should((interception) => {
        expect(interception.response.headers['content-type']).to.contain('application/vnd.api+json');
        // ❗️ fails
        expect(typeof interception.response.body).to.eq('object');
        // ❗️ fails
        expect(interception.response.body).to.deep.eq({ foo: 'bar' });
      });
  });
});
```

### Versions

6.3.0

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #14763

### User facing changelog

- BREAKING CHANGE: Updated cy.intercept to automatically parse more JSON MIME types, including 'application/vnd.api+json'.
	- This may remove the need to `JSON.parse(req.body)` or `JSON.parse(res.body)` manually in tests.
	
### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-describe('network stubbing', { retries: 2 }, function () {
+describe('network stubbing', { retries: 0 }, function () {
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1]: ohh my, pretty sure of yourself

Comment (flotwig) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1]: oh hehe
```suggestion
describe('network stubbing', { retries: 2 }, function () {
```

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 2]
```diff
@@ -1083,27 +1083,33 @@ describe('network stubbing', { retries: 2 }, function () {
...
+        ['application/vnd.api+json', '{}'],
+      ].forEach(([contentType, expectedBody]) => {
+        it(`automatically parses ${contentType} request bodies`, function () {
+          const p = Promise.defer()
 
-        cy.intercept('/post-only', (req) => {
-          expect(req.body).to.deep.eq({ foo: 'bar' })
+          cy.intercept('/post-only', (req) => {
+            expect(req.headers['content-type']).to.eq(contentType)
+            expect(req.body).to.deep.eq({ foo: 'bar' })
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1095]: but not `expectedBody`?

Comment (flotwig) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1095]: Yes, `expectedBody` is for the expected response body only - Express will not auto-parse the POSTed JSON with the content-type `application/vnd.api+json`, so that is why they differ

**Review by bahmutov — APPROVED** [review]
I think this works, and since you added tests, should work

**Comment by bahmutov** [comment]
🚢
