### PR TITLE
fix: silence dbus errors

### LINKED ISSUE #19299: "Failed to connect to the bus: Address does not contain a colon" throws a SIGSEGV error
### Current behavior

Our tests intermittently crash in our Docker runs with the error below. We get the `Failed to connect to the bus: Address does not contain a colon` error often, but it doesn't crash it.

But, when it *does* crash, that error is always the last one before the SIGSEGV.

I think we're going to downgrade to 8.5.0 to fix this as it wasn't happening back then. However, before we do, is there some kind of diagnostic log that will help you, help me, help you? :)

Thanks, and I know this is vague, not sure where to even start here.

```
[15:24:18]W:		 [Docker Run] [111:1207/202418.627106:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[15:24:19] :		 [Docker Run] The Test Runner unexpectedly exited via a exit event with signal SIGSEGV
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Please search Cypress documentation for possible solutions:
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] https://on.cypress.io
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Check if there is a GitHub issue describing this crash:
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] https://github.com/cypress-io/cypress/issues
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Consider opening a new issue.
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] ----------
[15:24:19] :		 [Docker Run] 
[15:24:19] :		 [Docker Run] Platform: linux-x64 (Debian - 10.10)
[15:24:19] :		 [Docker Run] Cypress Version: 9.1.1
[15:24:19] :		 [Docker Run] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[15:24:19]W:		 [Docker Run] error Command failed with exit code 1.
[15:24:19]W:		 [Docker Run] Error: Command failed with exit code 1: yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false
[15:24:19]W:		 [Docker Run]     at makeError (/workspace/Sites/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
[15:24:19]W:		 [Docker Run]     at handlePromise (/workspace/Sites/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
[15:24:19]W:		 [Docker Run]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[15:24:19]W:		 [Docker Run]   shortMessage: 'Command failed with exit code 1: yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false',
[15:24:19]W:		 [Docker Run]   command: 'yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false',
[15:24:19]W:		 [Docker Run]   escapedCommand: '"yarn test:cypress --reporter teamcity --config video=false,defaultCommandTimeout=10000 --record false"',
[15:24:19]W:		 [Docker Run]   exitCode: 1,
[15:24:19]W:		 [Docker Run]   signal: undefined,
[15:24:19]W:		 [Docker Run]   signalDescription: undefined,
[15:24:19]W:		 [Docker Run]   stdout: undefined,
[15:24:19]W:		 [Docker Run]   stderr: undefined,
[15:24:19]W:		 [Docker Run]   failed: true,
[15:24:19]W:		 [Docker Run]   timedOut: false,
[15:24:19]W:		 [Docker Run]   isCanceled: false,
[15:24:19]W:		 [Docker Run]   killed: false
[15:24:19]W:		 [Docker Run] }
[15:24:19]W:		 [Docker Run] error Command failed with exit code 1.
[15:24:19] :		 [Docker Run] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired behavior

Do not throw the SIGSEGV.

### Test code to reproduce

It can happen on any test, at any time, in our 850+ test test suite.

### Cypress Version

9.1.1

### Other

It doesn't seem to happen if we run on Windows, and we have a parallel set of Component tests (about 100) that have yet to show the issue and they're run exactly the same way in the same Docker container, just as component tests.

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes #19299

### User facing changelog
Silences electron warnings about being unable to connect to dbus. These errors are normal and expected, and do not result in test failures. They are present when running electron inside docker containers 100% of the time.

### Additional details
Chromium (which Electron uses) always makes several attempts to connect to the system dbus. This works fine in most desktop environments, but in a docker container, there is no dbus service and Chromium emits several error lines, similar to these:

```
[1957:0406/160550.146820:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1957:0406/160550.147994:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[1957:0406/160550.147994:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
[1957:0406/160550.147994:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
```

These warnings are absolutely harmless. Failure to connect to dbus means that electron won't be able to access the user's credential wallet (none exists in a docker container) and won't show up in the system tray (again, none exists). Failure to connect is expected and normal here, but users frequently misidentify these errors as the cause of their problems.

On a more technical level, chromium calls [dbus_bus_get()](https://dbus.freedesktop.org/doc/api/html/group__DBusBus.html#ga77ba5250adb84620f16007e1b023cf26), which is provided by libdbus. This call returns an error if dbus cannot be found or connected to for whatever reason. Chromium handles these errors correctly, internally ceasing to attempt to use the service, but it re-prints the errors to stderr while doing so.

Basically: It tries to connect, gets an error, and aborts. All very normal behavior, which is why no one has tried to 'fix' the problem. Because there is no problem.

### How has the user experience changed?
Users will no longer see errors in the log when running Cypress inside docker. Instead of:

image

they'll get

image

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: cli/lib/exec/spawn.js [hunk 1]
```diff
@@ -16,7 +16,21 @@ const isXlibOrLibudevRe = /^(?:Xlib|libudev)/
...
+
+// [1957:0406/160550.146820:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
+// [1957:0406/160550.147994:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
+
+// These warnings are absolutely harmless. Failure to connect to dbus means that electron won't be able to access the user's
+// credential wallet (none exists in a docker container) and won't show up in the system tray (again, none exists).
+// Failure to connect is expected and normal here, but users frequently misidentify these errors as the cause of their problems.
+
+// https://github.com/cypress-io/cypress/issues/19299
+const isDbusWarning = /Failed to connect to the bus:/
```
Comment (jennifer-shehane) [inline cli/lib/exec/spawn.js:31]: Do you think this is an adequate Regex? I guess it's highly unlikely someone would have "Failed to connect to the bus:" as some other output that would be stripped. Feels a bit less specific than the other ones stripped though.

Comment (BlueWinds) [reply cli/lib/exec/spawn.js:31]: This regex is applied pretty narrowly: to the stdout/stderr from electron itself. This doesn't filter any user-generated messages or things coming from our server. I settled on this based on the chromium source code:

```
  if (!connection_) {
    LOG(ERROR) << "Failed to connect to the bus: "
               << (dbus_error_is_set(error.get()) ? error.message() : "");
    return false;
  }
```
https://chromium.googlesource.com/chromium/src/+/524f7d22d706ccf6264dbe0ea90a5b469f2c3379/dbus/bus.cc#392

I think it's about as specific as is reasonable here - ideally we won't need to update it as we change electron versions, so the 'technical' stuff up front (`[1957:0406/160550.147994:ERROR:bus.cc(392)]`) doesn't seem like a good candidate for inclusion.

**Review by flotwig — COMMENTED** [review]
@BlueWinds When testing `yarn cypress:run` locally with `yarn docker`, there is a new Chromium stderr that looks like it will mislead folks in a similar way: 

`[371:0406/175035.061253:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is `

Can reproduce by doing `yarn docker` in the monorepo and running `yarn cypress:run --project packages/example`.

---

Also, when I run the latest prod `cypress open`, I get two log lines:

```
[343988:0406/135427.824393:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
[343988:0406/135427.825018:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
```

Sounds like these could all be related to video acceleration? https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled

Feels like these are important to address too, @BlueWinds thoughts?

**Comment by emilyrohrbough** [comment]
@BlueWinds I am good with the changes, but I'm wondering if this change will satisfy closing the issue it's linked to? Quite a few people have reported issues with crashes & SIGSEGV errors immediately after seeing these dbus errors and this isn't addressing SIGSEGV errors at all.

**Comment by BlueWinds** [comment]
> @BlueWinds I am good with the changes, but I'm wondering if this change will satisfy closing the issue it's linked to? Quite a few people have reported issues with crashes & SIGSEGV errors immediately after seeing these dbus errors and this isn't addressing SIGSEGV errors at all.

I am 100% sure that these errors are not causing the crashes they're seeing.

The ticket linked to here contains people reporting half a dozen different bugs - but none of them are actually related to dbus. This is just the last output line, so they assume their problems must be related, and put it all in the same ticket. The hope is, that by hiding these misleading lines, they will open new, more focused, more helpful tickets. Or at the very least, they'll clump their error reports in more useful ways (systems, browsers, versions).

It won't address the crashes people are seeing - but a bit 'catch all' ticket ensures that we'll never be able to help them at all.

**Comment by BlueWinds** [comment]
> @BlueWinds When testing `yarn cypress:run` locally with `yarn docker`, there is a new Chromium stderr that looks like it will mislead folks in a similar way:
> 
> `[371:0406/175035.061253:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is `
> 
> Can reproduce by doing `yarn docker` in the monorepo and running `yarn cypress:run --project packages/example`.
>
> Also, when I run the latest prod `cypress open`, I get two log lines:
> 
> ```
> [343988:0406/135427.824393:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
> [343988:0406/135427.825018:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
> ```
> 
> Sounds like these could all be related to video acceleration? https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled
> 
> Feels like these are important to address too, @BlueWinds thoughts?

Yes, I've seen these as well. I don't want to hide them because I don't understand them - I'd want to do another deep-dive into those log lines to see what they mean, if we can fix them, if they're genuinely harmless, etc. before deciding what to do about them. So far I've only done this with the dbus errors, not the GL ones.

Would prefer to do that in a separate effort though.

**Comment by emilyrohrbough** [comment]
100% agree with your thoughts and reasoning here. Just pointing out if we link this PR as closing this issue, our bot will indicate the issue has been which will be mis-leading since your intentions are close this issue with too many different issues reported and ask people to open new issues with details after upgrading with these error messages filtered out. Might be worth linking this issue, commenting your intentions on the thread when this merges and locking the issue to push towards new issue creation.

**Review by emilyrohrbough — APPROVED** [review]

**Comment by cubanx** [comment]
So I originally posted that message. Sorry it caused all the confusion, my original bug report was about `SIGSEV` and not about the issue this is fixing, I just pointed it out as I thought it *might* be related, but it turns out it isn't :)

You might want to point out to folks that I solved the `SIGSEV` issue by switching to Chrome from Electron. Our runs have been rock solid (well, except when we break them ;)) since.

Thanks for deep diving and hiding the errors, and tell @chrisbreiding I said 👋🏼

**Comment by BlueWinds** [comment]
> So I originally posted that message. Sorry it caused all the confusion, my original bug report was about `SIGSEV` and not about the issue this is fixing, I just pointed it out as I thought it _might_ be related, but it turns out it isn't :)
> 
> You might want to point out to folks that I solved the `SIGSEV` issue by switching to Chrome from Electron. Our runs have been rock solid (well, except when we break them ;)) since.
> 
> Thanks for deep diving and hiding the errors, and tell @chrisbreiding I said 👋🏼

Yeah, absolutely nothing wrong with your original report! It just got tangled up in a dogpile of other issues, and is now the top (and almost only) result when people google the dbus error, which leads to them to pile in there and connect the two (error + SIGSEV).

**Review by flotwig — APPROVED** [review]
> Yes, I've seen these as well. I don't want to hide them because I don't understand them - I'd want to do another deep-dive into those log lines to see what they mean, if we can fix them, if they're genuinely harmless, etc. before deciding what to do about them. So far I've only done this with the dbus errors, not the GL ones.
> 
> Would prefer to do that in a separate effort though.

Totally understand. Is there a follow-up issue or task created for this? I don't want this to get lost, if we don't follow up with that next fix, users will be back in the same confusing place.

**Comment by BlueWinds** [comment]
> > Yes, I've seen these as well. I don't want to hide them because I don't understand them - I'd want to do another deep-dive into those log lines to see what they mean, if we can fix them, if they're genuinely harmless, etc. before deciding what to do about them. So far I've only done this with the dbus errors, not the GL ones.
> > Would prefer to do that in a separate effort though.
> 
> Totally understand. Is there a follow-up issue or task created for this? I don't want this to get lost, if we don't follow up with that next fix, users will be back in the same confusing place.

https://github.com/cypress-io/cypress/issues/18947. It is marked as 'solved' in the title, but it's an issue specifically related to those errors which users are also finding and identifying as the source of their problems. Not quite as popular as the dbus one, but I'll bring it up for prioritization next.
