### PR TITLE
Handle webpack protocol file opening

### LINKED ISSUE #7294: Error file paths can't be opened in IDE when using webpack protocol
### Current behavior:

If using a webpack protocol for files (e.g. `webpack:///`), when an error is displayed, the file can't be opened in one's IDE.

Screen Shot 2020-05-11 at 9 59 25 AM

### Desired behavior:

Files can be opened even when using a webpack protocol to serve them.

### Test code to reproduce

This issue is reproducible within the [`code-frame-webpack-link-issue`](https://github.com/cypress-io/cypress-realworld-app/tree/code-frame-webpack-link-issue) branch of the `cypress-realworld-app` which uses TS spec files and uses `@cypress/webpack-preprocessor`.

1. Clone `https://github.com/cypress-io/cypress-realworld-app.git`
2. Check out [`code-frame-webpack-link-issue`](https://github.com/cypress-io/cypress-realworld-app/tree/code-frame-webpack-link-issue)  branch.
3. `yarn`
4. `yarn start`
5. Run [`new-transaction.spec.ts`](https://github.com/cypress-io/cypress-realworld-app/blob/code-frame-webpack-link-issue/cypress/tests/ui/new-transaction.spec.ts) which already has `.only` on at test for reproduction.

### Versions

Cypress: 4.6.0-prerelease (`develop` branch)

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7294 

### User facing changelog

N/A. This is only an issue in `develop`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/test/cypress/plugins/index.js [hunk 1]
```diff
@@ -5,11 +5,17 @@ const _ = require('lodash')
 const path = require('path')
 const fs = require('fs-extra')
 const Promise = require('bluebird')
-const webpack = require('@cypress/webpack-preprocessor')
+const wp = require('@cypress/webpack-preprocessor')
 
 process.env.NO_LIVERELOAD = '1'
 const webpackOptions = require('@packages/runner/webpack.config.ts').default
 
+// set mode to development
```
Comment (chrisbreiding) [inline packages/driver/test/cypress/plugins/index.js:13]: Can we change these comments to describe why these are being set instead of what they're being set to?

Comment (brian-mann) [reply packages/driver/test/cypress/plugins/index.js]: done
