### PR TITLE
fix: XHR event listener AUT redirect bug

### LINKED ISSUE #3975: Incorrect redirect to malformed url within AUT - adding `_/` in url
### Current behavior:
When I instruct cypress to login to an Oracle APEX application, the authentication re-directs cypress to a '404 not found' page because the authenticated URL is malformed. The malformed URL is the only issue and can simply corrected programmatically (with a find and replace command).
Screen Shot 2019-04-15 at 10 14 48 PM

However - it is very important to note that the cypress login correctly returns:
1. a valid cookie
2. a valid session

which is everything you need for authentication.

### Desired behavior:

Cypress, ideally, should be able to follow the same authentication redirect that a user would in a regular browser. 

### Steps to reproduce: (app code and test code)

I created a dummy application with dummy credentials hosted by apex.oracle.com to demonstrate:
```js
it('Login demo', function() {
    cy.visit('https://apex.oracle.com/pls/apex/f?p=54707:LOGIN_DESKTOP')
    cy.get('#P9999_USERNAME').type('ApexUser')
    cy.get('#P9999_PASSWORD').type('Oradoc_db1')
    cy.get('.t-Button').click()
  })
```
The above code (which should work until the application expires in many months) will redirect to a 404 not found page with a url in the format: 
https://apex.oracle.com/__/f?p=54707:1:[session_id]:::::
Outside of cypress the url will have the format:
https://apex.oracle.com/pls/apex/f?p=54707:1:[session_id]:::::

### Versions
I have tested this across 4 instances of Oracle APEX (APEX 5.0, 5.1, 18.1 and 19) and this behavior is consistent.

### LINKED ISSUE #7439: Redirect adds `__` within directory path when `experimentalSourceRewriting` is on
### Current behavior:

Current behavior:
When I login through the normal browser then I am able to log in.
But when running from cypress test runner the directory path is missing from URL.

The Cypress Test Runner redirects to: `http://:8084/__/branchHome.html`

image

I have added below after there was a comment on my previous same bug still it didn't worked.

The previous bug raised: #5569

image

My cypress.json file:

image

### Desired behavior:

The Cypress Test Runner should redirect to : http://:8084//branchHome.html 

### Test code to reproduce

Below is the code:

```js
cy.visit("http://<ip>:8084/<directory>")
cy.get("#login").click()
cy.get("input[value='Organization']").click()
cy.get("#username").type('<User name provided>')
cy.get("#pwd").type('<password provided>')
cy.get("#login").click()
```

### Versions

Cypress Version : 4.6.0
Operating System: Windows 10
Browser : Chrome 81 / Electron 80

### LINKED ISSUE #15490: Cypress is crashing after a redirection with a "Whoops no tests to run" error
### Current behavior
I have an editor in the middle of our main flow, that is built in angular. When I click Done it triggers a ng-onClick function that saves content and has a redirection, It is supposed to move to the next step of the process but instead it crashes. 

### Desired behavior
I want to see the next step

### Test code to reproduce
I'm using cucumber on top. Unfortunately I can't share the app or real data for security reasons but here are the steps where it fails. 

Open the editor (I have to manually switch the domain because it is getting the resources from a different place): 
`When('I click choose for opening the editor', () => {
    cy.intercept('GET', 'block.html', (req) => {
        let grootUrl = req.url.replace('dev.myapp.io', 'geteditor.com')
        req.url = grootUrl
    })
    cy.intercept('GET', 'repeater.html', (req) => {
        let grootUrl = req.url.replace('dev.myapp.io', 'geteditor.com')
        req.url = grootUrl
    })
    cy.intercept('GET', 'root-block.html', (req) => {
        let grootUrl = req.url.replace('dev.myapp.io', 'geteditor.com')
        req.url = grootUrl
    })
    campaigns.openEditorButton().click()
})`

And then I click Done
`When('I click Done editing', () => {
    draganddropeditor.doneEditingButton().click()
})`

Some more context. 
The Editor is a different application integrated within the flow. And in order to know where to redirect, it has the following code: 
`window.top.location = url || window.CALLBACK_URL`

Where the main app is replying with the URL where this one is supposed to redirect. 

After clicking Done, it goes to an endpoint that triggers a 302 redirect to /__/ and it crashes

### Versions
"cypress": "6.6.0"

### PR DESCRIPTION
**Pull request by tgriesser**
- Fixes #3975
- Fixes #7439

May also address #15490, #9261, #7871

### User facing changelog

Fix for incorrect redirect when `location.href` is set to a relative path within the call stack of an XHR event handler, which incorrectly sets the user's AUT to `/__/` rather than the correct path. 

~Additionally, adds code to detect when a form submit target is set to `_top` and sets to `''` to avoid redirecting the parent frame.~ Edit: Split out to #16394

### Additional details

This was caused by the changes in this Chromium commit: https://bugs.chromium.org/p/chromium/issues/detail?id=849236 (big thanks to @jennifer-shehane doing the initial range narrowing on that one) which changed the mechanics of how the window is bound around events, which I believe had an inadvertent side affect that affects `location.href` assignment. 

This ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=1195471 seems like it will possibly address the issue, but this behavior is consistent in both Firefox & Chrome, so it's likely worth fixing on our end for now. 

By wrapping the handlers in a function defined in the AUT window (@brian-mann had the idea for that one), the event handler is correctly associated with the AUT, and it doesn't impact the `location.href` assignment.

### How has the user experience changed?

User's AUT is no-longer redirected incorrectly to `/__/path` but instead to the correct relative window location path.

### PR Tasks

- [X] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/listeners.js [hunk 1]
```diff
@@ -21,9 +21,16 @@ const removeAllListeners = () => {
...
 
-  win.addEventListener(event, cb)
+  win.__cypressEventMapRPC = win.__cypressEventMapRPC || {}
+  win.__cypressEventMapRPC[id] = cb
+
+  const fn = new win.Function('evt', `window.__cypressEventMapRPC[${id}].call(this, evt)`)
+
+  events.push([win, event, fn])
+
+  win.addEventListener(event, fn)
```
Comment (flotwig) [inline packages/driver/src/cy/listeners.js:33]: seems like this could be moved into a function and reused here and in `server.js` `addXhrHandler`, they are pretty similar

also, a comment explaining what this does would be helpful

File: packages/driver/src/cy/listeners.js [hunk 2]
```diff
@@ -21,9 +21,16 @@ const removeAllListeners = () => {
 }
 
 const addListener = (win, event, cb) => {
-  events.push([win, event, cb])
+  const id = Math.random()
 
-  win.addEventListener(event, cb)
+  win.__cypressEventMapRPC = win.__cypressEventMapRPC || {}
+  win.__cypressEventMapRPC[id] = cb
```
Comment (flotwig) [inline packages/driver/src/cy/listeners.js:27]: Is this really RPC?

> In distributed computing, a remote procedure call is when a computer program causes a procedure to execute in a different address space, which is coded as if it were a normal procedure call, without the programmer explicitly coding the details for the remote interaction.

`win.__cypressListenerMap`, `win.__cypressListenerCbs`, `win.__cypressEventCbMap`, `win.__cypressEventCbs` i feel like are more apt names

**Review by flotwig — APPROVED** [review]
awesome, some minor nits

File: packages/driver/src/cy/listeners.js (hunk 2 above)
Comment (tgriesser) [reply packages/driver/src/cy/listeners.js:27]: Yeah, good point - I think I named it this was b/c we noted how this was similar to how other RPC implementations work in cross window communication, but in this case it's not.

File: packages/driver/src/cy/listeners.js (hunk 1 above)
Comment (tgriesser) [reply packages/driver/src/cy/listeners.js:33]: Probably could be, yeah. Also @brian-mann had an alternate idea for how we might solve this which won't require `new Function`

File: packages/driver/src/cy/listeners.js [hunk 3]
```diff
@@ -21,9 +21,16 @@ const removeAllListeners = () => {
 }
 
 const addListener = (win, event, cb) => {
-  events.push([win, event, cb])
+  const id = Math.random()
```
Comment (chrisbreiding) [inline packages/driver/src/cy/listeners.js:24]: This is intended to be a unique ID, right? I prefer to use something like [`_.uniqueId()`](https://lodash.com/docs/4.17.15#uniqueId) or an incrementing number in that case. The possibility of a collision with a random number is pretty unlikely, but not impossible. The problem is if a collision does occur, it can surface in an obscure way and be very difficult to debug since it's literally random. Using a unique ID won't have that problem and also expresses the intent more clearly.

Comment (tgriesser) [reply packages/driver/src/cy/listeners.js]: This is gone in the new implementation

File: cli/types/cypress.d.ts [hunk 4]
```diff
@@ -5284,7 +5290,7 @@ declare namespace Cypress {
      * Useful to modify the window on a page transition.
      * @see https://on.cypress.io/catalog-of-events#App-Events
      */
-    (action: 'window:before:load', fn: (win: AUTWindow) => void): Cypress
+    (action: 'window:before:load', fn: (win: AUTWindow, eventHandlerWrap?: EventHandlerWrap | undefined) => void): Cypress
```
Comment (chrisbreiding) [inline cli/types/cypress.d.ts:5293]: I don't know if we want or need to update the public API for this. The `app:window:before:load` event is internal, so I think this can be accomplished by only changing its signature.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

**Comment by jennifer-shehane** [comment]
@tgriesser I know this seems unrelated, but I'm wondering if this would also fix https://github.com/cypress-io/cypress/issues/1244 as a number of the users in that thread had a situation of redirecting to a __/ url, but were shown this illegal operation error as a result.

There's a repro example here: https://github.com/cypress-io/cypress/issues/1244#issuecomment-806070150

**Comment by tgriesser** [comment]
@jennifer-shehane yeah, looks very likely that's related (added it to the list of issues in the PR description). I'm guessing that the behavior when the incorrect redirect takes place could manifest in different ways depending on the situation.

Basically any issue that involves a location change within the same call stack as an event listener that's also observed by Cypress is a likely candidate.

I'd guess the `submit` or any of the `xhr` events are probably the common situations where this happens.

**Review by chrisbreiding — DISMISSED** [review]

**Review by brian-mann — CHANGES_REQUESTED** [review]
- cannot keep a reference to a function that's bound to an old window
- must recreate the function when each new window is bound such as during page navigation within a single test
- update impl to handle `about:blank`
- prevent `state` from wiping this reference in between tests like we do for `document` and `window`

File: packages/driver/src/cypress/server.js [hunk 5]
```diff
@@ -421,6 +422,8 @@ const create = (options = {}) => {
       const { send, open, abort } = XHR.prototype
       const srh = XHR.prototype.setRequestHeader
 
+      const bridgeContentWindowListener = makeContentWindowListener('cypressXhrBridge', contentWindow)
```
Comment (tgriesser) [inline packages/driver/src/cypress/server.js:425]: @brian-mann This is now only creating once per window load, since it's outside the XHR patching

**Comment by drumbeg** [comment]
Will this fix be behind the `experimentalSourceRewriting` flag?

Switching this flag on presents application breaking issues for us.

**Comment by drumbeg** [comment]
Great work guys. Thanks. Works in my limited testing so far.
