### PR TITLE
fix: performance regression due to enabling ScopeMemoryCachePerContext

### LINKED ISSUE #28295: Cached (status 304) requests may take longer than they used to
### Current behavior

Seeing an increase in timing for 304 requests:

**13.5.0**

image

vs.

**13.4.0**

image

This was broken with this change: https://github.com/cypress-io/cypress/pull/28217. While the font flooding did go down, it seems to have effected caches outside of just memory caches.

### Desired behavior

_No response_

### Test code to reproduce

Have a spec with multiple tests that load the same (large) asset.

### Cypress Version

13.5.0

### Node version

all

### Operating System

all

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28295 

### Additional details

This fix basically reverses the commit that was done to try and prevent the font flooding. The only addition is a change to ensure that https://github.com/cypress-io/cypress/issues/28150 stays fixed (namely [this commit](https://github.com/cypress-io/cypress/commit/498c394593032d84d12b7fc99e05ed46dd3fafe9)).

### Steps to test

n/a

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: system-tests/lib/protocol-stubs/protocolStubFontFlooding.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ export class AppCaptureProtocol implements AppCaptureProtocolInterface {
     }
 
     this.cdpClient.on('Network.requestWillBeSent', (params) => {
+      console.log(params)
```
Comment (ryanthemanuel) [inline system-tests/lib/protocol-stubs/protocolStubFontFlooding.ts]:
```suggestion
```

File: system-tests/__snapshots__/protocol_spec.js [hunk 2]
```diff
@@ -6678,6 +6678,50 @@ exports['component events - experimentalSingleTabRunMode: true'] = `
   "pageLoading": [],
   "resetTest": [],
   "responseEndedWithEmptyBody": [
+    {
```
Comment (mschile) [inline system-tests/__snapshots__/protocol_spec.js:6681]: Are these returning empty bodies now because of the caching change?

File: packages/driver/src/dom/elements/complexElements.ts [hunk 3]
```diff
@@ -290,6 +290,12 @@ export const isScrollable = ($el) => {
     return false
   }
 
+  const documentElement = $document.getDocumentFromElement(el).documentElement
+
+  if (el === documentElement) {
```
Comment (mschile) [inline packages/driver/src/dom/elements/complexElements.ts:296]: All the other scenarios are documented in this function, suggest documenting this one as well.

File: system-tests/__snapshots__/protocol_spec.js (hunk 2 above)
Comment (ryanthemanuel) [reply system-tests/__snapshots__/protocol_spec.js:6681]: Yeah this is similar to what we saw in the cypress-services repo. Slightly different behavior due to the caching change.

**Review by mschile — APPROVED** [review]

File: packages/driver/src/dom/elements/complexElements.ts [hunk 4]
```diff
@@ -290,6 +290,12 @@ export const isScrollable = ($el) => {
     return false
   }
 
+  const documentElement = $document.getDocumentFromElement(el).documentElement
```
Comment (ryanthemanuel) [inline packages/driver/src/dom/elements/complexElements.ts:294]:
```suggestion
  // If we're at the documentElement, we check its size against the window
  const documentElement = $document.getDocumentFromElement(el).documentElement
```

File: packages/driver/cypress/e2e/dom/visibility.cy.ts [hunk 5]
```diff
@@ -53,7 +53,7 @@ describe('src/cypress/dom/visibility', () => {
       expect(fn()).to.be.true
     })
 
-    it('returns false window and body > window height', () => {
+    it('returns false if window and body < window height', () => {
```
Comment (emilyrohrbough) [inline packages/driver/cypress/e2e/dom/visibility.cy.ts:56]: what this title wrong before?

Comment (ryanthemanuel) [reply packages/driver/cypress/e2e/dom/visibility.cy.ts:56]: Yes. Things should only be scrollable if they're > than the height not <.

Comment (ryanthemanuel) [reply packages/driver/cypress/e2e/dom/visibility.cy.ts:56]: Basically this is the opposite of line 45.

**Review by chrisbreiding — APPROVED** [review]
