### PR TITLE
fix: reduce requests paused and redundant headers

### LINKED ISSUE #26620: Cypress pauses every single request in CDP/Web Extension Unnecessarily
### Current behavior

Currently in Electron, Chrome, and Firefox, Cypress pauses every single request coming from the app to determine if the frame making the request is the AUT frame. This is really only needed to happen on ResourceType document requests. We have some data to suggest that possibly not pausing on every single request entering CDP/Web extension might improve performance of general network timings in the form of reducing blocking time. 

### Desired behavior

Cypress requests should only be paused if the request being made is a document request. This scope of work does not include support for electron as an electron upgrade is needed to support web filters (see issue #26621)

Right now, our invocation of [Fetch.RequestPaused](https://vanilla.aslushnikov.com/?Fetch.requestPaused) takes in every single request from the browser. However, the method [Fetch.Enable](https://vanilla.aslushnikov.com/?Fetch.enable) takes an optional [RequestPattern](https://vanilla.aslushnikov.com/?Fetch.RequestPattern). For the use of cy.origin(), Cypress really only needs to intercept Document [resourceType](https://vanilla.aslushnikov.com/?Network.ResourceType), which should greatly reduce the amount of intercepted requests and hypothetically would reduce blocking time.

[Fetch.Enable](https://vanilla.aslushnikov.com/?Fetch.enable) is really the chromium mechanism we use to pause requests, but we leverage other methods in [Electron](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/electron.ts#L388) and [Firefox](https://github.com/cypress-io/cypress/blob/develop/packages/extension/app/background.js#L65) to accomplish the same thing. The good thing for us is that these methods, like [onBeforeSendHeaders](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforesendheadersfilter-listener) in electron, takes a [WebRequestFilter](https://www.electronjs.org/docs/latest/api/structures/web-request-filter) option, and the extension [method](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders) for Firefox also takes a [RequestFilter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders), so we should be able to implement very similar logic across our supported browsers.

### Test code to reproduce

N/A. enable browser CDP debug logs to see every inbound request in the pause handler

### Cypress Version

12.11

### Node version

v16.16.0

### Operating System

macOS 12.6

### Debug Logs

_No response_

### Other

_No response_

### LINKED ISSUE #26622: Cypress no longer needs X-Cypress-Is-XHR-Or-Fetch to determine resourceType
### What would you like?

The `X-Cypress-Is-XHR-Or-Fetch` header code in firefox, electron, and chromium based browsers can be removed as we can infer the resourceType from the browser prerequest. 

### Why is this needed?

Reduces overhead and unnecessary calculation that might be leading to performance issues. 

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #26620
- Closes #26622

### Additional details
While investigating possible network slowness within Cypress, I noticed that we might be able to optimize the number of requests that are paused by CDP, electron, and Firefox. This PR's goal is to only pause network requests when necessary in order to associate the AUT.

However, we were also using paused network requests to attempt to associate resource types when a request was made with `fetch` or `xhr`. This was pointed out to me in https://github.com/cypress-io/cypress/pull/25075, meaning we no longer need to associate this in the request via CDP, because it happens in the prerequest logic. This has been removed entirely in the request intercepting logic.

When performance benchmarking, we noticed that when `Fetch.Enabled` was disabled, network blocking time most of the time would see a significant drop. This could be possibly due to other variables, but it seems to be a factor in improving blocking time, especially for certain mimetypes. 

### Steps to test
Unit tests have been adapted, or in some cases removed as they are no longer applicable. The cookie / origin tests serve as a really great regression suite in this case to make sure a) injection is still happening when it needs to and b) cookie logic in the server is still working correctly.

The binary has also been run against our origin providers to make sure no regressions are present that are detectable 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/proxy/lib/http/request-middleware.ts [hunk 1]
```diff
@@ -23,35 +23,75 @@ const LogRequest: RequestMiddleware = function () {
   this.next()
 }
 
+const CorrelateBrowserPreRequest: RequestMiddleware = async function () {
```
Comment (AtofStryker) [inline packages/proxy/lib/http/request-middleware.ts:77]: 1:1 move to have this middleware run sooner

File: packages/proxy/lib/http/request-middleware.ts [hunk 2]
```diff
@@ -23,35 +23,75 @@ const LogRequest: RequestMiddleware = function () {
...
-    (requestIsXhrOrFetch !== 'true' && requestIsXhrOrFetch !== 'xhr' && requestIsXhrOrFetch !== 'fetch')) {
+    (this.req.resourceType !== undefined && this.req.resourceType !== 'xhr' && this.req.resourceType !== 'fetch')) {
     this.next()
 
     return
   }
 
   this.debug(`looking up credentials for ${this.req.proxiedUrl}`)
-  const { requestedWith, credentialStatus } = this.requestedWithAndCredentialManager.get(this.req.proxiedUrl, requestIsXhrOrFetch !== 'true' ? requestIsXhrOrFetch : undefined)
+  const { credentialStatus, resourceType } = this.resourceTypeAndCredentialManager.get(this.req.proxiedUrl, this.req.resourceType)
```
Comment (AtofStryker) [inline packages/proxy/lib/http/request-middleware.ts:146]: same logic, but breaks out into its own middleware and uses the resourceType calculated off the prerequest

File: packages/server/test/unit/util/resourceTypeAndCredential_spec.ts [hunk 3]
```diff
@@ -0,0 +1,86 @@
+import { expect } from 'chai'
+import { resourceTypeAndCredentialManager } from '../../../lib/util/resourceTypeAndCredentialManager'
+
+context('resourceTypeAndCredentialManager Singleton', () => {
```
Comment (AtofStryker) [inline packages/server/test/unit/util/resourceTypeAndCredential_spec.ts:4]: 1:1 rename file and changed name from `requestedWith` to `resourceType`

File: packages/proxy/lib/http/util/cookies.ts [hunk 4]
```diff
@@ -220,18 +220,20 @@ export class CookiesHelper {
     // cross site cookies cannot set lax/strict cookies in the browser for xhr/fetch requests (but ok with navigation/document requests)
     // NOTE: This is allowable in firefox as the default cookie behavior is no_restriction (none). However, this shouldn't
     // impact what is happening in the server-side cookie jar as Set-Cookie is still called and firefox will allow it to be set in the browser
-    if (this.request.requestedWith && this.siteContext === 'cross-site' && toughCookie.sameSite !== 'none') {
+    const isXhrOrFetchRequest = this.request.resourceType === 'fetch' || this.request.resourceType === 'xhr'
```
Comment (AtofStryker) [inline packages/proxy/lib/http/util/cookies.ts:224]: resourceType can now be any valid resource, so we need to check for a fetch or xhr. This is covered by the cookie e2e tests

File: packages/extension/test/integration/background_spec.js [hunk 5]
```diff
@@ -274,49 +274,6 @@ describe('app/background', () => {
   })
 
   context('add header to aut iframe requests', () => {
-    it('does not add header if it is the top frame', async function () {
```
Comment (AtofStryker) [inline packages/extension/test/integration/background_spec.js]: since we filter the type in the webrequest API vs programmatically we can no longer unit test these

File: packages/server/lib/browsers/chrome.ts [hunk 6]
```diff
@@ -403,46 +403,26 @@ const _isAUTFrame = async (frameId: string) => {
 }
 
 const _handlePausedRequests = async (client) => {
-  await client.send('Fetch.enable')
+  await client.send('Fetch.enable', {
+    // only enable request pausing for documents
+    patterns: [{
+      resourceType: 'Document',
```
Comment (AtofStryker) [inline packages/server/lib/browsers/chrome.ts]: My only concern here is about the `Other` resourceType, which seems to happen sometimes on 302 redirects. However, a following document request should almost always be made, and I don't have a current reason to believe this is a problem due to origin provider tests passing with the binary + no failing cypress tests in this repo.

File: packages/extension/test/integration/background_spec.js (hunk 5 above)
Comment (AtofStryker) [reply packages/extension/test/integration/background_spec.js]: Actually scratch that. There was a bug with this removal where we needed to check for the parent frame, which was setting the AUT url to things that were not the AUT url. This is fixed in [99964fb](https://github.com/cypress-io/cypress/pull/26623/commits/99964fbfbda50370fbe7fc111482a081f24a9e47)

File: cli/CHANGELOG.md [hunk 7]
```diff
@@ -7,6 +7,7 @@ _Released 05/09/2023 (PENDING)_
 
 - Fixed an issue in Electron where devtools gets out of sync with the DOM occasionally. Addresses [#15932](https://github.com/cypress-io/cypress/issues/15932).
 - Updated the Chromium renderer process crash message to be more terse. Addressed in [#26597](https://github.com/cypress-io/cypress/pull/26597).
+- Fixed an issue where unnecessary requests were being paused. No longer sends `X-Cypress-Is-XHR-Or-Fetch` header and infers resource off of pre-request. Fixes [#26620](https://github.com/cypress-io/cypress/issues/26620) and [#26622](https://github.com/cypress-io/cypress/issues/26622).
```
Comment (emilyrohrbough) [inline cli/CHANGELOG.md]: This is a performance improvement yes?

Comment (AtofStryker) [reply cli/CHANGELOG.md]: I would say so but not exclusively, but I think we can group it as such.

**Review by chrisbreiding — APPROVED** [review]

File: packages/proxy/lib/http/request-middleware.ts (hunk 1 above)
Comment (mjhenkes) [reply packages/proxy/lib/http/request-middleware.ts:77]: do you have to move it to make it run sooner? Couldn't you just move it up in the export list?

File: packages/proxy/lib/http/request-middleware.ts [hunk 8]
```diff
@@ -305,11 +301,12 @@ const SendRequestOutgoing: RequestMiddleware = function () {
 
 export default {
   LogRequest,
+  CorrelateBrowserPreRequest,
```
Comment (mjhenkes) [inline packages/proxy/lib/http/request-middleware.ts]: Does moving this up in the queue cause a performance impact? Since we asynchronously wait on the on CDP to send down the pre-request, this middleware will now block the following middleware while waiting on the CDP pre-request instead of allowing the other middlewares to complete.

Did that make any sense? 🤷‍♂️

Comment (AtofStryker) [reply packages/proxy/lib/http/request-middleware.ts]: It does. I don't think it causes more of a performance issue than what already exists, or at least not significantly. I could see that delay happening earlier adding a few microseconds to maybe a 2/10 of a millisecond total to the middleware. I only say that because we know the jobs that happened before the `correlateBrowserPrerequest` take microseconds usually
Screenshot 2023-05-05 at 10 48 46 AM

**Review by mjhenkes — APPROVED** [review]
