### PR TITLE
chore: Fix a couple multi-domain bugs

### LINKED ISSUE #19689: Multi-domain: Querying nested elements fails with cross-origin error
### Current behavior

Within the `switchToDomain` callback, querying nested elements causes an uncaught cross-origin error that  makes the spec hang. The error only appears in the console.
Screen Shot 2022-01-13 at 9 21 58 AM

### Test code to reproduce

```js
it('fails', () => {
    cy.visit('/fixtures/multi-domain.html')
    cy.get('a').click()

    cy.switchToDomain('foobar.com', () => {
      cy.get('form button')
    })
})
```

### Cypress Version

feature-multidomain branch

### Other

_No response_

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #19689 

### User facing changelog

N/A - going into multi-domain feature branch

### Additional details

Fixes the following issues:

- Certain command errors wouldn't propagate correctly because the stubbed runnable was missing the `isPending` method
- Querying for nested elements resulted in a cross-origin when they were checked for visibility because we try to access `parent.frameElement`, which is cross-origin when the AUT is on a secondary domain

### PR Tasks

- [x] Have tests been added/updated?
- N/A Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/e2e/multi_domain_spec.ts [hunk 1]
```diff
@@ -136,9 +147,7 @@ describe('multi-domain', { experimentalSessionSupport: true, experimentalMultiDo
           done()
         })
 
-        cy.get('[data-cy="alert"]').then(($el) => {
-          $el.trigger('click')
-        })
+        cy.get('[data-cy="alert"]').click()
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/e2e/multi_domain_spec.ts:150]: Bonus fix - looks like the nested elements bug was the underlying cause of `click` not working, which I hadn't previously punted on by using `trigger('click')` instead.

**Review by mschile — APPROVED** [review]

File: packages/driver/src/dom/coordinates.ts [hunk 2]
```diff
@@ -12,7 +12,20 @@ const isAutIframe = (win) => {
...
+
+  try {
+    // window.frameElement only exists on iframe windows, so if it doesn't
+    // exist on parent, it must be the top frame, and `win` is the AUT
+    return !$elements.getNativeProp(parent, 'frameElement')
+  } catch (err) {
+    // if the AUT is cross-domain, accessing parent.frameElement will throw
+    // a cross-origin error, meaning this is the AUT
+    return true
+    // throw err
```
[the remark this answers is not in the document]
Comment (chrisbreiding) [reply packages/driver/src/dom/coordinates.ts]: Whoops - good catch! Fixed now.

File: packages/driver/src/multi-domain/index.ts [hunk 3]
```diff
@@ -110,6 +110,7 @@ const setup = () => {
       clearTimeout () {},
       resetTimeout () {},
       timeout () {},
+      isPending () {},
```
Comment (AtofStryker) [inline packages/driver/src/multi-domain/index.ts:113]: Nice to see this here because we need it for #19691!

File: packages/driver/src/dom/coordinates.ts [hunk 4]
```diff
@@ -12,7 +12,19 @@ const isAutIframe = (win) => {
 
   // https://github.com/cypress-io/cypress/issues/6412
   // ensure the parent is a Window before checking prop
-  return $window.isWindow(parent) && !$elements.getNativeProp(parent, 'frameElement')
+  if (!$window.isWindow(parent)) {
```
Comment (AtofStryker) [inline packages/driver/src/dom/coordinates.ts:15]: Is there anyway to add a test or test this in `coordinates_spec.ts`? I feel like this might be difficult currently.

**Review by AtofStryker — APPROVED** [review]

File: packages/driver/src/dom/coordinates.ts [hunk 5]
```diff
@@ -7,12 +7,26 @@ const getElementAtPointFromViewport = (doc, x, y) => {
   return $elements.elementFromPoint(doc, x, y)
 }
 
-const isAutIframe = (win) => {
+const isAUTFrame = (win) => {
```
Comment (chrisbreiding) [inline packages/driver/src/dom/coordinates.ts:10]: Renamed to match our [other usages](https://github.com/cypress-io/cypress/blob/2e5fbad2c050b81ce75575802578c307808d61b5/packages/proxy/lib/http/response-middleware.ts#L232).

**Review by mjhenkes — APPROVED** [review]
