### PR TITLE
Properly close login modal during project setup

### LINKED ISSUE #5631: Clicking on "set up project to record" then closing "log in" modal leaves modal backdrop covering app in 3.5.0
### Current behavior:
the log in pop-up:
image

cypress.exe unresponsive and not operational:
image

### Desired behavior:

cypress.exe is fully operational after closing the "Log in" pop-up.

### Steps to reproduce: (app code and test code)

1. open cypress.exe
2. under the section "Recent Projects" , click on any recent opened project which has no runs recorded.
3. on the tabs menu, click on "Runs" tab => result: it will display a page with a title that says "You have no recorded runs"
4. click on the blue button at the bottom "Set up project to record"
5. on the Log in pop-up message ,click on the X button at the right upper corner of the message
6. observe behavior of cypress.exe

**Another scenario to reproduce:**

same as above scenario from step 1 to step 4 and then:

5. on the Log in pop-up message ,click on "Log In to Dashboard" 
6. close the browser tab that has opened
7. go back to the cypress.exe window => the "Log In" window is still open and the status shown is "Waiting for browser login ..."
8. on the Log in pop-up message ,click on the X button at the right upper corner of the message
9. observe behavior of cypress.exe

*the only way to go back to a functional cypress.exe is to close it and open it again.

**A Scenario where it does not reproduce:** 

if the "Log in" pop-up message is opened via the upper right corner icon of "Log In". 

### Versions
cypress.exe version 3.6.0
browser: chrome Version 77.0.3865.120 (Official Build) (64-bit)
OS: windows 10 enterprise x64

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes #5631 

### User facing changelog

Fixed a bug where Cypress would appear frozen after cancelling user login while in the "Runs" tab.

### Additional details

- Previously, there were 2 overlapping modals, even once the auth closed, the "setup project" was still open
- This PR makes it so that if the auth is closed without the user logging in, the "setup project" modal will never open

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/desktop-gui/cypress/integration/setup_project_modal_spec.js [hunk 1]
```diff
@@ -447,13 +447,20 @@ describe('Set Up Project', function () {
       cy.get('.modal').contains('Log In to Dashboard')
     })
 
+    it('closes login modal', () => {
+      cy.get('.modal').contains('Log In to Dashboard')
+      cy.get('.close').click()
+      cy.get('.btn').contains('Set up project').click()
```
Comment (bahmutov) [inline packages/desktop-gui/cypress/integration/setup_project_modal_spec.js]: we don't have good selectors there?

File: packages/desktop-gui/cypress/integration/setup_project_modal_spec.js [hunk 2]
```diff
@@ -447,13 +447,20 @@ describe('Set Up Project', function () {
...
+    })
+
     describe('when login succeeds', function () {
       beforeEach(function () {
         cy.stub(this.ipc, 'beginAuth').resolves(this.user)
         cy.contains('button', 'Log In to Dashboard').click()
       })
 
       it('shows setup', () => {
+        cy.get('.login-content > .btn').click()
```
Comment (bahmutov) [inline packages/desktop-gui/cypress/integration/setup_project_modal_spec.js]: why this addition?

Comment (flotwig) [reply packages/desktop-gui/cypress/integration/setup_project_modal_spec.js]: previously, this test would always pass because both dialogs are actually on screen at the same time, but the login dialog obscures the setup dialog.

with this PR, the setup dialog opens *after* the login dialog closes, so the user actually needs to click "continue" for the `<h4>` to exist in the dom.

File: packages/desktop-gui/cypress/integration/setup_project_modal_spec.js (hunk 1 above)
Comment (flotwig) [reply packages/desktop-gui/cypress/integration/setup_project_modal_spec.js]: not really, i think this is based off the other tests in this file
