### PR TITLE
fix(vite-dev-server): only re-run tests when specs deps are updated

### LINKED ISSUE #16125: vite-dev-server: Prevent re-running the test when files that are not in a test's dependency tree are modified
### Current behavior
On a vite enabled repository, cypress re-runs all tests on file changes. including files that have nothing to do with the tests (or even with the code itself)

Currently, when using Vite, the user is able to get into an infinite loop when following the basic instructions for snapshots.

### Desired behavior
Not to have cypress re-run on modified files if they are not dependencies of tests.

### Test code to reproduce
https://github.com/elevatebart/calc-vite

Clone, install and launch, then try adding a .txt file within the source folder. The tests will be re-run. edit the text file and add something in it. re-run again.

### Versions

```json 
"devDependencies": {
    "@cypress/vite-dev-server": "^1.2.2",
    "@cypress/vue": "^3.0.1",
    "@testing-library/cypress": "7.0.6",
    "@vitejs/plugin-vue": "^1.1.5",
    "@vitejs/plugin-vue-jsx": "^1.1.2",
    "@vue/compiler-sfc": "^3.0.4",
    "cypress": "^7.1.0",
    "vite": "^2.2.1"
  },
```

### PR DESCRIPTION
**Pull request by elevatebart**
- Closes #16125

### User facing changelog
Only re-runs the tests, when one of the dependency of the specs is updated, instead of every file in the project.

### Additional details
Before this PR, the active spec was re-run when any file within the project, text or not, was created, modified or deleted. This could trigger some infinite loops when creating for example snapshots or screenshots. Now cypress . Slight issue, but much better

### CODE REVIEW

**Review by Rada8732 — APPROVED** [review]

**Review by lmiller1990 — DISMISSED** [review]

**Comment by lmiller1990** [comment]
The code looks fine. I did not test it yet, so let's hold of merging until we give it a bit of a test.

**Review by lmiller1990 — COMMENTED** [review]
Let's check for:

- circular imports
- add a check to bail out of potential infinite loop
- general testing

**Comment by lmiller1990** [comment]
1. Added a test for [circular imports](https://github.com/cypress-io/cypress/pull/16215/commits/584bf8ad5040f1f7d6728e788c62f27d406059b8). Seems okay.
2. Tested it out. It's so fast for our code-bases (we don't have a huge code-base to test it on - just the demo code-base).
3. Creating/modifying a file in the `cypress/components` directory does *not* cause a re-run or update. Great!

Probably not related to this PR but I could not test with npm/design-system. Seems the project is entirely broken. I don't know when this happened. This should be failing on CI.

image

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 1]
```diff
@@ -62,11 +68,45 @@ export const makeCypressPlugin = (
...
+      while (moduleImporters && moduleImporters.size) {
+        // as soon as we find one of the specs, we trigger the re-run of tests
+        moduleImporters.forEach((mod) => {
+          if (specs.some((spec) => spec.absolute === mod.file)) {
+            debug('handleHotUpdate - compile success')
+            devServerEvents.emit('dev-server:compile:success')
+            // don't go any further if the refresh is done
+            // NOTE: we cannot do return here since we are inside of a sub-function.
+            // It would move us only one step above.
+            stopIteration = true
```
Comment (agg23) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:87]: Please use a `for...of` then, because it doesn't make sense to continue iterating through the list of importers

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 2]
```diff
@@ -62,11 +68,45 @@ export const makeCypressPlugin = (
...
+      debug('handleHotUpdate - file', file)
+      // get the graph node for the file that just got updated
+      let moduleImporters = server.moduleGraph.fileToModulesMap.get(file)
+      let stopIteration = false
+
+      // until we reached a point where the current module is imported by no other
+      while (moduleImporters && moduleImporters.size) {
+        // as soon as we find one of the specs, we trigger the re-run of tests
+        moduleImporters.forEach((mod) => {
+          if (specs.some((spec) => spec.absolute === mod.file)) {
```
Comment (agg23) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:81]: Since we keep making this check, we should use a `Set` of available paths.

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 3]
```diff
@@ -62,11 +68,45 @@ export const makeCypressPlugin = (
...
-      // restart tests when code is updated
-      devServerEvents.emit('dev-server:compile:success')
+    handleHotUpdate: ({ server, file }) => {
+      debug('handleHotUpdate - file', file)
+      // get the graph node for the file that just got updated
+      let moduleImporters = server.moduleGraph.fileToModulesMap.get(file)
+      let stopIteration = false
+
+      // until we reached a point where the current module is imported by no other
+      while (moduleImporters && moduleImporters.size) {
```
Comment (agg23) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:78]: This should probably have a max number of steps. We don't need to go through a dependency tree of 1 million for example

**Review by agg23 — CHANGES_REQUESTED** [review]

**Comment by lmiller1990** [comment]
The error in the screenshot above is also in develop. Not introduced here. I made an issue: https://github.com/cypress-io/cypress/issues/16241

**Review by agg23 — APPROVED** [review]
