### PR TITLE
fix: Fix Cypress.dom.isVisible() regression caused by "position: fixed"

### LINKED ISSUE #8998: 4.12.0 Regression: Cypress.dom.isVisible change in behaviour
We have a scrollable dropdown list and our test wants to verify how many elements are visible when opening the list: to do so we use `Cypress.dom.isVisible`

Until Cypress version 4.11.0 our test were working as expected: `Cypress.dom.isVisible` was only detecting as visible the elements of the list that were visible on screen when opening the list and as not visible the ones present in the list but for which you need to scroll down in order to see them displayed on screen.

As from Cypress version 4.12.0, when opening the dropdown list all elements in the list are detected as visible.

If this is a wanted change in behaviour, could you please advise on a workaround to have our test working? 

Here a reproduction scenario: 
https://github.com/rosahealth/cypress-tiny-test-fork

Many thanks!

### LINKED ISSUE #9031: 4.12.0 Regression: Using cypress does not display success message when using open
Hi,
While I was writing a test to verify if a message is displayed, I've noticed that cypress is behaving strangely. 
When the app form is submitted, it should display a success messsage, but on v4.12.0 does not display.
Initially, I've thought it would be the app I was testing, but when I submit the form manually it displays as expected.
Started with v5.3.0, than I've figured that until version 4.11.0 it works fine, but from 4.12.0 the issue begins.

**Cypress 4.11.0**
test-message-v4 11 0

**Cypress 4.12.0**
test-message-4 12 0

It's strange because it fails only when using `cypress open`. 
Using `cypress run` or `cypress run --browser chrome` works fine. Plus, the console displays loads of `GET` requests.

Here it's the code that reproduces the issue https://github.com/karinecord/cypress-regression-test

```
npm install
./node_modules/.bin/cypress open
```

Doing the code below the test pass:

```
npm uninstall cypress --save && npm install cypress@4.11.0 --save
./node_modules/.bin/cypress open
```

## Tecnical details
Browser:
Chrome Version 86.0.4240.75 (Official Build) (64-bit)

OS
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Node: v10.15.1

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #8998
* Closes #9031 

### User facing changelog
Fix Cypress.dom.isVisible() regression caused by "position: fixed"

### Additional details
* Why was this change necessary? => When Cypress.dom.isVisible() is used with an ancestor element with "position: fixed", it causes a regression.
* What is affected by this change? => N/A
* Any implementation details to explain? => I only check `pointer-events: none` for the element to be tested and its parent element because of the performance. Looping to the body can be bad for performance. 

### How has the user experience changed?
Regression resolved. 

### PR Tasks
* [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/cypress/integration/issues/8998_spec.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+it('t', () => {
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/issues/8998_spec.js:1]: Fixing test title to more easily track this down if it fails.

```suggestion
// https://github.com/cypress-io/cypress/issues/8998
it('issue 8998', () => {
```

**Review by jennifer-shehane — APPROVED** [review]
I manually confirmed that this fixes the original issue and it's tested in this PR.

This PR also fixes this issue: https://github.com/cypress-io/cypress/issues/9031 Not sure if you'd want to add a test around this, but it's probably the same reasoning.
