### PR TITLE
fix coords when specified x,y during click

### LINKED ISSUE #5624: click red target is at the wrong position in 3.5.0
### Current behavior:
When issuing a click on a element using the `click` command and specifying the position, for eg. `cy.get('button').click(10, 2)`, there is a red pointer that is supposed to indicate where the click was issued but it always appears at the bottom of the button:

image

Other signatures of the click command seem to show the red indicator at the correct position.

### Desired behavior:
The red indicator should be there:

image

I thought the click was happening at the wrong position before I noticed that it's actually the red indicator that's not at the correct position.

### Steps to reproduce: (app code and test code)
I created a sample app [here](https://github.com/warpdesign/cypress-click-test). First run the server with `npm run server` then open Cypress with `npm run cypress:open`, the project contains a single spec file, comparing the three call signatures of the `click` command.

The third test exhibits the problem. Also notice how when clicking on the `click` operation on the left, the red indicator moves down after the click operation but doesn't move when using `click()` without any parameter:

click-problem

### Versions
Cypress: 3.6.0
OS: macOS Catalina
Browser: Chrome 78

### PR DESCRIPTION
**Pull request by kuceb**
- there was an edge case in `coordinates.js` that did not attach x,y property to `fromAUTWindow` as of `3.5.0`
- we now attach x,y to fromAUTWindow when given offset coords

- Closes #5624 

### User facing changelog
- fixed regression(3.5.0) causing click coordinate target to be rendered incorrectly when specifying offset coordinates to `cy.click()` #5624 

### How has the user experience changed?
during `cy.click(x, y)`
- before (target out of sight, appended at bottom of document)

- after (target correctly placed)

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
Verified. The original issue fixed in the sample case that was previously failing

File: packages/driver/src/dom/coordinates.js [hunk 1]
```diff
@@ -203,23 +203,30 @@ const getBottomRightCoordinates = (rect) => {
...
 
   fromElWindow.left += x
   fromElWindow.top += y
 
+  fromAutWindow.left += x
+  fromAutWindow.top += y
+
   const viewportTargetCoords = getTopLeftCoordinates(fromElViewport)
   const windowTargetCoords = getTopLeftCoordinates(fromElWindow)
+  const AUTwindowTargetCoords = getTopLeftCoordinates(fromAutWindow)
```
Comment (brian-mann) [inline packages/driver/src/dom/coordinates.js]: this variable should really be named `autWindowTargetCoords` and not be capitalized, but ill approve anyway and fix it in develop

**Review by brian-mann — APPROVED** [review]
