### PR TITLE
fix(net-stubbing): route HTTPS traffic through net-stubbing interceptors

### LINKED ISSUE #8487: cy.route2 routes not being matched with external URLs
First of all, thanks for the work on `cy.route2`, it looks like it's going to make a lot of things much easier to do! I've jumped in to try it out and am having some trouble with URLs that are outside of my application (ie, API requests and such).

### Current behavior:
If the application sends a request to an external URL:

```
fetch('https://example.cypress.io/example-path')
```

In the tests, when `cy.route2` is used, it does not appear to be possible to match the request.

**Specifying `path`:**

```
cy.route2({ path: '/example-path', method: 'GET' }, { fixture: 'example.json' }).as('example');
```

image

**Specifying `url`:**

```
cy.route2({ url: 'https://example.cypress.io/example-path', method: 'GET' }, { fixture: 'example.json' }).as('example');
```

image

**Specifying `hostname`:**

```
cy.route2({ hostname: 'example.cypress.io', method: 'GET' }, { fixture: 'example.json' }).as('example');
```

image

**Specifying `hostname` and `path`:**

```
cy.route2({ hostname: 'example.cypress.io', path: '/example-path', method: 'GET' }, { fixture: 'example.json' }).as('example');
```

image

### Desired behavior:
The request should be matched by the routes, and stubbed accordingly.

### Test code to reproduce
https://github.com/blakemann/cypress-test-tiny

### Versions
Cypress: 5.1.0
Operating System: MacOS Catalina (10.15.6)
Browser: Chrome 85

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #8487

### User facing changelog

Fixed an issue where routes defined with `cy.route2` would not match against HTTPS requests to a different origin.

### Additional details

- only affected HTTPS requests - all HTTP requests are proxied already
- makes an attempt to optimize which HTTPS requests are proxied. some will still be transparently proxied. only potentially-interceptable connections will be proxied through the Cy proxy layer, and thus through the net-stubbing code
	- check `is-host-interceptable.ts` for implementation

### How has the user experience changed?

Users can now use `cy.route2` to spy and stub on any URL, anywhere :smile: 

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -400,6 +400,32 @@ describe('network stubbing', function () {
...
+        .wait('@foo')
+      })
+
+      // @see https://github.com/cypress-io/cypress/issues/8487
+      it('different origin (HTTPS)', function () {
+        cy.route2('/foo', 'somethin').as('foo')
+        .then(() => {
+          $.get('https://bar.foobar.com:3502/foo')
+        })
+        .wait('@foo')
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:424]: and the response is available from other HTTPS domains? Like can we confirm that we can spy on the response from https://jsonplaceholder.cypress.io/ request?

Comment (flotwig) [reply packages/driver/cypress/integration/commands/net_stubbing_spec.ts:440]: i have pushed a commit with tests for intercepting HTTPS responses, am happy to report it works as expected :)

**Review by bahmutov — APPROVED** [review]
Confirmed that it works in https://github.com/cypress-io/cypress-example-recipes/pull/570
