### PR TITLE
fix: The content of `<script>` and `<style>` inside `<body>` should be ignored with `cy.contains`.

### LINKED ISSUE #14861: cy.contains('xxx').should('not.exist') try to expect <body> not to exist in the DOM
### Current behavior
I try to test input validation by cypress
When user enter page first time, user should not see the error message
So I write test like this
`cy.contains('forgot_password_error_email_empty').should('not.exist');`
but it seems that command try to expect body not to exist in the DOM so it fails in the end

When I reproduced my problem, I found this bug is related to `next-i18n` and only occur in `next production build`
If I have translation key `test` (public/static/locales/en) `cy.contains('test').should('not.exist')` will check body exist or not

If I write cy.contains with selector `cy.contains('span', 'test').should('not.exist')`, the test will pass.
But I think this is not the good solution.

### Desired behavior
cy.contains should not check the body 

### Test code to reproduce
clone this project (https://github.com/aNyMoRe0505/next-cypress)
npm install => npm run build =>  npm run start
then npm run cypress:open to execute test
### Versions
"cypress": "^6.3.0"

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #14861

### User facing changelog

When using `cy.contains()`, the content of `<script>` and `<style>` took into account. It's fixed.

### Additional details
- Why was this change necessary? => In most cases, users don't want to search the string inside `<script>` or `<style>` tag inside the `<body>`
- What is affected by this change? => Some tests that used the workaround might fail with this change. 
- Any implementation details to explain? => When testing `body` tag, `<script>` and `<style>` tags inside it will be removed 

### How has the user experience changed?

N/A

### Notes

* I'm a bit late to the party. It should be targetted to Cypress 9.0. 
* I think we don't need option like `includeScriptContent`, `includeStyleContent`, do we?

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/querying_spec.js [hunk 1]
```diff
@@ -1573,13 +1573,13 @@ describe('src/cy/commands/querying', () => {
     it('will not find script elements', () => {
       cy.$$('<script>// some-script-content </script>').appendTo(cy.$$('body'))
 
-      cy.contains('some-script-content').should('not.match', 'script')
+      cy.contains('some-script-content').should('not.exist')
```
Comment (sainthkh) [inline packages/driver/cypress/integration/commands/querying_spec.js:1576]: This code was added at #5079. It had to be written in this way because `cy.contains()` returns `<body>` tag at that time. 

It is changed, because it simply fails.

**Comment by jennifer-shehane** [comment]
Updated base branch to 9.0-release branch

**Comment by jennifer-shehane** [comment]
Thanks @sainthkh, we're prioritizing reviewing other work for now for the immediate release but do plan to review this when we can.

**Review by chrisbreiding — APPROVED** [review]

**Comment by frabcus** [comment]
Thanks everyone for making this change, it is very much appreciated!
