### PR TITLE
3.5.0 - fix clicking into iframe after interaction with AUT

### LINKED ISSUE #5449: 3.5.0  - CypressError: Timed out retrying: Cannot read property 'defaultView' of null
When I attempt to use a `.select()` on a `<select>` object, I am getting the posted error. 

This is only the case when attempting to select something from the dropdown that DOES exist on the list. If I attempt to select a value that doesn't exist, I get the standard 

```
Cypress error "CypressError: Timed out retrying: cy.select() failed because it could not find a single <option> with value or text matching...". 
```

I have previously been using this exact test successfully, and something must have changed causing it to error out. I find that even if I comment out this portion, similar errors follow with other commands later in the test. 

This is the stack trace for the error. 

```
CypressError: Timed out retrying: Cannot read property 'defaultView' of null
    at Object.cypressErr (http://app.locals/__cypress/runner/cypress_runner.js:104836:11)
    at Object.throwErr (http://app.locals/__cypress/runner/cypress_runner.js:104791:18)
    at Object.throwErrByPath (http://app.locals/__cypress/runner/cypress_runner.js:104823:17)
    at Object.retry (http://app.locals/__cypress/runner/cypress_runner.js:96197:16)
    at retryActionability (http://app.locals/__cypress/runner/cypress_runner.js:84998:19)
From previous event:
    at tryFn (http://app.locals/__cypress/runner/cypress_runner.js:96655:21)
    at whenStable (http://app.locals/__cypress/runner/cypress_runner.js:96690:12)
    at http://app.locals/__cypress/runner/cypress_runner.js:96240:16
```

I cannot seem to find anything called `defaultView` except within jQuery itself. I have tried searching this space for an answer, but cannot seem to figure out what the deal is. 

The code that causes this error is:
```js
cy.get('#inputDoctors').select(physicianName);
```

The get is successful, and I can confirm that element exists and the value is a valid option.

### Steps to reproduce:

I believe that this error is somehow project internal, which for many reasons cannot be completely shared. However, I will create a very simple idea of what is going on:

```html
<select id="inputDoctors>
  <option value="Doctor1">apples</option>
  <option value="Doctor2">oranges</option>
  <option value="Doctor3">bananas</option>
</select>
```
```js
cy.get('#inputDoctors').select('Doctor1'); --> Fails with defaultView Error
cy.get('#inputDoctors').select('Doctor15'); --> Fails with cannot find value error
```

I understand it may be hard to help debug, but really anywhere you can point us to to start debugging this error is greatly appreciated. 

### Versions

Cypress: 3.5.0

### PR DESCRIPTION
**Pull request by kuceb**
- needed a check for `.ownerDocument` when deciding whether to send mouse leave events to an element

- Closes #5449
- [x] includes link to issue

- [x] move test into click_spec
### User facing changelog
**bug fix**: fixed issue preventing users from using `.click` or `.type` inside an iframe element.

### How has the user experience changed?
When trying to `click` or `type` into an `iframe`, the test will no longer fail with `CypressError: cannot read propery defaultView of null`

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js [hunk 1]
```diff
@@ -1646,6 +1646,23 @@ describe('src/cy/commands/actions/type', () => {
...
+        cy.$$('<iframe src="/fixtures/dom.html"/>').prependTo(cy.$$('body'))
+
+        // type into aut
+        cy.get('input:first').click()
+
+        // type into iframe
+        cy.get('iframe:first')
+        .should((iframe) => expect(iframe.contents().find('input:first')).to.exist)
+        .then((iframe) => cy.wrap(iframe.contents().find('input:first'), { log: false }))
+        .type('foo')
```
Comment (jennifer-shehane) [inline packages/driver/test/cypress/integration/commands/actions/type_spec.js]: I suppose this also tests the `click`, since type will execute a `click`? Just wondering if there needed to be a test case added to cover `click` since that's also what this is fixing.

**Review by jennifer-shehane — DISMISSED** [review]
I confirmed this fixes the issue of trying to click or type into an input within an iframe so that it no longer throws.

File: packages/driver/test/cypress/integration/commands/actions/type_spec.js (hunk 1 above)
Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/type_spec.js]: correct, but maybe I should move this test into click_spec and use click instead

Comment (Bkucera) [reply packages/driver/test/cypress/integration/commands/actions/type_spec.js]: let me do that
