### PR TITLE
fix: cy.type('{enter}') on <input> elements submits the form correctly after Firefox 98.

### LINKED ISSUE #21033: `{enter}` not working in Firefox 99 and 100
### Current behavior

When sending `{enter}`, this has no effect in Cypress 9.5.4 in Firefox 100, while it did work in Firefox 97.

This had been already reported in #20562 and has been claimed to be fixed in v9.5.4, but it seems that is not the case.

Tested with Firefox Dev 99.0b8 and 100.0b4 (probably same problem with Firefox 98 as well).

### Desired behavior

Sending `{enter}` should work as it did in Firefox 97 and older.

### Test code to reproduce

```js
describe('Hitting enter', () => {
  it('works', () => {
    cy.visit('https://www.duckduckgo.com/');
    cy.get('input#search_form_input_homepage').type('hello{enter}');
    cy.get('div#links_wrapper').should('exist');
  });
});
```

### Cypress Version

9.5.4

### Other

_No response_

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #21033

### User facing changelog

cy.type('{enter}') submits the form correctly after Firefox 98.

### Additional details
- Why was this change necessary? => `Enter` event behavior change in Firefox 98 caused `cy.type('{enter}')` to not submit the `<form>`s.
- What is affected by this change? => N/A
- Any implementation details to explain? => N/A

### How has the user experience changed?

`<form>` is submitted correctly with `cy.type('{enter}')`.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
## Note

Our CI uses Firefox 93. This PR should be tested manually.

**Comment by jennifer-shehane** [comment]
@sainthkh Thanks for looking into this again!

File: packages/driver/src/cy/commands/actions/type.ts [hunk 1]
```diff
@@ -235,7 +237,8 @@ export default function (Commands, Cypress, cy, state, config) {
         // when we send {Enter} KeyboardEvent to the input fields.
         // Because of that, we don't have to click the submit buttons.
         // Otherwise, we trigger submit events twice.
-        if (!Cypress.isBrowser('firefox')) {
+        // But after Firefox 98, submit event isn't automatically fired.
+        if (!isFirefoxBefore98 || !Cypress.isBrowser('firefox')) {
```
Comment (BlueWinds) [inline packages/driver/src/cy/commands/actions/type.ts:241]: The second part of this conditional is redundant. Three cases:
FF 98: (!true || !true) == false
FF 99: (!false || !true) == true
Chromium: (!false || !false) == true

In every case, `!Cypress.isBrowser('firefox')` has no effect on the outcome (because it's already part of the "is FF before 98" check).

**Review by BlueWinds — CHANGES_REQUESTED** [review]

**Review by tbiethman — APPROVED** [review]
Tested against local FF98, the related tests pass after changes :+1:

File: packages/driver/src/cy/commands/actions/type.ts (hunk 1 above)
Comment (sainthkh) [reply packages/driver/src/cy/commands/actions/type.ts:241]: You're right. 

`isFirefoxBefore98` is `isFirefox && version < 98`.

`!isFirefoxBefore98 || !isFirefox` is `!isFirefox || !(version < 98) || !isFirefox`. 

I fixed it.

**Review by BlueWinds — APPROVED** [review]
