### PR TITLE
fix: cy.route swallows the error about missing fixture #7818

### LINKED ISSUE #7818: cy.route swallows the error about missing fixture
### Current behavior:
When I use shortcut to load a fixture that doesn't exists

```js
cy.route("/path", "fixture:myFileWithDifferentName")
```

I get an error:

    CypressError: The following error originated from your application code, not from Cypress.
    
    When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
    
    This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    
    https://on.cypress.io/uncaught-exception-from-applicationAnd in cy logger there is info that request has been stubbed but responded with `400` HTTP code:stubMaybe related: https://github.com/cypress-io/cypress/issues/78 ?### Desired behavior:Error message should be the same as for `cy.fixture` command:```jscy.fixture("notExistingFixture");``````

Error: A fixture file could not be found at any of the following paths:

> cypress/fixtures/examplEFixture
> cypress/fixtures/examplEFixture{{extension}}

Cypress looked for these file extensions at the provided path:
.json, .js, .coffee, .html, .txt, .csv, .png, .jpg, .jpeg, .gif, .tif, .tiff, .zip

Provide a path to an existing fixture file.
```

Screen:

![fixture](https://user-images.githubusercontent.com/3865478/85800502-609ed280-b741-11ea-932d-cf82d6772574.png)

### Test code to reproduce
You can read the full story on my blog:
https://przemuh.dev/en/blog/watch-out-for-fixtures-in-cypress

App to reproduce the issue (with caseSensitive name) on Linux:
https://github.com/przemuh/cypress-fixture-case

### Versions
4.9.0



┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-114) by [Unito](https://www.unito.io/learn-more)

### LINKED ISSUE #8010: `Cannot read property '__error' of null` error thrown when providing `null.json` to `cy.fixture()`
### Current behavior:
When passing a file containing `null` content to `cy.fixture()`, an error is thrown: `Cannot read property '__error' of null`

### Desired behavior:
Should read in `null.json` file as this is valid.

### Test code to reproduce
```js
it('works when fx in route', () => {
  cy.visit('https://example.cypress.io/commands/aliasing')
  cy.server()
  cy.route('GET', 'comments/*', 'fx:null.json').as('getComment')
  cy.get('.network-btn').click()
  cy.wait('@getComment').its('status').should('eq', 200)
})

it('works with non-null json', () => {
  cy.fixture("user.json")
})

it('fails with application error', () => {
  cy.fixture("null.json")
})
```

### Versions
4.10.0 (I thought this may have been a regression, but it appears to not be).

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-131) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by przemuh**
- Closes #7818
- Closes #8010 

### User facing changelog

- cy.route throws an error when fixture cannot be found.
- In addition I've fixed the `fixture` command which raised an error for `null.json`. BTW. did you know that if the fixture contains following key in the returned object `__error` then `cy.fixture` throws an error :) ?

### Additional details

- Why was this change necessary?
To provide better error message in case of missing fixture or problem with parsing

- What is affected by this change?
`cy.route` calls `cy.fixture` if response meets criteria of fixture shortcut `fx:` | `fixture:`. With this additional check we can raise an error even before HTTP request is sent.

### How has the user experience changed?

If fixture file doesn't exists, or there is a problem with fixture, `cy.route` will raise an error.

Before:
image

Screen Shot 2020-07-17 at 1 16 51 PM

Now:
image

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/server/lib/controllers/xhrs.js [hunk 1]
```diff
@@ -69,10 +69,10 @@ module.exports = {
         .set(headers)
         .status(status)
         .end(chunk)
-      }).catch((err) => {
+      }).catch(({ message, stack, ...err }) => {
         return res
         .status(400)
-        .send({ __error: err.stack })
+        .send({ __error: { message, stack, ...err } })
```
Comment (przemuh) [inline packages/server/lib/controllers/xhrs.js:75]: I have also another solution which doesn't require a changes here in the xhr controller:

```
diff --git a/packages/driver/src/cy/commands/xhr.js b/packages/driver/src/cy/commands/xhr.js
index 7b00ed70a..4075b8a04 100644
--- a/packages/driver/src/cy/commands/xhr.js
+++ b/packages/driver/src/cy/commands/xhr.js
@@ -200,7 +200,7 @@ const startXhrServer = (cy, state, config) => {
     },
 
     onFixtureError (xhr, err) {
-      err = $errUtils.cypressErr(err)
+      err = $errUtils.cypressErr({ message: err })
 
       return this.onError(xhr, err)
     },
```

But because `__error` which becomes `err` is a string of a stack trace, there is a lot of noise in error message :/ That's why I decided to pass message and stack separately. 

Let me know which solution is better.

File: packages/driver/src/cy/commands/xhr.js [hunk 2]
```diff
@@ -471,6 +471,13 @@ module.exports = (Commands, Cypress, cy, state, config) => {
           })
         }
 
+        // look ahead to see if fixture exists
+        const fixturesRe = /^(fx:|fixture:)/
```
Comment (przemuh) [inline packages/driver/src/cy/commands/xhr.js:475]: @jennifer-shehane I am not sure about this regExp. This is a duplication from `server` package. Is there any "shared" place where I can put it and import here (in xhr command) and in server package?

File: packages/driver/src/cy/commands/xhr.js [hunk 3]
```diff
@@ -200,7 +200,7 @@ const startXhrServer = (cy, state, config) => {
     },
 
     onFixtureError (xhr, err) {
-      err = $errUtils.cypressErr(err)
+      err = $errUtils.cypressErr({ message: err })
```
Comment (przemuh) [inline packages/driver/src/cy/commands/xhr.js:203]: When there was a problem with fixture, server returns `404` with `__error` field, which contains stack-trace (string). The value was passed here, but `cypressErr` helper expects that argument will be an object with `message` field. That's why I've wrapped `err` (stack trace string) with object `{ message }`.

File: packages/driver/src/cy/commands/fixtures.js [hunk 4]
```diff
@@ -58,7 +58,7 @@ module.exports = (Commands, Cypress, cy, state, config) => {
       return Cypress.backend('get:fixture', fixture, _.pick(options, 'encoding'))
       .timeout(timeout)
       .then((response) => {
-        const err = response.__error
+        const err = response?.__error
```
Comment (przemuh) [inline packages/driver/src/cy/commands/fixtures.js:61]: For `null.json` response could be a `null` value. That's why I've added optional chaining here.

File: packages/driver/src/cy/commands/xhr.js [hunk 5]
```diff
@@ -471,6 +471,13 @@ module.exports = (Commands, Cypress, cy, state, config) => {
           })
         }
 
+        // look ahead to see if fixture exists
+        const fixturesRe = /^(fx:|fixture:)/
+
+        if (hasResponse && fixturesRe.test(options.response)) {
+          return cy.fixture(options.response.replace(fixturesRe, '')).then(() => route())
```
Comment (przemuh) [inline packages/driver/src/cy/commands/xhr.js:478]: Ok, I know this fragment makes an error in creating an alias for a route (for example in kitchen-sink example app) :( ... I need to fix it somehow.

@jennifer-shehane / @bahmutov 
Could you tell me if this kind of calling one command inside another is a good idea? Or maybe it would be better to directly call `backend` fixture?

**Comment by przemuh** [comment]
@jennifer-shehane Please check it now, it should be ok :)

The problem was in `waiting` command. After adding additional wrap with `fixutre` the name of the command is no longer `route`. That's why I've added additional check if subject of the command has a prop. To be honest I am not sure about this solution and I would be more than happy if you could double check it :)

File: packages/driver/src/cy/commands/waiting.js [hunk 6]
```diff
@@ -138,7 +138,9 @@ module.exports = (Commands, Cypress, cy, state) => {
         log.set('referencesAlias', aliases)
       }
 
-      if (command.get('name') !== 'route') {
+      const isRouteCommand = () => command.get('name') === 'route' || command.get('subject').xhrUrl
```
Comment (przemuh) [inline packages/driver/src/cy/commands/waiting.js:141]: @jennifer-shehane I am not sure about this line. Can we assume that if `xhrUrl` is present in `subject` then it is a `route` command?

I mean, this is because I've added `cy.fixture` which wraps the `route`. So, the name of the final command is `then`... parent is `fixuture` and second parent is `route`. But subject stays the same. I am just wondering if it could stay as it is or should I be more explicite and check parents:

```
const isRouteCommandWithFixtureCheck = () => {
   if (command.get('name') === 'then') {
       const parent =command.get('prev');
       const root = parent.get('prev')
       return parent.get('name') === 'fixture' && root.get('name') === 'route'
    }
}

if (command.get('name') !== 'route' && !isRouteCommandWithFixtureCheck()) {
   // raise the error
}
```

File: packages/driver/cypress/integration/commands/xhr_spec.js [hunk 7]
```diff
@@ -2122,6 +2122,18 @@ describe('src/cy/commands/xhr', () => {
         .wrap({ foo: 'bar' }).as('foo')
         .route(/foo/, '@bar')
       })
+
+      it('throws when fixture cannot be found', (done) => {
```
Comment (jennifer-shehane) [inline packages/driver/cypress/integration/commands/xhr_spec.js:2126]: Add link to original issue this test is addressing.

```suggestion

      // https://github.com/cypress-io/cypress/issues/7818
      it('throws when fixture cannot be found', (done) => {
```

File: packages/driver/src/cy/commands/xhr.js (hunk 2 above)
Comment (bahmutov) [reply packages/driver/src/cy/commands/xhr.js:475]: Not easily - since the driver code runs in the browser, and the server code runs in the Node process. Thus we are cautious about sharing code between the two packages since they can pull extra code unexpectedly

File: packages/driver/src/cy/commands/xhr.js (hunk 5 above)
Comment (bahmutov) [inline packages/driver/src/cy/commands/xhr.js:478]: please split regex replacement into its own line for clarity
```suggestion
          const fixtureName = options.response.replace(fixturesRe, '')
          return cy.fixture(fixtureName).then(() => route())
```

Comment (bahmutov) [inline packages/driver/src/cy/commands/xhr.js:478]: question here: where is the loaded fixture going? I see you load it using `cy.fixture()` but shouldn't you feed it into `route` command?

File: packages/driver/src/cy/commands/fixtures.js (hunk 4 above)
Comment (bahmutov) [reply packages/driver/src/cy/commands/fixtures.js:61]: What if the value is `false`, which is also a valid JSON value, what will happen here? I would probably make it a little simpler in my opinion and do
```js
.then((response) => {
  if (response && response.__error) {
    return $errUtils.throwErr(response.__error)
  }

  // cache stuff
})
```

File: packages/driver/src/cy/commands/waiting.js (hunk 6 above)
Comment (bahmutov) [reply packages/driver/src/cy/commands/waiting.js:140]: I am not sure, @jennifer-shehane do you know by any chance this?

File: packages/driver/src/cy/commands/xhr.js (hunk 5 above)
Comment (chrisbreiding) [reply packages/driver/src/cy/commands/xhr.js:478]: Should be `cy.now('fixture', fixtureName).then` or else it's queueing the command, not running it.

**Comment by jennifer-shehane** [comment]
Hey @przemuh, there were some requests for changes. It should be good to go after those are addressed. Do you have time to address them?

**Comment by przemuh** [comment]
Hey @jennifer-shehane. This week I am on vacations🏖 without access to my computer...I will be more than happy to address all comments but around Sunday evening CET. I hope that it will not be a problem 😅

File: packages/driver/src/cy/commands/xhr.js (hunk 5 above)
Comment (przemuh) [reply packages/driver/src/cy/commands/xhr.js:478]: My first though was that, this fragment should only try to load a fixture and throw error if necessary. The second though was that, after sucessfull load the fixture data could be assigned as options.response. I am not sure, but with the second option the code on server side (mocking requests xhr) could be deleted, because all fixtures will be loaded here (in route command).

I wasn't sure if this approach is ok with the big picture of cypress architecture.

Please correct me/guide me if I am wrong :)

File: packages/driver/src/cy/commands/waiting.js (hunk 6 above)
Comment (przemuh) [reply packages/driver/src/cy/commands/waiting.js:140]: Ok, with `cy.now` this is not longer a problem :)

File: packages/driver/src/cy/commands/xhr.js (hunk 5 above)
Comment (przemuh) [reply packages/driver/src/cy/commands/xhr.js:478]: Done, thanks :)

File: packages/driver/src/cy/commands/fixtures.js (hunk 4 above)
Comment (przemuh) [reply packages/driver/src/cy/commands/fixtures.js:61]: For `false` value it will works as expected. 

`const err = response?.__error` is a shortcut for `response && response.__error` but I agree that your proposal is more clear and simpler :) 

Changed 👍

File: packages/driver/src/cy/commands/xhr.js (hunk 5 above)
Comment (przemuh) [reply packages/driver/src/cy/commands/xhr.js]: @bahmutov I've checked if I could use loaded fixture data. I can, but only for "truthy" values. cypress server will not stub a request when `option.response` is falsy.

Moreover, I've checked the case with `false.json` file and it is failing because of the:

```
        // when data is null, JSON.stringify returns null.
        // handle that case.
        if (data === null) {
          data = ''
        }

        const chunk = Buffer.from(data, encoding)
```

I am just wondering, why cypress returns an empty string if someone wanted to stub the network request and expects the `null` value. If it is for a reason it should be also extended with `data === false` check < without it, users cannot stub a network request with `false` as a content of json file.

I think we could leave the current solution as it is, and try to address `false/null` problems in separate ticket/MR.

What do you think?

**Comment by jennifer-shehane** [comment]
I've identified that this PR introduced a regression - where the fixture files take longer to load, especially at large fixture file sizes, sometimes timing out. Detailed here: https://github.com/cypress-io/cypress/issues/8181

**Comment by przemuh** [comment]
@jennifer-shehane I am really sorry about that :( I hope you will forgive me ;) 

Here is a pull request with fix/revert: https://github.com/cypress-io/cypress/pull/8215
