### PR TITLE
fix(cy.intercept): allow fixtures to define null encoding when used in static response

### LINKED ISSUE #19330: Issue with MP4 fixtures when intercepting with Cypress 9.1.1
### Current behavior

Cypress 9 does not intercept with mp4 fixtures correctly. The MP4 does not load when loaded via either the `<video>` tag or directly in the browser.

### Desired behavior

The MP4 should be mocked correctly by cypress and the video should autoplay. The test should pass.

### Test code to reproduce

This repo demonstrates the issue, it's setup with cypress 9.1.1 by default in which the test will fail.

https://github.com/ldabiralai/cypress-mp4-bug

### Cypress Version

9.1.1

### Other

_No response_

### LINKED ISSUE #19344: Reading a binary fixture get it's content changed
### Current behavior

In the process of updating from `cypress@8` to `cypress@9`, It was noticed that intercepting a binary file had changed, making the intercepted file to be corrupted (not in the expected format).

Here's a screenshot of the update and the files diffing
Screenshot 2021-12-13 at 11 19 09

### Desired behavior

When reading a binary fixture the content of it shouldn't be changed when serving it (via `cy.intercept`)

### Test code to reproduce

https://github.com/andrealmieda/react-cypress-boilerplate

I created a small test to download the intercepted binary file and then manually check it on the terminal 

### Cypress Version

9.1.1

### Other

_No response_

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- Closes #19330
- Closes #19344

This issue was introduced in Cypress 9.0.0. by #18534 which made changes such that

- when null is passed as the encoding to `cy.readFile()` or `cy.fixture()`, the file is treated as binary and read as a Buffer.
- when null passed as the encoding to `cy.writeFile()` allows direct writing of buffers.
- If the encoding is unspecified, the default remains ‘utf8’, matching the current behavior.

Before this changes, when a fixture path was specified in cy.intercept() without an encoding value, the encoding would assume to be null and the file extension would be used to determine the encoding type and eventually fallback be read a a Buffer.

#18534 unintentionally introduced a non-passive change such that when a fixture path was specified in cy.intercept() without an encoding value it would use the default `utf8` encoding option (instead of null). This change aligned the default encoding behavior to `cy.readFile()` and `cy.fixture()`. The miss was documenting this change as breaking and allowing a null string to be processed by cy.intercept() to allow the fixture to be read a Buffer.

### User facing changelog

Fixed a regression in [9.0.0](https://docs.cypress.io/guides/references/changelog#9-0-0) where a fixture provided in a static response to `cy.intercept()` did not support passing null to encoding to read the fixture as a Buffer. This identified  the undocumented 9.0.0 Breaking Change where the default read behavior of a fixture changed from a Buffer to being read with `utf8` encoding.

### Additional details

This change moves forward with the un-intentional non-passive change to keep the default behavior of `cy.intercept()`, `cy.readFile()` and `cy.fixture()` aligned. 

The Breaking Changes section of the 9.0.0 changelog will need to be updated with a note to this change of the new behavior.

### How has the user experience changed?

```diff
  it("should be able to mock an mp4", () => {
-    cy.intercept("video.mp4", { fixture: "video.mp4" }); // before 9.0.0 release
+    cy.intercept("video.mp4", { fixture: "video.mp4,null" });  // after 9.0.0 release

    cy.visit("http://localhost:3000/");

    cy.get("video").should("have.prop", "paused", false)
  });
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ x Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4278
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by mjhenkes — DISMISSED** [review]

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -1319,6 +1319,61 @@ describe('network stubbing', function () {
         cy.contains('#result', '""').should('be.visible')
       })
 
+      // @see https://github.com/cypress-io/cypress/issues/8623
+      // @see https://github.com/cypress-io/cypress/issues/8623
```
Comment (BlueWinds) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1323]: Duplicate comment

**Review by BlueWinds — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Review by BlueWinds — APPROVED** [review]
