### PR TITLE
fix: use util.getEnv to handle environment variables set with npm

### LINKED ISSUE #19559: CYPRESS_VERIFY_TIMEOUT ignored when passed via .npmrc
### Current behavior

When setting `CYPRESS_VERIFY_TIMEOUT` in `.npmrc` it is currently ignored and `VERIFY_TEST_RUNNER_TIMEOUT_MS` falls back to the default value.

### Desired behavior

`CYPRESS_VERIFY_TIMEOUT` can also be set in `.npmrc` and is picked up in `verify.js`

### Test code to reproduce

In `.npmrc` use:
```
CYPRESS_VERIFY_TIMEOUT=100000
```

### Cypress Version

9.2.0

### Other

@tbiethman, @emilyrohrbough: Sorry for the string to integer issue and thanks for the quick fix!
I just tested the new version today and realized the problem myself :man_facepalming: 

This issue here would improve the usability and handle this environment variable like I've seen in other parts in the code.

I will open another PR that will only change this line in verify.js:
```
const VERIFY_TEST_RUNNER_TIMEOUT_MS = parseInt(util.getEnv('CYPRESS_VERIFY_TIMEOUT')) || 30000;
```

Thanks for your effort and I would be happy if you could review the new pull-request :pray:

### PR DESCRIPTION
**Pull request by legap**
- Closes #19559

### User facing changelog
- CYPRESS_VERIFY_TIMEOUT can also be set in `package.json` and `.npmrc` (depending on os)

### Additional details
This change allows the CYPRESS_VERIFY_TIMEOUT environment variable to be set via `.npmrc` file or as config in `package.json`. The test cases were also updated to verify this case.

### How has the user experience changed?
Users can set `CYPRESS_VERIFY_TIMEOUT` the same way as the other [environment variables](https://docs.cypress.io/guides/getting-started/installing-cypress#Environment-variables) (config in `package.json` and `.npmrc` with some restrictions).

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: cli/lib/tasks/verify.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ const logger = require('../logger')
 const xvfb = require('../exec/xvfb')
 const state = require('./state')
 
-const VERIFY_TEST_RUNNER_TIMEOUT_MS = +process.env.CYPRESS_VERIFY_TIMEOUT || 30000
+const VERIFY_TEST_RUNNER_TIMEOUT_MS = +util.getEnv('CYPRESS_VERIFY_TIMEOUT') || 30000
```
Comment (emilyrohrbough) [inline cli/lib/tasks/verify.js:18]: Testing this locally, I'm noticing the capitalization makes a difference on the resolved value when testing with a simple dummy script. 

```package.json
"scripts": {
   "try": "node ./try.js"
}
```

```js
// try.js
const util = require('./cli/lib/util')

console.log(process.env)
console.log(' process.env -.CYPRESS_VERIFY_TIMEOUT', process.env.CYPRESS_VERIFY_TIMEOUT)
console.log('process.env.cypress_verify_timeout -', process.env.cypress_verify_timeout)
console.log('util.getEnv('CYPRESS_VERIFY_TIMEOUT') - ', util.getEnv('CYPRESS_VERIFY_TIMEOUT'))
console.log('util.getEnv('cypress_verify_timeout') -', util.getEnv('cypress_verify_timeout'))
```

.npmrc
```.npmrc
CYPRESS_VERIFY_TIMEOUT=yes
```

Terminal
```bash
> CYPRESS_VERIFY_TIMEOUT='no' npm run try
process.env - {
   ...
  npm_config_cypress_verify_timeout: 'yes',
  CYPRESS_VERIFY_TIMEOUT: 'no',
  ...
}
process.env.CYPRESS_VERIFY_TIMEOUT - no
process.env.cypress_verify_timeout - undefined
util.getEnv('CYPRESS_VERIFY_TIMEOUT') -  no
util.getEnv('cypress_verify_timeout') - yes
```

Comment (legap) [reply cli/lib/tasks/verify.js:18]: Thanks for the review and the testing @emilyrohrbough.

I had to dig a little deeper to understand how npm handles environment variables. The results are available in [this README](https://github.com/legap/npm-env-variable-examples/blob/main/README.md) in a small test project.

As a conclusion we can see, that npm itself handles the key of an environment variable different, depending on the operating system (I didn't have an OSX available but I would guess it behaves the same as linux).

I also looked up all calls to the `getEnv` method in the cypress codebase and had a look at the tests in [util_spec.js](https://github.com/legap/cypress/blob/develop/cli/test/lib/util_spec.js) and they are always with uppercase keys.

So in my opinion `getEnv` should work on all operating systems when using the key in uppercase and the benefit would be that we can also use the definition for `CYPRESS_VERIFY_TIMEOUT` in `package.json` or `.npmrc`.

Comment (emilyrohrbough) [reply cli/lib/tasks/verify.js:18]: @legap WOW! You led a very thorough investigation into these differences. I truly appreciate it & this is great information.

You conclusions regarding Mac OS seems correct (I have a Mac). With your findings it appears this accomplishes the intent of how `CYPRESS_VERIFY_TIMEOUT` will be used and accessed for this timeout.

**Review by emilyrohrbough — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
