### PR TITLE
Use is-html as a fallback to check if `cy.visit()` response is HTML

### LINKED ISSUE #1727: Cypress says Content-type is null but it is not
### Current behavior: 

When trying to access my application I am getting the error:

Error:     CypressError: cy.visit() failed trying to load:

http://site.com.au/applications/

The content-type of the response we received from your web server was:

  > null

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

cy.request() will automatically get and set cookies and enable you to parse responses.

screen shot 2018-05-17 at 3 38 58 pm

After making a cy.request after you can see that the page does not send null content-type. I've also checked the response and it's valid html that is being sent.

### Desired behavior:

Cypress renders the application and is able to test it. I have included a screenshot of the debugging console messages. Any help would be much appreciated.

Happy to make changes to the application under test, however I can't find anywhere where the content-type is null.

curling the headers of the URL gets this:
HTTP/1.1 200 OK
Date: Thu, 17 May 2018 06:21:57 GMT
Connection: keep-alive

### Steps to reproduce:

```js

```

### Versions  
 Latest

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #1727 by attempting to check if the response body is HTML-like using `is-html` if the content-type header is not set.

### CODE REVIEW

**Comment by mohammedroni4** [comment]
Next updated snapshot.
Screen Shot 2019-05-28 at 11 24 23 AM

File: packages/server/lib/server.coffee [hunk 1]
```diff
@@ -34,6 +36,15 @@ fileServer   = require("./file_server")
 DEFAULT_DOMAIN_NAME    = "localhost"
 fullyQualifiedRe       = /^https?:\/\//
 
+isResponseHtml = (contentType, responseBuffer) ->
+  if contentType
```
Comment (brian-mann) [inline packages/server/lib/server.coffee]: we probably want to be even more lax than this...

```coffee
if contentType is "text/html"
  return true

## else try to figure out if the body is HTML...
if body = _.invoke(responseBuffer, 'toString')
  return isHtml(body)

return false
```

You can add a test by sending something like `text/plain` as a `content-type` and I believe this will still pass.

Why do it this way? Because it likely better matches what the browser does. Check to see what happens if you send the **wrong** content-type but still serve `html`. My guess is the browser parses and renders the `html` correctly. If I'm wrong avoid this whole comment.

Comment (flotwig) [reply packages/server/lib/server.coffee]: I tried sending an HTML body with `text/plain` content-type, Chrome rendered it as plain text:

image

So this looks like it matches the behavior of Chrome.
