### PR TITLE
fix: don't show EPIPE error

### LINKED ISSUE #30659: Error: write EPIPE after CTRL+C in terminal
### Current behavior

image
sometimes after CTRL+C 'ing after `npx cypress run` on Windows (both Command Prompt and Powershell) and Linux (bash tested)

### Desired behavior

_No response_

### Test code to reproduce

very hard to reproduce with one example

### Cypress Version

13.15.1 and above versions

### Node version

v20.18.0

### Operating System

Windows 10 19045

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by alexsch01**
- Continuation of https://github.com/cypress-io/cypress/pull/32821
- Closes https://github.com/cypress-io/cypress/issues/30659

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

---

> [!NOTE]
> Suppress EPIPE errors from the config child process during load/setup, add a unit test, and note the fix in the changelog.
> 
> - **Runtime (data-context)**:
>   - `packages/data-context/src/data/ProjectConfigIpc.ts`
>     - Handle `EPIPE` in `_childProcess.on('error')` within `loadConfig()` and `registerSetupIpcHandlers()` by logging via `debug`, resolving the pending promise, and returning early.
>     - Type narrow error handler to `NodeJS.ErrnoException`.
> - **Tests**:
>   - Add `packages/data-context/test/unit/data/ProjectConfigIpc-real-child-process.spec.ts` to simulate `EPIPE` and assert debug messages for both code paths.
> - **Changelog**:
>   - Update `cli/CHANGELOG.md` (`15.8.0` Bugfixes) to document the EPIPE terminal error fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 47d8cb5f3a6f1b9589d3da7121e5a8f4073697c3. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alexsch01** [comment]
The failures appear to be unrelated to the PR

**Comment by jennifer-shehane** [comment]
@alexsch01 Thanks, we'll review when we have time and also make sure tests pass and merge.

**Comment by alexsch01** [comment]
The readme change entry is in the wrong spot but I'm not going to fix it until all potential checks are complete

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 1]
```diff
@@ -229,7 +233,11 @@ export class ProjectConfigIpc extends EventEmitter {
     return new Promise((resolve, reject) => {
       let resolved = false
 
-      this._childProcess.on('error', (err) => {
+      this._childProcess.on('error', (err: NodeJS.ErrnoException) => {
+        if (err.code === 'EPIPE') {
+          return
```
Comment (AtofStryker) [inline packages/data-context/src/data/ProjectConfigIpc.ts:248]: are you able to add a `debug` statement here that prints the error before we return?

**Review by AtofStryker — CHANGES_REQUESTED** [review]
I'm not sure we would want to block all broken pipe errors coming back from the process but I can't think of a reason as to what specifically. So I'm OK moving forward with the change. @cacieprins cam you think of a scenario where this would be problematic?

@alexsch01 are you able to add a unit test to https://github.com/cypress-io/cypress/blob/develop/packages/data-context/test/unit/data/ProjectConfigIpc.spec.ts

File: packages/data-context/src/data/ProjectConfigIpc.ts (hunk 1 above)
Comment (alexsch01) [reply packages/data-context/src/data/ProjectConfigIpc.ts:248]: done

**Comment by alexsch01** [comment]
> @alexsch01 are you able to add a unit test to https://github.com/cypress-io/cypress/blob/develop/packages/data-context/test/unit/data/ProjectConfigIpc.spec.ts

Since the original issue happens sporadically when doing CTRL+C, it's tricky to test this

**Comment by AtofStryker** [comment]
> > @alexsch01 are you able to add a unit test to https://github.com/cypress-io/cypress/blob/develop/packages/data-context/test/unit/data/ProjectConfigIpc.spec.ts
> 
> Since the original issue happens sporadically when doing CTRL+C, it's tricky to test this

@alexsch01 I'm more so talking about a unit test that emits and error to a mock child process and verifies the reject handler isn't called. I can take a look in setting that up if you'd like if that seems a bit challenging to do.

**Comment by alexsch01** [comment]
@AtofStryker done

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 2]
```diff
@@ -157,7 +157,13 @@ export class ProjectConfigIpc extends EventEmitter {
 
       let resolved = false
 
-      this._childProcess.on('error', (err) => {
+      this._childProcess.on('error', (err: NodeJS.ErrnoException) => {
+        if (err.code === 'EPIPE') {
+          debug('EPIPE error in loadConfig() of child process %s', err)
+
```
Comment (AtofStryker) [inline packages/data-context/src/data/ProjectConfigIpc.ts:163]: @alexsch01 I wonder if we just want to `resolve()` this before returning just to prevent a possible memory leak (even though the process _should_ be killed)
```suggestion
resolve()
```

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 3]
```diff
@@ -229,7 +235,13 @@ export class ProjectConfigIpc extends EventEmitter {
     return new Promise((resolve, reject) => {
       let resolved = false
 
-      this._childProcess.on('error', (err) => {
+      this._childProcess.on('error', (err: NodeJS.ErrnoException) => {
+        if (err.code === 'EPIPE') {
+          debug('EPIPE error in registerSetupIpcHandlers() of child process %s', err)
+
```
Comment (AtofStryker) [inline packages/data-context/src/data/ProjectConfigIpc.ts:244]: likely the same deal here as mentioned above

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 4]
```diff
@@ -157,7 +157,15 @@ export class ProjectConfigIpc extends EventEmitter {
...
 
-      this._childProcess.on('error', (err) => {
+      this._childProcess.on('error', (err: NodeJS.ErrnoException) => {
+        if (err.code === 'EPIPE') {
+          debug('EPIPE error in loadConfig() of child process %s', err)
+
+          resolve()
+
+          return
+        }
```
[the remark this answers is not in the document]
Comment (AtofStryker) [reply packages/data-context/src/data/ProjectConfigIpc.ts:168]: @cursoragent this should be unreachable

**Comment by AtofStryker** [comment]
@alexsch01 looks like there is a test failure? https://app.circleci.com/pipelines/github/cypress-io/cypress/77256/workflows/d625d494-edf6-4c36-9c39-2ac19b8f6d40/jobs/3309659

Screenshot 2025-11-20 at 1 29 19 PM

**Comment by alexsch01** [comment]
@AtofStryker addressed

File: packages/data-context/src/data/ProjectConfigIpc.ts [hunk 5]
```diff
@@ -229,7 +237,15 @@ export class ProjectConfigIpc extends EventEmitter {
...
 
-      this._childProcess.on('error', (err) => {
+      this._childProcess.on('error', (err: NodeJS.ErrnoException) => {
+        if (err.code === 'EPIPE') {
+          debug('EPIPE error in registerSetupIpcHandlers() of child process %s', err)
+
+          resolve()
+
+          return
+        }
```
[the remark this answers is not in the document]
Comment (AtofStryker) [reply packages/data-context/src/data/ProjectConfigIpc.ts:249]: the ipc main process is dead so I don't actually see this being a problem

[the remark this answers is not in the document]
Comment (AtofStryker) [reply packages/data-context/src/data/ProjectConfigIpc.ts:249]: process is dead

**Review by AtofStryker — APPROVED** [review]

**Comment by AtofStryker** [comment]
Screenshot 2025-12-04 at 11 33 21 AM
This test is failing on this branch but it appears to be flaky. I also verified that the changes here are not impacting the results of the test, so I am going to merge this in.
