### PR TITLE
fix: Revert cypress.json changes

### LINKED ISSUE #15497: When creating new project on Dashboard - projectId and extra config is created in cypress.json file which is invalid
### Current behavior

Introduced in 6.7.0, when you connect a project to the Dashboard - the `cypress.json` created is this gigantic config object. 

Screen Shot 2021-03-15 at 3 22 39 PM

### Test code to reproduce

- `cypress open`
- Click on 'Runs' tab
- Click 'Connect to Dashboard'
- Finish project creation
- Check `cypress.json` file

### Versions

6.7.0

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #15497

### User facing changelog

- Cypress no longer write extra config values to `cypress.json` when adding the project ID

### Additional details

This was caused by a combination of using `require` to obtain the contents of `cypress.json` and mutating the config object itself. Since node caches required modules, it mutated the in-memory cache of the `cypress.json`, so subsequent 'reads' had the mutated content with extra values, which then got written back to the file when writing the project ID.

This reverts PRs #15444 and #15263.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/config.js [hunk 1]
```diff
@@ -209,8 +209,8 @@ module.exports = {
       return this.set({
         projectName: this.getNameFromRoot(projectRoot),
         projectRoot,
-        config: settings,
-        envFile,
+        config: _.cloneDeep(settings),
+        envFile: _.cloneDeep(envFile),
```
Comment (chrisbreiding) [inline packages/server/lib/config.js:213]: The only code changes besides the reverting.

File: packages/server/test/unit/config_spec.js [hunk 2]
```diff
@@ -81,6 +80,19 @@ describe('lib/config', () => {
...
+
+      this.setup(settings, envSettings)
+
+      return config.get(this.projectRoot)
+      .then(() => {
+        expect(settings).to.deep.equal({ foo: 'bar' })
+        expect(envSettings).to.deep.equal({ baz: 'qux' })
+      })
+    })
+
```
Comment (chrisbreiding) [inline packages/server/test/unit/config_spec.js:95]: New test to make sure cypress settings don't get mutated.

**Comment by Bkucera** [comment]
nice. @chrisbreiding do you think we should squash+rebase this into three commits (two reverts, one bugfix) and do a merge commit? it would be nice to have the explicit revert commits in develop

**Review by Bkucera — DISMISSED** [review]
