### PR TITLE
Fix bug when taking screenshot of an element that changes size on scroll

### LINKED ISSUE #6099: Calling screenshot() on an element that changes sizes after scrolling throws 'is invalid for option "size"' exception
### Current behavior:
Using the screenshot command on an element that changes sizes after scrolling causes an exception to be thrown when trying to stitch them together.

```
RangeError: The value "-36960000" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:272:3)
    at Jimp.cropQuiet (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:42:27)
    at Jimp.<computed> [as crop] (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1266:23)
    at crop (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:145:26)
    at Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:209:22
    at arrayEach (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9342:14)
    at stitchScreenshots (Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:206:7)
    at Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:350:21
    at processImmediate (internal/timers.js:439:21)
```

### Desired behavior:

The screenshot command should properly create an image instead of throwing an exception.

### Steps to reproduce:
See: https://github.com/Keysox/cypress-screenshot-issue

### Versions
Cypress: 3.8.1

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-59) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #6099 

### User facing changelog

- Fixes an issue where taking a screenshot of an element that changes height on scroll would throw an error

### Additional details

I tried to find a solution to take the screenshot without triggering the `scroll` event, but I was unable to find something working that also achieved that. This PR will take a screenshot of the state after the animation triggered by the scroll event is complete (like all other animations during screenshots).

### How has the user experience changed?

Using the following test case:

```html
<html>
<body>
<main style="background: linear-gradient(yellow, blue); height: 250vh; transition: 10s;"></main>
<script>
  window.addEventListener('scroll', () => {
    const main = document.getElementsByTagName('main')[0]
    main.style.height = "50vh";
  })
</script>
</body>
</html>
```

```javascript
it('can screenshot when element height changes on scroll', () => {
  cy.visit('fixtures/index.html')
  cy.get('main').screenshot()
})
```

Before (no screenshot produced):

Screen Shot 2020-07-13 at 10 32 44 PM

After (produced screenshot):

can screenshot when element height changes on scroll

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
I confirmed this manually fixes the throwing of the invalid option size exception. 

You mention that the animated scroll happens before the screenshot, but I don't actually see the scroll take effect over time, with the 10 second transition. Is this expected? Because this changes the behavior of the application under test - if the scroll is just instant. 

I'm also thinking that the scroll shouldn't happen at all in this case? They're opening the window to take a screenshot at 350v height, nothing in the test told the AUT to scroll, so why would the screenshot be taken of the element after a scroll event?

In this case, I would expect the screenshot to be:

screenshot element (10)

But the actual screenshot taken is the 50vh, after a scroll has happened, but the test never told it to scroll. 

screenshot element (12)


Also there's this weird effect after the screenshot where something is still slightly scrolling that I don't understand. 



**Overall, I'm thinking this is still an improvement from the original error exception, so if these other issues are outside the scope of this, perhaps they should be moved to a new issue and still push this out.** Let me know what you think.

**Comment by jennifer-shehane** [comment]
@panzarino The exact same test is failing on every browser here. 🤔 I don't see this failure in other `develop` branches.

**Comment by panzarino** [comment]
@jennifer-shehane The animation is supposed to be instant, before every screenshot we [ensure that all animations complete instantly](https://github.com/cypress-io/cypress/blob/develop/packages/runner/src/lib/dom.js#L390). This is what is controlled by the `disableTimersAndAnimations` option.

Ideally, there is no scroll at all. Currently, the screenshot code relies on scrolling down the screen to take screenshots. There is no way to prevent the `scroll` event from being triggered when we call `scrollTo` or to remove, scroll, and then reset any listeners. I tried a solution which would keep the height fixed even when the event was triggered, but that wouldn't stop any other changes triggered by the event. The other possible solution is rather than moving the viewport down the page by scrolling, the page can move up in the viewport by modifying the `top`/`marginTop` of the body or something like that. Either way, that's a big change to how the screenshot currently functions and I think we should just get out this fix before discussing something like that. Ping @chrisbreiding for input here.

As far as the slightly scrolling goes, I think that happens because of a slight viewport change between the screenshot viewport and the viewport within the runner. Since the height units are in `vh`, which is calculated, the actual `px` value will change and animate over the `10s` defined as the animation duration.

I can fix tests once we decide that this is the solution we want (as opposed to one without scrolling at all).

File: packages/driver/src/cy/commands/screenshot.js [hunk 1]
```diff
@@ -347,6 +347,10 @@ const takeScreenshot = (Cypress, state, screenshotConfig, options = {}) => {
 
   return before()
   .then(() => {
+    const win = state('window')
+
+    win.dispatchEvent(new CustomEvent('scroll'))
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/screenshot.js:352]: Can you add a code comment here above this line referencing the issue and also describe (in the code comment) _why_ this is necessary / how it fixes the issue? I still don't understand that myself and a future developer won't either.

**Comment by panzarino** [comment]
I've pushed some commits to this branch but they aren't coming up here, will push some blank commits later once GitHub services are restored.

File: packages/driver/src/cy/commands/screenshot.js [hunk 2]
```diff
@@ -347,6 +347,16 @@ const takeScreenshot = (Cypress, state, screenshotConfig, options = {}) => {
...
   .then(() => {
+    const win = state('window')
+
+    // in the case that an element might change size on scroll
+    // we trigger a scroll event to ensure that all elements are
+    // at their final size before we calculate the total height
+    // since we scroll down the page in takeScrollingScreenshots
+    // and don't want the page size to change once we start
+    // https://github.com/cypress-io/cypress/issues/6099
+    win.dispatchEvent(new CustomEvent('scroll'))
```
Comment (chrisbreiding) [inline packages/driver/src/cy/commands/screenshot.js:358]:
```suggestion
    win.dispatchEvent(new win.CustomEvent('scroll'))
```

This might fix the cross-origin error that's failing the e2e tests.

**Review by chrisbreiding — DISMISSED** [review]

**Comment by chrisbreiding** [comment]
I think this is an alright solution for the time being. It may not be ideal, but it's an improvement over the previous behavior. We can always revisit if necessary.

Just need to fix the failing tests and this should be good to go.

**Review by jennifer-shehane — APPROVED** [review]
