### PR TITLE
fix(typedefs): Cypress.Commands.add can return Promises.

### LINKED ISSUE #7807: Type 'Promise<any>' is not assignable to type 'CanReturnChainable' in Cypress
### Current behavior:
Having updated from Cypress 4.8, TypeScript will now not compile my support code. #435 was not insightful. 

### Desired behavior:
Compile my TypeScript. Either I'm doing something wrong or there is a bug.

### Test code to reproduce
```ts
Cypress.Commands.overwrite(command, (originalFn, ...args) => {
  const origVal = originalFn(...args);
  return new Promise(resolve => {
    setTimeout(() => resolve(origVal), 1000);
  });
});
```
It fails similarly with `Cypress.Promise` as well. I'd like to avoid `cy.wrap()` unless necessary.

### Versions
Cypress 4.9.0
macOS 10.15.5
Chrome 83

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7807

### User facing changelog

`Cypress.Commands.add` could only return `void` or `Chainable`. Now, `Promise` is added to the list.

### Additional details

- Why was this change necessary? TypeScript throws an error for valid code.
- What is affected by this change? N/A
- Any implementation details to explain? N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by Bkucera** [comment]
Any idea what commit caused this regression?

**Comment by sainthkh** [comment]
@BKucera It's #7547. I wrote this line to fix #7510 and I missed the obvious `Promise`.

**Review by Bkucera — APPROVED** [review]

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -518,7 +518,7 @@ declare namespace Cypress {
     off: Actions
   }
 
-  type CanReturnChainable = void | Chainable
+  type CanReturnChainable = void | Chainable | Promise<unknown>
```
Comment (sinharaksh1t) [inline cli/types/cypress.d.ts:521]: I know this PR is already merged, but I had a question on this. There are some commands that are failing for me as well on Cypress v5.1.0. And I came across this PR as the fix for a similar issue that I was facing. The problem resolves for me if I do the following in my local `cypress.d.ts` file:
```typescript
  type CanReturnChainable = void | Chainable | boolean | string | number | string[] | undefined
```
Please let me know if this seems to be the correct solution and if I should open a PR for this? :)
Thank you in advance for your response!
cc: @sainthkh @Bkucera 

The code snippet that's causing this type error:
```typescript
/** Get the value of a DataTable date filter */
Cypress.Commands.add(
  'getDateValue',
  { prevSubject: 'element' },
  ($filter: JQuery<HTMLElement>) => {
    const input = $filter.find(DATE_FILTER_INPUT_SELECTOR);
    return input.val();
  },
);
```

Comment (sainthkh) [reply cli/types/cypress.d.ts:521]: Is it used like below?

```js
const x = cy.getDateValue();
```

Comment (sinharaksh1t) [reply cli/types/cypress.d.ts:521]: Something similar, it is used as
```typescript
cy.getDateFilter('Min Due Date')
  .toggleEnabled()
  .setDateValue(minDueDate);
```

Comment (sainthkh) [reply cli/types/cypress.d.ts:521]: Conventionally, Cypress commands return `thenable` objects. But in your case, `boolean | string | number | string[] | undefined` are not `thenable`. Because of that, I cannot tell you for sure that they are OK.

@BKucera. Is it OK to return non-`thenable`s?

Comment (sinharaksh1t) [reply cli/types/cypress.d.ts:521]: I see! Thank you! I appreciate your response. I'll wait for @Bkucera 's response on this thread to see what he says.
