### PR TITLE
fix: add the type definition for cy.writeFile with 4 arguments.

### LINKED ISSUE #15353: cy.writeFile type does not have 4 argument version
Cypress v6.6.0
`cy.writeFile` type signature does not allow 4 options, which works at runtime

Screen Shot 2021-03-06 at 9 04 26 AM

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #15353

### User facing changelog

Add the type definition for `cy.writeFile` with 4 arguments. 

### Additional details
- Why was this change necessary? => 4 argument definition is valid, but it doesn't exist. 
- What is affected by this change? => N/A
- Any implementation details to explain? => N/A

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by sainthkh** [comment]
flaky failures.

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -2138,6 +2138,22 @@ declare namespace Cypress {
     ```
      */
     writeFile<C extends FileContents>(filePath: string, contents: C, options?: Partial<WriteFileOptions>): Chainable<C>
+    /**
+     * Write to a file with the specified encoding and contents.
+     *
+     * The `encoding` option in `options` precedes the `encoding` argument.
```
Comment (jennifer-shehane) [inline cli/types/cypress.d.ts:2144]:
```suggestion
     * An `encoding` option in `options` will override the `encoding` argument.
```

File: cli/types/cypress.d.ts [hunk 2]
```diff
@@ -2138,6 +2138,22 @@ declare namespace Cypress {
...
+     *
+     * @see https://on.cypress.io/writefile
+    ```
+    cy.writeFile('path/to/ascii.txt', 'Hello World', 'utf8', {
+      flag: 'a+',
+      encoding: 'ascii'
```
Comment (jennifer-shehane) [inline cli/types/cypress.d.ts:2150]: I'd probably remove the double encoding from the example because I wouldn't exactly encourage this.

```suggestion
```

**Review by jennifer-shehane — APPROVED** [review]
