### PR TITLE
fix(launcher): support Firefox as a snap

### LINKED ISSUE #19793: Can’t use default Firefox on latest Ubuntu
### Current behavior

When trying to use Firefox from Cypress on a fresh install of Ubuntu 21.10, it just hangs with
“Firefox is already running, but not responding.”

Screenshot

### Desired behavior

Cypress should open Firefox.

### Test code to reproduce

`cypress open`

### Cypress Version

9.3.1

### Other

Ubuntu 21.10 has [moved Firefox](https://discourse.ubuntu.com/t/impish-indri-release-notes/21951) to a [snap](https://snapcraft.io/about).

The snap is configured to confine Firefox using the [home interface](https://snapcraft.io/docs/home-interface), which allows “access to non-hidden files.” The firefox profile Cypress creates at `~/.config/Cypress/cy/production/browsers/firefox-stable/interactive` is considered hidden because of the `.` in `.config`. Firefox can’t access the profile folder and gets confused and says it is already running.

A similar issue was already fixed for Chromium in #7039.

As a temporary workaround, if I run, `XDG_CONFIG_HOME=$HOME/cypress cypress open` so that Cypress creates and uses a firefox profile in a non-hidden directory, then Firefox opens and cypress tests run successfully.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #19793
- Unblocks UNIFY-1607

### User facing changelog

- Fixed an issue causing Linux users with Firefox installed via Snapcraft to encounter errors on launch.

### Additional details

- If we detect FF is running in a snap, we change the profilePath to the sandboxed one, like we did for Cr: https://github.com/cypress-io/cypress/issues/7020
- ~~Had to change `@types/node` to the correct version to use the `fs` features.~~
	- Gave up on this, too many failures. Created an issue: https://github.com/cypress-io/cypress/issues/21329

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/launcher/lib/linux/index.ts [hunk 1]
```diff
@@ -3,8 +3,33 @@ import type { FoundBrowser, Browser, PathData } from '../types'
...
+
+      // read the first 16kb, don't read the entire file into memory in case it is a binary
+      const fd = await fs.open(binaryPath, 'r')
+      // @ts-ignore - needs @types/node at least 16
+      // https://github.com/cypress-io/cypress/issues/21329
+      const { buffer, bytesRead } = await fd.read<Buffer>({ length: 16384 })
+
+      await fd.close()
+
+      return buffer.slice(0, bytesRead).toString('utf8').includes('exec /snap/bin/firefox')
```
Comment (BlueWinds) [inline packages/launcher/lib/linux/index.ts:24]: Today I learned about reading only the opening bytes of a file! This seemed odd (particularly the slice), so I poked around the docs and command line, and lo, you have done it correctly. :)

File: packages/launcher/lib/linux/index.ts [hunk 2]
```diff
@@ -3,8 +3,33 @@ import type { FoundBrowser, Browser, PathData } from '../types'
...
 import { utils } from '../utils'
 import os from 'os'
+import { promises as fs } from 'fs'
 import path from 'path'
 import Bluebird from 'bluebird'
+import which from 'which'
+
+async function isFirefoxSnap (binary: string): Promise<boolean> {
+  try {
+    return await Bluebird.resolve((async () => {
```
Comment (BlueWinds) [inline packages/launcher/lib/linux/index.ts:13]: I'd like to avoid Bluebird promises in newly written code when possible. Especially since we're already inside an `async` function, do we need `Bluebird.resolve` here?

**Review by BlueWinds — APPROVED** [review]

File: packages/launcher/lib/linux/index.ts (hunk 2 above)
Comment (flotwig) [reply packages/launcher/lib/linux/index.ts:13]: I'm using Bluebird.resolve to get access to `.timeout`. I could `Promise.race/new Promise/setTimeout` but I figure that unless we are planning on moving all the code in the code base to not use Bluebird, might as well use the utilities we have. I also generally agree that BB should be avoided in new code.

Comment (BlueWinds) [reply packages/launcher/lib/linux/index.ts:13]: That is something I would like to do at some point, remove bluebird from our existing code. But adding timeout utility functions is beyond the scope of this PR, fair enough.

**Review by tbiethman — APPROVED** [review]
Verified on my Ubuntu VM that both snap/non-snap firefox installations are launched by Cypress

**Comment by nicktelindertvmw** [comment]
The snap version of firefox and chromium are not detected by cypress for 12.17.2, testing on  Ubuntu 22.04 and newer

**Comment by jennifer-shehane** [comment]
@nicktelindertvmw Please open a new issue describing the behavior and a reproducible example
