### PR TITLE
fix: "bypass" proxying network requests from extra browser tabs/windows

### LINKED ISSUE #28113: Network delay in 13.3.1 running lighthouse in cypress
### Current behavior

Since Cypress 13.3.1 we have noticed another delay in the network layer when using the cypress browser for running lighthouse against. This isn't the first time this has happened - Related issue https://github.com/cypress-io/cypress/issues/17327 saw the same impact where the network request time was a minimum of 0.5 seconds to fetch any resource. Now as of 13.3.1 the minimum fetch time has jumped to massive 2.0 seconds! This renders our lighthouse tests redundant as they are not comparable to just a normal lighthouse test. For example the project we test against is a simlpe CreateReactApp with a simple data fetch that is intercepted. When testing outside of Cypress our score is 99. As of 13.3.1 the score has dropped to 56 due to these network latencies.
 

### Desired behavior

Lighthouse Tests ran against a cypress browser using a devPort should not be subject to network penalities set by the Cypress browser.

## Code to repoduce 

The reproducible tests in the repo below run a basic create react app which gets a lighthouse score of 56 our of 100. It should be 99/100.

Reproducible repo - https://github.com/metalix2/cypress-lighthouse-slow

Setup instructions in [readme](https://github.com/metalix2/cypress-lighthouse-slow#readme). 

Some observations. On the cypress window with the UI. the Page loads as expected. It's just when its loaded in a different tab it seems to be very slooooooooooow.

## See screenshots below.

cypress-page-trace
(Last few assets are of the page being tested the size strangely don't align with the other tab's network resources.)

### Loading assets taking 2000ms 👎 
cypress-tab-trace

Before 13.3.1 
cypress-13 2 0

I have videos and Cypress recordings available please do not hesitate to ask. I'd love to see this resolved once and for all.

### Cypress Version

13.3.2

### Node version

v18.18.1

### Operating System

macOS 13.5.2

### Debug Logs

```shell
https://gist.github.com/metalix2/38c3566f7c4db297ee5cc5094c10eb68
```

### Other

From the original investigation in https://github.com/cypress-io/cypress/issues/17327 I created a diff in one of my comments perhaps someone more familiar with the cypress core will understand better.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #28113

### Additional details

Filters out network requests from extra tabs and windows (extra meaning not the main Cypress tab) so that they bypass most of the proxy logic. They aren't correlated, awaited, injected into, etc. The intent is for the requests and responses to go through as unchanged as possible. 

### PR Tasks

- [x] Have tests been added/updated?
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 1]
```diff
@@ -281,9 +382,17 @@ export class BrowserCriClient {
...
+    const { targetId } = event
+
+    if (targetId !== browserCriClient.currentlyAttachedTarget?.targetId) {
+      if (browserCriClient.hasExtraTargetClient(targetId)) {
+        debug('Close extra target client (id: %s)')
+        browserCriClient.getExtraTargetClient(targetId)!.client.close().catch(() => { })
+        browserCriClient.removeExtraTargetClient(targetId)
+      }
+
+      // we may have gotten a delayed "Target.targetDestroyed" even for a page that we
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/browser-cri-client.ts]:
```suggestion
      // we may have gotten a delayed "Target.targetDestroyed" event for a page that we
```

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 2]
```diff
@@ -255,22 +267,111 @@ export class BrowserCriClient {
...
+
+    // the url often isn't specified with this event, so we get it
+    // from Target.getTargets
+    if (!url) {
+      const { targetInfos } = await browserClient.send('Target.getTargets')
+
+      const thisTarget = targetInfos.find((target) => target.targetId === targetId)
+
+      if (thisTarget) {
+        url = thisTarget.url
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/browser-cri-client.ts:315]: Out of curiosity, what does the url show as for service workers/web workers/shared workers? We want to make sure we're still using the proxy for them for workers started in the main target.

Can maybe use the system tests here to see? 

https://github.com/cypress-io/cypress/blob/develop/system-tests/test/web_worker_spec.js
https://github.com/cypress-io/cypress/blob/develop/system-tests/test/service_worker_spec.js

Comment (chrisbreiding) [reply packages/server/lib/browsers/browser-cri-client.ts:315]: For service workers, we can go off `targetInfo.type`. I think we only want to consider `type === 'page'` as an extra target, so I [updated the logic here](https://github.com/cypress-io/cypress/pull/28188/commits/5f72ec9f7f1ec10105fc3ff31994f1184c6b3fd8). Before that change, those system tests were failing, so looks like they were doing their jobs.

**Review by ryanthemanuel — APPROVED** [review]

File: packages/server/lib/browsers/browser-cri-client.ts [hunk 3]
```diff
@@ -255,22 +267,113 @@ export class BrowserCriClient {
...
+      // it's possible that the target was closed before we could enable
+      // network and continue, in that case, just ignore
+      debug('error running Network.enable:', error)
+    }
+
+    if (!waitingForDebugger) {
+      debug('Not waiting for debugger (id: %s)', targetId)
+
+      // targets created before we started listening won't be waiting
+      // for debugger and are not extras
```
Comment (mschile) [inline packages/server/lib/browsers/browser-cri-client.ts]:
```suggestion
      // a target created before we started listening won't be waiting
      // for the debugger and is therefore not an extra target
```

**Review by mschile — APPROVED** [review]
