### PR TITLE
chore: fix windows job due to ipv6 issues

### LINKED ISSUE #30376: Investigate flake in `windows-run-app-integration-tests-chrome` job
### What would you like?

This job has a 10% success rate, we should understand why this fails so often and take some action. The `windows-run-launchpad-integration-tests-chrome` tests are similarly failing a lot. 

[Insights](https://app.circleci.com/insights/github/cypress-io/cypress/workflows/windows/jobs?branch=develop)

- Increase retries?
- Reduce set of tests to run to be specific to Windows logic
- Is this related to cy in cy tests?

### Why is this needed?

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #30376 

### Additional details

Windows tests are periodically failing with Cypress in Cypress because the inner Cypress server is having communication issues when attempted to be connected to via ipv6. As a workaround for this, we will filter out ipv6 addresses (but only when doing Cypress in Cypress testing on windows).

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/network/lib/connect.ts [hunk 1]
```diff
@@ -39,6 +40,15 @@ export function getAddress (port: number, hostname: string): Bluebird<net.Addres
   .then((addresses) => {
     debug('got addresses %o', { hostname, port, addresses })
 
+    // ipv6 addresses are causing problems with cypress in cypress internal e2e tests
+    // so we are filtering them out here
```
Comment (ryanthemanuel) [inline packages/network/lib/connect.ts]:
```suggestion
    // on windows, so we are filtering them out here
```

**Review by jennifer-shehane — APPROVED** [review]
