### PR TITLE
fix(cli): Respect NO_PROXY on cypress download

### LINKED ISSUE #6304: Make it possible to support no_proxy environment variable for download
### Current behavior:

When downloading Cypress, the no_proxy environment variable is not taken into account.

image

### Desired behavior:

When downloading, I want Cypress to be able to use the no_proxy environment so that it doesn't go through the company proxy. Using CYPRESS_INSTALL_BINARY and downloading manually isn't really a solution as we don't want CI/CD build agents to download cypress every time. Installing cypress on every build agents doesn't seem like the best solution either.

### Versions
Cypress: 3.8.3

### PR DESCRIPTION
**Pull request by westarne**
- Closes #6304

### User facing changelog
As stated in the open issue, the download of cypress did not support the `NO_PROXY` environment variable and thus always used a proxy. This PR fixes that behaviour by adding an explicit NO_PROXY lookup. This change is based on https://github.com/cypress-io/request/blob/master/lib/getProxyFromURI.js.

### Additional details
I've selected this approach to still explicitly hand in the proxy to the `request` module, because in there the variables `npm_config_proxy` and `npm_config_https_proxy` are ignored to determine the proxy.
As alternative stated in https://github.com/cypress-io/cypress/issues/6304#issuecomment-877359711 it would also be possible to leave out the `proxy` parameter when executing the `request` as it will be determined in there. But as mentioned this would not respect the npm config properties.

### How has the user experience changed?
`npm install cypress` now works if a proxy is set but not used for cypress.

### PR Tasks

- [X] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: cli/lib/tasks/download.js [hunk 1]
```diff
@@ -9,23 +9,14 @@ const request = require('@cypress/request')
 const Promise = require('bluebird')
 const requestProgress = require('request-progress')
 const { stripIndent } = require('common-tags')
+const getProxyFromURI = require('./getProxyFromURI')
```
Comment (flotwig) [inline cli/lib/tasks/download.js:12]: Can you update the implementation to use the `proxy-from-env` node module instead of inlining `getProxyFromURI`? We use this library elsewhere so might as well keep using it here: https://github.com/Rob--W/proxy-from-env

**Review by flotwig — CHANGES_REQUESTED** [review]
Thank you for opening a PR.

File: cli/lib/tasks/download.js (hunk 1 above)
Comment (westarne) [reply cli/lib/tasks/download.js]: Sure, I've adjusted the implementation.

I've wrapped the method from that module to also be able to use the npm configured proxies. It behaves a bit different now though (see tests):
- http_proxy and HTTP_PROXY env are only used on http requests
- https_proxy and HTTPS_PROXY env are only used on https requests
- npm_config_https_proxy and npm_config_proxy are used if no other proxy was selected by the `proxy-from-env` module. https is preferred as before
- npm_config_https_proxy and npm_config_proxy are used with both http and https requests if set
- npm_config_https_proxy and npm_config_proxy do NOT respect `NO_PROXY`

**Review by flotwig — CHANGES_REQUESTED** [review]
I added a commit to add `proxy-from-env@1.0.0` to `package.json`.

Also, can you please open a PR in `cypress-documentation` to enhance the install docs with this information? This would be a good place: https://github.com/cypress-io/cypress-documentation/blob/master/content/guides/getting-started/installing-cypress.md

Once that's done this looks good to me.

**Comment by westarne** [comment]
Thank you @flotwig
I've created a PR on the documentation repo: https://github.com/cypress-io/cypress-documentation/pull/4089

**Review by flotwig — APPROVED** [review]
Thank you for the contribution @westarne
