### PR TITLE
Truncate httpprops in error message to show more chars

### LINKED ISSUE #3145: Should not truncate full url during cy.request() in stdout
### Is this a Feature or Bug?

I believe this to be a bug with Cypress dashboard where truncation of the output makes debugging issues via the dashboard or CI very difficult for developers. It is useful for instance to see body and url parameters when using something like `cy.request` however the output on failure is formatted in a way which inhibits the ability to debug issues.

### Current behavior:

the output in the cypress dashboard for a 404 (any sufficiently large output will do) looks like

```
 1) toolbar layer style "before all" hook for "should edit style name":
     CypressError: cy.request() failed on:

http://xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy/api/customer?token=uy9aG2yVRlyPAcW_xvTZEXlTvRm6O4u_

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy/api/customer?token=uy9aG2yVRlyPAcW_xvTZEXlTvRm6...
Headers: {
  "user-agent": "E2E",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 74
}
Body: {"clusterId":"Dev-Alpha-Cluster","name":"Fin Fang Foom e2e20190116163428","OtherStuff":"ThisIsSomeDa...
```

see that the body and url are being truncated in this final block of the log. For small payloads it's fine, but when payloads become larger (or other cy methods that produce longer lines) the truncation makes the output almost useless. This is more of a problem when the errors are only produced on the CI server.

### Desired behavior:

I would like some control over the output here, several options:

- Download the raw output (unmodified)
- Wrap long lines preserving the entire line
- Have an option to open raw in the browser

### Steps to reproduce: (app code and test code)

Simply perform a `cy.request` with a sufficiently large url or body e.g.

```JavaScript
cy.request({
  method: 'POST',
  url: 'http://myreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylong.url',
})
```

### Versions

Cypress: 3.1.3

I don't believe the browser to be an issue in this specific issue.

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- truncate httpProps shown in error messages to 2000 chars instead of 100 chars
- close #3145

### CODE REVIEW

File: packages/server/test/support/fixtures/projects/e2e/cypress/integration/request_long_http_props_failing_spec.coffee [hunk 1]
```diff
@@ -0,0 +1,4 @@
+describe "when status code isnt 2xx or 3xx", ->
+  it "fails", ->
+    cy.request("http://localhost:2294/myreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylong
```
Comment (brian-mann) [inline packages/server/test/support/fixtures/projects/e2e/cypress/integration/request_long_http_props_failing_spec.coffee]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Review by brian-mann — CHANGES_REQUESTED** [review]

**Comment by brian-mann** [comment]
@jennifer-shehane are you fixing these conflicts?
