### PR TITLE
fix: add deprecation notice for win 32-bit

### LINKED ISSUE #18094: Add deprecation warning for Win32 users
For #17962

- Send event when users hit deprecation warning?
- Link to the removal of win32 issue for them to comment on.

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #18094 

### User facing changelog

- Added a deprecation notice for Windows 32-bit users that support will be removed in a future release.

### How has the user experience changed?

warning for users on 32-bit windows:

image

warning for users on 64-bit windows:

image

same warning in runmode:

image

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/open_project.ts [hunk 1]
```diff
@@ -40,6 +43,33 @@ export interface LaunchArgs {
   onFocusTests?: () => any
 }
 
+// @see https://github.com/cypress-io/cypress/issues/18094
+async function win32BitWarning (onWarning) {
```
Comment (lmiller1990) [inline packages/server/lib/open_project.ts:47]:
```suggestion
async function win32BitWarning (onWarning: (error: string, hasX64: boolean) => void) {
```

**Review by lmiller1990 — COMMENTED** [review]
Slowly but steadily trying to type all the things 😇

File: packages/server/lib/open_project.ts (hunk 1 above)
Comment (flotwig) [reply packages/server/lib/open_project.ts:47]:
```suggestion
async function win32BitWarning (onWarning: (error: Error) => void) {
```

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
LGTM! I don't have a 32 bit windows machine to actually test this on, if someone does, that'd be great.

File: packages/server/lib/errors.js [hunk 2]
```diff
@@ -989,6 +989,15 @@ const getMsgByType = function (type, arg1 = {}, arg2, arg3) {
...
     case 'UNSUPPORTED_BROWSER_VERSION':
       return arg1
+    case 'WIN32_DEPRECATION':
+      return stripIndent`\
+        You are currently running a 32-bit build of Cypress. Cypress will remove Windows 32-bit support in a future release.
+
+        ${arg1 ? 'You are using Windows 64-bit, which will continue to support Cypress. Try installing Node.js 64-bit and reinstalling Cypress to use the 64-bit build.'
+        : 'You are on Windows 32-bit, which will be unable to run future releases of Cypress. Consider upgrading to a 64-bit OS to continue using Cypress.'}
+
+        For more information, see: https://on.cypress.io/win32-removal
```
Comment (jennifer-shehane) [inline packages/server/lib/errors.js:999]: I think what was confusing was it just seemingly restating the issue and mentioning it being removed in future versions twice. Might be best to just simply state the next step: 'how do I fix this', rather than reiterating on the problem.

```suggestion
        You are running a 32-bit build of Cypress. Cypress will remove Windows 32-bit support in a future release.

        ${arg1 ? 'Try installing Node.js 64-bit and reinstalling Cypress to use the 64-bit build.'
        : 'Consider upgrading to a 64-bit OS to continue using Cypress in future releases.'}

        For more information, see: https://on.cypress.io/win32-removal
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
We'll also need a PR against services for the https://on.cypress.io/win32-removal link

**Review by jennifer-shehane — APPROVED** [review]
