### PR TITLE
fix: re include document domain injections for spec-bridge and injection and disable origin-agent-cluster

### LINKED ISSUE #25010: Cypress spec-bridge cannot communicate with facebook.com due to document.domain difference
### Current behavior

Currently the following test times out. This is due to the `document.domain` changes we made in a3d3074e707ee3daceaf22cdc14fbfba3dd96896, which be believed to make sense at the time assuming `document.domain` would always be the host. The issue is this didn't account if the injection domain sets the bare domain via `document.domain` , which means the spec bridge iframe might not be able to communicate with the injected code. 

### Desired behavior

Facebook login should work. We likely need to revert a3d3074e707ee3daceaf22cdc14fbfba3dd96896  and implement `origin-agent-cluster=?0` in the `spec-bridge-iframe`.

### Test code to reproduce

```js
  it('logs in via Facebook', () => {
    cy.visit('https://localhost:3000');
    cy.get('[data-cy="login"]').click();
  
    cy.origin('https://<YOUR_AUTH0_INSTANCE>.us.auth0.com', () => {
      cy.scrollTo('bottom');
      cy.get('form[data-provider="facebook"]').submit();
    });
  
    cy.origin('https://www.facebook.com', () => {
      cy.get('#email').type(Cypress.env('FACEBOOK_USERNAME'));
      cy.get('#pass').type(Cypress.env('FACEBOOK_PASSWORD'), {
        log: false
      });
      cy.get('[type="submit"]').contains('Log In').click();
    });
  
    cy.get('[data-cy="user-name"]').invoke('text').should('equal', Cypress.env('FACEBOOK_NAME'));
  });
```

### Cypress Version

12.0.0

### Node version

v16.15.0

### Operating System

macOS 12.6

### Debug Logs

```shell
Not needed. Root cause of issue determined
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #25010

### User facing changelog
Fixed a regression introduced in `12.0.0` that sometimes does not allow `cy.origin()` to communicate correctly with the navigated to domain.

### Additional details
After merging `v12.0.0` we noticed that one of our auth provider integration tests was failing, but worked during the testing session last week. It turns out that some domains set `document.domain` to the bare domain, which means we would need to do the same in the spec bridge to communicate with `cy.origin()`. In other words, we need to continue setting `document.domain` inside the spec bridge and injection html😞 . This is mostly a least common denominator approach that we have before.

This code reverts a3d3074e707ee3daceaf22cdc14fbfba3dd96896 and adds the `origin-agent-cluster=?0` header to the `spec-bridge-iframe` requests.

#### Test timeout with Facebook
Screen Shot 2022-12-06 at 2 28 37 PM

##### After reverting a3d3074e707ee3daceaf22cdc14fbfba3dd96896, this issue appears in the console
origin--agent-cluster-unset

##### After adding 2e1d289279dd670cffcf58c4e206efa8e2a7269a, the issue no longer appears in the console
origin-agent-cluster-set

### Steps to test
run the integration tests in `@packages/server`

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/network/lib/cors.ts [hunk 1]
```diff
@@ -227,14 +227,11 @@ export function getOrigin (url: string) {
 }
 
 /**
- * Returns the super-domain of a URL
- *
- * The primary driver uses the super-domain origin to allow tests to
- * navigate between subdomains of the same super-domain by setting
- * document.domain to the super-domain
+ * We use the super domain origin in the driver to determine whether or not we need to reload/interact with the AUT, and
+ * currently in the spec bridge to interact with the AUT frame, which uses document.domain set to the super domain
```
Comment (AtofStryker) [inline packages/network/lib/cors.ts]: I think the comment update is still valid @chrisbreiding. I'd like to keep those changes and will update with a commit

File: packages/server/lib/routes-e2e.ts [hunk 2]
```diff
@@ -98,6 +98,13 @@ export const createRoutesE2E = ({
   routesE2E.get('/__cypress/spec-bridge-iframes', (req, res) => {
     debug('handling cross-origin iframe for domain: %s', req.hostname)
 
+    // Chrome plans to make document.domain immutable in Chrome 106, with the default value
```
Comment (mschile) [inline packages/server/lib/routes-e2e.ts]:
```suggestion
    // Chrome plans to make document.domain immutable in Chrome 109, with the default value
```

**Review by mschile — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Review by tbiethman — APPROVED** [review]

File: packages/network/lib/cors.ts (hunk 1 above)
Comment (AtofStryker) [reply packages/network/lib/cors.ts]: fixed in 070ba434bf

**Review by chrisbreiding — APPROVED** [review]
