### PR TITLE
Fix error on aborting XHRs of non responseType '' or 'text'

### LINKED ISSUE #3008: Frequent InvalidStateError when running tests in 3.1.4 update
### Current behavior:
When running certain tests, I will frequently get an InvalidStateError on tests that worked previously in 3.1.3. Additionally, this does not happen everytime the test is run. Sometimes the test will pass, but many times this error will happen. 

`InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').`

### Desired behavior:
The test should pass without any errors. 
Consistent behavior from one test run to another.

### Steps to reproduce: (app code and test code)

The below test is on a page that loads a HERE map, and consequently receives many XHR responses upon loading. 
Example code of a test case that resulted in this error, but worked in previous Cypress versions.
```js
const Accounts = require('../../constants/accounts');
const Routes = require('../../constants/routes');

describe('Switching organizations, then refreshes the page', () => {
  before(() => {
    cy.viewport('macbook-15');
    cy.visit(Routes().dashboardBaseUrl);
    cy.get('input[name=email]').type(Accounts().email);
    cy.get('input[name=password]')
      .type(Accounts().pw)
      .type('{enter}');
  });

  it('should default back to original organization view upon refresh', () => {
    context('switch from parent organization to child organization', () => {
      cy.get('[data=subscribedName]').should(
        'have.text',
        'organization name'
      );

      //open the dropdown
      cy.get('[data=dropdown-toggle]').click();

      //Click on the first child organization
      cy.get('[data=orgName]:first').click();

      //organization title should have changed
      cy.get('[data=subscribedName]').should(
        'have.text',
        'blacklist'
      );
    });

    cy.reload();
    cy.get('[data=subscribedName]').should(
      'have.text',
      'organization name'
    );
  });
});

```

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- write failing test for xhrs of responseType 'arraybuffer'
- TODO: How do we want to handle other responseTypes?

- close #3008

### CODE REVIEW

File: packages/driver/src/cypress/server.coffee [hunk 1]
```diff
@@ -31,7 +31,9 @@ nope = -> return null
 isAbortedThroughUnload = (xhr) ->
   xhr.readyState is 4 and
     xhr.status is 0 and
-      xhr.responseText is ""
+      ## TODO: How do we want to handle other responseTypes?
+      (xhr.responseType is "" or xhr.responseType is "text") and
```
Comment (brian-mann) [inline packages/driver/src/cypress/server.coffee]: - let's leave a comment here pointing to the issue that describes why `''` and `'text'` are the only two responseTypes we are looking at
- let's wrap this check up into a method that describes these two values: something like `responseTypeIsTextOrBlank`

**Review by brian-mann — CHANGES_REQUESTED** [review]
I plan on releasing `3.1.5` this weekend so I will make these changes

**Review by brian-mann — APPROVED** [review]
