### PR TITLE
fix(angular): mount cy-root in original location

### LINKED ISSUE #25956: Angular CT does not mount component within div[data-cy-root]'s original html element hierarchy
### Current behavior

Angular components are correctly mounted into the div[data-cy-root] root element but they aren't respecting the div's original position. 

component-index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Components App</title>
  </head>
  <body>
    <div id="outside">
      <div id="inside">
        <div data-cy-root></div>
      </div>
    </div>
  </body>
</html>

```

image

the issue is caused by the [following line of code ](https://github.com/cypress-io/cypress/blob/develop/npm/angular/src/mount.ts#L182)

```ts
       document.body.appendChild(rootElement)
```

### Desired behavior

The components should be mounted inside of `div data-cy-root></div>` and still keep it's original position. 

```html
<div class="outside">
      <div id="inside">
          <div data-cy-root="" id="root0" _nghost-a-c12="" ng-version="14.2.12"><div _ngcontent-a-c12="">yep, it works</div><button _ngcontent-a-c12="" data-cy="get-comp-name">Get component name</button></div>
      </div>
</div>
```

###  possible solution 

update the [following method](https://github.com/cypress-io/cypress/blob/develop/npm/angular/src/mount.ts#L176)

```ts
override insertRootElement (rootElId: string) {
    this.removeAllRootElements()

    const rootElement = getContainerEl()
    const parentElement = rootElement.parentElement

    rootElement.setAttribute('id', rootElId)

    if(parentElement && parentElement?.tagName !== 'HTML') {
        parentElement.appendChild(rootElement)
    } else {
        document.body.appendChild(rootElement) 
   }
    
  }
```

### Test code to reproduce

Any angular app with CT setup. You just need to edit the component-index.html file. 

`<div data-cy-root></div>` add the root div inside another div. 

```html
...
  <body>
      <div id="container">
        <div data-cy-root></div>
      </div>
  </body>
```

### Cypress Version

12.7.0

### Node version

v18.12.1

### Operating System

ubuntu 22.04

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mv740**
- Closes  [Angular CT does not mount component within div[data-cy-root]'s original html element hierarchy](https://github.com/cypress-io/cypress/issues/25956)

### Steps to test

Throw a .only on

https://github.com/mv740/cypress/blob/e7879be246f0db6e24901ece225eacc12afb3bde/system-tests/test/component_testing_spec.ts#L147

test with `yarn test component_testing`

### How has the user experience changed?

image

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: npm/angular/src/mount.ts [hunk 1]
```diff
@@ -177,9 +177,14 @@ export class CypressTestComponentRenderer extends TestComponentRenderer {
...
     const rootElement = getContainerEl()
+    const parentElement = rootElement.parentElement
 
     rootElement.setAttribute('id', rootElId)
-    document.body.appendChild(rootElement)
+    if (parentElement && parentElement?.tagName !== 'HTML') {
+      parentElement.appendChild(rootElement)
+    } else {
+      document.body.appendChild(rootElement)
+    }
```
Comment (ZachJW34) [inline npm/angular/src/mount.ts]:
```suggestion
```

The true fix here is the removal of `document.body.appendChild(rootElement)`, we don't need this extra logic since `rootElement` is already guaranteed to be in the DOM (`getContainerEl()` uses querySelector, so if it wasn't in the DOM it will throw)

**Review by ZachJW34 — CHANGES_REQUESTED** [review]
We can also trim up the system-tests added. Scaffolding system tests are expensive so if we can tack this on to an existing test that would be ideal. Plus, the system-test added is based on using a project using a custom-root, adding it to the default would make more sense.

You can remove your system-test changes and add:

```ts
context('component-index.html', () => {
    before(() => {
      const cyRoot = document.querySelector(cyRootSelector)!

      expect(cyRoot.parentElement === document.body)
      document.body.innerHTML = `
        <div id="container">
          <div data-cy-root></div>
        </div>
      `
    })

    it('preserves html hierarchy', () => {
      cy.mount(ChildComponent, { componentProperties: { msg: 'Render 1' } })
      cy.contains('Render 1')
      cy.get(cyRootSelector).should('exist').parent().should('have.id', 'container')
      cy.get('#container').should('exist').parent().should('have.prop', 'tagName').should('eq', 'BODY')

      // structure persists after teardown
      cy.mount(ChildComponent, { componentProperties: { msg: 'Render 2' } })
      cy.contains('Render 2')
      cy.get(cyRootSelector).should('exist').parent().should('have.id', 'container')
      cy.get('#container').should('exist').parent().should('have.prop', 'tagName').should('eq', 'BODY')
    })
  })
  ```
  
  to `system-tests/project-fixtures/angular/src/app/mount.cy.ts`. This will also run across all versions of angular for added coverage, and since it's already part of an existing scaffold it will be fast.

File: npm/angular/src/mount.ts (hunk 1 above)
Comment (mv740) [reply npm/angular/src/mount.ts]: Oh, I didn't see the mount.cy.ts. You are right, it is a much better idea to inject the different HTML during the test. 

I will update my branch based on your suggestion

**Review by ZachJW34 — APPROVED** [review]

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Will give @jordanpowell88 a chance to review before merging, but this looks good to me.

**Review by jordanpowell88 — APPROVED** [review]
