### PR TITLE
escape text before interpolating in getContainsSelector

### LINKED ISSUE #1322: contains() breaks with a regex containing a `'`
- Operating System: macos
- Cypress Version: 1.4.2
- Browser Version: chrome 65

### Is this a Feature or Bug?
bug

### Current behavior:
`cy.get('some selector').contains(/any regex containing a '/)` results in an error

### Desired behavior:
to select any dom nodes that match the provided regex, as is the behavior for any regex not containing a `'`

### How to reproduce / test code
https://github.com/cypress-io/cypress-test-tiny/pull/26

### PR DESCRIPTION
**Pull request by jbr**
even if it’s a regex, this selector is still passed to sizzle and needs to be valid, which means quotes must be escaped

closes #1322

### CODE REVIEW

File: packages/driver/test/cypress/integration/commands/querying_spec.coffee [hunk 1]
```diff
@@ -1422,12 +1422,18 @@ describe "src/cy/commands/querying", ->
...
+        it "finds content by string with character: #{char}", ->
           span = $("<span>special char #{char} content</span>").appendTo cy.$$("body")
 
           cy.contains("span", char).then ($span) ->
             expect($span.get(0)).to.eq span.get(0)
 
+        it "finds content by regex with character: #{char}", ->
+          span = $("<span>special char #{char} content</span>").appendTo cy.$$("body")
+
+          cy.contains("span", new RegExp(_.escapeRegExp(char))).then ($span) ->
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/querying_spec.coffee]: Awesome - thank you for taking the lead on this.

However, Isn't this obfuscating the actual bug? By escaping it in your argument here, this would pass even without your fix in `elements.coffee` right?

I believe you shouldn't be escaping the regexp here so that it proves we're correctly escaping it for you. I haven't run this though - so I could be totally off.

Comment (jbr) [reply packages/driver/test/cypress/integration/commands/querying_spec.coffee]: it does not pass without the fix in elements.coffee (confirmed before submitting). `‘` is a valid non-special reflex character and is passed through excapeRegExp unchanged. the escapeRegExp is for the other characters
