### PR TITLE
fix: ensure that absolute paths can be found via source maps

### LINKED ISSUE #32809: Open in IDE does not work when preprocessor uses a different root directory than the project root
### Current behavior

If you use a different root directory than the project root in your preprocessor, for example:

```js
  const options = {
    webpackOptions: {
      context: path.resolve(__dirname, 'cypress'),
    }
  }

  on('file:preprocessor', webpack(options))
```

This will cause source maps to look in the wrong place for the absolute file (which is necessary for when you want to open the IDE or view the code inline for `cy.prompt`). As a result, you will not be able to use the Open in IDE functionality

### Desired behavior

_No response_

### Test code to reproduce

See above for the config

### Cypress Version

all

### Debug Logs

```shell

```

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #32809

### Additional details

Current Cypress code that determines absolute paths assumes that source maps are relative to the project root. This is not true. Users can have a webpack configuration that specifies a new root via the context property. To allow for this, we determine the new root. We do this by treating the spec file as an anchor point since we know it's absolute path. We can then look at the source maps and determine what "relative" is for that spec file. From this, we then calculate what the root is.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

---

> [!NOTE]
> Determine and propagate a source map project root to resolve correct absolute file paths and IDE opening, and add targeted sourcemap tests and configs across runners.
> 
> - **Core/Driver (sourcemaps)**:
>   - Add `source_map_utils` APIs to extract source maps, set/get `projectRoot` via spec anchor, and compute `getBaseDirectory`.
>   - Use source map project root in `cypress.ts`, `script_utils`, `stack_utils`, `mocha`, `origin` and `sessions` commands to enhance stacks, invocation details, and file resolution.
>   - Expose `Cypress.areSourceMapsAvailable` and `Cypress.sourceMapProjectRoot`.
>   - Move custom protocol stripping to `utils.stripCustomProtocol` and update callers.
> - **Reporter/Verification**:
>   - Pass `filePath` through `createVerify` and `verifyIdeOpen` to assert correct absolute path and IDE open behavior.
> - **Tests**:
>   - Add/expand sourcemap E2E/CT tests (Vite and Webpack dev servers) to verify file path display and `open:file` events; scaffold specs under `src/`.
>   - Add system tests with new `.mjs` configs (enabled/disabled and updated sourcemap root) and a new fixture project `runner-e2e-specs-new-sourcemap-root`.
> - **Misc**:
>   - Update changelog with bugfix entry; tweak CI workflow branch filter.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 69f79b0c966ef04102190e52e96223c422c0bb2d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/driver/src/cypress/mocha.ts [hunk 1]
```diff
@@ -529,12 +530,12 @@ const patchRunnableClearTimeout = () => {
...
 }
 
-const patchSuiteAddTest = (specWindow, config) => {
+const patchSuiteAddTest = (specWindow, Cypress: InternalCypress.Cypress) => {
   Suite.prototype.addTest = function (...args) {
     const test = args[0]
 
     if (!test.invocationDetails) {
-      test.invocationDetails = $stackUtils.getInvocationDetails(specWindow, config)
+      test.invocationDetails = $stackUtils.getInvocationDetails(specWindow, $sourceMapUtils.getSourceMapProjectRoot())
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress/mocha.ts:538]: This has been addressed

File: packages/driver/src/cypress/source_map_utils.ts [hunk 2]
```diff
@@ -118,11 +120,66 @@ const areSourceMapsAvailable = () => {
...
+  const consumer = sourceMapConsumers[key]
+
+  for (let index = 0; index < consumer.sources.length; index++) {
+    const source = consumer.sources[index]
+    const strippedSource = stackUtils.stripCustomProtocol(source)
+
+    if (absolutePath.endsWith(strippedSource)) {
+      // @ts-expect-error
+      const relativeSource = consumer._sources.at(index)
+
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress/source_map_utils.ts:159]: We do this elsewhere. My goal with this is not to fix this necessarily.

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts [hunk 3]
```diff
@@ -0,0 +1,304 @@
...
+
+    vi.doMock('path', () => {
+      return {
+        default: { ...pathMock.posix, posix: pathMock.posix, win32: pathMock.win32 },
+        ...pathMock.posix,
+        posix: pathMock.posix,
+        win32: pathMock.win32,
+      }
+    })
+  }
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/test/unit/cypress/source_map_utils.spec.ts:96]: This has been resolved

**Comment by ryanthemanuel** [comment]
> ### Bug: Bug
> The source map project root is set too late. The mocha patches (in patchSuiteAddTest, patchSuiteAddSuite, and patchSuiteHooks) call getInvocationDetails() which depends on sourceMapProjectRoot being set. However, sourceMapProjectRoot is only set after runScripts() completes, which happens after the spec file is evaluated. During spec file evaluation, when describe() and it() are called, they trigger the patched mocha functions before sourceMapProjectRoot is initialized.
> 
> The correct order should be:
> 
> 1. Set sourceMapProjectRoot before evaluating the spec
> 2. Then evaluate the spec (which calls describe/it)
> 
> Currently the order is:
> 
> 1. Apply mocha patches (with empty sourceMapProjectRoot)
> 2. Load scripts and extract source maps
> 3. Evaluate spec file (describe/it calls use empty sourceMapProjectRoot)
> 4. Set sourceMapProjectRoot in .then() callback (too late)
> 
> `packages/driver/src/cypress.ts#L435-L454`
> https://github.com/cypress-io/cypress/blob/c7539c5a9d24e5de5c70e4616ca089bf363c4f41/packages/driver/src/cypress.ts#L435-L454
> 
> [Fix in Cursor](https://cursor.com/open?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9DVVJTT1IiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjA5OWI5YTIzLTYwYzgtNDYwOS1hZjkyLWVkOWM2YzhlZTQ2YiIsImVuY3J5cHRpb25LZXkiOiJ6dDBuQUtuMjByWTI2bHR0ZUVMWnpPb0w4MHY5TVE2OExzT2F5MnZqYzBVIiwiYnJhbmNoIjoicnlhbm0vZml4L2lzc3VlLXdpdGgtc291cmNlbWFwcyJ9LCJpYXQiOjE3NjE1ODQyMTgsImV4cCI6MTc2MjE4OTAxOH0.kbdEUi0ZVTTP7y7qGmH89XW3SYTbh3R4oIZ3Xdc7UjYH11SBl-nO3kl8r0WtTBJchc0m-YENfwsen0Fz78PC9glN3LsG2dTx_cOgbIUPOAMMv45mF27Qvi_uM-2V5X72kA_tiaQ0eLTnJe8vNCCT1HxmWv5LZJqYZSNKhQO8_jKAADe8jG8kVKg9QLWCi2OJvjkUiL3FcunXjqyy0CoVKyeX35IDPGj_H_71rej3Uux18m76-NFoDL3VOm1eeL7kOq_bANvkvt8YHDPiYLuah8jPXtIdCvvk3Z24YgLCjOdKsAe4Pt8MccOetcJNGisgtzSrAK78hqeGLrZwox7dcg) [Fix in Web](https://cursor.com/agents?data=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJ1Z2JvdC12MSJ9.eyJ2ZXJzaW9uIjoxLCJ0eXBlIjoiQlVHQk9UX0ZJWF9JTl9XRUIiLCJkYXRhIjp7InJlZGlzS2V5IjoiYnVnYm90OjA5OWI5YTIzLTYwYzgtNDYwOS1hZjkyLWVkOWM2YzhlZTQ2YiIsImVuY3J5cHRpb25LZXkiOiJ6dDBuQUtuMjByWTI2bHR0ZUVMWnpPb0w4MHY5TVE2OExzT2F5MnZqYzBVIiwiYnJhbmNoIjoicnlhbm0vZml4L2lzc3VlLXdpdGgtc291cmNlbWFwcyIsInJlcG9Pd25lciI6ImN5cHJlc3MtaW8iLCJyZXBvTmFtZSI6ImN5cHJlc3MiLCJwck51bWJlciI6MzI4MjAsImNvbW1pdFNoYSI6ImM3NTM5YzVhOWQyNGU1ZGU1YzcwZTQ2MTZjYTA4OWJmMzYzYzRmNDEifSwiaWF0IjoxNzYxNTg0MjE4LCJleHAiOjE3NjIxODkwMTh9.kQhpgUNB4Gd_z_4l6k2d9hj64u_6zhuWwOrtoqxVW3zebc4QXG0c23paAByTaqvfam9atK_uYOiq4G7Cr4zl-KQPNbXhUhdzLZpDzw4MHK-wMmNWK751l56XMI9tsJXvGlEG7SRsCeCUNrKWLLG4b-OwV50YVzVxFs_ZK65EbjrUZPO_PmGWZ5rHqUZqq63iufpDbFaCZliA3w54nj_HjOh3hIXkAvsT4nejpLPiyMeMiHe4JEmHrJVDT5VvRX3H4iZvO3tyzgjCuu2Y-onTfLj3REL1_HWi4Onlom_vcbP19pXK7KUvvbyE3Qj79tHLbl34MgukZ-8eZxb2Y93uSw)

This took a surgical approach. We:

1. Patch mocha. This reads the source map root at execution time not at patch time
2. Load the scripts and their corresponding sourcemaps
3. Update the source map root path
4. Run the scripts which then reads the root as described in step 1

File: packages/driver/src/cypress/stack_utils.ts [hunk 4]
```diff
@@ -364,12 +336,12 @@ const getSourceDetailsForLine = (projectRoot, line): MessageLineDetail | StackLi
...
   const originalFile = sourceDetails.file
 
-  let relativeFile = stripCustomProtocol(originalFile)
+  let relativeFile = $utils.stripCustomProtocol(originalFile)
 
   if (relativeFile) {
     relativeFile = path.normalize(relativeFile)
 
-    if (relativeFile.includes(projectRoot)) {
+    if (projectRoot !== '/' && relativeFile.includes(projectRoot)) {
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress/stack_utils.ts]: This is fixed now.

File: packages/reporter/src/lib/open-file-in-ide.tsx [hunk 5]
```diff
@@ -12,8 +12,13 @@ interface Props {
 // Catches click events that bubble from children and emits open file events to
 // be handled by the app.
 const OpenFileInIDE: React.FC<Props> = observer((props) => {
+  console.log('props.fileDetails', props.fileDetails)
+
   return (
-    <span className={props.className} onClick={() => events.emit('open:file:unified', props.fileDetails)}>
+    <span className={props.className} onClick={() => {
+      events.emit('open:file:unified', props.fileDetails)
+      console.log('clicked', props.fileDetails)
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/reporter/src/lib/open-file-in-ide.tsx]: These have now been removed.

File: packages/driver/src/cypress.ts [hunk 6]
```diff
@@ -409,6 +410,7 @@ class $Cypress {
       })
       .then(() => {
         this.areSourceMapsAvailable = $sourceMapUtils.areSourceMapsAvailable()
+        this.sourceMapProjectRoot = $sourceMapUtils.sourceMapProjectRoot(this.spec.relative, this.spec.absolute) || Cypress.config('projectRoot')
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress.ts]: This is fixed now.

File: packages/driver/src/cypress/source_map_utils.ts [hunk 7]
```diff
@@ -112,17 +114,91 @@ const destroySourceMapConsumers = () => {
...
+  if (!key) {
+    sourceMapProjectRoot = projectRoot
+
+    return
+  }
+
+  const consumer = sourceMapConsumers[key]
+
+  for (let index = 0; index < consumer.sources.length; index++) {
```
Comment (AtofStryker) [inline packages/driver/src/cypress/source_map_utils.ts]: a for/of array might slightly easier to ready

File: packages/driver/src/cypress/source_map_utils.ts [hunk 8]
```diff
@@ -112,17 +114,91 @@ const destroySourceMapConsumers = () => {
...
 
   sourceMapConsumers = {}
+  sourceMapProjectRoot = ''
 }
 
 const areSourceMapsAvailable = () => {
   return Object.keys(sourceMapConsumers).length > 0
 }
 
+const setSourceMapProjectRoot = (relativePath: string, absolutePath: string, projectRoot: string) => {
```
Comment (AtofStryker) [inline packages/driver/src/cypress/source_map_utils.ts:132]: are you able to add some jsdoc type comments to these functions to get a better idea what the full intend of `setSourceMapProjectRoot` and `getBaseDirectory`. `getBaseDirectory` is fairly clear but it looks like `setSourceMapProjectRoot` has some side effects?

File: packages/driver/src/cypress/source_map_utils.ts [hunk 9]
```diff
@@ -112,17 +114,91 @@ const destroySourceMapConsumers = () => {
...
+const getBaseDirectory = (absolutePath: string, relativePath: string) => {
+  const absNormalized = path.normalize(absolutePath)
+  const relNormalized = path.normalize(relativePath)
+
+  // Start with the directory of the absolute path
+  let dir = path.dirname(absNormalized)
+  let recurse = true
+
+  // Work backwards: check each parent directory
+  while (recurse) {
```
Comment (AtofStryker) [inline packages/driver/src/cypress/source_map_utils.ts]: is there a way we don't have to do this recursively?

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts [hunk 10]
```diff
@@ -0,0 +1,320 @@
...
+
+  SourceMapConsumer.initialize = vi.fn()
+
+  return {
+    SourceMapConsumer,
+  }
+})
+
+// import source_map_utils from '../../../src/cypress/source_map_utils'
```
Comment (AtofStryker) [inline packages/driver/test/unit/cypress/source_map_utils.spec.ts]:
```suggestion
```

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts [hunk 11]
```diff
@@ -0,0 +1,320 @@
...
+  const setupSourceMapConsumer = async (sourceMapUtils: typeof source_map_utils, scriptUrl: string, sources: string[] = ['src/components/Button.tsx']) => {
+    // Call the actual function to set up the consumer (SourceMapConsumer constructor is mocked)
+    const consumer = await sourceMapUtils.initializeSourceMapConsumer({ fullyQualifiedUrl: scriptUrl }, { sources })
+
+    return consumer
+  }
+
+  // Helper function to run tests with Windows path behavior
+  const withWindowsPaths = async (testFn: (sourceMapUtils: typeof source_map_utils) => Promise<void> | void) => {
+    vi.resetModules()
```
Comment (AtofStryker) [inline packages/driver/test/unit/cypress/source_map_utils.spec.ts]: is it possible to remove the `resetModules` to a `beforeEach` hook to make the side effect clearer?

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts [hunk 12]
```diff
@@ -0,0 +1,320 @@
...
+        ...pathMock.posix,
+        posix: pathMock.posix,
+        win32: pathMock.win32,
+      }
+    })
+
+    // Re-import the module to get the mocked path
+    const { default: sourceMapUtils } = await import('../../../src/cypress/source_map_utils')
+
+    await testFn(sourceMapUtils)
```
Comment (AtofStryker) [inline packages/driver/test/unit/cypress/source_map_utils.spec.ts]: should we wrap this in a try/catch/finally to make sure the mock is always undone in the case the test fails?

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.js [hunk 13]
```diff
@@ -0,0 +1,43 @@
+const wp = require('@cypress/webpack-preprocessor')
```
Comment (AtofStryker) [inline system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.js]: can we write an `mjs` config here instead as we start to move more to ECMAScript? Not a deal breaker by any means but would be nice!

Comment (AtofStryker) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.js]: same for the other added configs as well?

Comment (ryanthemanuel) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.js]: Done: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts (hunk 12 above)
Comment (ryanthemanuel) [reply packages/driver/test/unit/cypress/source_map_utils.spec.ts]: Done: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts (hunk 11 above)
Comment (ryanthemanuel) [reply packages/driver/test/unit/cypress/source_map_utils.spec.ts]: Done: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts (hunk 10 above)
Comment (ryanthemanuel) [reply packages/driver/test/unit/cypress/source_map_utils.spec.ts]: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/src/cypress/source_map_utils.ts (hunk 9 above)
Comment (ryanthemanuel) [reply packages/driver/src/cypress/source_map_utils.ts]: I think this is a little cleaner: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/src/cypress/source_map_utils.ts (hunk 8 above)
Comment (ryanthemanuel) [reply packages/driver/src/cypress/source_map_utils.ts:132]: Added comments: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/src/cypress/source_map_utils.ts (hunk 7 above)
Comment (ryanthemanuel) [reply packages/driver/src/cypress/source_map_utils.ts]: [`250dc88` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/250dc887771b73447641d8bcd6f9f6dd0ca2ad86)

File: packages/driver/test/unit/cypress/source_map_utils.spec.ts [hunk 14]
```diff
@@ -0,0 +1,324 @@
...
+
+    it('should return true when source map consumers exist', async () => {
+      withLinuxPaths(async (sourceMapUtils) => {
+        await setupSourceMapConsumer(sourceMapUtils, '/project/test.spec.js')
+
+        const result = sourceMapUtils.areSourceMapsAvailable()
+
+        expect(result).toBe(true)
+      })
+    })
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/test/unit/cypress/source_map_utils.spec.ts:115]: [`48980a6` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/48980a68926a576b8dc89648add95b5d1d1612c8)

File: packages/driver/src/cypress/mocha.ts [hunk 15]
```diff
@@ -622,7 +623,7 @@ const patchSuiteHooks = (specWindow, config) => {
         let invocationStack = hook.invocationDetails?.stack
 
         if (!hook.invocationDetails) {
-          const invocationDetails = $stackUtils.getInvocationDetails(specWindow, config)!
+          const invocationDetails = $stackUtils.getInvocationDetails(specWindow, $sourceMapUtils.getSourceMapProjectRoot())!
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress/mocha.ts:626]: This is not true they are not invoked during the override call. They are invoked at script evaluation.

File: packages/driver/src/cypress/script_utils.ts [hunk 16]
```diff
@@ -100,6 +107,6 @@ export default {
     // for other browsers, we get the contents of the scripts so that we can
     // extract and utilize the source maps for better errors and code frames.
     // we then eval the script contents to run them
-    return runScriptsFromUrls(specWindow, scripts)
+    return runScriptsFromUrls(specWindow, scripts, projectRoot, specRelativePath, specAbsolutePath)
```
[the remark this answers is not in the document]
Comment (ryanthemanuel) [reply packages/driver/src/cypress/script_utils.ts:114]: [`46e22c7` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/46e22c78e346a105dc865a66c510692cb68948f4)

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs [hunk 17]
```diff
@@ -0,0 +1,43 @@
+import wp from '@cypress/webpack-preprocessor'
```
Comment (AtofStryker) [inline system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs:1]:
```suggestion
import { defineConfig } from 'cypress'
import wp from '@cypress/webpack-preprocessor'
```

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+import path from 'node:path'
+
+module.exports = {
```
Comment (AtofStryker) [inline system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs]:
```suggestion
export default defineConfig({
```

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs [hunk 19]
```diff
@@ -0,0 +1,43 @@
...
+          },
+        },
+      }
+
+      on('file:preprocessor', wp(options))
+
+      return config
+    },
+  },
+}
```
Comment (AtofStryker) [inline system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs]:
```suggestion
})
```

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs [hunk 20]
```diff
@@ -0,0 +1,43 @@
...
+import path from 'node:path'
+
+module.exports = {
+  numTestsKeptInMemory: 0,
+  e2e: {
+    supportFile: false,
+    setupNodeEvents (on, config) {
+      const options = {
+        webpackOptions: {
+          context: path.resolve(__dirname, 'cypress'),
```
Comment (AtofStryker) [inline system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs:16]: The `__dirname` built in isn't available in a strict ESM context so you will likely need to use this:

```js
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```

File: system-tests/projects/sourcemaps/cypress-disabled.config.mjs [hunk 21]
```diff
@@ -0,0 +1,16 @@
+import path from 'node:path'
+import os from 'node:os'
+import cypressPreprocessor from './cypress-preprocessor-disabled.config.mjs'
+
+export default {
```
Comment (AtofStryker) [inline system-tests/projects/sourcemaps/cypress-disabled.config.mjs]: do we need to wrap in `defineConfig` or is the plan syntax acceptable? I can't remember tbh

File: system-tests/projects/sourcemaps/cypress-preprocessor-enabled-updated-sourcemap-root.config.mjs [hunk 22]
```diff
@@ -0,0 +1,33 @@
+import webpack from '@cypress/webpack-preprocessor'
+import path from 'node:path'
+
+export default (on, config) => {
+  const options = {
+    webpackOptions: {
+      context: path.resolve(__dirname, 'cypress'),
```
Comment (AtofStryker) [inline system-tests/projects/sourcemaps/cypress-preprocessor-enabled-updated-sourcemap-root.config.mjs:11]: same comment as above on `__dirname`

File: system-tests/projects/sourcemaps/cypress-disabled.config.mjs (hunk 21 above)
Comment (ryanthemanuel) [reply system-tests/projects/sourcemaps/cypress-disabled.config.mjs]: I think you can do either.

Comment (ryanthemanuel) [reply system-tests/projects/sourcemaps/cypress-disabled.config.mjs]: `defineConfig` just gives you ts helpers, etc. i believe

File: system-tests/projects/sourcemaps/cypress-preprocessor-enabled-updated-sourcemap-root.config.mjs (hunk 22 above)
Comment (ryanthemanuel) [reply system-tests/projects/sourcemaps/cypress-preprocessor-enabled-updated-sourcemap-root.config.mjs:11]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

File: system-tests/projects/sourcemaps/cypress-disabled.config.mjs (hunk 21 above)
Comment (ryanthemanuel) [reply system-tests/projects/sourcemaps/cypress-disabled.config.mjs]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs (hunk 20 above)
Comment (ryanthemanuel) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs:16]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs (hunk 19 above)
Comment (ryanthemanuel) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs (hunk 18 above)
Comment (ryanthemanuel) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

File: system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs (hunk 17 above)
Comment (ryanthemanuel) [reply system-tests/projects/runner-e2e-specs-new-sourcemap-root/cypress.config.mjs:1]: [`02d00f5` (#32820)](https://github.com/cypress-io/cypress/pull/32820/commits/02d00f514c25cdee6bf2ec6c0353c406b58c7f07)

**Review by AtofStryker — APPROVED** [review]
