### PR TITLE
fix(ff): use fixed inputFPS instead of vfr to prevent dropped frames

### LINKED ISSUE #6369: Dropped frames in video recording from firefox
### Current behavior:
- video recordings in firefox that visit a new domain or refresh `window.top` during test run will experience dropped frames.

### Desired behavior:
- entire test run is captured regardless of top navigation

### Versions

`4.0.0`

### PR DESCRIPTION
**Pull request by kuceb**
- use static `inputFPS(18)` instead of variable framerate when capturing frames from webm input

- Closes #6369

### PR Tasks

- [NO] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/video_capture.js [hunk 1]
```diff
@@ -167,10 +167,19 @@ module.exports = {
         if (options.webmInput) {
           cmd
           .inputFormat('webm')
-          .outputOption('-vsync vfr')
```
Comment (flotwig) [inline packages/server/lib/video_capture.js]: lol

**Review by flotwig — APPROVED** [review]
