### PR TITLE
fix: screenshot() times out when the main Cypress tab is not focused

### LINKED ISSUE #5016: Cypress cy.screenshot() timeout during `cypress run`
### Current behavior:
All of our tests pass locally, but when running the Codeship CI we get errors for a few tests.

The error during Codeship CI builds: `CypressError: cy.screenshot() timed out waiting '30000ms' to complete.`

### Desired behavior: 
All tests pass in Codeship CI

### Steps to reproduce: 

For our app the reproduction is running the `ci:codeship` command runs which calls `cy:record`
`
    "cy:record": "cypress run --record --key *key* --config video=false",
    "ci:codeship": "start-server-and-test start http://localhost:5000 cy:record"
`

I'm not exactly sure how to reproduce this other than creating a Codeship Basic app and attempting to run tests there. I have seen a few other issues point to a problem with how Cypress and Codeship interact. 

### Versions

Cypress version: 3.4.1

Sidenote: We are using the `cypress-autorecord` package, but it doesn't seem like this is involved.

### PR DESCRIPTION
**Pull request by cacieprins**
- Closes https://github.com/cypress-io/cypress/issues/5016

### Additional details

When the Renderer for a given Chromium tab is paused, CDP commands that query that renderer hang until the renderer is unpaused. Unfortunately, this causes issues with `cy.screenshot()` in both run and open mode, if the main Cypress tab becomes unfocused. This happens when an anchor is clicked within a test that has a `target` of `_blank`, among other scenarios. To keep tests running, we timeout on capturing a screenshot after 30 seconds.

When in `run` mode, this causes issues when a test assertion fails after a new tab has been opened. By default, Cypress takes a screenshot when an assertion fails. If this screenshot times out, the original assertion failure is replaced by the screenshot timeout error.

To fix this, we now attempt to activate the main Cypress tab in Chromium browsers before taking a screenshot. First, we request the extension to activate the main tab. This can fail if the Cypress extension has been disabled. As a last resort, the `Page.bringToFront` command is issued to CDP. This is less desirable, as it causes the browser to steal focus.

### Steps to test

See: `./system-tests/projects/config-screenshot-on-failure-enabled`. To test with the extension disabled, modify `./system-tests/test/issue_5016_spec.js` and pass both `noExit: true` and `headed: true`. Once the test completes, disable the extension in `chrome://extensions/` and reload the main Cypress tab.

### PR Tasks

- [X] Have tests been added/updated?
- [X] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/5735
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/extension/app/v2/background.js [hunk 1]
```diff
@@ -107,6 +107,11 @@ const connect = function (host, path, extraOpts) {
     return Promise.try(() => {
       return automation[method].apply(automation, args.concat(respond))
     }).catch((err) => {
+      ws.emit('automation:push:request', 'debug', {
```
Comment (ryanthemanuel) [inline packages/extension/app/v2/background.js]: Is this temporary?

Comment (cacieprins) [reply packages/extension/app/v2/background.js]: Yep, missed removing it with the previous commit. Thanks for the catch!

**Review by ryanthemanuel — APPROVED** [review]

File: system-tests/test/issue_5016_spec.js [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+describe('e2e issue 5016 - screenshot times out after clicking target _blank', function () {
+  systemTests.setup()
+
+  systemTests.it('fails but does not timeout taking screenshot', {
+    project: 'config-screenshot-on-failure-enabled',
+    sanitizeScreenshotDimensions: true,
+    snapshot: true,
+    expectedExitCode: 1,
+    browser: '!webkit',
```
Comment (AtofStryker) [inline system-tests/test/issue_5016_spec.js:11]: I only run into the issue in `chrome`. `firefox` and `electron` both seem to work as expected prior to the fix. 
```suggestion
    browser: 'chrome',
```

Comment (AtofStryker) [reply system-tests/test/issue_5016_spec.js:11]: could also be good to just exercise the behavior since it is a change to CDP automation itself and make sure the behavior doesn't regress in those browsers for whatever reason

**Review by AtofStryker — APPROVED** [review]
