### PR TITLE
Fix: skip sending stdout on PUT /instances

### LINKED ISSUE #7548: Running Cypress in parallel with debug cypress:* cannot complete because 413 responses from cypress servers
### Current behavior:

While trying to debug other issues we have had to run cypress in debug mode however this causes cypress to abort it's test run due to a 413 response from the cypress servers. 
This does not happen when not running in debug mode.

Start task:
```
set DEBUG=cypress:*
npx cypress run --tag debug --config baseUrl=<baseUrl>,video=false --config-file cypress.ci.json --headless --record --group 'Windows/Electron' --parallel --ci-build-id $(Release.DeploymentID) --specs "<specs..>"
```
Settings: 
```json
{
  "viewportWidth":1280,
  "viewportHeight":720,
  "env": {
    "RETRIES": 3
  },
  "numTestsKeptInMemory": 5,
  "video": true,
  "videoCompression": 0,
  "videoUploadOnPasses": false,
  "reporter":"junit",
  "reporterOptions": {
    "mochaFile": "results/TEST-output-[hash].xml",
    "toConsole": false
  },
  "ignoreTestFiles": [
    "*.ts",
    "*.js"
  ],
  "projectId": "xyz"
}
```
[Debug run logs](https://github.com/cypress-io/cypress/files/4710467/Cypress_run_logs.log)

### Desired behavior:
The tests to finish normally.

### Versions

Cypress: version 4.7
Platform: Azure DevOps pipelines
OS: Windows 10
Browser: Electron

### PR DESCRIPTION
**Pull request by tgriesser**
- Closes #7548

### User facing change log

- Dashboard upload of `stdout` is deferred until after the video/image uploads complete

### Additional details

`stdout` does not need to be sent on both `PUT /instances/:id` and `PUT /instances/:id/stdout`. Sending in the first could cause the request to the dashboard to fail if the payload size is too large, which will prevent the run from completing, prevent any asset uploads, etc.

### How has the user experience changed?

Stdout will be delayed from appearing in the dashboard until after any assets have uploaded

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/modes/record.js [hunk 1]
```diff
@@ -228,7 +227,7 @@ const updateInstance = (options = {}) => {
       error,
       video,
       hooks,
-      stdout,
+      stdout: null,
```
Comment (flotwig) [inline packages/server/lib/modes/record.js:230]: does the schema prevent it from being `undefined`?

Comment (tgriesser) [reply packages/server/lib/modes/record.js:230]: Yep, has to be string or null

Comment (brian-mann) [reply packages/server/lib/modes/record.js:230]: let's leave a comment indicating why this change is necessary

Comment (brian-mann) [inline packages/server/lib/modes/record.js:230]:
```suggestion
      stdout: null, // don't send stdout with the instance payload to prevent requests that are too large. stdout will later get uploaded separately anyway.
```
