### PR TITLE
fix: include event emitter types from cypress types

### LINKED ISSUE #14991: Cypress types need refactoring
Cypress v6.4.0

I have described how to get rid of the global Cypress objects like `cy`, `Cypress`, assertion methods, and Mocha's functions in the blog post https://glebbahmutov.com/blog/local-cypress/ While looking at the types I have noticed a few weird things:

- the `cypress-global-vars.d.ts` imports the EventEmitter types, thus including the type `NodeEventEmitter`, but that type is already used in `cypress.d.ts` without an explicit import
 
Thus, to work around these things I had to repeat a bunch of code from Cypress types, see https://github.com/bahmutov/local-cypress/blob/main/index.ts

Also just noticed that our `on` Action type does not return the object, thus this code is invalid but runs just fine

```js
// @ts-check
/// <reference types="cypress" />
Cypress.on('test:before:run', () => {
  console.log('before running a test')
}).on('test:after:run', () => {
  console.log('after running a test')
})
```

Screen Shot 2021-02-09 at 9 53 38 AM

So we should fix the `Action` interface to return `this` I think

## Proposal

Rejigger the type imports a little bit. The end-user will not notice a difference, but the types will actually make more sense and will be easier to work with if one wants to avoid global type clashes.

## Outside of the scope

- the top-level type is a union of cypress and EventEmitter - which is confusing to the user I believe. This is done in https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress-global-vars.d.ts

Screen Shot 2021-02-09 at 9 22 17 AM

We can merge the type in our code and have the `cy` be just of type `cy`, same for the top-level `Cypress` type

I have opened https://github.com/cypress-io/cypress/issues/15022 for this part

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #14991 by adding including the event emitter definition where it is used first

### User facing changelog

Types no longer complain when you chain event listeners like

```js
Cypress
  .on('test:before:run', () => {
    console.log('before running a test')
  })
  .on('test:after:run', () => {
    console.log('after running a test')
  })
```

### Additional details

Notice the types returned `void` while the test happily runs. Also moved the emitter reference line into the file where it was used.

### How has the user experience changed?

No more type errors

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: cli/types/cypress.d.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 /// <reference path="./cypress-npm-api.d.ts" />
+/// <reference path="./cypress-eventemitter.d.ts" />
```
Comment (bahmutov) [inline cli/types/cypress.d.ts:2]: since we are using NodeEventEmitter type here

**Review by sainthkh — COMMENTED** [review]
I became curious that `on` really returns `Cypress`. So, I tested with the code below:

```js
it('t', () => {
  console.log(Cypress
  .on('test:before:run', () => {
    console.log('before running a test')
  }).version)
})
```

And it returned `6.4.0` correctly. 

----

In #14991, `const cy: Cypress.cy & EventEmitter` was mentioned but not covered in this PR. 

I tried extending `EventEmitter` on `Cypress.cy` definition like `interface cy extends Chainable<undefined>, EventEmitter {}` but failed because of the clash in property types. It's [an open issue since 2017](https://github.com/microsoft/TypeScript/issues/16936).

Maybe, the easiest solution for this would be adding `type cy = Cypress.cy & EventEmitter` above `cy` definition and set the type with it.

**Comment by bahmutov** [comment]
Yup @sainthkh it returns `Cypress` - I think that's fine for now, we solve some problems first and leave any other refactoring for another day.

I tried `interface cy extends Chainable<undefined>, EventEmitter` too with same no luck, so again will punt on it

**Comment by bahmutov** [comment]
Also, I do find it funny that you can combine clashing types when declaring a variable like `const cy: Cypress.cy & EventEmitter`, but not when extending an interface.

**Comment by bahmutov** [comment]
I will split #14991 to have the type merge in a separate issue
