### PR TITLE
fix: do not assume valid file info in error stack line

### LINKED ISSUE #7915: TypeError: Cannot read property 'replace' of undefined at stripCustomProtocol
When my automated script lands on a new page, the script fails and when I print the error to console, I get the error in the subject line.

image

### Desired behavior:

For the test to continue on and finish successfully like it has in the past.

### Test code to reproduce

```js
describe('Edit a job', () => {
  beforeEach(() => {
    Cypress.on('window:before:load', (win: any) => { win.usabilla_live = win.usabilla_live || function () { }; });

  });
  it('Edit a job Subscriptions', function () {
    const env = Cypress.env();
    cy.clearCookies();
    Cypress.config('60000');
    Cypress.config('60000');

    cy.request({
      method: "POST",
      url: "https://www.dice.com//app/manage-jobs/active/1?pageSize=25&order=job_mod_date_desc/ajaxLogin",
      body: {
        username: 'essamtest2@dice.com',
        password: 'xxxxxxxx'
      },
      headers: {
        Accept: "application/json",
        "Content-Type": "application/x-www-form-urlencoded"
      }
    });
cy.visit('https://www.dice.com//app/manage-jobs/active/1?pageSize=25&order=job_mod_date_desc');

    cy.wait(10000);

    cy.get('body').then(($body) => {

      if ($body.find('.usabilla__overlay > iframe').length == 0) {
        //cy.wait(1000);
        cy.log('usabilla not found');
        cy.log('inside if');
      } else {
        cy.get(".usabilla__overlay > iframe").then(frame => {
          const iframe = frame.contents();
          const close = iframe.find("#close");
          cy.wrap(close).click();
        });
      }
    });
  }
  pageSize = 25 & order=job_mod_date_desc');

  cy.get('[data-cy=active]').click();
  cy.get('.job-list-item:first > .mx-auto > .ml-1 > .w-100').click();
  cy.get('.col-md-4 > .actions-contianer > .btn-secondary').click();
  cy.get('.border-bottom > :nth-child(1) > .btn').click();
```

### Versions

Cypress version: 4.10.0, Window 10.

### LINKED ISSUE #9106: Stack trace for app's error should not include "Open in IDE" messages for URL links
Cypress v5.5.0

Reproduction case in https://github.com/cypress-io/cypress-example-todomvc/tree/stack-problem file `cypress/integration/spec.js`

```
npm install
npm run dev
```

Starts local server, opens Cypress

## First, the good case

If a Cypress command fails (as it does in this case), the all is good, we show a good error and a good stack trace.

Screen Shot 2020-11-05 at 10 08 19 AM

I can click on the file link (blue) or on the error link in the stack trace and go right to the location. Nice. Very happy.

I can find the `error-stack.tsx` code and copy the Error object it receives to show the stack and the files linked. Here is the error object JSON (I used a breakpoint and `copy(err)` to copy it)

```json
{
  "name": "AssertionError",
  "message": "Timed out retrying: Expected to find element: `.new-todo`, but never found it.",
  "stack": "AssertionError: Timed out retrying: Expected to find element: `.new-todo`, but never found it.\n    at Context.eval (http://localhost:8888/__cypress/tests?p=cypress/integration/spec.js:103:8)",
  "sourceMappedStack": "AssertionError: Timed out retrying: Expected to find element: `.new-todo`, but never found it.\n    at Context.eval (webpack:///cypress/integration/spec.js:6:8)",
  "parsedStack": [
    {
      "message": "AssertionError: Timed out retrying: Expected to find element: `.new-todo`, but never found it.",
      "whitespace": ""
    },
    {
      "function": "Context.eval",
      "fileUrl": "http://localhost:8888/__cypress/tests?p=cypress/integration/spec.js",
      "originalFile": "webpack:///cypress/integration/spec.js",
      "relativeFile": "cypress/integration/spec.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/cypress/integration/spec.js",
      "line": 6,
      "column": 8,
      "whitespace": "    "
    }
  ],
  "docsUrl": "",
  "templateType": "",
  "codeFrame": {
    "line": 6,
    "column": 8,
    "originalFile": "cypress/integration/spec.js",
    "relativeFile": "cypress/integration/spec.js",
    "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/cypress/integration/spec.js",
    "frame": "  4 |   it('adds todos', () => {\n  5 |     cy.visit('/')\n> 6 |     cy.get('.new-todo').type('write code{enter}').type('write tests{enter}')\n    |        ^\n  7 |     cy.get('.todo-list li')\n  8 |     .should('have.length', 2)\n  9 |     .first()",
    "language": "js"
  }
}
```

Nice, then `fileUrl` was "http://localhost:8888/__cypress/tests?p=cypress/integration/spec.js" and it was correctly mapped back to the source file on disk "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/cypress/integration/spec.js". Super.

## Second - the wrong case

Now, let's do something else. Instead of a Cypress command failing, let the application under test throw an error. For example in the file `js/utils.js` let's randomly add the following code line 9. Neither `a` nor `b` exists.

```
a = b
```

We run the test again and see the application error. good.

Screen Shot 2020-11-05 at 10 15 49 AM

Let's open the error stack trace. Well now it makes little sense

Screen Shot 2020-11-05 at 10 16 33 AM

We see blue underlined links to `js/utils.js` file - but clicking on them does nothing. Let's see the error object

```json
{
  "name": "ReferenceError",
  "message": "The following error originated from your application code, not from Cypress.\n\n  > b is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.",
  "stack": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n  > b is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n    at http://localhost:8888/js/utils.js:9:3\n    at http://localhost:8888/js/utils.js:60:3\nFrom previous event:\n    at run (http://localhost:8888/__cypress/runner/cypress_runner.js:169474:21)\n    at $Cy.cy.<computed> [as visit] (http://localhost:8888/__cypress/runner/cypress_runner.js:169931:11)\n    at Context.runnable.fn (http://localhost:8888/__cypress/runner/cypress_runner.js:170155:21)\n    at callFn (http://localhost:8888/__cypress/runner/cypress_runner.js:104227:21)\n    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8888/__cypress/runner/cypress_runner.js:104214:7)\n    at http://localhost:8888/__cypress/runner/cypress_runner.js:175754:28\nFrom previous event:\n    at Object.onRunnableRun (http://localhost:8888/__cypress/runner/cypress_runner.js:175742:17)\n    at $Cypress.action (http://localhost:8888/__cypress/runner/cypress_runner.js:166291:28)\n    at Test.Runnable.run (http://localhost:8888/__cypress/runner/cypress_runner.js:174128:13)\n    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:8888/__cypress/runner/cypress_runner.js:104886:10)\n    at http://localhost:8888/__cypress/runner/cypress_runner.js:105012:12\n    at next (http://localhost:8888/__cypress/runner/cypress_runner.js:104795:14)\n    at http://localhost:8888/__cypress/runner/cypress_runner.js:104805:7\n    at next (http://localhost:8888/__cypress/runner/cypress_runner.js:104707:14)\n    at http://localhost:8888/__cypress/runner/cypress_runner.js:104773:5\n    at timeslice (http://localhost:8888/__cypress/runner/cypress_runner.js:98699:27)",
  "sourceMappedStack": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n    > b is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n    at <unknown> (http://localhost:8888/js/utils.js:9:4)\n    at <unknown> (http://localhost:8888/js/utils.js:60:4)\nFrom previous event:\n    at run (http://localhost:8888/__cypress/runner/cypress_runner.js:169474:22)\n    at $Cy.cy.<computed> [as visit] (http://localhost:8888/__cypress/runner/cypress_runner.js:169931:12)\n    at Context.runnable.fn (http://localhost:8888/__cypress/runner/cypress_runner.js:170155:22)\n    at callFn (http://localhost:8888/__cypress/runner/cypress_runner.js:104227:22)\n    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8888/__cypress/runner/cypress_runner.js:104214:8)\n    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:175754:29)\nFrom previous event:\n    at Object.onRunnableRun (http://localhost:8888/__cypress/runner/cypress_runner.js:175742:18)\n    at $Cypress.action (http://localhost:8888/__cypress/runner/cypress_runner.js:166291:29)\n    at Test.Runnable.run (http://localhost:8888/__cypress/runner/cypress_runner.js:174128:14)\n    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:8888/__cypress/runner/cypress_runner.js:104886:11)\n    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:105012:13)\n    at next (http://localhost:8888/__cypress/runner/cypress_runner.js:104795:15)\n    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:104805:8)\n    at next (http://localhost:8888/__cypress/runner/cypress_runner.js:104707:15)\n    at <unknown> (http://localhost:8888/__cypress/runner/cypress_runner.js:104773:6)\n    at timeslice (http://localhost:8888/__cypress/runner/cypress_runner.js:98699:28)",
  "parsedStack": [
    {
      "message": "ReferenceError: The following error originated from your application code, not from Cypress.",
      "whitespace": ""
    },
    {
      "message": "",
      "whitespace": ""
    },
    {
      "message": "  > b is not defined",
      "whitespace": "  "
    },
    {
      "message": "",
      "whitespace": ""
    },
    {
      "message": "When Cypress detects uncaught errors originating from your application it will automatically fail the current test.",
      "whitespace": ""
    },
    {
      "message": "",
      "whitespace": ""
    },
    {
      "message": "This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.",
      "whitespace": ""
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/js/utils.js",
      "originalFile": "http://localhost:8888/js/utils.js",
      "relativeFile": "localhost:8888/js/utils.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/js/utils.js",
      "line": 9,
      "column": 4,
      "whitespace": "    "
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/js/utils.js",
      "originalFile": "http://localhost:8888/js/utils.js",
      "relativeFile": "localhost:8888/js/utils.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/js/utils.js",
      "line": 60,
      "column": 4,
      "whitespace": "    "
    },
    {
      "message": "From previous event:",
      "whitespace": ""
    },
    {
      "function": "run",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 169474,
      "column": 22,
      "whitespace": "    "
    },
    {
      "function": "$Cy.cy.<computed> [as visit]",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 169931,
      "column": 12,
      "whitespace": "    "
    },
    {
      "function": "Context.runnable.fn",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 170155,
      "column": 22,
      "whitespace": "    "
    },
    {
      "function": "callFn",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104227,
      "column": 22,
      "whitespace": "    "
    },
    {
      "function": "Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104214,
      "column": 8,
      "whitespace": "    "
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 175754,
      "column": 29,
      "whitespace": "    "
    },
    {
      "message": "From previous event:",
      "whitespace": ""
    },
    {
      "function": "Object.onRunnableRun",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 175742,
      "column": 18,
      "whitespace": "    "
    },
    {
      "function": "$Cypress.action",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 166291,
      "column": 29,
      "whitespace": "    "
    },
    {
      "function": "Test.Runnable.run",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 174128,
      "column": 14,
      "whitespace": "    "
    },
    {
      "function": "Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104886,
      "column": 11,
      "whitespace": "    "
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 105012,
      "column": 13,
      "whitespace": "    "
    },
    {
      "function": "next",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104795,
      "column": 15,
      "whitespace": "    "
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104805,
      "column": 8,
      "whitespace": "    "
    },
    {
      "function": "next",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104707,
      "column": 15,
      "whitespace": "    "
    },
    {
      "function": "<unknown>",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 104773,
      "column": 6,
      "whitespace": "    "
    },
    {
      "function": "timeslice",
      "fileUrl": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "originalFile": "http://localhost:8888/__cypress/runner/cypress_runner.js",
      "relativeFile": "localhost:8888/__cypress/runner/cypress_runner.js",
      "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/__cypress/runner/cypress_runner.js",
      "line": 98699,
      "column": 28,
      "whitespace": "    "
    }
  ],
  "docsUrl": [
    "https://on.cypress.io/uncaught-exception-from-application"
  ],
  "templateType": ""
}
```

Notice the parsed stack line

```
{
  "function": "<unknown>",
  "fileUrl": "http://localhost:8888/js/utils.js",
  "originalFile": "http://localhost:8888/js/utils.js",
  "relativeFile": "localhost:8888/js/utils.js",
  "absoluteFile": "/Users/gleb/git/cypress-example-todomvc/localhost:8888/js/utils.js",
  "line": 9,
  "column": 4,
  "whitespace": "    "
}
```

Hmm, the "absoluteFile" value makes no sense here and should not be here.

## Proposal 

Stricter filter out stack lines where the file does not exist or cannot be found.

### PR DESCRIPTION
**Pull request by bahmutov**
* Closes #7915
* Closes #9106

### Additional details
* no more file open links for stack lines without `absoluteFile` property. So we don't even show "open" for `http:/...` (which does not work anyway)

### How has the user experience changed?
The original error that is causing the crash is shown, not our "cannot replace" error

Scripts without local file no longer have clickable links

### PR Tasks

* [x] Have tests been added/updated?
* [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cypress/stack_utils.js [hunk 1]
```diff
@@ -216,14 +220,23 @@ const getSourceDetailsForLine = (projectRoot, line) => {
 
   const sourceDetails = getSourceDetails(generatedDetails)
   const originalFile = sourceDetails.file
+
+  if (!originalFile) {
+    // this is an edge case: could not parse the stack trace
+    // let's not warn about it, but at least allow the user
+    // to see the original error by being defensive about it
+    /* eslint-disable-next-line no-console */
+    console.warn(`Could not get the original source file from line "${line}"`)
```
Comment (chrisbreiding) [inline packages/driver/src/cypress/stack_utils.js:229]: I don't think we need to output this to the console. There's nothing the user can do about it, so it's just adding noise to the console output.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/src/cypress/stack_utils.js (hunk 1 above)
Comment (bahmutov) [reply packages/driver/src/cypress/stack_utils.js:229]: it is so much easier for the user to report when complaining that their stack trace is missing :) But sure, I can remove it. By the way, we never use `debug` clientside really

Comment (chrisbreiding) [reply packages/driver/src/cypress/stack_utils.js:229]: Their stack trace won't be missing. The only consequence is that any lines we can't get the source file for won't be open-able by IDE.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]
The [stack traces in the reporter](https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/errors/error-stack.tsx#L44) need to be updated so that if the file details don't include the absolute file, it doesn't show the file path as open-able.

**Comment by bahmutov** [comment]
I opened https://github.com/cypress-io/cypress/issues/9106 to make sure the stack is parsed and displayed correctly in this case, since right now it seems incorrect.

File: packages/driver/src/cypress/stack_utils.js (hunk 1 above)
Comment (bahmutov) [reply packages/driver/src/cypress/stack_utils.js]: updated

**Review by chrisbreiding — APPROVED** [review]
Very nice
