### PR TITLE
fix: remove unnecessary eventemitter2 type definitions from cy, Cypress

### LINKED ISSUE #20556: Why can I use cy.waitFor()?
### Current behavior

I noticed that I can use `cy.waitFor(string)` to wait for a cypress alias.  I can't find any documentation on the matter. While there is a good page for `cy.wait(string)` (https://docs.cypress.io/api/commands/wait). While this oddly seems to work whilst waiting for an API stub to resolve. I'm not sure if it is the expected behavior for `wait()`. 

My IDE tells me that `cy.waitFor()` is a valid function to use. I just don't think it is. It looks like it's wrongly exposed in the typing files.

image

### Desired behavior

I would not expect the waitFor() function to show in my IDE as a possible method. Since it is not described in the documentation. OR it should be described in the documentation with the intended behavior.

### Test code to reproduce

Just write `cy.wiat` in any IDE enabled with code hinting and typescript for cypress.

### Cypress Version

8.1.0.

### Other

Or this all has to do with my IDE setup, although I can't imagine it is since it happens with multiple (if not all) team members...

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #20556

### User facing changelog

Remove unnecessary `eventemitter2` type definitions from `cy` and `Cypress`.

### Additional details
- Why was this change necessary? => Remove undocumented `eventemitter2` definitions from `cy` and `Cypress`. Especially, `cy.waitFor` is really confusing with `cy.wait` for beginners.
- What is affected by this change? => N/A
- Any implementation details to explain? => Created a new interface and cherry-picked the definitions. 

### How has the user experience changed?

```ts
cy.waitFor() // Before: type passes. After: Type fails.
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: cli/types/tests/actions.ts [hunk 1]
```diff
@@ -87,3 +87,17 @@ namespace CypressActionCommandOptionTests {
   cy.get('el').click({scrollBehavior: false})
   cy.get('el').click({scrollBehavior: true}) // $ExpectError
 }
+
+namespace CyEventEmitterTests {
```
Comment (tbiethman) [inline cli/types/tests/actions.ts:91]: Can we put a comment here (or alongside the types themselves) explaining why we'd expect errors for `waitFor`/`prependListener`? Without context, these assertions seem a little random.

File: cli/types/cypress-eventemitter.d.ts [hunk 2]
```diff
@@ -1,7 +1,23 @@
...
+  (event: event | eventNS, listener: ListenerFn, options?: boolean|OnOptions): this|Listener
+}
+
+interface CyEventEmitter {
+  once: CyActions
+  on: CyActions
+  off: CyActions
+  emit: EventEmitter2['emit']
+  removeListener: EventEmitter2['removeListener']
+  removeAllListeners: EventEmitter2['removeAllListeners']
```
Comment (tbiethman) [inline cli/types/cypress-eventemitter.d.ts:20]: Our docs say that Cypress/cy are "standard Node event emitters": https://docs.cypress.io/api/events/catalog-of-events#Binding-to-Events

I'm wondering if we need to either:
* Change the wording there if we only intend to support a subset of the API
* Add more functions here to align with what [Node's event emitter](https://nodejs.org/dist/latest-v16.x/docs/api/events.html) provides, like `addListener`. The other missing APIs are probably less frequently used, but it's hard to say.

File: cli/types/tests/actions.ts (hunk 1 above)
Comment (sainthkh) [reply cli/types/tests/actions.ts:94]: I wrote the reason like below:

```js
// `waitFor` doesn't exist in Node EventEmitter 
// and it confuses the users with `cy.wait`
```

File: cli/types/cypress-eventemitter.d.ts (hunk 2 above)
Comment (sainthkh) [reply cli/types/cypress-eventemitter.d.ts]: I decided to change the type to `Omit<EventEmitter2, 'waitFor'>`.

Because other functions are harmless, they're really unlikely to be used in the real world cases, though.

**Review by ryanthemanuel — APPROVED** [review]
