### PR TITLE
Reconnect to CDP on WebSocket failure

### LINKED ISSUE #5685: WebSocket is not open: readyState 3 (CLOSED) error when watching test files
### Current behavior:

I edited and saved a test file and got this error printed to the Command Log. 

```
WebSocket is not open: readyState 3 (CLOSED)
```

The error did not disappear upon refresh / reload. I had to kill the Cypress process and restart. Was fixed after this.

Screen Shot 2019-11-12 at 12 58 59 PM

Screen Shot 2019-11-12 at 12 59 11 PM copy

### Steps to reproduce: (app code and test code)

Unfortunately this did not happen again, so I don't know what may have caused this. Documenting for anyone that captures more DEBUG logs in the future. 

### Versions

3.6.1

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5685 

### User facing changelog

- Fixed an issue where using Chromium-family browsers could cause Cypress to throw a "WebSocket is not open: readyState 3" error under certain conditions.

### Additional details

- added reconnection logic for the CRI
- commands received while not connected will be enqueued and sent when reconnected
- subscribed events will be re-subscribed on reconnection
- there are 2 triggers for reconnection:
	- when the CRI fires a "disconnect" event (supposedly this works, but i could not observe it in my testing) https://github.com/cypress-io/cypress/blob/738378254571425f101efd46696fea8cc4a1ca1f/packages/server/lib/browsers/cri-client.ts#L190-L191
	- when a CDP command fails with a "WebSocket is not open..." error
- reconnection should only take 1 attempt - if it fails, a project-level error is thrown, instructing the user to try again

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Good news, I can reproduce this 100% of the time after I put my mac to sleep. 

Bad news, I can't get Cypress running locally so I cannot check this PR https://github.com/cypress-io/cypress/issues/6542

File: packages/server/lib/browsers/cri-client.ts [hunk 1]
```diff
@@ -128,17 +129,73 @@ const maybeDebugCdpMessages = (cri) => {
...
+    .then(() => {
+      debug('restoring subscriptions + running queued commands... %o', { subscriptions, enqueuedCommands })
+      subscriptions.forEach((sub) => {
+        cri.on(sub.eventName, sub.cb)
+      })
+
+      enqueuedCommands.forEach((cmd) => {
+        cri.send(cmd.command, cmd.params)
+        .then(cmd.p.resolve, cmd.p.reject)
+      })
```
Comment (brian-mann) [inline packages/server/lib/browsers/cri-client.ts]: i don't believe the logic here is correctly connected because the `forEach` is synchronous and is not properly returning the mapped promises.

I believe you want to return `Promise.mapSeries` here. I could be wrong though.

Comment (flotwig) [reply packages/server/lib/browsers/cri-client.ts]: that's what we want here - the intention of this code is to fire off all of the enqueued commands, in the order they were sent, and then resolving/rejecting the originally returned (deferred) promise.

the `.catch` on line 167 is mostly to ensure that errors from `connect()` are thrown somewhere instead of being unhandled, but it could potentially catch any synchronous errors in cri.on and cri.send as well

Comment (brian-mann) [reply packages/server/lib/browsers/cri-client.ts]: I suppose that the outer handlers calling into `.send()` are still returned the enqueued promise - which allows them to attach any `.catch()` handlers.

My concern was of uncaught promises - but I believe the chain is correctly propagated. 

I'll approve this - although I should look at the tests in more detail to verify that they're specifically covering the scenario I'm imagining.

**Comment by adilbagi123** [comment]
I still see this issue after Cypress runs few tests. Cypress version - 4.1.0, Windows, Chrome 80

**Comment by flotwig** [comment]
@adilbagi123 that error message won't be detected by this patch, can you please open a new issue with the full error message? Thanks!
