### PR TITLE
Fix shadow dom visibility hang

### LINKED ISSUE #7794: Bug: Cypress hangs when detecting element visibility with Shadow DOM enabled
### Current behavior:

It is the same or similar as #7679 (fixed in #7692), except this is _with_ `experimentalShadowDomSupport: true` and using Ionic (which heavily uses Shadow DOM).

Essentially when Cypress attempts to detect visibility of an Ionic component where there's a modal backdrop visible, it seems to go into an endless loop of that same find element code path.

**Note:** Also, notice how it thinks the `ion-button` is invisible. I think this is a separate regression/issue because I've seen this in other tests for Ionic popovers/toasts where it thinks it's not visible when they really are.

### Desired behavior:

Interacting with Ionic components shouldn't cause Cypress to hang.

I think that `while` loop may be due for a "max loop" check because it seems like we really don't want Cypress to totally hang under any circumstances. For example, this bug is causing my CI to generate 7GB video files, unless I force-stop the build/workflow.

### Test code to reproduce

https://github.com/kamranayub/junk-bug-cypress-ionic-hang

1. `npm install`
2. `npm run cypress:open`
3. Run the spec
4. Notice how Cypress hangs when the popover is shown

It tests against this URL: https://ionic-react-demo.stackblitz.io/app/account and clicks the top right button, then tries to detect visibility.

### Versions

- Cypress 4.9.0
- Chrome 83
- Windows 10

### Workaround

I think I can safely disable the experiment and rewrite my tests that were using `.shadow()`. 4.7.0 works with the experiment disabled. 4.8.0 had the other regression with clicking specifically.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7794

### User facing changelog

- Fixed an issue where checking for visibility on a shadow dom host element would hang if the host element was the foremost element and had an ancestor with fixed position.

### Additional details

More information in [this comment on the original issue](https://github.com/cypress-io/cypress/issues/7794#issuecomment-654240664). The fix itself is preventing an infinite loop and is pretty straightforward. 

I also refactored the code to use recursion instead of `while` loops, since a `while` loop will hang the browser, making it difficult to debug. If a recursive function infinitely recurses, it usually causes a `Maximum stack...` error pretty quickly without hanging the browser and the stack for the error points directly to the offending function.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/dom/elements.ts [hunk 1]
```diff
@@ -603,8 +603,12 @@ const getFirstCommonAncestor = (el1, el2) => {
   return el2
 }
 
+const isShadowRoot = (maybeRoot) => {
+  return maybeRoot?.toString() === '[object ShadowRoot]'
+}
+
 const isWithinShadowRoot = (node: HTMLElement) => {
-  return node.getRootNode().toString() === '[object ShadowRoot]'
+  return isShadowRoot(node.getRootNode())
```
Comment (JessicaSachs) [inline packages/driver/src/dom/elements.ts:611]: 👍  nice, I know this is something James was hoping to fix in his original PR.
