### PR TITLE
do not set url on invalid cookies

### LINKED ISSUE #2724: 3.1.1 regression: cookie can't be set when visiting local devserver
I was just following the tutorial and trying to setup simple tests for our app and an error stopped me.

### Current behavior:
The very simple test case:
```javascript
describe("Login", function() {
  it("Goes to login page", function() {
    cy.visit("https://localhost:8443");
  });
});
```

Generates the following error in the test runner:
```
CypressError: cy.visit() failed trying to load:

https://localhost:8443/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > TypeError: Cannot set property 'url' of undefined

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

TypeError: Cannot set property 'url' of undefined
    at Object.setCookie (/Users/koen/Library/Caches/Cypress/3.1.1/Cypress.app/Contents/Resources/app/packages/server/lib/request.js:91:20)
    at addCookie
```

### Desired behavior:

I want Cypress to open my page so I can start writing tests 😄 

### Steps to reproduce:

1. Add Cypress to a project or create a Cypress project
2. Just add a single file with the test case above
3. Run the test runner with that test.

Reproduce is probably going to be hard, because visiting a production version of our app with Cypress worked correctly.

### Versions

- Cypress: 3.1.1
- Chrome: 70
- OS: macOS High Sierra

### Workaround

I first asked a question about this on the Gitter channel and downgrading to 3.1.0 made the test case above work and my page was loaded correctly.

### Extra

I think something goes wrong here: [request.coffee](https://github.com/cypress-io/cypress/blob/25bdc955cd39e50766e963a0f478934c329bc0cd/packages/server/lib/request.coffee#L70)

### PR DESCRIPTION
**Pull request by brian-mann**
fixes #2724

### CODE REVIEW

File: packages/server/lib/request.coffee [hunk 1]
```diff
@@ -66,8 +66,12 @@ newCookieJar = ->
 
     setCookie: (cookieOrStr, uri, options) ->
       ## store the original URL this cookie was set on
-      cookie = j.setCookieSync(cookieOrStr, uri, options)
-      cookie.url = uri
+      if cookie = j.setCookieSync(cookieOrStr, uri, options)
```
Comment (bahmutov) [inline packages/server/lib/request.coffee]: hehe, have you seen my code in a paranoid style where arguments and results are constantly asserted? this is why
