### PR TITLE
Fixed null JSON file error.

### LINKED ISSUE #472: stubbing a XHR call using a fixture file with null content raises an error
### Current behavior:
when stubbing a XHR call using a fixture file with `null` content an error is raised

### Expected behavior:
`JSON.parse('null')` returns `null`, no error is raised

### How to reproduce the current behavior:

```js
cy.server().route({
  method: 'GET',
  url: 'some/url',
  response: 'fixture:stub_file.json'
})
```
where `stub_file.json` is a file containing the string 
```null```

### Additional Info (images, notes, stack traces, etc)
Error trace
```
Error:        CypressError: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:259:9)
    at Function.Buffer.from (buffer.js:96:10)
    at new Buffer (buffer.js:75:17)
    at Object.<anonymous> (/Applications/Cypress.app/Contents/Resources/app/index.js:1804:21)
    at Object.tryCatcher (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:636:18)
    at /Applications/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Applications/Cypress.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

* Operating System: OSX Sierra
* Cypress Version: 0.19.1

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #472

### User facing changelog

Doesn't raise any error if the content of a JSON file is `null`.

#### Why was this change necessary?

`null` is a valid JSON. But it raises an error. 

#### What is affected by this change?

N/A

#### Any implementation details to explain?

N/A

### How has the user experience changed?

Screenshot from 2019-11-01 12-50-34

### PR Tasks

- [x] Have tests been added/updated?
- ~~Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? ~~
- ~~Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?~~
- ~~Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?~~

### CODE REVIEW

File: packages/server/lib/controllers/xhrs.coffee [hunk 1]
```diff
@@ -50,6 +50,11 @@ module.exports = {
         if _.isObject(data)
           data = JSON.stringify(data)
 
+        ## when data is null, JSON.stringify returns null.
+        ## handle that case. 
+        if data is null
+          data = []
```
Comment (bahmutov) [inline packages/server/lib/controllers/xhrs.coffee]: why `[]` and not `''`?

Comment (sainthkh) [reply packages/server/lib/controllers/xhrs.coffee]: It's because I didn't read the documentation carefully. It starts with the function with array argument and [later string argument](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding). 

Changed it to `''`.

File: packages/driver/test/cypress/integration/commands/xhr_spec.coffee [hunk 2]
```diff
@@ -1426,6 +1426,31 @@ describe "src/cy/commands/xhr", ->
               }
             })
 
+    describe "response fixtures", ->
+      it "works if the JSON file is valid", ->
```
Comment (bahmutov) [inline packages/driver/test/cypress/integration/commands/xhr_spec.coffee]:
```suggestion
      it "works if the JSON file has an object", ->
```

File: packages/driver/test/cypress/integration/commands/xhr_spec.coffee [hunk 3]
```diff
@@ -1426,6 +1426,31 @@ describe "src/cy/commands/xhr", ->
...
+          .route({
+            method: 'POST',
+            url: '/test-xhr',
+            response: 'fixture:valid.json',
+          })
+          .visit('/fixtures/xhr-triggered.html')
+          .get('#trigger-xhr')
+          .click()
+
+      it "works if the JSON file has content, null", ->
```
Comment (bahmutov) [inline packages/driver/test/cypress/integration/commands/xhr_spec.coffee]:
```suggestion
      it "works if the JSON file has null content", ->
```

File: packages/driver/test/cypress/fixtures/xhr-triggered.html [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+<html>
+  <head>
+    <title>jQuery 3.2.1 Fixture</title>
+    <script type="text/javascript" src="/fixtures/jquery-3.2.1.js"></script>
+  </head>
+  <body>
+    <button id="trigger-xhr">Trigger XHR</button>
+    <script>
+      $('#trigger-xhr').click(function(event) {
+        $.post('/test-xhr')
```
Comment (bahmutov) [inline packages/driver/test/cypress/fixtures/xhr-triggered.html]: I would love to see an assertion here - what does the client receive for the object and for the `null` - does the client without a `null` stub receive ''?

Comment (sainthkh) [reply packages/driver/test/cypress/fixtures/xhr-triggered.html]: Added a callback that sets a div element with stringified data. 

And `cy` checks if the div has the correct string.
