### PR TITLE
fix: `test:after:run` passes the `runnable`

### LINKED ISSUE #25663: Runnable instance not passed to test:after:run
### Current behavior

It seems that after the update from 12.4.1 to 12.5.0, runnable instance is not passed to "test:after:run" event. Boolean is returned instead. 

### Desired behavior

_No response_

### Test code to reproduce

```js
// index.js

Cypress.on('test:after:run', (test, runnable) => {
    console.log(runnable) // Shall show runnable instance, "true" is being returned instead
});
```

### Cypress Version

v12.5.0

### Node version

v16

### Operating System

macOS 13

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes #25663

### Additional details

The `runnable` parameter was inadvertently removed with https://github.com/cypress-io/cypress/commit/facfd0d88c6060a2179c684e03a699c47ca659c5. Added the parameter back by refactoring to not modify the Cypress `test:after:run` event and instead pass along the `isInteractive` parameter to the reporter from the runner.

Also noticed the `log:added` and `log:changed` events were incorrectly typed stating they were passing the `interactive` boolean as the second parameter when in actuality the `log` was the second parameter and the `interactive` parameter is not being passed.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/app/src/runner/event-manager.ts [hunk 1]
```diff
@@ -537,8 +537,8 @@ export class EventManager {
     Cypress.on('after:screenshot', handleAfterScreenshot)
 
     driverTestEvents.forEach((event) => {
-      Cypress.on(event, (test, cb) => {
-        this.reporterBus.emit(event, test, cb)
+      Cypress.on(event, (test, _runnable) => {
```
Comment (emilyrohrbough) [inline packages/app/src/runner/event-manager.ts]: It honestly might be worth deleting `driverTestEvents` and breaking these out to match their apis: 🤷🏻‍♀️ 

```js
Cypress.on('test:before:run:async', (test, _runnable) => {
   this.reporterBus.emit(event, test)
})

Cypress.on('test:after:run', (test, _runnable) => {
  this.reporterBus.emit(event, test, Cypress.config('isInteractive'))
})
```

**Review by emilyrohrbough — APPROVED** [review]

File: packages/app/src/runner/event-manager.ts (hunk 1 above)
Comment (mschile) [reply packages/app/src/runner/event-manager.ts]: updated [4e8452e](https://github.com/cypress-io/cypress/pull/25678/commits/4e8452e9054088751d543a0c347b15644e8c3d97)

**Review by chrisbreiding — APPROVED** [review]
