### PR TITLE
Handle uncaught errors thrown as strings

### LINKED ISSUE #7590: Non-cross-origin uncaught error messages are left undefined
### Current behavior:

In [this PR](https://github.com/cypress-io/cypress/pull/3930/files#diff-6bc45df9d1822d1a0fc3b057744e9e66L37-L89), the way `createUncaughtException` creates an error changed, and the `message` variable was left `undefined` under these conditions: if `crossOriginScriptRe.test(msg)` fails and the `err` variable is not defined. The error that triggered the situation was a `ResizeObserver loop limit exceeded` error.

Because the error message ends up being `undefined`, checks like this no longer work:

```js
Cypress.on("uncaught:exception", (error) => {
  if (error.message && error.message.includes("ResizeObserver loop limit")) {
    return false;
  }
});
```

This is a screenshot of the debugging session in which I found this:

Image 2020-06-04 at 2 26 24 PM

### Desired behavior:

The final uncaught error message has the original information and can be used to catch expected errors.

### Test code to reproduce

Any thrown string should work:

`index.html`

```html
<html>
  <body>
    <button id="button">Click</button>
  </body>
  <script>
    document.getElementById("button").addEventListener(() => {
      throw "clicked";
    });
  </script>
</html>
```

`test.js`

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  if (err.message === "clicked") {
    return false;
  }
})

it("should not fail because the error should be caught", () => {
  cy.visit("index.html");
  cy.get("#button").click();
});
```

### Versions

Cypress 4.7.0
MacOS 10.15.5
Electron 80

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7590

### User facing changelog

- Fixed an issue where errors thrown as strings would not display correctly.

### Additional details

If a user application threw an error as a string (`throw 'some error'` as opposed to `throw new Error('some error')`, an internal error `Cannot read property 'split' of undefined` would be displayed and the `uncaught:exception` event would be called with the error as a string instead of as an object with typical error properties.

### How has the user experience changed?

If there is a string exception in an application, the test will now fail with the correct error. If the `uncaught:exception` event is being used, it will be called with an error object now, as it should.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.js [hunk 1]
```diff
@@ -143,4 +143,23 @@ describe('uncaught errors', () => {
 
     cy.visit('/fixtures/global-error.html')
   })
+
```
Comment (Bkucera) [inline packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.js:146]: issue comment
