### PR TITLE
Truncate file names for screenshots

### LINKED ISSUE #2403: Screenshot file name too long warning when Bytes exceeded
### Current behavior:
Currently I use BDD to document acceptance test cases, each test scenario is well detailed, Cypress uses the description of "it" to create the screenshot file name, but when "it" exceeds 255 characters it is not possible to create the screenshot file.

```
  6) As a quality manager, i would like to query the occurence history to find information about them GIVEN that im onthe search sreen, WHEN i fill in the ocurrence date fields, check the only delayed ones box and click on the filter button, THEN i see the filtered results:
     Error: ENAMETOOLONG: name too long, open '/home/node/cypress/screenshots/tools/us6.spec.js/As a quality manager iwould like to query the occurence history to find information about them -- GIVEN that im on the search sreen WHEN i fill in the ocurrence date fields check the only delayed ones box and click on the filter button THEN i see the filteredresults (failed).png'
```

### Desired behavior:
1. I hope Cypress allows me to change the name of the destination file from the screenshot before it writes it.
1. Or, I hope Cypress will worry about the size of the file before it writes it and limits it to 255 characters.

### Steps to reproduce:
1. Create a test case with "it" description too long, bigger then 255 caracteres.
1. Make a test case broken.
1. Run tests.
1. Look the verbose log, the screenshot not was created.

### Versions
Cypress:    3.0.3
Browser:    Chrome 67

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-90) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by lilaconlee**
- Fixes #2403 

Opted to set a max length of 242 for the original string so it's 255 with ` (failed).png`

### CODE REVIEW

File: packages/server/lib/screenshots.coffee [hunk 1]
```diff
@@ -313,14 +314,24 @@ getPath = (data, ext, screenshotsFolder) ->
   else
     names = [data.titles.map(replaceInvalidChars).join(RUNNABLE_SEPARATOR)]
 
+  # truncate file names to be less than 220 characters
+  # to accomodate filename size limits
+  maxFileNameLength = 220
```
Comment (lilaconlee) [inline packages/server/lib/screenshots.coffee]: This is a bit funky. From testing outside of Cypress, seems like this value should be 255 - length of `(failed) (N).png`, but that still causes a name too long error on CI. That doesn't happen when this value is a bit smaller 🤷‍♀️

**Comment by brian-mann** [comment]
I think ideally we would not truncate ahead of time, but instead recover from thrown errors like `ENAMETOOLONG` or whatever it is.

I'm merging this in regardless, but in case we wanted to tighten up later we could.
