### PR TITLE
3.5.0 - Fix actionability for covered elements

### LINKED ISSUE #5430: Cannot read property ‘ownerDocument’ of null on 'cy.click' in 3.5.0
### Current behavior:

Since 3.5.0, I am getting this error on `.click()`.

```
Timed out retying: Cannot read property ‘ownerDocument’ of null
```

Screen Shot 2019-10-23 at 5 26 45 PM

### Desired behavior:

Not throwing this error

### Steps to reproduce: (app code and test code)

```js
context('contact us modal', () => {
  before(() => {
    cy.visit('http://www.cypress.io/pricing')
  })

  it('opens modal on click of custom plan', () => {
    cy.contains('.call-modal', 'Get in touch').click()
    cy.get('.modal-body').should('be.visible')
  })

  it('form with proper class/script is in modal', () => {
    cy.contains('.call-modal', 'Get in touch').click()
  })
})
```

### Versions

3.5.0

### PR DESCRIPTION
**Pull request by kuceb**
fix bug that caused us to not error when the element is covered by a `position:fixed` element

- this in turn fixes issues that caused strange failures such as `cannot read property ownerDocument of null` during `cy.click` that would occur in Cypress `3.5.0`
fix #5430

### User facing changelog
bugfix - fix issue causing obscure error message when an element cannot be interacted with due to being covered by an element with `position:fixed`.

### How has the user experience changed?
**when trying to interact with an element that's covered by a `fixed` element**
- before (pre 3.5.0): user would receive no error that the element was covered, and the test would pass (incorrect)
- before (3.5.0): user would receive the error `cannot read property ownerDocument of null`
- after: user will receive failing test with an error message that the element is covered:
image

### PR Tasks

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cy/actionability.coffee [hunk 1]
```diff
@@ -49,8 +50,10 @@ ensureElIsNotCovered = (cy, win, $el, fromElViewport, options, log, onScroll) ->
     ## figure out the deepest element we are about to interact
     ## with at these coordinates
     $elAtCoords = getElementAtPointFromViewport(fromElViewport)
-
+    debug('elAtCoords', $elAtCoords)
+    debug('el has pointer-events none?')
     cy.ensureElDoesNotHaveCSS($el, 'pointer-events', 'none', log)
+    debug('is descendent of elAtCoords?')
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/actionability.coffee]: I guess this is new - to send debug info for driver events. I mean, I like more events, just wondering if this is what we're advised to do now - and when do we log versus not log?

**Review by jennifer-shehane — APPROVED** [review]
