### PR TITLE
fix: make vite-dev-server work on windows

### LINKED ISSUE #16096: Support Vite-dev-server on windows
### Current behavior
Running `@cypress/vite-dev-server` on windows throws the following error

```
Not allowed to load local resource: .../@cypress/vite-dev-server/client/initCypressTests.js
```

### Desired behavior
To use vite on windows

### Test code to reproduce
- checkout https://github.com/elevatebart/cy-ds-test on windows
- yarn install
- yarn cy
- click on one of the specs

### Versions

```
"cypress": "^7.1.0",
    "@cypress/react": "^5.3.3",
    "@cypress/vite-dev-server": "^1.2.2",
```

### PR DESCRIPTION
**Pull request by elevatebart**
- Closes #16096

### User facing changelog
Before this PR loading the testing client did not work on Windows.
See issue.

### Additional details
There was a bunch of backslashes mixed in the urls.

### How has the user experience changed?
@cypress/vite-dev-server is now working on windows

### CODE REVIEW

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 1]
```diff
@@ -16,14 +18,18 @@ export const makeCypressPlugin = (
 ): Plugin => {
   let base = '/'
 
+  const posixSupportFilePath = supportFilePath ? resolve(projectRoot, supportFilePath).replace(OSSepRE, '/') : undefined
+
+  const normalizedSupportFilePath = posixSupportFilePath ? `${base}@fs/${posixSupportFilePath}` : undefined
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:23]: Out of curiosity where does this `@fs` come from? I've seen it before for the node_modules but never really understood it.

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 2]
```diff
@@ -16,14 +18,18 @@ export const makeCypressPlugin = (
...
+
   return {
     name: pluginName,
     enforce: 'pre',
     config (_, env) {
       if (env) {
         return {
           define: {
-            'import.meta.env.__cypress_supportPath': JSON.stringify(supportFilePath ? resolve(projectRoot, supportFilePath) : undefined),
+            'import.meta.env.__cypress_supportPath': JSON.stringify(normalizedSupportFilePath),
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:32]: What does `JSON.stringify` do here? Do we need it?

File: npm/vite-dev-server/src/makeCypressPlugin.ts [hunk 3]
```diff
@@ -40,7 +46,7 @@ export const makeCypressPlugin = (
           tag: 'script',
           injectTo: 'body',
           attrs: { type: 'module' },
-          children: `import(${JSON.stringify(INIT_FILEPATH)})`,
+          children: `import(${JSON.stringify(`${base}@fs/${INIT_FILEPATH}`)})`,
```
Comment (lmiller1990) [inline npm/vite-dev-server/src/makeCypressPlugin.ts:49]: I don't think we need JSON.stringify. I was able to [remove something similar in webpack-dev-server](https://github.com/cypress-io/cypress/pull/16056/files#diff-fa95d7e53f1c3e9c95d91c3bab0b4692f126b57590abb85f0e13c8644807dccaR20).

**Review by lmiller1990 — COMMENTED** [review]
Few nit picks

File: npm/vite-dev-server/src/makeCypressPlugin.ts (hunk 2 above)
Comment (elevatebart) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:32]: Just like with webpack define plugin, the strings on the left are meant to be replaced in the code literally.

So if they contain any special character, I want it to be escaped automatically.
This way when they are eval-ed within the code, the special characters are kept.

I hope it is clear.

See https://webpack.js.org/plugins/define-plugin/

File: npm/vite-dev-server/src/makeCypressPlugin.ts (hunk 3 above)
Comment (elevatebart) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:49]: I am not sure you should have removed it from webpack-dev-server either.
Do test hard cases with special char in the folder name:
- `Oma's sister`. 
- `The "Best" project`
- `The back\slash`

In those cases we will end up with either an unterminated string or some characters that are removed from the string.
It is not my intention.

File: npm/vite-dev-server/src/makeCypressPlugin.ts (hunk 1 above)
Comment (elevatebart) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:23]: The proper functions to condition file calls in Vite are not yet exposed.
See `fileToUrl()` in `assets.ts`.
Maybe we can get Vite to expose some kind of util library?

Until then its the only way since we have our HTML in the wrong place (within node_modules)

Comment (lmiller1990) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:23]: All good, just curious - good to know this comes from Vite.

File: npm/vite-dev-server/src/makeCypressPlugin.ts (hunk 2 above)
Comment (lmiller1990) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:32]: ok!

File: npm/vite-dev-server/src/makeCypressPlugin.ts (hunk 3 above)
Comment (lmiller1990) [reply npm/vite-dev-server/src/makeCypressPlugin.ts:49]: Ooo ok. Maybe we should revert that change I made. :|

**Review by lmiller1990 — APPROVED** [review]
