### PR TITLE
fix: bug where cy.createSnapshot would interact with documents using custom elements

### LINKED ISSUE #1068: Cypress getting into an infinite XHR request loop
### Current behavior:
When visiting a page on our site through Cypress we're seeing it never complete loading because something causes the XHR requests being made to be made infinitely.

If we look at the Cypress CLI output when running the test we see:

```
GET /xhr/item/alternate-colours/1606925 200 236.222 ms - -
GET /xhr/item/alternate-colours/1606925 200 456.960 ms - -
GET /xhr/item/alternate-colours/1606925 200 288.704 ms - -
GET /xhr/item/alternate-colours/1606925 200 260.936 ms - -
```

This request is only made by our application once; if I got to the page in a browser and watch the network tab I can see that the request is made once. Watching the test through the Cypress UI, I can see that the browser just hangs and becomes unresponsive as all these requests are firing.

I'm not sure what, but something is causing these requests to run again and again and again.

Interestingly, this only happens via `cypress open` and then running the test through the UI. If I do `cypress run` and watch the video, the test does complete and the XHR requests complete as expected.

I'm not sure what extra info is useful here but let me know what I can provide to help with this.

* Operating System: Mac OS X Sierra 
* Cypress Version: 1.1.4
* Browser Version: Chrome 63

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-63) by [Unito](https://www.unito.io/learn-more)

### LINKED ISSUE #7187: Cypress snapshotting causes `attributeChangedCallback` to be triggered on custom elements
The documentation advertises that all websites can be tested with cypress. Unfortunately, I cannot confirm this for websites that use custom elements (https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements).

During the checks for elements with Cypress, the custom elements are apparently cloned or newly created. This means that the constructor of the custom element and possibly the `attributeChangedCallback` is called.

The functionality of the application is unfortunately changed by the Cypress tests! If, for example, a global variable is written in these lifecycle methods, a fetch request is executed, or the like, this happens several times in the test.

Here is a cypress project through which this behavior can be reproduced:
https://gitlab.com/benjaminknauer/cypress-custom-elements-bug

The project runs tests against this page, which contains a custom element that prints calls of the lifecycle methods to the console: https://benjaminknauer.gitlab.io/cypress-custom-elements-bug/

Best regards
Benjamin

### Current behavior:
Custom element lifecycle methods  are called several times.
The execution of the tests influences the application.

image

### Desired behavior:
Custom element lifecycle methods should be called just once. The execution of the application should not be affected by the tests.

image

### Test code to reproduce
Project with cypress tests
https://gitlab.com/benjaminknauer/cypress-custom-elements-bug

```js
context("customElement - broken", () => {
    it("customElement", () => {
        // when
        cy.visit("https://benjaminknauer.gitlab.io/cypress-custom-elements-bug");

        // then
        cy.get(".nonExistentElement").should("be.visible");
    });
});
```

Site with a custom element to run test against:
https://benjaminknauer.gitlab.io/cypress-custom-elements-bug/

### Versions
Cypress 4.5.0 / Chrome / Fedora 30

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-163) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #1068 
- Closes #7187

### User facing changelog

- Fixes a bug where `cy.createSnapshot` would interact with documents using custom elements
  - Fixes an issue many users were having where Cypress would get stuck in an infinite XHR loop on documents that used custom elements

### Additional details

See the following test case [as reported in the issue](https://github.com/cypress-io/cypress/issues/1068#issuecomment-654695273)

Before:

> ```js
> it('hangs', () => {
>   cy.visit('https://evryplace.com/panel/');
> })
> ```
> 
> #### In Cypress during `cypress open`
> 
> The `cy.visit()` does not resolve and the browser locks up in all browsers (Chrome, Electron) during `cypress open`. There are infinite requests that go out every second to `GET /panel/i18n/7fa71d4/app-webvr_en.json`.
> 
> screen shot 2018-04-19 at 8 22 46 pm
> 
> #### In Cypress during `cypress run`
> 
> The behavior is actually different during `cypress run`. The `cy.visit()` resolves and the test passes (although it looks like the page doesn't load exactly right still). 
> 
> ezgif-6-76c96ca00058

After:

The page loads properly as expected

Screen Shot 2020-07-24 at 6 01 32 AM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/driver/src/cy/snapshots.js [hunk 1]
```diff
@@ -147,7 +147,12 @@ const create = ($$, state) => {
 
       // TODO: throw error here if cy is undefined!
 
-      const $body = $$('body').clone()
+      // certain frameworks (ex. polymer) which use the shadow DOM
+      // get stuck here if we try to use cloneNode
```
Comment (jennifer-shehane) [inline packages/driver/src/cy/snapshots.js:151]: what do you mean by 'get stuck'?

**Review by jennifer-shehane — COMMENTED** [review]
@panzarino So nice. I confirmed manually that this fixes the original bug.

This actually fixes this other issue also, where calling clone would trigger an `attributeChangedCallback` within the application. https://github.com/cypress-io/cypress/issues/7187#issuecomment-623321726 This case may be more testable - seems you could ensure this isn't called if snapshots are on. I wonder if it's the same reason that's causing the polymer issue?

@chrisbreiding may have some advice on writing a test case or assessing why this is happening.

**Comment by flotwig** [comment]
@chrisbreiding added you for review since this seems to be fixing a Shadow DOM-related issue, apparently unrelated to the new Shadow DOM changes

**Review by flotwig — CHANGES_REQUESTED** [review]
@panzarino please add a test case here that demonstrates what is happening to shadow DOM elements on clone and that it is no longer happening

also, wow, shadow DOM? that was NOT my guess at all as to why this was happening 🤣

**Comment by panzarino** [comment]
@flotwig Actually, I'm not 100% sure that this is an issue with shadow dom. More realistically it's actually because of the issue that Jennifer linked to (really wish I saw that before spending so much time on this). The only thing that I could isolate/made sense during research was having to do with shadow dom (mainly the polymer framework), but I'm not confident thats what was actually causing this issue. I'm going to investigate in more detail and see if I can come up with a reproducible.

File: packages/driver/cypress/integration/cy/snapshot_spec.js [hunk 2]
```diff
@@ -166,4 +166,28 @@ describe('driver/src/cy/snapshots', () => {
       })
     })
   })
+
+  context('shadow dom', () => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/cy/snapshot_spec.js:170]: This doesn't seem to be related to shadow dom, but solely to custom elements. They're easy to confuse since they're often used together, but they're different features and can be used separate from each other. I think we should use a different fixture specifically for custom elements and rename the suite/test titles here to make it clear it's a custom elements issue that's being tested.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/integration/cy/snapshot_spec.js [hunk 3]
```diff
@@ -166,4 +166,28 @@ describe('driver/src/cy/snapshots', () => {
...
     })
   })
+
+  context('custom elements', () => {
+    beforeEach(() => {
+      cy.visit('/fixtures/custom-elements.html')
+    })
+
+    // https://github.com/cypress-io/cypress/issues/7187
+    it('does not trigger shadow dom constructor', () => {
```
Comment (chrisbreiding) [inline packages/driver/cypress/integration/cy/snapshot_spec.js:176]: I hate to nitpick, but the test titles and the method names still reference shadow dom. I just don't want there to be any confusion for a future developer looking at these.

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

File: packages/driver/cypress/integration/cy/snapshot_spec.js (hunk 3 above)
Comment (panzarino) [reply packages/driver/cypress/integration/cy/snapshot_spec.js]: Sorry, missed that. Definitely understand the need to clarify the difference, updated now.

**Review by chrisbreiding — APPROVED** [review]

**Review by flotwig — APPROVED** [review]
