### PR TITLE
fix: load TS plugins and support files

### LINKED ISSUE #7459: Support TypeScript support and plugin files
### Current behavior:

TypeScript support files (i.e `support/commands.ts`) and plugin file (`plugins/index.ts`) cause tasks and/or custom commands to not be found/registered. For example, the custom task `db:seed` could not be registered within the [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app) project:

Screen Shot 2020-05-20 at 3 12 52 PM

Converting the plugins file back to JavaScript resolved the issue, but a similar issue also exists for a `commands.ts`, which resulted in custom commands not being added:

Screen Shot 2020-05-20 at 5 36 17 PM

Converting the support files back to JavaScript also resolved the issue.

It should be noted that this issue did not exist with Cypress `develop` branch before and after the v4.6 release.

### Desired behavior:

- TypeScript support and plugin files to be properly loaded and/or executed for test execution.
- Customs commands should be added and tasks should be registered when declared in TS files.

### Test code to reproduce

Reproduction (with [associated commit](https://github.com/cypress-io/cypress-realworld-app/commit/40c612023f411c7fccf4d717341167ead1c3173c)) can be seen within this cypress-realworld-app test run: https://dashboard.cypress.io/projects/7s5okt/runs/1272/specs

### Versions

Cypress v4.6

### PR DESCRIPTION
**Pull request by bahmutov**
- Closes #7459

### User facing changelog

In production, we checked if `cypress/support/index.ts` and `cypress/plugins/index.ts` could be loaded using `require.resolve`. Without require hook to load `ts` files, this failed and we skipped loading plugins or support TS files. 

This PR extends the check and finds index TS files.

### Additional details

Note: when running from the monorepo, we register TS require hook, thus external project's `cypress/support/index.ts` is loaded right away. For user project's we cannot do this, thus it fails to find `cypress/support/index.ts`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/config.coffee [hunk 1]
```diff
@@ -539,25 +549,39 @@ module.exports = {
...
+              obj.supportFile = tsSupportFilename
+            else
+              ## if the directory exists, set it to false so it's ignored
+              debug("setting support file to false")
+              obj.supportFile = false
+        else
+          debug("support folder does not exist, set to default index.js")
+          ## otherwise, set it up to be scaffolded later
+          obj.supportFile = path.join(sf, "index.js")
+        return obj
```
Comment (flotwig) [inline packages/server/lib/config.coffee:584]: this nested if/else feels like an antipattern, maybe the logic for deciding `supportFile` should be in a function that is assigned to obj.supportFile here

File: packages/server/lib/config.coffee [hunk 2]
```diff
@@ -539,25 +549,39 @@ module.exports = {
...
-            obj.supportFile = false
-          else
-            debug("support folder does not exist, set to default index.js")
-            ## otherwise, set it up to be scaffolded later
-            obj.supportFile = path.join(sf, "index.js")
-          return obj
-      else
+      debug("support JS module %s does not load", sf)
+
+      loadingDefaltSupportFile = sf is path.resolve(obj.projectRoot, CONFIG_DEFAULTS.supportFile)
```
Comment (flotwig) [inline packages/server/lib/config.coffee:554]:
```suggestion
      loadingDefaultSupportFile = sf is path.resolve(obj.projectRoot, CONFIG_DEFAULTS.supportFile)
```

File: packages/server/lib/config.coffee [hunk 3]
```diff
@@ -539,25 +549,39 @@ module.exports = {
...
+      if !loadingDefaltSupportFile
         debug("support file is not default")
         ## they have it explicitly set, so it should be there
-        errors.throw("SUPPORT_FILE_NOT_FOUND", path.resolve(obj.projectRoot, sf), obj.configFile || CONFIG_DEFAULTS.configFile)
+        return errors.throw("SUPPORT_FILE_NOT_FOUND", path.resolve(obj.projectRoot, sf), obj.configFile || CONFIG_DEFAULTS.configFile)
```
Comment (flotwig) [inline packages/server/lib/config.coffee:558]: it seems like this would still fail if the user specifies a `.ts` file. example:

1. `supportFile` is `foo.ts`
2. `require.resolve("foo.ts")` will throw MODULE_NOT_FOUND in prod
3. `loadingDefaultSupportFile` will be `false`, and this error will be thrown

what am i missing?

File: packages/server/lib/config.coffee (hunk 2 above)
Comment (flotwig) [reply packages/server/lib/config.coffee:554]: also, i'm sorry you have to do this, this area of the codebase needs help

File: packages/server/lib/config.coffee [hunk 4]
```diff
@@ -594,18 +618,28 @@ module.exports = {
     Promise
     .try ->
       ## resolve full path with extension
-      obj.pluginsFile = require.resolve(pluginsFile)
+      obj.pluginsFile = utils.resolveModule(pluginsFile)
       debug("set pluginsFile to #{obj.pluginsFile}")
     .catch {code: "MODULE_NOT_FOUND"}, ->
-      debug("plugins file does not exist")
+      debug("plugins module %s does not exist", pluginsFile)
```
Comment (flotwig) [inline packages/server/lib/config.coffee:624]: for readability: 
```suggestion
      debug("plugins module does not exist %o", { pluginsFile })
```

File: packages/server/lib/config.coffee [hunk 5]
```diff
@@ -594,18 +618,28 @@ module.exports = {
...
       if pluginsFile is path.resolve(obj.projectRoot, CONFIG_DEFAULTS.pluginsFile)
-        debug("plugins file is default, check if #{path.dirname(pluginsFile)} exists")
+        debug("plugins file %s is default, check if folder %s exists",
+          pluginsFile, path.dirname(pluginsFile))
```
Comment (flotwig) [inline packages/server/lib/config.coffee:627]: for readability:
```suggestion
        debug("checking if pluginsFile exists", { pluginsFile, dirName: path.dirname(pluginsFile) })
```

File: packages/server/lib/config.coffee [hunk 6]
```diff
@@ -594,18 +618,28 @@ module.exports = {
...
+
         fs.pathExists(pluginsFile)
         .then (found) ->
           if found
-            debug("plugins folder exists, set pluginsFile to false")
-            ## if the directory exists, set it to false so it's ignored
-            obj.pluginsFile = false
+            debug("is there index.ts in the plugins folder %s?", pluginsFile)
```
Comment (flotwig) [inline packages/server/lib/config.coffee:632]: can you try to consolidate these debug lines so we don't need a bunch of them scattered everywhere? we are logging out the same data across many modules already and i want to decrease duplication in debug logs as much as possible

File: packages/server/lib/config.coffee [hunk 7]
```diff
@@ -594,18 +618,28 @@ module.exports = {
...
+            tsPluginsFilename = path.join(pluginsFile, "index.ts")
+            return fs.pathExists(tsPluginsFilename)
+            .then (foundTsFile) ->
+              if foundTsFile
+                debug("found index TS plugins file %s", tsPluginsFilename)
```
Comment (flotwig) [inline packages/server/lib/config.coffee:637]:
```suggestion
                debug("found index TS plugins file %o", { tsPluginsFilename })
```

File: packages/server/lib/config.coffee [hunk 8]
```diff
@@ -539,25 +549,39 @@ module.exports = {
...
+      debug("support file is default, check if #{path.dirname(sf)} exists")
+      # at this point suport file is probably just support folder
+      #  like "<project root>/cypress/support"
+      return fs.pathExists(sf)
+      .then (found) ->
+        if found
+          debug("support folder exists")
+
+          debug("is there index.ts in the support folder %s?", sf)
+          tsSupportFilename = path.join(sf, "index.ts")
```
Comment (flotwig) [inline packages/server/lib/config.coffee:570]: can this logic (and surrounding logic) be extracted into a separate function shared by `setSupportFileAndFolder` and `setPluginsFile`? it seems like it should be possible to clean this up

**Review by flotwig — CHANGES_REQUESTED** [review]
such a fun bug. i wonder if this would have been avoided by the work @brian-mann is doing on bundling the server, since we presumably won't have `.ts` registered in `require.extensions` once that happens

File: packages/server/test/unit/config_spec.coffee [hunk 9]
```diff
@@ -3,6 +3,7 @@ require("../spec_helper")
 _        = require("lodash")
```
Comment (flotwig) [inline packages/server/test/unit/config_spec.coffee:3]: Is there an existing e2e test/example project where we could add a true end-to-end test for this, somehow? This is such a weird bug that I don't know if only unit tests should suffice.

File: packages/server/lib/config.coffee (hunk 6 above)
Comment (bahmutov) [reply packages/server/lib/config.coffee:631]: I don't think the number of debug log messages is a problem, especially compared to debugging production code - then seeing each branch taken is huge benefit

File: packages/server/lib/config.coffee (hunk 3 above)
Comment (bahmutov) [reply packages/server/lib/config.coffee:558]: I will need to check - we know that setting explicit TS support and plugins files work

File: packages/server/lib/config.coffee (hunk 6 above)
Comment (flotwig) [reply packages/server/lib/config.coffee:631]: agreed, but you can accomplish the same thing with fewer debug lines by logging out branch conditions instead of logging out a different line for each branch, stuff like that... plus, pluginsFile is logged out prior to this point by other config code

**Comment by bahmutov** [comment]
Sure and we keep reassigning plugins file variable right? I don’t want to write the absolutely shortest code especially since it is just debugging lines

File: packages/server/lib/config.coffee (hunk 8 above)
Comment (bahmutov) [reply packages/server/lib/config.coffee]: I have refactored both code paths to use same function if the module cannot be found

**Review by flotwig — APPROVED** [review]
have not tested locally but other than that LGTM
