### PR TITLE
Fix automatically loading fixtures with more than one . in the name

### LINKED ISSUE #1402: Fails to automatically load fixture files if more than one . is in file name
- Operating System: OSX High Sierra 10.13.3
- Cypress Version: 2.1.0

### Is this a Feature or Bug?
Bug

### Current behavior:
`cy.fixture` function does not look up files without extension correctly if they have several dots. Is probably looking for first element after first ".", but should look for element after last "."

### How to reproduce:
Check this code: [tiny test fork](https://github.com/gautejohan/cypress-fixture-file-with-dots)
Create a fixture file with several dots in name (e.g. `parent.child.info.json`, and use `cy.fixture('parent.child.info')` in your test.

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #1402

Also fixes a few TODO comments in the fixtures.coffee file along the way

### CODE REVIEW

File: packages/server/lib/errors.coffee [hunk 1]
```diff
@@ -721,6 +721,12 @@ getMsgByType = (type, arg1 = {}, arg2) ->
 
       #{arg1.link}
       """
+    when "FIXTURE_NOT_FOUND"
+      """
+        A fixture with a supported file extension does not exist at the supplied path:
```
Comment (jennifer-shehane) [inline packages/server/lib/errors.coffee]: I'm confused by this message and what actionable thing there is for me to do here. 

- What is Cypress currently interpreting as the file extension from my fixture command?
- Do I need to provide the file extension? What do I do to fix this!
- What file extensions *are* supported?

All of these questions should be answered in the error message. If needed, link to a on.cypress.io link.

Comment (flotwig) [reply packages/server/lib/errors.coffee]: Good point, it's not very clear. I updated the error message with details on what was tried and what they should do when we can't find their fixture:

image

Comment (jennifer-shehane) [reply packages/server/lib/errors.coffee]: Is this awful? 

```
Error: A fixture file could not be found at any of the following paths:

 > cypress/fixtures/err.txt
 > cypress/fixtures/err.txt{{extension}}

Supported fixture file extensions include: 

 > .json, .js, .coffee, .html, .txt, .csv, .png, .jpg, .jpeg, .gif, .tif, .tiff, .zip

Provide a path to an existing fixture file.
```

Comment (flotwig) [reply packages/server/lib/errors.coffee]: It's a little misleading, since technically "any" file extension is supported, but those are just the extensions we attempt to tack on to the filename if the file can't be found at the user-supplied filename. I reworded it a bit:

image

?

Comment (jennifer-shehane) [reply packages/server/lib/errors.coffee]: Maybe 

"Cypress looked for these file extensions at the provided path"

Comment (flotwig) [reply packages/server/lib/errors.coffee]: Sounds good, changed it to that
