### PR TITLE
catch child process killed with a signal

### LINKED ISSUE #5808: CLI does not detect killed Electron process with SIGKILL, SIGBUS etc
Cypress v3.6

- start Cypress CLI

```
npx cypress open
```
- cli spawns new process, see code https://github.com/cypress-io/cypress/blob/e313f8cdc32a79330852362633196484e8e24cac/cli/lib/exec/spawn.js#L138

```js
const child = cp.spawn(executable, electronArgs, stdioOptions)

function resolveOn (event) {
  return function (code, signal) {
    debug('child event fired %o', { event, code, signal })
    resolve(code)
  }
}

child.on('close', resolveOn('close'))
child.on('exit', resolveOn('exit'))
child.on('error', reject)
```
- if the child process is killed for some reason, for example with
```
$ ps
66579 ttys005    0:00.47 node /Users/gleb/.nvm/versions/node/v12.13.0/bin/npx cypress open
66580 ttys005    0:02.83 /Users/gleb/Library/Caches/Cypress/3.6.1/Cypress.app/Contents/MacOS/Cypress 
$ kill -9 66580
```
then our CLI receives `code: null` and thinks everything is peachy

```
DEBUG=cypress:cli npx cypress open
  cypress:cli child event fired { event: 'exit', code: null, signal: 'SIGKILL' } +14s
  cypress:cli child event fired { event: 'close', code: null, signal: 'SIGKILL' } +1ms
$ echo $?
0
```

Seems `SIGBUS` is sent to the child process when it runs out of shared memory space for example https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot/53970825#53970825

## Proposal

Only exit with code 0 when the child process successfully finishes with `code: 0, signal: null`

### PR DESCRIPTION
**Pull request by bahmutov**
- Closes #5808

### User facing changelog

If the Test Runner child process is killed with a signal like `SIGKILL` or `SIGBUS`, the NPM CLI process shows an error and exits with non-zero code, no longer swallowing the error.

### Additional details

Child Electron process could crash for some reason (like running out of memory) while running tests, and close. In that case the CLI parent process would receive `code: null, signal: <name>` which is different from successful exit `code: 0, signal: null` or a failded test exit `code: 1, signal: null`. But the CLI parent process would just do truthy check `if (code) { reject ... }` thus swallowing the crash.

### How has the user experience changed?

The users should get better CI information, that no longer shows passing green build while the tests crashed in Electron browser.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 

## Local testing

- run Cypress with `npm start`. This will start the GUI in global mode
- find the PID of the process id with `ps` like this
```
68518 ttys000    0:00.26 npm  
68521 ttys000    0:00.35 node ./cli/bin/cypress open --dev --global
68522 ttys000    0:01.19 node /Users/gleb/git/cypress/scripts/start.js --cwd /Users/gleb/git/cypress 
68523 ttys000    0:04.56 /Users/gleb/git/cypress/packages/electron/dist/Cypress/Cypress.app/Contents/
68524 ttys000    0:00.31 /Users/gleb/git/cypress/packages/electron/dist/Cypress/Cypress.app/Contents/
68526 ttys000    0:00.62 /Users/gleb/git/cypress/packages/electron/dist/Cypress/Cypress.app/Contents/
```

- kill the `node /Users/gleb/git/cypress/scripts/start.js` process like `kill -9 68522`
- CLI should show the following error
```
The Test Runner received event exit with signal SIGKILL

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (16.7.0)
Cypress Version: 0.0.0
```
and the exit code should be non-zero
```
$ echo $?
1
```

### CODE REVIEW

File: cli/test/lib/exec/spawn_spec.js [hunk 1]
```diff
@@ -171,6 +173,20 @@ describe('lib/exec/spawn', function () {
...
+        return spawn.start('--foo')
+        .then(() => {
+          throw new Error('should have hit error handler but did not')
+        }, (e) => {
+          debug('error message', e.message)
+          snapshot(e.message)
+        })
+      })
+    })
+
```
Comment (flotwig) [inline cli/test/lib/exec/spawn_spec.js]: @bahmutov I think it would be worth it to add an `e2e` test for this, since it involves multiple processes, what do you think?

File: cli/lib/exec/spawn.js [hunk 2]
```diff
@@ -140,6 +140,13 @@ module.exports = {
         function resolveOn (event) {
           return function (code, signal) {
             debug('child event fired %o', { event, code, signal })
+
+            if (code === null && signal) {
```
Comment (flotwig) [inline cli/lib/exec/spawn.js]: the node.js docs state:

>  If the process exited, code is the final exit code of the process, otherwise null. If the process terminated due to receipt of a signal, signal is the string name of the signal, otherwise null. One of the two will always be non-null.

so this should just be:

```suggestion
            if (code === null) {
```

https://devdocs.io/node/child_process#child_process_event_exit

**Review by flotwig — COMMENTED** [review]
Can you give me a pointer on how to reproduce this locally? I tried killing the Electron process spawned by `npm run cypress:open`, but Cypress still seems to exit with exit code 0...

File: cli/lib/exec/spawn.js (hunk 2 above)
Comment (bahmutov) [reply cli/lib/exec/spawn.js]: hehe, this was more to be precise especially when doing testing to avoid sending `code: null, signal: null` via stub

File: cli/test/lib/exec/spawn_spec.js (hunk 1 above)
Comment (flotwig) [reply cli/test/lib/exec/spawn_spec.js]: would be tricky though, maybe not worth the time investment unless we have issues with this PR going forward

File: cli/lib/errors.js [hunk 3]
```diff
@@ -191,6 +192,20 @@ const invalidCypressEnv = {
...
+/**
+ * This error happens when CLI detects that the child Test Runner process
+ * was killed with a signal, like SIGBUS
+ * @see https://github.com/cypress-io/cypress/issues/5808
+ * @param {'close'|'event'} eventName Child close event name
+ * @param {string} signal Signal that closed the child process, like "SIGBUS"
+*/
+const childProcessKilled = (eventName, signal) => {
+  return {
+    description: `The Test Runner received event ${chalk.cyan(eventName)} with signal ${chalk.cyan(signal)}`,
```
Comment (flotwig) [inline cli/lib/errors.js]: make it clearer that this is an error? right now it's unclear that this is an exception

```suggestion
    description: `The Test Runner unexpectedly exited via a ${chalk.cyan(eventName)} event with signal ${chalk.cyan(signal)}`,
```

File: cli/test/lib/exec/spawn_spec.js (hunk 1 above)
Comment (bahmutov) [reply cli/test/lib/exec/spawn_spec.js]: I am not so sure e2e would be worth it
- we don't have e2e tests for CLI right now
- Node side (that one that delivers `code: null, signal: <name>` is pretty solid :)
- we have only changed our handling, which is covered by the tests
- finally, so far this has affected only very small number of our users I believe, otherwise we would hear about it again and again

**Comment by bahmutov** [comment]
love the new wording, will pull and update snapshot

**Review by flotwig — APPROVED** [review]

File: cli/test/lib/exec/spawn_spec.js [hunk 4]
```diff
@@ -171,6 +173,20 @@ describe('lib/exec/spawn', function () {
...
     })
 
+    context('detects kill signal', function () {
+      it('exits with error on SIGKILL', function () {
+        this.spawnedProcess.on.withArgs('exit').yieldsAsync(null, 'SIGKILL')
+
+        return spawn.start('--foo')
+        .then(() => {
+          throw new Error('should have hit error handler but did not')
+        }, (e) => {
```
Comment (brian-mann) [inline cli/test/lib/exec/spawn_spec.js]: the `.catch()` pattern is highly preferred over passing two arguments to `.then`

Comment (bahmutov) [reply cli/test/lib/exec/spawn_spec.js]: well, in this case, `catch` would let false positive slide (we really want NOT to resolve). Ideally we would plug in https://www.chaijs.com/plugins/chai-as-promised/
```
return spawn.start('--foo').should.eventually.rejectWith(...)
```
