### PR TITLE
fix: truncate screenshot filenames using byteLength

### LINKED ISSUE #2403: Screenshot file name too long warning when Bytes exceeded
### Current behavior:
Currently I use BDD to document acceptance test cases, each test scenario is well detailed, Cypress uses the description of "it" to create the screenshot file name, but when "it" exceeds 255 characters it is not possible to create the screenshot file.

```
  6) As a quality manager, i would like to query the occurence history to find information about them GIVEN that im onthe search sreen, WHEN i fill in the ocurrence date fields, check the only delayed ones box and click on the filter button, THEN i see the filtered results:
     Error: ENAMETOOLONG: name too long, open '/home/node/cypress/screenshots/tools/us6.spec.js/As a quality manager iwould like to query the occurence history to find information about them -- GIVEN that im on the search sreen WHEN i fill in the ocurrence date fields check the only delayed ones box and click on the filter button THEN i see the filteredresults (failed).png'
```

### Desired behavior:
1. I hope Cypress allows me to change the name of the destination file from the screenshot before it writes it.
1. Or, I hope Cypress will worry about the size of the file before it writes it and limits it to 255 characters.

### Steps to reproduce:
1. Create a test case with "it" description too long, bigger then 255 caracteres.
1. Make a test case broken.
1. Run tests.
1. Look the verbose log, the screenshot not was created.

### Versions
Cypress:    3.0.3
Browser:    Chrome 67

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-90) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #2403

### User facing changelog

- Fixed an issue where screenshots could fail because of names that were too long for the filesystem to accept.

### Additional details

- now using bytes instead of characters to resize the string
- if an ENAMETOOLONG error is encountered, the string will be further downsized, down to a minimum of 64 bytes after which the error will still be thrown, like described in https://github.com/cypress-io/cypress/pull/2635#issuecomment-434839317

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/screenshots.js [hunk 1]
```diff
@@ -18,6 +18,14 @@ const pathSeparatorRe = /[\\\/]/g
 // internal id incrementor
 let __ID__ = null
 
+// many filesystems limit filename length to 255 bytes/characters, so truncate the filename to
+// the smallest common denominator of safe filenames, which is 255 bytes. when ENAMETOOLONG
+// errors are encountered, `maxSafeBytes` will be decremented to at most `MIN_PREFIX_BYTES`, at
+// which point the latest ENAMTOOLONG error will be emitted.
```
Comment (jennifer-shehane) [inline packages/server/lib/screenshots.js:24]:
```suggestion
// which point the latest ENAMETOOLONG error will be emitted.
```
