### PR TITLE
fix(unify): Do not screenshot or trigger the failed event when tests are skipped

### LINKED ISSUE #14867: sync skip; aborting execution error thrown when this.skip() inside function
### Current behavior

Scenarios skipped with use of "@focus" annotation generates a bug as seen on screenshot:
image

Focused scenario(s) run(s) correctly. It happened shortly after upgrading cypress to v.6.4.0 (I was using 6.3.0 before). Also I am using cypress-cucumber-preprocessor v.4.0.0. Problem disappears while running tests without annotation. 
It's my first bug here so if you need any additional info please let me know, I will gladly provide :)  
 
### Desired behavior

It should simply run focused scenario(s) and skip the rest of them without failing .

### Versions
Cypress v.6.4.0
cypress-cucumber-preprocessor v.4.0.0
<!-- Cypress version, last known working Cypress version (if applicable), Browser and version, Operating System, CI

### LINKED ISSUE #17660: Screenshot (failed) captured during skipped tests
### Current behavior

In some circumstances invovling skipped tests and the Cypress 'fail' event listener a failure screenshot will be taken when it shouldn't be. 

### Desired behavior

1. A failure screenshot should never be taken when the test is skipped. 
2. The `fail` event handler shouldn't be triggered during skipped tests. 

### Test code to reproduce

`spec.js`

```js
Cypress.on('fail', () => {
  throw new Error('error')
})

describe('tests', () => {
  before(function () {
    this.skip()
  })
  it('failing test', () => {
    expect(true).to.be.false
  })
})
```

Screen Shot 2021-08-09 at 2 14 45 PM

### Cypress Version

8.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #17660 
- Closes #14867 

### User facing changelog

Skipped tests will no longer trigger the fail event or cause screenshots to be generated.

### Additional details

When a test is skipped, mocha triggers a ["sync skip; aborting execution" error](https://github.com/mochajs/mocha/blob/ac43029d6a86150a48ccd59e50e89ca10c72a9c0/lib/runnable.js#L143). In investigating #17660, it was determined that #14867 had the same root cause. The main difference is that #17660 deals with synchronous tests and #14867 deals with asynchronous tests. In both cases, the fix is to update the failure handling to check if the test is pending (mocha's indicator that the test was skipped) and not fail in that scenario.

### How has the user experience changed?

#17660 Before:

image

#17660 After:

image

#14866 Before:

image

#14866 After:

image

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/src/cypress/cy.ts [hunk 1]
```diff
@@ -1205,6 +1205,12 @@ export default {
             // else just return ret
             return ret
           } catch (err) {
+            // If the runnable was marked as pending, this test was skipped
+            // go ahead and just return
+            if (runnable.isPending()) {
```
Comment (mjhenkes) [inline packages/driver/src/cypress/cy.ts:1210]: What specifically is erroring in the above try block? Could we check is pending up there and return instead of relying on the try block?

Comment (ryanthemanuel) [reply packages/driver/src/cypress/cy.ts:1210]: Mocha is actually throwing the error: https://github.com/mochajs/mocha/blob/ac43029d6a86150a48ccd59e50e89ca10c72a9c0/lib/runnable.js#L143

I don't believe there's a way we could catch it earlier than this as it's being triggered directly from the test being executed here: https://github.com/cypress-io/cypress/pull/19279/files#diff-231d74866a51e1411d172ab6ca0658f7fa712e9676f216ba797c544c47dcbf94R1144

**Review by mjhenkes — APPROVED** [review]

**Comment by chrisbreiding** [comment]
@ryanthemanuel Does this also fix [this user's case](https://github.com/cypress-io/cypress/issues/17660#issuecomment-961912867)? If so, I think we should add a test covering that. Probably need tests covering `it.skip('test', () => {})` in addition to `this.skip()` in any case.

**Review by chrisbreiding — APPROVED** [review]
Looks good 👍 It's just a nitpick, but I prefer not to prefix every test title with 'should'. Just ends up being a bit redundant.

**Review by chrisbreiding — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]
