### PR TITLE
fix: Fix querying shadow dom in cy.within

### LINKED ISSUE #8478: Querying shadow dom in cy.within causes error 'root.getRootNode is not a function'
### Current behavior:

Querying shadow dom in a `cy.within` callback funciton causes the following error: 

```
root.getRootNode is not a function
```

Screen Shot 2020-09-02 at 11 09 03 AM

### Desired behavior:

Querying the shadow dom should work inside the `cy.within` callback function.

### Test code to reproduce

_cypress.json_

```json
{
  "experimentalShadowDomSupport": true
}
```

_cypress/fixures/shadow-dom.html_

```html
<html>
<body>
  <div id="outer">
    <div id="host"></div>
  </div>

  <script>
    document
    .getElementById('host')
    .attachShadow({ mode: 'open' })
    .innerHTML = '<div class="in-shadow-dom">In Shadow DOM</div>'
  </script>
</body>
</html>
```

_spec.js_

```javascript
it('fails querying shadow dom in cy.within', () => {
  cy.visit('/cypress/fixures/shadow-dom.html')
  cy.get('#outer').within(() => {
    cy.get('.in-shadow-dom', { includeShadowDom: true })
  })
})
```

### Versions

Cypress 4.8.0+

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #8478

### User facing changelog

- Fixed an issue where querying the shadow in a `cy.within()` callback would throw the error 'root.getRootNode is not a function'

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/querying_spec.js [hunk 1]
```diff
@@ -357,6 +357,38 @@ describe('src/cy/commands/querying', () => {
...
+      it('when within subject is shadow root, finds element without needing includeShadowDom option', () => {
+        cy.get('#shadow-element-1').shadow().within(() => {
+          cy
+          .get('p')
+          .should('have.length', 1)
+          .should('have.text', 'Shadow Content 1')
+        })
+      })
+
+      it('when within subject is already in shadow dom, finds element without needing includeShadowDom option', () => {
```
Comment (flotwig) [inline packages/driver/cypress/integration/commands/querying_spec.js:383]: so... does this mean that if i have somethin like this (apologies if this is incorrect shadow DOM syntax, i hope my meaning gets across):

```
<shadow-root>
	<foo>
		<shadow-root>
			<bar/>
        </shadow-root>
	</foo>
</shadow-root>
```

...and I do this:

```
cy.get('foo', { includeShadowDom: true }).within(() => {
 	cy.get('bar')
})
```

...`<bar/>` will successfully be found, because `foo` is within a shadow DOM already? even though it traverses an additional shadow bounary?

Comment (chrisbreiding) [reply packages/driver/cypress/integration/commands/querying_spec.js:383]: No, you still need to pass the option to get `bar` without enabling it at a higher level (test config, cypress.json, etc). The option is only in effect for the duration of the command.

So `cy.get('bar', { includeShadowDom: true })` outside the `within` could traverse through multiple shadow boundaries and find `bar`. However, `cy.within` does not persist the `includeShadowDom` behavior. It acts as it normally does and scopes queries inside so if there was another `bar` outside `foo`, it would not also be in the result of `cy.get('bar')`.

Comment (flotwig) [reply packages/driver/cypress/integration/commands/querying_spec.js:383]: ok, that seems reasonable, thanks

**Review by flotwig — APPROVED** [review]
