### PR TITLE
fix: Fix issues with Cypress.require() and TypeScript

### LINKED ISSUE #25885: Unable to use Cypress.require within cy.origin
### Current behavior

I am trying to use `Cypress.require` which was released with 12.6.0 to be able to import external dependencies within a `cy.origin` callback. I am using cypress within an angular project using typescript 4.7.4.

According to the documentation this should work with any typescript module: 
https://docs.cypress.io/api/cypress-api/require

As soon as I start the test suite including a `Cypress.require` it immediately fails with: 
`Error: Cannot find module 'typescript'`

### Desired behavior

Absence of current behavior. `Cypress.require` should work as documented.

### Test code to reproduce

```typescript
// test.js
module.exports = {
    foo: 'bar',
};

// test.cy.ts
describe('Some test', (): void => {
   it('should work', (): void => {
      cy.origin('https://example.com', (): void => {
         const test = Cypress.require('./test.js');
         cy.log('test', test);
      });
   });
});

// cypress config
export default defineConfig({
    e2e: {
        baseUrl: 'http://0.0.0.0:4200',
        supportFile: 'cypress/support/e2e.ts',
        defaultCommandTimeout: 10000,
        video: false,
        experimentalOriginDependencies: true,
    },
});
```

### Cypress Version

12.6.0

### Node version

16.18.0

### Operating System

macOS 12.6.1

### Debug Logs

```shell
CypressError
cy.origin() failed to run the callback function due to the following error:



Processing the origin callback errored:



Error: Cannot find module 'typescript'

Require stack:

- /Users/floriantopf/Library/Caches/Cypress/12.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/cross-origin/process-callback.ts

    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)

    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)

    at PackherdModuleLoader._tryResolveFilename (evalmachine.<anonymous>:1:735006)

    at PackherdModuleLoader._resolvePaths (evalmachine.<anonymous>:1:731827)

    at PackherdModuleLoader.tryResolve (evalmachine.<anonymous>:1:727083)

    at resolve (evalmachine.<anonymous>:1:741891)

    at Function.resolve (evalmachine.<anonymous>:1:752340)

    at customRequire.resolve (<embedded>:5225:1350439)

    at _ (<embedded>:5166:22380)

    at <embedded>:5205:68107

    at a.handle_request (<embedded>:3012:1038)

    at i (<embedded>:3027:1285)

    at <embedded>:2627:2101

    at n (<embedded>:2608:1794)

    at p (<embedded>:2608:1813)

    at IncomingMessage.f (<embedded>:2608:2273)

    at IncomingMessage.emit (node:events:539:35)

    at endReadableNT (node:internal/streams/readable:1345:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)Learn more
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #25885

### Additional details

The root of the fix is two-fold:

- Moving the cy.origin() callback preprocessing into the child process, so it's the same as preprocessing the spec file itself.
- Using the user-installed version of the `typescript` package instead of our own, which actually doesn't exist in the production build of Cypress. This is also the same way it works when preprocessing the spec file itself.

### Steps to test

Set up a test project with a TypeScript spec file and use `Cypress.require()` within `cy.origin()`:

```typescript
describe('Some test', (): void => {
  it('should work', (): void => {
     cy.origin('https://example.com', (): void => {
        const test = Cypress.require('./test.js');
        cy.log('test', test);
     });
  });
});
```

### PR Tasks

- [x] Have tests been added/updated?
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/lib/plugins/child/cross_origin.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
+const md5 = require('md5')
```
Comment (chrisbreiding) [inline packages/server/lib/plugins/child/cross_origin.js:1]: Moved this file into the child process. The main reason for the content changes are converting it from typescript to vanilla JS, since we currently don't have the processing set up for TS within the child process.

File: packages/server/lib/plugins/child/run_plugins.js [hunk 2]
```diff
@@ -14,6 +14,7 @@ const resolve = require('../../util/resolve')
 const browserLaunch = require('./browser_launch')
```
Comment (chrisbreiding) [inline packages/server/lib/plugins/child/run_plugins.js:14]: Most of the changes in here was just moving a couple methods around so that the order made a little more sense (to me at least) when I was updating the tests for this. The only thing I added were the lines referencing `_process:cross:origin:callback`.

File: packages/server/test/unit/plugins/child/run_plugins_spec.js [hunk 3]
```diff
@@ -1,433 +1,278 @@
 require('../../../spec_helper')
```
Comment (chrisbreiding) [inline packages/server/test/unit/plugins/child/run_plugins_spec.js:1]: All these tests had been skipped for over a year, so I unskipped them, fixed the existing ones, and added new ones for my changes to `run_plugins.js`. It doesn't have 100% test coverage of `run_plugins.js` (I didn't add tests for any functionality I didn't add or change), but it's a step in the right direction.

File: system-tests/projects/origin-dependencies/.gitignore [hunk 4]
```diff
@@ -1 +0,0 @@
-!node_modules
```
Comment (chrisbreiding) [inline system-tests/projects/origin-dependencies/.gitignore:1]: This `origin-dependencies` project is no longer used by any system tests.

File: packages/server/lib/plugins/child/cross_origin.js [hunk 5]
```diff
@@ -1,22 +1,19 @@
...
 fs.join = path.join
 
-export const processCallback = ({ file, fn }: Options) => {
+const processCallback = ({ file, fn, projectRoot }) => {
+  const { getFullWebpackOptions } = require('@cypress/webpack-batteries-included-preprocessor')
+
   const source = fn.replace(/Cypress\.require/g, 'require')
-  const webpackOptions = getFullWebpackOptions(file, require.resolve('typescript'))
+  const typescriptPath = resolve.typescript(projectRoot)
+  const webpackOptions = getFullWebpackOptions(file, typescriptPath)
```
Comment (chrisbreiding) [inline packages/server/lib/plugins/child/cross_origin.js:16]: This is the root of the fix. Instead of resolving typescript with our own, we get the path to it the same way we do for regular file preprocessing by finding the user's installed typescript.

File: cli/CHANGELOG.md [hunk 6]
```diff
@@ -7,6 +7,10 @@ _Released 03/14/2023 (PENDING)_
 
 - It is now possible to control the number of connection attempts to the browser using the CYPRESS_CONNECT_RETRY_THRESHOLD Environment Variable. Learn more [here](https://docs.cypress.io/guides/references/advanced-installation#Environment-variables). Addressed in [#25848](https://github.com/cypress-io/cypress/pull/25848).
 
+**Bugfixes:**
+
+- Fixed an issue where using `Cypress.require()` would throw the error `Cannot find module 'typescript'`. Fixes [#25885](https://github.com/cypress-io/cypress/issues/25885).
```
Comment (mschile) [inline cli/CHANGELOG.md:13]: Is this fixing a regression or did it never work?

Comment (chrisbreiding) [reply cli/CHANGELOG.md:13]: It worked with regular `require`, but hasn't worked with `Cypress.require()` since it was re-released.

File: npm/webpack-batteries-included-preprocessor/index.js [hunk 7]
```diff
@@ -181,11 +181,13 @@ preprocessor.defaultOptions = {
 }
 
 preprocessor.getFullWebpackOptions = (filePath, typescript) => {
-  const options = { typescript }
+  const options = typescript ? { typescript } : {}
 
   options.webpackOptions = getDefaultWebpackOptions()
 
-  addTypeScriptConfig({ filePath }, options)
+  if (options.typescript) {
```
Comment (mjhenkes) [inline npm/webpack-batteries-included-preprocessor/index.js]: so the variable we want to check is typescript.options.typescript? Is there a better name for the top variable? Or could we get options directly passed in?

**Review by mschile — APPROVED** [review]

File: npm/webpack-batteries-included-preprocessor/index.js (hunk 7 above)
Comment (chrisbreiding) [reply npm/webpack-batteries-included-preprocessor/index.js]: It wasn't quite typescript.options.typescript, but taking another look at this, I realized it had grown a little convoluted so I refactored it a bit in https://github.com/cypress-io/cypress/pull/25931/commits/fa105050e7c25ca05dafa80ebed7d712acf36bcf

**Review by mjhenkes — APPROVED** [review]
