### PR TITLE
fix: update fixture cache to prevent encoding conflicts

### LINKED ISSUE #32138: `fixture` behavior is inconsistent depending on test and command order
### Current behavior

When using `fixture` with and without an encoding option across different tests, the returned content does not consistently match the specified encoding. Instead, the behavior appears to depend on two factors:

- The order in which the tests are executed.
- The order in which the `fixture` commands are executed within a test.

This inconsistency suggests that `fixture` content may be cached and reused across calls in a way that does not respect the encoding set or the independent nature of tests.

There are several references to caching in https://github.com/cypress-io/cypress/blob/793d2c6dea10f4833ba1bf44be8c450348e7a526/packages/driver/src/cy/commands/fixtures.ts which may be contributing to the unexpected behavior.

### Desired behavior

Each `fixture` call should respect the specified encoding, regardless of test or execution order.

### Test code to reproduce

Steps to Reproduce

1. Create a `simple.xml` (from https://www.w3schools.com/xml/simple.xml) file in the `fixtures` folder in https://github.com/cypress-io/cypress-realworld-app.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<breakfast_menu>
    <food>
        <name>Belgian Waffles</name>
        <price>$5.95</price>
        <description>Two of our famous Belgian Waffles with plenty of real maple syrup</description>
        <calories>650</calories>
    </food>
    <food>
        <name>Strawberry Belgian Waffles</name>
        <price>$7.95</price>
        <description>Light Belgian waffles covered with strawberries and whipped cream</description>
        <calories>900</calories>
    </food>
    <food>
        <name>Berry-Berry Belgian Waffles</name>
        <price>$8.95</price>
        <description>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</description>
        <calories>900</calories>
    </food>
    <food>
        <name>French Toast</name>
        <price>$4.50</price>
        <description>Thick slices made from our homemade sourdough bread</description>
        <calories>600</calories>
    </food>
    <food>
        <name>Homestyle Breakfast</name>
        <price>$6.95</price>
        <description>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</description>
        <calories>950</calories>
    </food>
</breakfast_menu>
```

2. Run these tests:

```js
it.only("should log encoding then no encoding", () => {
  cy.fixture("simple.xml", "base64").then((content) => {
    cy.log(content); // logs base64 string
  });
  cy.fixture("simple.xml").then((content) => {
    cy.log(content); // logs base64 string (unexpected)
  });
});

it.only("should log no encoding then encoding", () => {
  cy.fixture("simple.xml").then((content) => {
    cy.log(content); // logs base64 string (unexpected)
  });
  cy.fixture("simple.xml", "base64").then((content) => {
    cy.log(content); // logs base64 string
  });
});
```

3. Reverse the test order:

```js
it.only("should log no encoding then encoding", () => {
  cy.fixture("simple.xml").then((content) => {
    cy.log(content); // logs utf8 string
  });
  cy.fixture("simple.xml", "base64").then((content) => {
    cy.log(content); // logs utf8 string (unexpected)
  });
});

it.only("should log encoding then no encoding", () => {
  cy.fixture("simple.xml", "base64").then((content) => {
    cy.log(content); // logs utf8 string (unexpected)
  });
  cy.fixture("simple.xml").then((content) => {
    cy.log(content); // logs utf8 string
  });
});
```

### Cypress Version

14.3.2

### Node version

v20.19.0

### Operating System

macOS 15.5

### Debug Logs

I get the following error when pasting the debug output.

> Field can not be longer than 65536 characters

### Other

_No response_

### PR DESCRIPTION
**Pull request by adamalston**
- Closes https://github.com/cypress-io/cypress/issues/32138

### Additional details

N/A

### Steps to test

1. Revert the code change.
2. Run the test and verify it fails due to encoding being ignored.
3. Restore the code change.
4. Run the test and verify it passes with correct encoding behavior.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@adamalston Another issue related to caching of fixtures. I'm unsure if your change would address this also. Thanks for the contribution.

**Comment by jennifer-shehane** [comment]
@adamalston Can you ensure you have checked the "Allow edits from maintainers" checkbox for this PR? I wasn't able to push a commit to trigger a CI run for some reason. 

31393427-b3105d44-ada9-11e7-80f2-0dac51e3919e

**Comment by adamalston** [comment]
I don't see a link in https://github.com/cypress-io/cypress/pull/32151#issuecomment-3150643378. Is there supposed to be one?

If you meant to link to https://github.com/cypress-io/cypress/issues/32139, I’ve already done some investigation. I have a probable fix.

**Comment by jennifer-shehane** [comment]
@adamalston Meant to link to this issue in my first comment. https://github.com/cypress-io/cypress/issues/4716

**Comment by adamalston** [comment]
> @adamalston Can you ensure you have checked the "Allow edits from maintainers" checkbox for this PR? I wasn't able to push a commit to trigger a CI run for some reason.

I'm curious, why can't contributors trigger CI?

> @adamalston Meant to link to this issue in my first comment. #4716

These changes don't address that issue. I can investigate a fix though. Maybe `writeFile` to a fixture should invalidate its cache entry, if it exists.

**Comment by adamalston** [comment]
All failures appear to be intermittent failures or issues unrelated to my changes. Let me know if that's not the case.

File: packages/driver/src/cy/commands/fixtures.ts [hunk 1]
```diff
@@ -54,6 +40,14 @@ export default (Commands, Cypress, cy, state, config) => {
         options.encoding = args[0]
       }
 
+      const cacheKey = `${fixture}\u0000${options.encoding}`
```
Comment (AtofStryker) [inline packages/driver/src/cy/commands/fixtures.ts]: helps keep the cache key clean in the case the encoding option is not defined
```suggestion
      const cacheKey = `${fixture}\u0000${options.encoding || ''}`
```

**Review by AtofStryker — APPROVED** [review]
Thanks for this contribution @adamalston!

File: packages/driver/src/cy/commands/fixtures.ts (hunk 1 above)
Comment (adamalston) [reply packages/driver/src/cy/commands/fixtures.ts]: Did https://github.com/cypress-io/cypress/commit/f693c4cccccfb532265cb4fbfff45cc328acc5cc, the change related to https://github.com/cypress-io/cypress/pull/32151#discussion_r2263330697, introduce a regression?

At this point, `options.encoding` can be either `null` or `undefined`. The ` || ''` operation coalesces both values to an empty string, conflating two distinct cases that should be treated separately.

Make these changes and run the test:

```diff
diff --git a/packages/driver/cypress/e2e/commands/fixtures.cy.js b/packages/driver/cypress/e2e/commands/fixtures.cy.js
index 553e14a5ae..83899f40ae 100644
--- a/packages/driver/cypress/e2e/commands/fixtures.cy.js
+++ b/packages/driver/cypress/e2e/commands/fixtures.cy.js
@@ -266,9 +266,12 @@ describe('src/cy/commands/fixtures', () => {
         })
       })
 
-      it('should respect encoding specification', () => {
+      it.only('should respect encoding specification', () => {
         const fixture = 'comma-separated.csv'
 
+        cy.fixture('aut-commands.html', { encoding: null })
+        cy.fixture('aut-commands.html')
+
         cy.fixture(fixture, 'base64').then((content) => {
           cy.wrap(content).should('eq', 'T25lLFR3byxUaHJlZQoxLDIsMwo=')
           cy.wrap(content).as('base64')
diff --git a/packages/driver/src/cy/commands/fixtures.ts b/packages/driver/src/cy/commands/fixtures.ts
index 91b99a50db..07fa9fd4f7 100644
--- a/packages/driver/src/cy/commands/fixtures.ts
+++ b/packages/driver/src/cy/commands/fixtures.ts
@@ -41,6 +41,8 @@ export default (Commands, Cypress, cy, state, config) => {
       }
 
       const cacheKey = `${fixture}\u0000${options.encoding || ''}`
+
+      console.log({ encoding: options.encoding, cacheKey })
       const cachedContent = cache[cacheKey]
 
       if (cachedContent) {
```

Console:

```console
{encoding: null, cacheKey: 'aut-commands.html\x00'}
{encoding: undefined, cacheKey: 'aut-commands.html\x00'}
{encoding: 'base64', cacheKey: 'comma-separated.csv\x00base64'}
{encoding: undefined, cacheKey: 'comma-separated.csv\x00'}
```

Then, revert https://github.com/cypress-io/cypress/commit/f693c4cccccfb532265cb4fbfff45cc328acc5cc and rerun the test.

Console:

```console
{encoding: null, cacheKey: 'aut-commands.html\x00null'}
{encoding: undefined, cacheKey: 'aut-commands.html\x00undefined'}
{encoding: 'base64', cacheKey: 'comma-separated.csv\x00base64'}
{encoding: undefined, cacheKey: 'comma-separated.csv\x00undefined'}
```

Comment (adamalston) [reply packages/driver/src/cy/commands/fixtures.ts]: I have unresolved this comment. @AtofStryker, any thoughts on https://github.com/cypress-io/cypress/pull/32151#discussion_r2264007120?

Comment (adamalston) [reply packages/driver/src/cy/commands/fixtures.ts]: https://github.com/cypress-io/cypress/issues/32274
