### PR TITLE
fix(cypress/schematic): run configuration does not work anymore without baseUrl 

### LINKED ISSUE #21555: @cypress/schematic: Run configuration does not work anymore without baseUrl
### Current behavior

After upgrading from `1.6.0` to `1.7.0` all tests stopped working because `cy.visit('/')` is trying to access a file instead of a URL. Now the `baseUrl` has to be defined additionally in order to run the tests.

### Desired behavior

Cypress takes the host and the port of the `devServerTarget`. The host and the port should be defined once and not twice. There should be a reference instead.

## Current workaround:
Add `baseUrl: http://localhost:{myPort}` to the `cypress-run` and `cypress-open` options in `angular.json` or to `cypress.json`

### Test code to reproduce

angular.json:
```json
...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            ...
          },
          "configurations": {
            "test": {
              ...
            }
          },
          "defaultConfiguration": ""
        },
        "serve-test": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myProject:build:test",
            "port": 5000
          },
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "myProject:serve-test",
            "watch": true,
            "headless": false,
            "browser": "chrome"
          },
          "configurations": {
            "production": {
              "devServerTarget": "myProject:serve-test"
            }
          }
        }
...
```

### Cypress Version

9.6.1

### Other

Angular core: `12.2.16`
cli, @angular-devkit/build-angular: `12.2.17`

### PR DESCRIPTION
**Pull request by admah**
Fixes #21555.

Users can now add custom options to `devServerTarget` in `angular.json` to specify `baseUrl`:

```json
"options": {
  "host": "localhost",
  "port": 4200
},
```

### CODE REVIEW

File: npm/cypress-schematic/src/builders/cypress/cypressBuilderOptions.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@ export interface CypressBuilderOptions extends JsonObject {
   configFile: string | false
   browser: 'electron' | 'chrome' | 'chromium' | 'canary' | 'firefox' | 'edge' | string
   devServerTarget: string
+  devServerBaseUrl: string
```
Comment (ZachJW34) [inline npm/cypress-schematic/src/builders/cypress/cypressBuilderOptions.ts:8]: This option would never be used since it is derived from the dev-server, so I think we can remove this.

Comment (admah) [reply npm/cypress-schematic/src/builders/cypress/cypressBuilderOptions.ts:8]: Good point!

Comment (ZachJW34) [reply npm/cypress-schematic/src/builders/cypress/cypressBuilderOptions.ts]: A general rule is that if the option is available in the `schema.json` it should be listed here as well, so I'd add back in the `devServerTarget` since you shouldn't have to cast the type in the builder.

**Review by ZachJW34 — APPROVED** [review]

**Comment by admah** [comment]
@ZachJW34 what do we typically do with the Percy tests when they fail? Nothing I touched should have altered those in any way.

**Comment by ZachJW34** [comment]
@admah Your changes have no impact on UI so we can ignore the Percy diffs. I reran the build that flaked, so let's get this merged once everything (besides Percy) is green
