### PR TITLE
fix: Introduce CypressCommandLine namespace to type NPM module api

### LINKED ISSUE #7309: Types not exported in .d.ts
### Current behavior:
The  types declared in cypress-npm-api.d.ts cannot be used by calling code since they are not being exported. 

### Desired behavior:
The types should be exported in order to be usable.

### Test code to reproduce
N/A

### Versions
Cypress 4.5.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-167) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7309 

### User facing changelog

Moved types inside `'cypress'` module to `CypressCmd` namespace to make them usable. 

### Additional details

- Why was this change necessary? Types defined in `cypress-npm-api.d.ts` weren't usable for users who want to create their own TypeScript commands.
- What is affected by this change? N/A
- Any implementation details to explain? N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Abrupt test failure.

**Comment by flotwig** [comment]
@sainthkh does this make the types exported from the NPM package, or does it only create an ambient global namespace `CypressCmd`?

File: cli/types/cypress-npm-api.d.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@
 // in the future the NPM module itself will be in TypeScript
 // but for now describe it as an ambient module
 
-declare module 'cypress' {
+declare namespace CypressCmd {
```
Comment (bahmutov) [inline cli/types/cypress-npm-api.d.ts:9]: I think this would be better named `CypressCommandLine`

**Comment by sainthkh** [comment]
@flotwig We cannot export interfaces in the module because there is `export = cypress`. Because of that, I had to create ambient global namespace, `CypressCommandLine`.

**Comment by jennifer-shehane** [comment]
Should this be documented somewhere in our TypeScript docs? @sainthkh

**Comment by sainthkh** [comment]
How about adding `types for module api` section and an example like below?

```ts
cypress.run({ env })
    .then((result: CypressCommandLine.CypressRunResult) => {
      logger.info(result.totalTests);
      logger.info(result.totalFailed);
    });
```
