### PR TITLE
fix: Support path aliases in plugins file

### LINKED ISSUE #8555: [TypeScript] Path aliases not handled in plugins file
### Current behavior:

Using a path alias in the plugins file results in a `Cannot find module` error.

Screen Shot 2020-09-11 at 10 03 53 AM

### Desired behavior:

Path aliases should be supported when used in the plugins file.

### Test code to reproduce

https://github.com/cypress-io/cypress-test-tiny/tree/alias-ts-paths

_package.json_

```json
{
  "devDependencies": {
    "cypress": "5.1.0",
    "typescript": "4.0.2"
  }
}
```

_tsconfig.json_

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "baseUrl": "./src",
    "paths": {
      "@apps/*": ["*"]
    },
  },
  "include": ["cypress/**/*.ts"]
}
```

_src/commons-e2e.ts_

```typescript
export const forward = true
```

_cypress/plugins/index.ts_

```typescript
import { forward } from '@apps/commons-e2e'
console.log('forward is', forward)
export default function () {}
```

### Versions

Cypress 4.6.0+

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #8555

### User facing changelog

- Fixed an issue where using TypeScript path aliases in the plugins file would error

### How has the user experience changed?

Users can now use TypeScript path aliases or 3rd party code that relies on 3rd party path aliases in their plugins file without it erroring.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/server/lib/util/ts-node.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ const registerTsNode = (projectRoot, pluginsFile) => {
     debug('typescript path: %s', tsPath)
     debug('registering project TS with options %o', tsOptions)
 
+    require('tsconfig-paths/register')
```
Comment (flotwig) [inline packages/server/lib/util/ts-node.js:30]: does `ts-node` not expose similar functionality? seems a bit weird that it wouldn't

**Review by flotwig — APPROVED** [review]
@chrisbreiding LGTM, as long as you're sure that `ts-node` doesn't have a built-in way to do this

**Comment by chrisbreiding** [comment]
It doesn't. They even recommend using `tsconfig-paths`: https://github.com/TypeStrong/ts-node#loading-tsconfigjson

It's something I find a bit ridiculous about TypeScript. It supports configuring these path aliases but doesn't support it at runtime. For Node and the browser, you need to go out of your way to make it work.
