### PR TITLE
fix(route2): always yield request body when .waited

### LINKED ISSUE #8695: Check request body using cy.route2()
### Current behavior
When I use cy.wait('@Test') to check the request that was mocked using cy.route2(), it does not contain a request body.
image

### Desired behavior
I expected a behavior similar to the one using cy.route().
image

### Test code to reproduce
```js
/// <reference types="cypress"/>

describe('Patch Test', () => {
  before(() => {
    cy.visit('https://www.test-cors.org/');
  })

  const method = 'POST';

  it('Using cy.route2()', () => {
    cy.route2(method, '**', {}).as('Route2');

    cy.get('#client_method').select(method);
    cy.get('#client_postdata').type("test");
    cy.get('#btnSendRequest').click();

    cy.wait('@Route2').then(req => {
      console.log(req);
      cy.wrap(req.request).its('body').should('contain', 'test');
    })
  })
  it('Using cy.route()', () => {
    cy.server();
    cy.route(method, '**', {}).as('Route');

    cy.get('#client_method').select(method);
    cy.get('#client_postdata').type("test");
    cy.get('#btnSendRequest').click();

    cy.wait('@Route').then(req => {
      console.log(req);
      cy.wrap(req.request).its('body').should('contain', 'test');
    })
  })
})
```

### Versions
Cypress 5.3.0
Windows 10
Chrome 85

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #8695 

### User facing changelog

Fixed an issue where `request.body` was not available when using `cy.wait` on an aliased `cy.route2` route which had not been intercepted.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/net_stubbing_spec.ts [hunk 1]
```diff
@@ -1699,6 +1699,25 @@ describe('network stubbing', function () {
...
+        }).wait('@foo').its('request.body').should('eq', 'some body')
+      })
+
+      it('when intercepted', function () {
+        cy.route2('/post-only', (req) => {
+          req.body = 'changed'
+        }).as('foo')
+        .then(() => {
+          $.post('/post-only', 'some body')
+        }).wait('@foo').its('request.body').should('eq', 'changed')
```
Comment (bahmutov) [inline packages/driver/cypress/integration/commands/net_stubbing_spec.ts:1717]: I think this is an important detail: the request body will be the changed one

**Review by bahmutov — APPROVED** [review]
nice
