### PR TITLE
fix desktop gui specs not being watched for file changes

### LINKED ISSUE #5933: Desktop GUI specs are not updating when they're changed due to regression with file watching

### PR DESCRIPTION
**Pull request by brian-mann**
- Fixes #5933 

### User facing changelog

- Fixed a bug where the specs list in interactive mode would not refresh when files are changed on disk.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by brian-mann** [comment]
@flotwig can you do a correct PR template and write tests for this thing? thx <3

File: packages/server/test/unit/open_project_spec.js [hunk 1]
```diff
@@ -141,5 +142,15 @@ describe('lib/open_project', () => {
         expect(onChange).to.be.calledOnce
       })
     })
+
+    it('destroys and creates specsWatcher as expected', function () {
+      expect(openProject.specsWatcher).to.exist
+      openProject.stopSpecsWatcher()
+      expect(openProject.specsWatcher).to.be.null
+      openProject.getSpecChanges()
```
Comment (brian-mann) [inline packages/server/test/unit/open_project_spec.js]: this is missing a `return` :-(
