### PR TITLE
perf: fix proxy correlation timeout issues

### LINKED ISSUE #28734: significant proxy regression since v13.3.2
### Current behavior

Something changed internally where requests that used to finish in under 100ms now take over 2s. Depending on how tests and data calls are structured, this results in a number of flaky and consistent timeouts.

### Desired behavior

Requests shouldn't consistently take an additional 2s beyond the server time.

### Test code to reproduce

Cannot provide, but I've narrowed it down to v13.3.2 where the regression starts. Requests still complete as expected through v13.3.1.

### Cypress Version

13.6.2

### Node version

v18.19.0

### Operating System

macOS 14.2.1

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by mschile**
- Closes https://github.com/cypress-io/cypress/issues/28734

### Additional details

In Cypress v13.3.2 we started [resetting](https://github.com/cypress-io/cypress/blob/04a1156ccd6093441c17ea04c98570ef8470a239/packages/proxy/lib/http/index.ts#L418) the browser pre-requests at different points during the test/spec execution. Removing the pre-requests caused some of the proxy requests to hit the correlation timeout (2s) if the proxy request came in after the pre-request was removed. In one instance, the correlation timeout was observed to happen when a request was aborted due to navigation or another `cy.visit`.

In order to resolve the issue, I removed resetting the pre-requests to only happen in-between specs to ensure we start each spec clean. Then I added an `res.on('close')` listener when waiting for the pre-request correlation. If the `onClose` handler is called before the request is correlated (this implies the request has been canceled/aborted), the `onError` handler is called.

Removed the `resetPreRequests` logic that was added with https://github.com/cypress-io/cypress/issues/28545 since it has been superseded by these changes.

### Steps to test

Added a system test that verifies no requests hit the correlation timeout.

### How has the user experience changed?

Users should no longer see requests hang for 2s.

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by AtofStryker — APPROVED** [review]

File: packages/proxy/lib/http/util/prerequests.ts [hunk 1]
```diff
@@ -275,6 +275,7 @@ export class PreRequests {
       proxyRequestReceivedTimestamp: performance.now() + performance.timeOrigin,
       timeout: setTimeout(() => {
         ctxDebug('Never received pre-request or url without pre-request for request %s after waiting %sms. Continuing without one.', key, this.requestTimeout)
+        debug('Never received pre-request or url without pre-request for request %s after waiting %sms. Continuing without one.', key, this.requestTimeout)
```
Comment (ryanthemanuel) [inline packages/proxy/lib/http/util/prerequests.ts:278]: What is the difference between ctxDebug and debug?

Comment (mschile) [reply packages/proxy/lib/http/util/prerequests.ts:278]: `ctxDebug` is enabled when `cypress-verbose:proxy:http` is set which includes a lot of other debug information. I wanted an easier way to see just the timeout issues so I added this debug which is set when `cypress:proxy:http:util:prerequests` is set.

**Review by ryanthemanuel — APPROVED** [review]

**Comment by ryanthemanuel** [comment]
Nice cleanup on this!
