### PR TITLE
error message for pointer-events:none

### LINKED ISSUE #3164: Better error message for actionability fail with pointer-events:none
We should have a better error message when a click fails due to `pointer-events:none`

### PR DESCRIPTION
**Pull request by Bkucera**
fix #3164 

image

#### still needs work on the console error message (still says it's covered):
image

#### tasks:
- [x] fix console error message
- [x] fix error message adding footer (link + force:true message)
- [x] add test for force:true

### CODE REVIEW

**Comment by Bkucera** [comment]
@brian-mann what do you think about have a general `ensureComputedStyle` and making a the error message generic?

File: packages/driver/src/cypress/error_messages.coffee [hunk 1]
```diff
@@ -182,6 +182,17 @@ module.exports = {
...
+    pointer_events_none: (obj) ->
+      """
+        #{cmd(obj.cmd)} failed because this element:
+
+        #{obj.element}
+
+        has style 'pointer-events:none'#{if obj.elementInherited then ", inherited from this element:" else ""}
+
+        #{if obj.elementInherited then obj.elementInherited else ""}
+
```
Comment (Bkucera) [inline packages/driver/src/cypress/error_messages.coffee]: not sure the best way to make this error message conditional

File: packages/driver/src/cypress/utils.coffee [hunk 2]
```diff
@@ -147,6 +147,19 @@ module.exports = {
     .join('\n\n')
     .value()
 
+
+  findParent: (el, fn) ->
```
Comment (brian-mann) [inline packages/driver/src/cypress/utils.coffee]: this should be part of `$dom` utils, not regular utils

File: packages/driver/src/cypress/utils.coffee [hunk 3]
```diff
@@ -147,6 +147,19 @@ module.exports = {
...
+    prevEl = el
+    curEl = el.parentElement
+    retEl = null
+    while (curEl)
```
Comment (brian-mann) [inline packages/driver/src/cypress/utils.coffee]: generally i prefer using a function and tail recursion as opposed to a `while` statement because it's clearer and oftentimes its easier to refactor and additionally provides a "name" to indicate how it's traversing

File: packages/driver/test/cypress/integration/commands/actions/click_spec.coffee [hunk 4]
```diff
@@ -131,6 +131,26 @@ describe "src/cy/commands/actions/click", ->
       cy.get("#button").click().then ->
         expect(events).to.deep.eq ["mousedown", "mouseup", "click"]
 
+    describe 'pointer-events:none', ->
+      beforeEach ->
+        cy.$$('<div id="ptr" style="position:absolute;width:200px;height:200px;background-color:aliceblue;"></div>').appendTo cy.$$('#dom')
+        ptrNone = cy.$$('<div id="ptrNone" style="position:absolute;width:400px;height:400px;background-color:salmon;pointer-events:none"></div>').appendTo(cy.$$('#dom'))
+        cy.$$('<div id="ptrNoneChild" style="position:absolute;top:50px;left:50px;width:200px;height:200px;background-color:grey;"></div>').appendTo ptrNone
+      it 'element behind pointer-events:none should still get click', ->
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.coffee]: newlines between `it` and `beforeEach` plz

File: packages/driver/test/cypress/integration/commands/actions/click_spec.coffee [hunk 5]
```diff
@@ -131,6 +131,26 @@ describe "src/cy/commands/actions/click", ->
...
+          expect(err.message).to.not.contain 'inherited from'
+          
+        cy.get('#ptrNone').click {timeout: 300}
+      it 'should error with message about pointer-events and include inheritance', ->
+        cy.once 'fail', (err) ->
+          expect(err.message).to.contain 'has style \'pointer-events:none\', inherited from this element:'
+          expect(err.message).to.contain '<div id="ptrNone"'
+
+        cy.get('#ptrNoneChild').click {timeout: 300}
+
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.coffee]: you should add a test that ensure that the test **does not fail** when you use `{ force: true }`

File: packages/driver/test/cypress/integration/commands/actions/click_spec.coffee [hunk 6]
```diff
@@ -131,6 +131,26 @@ describe "src/cy/commands/actions/click", ->
...
 
+    describe 'pointer-events:none', ->
+      beforeEach ->
+        cy.$$('<div id="ptr" style="position:absolute;width:200px;height:200px;background-color:aliceblue;"></div>').appendTo cy.$$('#dom')
+        ptrNone = cy.$$('<div id="ptrNone" style="position:absolute;width:400px;height:400px;background-color:salmon;pointer-events:none"></div>').appendTo(cy.$$('#dom'))
+        cy.$$('<div id="ptrNoneChild" style="position:absolute;top:50px;left:50px;width:200px;height:200px;background-color:grey;"></div>').appendTo ptrNone
+      it 'element behind pointer-events:none should still get click', ->
+        cy.get('#ptr').click() # should pass with flying colors
+      it 'should error with message about pointer-events', ->
+        cy.once 'fail', (err) ->
```
Comment (brian-mann) [inline packages/driver/test/cypress/integration/commands/actions/click_spec.coffee]: there is nothing in this test that guarantees the test hit the `fail` callback. for instance, it's theoretically possible for this test to comment out the `fail` callback and still pass.

In order to test that the `fail` callback **did** get called you either spy on it, or you use the mocha `(done)` callback and explicitly call `done()` in the callback.

File: packages/driver/src/cypress/error_messages.coffee [hunk 7]
```diff
@@ -182,6 +182,17 @@ module.exports = {
...
+      """
+    pointer_events_none: (obj) ->
+      """
+        #{cmd(obj.cmd)} failed because this element:
+
+        #{obj.element}
+
+        has style 'pointer-events:none'#{if obj.elementInherited then ", inherited from this element:" else ""}
+
+        #{if obj.elementInherited then obj.elementInherited else ""}
```
Comment (brian-mann) [inline packages/driver/src/cypress/error_messages.coffee]: You're missing the `https://on.cypress.io/element-cannot-be-interacted-with` at the bottom of this error - and additionally we'll need to update the docs to account for this situation.

You're also missing the verbiage about bypassing this error with `{ force: true }`.

Lastly, i would add a small bit explaining to the user that `pointer-events: none` prevents this element from receiving any events or being able to be interacted with the mouse, keyboard, etc which is **why** we cannot interact with it.

File: packages/driver/src/cypress/error_messages.coffee [hunk 8]
```diff
@@ -181,6 +181,20 @@ module.exports = {
 
       Fix this problem, or use {force: true} to disable error checking.
 
+      https://on.cypress.io/element-cannot-be-interacted-with
+      """
+    pointer_events_none: (obj) ->
+      """
+        #{cmd(obj.cmd)} failed because this element:
```
Comment (jennifer-shehane) [inline packages/driver/src/cypress/error_messages.coffee]: Is the indentation of this correct? Looks like it should not be tabbed in...

File: packages/driver/src/dom/elements.js [hunk 9]
```diff
@@ -536,6 +536,25 @@ const isDescendent = ($el1, $el2) => {
...
 }
 
+const findParent = (el, fn) => {
+  let prevEl = el
+  let curEl = el.parentElement
+  let retEl = null
+
+  let counter = 0
+
+  while (curEl && counter++ < 100) {
```
Comment (jennifer-shehane) [inline packages/driver/src/dom/elements.js]: why the counter 🤔 	just curious.

Comment (Bkucera) [reply packages/driver/src/dom/elements.js]: removed

**Comment by jennifer-shehane** [comment]
@Bkucera Whats up here with the console.error message? Did you ever finish fixing this so that it shows the same error in the console on click?
