### PR TITLE
fix: cy.intercept delay works correctly with 204 No Content

### LINKED ISSUE #15188: cy.intercept: delay is not working on 204 No Content
### Current behavior
When using `cy.intercept('POST', url, { statusCode: 204, delay: 5000 })` `delay` (or `delayMs`) is not respected.

Is this intended behavior? If so, why?

When running tests below I see: 

First spec: 
image

Second spec:
image

### Desired behavior
When a request responds with 204 No Content `delay` (or `delayMs`) should work.

### Test code to reproduce
```js
it('post a comment 200 OK', () => {
    cy.intercept('POST', 'https://jsonplaceholder.cypress.io/comments', {
            statusCode: 200,
            delay: 5000,
    }).as('success');

    cy.visit('https://example.cypress.io/commands/network-requests');

    cy.get('.network-post-comment').should('have.value', '')

    cy.get('.btn-success').click();

    cy.wait('@success'); // waits 5000 ms

    cy.get('.network-post-comment').should('contain', 'POST successful!')
});

it('post a comment 204 No Content', () => {
    cy.intercept('POST', 'https://jsonplaceholder.cypress.io/comments', {
            statusCode: 204, // delay is not respected
            delay: 5000,
    }).as('success');

    cy.visit('https://example.cypress.io/commands/network-requests');

    cy.get('.network-post-comment').should('have.value', '')

    cy.get('.btn-success').click();

    cy.wait('@success'); // resolves immediately

    cy.get('.network-post-comment').should('contain', 'POST successful!')
});
```
### Versions

* Cypress: 6.5.0
* Chrome: 88.0.4324.182
* MacOS: 10.15.7

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #15188

### User facing changelog

`delay` now works correctly with the `statusCode: 204`.

### Additional details
- Why was this change necessary? => `delay` didn't work correctly with `statusCode: 204`. 
- What is affected by this change? => N/A
- Any implementation details to explain? => It was happening because of `setTimeout` inside the [`getBodyStream`](https://github.com/cypress-io/cypress/blob/20de3e585fad675cb4abbd9a4764fa1c95e11a2a/packages/net-stubbing/lib/server/util.ts#L198-L226). It is called after the delay [when response is not an empty body but it isn't when it's not](https://github.com/cypress-io/cypress/blob/20de3e585fad675cb4abbd9a4764fa1c95e11a2a/packages/net-stubbing/lib/server/middleware/response.ts#L48-L54). I fixed this by changing `getBodyStream` as `async`.

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/net-stubbing/lib/server/util.ts [hunk 1]
```diff
@@ -220,11 +220,19 @@ export function getBodyStream (body: Buffer | string | Readable | undefined, opt
...
 }
 
+function wait (fn, ms) {
+  return new Promise((resolve) => {
+    setTimeout(() => {
+      resolve(fn())
+    }, ms)
+  })
+}
+
```
Comment (sainthkh) [inline packages/net-stubbing/lib/server/util.ts:235]: What is the right place for this utility function?

Comment (flotwig) [reply packages/net-stubbing/lib/server/util.ts:235]: Bluebird offers `Promise.delay` which may meet your needs. If it's just used in this function/file then this is fine.

**Review by flotwig — DISMISSED** [review]
Very good, nice fix.

File: packages/net-stubbing/lib/server/util.ts (hunk 1 above)
Comment (sainthkh) [reply packages/net-stubbing/lib/server/util.ts]: I changed the code with `Promise.delay`.

Comment (flotwig) [reply packages/net-stubbing/lib/server/util.ts]: @sainthkh There seems to be a type error with the change

**Comment by jennifer-shehane** [comment]
@sainthkh Is this ready for rereview?

**Review by flotwig — CHANGES_REQUESTED** [review]
Check create-build-artifacts, there is a type error

**Comment by sainthkh** [comment]
I rolled back and decided to use `wait` function instead. To use `bluebird` inside `net-stubbing` package, it should be included as a dependency.

**Review by flotwig — APPROVED** [review]
