### PR TITLE
misc: update postinstall cypress open instructions

### LINKED ISSUE #29935: Outdated run instructions after binary install
### Current behavior

Cypress binary installation may output the following instructions after completion:

```text
You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress
```

1. This instruction does not work on a default installation of Yarn Modern
2. The link https://on.cypress.io/installing-cypress is about installing Cypress, not about running it.

- A resolved documentation issue also described compatibility issues in detail in https://github.com/cypress-io/cypress-documentation/issues/5382

### Desired behavior

Cypress binary installation should provide instructions which are correct and up-to-date for each of the supported package managers. So either list these out explicitly:

| Package Manager | Command                  |
| --------------- | ------------------------ |
| npm             | `npx cypress open`       |
| Yarn            | `yarn cypress open`      |
| pnpm            | `pnpm cypress open` |

and / or provide a link which describes how to run Cypress:

- https://on.cypress.io/opening-the-app  or
- https://on.cypress.io/command-line 

### Test code to reproduce

Using Yarn Modern defaults:

```shell
corepack disable
npm install yarn@latest -g
mkdir cy-yarn-modern
cd cy-yarn-modern
git init
yarn set version stable
yarn init -y
yarn add cypress --dev
yarn cypress install --force
```

### Cypress Version

`13.13.1`

### Node version

`v20.16.0` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```shell
$ yarn cypress install --force

Cypress 13.13.1 is installed in /home/mike/.cache/Cypress/13.13.1

Installing Cypress (version: 13.13.1)

✔  Downloaded Cypress
✔  Unzipped Cypress
✔  Finished Installation /home/mike/.cache/Cypress/13.13.1

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress

$ node_modules/.bin/cypress open
bash: node_modules/.bin/cypress: No such file or directory
```

### Other

https://github.com/cypress-io/cypress/blob/0d5065a10646b7a4adf49a613553fef96210bc99/cli/lib/tasks/install.js#L57-L63

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress/issues/29935

### Additional details

The Cypress binary installation previously output the following instructions after completion:

```text
You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress
```

1. This instruction does not work on a default installation of Yarn Modern
2. The link https://on.cypress.io/installing-cypress is about installing Cypress, not about running it.

The text is changed to provide the following information:

| Package Manager | Command                  |
| --------------- | ------------------------ |
| npm             | `npx cypress open`       |
| Yarn            | `yarn cypress open`      |
| pnpm            | `pnpm exec cypress open` |

https://on.cypress.io/opening-the-app

### Steps to test

See https://github.com/cypress-io/cypress/blob/develop/cli/README.md#manual

### How has the user experience changed?

**BEFORE**

install before

**AFTER**

install after

### PR Tasks

- [x] Have tests been added/updated?
  - snapshots updated
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
  - https://github.com/cypress-io/cypress-documentation/pull/5390 already provided this update in July 2023
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I haven't worked out how to simulate the install on a develop branch yet.

File: cli/lib/tasks/install.js [hunk 1]
```diff
@@ -55,12 +55,15 @@ const displayCompletionMsg = () => {
 
   logger.log()
   logger.log(
-    'You can now open Cypress by running:',
-    chalk.cyan(path.join('node_modules', '.bin', 'cypress'), 'open'),
+    'You can now open Cypress by running one of the following, depending on your package manager:',
   )
```
Comment (jennifer-shehane) [inline cli/lib/tasks/install.js:60]: I think it'd be more readable with an extra space here:
```suggestion
logger.log()
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Thanks for updating and updating the snapshots along with it.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I think you would follow these instructions: https://github.com/cypress-io/cypress/blob/develop/cli/README.md#manual I haven't done this in a while, but I think it should still be up to date.

File: cli/lib/tasks/install.js (hunk 1 above)
Comment (MikeMcC399) [reply cli/lib/tasks/install.js:60]: I agree with you, which means I need to regenerate the snap-shots.

Comment (MikeMcC399) [reply cli/lib/tasks/install.js:60]: see https://github.com/cypress-io/cypress/pull/29957/commits/9219421e8ca77be0997a4e741e694bc51627ea72 for additional spacing line and snapshots

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I think you would follow these instructions: https://github.com/cypress-io/cypress/blob/develop/cli/README.md#manual I haven't done this in a while, but I think it should still be up to date.

Thanks for the hint! I got this to work and was able to log a simulation and post it in the original post.

File: cli/lib/tasks/install.js [hunk 2]
```diff
@@ -55,12 +55,16 @@ const displayCompletionMsg = () => {
...
 
   logger.log()
-  logger.log(chalk.grey('https://on.cypress.io/installing-cypress'))
+  logger.log(chalk.cyan('npx cypress open'))
+  logger.log(chalk.cyan('yarn cypress open'))
+  logger.log(chalk.cyan('pnpm cypress open'))
```
Comment (jennifer-shehane) [inline cli/lib/tasks/install.js]: Maybe it would look better with a list too? Sorry for more changes. It looks like a wall of text when see the examples. There is some convention of this in other places: https://github.com/cypress-io/cypress/blob/develop/cli/lib/tasks/install.js#L49

```suggestion
  logger.log(chalk.cyan('- npx cypress open'))
  logger.log(chalk.cyan('- yarn cypress open'))
  logger.log(chalk.cyan('- pnpm cypress open'))
```

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]

File: cli/lib/tasks/install.js (hunk 2 above)
Comment (MikeMcC399) [reply cli/lib/tasks/install.js]: I agree again with your formatting suggestion. Addressed in https://github.com/cypress-io/cypress/pull/29957/commits/11e5f0d4ba53fc4ae622c395c15efd6ad2b1b4f5.

I also updated with a screenshot to the original posting which also shows the colors rendered.

**Comment by MikeMcC399** [comment]
- waiting for PR https://github.com/cypress-io/cypress/pull/29964 before updating this branch to the base branch

**Review by jennifer-shehane — APPROVED** [review]

**Review by mschile — APPROVED** [review]
