### PR TITLE
retry CRI.List when connecting to the browser

### LINKED ISSUE #6053: Error: could not find CRI target / Failed to connect to Chrome
### Current behavior:

`cypress run --headless --browser chrome` is failing in GitHub Actions with this error:

```
Failed to connect to Chrome, retrying in 1 second (attempt 18/32)
could not find CRI target
Error: could not find CRI target
    at lazyAssLogic (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/lazy-ass/index.js:115:28)
    at /home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/lib/browsers/protocol.js:81:5
    at tryCatcher (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/.cache/Cypress/3.8.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

Link to the failing build: https://github.com/sweetalert2/sweetalert2/runs/365206238

### Steps to reproduce: (app code and test code)

Here's the GitHub Actions configuration: https://github.com/sweetalert2/sweetalert2/blob/master/.github/workflows/coverage.yml

The `cy:run` command is defined here: https://github.com/sweetalert2/sweetalert2/blob/master/package.json#L98

### Versions

Cypress: 3.8.1 
Operating System: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by bahmutov**
- Closes #6053 
- retries `CRI.List` if the `about:blank` page cannot be found, maybe the browser is starting

### User facing changelog

The CI runs should stop failing due to Cypress not being able to find the tab to control.

### Additional details

I did experiments with closing and opening Chrome Canary with lots of tabs and extensions and could get into situations where the initial `CRI.List` call returns no targets, but the next call returns full list of tabs. Adding retries seems like a solution we need to try.

### How has the user experience changed?

No changes, unless the user is running Cypress with debug logs `DEBUG=cypress:server:protocol`. In that case they should see several calls 

```
  cypress:server:protocol CRI.List on port 56428 +317ms
  cypress:server:protocol CRI List { numTargets: 1, targets: [ { description: '', devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:56428/devtools/page/2FCCB2A0FA8B1DCD5E1CDC2849A6A326', id: '2FCCB2A0FA8B1DCD5E1CDC2849A6A326', title: 'Sortify', type: 'background_page', url: 'chrome-extension://aehmpfeibpcclkbjjkclhncmjncpebef/_generated_background_page.html', webSocketDebuggerUrl: 'ws://localhost:56428/devtools/page/2FCCB2A0FA8B1DCD5E1CDC2849A6A326' } ] } +88ms
  cypress:server:protocol CRI.List on port 56428 +1s
  cypress:server:protocol CRI List { numTargets: 10,
...
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

File: packages/server/lib/browsers/protocol.js [hunk 1]
```diff
@@ -59,30 +94,13 @@ const getWsTargetFor = (port) => {
...
-
-    debug('found CRI target %o', target)
+    const findPage = findStartPageTarget.bind(null, connectOpts)
 
-    return target.webSocketDebuggerUrl
+    // p-retry https://github.com/sindresorhus/p-retry uses options
+    // from https://github.com/tim-kos/node-retry#retryoperationoptions
+    // and defaults (1 second first retry, exponential factor 2, 10 attempts)
+    // are reasonable
+    return pRetry(findPage)
```
Comment (flotwig) [inline packages/server/lib/browsers/protocol.js]: the way this is implemented, you won't get the retry counter in stdout once the TCP connection succeeds. this retry loop will also follow completely different rules from the initial retry loop. this behavior is defined and tested for, but this `pRetry` just glosses over it.

i think the easiest way to keep the retry counter and the existing retry behavior would be to just use the existing `createRetryingSocket` and call the `retry` function from the callback to trigger retries as necessary. it will not make the most beautiful code, but it will make the most beautiful user experience :)

Comment (bahmutov) [reply packages/server/lib/browsers/protocol.js]: I doubt this matters much, and if this solves the problem then all good. To me the initial connection seems to take longer than `CRI.List` update

Comment (flotwig) [reply packages/server/lib/browsers/protocol.js]: It's not the *most* important thing, but still, in this PR we have a chance to...

* maintain a consistent user experience,
* have well-defined retry behavior around an error-prone section of code,
* avoid introducing new dependencies since we already have this functionality in createRetryingSocket,
* and reduce confusion/technical debt around this code section instead of adding new complexity and external libraries that developers have to understand

If we don't do it before this PR gets merged, it just becomes even more tech debt, and this code is only a few months old so we should try to keep it in nice shape for as long as possible.

I can implement it if you like since I already know the APIs involved, just let me know.

Comment (bahmutov) [reply packages/server/lib/browsers/protocol.js]: Be my guest and change it.
I would prefer using off the shelf 3rd party libs for this, since they are well tested. I also don't find the argument for introducing technical debt convincing. We will do more stuff in the retry function:
- connect to socket
- `CRI.List`
- check if the list contains the blank page

If the check fails, we are going to go ... and connect back to the socket? What if we just need more time ... to get `CRI.List` to query the tabs AFTER the connection? Will we get into a loop where we are not solving the problem? 

Right now it seems to me the retries are split where they need to be and are isolated.

Comment (flotwig) [reply packages/server/lib/browsers/protocol.js]: You raise a good point re: reconnecting to the socket on each retry, that probably shouldn't happen.

I still think that it's important to preserve the retry messaging. Otherwise the error experience will look like this:

```
Retrying 20/33...
Retrying 21/33...
Failed to connect to browser
```

...then the user is left head-scratching, "why didn't it just retry like it said it was going to?" and we'll have to fix it later on...

So maybe we can keep pRetry and then move the "warning message" into a function that keeps track of how many times it's retried, so we can use it in both places when a retry occurs.

**Comment by bahmutov** [comment]
Funny enough, I see empty targets right now in another recipe with Chrome

```
  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.8.1                                                                              │
  │ Browser:    Chrome 79 (headless)                                                               │
  │ Specs:      1 found (spec.js)                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  spec.js                                                                         (1 of 1)
  cypress:server:protocol ensureRdpPort 59547 +0ms
  cypress:server:protocol Chrome arguments [ '--test-type', '--ignore-certificate-errors', '--start-maximized', '--silent-debugger-extension-api', '--no-default-browser-check', '--no-first-run', '--noerrdialogs', '--enable-fixed-layout', '--disable-popup-blocking', '--disable-password-generation', '--disable-save-password-bubble', '--disable-single-click-autofill', '--disable-prompt-on-repos', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-renderer-throttling', '--disable-restore-session-state', '--disable-translate', '--disable-new-profile-management', '--disable-new-avatar-menu', '--allow-insecure-localhost', '--reduce-security-for-testing', '--enable-automation', '--disable-device-discovery-notifications', '--disable-infobars', '--autoplay-policy=no-user-gesture-required', '--disable-site-isolation-trials', '--metrics-recording-only', '--disable-prompt-on-repost', '--disable-hang-monitor', '--disable-sync', '--disable-web-resources', '--safebrowsing-disable-auto-update', '--safebrowsing-disable-download-protection', '--disable-client-side-phishing-detection', '--disable-component-update', '--disable-default-apps', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--disable-ipc-flooding-protection', '--disable-backgrounding-occluded-window', '--disable-breakpad', '--password-store=basic', '--use-mock-keychain', '--proxy-server=http://localhost:59544', '--proxy-bypass-list=<-loopback>', '--headless', '--remote-debugging-port=59547', '--remote-debugging-address=127.0.0.1' ] +1ms
  cypress:server:protocol Getting WS connection to CRI on port 59547 +0ms
  cypress:server:protocol CRI.List on port 59547 +107ms
  cypress:server:protocol CRI List { numTargets: 0, targets: [] } +17ms
could not find CRI target
Error: could not find CRI target
    at lazyAssLogic (/Users/gleb/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/Users/gleb/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/lazy-ass/index.js:115:28)
    at /Users/gleb/Library/Caches/Cypress/3.8.1/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:81:5
```

So the message could be in your case
```
Retrying 20/33...
Retrying 21/33...
could not find CRI target
```

But I seriously doubt it now. We could keep the current retry in this PR and add a message there https://github.com/sindresorhus/p-retry#onfailedattempterror but again I doubt it will give you much

```
Retrying 20/33...
Retrying 21/33...
tried finding CRI target 10 times, failed
could not find CRI target
```

**Comment by bahmutov** [comment]
Oh, one last thing. Monkey-patching 3.8.1 binary using new code in `protocol.js` fixes the above failure

```
  cypress:server:protocol Getting WS connection to CRI on port 59700 +0ms
  cypress:server:protocol CRI.List on port 59700 +108ms
  cypress:server:protocol CRI List { numTargets: 0, targets: [] } +26ms
  cypress:server:protocol CRI.List on port 59700 +1s
  cypress:server:protocol CRI List { numTargets: 1, targets: [ { description: '', devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:59700/devtools/page/9BD87A144C2102288BDFF45FB6113D98', id: '9BD87A144C2102288BDFF45FB6113D98', title: 'about:blank', type: 'page', url: 'about:blank', webSocketDebuggerUrl: 'ws://localhost:59700/devtools/page/9BD87A144C2102288BDFF45FB6113D98' } ] } +3ms
  cypress:server:protocol found CRI target { description: '', devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:59700/devtools/page/9BD87A144C2102288BDFF45FB6113D98', id: '9BD87A144C2102288BDFF45FB6113D98', title: 'about:blank', type: 'page', url: 'about:blank', webSocketDebuggerUrl: 'ws://localhost:59700/devtools/page/9BD87A144C2102288BDFF45FB6113D98' } +1ms
```
👀 on the 🏀

**Comment by flotwig** [comment]
@bahmutov I updated the way it retries to incorporate the delay messaging & added tests that it console.logs as expected. 

I tried using `p-retry` for this, but the `onFailedAttempt` callback isn't well-documented and I didn't feel like poking at its behavior would be worth it when it's easy just to write the retry code inline.

**Comment by bahmutov** [comment]
@flotwig yeah, now you just need to use extra variables and write custom code, I understand it might feel simple right now. But I don't want to argue about it any more.

We have an example of failing CRI target in GH action! https://github.com/cypress-io/cypress-example-kitchensink/runs/383684300

**Comment by erezrokah** [comment]
Looks like I'm a bit late to the party, but instead of polling one could listen to the  `Target.targetCreated/Target.targetInfoChanged` events.
You can see this approach here: https://github.com/erezrokah/cypress/commit/470f0510d599d83d05b92e9e8da97bf60c669add#diff-173311a633635f1f07ee99371b5c362dR61

**Comment by bahmutov** [comment]
I have tested this branch using `cypress-example-recipe` by putting the protocol.js into global binary 3.8.2 and running

```
~/git/cypress-example-recipes/examples/fundamentals__chrome-remote-debugging on master
$ DEBUG=cypress:server:protocol npm run cypress:run:chrome

> chrome-remote-debugging@1.0.0 cypress:run:chrome /Users/gleb/git/cypress-example-recipes/examples/fundamentals__chrome-remote-debugging
> ../../node_modules/.bin/cypress run --headless --browser chrome


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.8.2                                                                              │
  │ Browser:    Chrome 79 (headless)                                                               │
  │ Specs:      1 found (spec.js)                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  spec.js                                                                         (1 of 1)
  cypress:server:protocol ensureRdpPort 59465 +0ms
  cypress:server:protocol Chrome arguments [ '--test-type', '--ignore-certificate-errors', '--start-maximized', '--silent-debugger-extension-api', '--no-default-browser-check', '--no-first-run', '--noerrdialogs', '--enable-fixed-layout', '--disable-popup-blocking', '--disable-password-generation', '--disable-save-password-bubble', '--disable-single-click-autofill', '--disable-prompt-on-repos', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-renderer-throttling', '--disable-restore-session-state', '--disable-translate', '--disable-new-profile-management', '--disable-new-avatar-menu', '--allow-insecure-localhost', '--reduce-security-for-testing', '--enable-automation', '--disable-device-discovery-notifications', '--disable-infobars', '--autoplay-policy=no-user-gesture-required', '--disable-site-isolation-trials', '--metrics-recording-only', '--disable-prompt-on-repost', '--disable-hang-monitor', '--disable-sync', '--disable-web-resources', '--safebrowsing-disable-auto-update', '--safebrowsing-disable-download-protection', '--disable-client-side-phishing-detection', '--disable-component-update', '--disable-default-apps', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--disable-ipc-flooding-protection', '--disable-backgrounding-occluded-window', '--disable-breakpad', '--password-store=basic', '--use-mock-keychain', '--proxy-server=http://localhost:59462', '--proxy-bypass-list=<-loopback>', '--headless', '--remote-debugging-port=59465', '--remote-debugging-address=127.0.0.1' ] +1ms
  cypress:server:protocol Getting WS connection to CRI on port 59465 +0ms
  cypress:server:protocol attempting to find CRI target... { retryIndex: 1 } +207ms
  cypress:server:protocol CRI.List { host: '127.0.0.1', port: 59465, getDelayMsForRetry: [Function: getDelayMsForRetry] } +2ms
  cypress:server:protocol CRI List { numTargets: 0, targets: [] } +22ms
  cypress:server:protocol error finding CRI target, maybe retrying { delay: 100, err: Error: could not find CRI target at lazyAssLogic (/Users/gleb/Library/Caches/Cypress/3.8.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/lazy-ass/index.js:110:14) at lazyAss (/Users/gleb/Library/Caches/Cypress/3.8.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/lazy-ass/index.js:115:28) at findStartPage (/Users/gleb/Library/Caches/Cypress/3.8.2/Cypress.app/Contents/Resources/app/packages/server/lib/browsers/protocol.js:58:3)     at processTicksAndRejections (internal/process/task_queues.js:85:5) } +0ms
  cypress:server:protocol attempting to find CRI target... { retryIndex: 2 } +101ms
  cypress:server:protocol CRI.List { host: '127.0.0.1', port: 59465, getDelayMsForRetry: [Function: getDelayMsForRetry] } +0ms
  cypress:server:protocol CRI List { numTargets: 1, targets: [ { description: '', devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:59465/devtools/page/0AE23AD5873121DC5BC9153E5C7BD315', id: '0AE23AD5873121DC5BC9153E5C7BD315', title: '', type: 'page', url: 'about:blank', webSocketDebuggerUrl: 'ws://localhost:59465/devtools/page/0AE23AD5873121DC5BC9153E5C7BD315' } ] } +2ms
  cypress:server:protocol found CRI target { description: '', devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:59465/devtools/page/0AE23AD5873121DC5BC9153E5C7BD315', id: '0AE23AD5873121DC5BC9153E5C7BD315', title: '', type: 'page', url: 'about:blank', webSocketDebuggerUrl: 'ws://localhost:59465/devtools/page/0AE23AD5873121DC5BC9153E5C7BD315' } +1ms


  Test
    ✓ Printable div is not visible normally (137ms)
```

Before, it was failing, but now it is retrying correctly.

**Comment by flotwig** [comment]
> Looks like I'm a bit late to the party, but instead of polling one could listen to the `Target.targetCreated/Target.targetInfoChanged` events.

@erezrokah Thanks! I've created an issue here to track that: #6153. 

Since this PR already has tests and has been manually confirmed, we'll merge it for now, but using the CDP events would be an improvement since it could cut down on the potential slowdown from retrying at an interval.

**Comment by erezrokah** [comment]
Thanks @flotwig, I'm just glad to see it resolved :)

**Comment by noamtamir** [comment]
When can we expect this fix to be released?
