### PR TITLE
fix: `res.send` of `cy.intercept` doesn't override json-related content types. 

### LINKED ISSUE #17084: Intercept resets compatible content type when body is an object
### Current behavior

The following test passes:

```javascript
const axios = require('axios');

it('overwrites the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    // A variant of the normal json content type specifically designed
                    // for error messages.
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                body: {
                    status: 500,
                    title: 'Internal Server Error',
                },
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            // Note that this asserts the standard json content type
            expect(error.response.headers['content-type']).to.equal('application/json');
        });
});
```

image

### Desired behavior

`.intercept()` should not overwrite the content type if I explicitly provide one. Especially if my content type matches the response body.

Or, in other words. The following test should pass:

<details>
  <summary>The test</summary>
  
  ```javascript
const axios = require('axios');

it('does not overwrite the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                body: {
                    status: 500,
                    title: 'Internal Server Error',
                },
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            // Now asserts the content type for Problem JSON
            expect(error.response.headers['content-type']).to.equal('application/problem+json');
        });
});

  ```
  
</details>

### Test code to reproduce

As above :)

I also have a random server up at `http://localhost:3000`. Since we're replacing the response of the server anyway, it really doesn't matter what's running there. My server is an Express Hello World :)

```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    res.send('Hello World!')
})

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})
```

### Versions

Cypress: 7.5.0

### Workaround

I already found a workaround. I'll share it in case it helps someone else.

This only happens when your response body is an object, so all you have to do is stringify it like so:

```javascript
const axios = require('axios');

it('overwrites the content-type header', () => {
    cy.intercept('http://localhost:3000', (req) => {
        req.on('response', (res) => {
            res.send({
                statusCode: 500,
                headers: {
                    'content-type': 'application/problem+json',
                    'access-control-allow-origin': '*',
                },
                // Stringify as a workaround. This issue only happens when body is an
                // object. `JSON.stringify` turns it into a string instead.
                body: JSON.stringify({
                    status: 500,
                    title: 'Internal Server Error',
                }),
            });
        });
    });

    axios
        .get('http://localhost:3000')
        .catch((error) => {
            expect(error.response.headers['content-type']).to.equal('application/problem+json');
        });
});
```

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #17084

### User facing changelog

`res.send` of `cy.intercept` doesn't override json-related content types. 

### Additional details
- Why was this change necessary? => There are a lot of [json-related MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml). But `res.send` only allows `application/json`. 
- What is affected by this change? => N/A
- Any implementation details to explain? => I checked to set `content-type` to `application/json` only when `content-type` doesn't have the text, `json`.

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

### CODE REVIEW

File: packages/driver/src/cy/net-stubbing/static-response-utils.ts [hunk 1]
```diff
@@ -112,7 +112,16 @@ export function getBackendStaticResponse (staticResponse: Readonly<StaticRespons
...
       backendStaticResponse.body = JSON.stringify(staticResponse.body)
-      _.set(backendStaticResponse, 'headers.content-type', 'application/json')
+
+      // There are various json-related MIME types. We cannot simply set it as `application/json`.
+      // @see https://www.iana.org/assignments/media-types/media-types.xhtml
+      if (
+        !(backendStaticResponse.headers &&
+        backendStaticResponse.headers['content-type'] &&
+        backendStaticResponse.headers['content-type'].includes('json'))
+      ) {
```
Comment (flotwig) [inline packages/driver/src/cy/net-stubbing/static-response-utils.ts:122]: Well, we might as well let people use any `content-type`. If they pass one we shouldn't ignore it in any case, it's extra confusing that way.

`caseInsensitiveGet` is required here, since the header names come from the user, they will not necessarily be lowercased.

**Review by flotwig — CHANGES_REQUESTED** [review]

File: packages/driver/src/cy/net-stubbing/static-response-utils.ts (hunk 1 above)
Comment (flotwig) [reply packages/driver/src/cy/net-stubbing/static-response-utils.ts]: 254ec0a

Comment (flotwig) [reply packages/driver/src/cy/net-stubbing/static-response-utils.ts]: @sainthkh there seem to be some failures with my change and `res.send()`, can you untangle it? it's something to do with the response merging

Comment (sainthkh) [reply packages/driver/src/cy/net-stubbing/static-response-utils.ts]: You told me about the 2 issues:

1. We should let users set any `content-type`. 
2. We need `caseInsensitiveGet` because users' header names would not always be lowercased. 

I agree with 2. And fixed it with `caseInsensitiveGet`.

As for 1, I took the hybrid way: Throw an error when the user-provided `content-type` doesn't contain `json`. Set it to `application/json` when it's `undefined`.

**Review by flotwig — APPROVED** [review]
