### PR TITLE
fix: force gzip when no accept encoding header is sent and use identity if gzip is not sent

### LINKED ISSUE #28025: Ensure that deflate/brotli is filtered out in Accept Encoding by the Cypress proxy
Currently, Cypress [tries to filter down](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/request-middleware.ts#L348-L374) Accept-Encoding headers to just gzip. This works when the header is present, but when it is blank according to the [standards for the header](https://www.rfc-editor.org/rfc/rfc9110#field.accept-encoding):

```
If no Accept-Encoding header field is in the request, any content coding is considered acceptable by the user agent.
```

Thus, we need to update the logic to specify `identity` when there is no Accept Encoding header.

The problem would manifest itself in the following scenario:

1. No Accept-Encoding header is sent on a request
2. The server sends back the response encoded in an unsupported encoding (e.g. brotli/deflate)
3. Something in Cypress relies on the decompressed body (this could include `cy.intercept` or CSS, font, and image assets in Test Replay)

### PR DESCRIPTION
**Pull request by ryanthemanuel**
- Closes #28025 

### Additional details

Currently, Cypress [tries to filter down](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/request-middleware.ts#L348-L374) Accept-Encoding headers to just gzip. This works when the header is present, but when it is blank according to the [standards for the header](https://www.rfc-editor.org/rfc/rfc9110#field.accept-encoding):

> If no Accept-Encoding header field is in the request, any content coding is considered acceptable by the user agent.

Thus, we need to update the logic to specify `identity` when there is no Accept Encoding header.

The problem would manifest itself in the following scenario:

1. No Accept-Encoding header is sent on a request
2. The server sends back the response encoded in an unsupported encoding (e.g. brotli/deflate)
3. Something in Cypress relies on the decompressed body (this could include `cy.intercept` or CSS, font, and image assets in Test Replay)

### Steps to test

1. Set up a server that returns brotli encoded assets when no Accept Encoding header is specified. 
2. Record a Cypress run where assets don't request an Accept Encoding. 
3. Ensure that Test Replay is still functional

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

File: packages/server/test/integration/http_requests_spec.js [hunk 1]
```diff
@@ -1139,10 +1139,9 @@ describe('Routes', () => {
       })
 
       it('removes accept-encoding when nothing is supported', function () {
```
Comment (chrisbreiding) [inline packages/server/test/integration/http_requests_spec.js]:
```suggestion
      it('sets accept-encoding header to "identity" when nothing is supported', function () {
```

File: packages/server/test/integration/http_requests_spec.js [hunk 2]
```diff
@@ -1158,6 +1157,22 @@ describe('Routes', () => {
           expect(res.body).to.eq('<html>accept</html>')
         })
       })
+
+      it('removes accept-encoding when no header is passed', function () {
```
Comment (chrisbreiding) [inline packages/server/test/integration/http_requests_spec.js]:
```suggestion
      it('sets accept-encoding header to "identity" when no header is passed', function () {
```

**Review by chrisbreiding — CHANGES_REQUESTED** [review]

**Review by chrisbreiding — APPROVED** [review]

File: packages/proxy/lib/http/request-middleware.ts [hunk 3]
```diff
@@ -365,8 +365,10 @@ const StripUnsupportedAcceptEncoding: RequestMiddleware = function () {
     if (doesAcceptHeadingIncludeGzip) {
       this.req.headers['accept-encoding'] = 'gzip'
     } else {
-      delete this.req.headers['accept-encoding']
+      this.req.headers['accept-encoding'] = 'identity'
     }
+  } else {
+    this.req.headers['accept-encoding'] = 'identity'
```
Comment (mschile) [inline packages/proxy/lib/http/request-middleware.ts]: If there is no accept-encoding header, would it make sense to set this to `gzip`?

Comment (ryanthemanuel) [reply packages/proxy/lib/http/request-middleware.ts]: I've gone back and forth on it. The wording in the spec is so annoying because it says that a blank accept encoding "may" indicate that we accept everything, but it probably varies from use case to use case.

Comment (mschile) [reply packages/proxy/lib/http/request-middleware.ts]: Where is that at? I'm seeing this:

```
If no Accept-Encoding header field is in the request, any content coding is considered acceptable by the user agent.
```

https://www.rfc-editor.org/rfc/rfc9110#section-12.5.3-10.1

Comment (ryanthemanuel) [reply packages/proxy/lib/http/request-middleware.ts]: Yeah you're right. I was looking at an old one first and then linked to the newer one :) I'll go with the newer one's verbage which I think means we should limit it to gzip.

Comment (ryanthemanuel) [inline packages/proxy/lib/http/request-middleware.ts]:
```suggestion
    // If there is no accept-encoding header, it means to accept everything (https://www.rfc-editor.org/rfc/rfc9110#name-accept-encoding). In that case, we want to explicitly filter that down to `gzip`
    this.req.headers['accept-encoding'] = 'gzip'
```

File: packages/server/test/integration/http_requests_spec.js [hunk 4]
```diff
@@ -1158,6 +1157,22 @@ describe('Routes', () => {
           expect(res.body).to.eq('<html>accept</html>')
         })
       })
+
+      it('sets accept-encoding header to "identity" when no header is passed', function () {
+        nock(this.server.remoteStates.current().origin)
+        .get('/accept')
+        .matchHeader('accept-encoding', 'identity')
```
Comment (ryanthemanuel) [inline packages/server/test/integration/http_requests_spec.js]:
```suggestion
        .matchHeader('accept-encoding', 'gzip')
```

File: packages/server/test/integration/http_requests_spec.js [hunk 5]
```diff
@@ -1158,6 +1157,22 @@ describe('Routes', () => {
           expect(res.body).to.eq('<html>accept</html>')
         })
       })
+
+      it('sets accept-encoding header to "identity" when no header is passed', function () {
```
Comment (ryanthemanuel) [inline packages/server/test/integration/http_requests_spec.js]:
```suggestion
      it('sets accept-encoding header to "gzip" when no header is passed', function () {
```

**Review by mschile — APPROVED** [review]

File: cli/CHANGELOG.md [hunk 6]
```diff
@@ -1,4 +1,10 @@
 <!-- See the ../guides/writing-the-cypress-changelog.md for details on writing the changelog. -->
+## 13.3.2
+
+_Released 10/25/2023 (PENDING)_
+
+- Fixed an issue with Accept Encoding headers by forcing gzip when no accept encoding header is sent and using identity if gzip is not sent. Fixes [#18025](https://github.com/cypress-io/cypress/issues/28025)
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
**Bugfixes:**

- Fixed an issue with Accept Encoding headers by forcing gzip when no accept encoding header is sent and using identity if gzip is not sent. Fixes [#18025](https://github.com/cypress-io/cypress/issues/28025)
```

File: cli/CHANGELOG.md [hunk 7]
```diff
@@ -1,4 +1,12 @@
 <!-- See the ../guides/writing-the-cypress-changelog.md for details on writing the changelog. -->
+## 13.3.2
+
+_Released 10/25/2023 (PENDING)_
+
+**Bugfixes:**
+
+- Fixed an issue with Accept Encoding headers by forcing gzip when no accept encoding header is sent and using identity if gzip is not sent. Fixes [#18025](https://github.com/cypress-io/cypress/issues/28025)
```
Comment (ryanthemanuel) [inline cli/CHANGELOG.md]:
```suggestion
- Fixed an issue with Accept Encoding headers by forcing gzip when no accept encoding header is sent and using identity if gzip is not sent. Fixes [#28025](https://github.com/cypress-io/cypress/issues/28025).
```
