### PR TITLE
fix: send click event with `cy.type('{enter}')`.

### LINKED ISSUE #19541: type('{enter}') does not fire click event
### Current behavior

When the target element is a button `type('{enter}')` fires the events

- keydown
- keypress
- keyup

image
Note the first "click" is from activating the button.

### Desired behavior

When the target element is a button `type('{enter}')` should fire the events

- keydown
- keypress
- **click**
- keyup

image

Note the first "click" is from activating the button.

### Test code to reproduce

https://github.com/jamime/cypress-test-tiny

### Cypress Version

9.2.0

### Other

> If the key is the Enter or   key and the current focus is on a state-changing element, the default action MUST be to dispatch a click event, and a DOMActivate event if that event type is supported by the user agent (refer to § 3.5 Activation triggers and behavior for more details)

https://w3c.github.io/uievents/#event-type-keydown

Once the cypress test has failed, if you click "reset", then click the second button and press "Enter" you will see the correct output.

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #19541

### User facing changelog

Send click event with `cy.type('{enter}')` on some button-like elements(`<button>` element, `button`, `reset`, `image`, `submit` input elements)

### Additional details
- Why was this change necessary? => Cypress doesn't reflect the browser behavior.
- What is affected by this change? => N/A
- Any implementation details to explain? => Click event is programatically sent on Chrome only. Firefox automatically sends click events. 

### How has the user experience changed?

**Before:** click event is not sent. 
**After:** click event is sent. 

### PR Tasks
- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

File: packages/driver/cypress/integration/commands/actions/type_spec.js [hunk 1]
```diff
@@ -557,6 +557,55 @@ describe('src/cy/commands/actions/type - #type', () => {
...
+        'button-tag',
+        'input-button',
+        'input-image',
+        'input-reset',
+        'input-submit',
+      ]
+
+      targets.forEach((targetId) => {
+        it(`${targetId}`, () => {
+          cy.get(`#target-${targetId}`).click()
```
Comment (BlueWinds) [inline packages/driver/cypress/integration/commands/actions/type_spec.js:577]: If you use `cy.focus()` instead of `cy.click()`, then we don't have the extraneous 'click' event first.

```
          cy.get(`#target-${targetId}`).focus()
          cy.get(`#target-${targetId}`).type('{enter}')

          cy.get('li').eq(0).should('have.text', 'keydown')
          cy.get('li').eq(1).should('have.text', 'keypress')
          cy.get('li').eq(2).should('have.text', 'click')
          cy.get('li').eq(3).should('have.text', 'keyup')
```

**Review by BlueWinds — CHANGES_REQUESTED** [review]

**Comment by jamime** [comment]
Thanks for working on this issue. I wanted to note that this issue also exists for `type{' '}`.

The events should fire in a slightly different order
- keydown
- keypress
- keyup
- click

It's also important if the target changes i.e. calling `.focus() in the keydown event` the `click` event is triggered on the new target.

I can create this in a new issue if you would prefer?

**Comment by sainthkh** [comment]
@jamime I think there are 2 more requests in your comment. 

* Support `cy.type(' ')`. 
* Support calling `element.focus()` on `keydown` 

I'll handle them in the next PR. If there are more cases I need to handle, please tell me.

File: packages/driver/src/cy/commands/actions/type.ts [hunk 2]
```diff
@@ -272,6 +272,11 @@ export default function (Commands, Cypress, cy, state, config) {
       const isContentEditable = $elements.isContentEditable(options.$el.get(0))
       const isTextarea = $elements.isTextarea(options.$el.get(0))
 
+      // click event is only fired on button, image, submit, reset elements.
+      // That's why we cannot use $elements.isButtonLike() here.
+      const type = (type) => $elements.isInputType(options.$el.get(0), type)
+      const isButtonLike = type('button') || type('image') || type('submit') || type('reset')
```
[the remark this answers is not in the document]
Comment (sainthkh) [reply packages/driver/src/cy/commands/actions/type.ts:278]: I think `sendClickEvent` is good enough.

File: packages/driver/cypress/integration/commands/actions/type_spec.js (hunk 1 above)
Comment (sainthkh) [reply packages/driver/cypress/integration/commands/actions/type_spec.js:577]: Fixed.

**Review by tbiethman — APPROVED** [review]

**Review by BlueWinds — APPROVED** [review]
