### PR TITLE
fix: Fire appropriate event when cy.type().

### LINKED ISSUE #5650: Inconsistant and invalid Events Typing using cypress
### Current behavior:

Testing a code who used `event instanceof KeyboardEvent`, I've seen some strange behavior, digging up, it seems that there is some strange inconsistencies between the events triggered and also into the way they are sent to the `eventListener`.

### Desired behavior:

Consistent behavior:
- `.type`
- `.trigger({..., type: 'keydown'})`
-  `.get('#element').then(element.dispatchEvent(new KeyboardEvent('keydown', ...)))`

Should all send a KeyboardEvent type event.

And the eventListener:

```js
element.addEventListener('keydown', (event) => (event instanceof KeyboardEvent));
```

Should always return true.

### Steps to reproduce: (app code and test code)

I've tested three different methods: `cy.type`, `cy.trigger`, `cy.get('#element').then( element.dispatchEvent)`.

And two different `eventListener` for each test:

1. One directly into a <script> inside the html page itself
2. One created into the test itself using `cy.get -> addEventListener`

You can find MWE here: https://github.com/avallete/cypress-test-tiny-event-bug

Simply run:

```
npm install
npm run cypress:open

# Then run the test and check the console.log inside the debuging tools.
# Each test is a specific case the 2 first show that event is type Event instead of KeyboardEvent.
# The third test show the inconsistency of the same eventListener if it's declared inside the test or outside (into the html <script>).
```

### Versions

3.6.1, Linux, Chromium 78 / Electron 73

### LINKED ISSUE #6125: Cannot read property 'indexOf' of undefined when using .type()
### Current behavior:

I'm currently using Cypress version 3.4.1 to run automation tests. 
I have a SignIn test suite to validate the login functionality . They are pretty straightforward tests that run against the application URL and validate if the user is able to login to the the app or not.

In Cypress 3.4.1, the login tests  are executed successfully. 
But when I tried to upgrade  to a version > 3.4.1, for example: latest version 3.8.1, I see this error 
`TypeError: Cannot read property 'indexOf' of undefined`

Let's take this one test **should display en error on invalid login attempt** as an example

I see the following error when I try to type in the username into the `#login_username` input field.

cypress_login_error

**Console output:**

image

### Desired behavior:

Cypress should Type the username into the input text box successfully.

**Console output when the behavior is correct.**

image

### Test code to reproduce

Below is the code for the Invalid Login test
```js
    it('should display en error on invalid login attempt', () => {
      cy.get('#login_username')
        .type('insuranceproctor');

      cy.get('#login_password')
        .type('54321drowssap');

      cy.get('#signin-btn')
        .should('be.enabled')
        .click();

      cy.get('h3')
        .should('be.visible')
        .and('contain', 'Whoops!');

      cy.get('p')
        .eq(0)
        .should('be.visible')
        .and('contain', 'Your username and password don\'t match, please try again.');

      cy.url()
        .should('contain', 'signin');
    });
```

### Versions

Currently used version:
Cypress 3.4.1
Chrome 79

Seeing this error in versions 3.5.0 and above.

### Extra Info

The URL loads just fine and I'm able to see the sign-in screen and the cookies are loading correctly.
All other tests where I have the login functionality mocked pass 100%
I'm seeing this issue only with these tests which interact directly with the UI to login. 

### Workaround

I'm able to use `invoke` to  change the value of the input fields, but that's not the actual purpose of the login test so I definitely need a solution.
I'm a fan of Cypress and I'm super excited to see all the improvements you guys are doing! thanks a lot ❤️

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #6125 
* fix #5650 

### User facing changelog
`cy.type()` now fires `KeyboardEvent`, not `Event`. 

It didn't because it had to support Chrome < 63. But Chrome 63 isn't in [the lastest list of chrominum](https://chromium.cypress.io/). I guess we don't have to support it any more.

#### Why was this change necessary?
* `cy.type()` fires `Event` class and it doesn't match the behavior of the Browsers. 
* When `Event` class is overridden and you cannot fix the code of the site, cy.type() fails. 

#### What is affected by this change?
N/A

#### Any implementation details to explain?
I tried to simply revive the commented-out code, but there were some problems in Firefox. 

* Firefox doesn't support `TextInput` event. So, we had to check if it's a valid Event constructor and fallback to `KeyboardEvent`. 
* When `KeyboardEvent` with `Enter` key is sent to an input field in a form in Firefox, `submit` event is automatically triggered. I had to fix problems related with it.

### How has the user experience changed?
N/A

### PR Tasks
* [x] Have tests been added/updated?
* [ ] Has the original issue been tagged with a release in ZenHub? 
* [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by Bkucera** [comment]
@sainthkh we should always be able to workaround cases where the AUT overwrites some native class that we need, we backup the getter/setter or prototype as soon as the page is loaded before the AUT has time to overwrite it, see https://github.com/cypress-io/cypress/blob/composite-error/packages/driver/src/dom/elements.ts#L264 

Is there any other reason we need to use `KeyboardEvent`? As far as I know the only real impact should be if AUT code is listening to events as using `e instanceOf KeyboardEvent`

**Comment by Bkucera** [comment]
@sainthkh  this should fix #5650  no?

File: packages/driver/cypress/integration/commands/actions/type_spec.js [hunk 1]
```diff
@@ -177,6 +177,21 @@ describe('src/cy/commands/actions/type - #type', () => {
...
+    .type('foobar')
+  })
+
+  // https://github.com/cypress-io/cypress/issues/5650
+  it('should trigger KeyboardEvent, not Event, for event listeners', () => {
+    cy.visit('fixtures/issue-5650.html')
+
+    cy.get('#test-input').type('A')
+    cy.get('#result').contains('isKeyboardEvent: true')
+  })
```
Comment (Bkucera) [inline packages/driver/cypress/integration/commands/actions/type_spec.js:193]: I would suggest something like (to keep test smaller, faster):

```suggestion
  it('should trigger KeyboardEvent, not Event, for event listeners', () => {
    cy.$$('input:first').on('keydown', (e) => {
      if (e instanceOf e.currentTarget.ownerDocument.defaultView.KeyboardEvent) return
      throw new Error('event was not instanceOf KeyboardEvent')
    })
    cy.get('input:first').type('A')
  })
```

File: packages/driver/src/cy/commands/actions/type.js [hunk 2]
```diff
@@ -202,19 +202,25 @@ module.exports = function (Commands, Cypress, cy, state, config) {
...
-        // on the button will indeed trigger the form submit event
-        // so we dont need to fire it manually anymore!
-        if (!clickedDefaultButton(defaultButton)) {
-          // if we werent able to click the default button
-          // then synchronously fire the submit event
-          // currently this is sync but if we use a waterfall
-          // promise in the submit command it will break again
-          // consider changing type to a Promise and juggle logging
-          return cy.now('submit', form, { log: false, $el: form })
+        // In Firefox, submit event is automatically fired
```
Comment (Bkucera) [inline packages/driver/src/cy/commands/actions/type.js:205]: nice comments :+1:

**Comment by sainthkh** [comment]
As I wrote in [the comment](https://github.com/cypress-io/cypress/issues/5650#issuecomment-671691934), there are 3 problems in #5650:

* `KeyboardEvent`
* documentation about iframe in the Test Runner AUT.
* `cy.trigger()`

`KeyboardEvent` is solved here. Doc issue is solved at cypress-io/cypress-documentation#3073. And I'm currently coping with `cy.trigger()` issue and #5650 will be closed with it.

File: packages/driver/cypress/integration/commands/actions/type_spec.js (hunk 1 above)
Comment (sainthkh) [reply packages/driver/cypress/integration/commands/actions/type_spec.js:193]: I tried to reuse the test created in #5650. But I prefer your way.

But the code above has 2 problems:

1. `e` is not a native event. To access it, we need to use `e.originalEvent`.

> It's also important to note that the event object contains a property called `originalEvent`, which is the event object that the browser itself created. jQuery wraps this native event object with some useful methods and properties, but in some instances, you'll need to access the original event via `event.originalEvent` for instance. This is especially useful for touch events on mobile devices and tablets.

2. `done` function should be used. Otherwise, the test would pass without checking `keydown` event. Or fail later when Cypress is running other tests. 

I fixed these 2 problems and updated the test.

**Comment by sainthkh** [comment]
kitchensink tests failed because of the change in #7782.

**Comment by jennifer-shehane** [comment]
@sainthkh sigh, yah, these should pass but I think they fail for outside contributors because the run doesn't have access to env var `NEXT_DEV_VERSION`. Let me try to rerun.

**Comment by sainthkh** [comment]
Flaky failure.

**Review by Bkucera — APPROVED** [review]
