### PR TITLE
fix: preserve orphaned process electron

### LINKED ISSUE #28397: Timed out waiting for the browser to connect - Cannot read properties of null (reading 'getWebSocketDebuggerUrl')
### Current behavior

Since updating to Node v20.9.0 and Cypress v13.6.0, my tests are failing with a timeout error. The problem only occurs in the CI (gitlab-runner 16.5.0).

```
Running: login/login.cy.ts (1 of 9)
Timed out waiting for the browser to connect. Retrying...
Cannot read properties of null (reading 'getWebSocketDebuggerUrl')
TypeError: Cannot read properties of null (reading 'getWebSocketDebuggerUrl')
at Object.open (:4454:111131)
at async Object.open (:4460:27335)
at async v.relaunchBrowser (:4526:36933)
```

### Desired behavior

_No response_

### Test code to reproduce

-

### Cypress Version

13.6.0

### Node version

20.9.0

### Operating System

public.ecr.aws/cypress-io/cypress/base:20.9.0

### Debug Logs

_No response_

### Other

Browser: Electron 114 (headless)

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes  #28397

### Additional details

This PR fixes an issue where orphaned processes were killing the whole electron browser CRI client, when in actually we want to preserve this until the electron process is terminated.

Unique to our electron setup, launching electron produces a [window](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/electron.ts#L514) and not a separate browser instance. Since orphaned processes (or in this case, windows/targets) need to be cleaned up, we want to only clean up those items related to the process/window and not the overall launched instance.

see https://github.com/cypress-io/cypress/issues/28397#issuecomment-2108783268 for more in depth details, as well as how we reproduced the issue

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by cacieprins — APPROVED** [review]

File: packages/server/lib/browsers/index.ts [hunk 1]
```diff
@@ -204,8 +206,11 @@ export = {
     // this browser, it means it has been orphaned and should be terminated.
     //
     // https://github.com/cypress-io/cypress/issues/24377
-    if (thisLaunchAttempt !== launchAttempt) {
-      await kill({ instance: _instance, nullOut: false })
+    const isOrphanedBrowserProcess = thisLaunchAttempt !== launchAttempt
+
+    if (isOrphanedBrowserProcess) {
+      debug(`killing process because launch attempt: ${thisLaunchAttempt} does not match current launch attempt: ${launchAttempt}`)
+      await kill({ instance: _instance, isOrphanedBrowserProcess, nullOut: false })
```
Comment (ryanthemanuel) [inline packages/server/lib/browsers/index.ts:213]: Is nullOut (or rather !nullOut) serving the same purpose as isOrphanedBrowserProcess?

Comment (AtofStryker) [reply packages/server/lib/browsers/index.ts:213]: I don't think so. I think the goal of `nullOut` is to set the current browser instance to null, which we don't want to do since we want the active instance to be set, but the `_instance` inside the closure to be cleaned up.

**Review by ryanthemanuel — APPROVED** [review]
